openvinotoolkit/openvino

src/core/tests/frontend/frontend_manager.cpp
src/core/tests/frontend/mock_frontend.cpp
src/frontends/common/src/frontend.cpp
src/frontends/common/src/input_model.cpp
src/frontends/common/src/utils.hpp
src/tests/functional/inference_engine/ir_serialization/partial_shape_deserialization.cpp

- Every call to frontend's API (except Places) can throw exception. If during exception handling, FrontEndManager is destroyed and calls 'dlclose' for plugin - call stack will be corrupted and crash will occur.
Solution is to wrap 'plugins' calls with try/catch and throw new exception in 'openvino' context
- Currently "Place" objects don't have 'actual' wrappers, so exception in 'place' objects will potentially cause such crash (if exception handler destroys FrontEndManager). Workaround for user would be to try/catch any calls of Place API on their side or ensure that FrontEndManager/Core objects will not be destroyed during potential exception handling.
We're not expecting users to use Place API directly, so this workaround looks acceptable
- N/A

Frontend exception safety

---

src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp
src/plugins/intel_gpu/tests/module_tests/test_module_fusing_reorder.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp
src/tests_deprecated/functional/vpu/common/layers/myriad_layers_convolution_test.cpp
src/tests_deprecated/functional/vpu/common/layers/myriad_layers_detection_output_test.cpp
src/tests_deprecated/functional/vpu/common/layers/myriad_layers_eltwise_test.hpp
src/tests_deprecated/functional/vpu/common/layers/myriad_layers_exp_detectionoutput_test.hpp
src/tests_deprecated/functional/vpu/common/layers/myriad_layers_exp_generateproposals_test.hpp
src/tests_deprecated/functional/vpu/common/layers/myriad_layers_exp_topkrois_test.hpp
src/tests_deprecated/functional/vpu/common/layers/myriad_layers_nonzero_test.hpp
src/tests_deprecated/functional/vpu/vpu_base/vpu_layer_tests_utils.cpp

- Fix for warnings spotted by clang compiler
* unused variable 'temp'
* convolution_fusion_test.cpp:2953:60: error: implicit conversion from 'double' to 'int' changes value from 0.5 to 0
* implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 (for RAND_MAX and generator.max())
*  variables max_batch_size/start/end/step is used uninitialized whenever 'if' condition is false (it's a FP, due it's inside ASSERT_NO_THROW macro)

Fix for warnings spotted by clang compiler

---

src/plugins/intel_cpu/thirdparty/CMakeLists.txt

- Compilation with ENABLE_CPU_DEBUG_CAPS was fixed.
Previous to this change it failed due to undefined dnnl::impl::md2dim_str
(since DNNL_VERBOSE was disabled in the scope of PR #11244).

[CPU] [DEBUG CAPS] Revert DNNL_VERBOSE

---

.ci/azure/linux.yml
tools/mo/unit_tests/mo/bom_test.py

**Description:** Recent test infrastructure changes affected MO unit-tests and they were disabled. Now it returns them to CI but bom tests. The BOM tests will be fixed in separate PR.
**Ticket:** 83076
Signed-off-by: Roman Kazantsev <roman.kazantsev@intel.com>

Enable MO unit-tests but bom tests

---

cmake/dependencies.cmake
cmake/features.cmake
src/cmake/ie_parallel.cmake
src/cmake/install_tbb.cmake
src/plugins/intel_myriad/third_party/XLink/XLink.cmake

- If `TBB_DIR` or `TBBROOT` env vars are set, they are used
- If no, and `ENABLE_SYSTEM_TBB` is set in cmake, it's used and TBB from system is found
- If all steps above are failed, try to search with custom TBBConfig.cmake which is explicitly created for old TBB versions (like 2017) with no cmake configs. Such custom cmake TBBCoonfig.cmake respects `TBBROOT` env var
- If no, prebuilt TBB is downloaded and used
- The same for TBBBind, it's downloaded only for TBB version less 2021 (and with respect to cmake var `ENABLE_TBBBIND_2_5`)

Tbb: download only if system libraries are not found

---

model-optimizer/extensions/front/tf/deconv_ext.py
model-optimizer/mo/ops/deconvolution.py
model-optimizer/unit_tests/mo/ops/deconvolution_test.py

**Root cause analysis:** [TensorFlow Conv2DBackpropInput](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/conv2-d-backprop-input) operation covers Grouped Deconvolution case that has been omitted in Model Optimizer Support.
**Solution:** Add group number computation function. TF does not support Grouped ConvBackpropInput on CPU so the layer tests are not added. In the meantime, I did manual check on the customer inpainting model by collecting reference results on GPU and OV results match them.
**Ticket:** 72871
Code:
Validation:
Documentation:
Signed-off-by: Roman Kazantsev <roman.kazantsev@intel.com>

[MO] Support TensorFlow Grouped Conv2DBackpropInput

---

src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp

Enable FakeQuantize fusion transformation in MOC backend, so new FEs can benefit from them.
Please check 76245 ticket for more details about internal validation results.

Enable FQ fusions in MOC

---

src/plugins/intel_gpu/include/intel_gpu/plugin/remote_context.hpp
src/tests/functional/plugin/gpu/remote_blob_tests/gpu_remote_tensor_tests.cpp

- *prevent calling additional blob.allocate() for blobs that already have been cached. This fixes the assert during multiple RemoteBlob constructions using the same USM or CL buffer*
- *81366*

[GPU] Fix allocation for cached USM remote blobs

---

samples/cpp/build_samples.sh

- If the `build_samples.sh` is run not from `samples/cpp`, it prints wrong samples type based on PWD, but not on folder where the script is located
- [CVS-83065](https://jira.devtools.intel.com/browse/CVS-83065)

Fixed detection of sample type c / cpp

---

src/plugins/intel_myriad/common/include/vpu/ngraph/operations/dynamic_shape_resolver.hpp
src/plugins/intel_myriad/common/src/ngraph/operations/dynamic_shape_resolver.cpp
src/plugins/intel_myriad/common/src/ngraph/transformations/dynamic_to_static_shape_transpose.cpp
src/plugins/intel_myriad/common/src/ngraph/transformations/extract_dynamic_batch/extract_dynamic_batch.cpp
src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp
src/plugins/intel_myriad/graph_transformer/src/frontend/in_out_convert.cpp
src/plugins/intel_myriad/myriad_plugin/myriad_executable_network.cpp
src/tests/functional/plugin/myriad/ngraph/transformations/dynamic_to_static_shape_transpose.cpp

This PR contains several fixes for models with dynamic inputs
- `DynamicShapeResolver` is able to save information about dynamic output in order to pass it in `INFER_DYNAMIC_SHAPE` mode. Previously, it propagated fully dynamic output shape (however ranks were equal) and dynamic Convolutions and Poolings were performed incorrectly. Now in the case of dynamic batch, DSR propagates only dynamic batch and Convolutions and Poolings are performed properly as a Loop of single-batch operations.
- Fixed `dynamicToStaticShapeTranspose` transformation. There was a bug: transposition indices could not be applied with Scatter because the formula is not applicable for this. Replaced with Gather.
i.e. Shape of output tensor of Transpose with transition [0,3,1,2] indices (NHWC [1, 224, 224, 3]->NCHW [1, …

[RT][VPU]: Fixes for dynamic models

---

docs/OV_Runtime_UG/Operations_specifications.md
docs/ops/sort/NonMaxSuppression_9.md

- *NMS-9_specification*
New version of the operation NonMaxSuppression is created to support for soft NMS behavior, where the candidate box is only suppressed by degraded score instead of suppressed by IOU directly.
In the cases such as TF soft NMS5, candidate boxed never suppressed by IOU, only suppressed by score to avoid suppression to box, which have high IOU but also having very high score([code](https://github.com/tensorflow/tensorflow/blob/3a7362750d5c372420aa8f0caf7bf5b5c3d0f52d/tensorflow/core/kernels/image/non_max_suppression_op.cc#L236-L237), [spec](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/non-max-suppression-v5)).
- *79200*

Specify NonMaxSuppression-9

---

docs/ops/generation/Eye_9.md
src/core/include/ngraph/op/eye.hpp
src/core/include/ngraph/ops.hpp
src/core/include/openvino/op/eye.hpp
src/core/include/openvino/op/ops.hpp
src/core/include/openvino/opsets/opset9_tbl.hpp
src/core/shape_inference/include/eye_shape_inference.hpp
src/core/src/op/eye.cpp
src/core/tests/CMakeLists.txt
src/core/tests/type_prop/eye.cpp
src/core/tests/visitors/op/eye.cpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference.cpp
src/tests/functional/inference_engine/transformations/op_conversions/detection_output_downgrade_test.cpp
src/tests/functional/inference_engine/transformations/op_conversions/detection_output_upgrade_test.cpp

- *nGraph shell for Eye-9*
- *Covered all exceptions by tests*
- *[PR](https://github.com/openvinotoolkit/openvino/pull/11104) with specification*
- *Updated spec: 3 inputs are required to avoid ctor conflicts*
- *Fixed DetectionOutput conversion op tests - not initialized attribute `nms_threshold` (BTW, Valgrind shows this error in this test). [Failed tests are in CI](https://dev.azure.com/openvinoci/dldt/_build/results?buildId=319331&view=results)*
- *82301*

Added shell for Eye-9

---

src/bindings/python/requirements_test.txt

- If system was using build-in wheel version which was lower than `0.36.2`, it was resulting in CMake errors due to dependency on `wheel.vendored` module. Adding lower bound solves the issue.
- *84294*

[PYTHON] Add lower bound for wheel package

---

src/tests/functional/plugin/conformance/test_runner/conformance_infra/include/conformance.hpp

Check first whether the path specified by --input_dirs is a directory.
Otherwise the argument is always treated as a .lst file,
and in case it is a directory it silently fails,
which causes the test runner to not execute any tests intended.

Fix conformance test runner handling of input directories

---

src/tests/functional/plugin/cpu/shared_tests_instances/behavior/ov_executable_network/properties.cpp
src/tests/functional/plugin/cpu/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/tests/functional/plugin/cpu/shared_tests_instances/behavior/plugin/configuration_tests.cpp

CPU plugin sets default affinity to HYBRID_AWARE if it's running on AlderLake,.
So we need to reflect that in cpuFuncTests.

Fix setting default affinity property in cpuFuncTests

---

docs/OV_Runtime_UG/Operations_specifications.md
docs/ops/detection/ROIAlign_9.md
docs/ops/opset9.md

- *Add an 'aligned_mode' attribute to 'ROIAlign' operator in order to specify how to transform the coordinate in original tensor to the feature map during 'ROIAlign' operation. e.g. transform method used in Paddle Framework: https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/vision/ops/roi_align_en.html*
- *82315*

Specify ROIAlign-9

---

docs/OV_Runtime_UG/Operations_specifications.md
docs/ops/detection/GenerateProposals_9.md
docs/ops/opset9.md

- *Add spec for GenerateProposals opset9*
- *GenerateProposals can support paddle generate proposals v2 (https://github.com/PaddlePaddle/PaddleDetection/blob/3c78716d30945e89129c1839453932482f4a6974/ppdet/modeling/ops.py#L1424 and https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/detection/generate_proposals_v2_op.cc) and Caffe2 Generate Proposal(https://github.com/pytorch/pytorch/blob/4dae85c38517fd066a67901f660ca3bc08da7446/caffe2/operators/generate_proposals_op.cc#L365)*
- *GenerateProposals is a new op based on v6::ExperimentalDetectronGenerateProposalsSingleImage. Below are the changes compared with v6::ExperimentalDetectronGenerateProposalsSingleImage:*
- Support batch
- Support dynamic output. Change both outputs to dynamic
- Add one output 'rpnroisnum'
- …

Specify GenerateProposals-9

---

scripts/setupvars/setupvars.sh

Based on #11579 
The splitting of Python version to array works differently on the `zsh` which is default shell on Mac
Solution tested on:
- zsh 5.8 (x86_64-ubuntu-linux-gnu)
- bash  5.0.17(1)-release (x86_64-pc-linux-gnu)

Getting of python version depend on the used shell

---

src/plugins/intel_gpu/src/graph/impls/cpu/detection_output.cpp
src/plugins/intel_gpu/tests/test_cases/detection_output_test.cpp

- Add TC for decrease_label_id=true to cover MXNet-style NMS models
- Fix segfault issue that occurs when data precision is fp16
- Follow up comment from https://github.com/openvinotoolkit/openvino/pull/10500
- *ticket-id*

[GPU] Add TC for MXNet-style NMS model(decrease_label_id)

---

tests/time_tests/include/timetests_helper/parse.h
tests/time_tests/scripts/run_timetest.py
tests/time_tests/src/timetests/timetest_infer.cpp
tests/time_tests/src/timetests/timetest_infer_api_2.cpp
tests/time_tests/src/timetests_helper/cli.h
tests/time_tests/src/timetests_helper/main.cpp

- Support reading config options from file for timetest_infer and timetest_infer_api_2 with `-f <path_to_configfile>`, the format of config file is the same as compile_tool
- Support running script run_timetest.py with parameter `-f <path_to_configfile>`
- [EISW-39369](https://jira.devtools.intel.com/browse/EISW-39369)

Support config option for time_tests suite

---

docs/OV_Runtime_UG/integrate_with_your_application.md

This edit adds links to more example applications, making it easier for users to discover how to build an OpenVINO application around their specific model.
- Added links to OpenVINO Samples page and Open Model Zoo Demos page at the end of the document
- Minor grammar fixes
- N/A

Docs: Add links to specific examples

---

tests/time_tests/test_runner/conftest.py
tests/time_tests/test_runner/test_timetest.py

- The changes of [#PR11628](https://github.com/openvinotoolkit/openvino/pull/11628) would cause error when running pytest to test script "tests/time_tests/test_runner/test_timetest.py". This PR fix the failure by adding config_message as an optional command-line option to script "tests/time_tests/test_runner/conftest.py".
- [EISW-39369](https://jira.devtools.intel.com/browse/EISW-39369)

Add config option in pytest of timetest

---

docs/MO_DG/prepare_model/convert_model/Convert_Model_From_ONNX.md
docs/OV_Runtime_UG/integrate_with_your_application.md

port to master from 22.1 merge 
* Update docs/OV_Runtime_UG/integrate_with_your_application.md
* Add links to specific examples
This edit adds links to more example applications, making it easier for users to discover how to build an OpenVINO application around their specific model.

Docs: Add links to specific examples - port (#11618)

---

docs/install_guides/installing-openvino-yocto.md

Update the documentation with correct override syntax and remove reference to staticdev package.

yocto doc update for 2021.4

---

docs/install_guides/installing-openvino-yocto.md

Update the branch to be used for 2022.1 and remove reference to
-staticdev package which isn't generated anymore.
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>

installing-openvino-yocto: update for 2022.1

---

docs/install_guides/installing-openvino-yocto.md

This is no longer generated or required.
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>

installing-openvino-yocto: remove reference to staticdev

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing_through.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- Enable FP quant fusing for FC and gemm 
- Enable more region can be mapped to int8 (disabled ignoreReshape flag for cldnn path. The flag is still turned on for onednn since onednn FC is not optimized for int8 yet. ).
- Enabled more quantization can be fused through reshape/reorder
- 84106
- 81451

[GPU] Improve int8 FC performance 

---

src/plugins/intel_gna/transformations/decompose_mvn.cpp
src/tests/unit/gna/ngraph/transformations/gna_decompose_mvn.cpp

- align precisions of Constant layers created during MVN decomposition with other passes (i32 -> i64).
- 84785

[GNA] Change Constants' precision in MVN decomposition

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/convolution/convolution_kernel_yxfb_yxio_b16.cpp

convolution_gpu_yxfb_yxio_b16 for fp16 has hardcoded reqd_work_group_size
to (16, 1, 1). On devices where CL_DEVICE_MAX_WORK_GROUP_SIZE is 512
GetOptimalLocalWorkGroupSizes picks (16, 2, 1) for LWS.
That causes issues during clEnqueueNDRangeKernel since LWS doesn't match
with reqd_work_group_size in the kernel.

Fix local work size for conv kernel yxfb_yxio_b16 with fp16

---

docs/install_guides/installing-openvino-windows.md

- Replaced filename for Linux script with Windows filename
- Fixed incorrect file location
- Replaced `<openvino>` with `<INSTALL_DIR>`

Fixes for OpenCV script filename in Windows install docs

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/mat_mul.cpp

- *Add reorder between FC matmal and reshape*
- *Add 5d/6d format for only_gemm_users in case of int8 model*
- *84182*

[GPU] Add reorder between FC matmal and reshape

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp

- *Existing throw method doesn't provide information of file, line number and specific value*
- *throw std::runtime_error() --> IE_THROW()*
- *84720*

[GPU] Use IE_THROW() instead of throw std::runtime_error

---

src/plugins/intel_gpu/src/kernel_selector/core/cl_kernels/deformable_convolution_gpu_bfyx_ref.cl
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/deformable_convolution.cpp

- *Update for-loop and fix index operations*
- *Add Multi-Groups testcases*
- *59600*

Fix deformable convolution cl kernel for Multi-Groups

---

docs/OV_Runtime_UG/Samples_Overview.md
samples/c/hello_classification/README.md
samples/c/hello_nv12_input_classification/README.md
samples/cpp/classification_sample_async/README.md
samples/cpp/hello_classification/README.md
samples/cpp/hello_nv12_input_classification/README.md
samples/cpp/hello_query_device/README.md
samples/cpp/hello_reshape_ssd/README.md
samples/cpp/model_creation_sample/README.md
samples/cpp/speech_sample/README.md
samples/python/classification_sample_async/README.md
samples/python/hello_classification/README.md
samples/python/hello_query_device/README.md
samples/python/hello_reshape_ssd/README.md
samples/python/model_creation_sample/README.md
samples/python/speech_sample/README.md

Added GitHub links in the README for each OpenVINO Sample to make it easier for users to access the source code from the OpenVINO online documentation. Links were added to the OpenVINO Samples Overview page and each C/C++/Python sample page.
-N/A

Docs: Add source code links to OpenVINO Samples

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp

- Update reorder_inputs opt pass for adding reorder to change input data type of fully-connected node from i32 to f32
- 85341

[GPU] Update reorder_inputs for data type conversion on fc layer

---

src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp

- Enable "fc_int8_inputs_fused_fp32_sum" again.
- This issue was resolved by https://github.com/openvinotoolkit/openvino/commit/98f989302a5ca1d33434a14a8eb4f6f806938220
- 85210

Revert "Disable fc_int8_inputs_fused_fp32_sum (#11709)"

---

.ci/azure/linux.yml
.ci/azure/mac.yml
.ci/azure/windows.yml

- Enable CI to run OV 2.0 C API unit test

ov 2.0 c api ci test enable

---

src/plugins/intel_cpu/src/plugin.cpp
src/tests/functional/plugin/cpu/shared_tests_instances/low_precision_transformations/reduce_mean_transformation.cpp
src/tests/functional/plugin/cpu/single_layer_tests/reduce_ops.cpp

- *Revert 21f3555f59b47317c5f5334424a5fef344e6d317 [[WA] Enabled ReduceSum -> AvgPool transformation due to perf issues](https://github.com/openvinotoolkit/openvino/pull/11627/commits/21f3555f59b47317c5f5334424a5fef344e6d317)*
Tests show disable the transformation will have positive impact.
- **

[CPU] Revert enable ReduceSum -> AvgPool transformation due to perf issues

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/oooq_memory_dependencies.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/skipped_branch_memory_dependencies.cpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp

- Constant memory does not use pool : No need to add constant nodes to deps.
- 82135
- 86267

[GPU] Optimize memory dep analysis 

---

src/frontends/onnx/frontend/src/core/graph.cpp
src/frontends/onnx/frontend/src/op/identity.hpp
src/frontends/onnx/frontend/src/utils/common.cpp
src/frontends/onnx/frontend/src/utils/common.hpp
src/frontends/onnx/frontend/src/utils/variadic.hpp

- ONNX variadic ops are optimized out when they contain only one input
- Such models produce an OV representation containing just 2 nodes: Parameter->Result
- Those nodes reuse a single tensor which now contains both names from the model (both input and output of the model)
- The OV user can access the name of such tensor with both strings now
- 85962

Additional tensor names for ONNX variadic ops

---

tools/mo/openvino/tools/mo/utils/get_ov_update_message.py

Do not show the message to check for OpenVINO updates in MO until October 31. This is a bit later than the expected update date, which is better than much earlier, which we had for the past two releases. 
Slightly change update message, remove "It's been a while" because that really depends. You now get this message on the day of install, which is not a great user experience.

Update date in MO update message

---

tools/pot/openvino/tools/pot/api/samples/speech/gna_sample.py

Need the ability to save compressed weights for GNA IR.
- adding ‘--write_quantized_weights_to_bin_file’ to gna_sample.py
- This option lets gna_sample.py store the quantized weights as INT8 to the output IR bin file
- 69817

Add an option to store the quantized weights as INT8 on the GNA sample

---

src/plugins/auto/auto_schedule.cpp

- *fix issue: benchmark_app -d AUTO -hint ctput -pc does not give perfcount data*
- *ticket-86026*

ctput enable perf_count

---

tests/samples_tests/smoke_tests/common/samples_common_test_clas.py
tests/samples_tests/smoke_tests/test_hello_classification.py

- *Add C API test sample(hello_classification) for OV API 2.0 in CI test* 
- *72178*

Add C test sample for OV API 2.0 in CI test

---

docs/_static/js/gsearch.js

Signed-off-by: intelkevinputnam <intelkevinputnam@github.com>
**root cause**: S3 expects the Query string to be sorted alphabetically
* Current page request will fail signature validation: https://docs.openvino.ai/nightly/search.html?query=aI&page=4&version=ALL
* Reorganizing the query strings succeeds: https://docs.openvino.ai/nightly/search.html?page=4&query=aI&version=ALL
Akamai docs address it here: https://techdocs.akamai.com/object-delivery/docs/origin-characteristics-and-od under the Additional considerations
> "Only the "Authorization" header is supported (AWS, only). If you're using query string parameters with this authentication, each query parameter in the incoming client request must be sorted alphabetically, and URL encoded."”

Puts page switch parameters in alphabetic order to support S3

---

scripts/setupvars/setupvars.sh

This extra semicolon creates output as in the example below. The extra
'::' is equivalent to adding '.' to the LD_LIBRARY_PATH. This breaks
glibc build, and very often creates weird issues when launching
commands from a different path.
...inference_engine/external/tbb/lib::/opt/intel/openvino_2021/...
We also noticed that ':${parameter:+:$parameter}' is widely used in
this file. Please review the code and fix it as needed.
- *item1*
- *...*
- *ticket-id*

setupvars.sh: Removing extra semicolon, which breaks glibc build

---

src/inference/dev_api/cpp_interfaces/interface/ie_internal_plugin_config.hpp
src/plugins/auto/CMakeLists.txt
src/plugins/auto/plugin.cpp
src/tests/unit/auto/auto_release_helper_test.cpp
src/tests/unit/auto/auto_select_device_failed_test.cpp
src/tests/unit/auto/exec_network_get_metrics.cpp

Remove the config key MULTI_WORK_MODE_AS_AUTO from the AUTO/MULTI plugin
Signed-off-by: Wang, Yang <yang4.wang@intel.com>
- Remove the config key MULTI_WORK_MODE_AS_AUTO
- CVS-84417

Remove the config key MULTI_WORK_MODE_AS_AUTO from the AUTO/MULTI plugin

---

src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/reduce.cpp

- *Remove vmaxps in store_vector. This instruction is not needed for dst_prc int8. And it may lead to wrong result with denormals optimization is on.*
- *86900*

[CPU] Remove vmaxps in store_vector.

---

samples/cpp/benchmark_app/README.md
samples/cpp/benchmark_app/benchmark_app.hpp
samples/cpp/benchmark_app/main.cpp
src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/inference/include/ie/ie_plugin_config.hpp
src/inference/include/openvino/runtime/properties.hpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/conv.h
src/plugins/intel_cpu/src/utils/general_utils.h
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
tools/benchmark_tool/README.md
tools/benchmark_tool/openvino/tools/benchmark/main.py
tools/benchmark_tool/openvino/tools/benchmark/parameters.py

- *Use config 'ENFORCE_EXPERIMENT_CONVOLUTION' to enable brgconv f32 for avx512 f32. Relevant PR #11866*
- *...*
- 86301

[CPU] [WA] Use config to enable brgconv f32 kernel

---

src/common/low_precision_transformations/src/fake_quantize.cpp
src/plugins/intel_cpu/src/docs/fake_quantize.md
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/fake_quantize.cpp
src/plugins/intel_cpu/src/nodes/fake_quantize.h
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h

- *Optimize FullyConnected FakeQuantize post-ops with a inner product output scaling*
- *Optimize FullConnected "eltwise+ FakeQuantize" post-ops with a eltwise scaling*
- *CVS-86027*
- *CVS-85020*

Optimize FullyConnected FakeQuantize post-ops

---

src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/tests/functional/plugin/gpu/remote_blob_tests/gpu_remote_tensor_tests.cpp

- *Issue fix: During nv12 batching with surface memory type, first infer works but second infer returns error.*
- *85605*

[GPU] Delete previous inputs by numbered new name for batching

---

src/plugins/intel_cpu/src/nodes/rnn.cpp
src/plugins/intel_cpu/src/nodes/rnn.h

- Memory size will quickly increase with inference iterations during running OCR dynamic shape model inference. The root cause comes from the rnn cache, almost all cache are missing, it was caused by incorrect match criteria.  
- 87097

[CPU]Fix rnn cache missing issue

---

CMakeLists.txt

- *Add build flag for GCC. Because some compiler flags restrict the compiler from making arbitrary decisions while handling undefined C/C++ behaviors.*
- 85228

Add build flag for GCC (for SDL: preventing GCC optimizing out security checks)

---

src/frontends/ir/src/frontend.cpp

- This reverts the mmap-ed constants in commit https://github.com/openvinotoolkit/openvino/commit/4b3dd808df47f857d3bf879e60a735afc571de10.
- The original PR https://github.com/openvinotoolkit/openvino/pull/10907 will be reapplied after more aggressive validation & analysis being conducted
- 68937

Revert the mmap-ed constants to the original buffer load

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/eltwise/eltwise_kernel_vload8.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/eltwise/eltwise_kernel_vload8.h

- Currently, the 'eltwise_kernel_vload8' does not support operation fusing.
- It prevents an activation layer to be processed by eltwise_vload8.
- This PR makes 'eltwise_vload8' to process an activation layer.
- 87395

Updated to fuse activation in eltwise_vload8

---

samples/cpp/speech_sample/README.md
samples/cpp/speech_sample/main.cpp
samples/cpp/speech_sample/speech_sample.hpp
samples/cpp/speech_sample/utils.hpp

[SAMPLES] Remove unused commandline arguments for speech_sample
- Removed -iname and -oname arguments declaration from header
and from documentation for speech_sample
- Fixed error message to use -i instead of -iname
85754

[SAMPLES] Remove unused commandline arguments for speech_sample

---

src/plugins/intel_gpu/src/graph/activation.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/eltwise.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/lrn/lrn_kernel_across_channel_multiple_features.h
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/lrn/lrn_kernel_across_channel_opt_b8.h
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/lrn/lrn_kernel_across_channel_ref.h
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/lrn/lrn_kernel_ref.h
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/lrn/lrn_kernel_within_channel_byxf_opt.h
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/lrn/lrn_kernel_within_channel_ref.h
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/lrn/lrn_kernel_within_channel_ref_opt.h
src/plugins/intel_gpu/tests/fusions/lrn_fusion_test.cpp

- Change Scale to Eltwise(mode::prod) in unit test topologies.
- Change ScaleWithBias to Eltwise(mode::prod)+Eltwise(mode::sum) in unit test topologies.
- Support Gather-Eltwise fusing.
- 67491

[GPU] Pass lrn unit tests on DG2

---

src/plugins/intel_gpu/tests/fusions/reduce_fusion_test.cpp

- Change Scale to Eltwise( mode::prod ) in unit test topologies.
- Change Activation::cos to Activation::hyperbolic_tangent in unit test topologies. (onednn not support cos activation)
- 67491

[GPU] Pass reduce unit tests on DG2

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/gemm/gemm_kernel_ref.cpp
src/plugins/intel_gpu/tests/test_cases/gemm_gpu_test.cpp

- Enable tensor offset to `GemmKernelRef` for input padding support from in-place crop optimization
- 87144

[GPU] Enable tensor offset to GemmKernelRef for input padding support

---

samples/cpp/benchmark_app/README.md
samples/cpp/benchmark_app/benchmark_app.hpp
samples/cpp/benchmark_app/main.cpp
src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/inference/include/ie/ie_plugin_config.hpp
src/inference/include/openvino/runtime/properties.hpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/conv.h
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
tools/benchmark_tool/README.md
tools/benchmark_tool/openvino/tools/benchmark/main.py
tools/benchmark_tool/openvino/tools/benchmark/parameters.py

- *Remove the config 'CPU_EXPERIMENTAL' for CPU plugin: #11990*
- *Enable brgconv avx512 on SPR by default*
- *PR to master: #12105*
- *87535*
- *86948*

[CPU] revert pr 11990 and enable brgconv avx512 on SPR by default

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/activation/activation_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/activation/activation_kernel_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/activation/activation_kernel_opt.h
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/activation/activation_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/activation/activation_kernel_ref.h
src/plugins/intel_gpu/src/kernel_selector/core/cl_kernels/activation_ref.cl
src/plugins/intel_gpu/tests/fusions/activation_fusion_test.cpp
src/plugins/intel_gpu/tests/test_cases/activation_simple_gpu_test.cpp

- This reverts commit 3334e8933cb268b1e48bff1922b22c0a5c93d0bb.
- The reverted commit prevented fusing an activation node to its predecessor, and it causes performance degradation in some cases.
- *ticket-id*

Revert "[GPU] Pass activation unit tests on DG2 (#11969)"

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/permute/permute_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/core/cl_kernels/permute_ref.cl

- Fix access order of permute_ref to process f axis first if input is fsv and output is bfyx and the f is moved to x position
- 86967

[GPU]  optimize permute_ref 

---

src/frontends/onnx/frontend/src/core/graph.cpp
src/frontends/tests/onnx/onnx_import.in.cpp
src/frontends/tests/onnx/onnx_tensor_names.cpp

- this PR aligns the cpp ONNX FE with legacy MO behavior
- because of how legacy runtime API works the nodes connected directly to the `Results` always have to be named just like the ONNX model outputs
- this is required even if the nodes in the ONNX models have their names set (non-empty)
- 87412

ONNX FE: friendly names of the last operators

---

install_build_dependencies.sh
scripts/install_dependencies/install_openvino_dependencies.sh
src/cmake/ie_parallel.cmake
src/core/CMakeLists.txt

- For libraries with `/usr/include` paths we cannot use `SYSTEM` to include their headers
- CVS-79566

Fixes for system libraries pugixml, tbb

---

src/plugins/intel_cpu/src/nodes/topk.cpp
src/tests/functional/plugin/cpu/single_layer_tests/topk.cpp

- *Fixed heap sort bug regarding heapifying for top1 sort in dynamic shape mode. This bug has not been observed in static shape mode, because other sorting algorithm is applied for top1 sort.*
- *84559*

[CPU] Fixed heap sort bug regarding heapifying

---

src/plugins/intel_cpu/thirdparty/CMakeLists.txt

- and rely on oneDNN default behavior otherwise
PR for release 2022.2
- https://github.com/openvinotoolkit/openvino/pull/12151
Ticket:
- 87745

[CPU] Explicitly enable DNNL_VERBOSE only in case of CPU_DEBUG_CAPS

---

src/plugins/intel_gna/gna_graph_compiler.cpp
src/plugins/intel_gna/layers/gna_layer_info.hpp
src/plugins/intel_gna/optimizer/gna_pass_manager.cpp
src/tests/functional/plugin/gna/pass_tests/remove_permutations_NHWC_to_NCHW_pass.cpp
src/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/split_relu.cpp

- *Fixed setting NHWC layout for layers in Transpose -> Convolution -> Transpose patterns where several convolutions have a shared input transpose.*
- *Fixed calculation of GNA dimensions for ConvolutionFilter and activations with more than 2 dimensions.*
- *Added tests for these cases.*
- *81370*
- *81287*
Original PR https://github.com/openvinotoolkit/openvino/pull/11373

[GNA] Fixed convolutions with shared transpose and un-fuse-able activations after Convolution filter (Renew PR11373)

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/pooling.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/pooling.cpp

- *Add reorder i32 to f32 for max-pooling input*
- *Add reorder i32 to f32 for convolution input and weight*
- *Add reorder i32 to f32 for fc weight*
- *87077*

[GPU] Add reorder from i32 to f32 for max-pooling/conv/fc which doesn't support i32

---

docs/requirements.txt

- backport of https://github.com/openvinotoolkit/openvino/pull/12168 to the release branch

ipython removal from the dependencies of the docs [2022/2]

---

src/frontends/tensorflow/src/op/conv_2d.cpp
src/frontends/tensorflow/src/op/conv_2d_backprop.cpp
src/frontends/tensorflow/src/op/conv_3d.cpp
src/frontends/tensorflow/src/op/conv_3d_backprop.cpp

**Details:** TensorFlow convolution operations have two optional attributes with default values: *data_format* and *dilations*. See the specifications for them: [Conv2D](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/conv2-d), [Conv2DBackpropInput](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/conv2-d-backprop-input), etc. This fix will top up e2e passrate for DeepLapv3/inception models.
**Ticket:** 88012

[TF FE] Handle optional attributes for Convolutional operations

---

cmake/templates/OpenVINOConfig.cmake.in
src/cmake/install_tbb.cmake

- On Windows we have to convert env variables values to cmake native path with forward slashes. 
- CVS-87872

Fixed Windows backslash paths

---

tools/mo/openvino/tools/mo/middle/passes/fusing/fuse_linear_ops.py

**Root cause analysis:** Mul fusion with Convolution/FC fails in case dynamic channel dimension
**Solution:** It is not possible to perform the fusion in case dynamic channel dimension
**Ticket:** 87733
Code:
Validation:
Documentation:

[MO] Fix Mul fusion with dynamic channel dimension

---

samples/cpp/build_samples.sh
src/cmake/install_tbb.cmake

- When `TBB_DIR` env var is set, no `TBBROOT` is defined then by cmake. We have deduce this value by ourselves.
- CVS-87872

Fixes for cases when TBB_DIR env var is set

---

src/frontends/tensorflow/src/op/linspace.cpp
src/frontends/tensorflow/src/op/matmul.cpp
src/frontends/tensorflow/src/op_table.cpp

**Details:** TensorFlow frontend lacks [LinSpace](https://www.tensorflow.org/api_docs/python/tf/linspace) and [BatchMatMul](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/batch-mat-mul-v2) translators for conversion of STN model (from e2e testing). Make a note that LinSpace translator is missed in legacy frontend and MO fallbacks a native call for constant folding for LinSpace operation. BatchMatMul translator is trivial because it easily maps to our MatMul specification.
LinSpace translation has a bit tricky implementation and based on the following scheme:
1) Compute deltas by which each element will be increased in each slice through new dimension as delta = (stop - start) / (num - 1)
2) Generate a range of numbers by which times delta will be added to start to compute new …

[TF FE] Implement LinSpace and BatchMatMul translators

---

src/common/legacy/src/graph_transformer.cpp
src/core/include/openvino/core/node.hpp
src/core/include/openvino/pass/constant_folding.hpp
src/core/src/node.cpp
src/core/src/op/convert_like.cpp
src/core/src/op/reshape.cpp
src/core/src/op/shape_of.cpp
src/core/src/op/squeeze.cpp
src/core/src/op/unsqueeze.cpp
src/core/src/pass/constant_folding.cpp
src/core/tests/constant_folding.cpp

- Constant fold check in operators not only in pass to be more consistent that if constant fold attribute set then node constant 
fold on happens if this attribute is supported.
- Refactor constant fold pass to using ov instead of ngraph namespaces and includes.
- Add constant_folding_is_disabled overload for raw pointer
- *75563*

Add const fold check in operators instead pass

---

samples/cpp/build_samples.sh
scripts/install_dependencies/install_NCS_udev_rules.sh
scripts/setupvars/setupvars.sh
src/tests/functional/plugin/myriad/run_tests_myriad_multistick.sh

- Fixed build_samples.sh not to call setupvars.sh for Debian package case
- CVS-79402

Fixed build_samples.sh not to call setupvars.sh for Debian package case

---

src/frontends/tensorflow/src/op/conv_2d.cpp
src/frontends/tensorflow/src/op/conv_2d_backprop.cpp
src/frontends/tensorflow/src/op/conv_3d.cpp
src/frontends/tensorflow/src/op/conv_3d_backprop.cpp
src/frontends/tensorflow/src/op/crop_and_resize.cpp
src/frontends/tensorflow/src/op/fake_quant_min_max_vars.cpp
src/frontends/tensorflow/src/op/interpolate.cpp
src/frontends/tensorflow/src/openvino_conversions.cpp
src/frontends/tensorflow/src/openvino_conversions.hpp
src/frontends/tensorflow/src/pass/transpose_sinking.cpp

**Details:** Currently the conversion for NetVLAD model (from e2e scope) fails due to no support of `Gather` evaluate method for `u64` type that is triggered during `TransposeToReshape` common transformation. `u64` type appears during creation IR by TensorFlow frontend. The TF frontend uses `u64` type for creation of Transpose nodes in a graph.
Now I changed this type into `i64` and refactor the code to have the single routine for Transpose node creation.
Now the model is converted and inferred successfully. 
**Ticket:** 88446

[TF FE] Fix conversion of NetVLAD model

---

src/plugins/intel_gpu/include/intel_gpu/primitives/scatter_elements_update.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/scatter_elements_update.cpp
src/plugins/intel_gpu/src/plugin/ops/scatter_elements_update.cpp
src/plugins/intel_gpu/tests/fusions/scatter_elements_update_fusion_test.cpp
src/plugins/intel_gpu/tests/test_cases/scatter_elements_update_gpu_test.cpp

- *Enum changed to int64_t for scatter_elements_update primitive.*

[GPU] Use int64_t type for axis in ScatterElementsUpdate

---

src/inference/src/ie_core.cpp

- *Auto-batch fix: if plugin if disabled during cmake*
- *88449*

Auto Batch: if plugin is disabled during cmake

---

src/core/src/pass/graph_rewrite.cpp

- Currently logs only show whether a matcher succeded and do not show the result
of matcher callback

Add debug log showing the result transformation callback

---

src/plugins/intel_gpu/include/intel_gpu/primitives/convolution.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/pre_replace_deconv.cpp

- Update pre_replace_deconv opt pass to support `output_shape` for transposed conv when it is specified as an input tensor of deconv
- 87062

[GPU] Update pre_replace_deconv to support output_shape for transposed conv

---

src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp

- The inputs containing gather indices might be scalars
- The concatenation of scalars is not supported
- An initial fix is to return false from the GroupedGatherElimination pass when such subgraph is found in a model
- This situation could potentially be handled by using Reshape operators before they are passed to the Concat node but it should be done as a follow-up of this PR
- 88091

GroupedGatherElimination short circuit

---

tools/mo/openvino/tools/mo/utils/get_ov_update_message.py

Root cause analysis: update date was too early, which may cause unexpected showing of update message.
Solution: Move update date in MO message to 1.02.22
Ticket: CVS 88686
Code:
Validation:
Documentation:

Updated date for update message.

---

docs/OV_Runtime_UG/auto_device_selection.md
docs/OV_Runtime_UG/automatic_batching.md

Signed-off-by: Chen Peter <peter.chen@intel.com>
- *Introduce ov::hint::allow_auto_batching and ov::auto_batch_timeout on AUTO page*
- *Change AUTO_BATCH_TIMEOUT to ov::auto_batch_timeout*
- *THROUGHPUT hint as default for AUTO*
- *ticket-id*

Add notes for AUTO hints

---

tools/mo/openvino/tools/mo/front/tf/loader.py
tools/mo/openvino/tools/mo/main.py

**Details:** Currently, the new TensorFlow frontend supports only frozen `.pb` format.
In order to unveil problems with conversion of models of other formats (`Checkpoint`, `MetaGraph`, and `SavedModel`) now, we have to implement workaround that helps to convert non-frozen model to frozen `.pb` format in MO before it is passing the model to the new TensorFlow frontend.
**Ticket:** 83868

[TF FE] Implement workaround to convert non-frozen models

---

cmake/test_model_zoo.cmake
src/frontends/tests/onnx/onnx_editor.cpp
src/frontends/tests/onnx/onnx_import.in.cpp
src/frontends/tests/onnx/onnx_import_com_microsoft.in.cpp
src/frontends/tests/onnx/onnx_import_const_folding.in.cpp
src/frontends/tests/onnx/onnx_import_controlflow.in.cpp
src/frontends/tests/onnx/onnx_import_convpool.in.cpp
src/frontends/tests/onnx/onnx_import_deprecated.in.cpp
src/frontends/tests/onnx/onnx_import_dyn_shapes.in.cpp
src/frontends/tests/onnx/onnx_import_exceptions.cpp
src/frontends/tests/onnx/onnx_import_external_data.in.cpp
src/frontends/tests/onnx/onnx_import_org_openvino.in.cpp
src/frontends/tests/onnx/onnx_import_quant.in.cpp
src/frontends/tests/onnx/onnx_import_reshape.in.cpp
src/frontends/tests/onnx/onnx_import_rnn.in.cpp
src/frontends/tests/onnx/onnx_import_with_editor.in.cpp
src/frontends/tests/onnx/onnx_tensor_names.cpp
src/frontends/tests/onnx/onnx_test_utils.in.cpp
src/frontends/tests/onnx/onnx_transformations.cpp

- ONNX tests modified to use another path to the models
- This change lets the test binaries operating on various models be executed outside of the bin/intel64/Debug (or Release) directory
- 88917

Models path adjustment in ONNX tests

---

src/frontends/tensorflow/src/op/strided_slice.cpp
tests/layer_tests/tensorflow_tests/test_tf_StridedSlice.py

**Details:** Currently, new_axis vector is cut by input rank that is incorrect and leads to the loss of new axes.
**Ticket:** 88982

[TF FE] Fix StridedSlice translator for new_axis vector size longer input rank

---

tools/mo/openvino/tools/mo/front/output_cut.py

- when processing a model with multiple outputs, their custom names are not transferred properly because each Result edge fw_tensor_debug_info is overridden by the fw_tensor_debug_info of the first found fake output.
- 61417

[MO] Result edges naming issue

---

docs/_static/css/custom.css

port from master
code formatting changed from blue to black, to distinguish from links

DOCS-code-reference-css-style-change (#12109)

---

src/frontends/onnx/frontend/src/core/graph.cpp
src/frontends/tests/onnx/onnx_import.in.cpp
src/frontends/tests/onnx/onnx_tensor_names.cpp

- Backport of https://github.com/openvinotoolkit/openvino/pull/12139 to the 2022.2 release branch
- 88695

ONNX FE: friendly names of the last operators [2022/2]

---

src/plugins/intel_gpu/src/kernel_selector/core/common/jitter.cpp
src/plugins/intel_gpu/src/kernel_selector/core/common/jitter.h
src/plugins/intel_gpu/src/kernel_selector/core/common/kernel_base_opencl.cpp

Previously INPUT/OUTPUT_SIZES was declared as an unnamed array macro.
However current ocl compiler deals with the value obtained from such an array non-constant, so that it results in a side effect in compiler optimization.
Here, a workaround for this issue is applied, i.e., declare the INPUT_OUTPUT_SIZES as a __const array instead of jit constants.
- 87391

[GPU] W/A for compilation issue

---

src/plugins/auto/plugin.cpp
src/plugins/auto/plugin.hpp
src/plugins/auto/utils/config.hpp
src/tests/functional/plugin/cpu/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
src/tests/unit/auto/auto_select_device_failed_test.cpp

- refine config
- return default values for config and enable tests
- support 2.0 API for getConfig
- 84420

refine auto config and enable default config values

---

src/plugins/intel_gpu/include/intel_gpu/runtime/stream.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.hpp

+ benchmark cache_dir option takes longer than cl_cache_dir env in loading network.
+ For clDNN execution, benchmark cache_dir created onednn_engine if just ONEDNN_ENABLE config is ON.
+ Creation of onednn_engine in ocl_engine is changed to on-demand.
- *item1*
- *...*
- 87811

[GPU] Fix network loading time related to onednn engine creation

---

src/plugins/intel_gpu/src/plugin/ops/cum_sum.cpp
src/plugins/intel_gpu/src/plugin/ops/gather_nd.cpp
src/plugins/intel_gpu/src/plugin/ops/mvn.cpp
src/plugins/intel_gpu/src/plugin/ops/prior_box.cpp
src/plugins/intel_gpu/src/plugin/ops/reduce.cpp
src/plugins/intel_gpu/src/plugin/ops/reshape.cpp
src/plugins/intel_gpu/src/plugin/ops/roll.cpp
src/plugins/intel_gpu/src/plugin/ops/scatter_elements_update.cpp
src/plugins/intel_gpu/src/plugin/ops/scatter_nd_update.cpp
src/plugins/intel_gpu/src/plugin/ops/select.cpp
src/plugins/intel_gpu/src/plugin/ops/shuffle_channels.cpp
src/plugins/intel_gpu/src/plugin/ops/softmax.cpp
src/plugins/intel_gpu/src/plugin/ops/space_to_batch.cpp
src/plugins/intel_gpu/src/plugin/ops/split.cpp
src/plugins/intel_gpu/src/plugin/ops/strided_slice.cpp
src/plugins/intel_gpu/src/plugin/ops/transpose.cpp
src/plugins/intel_gpu/src/plugin/ops/unary.cpp

- Get rid of a part get_*_shape calls which throw an exception for dynamic models
- Use ov::normalize_axis method instead of custom code
- Added static shapes check for some ops to have better exception messages

[GPU] Use partial shape in some ops factories

---

src/plugins/intel_cpu/src/nodes/normalize.cpp

It was agreed that eps application should be consistent in NormalizeL2: before sqrt everywhere. Currently it's applied before sqrt in some cases, and after sqrt in others
59788

[CPU] NormalizeL2: uniform application of eps

---

src/bindings/python/wheel/setup.py

When building wheel on Raspberry Pi the "ARCH" variable was not defined because the architecture of Pi is 'armv7l'

Fixed NameError: name 'ARCH' is not defined on Raspberry Pi (#12421)

---

cmake/developer_package/version.cmake

- During open-source build use the same scheme for `C_BUILD_NUMBER` version as in CI

Added version generation as in CI

---

.ci/azure/linux_debian.yml
cmake/features.cmake
scripts/setupvars/setupvars.sh
src/cmake/install_tbb.cmake
src/plugins/intel_cpu/CMakeLists.txt

- Don't set `ENABLE_SYSTEM_TBB_DEFAULT` to `ON` if a user has provided his variables.
- Handle case with TBB 2017 with no cmake files
- Added check before oneDNN to disable TBB finding, oneDNN can rely on OpenVINO TBB. Otherwise, we have issues that TBB target is defined multiple times
- CVS-89248
- CVS-86372

Fixed CVS-89248

---

src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp

- Disable TCs(_SUPPORTED_CONFIG_KEYS/METRICS) for OVClassHeteroExecutableNetworkGetMetricTest same as GPU and GNA plugin
- This is the same change with https://github.com/openvinotoolkit/openvino/pull/12433
- 88667

[GPU] Disable TCs for OVClassHeteroExecutableNetworkGetMetricTest

---

.github/workflows/build_doc.yml
.github/workflows/check_pr_commits.yml
.github/workflows/code_style.yml
.github/workflows/files_size.yml
.github/workflows/mo.yml
.github/workflows/py_checks.yml
cmake/developer_package/clang_format/clang_format.cmake
cmake/developer_package/ncc_naming_style/ncc_naming_style.cmake
cmake/developer_package/ncc_naming_style/requirements_dev.txt
cmake/developer_package/shellcheck/shellcheck.cmake
docs/requirements.txt
install_build_dependencies.sh
scripts/CMakeLists.txt
src/tests/functional/plugin/myriad/run_tests_myriad_multistick.sh

- Used U22 for all github actions except clang-format 
- Improved suggestions for users of NCC - what clang package versions need to be installed on the system depending on default python version on Ubuntu
- Added support of multiple shellcheck versions and fixed several issues in bash scripts

U22 adoption in github actions

---

tools/mo/openvino/tools/mo/utils/get_ov_update_message.py

Root cause analysis: update date was too early, which may cause unexpected showing of update message.
Solution: Move update date in MO message to 1.02.22
Ticket: CVS 88686, CVS 89383
Code:
Validation:
Documentation:

Changed update date in MO message.

---

tools/benchmark_tool/requirements.txt
tools/benchmark_tool/setup.py

- *switch openvino-dev package on opencv-python-headless version by default due to problem to run tools in docker and server platforms without UI*
- *88523*

[releases/2022/2] openvino-dev uses opencv-python-headless as default

---

thirdparty/ittapi/CMakeLists.txt

This PR fixes usage of ITT library from installed VTune profiler

Fix path of find_package of ITT counters in case of defined INTEL_VTUNE_DIR variable

---

src/tests/functional/plugin/shared/include/behavior/plugin/core_threading.hpp

- *remove test case smoke_LoadNetwork_SingleIECore from releases/2022/2*
- *master PR  https://github.com/openvinotoolkit/openvino/pull/12557*
- *ticket-89440*

remove test case LoadNetwork_SingleIECore

---

src/plugins/intel_cpu/src/emitters/jit_emitter.hpp
src/plugins/intel_cpu/src/emitters/jit_load_store_emitters.cpp
src/plugins/intel_cpu/src/emitters/jit_load_store_emitters.hpp
src/plugins/intel_cpu/src/nodes/interpolate.cpp
src/plugins/intel_cpu/src/nodes/mvn.cpp
src/plugins/intel_cpu/src/nodes/non_max_suppression.cpp
src/plugins/intel_cpu/src/nodes/roi_align.cpp
src/plugins/intel_cpu/src/nodes/roi_pooling.cpp
src/plugins/intel_cpu/src/nodes/topk.cpp
src/plugins/intel_cpu/src/utils/jit_kernel.cpp
src/plugins/intel_cpu/src/utils/jit_kernel.hpp
src/tests/unit/cpu/jit_kernel_test.cpp

- *Removed contexts from Load/Store emitters. At the moment `Store` [pollutes](https://github.com/openvinotoolkit/openvino/blob/af05733a3a8ee249a6be23ae3862c4b49005115a/src/plugins/intel_cpu/src/emitters/jit_load_store_emitters.cpp#L587) `src_vmm` register in cases when src and dst precisions are different. So in the next stage in jit pipeline our `src_vmm` can be broken. To avoid additional `aux_vmm` in each store emitter this PR removes contexts to create exact emitter using ctor. Thus, count of aux registers is known it the moment emitter creation and this count is different for each case (at the moment in master `Store` and `Load` emitters have hardcoded count of aux regs*
- *Updated `Interpolate`, `MVN`, `NMS`, `ROI Align`, `ROI Pooling`, `TopK`, `ColorConvert`*
- *89024*

[CPU] Removed contexts from Load/Store emitters

---

install_build_dependencies.sh

**Root cause:** 
Missing patchelf dependency for REHL8 in install_build_dependencies.sh, will cause OpenVINO runtime wheel not build on RHEL8 even when -DENABLE_WHEEL=ON.
**Solutions:** 
Add patchelf dependency for REHL8 in install_build_dependencies.sh
- *item1*
- *...*
- *ticket-id*

Add missing patchelf dependency on REHL8 for OV python wheel build

---

scripts/setupvars/setupvars.sh

Fixed:
* SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].
* SC2086: Double quote to prevent globbing and word splitting
in TBB related part of the script.

Fix some of shellcheck errors in setupvars.sh

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/tests/fusions/deconvolution_fusion_test.cpp

- Change Scale to Eltwise( mode::prod ) in unit test topologies.
- Block eltwise-activation fusing when the activation function is not supported in onednn.
- 67491

[GPU] Pass deconvolution unit tests on DG2

---

samples/cpp/common/utils/include/samples/common.hpp
src/common/util/include/openvino/util/common_util.hpp
src/frontends/ir/src/ir_deserializer.hpp
src/frontends/ir/src/rt_info_deserializer.hpp

This PR fixes broken MSVC 141 build (yeah, I know it's pretty outdated, but anyway) by adding missing STL header includes.

Fix build with MSVC 141 (Visual Studio 2017)

---

.ci/azure/mac.yml

- 10.x is deprecated
- CVS-89140

Use OSX 11 pool for MacOSX

---

src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/conv.h

- *default enable avx512 f32 brgconv due to it will get performance improvement on ICX*
- *checkry-pick from #12406 #12619*
- *86301*

[CPU] default enable avx512 f32 brgconv

---

src/cmake/install_tbb.cmake

- In old TBB packages there are a lot of libraries for several archs, compilers:
```c++
ilyal@wanglei-nuc:~/Documents/Programming/build/openvino-release/tbb2017_20170807oss$ tree -L 2 lib/
lib/
├── ia32
│   ├── gcc4.1
│   ├── gcc4.4
│   └── gcc4.7
├── intel64
│   ├── gcc4.1
│   ├── gcc4.4
│   └── gcc4.7
└── mic
├── libtbb_debug.so
├── libtbb_debug.so.2
├── libtbbmalloc_debug.so
├── libtbbmalloc_debug.so.2
├── libtbbmalloc_proxy_debug.so
├── libtbbmalloc_proxy_debug.so.2
├── libtbbmalloc_proxy.so
├── libtbbmalloc_proxy.so.2
├── libtbbmalloc.so
├── libtbbmalloc.so.2
├── libtbb_preview_debug.so
├── libtbb_preview_debug.so.2
├── libtbb_preview.so
├── libtbb_preview.so.2
├── libtbb.so
└── libtbb.so.2
```
So, let's install only required ones.

Install only required TBB libraries

---

src/plugins/intel_gpu/src/runtime/layout.cpp

- updated `to_weights_format()` to convert `b_fs_yx_fsv16` to `o_is_yx_isv16`
- original PR: https://github.com/openvinotoolkit/openvino/pull/12599
- 89449

[GPU] adding weight format conversion rule for b_fs_yx_fsv16

---

.ci/azure/android_arm64.yml
.ci/azure/linux.yml
.ci/azure/linux_arm64.yml
.ci/azure/linux_conditional_compilation.yml
.ci/azure/linux_debian.yml
.ci/azure/mac.yml
.ci/azure/windows.yml
.ci/azure/windows_conditional_compilation.yml

Otherwise, even if python is failed, CPU tests are still running https://dev.azure.com/openvinoci/dldt/_build/results?buildId=368159&view=logs&jobId=982848f2-7f8d-5e57-730a-8df1e5f991ba

Azure: Try to take into account result of previous step as well

---

src/plugins/auto/plugin.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp
src/tests/functional/plugin/shared/include/behavior/plugin/core_integration.hpp

Update the logic to check if device priorities is set through the value of device priorities instead of no found in the config map.
Signed-off-by: Wang, Yang <yang4.wang@intel.com>
- Update logic that checking if the value of device priorities is empty
- 84420
- 89781

[MULTI]Fix the issue that QueryNetworkMultiThrows failed to pass

---

cmake/features.cmake

- Because it's targeted only for debian package support

Don't use system tbb for 2022.2

---

thirdparty/cnpy/cnpy.cpp

Avoid GCC compiling issue ‘ULLONG_MAX’ was not declared in this scope
Co-authored-by: Ilya Lavrenov <ilya.lavrenov@intel.com>
Co-authored-by: Ilya Churaev <ilya.churaev@intel.com>
- *#include <climits>*

Porting Update to add climits for ULLONG_MAX to 2022.2 (#11958)

---

cmake/developer_package/tbb/lnx/TBBConfig.cmake
cmake/developer_package/tbb/mac/TBBConfig.cmake
cmake/developer_package/tbb/win/TBBConfig.cmake
src/cmake/ie_parallel.cmake
src/cmake/install_tbb.cmake

- On U22 with oneTBB 2021.5 TBBBind is not present in debian packages, so we still need to use our prebuilt static tbbind 2.5
- See https://github.com/oneapi-src/oneTBB/issues/879
- CVS-89825

Use static TBBBind if dynamic one is not found

---

src/plugins/intel_gpu/src/runtime/layout.cpp

Porting GPU fix #12630 related to models failure in OVTF validation 
- CVS-89872

Port to 2022/2: updated to convert b_fs_yx_fsv16 to o_is_yx_isv16

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/src/graph/network.cpp

This change allows to apply surfaces_lock only in really "surface scenario" and reduces infer request time preparing in other cases

[GPU] Shared memory optimization for network::execute_impl() call

---

src/plugins/intel_gpu/src/plugin/ops/interpolate.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/interpolate.cpp
src/tests/functional/shared_test_classes/src/single_layer/interpolate.cpp

This PR fixes missed alignment between axes and scales in Interpolate operation in case of empty Axes input
- 89673

[GPU] Fix Interpolate missed axes values alignment with scales

---

src/plugins/intel_gpu/src/plugin/ops/transpose.cpp

- *Failed to compile yolo-v4-tf FP16-INT8 model on dGPU, error:*
```
cldnn program build failed! could not create a descriptor for a dilated convolution forward propagation primitive
```
- *There's FakeQuantize between Transpose and ConvertColor in FP16-INT8 model, it needs to trace back one more layer to find the ConvertColor*
- *89726*

[GPU] fix Transpose issue for ConvertColor with FakeQuantize.

---

src/core/tests/frontend/paddle/requirements_dev.txt
src/core/tests/models/onnx/onnx_prototxt_converter_requirements.txt
src/core/tests/requirements_test_onnx.txt
tools/mo/requirements.txt
tools/mo/requirements_caffe.txt
tools/mo/requirements_onnx.txt

- Backport of #12713 
- target branch: releases/2022/2

Backport of #12713 "MO uses the same version of protobuf like other packages"

---

tools/pot/openvino/tools/pot/graph/passes.py

(cherry picked from commit 0592ba3e8c143f9c016dbe2c4a8ad8b2b247e2fe)
- *Cherry-picked fix from the master for the POT. This fix is applicable for the transformer-like architecture models that contain MatMuls without weights*
- *For the details see original PR: [!12234](https://github.com/openvinotoolkit/openvino/pull/12234)*
- *89866*

[POT][OV 2022.2] fix: incorrect fq type (cherry-pick from #12234)

---

scripts/install_dependencies/install_NEO_OCL_driver.sh
scripts/install_dependencies/install_openvino_dependencies.sh

dropped python-dev as a redundant component
added option to install NEO drivers on UBI8.6

adjustments for 2022.2 release on rh platform

---

src/frontends/tensorflow/src/op/conv_2d_backprop.cpp
src/frontends/tensorflow/src/op/conv_3d_backprop.cpp

**Details:** With `end=-1` StridedSlice behaves unclear. It seems to include the latest element (slice) in case `end=-1` but it doesn't. The specification for StridedSlice has unclear items that were requested to resolve in ticket 90128
**Ticket:** 90101

[TF FE] Correct Deconvolution for NCHW layout

---

src/frontends/common/src/utils.cpp

when cpuFuncTest and libopenvino.so in sampe directory
on redhat8, cpuFuncTest can't find front library path
- *CVS-89941*

fix get frontend library path issue

---

src/bindings/python/wheel/CMakeLists.txt

- Remove obsolete list of dependencies for `ie_wheel`

Fixed ie_wheel build with disabled IE API 1.0

---

cmake/dependencies.cmake
cmake/features.cmake
src/cmake/ie_parallel.cmake

- If TBB is not found, cmake scripts automatically fallback to SEQ with explicit warning message
- CVS-90218

Use TBB as default threading

---

src/frontends/tensorflow/src/op/conv_3d_backprop.cpp

**Details:** It is a partial port from [PR-12764](https://github.com/openvinotoolkit/openvino/pull/12764) for `Conv3DBackpropInputV2`.

[TF FE] Fix translator for Conv3DBackpropInputV2

---

src/frontends/tensorflow/src/op/space_to_batch_nd.cpp

**Details:** According to the specification we must have the same type for block_shape and crops inputs.
**Ticket:** 90418

[TF FE] Fix BatchToSpace translator

---

src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
src/plugins/intel_gpu/src/plugin/ops/variable.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/memory.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/single_layer_tests/memory.h
src/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/memory.hpp
src/tests/functional/shared_test_classes/src/single_layer/memory.cpp

Enable v3 operations for GPU plugin.
Add single-layer tests for v3 operations (disabled until v3 reference implementation is fixed).

[GPU] Assign-3/ReadValue-3 for GPU plugin

---

cmake/developer_package/version.cmake

- Port of https://github.com/openvinotoolkit/openvino/pull/12521
- Additionally `CI_BUILD_NUMBER` can really specify just a build number as integer, so it will be used as `IE_VERSION_BUILD`
- EISW-41342

Added version generation as in CI (#12521)

---

src/plugins/intel_cpu/src/nodes/reduce.cpp
src/plugins/intel_cpu/src/nodes/reduce.h

- *After [default enable avx512 f32 brgconv](https://github.com/openvinotoolkit/openvino/pull/12619)  being merged, there will be performance regression for reducing both Height and Width of nspc layout, this PR optimize these cases.*
- *88527*

[CPU] Reduce node improve performance for nspc layout

---

src/bindings/python/src/compatibility/ngraph/utils/types.py
src/bindings/python/src/openvino/runtime/utils/types.py

**Details:** NumPy import raises a warning about deprecated type np.bool in 1.20 release.
**Ticket:** 90079

[Python API] Port from the master - Replace deprecated NumPy type np.bool (#12786)

---

cmake/developer_package/version.cmake

Ported https://github.com/openvinotoolkit/openvino/pull/12840 to master
Changes: allow to use `CI_BUILD_NUMBER` as really ci build number

Ported changes related to versiong handling

---

src/frontends/tensorflow/src/op/space_to_batch_nd.cpp

**Details:** According to the specification we must have the same type for block_shape and crops inputs
**Ticket:** 90418

[TF FE] Port changes from 2022.2 - Fix BatchToSpace translator

---

src/plugins/intel_gpu/src/plugin/device_config.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/behavior/ov_executable_network/get_metric.hpp
src/tests/functional/plugin/shared/src/behavior/ov_infer_request/io_tensor.cpp

- Skipped SqueezeUnsqueezeLayerTest due to unsupported dimensions size (8D)
- Skipped OVInferRequestIOTensorTest due to unsupported tensor reshaping (in case of bigger shape) of default allocator in AUTO_BATCH Plugin
- Fixed InferStaticNetworkSetOutputTensor. nightly_OVClassGetMetricTest,nightly_OVClassHeteroExecutableNetworlGetMetricTest and nightly_OVClassGetMetricTest
- *ticket-id*

[GPU] GPU Plugin functional tests fixes

---

src/frontends/tensorflow/src/pass/transpose_sinking.cpp
src/frontends/tensorflow/tests/transpose_sinking.cpp

**Details:** Prelu operation is not simple unary operation so it requires a separate pass with handling different cases: a scalar slope, 1D slope, ND slope, etc. Now it covers a case with a scalar slope that is sufficient to quickly enable OVTF model.
**Ticket:** 90409
Signed-off-by: Kazantsev, Roman [roman.kazantsev@intel.com](mailto:roman.kazantsev@intel.com)

[TF FE] Port changes from 2022.2 branch - Add Transpose Sinking for Prelu operation

---

src/frontends/tensorflow/src/op/fake_quant_min_max_vars.cpp
src/frontends/tensorflow/src/op_table.cpp

**Details:** Avoid extra transposes in conversion of FakeQuantWithMinMaxVars and add translator FakeQuantWithMinMaxVarsPerChannels. It allows to convert MobileNetV2 with FakeQuantWithMinMaxVars and FakeQuantWithMinMaxVarsPerChannels operations.
**Ticket:** 89081

[TF FE] Support MobileNetV2 with FakeQuantize by TF FE

---

src/frontends/tensorflow/src/pass/transpose_sinking.cpp
src/frontends/tensorflow/tests/transpose_sinking.cpp

**Details:** Prelu operation is not simple unary operation so it requires a separate pass with handling different cases: a scalar slope, 1D slope, ND slope, etc. Now it covers a case with a scalar slope that is sufficient to quickly enable OVTF model.
**Ticket:** 90409

[TF FE] Add Transpose Sinking for Prelu operation

---

tools/mo/openvino/tools/mo/front/tf/loader.py

In model BiT-M-R50x1 'inputs' field is not set which caused failing of input indices determining and failing of TF2 import. So MO tries to import model as TF1 model and in this case model is not frozen properly.
Solution: Add check that 'inputs' is not None.
Ticket: 90495
Code:
Validation:
Documentation:

Fixed error in indices processing.

---

src/frontends/tensorflow/src/op/broadcast_args.cpp
src/frontends/tensorflow/src/op/broadcast_to.cpp
src/frontends/tensorflow/src/op/bucketize.cpp
src/frontends/tensorflow/src/op/einsum.cpp
src/frontends/tensorflow/src/op/reduce.cpp
src/frontends/tensorflow/src/op/unary_op.cpp
src/frontends/tensorflow/src/op_table.cpp

**Details:** Implemented for parity with MO legacy for TF. Add loaders: EuclidianNorm, Erf, Bucketize, BroadcastTo, BroadcastArgs, Einsum, Mish.

[TF FE] Add loaders: EuclidianNorm, Erf, Bucketize, BroadcastTo, BroadcastArgs, Einsum, Mish

---

cmake/developer_package/compile_flags/os_flags.cmake
thirdparty/onnx/CMakeLists.txt

- 3.6 mb versus 3.9 w/o the change
- *ticket-id*

Enabled LTO for ONNX

---

src/common/low_precision_transformations/include/low_precision/network_helper.hpp
src/common/low_precision_transformations/src/network_helper.cpp
src/common/low_precision_transformations/src/shuffle_channels.cpp
src/common/low_precision_transformations/src/split.cpp
src/common/low_precision_transformations/src/transpose.cpp
src/tests/functional/inference_engine/lp_transformations/pad_transformation.cpp
src/tests/functional/inference_engine/lp_transformations/reshape_transformation.cpp
src/tests/functional/inference_engine/lp_transformations/shuffle_channels_transformation.cpp
src/tests/functional/inference_engine/lp_transformations/split_transformation.cpp
src/tests/functional/inference_engine/lp_transformations/strided_slice_transformation.cpp
src/tests/functional/inference_engine/lp_transformations/transpose_transformation.cpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/common/builders.cpp

- *MoveDequantizationBefore/After: SubtractConvert shape computation added before propagation through operation*
- *NormalizeDequantizationShape: changed default value for the 'convertIsExpected' parameter in order to avoid errors in case of convert before subtract constant*
- NetworkHelper::makeDequantizationSubtract added to avoid precision inconsistency between dequantization subtract constant and data
- *Functional tests added*
- *86419*
- *88993*

[LPT] Fixes for the cases with convert before subtraction constant

---

samples/cpp/benchmark_app/inputs_filling.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
tools/benchmark_tool/openvino/tools/benchmark/main.py
tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py
tools/benchmark_tool/openvino/tools/benchmark/utils/utils.py

- There is a model which can get 2x speedup with this patch due to very slow gemm_ref kernel in cldnn.
- Added f64 support to c++ benchmark_app. Python version doesn't work due to issue 91169
- Fixed scalar inputs handling in python benchmark_app 
- Aligned input layout infer logic between c++ and python benchmark_app

[GPU] Use oneDNN gemm on DG2 in some cases

---

src/plugins/intel_gpu/include/intel_gpu/primitives/implementation_desc.hpp
src/plugins/intel_gpu/src/graph/impls/implementation_map.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/activation.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/adaptive_pooling.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/bucketize.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/roll.cpp

Now we have issue on declaring new primitive impl, when build depends on include order,  where
`#include "primitive_base.hpp"`
should be always before
`#include "impls/implementation_map.hpp"`
to pass the windows build.
This PR fixes this dependency in build

[GPU] Fix implementation map includes to fix the dependency

---

src/bindings/python/tests/test_runtime/test_compiled_model.py
thirdparty/CMakeLists.txt

- On U22 imported configuration is named as `NONE` instead of `NOCONFIG`. Let's request imported configuration name and use it later instead of hardcoded name

Fixed installation of pugixml on U22 for ie_wheel

---

src/frontends/tensorflow/src/op/identity.cpp
src/frontends/tensorflow/src/op/normalize_l2.cpp
src/frontends/tensorflow/src/op/reverse_sequence.cpp
src/frontends/tensorflow/src/op/top_k.cpp
src/frontends/tensorflow/src/op_table.cpp

**Details:** Add translators for NormalizeL2, ReverseSequence, IdentityN and refactor for TopK.
**Ticket:** CVS-91393

[TF FE] Add translators for NormalizeL2, ReverseSequence

---

src/plugins/auto/plugin.cpp

- fix performance gap between MULTI:CPU vs. CPU
- multi use stream executor for async load, this will unexpectedly affect CPU stream executor tbb config, we had workaround in auto, and now apply same to MULTI
- 91302

fix inconsistent tbb config due to executor used in multi

---

src/plugins/intel_gpu/src/plugin/infer_request.cpp

- Fix the new infer request to set output memory normally during enqueue stage for performance regression issue
- Fix to use the generated outputsMap instead of graph API to retrieve outputID
- *ticket-id*

[GPU] Fix the new infer request to set output memory normally during enqueue stage

---

src/plugins/intel_gpu/src/graph/graph_optimizer/trim_to_outputs.cpp
src/plugins/intel_gpu/src/graph/include/pass_manager.h
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/pass_manager.cpp

- Marks are needed in several passes only (graph traversal only), but it's mark itself is a node field and we clean them after each pass. So this patch removes marks cleanup from common pass manager code and moves it only to passes which requires it. May provide ~2-3% load time gain for some models

[GPU] Removed mark field from program_node

---

src/plugins/intel_gpu/src/graph/CMakeLists.txt
src/plugins/intel_gpu/src/kernel_selector/CMakeLists.txt
src/plugins/intel_gpu/src/runtime/CMakeLists.txt
src/plugins/intel_gpu/tests/CMakeLists.txt

- Diff in sizes (smaller is with more LTO, collected with gcc-10):
```
-rwxr-xr-x 1 root root 19468168 9月   5 01:08 libopenvino_intel_gpu_plugin.so
-rwxr-xr-x 1 root root 20770720 9月   5 00:59 libopenvino_intel_gpu_plugin.so
```

enabled LTO for GPU plugin helper libs

---

src/plugins/intel_gpu/src/graph/reshape.cpp
src/plugins/intel_gpu/src/plugin/graph.cpp
src/plugins/intel_gpu/tests/shape_infer/reshape_si_test.cpp

- Return `output_partial_shape` if input layout is dynamic
- Additional checks for static/dynamic layout in reshape
- Get rid of TensorDesc usages for exec graph construction

[GPU] Minor fix for dynamic reshape

---

samples/cpp/benchmark_app/inputs_filling.cpp

Fixes incorrect random input generation for `benchmark_app` for `I8` precision.

[benchmark_app] Fix I8 input random generation

---

src/plugins/intel_gpu/src/graph/impls/ocl/strided_slice.cpp
src/plugins/intel_gpu/src/graph/include/strided_slice_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/graph/strided_slice.cpp
src/plugins/intel_gpu/tests/test_cases/strided_slice_gpu_test.cpp

- removed unused get_default_format_for_dim method
- Moved strided_slice utils from header to cpp
- Added WA into is_dynamic check and update_shape method to handle strided_slice primitives with non-constant begin/end/stride which may happen in dynamic models.
- Fixed output rank of dynamic strided slice prim

[GPU] Fix strided_slice for dynamic cases

---

src/plugins/intel_gpu/include/intel_gpu/plugin/program.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/tile.cpp
src/plugins/intel_gpu/src/plugin/ops/tile.cpp
src/plugins/intel_gpu/src/plugin/program.cpp

- Added search for any dynamic op in the the model which may set allow_new_shape_infer build option
- Modified tile op factory to avoid reshape for dynamic or new shape infer cases
- Added proper alignment of input shape in tile impl
- Always return use partial shape in reorder shape infer

[GPU] Tile fix for dyn flow

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/lru_cache.hpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/test_cases/fully_connected_gpu_test.cpp

- Use LRU cache for weight reorder kernels. Since primitive_impl is not created for that case, we introduce separate cache object which operates with `kernel::ptr`.
- *90373*

[GPU] Weights reorder cache

---

src/plugins/intel_gpu/src/graph/impls/ocl/softmax.cpp

- Performance regression happens in mobilenet v1 after PR(https://github.com/openvinotoolkit/openvino/pull/12467). Network compiler changed from reorder+Softmax opt kernel to Softmax ref kernel which supports blocked format. And  it caused performance regression
- Removed blocked format support in Softmax ref kernel until fix.
- *ticket-id*

[GPU] Disable blocked format support in Softmax

---

src/frontends/common/include/openvino/frontend/extension/conversion.hpp
src/frontends/common/src/extension/conversion.cpp
src/frontends/tensorflow/include/openvino/frontend/tensorflow/extension/conversion.hpp
src/frontends/tensorflow/src/extension/conversion.cpp

**Details:** On MacOS there is problem with RTTI when all class definitions are put into the header file. For this reason, for example, OVTF can't register `ConversionExtension` into TF FE.
**Ticket:** 91854

[Frontend, TF FE] Fix RTTI for ConversionExtension on MacOS

---

.ci/azure/linux_debian.yml

**Details:** Fixing error "Cannot load library libtest_builtin_extensions_1.so libopenvino_tensorflow_fe.so"

[ONNX FE Tests] Fix ONNX FE tests on Debian

---

docs/nbdoc/consts.py

Porting:
https://github.com/openvinotoolkit/openvino/pull/12750/
There are newly generated files (since 30.08.2022) that seem to be fine but apparently "latest" is not build in the docs:
https://repository.toolbox.iotg.sclab.intel.com/projects/ov-notebook/0.1.0-latest/20220913220807/dist/rst_files/
The question remains, why is it so?

Porting: Change notebooks fetching link for documentation

---

docs/nbdoc/consts.py

Porting:
#12750
There are newly generated files (since 30.08.2022) that seem to be fine but apparently "latest" is not build in the docs:
https://repository.toolbox.iotg.sclab.intel.com/projects/ov-notebook/0.1.0-latest/20220913220807/dist/rst_files/
The question remains, why is it so?

Porting: Change notebooks fetching link for documentation #12750

---

tools/pot/openvino/tools/pot/api/samples/object_detection/README.md

A small fix for a broken link to MobileNetV1 FPN model in "Quantizing Object Detection Model with Accuracy Control" article.

DOCS: Fixing link to MobileNetV1 FPN for 22.2

---

docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md

A small fix for a broken admonition.

DOCS: Fixing note admonition in Converting a PyTorch RNN-T Model for 22.2

---

docs/OV_Runtime_UG/ov_infer_request.md

Fixing missing "Examples of Infer Request Usages" heading in "Infer Request" article.

DOCS: Fixing missing heading in Infer Request for 22.2

---

docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Paddle.md

A small fix for a broken link to PaddleClas for MobileNet v3 model.

DOCS: Fixing broken link to PaddleClas for 22.2

---

docs/ovsa/ovsa_get_started.md

Fixing links returning 404 and missing header.
Download for Ubuntu 18.04.05 is not working anymore, as it was replaced with 18.04.06 version. New hyperlink leads to general 18.04 download page. 
This issue has been raised before in https://github.com/openvinotoolkit/openvino/pull/12495#discussion_r942587118

DOCS: Security Add-On Fix for 22.2

---

src/plugins/intel_gpu/include/intel_gpu/plugin/async_infer_request.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/async_infer_request_legacy.hpp
src/plugins/intel_gpu/src/plugin/async_infer_request.cpp
src/plugins/intel_gpu/src/plugin/async_infer_request_legacy.cpp
src/tests/functional/plugin/gpu/remote_blob_tests/cldnn_remote_blob_tests.cpp
src/tests/functional/plugin/gpu/remote_blob_tests/gpu_remote_tensor_tests.cpp

- Use default sync pipeline for queue sharing case when request.infer() is called
- Fixes #13099

[GPU] Fix infer() for queue sharing case

---

src/tests/functional/plugin/conformance/subgraphs_dumper/src/main.cpp

Fixed incorrect behavior in case incorrect arguments are passed or in case some arguments are missed.
Otherwise SubgraphDumper is failing silently.

Fixed incorrect behavior in case incorrect arguments are passed

---

src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp

[ARM plugin] Fix ARM tests (case bf16)

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/detection_output/detection_output_kernel_ref.cpp

detection_output kernel support cross-type(fp16/fp32), so graph-optimization also support croos-type detection_output
- *87095*

[GPU] Support corss-data type from detection output

---

src/plugins/intel_gpu/src/graph/network.cpp

- This patch fixes performance regressions caused by moving surfaces_lock::create() under additional condition
- 92044

[GPU] Fix performance regression caused by surfaces_lock::create()

---

docs/MO_DG/prepare_model/customize_model_optimizer/Extending_Model_Optimizer_with_Caffe_Python_Layers.md

Fixing link to pre-compute Faster-R-CNN detectors which was accidentally broken in #11605

[DOC] Fix link to pre-computed FRCNN detectors for Caffe model

---

docs/MO_DG/prepare_model/customize_model_optimizer/Extending_Model_Optimizer_with_Caffe_Python_Layers.md

Port from https://github.com/openvinotoolkit/openvino/pull/13133
Fixing link to pre-compute Faster-R-CNN detectors for 22.2

DOCS: Fix link to pre-computed FRCNN detectors for Caffe model for 22.2

---

src/plugins/intel_gpu/src/graph/graph_optimizer/set_required_layouts.cpp

This might happen unnecessarily because of unsupported primitive, such as asymmetric weights.
This is causing unittest failure in next-gen GPU.

[GPU] Ignore exception that happens during layout querying

---

cmake/extra_modules.cmake

- Cmake `if` operator cannot check if file exists using relative paths https://cmake.org/cmake/help/latest/command/if.html#file-operations

Allow to extra modules by relative path

---

src/plugins/intel_gpu/src/graph/include/reduce_inst.h
src/plugins/intel_gpu/src/graph/reduce.cpp
src/plugins/intel_gpu/tests/shape_infer/reduce_si_test.cpp

- *Add calc_output_layouts which returns vector type*
- *Use ngraph shape infer to calculate output layout*
- *91202*

Reduce to use ngraph shape infer at calc_output_layouts

---

docs/OV_Runtime_UG/hetero_execution.md
docs/OV_Runtime_UG/supported_plugins/GPU.md
docs/OV_Runtime_UG/supported_plugins/GPU_RemoteTensor_API.md

- There is a user encountered the https://github.com/openvinotoolkit/openvino/issues/12570of decreasing the accuracy of the model when setting the affinity of operations. So we added some prompts to the document, hoping to avoid the same problem for users again.
- Some spelling errors.

Docs: Update the doc on how to manually set operations affinity & fix some spelling errors

---

src/bindings/python/tests/mock/mock_py_frontend/src/frontend_wrapper.cpp

Solves compilation issue if either of TF or Paddle frontend is disabled while tests are on.
#13198

[Python] Add compilation control to python test FE mocks

---

src/cmake/openvino.cmake

pkg-config support --validate option after 0.29, for pkg-config less than 0.29, use --exist option to validate .pc files
CVS-92902

Fix unknown --validate option with pkg-config lower than 0.29

---

src/core/include/openvino/opsets/opset.hpp
src/core/src/itt.hpp
src/core/src/opsets/opset.cpp
src/core/tests/conditional_compilation/ngraph_cc_collect.cpp
src/core/tests/conditional_compilation/ngraph_cc_off.cpp
src/core/tests/conditional_compilation/ngraph_cc_on.cpp

- for `cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_CLDNN=OFF -DENABLE_TESTS=OFF -DENABLE_SAMPLES=ON -DENABLE_PYTHON=OFF -DENABLE_IR_V7_READER=OFF -DENABLE_TEMPLATE=OFF -DENABLE_INTEL_VPU=OFF -DENABLE_OV_ONNX_FRONTEND=OFF -DENABLE_OV_PADDLE_FRONTEND=OFF -DENABLE_OV_IR_FRONTEND=ON -DENABLE_OV_TF_FRONTEND=OFF -DENABLE_SSE42=OFF -DENABLE_AVX2=OFF -DENABLE_AVX512F=OFF -DENABLE_INTEL_GNA=ON -DENABLE_INTEL_CPU=OFF -DENABLE_GAPI_PREPROCESSING=OFF -DENABLE_MULTI=OFF -DENABLE_AUTO=OFF -DENABLE_INTEL_MYRIAD=OFF -DENABLE_INTEL_MYRIAD_COMMON=OFF -DENABLE_AUTO_BATCH=OFF -DENABLE_HETERO=OFF -DENABLE_FASTER_BUILD=ON -DENABLE_PROFILING_ITT=OFF -DSELECTIVE_BUILD=ON -DSELECTIVE_BUILD_STAT=<some.csv> -DBUILD_SHARED_LIBS=OFF ..` CMake options there is a binary size **decrease …

Apply CC to ov::OpSet

---

docs/ovsa/ovsa_get_started.md

Fixing links returning 404 and missing header.
Download for Ubuntu 18.04.05 is not working anymore, as it was replaced with 18.04.06 version. New hyperlink leads to general 18.04 download page.
Port from https://github.com/openvinotoolkit/openvino/pull/13087

DOCS: Security Add-On Fix port to master

---

src/common/transformations/CMakeLists.txt

This is a temporary workaround for fatal error LNK1248: image size (1004722F6) exceeds maximum allowable size (FFFFFFFF). The symbolic debugging information will be stored in a separate .pdb file.
- *91401*

Change debug information format from Z7 to Zi for transformation library on Windows

---

README.md

Update badge in main README to 2022.2 release
The "Github checks" and "Public CI" badges don't link to anything (if you click on them you just get an image of the badge). It would be nice if they can be updated with links too.

Update version badge in README to 2022.2

---

src/plugins/intel_gpu/src/graph/graph_optimizer/set_required_layouts.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/concatenation_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/deconvolution_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/pooling_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/impls/onednn/reduction_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/reorder_onednn.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Use impl_params instead of program_node in some parts
- Simplified impls registration
- Removed program_node reference from onednn base impl class and replaced with engine ref
- Some fixes in layout optimizer for dynamic bert base via onednn
- Fixed primitives synchronization for in-order queues before shape inference
- *85556*

[GPU] Fixes for onednn-based impls for dynamic models

---

src/plugins/intel_cpu/src/nodes/kernels/registers_pool.hpp
src/plugins/intel_cpu/src/utils/cpu_utils.hpp
src/plugins/intel_cpu/tests/unit/registers_pool.cpp

The RegistersPool class was implemented. It is helpful for managing registers while developing jit kernels.
This is done as the first part of the Gather JIT kernel improvement to cover all execution cases.

[CPU] The registers pool implementation for JIT kernels.

---

src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/reorder.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/conv_sum_broadcast.cpp

- *Convolution: descriptor creation is fixed for case of static add after dynamic convolution*
- *Reorder: createPrimitive is fixed for case with static input and dynamic output shapes*
- *82665*

[CPU] Fixes for static postops after dynamic convolutions

---

src/bindings/c/tests/ov_compiled_model_test.cpp
src/bindings/c/tests/ov_core_test.cpp
src/bindings/c/tests/ov_infer_request_test.cpp
src/bindings/c/tests/ov_model_test.cpp
src/bindings/c/tests/ov_preprocess_test.cpp

- Remove unnecessary assert to keep test going on even it reports failure 
- Keep reasonable assert to avoid segment fault
- *ticket-id*

[CAPI]Remove unreasonable assert in test cases

---

src/common/transformations/src/transformations/common_optimizations/split_concat_pair_to_interpolate_fusion.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/split_concat_pair_to_interpolate_fusion_test.cpp
tools/mo/openvino/tools/mo/front/common/partial_infer/utils.py

**Details:** It fixes a case when Split goes with disconnected output port. For this case, this transformation must not be applied.
**Ticket:** 91813

[MO, Common] Fix SplitConcatPairToInterpolateFusion transformation

---

src/plugins/intel_gpu/src/graph/impls/ocl/resample.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/test_cases/resample_gpu_test.cpp

- add bs_fs_yx_bsv16_fsv16 format to interpolate. 
- fix unit tests to check blocked inputs and outputs/ not reordered to plane
- 90556

[GPU] Add bs_fs_yx_bsv16_fsv16 format to interpolate. 

---

src/common/transformations/src/transformations/control_flow/unroll_if.cpp
src/tests/functional/inference_engine/transformations/control_flow/unroll_if_test.cpp

Fixes case when input node to a an If operator has multiple outputs itself.
Ticket: 93116

Use Output<Node> of If inputs to replace its body parameters in UnrollIf

---

src/plugins/intel_gna/gna_model_serial.cpp
src/plugins/intel_gna/gna_model_serial.hpp
src/plugins/intel_gna/gna_plugin.cpp
src/tests/unit/gna/gna_export_import_test.cpp
src/tests/unit/gna/gna_model_serial_test.cpp

- Add OV version (eg hash commit) to GNA export format file (using wg/rg flag).
- Add GNA Lib version to GNA export format file (using wg/rg flag).
- Enable version printing for speech_sample demo only when log mode is set to LOG_DEBUG
- 86924

[GNA] Add OV & GNA versions to GNA export file

---

src/bindings/python/src/openvino/_offline_transformations/__init__.py
src/bindings/python/src/openvino/offline_transformations/__init__.py
src/bindings/python/src/pyopenvino/core/offline_transformations.cpp
src/bindings/python/tests/test_transformations/test_offline_api.py
src/common/transformations/include/transformations/common_optimizations/fused_names_cleanup.hpp
src/common/transformations/src/transformations/common_optimizations/fused_names_cleanup.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/fused_names_cleanup.cpp
tools/mo/openvino/tools/mo/back/offline_transformations.py
tools/mo/openvino/tools/mo/moc_frontend/serialize.py
tools/mo/openvino/tools/mo/utils/check_ie_bindings.py

- *MO runs MOC transformation pipeline which insert fused_names into the runtime info of operations. This names should not cross boundaries of our API and be visible in IR.*
- *91551*, *91782*

[MO] cleanup fused names after all transformations

---

src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/mat_mul.cpp

- This patch fixes incorrect feature's dimension size selection in case of transposed `shape_a`
- 92959

[GPU] Fix reshape shape calculation for MatMul operation

---

tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py

- OpenCV module is now optional when using benchmark app - it will be imported only when images are provided in the console.
- 88029

[BENCHAMRK_APP/PYTHON] CV2 module required only when loading images

---

src/plugins/intel_gpu/src/graph/impls/ocl/resample.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/resample/resample_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/core/cl_kernels/resample_ref.cl
src/plugins/intel_gpu/src/plugin/ops/interpolate.cpp
src/plugins/intel_gpu/tests/test_cases/resample_gpu_test.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/interpolate.cpp

- added support linear onnx mode for 5d formats
- added support blocked formats
- added single layer tests for linear onnx formats
- added linear onnx unit test for planar and blocked 5d formats 
- 89816

[GPU] added 5d supporting to interpolate onnx and tests

---

tools/benchmark_tool/openvino/tools/benchmark/main.py
tools/benchmark_tool/openvino/tools/benchmark/utils/statistics_report.py
tools/benchmark_tool/openvino/tools/benchmark/utils/utils.py

When ProfilingInfo was bound by pybind11, those entries turned into
Python timedelta objects. This caused two problems:
1. There was a division by 1000 to go to milliseconds. This caused a lot
of precision lost, because `timedelta(microseconds=2300)/1000.0 =
timedelta(2)` and `timedelta(microseconds=33) = timedelta(0)`.
2. When converting those timedelta objects to str, the output is in the
form of (HH:MM:SS.XXXXXX). This is not very useful microsecond based
performance counters.
This change simply reverts everything to printing plain microsecond
based integers.

Fix benchmark perf counter stats output

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp

Reproduced in yolo_v5s.int8
Add OV_GPU_DisableOnednnOptPostOps in debug_configuration
- *92276*

[GPU] Fix endless loop issue in onednn optimization post-opt

---

.ci/azure/mac.yml

- Disable IR frontend tests to fix Mac CI
- *ticket-id*

Fix Mac CI. Disable ir frontend tests

---

src/frontends/ir/tests/frontend_test_basic.cpp

- Temporary disable because it fails on CI on ubuntu 18.04
- CVS-94211

Disable v9 test

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- Optimize reorder (with b_fs_yx_fsv32 -> byxf format conversion ) in case if it is placed after Permute
- 93866

[GPU] Optimize reorder between permute and first convolution

---

src/cmake/openvino.cmake

- Otherwise, cmake incorrectly computes TBB_DIR in OpenVINOConfig.cmake
- Fix for https://github.com/openvinotoolkit/openvino_contrib/pull/447

Fixed arm cross compilation build with custom TBB

---

src/plugins/intel_cpu/src/nodes/kernels/rdft_kernel.cpp

- To fix the issue one should change VEX "vmovq" instruction to universal "uni_vmovq", which will be automatically replaced with "movq" in case of SSE https://github.com/openvinotoolkit/openvino/blob/270051ebcef7639a89e4f5fc73d6c38b5aa120ef/src/plugins/intel_cpu/src/nodes/kernels/rdft_kernel.cpp#L164
BTW, it is better to change all the SIMD mnemonics with uni_* versions to avoid known VEX to nonVEX encoding switch, which has substantial performance penalty on modern platforms.
- CVS-93107

Fixed RDFT under Rosetta

---

src/core/dev_api/dimension_tracker.hpp
src/core/include/openvino/core/validation_util.hpp
src/core/shape_inference/include/compare.hpp
src/core/shape_inference/include/concat_shape_inference.hpp
src/core/src/op/concat.cpp
src/core/src/validation_util.cpp
src/core/tests/CMakeLists.txt
src/core/tests/evaluate_bound/concat.cpp
src/core/tests/op_eval/concat.cpp
src/core/tests/type_prop/concat.cpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference.cpp
src/plugins/intel_cpu/tests/unit/shape_inference_test/concat_shape_inference_test.cpp

- Add template implementation of Concat shape inference
- Extend testing to label evaluation
- Extend type prop test for PartialShape and interval/dynamic dimensions
- Add no label checker in validation util
- 90596
- 90693
- 90730
- 90767
- 90878
- 90915

Review opset1 concat for shape inference aspects

---

cmake/extra_modules.cmake

- Before this change https://github.com/openvinotoolkit/openvino/pull/13476/files we use `InferenceEngine::` namespace of targets in Developer package. Now, we use `openvino::` and it conflicts with our own `ALIAS`es and we need to check whether target exists or not.

Fixing OpenVINO extra modules usage

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/infer_request.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/graph.cpp
src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/plugins/intel_gpu/src/plugin/ops/parameter.cpp
src/plugins/intel_gpu/src/plugin/ops/result.cpp
src/plugins/intel_gpu/src/plugin/ops/rnn.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp

- Implemented several fixes for infer request in dynamic scenarios and enabled several behavior tests.
- allocate_input/output methods now create empty blob for dynamic inputs/outputs
- blob ptr is not replaced after allocation (reallocation of internal memory happens instead)

[GPU] Fixes for infer request impl in dynamic cases

---

tests/lib/CMakeLists.txt

- OSX builds both release and debug. Currently, openvino.pc files are valid only for Release.
- CVS-94395

Fixed stress_tests on OSX in debug mode

---

.ci/azure/mac.yml
docs/snippets/src/main.c

- change `ov_output_const_port_t` to `ov_output_port_t`, for fixing mac build error.
- 94497

[C API DOC] fix mac doc build error caused by ov_output_const_port_t

---

tools/compile_tool/main.cpp

- compile_tool, when using OV API 2.0, should parse the iop, iol and ioml parameters list, read the tensors inputs and outputs, and try to match the user provided list with the tensor information and apply the right precision, layout and model layout
- this is happening right now, except that there's an assert at the end of every user provided name, to verify whether it was found and applied or not
- the assert right now seems backwards, and it actually asserts when it finds the name rather than when it doesn't find it
- 94496

Fixing assert when handling iop, iol and ioml in compile tool

---

docs/requirements.txt

missing ipython component is causing incorrect highlighting for notebook code in sphinx documentation

fix documentation building including notebooks

---

src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/layers/gna_layer_type.hpp
src/plugins/intel_gna/src/ops/identity.cpp
src/plugins/intel_gna/src/ops/identity.hpp
src/plugins/intel_gna/src/ops/util/util.hpp
src/plugins/intel_gna/src/transformations/insert_identity_layer.cpp
src/plugins/intel_gna/src/transformations/insert_identity_layer.hpp
src/plugins/intel_gna/src/transformations/reorder_activation_and_pooling.cpp
src/plugins/intel_gna/src/transformations/rt_info/gna_precision_change_flag.cpp
src/plugins/intel_gna/src/transformations/rt_info/gna_precision_change_flag.hpp
src/plugins/intel_gna/tests/unit/transformations/gna_insert_identity_layer.cpp

- *Rewrite InsertIdentityLayerPass using ngraph (legacy pass is kept until unaligned split and concat will be moved to ngraph*
- *Rewrite BreakFusingOfOutputLayersPass using ngraph*
- *52111*
- *52112*

[GNA] Insert identity using ngraph transformation

---

src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp

reorder_input has the issue when using generated reorder case. 
And handle_reshape has only handle 4 dims (bfyx), so support 5, 6 dimes
- *93114*

[GPU] Fix brain-tumor-segmentation-002/INT8/onnx running failed

---

.github/workflows/py_checks.yml
src/bindings/python/src/openvino/runtime/ie_api.py
src/bindings/python/src/openvino/runtime/utils/types.py
src/bindings/python/tests/test_runtime/test_type.py

- Python 3.6 is no longer supported. The linter should be ran on a higher version.
- 94540

[PyOV] Upgrade linter Python version

---

tools/mo/openvino/tools/mo/middle/RNNSequenceNormalizeToIE.py

- *output pattern of Reshape is simplified to avoid dependance of LSTM constant on data input shape*
- *79127*
With original behavior model looks like this:

Simplify Reshape inserted while converting RNN from mxnet

---

src/bindings/python/wheel/CMakeLists.txt
tools/openvino_dev/CMakeLists.txt

- During cross-compilation python uses platform tags from build python, while we need to use from host-python one. In order to fix this, we track libc version as well as architecture and create our own platform tag
- The same for OSX where can we compile for target macOS (min version) and use different architecture than python one. E.g. default python provides universal2 as architecture, while we need arch64

Added post-processing for python wheel platform tags

---

cmake/developer_package/ncc_naming_style/ncc_naming_style.cmake

If ENABLE_NCC_STYLE=OFF, the check for ncc.py still happens. A confusing warning is reported and a redundant setting of ENABLE_NCC_STYLE to OFF is done.
Check that ENABLE_NCC_STYLE is enabled before looking for ncc.py
Signed-off-by: Tom Rix <trix@redhat.com>
- *item1*
- *...*
- *ticket-id*

check if ncc is enabled before looking for ncc.py

---

thirdparty/CMakeLists.txt

Static gflags is not available on Fedora, leading to a configure error.  So use the shared version.
Signed-off-by: Tom Rix <trix@redhat.com>
- *item1*
- *...*
- *ticket-id*

Use shared gflags on Fedora

---

src/core/shape_inference/include/strided_slice_shape_inference.hpp
src/core/tests/type_prop/strided_slice.cpp

**Details:** In case non-constant begin, end, or strides with shrink axes, shape inference for StridedSlice is incorrect and it just outputs a shape of the input rank with all dynamic dimensions.
This case is met in the MUSE model.
**Ticket:** 94730

[Core] Correct shape inference for StridedSlice with non-const begin

---

src/common/snippets/src/pass/collapse_subgraph.cpp
src/plugins/intel_cpu/src/emitters/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/convert.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/eltwise.cpp
src/plugins/intel_cpu/tests/functional/test_utils/fusing_test_utils.hpp
src/tests/ie_test_utils/common_test_utils/ov_tensor_utils.cpp

- Correct integer computations for arithmetic operations
- Disable snippets tokenization for I32 precision 
- Extend Eltwise single layer tests to cover I32
- Changed test results check logic to enable bit-exact comparison
- *CVS-93903*

[CPU] Fixed integer compute for arithmetic operations

---

docs/IE_PLUGIN_DG/PluginTesting.md

A minor fix that corrects indentation of snippets.

DOCS: Fixing indentation in Plugin Testing - for 22.2

---

src/plugins/intel_gpu/src/graph/resample.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_opt.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_opt.cpp
src/plugins/intel_gpu/src/plugin/ops/interpolate.cpp
src/plugins/intel_gpu/tests/test_cases/resample_gpu_test.cpp
src/plugins/intel_gpu/tests/test_utils/test_utils.cpp
src/plugins/intel_gpu/tests/test_utils/test_utils.h
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/interpolate.cpp

Performance optimization for 5d ONNX linear blocked formats for f32/16 and u8/i8 types:
- adjusting interpolate/resample GPU implementation for supporting u8/i8
- adjusting resample opt kernels implementations to support new features
- wrote performance tests as unit tests

[GPU] optimized 5d linear_onnx and nearest mode and tests

---

src/bindings/python/requirements_test.txt
src/core/tests/CMakeLists.txt
src/core/tests/type_prop/gather.cpp

- Fix warnings as error on windows build for gather type prop tests.
- Fix ngraph ONNX CI added pytest-forked

Fix gather type_prop test build issue on windows

---

src/plugins/intel_cpu/src/emitters/cpu_generator.cpp
src/plugins/intel_cpu/src/nodes/bin_conv.cpp
src/plugins/intel_cpu/src/nodes/color_convert.cpp
src/plugins/intel_cpu/src/nodes/common/cpu_convert.cpp
src/plugins/intel_cpu/src/nodes/common/permute_kernel.cpp
src/plugins/intel_cpu/src/nodes/common/softmax.cpp
src/plugins/intel_cpu/src/nodes/def_conv.cpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/extract_image_patches.cpp
src/plugins/intel_cpu/src/nodes/fake_quantize.cpp
src/plugins/intel_cpu/src/nodes/input.cpp
src/plugins/intel_cpu/src/nodes/interpolate.cpp
src/plugins/intel_cpu/src/nodes/kernels/gather_uni_kernel.cpp
src/plugins/intel_cpu/src/nodes/kernels/rdft_kernel.hpp
src/plugins/intel_cpu/src/nodes/kernels/registers_pool.hpp
src/plugins/intel_cpu/src/nodes/mha.cpp
src/plugins/intel_cpu/src/nodes/mvn.cpp
src/plugins/intel_cpu/src/nodes/non_max_suppression.cpp
src/plugins/intel_cpu/src/nodes/normalize.cpp
src/plugins/intel_cpu/src/nodes/reduce.cpp
src/plugins/intel_cpu/src/nodes/region_yolo.cpp
src/plugins/intel_cpu/src/nodes/roi_align.cpp
src/plugins/intel_cpu/src/nodes/roi_pooling.cpp
src/plugins/intel_cpu/src/nodes/topk.cpp
src/plugins/intel_cpu/src/utils/jit_kernel.cpp
src/plugins/intel_cpu/src/utils/jit_kernel.hpp
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.cpp
src/plugins/intel_cpu/tests/unit/jit_kernel_test.cpp

Moving to the recent oneDNN 2.7 release
Note:
- xbyak submodule was updated in order to avoid build conflicts with oneDNN xbyak (which is a part of the oneDNN sources).
oneDNN uses 6.051 version as a baseline. Openvino version is updated to 6.06, since 6.051 has an issue with getting cpu isa using static variables
oneDNN branch:
- https://github.com/openvinotoolkit/oneDNN/tree/v2.7_for_ie_master_migration
Ticket:
- 81373

[CPU] Move to oneDNN 2.7

---

src/plugins/intel_gpu/src/graph/reshape.cpp

-  Fix reshape calc_output_layout failure in squeeze shape_infer test.
Failure: Comparing reshape->output_shape with a new tensor() object was not working as intended.
Since the original intention was to check whether cldnn::tensor type output_shape is set or not,
so replaced the comparision to use size of the output_shape.
- 95329

[GPU] Fix reshape calc_output_layout failure in squeeze shape_infer test.

---

src/plugins/intel_gna/src/frontend/layer_quantizer.hpp
src/plugins/intel_gna/src/frontend/scale_factor_calc.hpp
src/plugins/intel_gna/src/gna_graph_compiler.cpp
src/plugins/intel_gna/src/gna_graph_patterns.hpp
src/plugins/intel_gna/src/gna_graph_tools.hpp
src/plugins/intel_gna/src/layers/gna_convolution_layer.cpp
src/plugins/intel_gna/src/layers/gna_crop_layer.cpp
src/plugins/intel_gna/src/layers/gna_crop_layer.hpp
src/plugins/intel_gna/src/layers/gna_layer_info.hpp
src/plugins/intel_gna/src/optimizer/gna_pass_manager.cpp
src/plugins/intel_gna/tests/functional/pass_tests/convolution_crop_axis_h.cpp
src/plugins/intel_gna/tests/unit/gna_get_crop_params.cpp

- Support Slice/Crop layer along H axis after Convolution, The GNA convolution layout is NHWC (N==1) therefore H is in fact the first dimension (i.e., the mayor one in terms of memory address)
- 93393

[GNA] Support Slice/Crop layer along H axis after Convolution

---

samples/cpp/speech_sample/utils.hpp

- Simplify speech_sample to remove `float getGnaFrequencyMHz()` function, since it should no longer be needed when GNA Plugin reports perf counters in time domain instead cycles.
- GNA library was updated from 1455->1815 (while 1455 was not providing perf counter in time domain, but 1815 does) (https://github.com/openvinotoolkit/openvino/pull/13188)
- 58361

[SAMPLES] Remove unneeded GNA clock multiplier in performance counters

---

cmake/packaging/debian.cmake

- Added suppression for debian ubu18 description-starts-with-package-name error
- 89401

Suppress openvino_latest ubu18 lintian error

---

src/bindings/c/src/CMakeLists.txt
src/bindings/c/src/ov_infer_request.cpp

Signed-off-by: Zhai <xuejun.zhai@intel.com>
- warning caused by `size_t` assign to `int`
- 95167

[C API] fix warning as error issue for C API

---

docs/IE_PLUGIN_DG/Building.md

Minor fixes that correct indentation of code snippets and note admonitions.

DOCS: Fixing indentation in Build Plugin Using CMake - for 22.2

---

samples/cpp/speech_sample/main.cpp
samples/cpp/speech_sample/utils.hpp

Remove port assertion in speech_sample when importing the GNA format model
- When user selects output (from CLI on speech_sample) there is no need to always assert it to contain port number
- Specifying port number is not needed in the use case where GNA model is imported, as the exported GNA model may not contain the port number
- Simplify parsing, extract few functions
- 95273

[SAMPLES] [GNA] Remove port assertion in speech_sample when importing

---

src/plugins/intel_cpu/CMakeLists.txt

Enabled exceptions for Xbyak in Debug build
Depends on [Add support for exceptions during code generation](https://github.com/openvinotoolkit/oneDNN/pull/146)

Added -DDNNL_ENABLE_EXCEPTIONS for Debug build

---

docs/install_guides/installing-model-dev-tools.md

Port of changes from https://github.com/openvinotoolkit/openvino/pull/13348 to 22.2.
Details:
* Rewrote the introductory section to give more explanation of what OpenVINO Dev Tools is
* Added "For Python Developers" and "For C++ Developers" sections in the introduction to explain the difference in the install process
* Changed the existing "For Python Developers" section to "Installing OpenVINO Development Tools"
* In Step 4, added a Sphinx tab to provide different instructions for Python and C++ users. Python users install using pip install openvino-dev, while C++ install using requirements.txt files. (C++ can alternatively install using pip install openvino-dev, but must be careful to use the right version.)
* In Step 5, added a sentence to tell users to visit the Troubleshooting page …

DOCS: Rewrite "Install OpenVINO Development Tools" page - port to 22.2

---

src/plugins/intel_gpu/src/graph/concatenation.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/concat_input_order.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_infer_request/infer_request_dynamic.cpp

- Error happens when node.is_dynamic() is called but its input nodes' output layouts are not valid yet. 
- Fixed to check output_layout.is_dynamic() instead of is_dynamic() of the node itself.

[GPU] Fix error in calling is_dynamic

---

tools/pot/setup.py

- Bumpy `torch` to 1.12 since lower versions use `onnx.optimizer` which has been deprecated and trying to import it in CIs throws errors.
- 95233

[POT] Bump torch version to 1.12

---

tools/mo/openvino/tools/mo/ops/slice.py
tools/mo/openvino/tools/mo/utils/ir_reader/layer_to_class.py
tools/mo/unit_tests/mo/ops/slice_test.py

- *Slice in MO is different from Slice in openvino opset, but it is not serialize into IR it converts to `StridedSlice`.*
- *When MO IR Reader reads `Slice` from IR it uses shape inference from `Slice` in MO*
Solution: For backward combability and to limit changes in legacy MO we introduce new operation `OvSlice`. This operation will be used by MO IR Reader.
Ticket: *95071*
Code:
* [*]  Comments
* [*]  Code style (PEP8)
* [*]  Transformation generates reshape-able IR
* [*]  Transformation preserves original framework node names
* [*]  Transformation preserves tensor names
Validation:
* [*]  Unit tests
* [*]  Framework operation tests
* [*]  Transformation tests
* [*]  Model Optimizer IR Reader check
Documentation:
* [*]  Supported frameworks operations list
* [*] …

Fix Slice issue in MO IR Reader

---

src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.h

- Set subgroup size as 16 when out batch size != 1
- 94734

[GPU] Fix performance degradation of bfyx conv with FP16 compared to FP32

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/device_info.hpp
src/plugins/intel_gpu/src/graph/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp

- remove overhead of is_local_block_io_supported by using cache_dir
- Add device name to hash_value generation in kernel cache
- query a device supports is_local_block_io_supported while set_option in program
- 92893

[GPU] Reduce overhead in device_query

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- in_fmt:bfyx, out_fmt:b_fs_yx_fsv16, bs_fs_yx_bsv16_fsv16
- fuse reorder to first shallow input conv
- 94643

fuse reorder to next conv

---

src/plugins/intel_gpu/include/intel_gpu/primitives/select.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/select.cpp
src/plugins/intel_gpu/src/graph/include/select_inst.h
src/plugins/intel_gpu/src/graph/select.cpp
src/plugins/intel_gpu/src/plugin/ops/select.cpp
src/plugins/intel_gpu/tests/shape_infer/select_si_test.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/select.cpp

- *Add calc_output_layouts() using ngraph shape infer for Select OP*
- *Add unittests to test broadcast_types such as none, numpy, and pdpd*
- *Modify to get AutoBroadcastSpec instead of getting simple broadcast string in API*
- *Add gpuFuncTest using dynamic shapes*
- *94474*

[GPU] Update Select Op to use ngraph shape infer

---

src/plugins/intel_cpu/src/ngraph_transformations/snippets_mark_skipped.cpp

- *Fixed dynamism unsafe `isSuitableChildForFusingMatMul` check in `SnippetsMarkSkipped`*
- *N/A*

[Snippets] Fixed isSuitableChildForFusingMatMul for dynamic case

---

docs/install_guides/installing-model-dev-tools.md
docs/install_guides/installing-openvino-overview.md

Porting:
https://github.com/openvinotoolkit/openvino/pull/13830/
Details:
Edit install-openvino-overview.md to list 3 options for installing OpenVINO, with Installing OpenVINO Development Tools being the recommended option for new users

DOCS: Edits to streamline Install OpenVINO Overview Page - port to 22.1

---

src/tests/functional/inference_engine/caching_test.cpp

- Fixed crash in the destructor of ov::Model after the caching test
- 95614

Fix caching tests

---

src/common/util/src/file_util.cpp

Some filesystem does not return dt_type properly. (such as sshfs) Without this fix, openvino fails to search frontend when mounted on sshfs.

Handle DT_UNKNOWN as DT_REG during file list-up

---

docs/install_guides/configurations-for-iei-card.md
docs/install_guides/configurations-for-intel-gna.md
docs/install_guides/configurations-for-intel-gpu.md
docs/install_guides/configurations-for-ivad-vpu.md
docs/install_guides/configurations-for-ncs2.md
docs/install_guides/configurations-header.md
docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-conda.md
docs/install_guides/installing-openvino-linux-header.md
docs/install_guides/installing-openvino-linux.md
docs/install_guides/installing-openvino-macos-header.md
docs/install_guides/installing-openvino-macos.md
docs/install_guides/installing-openvino-windows-header.md
docs/install_guides/installing-openvino-windows.md
docs/install_guides/installing-openvino-yum.md

Porting changes from:
https://github.com/openvinotoolkit/openvino/pull/13829 to 22.1
Details:
Changing "Intel Distribution of OpenVINO Toolkit" to "OpenVINO Runtime".

DOCS: Update for consistent usage of OpenVINO Runtime - port to 22.1

---

src/plugins/intel_gpu/src/kernel_selector/kernels/eltwise/eltwise_kernel_base.cpp

LWS is adjusted to make items are fetched along batch axes in a workgroup if a layout has bsv32 or bsv16
- added if block for creating LWS for batch blocked layout
- 96189

[GPU] Eltwise adjusted LWS for batch-blocked format

---

src/common/low_precision_transformations/src/markup_precisions.cpp

Fix building error due missing header `<ngraph/opsets/opset5.hpp>` introduced by following two PRs:
- https://github.com/openvinotoolkit/openvino/pull/12981 added `opset5::LSTMSequence` as follow: https://github.com/openvinotoolkit/openvino/blob/71c23489c6265e1f678a4dbc0e194e4ffc82c990/src/common/low_precision_transformations/src/markup_precisions.cpp#L223
- https://github.com/openvinotoolkit/openvino/pull/13469 removed `#include <ngraph/opsets/opset5.hpp>`

Add missing opset5 header for LSTMSequence in LPT

---

src/bindings/python/tests/test_utils/test_utils.py

- Replace `.` with `_` so file extension won't be misread.
- *N/A*

[PyOV] Fix typo in filename generator

---

tests/layer_tests/onnx_tests/test_prelu.py

- *After changing Caffe2 to ONNX RT https://github.com/openvinotoolkit/openvino/pull/13759 per channel broadcast stopped working for slope inputs. This PR modify slope inputs according to numpy broadcast.*
- *Removed opset6 tests as it is not supported by the ONNX RT*

[MO TESTS] PReLU tests fix

---

src/plugins/intel_gpu/src/plugin/plugin.cpp
src/tests/functional/shared_test_classes/src/base/layer_test_utils.cpp

- Return fully specified name from QueryNetwork to ensure device ID is not lost in hetero scenario
- 
- 96122

[GPU] Fixed device name in query network result

---

src/bindings/python/tests/test_runtime/test_compiled_model.py
src/bindings/python/tests/test_runtime/test_core.py
src/bindings/python/tests/test_runtime/test_function.py
src/bindings/python/tests/test_runtime/test_infer_request.py
src/bindings/python/tests/test_runtime/test_tensor.py
src/bindings/python/tests_compatibility/__init__.py
src/bindings/python/tests_compatibility/test_inference_engine/test_Blob.py
src/bindings/python/tests_compatibility/test_inference_engine/test_ExecutableNetwork.py
src/bindings/python/tests_compatibility/test_inference_engine/test_InferRequest.py
src/bindings/python/tests_compatibility/test_ngraph/test_convolution.py
src/bindings/python/tests_compatibility/test_ngraph/test_if.py
src/bindings/python/tests_compatibility/test_utils/test_utils.py

- `test_utils.py` file in the `tests_compatibility` folder used the new API instead of old one that caused this issue.
- add absolute import instead of relative one.
- 86384

[PyOV] Fix compatibility if-ops test

---

src/common/legacy/src/graph_transformer.cpp
src/tests_deprecated/unit/inference_engine_tests/util_const_infer_test.cpp

https://jira.devtools.intel.com/browse/CVS-89635
OVTF faced issue with new clusters that work fine on CPU.
**Old cluster:**
**Recent clusters with issues:**
`removeConstLayers` removes Const layers, including `StatefulPartitionedCall/StatefulPartitionedCall/bert_pack_inputs/PartitionedCall/RaggedConcat/RaggedFromTensor_1/RaggedFromUniformRowLength/RowPartitionFromUniformRowLength/range/delta` which is used later, so we need to keep it.
Fails here:
```
if (data->_usage == DataUsage::Output) {
IE_ASSERT(data->_producerEdge != nullptr);
}
```

[MyriadX][CVS-89635] - ovtf data->_producerEdge != nullptr - fix

---

src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp
src/plugins/intel_gpu/tests/fusions/deconvolution_fusion_test.cpp

- exception: could not create a primitive descriptor
- fusings_gpu/deconv_actv_eltw_actv.basic/20
- fusings_gpu/deconv_scale_actv_quant_u8_eltw_scale_actv_quant_i8.basic/8
- count of fused primitive not matched
- fusings_gpu/conv_scale_activation_eltwise_fp32_quantize_i8.basic/4
- fusings_gpu/conv_int8_eltwise_scale_onednn.u8_eltwise_prod_out_reuse/0
- fusings_gpu/deconv_actv_eltw_actv.basic/20
- 8947
- fusings_gpu/deconv_scale_actv_quant_u8_eltw_scale_actv_quant_i8.basic/8
- 8947
- fusings_gpu/conv_scale_activation_eltwise_fp32_quantize_i8.basic/4
- Fusing behavior is different with cldnn.
- fusings_gpu/conv_int8_eltwise_scale_onednn.u8_eltwise_prod_out_reuse/0
- Invalid testcase for current onednn.
- 67491

[GPU][DG2] Skip/Disable some tests in Conv/Deconv

---

src/frontends/onnx/frontend/src/op/constant_of_shape.cpp
src/frontends/onnx/tests/models/constant_of_shape_empty_init.prototxt
src/frontends/onnx/tests/models/constant_of_shape_null_node.prototxt
src/frontends/onnx/tests/onnx_import.in.cpp

- According to the ONNX standard ConstantOfShape with empty tensor input should lead to the scalar output shape.
- https://github.com/openvinotoolkit/openvino/issues/13970

[ONNX] ConstantOfShape with empty tensor input

---

docs/snippets/gpu/context_sharing_va.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_command_queues_builder.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.hpp

- Currently all devices w/o OOO queue support are rejected. This patch changes this policy and just use in-order queue in such cases

[GPU] Allow devices which don't support OOO queue

---

tests/layer_tests/tensorflow_tests/test_tf_ParallelDynamicStitch.py

- *we support DynamicStitch via decomposition to subgraph with ScatterUpdate op, but ScatterUpdate has undefined behavior if there are multiple identical indexes. Fix tests
- *96452*

Fix DynamicStitch tests

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Checked iterators are enabled in Windows Debug builds, and cannot be converted to 'void *'.
- This patch changes the memory accessor from `begin()` to `data()`.
- 96522

[GPU] updated memory accessor

---

src/plugins/intel_gpu/include/intel_gpu/plugin/infer_request.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/engine.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.hpp
src/tests/functional/plugin/gpu/concurrency/gpu_concurrency_tests.cpp
src/tests/ie_test_utils/common_test_utils/data_utils.hpp
src/tests/ie_test_utils/functional_test_utils/include/functional_test_utils/blob_utils.hpp

- The intention of these changes is to avoid incorrect memory re-usage between user's memory (`_inputs` or `_outputs` ) and device's memory (`_deviceInputs` or `_deviceOutputs`) for USM Host type in case of swapping blobs between infer requests. Here is example:
```
...
// If USM memory is supported, then input_tensors(1,2) will be allocated with USM Host type; and device's inputs will
// be allocated on top of this buffers (for avoiding internal memory copy between user's memory and
// device's memory)
auto input_tensor1 = infer_request1.get_input_tensor();
auto input_tensor2 = infer_request2.get_input_tensor();
...
// Fill tensors input_tensor(1,2) with data
...
infer_request1.set_input_tensor(input_tensor2);
infer_request2.set_input_tensor(input_tensor1);
// Buffers swapping will lead …
```

[GPU] Move device memory allocation from preprocessing stage to runtime for usm memory type

---

src/tests/unit/auto/auto_property_test.cpp

- *disable  smoke_AUTO_SetPropertyOverwriteTestNoThrow and smoke_MULTI_SetPropertyOverwriteTestNoThrow due to blocking CI*
- *96846 *

disable SetPropertyOverwriteTestNoThrow for MULTI and AUTO

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

+ Do not select a planar format if keep_dims is false and blocked axis is reduced.
- *item1*
- *...*
- 96096

[GPU] Modify perferred format of Blocked axis reduction

---

samples/cpp/benchmark_app/main.cpp
tools/benchmark_tool/openvino/tools/benchmark/main.py

This reverts commit f893a58816c8c84e91541f5ba9f249154d59dfa2.
- *Reverts https://github.com/openvinotoolkit/openvino/pull/13402*
- *ticket-id*

Revert "[BENCHMARK_APP] Show input command in output (#13402)"

---

cmake/developer_package/compile_flags/os_flags.cmake
src/core/tests/CMakeLists.txt
src/frontends/onnx/tests/CMakeLists.txt
src/tests_deprecated/unit/CMakeLists.txt

It might not be available in some cross-toolchains.
Extract the code for switching to gold linker into separate CMake utility function to avoid duplication between multiple CMake scripts.

Avoid gold linker usage in case of cross-compilation

---

src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/src/backend/gna_limitations.hpp
src/plugins/intel_gna/src/gna_graph_compiler.cpp
src/plugins/intel_gna/src/gna_graph_compiler.hpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/layers/gna_convolution_layer.cpp
src/plugins/intel_gna/src/layers/gna_convolution_layer.hpp
src/plugins/intel_gna/src/transformations/split_convolution_with_large_buffer_size.cpp
src/plugins/intel_gna/tests/functional/pass_tests/conv_with_padding.cpp
src/plugins/intel_gna/tests/functional/pass_tests/convert_padded_to_valid_conv.cpp
src/plugins/intel_gna/tests/functional/pass_tests/decompose_2d_conv.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/conv_low_precision.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/skip_tests_check.hpp

- Provide support for 1DConvolution with padding on GNA 3.5
- Starting from GNA 3.5, GNA Library supports all convolutions (1D & 2D) using CNN 2D GNA model API (NHWC tensors having H==1).
- Simple mapping from CNN 2D to 1D is not needed as 2D CNN are supported natively in GNA 3.5.
- 93535

[GNA] Add 1DConv validator for GNA 3.5

---

src/bindings/python/tests/test_graph/test_create_op.py
src/bindings/python/tests_compatibility/test_ngraph/test_create_op.py

-  Restore and align tests for Unique PythonAPI
With the Unique-10 reference implementation PR, shape inference for the third output was improved, 
so the tests need alignment.
The tests were previously removed to unblock CI: https://github.com/openvinotoolkit/openvino/pull/14102
- N/A

[Unique-10] Restore and align tests for Unique PythonAPI

---

src/plugins/intel_gpu/src/plugin/ops/result.cpp
src/plugins/intel_gpu/src/plugin/program.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/split.cpp

-  Currently split/variadic split op is splitted to multiple crops. So the user node should use the crop's first output

[GPU] Fix dynamic shape accuracy issue w.r.t crop 

---

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/deconvolution/deconvolution_kernel_b_fs_zyx_fsv16.cpp
src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp

- In some cases jitter could throw an error about unsupported mixed layouts for eltwise due to planar layout of extra input while output had blocked format. This patch modifies add_required_reorder pass to insert reorders after between const and fused primitive to match output layout when broadcast is not possible.
- *94983*

[GPU] Insert reorder for eltwise const dependency

---

src/common/util/CMakeLists.txt
src/common/util/include/openvino/util/shared_object.hpp
src/common/util/src/os/lin/lin_shared_object_loader.cpp
src/common/util/src/os/win/win_shared_object_loader.cpp
src/inference/src/ie_core.cpp

Ignore LD_LIBRARY_PATH / PATH or other unsafe places for security purposes
- CVS-96201

Load plugins strictly by absolute paths

---

tools/mo/openvino/tools/mo/utils/cli_parser.py
tools/mo/unit_tests/mo/utils/cli_parser_test.py

Regressing after changing of layout parsing in MO. Reg exp waits for input names which consist from only word characters, while input names may contain slashes or dots. 
Solution: 
Update reg exp to include slashes or dots.
Ticket: 
Code:
Validation:
Documentation:

Fixed layout parsing.

---

tools/mo/openvino/tools/mo/utils/ir_engine/ir_engine.py

Solution: 
Ticket: 97172
Code:
Validation:
Documentation:

Fix for MO IR reader loading old meta data.

---

src/bindings/python/src/pyopenvino/graph/partial_shape.cpp

During converting models with while loops subgraphs are copied using deepcopy() method.
Such subgraphs have attributes with PartialShape type which fail on deepcopy, because PartialShape does not have __deepcopy__() method. 
Solution: define __copy__() and __deepcopy__() methods for PartialShape.
Ticket: 96984
Code:
Validation:
Documentation:

copy() and deepcopy() methods for PartialShape.

---

src/plugins/intel_gpu/include/intel_gpu/graph/serialization/layout_serializer.hpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp

- Reduced the range of min max values ​​for the test case `conv_int8_scale_shift_swish`
- `kernel_impl_params` should be serialized before `primitive_impl`
- 97193

[GPU] GPU serialization fix

---

tools/mo/openvino/tools/mo/__main__.py
tools/mo/openvino/tools/mo/mo.py
tools/mo/openvino/tools/mo/mo_caffe.py
tools/mo/openvino/tools/mo/mo_kaldi.py
tools/mo/openvino/tools/mo/mo_mxnet.py
tools/mo/openvino/tools/mo/mo_onnx.py
tools/mo/openvino/tools/mo/mo_paddle.py
tools/mo/openvino/tools/mo/mo_tf.py
tools/mo/openvino/tools/mo/utils/telemetry_utils.py

Telemetry library checks if it is in main process or not. If the process is not main, it does not show dialog. Which caused dialog stop to show in MO, which runs conversion in subprocess.
Solution: Initialize telemetry library before running subprocess with conversion.
Ticket: 97035
Code:
Validation:
Documentation:

Added telemetry initialization before running main subprocess.

---

.ci/azure/linux_debian.yml

Since GNA isn't a part of Debian package, no need to run tests on it
- *item1*
- *...*
- *ticket-id*

Filter out samples tests on GNA for Debian

---

src/core/reference/include/ngraph/runtime/reference/gather.hpp
src/plugins/template/tests/functional/op_reference/gather.cpp

Gather-8 conformance tests crash on the line https://github.com/openvinotoolkit/openvino/blob/master/src/core/reference/include/ngraph/runtime/reference/gather.hpp#L54
because of the out of bound index values.
But according to specification Gather-8 for out of bound indices should fill with zeros  https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/movement/Gather_8.md?plain=1#L148-L156
Added check for out of bound, added filling with zeros and added unit-test for that case
- xxx-96723

fix out of bound indices of Gather reference

---

src/core/tests/type_prop/unique.cpp

- Remove braces around scalar initializer to fix android-arm64 postcommit check
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=434314&view=logs&j=92ba3447-fcaa-530d-6438-b829fe1e7d1d&t=b0a91e75-8666-5718-e63e-df215ecb48f9&l=2845
- N/A

Remove braces around scalar initializer - android-arm64 post-commit check

---

src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_base_event.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_event.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_user_event.hpp
src/plugins/intel_gpu/tests/module_tests/usm_memory_test.cpp

- Fixed incorrect `copy_from()` function usage without processing output events, which may cause incorrect synchronization in some cases
- Fixed OpenCL events usage obtained from `ocl::ocl_event` class. Previously `ocl::ocl_event::get()` returns `cl::Event` by value and any usage of this `cl::Event` not affected underlying `cl::Event` of `ocl::ocl_event` object
- Added explicit `blocking = true` parameter for `memory::copy_*()` functions
Note: should be merged after https://github.com/openvinotoolkit/openvino/pull/13697
- *96647*

[GPU] Add explicit blocking option for copy_*() functions

---

src/bindings/python/tests/test_graph/test_core.py

Description: 
Added copy() and deepcopy() tests for PartialShape.
Leftover after PR: https://github.com/openvinotoolkit/openvino/pull/14136
Ticket: 96984
Code:
Validation:
Documentation:

copy() and deepcopy() tests for PartialShape.

---

src/core/shape_inference/include/pad_shape_inference.hpp
src/core/tests/type_prop/pad.cpp

**Details:** Pad shape infer logic is adapted to NCWH layout and it expects to pad only spatial dimensions based on its logic.
**Ticket:** 95067

[Core] Fix Pad shape inference for Edge and Reflect modes

---

src/plugins/intel_cpu/src/nodes/tensoriterator.cpp
src/plugins/intel_cpu/src/nodes/tensoriterator.h
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/loop.cpp

- *If input body shape is changed after execution, it means that the execution influences shapes. Thus, for these cases we should always reset this input shape after execution even if `Loop`/`TI` has the same input shapes, the same input data to have correct (not-changed) input shape for the next InferRequest (execution). For example, it's a valid case when body has explicit concatenation Result. This PR adds check for that we really need to reshape changed input shapes of body*
- *You can see more details (code example)  here #13922*
- *90554*

[CPU] Fixed dynamic Loop with explicit Concat Result

---

src/plugins/intel_cpu/src/memory_desc/cpu_memory_desc_utils.h
src/plugins/intel_cpu/src/nodes/rnn.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/augru_sequence.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/gru_sequence.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/lstm_sequence.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/rnn_sequence.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/softmax.cpp

- oneDNN requires particular input / output ports to have bf16 precision
for bf16 primitive
- 96975
- 97265
- 97068

[CPU] Fix ports configuration for bf16 RNN primitives

---

src/plugins/intel_gpu/include/intel_gpu/plugin/internal_properties.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp

- To check blob compatibility, a new internal property `ov::intel_gpu::driver_version` is added.
- `ov::device::architecture` is updated according to Intel® graphics processor table
- https://dgpu-docs.intel.com/devices/hardware-table.html
- 95408

[GPU] GPU driver version and architecture properties

---

docs/snippets/CMakeLists.txt
samples/cpp/benchmark_app/CMakeLists.txt
samples/cpp/benchmark_app/remote_tensors_filling.cpp
samples/cpp/benchmark_app/remote_tensors_filling.hpp

- In case if  GPU plugin build is disabled, OCL is installed and found, but opencl.hpp is not present snippets and benchmark_app could cause build errors due to attempt to include "opencl.hpp". This patch changes corresponding cmake files to look for opencl.hpp instead of cl2.hpp as code contains `#define OV_GPU_USE_OPENCL_HPP` before ocl wrapper include.
- *96814*

[GPU] Replace cl2.hpp with opencl.hpp in cmake search for docs and BA

---

src/plugins/intel_gna/src/gna_graph_compiler.cpp
src/plugins/intel_gna/src/layers/gna_convolution_layer.cpp
src/plugins/intel_gna/src/layers/gna_convolution_layer.hpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/convolution.cpp

[GNA] Fix 2D->1D mapping of Convolutions where transpose BTW H and W is not applicable
- Only convolution with a single channel may be subject to filters transposition BTW H and W (see https://github.com/openvinotoolkit/openvino/pull/9474)
- New tests added to verify 78578 (kernel size equal to input size with multiple input/filter channels)
- 78578

[GNA] Fix 2D->1D mapping of Convolutions

---

src/common/low_precision_transformations/include/low_precision/fake_quantize.hpp
src/common/low_precision_transformations/src/assign_and_read_value.cpp
src/common/low_precision_transformations/src/fake_quantize.cpp
src/common/low_precision_transformations/tests/fuse_fake_quantize_transformation.cpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/fuse_fake_quantize_function.cpp

- *element-wise fuse operations extension to support `updatePrecisions`*
- *95943*

LPT: element-wise ops fuse extension to support updatePrecisions

---

src/plugins/intel_gpu/src/graph/reshape.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/strided_slice.cpp

- add using output_partial_shape in calc_output_layout of reshape primitive
- add single layer test of strided_slice for the fix. input shape and op attributes from real model(XLNET_IMDB)
- 95822

[GPU] add using output_partial_shape in calc_output_layout of reshape primitive

---

tools/mo/openvino/tools/mo/ops/scatter.py
tools/mo/unit_tests/mo/ops/scatter_test.py

Root cause analysis: In case of dynamic value in `updates` of `ScatterUpdate` the value infer was incorrect, it was producing value `-1000000007` instead of dynamic value.
Solution: In case of masked array as `updates` produce masked array as value in value infer.
Ticket: 96978
Code:
Validation:
Documentation:

Fix value infer for ScatterUpdate in case of dynamic value in updates

---

src/core/src/interval.cpp
src/core/tests/dimension.cpp

- During interval multiplication we exceed int64_max if values are large. E.g. interval (2, 4611686018427387904) multiplied with 2 (e.g. in BtS, StB, and other ops) gives interval (4, 922337203685477580**8**) interval exceed int64_max value (int64_max = 922337203685477580**7**)
- Added a check if `a*b > int64_max`. Since direct calculation `a * b` will result in overflow, we can hack a little bit and check if `a > int64_max / b`. Mathematically they are equivalent but computationally in the latter case no overflows happen since `a, b > = 0 and a, b <= int64_max`
- xxx-93369

fix Interval multiplication when result exceeds int64_max

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

+ Remove reorder fusing condition for oneDNN execution of permute
Signed-off-by: byungilm <byungil.min@intel.com>
- *item1*
- *...*
- 95932

[GPU] Modify can_fuse_reorder for permute

---

src/plugins/intel_gpu/include/intel_gpu/plugin/remote_context.hpp
src/plugins/intel_gpu/src/plugin/remote_context.cpp

- When RemoteContext was removed earlier than RemoteTensors, we had invalid memory access in some cases on attempt to free device memory. This patch add engine shared ptr to RemoteBlobImpl to guarantee that it's not freed.

[GPU] Retain engine ptr in RemoteBlob impl

---

src/plugins/intel_gna/src/gna_device.cpp
src/plugins/intel_gna/src/gna_device.hpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/log/log.hpp

- GNA text model description will be exported for log levels >= DEBUG (not only for DEBUG level)
- GNA allocations will be exported for log level >=TRACE (not only for DEBUG level)
- 97849

[GNA] Fix log level settings to control exporting of diagnostic info

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/src/graph/compilation_context.cpp
src/plugins/intel_gpu/src/graph/include/compilation_context.hpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- each network now has compilation queue and thread worker for processing of that queue. 
- When we have impl cache miss in dynamic flow, and shape agnostic impl is used, we put static version of that kernel into compilation queue to accelerate next iterations with the same shape.

[GPU] Async static kernels compile for dynamic flow

---

cmake/features.cmake
src/tests_deprecated/behavior/CMakeLists.txt
src/tests_deprecated/behavior/vpu/CMakeLists.txt
src/tests_deprecated/behavior/vpu/myriad_tests/aot_behavior_tests.cpp

cmake: removed global definitions for plugins

---

src/plugins/intel_cpu/CMakeLists.txt

Two oneDNN changes in scope of single PR
- Add option to only explicitly disable XBYAK_NO_EXCEPTION
To make sure it is not implicitly enabled
- ITT fix for lib loading on windows
Cherry-pick commit from oneDNN without any conflicts
oneDNN PR:
- https://github.com/openvinotoolkit/oneDNN/pull/166
- *ticket-id*

[CPU] Add option to disable XBYAK_NO_EXCEPTION and fix itt win lib load

---

src/plugins/intel_gpu/src/graph/impls/ocl/reduce.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Some kernels (such as reduce_kernel_b_fs_yx_fsv16, deconvolution_kernel_b_fs_zyx_fsv16) assume that input memory is initialized to zero.
- These kernels force memory initialization by setting the `can_reuse_memory` flag to false.
- This PR serializes the memory initialization flag.
- 57672

[GPU] Serialize GPU memory reuse flag

---

src/common/transformations/src/transformations/common_optimizations/convert_compression_only_to_legacy.cpp
src/core/tests/dimension.cpp

Details:
- replaced `get_element_type` with `get_output_element_type` with explicit out port 0 and check if it's Const
- more readable unit-test for out of bound Interval multiplication: instead of `9223372036854775806`, `4611686018427387903`, ... used  `ov::Interval::s_max - 1` , `ov::Interval::s_max / 2` and so on
- xxx-91832, xxx-93369

Leftovers: safer get_output_types ConvertCompressedOnlyToLegacy, more readable Interval unit-tests

---

src/common/low_precision_transformations/include/low_precision/network_helper.hpp
src/common/low_precision_transformations/src/network_helper.cpp
src/common/low_precision_transformations/tests/CMakeLists.txt
src/common/low_precision_transformations/tests/subgraph/src/fq_decomposition_with_shared_constants.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fuse_conv_fq_with_shared_constants.cpp
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.cpp
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.hpp

- *FQ decomposition modified to create FQ with the constants that have only one consumer. This FQ representation is more affordable for further plugin optimizations*
- *97477*

[LPT] FQ Decomposition improvement

---

src/core/src/op/fake_quantize.cpp
src/core/tests/eval.cpp

- Set output tensor shape in FakeQuantize operator. It solve issue when output tensor has not set shape because of dynamic input when operator created. The output shape can be evaluated when do inference on input data which have got set shapes.
- 97870

Set out tensor shape in FakeQuantize evaluate

---

samples/cpp/benchmark_app/main.cpp
samples/cpp/common/utils/include/samples/common.hpp

- Align performance counters (PC) flag output with reports statistics
- Bug caused by dividing long long by 1000 (int) vs 1000.0 (double)
- 81376

[BENCHMARK_APP/C++] Align performance counters and report output

---

src/plugins/intel_gna/src/frontend/layer_quantizer.cpp
src/plugins/intel_gna/src/frontend/layer_quantizer.hpp
src/plugins/intel_gna/src/frontend/scale_factor_calc.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/conv_low_precision.cpp

- Fix scale factor calculation for convolution layers with int8 weights
- Fix tests for the above layer type.
- 97011

[GNA] Fix scale factor calculation for int8 convolution weights

---

src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/log/log.hpp
src/plugins/intel_gna/tests/unit/log/logger.cpp

- Fix GNA Plugin logger log level initialization order
- Clean-up GnaLog class
- 97849

[GNA] Fix logger initialization order

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/graph/reshape.cpp
src/plugins/intel_gpu/tests/passes/prepare_buffer_fusing_test.cpp

- Fixed one bert version which had an exception due to attempt to set not allocated input buffer in static FC due to optimized out dynamic reshape

[GPU] Fix exception for dyn reshape followed by static node

---

src/plugins/intel_cpu/src/nodes/rnn.cpp

- Previously this test crashed with 'out-of-bounds' segmentation fault
- *92404*

Unbreak LSTMCell-1 conformance test by adding missing descriptor

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- avoid can_fuse_reorder_to_prev() when detection_output  is cldnn::impl_type::cpu
- 92967

[GPU] avoid can_fuse_reorder_to_prev() for detection_output cpu impl

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp

- Each cache entry consumes around ~20KB. So 10000 * 20KB ~= 200 MB in total per cache 
-

[GPU] Reset in memory cache capacity to 10000 instead of infinite value

---

src/plugins/intel_gpu/src/graph/impls/onednn/pooling_onednn.cpp

Because pooling to use ngraph shape infer, extend 1D to 2D logic moved ngraph_opt to cldnn_pooling. This change has side-effect in onednn pooling, onednn pooling also doesn't support 1D.
- *98051*

[GPU] Fix text-to-speech-en-multi-0001-duration-prediction failed

---

src/common/transformations/include/transformations/convert_precision.hpp
src/common/transformations/src/transformations/convert_precision.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/conversion.cpp

- *For Convert node, converting precision from floating point to boolean will lead to mathematical error, because the output precision boolean is replaced by u8 beforehand during common transformation. E.g. floating point value 0.01 is converted to be 1 for boolean, but 0 for u8. Thus an Abs and Ceil node will be added before the Convert node for this scenario.*
- *94855*

[CPU] Ensure mathematical correctness of converting floating point to boolean

---

src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/inference/include/ie/cpu/cpu_config.hpp
src/inference/include/openvino/runtime/intel_cpu/properties.hpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/graph.h
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h
src/plugins/intel_cpu/src/onednn/iml_type_mapper.cpp
src/plugins/intel_cpu/src/onednn/iml_type_mapper.h

Issue: 77198
PR in onednn fork: https://github.com/openvinotoolkit/oneDNN/pull/158

[CPU] [EXPERIMENTAL] FullyConnected: enabled sparsity weights decompression

---

src/plugins/intel_myriad/myriad_dependencies.cmake

Update the firmware version and where to get it from.
Firmware has been uploaded to storage.openvinotoolkit.org:
```
https://storage.openvinotoolkit.org/dependencies/myriad/firmware_pcie-ma2x8x_20221129_35.zip
https://storage.openvinotoolkit.org/dependencies/myriad/firmware_usb-ma2x8x_20221129_35.zip
```
It is impossible to upload them to
```
https://download.01.org/opencv/master/openvinotoolkit/thirdparty/unified/VPU/ 
```
anymore.
Cloned from https://github.com/openvinotoolkit/openvino/pull/14373

R20 MX firmware update

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

During constant propagation, unexpected to access not allocated memory in input_layout_inst
- *97989*

[GPU] Fix to access from not allocated memory

---

src/common/legacy/src/graph_transformer.cpp

- Disabled constant folding for branch with Range operation
- 14382

Disabled constant folding for branch with Range operation

---

src/common/snippets/CMakeLists.txt
src/tests/ngraph_helpers/snippets_ngraph_functions/CMakeLists.txt

Details:
- `inference_engine_snippets` is not exported when building OpenVINO with `-D BUILD_SHARED_LIBS=ON -D BUILD_TESTS=OFF` CMake options
- this PR exports the library to allow its use in projects that use OpenVINO as a thirdparty component

Export `inference_engine_snippets` to `core` component

---

docs/requirements.txt
src/bindings/python/src/compatibility/openvino/requirements_dev.txt

- `mistune` has been bumped due to a security vulnerability
- `import-order` is an unnecessary package causing security vunlerability, used only manually, and [not updated for the past 6 years](https://pypi.org/project/import-order/)
- 96648, 97000

[PyOV] Upgrade `mistune` and remove `import-order`

---

src/plugins/auto/plugin.cpp
src/plugins/auto/utils/config.hpp

- currently , before the batch keys been unified to ie core, we have to continue support in multi/auto to allow user sets the batch keys.
-

keep the behavior of setting batch config through auto/multi

---

src/plugins/intel_gpu/include/intel_gpu/plugin/remote_context.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/plugin/remote_context.cpp

Dead lock hang issue because remote_context ignore the exception and return null. Handling unlock through lock_guard.
target model: imagesr with not enough host memory machine (device <=15G, host M<=15G)
- *98315*

[GPU] Fix dead lock from exceeded max size of host memory allocation.

---

tools/mo/openvino/tools/mo/convert_impl.py

- Always remove `_tmp.xml`, `_tmp.bin`, `_tmp.mapping` files even if model fails because these files are confusing. 
- Accuracy validation interprets as if there is any file (even `_tmp` then conversion was successful). Therefore not to confuse ourselves need always to cleanup these files not only after successful conversion.
- xxx-98168

[MO] remove '_tmp' files when layout is specified incorrectly

---

docs/OV_Runtime_UG/Samples_Overview.md
docs/get_started/get_started_demos.md

Porting: https://github.com/openvinotoolkit/openvino/pull/13807
This pull request introduces minor edits to the [Basic OpenVINO Workflow](https://docs.openvino.ai/nightly/openvino_docs_get_started_get_started_demos.html) page. The edits improve readability and make it clear that the guide is intended for C++ samples only.

DOCS: Edits to Basic OpenVINO Workflow page - porting #13807 to 22.1

---

src/plugins/intel_gpu/src/graph/program.cpp

- Removed blocked format support of arg_max_min and experimental_detectron_topk_roi in program.cpp whitelist
- PR#12456 causes accuracy regression in 95963
- 95963

[GPU] revert PR#12456 - removing blocked format support in program.cpp whitelist

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/merge_xmls.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/rename_conformance_ir.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/requirements.txt
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_conformance.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py
src/tests_deprecated/functional/vpu/tester.py
tests/layer_tests/common/layer_test_class.py
tests/layer_tests/common/utils/parsers.py
tests/stress_tests/scripts/get_testdata.py
tests/stress_tests/scripts/memcheck_upload.py
tests/stress_tests/scripts/requirements.txt
tools/mo/unit_tests/mo/back/ie_ir_ver_2/emitter_test.py

- According to bandit scan `xml.ElementTree`, `xml.dom.minidom`  [are vulnerable and better to use](https://pypi.org/project/defusedxml/#toc-entry-10) `defusedxml`.
- 93400

Fix XML vulnerabilities found by bandit

---

docs/_static/css/custom.css

Porting:
https://github.com/openvinotoolkit/openvino/pull/13187
Fixing the version selector dropdown, to avoid horizontal scrollbar and trimming text.

DOCS: Fixing version selector dropdown - porting #13187 to 22.1

---

src/frontends/tensorflow/src/input_model.cpp
tools/mo/openvino/tools/mo/moc_frontend/pipeline.py
tools/mo/unit_tests/moc_tf_fe/conversion_basic_models.py
tools/mo/unit_tests/moc_tf_fe/test_models/model_bool.pbtxt
tools/mo/unit_tests/moc_tf_fe/test_models/model_bool.py
tools/mo/unit_tests/moc_tf_fe/test_models/model_bool2.pbtxt
tools/mo/unit_tests/moc_tf_fe/test_models/model_bool2.py
tools/mo/unit_tests/moc_tf_fe/test_models/model_fp32.pbtxt
tools/mo/unit_tests/moc_tf_fe/test_models/model_fp32.py
tools/mo/unit_tests/moc_tf_fe/test_models/model_int32.pbtxt
tools/mo/unit_tests/moc_tf_fe/test_models/model_int32.py
tools/mo/unit_tests/moc_tf_fe/test_models/model_three_inputs.pbtxt
tools/mo/unit_tests/moc_tf_fe/test_models/model_three_inputs.py
tools/mo/unit_tests/moc_tf_fe/test_models/mul_with_unknown_rank_y.pbtxt
tools/mo/unit_tests/moc_tf_fe/test_models/mul_with_unknown_rank_y.py
tools/mo/unit_tests/moc_tf_fe/test_models/placeholder_with_default.pbtxt
tools/mo/unit_tests/moc_tf_fe/test_models/placeholder_with_default.py

**Details:** It supports of extraction of the original shape and type for PlaceholderWithDefault nodes and freezing Placeholders of dynamic shape for which cases shape of created Constant will be deduces on the value shape.
Also, this PR contains reorganization of python unit tests for TF FE that covers conversion and inference of different models in pbtxt. This mini-infrastructure will be used in the future for TF FE support.
**Tickets:** 98459, 98458

[TF FE] Support dynamic shape Placeholder freezing and PlaceholderWithDefault

---

tools/mo/openvino/tools/mo/main.py
tools/mo/unit_tests/mo/frontend_ngraph_test.py
tools/mo/unit_tests/mo/main_test_error_log.py

parse_agrs() in main() stands before initialization of logger. If parse_args() prints anything to logger, like deprecated parameter warning, it leads to breaking of logger and printing of all messages two times.
Also parse_agrs() is used two times in main() and in inner convert() method. Which leads to printing of messages from parse_args() two times.
Solution: 
1. Initialize logger before parse_agrs() in main()
2. Mute logger for parse_agrs() in main() to have messages only from inner parse_agrs().
Ticket: 
Code:
Validation:
Documentation:

Fix of double printing of errors in MO

---

.ci/azure/linux_conditional_compilation.yml

- *Porting https://github.com/openvinotoolkit/openvino/pull/14367 to releases/2022/3*
- *96476*

[CC] Upgrade oneDNN to fix CC inference test_model_fp32.xml crash issue.

---

tools/mo/openvino/tools/mo/convert_impl.py
tools/mo/unit_tests/mo/convert/import_from_mo_test.py

input_model parameter in convert_model() should accept string or pathlib.Path as path to input model. During implementation of passing model objects from memory (Ticket 89705) a check was added that input_model is not string to treat it as model object. But Path type was not considered in this check.
Solution: Add Path type in check that input model is model object.
Ticket: 98729
Code:
Validation:
Documentation:

Fixed type check in convert_model()

---

src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/tests/convert_model.cpp
src/frontends/tensorflow/tests/test_models/models_pbtxt/forward_edge_model.pbtxt
src/frontends/tensorflow/tests/test_models/models_pbtxt/forward_edge_model.py
src/frontends/tensorflow/tests/test_models/models_pbtxt/forward_edge_model2.pbtxt
src/frontends/tensorflow/tests/test_models/models_pbtxt/forward_edge_model2.py

**Details:** Earlier solution was incorrect due to inproper handling of forward edges cases (edges going from parent to grand-child) for which topological sorting of nodes can be interrupted.
**Ticket:** 98057

[TF FE] Break the cycle in the different way

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/program.cpp

- Removing arg_max_min from fsv16 whitelist in program.cpp in PR#14422 causes performance regression in several models.
- Added arg_max_min in fsv16 whitelist and set preferred format as planar format to avoid accuracy issue in arg_max_min ref kernel.
- 98750

[GPU] fix PR14422 regression for using arg_max_min opt kernel

---

scripts/install_dependencies/install_openvino_dependencies.sh

* install_openvino_dependencies: Added ocl-icd for ubi8 image
* install_openvino_dependencies.sh: Added json-devel to pkgs_dev for ubi8
* install_openvino_dependencies: Added pkgconf-pkg-config to pkgs_dev
* install_openvino_dependencies: Moved pkgconf-pkg-config to high-level pkgs_dev
* install_openvino_dependencies: Fixed with case for centos7
* Update scripts/install_dependencies/install_openvino_dependencies.sh
applied comments
Co-authored-by: Ilya Lavrenov <ilya.lavrenov@intel.com>
- *item1*
- *...*
- *ticket-id*

Added json-devel for ubi8 image (#14525)

---

src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/tests/functional/plugin/gpu/behavior/infer_request.cpp

- Updated to get lockable memories for device inputs in prepare_input()
- Without this PR, it fails to set f64 scalar tensor as input
- PR to master: https://github.com/openvinotoolkit/openvino/pull/14418
- 98232

[GPU] Updated to get lockable memories for device inputs in prepare_input()

---

src/core/src/op/logical_not.cpp
src/core/tests/eval.cpp

- Exception that tries to get element count from dynamic shape will be not thrown as count is taken from input tensor instead 
operator input which can be dynamic.
- 98450

Fix LogicalNot evaluate when created with dynamic input

---

src/bindings/python/tests/test_frontend/test_frontend_onnx_editor.py
src/frontends/onnx/frontend/src/input_model.cpp
src/frontends/onnx/frontend/src/input_model.hpp
tools/mo/unit_tests/mo/utils/freeze_placeholder_test.py

**Details:** Implement `get_element_type` method for ONNX InputModel. Implement tests with freezing integer input and float models.
**Tickets:** 98484, 98149

[ONNX FE] Support value freezing without specifying type (#14481)

---

src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/tests/test_cases/crop_gpu_test.cpp

- Tensor offset generated for some crop cases didn't respect batch padding. This patch adds such checks.
- *95768*

[GPU] Fixed invalid offset for tensor with batch padding

---

src/plugins/intel_cpu/src/memory_desc/cpu_memory_desc_utils.cpp
src/plugins/intel_cpu/src/memory_desc/cpu_memory_desc_utils.h
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/conv.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/convolution.cpp
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.cpp

Now dummy shape dimensions consider relations between the filter size, strides, dilations and padding.
PR to master: https://github.com/openvinotoolkit/openvino/pull/14520
- 95197

[CPU] Fix for the convolution node dummy shapes generation

---

src/plugins/intel_gna/src/frontend/scale_factor_calc.cpp
src/plugins/intel_gna/tests/functional/pass_tests/convert_matmul_to_pointwise_conv.cpp
src/plugins/intel_gna/tests/functional/pass_tests/fq_fusion_with_multiple_weights.cpp
src/plugins/intel_gna/tests/functional/pass_tests/fq_maxpool_reordering.cpp
src/plugins/intel_gna/tests/functional/scale_factors_tests/matmul_overload_correction.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/conv_fq_eltwise.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/conv_fq_relu.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/conv_fq_eltwise.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/conv_fq_relu.hpp
src/tests/functional/shared_test_classes/src/subgraph/conv_fq_eltwise.cpp
src/tests/functional/shared_test_classes/src/subgraph/conv_fq_relu.cpp

- remove plugin's internal overload correction algorithm for affine layers, which is now included in POT.
- 78001.

[GNA] Remove internal overload correction algorithm

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/lrn_gpu_across_channel_multiple_features_fsv16.cl

- input_offset_f could be negative which led to invalid memory access for input tensor.

[GPU] Fix invalid memory access in lrn fsv16 kernel

---

src/common/offline_transformations/CMakeLists.txt
src/common/offline_transformations/src/pruning/shrink_weights.cpp

- Removes MSVC warnings suppression from Offline Transformations
- Fixes the warnings
- 95170

[Offline Transformations] Avoid VC warnings

---

src/core/shape_inference/include/squeeze_shape_inference.hpp
src/core/tests/type_prop/squeeze.cpp

- *Not set squeeze output to dynamic in the case of its input_shape.size() == 1 and 0 <= input_shape[0] <= 1, because cpu_plugin can not handle dynamic rank shape*
- *CVS-96802*

Set squeeze output shape to scalar if 0 <= input_shape[0] <= 1

---

src/common/low_precision_transformations/tests/CMakeLists.txt

- Disable clang format for lp transformation test for fix CI
- *...*
- *ticket-id*

Disable clang format for lp transformation test for fix CI

---

src/common/transformations/tests/CMakeLists.txt

- Disable clang format for transformation test for fix CI
- *ticket-id*

Disable clang format for transformation test for fix CI

---

tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py

The Python benchmark_app incorrectly parses `-i` argument with files mapped to the network inputs in the following cases:
* Input name contains `.` character (`h1.1` input of [wavernn-rnn](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/wavernn#wavernn-rnn-model-specification))
* Input name has length 1 (`x` input)
The C++ version of the tool works fine with this inputs in command line.
How to reproduce on wavernn-rnn model:
```
benchmark_app -m models/public/wavernn/wavernn-rnn/FP32/wavernn-rnn.xml -i x:data/wavernn-rnn/x
[ ERROR ] Path 'x:data/wavernn-rnn/x' doesn't exist 
x:data/wavernn-rnn/x
Traceback (most recent call last):
File "/mnt/c/github/openvino/tools/benchmark_tool/openvino/tools/benchmark/main.py", line 467, in main
data_queue = …
```

benchmark_app python: fix incorrect -i argument parsing for wavernn-rnn input names

---

src/common/offline_transformations/src/compress_quantize_weigths.cpp
src/common/offline_transformations/src/pruning/shrink_weights.cpp
src/common/transformations/src/transformations/common_optimizations/align_eltwise_input_ranks.cpp
src/common/transformations/src/transformations/common_optimizations/fold_subgraph_empty_inputs.cpp
src/common/transformations/src/transformations/common_optimizations/remove_concat_zero_dim_input.cpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_split.cpp
src/common/transformations/src/transformations/smart_reshape/shape_of_const_folding.cpp
src/core/include/openvino/core/runtime_attribute.hpp
src/core/include/openvino/op/shape_of.hpp
src/core/include/openvino/op/util/shape_of_base.hpp
src/core/include/openvino/pass/constant_folding.hpp
src/core/src/node.cpp
src/core/src/op/shape_of.cpp
src/core/src/pass/constant_folding.cpp
src/core/src/rt_info.cpp
src/core/src/runtime_attribute.cpp
src/core/tests/constant_folding.cpp
src/inference/src/cpp_interfaces/interface/ie_iplugin_internal.cpp
src/inference/tests/unit/query_model_test.cpp
src/plugins/intel_cpu/src/ngraph_transformations/convert_matmul_to_fc.cpp
src/plugins/intel_cpu/src/ngraph_transformations/move_eltwise_up_data_movement.cpp
src/plugins/intel_cpu/src/utils/rt_info/memory_formats_attribute.hpp
src/plugins/intel_gna/src/transformations/handle_transposes_around_matmul.cpp
src/plugins/intel_gna/src/transformations/insert_reshape_around_matmul.cpp
src/plugins/intel_gna/src/transformations/insert_transpose_after_convolution_or_pooling.cpp
src/plugins/intel_gna/src/transformations/pwl_approximation.cpp
src/plugins/intel_gna/src/transformations/swap_input_matmul_gna.cpp
src/tests/ie_test_utils/common_test_utils/graph_comparator.cpp
src/tests/unit/inference_engine/query_model_test.cpp

- *Fix handling of Constants without supported consumers. Previously Constants from original graph was handled, but that's wrong - we should check Constants from transformed graph. And also fused_names of consumers should be checked, not only node name.*
- *Fix handling of case, when additional node is inserted and uses name of previous node.*
- *Fix propogation of RTInfo for ConstantFolding. Previous behaviour leads to situation when Constant names were included into the fused_names of the next functional layer. Instead of it we should copy RTInfo of folded operations into the replacement Constant*
- *Update tests for ConstantFolding in order to verify fused_names attribute*
- *Clean up fused_names if they are present in orignal model in QN*
- *Create tests for GetSupportedNodes function …

[HETERO][nGraph] Fix ConstantFolding fused_names handling

---

src/bindings/python/tests/test_runtime/test_properties.py

- Covers full scope of Python Properties API
- Refactor of tests
- Part of: 98111

[PyOV] Rewriting properties tests as hardware agnostic

---

src/common/low_precision_transformations/tests/CMakeLists.txt
src/common/transformations/tests/CMakeLists.txt

- Enable clang-format for ov_transformations_tests & ov_lp_transformations_teststests
- CVS-99422

Enable clang-format for tests

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/shape_infer/broadcast_si_test.cpp

- When shape infer dep node is blocked format, the memory cannot be read by ngraph shape infer as expected. 
- Fixed node's layout to be plain format when it is to be used as shape infer dep from the user node

[GPU] Fixed shape infer dep for blocked format

---

docs/OV_Runtime_UG/supported_plugins/CPU.md
docs/snippets/cpu/dynamic_shape.cpp
docs/snippets/cpu/dynamic_shape.py

Since memory reuse was introduced for dynamic shapes, the recommendation to use partially defined shapes to reduce memory consumption is not relevant anymore.
master branch PR: https://github.com/openvinotoolkit/openvino/pull/14674

[CPU][DOCS]Remove recommendation to use partially defined shapes

---

docs/OV_Runtime_UG/supported_plugins/CPU.md
docs/snippets/cpu/dynamic_shape.cpp
docs/snippets/cpu/dynamic_shape.py

Since memory reuse was introduced for dynamic shapes, the recommendation to use partially defined shapes to reduce memory consumption is not relevant anymore.
PR to release branch: https://github.com/openvinotoolkit/openvino/pull/14675

[CPU][DOCS] Remove recommendation to use partially defined shapes

---

src/bindings/python/requirements_test.txt

**Details:** Fix upper-bound version of NumPy for testing Python bindings.
Tests use deprecated type

Use upper-bound version of numpy for Python binding testing

---

src/common/transformations/tests/common_optimizations/eliminate_duplicate_ti_inputs.cpp
src/common/transformations/tests/smart_reshape/broadcast_const_range_replacement.cpp

- Fix clang warnings for ov_transfomations_tests
- CVS-99423

Fix clang warnings for transformation tests

---

src/plugins/intel_cpu/src/nodes/strided_slice.cpp
src/plugins/intel_cpu/src/nodes/strided_slice.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/strided_slice.cpp
src/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/builders.hpp
src/tests/ngraph_helpers/ngraph_functions/src/strided_slice.cpp

- Support of non-const data on Begin, End and Stride inputs via optimized implementation. Previously such operations were executed via fallback on ngraph reference which resulted in poor performance 
- Extended StridedSlice single layer test to cover non-const data on corresponding inputs.
- *CVS-99479*

[CPU] Extend StridedSlice dynamic shape support

---

src/common/legacy/include/legacy/ie_layers.h
src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/src/backend/gna_limitations.hpp
src/plugins/intel_gna/src/common/gna_target.hpp
src/plugins/intel_gna/src/gna_device.cpp
src/plugins/intel_gna/src/gna_graph_compiler.cpp
src/plugins/intel_gna/src/gna_graph_compiler.hpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/gna_plugin.hpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/convolution_negative.cpp
src/plugins/intel_gna/tests/unit/CMakeLists.txt
src/plugins/intel_gna/tests/unit/backend/gna_limitations_test.cpp
src/plugins/intel_gna/tests/unit/gna_mock_api.hpp
src/plugins/intel_gna/tests/unit/gna_mock_api_initializer.cpp
src/plugins/intel_gna/tests/unit/gna_mock_api_initializer.hpp
src/plugins/intel_gna/tests/unit/gna_plugin_load_network_test.cpp
src/tests_deprecated/unit/engines/gna/gna_mock_api.hpp

- Assert that kernel above padding size (fix 96890)
- Fix and simplify compile target handling in graph compiler (fix 98584) 
- Swap padding end axes when swapping begin (fix 99008)
- Add tests
- Some new GNA unit test files are excluded at cmake levels due to static build issues described in issue 71010
- 98584
- 99008
- 96890

[GNA] Fix input padding validator

---

src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/fusions/deconvolution_fusion_test.cpp

- Accuracy Issue
- fusings_gpu/deconv_scale_actv_quant_u8_eltw_scale_actv_quant_i8.basic/15
- Remove WA
- fusings_gpu/deconv_actv_eltw_actv.basic/20
- fusings_gpu/deconv_scale_actv_quant_u8_eltw_scale_actv_quant_i8.basic/8
- fusings_gpu/deconv_scale_actv_quant_u8_eltw_scale_actv_quant_i8.basic/15
- Quantize clamp optimization(prepare_quantization.cpp:227) for cldnn is not proper to onednn.
- cast intermediate variable to output type after ~
- cldnn:  every fused quantization.
- onednn: all post-ops are processed.
- A little perf regression expected in onednn because clamp is relatively heavier operation than type casting.
- fusings_gpu/deconv_actv_eltw_actv.basic/20
- 8947 fixed (#14139)
- fusings_gpu/deconv_scale_actv_quant_u8_eltw_scale_actv_quant_i8.basic/8
- 8947 fixed (#14139)
- …

[GPU][DG2] Fix deconv unit tests

---

src/core/include/openvino/core/partial_shape.hpp
src/core/shape_inference/include/squeeze_shape_inference.hpp
src/core/tests/partial_shape.cpp

Extend the partial shape interface to support the:
- back inserter iterator
- emplace back
This can improve implementing shape inference in template way as all shapes interface will be more common:
- reduce empty allocation or copies form input shapes and then replace elements 
- reduce create some temporary object with dimension
- allows to create dimension in-place or use back inserter by algorithm functions
- 99460

Extend partial shape to use back inserter and emplace

---

src/plugins/intel_gpu/include/intel_gpu/primitives/broadcast.hpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/broadcast.cpp

- Broadcast op shape infer impl for scalar input and scalar target shape could return tensor with 0 shape which can't be processed correctly in some cases. This patch initialize `broadcast_sizes` with tensor(1) for the cases when target shape is empty to convert scalar to 1d tensor.
- *99651*

[GPU] Fix shape infer for 0d broadcast

---

src/core/include/openvino/core/descriptor/tensor.hpp

- Removed deprecated `get_name()` for tensor
- *ticket-id*

Removed legacy get_name

---

docs/suppress_warnings.txt

suppress additional build warnings:
autosummary: stub file not found
failed to parse name
port https://github.com/openvinotoolkit/openvino/pull/14776

DOCS-Add-warnings-for-docs (#14776)

---

src/tests/functional/plugin/gpu/single_layer_tests/dynamic/gather.cpp

Currently limited scope of gather is supported for dynamic shape: i.e., input/output dimension should be same if the shape is > 4D

[GPU] Added gather dynamic gpu func test

---

src/common/transformations/include/ov_ops/nms_static_shape_ie.hpp
src/common/transformations/tests/op_conversions/convert_matrix_nms_to_matrix_nms_ie_internal.cpp

- *Set correct output precision of `MatrixNmsIE` in `ConvertMatrixNmsToMatrixNmsIE` transformation.*
- *ticket-id*

[nGraph] Fix output precision of MatrixNmsIE

---

src/frontends/tensorflow/src/op/interpolate.cpp
tests/layer_tests/tensorflow_tests/test_tf_Resize.py

**Details:** Fix ResizeBilinear operation for uint8 input type and add layer tests for ResizeBilinear and ResizeNearestNeighbor operations.
**Tickets:** 92858, 92859, 95182

[TF FE] Fix ResizeBilinear for uint8 type and test Resize operations

---

src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp
src/plugins/intel_gpu/tests/fusions/gemm_fusion_test.cpp

- fusings_gpu/gemm_2in_scale.basic/7
- fusings_gpu/gemm_2in_scale.fp16_scale_out/7
- Set default tolerance
- fusings_gpu/gemm_2in_act_scale_eltwise.basic/0
- fusings_gpu/gemm_2in_act_scale_eltwise.broadcast_eltwise/0
- Fix incorrect condition of expected_fused_count adjustment
- eltwise_sum_fusings_gpu/onednn_binary_add_full_tensor.basic/0
- multiple_eltwise_sum_fusings_gpu/onednn_multiple_binary_add_full_tensor.basic/0
- Onednn does not support 'negative' activation function.
- 67491

[GPU][DG2] Fix gemm unit tests

---

src/plugins/intel_gpu/src/graph/include/activation_inst.h
src/plugins/intel_gpu/src/graph/include/bucketize_inst.hpp
src/plugins/intel_gpu/src/graph/include/grn_inst.h
src/plugins/intel_gpu/src/graph/include/lrn_inst.h
src/plugins/intel_gpu/src/graph/include/mvn_inst.h
src/plugins/intel_gpu/src/graph/include/normalize_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/reverse_inst.h
src/plugins/intel_gpu/src/graph/include/reverse_sequence_inst.h
src/plugins/intel_gpu/src/graph/include/roll_inst.hpp
src/plugins/intel_gpu/src/graph/include/scatter_update_inst.h
src/plugins/intel_gpu/src/graph/include/softmax_inst.h
src/plugins/intel_gpu/src/graph/mvn.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/scatter_update.cpp
src/plugins/intel_gpu/tests/shape_infer/activation_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/bucketize_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/grn_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/lrn_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/normalize_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/reverse_sequence_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/reverse_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/roll_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/softmax_si_test.cpp

- Added new shape infer impls for the following list of primitives:
- activation
- bucketize
- grn
- lrn
- reverse
- reverse_sequence
- roll
- softmax
- normalize
- modified shape infer impl for mvn and scatter_update to use common helper

[GPU] new shape infer for several trivial primitives

---

src/plugins/auto/plugin.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp

- Disable AUTO/MULTI repeatedly loading network to meta plugin  itself
- 96209

[AUTO Plugin] AUTO/MULTI should not support the meta plugin appearing in candidate device list

---

cmake/developer_package/compile_flags/os_flags.cmake
samples/cpp/CMakeLists.txt

On gcc-11 and higher armv7 architecture native build fails on samples compilation with the following error:
```
cc1plus: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU
```
This patch is intended to fix this issue.
Similar issue can be found here: https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1939379

Fix samples build on armv7

---

.github/workflows/code_style.yml

- Added GitHub action to automatically apply code-style changes based on clang-format
- Added GitHub action's step to review PRs for shell scripts mistakes

Smart github actions for shellcheck and clang-format

---

docs/_static/css/custom.css

This fix addresses word wrapping in &lt;pre&gt; tags in the output html files of documentation.
The result:
http://openvino-doc.iotg.sclab.intel.com/seba-test-p-1-1/notebooks/223-gpt2-text-prediction-with-output.html#run

DOCS: Word wrapping in preformatted text

---

src/inference/include/openvino/runtime/properties.hpp

- `error: expected unqualified-id` because component defines: `#define DEBUG 1`
- 100153

Undef DEBUG macro for log level property

---

docs/_static/css/custom.css

Porting: 
https://github.com/openvinotoolkit/openvino/pull/14889
This fix addresses word wrapping in &lt;pre&gt; tags in the output html files of documentation.
The result:
http://openvino-doc.iotg.sclab.intel.com/seba-test-p-1-1/notebooks/223-gpt2-text-prediction-with-output.html#run

DOCS: Word wrapping in preformatted text - port to 22.3

---

docs/_static/css/custom.css

Porting: 
https://github.com/openvinotoolkit/openvino/pull/14889
This fix addresses word wrapping in &lt;pre&gt; tags in the output html files of documentation.
The result:
http://openvino-doc.iotg.sclab.intel.com/seba-test-p-1-1/notebooks/223-gpt2-text-prediction-with-output.html#run

DOCS: Word wrapping in preformatted text - port to 22.2

---

docs/_static/css/custom.css

Porting:
https://github.com/openvinotoolkit/openvino/pull/14889
This fix addresses word wrapping in &lt;pre&gt; tags in the output html files of documentation.
The result:
http://openvino-doc.iotg.sclab.intel.com/seba-test-p-1-1/notebooks/223-gpt2-text-prediction-with-output.html#run

DOCS: Word wrapping in preformatted text - port to 22.1

---

docs/snippets/ie_common.cpp

Minor documentation fix:
In the ["Fill Input Tensors with Data" section](https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html#doxid-openvino-2-0-inference-pipeline-1fill-tensor) of the [Inference Engine documentation](https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html), in the example using the Inference Engine API, the comment should refer to the first blob, then to the second blob. This PR fixes that.
See also https://github.com/openvinotoolkit/openvino_docs/pull/230

Fix inference pipeline C++ doc: refer to the correct input blob

---

docs/snippets/ie_common.cpp

Minor documentation fix:
In the ["Fill Input Tensors with Data" section](https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html#doxid-openvino-2-0-inference-pipeline-1fill-tensor) of the [Inference Engine documentation](https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html), in the example using the Inference Engine API, the comment should refer to the first blob, then to the second blob. This PR fixes that.
Port from https://github.com/openvinotoolkit/openvino/pull/14709

Fix inference pipeline C++ doc: refer to the correct input blob for 22.2

---

docs/snippets/ie_common.cpp

Minor documentation fix:
In the ["Fill Input Tensors with Data" section](https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html#doxid-openvino-2-0-inference-pipeline-1fill-tensor) of the [Inference Engine documentation](https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html), in the example using the Inference Engine API, the comment should refer to the first blob, then to the second blob. This PR fixes that.
Port from https://github.com/openvinotoolkit/openvino/pull/14709

Fix inference pipeline C++ doc: refer to the correct input blob for 22.3

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/plugin/transformations/decompose_reduce_for_false_keepdims.cpp
src/plugins/intel_gpu/src/plugin/transformations/decompose_reduce_for_false_keepdims.hpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/transformations/decompose_reduce_for_false_keepdims_test.cpp

+ Fix accuracy issue of oneDNN reduction
+ Add Reshape to modify output of Reduce and update keep_dims to true : reduce-reshape
- A clDNN Reduce reorders un-reduced axes of its output tensor to b-f and spatial order when keep_dims is false. oneDNN reduction does not allow this. And clDNN execution shows a hug perf drop for blocked formats.
- Resolve accuracy issue of deblurgan-v2 model. 
- 98612

Bugfix for byx reduction

---

docs/OV_Runtime_UG/ShapeInference.md
docs/OV_Runtime_UG/migration_ov_2_0/deployment_migration.md
docs/dev/build.md
docs/install_guides/installing-openvino-yocto.md
docs/install_guides/troubleshooting-issues.md
docs/ops/activation/SoftPlus_4.md
docs/ops/internal/AUGRUCell.md
docs/ops/internal/AUGRUSequence.md
docs/optimization_guide/model_optimization_guide.md
docs/resources/telemetry_information.md
thirdparty/cnpy/README.md
tools/legacy/benchmark_app/README.md
tools/pot/openvino/tools/pot/api/samples/3d_segmentation/README.md
tools/pot/openvino/tools/pot/api/samples/classification/README.md
tools/pot/openvino/tools/pot/api/samples/face_detection/README.md
tools/pot/openvino/tools/pot/api/samples/segmentation/README.md

This fixes the broken links found throughout the OV docs.
Port from https://github.com/openvinotoolkit/openvino/pull/14935

DOCS: Fixing broken links in documentation for 22.3

---

docs/_static/css/custom.css
docs/_static/js/hide_banner.js
docs/_templates/layout.html

Porting: https://github.com/openvinotoolkit/openvino/pull/14949
This enables keeping the banner hidden after closing it.

DOCS: Hiding Transition to API 2.0 banner - for 22.3

---

docs/_static/css/custom.css
docs/_static/js/hide_banner.js
docs/_templates/layout.html

Porting: https://github.com/openvinotoolkit/openvino/pull/14949
This enables keeping the banner hidden after closing it.

DOCS: Hiding Transition to API 2.0 banner - for 22.2

---

docs/_static/css/custom.css
docs/_static/js/hide_banner.js
docs/_templates/layout.html

Porting: https://github.com/openvinotoolkit/openvino/pull/14949
This enables keeping the banner hidden after closing it.

DOCS: Hiding Transition to API 2.0 banner - for 22.1

---

tools/mo/openvino/tools/mo/back/ResultRename.py
tools/mo/unit_tests/mo/back/ResultRename_test.py

- *MO IR Reader doesn't preserve the output order because in case of `ResultRename` transformation is called names preserved in `outputs_order` list are changed*
- *10010*

Fix ResultRename transformation to preserve output order

---

samples/cpp/benchmark_app/benchmark_app.hpp
samples/cpp/benchmark_app/main.cpp
samples/cpp/benchmark_app/utils.hpp
tools/legacy/benchmark_app/benchmark_app.hpp
tools/legacy/benchmark_app/main.cpp

* uint32->uint64 for RedHat gflags 2.1 failing at runtime
* tools/legacy/benchmark_app: uint32->uint64 for RedHat gflags 2.1 failing at runtime
Co-authored-by: Ilya Lavrenov <ilya.lavrenov@intel.com>

uint32->uint64 for RedHat gflags 2.1 failing at runtime (#14724)

---

.ci/azure/linux.yml
.ci/azure/linux_debian.yml
tools/mo/requirements.txt

**Details:** Clarify that `requirements.txt` file is used only for the default installation. Now it confuses the validation that it combines dependencies for all extras installation but it is not true. Moreover, we are going to remove duplicates in requirements files so that it will be more easier to update it by `dependant-bot`.

[Tools][MO] Clean up requirements for default installation

---

src/core/include/openvino/op/if.hpp
src/core/include/openvino/op/util/framework_node.hpp
src/core/include/openvino/op/util/multi_subgraph_base.hpp
src/core/src/op/if.cpp
src/core/src/op/util/framework_node.cpp
src/core/src/op/util/multi_subgraph_base.cpp
src/core/src/pass/serialize.cpp
src/core/tests/pass/serialization/custom_ops.cpp
src/core/tests/visitors/op/framework_node.cpp
src/tests/util/visitor.hpp

- *Inherit `FrameworkNode` from `MultiSubGraphOp` to enable frontends to create abstract operations which contain subgraphs*
- *Allow serialization of `FrameworkNode` with multiple bodies*
- *100399*

Support FrameworkNode with subgraphs

---

src/plugins/intel_gna/src/gna_graph_patterns.hpp
src/plugins/intel_gna/tests/functional/limitations/layers_limit.cpp

- Test model should be spitted on several branches to avoid stack overflow error on windows in legacy DFS function 
- *98431*

[GNA] Changed max layer limit tests to avoid SEH exceptions

---

src/tests/functional/shared_test_classes/include/shared_test_classes/base/ov_subgraph.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp

- *Added static_shapes_to_test_representation but for partial shapes. This will be used in snippets tests: [PR#14327](https://github.com/openvinotoolkit/openvino/pull/14327)*
- *I noticed that data generate method could generate inputs in a very narrow range of values. A fix is proposed.*

Common test infrastructure suggestions

---

src/tests/functional/plugin/shared/include/behavior/plugin/core_integration.hpp

- `ImportNetwork()` is supported by GPU plugin from 2022.3 release.
- So, the test case `IEClassBasicTestP.ImportNetworkThrows` is not necessary anymore.

[GPU] GPU plugin supports ImportNetwork()

---

src/plugins/intel_gpu/src/graph/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_bfyx_1x1_hgemm_buf_16x1.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_winograd_6x3_s1_fused.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gen9_common_conv_fwd_data_f32.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_1x1_gemm_buf.cpp

- Fixed perf regression on several models. Use intel_sub_group_block_read_us8 instead of wrapper _sub_group_block_read_us8 for image cases
- *100290*

[GPU] Added missing supports_image initialization in EngineInfo

---

src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp

- *When we just call set_properties and no initialize plugin before it or indirectly(in compile_model for example), the properties will set just in PluginRegistry to structure with type of values Any and no validations will be made. So, let's add get_version to force initialization of plugin.*
- *Please note, that commit fixes test SetPropertiesWithIncorrectKey , but after adding the function call tests SetCorrectProperties for CPU plugin will be fails, because of unsupported DeviceID, but looks like it more correct.*
- *CVS-98405*

[apiConformancForce] creating plugin before setting properties

---

src/common/transformations/include/transformations/common_optimizations/transpose_sinking_binary.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_unary.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_utils.hpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_concat.cpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_general.cpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_split.cpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_unary.cpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_utils.cpp
src/common/transformations/tests/common_optimizations/transpose_sinking_binary_test.cpp
src/common/transformations/tests/common_optimizations/transpose_sinking_concat_test.cpp
src/common/transformations/tests/common_optimizations/transpose_sinking_split_test.cpp
src/common/transformations/tests/common_optimizations/transpose_sinking_unary_test.cpp

-  TransposeSinking for binary elementwise, Concat, Split for multiple consumers case
- wrote new unit tests for multi consumers cases
- reorganize exited unit tests
- TransposeSinking for PRelu
- 96628
- 99240
- 92223

Transpose sinking binary/split/concat mult consumers case + PRelu

---

src/plugins/intel_gpu/src/runtime/kernels_cache.cpp

- In dynamic shape, kernels are newly created and compiled for new shapes. Previously, dumped cl source codes for the same program id was overwritten by such new kernels, because the file name is only identified by prog_id, batch_id. 
- Fixed dump file name to include hash value so that it will not be overwritten.

[GPU] Fix cl source dump file name not to be overwritten

---

src/plugins/intel_gpu/tests/gtest_main_gpu.cpp

- *--help option doesn't print available test options*
- *gtest_main_gpu.cpp has minor memory leak*
- *ticket-id*

[GPU tests] fix --help option and memory leak

---

src/inference/src/compilation_context.cpp

- `modelPath` of `CacheContent` can be a null string.
- In this case, `InferenceEngine::NetworkCompilationContext::calculateFileInfo` returns non-consistent results on some environments
https://github.com/openvinotoolkit/openvino/blob/9c7beee5e55808730418dfd6bb5fb22e7bb28dc8/src/inference/src/compilation_context.cpp#L46-L64
1. Let's assume that `filePath` = "" @ L46
2.  `FileUtils::absoluteFilePath(filePath)` returns the present working DIRECTORY of current app @ L50
3.  `stat(absPath.c_str(), &result)` succeeds @ L59
4.  `result.st_mtime` is the last modification time of the present working DIRECTORY @ L60
5.  if some changes occur in the DIRECTORY, different FileInfo is generated.
6.  FileInfo mismatch in `ov::CoreImpl::LoadNetworkFromCache` …

Update calculateFileInfo for the null string case

---

src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/bindings/python/src/pyopenvino/core/properties/properties.hpp
src/bindings/python/src/pyopenvino/utils/utils.cpp
src/bindings/python/tests/test_runtime/test_properties.py

- Added new submodules to properties: `intel_gpu`, `intel_gpu.hint`, `intel_gpu.MemoryType`, `intel_gpu.CapabilityGPU`
- Added tests.
- "in-line" explanation for conflicting `ov::intel_gpu::hint::ThrottleLevel`.
- *100915*

[PyOV] Add properties of GPU plugin to bindings

---

src/plugins/intel_gpu/src/graph/impls/onednn/concatenation_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h

The issue is reproduced in models included implicit concat
Opt-out primtive_onednn_imple doesn't share ExecutionConfig issue
- *101368*

[GPU] Fix segfault with exec_graph_path option

---

tools/mo/openvino/tools/mo/back/ie_ir_ver_2/emitter.py
tools/mo/unit_tests/mo/back/ie_ir_ver_2/emitter_test.py

**Root cause analysis**: There are some operation with several outputs e.g. `MaxPool-8`. And during emitting there was an assert that operation does contain output data node, but check was quite rigorous and checked if number of out_nodes are strictly 1 which didn't cover cases for ops with several outputs.
E.g. starting from 2022.1 such ops at the end of the graph cause error despite that graph is correct and on 2021.4 was converted without any issues.
**Solution**: replace assert to a more correct one: check if number of out nodes >=1. 
`assert len(node.out_nodes()) == 1` => `assert len(node.out_nodes()) >= 1`
Ticket: xxx-87292
Code:
Validation:
* n/a  Unit tests
* n/a  Framework operation tests
* n/a  Transformation tests
Documentation:
* n/a  Supported frameworks operations list
* n/a …

fix check for data nodes in emitter.py

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/gather.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_kernel_ref.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/gather.cpp

- Previously, reorder_input pass checked only output layouts of each node, with an assumption that the input/output ranks are same at that pass. 
- However in dynamic shape using ngraph shape infer, there are cases input / output ranks differ. In such cases, the reorder_input pass inserts reorder to the format of current node's output_layout in the input of the current node, which causes error.
- Fixed the above behavior by applying set_preferred_input/output_layout.
- 99432

[GPU] Let reorder_inputs pass to use not only output_layout but also input layout for dynamic shape

---

tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py

Python benchmark_app crashes with the `KeyError` exception in case of binary input file and batch_size > 1:
```
$ benchmark_app.py -m /tmp/models/public/robust-video-matting-mobilenetv3/FP32/robust-video-matting-mobilenetv3.xml -i src:image_0.png r1:r1.bin -b 4 
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] 
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] 
[ INFO ] 
<...>
[Step 9/11] Creating infer requests and preparing input tensors
[ WARNING ] Some images will be dublicated: 4 is required, but only 1 were …
```

[benchmark_app python] Fix crash in case of binary input and batch > 1

---

cmake/packaging/copyrights/arm_cpu

Should be merged after https://github.com/openvinotoolkit/openvino_contrib/pull/489

[ARM] Added neon_mathfun license

---

docs/install_guides/configurations-for-ncs2.md

Fixing indentation of code blocks in Step 5 for Raspbian OS.

DOCS: Fixing formatting in 'Configurations for NCS2' article - for 22.3

---

src/frontends/onnx/frontend/include/onnx_import/core/node.hpp
src/frontends/onnx/frontend/src/core/attribute.cpp
src/frontends/onnx/frontend/src/core/attribute.hpp
src/frontends/onnx/frontend/src/core/graph.cpp
src/frontends/onnx/frontend/src/core/graph.hpp
src/frontends/onnx/frontend/src/core/node.cpp
src/frontends/onnx/tests/models/controlflow/if_inside_if_inside_loop.prototxt
src/frontends/onnx/tests/onnx_import_controlflow.in.cpp
src/frontends/onnx/tests/runtime/interpreter/unit_test.manifest

In case when subgraph has implicit inputs from their indirect parent, those inputs are not registered in direct parent.
So when subgraph node is created - it references input that is not available in direct parent's scope.
In this patch, the proposed solution registers the input (the particular subgraph references), in every (direct or indirect) that subgraph's parent.

[ONNX] Fix "Model references undeclared parameters" exception

---

docs/snippets/ie_common.cpp

Minor documentation fix:
In the ["Fill Input Tensors with Data" section](https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html#doxid-openvino-2-0-inference-pipeline-1fill-tensor) of the [Inference Engine documentation](https://docs.openvino.ai/latest/openvino_2_0_inference_pipeline.html), in the example using the Inference Engine API, the comment should refer to the first blob, then to the second blob. This PR fixes that.
Port from https://github.com/openvinotoolkit/openvino/pull/14709

DOCS: Fix inference pipeline C++ doc: refer to the correct input blob - for 22.1

---

src/inference/src/compilation_context.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/caching_tests.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp

- Compute hash doesn't work with empty tensor
- *ticket-id*

Ignore empty tensor for hash calculation

---

src/frontends/tensorflow_common/include/pass/transpose_sinking.hpp
src/frontends/tensorflow_common/src/pass/transpose_sinking.cpp
src/frontends/tensorflow_common/tests/transpose_sinking.cpp

**Details:** The current Transpose Sinking actively uses `get_shape` method without checking if tensor is static.

[TF FE] Fix Transpose Sinking for dynamic shapes

---

.ci/azure/linux_debian.yml

Since there is no GNA for that build, tests are not built, so call of InferenceEngineUnitTests lead to failure because file not found

Remove "IEUnitTests" from linux_debian.yml

---

src/bindings/python/src/openvino/offline_transformations/__init__.py

- Decided to update this warning as not all transformations will be part of `openvino.runtime.passes`
- 98829

[PyOV] Update futureWarning in offline_transformations

---

src/core/reference/src/runtime/reference/convert.cpp

- Mixed Vex/NonVex encoded instruction inside Convert evaluate implementation (FP16->FP32, U8->FP16) led to significant performance penalties on ADL/RPL CPUs. PRs removes nonVEX istructions usage which allows to improve loadTime on several times for particular FP16 models.

[CORE] Fixed VEX/NonVEX performance penalty inside Convert evaluate impl

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp

onednn doesn't support activation fusing. Add missed check-logic.
faceboxes, icv-reid-embeddin, modnet_webcam_portrait_matting fail to run.
- *102215*

[GPU] Fix onednn concat, activation fusing functional regression.

---

src/plugins/intel_gpu/src/graph/data.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.hpp

- This PR implements copy_to() and copy_from() functions for the `gpu_image2d` memory type.
- These functions are required for GPU model caching.
- *ticket-id*

[GPU] Adding copy functions for image2d memory

---

docs/OV_Runtime_UG/Samples_Overview.md

Adding missing info about architecture for 'Build the Sample Applications on Microsoft Windows' section.

[DOCS] Installation issues #15090 - post merge fixes for 22.3

---

install_build_dependencies.sh

It failed in running 'install_build_dependencies.sh' for proper dependencies for CentOS/RedHat OS. 
Part of the error messages are:
```shell
Dependencies resolved.
Nothing to do.
Complete!
CMake Error: The source directory "/home/david/feMON/target/openvino/openvino/pugixml-devel" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
./install_build_dependencies.sh: line 109: libva-devel: command not found
./install_build_dependencies.sh: line 111: python3-pip: command not found
./install_build_dependencies.sh: line 155: apt-get: command not found
```
Fix this.

Fix dependency install issue for CentOS/RedHat

---

tools/compile_tool/main.cpp

Fixes issue in compile_tool whereby unknown argument error prints address instead of string.
- 102048

Print unknown argument itself instead of pointer address

---

src/frontends/tests/frontend/shared/src/basic_api.cpp
src/frontends/tests/frontend/shared/src/conversion.cpp
src/frontends/tests/frontend/shared/src/convert_model.cpp
src/frontends/tests/frontend/shared/src/cut_specific_model.cpp
src/frontends/tests/frontend/shared/src/library_extension.cpp
src/frontends/tests/frontend/shared/src/load_from.cpp
src/frontends/tests/frontend/shared/src/op_extension.cpp
src/frontends/tests/frontend/shared/src/op_fuzzy.cpp
src/frontends/tests/frontend/shared/src/partial_shape.cpp
src/frontends/tests/frontend/shared/src/set_element_type.cpp
src/frontends/tests/frontend/shared/src/telemetry.cpp

- Remove extra dependency - OV_FRONTEND_PATH points to the same place from what FrontEndManager loads frontends by default
- 101687

Remove `setupTestEnv()` from  `frontend_shared_test_classes`

---

src/bindings/python/src/openvino/runtime/passes/__init__.py
src/bindings/python/src/pyopenvino/graph/passes/manager.cpp
src/bindings/python/src/pyopenvino/graph/passes/transformations.cpp
src/bindings/python/src/pyopenvino/utils/utils.cpp
src/bindings/python/src/pyopenvino/utils/utils.hpp
src/bindings/python/tests/test_graph/test_manager.py
src/bindings/python/tests/test_runtime/test_model.py
src/bindings/python/tests/test_transformations/test_offline_api.py
src/bindings/python/tests/test_transformations/test_public_transformations.py
src/bindings/python/tests/test_utils/test_utils.py

- Added `tmp_path` [fixture](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmp-path-fixture) for working with temporary files in tests.
- Update `test_manager.py` -- reduce amount of `DeprecationWarning` (use Serialize transformation directly wherever it's possible).
- Update `Serialize` python ctor -- support of `IR Vesrion` enum in python + add `string`-type for `IR Version` to be aligned with `manager.register_path` for Serialize transformation.
- Move `convert_to_version` under `Common::utils` namespace.
- 98936

[PyOV] Try to fix PosixPath error in CI

---

src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- onednn concat impl does not support i32
- enable onednn enable_profiling for dump_profiling

[GPU] Use ocl for i32 dtype concat / enable_profiling for dump_profiling

---

src/frontends/pytorch/src/frontend.cpp

- *Use transformation added by #15250 to remove the need for second call of UnrollIf*
- *None*

[PT FE] Remove second call for UnrollIf

---

src/plugins/intel_gpu/src/graph/include/activation_inst.h
src/plugins/intel_gpu/src/graph/include/arg_max_min_inst.h
src/plugins/intel_gpu/src/graph/include/convolution_inst.h
src/plugins/intel_gpu/src/graph/include/cum_sum_inst.h
src/plugins/intel_gpu/src/graph/include/deformable_convolution_inst.h
src/plugins/intel_gpu/src/graph/include/gather_tree_inst.h
src/plugins/intel_gpu/src/graph/include/non_max_suppression_inst.h
src/plugins/intel_gpu/src/graph/include/normalize_inst.h
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/include/reduce_inst.h
src/plugins/intel_gpu/src/graph/include/select_inst.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp

- Shape inference with memory inputs are time consuming if those values are in the device memory, because it needs copy to host
- Allocate such memories to host improved shape inference performance in dGPU
- 93592

[GPU] Allocate output to host if it is to be used as shape infer dependency 

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/add_onednn_optimization_attributes.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp

Huge performance improvement FC and gemm in oneDNN3.0
Update to use onednn FC and gemm in OV and remove W.A code force using cldnn in FC, gemm
Fix the issues used from onednn fc, gemm(eltwise post op)
- FC b16 ACC issue: cldnn updates yxfb format in b16 for opt kernel, but FC onednn should bfyx
- FC ACC issue: 3 input dims with eltwise post-po.
- gemm ACC issue: multiple batch with eltwise post-po.
- *101284*

[GPU] Use onednn fc/gemm in dGPU.

---

src/core/include/openvino/op/constant.hpp

This patch fixes two issues:
* Typo in clang pragma directive
* Reverse the order of the arguments in OPENVINO_ASSERT() in constant.hpp so this assert compiles successfully for ov::bfloat16 and ov::float16 argument types which have implemented binary comparison operators as the member functions

Fix OpenVINO 2022.3.0 Chrome OS compilation

---

src/common/transformations/src/transformations/common_optimizations/shuffle_channels_fusion.cpp
src/inference/tests/unit/query_model_test.cpp

- *Fix fused names for ShuffleChannelsFusion transformation: constant names were not saved, which lead to wrong processing during HETERO scenario*
- *ticket-id*

[nGraph]: fix fused names for ShuffleChannelsFusion transformation

---

src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/bindings/python/src/pyopenvino/utils/utils.cpp
src/bindings/python/tests/test_runtime/test_properties.py

- Added the `ExecutionMode` enum and  `execution_mode` property to Python API.
- New translator in dispatching of related ov::Any directly to a value.
- Added test.
- 102675
- 102435

[PyOV] Add ExecutionMode enum and property

---

src/plugins/intel_gpu/src/graph/kernel_selector_helper.cpp
src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp

- This patch fixes the situation when single fused activation is always treated as legacy-fused (in case of Convolutions). Some of new kernels do not have legacy fusions mechanism that leads to ignoring fused activation and accuracy problems.
- *ticket-id*

[GPU] Limit legacy fusions usage in Convolution kernels

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_opt.cpp

- overwrite zero value to padding area of resample. This issue is occurred if implicit concat is next of resample.
- feature num includes padding.
- 101957

[GPU] fix bug on resample_opt

---

src/plugins/intel_gpu/src/graph/network.cpp

- This patch fixes synchronization issue caused by unproper `reset_execution(true)` in case of `in_order` queue type. The issue became visible in case of cross-networks memory usage during model loading stage (e.g. network1 produces output1 memory and network2 accepts output1 as input - and since network1's reset_execution(true) call does not wait for calculations to complete, network2 starts inference with invalid data).
Note: checked performance on several models in dGPU - didn't find any impact on performance.
- *102617*

[GPU] Fix reset_execution() method with wait option enabled for `in_order` queue type

---

docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
docs/OV_Runtime_UG/supported_plugins/VPU.md

Porting: https://github.com/openvinotoolkit/openvino/pull/13580
Changing Eltwise-LessEqual layer to Not Supported.
---
Porting: https://github.com/openvinotoolkit/openvino/pull/13997
Update support "Sign" layer to not supported.
Update support "Floor" layer to limited support.
Tickets: 88871, 88693
--
Porting: https://github.com/openvinotoolkit/openvino/pull/13995
Add "Floor" in Known Layers Limitations section.
Add "ConvTranspose" in Known Layers Limitations section.
Add "GatherElements" in Known Layers Limitations section.
Tickets: 88871, 75208, 88690

[DOCS] Supported Layers update - for 22.3

---

docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
docs/OV_Runtime_UG/supported_plugins/VPU.md

Porting: https://github.com/openvinotoolkit/openvino/pull/13580
Changing Eltwise-LessEqual layer to Not Supported.
Porting: https://github.com/openvinotoolkit/openvino/pull/13997
Update support "Sign" layer to not supported.
Update support "Floor" layer to limited support.
Tickets: 88871, 88693
Porting: https://github.com/openvinotoolkit/openvino/pull/13995
Add "Floor" in Known Layers Limitations section.
Add "ConvTranspose" in Known Layers Limitations section.
Add "GatherElements" in Known Layers Limitations section.
Tickets: 88871, 75208, 88690

[DOCS] Supported Layers update - for 22.2

---

docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
docs/OV_Runtime_UG/supported_plugins/VPU.md

Porting: https://github.com/openvinotoolkit/openvino/pull/13580
Changing Eltwise-LessEqual layer to Not Supported.
Porting: https://github.com/openvinotoolkit/openvino/pull/13997
Update support "Sign" layer to not supported.
Update support "Floor" layer to limited support.
Tickets: 88871, 88693
Porting: https://github.com/openvinotoolkit/openvino/pull/13995
Add "Floor" in Known Layers Limitations section.
Add "ConvTranspose" in Known Layers Limitations section.
Add "GatherElements" in Known Layers Limitations section.
Tickets: 88871, 75208, 88690

[DOCS] Supported Layers update - for 22.1

---

src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/models_pbtxt/model_savev2.pbtxt
src/frontends/tensorflow_common/include/helper_transforms/unsupported_const_to_result_remover.hpp
src/frontends/tensorflow_common/src/helper_transforms/unsupported_const_to_result_remover.cpp
src/frontends/tensorflow_common/src/op/const.cpp
src/frontends/tensorflow_common/src/op/no_op.cpp

**Details:** Support SaveV2 operation. Also, implement transformation to remove UnsupportedConstant to Result isolated sub-graphs. It allows to convert one more model OOB.
**Ticket:** 102648

[TF FE] Support SaveV2 operation

---

src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_tile_8x8_4x4.cpp
src/plugins/intel_gpu/tests/fusions/permute_fusion_test.cpp

- Optimized permute kernel cannot be fused with both eltwise + reorder. So prevented selection of optimized kernel for such case. However it may be better not to fuse reorder instead in such case. Need further investigation with performance impact. 
- 93264

[GPU] Optimized permute kernel cannot be fused with both eltwise + reorder.

---

src/frontends/pytorch/src/op/full.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_empty.py

- `aten::empty` operator has been added
- layer test for this operator has been added
- 101075
- Generally in PyTorch `aten::empty` operator returns a tensor with uninitialized data, but we don't support such case in OV, so I decided to return a tensor filled with zeros. My solution is based on: https://github.com/pytorch/pytorch/blob/b41e2779f2e24364515d3980e660a6bb23ef5926/torch/onnx/symbolic_opset9.py#L3554

[PT FE] Add aten::empty operator with layer test

---

src/plugins/intel_gpu/src/plugin/plugin.cpp

- Show num_ccs from hello_query_device through RANGE_FOR_STREAM property.
This is backport of #15525

[GPU] Show num_ccs for RANGE_FOR_STREAMS

---

src/core/src/preprocess/pre_post_process.cpp

- Fixes a compilation warning produced by GCC-9
`openvino/src/core/src/preprocess/pre_post_process.cpp:288:32: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]`

PrePostProcessor - compilation warning fix

---

cmake/packaging/debian.cmake
samples/cpp/benchmark_app/CMakeLists.txt

- To avoid distribute-dependent package names in dependencies. Now, the list is unified and dependency name is resolved automatically.

DEB: use alternative package names for nlohmann json

---

cmake/coverage.cmake

- Excluded 2 files (CMakeCXXCompilerId.cpp, CMakeCCompilerId.c) from coverage report. It fixes ov_coverage target
- CVS-102343

Fix ov_coverage target

---

src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
src/plugins/intel_gpu/src/graph/gemm.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/include/primitive_type_base.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/strided_slice.cpp
src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/src/runtime/layout.cpp
src/plugins/intel_gpu/tests/passes/handle_reshape.cpp
src/plugins/intel_gpu/tests/shape_infer/crop_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/reduce_si_test.cpp
src/plugins/intel_gpu/tests/shape_infer/strided_slice_si_test.cpp
src/plugins/intel_gpu/tests/test_cases/non_max_suppression_test.cpp

- Check shape rank in `layout::operator==` to ensure that reshapes are not removed from the graph if those change tensor rank
- Fix strided slice shape infer impl to support begin/end/stride shape < input0 rank
- Gemm primitive now checks count of inputs from primitive to avoid use of fused primitive input

[GPU] Minor fixes for dynamic models

---

src/frontends/tensorflow_common/src/op/fused_batch_norm.cpp
tests/layer_tests/tensorflow_tests/test_tf_FusedBatchNorm.py

**Details:** Fix FusedBatchNormV3 in case of mean and variance empty tensors
**Ticket:** 99675

[TF FE] Fix FusedBatchNormV3 in case of mean and variance empty tensors

---

src/tests/functional/plugin/conformance/subgraphs_dumper/src/ops_cache.cpp
src/tests/functional/plugin/conformance/test_runner/conformance_infra/include/conformance.hpp
src/tests/functional/plugin/conformance/test_runner/conformance_infra/src/read_ir_test/read_ir.cpp
src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir_compare_with_refs.cpp
src/tests/ie_test_utils/common_test_utils/file_utils.hpp
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/rename_conformance_ir.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/test_cache.lst

* Example of serialized IR: `/opt/repo/conformance_ir/static/Add/f32/Add_sjdskdnm.xml` -> `/opt/repo/conformance_ir/static/Add-1/f32/Add_sjdskdnm.xml`
* Example of new test_name:
`conformance_Add/ReadIRTest.ReadIR/Op=Add.1_Type=f32_IR=1268_Device=CPU_Config=()`
- *103437*

[CONFORMANCE] Change Name of ReadIR tests and op serialization folder by `subgraphsDumper`

---

tests/lib/src/common_utils.h

- avoid division by zero error (and thus failing test suites) on Windows where RAND_MAX is only 0x7FFF
- 102074

Correct random number generation

---

src/inference/src/threading/ie_parallel_custom_arena.cpp

- *On ubuntu22.04, system default tbb is oneTBB 2021.5 and tbbbind dynamic library does not exist, in this case the prebuilt tbbbind static library should be used*
- *100340*

22.3-remove tbb version check for using tbbbind static library

---

src/frontends/pytorch/src/op/to.cpp
tests/layer_tests/pytorch_tests/test_to.py

- *added support aten::to with 8 arguments (in PyTorch named as aten::to.dtype_layout), this case for tensor.to(other.device) in tracing mode*
tested on t5 models family from huggingface
This PR is not cover tensor.to(torch.device) in scripting mode, where prim::device take place, I stayed it for  @mmikolajcz (as part of work on https://github.com/openvinotoolkit/openvino/pull/15563)

[PT FE] aten::to extend op support for device tracing case

---

src/plugins/intel_cpu/src/ngraph_transformations/convert_to_cpu_specific_opset.hpp
src/plugins/intel_cpu/src/transformation_pipeline.cpp

- *Optimize number of pass::Validate calls in postLPT, postSnipppet, snippets and ConvertToCPUSpecificOpset managers*
- *97815*

[CPU] Optimize number of pass::Validate in transformation pipeline

---

src/frontends/pytorch/src/op/masked_fill.cpp
tests/layer_tests/pytorch_tests/test_masked_fill.py

- *fixed aten:masked_fill translator for non float32 cases and non constant values*
- *exteneded tests*
tested on bart and led models families from hf

[PT FE]: update masked_fill support for multiple precisions

---

src/plugins/intel_gpu/src/plugin/ops/eltwise.cpp

- Should not reshape to 4D for < 4D tensor when new shape infer is used.

[GPU] Minor fix for dynamic shape

---

src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/models_pbtxt/model_with_const_result.pbtxt
src/frontends/tensorflow_common/include/helper_transforms/const_to_result_remover.hpp
src/frontends/tensorflow_common/src/helper_transforms/const_to_result_remover.cpp

**Details:** Add Const to Result removing transformation. TensorFlow can remain training artifacts in models. It can be multiple isolated Constant nodes storing training artifacts. In IR they are expressed in a form of Const to Result sub-graphs. Multiple sub-graphs in the model can significantly affect performance.
**Ticket:** 103927

[TF FE] Add Const to Result removing transformation

---

src/frontends/onnx/frontend/src/core/transform.cpp
src/frontends/onnx/tests/models/transformations/celu_with_initializers.prototxt
src/frontends/onnx/tests/onnx_import.in.cpp

- Fixes the TypeProto retrieval for ONNX context dependent functions
- When the function Node is connected to an initializer it's possible to create a TypeProto on the fly using initializer's descriptor
- 103452

ONNX functions expanding

---

src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h

Since the FC node always has a constant tenzor on its second input the OC size is always static, and we can exploit this fact and initialize the `dnnl::primitive_attr` object only once on the `createPrimitive` stage. This modification helps to save a lot of `prepareParams` time in the case of dynamic shapes.

[CPU] Use static post ops in the FC node

---

src/frontends/tensorflow_common/src/op/dynamic_partition.cpp

**Details:** Optimize DynamicPartition translator. It avoids squared complexity to compute split lengths for each partition
**Ticket:** 103656
Before:
After:

[TF FE] Optimize DynamicPartition translator

---

src/tests/functional/plugin/conformance/test_runner/conformance_infra/include/conformance.hpp
src/tests/functional/plugin/conformance/test_runner/conformance_infra/include/gflag_config.hpp
src/tests/functional/plugin/conformance/test_runner/conformance_infra/include/read_ir_test/read_ir.hpp
src/tests/functional/plugin/conformance/test_runner/conformance_infra/src/main.cpp
src/tests/functional/plugin/conformance/test_runner/conformance_infra/src/read_ir_test/read_ir.cpp
src/tests/functional/plugin/conformance/test_runner/conformance_infra/src/skip_tests_config.cpp
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp

- *Add new command-line argument for conformance to enable using pre-generated reference*
- *If `ref_dir=""` then use default scenario*
- *102268*

[CONFORMANCE] Enable ref cache if it exists

---

src/plugins/intel_cpu/src/emitters/utils.cpp
src/plugins/intel_cpu/src/emitters/utils.hpp

- *Register printing utilities for JIT kennels of CPU plugin. Invoke RegPrinter::print method inside JIT kernels.*
-  *Param:*
```
The following combinations of Register types and precisions are supported.
fp32         int32         int8         u8
Vmm        Yes          Yes           No          No
Reg64      Yes          Yes           No          No
Reg32      Yes          Yes           No          No
Reg16      No           No            Yes         Yes
Reg8       No           No            Yes         Yes
```
- *Usage:*
```
Here are some examples. Note that user friendly register name will be printed, if it has been set.
While original Xbyak register name will always be printed.
Example 1:
Invocation: RegPrinter::print<float>(*this, vmm_val, "vmm_val");
Console:    vmm_val | ymm0: …
```

[CPU] Register printing utilities

---

src/tests/functional/plugin/shared/include/snippets/matmul.hpp
src/tests/functional/plugin/shared/src/snippets/matmul.cpp

- *Linker issue fix in snippets tests. There are two TransposeMatMul tests in the same namespace ov::test::snippets*

Snippets: linker issue fix in tests

---

src/tests/ie_test_utils/functional_test_utils/src/plugin_cache.cpp

- Remove WA for myriad plugin in tests because it is not longer needed
- CVS-104079

Remove WA for myriad plugin

---

src/plugins/auto/auto_executable_network.cpp

- Prioritize to get ov::model_name from CompiledModel(ExecutableNetwork) of acceleration device (CPU) since the target device CompiledModel(ExecutableNetwork) may not be ready.
- Add the lock to guarantee the concurrency safe 
- 96206

[AUTO] Failed to get the ov::model_name when loading network to target device is not ready

---

src/frontends/pytorch/src/op/narrow.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_narrow.py

- add support for `aten::narrow`
- add test coverage
- update `op_table.cpp`
- 101085
- This is continuation of the following PR: https://github.com/openvinotoolkit/openvino/pull/15493

[PT FE] Add aten::narrow operator with layer test

---

cmake/developer_package/compile_flags/os_flags.cmake

Using a custom linker leads to a compilation error, because `ov_try_use_gold_linker` overrides the linker used.
```
"cacheVariables": {
"CMAKE_EXE_LINKER_FLAGS": "-B /usr/libexec/mold -Wl,--fork -Wl,--quick-exit -Wl,--thread-count=32",
"CMAKE_MODULE_LINKER_FLAGS": "-B /usr/libexec/mold -Wl,--fork -Wl,--quick-exit -Wl,--thread-count=32",
"CMAKE_SHARED_LINKER_FLAGS": "-B /usr/libexec/mold -Wl,--fork -Wl,--quick-exit -Wl,--thread-count=32"
}
```
Error message:
```
[build] /usr/bin/ld.gold: --fork: unknown option
[build] /usr/bin/ld.gold: use the --help option for usage information
[build] collect2: error: ld returned 1 exit status
```
- *ticket-id*

Make an exception for mold linker in ov_try_use_gold_linker cmake function

---

src/frontends/tensorflow/src/op/queue_dequeue.cpp
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/models_pbtxt/model_with_queue_ops2.pbtxt

**Details:** Fix auto-pruning for QueueDequeue operation. It allows OOB conversion for attrack-coco-multi model.
**Ticket:** 103793

[TF FE] Fix auto-pruning for QueueDequeue operation

---

cmake/developer_package/packaging/rpm/post_build.cmake

Supported rpmlint versions less 2.0

---

src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/plugins/intel_gpu/src/plugin/remote_context.cpp

- Fix remote blob memory checking failure due to the adjusted shape for cldnn::tensor

[GPU] Fix remote blob creation to use original shape

---

src/bindings/python/wheel/requirements-dev.txt

- To enable platforms like openSUSE where patchelf is not available from system level package manager

Install patchelf for aarch64 linux

---

src/bindings/python/tests/test_graph/test_manager.py
src/bindings/python/tests/test_transformations/test_manager.py
src/bindings/python/tests/test_transformations/test_offline_api.py
src/bindings/python/tests_compatibility/test_ngraph/test_einsum.py
src/bindings/python/tests_compatibility/test_ngraph/test_ops_fused.py

- Some overloadings of `register_pass` are deprecated and should be removed in this release, so I updated tests
-  17 warnings -> 0 warnings for `tests` folder.
-  24 warnings -> 0 warnings for `tests_compatibility` folder.
- 104388

[PyOV] Fix deprecation warning in tests

---

src/core/src/op/normalize_l2.cpp
src/core/tests/type_prop/normalize_l2.cpp

* Normalize axes in operation NormalizeL2
* Add test for negative axes
* https://github.com/openvinotoolkit/openvino/pull/15841

Port: [NormalizeL2] normalization of reduction axes (#15841)

---

src/plugins/intel_gpu/include/intel_gpu/plugin/compiled_model.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/plugin.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/plugin/compiled_model.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/plugin/caching_tests.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp

- For dynamic shape models, kernel caching is enabled instead of model caching.
- Now, model caching is the default caching policy instead of kernel caching.
- 97997

[GPU] Fallback to kernel caching in the case of dynamic models

---

src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/graph/gemm.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp
src/plugins/intel_gpu/src/graph/include/layout_optimizer.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

oneDNN FC always run bfyx.
It prevent the wrong format selection from FC's around because undetermined impl_type.
- *ticket-id*

[GPU] Add oneDNN FC preferred_format to bfyx

---

src/tests/functional/plugin/gpu/single_layer_tests/dynamic/split.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/variadic_split.hpp
src/tests/functional/shared_test_classes/src/single_layer/variadic_split.cpp
src/tests/functional/shared_test_classes/src/subgraph/variadic_split_pad.cpp
src/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/builders.hpp
src/tests/ngraph_helpers/ngraph_functions/src/variadic_split.cpp

- *Make axis of VariadicSplit int in tests to support negative values*
```
2: axis. Axis along data to split. A scalar or tensor with shape [1] of type T2 with value from range -rank(data) .. rank(data)-1. Negative values address dimensions from the end. Required.
```
[VariadicSplit](https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/movement/VariadicSplit_1.md)
- *ticket-id*

[TESTS] make axis of VariadicSplit int in tests to support negative values

---

src/common/snippets/src/pass/convert_constants.cpp
src/common/snippets/src/pass/convert_power_to_powerstatic.cpp

- *Fixed CC for Snippets - there was missed name for matcher pass `ConvertConstantsToScalars`*
- *Fixed ITT task name for `ConvertPowerToPowerStatic` pass*
- *104501*

[Snippets] Added matcher_name in ConvertConstantsToScalars pass

---

samples/cpp/benchmark_app/CMakeLists.txt
samples/cpp/speech_sample/CMakeLists.txt

```
CMake Error at benchmark_app/CMakeLists.txt:29 (add_library):
add_library cannot create ALIAS target "nlohmann_json::nlohmann_json"
because target "nlohmann_json" is imported but not globally visible.
```

Fixed samples build on Debian 10 with cmake 3.13

---

src/plugins/intel_gpu/include/intel_gpu/graph/serialization/binary_buffer.hpp
src/plugins/intel_gpu/src/graph/data.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/compiled_model.cpp

- This PR enables sharing constant data across multiple streams in deserialized models.
- 104513

[GPU] Sharing constant data memories across multiple streams

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/tests/passes/remove_redundant_reorders_tests.cpp

- Fix dep reorder node's output format to be saved to the current reorder node's `output_format` during removing dep reorder node in `remove_redundant_reorders` opt pass
- 103951

[GPU] Fix output format not changing at runtime

---

cmake/developer_package/api_validator/api_validator.cmake

- See https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/validating-windows-drivers#known-apivalidator-issues

Turn off apiValidator for ARM64 WoA hosts

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/plugin/graph.cpp

- This PR enables get `exec_graph` and `pc` (performance counter) from deserialized models.
- 97995

[GPU] Enabled exec_graph and pc in deserialized models

---

tests/layer_tests/tensorflow_tests/test_tf_CTCGreedyDecoder.py
tests/layer_tests/tensorflow_tests/test_tf_Conv2D.py
tests/layer_tests/tensorflow_tests/test_tf_DynamicPartition.py
tests/layer_tests/tensorflow_tests/test_tf_If.py
tests/layer_tests/tensorflow_tests/test_tf_IsFinite.py
tests/layer_tests/tensorflow_tests/test_tf_IsInf.py
tests/layer_tests/tensorflow_tests/test_tf_IsNan.py
tests/layer_tests/tensorflow_tests/test_tf_L2Loss.py

**Details:** Mark-up xfailed layer tests on GPU in nightly

[TF FE] Mark-up xfailed layer tests on GPU in nightly

---

src/core/include/openvino/core/model.hpp
src/core/src/model.cpp
src/core/tests/model.cpp

- Found that check for creating `Model` from `shared_ptr<Node> == nullptr` was missed (that called when a user tries to create it in python as `Model(None, [])` that caused segfault)
- 
- 102965

Check Node in Model creation

---

cmake/developer_package/api_validator/api_validator.cmake
src/cmake/ie_parallel.cmake
src/cmake/openvino.cmake

Apply Apivalidator to TBB and TBBBind libs

---

src/plugins/intel_cpu/src/docs/README.md
src/plugins/intel_cpu/src/docs/compilation_options.md
src/plugins/intel_cpu/src/docs/logging.md
src/plugins/intel_cpu/tests/functional/CMakeLists.txt
src/plugins/intel_cpu/tests/functional/specific_tests.cmake
src/plugins/intel_cpu/tests/functional/target_per_test.cmake

* `ENABLE_CPU_SUBSET_TESTS_PATH="relative/path/to/test/file"`
* Example: `-DENABLE_CPU_SUBSET_TESTS_PATH="single_layer_tests/convolution.cpp subgraph_tests/src/mha.cpp"`
* Specifies the list of relative paths to functional tests which will be included into the new target `ov_cpu_func_tests_subset`
* When the option is specified, the target `ov_cpu_func_tests` is excluded from the target `all`
* Motivation: To reduce overhead of running / debugging the full test scope
* `DENABLE_CPU_SPECIFIC_TARGET_PER_TEST=ON`
* Generates specific make target for every file from `single_layer_tests` and `subgraph_tests` directories
* Examples of the generated targets:
- `ov_cpu_func_slt_convolution` (single_layer_tests/convolution.cpp)
- `ov_cpu_func_subgraph_mha` (subgraph_tests/src/mha.cpp)
* All the …

[CPU][TESTS] Add options to manage test targets and scope

---

src/common/transformations/src/transformations/common_optimizations/strides_optimization.cpp
src/common/transformations/tests/common_optimizations/strides_optimization.cpp
src/common/transformations/tests/offline_transformations/pruning_test.cpp

Backport of #15796
* Add rt info propagation to StridesOptimization
* Enable rt info check for pruning tests
- 68696
- 103938

[Transformations] Enable missing runtime info check

---

src/plugins/intel_cpu/src/ngraph_transformations/convert_matmul_to_fc.cpp
src/plugins/intel_cpu/tests/unit/ngraph_transformations/convert_matmul_test.cpp

- *ConvertMatMulToFC: don't perform the transformation in case of per-batch constant*
- [*GitHub issue #15819*](https://github.com/openvinotoolkit/openvino/issues/15819)
- *IR comparison has been run on local model cache. The validation did not detect any differences on any model.*

[CPU] ConvertMatMulToFC fix

---

src/inference/src/dev/converter_utils.cpp

- `old_info.execution_index` wasn't initalized
- 104206

Fix coverity uninialized variable

---

src/core/include/openvino/core/graph_util.hpp
src/core/tests/model.cpp

- For the moment any loop (generated with `replace_node` or `add_control_dependency`) leads to infinite execution. In this case added a detector which checks that there is no nodes visited more than twice. If loop detected, throw exception
- 102982

Detect loops in topological_sort

---

tests/layer_tests/mo_python_api_tests/test_legacy_exts/test_config_transform/front/custom_transform.py
tests/layer_tests/mo_python_api_tests/test_mo_convert_complex_params.py
tests/layer_tests/mo_python_api_tests/test_transform_config/test_config.json
tools/mo/openvino/tools/mo/utils/class_registration.py

Custom replacement are registered in global class field CustomReplacementRegistry.registry.
If convert_model() runs multiple times this field keeps previously registered custom replacements which break MO pipeline.
Solution: Clear CustomReplacementRegistry.registry at start of convert_model().
Ticket: 104326, 104379
Code:
Validation:
Documentation:

Clearing of CustomReplacementRegistry.registry in convert_model()

---

src/bindings/python/wheel/requirements-dev.txt

- Now that https://github.com/openvinotoolkit/openvino/pull/16021 has been merged and POT version has been made PEP440 compliant we can remove `setuptools` upper bound.
- Please wait for my confirmation that `openvino-dev` wheel is being generated correctly in CIs before merging
- 101371

[PyOV] Remove `setuptools` upperbound

---

tools/openvino_dev/CMakeLists.txt
tools/openvino_dev/setup.cfg
tools/openvino_dev/setup.py

- Since 2022.3 `openvino-dev` is built using open-source scripts, which missed license files

Added missed licenses to openvino-dev

---

src/core/dev_api/shape_util.hpp
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/adaptive_pooling.cpp
src/plugins/intel_cpu/src/nodes/color_convert.cpp
src/plugins/intel_cpu/src/nodes/deconv.cpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/generic.cpp
src/plugins/intel_cpu/src/nodes/matmul.cpp
src/plugins/intel_cpu/src/nodes/one_hot.cpp
src/plugins/intel_cpu/src/nodes/priorbox.cpp
src/plugins/intel_cpu/src/nodes/priorbox_clustered.cpp
src/plugins/intel_cpu/src/nodes/reference.cpp
src/plugins/intel_cpu/src/nodes/reference.h
src/plugins/intel_cpu/src/nodes/rnn.cpp
src/plugins/intel_cpu/src/nodes/shapeof.cpp
src/plugins/intel_cpu/src/nodes/subgraph.cpp
src/plugins/intel_cpu/src/nodes/subgraph.h
src/plugins/intel_cpu/src/nodes/transpose.cpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference.cpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference.hpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference_cpu.hpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference_internal_dyn.hpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference_ngraph.cpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference_ngraph.hpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference_pass_through.hpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference_status.hpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/custom_op_internal_dyn.cpp
src/plugins/intel_cpu/tests/unit/shape_inference_test/utils.hpp

This PR introduce support for extension operations with so called internal dynamism, i.e. when the output shapes can only be defined after performing the computations, for example NMS operation.
- 99106
- 81379

[CPU] Internal dynamism support for extensions

---

src/plugins/intel_cpu/src/graph.cpp

Change the call sequences to prevent possible read out of bounds the executableGraphNodes  vector.
- 105041

[CPU] Prevent out of bounds executableGraphNodes read

---

src/plugins/intel_cpu/CMakeLists.txt
src/plugins/intel_cpu/src/nodes/unique.cpp
src/plugins/intel_cpu/src/utils/blob_dump.cpp
src/plugins/intel_cpu/tests/functional/bfloat16/bfloat16_helpers.hpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/denormal_check.cpp
src/tests/ie_test_utils/functional_test_utils/include/functional_test_utils/blob_utils.hpp

- *Remove: ie_add_compiler_flags(-Wno-sequence-point)*
- *Remove: ie_add_compiler_flags(-Wno-strict-aliasing)*
- *Fix corresponding warnings*
- *104795*

Fix warning: sequence point strict aliasing

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_kernel_ref.cpp
src/plugins/intel_gpu/tests/passes/prepare_primitive_fusing_test.cpp

- Fix removing redundant reshapes is skipped so that only the current reshape is not removed if only the input size of dependency reshape is not 1 among the sequence of reshapes in `prepare_primitive_fusing` opt pass
- Fix to set kernel arguments correctly when only the input tensor of `gather` is dynamic
- 104936

[GPU] Minor fixes for dynamic model

---

src/common/snippets/src/utils.cpp
src/common/snippets/tests/src/pass/collapse_subgraph.cpp
src/tests/ngraph_helpers/snippets_ngraph_functions/CMakeLists.txt
src/tests/ngraph_helpers/snippets_ngraph_functions/include/subgraph_fq.hpp
src/tests/ngraph_helpers/snippets_ngraph_functions/src/subgraph_fq.cpp

- *Before `get_non_scalar_constant_count_for_fq` returned incorrect number of potential constants for optimized FQ*
- *103438*

[Snippets] Fixed potential constants getter for FQ

---

src/plugins/intel_cpu/src/emitters/jit_load_store_emitters.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/mvn.cpp

- *remove redundant fill as load_byte is reused*
- *fill should be after precision convert*
- *93987*

single place to fill tails of load emitter

---

src/plugins/intel_gpu/include/intel_gpu/primitives/convolution.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/quantize.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/pre_replace_deconv.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/quantize.cpp
src/plugins/intel_gpu/src/graph/include/convolution_inst.h
src/plugins/intel_gpu/src/graph/include/deformable_convolution_inst.h
src/plugins/intel_gpu/src/graph/include/quantize_inst.h
src/plugins/intel_gpu/src/graph/quantize.cpp
src/plugins/intel_gpu/tests/test_cases/hash_key_gpu_test.cpp

- `transposed` flag was moved to `convolution` primitive
- scale shift opt related parameters were moved from node to `quantize` primitive
- now those primitives are created from scratch if we need to update such parameters instead of modifying program_node
- this will allow to remove hashing for program_node and do it for kernel_impl_params only

[GPU] Move some op parameters from node to primitive class

---

src/common/transformations/src/transformations/op_conversions/reduce_l2_decomposition.cpp
src/inference/tests/unit/query_model_test.cpp

- *Constant name is missing in fused names of new operations in ReduceL2Decomposition which lead to problem after subsequent call of  ConvertReduceToPooling transformation. Model facenet is failed on HETERO:NVIDIA,GPU device due to cut Constant.*
```
Unsupported parameter nodes type in ReduceL2_361 (ReduceL2)
```
- *ticket-id*

Fix RTInfo for ReduceL2Decomposition

---

src/frontends/pytorch/src/input_model.cpp
src/frontends/pytorch/src/input_model.hpp
src/frontends/pytorch/src/place.cpp
src/frontends/pytorch/src/place.hpp
src/frontends/pytorch/src/translate_session.cpp
src/frontends/pytorch/src/translate_session.hpp
tests/layer_tests/py_frontend_tests/test_torch_frontend.py
tests/layer_tests/pytorch_tests/test_rsub.py

- *Implement `get_inputs`, `get_outputs`, `get_place_by_tensor_name`, `set_partial_shape`, `get_partial_shape`, `set_element_type`, `get_element_type`, `set_tensor_value` to allow specifying input element type, partial shape and value before conversion*
- *102339*

[PT FE] Support set/get element type, shape and value in PyTorch FE InputModel

---

src/frontends/common/include/openvino/frontend/decoder.hpp
src/frontends/tensorflow/src/decoder_argdef.cpp
src/frontends/tensorflow/src/decoder_argdef.hpp
src/frontends/tensorflow/src/decoder_proto.cpp
src/frontends/tensorflow/src/decoder_proto.hpp
src/frontends/tensorflow/src/translate_session.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/models_pbtxt/partitioned_call2.pbtxt
src/frontends/tensorflow/tests/test_models/models_pbtxt/partitioned_call2.py
src/frontends/tensorflow_common/include/helper_ops/internal_operation.hpp
src/frontends/tensorflow_lite/src/decoder_flatbuffer.cpp
src/frontends/tensorflow_lite/src/decoder_flatbuffer.h
src/frontends/tensorflow_lite/src/decoder_map.hpp

**Details:** This is a corner case because body graph nodes have named output ports. This allows to support custom RetinaNet model.
**Ticket:** 97993

[TF FE] Support Multi-output Body Graph nodes with named ports

---

src/inference/dev_api/cpp_interfaces/interface/ie_internal_plugin_config.hpp
src/inference/src/compilation_context.cpp
src/inference/src/compilation_context.hpp
src/inference/src/core.cpp
src/inference/src/dev/core_impl.cpp
src/inference/src/dev/core_impl.hpp
src/inference/src/dev/icompiled_model.cpp
src/inference/src/dev/plugin.cpp
src/inference/src/dev/plugin.hpp
src/inference/src/ie_core.cpp
src/inference/tests/unit/ie_compilation_context_test.cpp
src/plugins/auto/plugin.cpp
src/plugins/hetero/executable_network.cpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/template/src/plugin.cpp

- *item1*
- *...*
- *ticket-id*

CoreImpl small refactoring

---

src/plugins/intel_gpu/src/graph/impls/ocl/border.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/border_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/border/border_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/border/border_kernel_ref.cpp
src/plugins/intel_gpu/tests/test_cases/border_gpu_test.cpp

- Shape agnostic Pad ref kernel implementation
- 95104

[GPU] Added shape agnostic Pad ref kernel

---

src/frontends/pytorch/src/place.cpp

```
In file included from /openvino/src/frontends/pytorch/src/place.cpp:5:
/openvino/src/frontends/pytorch/src/place.hpp:37:37: error: private field 'm_input_model' is not used [-Werror,-Wunused-private-field]
const ov::frontend::InputModel& m_input_model;
^
1 error generated.
```
On Android arm64 in post commit https://dev.azure.com/openvinoci/dldt/_build/results?buildId=510345&view=logs&j=92ba3447-fcaa-530d-6438-b829fe1e7d1d&t=b0a91e75-8666-5718-e63e-df215ecb48f9&l=2188

Fixed PT FE compilation with clang on macOS

---

.ci/azure/linux.yml
cmake/dependencies.cmake
src/plugins/intel_gna/src/gna_device.hpp
src/plugins/intel_gna/tests/functional/pass_tests/conv_with_padding.cpp

- Changed GNA library version from 3.0.0.1910 to 3.5.0.1906
- 94946

[GNA] Update GNA library version to 3.5.0.1906

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Previously, PR15386 changed allocation of memory of primitives which are to be used as shape infer dep to host memory, for better shape infer perf.
- However this causes cache coherence issue in dGPU.
- Reverting this change so that the memory will be allocated to device
- 105246

[GPU] Revert PR15386's change

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing_through.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp

- Fix eltwise not to be raised above dependency unsqueeze(2D->4D) unintentionally for dynamic shape in `prepare_primitive_fusing_through` opt pass
- Fix to check full tensor only for static shape on onednn gemm creation
- 104871

[GPU] Minor fixes for dynamic BERT models

---

.ci/azure/linux.yml
.ci/azure/windows.yml

Disable sentencepiece extension in static build to prevent double linking of protobuf
Example of failure https://dev.azure.com/openvinoci/dldt/_build/results?buildId=511273&view=logs&jobId=982848f2-7f8d-5e57-730a-8df1e5f991ba&j=982848f2-7f8d-5e57-730a-8df1e5f991ba&t=e34f4ac2-e568-502a-2d74-a30ae92fdad2

Disable sentencepiece extension in static build

---

src/plugins/intel_cpu/src/emitters/jit_emitter.hpp
src/plugins/intel_cpu/src/emitters/jit_snippets_emitters.hpp

- *fix warnings by telling compiler explicitly that function is overloaded or override*

fix warnings of overloaded virtual function

---

samples/cpp/benchmark_app/main.cpp
tools/benchmark_tool/openvino/tools/benchmark/main.py

Ticket: E-71637
With the latest OV master benchmark_app output looks like this:
It should be like this:
The `performance_hint` parameter is ignored.
These changes seem to cause this behavior:
- https://github.com/openvinotoolkit/openvino/commit/a088d1ab7dd92d471f392003df05d3daa8c903cd#diff-e7a536b4318b2270a4ee67f723b8ff57e9a5aed0928c11fa46e5a0b02db6300fL609-L613
- https://github.com/openvinotoolkit/openvino/commit/a088d1ab7dd92d471f392003df05d3daa8c903cd#diff-f311f9345d31892350d1e310ba8f0119806af62f514f7936f632df7fa6a32995L325
I tested the changes from this PR in our Net-Validation CI job. But feel free to point out any other OV check to confirm the fix.

[VPUX] - benchmark app issue fix - PERFORMANCE_HINT: UNDEFINED

---

docs/install_guides/installing-openvino-pip.md

This PR addresses the issue: https://github.com/openvinotoolkit/openvino/issues/15090
The tabs for `Linux and macOS` and `Windows` are linked.

[DOCS] Align tabs in 'Install from PyPI' article - for 22.3

---

src/frontends/tensorflow/src/decoder_argdef.cpp
src/frontends/tensorflow/src/decoder_proto.cpp
src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/src/translate_session.cpp
src/frontends/tensorflow/src/translate_session.hpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_unsupported_op_itergetnext.py
src/frontends/tensorflow_common/include/utils.hpp
src/frontends/tensorflow_common/src/op/const.cpp
src/frontends/tensorflow_common/src/op/fused_batch_norm.cpp
tools/mo/openvino/tools/mo/moc_frontend/pipeline.py

**Details:** Now the conversion pipeline will convert all unsupported operations to Framework nodes, It is done with a hope that sub-graphs with Framework Nodes will be cut in later stages like auto-pruning and the conversion will not be failed immediately.

[TF FE] Convert a model with Framework nodes

---

samples/cpp/common/utils/src/args_helper.cpp

Ticket 100990
Python benchmark_app already prohibits FP16 and FP32.

Prohibit FP16 FP32 values for cpp benchmark_app

---

docs/OV_Runtime_UG/migration_ov_2_0/preprocessing.md

Fixing directives for code snippets. Switching to reST.

DOCS shift to rst - `Preprocessing` article

---

src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/nodes/input.cpp
src/plugins/intel_cpu/src/plugin.cpp

- Optimize weights memory usage by avoiding cloning weights with sub-normals when DAZ is set
- Introduce a util function `is_denormals_as_zero_set()`
- fix duplicate definitions issue by separate `denormals.hpp` into a hpp and cpp
- CVS-82367

Only clone weights when DAZ is not set

---

tools/mo/openvino/tools/mo/front/tf/loader.py
tools/mo/openvino/tools/mo/utils/pipeline_config.py
tools/mo/unit_tests/mo/front/tf/ObjectDetectionAPI_test.py
tools/mo/unit_tests/mo/front/tf/convert_to_pb_test.py
tools/mo/unit_tests/mo/front/tf/test_configs/config1.config
tools/mo/unit_tests/mo/front/tf/test_configs/config2.config

After loading of Meta Graph with tf_v1.train.import_meta_graph() models TF2 keeps loaded graph in memory in global keras session. So next loading may fail if graphs contain nodes with different names. This leads to failing of convert_model() if used twice or more for Meta Graph's. 
Another problem is that PipelineConfig keeps internal values from previous convert_model() runs. This leads to failing  of convert_model() if used twice or more for models with pipeline configs.
Solution: 
Clear TF session for TF2. For TF1 problem does not reproduce.
Clear PipelineConfig before every config reading.
Ticket: 105439, 104381
Code:
Validation:
Documentation:

Fixed clearing of pipeline config params and TF session in convert_model()

---

src/plugins/intel_cpu/src/graph_dumper.cpp

- *when openvino is compiled with option -DENABLE_DEBUG_CAPS=ON, run ./ov_cpu_func_tests  in a docker contain with a memory limit of 8G, then a crash error will appear for test case "smoke_MemoryTest/MemoryTest.CompareWithRefs/transformation=LOW_LATENCY_V2_iteration_count=3_IS=(3)_netPRC=FP32_trgDev=HETERO:CPU)"*

fix core dump issue for ENABLE_DEBUG_CAPS

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/resample.cpp

- Fix are_data_types_suitable_for_onednn not to invalidate output layout
- Fix seg fault of printing resample node info

[GPU] Minor fixes : are_data_types_suitable_for_onednn not to invalidate output layout

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl
src/plugins/intel_gpu/tests/test_cases/strided_slice_gpu_test.cpp

- If begin/end/stride are inputs with shape `{1}`, then current strided_slice impl works incorrectly as *_GET_INDEX is generated as `(b % 1)`, thus all dimensions have the same index and offset if invalid.

[GPU] Fix strided slice kernel with begin/end/stride as inputs

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_data_bfyx_to_blocked_format.cl

- Change activation position in reorder_data_bfyx_to_blocked_format kernel. Activation in load function causes ambiguous call error of fmax/fmin when input/output data type are different.
- 103092

[GPU] change activation position in reorder_data_bfyx_to_blocked_format kernel

---

src/bindings/python/src/openvino/runtime/utils/data_helpers/data_dispatcher.py
src/bindings/python/src/pyopenvino/core/common.cpp
src/bindings/python/tests/test_runtime/test_infer_request.py
src/bindings/python/tests/test_runtime/test_memory_modes.py
src/bindings/python/tests/test_utils/test_data_dispatch.py
src/bindings/python/tests/test_utils/test_utils.py

- Improve implementation of `Constant`/`Tensor` to allow creation of scalars from numpy arrays with 0-dim.
- Updated `data_dispatcher` to use new feature. Adjust the function to correctly consume scalars in other forms.
- Added test cases for new constructors and inference with scalar inputs. Check for data sharing in various cases (in other words, validate inner-workings of `data_dispatcher`).
```python
In [1]: import numpy as np
...: import openvino.runtime as ov
...: 
...: value = np.array(1)
...: t_copy = ov.Tensor(value, shared_memory=False)
...: t_shared = ov.Tensor(value, shared_memory=True)
...: 
In [2]: t_copy.data
Out[2]: array(1)
In [3]: np.shares_memory(t_copy.data, value)
Out[3]: False
In [4]: t_shared.data
Out[4]: array(1)
In [5]: value[()] = 3
In [6]: t_shared.data
Out[6]: …
```

[PyOV] Constant/Tensor from scalars

---

src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/src/gna_graph_compiler.cpp
src/plugins/intel_gna/tests/functional/pass_tests/concat_restrictions.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/permute_concat_concat_permute.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/permute_concat_permute.cpp
src/tests/functional/plugin/shared/include/subgraph_tests/permute_concat_concat_permute.hpp
src/tests/functional/plugin/shared/include/subgraph_tests/permute_concat_permute.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/base/layer_test_utils.hpp
src/tests/functional/shared_test_classes/src/base/layer_test_utils.cpp

Decision was made to change WARNINGS to EXCEPTIONS in case of unsupported Concat to prevent model compilation while it does not work properly.
- Replaced log::warning() with THROW_GNA_EXCEPTION for unsupported Concat
- Updated tests to expect exceptions instead of reading warnings from stdout
- 62674

[GNA] Model with unsupported concat does not produce error

---

src/plugins/intel_gpu/src/graph/program_helpers.cpp
src/plugins/intel_gpu/src/plugin/transformations/convert_pooling_to_reduce.cpp

- Fix to skip `ConvertAvgPoolingToReduce` matcher pass for dynamic shape
- Fix to skip `onednn_add_fusing_helpers::get_add_fusing_type` to check fusing type for post-op input format

[GPU] Minor fixes for dynamic model in dGPU

---

src/plugins/intel_gpu/src/graph/deconvolution.cpp

convolutionbackpropdata:conv3d_transpose in unet3d_mlperf doesn't have bias(),
- *106024*

Fix unet3d mlperf dump

---

src/plugins/intel_gpu/src/kernel_selector/jitter.cpp

- Add condition for activation ceil so it works when data type is fp32 or fp16 only
- 105337

[GPU] add condition for activation ceil so it works when data type is fp32 or fp16 only

---

src/common/offline_transformations/src/compress_quantize_weigths.cpp
src/common/transformations/tests/utils/compress_quantize_weights.cpp

- *CompressQuantizeWeights: support a pattern `Constant{f16}->Convert{f32}` as a FQ data input*
- *105441*

[Transformations] CompressQuantizeWeights: fp16 weights support

---

src/common/transformations/include/transformations/op_conversions/convert_topk11_downgrade.hpp
src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
src/common/transformations/src/transformations/op_conversions/convert_topk11_downgrade.cpp
src/common/transformations/tests/op_conversions/convert_topk11_downgrade_test.cpp

- The downgrade transformation which takes effect when v11's `stable` attribute is set to `false`
- 105860

TopK v11 -> v3 downgrade transformation

---

src/plugins/intel_cpu/src/cpu_memory.cpp
src/plugins/intel_cpu/src/cpu_memory.h
src/plugins/intel_cpu/src/dnnl_extension_utils.cpp
src/plugins/intel_cpu/src/memory_desc/blocked_memory_desc.h
src/plugins/intel_cpu/src/memory_desc/cpu_blocked_memory_desc.cpp
src/plugins/intel_cpu/src/memory_desc/cpu_memory_desc.h
src/plugins/intel_cpu/src/memory_desc/dnnl_blocked_memory_desc.cpp
src/plugins/intel_cpu/src/memory_desc/dnnl_blocked_memory_desc.h
src/plugins/intel_cpu/src/memory_desc/dnnl_memory_desc.cpp
src/plugins/intel_cpu/src/memory_desc/dnnl_memory_desc.h
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/tests/unit/dnnl_memory_test.cpp

CPU memory class was previously designed as a wrapper for oneDNN memory class. However, in the plugin we do not always need oneDNN memory object in our own node implementations, while  oneDNN memory instantiation is not free and we see this overhead especially in the dynamic shapes scenario. This PR changes the logic, now we insatiate oneDNN memory object on demand.
Ticket id:
* 99122

[CPU] Lazy oneDNN memory object creation

---

src/frontends/tensorflow_lite/src/op/one_hot.cpp

- *We rename one hot to fit the requirements of tensorflow common library.*
- *CVS-105549*

CVS-105549 TFL OneHot renamed

---

samples/cpp/benchmark_app/inputs_filling.cpp

A few networks fail (on benchmark_app) with the following errors:
```
[Step 9/11] Creating infer requests and preparing input tensors
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ ERROR ] Check 'false' failed at C:\jenkins\workspace\openVINO-builder-ws\dldt\src\core\src\runtime\ov_tensor.cpp:217:
Check 'element_type == get_element_type()' failed at C:\jenkins\workspace\openVINO-builder-ws\dldt\src\core\src\runtime\itensor.cpp:46:
Tensor data with element type f16, is not representable as pointer to i16 
```

[VPUX] - Tensor data with element type f16, is not representable as pointer to i16

---

src/core/src/util.cpp
src/core/tests/pass/serialization/deterministicity.cpp

- https://github.com/openvinotoolkit/openvino/pull/16330
- Hash generation from onnx file is not deterministic on Windows
- This PR makes it deterministic by memory initialization.
- 105515

making hash generation deterministic

---

tools/mo/openvino/tools/mo/utils/ir_reader/internal_ops/squeeze.py
tools/mo/unit_tests/mo/utils/ir_reader/layer_to_class_test.py

- *Legacy MO never had Squeeze without second input, while frontend can generate such Squeeze. Fix MO Reader to support this case.*
- *104158*

Fix MO Reader for Squeeze without axes

---

src/frontends/onnx/frontend/src/op/hardmax.cpp
src/frontends/onnx/frontend/src/op/topk.cpp
src/frontends/onnx/frontend/src/utils/arg_min_max_factory.cpp

- Switch to TopK v11 in ONNX FE code
- The "default_opset" will be updated to opset11 when https://github.com/openvinotoolkit/openvino/pull/16448 is merged which should unblock the switch to Interpolate v11 in ONNX FE
- 101502

TopK v11 usage in ONNX FE

---

src/plugins/intel_gpu/src/kernel_selector/kernels/eltwise/eltwise_kernel_blocked_opt.cpp
src/plugins/intel_gpu/tests/test_cases/eltwise_gpu_test.cpp

- Fix eltwise_blocked_opt kernel for byxf+fsv16 to fsv16
- 106465

Resolve eltwise kernel build failure

---

src/frontends/tensorflow/src/decoder_argdef.hpp
src/frontends/tensorflow/src/decoder_proto.hpp
src/frontends/tensorflow/src/graph_iterator_proto.hpp

**Details:** TF FE decoders can be invalidated in case destruction of `GraphIteratorProto` or `GraphDef`. It leads to loss of `NodeDef` object in the memory and invalidation of decoders. So we should care of lifetime of `GraphDef` while decoder is alive.

[TF FE] Fix problems with invalidation of decoders

---

src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/test_cases/deconvolution_gpu_test.cpp

- *Fused mem_dep doesn't be considered as shape_infer_dep*
- *100964*

[GPU] Need to exclude fused mem_dep from shape_infer_dep

---

docs/install_guides/installing-openvino-yocto.md
docs/install_guides/troubleshooting-issues.md
docs/install_guides/troubleshooting-steps.md
docs/install_guides/troubleshooting.md

DOCS shift to rst - Troubleshooting

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py

- VPUX contains abs report and other ones are based using rel: https://openvino-ci.toolbox.iotg.sclab.intel.com/blue/organizations/jenkins/private-ci%2FcustomJobs%2Fe2e-tests-linux/detail/e2e-tests-linux/10929/pipeline/
- *ticket-id*

[CONFORMANCE] Fix report gewneration in case of mixed reports: rel and abs

---

src/plugins/intel_cpu/src/memory_desc/dnnl_memory_desc.cpp
src/plugins/intel_cpu/src/memory_desc/dnnl_memory_desc.h
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/common/dnnl_executor.cpp
src/plugins/intel_cpu/src/nodes/common/dnnl_executor.h
src/plugins/intel_cpu/src/nodes/concat.h
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/deconv.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h
src/plugins/intel_cpu/src/nodes/input.h
src/plugins/intel_cpu/src/nodes/interaction.h
src/plugins/intel_cpu/src/nodes/lrn.cpp
src/plugins/intel_cpu/src/nodes/lrn.h
src/plugins/intel_cpu/src/nodes/matmul.cpp
src/plugins/intel_cpu/src/nodes/matmul.h
src/plugins/intel_cpu/src/nodes/pooling.cpp
src/plugins/intel_cpu/src/nodes/pooling.h
src/plugins/intel_cpu/src/nodes/reorder.cpp
src/plugins/intel_cpu/src/nodes/reorder.h
src/plugins/intel_cpu/src/nodes/rnn.cpp
src/plugins/intel_cpu/src/nodes/rnn.h
src/plugins/intel_cpu/src/nodes/softmax.cpp
src/plugins/intel_cpu/src/nodes/softmax.h
src/plugins/intel_cpu/src/nodes/transpose.h

Since v3.1 it was observed that early inefficient dnnl::primitive_desc query became even slower. It was decided to store input, output and scratchpad memory descriptors in the DnnlExecutor to avoid dnnl::primitive_desc query calls at runtime.
- 99126

[CPU] Use Dnnl executor to avoid extra dnnl primitve desc query

---

cmake/developer_package/compile_flags/os_flags.cmake

- Added flag to build with spectre mitigated libraries for prevent usage of Spectre and Meltdown vulnerabilities.
- 102790

Added compilation flag to build with spectre mitigated libraries

---

samples/cpp/benchmark_app/main.cpp
tools/benchmark_tool/openvino/tools/benchmark/main.py
tools/benchmark_tool/openvino/tools/benchmark/parameters.py

Don't warn about values which are explicitly set in -hint. That aligns C++ and Python implementations.
Ticket 106544

py/benchmark_app: fix -hint

---

src/frontends/tensorflow/src/decoder_proto.cpp
src/frontends/tensorflow/src/translate_session.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_partitioned_call_with_unique.py
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_ragged_tensor_to_sparse.py

**Details:** It contains tests imitating a case with Tokenizer extension and raised problems: setting custom type for body graph Parameter via conversion extension, named ports for `RaggedTensorToSparse` and `Unique` operations.

[TF FE] Post leftovers to support the MUSE model in SavedModel format

---

src/inference/dev_api/ie_icore.hpp
src/inference/src/dev/core_impl.cpp
src/inference/src/dev/core_impl.hpp
src/inference/src/dev/core_impl_ie.cpp
src/inference/tests/functional/caching_test.cpp
src/plugins/hetero/executable_network.cpp
src/plugins/hetero/plugin.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_gpu/src/plugin/legacy_api_helper.cpp
src/plugins/template/src/plugin.cpp
src/tests/ie_test_utils/unit_test_utils/mocks/cpp_interfaces/interface/mock_icore.hpp

- Model caching is supposed to be supported if both `import_export` and `ov::caching_properties` are implemented. 
- Secondly, removed code from the Core logic which asks `ov::device::architecture`, because we rely only on caching properties now
- Thirdly, CPU and Template needs to support at least one key in `ov::caching_properties` to be distinguished by caching mechanism
- Plugins need to support `ov::caching_properties` for both API 1.0 and 2.0, while currently some plugins do it only for 2.0 API

Align plugins in caching properties

---

src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/src/backend/gna_limitations.hpp
src/plugins/intel_gna/src/gna_device.cpp
src/plugins/intel_gna/src/gna_device.hpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/tests/unit/gna_memory_alignment.cpp

- Enable 16Byte memory alignment for GNA 3.6 target
- 102861

[GNA] Introduce 16Byte memory alignment for LNL (GNA3.6)

---

src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/module_tests/network_test.cpp

- Currently models with scalar inputs are marked as dynamic which impacts import/export behavior and blocks full model serialization.

[GPU] Fixed invalid is_dynamic flag value for scalar inputs

---

docs/Doxyfile.config

Porting:
https://github.com/openvinotoolkit/openvino/pull/16564
The `ov::hint::num_requests` property key is not shown in documentation. It is not displayed on the Device Properties list: https://docs.openvino.ai/nightly/groupov_runtime_cpp_prop_api.html

[DOCS] `ov::hint::num_requests` - not shown in documentation - fix for 22.3

---

docs/dev/cmake_options_for_custom_comiplation.md

- *Miss libtbbbind in Ubuntu22.04*
- *Low hwloc version can't support hybrid CPUs correctly*
- **

Add notes for oneTBB

---

src/bindings/c/tests/ov_infer_request_test.cpp
src/bindings/python/tests/test_graph/test_manager.py
src/core/tests/frontend/mock_frontend.cpp
src/frontends/ir/src/frontend.cpp
src/frontends/ir/src/os/win/win_mmap_object.cpp
src/frontends/paddle/src/frontend.cpp
src/frontends/pytorch/src/frontend.cpp
src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow_lite/src/frontend.cpp
src/inference/src/ie_network_reader.cpp

- Use `mmap` instead of `read` for IR .bin files. It provides next benefits:
- Small performance improvement on CPU and GPU for big models (~ >50 Mb)
- Careful use of memory by OS (unload unused memory from RAM)
- Weights sharing between processes
- Weights reuse (page caching) for repetitive runs
- 68937

Enable MapAllocator in IR Frontend

---

src/plugins/template/src/plugin.cpp

OpenVino build fails when enabling the ITT Traces flag with the following message:
_**C:\Users\bpereanu\WORK\OpenVinoSources\openvino\src\plugins\template\src\plugin.cpp(166): error C2653: 'TemplatePlugin': is not a class or namespace name**_
Still waiting for the build to finish, I will update the PR when it finishes and can confirm that this fixes the issue.
- *C[VS-107186](https://jira.devtools.intel.com/browse/CVS-107186)*

Fix ITT build fail

---

thirdparty/cnpy/cnpy.h

- Change max array element check in cnpy to avoid out-of-memory error in sanitizer tests
- CVS-105669

Fix sanitizer out-of-memory error

---

src/common/transformations/src/transformations/convert_precision.cpp
src/core/reference/include/ngraph/runtime/reference/convert.hpp
src/core/reference/src/runtime/reference/convert.cpp

GPU pugin enabled ov::hint:inference_precision property suppport which alllows OV users to launch FP16 inference on FP32 models. In that scenario we are facing bad model compilation time due to slow FP32->FP16 precision conversion procedure.
The PR adds optimized implementation for FP32->FP16 conversion routine that allows to significantly speedup (up to several times) FP32 model compilation stage in case of FP16 inference.

[CORE] Added optimized fp32->fp16 precision conversion implementation

---

tests/layer_tests/tensorflow_tests/test_tf_TopKV2.py

**Details:** The CPU plugin recently introduced TopK-11 operation with stable mode and TF FE moved to TopK-11. So we are ready to activate it in the TF FE layer tests.

[TF FE] Activate TopK layer test with the second output in the pre-commit

---

docs/snippets/gpu/context_sharing_va_c.cpp

- Double free in context_sharing_va_c.cpp
- 107183

Fix double free in snippets

---

tools/openvino_dev/requirements_dev.txt.in

- Fix for an issue seen in https://github.com/openvinotoolkit/openvino/network/updates/636684762
- Dependabot doesn't see environment variables
- They can be set, but the variables in this requirement are defined during runtime
- All the work on setting them is not worth it since dependabot will never update `openvino-dev`, as it's our own package with dynamic versioning
- Ignoring the package will do no harm and will let us get rid of an error in workflows
- NA

[PyOV] Dependabot - ignore `openvino-dev` dependency

---

tests/time_tests/scripts/run_timetest.py
tests/time_tests/test_runner/conftest.py
tests/time_tests/test_runner/test_timetest.py

Fixing run_timest python script for input and output precision
Errors: https://openvino-ci.toolbox.iotg.sclab.intel.com/view/Main/job/private-ci/job/developer-services/job/e2e/3743/
- [CVS-104240](https://jira.devtools.intel.com/browse/CVS-104240)

Fixing run_timest python script for input and output precision

---

src/frontends/pytorch/src/transforms/aten_index_replacer.cpp
tests/layer_tests/pytorch_tests/test_index.py

- *ifix bug in detectron reshape shapes are inconsistent in index op*
- *105142*

[PT FE]:  fix aten::index inconsistent reshape

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/transformations/einsum_decomposition.cpp
src/plugins/intel_gpu/src/runtime/layout.cpp
src/plugins/intel_gpu/tests/module_tests/layout_test.cpp
src/plugins/intel_gpu/tests/passes/prepare_buffer_fusing_test.cpp
src/plugins/intel_gpu/tests/test_cases/reshape_gpu_test.cpp

- Avoid redundant weights reordering for formats that can be reinterpreted to each other
- Optimize out dynamic -> static reshape to avoid recompilation
- Disable internal einsum decomposition for dynamic shapes and rely on common transform

[GPU] Don't reorder weights when can reinterpret

---

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp

Force exit without releasing any resources if CL_OUT_OF_RESOURCE is returned from call OpenCL API.
- 106623

[GPU] add WA to avoid hang issue.

---

docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_EfficientDet_Models.md
docs/dev/installing.md

Description:
Corrected command in Convert_EfficientDet_Models.md.
Updated missed data_type=True to 'compress_to_fp16'
Ticket: -
Code:
Validation:
Documentation:

Fixed command lines in MO docs.

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/experimental_detectron_generate_proposals_single_image_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/generate_proposals_ref.cl

- OpenCL kernel should use unique symbol name
- These two kernels were not using unique name
- Test is unnecessary as the test will be very specific to this change.
- 107132

[GPU] Use unique symbol name for typedef

---

src/common/transformations/src/transformations/utils/utils.cpp
src/common/transformations/tests/common_optimizations/nop_elimination.cpp

- Helps to avoid nops for fp16 models (SD2.1 specifically) on GPU

Enable nop elimination for f16 type

---

src/inference/src/os/win/win_system_conf.cpp
src/inference/tests/unit/cpu_map_parser.cpp

According to this https://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr:
**(until C++17)**
If T is an array type U[N], (3-4,6) do not participate in overload resolution if Y(*)[N] is not convertible to T*. If T is an array type U[], (3-4,6) do not participate in overload resolution if Y(*)[] is not convertible to T*. Otherwise, (3-4,6) do not participate in overload resolution if Y* is not convertible to T*.
**(since C++17)**
Additionally:
Uses the delete-expression delete ptr if T is not an array type; delete[] ptr if T is an array type (since C++17) as the deleter. Y must be a complete type. The delete expression must be well-formed, have well-defined behavior and not throw any exceptions. This constructor additionally does not participate in overload resolution if the delete …

[VPUX] - Detected possible vulnerability with shared_ptr

---

src/tests/functional/shared_test_classes/src/subgraph/concat_conv.cpp
src/tests/functional/shared_test_classes/src/subgraph/const_conv_concat.cpp
src/tests/functional/shared_test_classes/src/subgraph/eltwise_conv_eltwise.cpp
src/tests/functional/shared_test_classes/src/subgraph/fc_conv_fc.cpp
src/tests/functional/shared_test_classes/src/subgraph/scaleshift_conv_scaleshift.cpp
src/tests/functional/shared_test_classes/src/subgraph/split_conv.cpp
src/tests/functional/shared_test_classes/src/subgraph/stridedslice_conv.cpp

- Limit stride height to kernel height in several tests to avoid breaking GNA limitations
- 105916

[GNA] Fix stride height setting in tests

---

src/plugins/intel_cpu/tests/functional/specific_tests.cmake

- cmake iterates over a list and cannot iterate over space separated string

[CPU][TESTS] Fix cmake subset target

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/module_tests/kernel_impl_params_relevance_test.cpp
src/plugins/intel_gpu/tests/test_utils/program_wrapper.h

- This patch adds proper update of required weights_layout in case if impl doesn't require weights reorder, otherwise previously used weights will be used

[GPU] Fix missed weights params update

---

src/plugins/intel_gpu/include/intel_gpu/primitives/resample.hpp
src/plugins/intel_gpu/src/graph/resample.cpp
src/plugins/intel_gpu/src/plugin/ops/interpolate.cpp
src/plugins/template/backend/evaluates_map.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/interpolate.cpp

- Relaxed restrictions for Interpolate operation with `SIZES` shapes calculation mode (ShapeCalcMode::SIZES), because scales input may not be fully configured during InterpolateV11 -> InterpolateV4 conversion, but GPU Plugin can handle such cases
- Added new tests cases
- Fixed evaluation function for InterpolateV11
- 106893

[GPU] Fix Interpolate assert

---

src/core/src/node.cpp
src/plugins/intel_gna/legacy/tests/convert_ngraph_to_cnn_network_tests.cpp

- Remove incorrect opset version if print the operation:
`vopset1::...` -> `opset1::...`
- *ticket-id*

Remove vopset typo

---

src/inference/dev_api/threading/ie_thread_safe_containers.hpp

- do not pop from idle queue if capacity been cleared
- 107970

query capacity before popping

---

src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_nms_named_outputs.py
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/non_max_suppression.cpp

**Details:** Support NonMaxSuppression with named outputs. Such NMS nodes are encountered in body graphs.

[TF FE] Support NonMaxSuppression with named outputs

---

src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/tests/functional/pass_tests/concat_restrictions.cpp

- unsupported concat detection is being extended to a case when cascaded concat is connected to convolution output.
- 106530

[GNA] Extend unsupported concat detection

---

src/plugins/intel_gna/tests/functional/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
src/plugins/template/tests/functional/skip_tests_config.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_infer_request/io_tensor.cpp
src/tests/functional/plugin/shared/include/behavior/ov_executable_network/exec_network_base.hpp
src/tests/functional/plugin/shared/include/behavior/ov_infer_request/io_tensor.hpp
src/tests/functional/plugin/shared/src/behavior/ov_infer_request/io_tensor.cpp
src/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/subgraph_builders.hpp

Update tests according to apiConformance test review.
- *update  checks in secondCallGetInputAfterInferSync, secondCallGetOutputAfterInferSync, canInferWithSetInOutBlobs*
- *update name for InferStaticNetworkSetOutputTensor and InferStaticNetworkSetInputTensor*
- *remove canInferWithGetOut*
- *remove from get[Input|Output]FromFunctionWith[Single|Multiple]Input from exec_network_base.hpp part with infer_requiest and move it to io_tesnsor*
- *add to io_tesnsor get[Input|Output]FromFunctionWith[Single|Multiple]Input tests*
- *add instantiation of OVInferRequestCheckTensorPrecision to apiConformance*
- *ticket-id*

[apiConformance] Refactor io_tensor tests

---

src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.cpp

- This is to fix unexpected change in https://github.com/openvinotoolkit/openvino/pull/16818
- The PR 16818 was for fixing accuracy, but resulted in perf degradation due to the incomplete condition in https://github.com/openvinotoolkit/openvino/blob/63b16baa7eff6cbaab5463bdfd0535c2ce567cef/src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.cpp#L59 which enforces too many cases to have block size 1 
- Stable diffusion originally had block size 8, so I fixed the condition to restore the performance 
- Since it is not about the functional behavior, unittest cannot cover this change. So I checked the target networks' block size locally.

[GPU] Fix softmax perf of stable diffusion

---

src/bindings/c/tests/test_model_repo.hpp

- Windows & MacOS contains d suffix for debug libraries.
- Fix CAPI tests with adding "d" postfix.
- 57948

Fix C API test failed with debug version on Windows & MacOS

---

src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/ref_convert_i64_i32.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/ref_convert_i64_i32.hpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *This transformation adds convert i64->i32 to CPU Reference nodes output.*
- **

[CPU] Convert i64->i32 for Reference node.

---

src/plugins/intel_cpu/src/nodes/bin_conv.cpp
src/plugins/intel_cpu/src/nodes/bin_conv.h
src/plugins/intel_cpu/src/nodes/executors/acl/acl_interpolate.hpp

- Fixes for android-arm postcommit build 
Link on failed build: https://dev.azure.com/openvinoci/dldt/_build/results?buildId=539767&view=logs&j=92ba3447-fcaa-530d-6438-b829fe1e7d1d&t=b0a91e75-8666-5718-e63e-df215ecb48f9&l=5653

[CPU] Fixed unused-private-field compilation errors

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/softmax.cpp

- In bounded dynamic execution, it attempts to allocate ibuf with size 0 which causes crash 
- 107919

[GPI]Fixed not to allocate internal buffer with size 0

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/fusions/gemm_fusion_test.cpp

- Onednn has limited broadcast support for fused eltwise input for gemm primitive, so in static case we insert explicit `broadcast` primitive for that input port. But for dynamic case we can't use same WA as shapes are unknown and we don't know if broadcast is needed or not. Thus we skip WA in reorder_inputs pass for dynamic cases and do similar check in `primitive_inst::is_valid_fusion()` to have unfused execution in case if unsupported broadcast pattern occur
- Fixes functional issue for https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/233-blip-visual-language-processing

[GPU] Handle unsupported eltwise fusion for onednn gemm in dynamic cases

---

cmake/features.cmake
src/plugins/intel_cpu/thirdparty/CMakeLists.txt
src/plugins/intel_cpu/thirdparty/FindACL.cmake

- It's still disabled, because of multiple issues on ARM Compute Library side.
- See https://github.com/ARM-software/ComputeLibrary/issues/1048

Used cmake interface in ARM compute

---

src/plugins/intel_cpu/src/nodes/fake_quantize.cpp

- 99838
- Output scale can be negative, so crop high and crop low can be swapped when multiplied.

[CPU] Correct crop in FQ optimized formula

---

cmake/packaging/debian.cmake
cmake/packaging/rpm.cmake

- Now, in CI only new ARM CPU plugin is used, so we can remove workarounds for old one

Removed WAs from packaging scripts related to old ARM plugin

---

src/core/include/openvino/core/any.hpp
src/core/include/openvino/core/model.hpp
src/core/src/any.cpp
src/core/src/model.cpp
src/core/tests/any.cpp
src/inference/src/dev/core_impl.cpp
src/plugins/hetero/plugin.cpp
src/plugins/intel_gna/tests/deprecated/unit/CMakeLists.txt

- Create custom copy constructor and copy assignment operator for ov::Any
- Add test
- Remove clone_map methods as excess
- Fix cmake in gna legacy tests
- CVS-106375

Fix copy constructor and assignment for ov::Any

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/tests/passes/remove_redundant_reorders_tests.cpp

- feature padding is merged into output layout for reorder(`bf_fs_yx_fsv16`->`bfyx`) for optimization during `remove_redundant_reorders` pass in post_optimized_graph phase
- if selected kernel of reorder's user node does not handle properly, it may cause incorrect input data access along feature offset
- 76981

[GPU] Fix to skip reorder optimization during post_optimize_graph phase

---

src/plugins/intel_gpu/src/graph/data.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/oooq_memory_dependencies.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/tests/test_cases/memory_test.cpp

- This PR changes to allocate memory in order from largest to smallest when deserializing.
- This is the same order as when running without cache.
- 107612

[GPU] Updated to allocate memory in order of size while deserializing

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/utils/stat_update_utils.py

+ avoid failing when rel_weights_path is not defined
- *108579*

[conformance] Fix iteration of ops_list when recalculating tests counters

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_mmad_b_fs_yx_fsv32.cl
src/plugins/intel_gpu/tests/test_cases/convolution_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/test_utils/test_utils.cpp

+ Resolve TCs' failure of oneDNN tests
- Bugfix in convolution_gpu_mmad_b_fs_yx_fsv32 kernel (invalid index calculation)
- depthwise_conv_b_fs_yx_fsv16 tested a given clDNN kernel. But it could not be applied for oneDNN execution.
Added a logic for oneDNN execution in the test.
- Added func to check possible implementation for a certain imple type (e.g. impl_types::onednn)
- Resolve TCs' failure of oneDNN tests
- 107829, 67491

Resolved failed unit-tests

---

src/core/shape_inference/include/shape_infer_type_utils.hpp

- Fix `Cast` functor when perform cast from floating point to integer when floating point value is out of integer range.
- Fix sanitizer `float-cast-overflow` runtime error message .
- 105002

Fix Cast util functor when cast from floating point to integer

---

src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/src/gna_graph_compiler.cpp
src/plugins/intel_gna/src/runtime/cnn.cpp
src/plugins/intel_gna/src/runtime/cnn.h
src/plugins/intel_gna/src/runtime/gna_float_runtime.cpp
src/plugins/intel_gna/src/runtime/gna_float_runtime.hpp
src/plugins/intel_gna/src/runtime/gna_float_runtime_op.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/convolution_relu_sequence.cpp

- avoid swap of H with W in pooling when Convolution 2D is not enforced 
- add enforcing of Pooling2D for FP32
- reconfigured tests for  window/stride of pooling
- 105916

[GNA] Fix issues with GNA 3.5 - Fix pooling for Convolution1D and Convolution2D

---

tools/mo/openvino/tools/mo/utils/cli_parser.py
tools/mo/unit_tests/mo/utils/cli_parser_test.py

Model conversion fails if '-' symbol is in input name in 'layout' parameter. 
It happens because regular expression for layout parsing expects input name to have unicode symbols or one of ":", "\","/".
So '-' is not expected.
Solution:
Change regular expression to expect in input name any symbols except of '[', ']','(', ')', because in braces layout values are set. 
Ticket: 105919
Code:
Validation:
Documentation:

Fixed parsing of 'layout' param

---

src/plugins/intel_cpu/src/cpu_memory.cpp
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/eltwise.cpp

Before introducing the memory reuse for dynamic shapes, we allocated memory by the defined upper bound of partially defined tensor dimensions, if there were any. It allowed to use the static memory solver. But, user can set any size for the upper bound and it does not necessary mean that this size of the input tensor will ever be requested. Thus, this is more of a hint than a requirement. On the other hand, with the memory reuse for the dynamic shapes inference, memory allocation by the upper bound simply does not bring any significant memory/performance gain anymore. Therefore, it is more safe to treat tensors with partially defined shapes as undefined in terms of memory allocation.
- 98727

[CPU] Remove memory allocation by the dynamic shape upper bound

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.cpp

- Added try/catch for device creation loop to handle possible exception on `getDevices()` call which can throw an exception for some weird platforms and prevent usage of properly installed OCL runtime for GPU. So now an exception on device creation leads to silent platform skip
- *108597*

[GPU] Try catch for device detection

---

src/common/snippets/src/pass/collapse_subgraph.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/edge_replace.cpp
src/tests/functional/plugin/shared/include/snippets/edge_replace.hpp
src/tests/functional/plugin/shared/src/snippets/edge_replace.cpp
src/tests/ngraph_helpers/snippets_ngraph_functions/include/subgraph_simple.hpp
src/tests/ngraph_helpers/snippets_ngraph_functions/src/subgraph_simple.cpp

- *fix unite two body parameters from two input subgraphs when the two input subgraphs are connected to the same parent node/subgraph, but does not respect which output port the two edges link*
- *99399*

[CPU][Snippets]fix candidate merged node's subgraph inputs have common subgraph input

---

src/plugins/intel_gna/src/gna_graph_compiler.cpp

The warning is "warning: no previous declaration for"
Which becomes error with '-Werror'

[GNA] fix compilation warning

---

src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/dynamic_execution/memory_realloc_test.cpp

- For iGPU, using usm_device for shape_infer_dep memory causes memcpy from device to host 
-  This PR prevents such copy to improve shape infer performance in dynamic shape execution for iGPU
-  Also fixed is_shape_infer_dep to use pointer instead of unique id (unique id is not set before compile_graph stage)

[GPU] Improve shape infer performance 

---

src/plugins/intel_gna/tests/functional/limitations/layers_limit.cpp
src/plugins/intel_gna/tests/functional/pass_tests/conv_with_padding.cpp
src/plugins/intel_gna/tests/functional/pass_tests/convert_padded_to_valid_conv.cpp
src/plugins/intel_gna/tests/functional/pass_tests/convolution_crop_axis_h.cpp
src/plugins/intel_gna/tests/functional/pass_tests/decompose_2d_conv.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/conv_low_precision.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/convolution_relu_sequence.cpp
src/plugins/intel_gna/tests/functional/subgraph_tests/add_transpose_detection.cpp

- fixed configuration to ensure that tests will be also executed for 3_5
when specific exec targets are set.
- 105916

[GNA] Fix tests configuration to ensure that 3_5 target is tested too

---

samples/cpp/speech_sample/main.cpp
samples/cpp/speech_sample/utils.hpp
src/inference/include/openvino/runtime/intel_gna/properties.hpp

- If the input tensor name contains *:port* (Parameter:0) then SF property will be incorrectly parsed by ov::util::from_string by GNA plugin because property value would be *Parameter:0:16384*.  
- 108931

[GNA] WA to fix config parsing of scale factor map

---

src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/graph.h
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/conv.h

We need to safely access constant memory on the prepareParams stage. However, there might be so called constant path, where several constant nodes are chained one after another. Since in the current implementation all the constant nodes are executed after the createPrimitive (and prepareParams) call for all nodes, it might lead to hardly detected errors.
In this PR the calls sequence has changed. We run createPrimitive for all nodes together with the execute call for constant nodes in one pass in topological order. That means that now we always have valid data on constant inputs at the moment of the createPrimitive call.
- 106650

[CPU] Execute constants in order with the create primitives calls

---

src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
src/plugins/intel_gpu/src/graph/strided_slice.cpp

1. to_string() in strided_slice always access begin/end/stride param id from dependencies regardless max dependencies. Fix only for vaild.
2. Add an exception in dump_full_node(). It helps below.
- Avoid a dump failure. Usually, graph dump are used during debugging, which reduces unnecessary debugging time due to graph dump failure.
- You can immediately see which node has failed, making it easy to find it.
- *108865*

[GPU] Fix dump graph failure issue in levit-128s model.

---

docs/OV_Runtime_UG/Python_API_exclusives.md
docs/OV_Runtime_UG/Python_API_inference.md
docs/OV_Runtime_UG/integrate_with_your_application.md
docs/snippets/ov_python_exclusives.py
docs/snippets/ov_python_inference.py
src/bindings/python/README.md

- Added new pages describing various advanced inference options and use-cases in current Python API.
- Added section about `OVDict` to Python exclusives docs.
- Linked pages.
- *100874*

[PyOV][DOCS] Added Python advanced inference documentation 

---

src/bindings/python/tests/test_runtime/test_infer_request.py
src/bindings/python/tests_compatibility/test_inference_engine/test_Blob.py
src/bindings/python/tests_compatibility/test_inference_engine/test_ExecutableNetwork.py
src/bindings/python/tests_compatibility/test_inference_engine/test_InferRequest.py

bool tests were skipped because legacy ARM plugin does not support bool: CVS-101726

[CPU] Enable Python test test_infer_request.test_infer_mixed_values with bool for ARM

---

src/bindings/c/tests/ie_c_api_test.cpp

Reverts openvinotoolkit/openvino#17012
Reason: failed post commit https://dev.azure.com/openvinoci/dldt/_build/results?buildId=547018&view=logs&j=e0e676f4-9664-538a-6d6b-aa53516aa09f&t=accf7040-0790-5a3c-3c61-9d660941426c&l=263

Revert "Fix C API unite test case error"

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/include/layout_optimizer.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/test_cases/convolution_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/depth_concatenate_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/reorder_gpu_test.cpp

- Modified unit-tests of asymetric conv with per channel(WA for oneDNN issue)
- Bugfix for reorder opt out related to padding
- Reorder from fsv16 to bfyx should not be optimized out if not aligned by 16
- Modified accuracy checking logic in unit-test
- currently, oneDNN conv has an issue on a certain tensor size e.g.) ic2oc2. Reported a ticket and modified tests to be enabled for original purpose of the test
- 107829, 67491

[GPU] Resolve failed onednn tests

---

src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.hpp
src/plugins/intel_gpu/tests/test_cases/convolution_gpu_test.cpp

- Fix for dynamic convolutions with 1d spatial executed via onednn. Current impl extends in/out shape to 4d, so we have mismatch of spatial rank and size of conv parameters. 
- *108607*

[GPU] Fix 1d onednn convolutions

---

tools/pot/compression/__init__.py
tools/pot/openvino/tools/pot/algorithms/quantization/optimization/algorithm.py
tools/pot/openvino/tools/pot/api/__init__.py
tools/pot/openvino/tools/pot/app/run.py

POT deprecation warning  is added.
Example:
```
$ pot
/home/dlyakhov/env/tmp/lib/python3.8/site-packages/openvino/offline_transformations/__init__.py:10: FutureWarning: The module is private and following namespace `offline_transformations` will be removed in the future, use `openvino.runtime.passes` instead!
warnings.warn(
Post-training Optimization Tool is deprecated and will be removed in future.```

[POT] POT deprecation warning

---

src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/fusions/gemm_fusion_test.cpp

Fix wrong batch dims for fused eltwise of gemm, it make different batch dims between fused eltwise and gemm.
levit-128s ACC has 2 issues.
1. Wrong batch dims for fused eltwise of gemm.
-> The issue is getting incorrect batch size of fused eltwise used by gemm, it causes to reduce eltwise dims. It is only reproduce in batch 1 and full tensor.
The batch size in here means all of non spatial dims, but previous implementation was default batch dim role.
2. Reuse sum post operation buffer issue in case constant input.
-> Fixed by https://github.com/openvinotoolkit/openvino/pull/17078
Add non broadcast gemm eltwise fusion unit test.
- *105495*

[GPU] Fix levit-128s accuracy issue

---

src/plugins/intel_gpu/src/graph/fully_connected.cpp

- Improves dynamic models perf on iGPU for some LLMs by ~20% (llama, gpt-neox)

[GPU] Skip FC fake alignment for some vector by matrix multiplications

---

src/common/low_precision_transformations/src/eltwise_base_transformation.cpp
src/common/low_precision_transformations/tests/add_transformation.cpp
src/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/add_function.hpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/add_function.cpp

AddTransformation branch selection fix: the logic corrected for the cases when bias after Conv/GrConv/MatMul has constant on zero's input.
- *CVS-108848*

[LPT] AddTransformation fix

---

src/bindings/python/wheel/requirements-dev.txt

Using freshly released patchelf 0.18 causes "ELF load command address/offset not properly aligned" error
- 109159

Upper-bound for patchelf

---

src/plugins/intel_gpu/include/intel_gpu/graph/fused_primitive_desc.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/basic_memory_dependencies.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/graph/program_helpers.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/passes/prepare_primitive_fusing_test.cpp

- Fix fused_primitive_desc::dep_start_idx to have -1 if unset
- Previously it was always set as the size of total # of deps of fused dep 
- Which is likely to cause many issues and being used wrongly 
- Also renamed dep_start_idx to "outer"_dep_start_idx to reduce consusion
- 108607

[GPU] Fixed fused_primitive_desc to have -1 value for dep_start_idx

---

src/inference/src/system_conf.cpp

Otherwise, multiple threads (parallel compile_model()) are accessing and changing the static object concurrently.
Reproduces sporadically be the following test:
- CoreThreadingTestsWithIterations
- 109210

[CPU] Fix data race in concurrent compile_model calls

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/tests/functional/plugin/gpu/subgraph_tests/dynamic/broadcast_eltwise.cpp

- Significantly improves performance of dynamic SD unet for dGPU. Some perf data below (SD1.5 32it 512x512)
| |	Static |	Dynamic w/o BroadcastTransition	| Dynamic w/ BroadcastTransition |
|--|-----|----|----|
| Time (mm::ss)| 	00:03 |	02:58 |	00:18 |

[GPU] Enable broadcast transition pass

---

tests/layer_tests/onnx_tests/test_reduce.py
tests/layer_tests/onnx_tests/test_reduce_lp.py

[ONNX Tests update only]
- Set ONNX opset in Reduce ops layer tests to fix version incompatibilities 
(enable tests skipped by https://github.com/openvinotoolkit/openvino/pull/16730)
- Generation of reference values for Reduce ops tests started failing after upgrade onnx version to 1.13 (onnx opset 18), 
where `axes` is no longer attribute but input. The solution is to use for testing any of the previous onnx opsets supporting `axes` as attribute. 
- Support of the ONNX Reduce*-18 ops with `axes` as input should be considered as a feature to support and covered by corresponding tests (ticket: 99962) 
-------------
✔️   layer_ubuntu20_release CI check passed ([test_reduce* logs](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/e2e-tests-linux-ubuntu20-layer/46173/c …

[ONNX tests] Set ONNX opset in Reduce ops layer tests

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp

oneDNN fc(ip) and gemm does not support pot-op Prelu, so disable fusing it until implement it.
- *108233*

[GPU] Disable oneDNN post-op Prelu in FC,gemm

---

src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
src/plugins/intel_gpu/src/graph/include/to_string_utils.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/reduce/reduce_kernel_base.cpp
src/plugins/intel_gpu/tests/fusions/reduce_fusion_test.cpp
src/plugins/intel_gpu/tests/passes/handle_reshape.cpp

- Propagate all reshape parameters for reshape split pass
- Fixed dynamic tensor offset for reduce primitive with fused ops
- Fixes crash & accuracy on SAM predictor
- Minor improvements to graph dumper:
- show primitive type
- print short format of layout when pad is empty

[GPU] Fix reshape split for dynamic models

---

src/frontends/pytorch/src/op/batch_norm.cpp
tests/layer_tests/pytorch_tests/test_batch_norm.py

- *support aten::batch_norm with training=True argument*
- *101042*
tested on functorch_maml_omniglot from torchbench

[PT FE]: extend batch norm to support training mode

---

src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp
src/plugins/intel_gpu/tests/test_cases/activation_simple_gpu_test.cpp

- jitter saves all compile time constants as `float`. So if the activation function is clamp and the output data type size is 1, values for min/max are converted to output type(`i8`or`u8`). At this time, `i8` or `u8` representation error occurs due to overflow.
- Fix jitter to clamp original min/max to output type range and adjust them to input value
- 100877

[GPU] Fix i8/u8 representation error for clamp due to overflow

---

src/plugins/intel_cpu/thirdparty/FindACL.cmake

- During the build, `arm_compute_version.embed` file is created in a binary directory. OneDNN's cmake later uses this file to parse version and check minimal requirements 
Warning to fix:
```
CMake Warning at src/plugins/intel_cpu/thirdparty/onednn/cmake/ACL.cmake:39 (message):
Build may fail: Could not determine ACL version (minimum required is 22.08)
Call Stack (most recent call first):
src/plugins/intel_cpu/thirdparty/onednn/CMakeLists.txt:125 (include)
```

Proper ACL version detection

---

src/plugins/intel_gpu/include/intel_gpu/runtime/profiling.hpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- This patch allows to collect real kernels' execution time (ov::enable_profiling property should be enabled by -pc/-exec_graph_path benchmark_app's options or in any other way; otherwise wall-clock time will be collected)
- *ticket-id*

[GPU] Add real kernels' execution timings collection for DumpProfilingData debug option
