samples/cpp/build_samples.sh

Close https://github.com/openvinotoolkit/openvino/issues/14553

build_samples.sh: detect cmake3 for CentOS

---

docs/_static/css/custom.css
docs/_static/js/open_sidebar.js
docs/conf.py

port https://github.com/openvinotoolkit/openvino/pull/14567

Docs menu lvl1 expand script port2master

---

docs/MO_DG/prepare_model/Getting_performance_numbers.md
docs/benchmarks/performance_benchmarks.md
docs/benchmarks/performance_benchmarks_faq.md
docs/documentation.md

Restructure menu and adjust content for benchmarks and getting performance numbers

Adjusting the benchmarks structure

---

docs/OV_Runtime_UG/supported_plugins/ARM_CPU.md

PR should be propagated to 22.3 release branch if it's decided to include ARM plugin to release wheel and release archive.

Update ARM CPU plugin documentation

---

tools/deployment_manager/configs/darwin.json
tools/deployment_manager/configs/linux.json
tools/deployment_manager/configs/windows.json

[Deployment Manager Configs] Updated with actual 2022.3.0 structure

---

src/common/preprocessing/ie_preprocess_gapi.cpp
src/inference/include/ie/cpp/ie_infer_request.hpp
src/inference/include/ie/ie_api.h
src/inference/include/ie/ie_common.h
src/inference/include/ie/ie_iinfer_request.hpp
src/inference/tests/functional/async_infer_request_test.cpp
src/tests_deprecated/fluid_preproc/common/fluid_tests.cpp
src/tests_deprecated/fluid_preproc/cpu/fluid_tests_cpu.cpp

- Deprecated legacy API which is not compatible with OV 2.0
- *ticket-id*

Deprecated legacy pre-processing dynamic and NV12/i420 API

---

docs/install_guides/pypi-openvino-rt.md

- Added macOS arm64
- Added CentOS 7 x86

Adjusted pypi supported OS matrix

---

docs/snippets/ie_common.c

Signed-off-by: xuejun <Xuejun.Zhai@intel.com>
- Fix the error C 2.0 API in 1.0 doc 
- 98931

[C API][DOC] fix error c 2.0 api in 1.0 doc

---

docs/MO_DG/prepare_model/Supported_Frameworks_Layers.md

- *Update paddle supported ops*
- *CVS-86380*

update paddle supported ops (#13923)

---

docs/install_guides/installing-openvino-docker-linux.md

Update of Python version for docker distribution page.
Jira ticket: [CVS-98910](https://jira.devtools.intel.com/browse/CVS-98910)
Port from https://github.com/openvinotoolkit/openvino/pull/14568

DOCS: Python version update for docker - master

---

src/tests/functional/plugin/shared/include/behavior/executable_network/get_metric.hpp
src/tests/functional/plugin/shared/include/behavior/ov_executable_network/get_metric.hpp

- *item1*
- *...*
- *ticket-id*

[Confromance] Remove CPU from heteroDeviceName

---

docs/Documentation/deployment_guide_introduction.md
docs/Documentation/openvino_ecosystem.md
docs/documentation.md
docs/learn_openvino.md
docs/optimization_guide/dldt_deployment_optimization_guide.md

port https://github.com/openvinotoolkit/openvino/pull/14583

documentation section tweaks

---

docs/_static/css/getstarted_style.css
docs/get_started.md

https://github.com/openvinotoolkit/openvino/pull/13917
This pull request introduces a significant rewrite to the Get Started page. The rewrites re-organize the content to add a learning path for new users and provides more links to tutorials and features.
Details:
The same HTML and CSS code is used for the top portion of the page to create the three blue display blocks. Markdown is used to implement the rest of the page.

DOCS:  Update Get Started page - porting #13917 to 22.2

---

docs/get_started/get_started_demos.md
docs/install_guides/installing-model-dev-tools.md
docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-linux-header.md
docs/install_guides/installing-openvino-overview.md
docs/install_guides/installing-openvino-yum.md

Porting: https://github.com/openvinotoolkit/openvino/pull/14492/
Reintroducing APT and YUM installation methods in Linux.

DOCS: Reintroducing APT and YUM installation methods - porting #14492 to master

---

src/plugins/intel_gpu/src/graph/border.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/border.cpp
src/plugins/intel_gpu/src/plugin/ops/pad.cpp
src/plugins/intel_gpu/tests/shape_infer/pad_si_test.cpp
src/tests/functional/plugin/gpu/concurrency/gpu_concurrency_tests.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/pad.cpp

- Pass original pads_begin and pads_end values to Pad primitive
- Fix copy-paste error in canSwapTensorsBetweenInferRequests test
- *96592*

[GPU] Fix Pad Primitive shape inference

---

samples/c/hello_classification/README.md
samples/c/hello_nv12_input_classification/README.md

Proofreading of C Samples for 22.2

DOCS: Proofreading C Samples for 22.2

---

src/common/transformations/tests/common_optimizations/transpose_sinking_general_test.cpp

- *Fix coded style after merge https://github.com/openvinotoolkit/openvino/pull/13943*
- *ticket-id*

Fix code style on master

---

docs/ops/movement/Transpose_1.md

- *Fixed cursive front in Transpose specification*
- *N/A*

Fixed Transpose spec

---

src/tests/functional/shared_test_classes/src/base/layer_test_utils.cpp

- *Fix QN tests for case when device id is reported*
- *ticket-id*

[TESTS] Fix QN tests for case when device id is reported

---

docs/img/quantization_picture.png
docs/optimization_guide/model_optimization_guide.md
docs/optimization_guide/nncf/ptq/basic_quantization_flow.md
docs/optimization_guide/nncf/ptq/code/ptq_aa_openvino.py
docs/optimization_guide/nncf/ptq/code/ptq_onnx.py
docs/optimization_guide/nncf/ptq/code/ptq_openvino.py
docs/optimization_guide/nncf/ptq/code/ptq_tensorflow.py
docs/optimization_guide/nncf/ptq/code/ptq_torch.py
docs/optimization_guide/nncf/ptq/ptq_introduction.md
docs/optimization_guide/nncf/ptq/quantization_w_accuracy_control.md
docs/optimization_guide/ptq_introduction.md
tools/pot/docs/Introduction.md

port https://github.com/openvinotoolkit/openvino/pull/14437 by Alexander

[Documentation]: Added description for NNCF PTQ (#14437)

---

samples/python/classification_sample_async/README.md
samples/python/hello_classification/README.md
samples/python/hello_query_device/README.md
samples/python/hello_reshape_ssd/README.md
samples/python/model_creation_sample/README.md

Porting: https://github.com/openvinotoolkit/openvino/pull/14423
Fixing the reference to Python API.

Fixing Python API links

---

samples/python/speech_sample/README.md

Porting:
https://github.com/openvinotoolkit/openvino/pull/14253
Addressing:
https://jira.devtools.intel.com/browse/CVS-96910
Fixing links to Python API.

DOCS: Fixing reference to Python API in Samples - for master

---

docs/MO_DG/Deep_Learning_Model_Optimizer_DevGuide.md
docs/MO_DG/prepare_model/MO_Python_API.md

- documentation for convert_model().

[DOCS] Document Model Optimizer Python API 

---

src/frontends/onnx/frontend/src/op/adaptive_avg_pooling2d.cpp
src/frontends/onnx/frontend/src/op/adaptive_avg_pooling2d.hpp
src/frontends/onnx/frontend/src/ops_bridge.cpp
src/frontends/onnx/tests/CMakeLists.txt
src/frontends/onnx/tests/models/org.pytorch/adaptive_avg_pooling2d_chw.prototxt
src/frontends/onnx/tests/models/org.pytorch/adaptive_avg_pooling2d_nchw.prototxt
src/frontends/onnx/tests/onnx_import_org_pytorch.in.cpp

- support for `adaptive_avg_pool2d` from the `org.pytorch.aten` domain
- 56359

ONNX Adaptive average pooling implementation

---

tools/pot/docs/SimplifiedMode.md

- *Added synthetic image generation guide*
- *80033*

[POT] Updated Simplified mode documentation

---

src/plugins/intel_cpu/src/cpu_memory.cpp
src/plugins/intel_cpu/src/node.h

[CPU] Improve some error messages

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/docs/README.md
src/plugins/intel_cpu/src/docs/blob_dumping.md
src/plugins/intel_cpu/src/docs/debug_caps_filters.md
src/plugins/intel_cpu/src/docs/feature_disabling.md
src/plugins/intel_cpu/src/docs/graph_serialization.md
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/graph_dumper.cpp
src/plugins/intel_cpu/src/ngraph_transformations/convert_to_cpu_specific_opset.hpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/plugin.h
src/plugins/intel_cpu/src/transformation_pipeline.cpp
src/plugins/intel_cpu/src/transformation_pipeline.h
src/plugins/intel_cpu/src/utils/debug_capabilities.h
src/plugins/intel_cpu/src/utils/debug_caps_config.cpp
src/plugins/intel_cpu/src/utils/debug_caps_config.h
src/plugins/intel_cpu/src/utils/ngraph_transformation.hpp
src/plugins/intel_cpu/src/utils/node_dumper.cpp
src/plugins/intel_cpu/src/utils/node_dumper.h

- OV_CPU_DISABLE and OV_CPU_DUMP_IR env variables were added,
- OV_CPU_DISABLE: to disable ov transformation scopes from CPU transformation pipeline
- OV_CPU_DUMP_IR: to dump IR between transformation scopes
- 75552

[CPU] [DEBUG CAPS] Extension for snippets and other ngraph transformations

---

src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h
src/plugins/intel_gpu/tests/fusions/eltwise_fusion_test.cpp

- This PR fixes eltwise fusions code generation in case of enabled LT_ALIGNED_READ and vec_size > 1 for blocked formats
- *97694, 97908*

[GPU] Fix eltwise fusions in case of LT_ALIGNED_READ and vec_size>1

---

src/plugins/intel_gna/src/gna_device.cpp
src/plugins/intel_gna/src/gna_infer_request.cpp
src/plugins/intel_gna/src/gna_infer_request.hpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/request/subrequest.hpp
src/plugins/intel_gna/src/request/subrequest_impl.cpp
src/plugins/intel_gna/src/request/subrequest_impl.hpp
src/plugins/intel_gna/src/request/worker.hpp
src/plugins/intel_gna/src/request/worker_impl.cpp
src/plugins/intel_gna/src/request/worker_impl.hpp
src/plugins/intel_gna/src/request_status.hpp
src/plugins/intel_gna/tests/unit/CMakeLists.txt
src/plugins/intel_gna/tests/unit/gna_api_stub.cpp
src/plugins/intel_gna/tests/unit/gna_infer_request_test.cpp
src/plugins/intel_gna/tests/unit/gna_mock_api.hpp
src/plugins/intel_gna/tests/unit/gna_wait_test.cpp
src/plugins/intel_gna/tests/unit/request/gna_request_worker_impl_test.cpp
src/plugins/intel_gna/tests/unit/request/mock_subrequest.hpp
src/plugins/intel_gna/tests/unit/request/mock_worker.hpp
src/plugins/intel_gna/tests/unit/scale_factor_helper_test.cpp

- added exception handling for wait to allow to start new inference if error happened on wait
- added closing unfinished queued requests if error happen on wait or enqueue
-  98800

[GNA] Fix exception handling on wait and infer

---

docs/Documentation/deployment_guide_introduction.md
docs/Documentation/openvino_ecosystem.md
docs/Documentation/openvino_workflow.md
docs/OV_Runtime_UG/integrate_with_your_application.md
docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
docs/documentation.md
docs/get_started.md
docs/learn_openvino.md
docs/resources/resources.md
docs/resources/tensorflow_frontend.md

- *item1*
- *...*
- *ticket-id*

DOCS: Add text for doc headers

---

docs/Documentation/deployment_guide_introduction.md
docs/Documentation/openvino_ecosystem.md
docs/Documentation/openvino_workflow.md
docs/OV_Runtime_UG/integrate_with_your_application.md
docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
docs/documentation.md
docs/get_started.md
docs/learn_openvino.md
docs/resources/resources.md

port https://github.com/openvinotoolkit/openvino/pull/14671
Co-authored-by: Karol Blaszczak <karol.blaszczak@intel.com>

DOCS: Add text for doc headers (#14671)

---

src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/tests/telemetry.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_nonexistent_add.py

**Details:** Collect statistics about operations that fails the conversion
**Ticket:** 98861

[TF FE][Telemetry] Collect statistics about operations that fails the conversion

---

src/core/include/openvino/core/version.hpp
src/inference/include/ie/ie_version.hpp

- Upgrade OV to 2023.0 version
- NA

Bump OpenVINO version

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/plugin/caching_tests.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_plugin/caching_tests.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/plugin/caching_tests.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/plugin/caching_tests.cpp
src/tests/functional/plugin/myriad/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/tests/functional/plugin/myriad/shared_tests_instances/behavior/plugin/caching_tests.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/caching_tests.hpp
src/tests/functional/plugin/shared/include/behavior/plugin/caching_tests.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp
src/tests/functional/plugin/shared/src/behavior/plugin/caching_tests.cpp

- *item1*
- *...*
- *CVS-97799*

[CompileModelCacheTestBase] Avoid tests with ops and them unsupported precision

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/experimental_detectron_detection_output_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/experimental_detectron_roi_feature_extractor_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/ed_rfe/roi_feature_extractor_kernel_ref.cpp
src/plugins/intel_gpu/tests/test_cases/experimental_detectron_roi_feature_extractor_gpu_test.cpp

- Fix pyramid levels data index calculation in case of padded formats in Experimental Detectron ROI Feature Extractor
- Fix class agnostic box regression attribute processing in Experimental Detectron Detection Output
- *98309*

[GPU] Fix Experimental Detectron ROI Feature Extractor and DO

---

docs/install_guides/pypi-openvino-dev.md
docs/install_guides/pypi-openvino-rt.md

- *item1*
- *...*
- *ticket-id*

Delete pre-release note

---

src/inference/src/cnn_network_ngraph_impl.cpp

**Details:** In order to understand what operations are affected by dynamism, we also need to track operations from sub-graphs of multi-subgraph operations.

[Core util] Collect dynamism signature for sub-graph operations

---

docs/suppress_warnings.txt

- *item1*
- *...*
- *ticket-id*

Add warnings for docs

---

src/inference/src/threading/ie_istreams_executor.cpp

- *correct statistical information threads in Latency mode*
- *98210*

correct statistical information threads in Latency mode

---

docs/requirements.txt

- Bump version of `markupsafe` and `jinja2`
- Remove duplicate of `py`
- 99220

Fix docs requirements versions

---

docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_GNMT_From_Tensorflow.md
docs/home.rst
docs/install_guides/installing-openvino-from-archive-linux.md
docs/install_guides/installing-openvino-from-archive-macos.md
docs/optimization_guide/nncf/introduction.md
docs/optimization_guide/nncf/ptq/ptq_introduction.md
tools/pot/docs/Introduction.md

- *item1*
- *...*
- *ticket-id*

Release doc updates

---

docs/Extensibility_UG/frontend_extensions.md
docs/snippets/ov_extensions.cpp
docs/snippets/ov_extensions.py

Update frontend extension docs with python examples

---

docs/OV_Runtime_UG/Samples_Overview.md

- *Update the information on how to find samples for PyPI installation as there is no <INSTALL_DIR>*
- *[CVS-85216](https://jira.devtools.intel.com/browse/CVS-85216)*

add ways to find samples for PyPI installation

---

src/plugins/intel_gpu/include/intel_gpu/graph/serialization/loop_serializer.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/loop.hpp
src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
src/plugins/intel_gpu/src/graph/include/loop_inst.h
src/plugins/intel_gpu/src/graph/include/mutable_data_inst.h
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/graph/mutable_data.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/test_cases/loop_gpu_test.cpp

- Serialization of loop primitive
- 97994

[GPU] Serialization of loop primitive

---

src/plugins/intel_gpu/src/plugin/graph.cpp

- Fix exception on intermediate optimizer steps dump in ngraph format

[GPU] Fixed debug graph dump

---

samples/cpp/build_samples_msvc.bat

Close https://github.com/openvinotoolkit/openvino/issues/14825

Parallelize build_samples_msvc.bat

---

src/plugins/intel_gpu/tests/CMakeLists.txt
src/tests/functional/plugin/gpu/CMakeLists.txt

- Align GPU func/unit test names

[GPU] Rename GPU unit and func tests

---

src/frontends/tensorflow/include/openvino/frontend/tensorflow/frontend.hpp
src/frontends/tensorflow/include/openvino/frontend/tensorflow/graph_iterator.hpp
src/frontends/tensorflow/src/decoder_argdef.cpp
src/frontends/tensorflow/src/decoder_argdef.hpp
src/frontends/tensorflow/src/decoder_proto.cpp
src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/src/graph_iterator_proto.hpp
src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/src/input_model.hpp
src/frontends/tensorflow/src/op/argdef_ops.cpp
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/models_pbtxt/swish_f32.pbtxt

**Details:** Now this is a base for further implementation support for StatefulPartitionedOp, While, and If operations
**Ticket:** 98457

[TF FE] Support body graph conversion and its injection

---

.github/dependency_review.yml
.github/workflows/dependency_review.yml

- See https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review to understand what is it
- Example of failure https://github.com/ilya-lavrenov/openvino/actions/runs/3796550654/jobs/6456747431#step:3:9

Added dependency review action

---

src/frontends/tensorflow/src/op/random_uniform.cpp
tests/layer_tests/tensorflow_tests/test_tf_RandomUniform.py

**Details:** Refactor RandomUniform support and provide more test coverage.
**Ticket:** 56598

[TF FE] Refactor RandomUniform support and provide more test coverage

---

src/plugins/intel_cpu/src/emitters/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/comparison.cpp
src/tests/functional/shared_test_classes/src/single_layer/comparison.cpp
src/tests/functional/shared_test_classes/src/single_layer/is_inf.cpp

- *JIT emitters for IsFinite, IsInf and IsNaN.*
- *98206*

[CPU] IsFinite, IsInf and IsNaN operations JIT implementation.

---

src/frontends/onnx/tests/onnx_prototxt_converter_requirements.txt

- Replaced by https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/requirements.txt

Removed onnx_prototxt_converter_requirements.txt

---

cmake/packaging/debian.cmake
cmake/packaging/rpm.cmake

- *item1*
- *...*
- *ticket-id*

Set conflicting versions for RPM / DEB

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/profiling.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/nodes_ordering.cpp
src/plugins/intel_gpu/src/graph/pass_manager.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/plugin/program.cpp

- Added memory usage profiling support
- Changed allocation type for weights reordering
- Removed kernels sources after compilation
- Added malloc_trim(0) call in CleanupBuild Program's stage
- *ticket-id*

[GPU] Peak memory usage optimizations

---

scripts/CMakeLists.txt
scripts/install_dependencies/install_openvino_dependencies.sh
src/bindings/python/tests/test_onnx/model_zoo_preprocess.sh
src/bindings/python/tests_compatibility/test_onnx/model_zoo_preprocess.sh
src/tests/functional/plugin/myriad/run_tests_myriad_multistick.sh

- *item1*
- *...*
- *ticket-id*

Fixed shellcheck

---

src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/passes/select_preferred_formats_test.cpp

- test_select_preferred_formats.setting_target_conv_format
- Fix wrong weight shape
- Output layout initialization
- Ensure preferred output format is selected
- 67491

[GPU][DG2] Fix unit test: test_select_preferred_formats.setting_target_conv_format

---

docs/install_guides/installing-openvino-raspbian.md

- Small corrections
- CVS-98909

Updated docs for Raspbian OS

---

docs/Documentation/deployment_guide_introduction.md
docs/Documentation/openvino_workflow.md
docs/OV_Runtime_UG/deployment/deployment_intro.md

port
https://github.com/openvinotoolkit/openvino/pull/14892

DOCS]-workflow-article-titles-tweaks

---

docs/_static/benchmarks_files/benchmark-data.csv

port
https://github.com/openvinotoolkit/openvino/pull/14794

Update benchmark-data.csv (#14794)

---

.github/CODEOWNERS
.github/labeler.yml
.github/workflows/labeler.yml

- Automatically add label based on changes.
- Refactored codeowners file to list generic patterns first, specific last. This is required to ensure that if files are matched by several patterns, last pattern is applied. 
- On current master we have multiple issues with docs, tests when generic rules are still applied. E.g. [this readme](https://github.com/openvinotoolkit/openvino/blob/master/tools/README.md) file is owned by tools instead docs maintainers.

Added workflow to add labels

---

.github/workflows/labeler.yml

- Tested here https://github.com/ilya-lavrenov/openvino/pull/126

Add token for labeler workflow

---

docs/install_guides/installing-openvino-from-archive-linux.md

- *item1*
- *...*
- *ticket-id*

Update install linux page for master (port from #14625)

---

tests/layer_tests/common/tf_layer_test_class.py
tests/layer_tests/tensorflow_tests/test_tf_Conv2D.py
tests/layer_tests/tensorflow_tests/test_tf_Conv3D.py

- Conv2D layer test
- Conv3D layer test
- 92761, 92763

[TF FE] Add Conv layer tests

---

docs/install_guides/installing-openvino-raspbian.md

- *item1*
- *...*
- *ticket-id*

Install raspbian updates

---

docs/home.rst
docs/install_guides/installing-openvino-from-archive-linux.md
docs/install_guides/installing-openvino-from-archive-macos.md
docs/install_guides/installing-openvino-from-archive-windows.md

- *item1*
- *...*
- *ticket-id*

DOCS: Update release notes link

---

docs/img/nncf_workflow.png
docs/img/nncf_workflow.svg
docs/optimization_guide/nncf/introduction.md

Recreation of image in svg format for Compressing Models During Training article.
JIRA: [CVS-99006](https://jira.devtools.intel.com/browse/CVS-99006)

DOCS: Compressing Models During Training image recreation for master

---

docs/img/nncf_workflow.png
docs/img/nncf_workflow.svg
docs/optimization_guide/nncf/introduction.md

Recreation of image in svg format for Compressing Models During Training article.
JIRA: [CVS-99006](https://jira.devtools.intel.com/browse/CVS-99006)
Port from https://github.com/openvinotoolkit/openvino/pull/14865

DOCS: Compressing Models During Training image recreation for 22.3

---

docs/img/nncf_workflow.png
docs/img/nncf_workflow.svg
docs/optimization_guide/nncf/introduction.md

Recreation of image in svg format for Compressing Models During Training article.
JIRA: [CVS-99006](https://jira.devtools.intel.com/browse/CVS-99006)
Port from https://github.com/openvinotoolkit/openvino/pull/14865

DOCS: Compressing Models During Training image recreation for 22.2

---

docs/install_guides/configurations-for-iei-card.md
docs/install_guides/configurations-for-intel-gpu.md
docs/install_guides/installing-openvino-from-archive-windows.md
docs/install_guides/installing-openvino-linux.md
docs/install_guides/installing-openvino-pip.md

- *item1*
- *...*
- *ticket-id*

update windows installation & links

---

docs/install_guides/installing-openvino-from-archive-macos.md

- *item1*
- *...*
- *ticket-id*

Install macos updates (port from #14656)

---

docs/OV_Runtime_UG/Samples_Overview.md

- *item1*
- *...*
- *ticket-id*

Add ways to find samples for PyPI installation (port from #14658)

---

docs/OV_Runtime_UG/Samples_Overview.md

- *item1*
- *...*
- *ticket-id*

Samples overview update (port from #14658)

---

.ci/azure/android_arm64.yml
.ci/azure/linux.yml
.ci/azure/linux_arm64.yml
.ci/azure/linux_conditional_compilation.yml
.ci/azure/linux_coverity.yml
.ci/azure/linux_cuda.yml
.ci/azure/linux_debian.yml
.ci/azure/linux_lohika.yml
.ci/azure/linux_ngraph_onnx.yml
.ci/azure/linux_onnxruntime.yml
.ci/azure/mac.yml
.ci/azure/windows.yml
.ci/azure/windows_conditional_compilation.yml
SECURITY.md

- Remove useless options like `continueOnError: false`
- Clone with depth=1, recursive submodules => only submodules of first level.

Updated Azure pipelines

---

.ci/azure/android_arm64.yml
.ci/azure/linux_arm64.yml
.ci/azure/linux_conditional_compilation.yml
.ci/azure/linux_cuda.yml
.ci/azure/linux_ngraph_onnx.yml
.ci/azure/linux_onnxruntime.yml
.ci/azure/windows.yml
.ci/azure/windows_conditional_compilation.yml

- Excluded some CI checks for contributions to the tools to speed up the CI and contribution process.

Excluded some CI checks for changes in the tools

---

src/plugins/intel_gpu/include/intel_gpu/plugin/device_config.hpp
src/tests/functional/plugin/gpu/concurrency/gpu_concurrency_tests.cpp
src/tests/functional/plugin/gpu/remote_blob_tests/cldnn_remote_blob_tests.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/core_config.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/behavior/plugin/auto_batching_tests.hpp
src/tests/functional/plugin/shared/src/execution_graph_tests/normalize_l2_decomposition.cpp
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
tests/layer_tests/common/layer_test_class.py
tests/layer_tests/common/layer_utils.py
tests/layer_tests/common/onnx_layer_test_class.py

- Use fp16 infer precision by default regardless IR precision. 
- *99756*

[GPU] Change default infer precision to fp16

---

docs/install_guides/pypi-openvino-dev.md
docs/install_guides/pypi-openvino-rt.md

Propagation of https://github.com/openvinotoolkit/openvino/pull/14919

22.3 PyPi documentation - add M1 related updates

---

src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/strided_slice_optimize.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl
src/plugins/intel_gpu/tests/test_cases/strided_slice_gpu_test.cpp

- fix strided_slice_optimize for 5d new axis output
- fix typo in strided_slice cl kernel
- avoid handle_reshape when user is only one
- 97904

[GPU] fix strided_slice_optimize for 5d new axis output, typo in strided_slice cl kernel, avoid handle_reshape when user is only one

---

docs/OV_Runtime_UG/ShapeInference.md
docs/OV_Runtime_UG/migration_ov_2_0/deployment_migration.md
docs/dev/build.md
docs/install_guides/installing-openvino-yocto.md
docs/install_guides/troubleshooting-issues.md
docs/ops/activation/SoftPlus_4.md
docs/ops/internal/AUGRUCell.md
docs/ops/internal/AUGRUSequence.md
docs/optimization_guide/model_optimization_guide.md
docs/resources/telemetry_information.md
thirdparty/cnpy/README.md
tools/legacy/benchmark_app/README.md
tools/pot/openvino/tools/pot/api/samples/3d_segmentation/README.md
tools/pot/openvino/tools/pot/api/samples/classification/README.md
tools/pot/openvino/tools/pot/api/samples/face_detection/README.md
tools/pot/openvino/tools/pot/api/samples/segmentation/README.md

This fixes the broken links found throughout the OV docs.

DOCS: Fixing broken links in documentation.

---

src/plugins/intel_gpu/include/intel_gpu/primitives/strided_slice.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/strided_slice_optimize.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/strided_slice.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/graph/strided_slice.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/strided_slice/strided_slice_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/strided_slice/strided_slice_kernel_ref.h
src/plugins/intel_gpu/src/plugin/ops/strided_slice.cpp
src/plugins/intel_gpu/tests/shape_infer/strided_slice_si_test.cpp
src/plugins/intel_gpu/tests/test_cases/strided_slice_gpu_test.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/strided_slice.cpp

- Update primitive API for non-constant begin/end/stride support
- Update impl and strided slice ref kernel w/o kernel params from memory_deps
- Remove existing W/A for strided slice with non-constant begin/end/stride
- Add strided slice dynamic TCs for gpuFunctests
- 94606

[GPU] Update strided slice impl for non-constant begin/end/stride support

---

docs/nbdoc/consts.py
docs/tutorials.md

Porting: https://github.com/openvinotoolkit/openvino/pull/14945
This update adds new tutorials.

DOCS: Updating Interactive Tutorials - for 22.2

---

docs/nbdoc/consts.py
docs/tutorials.md

This update adds new tutorials.

DOCS: Updating Interactive Tutorials - for master

---

docs/_static/css/custom.css
docs/_static/js/hide_banner.js
docs/_templates/layout.html

This enables keeping the banner hidden after closing it.

DOCS: Hiding Transition to API 2.0 banner - for master

---

.github/labeler.yml
.github/workflows/code_style.yml

- Example https://github.com/ilya-lavrenov/openvino/pull/130
- Also, adjusted labels

Fixed clang-format action to provide suggestions

---

samples/python/classification_sample_async/requirements.txt
samples/python/hello_classification/requirements.txt
samples/python/hello_reshape_ssd/requirements.txt
tools/cross_check_tool/requirements.txt

Close https://github.com/openvinotoolkit/openvino/issues/14875

Relax OpenCV dependency

---

src/plugins/intel_gpu/include/intel_gpu/primitives/broadcast.hpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/broadcast.cpp

- Cherry-pick of #14744 for 2022.3.1 release
- *99651*

[GPU] Fix shape infer for 0d broadcast (#14744)

---

src/plugins/intel_gpu/src/graph/impls/onednn/utils.hpp
src/plugins/intel_gpu/tests/CMakeLists.txt
src/plugins/intel_gpu/tests/onednn/utils_test.cpp

+ Remove invalid referencing if ENABLE_INTEL_CPU is off
- Resolve build issue of ov_gpu_unit_test if ENABLE_INTEL_CPU is off
- Removed unnecessary include
- *ticket-id*

Bugfix build issue of onednn test

---

src/plugins/intel_gna/src/backend/am_intel_dnn.cpp
src/plugins/intel_gna/src/gna_graph_compiler.cpp
src/plugins/intel_gna/src/serial/headers/2dot2/gna_model_header.hpp
src/plugins/intel_gna/tests/unit/backend/gna_limitations_test.cpp
src/plugins/intel_gna/tests/unit/gna_get_aligned_split_sizes.cpp

- fix items remaining after namespace alignment.
- 100273

[GNA] Fix GNA namespaces

---

tools/mo/requirements.txt
tools/mo/setup.py

**Details:** Simplify setup.py logic for MO since all default dependencies is now in requirements.txt file

[MO][Install] Clean up setup

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/analyze_confomance_fails.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/requirements.txt
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/utils/utils.py

- *item1*
- *...*
- *ticket-id*

[Conformance] Script for analyze logs for fail and create exel with result

---

docs/nbdoc/consts.py
docs/tutorials.md

This includes the package with the latest notebooks.

DOCS: Adding new tutorials - for master

---

src/tests/functional/plugin/gpu/single_layer_tests/dynamic/shapeof.cpp

- *Add dynamic functional tests for shape_of op*
- *...*

[GPU] Add dynamic functional tests for shapeof op

---

src/core/shape_inference/include/convolution_shape_inference.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/deconvolution.hpp
src/plugins/intel_gpu/src/graph/deconvolution.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/pre_replace_deconv.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/include/deconvolution_inst.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/plugin/ops/convolution.cpp
src/plugins/intel_gpu/tests/shape_infer/deconvolution_si_test.cpp
src/plugins/intel_gpu/tests/test_cases/deconvolution_gpu_test.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/convolution_backprop_data.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/group_convolution_backprop_data.cpp

- Update Deconv/GroupDeconv to use ngraph shape infer
- 95560

[GPU] Enable Deconv/GroupDeconv shape infer

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/behavior/ov_executable_network/exec_network_base.hpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/caching_tests.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp

- check that model was loaded from cache
- 100838

Add ov::loaded_from_cache checking for CompileModelLoadFromMemoryTest

---

tests/lib/src/common_utils.cpp
tests/lib/src/common_utils.h
tests/lib/src/reshape_utils.cpp

Leftovers after https://github.com/openvinotoolkit/openvino/pull/14704 for API1.0 / API2.0

Add support of f64/i64 for tests/

---

docs/nbdoc/consts.py
docs/tutorials.md

port https://github.com/openvinotoolkit/openvino/pull/15027
includes the package with the latest notebooks.

adding new tutorials (#15027)

---

src/plugins/hetero/executable_network.cpp
src/tests/functional/plugin/shared/src/behavior/plugin/hetero_synthetic.cpp

- *Remove marking of Parameters, Results and Constants from HETERO plugin.*
- *CVS-100138*

[HETERO] Remove WA for Parameters, Results and Constants.

---

.ci/azure/android_arm64.yml

- Revert changes in this job because it's now failing due to reasons described in 100817
- This PR partially reverts https://github.com/openvinotoolkit/openvino/pull/13550
- 100817

Disable GitHub Action setupPython in android-arm64 job

---

src/plugins/intel_gpu/src/graph/impls/ocl/strided_slice.cpp
src/plugins/intel_gpu/tests/test_cases/strided_slice_gpu_test.cpp

- Fix edge case of strided slice for clamped out-of-bounds begin/end values with negative stride
- 100666

[GPU] Fix strided slice for clamped out-of-bounds begin/end with negative stride

---

samples/cpp/common/utils/include/samples/common.hpp

- *item1*
- *...*
- *ticket-id*

Fixed possible overflows to clean KW scan

---

docs/install_guides/installing-openvino-apt.md

Fixing indentation, faulty code-blocks, numbering in lists.

DOCS: Fixing formatting in 'Install From Apt' article

---

docs/install_guides/installing-openvino-apt.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15062
Fixing indentation, faulty code-blocks, numbering in lists.

DOCS: Fixing formatting in 'Install From Apt' article - for 22.3

---

src/plugins/intel_gna/src/gna_executable_network.hpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/gna_plugin.hpp
src/plugins/intel_gna/src/gna_plugin_query_api.cpp
src/plugins/intel_gna/tests/unit/gna_executable_network_metrics_test.cpp

Added following metrics to GNAExecutableNetwork:
- NETWORK_NAME
- 18180

[GNA] Add missing metrics to GNAExecutableNetwork

---

tools/pot/openvino/tools/pot/graph/special_patterns.py

[POT] Add transformer block pattern

---

docs/install_guides/pypi-openvino-dev.md

Update doc link and extras description

---

src/frontends/tensorflow/src/graph_iterator_proto.hpp

**Details:** Fix build on MacOS and Android ARM64 after https://github.com/openvinotoolkit/openvino/pull/15043

Fix build for macos and android-arm64

---

docs/install_guides/installing-openvino-from-archive-linux.md

- *add a cd command*
- *...*
- *[100916](https://jira.devtools.intel.com/browse/CVS-100916)*

Fix Step 5 in Linux installation

---

docs/snippets/ov_multi.py

- Changes the device order in the first python snippet of [MULTI docs](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Running_on_multiple_devices.html) to make both commands in Option 2 equivalent 
- None
CC @helena-intel @ryanloney

Change device order in MULTI python snippet

---

docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md

- *Update support "Sign" layer to not supported.*
- *Update support "Floor" layer to limited support.*
- *88871*
- *88693*

Update VPU plugins layer support

---

src/core/tests/pass/serialization/cleanup.cpp
src/core/tests/pass/serialization/const_compression.cpp
src/core/tests/pass/serialization/custom_ops.cpp
src/core/tests/pass/serialization/deterministicity.cpp
src/core/tests/pass/serialization/from_model.cpp
src/core/tests/pass/serialization/rt_info_serialization.cpp
src/core/tests/pass/serialization/serialize.cpp
src/core/tests/pass/serialization/tensor_iterator.cpp
src/core/tests/pass/serialization/tensor_names.cpp
src/frontends/ir/tests/frontend_test.hpp
src/frontends/ir/tests/meta_data_tests.cpp
src/inference/tests/functional/caching_test.cpp
src/inference/tests/functional/cnn_network_test.cpp
src/inference/tests/functional/core_threading.cpp
src/inference/tests/unit/ie_compilation_context_test.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/augru_cell.cpp
src/tests/functional/plugin/conformance/subgraphs_dumper/src/ops_cache.cpp
src/tests/functional/plugin/shared/include/behavior/executable_network/exec_network_base.hpp
src/tests/functional/plugin/shared/include/behavior/ov_executable_network/exec_network_base.hpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp
src/tests/functional/plugin/shared/include/behavior/plugin/core_integration.hpp
src/tests/functional/plugin/shared/src/behavior/executable_network/exec_graph_info.cpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp
src/tests/functional/shared_test_classes/src/base/layer_test_utils.cpp
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
src/tests/ie_test_utils/common_test_utils/common_utils.cpp
src/tests/ie_test_utils/common_test_utils/common_utils.hpp

- Add api to common test utils to create unique names
- Use this api in tests
- CVS-96479

Use unique file names in tests

---

.github/dependency_review.yml
src/frontends/paddle/tests/requirements.txt
tests/memory_tests/test_runner/requirements.txt
tests/time_tests/test_runner/requirements.txt
tools/mo/requirements_dev.txt

- Update requirements to versions which support Python 3.11 according to PyPI (wherever possible)
- 96724

[PyOV] Update requirements for Python 3.11

---

src/inference/src/compilation_context.cpp

- Original PR: https://github.com/openvinotoolkit/openvino/pull/15064
- 100835

Update calculateFileInfo for the null string case for 2022.3

---

docs/install_guides/installing-model-dev-tools.md
docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-yum.md

- *item1*
- *...*
- *[CVS-100552](https://jira.devtools.intel.com/browse/CVS-100552)*

Add install dependencies info for APT & YUM

---

docs/snippets/CMakeLists.txt
docs/snippets/src/main.c
docs/snippets/src/main.cpp

- After https://github.com/openvinotoolkit/openvino/pull/15119

Fixed compilation on Linux

---

docs/install_guides/installing-model-dev-tools.md
docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-yum.md

* add install dependencies info
* update according to comments
* fix formatting
* fix formatting
* small corrections
* fix formatting & issues
* minor correction
- *item1*
- *...*
- *ticket-id*

Add install dependencies info for APT & YUM (#15023)

---

src/core/include/openvino/op/clamp.hpp
src/core/shape_inference/include/broadcast_shape_inference.hpp

- Add error handling in broadcast shape inference
- Initialize Clamp class members
- 100694

Add error handling in broadcast shape inference and init clamp attributes

---

docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/footer_info.html

- *item1*
- *...*
- *ticket-id*

Update doc footer

---

docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/footer_info.html

- *item1*
- *...*
- *ticket-id*

Update footer link

---

src/frontends/tensorflow/src/op/lrn.cpp
tests/layer_tests/tensorflow_tests/test_tf_LRN.py

**Details:** It allows to fix inference results mismatch for some models
**Tickets:** 95068, 92866

[TF FE] Fix LRN operation and test it

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_opt.cl

[GPU] bugfix: block copy accessed out of valid position.

---

docs/install_guides/installing-openvino-raspbian.md

Correcting the levels of headings.

DOCS: Fixing formatting of headings in 'Raspbian OS' article

---

.ci/azure/android_arm64.yml

- To fix https://dev.azure.com/openvinoci/dldt/_build/results?buildId=469922&view=logs&j=92ba3447-fcaa-530d-6438-b829fe1e7d1d&t=247ac7f2-d646-5c8f-a5bf-fc23326bb02c

Fixed Azure CI post-commit build

---

cmake/developer_package/ncc_naming_style/ncc_naming_style.cmake

* add possibility to set custom ncc style file
* add possibility to run NCC on Windows in case Clang is installed
and available in PATH
- 100829

[CMAKE][NCC]Enable custom ncc style file path and enable ncc for Windows

---

docs/nbdoc/consts.py
docs/tutorials.md

Reverting tutorials to last known working version.

DOCS: Reverting the version of tutorials -for 22.3

---

docs/nbdoc/consts.py
docs/tutorials.md

Reverting tutorials to last known working version.

DOCS: Reverting the version of tutorials

---

src/inference/src/core.cpp
src/inference/tests/functional/ov_extension_test.cpp

Resolve relative path to the extension

---

src/frontends/paddle/src/proto/framework.proto
src/frontends/paddle/tests/op_fuzzy.cpp
src/frontends/paddle/tests/requirements.txt
src/frontends/paddle/tests/test_models/gen_scripts/generate_tensorarray.py

- *Update paddlepaddle to 2.4.0*
- *Disable paddle tensorarray test because of its failure in paddlepaddle v2.4.0*
- *CVS-98752*

Meiyang/paddle 2.4

---

.github/CODEOWNERS
.github/labeler.yml

- *item1*
- *...*
- *ticket-id*

Added PT FE to codeowners / labeler

---

src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/strided_slice_optimize.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl
src/plugins/intel_gpu/tests/test_cases/strided_slice_gpu_test.cpp

- Cherrypick PR14812(https://github.com/openvinotoolkit/openvino/pull/14812) to releases/2022/3
- 97904

Cherrypick PR14812 to releases/2022/3

---

src/common/snippets/src/op/loop.cpp
src/plugins/intel_cpu/src/emitters/jit_snippets_emitters.cpp

- *Fix minor postcommit errors introduced by [PR#14327](https://github.com/openvinotoolkit/openvino/pull/14327)

[Snippets] FP32 MHA postcommit fixes

---

src/bindings/python/src/pyopenvino/utils/utils.cpp

[PyOV] Add new types to Any dispatcher

---

src/tests/functional/plugin/shared/src/snippets/mha.cpp

Fix minor postcommit errors introduced by https://github.com/openvinotoolkit/openvino/pull/14327

[Snippets] FP32 MHA postcommit fixes (arm64)

---

src/bindings/python/tests/test_runtime/test_infer_request.py
src/bindings/python/tests/test_runtime/test_properties.py
src/bindings/python/tests_compatibility/test_inference_engine/test_ExecutableNetwork.py

- *item1*
- *...*
- *ticket-id*

[PyOV] Skip tests with bool for arm

---

src/bindings/python/tests/test_runtime/test_infer_request.py
src/bindings/python/tests/test_runtime/test_properties.py
src/bindings/python/tests_compatibility/test_inference_engine/test_ExecutableNetwork.py

* [PyOV] Skip tests with bool for arm
* exec_net export test rewrite
- *item1*
- *...*
- *ticket-id*

Cherry-pick of (#15208)

---

src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/pre_replace_deconv.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/activation.cpp
src/plugins/intel_gpu/src/graph/include/fused_primitive_desc.h
src/plugins/intel_gpu/src/graph/include/kernel_selector_helper.h
src/plugins/intel_gpu/src/graph/include/pass_manager.h
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/include/reshape_inst.h
src/plugins/intel_gpu/src/graph/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_winograd_6x3_s1_fused.cl

- Removed pass with legacy activation primitive fusion and added conversion during kernel selector params creation for single activation in fused ops
-  Fix winograd kernel compilation

[GPU] Remove legacy fused ops

---

docs/install_guides/configurations-for-iei-card.md

Porting:
https://github.com/openvinotoolkit/openvino/pull/15173
Fixing formatting issues and broken links. Changing layout of 'Recommended Settings' section.

DOCS: Fixing formatting in 'Configurations for IEI Mustang' article - for 22.3

---

docs/install_guides/configurations-for-iei-card.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15174
Fixing formatting issues and broken links. Changing layout of 'Recommended Settings' section.

DOCS: Fixing formatting in 'Configurations for IEI Mustang' article - for 22.2

---

docs/install_guides/configurations-for-iei-card.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15174
Fixing formatting issues and broken links. Changing layout of 'Recommended Settings' section.

DOCS: Fixing formatting in 'Configurations for IEI Mustang' article - for 22.1

---

docs/install_guides/installing-openvino-raspbian.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15162
Correcting the levels of headings.

DOCS: Fixing formatting of headings in 'Raspbian OS' article - for 22.3

---

.gitattributes

- See https://github.com/openvinotoolkit/openvino/pull/14873#issuecomment-1370734031, we are updating a lot of images to SVG

Added SVG files to lfs

---

src/bindings/python/tests_compatibility/test_ngraph/test_ops_binary.py
src/frontends/paddle/tests/test_models/gen_scripts/generate_assign_value.py
src/plugins/intel_cpu/tools/dump_check/dump_check.py
tests/layer_tests/onnx_tests/test_loop.py
tests/layer_tests/tensorflow_tests/test_tf_BinaryOps.py

**Details:** Fix rest of NumPy deprecated types

[Tests] Fix rest of NumPy deprecated types

---

tests/layer_tests/pytorch_tests/test_eq.py

add tests for aten::eq

---

src/frontends/tensorflow/src/op/clip_by_value.cpp
src/frontends/tensorflow/src/op_table.cpp
tests/layer_tests/tensorflow_tests/test_tf_ClipByValue.py

**Details:** Support ClipByValue operation and test it

[TF FE] Support ClipByValue operation

---

docs/install_guides/configurations-for-ncs2.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15236
Fixing indentation of code blocks in Step 5 for Raspbian OS.

DOCS: Fixing formatting in 'Configurations for NCS2' article - for 22.2

---

docs/install_guides/installing-openvino-yocto.md

Updating master branch in meta-intel repository for OpenVINO 22.3.

DOCS: Update of 'Creating a YOCTO image' article - for 22.3

---

docs/install_guides/configurations-for-intel-gna.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15207
Fixing headings and adding 'What's next' section.

DOCS: Fix formatting in 'Configurations in GNA' article - for 22.3

---

.ci/azure/android_arm64.yml
.ci/azure/linux_arm64.yml
.ci/azure/linux_cuda.yml
.ci/azure/linux_debian.yml
.ci/azure/linux_ngraph_onnx.yml
.ci/azure/linux_onnxruntime.yml
.ci/azure/mac.yml

- Skipping checks where layer tests are not executed
- 99680

Skip unnecessary checks for Layer Tests

---

src/plugins/intel_cpu/src/utils/ngraph_transformation.hpp

- Ensure cross-platform _VA_ARGS_ behavior
- 100925

[CPU][DEBUG_CAPS] Fix Windows build

---

src/bindings/python/tests/test_runtime/test_infer_request.py

[PyOV] skip dynamic test for arm

---

src/inference/src/dev/converter_utils.cpp

- Changed asserts
- CVS-101852

Fixed Windows crash: map/set iterators incompatible

---

src/bindings/python/tests/test_runtime/test_infer_request.py

* [PyOV] skip dynamic test for arm
* Update src/bindings/python/tests/test_runtime/test_infer_request.py
Co-authored-by: Ilya Lavrenov <ilya.lavrenov@intel.com>
Co-authored-by: Ilya Lavrenov <ilya.lavrenov@intel.com>
- *item1*
- *...*
- *ticket-id*

[PyOV] skip dynamic test for arm (#15257)

---

src/bindings/python/wheel/CMakeLists.txt

- Ported https://github.com/openvinotoolkit/openvino/pull/15215 to master

Use manylinux2014 instead of manylinux_2_17 as a platform tag

---

docs/OV_Runtime_UG/Samples_Overview.md
docs/install_guides/configurations-for-intel-gpu.md
docs/install_guides/installing-openvino-pip.md
docs/install_guides/troubleshooting-issues.md
docs/install_guides/troubleshooting-steps.md

This addresses issues in the following:
- *https://github.com/openvinotoolkit/openvino/issues/15090*

DOCS: Fix installation issues for #15090 - port to master

---

src/plugins/intel_cpu/src/infer_request.cpp
src/plugins/intel_cpu/src/infer_request.h
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/behavior/infer_request/io_blob.hpp
src/tests/functional/plugin/shared/src/behavior/ov_infer_request/infer_request_dynamic.cpp
src/tests/functional/plugin/shared/src/behavior/ov_infer_request/io_tensor.cpp

- *porting code from [5902](https://github.com/openvinotoolkit/openvino/pull/5902)*
- *Renewed external pointers before infer to take into account user's manipulations with blob*
- *Compatibility with preprocessing*
- *disable this test on GPU, there is also blob allocated issue, created ticket 100145 for it*
- *fix the shape issue in set_shape test*
- *27632*

[CPU] Allow external blob to be reallocated

---

tests/layer_tests/tensorflow_tests/test_tf_BroadcastTo.py

- Added layer test for BroadcastTo operation
- 92755

[TF FE] Added BroadcastTo layer tests

---

tools/pot/openvino/tools/pot/algorithms/quantization/utils.py
tools/pot/openvino/tools/pot/app/argparser.py
tools/pot/openvino/tools/pot/configs/hardware_config.py
tools/pot/openvino/tools/pot/graph/cpu_patterns.py
tools/pot/openvino/tools/pot/graph/gna_patterns.py
tools/pot/openvino/tools/pot/graph/gpu_patterns.py
tools/pot/openvino/tools/pot/graph/model_utils.py
tools/pot/openvino/tools/pot/graph/passes.py
tools/pot/openvino/tools/pot/graph/pattern_utils.py
tools/pot/openvino/tools/pot/graph/special_patterns.py
tools/pot/openvino/tools/pot/graph/utils.py
tools/pot/openvino/tools/pot/graph/vpu_patterns.py
tools/pot/tests/data/reference_models/resnet_example_pytorch.xml
tools/pot/tests/test_graph.py

- *[CPU_SPR] Update Resnet quantization*
Before / After
- *...*
- *97884*
- *[CPU_SPR] Swin-transformer: 80294*
- *[CPU_SPR] Twins-transformer: 80295*

[POT] Update CPU_SPR transformer quantization

---

docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-brew.md
docs/install_guides/installing-openvino-linux-header.md
docs/install_guides/installing-openvino-linux.md
docs/install_guides/installing-openvino-macos-header.md
docs/install_guides/installing-openvino-macos.md
docs/install_guides/installing-openvino-yum.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15141
- *Adding information for installing OpenVINO via Brew*
- *Updated APT page to add mentions for C++ users and align the What's Next and Additional Resources sections*
- *[CVS-98905](https://jira.devtools.intel.com/browse/CVS-98905)*

DOCS: Add brew installation & update APT and YUM pages - for master

---

src/frontends/tensorflow_common/src/op/ctc_greedy_decoder.cpp
tests/layer_tests/tensorflow_tests/test_tf_CTCGreedyDecoder.py

- CTC Greedy Decoder layer test
- 92757

[TF FE] Added CTC Greedy Decoder layer test with fixes

---

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp

- Use bfyx format as defalut for scalar layout
- 99948

[GPU] Use bfyx format as defalut for scalar layout

---

src/plugins/intel_gpu/src/graph/broadcast.cpp
src/plugins/intel_gpu/src/graph/gemm.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/broadcast.cpp
src/plugins/intel_gpu/src/graph/include/broadcast_inst.h
src/plugins/intel_gpu/src/graph/include/gemm_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_type.h
src/plugins/intel_gpu/src/graph/include/primitive_type_base.h
src/plugins/intel_gpu/src/graph/include/shape_of_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/shape_of.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/broadcast/broadcast_kernel_base.cpp
src/plugins/intel_gpu/src/plugin/ops/broadcast.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/broadcast.cpp

- *Add functional tests for dynamic input of Broadcast*
- *Extend input dimensions with '1' during setting kernel params considering dynamic case*
- *96281*

[GPU] Update Broadcast operation to use dynamic input

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/program.cpp

- This PR disables usm_host -> usm_device memory transfers in case of iGPUs since it doesn't provide any gain
- *ticket-id*

[GPU] Perform memory transfer from usm_host to usm_device for dGPU only 

---

tests/layer_tests/pytorch_tests/test_sum.py

Try to fix sporadic sum layer test fail

---

src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/transformations/insert_copy_layer.cpp
src/plugins/intel_gna/src/transformations/insert_copy_layer.hpp
src/plugins/intel_gna/tests/functional/pass_tests/broadcast_tile_issue.cpp

- added InsertCopyBeforeLayerToBeEliminated transofrmation: handling issue with
Broadcast and Tile layer in case they are eliminated from network,
- added tests for verifying fix
- 97187

[GNA] Fix issue with Parameter followed by Broadcast/Tile layer

---

docs/OV_Runtime_UG/Samples_Overview.md

Adding missing info about architecture for 'Build the Sample Applications on Microsoft Windows' section.

[DOCS] Installation issues #15090 - post merge fixes for master

---

src/bindings/python/wheel/setup.py

- Fix UserWarning on WinOS
- https://github.com/openvinotoolkit/openvino/issues/15333

[PyOV] Fix UserWarning in setup.py

---

src/common/preprocessing/CMakeLists.txt
src/common/preprocessing/tests/common/fluid_tests.cpp
src/common/preprocessing/tests/common/fluid_tests_common.hpp
src/common/preprocessing/tests/fluid_test_computations/CMakeLists.txt
src/common/preprocessing/tests/fluid_test_computations/fluid_test_computations.cpp

- See https://dev.azure.com/openvinoci/dldt/_build/results?buildId=477530&view=logs&j=503d1592-119c-586f-46c7-e27f62244013&t=0a98a7e9-bf5d-5d2d-4ef2-08b81f6cd0f5&l=1354
- These tests were not compiled for a long time, but started to be compiled after https://github.com/openvinotoolkit/openvino/pull/15244

Fixed G-API preprocessing tests

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/customJobs/job/ie-tests-linux/3887/*

Fix broken CI

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/cum_sum_ref.cl
src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/src/kernel_selector/jitter.h
src/plugins/intel_gpu/src/kernel_selector/kernels/cum_sum/cum_sum_kernel_ref.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/cum_sum.cpp

- *Add STOP_IND by shape_info in case of reverse*
- *Add dynamic functional tests*

[GPU] Add functional tests with dynamic input for CumSum op

---

src/inference/src/dev/core_impl_ie.cpp

- Removed legacy constant folding
- NA

Remove legacy constant folding from core

---

src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
src/plugins/intel_gpu/src/graph/crop.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/non_max_suppression.cpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/non_max_suppression_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/non_max_suppression/non_max_suppression_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/non_max_suppression/non_max_suppression_kernel_ref.h
src/plugins/intel_gpu/src/plugin/program.cpp
src/plugins/intel_gpu/src/runtime/layout.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
src/plugins/intel_gpu/tests/dynamic_execution/memory_realloc_test.cpp

- Enable pre-alloc for bounded dynamic shape 
- Reuse internal buffer for smaller memory
- 93614

[GPU] Optimize realloc for dynamic shape 

---

src/core/reference/src/runtime/reference/convert.cpp

- Cherry-picks: https://github.com/openvinotoolkit/openvino/pull/15336

[CORE] Fixed VEX/NonVEX performance penalty inside Convert evaluate impl

---

src/core/shape_inference/include/squeeze_shape_inference.hpp
src/core/src/type/float16.cpp

Port 15303

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/tests/test_cases/crop_gpu_test.cpp

[GPU] Add black list to avoid fusing crop before experimental_detectron_roi_feature_extractor

---

src/bindings/python/src/openvino/offline_transformations/__init__.py

- Port of -- https://github.com/openvinotoolkit/openvino/pull/15319
- 98829

[PyOV] Update futureWarning in offline_transformations (#15319)

---

src/frontends/pytorch/src/transforms/append_list_unpack_replacer.cpp
src/frontends/pytorch/src/transforms/aten_cat_replacer.cpp
src/frontends/pytorch/src/transforms/aten_getitem_replacer.cpp
src/frontends/pytorch/src/transforms/max_prim_list_construct_replacer.cpp
src/frontends/pytorch/src/transforms/prim_list_unpack_replacer.cpp
src/frontends/pytorch/src/utils.cpp
src/frontends/pytorch/src/utils.hpp

- *Remove opset include from header*
- *Pass **NodeContext** as const in utils helper functions*
- *None*

Remove opset include from utils.hpp

---

src/inference/dev_api/openvino/runtime/icompiled_model.hpp
src/inference/src/compiled_model.cpp
src/inference/src/dev/converter_utils.cpp
src/inference/src/dev/icompiled_model.cpp
src/inference/src/dev/icompiled_model_wrapper.cpp
src/inference/src/dev/icompiled_model_wrapper.hpp

- Fixed comments after PR https://github.com/openvinotoolkit/openvino/pull/15276
- *ticket-id*

Fixed compiled model leftovers

---

src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp

- *Update device architecture to support other vendors. Examples:*
```
Immutable: DEVICE_ARCHITECTURE : GPU: vendor=0x8086 arch=v12.0.0
Immutable: DEVICE_ARCHITECTURE : GPU: vendor=0x10de arch=v8.6.0
```
- *ticket-id*

[GPU]: Update device architecture to support other vendors

---

.gitmodules

- After https://github.com/google/flatbuffers/pull/7801

Migrate to official flatbuffers repo

---

docs/install_guides/installing-openvino-yum.md

Adding a missing filename in instructions for 'Set up the repository' section of 'Install OpenVINO from YUM' article.
- *100947*

[DOCS] Add a filename for YUM repo file.

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_onnx.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_onnx.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_onnx.h
src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_selector.cpp
src/plugins/intel_gpu/tests/fusions/fusion_validity_test.cpp
src/plugins/intel_gpu/tests/test_cases/resample_gpu_test.cpp

- added 3-axis interpolation for linear-onnx mode
- fixed resample_opt for onnx mode, it didn't work in case of padding
- added tests for the new implementation and fix
- 96212

[GPU] Feature/intepolate 3 axes onnx 5d

---

src/frontends/tensorflow_common/src/op/crop_and_resize.cpp
tests/layer_tests/tensorflow_tests/test_tf_CropAndResize.py

**Details:** Make it more reshape-oriented. It allows to convert Mask R-CNN model without config file.
**Tickets:** 99304, 92856

[TF FE] Refactor CropAndResize support

---

src/bindings/python/CMakeLists.txt
tools/mo/unit_tests/mock_mo_frontend/mock_mo_python_api/CMakeLists.txt

Setup minimum supported version for pybind11

---

src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_plugin/properties.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/properties_tests.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp

- *item1*
- *...*
- *CVS98924*

[apiConformance] Add tests on props

---

tests/layer_tests/pytorch_tests/test_sub.py

- Layer test for `aten::sub` operator has been added.
- 101097

[PT FE] Add layer test for aten::sub operator

---

src/bindings/python/setup.py
src/bindings/python/src/openvino/runtime/utils/node_factory.py
src/bindings/python/tests/test_graph/test_create_op.py
src/bindings/python/tests/test_graph/test_dft.py
src/bindings/python/tests/test_graph/test_eye.py
src/bindings/python/tests/test_graph/test_ops_unary.py
src/bindings/python/tests/test_graph/test_rdft.py
src/bindings/python/tests/test_graph/test_reduction.py

- *item1*
- *...*
- *ticket-id*

[PyOV] Change default opset9->opset10

---

src/plugins/intel_cpu/src/nodes/fullyconnected.cpp

- *cpu specific shape infer for FC*
- *100505*

[CPU]FC shape infer with an CPU shapeInfer object

---

docs/openvino_sphinx_theme/openvino_sphinx_theme/static/css/media/burger.svg
docs/openvino_sphinx_theme/openvino_sphinx_theme/static/css/openvino_sphinx_theme.css

Adjusting the resolution for mobile devices. Adding a new burger icon.

[DOCS] Restyling the documentation website - for master

---

docs/openvino_sphinx_theme/openvino_sphinx_theme/static/css/media/burger.svg
docs/openvino_sphinx_theme/openvino_sphinx_theme/static/css/openvino_sphinx_theme.css

Porting: https://github.com/openvinotoolkit/openvino/pull/15409
Adjusting the resolution for mobile devices. Adding a new burger icon.

[DOCS] Restyling the documentation website - for 22.3

---

scripts/install_dependencies/install_NEO_OCL_driver.sh

Unlock possibility to install GPU driver on ubuntu22

---

src/core/shape_inference/include/utils.hpp

- Add check for nullptr
- CVS-102589, CVS-102587

Fix sanitizer SEGV

---

src/inference/src/dev/converter_utils.cpp
src/inference/src/dev/core_impl_ie.cpp

Fixed cc build

---

src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_executable_network/get_metric.cpp
src/tests/functional/plugin/shared/include/base/ov_behavior_test_utils.hpp
src/tests/functional/plugin/shared/src/behavior/ov_executable_network/get_metric.cpp

- fix cases not getting instantiated and thus not been test in CI
- 102744

fix cases not getting instantiated

---

src/frontends/tensorflow_common/src/op/expand_dims.cpp
tests/layer_tests/tensorflow_tests/test_tf_ExpandDims.py

**Details:** Refactor ExpandDims translator and add tests
**Ticket:** 92774

[TF FE] Refactor ExpandDims translator and add tests

---

src/inference/include/openvino/runtime/properties.hpp

- port changes from PR #14897
- 100153

properties.hpp: Undef DEBUG macro for log level property

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *If cache is not enough, run other tests in gtest parallel mode*
- *102890*

Extend Parallel runner to work in hybrid mode in case cache is not relevant

---

src/bindings/python/src/openvino/frontend/pytorch/decoder.py
src/core/src/op/if.cpp
src/frontends/pytorch/src/utils.cpp
tests/layer_tests/py_frontend_tests/test_torch_decoder.py

- *Fix issue with outputs shrinking*
- *bool in Python return True for `isinstance(int)` so need to check for bool first*
- *None*

Fix issue with If and bool type

---

src/plugins/intel_gpu/src/graph/impls/ocl/shuffle_channels.cpp

- Add onednn layout support for shuffle_channels
- 102500

[GPU] Add layout supports for shuffle_channels

---

src/plugins/intel_gpu/src/graph/impls/ocl/gemm.cpp
src/plugins/intel_gpu/src/graph/include/kernel_selector_helper.h
src/plugins/intel_gpu/src/graph/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
src/plugins/intel_gpu/tests/test_cases/gemm_gpu_test.cpp

- Shape agnostic optimized GEMM kernel implementation
- 99596

[GPU] Added shape agnostic optimized GEMM kernel

---

docs/install_guides/installing-model-dev-tools.md
docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-brew.md
docs/install_guides/installing-openvino-conda.md
docs/install_guides/installing-openvino-docker-linux.md
docs/install_guides/installing-openvino-docker-windows.md
docs/install_guides/installing-openvino-from-archive-linux.md
docs/install_guides/installing-openvino-from-archive-macos.md
docs/install_guides/installing-openvino-from-archive-windows.md
docs/install_guides/installing-openvino-linux-header.md
docs/install_guides/installing-openvino-linux.md
docs/install_guides/installing-openvino-macos-header.md
docs/install_guides/installing-openvino-macos.md
docs/install_guides/installing-openvino-overview.md
docs/install_guides/installing-openvino-pip.md
docs/install_guides/installing-openvino-raspbian.md
docs/install_guides/installing-openvino-windows-header.md
docs/install_guides/installing-openvino-windows.md
docs/install_guides/installing-openvino-yocto.md
docs/install_guides/installing-openvino-yum.md
docs/install_guides/pypi-openvino-dev.md
docs/install_guides/pypi-openvino-rt.md
docs/resources/supported_models.md

adding selector tool links as additional resources in install articles
updating formatting for two buttons

[DOCS] minor adjustments to Add. Res. sections in Install guide

---

docs/install_guides/installing-model-dev-tools.md
docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-brew.md
docs/install_guides/installing-openvino-conda.md
docs/install_guides/installing-openvino-docker-linux.md
docs/install_guides/installing-openvino-docker-windows.md
docs/install_guides/installing-openvino-from-archive-linux.md
docs/install_guides/installing-openvino-from-archive-macos.md
docs/install_guides/installing-openvino-from-archive-windows.md
docs/install_guides/installing-openvino-linux-header.md
docs/install_guides/installing-openvino-linux.md
docs/install_guides/installing-openvino-macos-header.md
docs/install_guides/installing-openvino-macos.md
docs/install_guides/installing-openvino-overview.md
docs/install_guides/installing-openvino-pip.md
docs/install_guides/installing-openvino-raspbian.md
docs/install_guides/installing-openvino-windows-header.md
docs/install_guides/installing-openvino-windows.md
docs/install_guides/installing-openvino-yocto.md
docs/install_guides/installing-openvino-yum.md
docs/install_guides/pypi-openvino-dev.md
docs/install_guides/pypi-openvino-rt.md
docs/resources/supported_models.md

port https://github.com/openvinotoolkit/openvino/pull/15462

Docs formatting for models article port

---

src/frontends/tensorflow_common/src/op/leaky_relu.cpp
tests/layer_tests/tensorflow_tests/test_tf_LeakyRelu.py

**Details:** Refactor LeakyRelu and add layer tests
**Ticket:** 92787

[TF FE] Refactor LeakyRelu and add layer tests

---

src/frontends/tensorflow_common/src/op/linspace.cpp
tests/layer_tests/tensorflow_tests/test_tf_LinSpace.py

**Details:** Refactor LinSpace translator and add layer test
**Ticket:** 92790

[TF FE] Refactor LinSpace translator and add layer test

---

src/common/low_precision_transformations/include/low_precision/propagate_through_precision_preserved.hpp
src/common/low_precision_transformations/include/low_precision/propagate_to_input.hpp
src/common/low_precision_transformations/include/low_precision/rt_info/avg_pool_precision_preserved_attribute.hpp
src/common/low_precision_transformations/include/low_precision/rt_info/intervals_alignment_attribute.hpp
src/common/low_precision_transformations/include/low_precision/rt_info/precisions_attribute.hpp
src/common/low_precision_transformations/include/low_precision/rt_info/quantization_alignment_attribute.hpp
src/common/low_precision_transformations/src/rt_info/avg_pool_precision_preserved_attribute.cpp
src/common/low_precision_transformations/src/rt_info/intervals_alignment_attribute.cpp
src/common/low_precision_transformations/src/rt_info/precisions_attribute.cpp
src/common/low_precision_transformations/src/rt_info/quantization_alignment_attribute.cpp

[LPT] clang merge warning fix

---

samples/cpp/build_samples_msvc.bat

Close https://github.com/openvinotoolkit/openvino/issues/14825

Parallelize build_samples_msvc.bat (#14828)

---

cmake/developer_package/compile_flags/os_flags.cmake

- After https://github.com/openvinotoolkit/openvino/pull/15502

Added "-Woverloaded-virtual" warning to clang

---

scripts/CMakeLists.txt

- Since the issue are fixed here https://github.com/openvinotoolkit/openvino/pull/15484

Removed shellcheck suppression for GPU configure script

---

.ci/azure/linux_debian.yml
cmake/packaging/debian.cmake
cmake/packaging/rpm.cmake

- See https://dev.azure.com/openvinoci/dldt/_build/results?buildId=484079&view=logs&j=e0e676f4-9664-538a-6d6b-aa53516aa09f&t=6b765ac8-a946-597f-c2ee-9b7fa8f504d2&l=521

Trying to fix debian packages

---

src/plugins/intel_gpu/src/graph/include/scatter_nd_update_inst.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/scatter_nd_update.cpp
src/plugins/intel_gpu/tests/shape_infer/scatter_nd_update_si_test.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/scatter_nd_update.cpp

- *Update ScatterNDUpdate Op to use ngraph shape infer*
- *95092*

[GPU] Update ScatterNDUpdate Op to use ngraph shape infer

---

src/frontends/tensorflow_common/src/op/list_diff.cpp
tests/layer_tests/tensorflow_tests/test_tf_ListDiff.py

**Details:** Refactor ListDiff translator and add layer test
**Ticket:** 92791

[TF FE] Refactor ListDiff translator and add layer test

---

tests/layer_tests/tensorflow_tests/test_tf_If.py

**Details:** Add layer tests for If operation
**Tickets:** 92783, 92832

[TF FE] Add layer tests for If operation

---

docs/install_guides/installing-openvino-yum.md

- *port from [#15453](https://github.com/openvinotoolkit/openvino/pull/15453)*
- *...*
- *ticket-id*

Add a disclaimer about CentOS for YUM install (#15453)

---

docs/install_guides/installing-openvino-from-archive-windows.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15356
Fixing links in 'Additional Resources' section of the article.

[DOCS] Fixing links in 'Install Openvino on Windows from Archive' article - for 22.2

---

docs/install_guides/installing-openvino-from-archive-windows.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15356
Fixing links in 'Additional Resources' section of the article.

[DOCS] Fixing links in 'Install Openvino on Windows from Archive' article - for 22.3

---

docs/install_guides/installing-openvino-from-archive-windows.md

Fixing links in 'Additional Resources' section of the article.

[DOCS]Fixing links in 'Install Openvino on Windows from Archive' article - for master

---

src/frontends/tensorflow_common/src/op/pack.cpp
tests/layer_tests/tensorflow_tests/test_tf_Pack.py

**Details:** Add layer test for Pack
**Ticket:** 92869

[TF FE] Add layer test for Pack

---

src/plugins/intel_gpu/src/graph/impls/ocl/strided_slice.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/strided_slice/strided_slice_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/strided_slice/strided_slice_kernel_ref.h
src/plugins/intel_gpu/src/plugin/ops/strided_slice.cpp
src/plugins/intel_gpu/tests/test_cases/strided_slice_gpu_test.cpp

[GPU] Added strided_slice shape agnostic kernel

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *item1*
- *...*
- *ticket-id*

[CONFORMANCE] Change log extension in runner

---

src/frontends/tensorflow_common/src/op/unpack.cpp
tests/layer_tests/tensorflow_tests/test_tf_Unpack.py

**Details:** Refactor Unpack and add layer test
**Ticket:** 92852

[TF FE] Refactor Unpack and add layer test

---

src/plugins/intel_gpu/src/graph/assign.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/assign.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/read_value.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/assign_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/read_value_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/read_value.cpp
src/plugins/intel_gpu/src/plugin/graph.cpp
src/plugins/intel_gpu/tests/test_cases/variable.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp

- Serialization of `read_value` and `assign` primitives
- 98690

[GPU] Serialization of read_value and assign

---

cmake/developer_package/download/download_and_extract.cmake

**This should be merged after changes in hddl-plugin.** 
Related PRs:
- https://gitlab-icv.toolbox.iotg.sclab.intel.com/inference-engine/hddl-plugin/-/merge_requests/308
- https://github.com/intel-innersource/frameworks.ai.openvino.inference-engine.hddl-plugin/pull/1
New location:
- https://storage.openvinotoolkit.org/drivers/vpu/hddl/2022.3/

[HDDL] - Update path

---

src/frontends/tensorflow_common/src/op/range.cpp
tests/layer_tests/tensorflow_tests/test_tf_Range.py

**Details:** Refactor Range and add layer test
**Ticket:** 92816

[TF FE] Refactor Range and add layer test

---

src/tests/functional/plugin/conformance/subgraphs_dumper/src/ops_cache.cpp
src/tests/functional/plugin/conformance/test_runner/conformance_infra/src/read_ir_test/read_ir.cpp

[CONFORMANCE] FIX bug with the dynamic shapes to separate run

---

src/plugins/intel_cpu/src/nodes/grid_sample.cpp
src/plugins/intel_cpu/src/nodes/kernels/grid_sample.cpp
src/plugins/intel_cpu/src/nodes/kernels/jit_kernel_base.cpp
src/plugins/intel_cpu/src/nodes/kernels/jit_kernel_base.hpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/grid_sample.cpp

- *Fix for sporadic SIGFAULT in GridSample.*
- *The relative threshold for bf16 was changed to 0.01*
- *94989*

[CPU] Sporadic SIGFAULT in GridSample.

---

src/frontends/tensorflow_common/src/op/shape.cpp
tests/layer_tests/tensorflow_tests/test_tf_Shape.py

**Details:** Refactor Shape translator and add layer test
**Ticket:** 92821

[TF FE] Refactor Shape translator and add layer test

---

src/frontends/tensorflow_common/src/op/reshape.cpp
tests/layer_tests/tensorflow_tests/test_tf_Reshape.py

**Details:** Refactor Reshape and add layer test
**Ticket:** 92817

[TF FE] Refactor Reshape and add layer test

---

src/frontends/tensorflow_common/src/op/softmax.cpp
tests/layer_tests/tensorflow_tests/test_tf_Softmax.py

**Details:** Refactor Softmax and add layer test
**Ticket:** 92822

[TF FE] Refactor Softmax and add layer test

---

scripts/install_dependencies/install_NEO_OCL_driver.sh

install_NEO_OCL_driver: Fixed ShellCheck errors

---

src/plugins/intel_myriad/myriad_plugin/myriad_executable_network.cpp

- the myriad plugin requests a task executor (ie::ITaskExecutor) based on the name of the loaded network. If two or more networks are loaded on separate devices from blob files, they will have the same name, therefore will get the same task executor. The net effect is that the completion of one inference is determined by the completion of another inference running on another device. The proposed solution is to ensure that every loaded network gets a unique name.
- https://jira.devtools.intel.com/browse/CVS-88683

Fix Myriad plugin wait for inference on multiple devices

---

src/plugins/hetero/executable_network.cpp
src/tests/functional/plugin/shared/include/behavior/executable_network/get_metric.hpp

- *Return only own properties for compiled model in HETERO plugin*
- *96210*

[HETERO] Return only own properties for compiled model

---

docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_CRNN_From_Tensorflow.md

- Port https://github.com/openvinotoolkit/openvino/pull/14531 to release 22.1
- CVS-98838

[Docs] Port fix convert tf crnn model docs for release 22.1

---

docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_CRNN_From_Tensorflow.md

- Port https://github.com/openvinotoolkit/openvino/pull/14531 to release 22.2
- CVS-98838

[Docs] Port fix convert tf crnn model docs for release 22.2 

---

docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_CRNN_From_Tensorflow.md

- Port https://github.com/openvinotoolkit/openvino/pull/14531 to release 22.3
- CVS-98838

[Docs] Port fix convert tf crnn model docs for release 22.3

---

src/core/include/ngraph/opsets/opset.hpp

- *item1*
- *...*
- *ticket-id*

Fix void function returns value kw issue

---

src/frontends/tensorflow_common/src/op/linspace.cpp

**Details:** Fix sporadic failure in LinSpace
**Ticket:** 103318

[TF FE] Fix sporadic failure in LinSpace

---

src/frontends/onnx/tests/models/top_k_repeating.prototxt
src/frontends/onnx/tests/models/top_k_repeating_1D.prototxt
src/frontends/onnx/tests/models/top_k_repeating_axis_0.prototxt
src/frontends/onnx/tests/models/top_k_repeating_unsorted.prototxt
src/frontends/onnx/tests/onnx_import.in.cpp
src/frontends/onnx/tests/runtime/ie/unit_test.manifest
src/frontends/onnx/tests/runtime/interpreter/unit_test.manifest
src/tests/engines_util/test_case.cpp
src/tests/engines_util/test_case.hpp

- Missing test for some corner cases
- Some tests are disabled and waiting for the new version of OV TopK
- 88024

ONNX TopK missing tests

---

src/tests/functional/plugin/conformance/subgraphs_dumper/src/main.cpp
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/data/models.lst
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_conformance.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/utils/file_utils.py

- *Add support of download models by list file*
- *Add support of working with original models via frontends*
- *103277*

[CONFORMANCE] Add support of models and lists of models to the conformance rrunner

---

tools/mo/openvino/tools/mo/ops/broadcast.py
tools/mo/unit_tests/mo/ops/broadcast_test.py

- *Add support for dynamic cases in legacy Broadcast shape infer*
- *103308*
- *#15427*

[MO] Add support for dynamic cases in legacy Broadcast shape infer

---

src/frontends/pytorch/src/op/conv_transposend.cpp
src/frontends/pytorch/src/op/convnd.cpp
src/frontends/pytorch/src/op/convolution.cpp
src/frontends/pytorch/src/op/convolution_mode.cpp
src/frontends/pytorch/src/utils.cpp
src/frontends/pytorch/src/utils.hpp
tests/layer_tests/pytorch_tests/test_convnd.py

- *Do not use shape of input for reshaping kernel.*
- *103249*

[PT FE] Fix GroupConvolution weights reshape

---

src/core/shape_inference/include/reverse_shape_inference.hpp

- *item1*
- *...*
- *ticket-id*

Fixed compilation error after conflicting PRs merge

---

src/inference/dev_api/ie_system_conf.h
src/inference/include/ie/streams_executor.hpp
src/inference/src/os/lin/lin_system_conf.cpp
src/inference/src/os/win/win_system_conf.cpp
src/inference/src/streams_executor.hpp
src/inference/tests/unit/cpu_map_parser.cpp

- move CPU mapping parser API from dev_api header file to specific header file
- 103312

move CPU mapping parser API from dev_api header file to specific header file

---

src/plugins/intel_gpu/src/graph/impls/ocl/scatter_nd_update.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/scatter_nd_update_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_nd_update_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_nd_update_kernel_ref.h
src/plugins/intel_gpu/tests/test_cases/scatter_nd_update_gpu_test.cpp

[GPU] Added ScatterNDUpdate shape agnostic kernel

---

src/frontends/pytorch/src/op/rsub.cpp
tests/layer_tests/pytorch_tests/test_rsub.py
tests/layer_tests/pytorch_tests/test_sub.py

- *add test for aten::rsub*
- *support mixed precision inputs in aten::rsub*

[PT FE]: add tests for rsub and handle mixed precision

---

src/inference/src/ie_core.cpp
src/inference/tests/functional/ov_extension_test.cpp
src/tests/ie_test_utils/common_test_utils/file_utils.cpp
src/tests/ie_test_utils/common_test_utils/file_utils.hpp

* Resolve relative path to the extension [#15047]
* Add test to verify add_extension with relative path[#15212]

Port relative path 2022.3

---

tools/mo/openvino/tools/mo/convert_impl.py
tools/mo/unit_tests/moc_tf_fe/conversion_basic_models.py
tools/mo/unit_tests/moc_tf_fe/test_models/model_oneshot_iterator.pbtxt

**Details:** Add additional fallback for Iterator operations
**Ticket:** 102606

[MO][TF FE] Add additional fallback for Iterator operations

---

src/plugins/intel_gpu/src/graph/impls/ocl/non_zero.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/count_nonzero_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_nonzero_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/non_zero/count_nonzero_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/non_zero/count_nonzero_kernel_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/non_zero/gather_nonzero_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/non_zero/gather_nonzero_kernel_ref.h
src/plugins/intel_gpu/tests/test_cases/non_zero_gpu_test.cpp

- Shape agnostic NonZero ref kernel implementation
- 95104

[GPU] Added shape agnostic NonZero ref kernel

---

src/frontends/tensorflow_common/src/op/tile.cpp
tests/layer_tests/tensorflow_tests/test_tf_Tile.py

**Details:** Refactor Tile and add layer test
**Ticket:** 92848

[TF FE] Refactor Tile and add layer test

---

src/plugins/intel_gpu/src/plugin/plugin.cpp
src/tests/functional/plugin/gpu/CMakeLists.txt
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_plugin/core_integration.cpp

- *Replace ov::intel_gpu::uarch_version and ov::intel_gpu::device_id by ov::device::architecture in ov::caching_properties.*
- *Add ov::inference_precision and ov::hint::execution_mode to ov::caching_properties.*
- *ticket-id*

[GPU] Update caching properties for GPU

---

.ci/azure/android_arm64.yml
.ci/azure/linux.yml
.ci/azure/linux_arm64.yml
.ci/azure/linux_conditional_compilation.yml
.ci/azure/linux_debian.yml
.ci/azure/linux_onnxruntime.yml

Reverts openvinotoolkit/openvino#15240

Revert "[CI] Add task UsePythonVersion@0 to Azure Pipelines"

---

src/inference/include/ie/ie_blob.h
src/inference/src/ie_blob_common.cpp

- Port PR #15516
- *ticket-id*

Port #15516

---

src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/transformation_pipeline.h
src/plugins/intel_cpu/src/utils/debug_capabilities.h

Build with enabled CPU debug capabilities is broken after PR [#15513](https://github.com/openvinotoolkit/openvino/pull/15513) merge into master. This PR reverts particular changes that introduce the build issue.

[CPU][DEBUG CAPS] Build fix

---

src/plugins/intel_gpu/src/graph/impls/ocl/scatter_update.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/scatter_update_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_update_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_update_kernel_ref.h
src/plugins/intel_gpu/tests/test_cases/scatter_update_gpu_test.cpp

[GPU] Added ScatterUpdate shape agnostic kernel

---

src/frontends/tensorflow_common/src/op/lrn.cpp

**Details:** Fix sporadic failure for TF1 LRN layer test
**Ticket:** 103487

[TF FE] Fix sporadic failure for TF1 LRN layer test

---

src/frontends/tensorflow_common/src/op/log1p.cpp
tests/layer_tests/tensorflow_tests/test_tf_Log1p.py

**Details:** Refactor Log1p translator and add layer test
**Ticket:** 92865

[TF FE] Refactor Log1p translator and add layer test

---

src/plugins/intel_gpu/include/intel_gpu/graph/serialization/binary_buffer.hpp
src/plugins/intel_gpu/include/intel_gpu/graph/serialization/bind.hpp
src/plugins/intel_gpu/include/intel_gpu/graph/serialization/buffer.hpp
src/plugins/intel_gpu/include/intel_gpu/graph/serialization/polymorphic_serializer.hpp
src/plugins/intel_gpu/include/intel_gpu/graph/serialization/utils.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/loop.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/non_max_suppression.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/primitive.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/proposal.hpp
src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/non_max_suppression.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/proposal.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/non_max_suppression_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/proposal_inst.h
src/plugins/intel_gpu/src/graph/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/proposal.cpp
src/plugins/intel_gpu/src/plugin/compiled_model.cpp
src/plugins/intel_gpu/tests/test_cases/detection_output_test.cpp
src/plugins/intel_gpu/tests/test_cases/loop_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/non_max_suppression_test.cpp
src/plugins/intel_gpu/tests/test_cases/proposal_cpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/serialization_test.cpp
src/plugins/intel_gpu/tests/test_utils/test_utils.h

- Serialization of the selected primitives
- proposal, loop, nms
- By serializing the primitive class, several duplicated copies can be avoided.
- 100089, 102630

[GPU] Serialization of the primitive class

---

src/frontends/tensorflow_common/src/op/split.cpp
tests/layer_tests/tensorflow_tests/test_tf_Split.py
tests/layer_tests/tensorflow_tests/test_tf_SplitV.py

**Details:** Refactor Split and SplitV translators and add layer tests
**Ticket:** 92879

[TF FE] Refactor Split and SplitV translators and add layer tests

---

src/frontends/tensorflow_common/src/op/size.cpp
tests/layer_tests/tensorflow_tests/test_tf_Size.py

**Details:** Refactor Size translator and add layer test
**Ticket:** 92876

[TF FE] Refactor Size translator and add layer test

---

src/frontends/tensorflow_common/src/op/reciprocal.cpp
tests/layer_tests/tensorflow_tests/test_tf_Reciprocal.py

**Details:** Refactor Reciprocal translator and add layer test
**Ticket:** 92874

[TF FE] Refactor Reciprocal translator and add layer test

---

docs/img/deployment_simplified.svg

Update of deployment_simplified.svg image.

[DOCS] deployment_simplified image update for master

---

src/plugins/intel_cpu/src/nodes/pad.h

- *fix mac build with unused value*
- *...*
- *ticket-id*

remove unused value

---

src/plugins/intel_gpu/include/intel_gpu/primitives/range.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/range.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/range_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/range/range_kernel_ref.cpp
src/plugins/intel_gpu/src/plugin/ops/range.cpp
src/plugins/intel_gpu/tests/test_cases/range_gpu_test.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/range.cpp

[GPU] Added shape agnostic kernel support for Range + fix dynamic tests

---

src/frontends/pytorch/CMakeLists.txt
src/frontends/pytorch/src/op/eye.cpp
src/frontends/pytorch/src/op/repeat_interleave.cpp
src/frontends/pytorch/src/pt_framework_node.hpp
src/frontends/pytorch/src/transforms/append_list_unpack_replacer.cpp
src/frontends/pytorch/src/transforms/aten_getitem_replacer.cpp
src/frontends/pytorch/src/utils.cpp
src/frontends/pytorch/src/utils.hpp

- *Remove warnings suppression in frontend code*
- *103431*

[PT FE] Remove warnings suppression in frontend code

---

samples/c/common/opencv_c_wrapper/bmp_reader.c
samples/c/hello_nv12_input_classification/main.c
src/frontends/paddle/CMakeLists.txt
src/frontends/paddle/src/frontend.cpp
src/frontends/paddle/src/input_model.cpp
src/frontends/paddle/src/internal/op/conditional_block.cpp
src/frontends/paddle/src/internal/op/while.cpp
src/frontends/paddle/src/internal/pass/transform_if.cpp
src/frontends/paddle/src/op/meshgrid.cpp
src/frontends/paddle/src/op/slice_ops.hpp
src/frontends/paddle/src/op/sum.cpp
src/frontends/paddle/src/place.cpp

- *fix warnings in /paddle and add -Wsign-compare*
- *103433*

Fix sign-compare warnings in PDPD FE

---

src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/src/backend/gna_limitations.hpp
src/plugins/intel_gna/src/frontend/model_quantizer.hpp
src/plugins/intel_gna/src/gna_graph_compiler.cpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/gna_transformations_pipeline.cpp
src/plugins/intel_gna/src/gna_transformations_pipeline.hpp
src/plugins/intel_gna/src/ops/util/util.hpp
src/plugins/intel_gna/src/transformations/utils/transformation_helper.cpp
src/plugins/intel_gna/src/transformations/utils/transformation_helper.hpp
src/plugins/intel_gna/tests/deprecated/unit/engines/gna/I8_quantisation_test.cpp
src/plugins/intel_gna/tests/deprecated/unit/engines/gna/graph_tools/graph_copy_tests.cpp
src/plugins/intel_gna/tests/deprecated/unit/engines/gna/i16_quantisation_test.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/convolution_negative.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_gna/tests/unit/gna_get_aligned_split_sizes.cpp

- *Get back QueryNetwork  for GNA plugin (ngraph based)*
- *High level checks for supported layers (should be finilazed later, when all transformation will moved to ngraph)*
- *Convert constant precision using ngraph transformation* 
- *Enable some previously disabled tests*
- *24757*
- *29577*
- *32923*
- *52093*

[GNA]: QueryNetwork support

---

tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
tests/layer_tests/pytorch_tests/test_bool.py

- *item1*
- *...*
- *ticket-id*

[PT FE]: fix sporaidic failure in pytorch layer tests

---

src/plugins/intel_gpu/src/plugin/ops/constant.cpp

-  fix getConstTensor() for 1d from [1,N,1,1] to [N,1,1,1]
- 102743

[GPU] fix getConstTensor() for 1d from [1,N,1,1] to [N,1,1,1]

---

src/plugins/intel_gpu/include/intel_gpu/primitives/arg_max_min.hpp
src/plugins/intel_gpu/src/graph/arg_max_min.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/arg_max_min.cpp
src/plugins/intel_gpu/src/plugin/ops/topk.cpp
src/plugins/intel_gpu/tests/shape_infer/arg_max_min_si_test.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/top_k.cpp

- *Update TopK to support parameter input*
- *Refactor primitive_impl create for arg_max_min*
- *Add new constructors for new shape infer*
- *98114*

[GPU] Update TopK to support non const top_k input

---

src/plugins/intel_cpu/src/nodes/matmul.cpp

- simplify the shape infer flow for matmul
- 100506

optimize shape_infer time of matmul

---

tests/layer_tests/tensorflow_tests/test_tf_Concat.py

**Details:** Refactor Concat layer test and extend pre-commit
**Ticket:** 92883

[TF FE] Refactor Concat layer test and extend pre-commit

---

src/frontends/tensorflow_common/src/op/squeeze.cpp
tests/layer_tests/tensorflow_tests/test_tf_Squeeze.py

**Details:** Refactor Squeeze and layer test
**Ticket:** 92831

[TF FE] Refactor Squeeze and layer test

---

src/frontends/tensorflow_common/src/op/identity.cpp
tests/layer_tests/tensorflow_tests/test_tf_IdentityN.py

**Details:** Refactor IdentityN translator and add layer test
**Ticket:** 92887

[TF FE] Refactor IdentityN translator and add layer test

---

docs/install_guides/uninstalling-openvino.md

- *item1*
- *...*
- *[CVS-100955](https://jira.devtools.intel.com/browse/CVS-100955)*

Fix an issue with uninstall

---

src/plugins/intel_gpu/src/graph/include/loop_inst.h

- Add mem_lock_type of get_sliced_mem() in loop
- 103594

[GPU] Add mem_lock_type of get_sliced_mem() in loop

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/mvn_gpu_bfyx_opt.cl
src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/src/kernel_selector/jitter.h
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/mvn/mvn_kernel_base.h
src/plugins/intel_gpu/src/kernel_selector/kernels/mvn/mvn_kernel_bfyx_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/non_zero/gather_nonzero_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/reduce/reduce_kernel_base.cpp
src/plugins/intel_gpu/tests/test_cases/mvn_gpu_test.cpp

- Shape agnostic optimized MVN kernel implementation
- 102838

[GPU] Added shape agnostic optimized MVN kernel

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/strided_slice/strided_slice_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/strided_slice/strided_slice_kernel_ref.h
src/plugins/intel_gpu/tests/fusions/strided_slice_fusion_test.cpp

[GPU] Geti: Add jit value for fused_ops in strided_slice_ref

---

src/plugins/hetero/executable_network.cpp
src/plugins/hetero/graph_debug_dump.cpp
src/plugins/hetero/graph_debug_dump.hpp

- *item1*
- *...*
- *ticket-id*

HETERO move dumping dot files to separate file

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/data/models.lst
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *item1*
- *...*
- *ticket-id*

[CONFORMANCE] Fix small bug with hours && replace URL for models

---

src/tests/unit/auto/exec_network_get_metrics.cpp

- *remove invalid KEY_EXCLUSIVE_ASYNC_REQUESTS*
- *...*
- *ticket-id*

hot fix for MULTI unit test issue in CI

---

src/frontends/tensorflow_common/src/op/one_hot.cpp
tests/layer_tests/tensorflow_tests/test_tf_OneHot.py

**Details:** Refactor OneHot translator and add layer test
**Ticket:** 92813

[TF FE] Refactor OneHot translator and add layer test

---

src/frontends/tensorflow_lite/src/CMakeLists.txt
src/frontends/tensorflow_lite/src/decoder_flatbuffer.cpp

- *Treats warnings as errors for TF Lite FrontEnd*
- *102307*

Fix TFL warnings

---

src/inference/src/ie_itt.hpp
src/inference/src/ie_network_reader.cpp

- Apply CC for IR reader case: IR10 with new API,  IR11 with old API
- CVS-103542

[CC]Add CC support for ir reader

---

src/core/include/openvino/op/constant.hpp
src/core/src/op/constant.cpp

- Remove API `void set_data_shape(const Shape& shape)`
- 100091

[Remove APIs] remove api set_data_shape

---

src/frontends/tensorflow_common/src/op/gather.cpp
tests/layer_tests/tensorflow_tests/test_tf_Gather.py

**Details:** Refactor Gather operations and add layer tests
**Ticket:** 92780

[TF FE] Refactor Gather operations and add layer tests

---

tests/layer_tests/tensorflow_tests/test_tf_GatherNd.py

**Details:** Implement layer test for GatherNd translator
**Ticket:** 92779

[TF FE] Implement layer test for GatherNd translator

---

src/frontends/tensorflow_common/src/op/reverse_sequence.cpp
tests/layer_tests/tensorflow_tests/test_tf_ReverseSequence.py

**Details:** Refactor ReverseSequence and add layer test
**Ticket:** 92819

[TF FE] Refactor ReverseSequence and add layer test

---

src/common/transformations/src/transformations/common_optimizations/reverse_shape_and_type_infer.cpp
src/common/transformations/tests/common_optimizations/reverse_shape_and_type_infer.cpp
src/frontends/pytorch/src/frontend.cpp
src/plugins/intel_cpu/src/ngraph_transformations/snippets_mark_skipped.cpp

- *No need to specify input type and rank for majority of models*
- *102349*

[PT FE] Enable reverse infer

---

src/frontends/pytorch/src/op/len.cpp
tests/layer_tests/pytorch_tests/test_len.py

- *Fix aten::len for empty lists*
- *104301*

[PT FE] Fix aten::len for empty lists

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/permute_bfzyx_to_bfyxz.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_bfzyx_to_bfyxz.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_bfzyx_to_bfyxz.h
src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_selector.cpp
src/plugins/intel_gpu/tests/fusions/permute_fusion_test.cpp
src/plugins/intel_gpu/tests/test_cases/permute_gpu_test.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/transpose.cpp

- *added kernel for optimized 5d permute bfzyx to bfyxz*
- 92378

[GPU] Permute 5d optimization

---

src/plugins/intel_cpu/src/nodes/transpose.cpp

- *simplify the shape infer flow for transpose*
- *100508*

optimize the shape infer for transpose

---

src/tests/functional/plugin/shared/include/base/ov_behavior_test_utils.hpp
src/tests/functional/shared_test_classes/src/single_layer/eltwise.cpp
src/tests/functional/shared_test_classes/src/single_layer/experimental_detectron_roifeatureextractor.cpp

- This is a continuation of #15786
- CVS-104079

Remove WAs for myriad

---

src/plugins/intel_gna/src/gna_graph_patterns.hpp
src/plugins/intel_gna/src/gna_graph_tools.hpp
src/plugins/intel_gna/src/gna_transformations_pipeline.cpp
src/plugins/intel_gna/src/optimizer/gna_pass_manager.cpp
src/plugins/intel_gna/src/optimizer/gna_pass_manager.hpp
src/plugins/intel_gna/src/transformations/swap_input_matmul_gna.cpp
src/plugins/intel_gna/tests/functional/pass_tests/diagonal_insertion_test.cpp

This solution provides proposal for workaround for the problem described in the ticket by:
- Newly created legacy pass *FuseFullyConnectedWithEltwisePass* to fuse FullyConnected and Eltwise layers into single functional layer
- Removing unnecessary Reshape and Transpose layers (in case they have *practically* single dimension inputs)
- 58806

[GNA] incorrect diag insertion

---

scripts/CMakeLists.txt
scripts/setupvars/setupvars.sh

- Absence of realpath on macOS by default
- Shellcheck issues

Fixed issues in setupvars.sh

---

src/frontends/common/include/openvino/frontend/manager.hpp

- *Change from void FRONTEND_API shutdown();
to
FRONTEND_API void shutdown();*
- *CVS-93737*

ov::shutdown align definition

---

src/core/reference/include/ngraph/runtime/reference/convert_color_nv12.hpp
src/core/reference/include/ngraph/runtime/reference/convolution_backprop_data.hpp
src/core/reference/include/ngraph/runtime/reference/detection_output.hpp
src/core/reference/include/ngraph/runtime/reference/roi_align.hpp
src/plugins/template/backend/CMakeLists.txt

- *fix sign-compare warnings in template backend*
- *104393*

fix sign-compare warnings in template backend

---

install_build_dependencies.sh
scripts/install_dependencies/install_openvino_dependencies.sh
src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp

- *item1*
- *...*
- *ticket-id*

Supported OpenSUSE 15.3

---

src/frontends/pytorch/src/op/upsample.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_upsample.py

- *Extend upsample support*
- *None*

[PT FE] Extend upsample support

---

src/frontends/pytorch/src/frontend.cpp
src/frontends/pytorch/src/transforms/einsum_list_construct.cpp
src/frontends/pytorch/src/transforms/einsum_list_construct.hpp
tests/layer_tests/pytorch_tests/test_einsum.py

- *added support aten::einsum operator*
- *101058*

[PT FE]: support aten::einsum

---

src/common/transformations/include/transformations/op_conversions/convert_reduce_to_pooling.hpp
src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp

Ticket: C#67541
Error: `21:01:06  RuntimeError: Const layer Constant_23182 has incorrect dimensions in the output data 0`

[67541] - face-detection-0205, 0206 issues fixed (incorrect dimensions error)

---

docs/install_guides/uninstalling-openvino.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15720/ 
Fixing path.

[DOCS] Fix an issue with uninstall - for master

---

src/inference/include/openvino/runtime/core.hpp

- *Change from void OPENVINO_RUNTIME_API shutdown();
to
OPENVINO_RUNTIME_API void shutdown();*
- *93737*

fix ov::shutdown align definition

---

src/plugins/intel_gna/src/transformations/utils/gather_sinking_utils.cpp

[GNA] fix Coverity warning

---

src/bindings/python/wheel/requirements-dev.txt

This reverts commit e34d4e4664d1292fd6af8e69cbb78232ea96644b.
- *item1*
- *...*
- *ticket-id*

Revert "Install patchelf for aarch64 linux (#15865)"

---

src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/tests/fusions/fusion_test_common.hpp
src/plugins/intel_gpu/tests/test_utils/test_utils.cpp

[GPU] Resolve unit test not run as onednn

---

install_build_dependencies.sh
scripts/install_dependencies/install_openvino_dependencies.sh
src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp

- Ported https://github.com/openvinotoolkit/openvino/pull/15897

Supported OpenSUSE 15.3 (#15897)

---

src/frontends/tensorflow_common/src/op/fake_quant_min_max_vars.cpp
tests/layer_tests/tensorflow_tests/test_tf_FakeQuantWithMinMaxVars.py

**Details:** Simplify FakeQuantWithMinMaxVars translator and add layer test
**Ticket:** 92857

[TF FE] Simplify FakeQuantWithMinMaxVars translator and add layer test

---

src/frontends/pytorch/src/frontend.cpp
src/frontends/pytorch/src/transforms/aten_index_replacer.cpp
src/frontends/pytorch/src/transforms/aten_index_replacer.hpp
tests/layer_tests/pytorch_tests/test_index.py

- *support aten::index* 
transformation tested on swinv2, maxvit, ssd300 from torchvision, coatnets from timm
- *94303*

[PT FE]: support aten::index

---

src/bindings/python/src/openvino/runtime/utils/data_helpers/data_dispatcher.py
src/bindings/python/tests/test_runtime/test_infer_request.py

- Fix passing of the key for copy scenario in the inference's data dispatcher.
- #15902 
- *104787*

[PyOV] Fix passing of the key in data dispatcher

---

src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp

- Fix issue mentioned in https://github.com/openvinotoolkit/openvino/pull/15683#discussion_r1117474479

[GPU] Fix build error in clang++

---

src/bindings/python/wheel/requirements-dev.txt

Top-limited setuptools with 65.7.0 version

---

cmake/developer_package/api_validator/api_validator.cmake
cmake/developer_package/api_validator/api_validator_run.cmake
src/plugins/intel_gna/cmake/libGNAConfig.cmake

- *item1*
- *...*
- *ticket-id*

Fix for apiValidator when more than 1 target needs to be checked

---

scripts/CMakeLists.txt
scripts/setupvars/setupvars.sh

Ported https://github.com/openvinotoolkit/openvino/pull/15884

Fixed issues in setupvars.sh (#15884)

---

src/plugins/intel_gpu/src/graph/impls/ocl/crop.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/generic_eltwise_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernel_base_opencl.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/eltwise/eltwise_kernel_base.cpp
src/plugins/intel_gpu/tests/test_cases/crop_gpu_test.cpp

- Enabled crop for shape agnostic kernel
- 95104

[GPU] Enable crop for shape agnostic kernel

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- Layout optimizer fix for quantize
- 104653

[GPU] Minor fix for dynamic mobilebert

---

tests/layer_tests/tensorflow_tests/test_tf_NestedWhile.py

**Details:** Test Nested While in the pre-commit
**Ticket:** 62349

[TF FE] Test Nested While in the pre-commit

---

src/common/snippets/src/pass/convert_constants.cpp
src/common/snippets/src/pass/convert_power_to_powerstatic.cpp

- *Porting of [PR#15883](https://github.com/openvinotoolkit/openvino/pull/15883) to the release branch*
- *104501*

[Snippets] Added matcher_name in ConvertConstantsToScalars pass

---

src/plugins/intel_gpu/src/graph/impls/ocl/gather_tree.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_tree_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/gather_tree/gather_tree_kernel_ref.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/gather_tree.cpp

[GPU] Added fp16 support for GatherTree

---

scripts/install_dependencies/install_openvino_dependencies.sh

- Ported https://github.com/openvinotoolkit/openvino/pull/15992

Install libtbb2 instead of libtbb12 on U22.04

---

cmake/developer_package/api_validator/api_validator.cmake
src/cmake/ie_parallel.cmake
src/cmake/openvino.cmake

- Ported https://github.com/openvinotoolkit/openvino/pull/15938
- 89932

Apply Apivalidator to TBB libs

---

docs/snippets/CMakeLists.txt
docs/snippets/gpu/preprocessing_nv12_single_plane.cpp
docs/snippets/gpu/preprocessing_nv12_to_gray.cpp

- Fixed regression https://dev.azure.com/openvinoci/dldt/_build/results?buildId=503574&view=logs&j=e0e676f4-9664-538a-6d6b-aa53516aa09f&t=839cb6ab-4ea8-51d4-e102-9a106ad673bf

Fixed compilation of docs snippets

---

docs/snippets/src/main.c

- Regression after https://github.com/openvinotoolkit/openvino/commit/21ac61fef5043bca830488ac4f4723b480d331c4
- *ticket-id*

Fixed typo in docs

---

cmake/developer_package/clang_format/clang_format.cmake
cmake/developer_package/frontends/frontends.cmake
src/bindings/c/include/openvino/c/openvino.h
src/bindings/c/include/openvino/c/ov_common.h
src/bindings/c/include/openvino/c/ov_compiled_model.h
src/bindings/c/include/openvino/c/ov_core.h
src/bindings/c/include/openvino/c/ov_infer_request.h
src/bindings/c/include/openvino/c/ov_model.h
src/bindings/c/include/openvino/c/ov_node.h
src/bindings/c/include/openvino/c/ov_partial_shape.h
src/bindings/c/include/openvino/c/ov_prepostprocess.h
src/bindings/c/include/openvino/c/ov_remote_context.h
src/bindings/c/include/openvino/c/ov_shape.h
src/bindings/c/include/openvino/c/ov_tensor.h
src/bindings/c/src/CMakeLists.txt

- *item1*
- *...*
- *ticket-id*

Fixed clang-format for C API

---

src/bindings/python/wheel/requirements-dev.txt
tools/openvino_dev/setup.cfg

- A warnings should disappeared with bump-up of setuptools. [Their release log](https://setuptools.pypa.io/en/latest/history.html#id42)
- 104887

Try to update minimum setuptools req

---

.github/workflows/code_snippets.yml
docs/snippets/CMakeLists.txt
thirdparty/CMakeLists.txt

- To prevent issues like
- https://dev.azure.com/openvinoci/dldt/_build/results?buildId=504368&view=logs&j=e0e676f4-9664-538a-6d6b-aa53516aa09f&t=839cb6ab-4ea8-51d4-e102-9a106ad673bf
- https://dev.azure.com/openvinoci/dldt/_build/results?buildId=503574&view=logs&j=e0e676f4-9664-538a-6d6b-aa53516aa09f&t=839cb6ab-4ea8-51d4-e102-9a106ad673bf&l=4502
- CVS-92156

Improved GA precommit to track docs regressions

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
src/plugins/intel_gpu/src/graph/include/activation_inst.h
src/plugins/intel_gpu/src/graph/include/depth_to_space_inst.h
src/plugins/intel_gpu/src/graph/include/eltwise_inst.h
src/plugins/intel_gpu/src/graph/include/fused_primitive_desc.h
src/plugins/intel_gpu/src/graph/include/kernel_impl_params.hpp
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/include/quantize_inst.h
src/plugins/intel_gpu/src/graph/include/reorder_inst.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/test_cases/condition_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/memory_test.cpp
src/plugins/intel_gpu/tests/test_cases/reshape_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/split_gpu_test.cpp

- Added backend independent fusion parameters and conversion to kernel selector specific descriptors in order to avoid ocl dependency in gpu graph.

[GPU] Backend independent fuse params

---

src/plugins/intel_gpu/src/graph/select.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/select_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/select/select_kernel_base.cpp
src/plugins/intel_gpu/tests/test_cases/select_gpu_test.cpp

[GPU] Added support mixed input formats for Select

---

src/bindings/c/include/openvino/c/ov_core.h
src/bindings/python/src/openvino/runtime/ie_api.py
src/bindings/python/src/pyopenvino/core/core.cpp
src/inference/include/openvino/runtime/core.hpp

- *item1*
- *...*
- *ticket-id*

Added TF / TF Lite in API reference docs

---

docs/_static/css/custom.css
docs/_static/html/modal.html
docs/_static/js/graphs.js

- *Added bugfixes and style improvements of modal settings*
- *Added disclaimers to modal footer*
- *Changed precision graphs colors*
- *Added default options*
- *Improved modal responsiveness*

Graph builder modal

---

src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/fetch_weights.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_weights.cl
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.cpp
src/plugins/intel_gpu/src/kernel_selector/tensor_type.cpp
src/plugins/intel_gpu/src/kernel_selector/tensor_type.h
src/plugins/intel_gpu/src/runtime/format.cpp

Integration oneDNN3.1
- *98839*

[GPU] Integration oneDNN3.1

---

.ci/azure/android_arm64.yml
.ci/azure/linux.yml
.ci/azure/linux_arm64.yml
.ci/azure/linux_conditional_compilation.yml
.ci/azure/linux_coverity.yml
.ci/azure/linux_cuda.yml
.ci/azure/linux_debian.yml
.ci/azure/linux_lohika.yml
.ci/azure/linux_ngraph_onnx.yml
.ci/azure/linux_onnxruntime.yml
.ci/azure/mac.yml
.ci/azure/windows.yml
.ci/azure/windows_conditional_compilation.yml

- To fix https://dev.azure.com/openvinoci/dldt/_build/results?buildId=505483&view=logs&j=21afc441-30ce-5735-0df5-9a014bfc4f9c&t=a1735572-e988-5e43-98d7-560169296da8

Removed fetch depth from Azure Pipelines

---

cmake/packaging/debian.cmake
cmake/packaging/rpm.cmake
thirdparty/ocl/CMakeLists.txt

- *item1*
- *...*
- CVS-102787

Fixed OpenMP + debian package code-path

---

.ci/azure/android_arm64.yml
src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp
src/plugins/intel_gpu/tests/test_cases/concatenation_gpu_test.cpp

- *item1*
- *...*
- *ticket-id*

Test GPU plugin arm64 build via Android precommit

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp

- *Recalculate processing order if the dependent nodes are not processed before the user node*
- *100866*

Added recalculating processing order if it is not correctly processed

---

src/plugins/intel_cpu/src/emitters/utils.cpp
src/plugins/intel_cpu/src/emitters/utils.hpp

- *Fix issue about overwriting register names in https://github.com/openvinotoolkit/openvino/pull/15423.*
- *101222*

[CPU] Fix issue about overwriting register names

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *item1*
- *...*
- 104436
- 105244

[CONFORMANCE] Add check the crash or non zero status in python runner

---

docs/snippets/ov_network_state_intro.py
src/bindings/python/src/pyopenvino/graph/passes/transformations.cpp
src/bindings/python/tests/test_graph/test_basic.py
src/bindings/python/tests/test_transformations/test_public_transformations.py

- code snippets are based on https://github.com/openvinotoolkit/openvino/pull/11034
- add docstrings for transformations (MakeStateful, LowLatency2)
- add one more test for `MakeStateful` transformation
- 99444

[Docs][PyOV] Add docstrings for transformations + python examples for stateful model

---

docs/nbdoc/consts.py
docs/tutorials.md

Updating the notebooks to the most recent version.

[DOCS] Notebooks - the most recent version - for 22.3

---

docs/nbdoc/consts.py
docs/tutorials.md

Updating the notebooks to the most recent version.

[DOCS] Notebooks - the most recent version

---

tools/mo/openvino/tools/mo/utils/get_ov_update_message.py

- Shifting reminder for half of a year ahead

[MO] Update reminder message for 2023.0

---

src/frontends/pytorch/src/op/arange.cpp
tests/layer_tests/pytorch_tests/test_arange.py

- *fixed issue with incorrect output type from aten::arrange translation and extended tests*
validated on hfl/chineese-xlnet-base
- *105278*

[PT FE]: fix arange dtype if it is not provided

---

src/frontends/pytorch/src/op/pad.cpp
src/frontends/pytorch/src/transforms/prim_list_construct_pad.cpp
tests/layer_tests/pytorch_tests/test_pad.py

- *fix inconsistent argument type for padding* tested on longformer models family
- **103292**

[PT FE]: fix padding value dtype

---

docs/MO_DG/prepare_model/customize_model_optimizer/Customize_Model_Optimizer.md

Porting: https://github.com/openvinotoolkit/openvino/pull/15679

[DOCS] Better statement about MO extensions as internal API - for 22.3

---

src/core/src/pass/visualize_tree.cpp

- *VisualizeTree displays tensors*

[nGraph] VisualizeTree displays tensors

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/softmax_gpu_bf.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_base.h
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_fb.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_items_class_optimized.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_ref.cpp
src/plugins/intel_gpu/tests/test_cases/softmax_gpu_test.cpp

- Shape agnostic optimized SoftMax kernel implementation
- 102836

[GPU] Added shape agnostic optimized SoftMax kernel

---

docs/dev/enabling_ci_step.md
docs/dev/get_started.md
docs/dev/index.md

- Added documentation which oversees the existed CIs
- 49714

Added CI documentation

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/graph/program.cpp

- `is_local_block_io_supported` moved to kernel selector helper

[GPU] Move local_block_io_support check to kernel selector helper

---

src/plugins/intel_gpu/src/graph/impls/ocl/gather_elements.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/range.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/softmax.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/tile.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_elements_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/tile_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_elements_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_elements_kernel_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/range/range_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/tile/tile_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/tile/tile_kernel_ref.h
src/plugins/intel_gpu/tests/test_cases/gather_elements_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/tile_gpu_test.cpp

[GPU] Added shape agnostic kernels for GatherElements and Tile

---

src/plugins/intel_gpu/include/intel_gpu/runtime/utils.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/program_helpers.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/fusions/gemm_fusion_test.cpp

This PR's purpose is for checking full models performance.
Based on https://github.com/openvinotoolkit/openvino/pull/15782 and enabling oneDNN gemm(matmul) from support multiple users and non constant input.
Fix multiple batch issue.
- *103387, 104821*

Broadcast for post ops enable enable onednngemm

---

src/core/src/pass/visualize_tree.cpp

- post commit cclang issue fix: https://dev.azure.com/openvinoci/dldt/_build/results?buildId=508194&view=logs&j=e0e676f4-9664-538a-6d6b-aa53516aa09f&t=839cb6ab-4ea8-51d4-e102-9a106ad673bf

[nGraph] VisualizeTree cclang quick fix

---

scripts/CMakeLists.txt

- *item1*
- *...*
- *ticket-id*

Fixed RelWithDebInfo build

---

src/plugins/intel_gpu/tests/fusions/lrn_fusion_test.cpp

[GPU] disable test-case: fusings_gpu/lrn_fp16_eltwise_activation.basic/7

---

src/plugins/auto_batch/tests/unit/auto_batch_infer_request_tests.cpp

- *item1*
- *...*
- *ticket-id*

Fix build error in ubuntu 22.04

---

src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_executable_network/exec_network_base.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_executable_network/get_metric.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_executable_network/properties.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
src/plugins/template/tests/functional/skip_tests_config.cpp

- *item1*
- *...*
- *CVS-74308*

Add missing ov_executable_network tests for teamplte plugin

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/binary_convolution/binary_convolution_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bs_f_bsv16_af8.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bs_f_bsv8_af8.cpp
src/plugins/intel_gpu/src/runtime/layout.cpp

[GPU] Fix binary_convolution non-constant weights

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/merge_xmls.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/utils/stat_update_utils.py

- *item1*
- *...*
- *ticket-id*

Fix generation of report in CI

---

docs/OV_Runtime_UG/ov_dynamic_shapes.md

Fixing directives for code snippets. Shifting to reST.

DOCS shift to rst - `Dynamic Shapes` article

---

docs/nbdoc/consts.py
docs/tutorials.md

Updating the notebooks to the newest version.

[DOCS] Updating `Interactive Tutorials` to the newest version - for 22.3

---

docs/nbdoc/consts.py
docs/tutorials.md

Updating the notebooks to the newest version.

[DOCS] Updating `Interactive Tutorials` to the newest version

---

docs/Documentation/openvino_ecosystem_ovtf.md

Fixing directives for code snippets. Shifting to reST.

DOCS shift to rst - OpenVINO™ integration with TensorFlow

---

docs/install_guides/configurations-for-intel-gna.md

Adding command for installation of prerequisites on Linux.
This addresses the https://github.com/openvinotoolkit/openvino/issues/15090

[DOCS] Updating 'Prerequisites' section in 'Configurations for GNA' article

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/count_nonzero_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/non_zero/count_nonzero_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/non_zero/count_nonzero_kernel_ref.h
src/plugins/intel_gpu/tests/test_cases/non_zero_gpu_test.cpp
src/plugins/intel_gpu/tests/test_utils/test_utils.h

- *Set 1 work group to avoid synchronization issue for summation of nonzero count*
- *...*
- *102467*

[GPU] Change lws to avoid synchronization issue in nonzero_count

---

src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp

- *item1*
- *...*
- *ticket-id*

Fixed typo in core tests

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

[CONFOMANCE] Add handling crashes

---

docs/OV_Runtime_UG/layout_overview.md

Fixing directives for code snippets. Switching to reST.

DOCS shift to rst - `Layout API Overview` article

---

src/inference/dev_api/exec_graph_info.hpp
src/inference/dev_api/openvino/runtime/exec_model_info.hpp
src/inference/dev_api/openvino/runtime/iasync_infer_request.hpp
src/inference/dev_api/openvino/runtime/iplugin.hpp
src/inference/src/dev/exec_model_info.cpp

- *item1*
- *...*
- *ticket-id*

Introduce openvino ExecutionNode to new developer API

---

tests/layer_tests/tensorflow_tests/test_tf_While.py

**Details:** Test low-level While support by TF FE
**Tickets:** 92769, 92798, 92836, 92837

[TF FE] Test low-level While support by TF FE

---

tests/layer_tests/tensorflow_tests/test_tf_If.py

**Details:** Test Switch and Merge support by TF FE.
**Tickets:** 92835, 92804

[TF FE] Test Switch and Merge support by TF FE

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/test_cases/gemm_gpu_test.cpp
src/plugins/intel_gpu/tests/test_utils/test_utils.h

gemm/FC select_preferred_format select simple format depends on out rank size.
And customized_resnet50_fp16 ACC issue is also solved with this PR.
- *105400*

[GPU] Fix twin tranformer functional regression.

---

docs/OV_Runtime_UG/migration_ov_2_0/graph_construction.md

Fixing directives for code snippets. Switching to reST.

DOCS shift to rst - `Model Creation in OpenVINO RUNTIME` article

---

.ci/azure/linux.yml
.ci/azure/windows.yml
src/bindings/c/tests/CMakeLists.txt
src/bindings/c/tests/ie_c_api_test.cpp
src/bindings/c/tests/ov_compiled_model_test.cpp
src/bindings/c/tests/ov_core_test.cpp
src/bindings/c/tests/ov_infer_request_test.cpp
src/bindings/c/tests/ov_model_test.cpp
src/bindings/c/tests/ov_preprocess_test.cpp
src/bindings/c/tests/ov_remote_context_test.cpp
src/bindings/c/tests/ov_test.cpp
src/bindings/c/tests/ov_test.hpp
src/bindings/c/tests/test_model_repo.hpp

- remove testdata repository dependency
- 86537

[CAPI][TEST] remove testdata repository dependency

---

src/common/transformations/include/transformations/common_optimizations/transpose_sinking_binary.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_concat.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_data_movement.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_general.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_interpolate.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_reduction.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_split.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_unary.hpp
src/common/transformations/include/transformations/common_optimizations/transpose_sinking_utils.hpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_concat.cpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_fuse.cpp
src/common/transformations/src/transformations/common_optimizations/transpose_sinking_interpolate.cpp

Added descriptions to the transformations.
Added additional checks.
Resolved comments from https://github.com/openvinotoolkit/openvino/pull/15660

Transpose Sinking: refactoring

---

src/core/src/runtime/itensor.cpp
src/inference/src/dev/iremote_tensor.cpp

- *item1*
- *...*
- *ticket-id*

Fixed some ITensor leftovers

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/utils/stat_update_utils.py

- *item1*
- *...*
- *106017*
- *104978*

Fix win run

---

docs/install_guides/configurations-for-intel-gna.md

Adding command for installation of prerequisites on Linux.
This addresses the https://github.com/openvinotoolkit/openvino/issues/15090
Porting: https://github.com/openvinotoolkit/openvino/pull/16207

[DOCS] Updating 'Prerequisites' section in `Configurations for GNA` article - for 22.3

---

docs/IE_PLUGIN_DG/Building.md
docs/IE_PLUGIN_DG/PluginTesting.md
docs/IE_PLUGIN_DG/layout.xml

- Update more plugin developer guide documentation
- *ticket-id*

Update building and plugin testing docs

---

src/plugins/intel_cpu/src/nodes/strided_slice.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/strided_slice.cpp

- *optimize the shape infer of stridedslice*
- *not include ellipsis_axis for now*
- *100507*

optimize shape infer of stridedslice

---

src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_nd_update_kernel_ref.cpp
src/plugins/intel_gpu/tests/test_cases/scatter_nd_update_gpu_test.cpp

- In case of 5d indices tensor with all dynamic dimensions current logic generates wrong offsets in shape_info tensor.

[GPU] Fixed shape agnostic scatter nd update kernel

---

src/core/tests/visitors/op/interpolate.cpp

- Fixes the out-of-bounds access to the axes/scales vector
- 106294

Interpolate op bugfix

---

src/plugins/intel_gpu/src/graph/program.cpp

[GPU] enable dump-graph in unit-test

---

src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/runtime/layout.cpp
src/plugins/intel_gpu/tests/test_cases/reorder_gpu_test.cpp

+ Reorder 1d data
+ Reorder which only changes format
- Update general function 'are_layouts_identical'
- 82743

Remove redundant reorder

---

src/plugins/intel_cpu/src/nodes/gather.cpp
src/plugins/intel_cpu/src/nodes/matmul.cpp
src/plugins/intel_cpu/src/nodes/subgraph.cpp
src/plugins/intel_cpu/src/nodes/transpose.cpp

- *CPU plugin specific shape infer for Gather node.*
- *100511*

[CPU] Gather node shape infer

---

src/frontends/tensorflow_common/src/op/matrix_diag.cpp
tests/layer_tests/tensorflow_tests/test_tf_MatrixDiag.py

**Details:** Test MatrixDiag translator in the pre-commit
**Ticket:** 92799

[TF FE] Test MatrixDiag translator in the pre-commit

---

src/plugins/intel_gpu/src/graph/tile.cpp
src/plugins/intel_gpu/src/plugin/ops/tile.cpp
src/plugins/intel_gpu/tests/shape_infer/tile_si_test.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/tile.cpp

- Fixes one of the [notebooks](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/233-blip-visual-language-processing/233-blip-visual-language-processing.ipynb)
- *98549*
- *106287*
- *101328*
- *105899*

[GPU] Enable tile with non-constant repeats

---

src/frontends/paddle/tests/CMakeLists.txt
src/frontends/paddle/tests/paddle_pip_check.py

- *WA to resolve conflict between paddlepaddle and protobuf 3.20.3*
- *CVS-104788*

WA to resolve conflict between paddlepaddle and protobuf 3.20.3

---

src/frontends/pytorch/src/op/full.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_empty.py

- *Add aten::new_empty based on draft from https://github.com/openvinotoolkit/openvino/pull/16011*
- *Add test cases for aten::new_empty*
- *Fix sporadic issues with existing tests for aten::empty*
- *Fix issues with aten::full_like, aten::ones_like and aten::zeros_like where specified dtype is none and it should default to dtype of input.*
- *101109*

[PT FE] Add aten::new_empty

---

tools/mo/openvino/tools/mo/convert_impl.py
tools/mo/openvino/tools/mo/main.py
tools/mo/unit_tests/moc_tf_fe/check_info_messages.py
tools/mo/unit_tests/moc_tf_fe/test_models/model_switch_merge.pbtxt
tools/mo/unit_tests/moc_tf_fe/test_models/model_switch_merge.py

**Details:** Do not print TF FE message in case of fallback

[MO][TF FE] Do not print TF FE message in case of fallback

---

src/plugins/intel_gpu/README.md
src/plugins/intel_gpu/docs/gpu_plugin_driver_troubleshooting.md
src/plugins/intel_gpu/docs/source_code_structure.md

- Update of GPU plugin documentation
- *...*
- 96623

GPU documentation update

---

src/frontends/tensorflow/tests/convert_unsupported.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_dynamic_type_model.py
src/frontends/tensorflow_common/include/utils.hpp
src/frontends/tensorflow_common/src/op/broadcast_args.cpp
src/frontends/tensorflow_common/src/op/ctc_greedy_decoder.cpp
src/frontends/tensorflow_common/src/op/ctc_loss.cpp
src/frontends/tensorflow_common/src/op/dynamic_partition.cpp
src/frontends/tensorflow_common/src/op/fake_quant_min_max_vars.cpp
src/frontends/tensorflow_common/src/op/fused_batch_norm.cpp
src/frontends/tensorflow_common/src/op/l2_loss.cpp
src/frontends/tensorflow_common/src/op/linspace.cpp
src/frontends/tensorflow_common/src/op/log1p.cpp
src/frontends/tensorflow_common/src/op/non_max_suppression.cpp
src/frontends/tensorflow_common/src/op/pad.cpp
src/frontends/tensorflow_common/src/op/parallel_dynamic_stitch.cpp
src/frontends/tensorflow_common/src/op/random_uniform.cpp
src/frontends/tensorflow_common/src/op/range.cpp
src/frontends/tensorflow_common/src/op/reciprocal.cpp
src/frontends/tensorflow_common/src/op/rsqrt.cpp
src/frontends/tensorflow_common/src/op/scatter_nd.cpp
src/frontends/tensorflow_common/src/op/segment_sum.cpp
src/frontends/tensorflow_common/src/op/slice.cpp
src/frontends/tensorflow_common/src/op/space_to_batch_nd.cpp
src/frontends/tensorflow_common/src/op/sparse_to_dense.cpp
src/frontends/tensorflow_common/src/op/sqrt.cpp
src/frontends/tensorflow_common/src/op/tensor_list_operations.cpp
src/frontends/tensorflow_common/src/op/xdivy.cpp
src/frontends/tensorflow_common/src/op/zeros_like.cpp

**Details:** Support dynamic type for all operation translators.

[TF FE] Support dynamic type for all operation translators

---

src/bindings/python/tests/test_runtime/test_infer_request.py

Skip `test_mixed_dynamic_infer` on ARM devices

---

src/core/src/pass/pass.cpp

Remove RunLocker class

---

docs/IE_PLUGIN_DG/CompiledModel.md
docs/IE_PLUGIN_DG/Intro.md
docs/IE_PLUGIN_DG/RemoteContext.md
docs/IE_PLUGIN_DG/RemoteTensor.md
docs/IE_PLUGIN_DG/layout.xml
src/plugins/template/include/template/remote_tensor.hpp
src/plugins/template/src/remote_context.cpp
src/plugins/template/src/remote_context.hpp

- *item1*
- *...*
- *ticket-id*

Added documentation for RemoteTensor and RemoteContext

---

src/core/tests/visitors/op/interpolate.cpp

- Follow up of the fix from this PR https://github.com/openvinotoolkit/openvino/pull/16365
- 106294

Interpolate op bugfix follow-up

---

src/plugins/intel_gpu/include/intel_gpu/plugin/plugin.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/runtime/engine.cpp

- Removed `update_memory_statistics` method and query stats on demand for specific device only.

[GPU] Update memory_statistics property impl

---

src/frontends/tensorflow_common/src/op/strided_slice.cpp
tests/layer_tests/tensorflow_tests/test_tf_StridedSlice.py

**Details:** Refactor StridedSlice translator and add layer test to precommit. Now the translator will set shorter masks by removing extra zeros from the end.
**Ticket:** 92834

[TF FE] Refactor StridedSlice translator and add layer test to precommit

---

src/core/src/pass/serialize.cpp
src/core/tests/pass/serialization/deterministicity.cpp

- Port #16357 to 2022/3 branch
- CVS-104357

Fix ir10 inputs outputs serialization order (#16357)

---

src/inference/dev_api/ie_icore.hpp
src/inference/dev_api/openvino/runtime/device_id_parser.hpp
src/inference/dev_api/openvino/runtime/iplugin.hpp
src/inference/src/core.cpp
src/inference/src/dev/core_impl.cpp
src/inference/src/dev/core_impl_ie.cpp
src/inference/src/dev/device_id_parser.cpp
src/inference/src/ie_core.cpp
src/plugins/auto/plugin.cpp
src/plugins/auto/utils/plugin_config.hpp
src/plugins/auto_batch/src/auto_batch.cpp
src/plugins/hetero/plugin.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/tests/functional/shared_test_classes/src/base/layer_test_utils.cpp

- *item1*
- *...*
- *ticket-id*

Fixed some leftovers for 2.0 dev api

---

src/plugins/intel_gpu/thirdparty/CMakeLists.txt

- Fix group conv perf regression issue in oneDNN (OneDNN's ticket is 9508)
- *ticket-id*

[GPU] Update the latest oneDNN3.1

---

src/core/tests/any.cpp

- *item1*
- *...*
- CVS-106452

Fixed comparison of iterators

---

tools/pot/openvino/tools/pot/algorithms/quantization/fake_quantize.py
tools/pot/openvino/tools/pot/algorithms/quantization/utils.py

- *Add target device to `get_ignored_operations`*
- *...*
- *ticket-id*

[POT] Return Mul to ignored ops for transformers (except CPU_SPR)

---

src/plugins/auto/plugin.cpp

- Fixed conflict of PRs: #16421 and #16037
- *ticket-id*

Fixed build after conflict

---

docs/OV_Runtime_UG/supported_plugins/GPU_RemoteTensor_API.md
docs/snippets/gpu/context_sharing_va_c.cpp
docs/snippets/gpu/preprocessing_nv12_two_planes_c.cpp
docs/snippets/gpu/remote_objects_creation_c.cpp

- Document for remote tensor C API
- 95165

[DOC][CAPI] document for remote tensor

---

samples/c/hello_classification/main.c

- memleak in c sample
- 106250

[C Sample]fix mem leak

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_imad.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_imad.cpp
src/plugins/intel_gpu/tests/test_cases/fully_connected_gpu_test.cpp

- Shape agnostic optimized fully_connected_gpu_imad kernel implementation
- 104931

[GPU] Add shape agnostic optimized FullyConnectedIMAD kernel

---

docs/IE_PLUGIN_DG/Building.md
src/plugins/template/src/compiled_model.hpp

- *item1*
- *...*
- *ticket-id*

Small Plugin DG changes

---

src/bindings/c/include/openvino/c/ov_property.h
src/bindings/c/src/ov_property.cpp
src/bindings/c/tests/ov_core_test.cpp

- Add execution_mode to C-API
- 106427

[CAPI] Add ov::hint::execution_mode property

---

src/plugins/intel_cpu/src/nodes/reduce.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/reduce_ops.cpp

- *Fix issue in reducing HW with small channel size in npsc layout.*
- *106448*

Fix issue in reducing HW with small channel size in npsc layout

---

src/core/src/descriptor/tensor.cpp

Fixed CVS-93736

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/merge_xmls.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *item1*
- *...*
- *ticket-id*

[CONFORMANCE] Fix if impossible to remove log

---

cmake/developer_package/plugins/create_plugins_hpp.cmake
cmake/developer_package/plugins/plugins.cmake
cmake/developer_package/plugins/plugins.hpp.in
cmake/extra_modules.cmake
scripts/setupvars/setupvars.sh
src/common/util/CMakeLists.txt
src/common/util/src/file_util.cpp
src/inference/CMakeLists.txt
src/inference/src/core.cpp
src/inference/src/dev/core_impl.cpp
src/inference/src/dev/core_impl.hpp
src/inference/src/ie_core.cpp
src/inference/tests/unit/CMakeLists.txt

- *item1*
- *...*
- *ticket-id*

Fix leftovers after removing plugins.xml

---

src/plugins/template/backend/executable.hpp
src/plugins/template/backend/int_executable.cpp
src/plugins/template/backend/int_executable.hpp
src/plugins/template/src/sync_infer_request.cpp

- Evaluation context is needed to save variable states
- *ticket-id*

Use evaluation context for the inference

---

src/plugins/intel_gpu/tests/test_cases/multiple_streams_gpu_test.cpp

- *Fix the issue of gpu multi-stream test for dynamic model*
- *...*
- *106537*

[GPU] Fix gpu dynamic model  multistream test issue

---

src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp

- These changes improve performance of shape-agnostic FC kernel in dGPU
- 104973

[GPU] Update tuning params of shape agnostic version of fully_connected_bf_tiled kernel for dGPUs

---

docs/IE_PLUGIN_DG/InferRequest.md
docs/IE_PLUGIN_DG/Intro.md
src/plugins/template/src/sync_infer_request.cpp

- *item1*
- *...*
- *ticket-id*

Small fixes for template plugin developer documentation

---

src/plugins/intel_cpu/src/nodes/conv.cpp

- *enable brgconv512 when exists binary post ops. *
- *...*
- *105755*

[CPU] enable brgconv512 when exists binary post ops. 

---

src/plugins/auto/plugin.cpp
src/plugins/hetero/internal_properties.hpp
src/plugins/hetero/plugin.cpp
src/plugins/hetero/plugin.hpp

- *Support caching properties in HETERO plugin*
- *95239*

[HETERO]: support caching properties

---

src/plugins/intel_gpu/src/graph/broadcast.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/arg_max_min.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/network.cpp

- *fix warning in GPU plugin*
- *93716*

[GPU] Fix warnings

---

src/core/CMakeLists.txt
src/core/reference/include/ngraph/runtime/reference/gather.hpp
src/core/reference/include/ngraph/runtime/reference/grid_sample.hpp
src/core/shape_inference/include/space_to_batch_shape_inference.hpp
src/core/shape_inference/include/tile_shape_inference.hpp

- *item1*
- *...*
- *ticket-id*

Fixed Windows warnings for core

---

docs/nbdoc/consts.py
docs/tutorials.md

[DOCS] Update `Interactive Python Tutorials` article - for 22.3

---

docs/nbdoc/consts.py
docs/tutorials.md

[DOCS] Update `Interactive Python Tutorials` article

---

src/cmake/ie_parallel.cmake

- *item1*
- *...*
- *ticket-id*

More accurate hwloc finding in case of dynamic tbbbind

---

src/frontends/pytorch/src/op/norm.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_norm.py

- *support aten::linalg_vector_norm*
- *101061*

[PT FE]: support aten::linalng_vector_norm

---

src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/arg_max_min.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/arg_max_min_axis.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/arg_max_min_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/arg_max_min/arg_max_min_kernel_axis.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/arg_max_min/arg_max_min_kernel_axis.h
src/plugins/intel_gpu/src/kernel_selector/kernels/arg_max_min/arg_max_min_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/arg_max_min/arg_max_min_kernel_gpu_ref.cpp
src/plugins/intel_gpu/tests/test_cases/arg_max_gpu_test.cpp

- Shape agnostic TopK ref kernel implementation
- 95104

[GPU] Added shape agnostic TopK kernel

---

src/plugins/intel_cpu/src/cpu_memory.cpp

Fix accessing temporally memory descriptor object.

[CPU] Temporal object access fix

---

tests/layer_tests/common/layer_test_class.py
tests/layer_tests/common/utils/common_utils.py
tools/mo/openvino/tools/mo/analysis/tf_od_api.py
tools/mo/openvino/tools/mo/analysis/tf_retinanet.py
tools/mo/openvino/tools/mo/analysis/tf_yolo.py
tools/mo/openvino/tools/mo/back/offline_transformations.py
tools/mo/openvino/tools/mo/convert_impl.py
tools/mo/openvino/tools/mo/front/tf/ObjectDetectionAPI.py
tools/mo/openvino/tools/mo/load/tf/loader.py
tools/mo/openvino/tools/mo/main.py
tools/mo/openvino/tools/mo/moc_frontend/serialize.py
tools/mo/openvino/tools/mo/utils/cli_parser.py

Reverts openvinotoolkit/openvino#16394

Revert "[MO] remove deprecated: data_type, disable_nhwc_to_nchw, tensorflow_use_custom_operations_config"

---

src/plugins/intel_cpu/src/dnnl_extension_utils.cpp
src/plugins/intel_cpu/src/dnnl_extension_utils.h
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/nodes/concat.cpp
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/deconv.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/interaction.cpp
src/plugins/intel_cpu/src/nodes/lrn.cpp
src/plugins/intel_cpu/src/nodes/matmul.cpp
src/plugins/intel_cpu/src/nodes/pooling.cpp
src/plugins/intel_cpu/src/nodes/reorder.cpp
src/plugins/intel_cpu/src/nodes/softmax.cpp
src/plugins/intel_cpu/src/nodes/transpose.cpp
src/plugins/intel_cpu/src/utils/verbose.cpp

Fix broken `ENABLE_DEBUG_CAPS`  CPU plugin build.

[CPU] Debug Caps build fix

---

tests/layer_tests/tensorflow_tests/test_tf_Bucketize.py

**Details:** Add layer test for Bucketize
**Ticket:** 51023

[TF FE] Add layer test for Bucketize

---

src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/concat_reorder_inplace.cpp

- *Fix find base edge error in the specific subgraph described in CVS-104307*
- *CVS-104307*

Fix edge memory share issue

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp

- Enable oneDNN FC and eltwise fusion in fp16
- *101693*

[GPU] Support FC+eltwise fusion in fp16 for OneDNN

---

src/plugins/intel_gpu/CMakeLists.txt
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_nd_update_kernel_ref.cpp
src/plugins/intel_gpu/src/plugin/ops/gather.cpp
src/plugins/intel_gpu/tests/test_cases/scatter_nd_update_gpu_test.cpp

- Remove suppression of C4267 warnings
- Part of 93716

[GPU] Treat warnings C4267 as errors for Windows

---

src/plugins/intel_gpu/include/intel_gpu/runtime/internal_properties.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/crop.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp
src/plugins/intel_gpu/tests/test_cases/crop_gpu_test.cpp

- Static crop kernels are created with wrong params in async compilation in dynamic shape scenario
- This PR is needed to fix accuracy drop for dynamic shape

[GPU] Fix malfunction in crop static kernel in dynamic shape scenario

---

tools/mo/openvino/tools/mo/subprocess_main.py

**Details:** Remove Python version check to unblock users with old Python versions.

[MO] Remove Python version check

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/include/layout_optimizer.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/fusions/activation_fusion_test.cpp
src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp
src/plugins/intel_gpu/tests/fusions/lrn_fusion_test.cpp
src/plugins/intel_gpu/tests/test_cases/fully_connected_gpu_test.cpp

- Resolve failed unit-tests for fully-connected
- Disable failed cases
- 67491

Disable failed onednn tests

---

cmake/developer_package/compile_flags/os_flags.cmake
scripts/setupvars/setupvars.sh
src/bindings/python/src/compatibility/openvino/cmake/CythonConfig.cmake
src/bindings/python/src/compatibility/openvino/inference_engine/CMakeLists.txt
src/cmake/ie_parallel.cmake
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp

- https://github.com/openvinotoolkit/openvino/pull/16235
- https://github.com/openvinotoolkit/openvino/pull/16514
- https://github.com/openvinotoolkit/openvino/pull/16488

Port 2022 3

---

src/common/transformations/include/transformations/common_optimizations/prelu_fusion.hpp
src/common/transformations/src/transformations/common_optimizations/prelu_fusion.cpp
src/common/transformations/tests/prelu_fusion.cpp

- Adds PReLu fusion transformation for subgraph:
```
Op
/     \
Relu  Negative
|       |
|      Relu
|       |
|    Multiply
\     /
Add
```
- 106701

[Transformations] Add NegReluMulAdd PReLu fusion

---

src/common/transformations/include/transformations/common_optimizations/nonzero_fusion.hpp
src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/src/transformations/common_optimizations/nonzero_fusion.cpp
src/common/transformations/tests/common_optimizations/nonzero_fusion_test.cpp
src/core/include/openvino/pass/pattern/op/pattern.hpp
src/core/src/pattern/op/pattern.cpp
src/plugins/intel_gna/src/transformations/gather_sinking_unary.cpp

Horizontal fusion of equal NonZero layers with the same parent.
- *102297*
- *106820*

[Transforamtions] NonZero horizontal fusion

---

src/frontends/tensorflow/tests/compilation.cpp

TF FE NgramCompilation test fix

[TF FE] NgramCompilation test fix

---

docs/optimization_guide/nncf/ptq/basic_quantization_flow.md
docs/optimization_guide/nncf/ptq/ptq_introduction.md
docs/optimization_guide/nncf/ptq/quantization_w_accuracy_control.md

DOCS shift to rst - `Post-training Quantization with NNCF` article

---

src/core/src/any.cpp

- Fixed use after move warning
- CVS-107181

Fixed coverity for ov::Any

---

CMakeLists.txt
cmake/developer_package/native_compile.cmake
src/plugins/intel_gpu/thirdparty/CMakeLists.txt

- Propagate new variables depending on their version

Fixed cmake dev warnings

---

src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow/src/translate_session.cpp
src/frontends/tensorflow_common/include/utils.hpp
src/frontends/tensorflow_common/src/op/fused_batch_norm.cpp
src/frontends/tensorflow_common/src/utils.cpp
src/frontends/tensorflow_lite/src/op/op_translation_utils.hpp
src/frontends/tensorflow_lite/src/op_table.cpp

**Details:** Align opset usage in utils. Fixed leftovers from https://github.com/openvinotoolkit/openvino/pull/16554

[TF FE] Align opset usage in utils

---

src/bindings/python/src/openvino/runtime/ie_api.py

[PyOV] Fix Python linter

---

src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/eltwise.h
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/eltwise_caching.cpp

TODO: leave a more detailed comment
Current limitations: dynamic node, without fused FQ

[CPU] Introduced shape agnostic eltwise

---

cmake/developer_package/features.cmake
src/frontends/paddle/CMakeLists.txt
src/frontends/paddle/tests/op_fuzzy.cpp
src/frontends/tests/CMakeLists.txt
src/frontends/tests/frontend/shared/src/op_fuzzy.cpp
src/plugins/intel_cpu/tests/unit/CMakeLists.txt
src/plugins/intel_gpu/tests/test_cases/lstm_gpu_test.cpp
thirdparty/cnpy/cnpy.cpp

- Connected PR https://github.com/openvinotoolkit/oneDNN/pull/182
- CVS-101471

Fixed LTO build

---

src/common/transformations/src/transformations/convert_precision.cpp
src/plugins/intel_cpu/src/nodes/topk.cpp
src/plugins/intel_cpu/src/nodes/topk.h
src/plugins/intel_cpu/src/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/topk.cpp
src/tests/functional/shared_test_classes/src/base/utils/compare_results.cpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
src/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/builders.hpp

- *Implement TopK-11 to CPU plugin*
- *101503*

[CPU] Implement TopK-11 to CPU plugin

---

src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp
src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/lru_cache.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
src/plugins/intel_gpu/src/graph/include/convolution_inst.h
src/plugins/intel_gpu/src/graph/include/deconvolution_inst.h
src/plugins/intel_gpu/src/graph/include/fully_connected_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_weights.cl
src/plugins/intel_gpu/tests/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/test_cases/gemm_gpu_test.cpp

- Use clDNN's shape agnostic kernels for dGPU as default dynamic impls
- Add LRU weights caching
- 104960, 105028

[GPU] Add clDNN shape agnostic kernels usage as an initial impls for dGPU

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/exec_network.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/plugin.h
src/plugins/intel_cpu/src/transformation_pipeline.h
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_executable_network/get_metric.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp

- Default value is PERFORMANCE
- 99759

[CPU] Enable execution_mode API property

---

src/common/transformations/src/transformations/common_optimizations/push_constant_to_subgraph.cpp
src/core/dev_api/validation_util.hpp
src/core/include/openvino/core/validation_util.hpp
src/core/shape_inference/include/slice_shape_inference_utils.hpp
src/core/src/op/concat.cpp
src/core/src/validation_util.cpp
src/core/tests/validation_utils.cpp

- Hide utils  functions from public api and move them to dev api
- CVS-101941

Move new util functions from public api to dev api

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/softmax_gpu_bf.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_base.h
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/softmax.cpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp

- *Added single layer test which covers Softmax in stable diffusion case*
- *Improved inputs generation and absolute error threshold*
- *Scalar intel_sub_group_read/intel_sub_group_read are incorporated*
- *CVS-91171*

[GPU] Softmax for stable diffusion

---

tools/pot/openvino/tools/pot/algorithms/quantization/accuracy_aware/README.md

DOCS shift to rst - `AccuracyAwareQuantization Parameters` article

---

docs/optimization_guide/dldt_deployment_optimization_latency.md

Add `mmap` notes in dldt_depl_optimization_latency.md

---

docs/MO_DG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
docs/MO_DG/prepare_model/convert_model/kaldi_specific/Aspire_Tdnn_Model.md
docs/MO_DG/prepare_model/convert_model/mxnet_specific/Convert_GluonCV_Models.md
docs/MO_DG/prepare_model/convert_model/mxnet_specific/Convert_Style_Transfer_From_MXNet.md
docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Cascade_RCNN_res101.md
docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_F3Net.md
docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_QuartzNet.md
docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RCAN.md
docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md
docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_YOLACT.md

DOCS shift to rst - `Converting Pytorch Models` articles

---

src/common/transformations/include/transformations/common_optimizations/convolution_to_group_convolution_fusion.hpp
src/common/transformations/src/transformations/common_optimizations/convolution_to_group_convolution.cpp
src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/tests/common_optimizations/convolution_to_group_convolution_fusion.cpp

Fuses Split->series of Conv->Concat to GroupConvolution op.
Ticket: 105170

Add ConvolutionToGroupConvolutionFusion

---

src/bindings/c/include/openvino/c/ov_property.h

- remove UNDEFINED property value
- 107560

[C API] remove UNDEFINED property value

---

src/plugins/intel_gna/src/frontend/model_quantizer.hpp

- added extra checks for condition fixing infinity loop
- 104500

[GNA] Fix crash in GNA plugin when using POT

---

src/plugins/intel_gna/src/frontend/model_quantizer.hpp

Reverts openvinotoolkit/openvino#16003

Revert "[GNA] Fix crash in GNA plugin when using POT"

---

.github/workflows/build_doc.yml

To avoid failed status for push commits
- CVS-104864

[CVS-104864] Action: Renamed group for concurrency

---

src/plugins/intel_gpu/include/intel_gpu/graph/fused_primitive_desc.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/kernel_impl_params.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp
src/plugins/intel_gpu/tests/fusions/gemm_fusion_test.cpp

- This PR fixes a bug in OneDNN primitive attr serialization logic.
- In some cases, memory format tags are missed to be stored.
- 107099

[GPU] Fix OneDNN primitive attr serialization logic

---

tests/layer_tests/tensorflow_tests/test_tf_BatchToSpace.py

**Details:** Fix layer tests for BatchToSpace and add to the pre-commit
**Ticket:** 51022

[TF FE] Fix layer tests for BatchToSpace and add to the pre-commit

---

docs/dev/installing.md

https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/build_samples.sh#L18
- 102001

 DOCS Change sample path 

---

src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp
src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/src/graph/arg_max_min.cpp
src/plugins/intel_gpu/src/graph/border.cpp
src/plugins/intel_gpu/src/graph/broadcast.cpp
src/plugins/intel_gpu/src/graph/crop.cpp
src/plugins/intel_gpu/src/graph/deconvolution.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/resample.cpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/non_max_suppression.cpp
src/plugins/intel_gpu/src/graph/non_zero.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/range.cpp
src/plugins/intel_gpu/src/graph/resample.cpp
src/plugins/intel_gpu/src/graph/reshape.cpp
src/plugins/intel_gpu/src/graph/strided_slice.cpp
src/plugins/intel_gpu/src/graph/tile.cpp
src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp
src/plugins/intel_gpu/tests/test_cases/multiple_streams_gpu_test.cpp

- Update to store network pointer in `kernel_impl_params` and use mem_lock through stream from network at runtime for `calc_output_layouts`
- 105711

[GPU] Fix synchronization issue from wrong stream in multi-stream mode on dGPU

---

src/bindings/c/include/openvino/c/ov_property.h
src/bindings/c/src/ov_property.cpp
src/bindings/c/tests/ov_core_test.cpp
src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/bindings/python/tests/test_runtime/test_properties.py
src/frontends/ir/src/frontend.cpp
src/frontends/ir/tests/frontend_test_basic.cpp
src/inference/include/openvino/runtime/properties.hpp
src/inference/src/dev/core_impl.cpp
src/inference/src/dev/core_impl.hpp
src/inference/src/dev/core_impl_ie.cpp
src/inference/src/ie_network_reader.cpp
src/inference/src/ie_network_reader.hpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp

- Continuation of https://github.com/openvinotoolkit/openvino/pull/12673
- 68937

Add Core property to switch from `mmap` to `read` in IR Frontend

---

src/inference/src/streams_executor.hpp
src/inference/src/system_conf.cpp

- *fix cpu binding cannot follow numactl's control issue*
- *CVS-107653*

HOT FIX: CPU binding cannot follow numactl's control

---

src/bindings/python/src/pyopenvino/graph/util.cpp

- Fixed azure windows after #16716
- *ticket-id*

Fixed windows build after #16716

---

src/plugins/intel_gpu/src/plugin/ops/gather_elements.cpp
src/tests/functional/plugin/gpu/single_layer_tests/dynamic/gather_elements.cpp

- Updated GatherElements op factory to properly handle dynamic shapes case
- *107614*

[GPU] Enable dynamic shapes support for gather elements

---

tools/pot/openvino/tools/pot/graph/graph_utils.py

[POT] use serialize method

---

src/bindings/python/wheel/setup.py

- Regression after https://github.com/openvinotoolkit/openvino/pull/16548
- *ticket-id*

Extended a list of libraries to exclude from wheel package

---

src/bindings/python/wheel/setup.py

- Regression after https://github.com/openvinotoolkit/openvino/pull/16548

Added rpath for TBB libs to find hwloc

---

src/plugins/intel_gpu/include/intel_gpu/runtime/kernel.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_kernel.hpp
src/plugins/intel_gpu/tests/passes/kernels_cache_test.cpp

- *Fix sub kernel ordering code in build_batch in kernels_cache*
- *...*
- *107335*
- *107542*
- *107831*

[GPU] Fix sub kernel ordering issue in kernels_cache

---

src/plugins/intel_gpu/include/intel_gpu/primitives/lstm.hpp
src/plugins/intel_gpu/src/graph/data.cpp
src/plugins/intel_gpu/src/graph/detection_output.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp
src/plugins/intel_gpu/src/graph/mutable_data.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp

- This PR fixes uninitialized scalar variables.
- 104204

[GPU] Fixed uninitialized scalar variables

---

src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp

- This PR makes to store dims and data types of mem descs of OneDNN post ops.
- 107729

[GPU] Fixed onednn post ops serialization logic

---

src/plugins/intel_cpu/src/nodes/reshape.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/shape_ops.cpp

This reverts commit 75c62ea320418c302e0571ac6d8a9164994c299e.
- *will re-submit a PR for reshape after all issues in tickets are fixed*
- *107228*
- *100509*

Revert "[CPU] optimize shape infer of Reshape (#16537)"

---

src/bindings/python/wheel/setup.py

- *fix wheel_blacklist_extension for macos*

fix wheel_blacklist_extension for macos

---

src/plugins/auto/src/auto_executable_network.cpp
src/plugins/auto/src/auto_schedule.cpp
src/plugins/auto/src/auto_schedule.hpp
src/plugins/auto/src/common.hpp
src/plugins/auto/src/multi_executable_network.cpp
src/plugins/auto/src/plugin.cpp

- *Initialize variable*
- *Use reference to reduce variable copy*
- *CVS-107195*

[AUTO] Initialize variable / reduce variable copy

---

src/plugins/intel_cpu/src/emitters/jit_load_store_emitters.cpp
src/plugins/intel_cpu/src/emitters/jit_load_store_emitters.hpp

- *store emitter keep source vec values intact*
- onednn PR: https://github.com/openvinotoolkit/oneDNN/pull/180
- *105903*

store emitter keep source vec values intact

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/broadcast.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/eltwise.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_io_gemm.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_io_gemm.h
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_io_input_spatial.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_io_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_io_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bs_f_bsv16_af8.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bs_f_bsv16_b1.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bs_f_bsv16_b1.h
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bs_f_bsv8_af8.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_fb_io_b8_f8.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_fb_io_block.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_fb_io_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_fb_io_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_fb_oi_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_fb_oi_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_fs_byx_fsv32.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_fs_byx_fsv32.h
src/plugins/intel_gpu/src/runtime/format.cpp
src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp

Fix the accuracy issue in fp16/32 FC kernels with different data type between input and bias
- *107418*

[GPU] Add to check FC bias data-type logic in issued kernel selection.

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- *Fix possible resource leak reported from coverity*
- *107179*

[Coverity] Resource leak in primitive_inst.cpp

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *Re-run interapted tests added*
- *ticket-id*
###CI:
- *https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/customJobs/job/ie-tests-linux/7084/*

[CONFORMANCE] Add re-run of interapted tests to avoid not reported tests

---

tests/layer_tests/tensorflow_tests/test_tf_SpaceToBatch.py

**Details:** Correct SpaceToBatch layer test
**Ticket:** 51027

[TF FE] Correct SpaceToBatch layer test

---

src/bindings/python/wheel/CMakeLists.txt
tools/benchmark_tool/setup.py
tools/openvino_dev/CMakeLists.txt
tools/openvino_dev/setup.py

- Regression after https://github.com/openvinotoolkit/openvino/pull/15343
- CVS-107259

Return benchmark_tool to openvino-dev wheel

---

src/inference/CMakeLists.txt
src/inference/src/cnn_network_ngraph_impl.cpp
src/plugins/intel_gna/legacy/CMakeLists.txt

- Clean-up cmake files
- CVS-79544

Removed legacy src files from inference library

---

src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_resource_gather_model.py

**Details:** This PR fixes the debug or failures reporting capabilities. Namely, it fixes a case when model contains multiple nodes of the same type for which the existing translator failures. In this case, we should report only failure message but we must not report `No translator found`.
Also, in this PR we represent testing a model with `ResourceGather` operation.
**Tickets:** 92818, 89082

[TF FE] Test ResourceGather operation and fix debug caps

---

src/frontends/pytorch/src/op/gather.cpp
src/frontends/pytorch/src/op/sign.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_gather.py
tests/layer_tests/pytorch_tests/test_sign.py

- *support aten::gather op*
- *support aten::detach*
- *support aten::sign*
- *101101*
- *105961*

[PT FE]: aten::gather

---

src/common/transformations/src/transformations/smart_reshape/broadcast_const_range_replacement.cpp
src/common/transformations/tests/smart_reshape/broadcast_const_range_replacement.cpp

BroadcastConstRangeReplacement - skip unsqueeze if Broadcast input is 1D

---

src/plugins/intel_gpu/src/graph/impls/ocl/strided_slice.cpp
src/plugins/intel_gpu/tests/test_cases/strided_slice_gpu_test.cpp

- Fix edge case of strided slice for clamped negative(`-1`) begin with negative stride
- 65043

[GPU] Fix strided slice for clamped negative begin with negative stride

---

samples/cpp/benchmark_app/main.cpp
tools/benchmark_tool/openvino/tools/benchmark/main.py

- Retrieve the ov::num_streams through compiledModel rather than through plugin.
- 107975

[IE Sample] incorrect nstreams retrieved from plugin

---

src/bindings/python/src/compatibility/pyngraph/ops/util/regmodule_pyngraph_op_util.cpp
src/bindings/python/src/pyopenvino/graph/ops/util/regmodule_graph_op_util.cpp

- *item1*
- *...*
- *ticket-id*

[PyOv] remove commented functions without implementation

---

src/plugins/intel_gpu/tests/test_cases/lstm_gpu_test.cpp

[GPU] Skip failing lstm tests

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp
src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp

- *Compensation processing for asymmetric weights of non-data type generates error*
- *And skip asymmetric_weight compensation processing*
- *104165*

Skip asymmetric_weight compensation processing

---

src/plugins/intel_gpu/src/kernel_selector/kernels/non_zero/gather_nonzero_kernel_ref.cpp
src/plugins/intel_gpu/tests/test_cases/non_zero_gpu_test.cpp

- `MAX_LOCAL_MEM_SIZE` *is a mandatory constant for the kernel, but in some cases it is not declared*

[GPU] Small fix for gather_nonzero

---

src/frontends/paddle/tests/CMakeLists.txt
src/frontends/paddle/tests/paddle_pip_check.py

- *fix Paddle unit tests unexpected exceptions and seg fault issue because models failed to generate*
- *107226*

fix Paddle unit tests unexpected exceptions and seg fault issue

---

src/plugins/intel_gna/src/frontend/model_quantizer.hpp

- Fix plugin crash when infinite loop discovered.
- 104500

[GNA] Fix plugin crash when infinite loop discovered.

---

src/tests/functional/plugin/shared/include/base/ov_behavior_test_utils.hpp
src/tests/ie_test_utils/functional_test_utils/include/functional_test_utils/crash_handler.hpp
src/tests/ie_test_utils/functional_test_utils/src/crash_handler.cpp

- *item1*
- *...*
- *ticket-id*

[apiConformance] Stop work after crash and save report

---

licensing/runtime-third-party-programs.txt

Propagation of https://github.com/openvinotoolkit/openvino/pull/14659

Add ACL license

---

src/frontends/onnx/frontend/src/op/squeeze.cpp
src/frontends/onnx/tests/models/squeeze_empty_axes_attribute.prototxt
src/frontends/onnx/tests/onnx_import_reshape.in.cpp

Ticket: 105515
Port of https://github.com/openvinotoolkit/openvino/pull/16865

[port from master][ONNX FE] Fix Squeeze v1

---

src/plugins/intel_gpu/src/graph/gather_nd.cpp
src/plugins/intel_gpu/src/graph/pooling.cpp
src/plugins/intel_gpu/src/graph/select.cpp
src/tests/functional/plugin/shared/include/subgraph_tests/tensor_names.hpp

Fixed compilation with gcc-12

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- Resolve seg fault issue from unit-test 'reshape_gpu_f32.basic_dynamic_shape_to_static_optimized_out'
- 107829
- 107863

[GPU] fix unit-test seg fault error on dGPU

---

src/tests/functional/plugin/shared/include/low_precision_transformations/group_convolution_transformation.hpp
src/tests/functional/plugin/shared/src/low_precision_transformations/group_convolution_transformation.cpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/group_convolution_function.cpp

[LPT] GroupConvolution plugin tests: test class corrected to restore behavior in arm plugin instances

---

docs/OV_Runtime_UG/Model_caching_overview.md
docs/OV_Runtime_UG/supported_plugins/GPU.md

Update GPU.md
Update Model_caching_overview.md

[DOCS] model caching update to GPU

---

cmake/developer_package/plugins/plugins.cmake

- CPU cannot find because we try to find intel_cpu_plugin (we have another name for output file
- CVS-108295

Fixed ARM CPU tests. 

---

src/plugins/intel_gpu/tests/fusions/resample_fusion_test.cpp

[GPU] Disable oneDNN failed TCs on dGPU

---

docs/_static/js/custom.js

- update version switcher
- update language switcher

[docs] Update switchers 4

---

src/tests/functional/shared_test_classes/include/shared_test_classes/base/benchmark.hpp

Fix for ambiguous overloaded function call

---

src/frontends/pytorch/src/frontend.cpp
src/frontends/pytorch/src/transforms/dict_resolver.cpp
src/frontends/pytorch/src/transforms/dict_resolver.hpp
tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
tests/layer_tests/pytorch_tests/test_dict.py

- *Support `prim::DictConstruct` on the output*
- *TBD*

[PT FE] Support prim::DictConstruct on the output

---

src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/plugin/core_integration.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/plugin/hetero_synthetic.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/plugin/plugin_name.cpp

- *item1*
- *...*
- *ticket-id*

Fixed plugin name in tests for ARM CPU

---

src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/lstm_cell_basic.cpp

- Fixed smoke_LSTMCellBasicCommon for GNA 3.5
- 105916

[GNA] Fix smoke_LSTMCellBasicCommon for GNA 3.5

---

src/plugins/intel_gna/tests/unit/CMakeLists.txt
src/plugins/intel_gna/tests/unit/gna_extra_pwl_segments_tests.cpp

- Fix UT for adding extra segments to PWL after convolution
- 105916

[GNA] Fix issues with GNA 3.5 - Fix UT 

---

docs/ops/broadcast_rules.md
docs/snippets/ov_auto.py
docs/snippets/ov_preprocessing.py

Ported https://github.com/openvinotoolkit/openvino/pull/16945

[2022.3] Small docs fixes (#16945)

---

src/tests/ie_test_utils/functional_test_utils/include/functional_test_utils/summary/op_summary.hpp
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/merge_xmls.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/template/filters.js
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/template/report_template.html
src/tests/ie_test_utils/functional_test_utils/src/summary/op_summary.cpp

- *Using runtime info instead of op version comparation*
- *107208*

[CONFORMANCE] Fix Opset filters

---

docs/Extensibility_UG/frontend_extensions.md
docs/snippets/ov_extensions.py

- http://openvino-doc.iotg.sclab.intel.com/python-snippets/openvino_docs_Extensibility_UG_Frontend_Extensions.html
- 91071

DOCS Add Missing Python snippets to FE extensibility page

---

src/plugins/intel_cpu/src/plugin.cpp

- *fix omp threading is disable issue *
- *ticket-id*

Hot Fix: threading is disable with "threading=omp"

---

tools/pot/tests/utils/open_model_zoo.py

[POT] Fix POT CI

---

src/plugins/template/tests/functional/skip_tests_config.cpp

- *item1*
- *...*
- *ticket-id*

Skipped failed tests on Linux ARM64

---

src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/test_cases/non_zero_gpu_test.cpp

- Fix gather_nonzero not to be marked as constant.
- Even though count nonzero is to be turned into a constant, gather nonzero still cannot infer shape at the moment of propagate constant.
- 108008

[GPU] Fix nonzero issue in constant propagate

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp
src/plugins/intel_gpu/tests/passes/prepare_padding_test.cpp

- Weight layout was not properly handled in prepare_padding. Fixed it.
- 108469

[GPU]Fix prepare padding which was not handling group size properly

---

src/plugins/intel_cpu/tests/functional/subgraph_tests/src/input_noreorder_eltwise_bf16.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/subgraph_serialize.cpp
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.cpp
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.hpp

- Add possibility to provide multiple node types for checking the presence of the node types

[CPU] Add few tests to the smoke scope

---

src/plugins/intel_gpu/src/graph/non_max_suppression.cpp
src/plugins/intel_gpu/tests/shape_infer/non_max_suppression_si_test.cpp

- For static output tensor, checking dynamism of input tensor's dimensions is needed additionally
- 107654

[GPU] Fix incomplete condition for NMS shape inference

---

src/plugins/auto/src/executable_network.cpp
src/plugins/auto/src/executable_network.hpp
src/tests/functional/plugin/shared/src/behavior/executable_network/exec_graph_info.cpp

- *Add the implementation to GetExecGraphInfo API in AUTO plugin*
- *CVS-93769*

[AUTO] Add the implementation to GetExecGraphInfo API in AUTO plugin

---

src/bindings/c/docs/api_overview.md
src/bindings/c/include/c_api/ie_c_api.h
src/bindings/c/include/openvino/c/deprecated.h
src/bindings/python/src/compatibility/openvino/inference_engine/constants.pyx
src/common/preprocessing/src/ie_preprocess_gapi.cpp
src/inference/include/ie/gpu/gpu_context_api_dx.hpp
src/inference/include/ie/gpu/gpu_context_api_ocl.hpp
src/inference/include/ie/gpu/gpu_context_api_va.hpp
src/inference/include/ie/ie_compound_blob.h
src/inference/src/ie_compound_blob.cpp
src/inference/tests/unit/ie_compound_blob_test.cpp

- *item1*
- *...*
- *ticket-id*

Added deprecation of nv12 legacy API

---

docs/Extensibility_UG/VPU_Extensibility.md
docs/OV_Runtime_UG/deployment/deployment-manager-tool.md
docs/OV_Runtime_UG/supported_plugins/MYRIAD.md
docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
docs/OV_Runtime_UG/supported_plugins/VPU.md
docs/get_started/get_started_demos.md
docs/install_guides/configurations-for-iei-card.md
docs/install_guides/configurations-for-ivad-vpu.md
docs/install_guides/configurations-for-ncs2.md
docs/install_guides/installing-openvino-overview.md
docs/install_guides/installing-openvino-yocto.md
docs/install_guides/troubleshooting-issues.md

quick fix for a nonfunctioning markdown directive

[DOCS] quick vpu fix

---

src/core/reference/include/ngraph/runtime/reference/fake_quantize.hpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

Fix broadcasting issue in FQ ref implementation

---

src/common/itt/include/openvino/itt.hpp
src/common/preprocessing/src/ie_preprocess_gapi_kernels.hpp
src/common/util/include/openvino/util/file_util.hpp
src/core/include/openvino/core/partial_shape.hpp
src/core/src/partial_shape.cpp
src/plugins/intel_cpu/CMakeLists.txt
src/plugins/intel_cpu/src/memory_desc/dnnl_memory_desc.cpp
src/plugins/intel_cpu/src/utils/shape_inference/static_shape.cpp
src/plugins/intel_cpu/src/utils/shape_inference/static_shape.hpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_mat_mul.cpp
src/plugins/intel_cpu/thirdparty/CMakeLists.txt
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_mat_mul.hpp
src/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/common/fake_quantize_on_data.hpp
src/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/common/fake_quantize_on_weights.hpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/common/fake_quantize_on_data.cpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/common/fake_quantize_on_weights.cpp

- Extracted from https://github.com/openvinotoolkit/openvino/pull/16900

Generic ARM32 fixes

---

tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_conv_lstm_2d.py

**Details:** Correct layer test for ConvLSTM2D and add to the pre-commit
**Ticket:** 50141

[TF FE] Correct layer test for ConvLSTM2D and add to the pre-commit

---

cmake/test_model_zoo.cmake

- https://dev.azure.com/openvinoci/dldt/_build/results?buildId=543029&view=logs&jobId=b5f22b75-a995-5545-eb44-87d86e78d173&j=b5f22b75-a995-5545-eb44-87d86e78d173&t=d8150bbb-90e5-5a93-fe9d-9aeee1771aec

Fixed multi-config generators

---

src/common/low_precision_transformations/src/pull_reshape_through_dequantization.cpp
src/common/low_precision_transformations/tests/pull_reshape_through_dequantization_transformation.cpp

[LPT] PullReshapeThroughDequantization transformation fix

---

tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_conv_lstm_2d.py

**Details:** Mark one Keras ConvLSTM2D test with xfail

[TF FE] Skip one Keras ConvLSTM2D test

---

src/core/reference/include/ngraph/runtime/reference/fake_quantize.hpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/template/tests/functional/op_reference/fake_quantize.cpp

- Master PRs: https://github.com/openvinotoolkit/openvino/pull/16812, https://github.com/openvinotoolkit/openvino/pull/17009
- 107400, 104402

Fix FQ ref impl broadcasting

---

src/plugins/intel_cpu/src/graph.cpp

Parallel execution of the updateShapes and updateDynParams stages was revised. Now each task is pinned to a particular slot inside the task area. It helps to mitigate overheads on threads switching. Also OMP version the parallel tasks run was introduced.
- 99129

[CPU] Optimize TBB usage in the parallel dynamic shapes processing

---

src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/convolution.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/single_layer_tests/lstm_cell_basic.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/convolution_relu_sequence.cpp
src/plugins/intel_gna/tests/unit/gna_extra_pwl_segments_tests.cpp

- fix for review comment for previous PR-s with fixes for 3_5
- 105916

[GNA] Fix for GNA 3_5 fixing tests after review

---

src/docs/architecture.md

- Add dependencies graph on the arch diagram
- NA

Added components relationships on architecture page

---

src/plugins/intel_cpu/src/nodes/executors/acl/acl_interpolate.cpp
src/plugins/intel_cpu/src/nodes/executors/interpolate.hpp
src/plugins/intel_cpu/src/nodes/interpolate.cpp
src/plugins/intel_cpu/src/nodes/interpolate.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/interpolate.cpp
src/tests/ngraph_helpers/ngraph_functions/src/utils/ngraph_helpers.cpp

- *interpolate-11 support in CPU plugin, with new modes "bilinear_pillow" and "bicubic_pillow"*
- *JIT optimization for nspc layout*
- *104328*

[CPU]interpolate-11 support

---

src/plugins/intel_gna/src/frontend/quantization.cpp

- fix channel multiplier calculation/passing for int8 weights quantization
- 108530

[GNA] Fix channel multiplier calculation

---

src/common/offline_transformations/src/pruning/propagate_masks.cpp
src/common/transformations/src/transformations/smart_reshape/broadcast_const_range_replacement.cpp

Fix transformations tests on 32 bit build

---

src/frontends/tensorflow_lite/src/graph_iterator_flatbuffer.cpp
src/frontends/tensorflow_lite/src/graph_iterator_flatbuffer.hpp

- *Read model to the vector<uint8>*
- *There is no need to delete tflite::Model as it is just a reinterpretation of original buffer*
- *102308*

Read tflite model to vector

---

src/bindings/c/include/c_api/ie_c_api.h
src/bindings/python/src/compatibility/openvino/inference_engine/ie_api.pyx
src/inference/dev_api/cpp_interfaces/impl/ie_infer_async_request_thread_safe_default.hpp
src/inference/dev_api/cpp_interfaces/interface/ie_iinfer_request_internal.hpp
src/inference/include/ie/cpp/ie_infer_request.hpp
src/inference/include/ie/ie_iinfer_request.hpp
src/inference/include/ie/ie_plugin_config.hpp
src/inference/tests/functional/async_infer_request_test.cpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_gpu/src/plugin/legacy_api_helper.cpp

- *item1*
- *...*
- *ticket-id*

Deprecate set batch method

---

src/core/tests/pass/serialization/deterministicity.cpp
src/core/tests/pass/serialization/serialize.cpp

- The tests now pass so they can be enabled again
- 99981

ONNX Serialization test re-enabled

---

tests/layer_tests/mo_python_api_tests/test_mo_convert_pytorch.py
tools/mo/openvino/tools/mo/back/preprocessing.py

Removed naming of inputs in MO Python API PyTorch tests.
-

Removed naming of inputs in MO Python API PyTorch tests.

---

src/plugins/intel_cpu/src/nodes/reshape.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/shape_ops.cpp

- *optimize the shape infer of Reshape, squeeze, unsqueeze*
- *fix the issue when reshape connect with nonzero op*
- *100509*

[cpu] resubmit pr for optimize shape infer of Reshape

---

src/common/low_precision_transformations/include/low_precision/network_helper.hpp

[LPT] Revert changes in fold_reshape

---

src/plugins/intel_cpu/src/config.cpp

- *update default affinity for macOS*
- *108572*

HOT FIX: update default affinity for macOS

---

src/bindings/python/tests_compatibility/test_inference_engine/test_IECore.py

[PyOV] Check for glibc version in python test

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *enable test smoke_SetConfigAffinity agin for ARM*
- *...*
- *ticket-id*

enable smoke_SetConfigAffinity for ARM

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/test_cases/reorder_gpu_test.cpp

- Issue fixing from code refactoring PR-16827

[GPU] Choose onednn impl for reorder

---

src/plugins/intel_cpu/tools/commit_slider/utils/common_mode.py
src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py

[CPU] Safe file opening in commit slider

---

src/plugins/intel_cpu/src/plugin.cpp

- *fix number of streams is not correct with latency mode on core machine*
- *ticket-id*

[HOT FIX] fix streams is not correct with latency mode based on PR16692

---

src/plugins/intel_cpu/src/nodes/executors/acl/acl_eltwise.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *item1*
- *...*
- CVS-108787

[ARM CPU] Fix smoke_if tests

---

src/plugins/auto/src/auto_executable_network.cpp
src/plugins/auto/src/auto_schedule.cpp
src/plugins/auto/src/auto_schedule.hpp
src/plugins/auto/src/common.hpp
src/plugins/auto/src/multi_executable_network.cpp
src/plugins/auto/src/multi_executable_network.hpp
src/plugins/auto/src/multi_schedule.cpp
src/plugins/auto/src/multi_schedule.hpp
src/plugins/auto/src/plugin.cpp
src/plugins/auto/src/plugin_config.cpp
src/plugins/auto/src/plugin_config.hpp

This reverts commit 359b444558cb1e356de561d08a55d61bbf75e421.
- 109040
- *ticket-id*

Revert "Clean up unused code (#17006)"

---

src/bindings/c/tests/CMakeLists.txt
src/bindings/c/tests/ie_c_api_test.cpp
src/bindings/c/tests/ov_core_test.cpp
src/bindings/c/tests/test_model_repo.hpp

- *item1*
- *...*
- CVS-102839

Enabled C-API tests on ARM platform

---

thirdparty/ocv/opencv_hal_neon.hpp

- *item1*
- *...*
- *ticket-id*

Fixed compilation errors on Linux arm64

---

src/common/transformations/src/transformations/common_optimizations/gelu_fusion.cpp
src/common/transformations/tests/common_optimizations/gelu_fusion.cpp

- Add threshold for M_SQRT2 const comparison to enable gelu fusion for fp16 IRs
- *108607*

[Transformations] Enable GELU fusion for fp16 models

---

src/common/low_precision_transformations/src/eliminate_fake_quantize.cpp
src/common/low_precision_transformations/tests/eliminate_fake_quantize_transformation.cpp

- *Extending EliminateFakeQuantize transformation*
- *extending 98890 & workaround 107875*

[LPT] Extending EliminateFakeQuantize transformation (two interval boundaries)

---

src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/rnn.cpp
src/plugins/intel_cpu/src/nodes/rnn.h
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/rnn_sequence.cpp

Add RNN weights repacking in the case when their layout depends on the input shape.
Also withing this PR we adjust relative thresholds in some SL tests in accordance with the precision. 
- 95915
- 107085

[CPU] Rnn weights repacking

---

src/plugins/auto/docs/architecture.md

- *Update auto architect document in GitHub for 2023.0 release*
- *...*
- *100527*

update auto architecture document in GitHub for 2023.0 release

---

src/plugins/intel_gna/legacy/include/legacy/ie_reader.hpp

- *item1*
- *...*
- *ticket-id*

Fixed compilation with clang sanitizer

---

src/plugins/intel_cpu/src/nodes/common/tile_broadcast_utils.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/broadcast_eltwise.cpp

Main PR: #16861 
- CVS-107667
- CVS-109204

[Transformations] BroadcastTransition transformation leftovers

---

src/plugins/intel_gpu/src/kernel_selector/kernels/detection_output/detection_output_kernel_ref.cpp

+ Check local memory size used in the kernel and choose proper kernel.
+ 	Select DO_STAGE_0_CAFFE instead of DO_STAGE_0_CAFFE_OPT
- *108265*

[GPU] Fix detection output kernel build error on dGPU

---

src/plugins/auto_batch/src/auto_batch.cpp

- *Fixed Coverity hits in auto_batch.cpp*
- *108963*

Coverity fixes

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp
src/plugins/intel_gpu/tests/test_cases/convolution_gpu_test.cpp
src/plugins/intel_gpu/tests/test_utils/test_utils.h

- This PR fixes the compensation data generation logic to support `grouped_weights_shape`.
- 106255

[GPU] Fixed the prepare_quantization pass to support grouped_weights_shape

---

src/plugins/intel_cpu/src/nodes/eltwise.cpp

- Removed unused lambda capture to make it simpler and avoid reporting compilation error `-Wunused-lambda-capture`
- N/A

[CPU] Remove unused lambda capture from eltwise node

---

src/plugins/intel_gpu/include/intel_gpu/plugin/program.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/activation.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/pooling.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/quantize.cpp
src/plugins/intel_gpu/src/graph/include/implementation_map.hpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/activation_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/quantize_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/quantize_gpu_scale_shift_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/activation/activation_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/activation/activation_kernel_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/quantize/quantize_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/quantize/quantize_kernel_scale_shift_opt.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/plugin/program.cpp
src/plugins/intel_gpu/tests/fusions/activation_fusion_test.cpp
src/plugins/intel_gpu/tests/fusions/eltwise_fusion_test.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/activation.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/fake_quantize.cpp

- up to 8d tensors support in activation and quantize primitives
- *108270*

[GPU] Support 8d tensors in activation and quantize primitives

---

src/plugins/intel_cpu/tests/functional/subgraph_tests/src/mha.cpp

- *Allow to tokenize MHA without machine dependency (Snippets MHA Tokenization depends on target machine configuration*
- *101903, 104954*

[Snippets][CPU][Test] Allow to tokenize MHA without machine dependency

---

src/plugins/intel_gna/src/gna_plugin_internal.hpp

Fix TSAN issue in GNA plugin

---

tools/pot/openvino/tools/pot/statistics/statistic_graph_builder.py

- A new shape inference step has been added to calculate accurate shape for the inserted statistics.
- 104158

[POT] Added inference shape for in-place statistics

---

src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp

- *fix input issuse of ScatterNDUpdate conformance test*
- *96718*

fix input issuse of ScatterNDUpdate conformance test

---

src/plugins/intel_cpu/src/nodes/executors/acl/acl_reduce.cpp
src/plugins/intel_cpu/src/nodes/executors/acl/acl_reduce.hpp

The same check is presented in inti method but it could be done in isSupported

[CPU] Add axis check to ACL Reduce isSupported method

---

src/common/offline_transformations/src/pruning/propagate_masks.cpp

- Fix Coverity issues
- CVS-108959

Fix Coverity

---

src/inference/dev_api/cpp_interfaces/impl/ie_executable_network_thread_safe_default.hpp
src/plugins/intel_gna/src/log/log.cpp
src/plugins/intel_gna/src/log/log.hpp

Fix TSAN issue No2 in GNA plugin

---

src/common/low_precision_transformations/include/low_precision/network_helper.hpp
src/common/low_precision_transformations/src/convolution.cpp
src/common/low_precision_transformations/src/convolution_backprop_data.cpp
src/common/low_precision_transformations/src/eliminate_fake_quantize.cpp
src/common/low_precision_transformations/src/fold_fake_quantize.cpp
src/common/low_precision_transformations/src/network_helper.cpp
src/common/low_precision_transformations/tests/fold_fake_quantize_in_transformations.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/group_convolution_transformation.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/low_precision_transformations/group_convolution_transformation.cpp
src/tests/functional/plugin/shared/src/low_precision_transformations/group_convolution_transformation.cpp

[LPT] FQ reference implementation reused in foldFakeQuantize function

---

src/plugins/intel_cpu/thirdparty/FindACL.cmake

Reverts openvinotoolkit/openvino#17152

Revert "Proper ACL version detection"

---

samples/cpp/benchmark_app/README.md
samples/cpp/classification_sample_async/README.md
samples/cpp/speech_sample/README.md
samples/python/classification_sample_async/README.md
samples/python/speech_sample/README.md
tools/benchmark_tool/README.md
tools/compile_tool/README.md

State single value is uese

---

src/inference/dev_api/cpp_interfaces/impl/ie_executable_network_thread_safe_default.hpp
src/plugins/intel_gna/src/gna_plugin_internal.hpp
src/plugins/intel_gna/src/log/log.cpp
src/plugins/intel_gna/src/log/log.hpp

[2022.3] Fix TSAN issues in GNA plugin

---

src/common/low_precision_transformations/include/low_precision/common/precisions_restriction.hpp
src/common/low_precision_transformations/include/low_precision/markup_precisions.hpp
src/common/low_precision_transformations/src/markup_precisions.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- *Precision restriction customization extending + usage for 3D convolution in CPU*
- *Tests: https://github.com/openvinotoolkit/openvino/pull/17196*
- *104566*

[LPT] Precision restriction customization extending

---

src/plugins/intel_gna/legacy/include/legacy/graph_tools.hpp
src/plugins/intel_gna/src/gna_infer_request.cpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/src/optimizer/gna_pass_manager.cpp

- CID: 1491505, 1491595, 1502494, 1502500, 1504698, 1504769, 1507058
- 108942

[Gna][coverity] fixes for issue type AUTO_CAUSES_COPY

---

src/common/low_precision_transformations/include/low_precision/common/precisions_restriction.hpp
src/common/low_precision_transformations/include/low_precision/markup_precisions.hpp
src/common/low_precision_transformations/src/markup_precisions.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/group_convolution_transformation.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/fake_quantize_and_convolution_function.cpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/group_convolution_function.cpp

- leftover https://github.com/openvinotoolkit/openvino/pull/17147: *Precision restriction customization extending + usage for 3D convolution in CPU: tests*
- *104566*

[LPT] Precision restriction customization extending: tests

---

src/plugins/intel_gpu/src/graph/dft.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/tests/passes/reorder_inputs_test.cpp

- Adjust layout optimization logic to avoid unwanted rank changes
- *108740*

[GPU] Fix layout propagation logic

---

src/plugins/intel_cpu/src/nodes/space_to_batch.cpp
src/plugins/intel_cpu/src/nodes/space_to_batch.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/space_to_batch.cpp
tests/layer_tests/tensorflow_tests/test_tf_SpaceToBatch.py

- *Threads with WorkAmount == 0 tried to read/write out of bounds.*
- *107967*

[CPU] Infer_request crashes for SpaceToBatch operation.

---

tests/layer_tests/mo_python_api_tests/test_mo_convert_pytorch.py
tools/mo/openvino/tools/mo/convert_impl.py
tools/mo/openvino/tools/mo/moc_frontend/pytorch_frontend_utils.py

- *item1*
- *...*
- *ticket-id*

use input parameter for building example_inputs

---

tests/layer_tests/mo_python_api_tests/test_mo_convert_pytorch.py

- Disabled failing MO Python API tests.
- 109430

Disabled failing MO Python API tests.

---

docs/nbdoc/consts.py
docs/tutorials.md

Porting: https://github.com/openvinotoolkit/openvino/pull/17201
Updating tutorials with new notebooks.

[DOCS] Updating Interactive Tutorials for 22.3

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *Disable test case with sporadic failure.*
- *109482*

[CPU] Disable test case with sporadic failure.

---

docs/ops/activation/GELU_2.md
docs/ops/activation/GELU_7.md
docs/ops/arithmetic/FloorMod_1.md
docs/ops/arithmetic/Floor_1.md
docs/ops/comparison/GreaterEqual_1.md
docs/ops/comparison/Greater_1.md
docs/ops/convolution/GroupConvolutionBackpropData_1.md
docs/ops/convolution/GroupConvolution_1.md
docs/ops/detection/GenerateProposals_9.md
docs/ops/image/GridSample_9.md
docs/ops/movement/GatherElements_6.md
docs/ops/movement/GatherND_5.md
docs/ops/movement/GatherND_8.md
docs/ops/movement/GatherTree_1.md
docs/ops/movement/Gather_1.md
docs/ops/movement/Gather_7.md
docs/ops/movement/Gather_8.md
docs/ops/normalization/GRN_1.md
docs/ops/quantization/FakeQuantize_1.md
docs/ops/sequence/GRUCell_3.md
docs/ops/sequence/GRUSequence_5.md
docs/requirements.txt

port 
https://github.com/openvinotoolkit/openvino/pull/17253

[DOCS] shift to rst - opsets F,G

---

src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/src/variables_index.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_metagraph_variables.py

- Added handling of additional pruned inputs
- Added possible topology of RestoreV2 -> AssignVariableOp
- Added additional checks
- ...

[TF FE] Added additional pruned inputs for MetaGraph support

---

src/plugins/intel_cpu/src/nodes/interpolate.cpp
src/plugins/intel_cpu/src/nodes/interpolate.h

- *proofreading correction for interpolate code comments*

[CPU]proofreading correction for code comments

---

docs/install_guides/pre-release-note.md
docs/install_guides/pypi-openvino-dev.md
docs/install_guides/pypi-openvino-rt.md

- *item1*
- *...*
- *ticket-id*

[DOCS] Remove pre-release notes

---

thirdparty/CMakeLists.txt

- Ported https://github.com/openvinotoolkit/openvino/pull/17273

Fixes for OpenCL via brew package

---

.ci/openvino-onnx/Dockerfile
install_build_dependencies.sh
src/bindings/python/CMakeLists.txt
tools/mo/unit_tests/mock_mo_frontend/mock_mo_python_api/CMakeLists.txt

-  Ported https://github.com/openvinotoolkit/openvino/pull/17297

Fixed Python API build for Ubuntu 22.04 with python3.11 (#17297)

---

docs/MO_DG/Deep_Learning_Model_Optimizer_DevGuide.md
docs/MO_DG/prepare_model/MO_Python_API.md
docs/MO_DG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md

Port https://github.com/openvinotoolkit/openvino/pull/14380 to release docs
- *ticket-id*

[DOCS] Document Model Optimizer Python API port

---

tests/layer_tests/tensorflow_tests/test_tf_SpaceToBatch.py

**Details:** Extend pre-commit for SpaceToBatch after CPU crash
**Ticket:** 107967

[TF FE] Extend pre-commit for SpaceToBatch after CPU crash

---

docs/ops/activation/HSigmoid_5.md
docs/ops/activation/HSwish_4.md
docs/ops/activation/HardSigmoid_1.md
docs/ops/comparison/IsFinite_10.md
docs/ops/comparison/IsInf_10.md
docs/ops/comparison/IsNaN_10.md
docs/ops/condition/If_8.md
docs/ops/image/I420toBGR_8.md
docs/ops/image/I420toRGB_8.md
docs/ops/image/Interpolate_1.md
docs/ops/image/Interpolate_11.md
docs/ops/image/Interpolate_4.md
docs/ops/signals/IDFT_7.md
docs/ops/signals/IRDFT_9.md

DOCS shift to rst - Opsets H & I - for 23.0

---

docs/Documentation/openvino_ecosystem.md
docs/Documentation/openvino_training_extensions.md

- *item1*
- *...*
- *ticket-id*

DOCS Port update OTE and Datumaro links 

---

docs/OV_Runtime_UG/supported_plugins/CPU.md

this small fix was here https://github.com/openvinotoolkit/openvino/pull/14901
but we forgot to add it here https://github.com/openvinotoolkit/openvino/pull/15918
PR to master branch: https://github.com/openvinotoolkit/openvino/pull/17315

[DOC] small fix for sparse weights decompression feature  documentation

---

src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h

- Reduces plugin binary size by ~150KB

[GPU] Minor binary size reduction

---

src/frontends/pytorch/src/utils.cpp
tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
tests/layer_tests/pytorch_tests/test_pow.py

- *Cherry-pick #17305*
- *109763*

Fix issue with Pow when both inputs are scalars

---

src/plugins/intel_cpu/src/dnnl_extension_utils.cpp
src/plugins/intel_cpu/src/dnnl_extension_utils.h
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/conv.h
src/plugins/intel_cpu/src/nodes/deconv.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/lrn.cpp
src/plugins/intel_cpu/src/nodes/matmul.cpp
src/plugins/intel_cpu/src/nodes/pooling.cpp
src/plugins/intel_cpu/src/nodes/softmax.cpp

[CPU] Clean up primitive desc creation in prepareParams

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_infer_request/perf_counters.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/behavior/ov_infer_request/perf_counters.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_infer_request/perf_counters.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_infer_request/wait.cpp
src/tests/functional/plugin/shared/src/behavior/ov_infer_request/perf_counters.cpp

- *item1*
- *...*
- *ticket-id*

[ie tests] Move CheckOperationInProfilingInfo to common part

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/merge_xmls.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_conformance.py

- *Remove duplications of results per devices in api_report*
- *CVS-109885*

[CONFORMANCE] Remove duplications from API Conformance report

---

src/core/src/op/non_max_suppression.cpp
src/core/tests/type_prop/non_max_suppression.cpp
src/inference/src/cnn_network_ngraph_impl.cpp

Fix regression for legacy IRs with NMS-5 after: https://github.com/openvinotoolkit/openvino/pull/15853
PR to master: https://github.com/openvinotoolkit/openvino/pull/17313

NMS-5 calculate upper-bound

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp

- *Propagate output layout padding info to optimized out user node when Crop node is optimized out*
- *...*
- *107749*

[GPU] update padding info for optimized out node

---

src/plugins/auto/docs/tests.md

- update test doc part for auto plugin
- 100527

[AUTO DOC] test cases

---

docs/ops/activation/LogSoftmax_5.md
docs/ops/arithmetic/Log_1.md
docs/ops/comparison/LessEqual_1.md
docs/ops/comparison/Less_1.md
docs/ops/infrastructure/Loop_5.md
docs/ops/logical/LogicalAnd_1.md
docs/ops/logical/LogicalNot_1.md
docs/ops/logical/LogicalOr_1.md
docs/ops/logical/LogicalXor_1.md
docs/ops/normalization/LRN_1.md
docs/ops/sequence/LSTMCell_1.md

DOCS shift to rst - `L` Opsets for 23.0

---

docs/ops/activation/LogSoftmax_5.md
docs/ops/arithmetic/Log_1.md
docs/ops/comparison/LessEqual_1.md
docs/ops/comparison/Less_1.md
docs/ops/infrastructure/Loop_5.md
docs/ops/logical/LogicalAnd_1.md
docs/ops/logical/LogicalNot_1.md
docs/ops/logical/LogicalOr_1.md
docs/ops/logical/LogicalXor_1.md
docs/ops/normalization/LRN_1.md
docs/ops/sequence/LSTMCell_1.md

DOCS shift to rst - L Opsets

---

src/plugins/intel_cpu/src/nodes/space_to_batch.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *The subtraction operation with unsigned operands was a cause of unpredictable behavior.*
- *107967, 109482*

[CPU] Fix for SpaceToBatch dead loop.

---

docs/ops/activation/Elu_1.md
docs/ops/activation/Exp_1.md
docs/ops/arithmetic/Abs_1.md
docs/ops/arithmetic/Acos_1.md
docs/ops/arithmetic/Acosh_3.md
docs/ops/arithmetic/Add_1.md
docs/ops/arithmetic/Asin_1.md
docs/ops/arithmetic/Asinh_3.md
docs/ops/arithmetic/Atan_1.md
docs/ops/arithmetic/Atanh_3.md
docs/ops/arithmetic/Erf_1.md
docs/ops/comparison/Equal_1.md
docs/ops/detection/ExperimentalDetectronDetectionOutput_6.md
docs/ops/detection/ExperimentalDetectronGenerateProposalsSingleImage_6.md
docs/ops/detection/ExperimentalDetectronPriorGridGenerator_6.md
docs/ops/detection/ExperimentalDetectronROIFeatureExtractor_6.md
docs/ops/generation/Eye_9.md
docs/ops/infrastructure/Assign_3.md
docs/ops/matrix/Einsum_7.md
docs/ops/movement/ExtractImagePatches_3.md
docs/ops/pooling/AdaptiveAvgPool_8.md
docs/ops/pooling/AdaptiveMaxPool_8.md
docs/ops/pooling/AvgPool_1.md
docs/ops/sort/ExperimentalDetectronTopKROIs_6.md
docs/ops/sparse/EmbeddingBagOffsetsSum_3.md
docs/ops/sparse/EmbeddingBagPackedSum_3.md
docs/ops/sparse/EmbeddingSegmentsSum_3.md

Shifting to reST
Port from https://github.com/openvinotoolkit/openvino/pull/17363
- Einsum-7
- Elu-1
- EmbeddingBagOffsetsSum-3
- EmbeddingBagPackedSum-3
- EmbeddingSegmentsSum-3
- Equal-1
- Erf-1
- Exp-1
- ExperimentalDetectronDetectionOutput-6
- ExperimentalDetectronGenerateProposalsSingleImage-6
- ExperimentalDetectronPriorGridGenerator-6
- ExperimentalDetectronROIFeatureExtractor-6
- ExperimentalDetectronTopKROIs-6
- ExtractImagePatches-3
- Eye-9

DOCS shift to rst - Opsets E for 23.0

---

docs/OV_Runtime_UG/supported_plugins/GPU.md

porting: https://github.com/openvinotoolkit/openvino/pull/17274
* Update dynamic shape document for GPU
* Applied review comments

[GPU] Update dynamic shape document  (#17274)
