openvinotoolkit/openvino

src/bindings/python/tests/test_graph/test_ops_fused.py

- Reenable of the xpassing test.
- *...*

[PyOV] Enable group_convolution_backprop test

---

tools/mo/automation/package_BOM.txt
tools/mo/openvino/tools/mo/utils/ir_reader/internal_ops/scatter.py
tools/mo/openvino/tools/mo/utils/ir_reader/layer_to_class.py
tools/mo/unit_tests/mo/utils/ir_reader/ops_test.py

- *For pattern `ShapeOf->Gather->Unsqueeze->ScatterUpdate` on fully dynamic shape, there is an issue with ScatterUpdate when non normalized value of `updates` are passed to value infer. Fix this issue for MO IR Reader only to limit impact.*
- *108212*

Fix Scatter value infer for fully dynamic value

---

src/common/transformations/src/transformations/convert_precision.cpp

- Change constant precision routine cannot use ngraph::runtime::reference::convert as underling impl fpr fp32->fp16 case due to missed lower/upper bounds (+-fp16 max) clamp logic. 
- Partially reverts logic added here: https://github.com/openvinotoolkit/openvino/pull/16672/
- *CVS-108209*

[CORE] Disable fp32->fp16 optimized constant conversion impl

---

src/plugins/intel_gpu/src/graph/include/layout_optimizer.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

-deconv and conv used same logic to check data_types
At document, they are not same.
- 108266

[GPU] update are_data_types_suitable_for_onednn for deconv

---

src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/src/op/if.cpp
src/frontends/tensorflow/src/op/partitioned_call.cpp
src/frontends/tensorflow/src/op/while.cpp
src/frontends/tensorflow/src/translate_session.cpp
src/frontends/tensorflow/src/translate_session.hpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_partitioned_call_with_conv.py

**Details:** Preliminary setting input shapes and types for body graph InputModel provides more optimal conversion of body-graphs. That is because we concretize input shapes and types and it helps to avoid that translator will work with dynamic ranks and types for body graph operations. The dynamic ranks and types lead to complex sub-graphs with `Convert`, `GroupConv` sub-graphs.
**Ticket:** 109282

[TF FE] Implement optimal conversion of body graphs

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/adaptive_pooling_gpu_ref.cl
src/plugins/intel_gpu/tests/passes/prepare_primitive_fusing_test.cpp
src/plugins/intel_gpu/tests/test_cases/adaptive_avg_pooling_gpu_test.cpp

- This PR fixed a missing data type in the `adaptive_pooling_gpu_ref.cl`
- 107335

[GPU] fixed a missing data type

---

src/plugins/intel_gpu/tests/fusions/fusion_test_common.hpp
src/plugins/intel_gpu/tests/fusions/scatter_nd_update_fusion_test.cpp
src/plugins/intel_gpu/tests/test_utils/test_utils.h

- Currently random generator for unit tests is initialized once on test binary startup, so the actual data generated in each test depends on the order of tests and sensitive to adding/removing of test cases. This patch changes fusion tests to initialize random generator on test startup with seed computed as hash of test case name. So the generated data is supposed to be same regardless filters or tests scope updates.
- This patch impacts only fusion tests, so in the future we'll need to update some other unit tests that call `generate_random_*`  functions
- *109336*

[GPU] Use hash of test name for random generator initialization

---

src/plugins/intel_cpu/src/nodes/executors/interpolate.hpp
src/plugins/intel_cpu/src/nodes/interpolate.cpp
src/plugins/intel_cpu/src/nodes/interpolate.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/interpolate.cpp

-*Some FEs or preprocessing step resize spatial dimenion for tensor with NHWC layout memory, but imported as planar layout[abcd] with axis[1,2] for convinence. In this case, for pillow modes and no pad for now, nhwc layout pass and kernel can be used for this planar layout and axis settings(flag NCHWAsNHWC is true) to get higher perf with: 
1. logical shape alignment [abcd-nhwc] to [adbc-nchw].
2. axis alignment [1,2] to [2,3].
3. config planar layout support and treated it as channel_first layout.*

[CPU] layout alignment to improve perf for interpolate pillow modes

---

src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp
src/tests/functional/plugin/shared/include/snippets/mha.hpp
src/tests/functional/plugin/shared/src/snippets/mha.cpp
src/tests/ngraph_helpers/snippets_ngraph_functions/include/subgraph_mha.hpp
src/tests/ngraph_helpers/snippets_ngraph_functions/src/subgraph_mha.cpp

- *Added check for config parameter `inference_precision`. Before there was only `PluginConfigParams::KEY_ENFORCE_BF16`. It's not enough to know that `enforcebf16` will be really enabled. So some transformations which depend on `enforcebf16` flag, can work incorrectly.*
- *N/A*

[CPU] Fixed enforcebf16 condition for transformation pipeline

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/tests/passes/remove_redundant_reorders_tests.cpp

- Fix remove redundant reorder to skip reorder fusing when sibling node doesn't support fused padding
- 57614

[GPU] Fix remove redundant reorder to skip reorder fusing when sibling node doesn't support fused padding

---

src/common/transformations/src/transformations/transpose_sinking/ts_binary.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp
src/common/transformations/tests/transpose_sinking/ts_common_test.cpp

Added support for FQ op in TS transformation
Tests
Before
After
- *105091*

Add FakeQuantize op support in TS transformations

---

tools/pot/docs/AccuracyAwareQuantizationUsage.md
tools/pot/docs/DefaultQuantizationUsage.md

- Couple of code blocks were missing an `import` keyword

[DOCS] Added a missing import keyword

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_executable_network/ov_exec_net_import_export.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/behavior/ov_executable_network/exec_graph_info.cpp
src/plugins/intel_gna/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_executable_network/ov_exec_net_import_export.cpp
src/plugins/template/tests/functional/skip_tests_config.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_executable_network/exec_graph_info.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_plugin/life_time.cpp
src/tests/functional/plugin/shared/include/behavior/compiled_model/import_export.hpp

- *COMMON: move ImportExport tests to new file, with more appropriate name*
- *API: setup mandatory scope for ImportExport and LifeTime tests*
- *CVS-103950*

[apiConformance] Rebalance ImportExport and LifeTime tests

---

cmake/features.cmake

`cmake_dependent_option(<option> "<help_text>" <value> <depends> <force>)`
Makes `<option>` available to the user if the [semicolon-separated list](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#cmake-language-lists) of conditions in `<depends>` are all true. Otherwise, a local variable named `<option>` is set to `<force>`.
https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html
- E78176
- E78327

Fix enable plugins xml

---

.ci/openvino-onnx/Dockerfile
install_build_dependencies.sh
src/bindings/python/CMakeLists.txt
tools/mo/unit_tests/mock_mo_frontend/mock_mo_python_api/CMakeLists.txt

- Increase minimal pybind11 version for python 3.11
- CVS-109469

Fixed Python API build for Ubuntu 22.04 with python3.11

---

src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.hpp

- ocl nodes in  OV_GPU_DumpGraph will show corresponding batch hash and kernel entry name in the dumped cl codes by OV_GPU_DumpSources

[GPU] Added print batch_hash and entry_hash of corresponding opencl kernel

---

src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/tests/basic_api.cpp
src/frontends/tensorflow/tests/compilation.cpp
src/frontends/tensorflow/tests/conversion.cpp
src/frontends/tensorflow/tests/convert_model.cpp
src/frontends/tensorflow/tests/convert_saved_model.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
src/frontends/tensorflow/tests/library_extension.cpp
src/frontends/tensorflow/tests/op_extension.cpp
src/frontends/tensorflow/tests/telemetry.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_saved_model_with_gather.py
src/frontends/tensorflow/tests/tf_utils.cpp
src/frontends/tensorflow/tests/tf_utils.hpp

**Details:** The problem is that if user tries to convert a model with specified shapes `"--input input1[2,3],input2[4,5]"`, TF FE creates a new tensor place with dynamic type. Though, it should use the original type for `input1` and `input2`. That is a reason to get inconsistent type during conversion of SM format.
Also, refactor TF FE unit-tests. 
**Ticket:** 109544

[TF FE] Use original input types for SavedModel

---

src/bindings/c/tests/ov_remote_context_test.cpp
src/plugins/intel_gpu/include/intel_gpu/runtime/engine_configuration.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/plugin/remote_blob.cpp
src/plugins/intel_gpu/src/runtime/device_query.cpp
src/plugins/intel_gpu/src/runtime/engine.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.cpp
src/plugins/intel_gpu/tests/unit/gtest_main_gpu.cpp
src/plugins/intel_gpu/tests/unit/test_cases/cl_mem_input_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convert_color_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/mem_perf_test.cpp

- Currently GPU plugin may throw exception in `Plugin` c-tor if no available devices are found. In case if user just query the devices via `core.get_property("GPU", ov::available_devices);` he'll get an exception for such hw configuration. This patch allows empty result of the devices query
- Also changed `GetMetric` impl to handle several properties before trying to determine current device

[GPU] Don't throw exception if no devices are found

---

src/core/shape_inference/include/nms_shape_inference.hpp

- Follow-up PR from https://github.com/openvinotoolkit/openvino/pull/16960
- Remove temporary W/A for GPU NMS shape inference
- 79544

[GPU] Remove temporary W/A for GPU NMS shape inference

---

src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/unit/module_tests/graph_manipulation_gpu_test.cpp

- This PR fixes performance issue caused by changing processing order from DFS to BFS during remove redundant reorder pass, which leads to less efficient kernels execution in case of out_of_order queue and higher host overheads in case of barriers usage for kernels synchronization 
- 108347

[GPU] Use BFS processing order for out_of_order queue

---

src/plugins/intel_gna/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_infer_request/io_tensor.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_plugin/core_integration.cpp
src/tests/functional/plugin/shared/include/base/ov_behavior_test_utils.hpp
src/tests/functional/plugin/shared/include/behavior/compiled_model/compiled_model_base.hpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration_sw.hpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/query_model.hpp

- *API: remove u1 u4 i4 for OVInferRequestIOTensorSetPrecisionTest and OVInferRequestCheckTensorPrecision*
- *API: OVInferRequestIOTensorTest , OVInferRequestIOTensorSetPrecisionTest , OVInferRequestCheckTensorPrecision set us mandatory*
- *GPU: add missing OVGetMetricPropsTest tests to skip_tests_config*
- *API: split OVClassModelTestP tests to mandatory and optional, optional tests is named OVClassModelOptionalTestP*
- *remove some OVClassQueryModelTest*
- *CVS-103950*

[apiConformance] Fix rebalance missing changes

---

src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/src/variables_index.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_metagraph_variables.py

- Added handling of additional pruned inputs
- Added possible topology of RestoreV2 -> AssignVariableOp
- Added additional checks
- 109840
PR to master: https://github.com/openvinotoolkit/openvino/pull/17237

[TF FE] Added additional pruned inputs for MetaGraph support (#17237)

---

src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/tests/basic_api.cpp
src/frontends/tensorflow/tests/compilation.cpp
src/frontends/tensorflow/tests/conversion.cpp
src/frontends/tensorflow/tests/convert_model.cpp
src/frontends/tensorflow/tests/convert_saved_model.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
src/frontends/tensorflow/tests/library_extension.cpp
src/frontends/tensorflow/tests/op_extension.cpp
src/frontends/tensorflow/tests/telemetry.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_saved_model_with_gather.py
src/frontends/tensorflow/tests/tf_utils.cpp
src/frontends/tensorflow/tests/tf_utils.hpp

**Details:** The problem is that if user tries to convert a model with specified shapes `"--input input1[2,3],input2[4,5]"`, TF FE creates a new tensor place with dynamic type. Though, it should use the original type for `input1` and `input2`. That is a reason to get inconsistent type during conversion of SM format.
Also, refactor TF FE unit-tests. 
**Ticket:** 109544
PR to master: https://github.com/openvinotoolkit/openvino/pull/17295

[TF FE] Use original input types for SavedModel (#17295)

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
src/plugins/intel_gpu/src/graph/include/loop_inst.h
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/lstm/lstm_elt_kernel_base.cpp
src/plugins/intel_gpu/tests/unit/passes/remove_redundant_reorders_tests.cpp

- 1) reshape w/ fused primiitive should not be optimized out 
- 2) Wrong usage of slice mem / concat mem in loop
- 3) LWS not set in lstm_elt
- 109657

[GPU] Fix bug in reorder_redundant_reorder

---

src/bindings/python/src/openvino/frontend/pytorch/decoder.py
tests/layer_tests/mo_python_api_tests/test_mo_convert_pytorch.py
tools/mo/openvino/tools/mo/convert_impl.py

- *If user do not provide "example_input" or incorrectly provide "example_inputs" instead Decoder and convert_model was printing tracing or scripting stacktrace, which could confuse user. Print better exception.*
- *109831*

[PT FE] Improve exception when decoder cannot trace or script the model

---

src/plugins/intel_cpu/src/nodes/reduce.cpp

- *The bug is introduced in by the last commit 44b7e448c3037a599fd321cdb6cb0936f9055796 of https://github.com/openvinotoolkit/openvino/pull/16829. The precision constraints imposed on the usage of auxiliary kernel (use_aux_kernel), should also be imposed on the optimization entrance (ReduceAll_opt).*
- *[CVS-110021](https://jira.devtools.intel.com/browse/CVS-110021)*

[CPU] Fix kernel precision mismatch in Reduce node

---

src/common/transformations/include/transformations/transpose_sinking/ts_utils.hpp
src/common/transformations/src/transformations/transpose_sinking/ts_binary.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_concat.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_data_movement.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_fuse.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_gather.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_interpolate.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_reduction.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_slice.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_split.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_squeeze.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_unary.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_unsqueeze.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp
src/common/transformations/tests/transpose_sinking/ts_general_test.cpp
src/tests/ie_test_utils/common_test_utils/graph_comparator.cpp
src/tests/ie_test_utils/common_test_utils/ngraph_test_utils.cpp

PR to the master branch: https://github.com/openvinotoolkit/openvino/pull/17283 
- Fix copying of `tensor names` in TS sinking transformations in multi consumers cases. The new logic:
- Fix `friendly names` copying in TS transformation in multi consumers cases.
The new logic: We detect Transpose directly connected to Result operation and copy its name.
If there are multiple such Transposes, TS will work anyway and copy one of available names.
- Fix `sinking is available` check in TS transformations.
- Added `sorting by tensor names` option to GraphComparator 
Performance runs showed no significant degradation.
- *108928*

Fix the names copying in TransposeSinking backward transformations

---

src/frontends/tensorflow_common/src/op/interpolate.cpp

This change mimicks LinearToLinearONNXReplacer transformation in legacy frontend, where linear interpolate mode is replaced with linear_onnx due to performance reasons.
Ticket: CVS-108343

[TF frontend] use InterpolateMode::LINEAR_ONNX if input rank is 4

---

src/inference/src/dev/threading/cpu_streams_executor.cpp

- *fix binding wrong core with latency mode in i9-13900 which is 8Pcore + 16Ecore*
- *ticket-id*

HOT FIX: fix binding wrong core with latency mode in i9-13900

---

src/inference/src/dev/threading/cpu_streams_executor.cpp

- *fix performance degradation with latency mode in i9-13900 which is 8Pcore + 16Ecore*
- *ticket-id*

[HOT FIX]fix binding wrong core with latency mode in RPL(i9-13900 8P+16E)

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gen9_common_conv_fwd_data_f32.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16.cpp
src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp

- The `gen9_common_conv_fwd_data_f32` kernel didn't support operation fusion when #input_channel is 3.
- This PR resolves this issue.
- 107754

[GPU] fix `gen9_common_conv_fwd_data_f32` kernel to support op fusion when #input_channel == 3

---

src/common/low_precision_transformations/CMakeLists.txt

- *CMake warning ignore compiler flag was removed*
- *95169*

LPT cmake warning flag was removed

---

src/common/transformations/tests/op_conversions/convert_prior_box_v8_to_v0_test.cpp
src/core/include/openvino/op/prior_box.hpp
src/core/include/openvino/op/prior_box_clustered.hpp
src/core/shape_inference/include/prior_box_clustered_shape_inference.hpp
src/core/shape_inference/include/prior_box_shape_inference.hpp
src/core/shape_inference/include/prior_box_shape_inference_util.hpp
src/core/src/op/prior_box.cpp
src/core/src/op/prior_box_clustered.cpp
src/core/tests/type_prop/prior_box.cpp
src/core/tests/type_prop/prior_box_clustered.cpp
src/core/tests/visitors/op/prior_box.cpp
src/core/tests/visitors/op/prior_box_clustered.cpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference.cpp
src/plugins/intel_cpu/tests/unit/shape_inference_test/prior_box_clustered_shape_inference_test.cpp
src/plugins/intel_cpu/tests/unit/shape_inference_test/prior_box_shape_inference_test.cpp

- Review for partial shape and label propagation.
- Add template implementation of shape inference.
- Add/update unit test for static and dynamic shapes.
- Review partial values and labels are preserved on inputs.
- Update `evaluate` member functions to use `Tensor` instead `HostTensor`.
- Remove `ngraph` namespace from reviewed operators where possible.
- 97242
- 97296
- 97345
- 97394
- 97497
- 97546

Review prior box and clustered class for shape inference aspects

---

docs/OV_Runtime_UG/supported_plugins/CPU.md
samples/python/benchmark/bert_benchmark/requirements.txt

- backport of https://github.com/openvinotoolkit/openvino/pull/17117

[Backport] OMZ submodule bump for Python 3.11

---

src/common/conditional_compilation/tests/CMakeLists.txt

- Because `ov_conditional_compilation_tests` is enabled via `ENABLE_TESTS`, so with `ENABLE_FUNCTIONAL_TESTS=OFF` build fails with "fatal error: openvino/itt.hpp: No such file or directory" due `funcTestUtils` dependency

Remove `funcTestUtils` from `ov_conditional_compilation_tests`

---

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_MMAD.cl
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/variable.cpp

- Add reorder with output data type between dep and `assign` if input and output data types are different during `add_required_reorders` pass
- Fix incorrect input index to handle leftovers for `fullyconnected_mmad` kernel
- 98010

[GPU] Fix accuracy issue for assign and fully_connected_mmad

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/adaptive_pooling_gpu_ref.cl
src/plugins/intel_gpu/tests/unit/test_cases/adaptive_avg_pooling_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/adaptive_max_pooling_gpu_test.cpp

- Current floating point operations have accuracy issues.
- This PR updates the adaptive pooling kernel to calculate indexes by integer operations instead of floating point operations.
- 107335

[GPU] fix adaptive pooling kernel

---

src/plugins/intel_cpu/src/nodes/reshape.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/shape_ops.cpp

- *Fix bug when reshape is called with empty tensor containing 0 in shape*
- *https://github.com/openvinotoolkit/openvino/pull/17014*
- *ticket-id*

[CPU] Fix bug with reshape on empty tensor CPU Plugin

---

CONTRIBUTING.md
README.md

- Update docs with info about https://github.com/openvinotoolkit/openvino/issues/17502
- Co-authored with @kblaszczak-intel
- na

[Docs] Update docs with information about Contributions Welcome issue

---

src/core/include/openvino/op/strided_slice.hpp
src/core/src/bound_evaluate.cpp
src/core/src/op/strided_slice.cpp
src/core/tests/constant_folding.cpp

- Perform bound evaluation when begin, end inputs got partial value but mask for corresponding input is set and this value is ignored.
- Implement custom fold if default not work to check `StridedSlice` special case where begin and end values are ignored but mask but they are not constants.
-  101315

[Core] StridedSlice improvements of bound evaluation and constant folding

---

src/plugins/intel_cpu/src/nodes/fullyconnected.cpp

- The reason why at the moment a oneDNN acl implementation is picked for fullyconnected node is the fallback logic we have for selecting optimal primitive descriptor. So acl implementation was not in the list and we picked the first supported primitive descriptor (which is acl implementation).
With the fix the node will actually find acl implementation in the priority list.
There is no impact on overall logic, but the fallback should be avoided in general.

[CPU][ARM] Enable oneDNN acl fullyconnected (inner_product)

---

src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/conv.h

- No code logic changed overall
At the moment shouldTryBrgConv is essentially just a check for avx512 isa.

[CPU] Get rid of shouldTryBrgconv flag

---

src/core/src/op/normalize_l2.cpp
src/core/tests/type_prop/normalize_l2.cpp

- After the changes (https://github.com/openvinotoolkit/openvino/commit/b452dab8f08055cefac5d8d1eec79455563961f9) in TypeRelaxed::clone_with_new_inputs -- relaxed NormalizeL2 operation cannot be cloned
- *110999*
PR to master: https://github.com/openvinotoolkit/openvino/pull/17568

Normalize_L2 relax constant input restriction

---

src/plugins/intel_gpu/src/graph/impls/ocl/pooling.cpp

- Fix pooling dynamism check for kernel size 1
- fixed out of range in smoke_MaxPool_GPU_3D/PoolingLayerGPUTest on windows
- no (some random fails on windows)

[GPU] Fix out of range check for pooling

---

docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-yum.md

- Updated APT/YUM instructions with actual version
- Added instructions for Ubuntu22
- Updated subfolders naming for APT

Updated APT/YUM install instructions for 2023.0.0

---

.ci/azure/linux_arm64.yml
src/plugins/intel_cpu/thirdparty/ACLConfig.cmake
src/plugins/intel_cpu/thirdparty/CMakeLists.txt

- Compiling ARM Compute Library for multi isa to be able to run different kernels depending on target architecture. E.g. on Graviton 2 / Graviton ARM CPU plugin can select SVE / SVE2 / SME kernels, on systems with FP16 support - FP16 kernels can be selected. 
- *ticket-id*

Build ARM Compute Library for multi_isa

---

scripts/install_dependencies/install_openvino_dependencies.sh

- Ubuntu 22.04 and newer use `libtbb12` to build OpenVINO. So, we have to use this version in our `install_openvino_dependencies.sh` to be aligned.
- *ticket-id*

Install libtbb12 on U22

---

src/plugins/intel_gpu/src/graph/reshape.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/reshape_si_test.cpp

- Reshape does not support 0D tensor(scalar) for `shape` input
- If the preceding reshape node which converts from 0D tensor to 1D tensor is removed during `handle_reshape` opt pass, the next reshape node should handle 0D tensor with 1D tensor manually
- 110534

[GPU] Minor fix for shape inference of dynamic reshape

---

src/bindings/python/requirements_test.txt

- Limit linter version to avoid release branch CI breaking

[PyOV] Add upper bound to flake version

---

src/bindings/python/wheel/CMakeLists.txt

- Ability to build `openvino-2023.1.0-11090-cp39-cp39-macosx_13_0_universal2.whl`
wheel

Ability to build universal2 wheel packages

---

src/plugins/intel_gpu/tests/unit/fusions/gather_fusion_test.cpp

- Currently, fusion for dynamic shape is prevented for dGPU.

[GPU] Prevented gather fusion test for dgpu dynamic shape

---

tests/constraints.txt
tools/constraints.txt

- Dependabot failed the upgrade at https://github.com/openvinotoolkit/openvino/pull/17648 because of pip conflicts. An update to tools constraints was also needed.
- N/A

[PyOV] Bump `fastjsonschema` for dependabot

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/activation.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/template/tests/functional/skip_tests_config.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/base/utils/ranges.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
src/tests/ie_test_utils/common_test_utils/data_utils.hpp

- In current implementation k (resolution) parameter of generation function affect the range of the generated data. Change the behavior so k parameter only affects granularity.
Example:
- Before: start_from -1, range 2, resolution 100 generates numbers in range: [-1, 0.01] with resolution 100
- After: start_from -1, range 2, resolution 100 generates numbers in range: [-1, 1] with resolution 100
- 110384
Multiple test instances started to fail after correction of random data generation.
Failing instances were skipped for now and follow-up tickets were created for future investigation.
- 111440 - GatherElements
- 111437 - Deconv, GroupDeconv
- 111443 - Eltwise Mod
- 111418 - Snippets Convert
- 111412 - Proposal
- 111406 - Interpolate
- 111405 - GridSample
- 111404 - GatherElements

[IE_TESTS] Correct random data generation

---

samples/cpp/benchmark_app/README.md
samples/cpp/benchmark_app/benchmark_app.hpp

The issue is for the benchmark_app.exe, the -ip and -op params used to take the value “FP16”.  Now you must enter “F16”.  According to the help text, it still says ”FP16”
Copy of: https://github.com/openvinotoolkit/openvino/pull/17707

[Benchmark_app] - Update comments and help text

---

src/core/src/except.cpp

- Don't print `Check: 'false' at`
- *ticket-id*

Don't print check in case of throwing ov::Exception

---

.ci/azure/linux.yml
.ci/azure/linux_debian.yml
.ci/azure/windows.yml

- First of all we need to run tests on C++ in order to see C++ issues
- *ticket-id*

Move Python tests to the end of CI Pipeline.

---

src/inference/src/dev/make_tensor.cpp

- Improve the strides calculation performance by reduce number of loops (2 ->1). 
- Move strides calculation from `TensorView` constructor to `get_strides` and `set_shape` member functions. Strides are calculated only once until (on demand) or when new shape is set. This change improve speed of tensor creation from `TensorView` as this type  of tensor is wrapper for existing memory and use default strides which not always is used.
- 111776

Calculate TensorView strides on demand not in ctor

---

docs/OV_Runtime_UG/migration_ov_2_0/configure_devices.md

- Fixed directives
- Rewritten first paragraph to not link to 2021.4 version of OpenVINO
- Added a separate note with information where to find details about the legacy API.
Port from https://github.com/openvinotoolkit/openvino/pull/17756

[DOCS] Configuring devices article update for 2023.0

---

docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-brew.md
docs/install_guides/installing-openvino-conda.md
docs/install_guides/installing-openvino-from-archive-linux.md
docs/install_guides/installing-openvino-from-archive-macos.md
docs/install_guides/installing-openvino-from-archive-windows.md
docs/install_guides/installing-openvino-pip.md
docs/install_guides/installing-openvino-raspbian.md
docs/install_guides/installing-openvino-yum.md
docs/install_guides/pypi-openvino-dev.md
docs/install_guides/pypi-openvino-rt.md
docs/install_guides/troubleshooting-steps.md
docs/install_guides/uninstalling-openvino.md

- Updated versions in all places (exact archives names will be later)
- Added more descriptive example to check that OpenVINO installed via pypi correctly (printing of available devices)
- Sorted some tabs (Ubuntu 22.04 comes earlier than Ubuntu 18.04 as more modern platform), arm64 is more important than armhf.

Updated install docs for 2023.0

---

src/core/shape_inference/include/interpolate_shape_inference.hpp
src/core/tests/type_prop/interpolate.cpp

- Relax the input validation for Interpolate v4 as current implementation is not backward compatible after changed in 
#17667 
- N/A

Relax sizes and scales check for

---

src/common/snippets/include/snippets/lowered/expression.hpp
src/common/snippets/include/snippets/lowered/loop_manager.hpp
src/common/snippets/include/snippets/lowered/pass/fuse_loops.hpp
src/common/snippets/include/snippets/lowered/pass/init_loops.hpp
src/common/snippets/include/snippets/lowered/pass/insert_buffers.hpp
src/common/snippets/include/snippets/lowered/pass/validate_loops.hpp
src/common/snippets/src/lowered/expression.cpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/allocate_buffers.cpp
src/common/snippets/src/lowered/pass/fuse_loops.cpp
src/common/snippets/src/lowered/pass/init_loops.cpp
src/common/snippets/src/lowered/pass/insert_buffers.cpp
src/common/snippets/src/lowered/pass/insert_load_store.cpp
src/common/snippets/src/lowered/pass/move_result_out_of_loop.cpp
src/common/snippets/src/lowered/pass/softmax_decomposition.cpp
src/common/snippets/src/lowered/pass/validate_loops.cpp
src/common/snippets/src/op/subgraph.cpp

- *Removed limitation for Loop IDs normalization. Now we don't need to normalize the count of nested Loops. It'd be different for expressions.*
- *Allowed to disable incrementing of `LoopPort` in `LoopInfo`*
- *111497*
We don't have tests for LinearIR infrastructure but anyway I've tried to emulate blocking for simple eltwise test `Add` with input shapes `[1x16x32x25],[1x16x32x25]` and `block_size = 4`.

[Snippets] Refactored work with Loop ID

---

src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py

- *For some environments python functions for file handling fail in linux systems. We explicitly use command line in such cases*
- *112380*

[Commit slider] Safe tmp directory handling in linux

---

.ci/azure/linux_arm64.yml
conanfile.txt

- See https://github.com/conan-io/conan-center-index/pull/17416
- Now, we can use OpenCL from CCI in post-commit jobs, which tests Conan integration

Use OpenCL from CCI

---

.ci/azure/linux_debian.yml
cmake/packaging/debian.cmake
cmake/packaging/rpm.cmake

- They are used to test that previous version of release is deleted during installation of current one

Use 2023.0.0 debian packages on CI

---

src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/highlight_tables.py
src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/template/highlight_tables_template.html

It was add some details about run to the top and information about relative passrate. 
Example below was run on cmd(some data was only for devices CPU, GPU, NVIDIA, commit hash is also random):
python highlight_tables.py --current_xmls ..\summary2 --prev_xml  ..\summary1  --expected_devices VPUX DGPU NVIDIA GNA TEMPLATE GPU CPU_ARM CPU  --expected_test_mode static dynamic apiConformanceTests  --current_commit 82ec92dd9860208eb7a9088ddc70af18600e6e2e --prev_commit 82ec92dd9860208eb7a9088ddc70af18600e6e2e
- *CVS-109776*

[conformance] Add rel pass rate to highlight table

---

src/inference/include/ie/ie_precision.hpp

This fixes a compilation problem that happens if compiling with Visual Studio 17.6 using the latest C++ language version.
To reproduce the problem, create e.g. a Windows console application and set the C++ language standard to latest (`/std:c++latest`). The following program then failed with error C2666:
```c++
#define NOMINMAX
#pragma warning(disable : 4996)
#include <Windows.h>
#include <iostream>
#include "openvino/openvino.hpp"
#include "ie/ie_precision.hpp"
using namespace InferenceEngine;
using namespace std;
int main()
{
Precision p{};
auto x = p == Precision::FP32;
std::cout << "Hello World!\n";
}
```
- #17852

Add missing != operator, fixing compilation issue with Visual Studio 17.6 with /std:c++latest.

---

.github/workflows/stale_prs_and_issues.yml

This reverts commit c351335661b5fd4bbfe229fe548a439db237814a.
The number of PRs to scan has reduced and we don't need so many operations per run (and personal token for higher API request limits) anymore

Revert "Stale PRs/Issues action limit extention (#17491)"

---

src/plugins/intel_gpu/include/intel_gpu/plugin/remote_blob.hpp
src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/plugins/intel_gpu/src/plugin/remote_blob.cpp
src/plugins/intel_gpu/tests/functional/behavior/infer_request.cpp
src/plugins/intel_gpu/tests/functional/remote_blob_tests/gpu_remote_tensor_tests.cpp

- Currently we do redundant device input realloc in dynamic case even if actual memory buffer is big enough. This patch fixes it, so memory handle in remote blob is not changed and stores actual memory layout and size, and `m_layout` stores currently requested layout, so get_memory() now does reinterpret internally, but doesn't update original memory handle.
- Also removed device blobs check from set_input() as similar logic is implemented in prepare_inputs()

[GPU] Better device input memory reuse

---

docs/_static/images/model_conversion_diagram.svg

Porting: https://github.com/openvinotoolkit/openvino/pull/17871
Removing info about soon to be deprecated Kaldi, MxNet and Caffee frameworks.

[DOCS] Updating model conversion diagram - for 23.0

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/group_convolution.cpp

We added the group offset twice to the biases, as a result of which we could get accuracy errors or segfaults. It was noticed on the arm64 platform, because under x64 other primitives are mainly used.
**TODO**
PR to onednn fork: https://github.com/openvinotoolkit/oneDNN/pull/194

[CPU] gemm convolution: fixed bias offset

---

src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/kernel_impl_params.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp

There were two issues in runtime buffer fusing
1) Missing condition in matcher for dyanmic tensor 
2) If the node is marked as can_be_optimized = true at build time and then turned out to false at runtime, the kernel compilation has been skipped, because it was checking node->can_be_optimized 
=> To resolve this issue, added can_be_optimzied to impl_param and let the impl create check can_be_optimized in impl_param instead of that in node.
- CVS-112729

[GPU] Fix issue in runtime buffer fusing

---

samples/cpp/benchmark_app/utils.cpp

- *Added `{"VPU", 60}` to `deviceDefaultDurationInSeconds` map*
- *[EISW-83125](https://jira.devtools.intel.com/browse/EISW-83125)*

[EISW-83125] C++ benchmark_app 2.0 does not recognise VPU/VPUX

---

docs/dev/build_linux.md

Ticket: 101774
Link update for driver package in "Build OpenVINO™ Runtime for Linux systems" from 19.41.14441 to 23.13.26032.30
Port from https://github.com/openvinotoolkit/openvino/pull/17966

[DOCS] BuildingForLinux fix for 23.0

---

docs/dev/build_linux.md

Ticket: 101774
Link update for driver package in "Build OpenVINO™ Runtime for Linux systems" from 19.41.14441 to 23.13.26032.30

[DOCS] BuildingForLinux fix

---

src/inference/include/ie/cpu/cpu_config.hpp
src/inference/include/ie/gna/gna_config.hpp
src/inference/include/ie/gpu/details/gpu_context_helpers.hpp
src/inference/include/ie/gpu/gpu_config.hpp
src/inference/include/ie/gpu/gpu_context_api_dx.hpp
src/inference/include/ie/gpu/gpu_context_api_ocl.hpp
src/inference/include/ie/gpu/gpu_context_api_va.hpp
src/inference/include/ie/gpu/gpu_ocl_wrapper.hpp
src/inference/include/ie/gpu/gpu_params.hpp
src/inference/include/ie/hetero/hetero_plugin_config.hpp
src/inference/include/ie/multi-device/multi_device_config.hpp
src/inference/include/ie/vpu/hddl_config.hpp
src/inference/include/ie/vpu/myriad_config.hpp
src/inference/include/ie/vpu/vpu_config.hpp
src/inference/include/openvino/runtime/intel_gpu/ocl/dx.hpp
src/inference/include/openvino/runtime/intel_gpu/ocl/ocl.hpp
src/inference/include/openvino/runtime/intel_gpu/ocl/va.hpp

- *item1*
- *...*
- *ticket-id*

Deprecate plugins config keys

---

src/plugins/intel_gpu/src/graph/concatenation.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/include/reorder_inst.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/concatenation/concatenation_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/concatenation/concatenation_kernel_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/concatenation/concatenation_kernel_simple_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/mvn/mvn_kernel_bfyx_opt.h
src/plugins/intel_gpu/src/kernel_selector/kernels/mvn/mvn_kernel_ref.h
src/plugins/intel_gpu/src/plugin/ops/result.cpp
src/plugins/intel_gpu/tests/unit/passes/remove_redundant_reorders_tests.cpp

- Update reorders that only do type conversion to be fused to previous nodes. i.e. `mvn` and `concatenation`
- 110530

[GPU] Fuse type conversion only reorders to the prev nodes

---

.ci/azure/android_arm64.yml
.ci/azure/linux_arm64.yml
cmake/features.cmake
cmake/templates/OpenVINOConfig.cmake.in
src/frontends/common/include/openvino/frontend/extension/conversion.hpp
src/inference/dev_api/threading/ie_cpu_streams_executor.hpp
src/inference/src/dev/threading/cpu_streams_executor.cpp
src/inference/src/threading/ie_cpu_streams_executor.cpp

- For VCPKG integration 
- Resolves https://github.com/openvinotoolkit/openvino/issues/17985

ARM static build

---

src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/src/runtime/layout.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp

- This PR fixes "[GPU] Can't choose implementation for ..." error at compile graph stage caused by calling `Pad::Total()` of dynamic padding (affected models: chatGlm, dolly quantized version)
- *ticket-id*

[GPU] Fix dynamic padding processing of static dimension

---

src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/assign_registers.cpp

[Snippets] Fixed set for Windows

---

src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
src/plugins/intel_gpu/src/graph/impls/common/wait_for_events.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp
src/plugins/intel_gpu/tests/unit/module_tests/network_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/activation_simple_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp

- Aligned behavior of `ocl_stream::enqueue_marker()` method with OpenCL specification (marker with empty dependencies vector waits for all previous tasks in the queue)
- Fixed events collection in `network::execute_primitive()` method. Previously we stored events only for OOO queue and profiling mode, despite the fact that we need events for synchronization between GPU and CPU impls in in-order queue
- Added dependency events preparation in `primitive_inst::execute()` method for CPU implementations and optimized out implementation if it has CPU users (previously it was done only for OOO queue)
- Return marker from `onednn_primitive::execute()` method if the next operation require synchronization
- Related tests added
- *ticket-id*

[GPU] Fix in-order queue synchronization issue related to OCL/OneDNN impls interaction with CPU impls

---

src/core/include/ngraph/util.hpp
src/core/include/openvino/core/except.hpp
src/core/include/openvino/core/type/element_type.hpp
src/core/include/openvino/op/constant.hpp
src/core/src/except.cpp
src/core/src/node.cpp
src/core/src/op/constant.cpp
src/core/src/partial_shape.cpp
src/core/src/util.cpp
src/core/tests/node_input_output.cpp
src/core/tests/partial_shape.cpp

- Introduce new helper macros for OPENVINO_THROW and NOT_IMPLEMENTED to reduce insert not used code.
- Add Exception default message as class static member which reduce insert literal string by macro
- Use OPENVINO macros instead `throw` and optimize some throw messages.
- On test machine with Ubuntu 20.04 and gcc 9.3 get at least `200 KiB` in size reduction for `libopenvino.so` (LTO enabled)
-  103685

Reduce binary size by optimize exceptions

---

src/frontends/pytorch/src/op/unflatten.cpp
tests/layer_tests/pytorch_tests/test_unflatten.py

- fixed aten::unflatten conversion for case when sizes in prim::ListConstruct
- tested on open_clip models family (https://github.com/mlfoundations/open_clip/tree/main)

[PT FE]: fix unflatten for list construct sizes

---

src/common/snippets/include/snippets/pass/common_optimizations.hpp
src/common/snippets/include/snippets/pass/explicit_transpose_matmul_inputs.hpp
src/common/snippets/src/pass/common_optimizations.cpp
src/common/snippets/src/pass/explicit_transpose_matmul_inputs.cpp
src/common/snippets/src/pass/mha_tokenization.cpp
src/common/snippets/tests/src/pass/mha_tokenization.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp
src/tests/functional/plugin/shared/include/snippets/mha.hpp
src/tests/functional/plugin/shared/src/snippets/mha.cpp
src/tests/ngraph_helpers/snippets_ngraph_functions/include/subgraph_mha.hpp
src/tests/ngraph_helpers/snippets_ngraph_functions/src/subgraph_mha.cpp

- *Updated pass `ExplicitTransposeMatMulInputs`. Now the pass can extract `Transpose` from transposed inputs from MatMul if there isn't another `Transpose` even*
- *Added function that extracts unsupported `Transpose` from body*
- *Failed onnx tests are fixed by https://github.com/openvinotoolkit/openvino/pull/17774*
- *111980*

[Snippets] Added support of MatMuls with transposed inputs

---

samples/cpp/build_samples.sh
samples/cpp/build_samples_msvc.bat

- Don't user direct `make` => use `cmake --build`
- Don't use `-A` to specify platform on Windows, because it works only for MSVC generator

Improved samples build stability

---

docs/dev/build_linux.md

Port from https://github.com/openvinotoolkit/openvino/pull/18101
Ticket: 113196
Updated the Build OpenVINO™ Runtime for Linux systems article to include information on CMake options for Custom Compilation with a link to list of all available options.

[DOCS] CMake options description in build guide for 23.0

---

src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/src/backend/gna_limitations.hpp
src/plugins/intel_gna/src/common/graph_utils.hpp
src/plugins/intel_gna/src/layers/gna_split_layer.hpp
src/plugins/intel_gna/src/optimizer/gna_pass_manager.cpp
src/plugins/intel_gna/src/optimizer/gna_pass_manager.hpp
src/plugins/intel_gna/src/transformations/split_convolution_with_large_buffer_size.cpp
src/plugins/intel_gna/tests/unit/gna_get_aligned_split_sizes.cpp
src/plugins/intel_gna/tests/unit/transformations/gna_insert_copy_layer.cpp
src/plugins/intel_gna/tests/unit/transformations/gna_split_convolution_with_large_buffer_size.cpp
src/plugins/intel_gna/tests/unit/transformations/gna_split_eltwise.cpp

- Use 16-byte memory alignment for nGraph transformations when the graph is compiled for LNL
- Replace the usage of the ALING64 macro with GNA device-specific alignment
- Update tests to support LNL 16-byte memory alignment
- 107362

16 byte memory alignment and concat

---

src/inference/src/ie_network_reader.cpp

- Fixed behavior in case we are passing folder path on input for another frontend
- _CVS-113384_

[IRv7] Fixed behavior if folder path on input

---

samples/cpp/build_samples.sh

- The "-j" flag is already defined in the running command https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/build_samples.sh#L105.

[Samples] Remove duplicating job number declaration

---

src/frontends/onnx/tests/op_extension.cpp

- Conan / VCPKG define `ONNX_NAMESPACE` as `onnx`, which conflicts with OpenVINO's `ov::frontend::onnx`, when not fully qualified namespace is used.
- https://dev.azure.com/openvinoci/dldt/_build/results?buildId=581492&view=logs&j=92ba3447-fcaa-530d-6438-b829fe1e7d1d&t=4f935517-a7be-5d65-8946-2dc835c10dac&l=338466

Fixed compilaiton of ONNX FE tests

---

src/plugins/intel_cpu/src/emitters/utils.cpp

MSVC141 fails to handle `reinterpret_cast` of a template function pointer due to [a bug in the compiler](https://developercommunity.visualstudio.com/t/bug-reinterpret-cast-address-of-templated-static-f/396044).
This is the most "elegant" solution I could come up for this case.
I'm really sorry for these multiple PRs targeting outdated compiler support, and I hope this will be the last one.

Add workaround for MSVC141 bug evoking C2440 compilation error

---

cmake/features.cmake

- When TF is disabled, we don't have to build Snappy dependency

Fixed Snappy dependent option default value

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/plugin/ops/gather.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/gather_si_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/crop_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gather_gpu_test.cpp

+ Changed Gather if it cropped input along batch
+ Converted Gather to cldnn Crop in CreateGatherOpBase
- Converted Gather to cldnn Crop in CreateGatherOpBase in ops/gather
- Optimized Crop as implicit crop
- 104425

[GPU] Optimize out Gather by converting to implicit crop

---

src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/conv.h
src/plugins/intel_cpu/src/nodes/deconv.cpp
src/plugins/intel_cpu/src/nodes/deconv.h

Otherwise the plugin will throw later when trying to select optimal
primitive descriptor (when there is actually no descriptors at all)
Also remove legacy filters for convolution and deconvolution node which are meaningless at this point

[CPU] Add early throw for filtering primitive descriptors

---

src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp

Current GemmBaseTests in iGPU are skipped, just showed pass, but actual did not run.
- *ticket-id*

[GPU] Fix skipped GemmBaseTests in iGPU.

---

tools/compile_tool/main.cpp

A common mistake is to provide `compile_tool` with  `-c plugin.conf` file that contains `KEY=VALUE`. The parameter will be silently ignored. Fix that behavior by throwing an exception.
#-113187

[CompileTool] Throw when provided plugin config is incorrect

---

src/common/snippets/include/snippets/lowered/loop_manager.hpp
src/common/snippets/include/snippets/lowered/pass/fuse_loops.hpp
src/common/snippets/include/snippets/lowered/pass/insert_load_store.hpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/fuse_loops.cpp
src/common/snippets/src/lowered/pass/insert_load_store.cpp
src/common/snippets/src/lowered/pass/softmax_decomposition.cpp

- *Hided all methods with explicit `Loop ID` work inside private section of `LoopManager`*
- *Added methods `update_loop_ports`*
- *Added methods `fuse_loops` that unite two `LoopInfo` into one and mark expression by new `Loop ID`*
- *Added method `expression_replacement`. The method should be removed after `Softmax Decomposition` refactoring (moving to data flow)*
- *Fixed `FuseLoops` pass. Inner Loops can contain ports which are ports of outer Loops as well. When we fuse and move these inner loops, we can corrupt the sort of LoopPorts of outer Loops. Because of that we have to sort outer Loop ports if we moved loops*
- *112195*

[Snippets] Refactored LoopManager

---

src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_control_dependency.py

**Details:** Handle control dependencies to have correct a number of outputs. Nodes having control flow dependents can be terminating.
**Ticket:** 111548

[TF FE] Handle control dependencies to have correct outputs

---

src/plugins/intel_gpu/include/intel_gpu/primitives/shape_of.hpp
src/plugins/intel_gpu/src/graph/shape_of.cpp
src/plugins/intel_gpu/src/plugin/ops/shape_of.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/shapeof.cpp
src/plugins/intel_gpu/tests/unit/test_cases/shape_of_gpu_test.cpp

- *Fixed to use input shape rank when calculating output layout*
- *In the case of ShapeOfOp, enable allow_new_shape_infer (deprecated)*
- *110900*

Allow new shape infer of ShapeOf

---

src/common/snippets/include/snippets/lowered/loop_manager.hpp
src/common/snippets/include/snippets/lowered/pass/init_loops.hpp
src/common/snippets/include/snippets/lowered/pass/insert_loops.hpp
src/common/snippets/include/snippets/lowered/pass/insert_tail_loop.hpp
src/common/snippets/include/snippets/op/brgemm.hpp
src/common/snippets/include/snippets/op/loop.hpp
src/common/snippets/include/snippets/op/memory_access.hpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/cleanup_loop_offsets.cpp
src/common/snippets/src/lowered/pass/fuse_loops.cpp
src/common/snippets/src/lowered/pass/init_loops.cpp
src/common/snippets/src/lowered/pass/insert_buffers.cpp
src/common/snippets/src/lowered/pass/insert_loops.cpp
src/common/snippets/src/lowered/pass/insert_tail_loop.cpp
src/common/snippets/src/lowered/pass/load_movebroadcast_to_broadcastload.cpp
src/common/snippets/src/lowered/pass/move_result_out_of_loop.cpp
src/common/snippets/src/lowered/pass/move_scalar_to_consumer.cpp
src/common/snippets/src/lowered/pass/validate_loops.cpp
src/common/snippets/src/op/brgemm.cpp
src/common/snippets/src/op/loop.cpp
src/common/snippets/src/op/memory_access.cpp
src/common/snippets/src/op/subgraph.cpp
src/common/snippets/tests/src/pass/lowered/loop.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_copy_b.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_copy_b.hpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_cpu.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_cpu.hpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/add.cpp

- *Added `ptr_increments` and etc. storage in `LoopInfo`* 
- *Split `InitLoops` into 2 passes: `InitLoops` (inits `ptr_increments` and etc. storage in `LoopInfo`) and `InsertLoops` (explicitly insert in Linear IR)*
- *Added `loop_ids` support for `Loops`, `Buffers` and passes that are called after `InitLoops` to have correct `LoopManager` during the whole pipeline*
- *Updated `InsertTailLoop` logic: added tailing processing support for splitted Loops*
- *Fixed `clone_with_new_inputs` for `Brgemm` ops - before `count` weren't copied*

[Snippets] Added tailing processing support for splitted Loops

---

src/plugins/intel_gpu/src/graph/impls/onednn/reorder_onednn.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp

Missed memory offset handling for onednn reorder.
- *ticket-id*

[GPU] Fix onednn implicit concat issue with reorder as input.

---

samples/python/setup.cfg
src/bindings/python/tests/test_onnx/test_ops_reshape.py
src/bindings/python/wheel/setup.py

- Ignore the rule of flake8-variables-names "single letter variable names" which is not applicable in samples.
- Fix other minor issues in other files.
- N/A

Fix flake8 warnings and ignore VNE001 for Python samples

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- The original memory was overwritten unexpectedly because it was chekcing shared_ptr instead of actual buffer address
- This case happened in the following sequence 
- 1) At first run, a layer uses a kernel, which requires reorder weight reorder and the format is compatible with original layout(e.g., jit::gemm::any with oiyx) => So the memory object is original as is and it is registered to reordered_weights_cache
- 2) Then in the next iteration with different shape, it selects a new kernel which requires weight reorder(e.g., fc_bf_tiled_opt kernel with os_iyx_osv16 format). At this time, it attempts to check whether the memory in the reordered_weights_cache is reusable. Here, it was reordering the "original memory" object because it was registered in the reordered_weights_cahce. 
- 3) …

[GPU] Fix bug in weight reorder.

---

src/bindings/python/wheel/setup.py
tools/benchmark_tool/CMakeLists.txt

- Removed benchmark_tool from `openvino` since the `opencv` dependency is still not solved

Removed benchmark_tool from openvino

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- If the node is part of shape of subgraph, no need to wait for dependent node because it will be cpu impl
- N/A
-

[GPU] Not to add sync if the node belongs to shape of subgraph

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/is_valid_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/passes/add_onednn_optimization_attributes_test.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_primitive_fusing_test.cpp

- Avoiding wrong enum type check in activation fusing
- Getting feature value by get_partial_shapes() instead of get_tensor() for dynamic shape unbounded case
- Avoiding eltwise fusing to onednn gemm when rank > 4.
- 110936

[GPU] fix issues of MobileFaceNet for dynamic shape

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp

- From the PR https://github.com/openvinotoolkit/openvino/pull/18158, shape of subgraphs' mem dep was missing so that many dynamic shape execution crashed
- Fixed not to skip memdep set

[GPU] Fix crash for shape of subgraph due to missing mem_dep

---

src/plugins/intel_gpu/include/intel_gpu/runtime/tensor.hpp
src/plugins/intel_gpu/src/graph/crop.cpp
src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/crop.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/crop_si_test.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/matmul_si_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp

- Fix `get_partial_shape` tensor API to access the correct index of dimensions
- Update the rule specifying output data type to the legacy one by referring to `calc_output_layout` to prevent propagating to output data type not supported by fc kernels
- Fix `are_data_types_sutable_for_onednn` not to invalidate output layout
- 99450

[GPU] Fix output layout calculation for crop and fc

---

src/common/snippets/include/snippets/lowered/loop_manager.hpp
src/common/snippets/include/snippets/lowered/pass/fuse_loops.hpp
src/common/snippets/include/snippets/lowered/pass/split_loops.hpp
src/common/snippets/include/snippets/op/subgraph.hpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/fuse_loops.cpp
src/common/snippets/src/lowered/pass/init_loops.cpp
src/common/snippets/src/lowered/pass/insert_buffers.cpp
src/common/snippets/src/lowered/pass/split_loops.cpp
src/common/snippets/src/op/subgraph.cpp
src/common/snippets/tests/src/lowering_utils.cpp
src/plugins/intel_cpu/src/emitters/x64/jit_snippets_emitters.cpp
src/plugins/intel_cpu/src/emitters/x64/jit_snippets_emitters.hpp
src/plugins/intel_cpu/src/nodes/subgraph.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.hpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/fuse_load_store_and_convert.hpp

- *Brgemm emitter: removed blocking by M*
- *Blocking markup pass which covers brgemm with loop by M*
- *SplitLoops pass: split loop to prepare it for further fusion*
- *FuseLoops: added a check on ports compatibility*
- *InsertBuffer: added a logic for allocation shape computation in order to reduce memory allocation in case of blocking*
- *CVS-112491*

[Snippets] MatMul: blocking by M dimension at the LIR stage

---

src/bindings/python/src/compatibility/openvino/inference_engine/ie_api_impl.cpp
src/inference/include/ie/details/ie_so_pointer.hpp
src/inference/include/ie/ie_common.h
src/inference/src/cpp/exception2status.hpp
src/inference/src/cpp/ie_extension.cpp
src/inference/tests/unit/cpp_interfaces/exception_test.cpp
src/inference/tests/unit/ie_exception_test.cpp
src/plugins/intel_gna/src/gna_infer_request.cpp

-  Reduce binary size of IE_THROW and IE_ASSERT macros.
- The size reduction difference in libraries (on Ubuntu 20.04, gcc 9.3 no LTO)
|   **Library**                                  | **Size reduction [KiB]** |
|-------------------------------------|---------------------------|
| libopenvino.so                             | 29.97                              |
| libopenvino_intel_cpu_plugin.so | 40.38                              |
| libopenvino_intel_gpu_plugin.so | 12.73                              |
| libopenvino_intel_gna_plugin.so | 45.23                              |
| libopenvino_ir_frontend.so          | 0.69                                |
| libopenvino_onnx_frontend.so    | 0                                     |
| libopenvino_hetero_plugin.so     | 2.45 …

Optimize IE_THROW and IE_ASSERT for size reduction

---

src/common/transformations/include/transformations/op_conversions/convert_scatter_elements_update12_downgrade.hpp
src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
src/common/transformations/src/transformations/op_conversions/convert_scatter_elements_update12_downgrade.cpp
src/common/transformations/tests/op_conversions/convert_scatter_elements_update12_downgrade_test.cpp

- Downgrades v12 to v3 as a part of common optimizations
- The downgrade doesn't happen if any reduction mode is selected (other than NONE)
- 114127

ScatterElementsUpdate-12 downgrade transformation

---

src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fq_fused_with_ss.cpp

- Checking of nonbias port in FQ-MM fusing
- Caused by *https://github.com/openvinotoolkit/openvino/pull/13502*
- *110147*

[CPU] Checking of nonbias port in FQ-ScaleShift fusing

---

src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/swap_convert_transpose.cpp
src/plugins/intel_cpu/tests/unit/ngraph_transformations/swap_convert_transpose.cpp

- *The CPU Plugin Pass `SwapConvertTranspose` swaps the nodes but doesn’t change the output name.  The PR adds the updates of names and refactors the code a little bit*
- *Added unit test that verifies: names, graph and runtime info*
- *113703*

[CPU] Fixed naming in SwapConvertTranspose pass

---

src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/src/graph/impls/cpu/shape_of.cpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/reduce_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/runtime/memory_pool.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/memory_test.cpp

- This PR enables memory reuse for dynamic models.
* updated `user_requesting_mem_reuse_false` not to return true when dynamic models
* updated `user_requesting_mem_reuse_false` to use `primitive_inst` instead of `program_node` in runtime
* updated memory_pool.release_memory() to compare buffer_ptrs 
- 91383

[GPU] memory reuse for dynamic models

---

src/inference/src/dev/make_tensor.cpp
src/inference/tests/unit/ie_blob_test.cpp

- Update the `setShape` member function of `TensorMemoryBlob` class to synchronize the Blob pointer with `ITensor` instance data pointer.
- 114388

[core] Update setShape TensorMemoryBlob

---

src/common/transformations/include/transformations/op_conversions/convert_pad_to_group_conv.hpp
src/common/transformations/src/transformations/op_conversions/convert_pad_to_group_conv.cpp
src/common/transformations/tests/op_conversions/convert_pad_to_group_conv.cpp

- fix ConvertPadToGroupConvolution to support Pad12 with positive indexes
- fix unit tests to check both v1::Pad and v12::Pad
- add unit test to check negative padding case
- 112279

ConvertPadToGroupConvolution support Pad12 with positive indexes

---

src/common/transformations/src/transformations/fp16_compression/mark_subgraphs_to_keep_in_mixed_precision.cpp

- fix PropagateDownDisableSensitivityForQuantized to support both v1::Pad and v12::Pad
- 112279

PropagateDownDisableSensitivityForQuantized Pad12 support

---

src/bindings/python/tests/__init__.py
src/bindings/python/tests/test_onnx/test_backend.py
src/plugins/intel_cpu/src/nodes/common/cpu_memcpy.h
src/plugins/intel_cpu/src/nodes/unique.cpp
src/plugins/intel_cpu/src/nodes/unique.hpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/unique.cpp

- *Fix for invalid sorting in sliced case*
- *101008, 103964*

[CPU] ONNX Unique tests failing on CPU

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/unit/passes/handle_reshape.cpp
src/plugins/intel_gpu/tests/unit/passes/reorder_inputs_test.cpp

- *Set preferred format of gather to avoid add reorder in front of gather and reshpae*
- *Prevent adding reorder:_reshape_input_ for dynamic*
- *105930*

[GPU] Selected format adjusts to the required input rank at get_preferred_format

---

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/unit/passes/add_required_reorders_test.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
src/plugins/intel_gpu/tests/unit/passes/remove_redundant_reorders_tests.cpp

- Skip `fuse_quantize_f` if input or output layout is dynamic on `prepare_primitive_fusing`
- Update condition of `can_fuse_reorder_to_prev` for concat in shape_of subgraph
- Skip `concat_in_place` optimization if concat is shape_of subgraph on `prepare_buffer_fusing`
- Add reorder if eltwise is shape_of subgraph and data types between input and output are different
- Skip reorder+quantize optimization if reorder has dynamic shape on `remove_redundant_reorders`
- 114263

[GPU] Some fixes to enable dynamic validation model

---

src/common/snippets/include/snippets/lowered/linear_ir.hpp
src/common/snippets/include/snippets/lowered/pass/insert_buffers.hpp
src/common/snippets/src/lowered/linear_ir.cpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/insert_buffers.cpp
src/common/snippets/src/lowered/pass/insert_load_store.cpp
src/common/snippets/src/lowered/pass/insert_tail_loop.cpp
src/common/snippets/src/lowered/pass/load_movebroadcast_to_broadcastload.cpp

- *Fixed Buffer insertion position: `potential_consumers` is unsorted by `linear IR` set. We have to find first expr in `Linear IR` from the set to insert `Buffer` before **all** consumers*
- *Added `OPENVINO_ASSERT` for all `std::find` if needed*
- *N/A*

[Snippets] Fixed insertion position iterators

---

docs/OV_Runtime_UG/supported_plugins/GNA.md
docs/install_guides/installing-openvino-overview.md

Fixing references in the `Install Intel® Distribution of OpenVINO™ Toolkit` article.

[DOCS] Fix references in installation guide for 23.0

---

docs/OV_Runtime_UG/supported_plugins/GNA.md
docs/install_guides/installing-openvino-overview.md

Fixing references in the `Install Intel® Distribution of OpenVINO™ Toolkit` article.

[DOCS] Fix references in installation guide

---

tools/mo/requirements_mxnet.txt

- the newest version of mxnet is 1.9.1: https://pypi.org/project/mxnet/1.9.1/#history
- numpy==1.24.0 deprecated `np.bool` symbol: https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations
- mxnet==1.9.1 uses it, causing errors in CI pipelines: https://github.com/apache/mxnet/blob/v1.9.1/python/mxnet/numpy/utils.py#L37
- we can't upgrade mxnet, so we have to limit numpy version for MO mxnet
- N/A

[PyOV] Limit `numpy` version to 1.23 for MO mxnet

---

src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/fully_connected.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp

- *FC kernel supports only 4d input/output for dynamic case, so compress the shape 6d/5d to 4d for fc kernel execution*
- *105930*

[GPU] Support FC 6d output by compressing as 4d in kernel

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/include/intel_gpu/graph/serialization/binary_buffer.hpp
src/plugins/intel_gpu/src/graph/data.cpp
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/plugin/graph.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/proposal_cpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/streams_test.cpp
src/plugins/intel_gpu/tests/unit/test_utils/test_utils.h

- This PR updates the model caching to use a new graph local net_id for the multiple streams execution.
- It resolves a thread safety issue of GPU model caching.
- 112483

[GPU] updates to use a graph local net_id for model caching

---

src/plugins/intel_gpu/src/graph/impls/cpu/shape_of.cpp

- This PR updates the `shape_of` primitive not to propagate dependent layer's events when in-order queue is used.
- *ticket-id*

[GPU] updated not to propagate events when in-order queue is used

---

tools/mo/openvino/tools/mo/back/preprocessing.py

There was an error in 2022.3.1 LTS with resnet-50-tf and some other models. The error message `"setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part."` is in numpy. And happens for newer numpy>=1.24.4 when np.copy is called:
https://github.com/openvinotoolkit/openvino/blob/358efd2d0645aa4eeac37fb243269b4af48af6da/tools/mo/openvino/tools/mo/back/preprocessing.py#L28
np.copy function does not want to copy mean_scale_val (which is a list with a an array and with a None). 
To fix this need to replace `np.copy` -> `copy`, indeed this is already done in PR #17070. Here i port that changes into 2022.3 (changes in unit-tests were not ported since they are not compatible with 2022.3)
- …

[MO] fix np.copy error for older numpy versions

---

src/plugins/intel_gna/src/common/graph_utils.hpp
src/plugins/intel_gna/src/gna_transformations_pipeline.cpp
src/plugins/intel_gna/src/transformations/insert_copy_layer.cpp
src/plugins/intel_gna/src/transformations/insert_identity_layer.cpp
src/plugins/intel_gna/src/transformations/insert_identity_layer.hpp
src/plugins/intel_gna/tests/unit/transformations/gna_insert_identity_layer.cpp

Problem: if between one of Concat inputs and the Parameter layer there is no layer, which could get requantized according to scale factors from the second Concat input, plugin cannot properly propagate scale factors
Solution: in such a case additional layer has been added - Identity, which is used as a holder for scale factors data
- 111356

[GNA] Fix for concat requantization problem

---

src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/memory_realloc_test.cpp

- Fix two issues 
- 1) internal buffer was always using host mem 
- 2) internal buffer was always enqueuing reset mem
- 113149

[GPU] Disable redundant reset for internal buffer

---

src/frontends/onnx/frontend/src/op/cum_sum.cpp
src/frontends/onnx/tests/models/cum_sum_2d_axis_input_1d.prototxt
src/frontends/onnx/tests/models/cum_sum_2d_dynamic_axis_input_1d.prototxt
src/frontends/onnx/tests/onnx_import.in.cpp

- *enable 1-D axis in cumsum, which is aligned with ort*
- *111483*

enable 1-D axis in cumsum

---

.github/workflows/linux.yml
.github/workflows/windows.yml

This PR introduces the skip mechanism for GHA pipelines that prevents the Linux & Windows pipelines from running on documentation-related PRs.
- *115385*

[CI] [GHA] Do not run GHA pipelines (Linux & Windows) on documentation-related PRs

---

src/common/util/src/log.cpp
src/plugins/intel_gpu/include/intel_gpu/plugin/program.hpp
src/plugins/intel_gpu/src/plugin/program.cpp

- Fixed data race in RegisterFactory() function (previously we had unique instance of static mutex for each specific template's type)
- Fixed access to not a thread safe result of gmtime() function which uses single static buffer under the hood
- *ticket-id*

[GPU] Fix data races in RegisterFactory() and log functions

---

.github/workflows/linux.yml
.github/workflows/windows.yml
README.md

This PR introduces the cancel mechanism for the in-progress pipelines of PRs in favour of that of the latest commit. It affects only the pipelines on PRs, it **_does not change_** the behaviour on the master branch as `github.head_ref` is only defined for the PRs and `github.run_id` is guaranteed to be unique.
- *115463*

[CI] [GHA] Cancel in-progress Linux & Win pipelines in favour of that of on the latest commit in PRs

---

.github/workflows/windows.yml

This PR prevents the Windows GHA workflow from starting on PR and push events. It can only be started manually.
We have to do this since we've exceeded the limits of GA runners usage defined for our current billing plan, and openvinotoolkit organization started suffering from long queues.

[CI] [GHA] Disable Windows workflow

---

src/tests/ie_tsan.supp

- Issue is caused by signal that terminates full run. After signal is handled by tests utilities, run generates tests report, and TSAN claims issue (`handler calls malloc()` - from https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions) on it
- CVS-114114

Suppress `signal-unsafe call` tsan issue

---

tools/benchmark_tool/requirements.txt
tools/constraints.txt

cv2 availability is already optional: https://github.com/openvinotoolkit/openvino/blob/238c7fa47e02e9cc44aa0ede9e934a45d0a6cd45/tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py#L148

Don't require opencv-python for benchmark_app

---

cmake/developer_package/compile_flags/os_flags.cmake

- After previous changes LLDB doesn't stop on breakpoints or doesn't show lines of code.
- Enable path changing only for the release mode
- *ticket-id*

Trim paths only for Release mode

---

src/plugins/intel_gpu/src/graph/compilation_context.cpp
src/plugins/intel_gpu/src/graph/include/compilation_context.hpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp

- This PR fixes the async compilation context to use the kernel_impl_params as the keys to overcome hash collisions.
- 114982

[GPU] fix compilation context to use kernel_impl_params as key

---

cmake/developer_package/compile_flags/os_flags.cmake
src/common/util/src/file_util.cpp
src/core/tests/file_util.cpp

- __FILE__ macro on windows build can have also forward slash as path separator add it to trim by compiler.
- If not trimmed by compiler, function `ov::util::trim_file_name` will also try trim forward slash if file not already trimmed (on windows only).
- 115443

Improve __FILE__ trim on windows builds

---

tools/mo/unit_tests/mo/utils/ir_reader/restore_graph_test.py

In test_save_and_restore_with_converts() temporary directory is created using tempfile library, then the directory is explicitly deleted by os.removedirs().
If tempfile.TemporaryDirectory object is destroyed by garbage collector then the corresponding directory is cleared automatically, which leads to failing of explicit deletion. 
This leads to sporadic fail of test.
Solution: 
Do not remove tempfile.TemporaryDirectory() explicitly, but use **with** expression to make sure, that directory is closed and cleared.
Ticket: 115444
Code:
Validation:
Documentation:

Fixed temporary directory creating in test_save_and_restore_with_converts().

---

src/inference/dev_api/ie_system_conf.h
src/inference/dev_api/openvino/runtime/system_conf.hpp
src/inference/src/system_conf.cpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/nodes/reduce.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/reduce.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/reduce.hpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/instances/common/reduce.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/instances/x64/reduce.cpp

- *Reduce node supports fp16 precision.*
- *https://jira.devtools.intel.com/browse/CVS-108837*

[CPU] Reduce node supports fp16 precision

---

docs/MO_DG/prepare_model/convert_model/supported_model_formats.md

Content realignment between nightly and 23.0 versions after porting.
Fixing the deprecation notice for legacy formats in `Supported Model Formats` article.

[DOCS] Fixing the deprecation notice 

---

src/frontends/pytorch/src/op/upsample.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_upsample.py

- *support aten::_upsample_bilinear2d_aa, aten::_upsample_bicubic2d_aa*
tested on fastcomposer model
- *ticket-id*

[PT FE]: support upsample2d bilinear and bicubic with antialias

---

src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/include/conv_with_zero_point_fuse.hpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/conv_with_zero_point_fuse.cpp
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.cpp
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.hpp
src/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/builders.hpp
src/tests/ngraph_helpers/ngraph_functions/src/convolution.cpp

- *CPU zero-point fuse fix*
- *CVS-111175*

[CPU] zero-point fix

---

src/inference/tests/functional/caching_test.cpp
src/plugins/hetero/src/compiled_model.cpp
src/plugins/hetero/src/compiled_model.hpp

- Model returned by `get_runtime_model()` not useful for import/export

Revert "Remove extra model from CompiledModelDesc" 

---

src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_selector.cpp
src/plugins/intel_gpu/tests/unit/test_cases/permute_gpu_test.cpp

- The PR https://github.com/openvinotoolkit/openvino/pull/13561 caused many accuracy issues. Disable it and enable it once the issues are resolved.
- *ticket-id*

[GPU] Disable permute_f_y_axis because of accuracy issue

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/infer_request.hpp
src/plugins/intel_gpu/src/graph/include/input_layout_inst.h
src/plugins/intel_gpu/src/graph/include/loop_inst.h
src/plugins/intel_gpu/src/graph/include/mutable_data_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/input_layout.cpp
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/graph/mutable_data.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/infer_request.cpp

- Not need to do reset_execution for each prepare_input/output
- Instead, fixed the sync of I/O to be done by event
- Also there was a problem of allocation of output memory, i.e., even though the node has only  shape_of user as cpu user, it was allocating host memory. 
- Also fixed not to do clFinish before shape_of
- 115589

[GPU]  Reduce clfinish io and allow input reorder to use device mem

---

cmake/templates/OpenVINOConfig.cmake.in

- It fails in conda-forge for macOS cross-compilation from x86_64 for arm64.

Don't use -Wl,--allow-shlib-undefined on macOS

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/run_conformance.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *run_conformance.py and run_parallel.py fails for apiConformanceTests, because opset tests was excluded from apiConformance. So also report_op.xml and failed_ir no longer exists for apiConformance.*
- *CVS-116217*

[apiConformance] Fix run_confoormance fails after exclusion opset tests

---

src/bindings/python/requirements.txt
tools/constraints.txt
tools/mo/openvino/tools/mo/convert_impl.py
tools/mo/openvino/tools/mo/main.py
tools/mo/openvino/tools/mo/utils/check_ie_bindings.py
tools/mo/openvino/tools/mo/utils/telemetry_utils.py
tools/mo/openvino/tools/mo/utils/utils.py
tools/mo/unit_tests/mo/extensions_test_actual.py
tools/mo/unit_tests/mo/unit_test_with_mocked_telemetry.py
tools/mo/unit_tests/mo/utils/freeze_placeholder_test.py
tools/mo/unit_tests/mo/utils/mo_fallback_test_actual.py
tools/mo/unit_tests/mo/utils/mo_fallback_test_tf_fe.py
tools/mo/unit_tests/mo/utils/telemetry_utils_test.py
tools/mo/unit_tests/mo/utils/test_mo_model_analysis_actual.py
tools/ovc/openvino/tools/ovc/convert_impl.py
tools/ovc/openvino/tools/ovc/main.py
tools/ovc/openvino/tools/ovc/telemetry_utils.py
tools/ovc/openvino/tools/ovc/utils.py
tools/ovc/unit_tests/ovc/unit_test_with_mocked_telemetry.py

Telemetry package with version less than 2023.1.0 causes error during Telemetry initialization with GA4 backend.
Solution: 
Increase openvino_telemetry version in requirements to 2023.1.0
In case if GA4 backend is not available use telemetry_stab class.
Ticket: 116174
Code:
Validation:
Documentation:

Increased telemetry version in requirements, corrected telemetry imports.

---

src/plugins/intel_cpu/thirdparty/ACLConfig.cmake

- gemm primitive is selected instead of acl one
- revert v3.2 changes for acl_matmul for now
- enable fixed size kernels to use "any" format (has_opt_impl() acl feature)
- bring back winograd convolution
oneDNN PR:
- https://github.com/openvinotoolkit/oneDNN/pull/200
Ticket:
- 115969
TBD:

[CPU][ARM] Fix perf issues of oneDNN 3.2 migration

---

src/plugins/intel_cpu/src/exec_network.cpp
src/plugins/intel_cpu/src/exec_network.h
src/plugins/intel_cpu/src/weights_cache.cpp
src/plugins/intel_cpu/src/weights_cache.hpp

- *Current OpenVINO weight sharing mechanism only shares weight inside NUMA Node, each NUMA Node has one copy of weight. It's not always efficient in a system with SNC enabled. This PR put only one copy of weight in one Socket, the NUMA nodes inside the Socket can share weight*
- *...*
- CVS-113069
- Closes https://github.com/openvinotoolkit/openvino/issues/17942

Allow weight sharing across NUMA nodes inside one socket

---

README.md

- Current `openvino` is a high-level meta-package, while users can download individual packages (e.g. IR + CPU components only), so we need to track by base subpackage, which is `libopenvino` with OpenVINO shared library itself

Changed the component for conda-forge downloads stat

---

src/frontends/pytorch/src/op/squeeze.cpp
tests/layer_tests/pytorch_tests/test_slice.py
tests/layer_tests/pytorch_tests/test_squeeze.py

- *disable workaround for squeezing non 1 size axes, that introduces dynamic squeeze issue*
verified on llama models family
- *CVS-115765*

[PT FE]: fix issues with squeeze producing dynamic rank

---

src/plugins/intel_cpu/thirdparty/ACLConfig.cmake

- It currently does not affect any production code, because we use gcc older than 10 in production builds.
- But in conda-forge or Ubuntu 22.04 newer compiler versions are used and this branch is triggered. But it leads to internal issues inside the scons build.

Disabled multi_isa in ARM CPU plugin

---

src/bindings/python/src/openvino/frontend/tensorflow/graph_iterator.py
src/bindings/python/src/openvino/frontend/tensorflow/node_decoder.py
src/bindings/python/src/openvino/frontend/tensorflow/utils.py
tests/layer_tests/mo_python_api_tests/test_mo_convert_tf.py
tools/mo/openvino/tools/mo/convert_impl.py
tools/ovc/openvino/tools/ovc/convert_impl.py

Description: 
Used "share_memory" parameter to turn on/off shared memory in tf.Graph decoder.
Ticket: 114971
Code:
Validation:
Documentation:

Use of share_memory parameter in tf.Graph decoder.

---

src/inference/src/dev/core_impl.cpp
src/plugins/hetero/src/compiled_model.cpp
src/plugins/hetero/src/config.cpp
src/plugins/hetero/src/config.hpp
src/plugins/hetero/tests/unit/compile_model_tests.cpp
src/plugins/hetero/tests/unit/hetero_tests.cpp
src/plugins/hetero/tests/unit/properties_tests.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_gna/src/gna_plugin_config.cpp
src/plugins/intel_gpu/include/intel_gpu/runtime/internal_properties.hpp
src/plugins/intel_gpu/src/plugin/compiled_model.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp
src/plugins/template/src/plugin.cpp

…ted_properties
- *[GPU] Replace ov::intel_gpu::exclusive_async_requests by ov::internal::exclusive_async_requests*
- *[GPU] Show actual number of streams when ov::intel_gpu::exclusive_async_requests is set*
- *[GPU][CPU][GNA][Template] Add ov::internal::exclusive_async_requests in ov::internal::supported_properties*
- *[HETERO] Set  ov::internal::exclusive_async_requests if model is split and property is supported*
- *ticket-id*

Adds ov::internal::exclusive_async_requests in ov::internal::supported_properties

---

src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/runtime/execution_config.cpp

- This change enables ov::enable_profiling property if OV_GPU_DumpProfilingData debug option applied. ov::enable_profiling property configures OpenCL queue with CL_QUEUE_PROFILING_ENABLE option which is needed for proper OneDNN's primitives profiling
- *ticket-id*

[GPU] Force ov::enable_profiling if OV_GPU_DumpProfilingData debug option is used

---

src/core/include/openvino/pass/pass_config.hpp
src/core/src/pass/pass_config.cpp
src/frontends/onnx/frontend/include/openvino/frontend/onnx/extension/conversion.hpp
src/frontends/onnx/frontend/src/extensions.cpp
src/frontends/paddle/include/openvino/frontend/paddle/extension/conversion.hpp
src/frontends/paddle/src/extensions.cpp
src/frontends/pytorch/include/openvino/frontend/pytorch/extension/conversion.hpp
src/frontends/pytorch/src/extensions.cpp

- Fixed warnings like:
```
In file included from $SRC_DIR/src/core/include/openvino/pass/pass.hpp:16,
from $SRC_DIR/src/core/include/openvino/pass/graph_rewrite.hpp:11,
from $SRC_DIR/src/frontends/common/include/openvino/frontend/node_context.hpp:10,
from $SRC_DIR/src/frontends/paddle/include/openvino/frontend/paddle/decoder.hpp:7,
from $SRC_DIR/src/frontends/paddle/include/openvino/frontend/paddle/node_context.hpp:7,
from $SRC_DIR/src/frontends/paddle/src/op/hard_sigmoid.cpp:5:
$SRC_DIR/src/core/include/openvino/pass/pass_config.hpp:160:33: warning: the mangled name of 'ov::pass::PassConfig::<lambda(const std::shared_ptr<const ov::Node>&)>::operator bool (*)(const std::shared_ptr<const ov::Node>&)() const' changed between '-fabi-version=11' …
```

Fixed -Wabi warnings in headers

---

src/core/include/openvino/op/random_uniform.hpp
src/core/shape_inference/include/random_uniform_shape_inference.hpp
src/core/src/op/random_uniform.cpp
src/core/tests/copy.cpp
src/core/tests/type_prop/random_uniform.cpp
src/plugins/intel_cpu/src/utils/shape_inference/shape_inference.cpp
src/plugins/intel_cpu/tests/unit/shape_inference_test/random_uniform_shape_inference_test.cpp
src/plugins/intel_cpu/tests/unit/shape_inference_test/utils.hpp

- Check dynamic and static shape propagation.
- Check label propagation.
- Check preserve input values and labels.
- Add template implementation of `shape_infer`.
- 97245
- 97293
- 97342
- 97391
- 97440
- 97494

Review RandomUniform for shape inference

---

src/plugins/intel_gpu/src/graph/permute.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/reorder.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/bounded_shape_mem_alloc.cpp

- Allow reorder & permute to allocate memory at build time for bounded dynamic shape
- 116421

[GPU] Allocate reorder & permute's output memory for bounded dynamic shape

---

src/core/src/dimension_tracker.cpp
src/core/src/op/reshape.cpp
src/core/tests/dimension.cpp

- *Fixed `TableOfEquivalence::are_equal`* to treat same label as equal
- *Allowed Reshape operation to treat labeled constant dimensions as constant*

Dimension equality fix

---

src/common/util/src/file_util.cpp
src/tests/test_utils/common_test_utils/tests/utils_tests.cpp

- Fixes https://github.com/openvinotoolkit/openvino/issues/18243

Fix `get_directory()` to return `/` on Linux

---

src/plugins/intel_gpu/src/plugin/graph.cpp
src/plugins/intel_gpu/src/plugin/ops/parameter.cpp

- Do not add post type conversion reorder for inputs if mean value is not specified and the data type does not change
- 116261

[GPU] Do not add post reorder for inputs if data type does not change 

---

src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/src/nodes/input.cpp

When nstreams is 1,  CPU plugin would directly reuse the ngraph const blob memory. Current ngrpah would use mmap() to 
map the whole blob into user space memory. So there is no memory alignment from Ngrpah side. SSE41 has 16-byte memory 
alignment with some  instructions. Fix by cloning input blob if input blob is not 16 byte aligned on SSE.
- *114257*

Ensure const blob 16 byte alignment on SSE.

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/summarize.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/template/report_api_template.html

- *'passed' counted twice for 'all test amount' for optional scope, so passrate was wrong*
- *first view option was 'mandatory', but it was shown statistic for 'optional' scope*
- *CVS-116515*

[apiConformanceReport] Fix double 'passed' in 'all test amount' and fist mandatory view

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/unit/passes/remove_redundant_reorders_tests.cpp

- Add dependency output port to some program_node/program methods to have correct node removal in case if removed node is connected to non-default port of dependency.
- Add ports info to .dot debug dumps

[GPU] Fixed removal of reorder connected to non-default out port

---

src/plugins/intel_cpu/src/utils/shape_inference/shape_inference_ngraph.hpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/custom_op_internal_dyn.cpp

- *Fixed `get_port_mask()` behavior of `NgraphShapeInfer`: only port mask which was set by plugin node is returned, mask from `m_shape_infer` is ignored*
- *CVS-116464*

[CPU] Extensions shape inference issue fix

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- A monolith MVN on GPU side can handle overflows inside itself without being marked as precision sensitive.
- Need to fuse subgraphs into a singe MVN before the `ConveertPrecision` pass where marking of precision sensitive nodes takes place. If we don't do that because of `Division`s with `Eps` these subgraphs will be marked as precision sensitive and additional converts to `f32` and back to `f16` will be inserted, slowing down execution. 
- [CVS-115851](https://jira.devtools.intel.com/browse/CVS-115851)

[GPU] Fuse MVN before ConvertPrecision

---

src/common/low_precision_transformations/src/convert_subtract_constant.cpp
src/common/low_precision_transformations/tests/mark_dequantization_subgraph_transformation.cpp
src/common/transformations/include/transformations/low_precision/mark_dequantization_subgraph.hpp
src/common/transformations/src/transformations/low_precision/mark_dequantization_subgraph.cpp
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/graph_optimizer.h
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/convert_matmul_to_fc.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/move_fc_reshape_to_weights.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/move_fc_reshape_to_weights.hpp
src/plugins/intel_cpu/src/transformations/cpu_opset/convert_to_cpu_specific_opset.hpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/concat_reshape_concat.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_compressed_i8_weights.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp
src/plugins/intel_cpu/tests/unit/ngraph_transformations/convert_matmul_test.cpp
src/plugins/intel_cpu/tests/unit/ngraph_transformations/move_fc_reshape_to_weights.cpp

- *Reused LPT pass for ConstantFold pass disabling for decompression subgraph*
- *GraphOptimizer: added FuseFCAndWeightsDecompression transformation*
- *Transformation pipeline adapted to the MatMuls with compressed weights*
- *Added MoveFCReshapeToWeights CPU transformation*
- *CVS-113732*

[CPU] MatMul: move i8 compressed constants constant folding to the plugin

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/reorder.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/post_optimize_weights.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
src/plugins/intel_gpu/tests/unit/module_tests/kernel_impl_params_relevance_test.cpp
src/plugins/intel_gpu/tests/unit/passes/post_optimize_weights.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp

- Cldnn fc kernels' weights are not likely to be reordered again from the shape agnostic optimal kernel, thus do the weight reorder at build time.
- 116422

[GPU] Do weight reorder for fc shape agnostic kernels at build time

---

src/plugins/intel_cpu/src/nodes/mvn.cpp

- *Valid tails number is [0, 15] on avx512, [0, 7] on avx2 and [0, 3] on sse41. Generic 8/4/2/1 tiles processing for tails should have conditional start. On AVX2, should be 4/2/1. On SSE, should be 2/1. Otherwise, for example, load 8 tails on sse is not allowed*
- *CVS-116378*

[CPU] Fix jit compilation exception on sse for mvn

---

tools/mo/openvino/tools/mo/moc_frontend/pytorch_frontend_utils.py
tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py

- *Models from `nncf<2.6` require strip() to be called before conversion otherwise converted model will lose quantization.*
- *115147*

[MO] Raise exception for older nncf models

---

tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_upsampling2d.py
tests/layer_tests/tensorflow_tests/test_tf_LRN.py

- This PR unskips several tests that were failing in the GitHub Actions environment.
- *113362*

[CI] [GHA] Unskip `test_keras_upsampling2d_bilinear` and `test_lrn_basic` in GHA

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/memory_pool.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
src/plugins/intel_gpu/src/runtime/layout.cpp
src/plugins/intel_gpu/src/runtime/memory_pool.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/memory_realloc_test.cpp

- Fixed issue in memory reuse for ibuf, which was time consuming because previously allocated memories were not released properly.
- Also, added a new debug config OV_GPU_DumpRuntimeMemoryPool to track memory pool status in dynamic shape
- 116913

[GPU] Release unused internal memory from pool

---

src/core/CMakeLists.txt

- Fixed: `Error    LNK1248    image size (1010DF49D) exceeds maximum allowable size (FFFFFFFF)    ngraph_obj `
- CVS-116682

Change linker flags to fix ngraph_obj build in Debug mode

---

src/bindings/python/requirements_test.txt

- Revert the packages to requirements file, which were deleted in https://github.com/openvinotoolkit/openvino/pull/18259
- They need to stay there until Python API 1.0 is removed.
- This fixes openvino-lin-debian postcommit check
- N/A

[PyOV] Restore ONNX requirement for Python tests

---

src/common/snippets/include/snippets/op/vector_buffer.hpp
src/common/snippets/include/snippets/pass/tokenization.hpp
src/common/snippets/src/generator.cpp
src/common/snippets/src/lowered/pass/allocate_buffers.cpp
src/common/snippets/src/lowered/pass/assign_registers.cpp
src/common/snippets/src/lowered/pass/softmax_decomposition.cpp
src/common/snippets/src/op/subgraph.cpp
src/common/snippets/src/op/vector_buffer.cpp
src/common/snippets/src/pass/collapse_subgraph.cpp
src/common/snippets/src/pass/mha_tokenization.cpp
src/plugins/intel_cpu/src/emitters/x64/cpu_generator.cpp
src/plugins/intel_cpu/src/emitters/x64/jit_snippets_emitters.cpp
src/plugins/intel_cpu/src/emitters/x64/jit_snippets_emitters.hpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/mha.cpp
src/tests/functional/plugin/shared/include/snippets/mha.hpp
src/tests/functional/plugin/shared/src/snippets/mha.cpp
src/tests/ngraph_helpers/snippets_ngraph_functions/include/subgraph_mha.hpp
src/tests/ngraph_helpers/snippets_ngraph_functions/src/subgraph_mha.cpp

- *Enable Snippets tokenization on quantized models and float models with `inference_precision=bf16`*
- *Disabled custom MHA Fusion pass*
- *Added `Fill` op after `VectorBuffer` to fill the correct default value for accumulator pattern. Before `ReduceMax` had zeros in buffers but should have `-float_max`*
- *Fixed buffer allocation size*
- *Updated subgraph CPU tests for MHA*
- *112973, 105339*

[Snippets][CPU] Enabled MHA tokenization for quant and bf16 cases

---

src/plugins/intel_gpu/src/graph/network.cpp

- This PR updates to reset 'variable memory's status when shape is changed.
- It's also expected the sporadic error to be fixed.
- 113724

[GPU] updated to reset variable memory's status when shape is changed

---

src/common/snippets/include/snippets/pass/common_optimizations.hpp
src/common/snippets/include/snippets/pass/tokenization.hpp
src/common/snippets/src/pass/common_optimizations.cpp
src/common/snippets/tests/src/pass/mha_tokenization.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *SplitDimensionM optimization has 2 tries to reshape body. First step splits dimension `M` of MHA pattern into two `batch_dim` and `new_dim_m` to have `batch * batch_dim % threads == 0` - all threads have the same work amount. If it's not possible, we have Second step (second attempt). On the master branch this stage tries to make `new_dim_m` as the most value that `new_dim_m < optimal_m_dim`. It's not optimal way since not all threads have work anyway. The PR updates this step. Now the algorithm tries to select such values so that as many threads as possible have work (see the comment for `[ Second Step ]`)*
- *Removed `optimal_m_dim` to increase work thread amount*
- *115284*

[Snippets] Optimized second attempt of SplitDimensionM optimization

---

tools/mo/unit_tests/mo/convert/import_from_mo_test.py
tools/ovc/openvino/tools/ovc/cli_parser.py
tools/ovc/unit_tests/ovc/convert/import_from_mo_test.py

OVC tries to split pathlib.Path by "," which leads to error.
Solution: 
convert pathlib.Path to str before splitting.
Ticket: _CVS-117018_
Code:
Validation:
Documentation:

Fixed OVC "input_model" parameter to work with pathlib.Path.

---

src/plugins/intel_cpu/src/dnnl_postops_composer.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer.h
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp
src/plugins/intel_cpu/tests/functional/target_per_test.cmake

- This PR adds runtime acceleration for LLMs with quantized weights on x86 CPUs
- Supported cases:
-- nodes: FullyConnected
-- weights compression: unsigned 8bit
-- isa: avx2, avx512
- OneDNN PR: https://github.com/openvinotoolkit/oneDNN/pull/206/
- *[CVS-113727](https://jira.devtools.intel.com/browse/CVS-113727)*

[CPU] FullyConnected acceleration with 8bit weights decompression

---

src/frontends/pytorch/src/op/arange.cpp

- *Remove converts to target type before `Range` for `aten::arange` op. `Range` operation specification allow mixed type input, so conversion to destination type before calling Range is not required. Layer tests pass after removing conversion.*
- *116366*

[PT FE] Remove converts to target type before Range for aten::arange op

---

src/plugins/intel_gpu/src/runtime/debug_configuration.cpp

- Restore `disable_memory_reuse` debug config initialization (removed from https://github.com/openvinotoolkit/openvino/pull/18859)
- This issue forces new allocation rather than reuse from memory pool at runtime
- 117089

[GPU] Minor fix for dynamic model regression

---

src/frontends/pytorch/src/op/max_poolnd.cpp
tests/layer_tests/pytorch_tests/test_pooling.py

- Improved conversion of `MaxPool` operator by `PyTorch` frontend, when sliding windows go off bound.
Example:
input shape: [1,3,5,5], kernel=2, stride=2, pad=1,dilation=1, ceil_mode
- `PyTorch` result shape [1,3,3,3] 
- `OV` result shape after conversion [1,3,4,4]
This change makes conversion to be aligned with `PyTorch` result.
- #18731

[PT FE] Improved MaxPool convert by PyTorch FE

---

src/frontends/pytorch/src/op/var_mean.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_reshape_as.py
tests/layer_tests/pytorch_tests/test_var_mean.py

- *support aten::std. aten::std_mean and aten::view_as ops*
tested on wavelm and vaw2vec-conformer models
- *CVS-117016*
- *CVS-117015*

[PT FE]: support aten::view_as and aten::std

---

src/bindings/python/constraints.txt
src/bindings/python/src/openvino/preprocess/__init__.py
src/bindings/python/wheel/requirements-dev.txt
tests/constraints.txt

- Attempt to unblock CI pipelines
- This is not a fix for the issue, but rather a workaround to give us time to resolve it
- The issue with pipelines is most likely to come from new wheel release on August 5 (https://pypi.org/project/wheel/0.41.1/#history)
- Wheel package has caused problems in the past with being non backwards-compatible
- 117193

[PyOV] Add temporary workaround for wheel building issue

---

src/common/transformations/include/transformations/common_optimizations/align_eltwise_input_ranks.hpp
src/common/transformations/include/transformations/common_optimizations/matmul_const_transposes_extraction.hpp
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/graph_optimizer.h
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h
src/plugins/intel_cpu/src/nodes/transpose.cpp
src/plugins/intel_cpu/src/nodes/transpose.h
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/convert_matmul_to_fc.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_decompress_convert.cpp
src/plugins/intel_cpu/tests/unit/ngraph_transformations/convert_matmul_test.cpp

This PR moves constant folding of Transpose nodes (only on weights path of FullyConnected node) to the CPU plugin side, that allows to reduce memory consumption of compile model stage
- added FuseFCAndTransposeOnWeights transformation in cpu graph optimizer
- fixed RTTI for AlignEltwiseInputRanks and MatMulConstTransposesExtraction transformation passes

[CPU] Transpose constant folding on cpu plug-in side for MatMul node only

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/src/graph/compilation_context.cpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp

- This PR updates the async build for dynamic models to build convolution, fully_connected, and softmax layers.
- Current kernel build process has negative impact on inference tasks. So we need to select effective kernels and to build them.
- 103753

[GPU] updated to enqueue only fully_connected layers for async build

---

src/cmake/ie_parallel.cmake

- Fixed there https://github.com/conan-io/conan-center-index/pull/19024
- CVS-117282

Remove WA for Conan in TBB search

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/deformable_convolution.cpp
src/plugins/intel_gpu/src/graph/include/binary_convolution_inst.h
src/plugins/intel_gpu/src/graph/include/convolution_inst.h
src/plugins/intel_gpu/src/graph/include/deconvolution_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/reduce_inst.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_bfyx_os_iyx_osv16.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_yx_fsv_16_32_imad_dw.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_base.h
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_1x1_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_depthwise_weights_lwg.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_winograd_2x3_s1_fused.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_winograd_6x3_s1_fused.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_params.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_params.h
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/deformable_convolution_kernel_bfyx_interp.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/is_valid_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp

- Enabled paddings for dynamic convolutions with `explicit` paddings type
- Enabled convolution_osv16 kernel for bfyx format
- 116788

[GPU] Add paddings for dynamic convolutions

---

src/inference/dev_api/openvino/runtime/internal_properties.hpp
src/inference/src/dev/converter_utils.cpp
src/inference/src/dev/core_impl.cpp
src/inference/src/dev/plugin.cpp
src/inference/src/dev/plugin.hpp
src/inference/src/dev/threading/istreams_executor.cpp
src/plugins/template/src/compiled_model.cpp
src/plugins/template/src/config.cpp
src/plugins/template/src/plugin.cpp
src/plugins/template/src/variable_state.hpp

- Remove legacy metics from the template plugin
- Move legacy supported metric for cases if plugin doesn't support specific legacy metrics to common part
- Introduce new internal properties
- *ticket-id*

Remove legacy API from from template plugin

---

src/plugins/intel_cpu/src/graph.cpp

There are various issues on ARM related to uninitialised operation executor.
The article https://www.arangodb.com/2021/02/cpp-memory-model-migrating-from-x86-to-arm/ says memory_order_relaxed does not guarantee that the initialization is executed before store on ARM.
Tickets: 
CVS-116674
CVS-115839
CVS-113372
CVS-112750

[CPU] Replace memory_order_relaxed with release/acquire in UpdateNodesBase class

---

src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
src/frontends/pytorch/src/utils_quantize.cpp
src/frontends/pytorch/src/utils_quantize.hpp

- *Fix issue with kwargs in signature*
- *117404*

[PT FE] Fix issue with kwargs in signature

---

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
src/plugins/intel_gpu/src/graph/include/pass_manager.h
src/plugins/intel_gpu/tests/unit/passes/add_required_reorders_test.cpp

- This change prevents Conv's input data type changing at reorder_inputs pass in case of supported layout mismatch 
- 116410

[GPU] Prevent Conv's input data type changing at reorder_inputs pass

---

src/plugins/intel_gpu/src/graph/include/program_node.h

- `onednn_impl` requires onednn attr to be initialized before `choose_impl`, and it's done by the `add_onednn_optimization_attributes` pass in the `pre_optimize_graph`.
- If any `onednn_impl` is newly created in `update_impl`, its onednn attr can be in an uninitialized status.
- This PR fixes this problem by initializing onednn attr in `get_onednn_primitive_attributes`.
- 116350

[GPU] updates to initialize onednn attr a new onednn_impl is chosen

---

src/core/shape_inference/include/tensor_data_accessor.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/tensor_accessor.hpp
src/plugins/intel_gpu/src/graph/CMakeLists.txt
src/plugins/intel_gpu/src/graph/arg_max_min.cpp
src/plugins/intel_gpu/src/graph/batch_to_space.cpp
src/plugins/intel_gpu/src/graph/border.cpp
src/plugins/intel_gpu/src/graph/broadcast.cpp
src/plugins/intel_gpu/src/graph/crop.cpp
src/plugins/intel_gpu/src/graph/gather.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/range.cpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/non_max_suppression.cpp
src/plugins/intel_gpu/src/graph/one_hot.cpp
src/plugins/intel_gpu/src/graph/prior_box.cpp
src/plugins/intel_gpu/src/graph/random_uniform.cpp
src/plugins/intel_gpu/src/graph/range.cpp
src/plugins/intel_gpu/src/graph/reduce.cpp
src/plugins/intel_gpu/src/graph/reshape.cpp
src/plugins/intel_gpu/src/graph/space_to_batch.cpp
src/plugins/intel_gpu/src/graph/strided_slice.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/pad_si_test.cpp

- use ov::Tensor for shape inference instead of deprecated HostTensor
- replace map with unordered_map to match available tensor accessor specializations

[GPU] Use ov::Tensor intead of ngraph::HostTensor

---

src/plugins/intel_gna/tests/functional/shared_tests_instances/skip_tests_config.cpp

- Deactivate all smoke_Decompose2D tests,
- It will be reverted once the root cause is identified and resolved
- 114149

[GNA] Temporary deactivation of sporadically failing tests

---

docs/install_guides/installing-openvino-from-archive-linux.md
docs/install_guides/installing-openvino-from-archive-macos.md
docs/install_guides/installing-openvino-from-archive-windows.md

Adding `Install "numpy" Python library` step in installation instructions. 
Porting: https://github.com/openvinotoolkit/openvino/pull/19093

[DOCS] Add numpy to installation instructions for 2023.0

---

src/bindings/python/src/openvino/frontend/pytorch/fx_decoder.py
src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
src/bindings/python/src/openvino/frontend/pytorch/utils.py
src/bindings/python/src/pyopenvino/frontend/pytorch/decoder.hpp
src/frontends/pytorch/include/openvino/frontend/pytorch/decoder.hpp
src/frontends/pytorch/src/translate_session.cpp
src/frontends/pytorch/src/utils.hpp
tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
tests/layer_tests/pytorch_tests/test_quantized_convnd.py

- *This is a legacy POC artifact. Torch tensors can have non-contiguous strides, but openvino doesn't have this concept, we accept only contiguous tensors, so we do not need to correct strides of the input. The problem was found on models obtained without freezing, because freezing removes strides from graph.*
- *None*

[PT FE] Remove torch strides compensation

---

src/bindings/python/requirements_test.txt

- `torch` needs `sympy`, but does not formally require it as a dependency
- it can be seen in https://github.com/pytorch/pytorch/blob/v2.0.1/torch/_guards.py#L11-L16
- this causes sporadic errors in CI when running torchvision to OpenVINO preprocessor tests
- PR forces `sympy` to be installed
- 117517

[PyOV] Add `sympy` dependency for torchvision preprocessor tests

---

src/plugins/intel_cpu/src/dnnl_postops_composer.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer.h
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp

- This PR adds runtime acceleration for LLMs with quantized weights on SPR Xeons
- Supported cases:
-- nodes: FullyConnected
-- weights compression: unsigned 8bit
-- isa: AMX
- OneDNN PR: https://github.com/openvinotoolkit/oneDNN/pull/207
- *[CVS-113727](https://jira.devtools.intel.com/browse/CVS-113727)*

[CPU] FullyConnected acceleration with 8bit weights decompression on SPR

---

src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/tests/common_optimizations/moc_transformations.cpp
tests/layer_tests/mo_python_api_tests/test_mo_convert_tf.py

Names are lost after `validate_nodes_and_infer_types()`. 
In Result `validate_and_infer_types()` output tensor pointer is replaced with input tensor pointer : https://github.com/openvinotoolkit/openvino/blob/648351ba391ce55e17bcc6e758d824a9220f4711/src/core/src/op/result.cpp#L34
So if some tensor name was set in Result output tensor, it becomes lost. 
If we try to set tensor name again after `validate_nodes_and_infer_types()`, it works, as pointers are the same at this point.
The issue appeared when `cf=True` was turned on in MOC transformations.
`cf=True` turns on shape-off constant folding and removes `validate_nodes_and_infer_types()` in the end of MOC transformations pipeline: https://github.com/openvinotoolkit/openvino/blob/648351ba391ce55e17bcc6e758d824a9220f471 …

Fix of tensor names loosing for cf=True flag in MOC transformations.

---

samples/cpp/benchmark_app/utils.cpp

The Python version uses `app_inputs_info` to represent different input configurations, but the C++ version extends that use case and uses `app_inputs_info` to represent different input images as well. That means that the assumption that if `app_input_info.size() > 1`, then input shape is dynamic, doesn’t always hold for C++
Ticket 117673

benhcmark_app: fix -api sync -i multiple images

---

src/tests/test_utils/common_test_utils/include/common_test_utils/data_utils.hpp
src/tests/test_utils/common_test_utils/src/data_utils.cpp

- Improve fill_tensor_random func to work with real value boundaries
- [CVS-117139](https://jira.devtools.intel.com/browse/CVS-117139)

Fix fill_tensor_random for real values:

---

src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
src/plugins/intel_cpu/tests/unit/streams_info/streams_info_table_test.cpp

- *fix manually setting Pcore+Ecore manually when model prefers Pcore only*
- *ticket-id*

HOT FIX: fix manually setting Pcore+Ecore manually when model prefers Pcore only

---

cmake/developer_package/frontends/frontends.cmake
thirdparty/dependencies.cmake

- Our cmake should expect that protobuf-lite can be unavailable

Fixed build without protobuf-lite

---

src/inference/src/dev/make_tensor.cpp
src/plugins/intel_cpu/src/infer_request.h

TensorMemoryBlob doesn't synchronize the internal data pointer with the data pointer of the underlying ITensor object. To address the problem without changes to the `InferenceEngine::Blob` interface, `allocate` method was overloaded, so that it performs the synchronization on demand. 
- 117418

[Core] TensorMemoryBlob: sync data handle on alloc call

---

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
src/plugins/intel_gpu/tests/unit/passes/add_required_reorders_test.cpp

- This change marks output layout of inserted padded_layout -> non_padded_layout reorder as valid - this prevents incorrect format propagation of reorder's users. This patch fixes SD model (FP32) functional issue
- *ticket-id*

[GPU] Don't invalidate users after reorder insertion

---

tools/pot/docs/AccuracyAwareQuantizationUsage.md
tools/pot/docs/DefaultQuantizationUsage.md

- Couple of code blocks were missing an `import` keyword
Port from https://github.com/openvinotoolkit/openvino/pull/17271

[DOCS] Added a missing import keyword for 22.3

---

src/bindings/python/constraints.txt
src/bindings/python/wheel/requirements-dev.txt
src/bindings/python/wheel/setup.py
tests/constraints.txt

- Since `wheel` 0.41.1 we have to create package dir, because since https://github.com/pypa/wheel/commit/e43f2fcb296c2ac63e8bac2549ab596ab79accd0 `egg_info` command works in this folder, because it's being created automatically
- Let's also wait conda-forge build to complete to make sure the issue is fixed there https://github.com/conda-forge/openvino-feedstock/pull/34
- CVS-117193

Removed 'wheel' upper bound in requirements.txt

---

src/plugins/intel_cpu/src/graph.cpp

- oneDNN lacks jit reorder for FP16 precision on ARM and uses
slow ref implementation
- prefer Convert over Reorder for convert-only operation
- 117049

[CPU][ARM][FP16] Prefer Convert over Reorder for conversion

---

src/plugins/intel_gpu/src/plugin/ops/parameter.cpp

- Quantize impl has performance regression when its output format is different from its input format.
- This PR partially reverts https://github.com/openvinotoolkit/openvino/pull/18797
- 117544

[GPU] updated to add reorder after parameter when it is connected to quantize

---

src/common/transformations/src/transformations/op_conversions/convert_interpolate11_downgrade.cpp
src/common/transformations/tests/op_conversions/convert_interpolate11_downgrade_test.cpp

CommonTransformations pass doesn't call ConstantFolding at the end of pipeline, we expect that all transformations after the last ConstantFolding in the pipeline do not insert ShapeOf subgraph in case of static shapes. 
So we decided to add ConstantFolding in ConvertInterpolate11ToInterpolate4 transformation.
- *117863*

Adds constant folding in ConvertInterpolate11ToInterpolate4

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_plugin/properties.cpp

- [FP16 enabling PR](https://github.com/openvinotoolkit/openvino/pull/19069) broke CPU plugin behavior with `Accuracy` execution mode on ARM (expected infer precision is `f32` instead of current `f16`). This PR restores the behavior and fixes `PluginSetConfigExecutionModeExpectCorrespondingInferencePrecision` test

[CPU][ARM] Fixed execution mode behavior

---

src/common/transformations/src/transformations/transpose_sinking/ts_gather.cpp
src/common/transformations/tests/transpose_sinking/ts_gather_test.cpp
tests/layer_tests/tensorflow_tests/test_tf_MaxPoolWithArgmax.py

-  Fixed a crash when the output of gather node was a scalar after the transformation
- Updated unit tests
- *CVS-117415*

Fix TransposeSinking for Gather

---

src/plugins/intel_cpu/src/nodes/gather.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/gather.cpp

Disable inplace memory usage for the case of indices out of the `[-data.shape[axis], data.shape[axis] - 1]` range. In that case the  output data for corresponding index shell be filled with zeros.
- 117378

[CPU] Disable gather inPlace for out of range indices

---

src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/split_concat_add.cpp

We need to remove skipping the first inPlace edge connected to the port in the base edge searching algo. This skip breaks the logic of searching the base edge in the case when a Result and InPlace nodes are connected to the same port. The reasons of having this skip are not so obvious, and at the moment this skip looks obsolete.
- 117593

[CPU] Remove skip for the first inPlace base edge

---

src/bindings/python/tests/test_torchvision_to_ov/test_preprocessor.py

- Current value causes sporadic numerical comparison errors in CI pipelines:
`AssertionError: assert 0.00020426512 < 0.0002`
- 117643

[PyOV] Raise allowed diff value for torchvision preprocessor test

---

src/core/shape_inference/include/nms_shape_inference.hpp
src/core/tests/type_prop/non_max_suppression.cpp

- Fix NMS shape infer for selected boxes dim upper bound (changes proposed by @jade-cho)
- 117397

[ShapeInference] Fix NMS shape infer for selected boxes dim upper bound

---

tools/mo/openvino/tools/mo/moc_frontend/pytorch_frontend_utils.py
tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py

When nncf is imported it shows confusing logs from MO and OVC convert_model().
Solution: 
Check if nncf is in imported modules before importing.
Ticket: 117543
Code:
Validation:
Documentation:

Fix of confusing logs in convert_model().

---

src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp

+ Resolved perf regression from propagation of padded input
- gemm selected gemm_ref kernel by propagated padded input
- padded input is propagated along 'implicit crop - reorder -reshape - matmul'
- CVS-117532

[GPU] Make gemm_tiled_opt support outer axis

---

tests/layer_tests/common/utils/tf_utils.py
tests/layer_tests/ovc_python_api_tests/test_ovc_cli_tool.py
tools/ovc/openvino/tools/ovc/cli_parser.py

Output model is deduced incorrectly if saved model directory is used with separator in the end.
Solution: 
Split input directory in cycle until non-zero name is found.
If no name can be deduced from input directory, set model name to "model".
Ticket: _CVS-117820_
Code:
Validation:
Documentation:

Fixed 'output_model' logic in OVC.

---

src/plugins/intel_gpu/src/graph/graph_optimizer/clamp_fp16_output.cpp
src/plugins/intel_gpu/src/graph/include/pass_manager.h
src/plugins/intel_gpu/src/graph/program.cpp

+ Fixed black output image by Nan output.
+ Resolved fp16 overflow of gemm primitive before softmax
+ Added fused post ops of clamp activation not to get inf which caused Nan output
+ Added new pass modify_fused_ops
- 
- CVS-112747, CVS-114209

[GPU] Resolve fp16 overflow of mul

---

src/common/transformations/src/transformations/op_conversions/convert_sequences_to_tensor_iterator.cpp
src/common/transformations/tests/op_conversions/convert_sequences_to_ti_test.cpp

[REGRESSION]
For some (e.g. quantized) models, W, R, B inputs to sequence operations are not direct constants, but a subgraph that can be constfolded later. In that case, we don't need to have them as inputs to TensorIterator, they can be pulled into its body instead.
Ticket: CVS-117544

ConvertSequenceToTensorIterator - push on-constant-path W, R, B inputs to TI's body

---

src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp
src/common/transformations/tests/transpose_sinking/ts_common_test.cpp

- *Handle the case when the input with the target transpose op is broadcasted
The inserted Transpose after TS had only 2 values in the order input.
```
Input1 (2, 3) -> Transpose -----
Add (out: 1, 2, 3) -> 
Input2 (1, 1, 1) ----------------- 
```
- *CVS-111267*

Fix TransposeSinking when the data input is broadcasted

---

src/core/src/tensor_conversion_util.cpp
src/core/tests/constant_folding.cpp
src/core/tests/tensor.cpp

- The original model contains Parameter node with "unspecified" type. ConstantFolding tries to create ViewTensor via wrap_tensor function with "unspecified" type. ViewTensor ctor contains an assert for this case. So "unspecified" type was handled in wrap_tensor function.
- *CVS-111263*

Handle unspecified type in wrap_tensor function

---

src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_conv_with_dynamic_input_channel.py
src/frontends/tensorflow_common/src/utils.cpp
tools/mo/unit_tests/moc_tf_fe/conversion_with_layout_test.py

**Details:** This solution is aligned with the legacy frontend but it has limitation. This is a temporal solution until the core obtains more precise ShapeOf evaluator.
**Ticket:** 102611

[TF FE] Use regular Convolution in case dynamic input channels

---

.ci/azure/linux.yml
.github/CODEOWNERS
.github/workflows/linux.yml
.github/workflows/windows.yml
src/frontends/tensorflow/src/op/xla_dot.cpp
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow/src/proto/xla_data.proto
tests/layer_tests/jax_tests/conftest.py
tests/layer_tests/jax_tests/jax_layer_test_class.py
tests/layer_tests/jax_tests/test_dot_general.py
tests/layer_tests/requirements.txt

**Details:** Introduce JAX layer tests and support of XLA operations.
Using JAX for models training gives possibility to save a model in SavedModel format or to convert to `tf.function` object.
This conversion can generate XLA operations for some JAX operations that we need to support by TF FE and to test via JAX layer tests.
```python
from openvino import convert_model
from jax.experimental import jax2tf
import tensorflow as tf
def jax_dot_general(lhs, rhs):
out = lax.dot_general(lhs, rhs, (((3),(3)),((0,1),(0,1))))
return out
f = tf.function(jax2tf.convert(jax_dot_general), autograph=False,
input_signature=[tf.TensorSpec([3, 2, 3, 4], tf.float32), tf.TensorSpec([3, 2, 2, 4], tf.float32)])
ov_model = convert_model(f)
```
These JAX layer tests can be easily adopted to test JAX frontend in …

[JAX][TF Hub][TF FE] Introduce JAX layer tests and support of XLA operations

---

src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_conv_with_dynamic_input_channel.py
src/frontends/tensorflow_common/src/utils.cpp
tools/mo/unit_tests/moc_tf_fe/conversion_with_layout_test.py

**Details:** This solution is aligned with the legacy frontend but it has limitation. This is a temporal solution until the core obtains more precise ShapeOf evaluator.
Back-port of https://github.com/openvinotoolkit/openvino/pull/19253
**Ticket:** 102611

[TF FE] Use regular Convolution in case dynamic input channels (#19253)

---

src/plugins/intel_cpu/src/mlas/thread_pool.cpp

- *The parallel_nt doesn't use tbb::static_partitioner, it uses tbb::auto_partitioner, it allows work-stealing, which causes overhead in Xeon-Gold platform.*
- *CVS-118282*

[CPU]Use parallel_nt_static to WA cpu scheduling issue

---

docs/Extensibility_UG/frontend_extensions.md

Adding information on how to link to a frontend when using OPENVINO_FRAMEWORK_MAP macro.
This PR addresses the following issue:
https://github.com/openvinotoolkit/openvino/issues/13744

[DOCS] OPENVINO_FRAMEWORK_MAP macro - link to a frontend

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/rename_conformance_ir.py

-  *Sometimes input/output params and meta data the same for two models, hash will be the same and the second model would not be renamed. So, add the attributes to hash*
- *CVS-115262*

Add attr info to rename_conformance_ir  hash

---

src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/compile.py

- BugFix in TorchFX
- Missing core object in get_device()

TorchFX bugfix missing core object in get_device()

---

docs/Extensibility_UG/frontend_extensions.md

Adding information on how to link to a frontend when using OPENVINO_FRAMEWORK_MAP macro.
This PR addresses the following issue:
https://github.com/openvinotoolkit/openvino/issues/13744
Porting: 
https://github.com/openvinotoolkit/openvino/pull/19178

[DOCS] OPENVINO_FRAMEWORK_MAP macro - link to a frontend - for 23.1

---

src/common/snippets/include/snippets/lowered/expression_port.hpp
src/common/snippets/src/lowered/expression_factory.cpp
src/common/snippets/src/lowered/expression_port.cpp

- *Changed `shared_ptr<Expression>` in `ExpressionPort` to `weak_ptr<Expression>` to remove retain cycle in Linear IR*
- *[PR](https://github.com/openvinotoolkit/openvino/pull/19317) to release branch*
- *117366*

[Snippets] Fixed memory leak in LinearIR

---

src/inference/src/dev/icompiled_model_wrapper.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- Fix 2 new threads created in 1.0 req convert to 2.0 req issue
- 115961

Avoid creating new threads when converting legacy inference request to API 2.0

---

src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.h

Earlier, streams calculation logic has been moved before all transformations. This led to performance degradations in `hint=tput` mode on some INT8 models.
In this PR, number of streams calculation heuristic moved after LPT in plugin pipeline. This allows to take into account the precision of the weights when heuristic is applied.
- *CVS-117971*
PR to release branch: #19312

[CPU] Number of streams calculation heuristic moved after LPT

---

src/inference/src/dev/icompiled_model_wrapper.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- Fix 2 new threads created in 1.0 req convert to 2.0 req issue
- 115961

[Wrapper] Avoid creating new threads when converting legacy inference request to API 2.0

---

src/bindings/python/tests/test_transformations/test_compression.py

- sporadic failures were observed when temporary IRs are saved with the same name. Need to save into a file with unique temporary name to fix that.
- [CVS-118122](https://jira.devtools.intel.com/browse/CVS-118122)

[tests] save into different file in compression_test.py

---

src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir.cpp

- *Fix issue with duplicated test names for DLB based conformance run*
- *https://jira.devtools.intel.com/browse/CVS-118876*

[conformance] Read models only matching with shape_mode

---

src/plugins/intel_cpu/src/nodes/input.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/denormal_check.cpp

- *Context:* CPU plugin has logic that check if constant tensors contain denormal values. In case denormal values are found constant tensor will be copied and denormal values will be zeroed.
- *Issue:* denormals check logic has incorrectly handled negative zero values (-0.0f) assuming them to be denormal. That has led to significant amount of "false-positive" answers and as a results to redundant memory copies. The last thing extremly affects LLMs in terms of memory consumption and compilation time.
- The PR fixes denormals check logic behavior
Cherry-picks: https://github.com/openvinotoolkit/openvino/pull/19360

[CPU] Fixed has_subnormals behavior for negative zero values

---

src/plugins/intel_gpu/src/graph/include/convolution_inst.h
src/plugins/intel_gpu/src/graph/include/deconvolution_inst.h
src/plugins/intel_gpu/src/graph/include/fully_connected_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Previously reordered_weights_cache contained original memory too, which is just reinterpreted
- It is waste of reordered_weights_cache slot, and causes eviction of actually reordered weights which may be needed in the future. 
-  Fixed above issue 
- 119145

[GPU] Fixed reordered memory cache not to contain original weight memory

---

tools/ovc/openvino/tools/ovc/cli_parser.py
tools/ovc/openvino/tools/ovc/convert.py
tools/ovc/unit_tests/ovc/utils/cli_parser_test.py

- inputs with incorrect values were taken as is and then passed into `PartialShape` which caused ungraceful error message. Need to check if --input is acceptable before calling `PartialShape`.
- Example of error message after fix
- [CVS-118217](https://jira.devtools.intel.com/browse/CVS-118217)

[ovc] check if input is correct in split_inputs

---

src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_items_class_optimized.cpp
src/plugins/intel_gpu/tests/unit/fusions/softmax_fusion_test.cpp

- *Try to use softmax_gpu_ref when the input type of softmax that tries to fuse the fakequantize is not same as the output type of the fakequantize*
- *113414*

[GPU] Try to use softmax_gpu_ref when types are mismatched (#19209)

---

src/core/reference/include/openvino/reference/acos.hpp
src/core/reference/include/openvino/reference/acosh.hpp
src/plugins/template/tests/functional/op_reference/acos.cpp

- Improve `Acos` operator reference  accuracy for integral types by replace cast by round. 
- N/A

Improve acos ref accuracy for integral types

---

src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/src/graph/input_layout.cpp
src/plugins/intel_gpu/tests/unit/module_tests/engine_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/data_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/proposal_cpu_test.cpp

- Fixed logic in input_layout::set_data() to handle simple_attached_memory case in constant folding pass
- Throw exception instead of returning nullptr in unimplemented copy_to/copy_from methods
- Added extra alloc type check in `is_allocated_by` engine method to ensure that simple_attached_mem is not reported as engine's memory

[GPU] Allow simple attached mem as input memory for network

---

.ci/azure/linux_conditional_compilation.yml
.ci/azure/linux_cuda.yml
.ci/azure/windows_conditional_compilation.yml
conanfile.txt

- Ported https://github.com/openvinotoolkit/openvino/pull/19525

Aligned protobuf version in conanfile.txt with onnx recipe

---

.ci/azure/linux_cuda.yml
cmake/features.cmake

- Fixed order of dependent cmake options
- CVS-119550

Fixed order of dependent cmake options

---

src/plugins/intel_gpu/src/plugin/ops/constant.cpp
src/plugins/intel_gpu/src/plugin/ops/convolution.cpp

- Insert explicit permute primitive for deconv weights in all cases to simplify Constant op handling

[GPU] Add permute primitive instead of manual copy for deconv weights

---

src/frontends/pytorch/src/op/masked_fill.cpp

- *broad is an extra node in masked_fill mapping, which blocks the performance a lot, especially in llm of bloom series.*
- *eliminate broadcast node in masked_fill.*
- *119575*

[PT FE] eliminate broadcast node in masked_fill

---

src/bindings/python/wheel/CMakeLists.txt

- To try to build `manylinux_2_24_aarch64` from Debian 9 system.

Unlock custom creation of PLATFORM_TAG

---

src/plugins/intel_cpu/src/cpu_tensor.cpp

- With c++17 we cannot use `std::bind1st` because it's removed 
```
[ 85%] Building CXX object src/plugins/intel_cpu/CMakeFiles/openvino_intel_cpu_plugin.dir/src/dnnl_extension_utils.cpp.o
/Users/jenkins/w/prod-v2/bsr/2397/bacfb/p/openv277e958eae47e/s/src/src/plugins/intel_cpu/src/cpu_tensor.cpp:72:22: error: no member named 'bind1st' in namespace 'std'
std::bind1st(std::multiplies<size_t>(), m_element_type.size()));
~~~~~^
[ 85%] Building CXX object src/plugins/intel_cpu/CMakeFiles/openvino_intel_cpu_plugin.dir/src/dnnl_postops_composer.cpp.o
18 warnings and 1 error generated.
make[3]: *** [src/plugins/intel_cpu/CMakeFiles/openvino_intel_cpu_plugin.dir/src/cpu_tensor.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```
- Fixed cross-compilation from macOS arm64 to x86_64 for …

Fixed CPU plugin compilation

---

src/plugins/intel_cpu/src/infer_request.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/concat_reshape_concat.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/input_output_tensor_reuse.cpp

In this PR a more conservative condition of using the double buffering is applied. In this PR when the output blob is used as an input, the second buffer is always used. Though the solution is not perfectly optimal (there are still cases when just one buffer would be enough), it doesn't bring any coupling between the infer request and the graph levels, thus it's more reliable and robust to the graph level changes. In the most LLM applications the double buffering is applied anyway due to the topological specifics, so we doesn't lose much in terms of optimal memory use there.
A more elegant solution would be by far more complex and require developing auxiliary abstraction layers, so following the Pareto principle I decided to sacrifice some theoretical memory usage benefits in favor to …

[CPU] Fix input output tensor binding

---

src/plugins/intel_cpu/src/emitters/x64/jit_bf16_emitters.hpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/unit/jit_kernel_test.cpp

- Fix incorrect output for float to bf16 in avx2 isa
- 118588, 117486

Fix incorrect output for float to bf16 in avx2 isa

---

src/bindings/python/constraints.txt
src/bindings/python/wheel/requirements-dev.txt

- There are errors on some CI jobs (`openvino-lin` at https://github.com/openvinotoolkit/openvino/pull/19534 for example)
- It's most likely due to today's release of `setuptools` - https://pypi.org/project/setuptools/#history
- This PR is a hotfix for unblocking precommit while the issue is investigated
- N/A

[PyOV] Add upper bound for `setuptools`

---

docs/_static/images/torch_compile_backend_openvino.svg
docs/_static/images/torch_compile_backend_openvino_ts.svg

Port from https://github.com/openvinotoolkit/openvino/pull/19699
Image fix for torch.compile documentation as mentioned in https://github.com/openvinotoolkit/openvino/pull/19540#pullrequestreview-1617354770

[DOCS] Torch.compile() image fix for 23.1

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp

- Missed include for `std::string`
- *ticket-id*

Fixed GPU plugin compilation with gcc-13.2

---

src/plugins/intel_cpu/src/nodes/reference.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/custom_op_scalar.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/custom_op_zero_shape.cpp

- *`get_input_partial_shape` and input shape have different rank in the `evaluate` fn for custom node.*
- *113022*

[CPU] Scalar is passed as a tensor with shape [1] in custom op evaluate.

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_nd_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_nd_kernel_ref.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/gather_nd.cpp

- Fix the case where the calculation of `wi_slice`(the number of output data processed by 1 WI) is incorrect
- 116597, 118222

[GPU] Fix GatherND shape agnostic ref kernel

---

src/plugins/intel_gpu/src/graph/network.cpp

- Input layout is not updated before execution for dynamic shape
- Fix to get the updated output layout from dependency for dump layer
- *ticket-id*

[GPU] Minor fix to get correct input layout for dump layer

---

.github/workflows/linux_android_arm64.yml

- Sync with https://github.com/openvinotoolkit/openvino/commit/888d4e96332925c8cfe0528940682d53b7ccde2b

Added python3 vcpkg port dependecies to GHA workflow

---

src/plugins/intel_gpu/include/intel_gpu/op/fully_connected_compressed.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/fully_connected.hpp
src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/fully_connected.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bfyx_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bfyx_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/weight_bias_params.cpp
src/plugins/intel_gpu/src/kernel_selector/weight_bias_params.h
src/plugins/intel_gpu/src/plugin/ops/fully_connected.cpp
src/plugins/intel_gpu/src/plugin/program_builder.cpp
src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.cpp
src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.hpp
src/plugins/intel_gpu/src/plugin/transformations/op/fully_connected_compressed.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp

- merge after https://github.com/openvinotoolkit/openvino/pull/19539 
- Added FC compressed op
- Added transformation which converts FC with compressed weights subgraph into `FullyConnectedCompressed` operation
- Added compression support into fc_bfyx_ref and fc_bf_tiled kernels
- *118099*

[GPU] Support of int8 compressed weights for matmul

---

src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/border.hpp
src/plugins/intel_gpu/src/graph/border.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/border.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/border_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/border/border_kernel_base.h
src/plugins/intel_gpu/src/plugin/ops/pad.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/pad.cpp
src/plugins/intel_gpu/tests/unit/test_cases/border_gpu_test.cpp
src/tests/functional/plugin/shared/include/single_layer_tests/pad.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/pad.hpp
src/tests/functional/shared_test_classes/src/single_layer/pad.cpp
src/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/builders.hpp
src/tests/ngraph_helpers/ngraph_functions/src/pad.cpp

Ticket [CVS-117259](https://jira.devtools.intel.com/browse/CVS-117259)

[GPU] Pad-12

---

src/common/snippets/include/snippets/op/serialization_node.hpp
src/common/snippets/src/lowered/linear_ir.cpp
src/common/snippets/src/op/serialization_node.cpp
src/common/snippets/src/op/serialize_node.cpp

1. Serialization shapes are taken from expression instead of ov::Node
2. This PR changes LIR serialization logic: LoopBegin and LoopEnd serialization nodes are now connected with an additional edge.

[Snippets] LIR serialization: additional connections between LoopBegin and LoopEnd nodes

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/clamp.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/comparison.cpp
src/tests/functional/plugin/shared/include/single_op_tests/clamp.hpp
src/tests/functional/plugin/shared/include/single_op_tests/comparison.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/clamp.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/comparison.hpp
src/tests/functional/shared_test_classes/src/single_op/clamp.cpp
src/tests/functional/shared_test_classes/src/single_op/comparison.cpp

- Refactor ComparisonLayerTestand, ClampLayerTest to use SubgraphBaseTest

Refactor ComparisonLayerTest, ClampLayerTest

---

src/core/include/openvino/op/abs.hpp
src/core/reference/include/openvino/reference/abs.hpp
src/core/reference/include/openvino/reference/reduce_l1.hpp
src/core/src/op/abs.cpp

- Migrate Abs operator to new API.
- Move abs function from reduce_l1 to abs.
-  [CVS-118475](https://jira.devtools.intel.com/browse/CVS-118475)

[core]Migrate the Abs operator to new API

---

src/plugins/intel_gpu/thirdparty/CMakeLists.txt

- Ported https://github.com/openvinotoolkit/openvino/pull/19716
- It finally fixes Conan build on all OSes with oneDNN for GPU

Removed CMAKE_INSTALL_LIBDIR from oneDNN GPU configuration (#19716)

---

.github/workflows/linux_arm64.yml

- This PR introduces directories creation for `conan` build. It fixes [this failure](https://github.com/openvinotoolkit/openvino/actions/runs/6153126985/job/16696482886).

[CI] [GHA] Create directories for `conan` in ARM64 pipeline

---

.github/workflows/linux_arm64.yml

- This PR fixes [this failure](https://github.com/openvinotoolkit/openvino/actions/runs/6166196896/job/16735286398) by creating only a top-level build directory instead of a full path.

[CI] [GHA] Create only build directory for `conan` build

---

.ci/azure/linux_debian.yml
thirdparty/onnx/CMakeLists.txt

- Backported https://github.com/openvinotoolkit/openvino/pull/17765/files#diff-ebc4deac8d5d3651526e727a62f01bcb07424c49c9ac1c1f74071715f7c3ce10R68
- Adjusted CI to check the fix is working
- Closes https://github.com/openvinotoolkit/openvino/issues/19784

Fixed issue 19784

---

src/frontends/pytorch/src/op/one_hot.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_one_hot.py

- *Support aten::one_hot*
- *119340*

[PT FE] Support aten::one_hot

---

src/bindings/python/constraints.txt
src/bindings/python/wheel/requirements-dev.txt

- The setuptools bug which broke CI a few days a go has been fixed in the newest setuptools patch release: https://pypi.org/project/setuptools/68.2.2/
- N/A

[PyOV] Remove upper bound on `setuptools` and move wheel requirements under constraints

---

src/core/shape_inference/include/squeeze_shape_inference.hpp
src/core/tests/type_prop/squeeze.cpp
src/frontends/paddle/src/op/slice_ops.hpp

- *Fixes shape inference of Squeeze operation. Previously Squeeze of tensor with shape [1, 2, -1, 4] had output shape of [2, 4]. Now we recognize that dynamic dimensions may become 1 or may become another dimension. This is why with current changes such Squeeze would have output shape of dynamic rank*
- *Squeeze shape inference was previously altered to suite PDPD FE needs expressing unique behavior of Slice operation. I removed unnecessary change in the common Squeeze operation and put all the specifics of the PDPD operator in the translation rule*
- *CVS-119569*

Squeeze fix

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/build.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/performance.yml
.github/ISSUE_TEMPLATE/pre_release_feedback.yml

- There are some inconsistencies in our issue templates, such as placeholders about build issues in `documentation.yml`, typos or fields `value` which should rather be placeholders.
- Issue templates are one of the first things people who come to the repository might see, so they should be well maintained and clean.
- N/A

Clean up issue templates

---

src/plugins/template/src/config.cpp
src/plugins/template/src/config.hpp
src/plugins/template/src/plugin.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_executable_network/properties.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_executable_network/properties.cpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp

- *added faked props `ov::hint::inference_precision` `ov::hint::execution_mode` `ov::hint::num_requests`*
- *fixed default `perf_count` value, it is False now*
- *fixed test for property ov::hint::model_priority in apiConformance. Property was tested by core->get_property in apiConformance , but it is implemented as compiled_model property, so this test is removed now . Another existing test, where getting property tested with compiled_model->get_property, added to apiConformance scope. Test with setting this property will be added after with task CVS-109419*
- *CVS-103948*

[template] Add faked hint property

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/adaptive_pooling.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/batch_norm.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/batch_to_space.cpp
src/tests/functional/plugin/shared/include/single_layer_tests/adaptive_pooling.hpp
src/tests/functional/plugin/shared/include/single_op_tests/adaptive_pooling.hpp
src/tests/functional/plugin/shared/include/single_op_tests/batch_norm.hpp
src/tests/functional/plugin/shared/include/single_op_tests/batch_to_space.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/adaptive_pooling.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/batch_norm.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/batch_to_space.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/comparison.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/gru_sequence.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
src/tests/functional/shared_test_classes/src/single_op/adaptive_pooling.cpp
src/tests/functional/shared_test_classes/src/single_op/batch_norm.cpp
src/tests/functional/shared_test_classes/src/single_op/batch_to_space.cpp
src/tests/functional/shared_test_classes/src/single_op/comparison.cpp
src/tests/functional/shared_test_classes/src/single_op/gru_sequence.cpp

- Refactor AdaPool, BatchToSpace, and BatchNorm layer tests to use SubgraphBaseTest
- Gtest requires to have test fixture class name which is not equal to old class. That's why new tests are placed to new directory. This way we can use the same names and don't mix old and new tests together in Gtest

Refactor AdaPool, BatchToSpace, and BatchNorm shared tests

---

tests/constraints.txt

**Details:** Add upper bound for jax dependencies. The newest release of JAX from Sep. 19 introduced not backward compatible changes. 

[TF FE][JAX] Add upper bound for jax dependencies

---

src/bindings/c/src/CMakeLists.txt
src/bindings/c/src/common.h

- *item1*
- *...*
- *ticket-id*

Disable clang-format for legacy C API

---

src/plugins/template/src/plugin.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_executable_network/get_metric.cpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp

- *added ov::device::type  ov::execution_devices*
- *removed tests for optimal_number_of_infer_requests and model_name with core->get_property, moved tests for these props with compile_model->get_property to mandatory scope*
- *CVS-103948*

[template] Add some ro props and fix props test

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/convolution.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/convolution_backprop_data.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/deformable_convolution.cpp
src/tests/functional/plugin/shared/include/single_op_tests/convolution.hpp
src/tests/functional/plugin/shared/include/single_op_tests/convolution_backprop_data.hpp
src/tests/functional/plugin/shared/include/single_op_tests/deformable_convolution.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/convolution.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/convolution_backprop_data.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/deformable_convolution.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
src/tests/functional/shared_test_classes/src/single_op/convolution.cpp
src/tests/functional/shared_test_classes/src/single_op/convolution_backprop_data.cpp
src/tests/functional/shared_test_classes/src/single_op/deformable_convolution.cpp

- Refactor ConvolutionBackpropDataLayerTest, ConvolutionLayerTest, DeformableConvolutionLayerTest
- Temporary disable some cases CVS-120413

Refactor ConvolutionBackpropDataLayerTest, ConvolutionLayerTest, DeformableConvolutionLayerTest

---

src/core/include/openvino/op/logical_xor.hpp
src/core/include/openvino/op/xor.hpp
src/core/reference/include/openvino/reference/xor.hpp
src/core/src/op/xor.cpp

- Migrate `LogicalXor` operator (v0, v1) to new API. Remove legacy, headers, functions, includes. Modify for bin size reduction.
- Update the reference implementation to reduce binary size.
- [CVS-118685](https://jira.devtools.intel.com/browse/CVS-118685)

[core] API 2.0/Migrate LogicalXor to new API

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

Skip failed `TensorIteratorTest` and `CTCGreedy*` CPU f16 tests on Mac

---

tests/stress_tests/common/ie_pipelines/pipelines.cpp
tests/stress_tests/common/ie_pipelines/pipelines.h
tests/stress_tests/memleaks_tests/tests.cpp
tests/stress_tests/scripts/get_testdata.py

- Because `ie_wrapper` was captured by reference, tests actually execute only last model instead of several models

Fix `StressMemLeaksTests` with several models

---

src/common/transformations/src/transformations/smart_reshape/matmul_sr.cpp
src/inference/tests/functional/matmul_sr_tests.cpp

- *ReshapeAMatMul & ReshapeBMatMul: fixed the case when `shape_source` rank is not equal to `reshape_rank`*
- *CVS-119625*

SmartReshape: ReshapeMatMul transformations are fixed

---

src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp
src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/kernel_impl_params.cpp
src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
src/plugins/intel_gpu/tests/unit/fake_alignment/fc_fake_alignment_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp

- fc : fake alignment for 16 is better in iGPU.
- Gemm : permute + gemm_tiled_opt is better than transposed_input + gemm_ref kernel for unaligned shapes to 16. Note that this is an temporal optimization and will be removed once the final solution (i.e., support unaligned transposed input shape in gemm_tiled_opt kernel) is availalbe.
- 119570
- 118755

[GPU] Optimization for gemm & fc in iGPU.

---

src/frontends/pytorch/src/op/min_max.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_min_max.py

- *support aten::maximum and aten::minimum operators*
- *119961,*

[PT FE]: support aten::minimum aten::maximum

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/nodes/eltwise.cpp

- Eltwise order of the supported primitive descriptors affects the
performance of the model.
Often only one of the port descriptors matches with the layout
of the parent descriptors, i.e. when two parent ports have mixed
layout "nchw nhwc".
So either nchw or nhwc layout will be used for the eltwise node
and reorder will be used for either of the ports.
The shape of the ports also can be different (when one of the inputs is
broadcasted). So reorders on different ports have different
performance impact.
- The layout of the eltwise node child has an effect on the performance
as well, since it may or may not require reorder on input.
- 118088

[CPU][ARM] Choose eltwise layout based on model type

---

src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h

- Basically move weights reordering from first inference to compile_model
- *ticket-id*

[CPU][ARM] Reorder FullyConnected weights in scope of compile_model

---

src/frontends/pytorch/src/op/logical.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_logical_ops.py

- *added support aten::logical_and, aten::logical_or, aten::logical_not, aten::logical_xor*
- *ticket-id*

[PT FE]: extend logical operations support

---

src/plugins/intel_gpu/include/intel_gpu/plugin/program_builder.hpp
src/plugins/intel_gpu/src/plugin/ops/constant.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/shared_constant.cpp

- It seems that several constant with different element types may point to the same memory is some cases. Current `data` primitive reuse logic may lead to the data types mismatch, so we need to consider element type too in a cache key.

[GPU] Fix constants reuse

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/cpu_map_scheduling.cpp
src/plugins/intel_cpu/src/cpu_map_scheduling.hpp
src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_plugin/properties.cpp
src/plugins/intel_cpu/tests/unit/streams_info/streams_e2e_test.cpp

- *enable cpu pinning by setting command  '-pin YES' or '-pin CORE'*
- *ticket-id*

enable cpu pinning on Windows by setting property affinity CORE

---

docs/scripts/prepare_xml.py

- C++ API reference docs were not properly displayed (arguments missing or mixed with method/function name). This change resolves that issue.
- CVS-121041

use etree to fix docs generated by doxygen

---

src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/behavior/ov_plugin/properties.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/properties_tests.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp

- *move the ov::hint::inference_precision check to separate test. Now we check if property supported in general and if at least one precision is implemented. But if some precision is not maintained, it will not be a reason for the test to fail*
- *CVS-103948*

[apiConformance] Change test for ov::hint::inference_precision RW property

---

src/common/low_precision_transformations/src/pad.cpp
src/common/low_precision_transformations/tests/pad_transformation.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/pad_transformation.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/pad_transformation.cpp
src/tests/functional/plugin/shared/include/low_precision_transformations/pad_transformation.hpp
src/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/pad_function.hpp
src/tests/ngraph_helpers/lpt_ngraph_functions/src/pad_function.cpp

- Update LPT PadTransformation to support v12::Pad negative indexes
- Add unit test for negative and mixed cases
- 115474

LPT opset12::Pad negative indexes support

---

src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir.cpp
src/tests/test_utils/functional_test_utils/include/functional_test_utils/summary/op_summary.hpp
src/tests/test_utils/functional_test_utils/include/functional_test_utils/summary/summary.hpp
src/tests/test_utils/functional_test_utils/src/summary/op_summary.cpp

- *Provide rel_all && rel_passed based on TEST_P cnt to avoid 300% passrate* 
CC @andrei-kochin

[CONFORMANCE] Provide correct numbers for rel_passed && rel_all

---

src/bindings/c/include/openvino/c/openvino.h
src/bindings/c/tests/ov_windows_conflict_test.cpp

- Fix conflict of "BOOLEAN", after include header file "Windows.h"
- 117890

[C API] Fix the BOOLEAN in ov_element_type conflict with the typedefine in Windows.h

---

.github/workflows/linux.yml

- fixed regression issue when job can be cancelled by another job in post-commits, because github.ref is not unique in the master
- *TBD*

[GHA] concurrency fix

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/grn.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/group_convolution.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/group_convolution_backprop_data.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/gru_cell.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/single_op_tests/grn.hpp
src/tests/functional/plugin/shared/include/single_op_tests/group_convolution.hpp
src/tests/functional/plugin/shared/include/single_op_tests/group_convolution_backprop_data.hpp
src/tests/functional/plugin/shared/include/single_op_tests/gru_cell.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/grn.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/group_convolution.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/group_convolution_backprop_data.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/gru_cell.hpp
src/tests/functional/shared_test_classes/src/single_op/grn.cpp
src/tests/functional/shared_test_classes/src/single_op/group_convolution.cpp
src/tests/functional/shared_test_classes/src/single_op/group_convolution_backprop_data.cpp
src/tests/functional/shared_test_classes/src/single_op/gru_cell.cpp

- Refactor GrnLayerTest, GroupConvBackpropLayerTest, GroupConvolutionLayerTest, GRUCellTest
- f16 and f32 tests for GroupConvBackpropLayerTest tests with defined output padding are disabled until fixed CVS-121313

Refactor GrnLayerTest, GroupConvBackpropLayerTest, GroupConvolutionLayerTest, GRUCellTest

---

.github/workflows/android_arm64.yml

- Both ccache and vcpkg cache for binary artifacts
- CVS-121640

Enable caches for Android ARM64 build

---

src/frontends/pytorch/src/input_model.cpp
src/frontends/pytorch/src/op/cat.cpp
tests/layer_tests/pytorch_tests/test_linear.py

- *Fix issue when cat input is folded to tensor: if `prim::ListConstruct` has all inputs as constants with compatible sizes they  will be merged into a single tensor by adding additional dim - 0. `aten::cat` translation needs to be updated to expect such inputs.*
- *121627*

[PT FE] Fix issue when cat input is folded to tensor

---

src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_yx_fsv_16_32_imad_dw.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_mmad_int8.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_mmad_int8_slm.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp

- Add handling of unsupported simd8 for PVC (the issue originally happened with gemm_kernel_tiled_opt kernel)
- *ticket-id*

[GPU] Add handling of unsupported simd8 for PVC

---

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

- This PR prohibits usm_host memory buffers usage as a device inputs since sometimes it causes significant perf degradations 
- 121649

[GPU] Do not use usm_host memory buffers for PVC as a device inputs

---

docs/dev/build_windows.md

Providing easier to read placeholders for installation path of OpenVINO in build instructions.
Closes https://github.com/openvinotoolkit/openvino/issues/20097

[DOCS] Easy to read placeholders in build instructions

---

docs/dev/build_windows.md

Providing easier to read placeholders for installation path of OpenVINO in build instructions.
Closes https://github.com/openvinotoolkit/openvino/issues/20097
Porting: https://github.com/openvinotoolkit/openvino/pull/20126

[DOCS] Easy to read placeholders in build instructions for 23.1

---

docs/dev/build_windows.md

Providing easier to read placeholders for installation path of OpenVINO in build instructions.
Closes https://github.com/openvinotoolkit/openvino/issues/20097
Porting: https://github.com/openvinotoolkit/openvino/pull/20126

[DOCS] Easy to read placeholders in build instructions for 23.0

---

src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp

- This PR fixes fully_connected_gpu_imad (and all other kernels which use this format) accuracy issue caused by incorrect formats matching
- 121175

[GPU] Fix os_is_yx_osv16_isv4 weights format matching

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

These PRs that are part of migration activity fail some Conversion, GRUCell and Eltwise tests on Apple M1 and Raspberry:
https://github.com/openvinotoolkit/openvino/pull/19777
https://github.com/openvinotoolkit/openvino/pull/19922
https://github.com/openvinotoolkit/openvino/pull/20026
As was discussed with @olpipi (migration activity author) it makes sense to disable failed tests temporary until migration activity is finished.
As soon as it's finished skipped tests should be fixed and enabled. 
- 121173
- 121295

[CPU][ARM] Skip tests affected by in-completed tests migration to new API

---

samples/cpp/build_samples_msvc.bat

At least in some environments build_samples_msvc.bat may exit with a zero exit code even in case of an error. This PR fixes that behavior by setting an exit code explicitly if error occurs
- 121769

[build_samples_msvc] Exit properly on error

---

docs/resources/release_notes.md

Port from https://github.com/openvinotoolkit/openvino/pull/20113
Update for the Release Notes article to link to the 23.1 release notes.

[DOCS] Release Notes version update for 23.1

---

src/plugins/intel_gpu/src/plugin/ops/custom.cpp
src/plugins/intel_gpu/tests/functional/CMakeLists.txt
src/plugins/intel_gpu/tests/functional/custom_op/custom_op.cl
src/plugins/intel_gpu/tests/functional/custom_op/custom_op.cpp
src/plugins/intel_gpu/tests/functional/custom_op/custom_op.xml

- Currently graph created for custom op may be incorrect as reorder primitive added after custom op is not connected with subsequent ops properly.

[GPU] Fix GPU custom layer handling

---

src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_redundant_reorder_at_runtime.cpp

- This patch prevents incorrect memory reuse issue caused by runtime reorders optimization by adding new `_runtime_memory_dependencies` which can be modified during model execution
- 121175

[GPU] Fix runtime reorders optimization and add runtime memory dependencies

---

src/plugins/intel_cpu/src/nodes/subgraph.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp

- *Fixed the order of registration CPU specific transformations for data flow: `EnforcePrecision` should be executed after `MatMulToBrgemm`*
- *119707*

[CPU][Snippets] Fixed EnforcePrecision pass registration

---

src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp

- *Keep precision of inputs/outputs in SubgraphBaseTest::calculate_refs otherwise it leads to precision mismatch for f16*
- *ticket-id*

Keep precision of inputs/outputs in SubgraphBaseTest::calculate_refs

---

docs/nbdoc/consts.py
docs/nbdoc/nbdoc.py

Creating a direct link to a specific notebook in the `openvino_notebooks` Github repository.
This PR addresses Jira ticket: 121735

[DOCS] Direct Github link to a specific notebook

---

src/bindings/python/wheel/setup.py

- Use RPATH instead of RUNPATH for wheel package
- Closes https://github.com/openvinotoolkit/openvino/issues/20217

Use RPATH instead of RUNPATH for wheel package

---

.github/workflows/linux.yml
.github/workflows/windows.yml

[CI] [GHA] Refactor Win pipeline: split the `Build` job, remove unnecessary requirements installation

---

docs/nbdoc/consts.py
docs/nbdoc/nbdoc.py

Creating a direct link to a specific notebook in the `openvino_notebooks` Github repository.
This PR addresses Jira ticket: 121735
Porting:
https://github.com/openvinotoolkit/openvino/pull/20248

[DOCS] Direct Github link to a specific notebook for 23.1

---

docs/nbdoc/consts.py
docs/nbdoc/nbdoc.py

Creating a direct link to a specific notebook in the `openvino_notebooks` Github repository.
This PR addresses Jira ticket: 121735
Porting: https://github.com/openvinotoolkit/openvino/pull/20248

[DOCS] Direct Github link to a specific notebook for 23.0

---

src/common/transformations/src/transformations/convert_precision.cpp
src/common/transformations/tests/utils/convert_precision.cpp

- *Add missing rtinfo copy in ConvertPrecision transformation*
- *ticket-id*

[nGraph Transformations] Add missing rtinfo copy in ConvertPrecision transformation

---

src/bindings/python/constraints.txt
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/ones_like.cpp
tests/constraints.txt
tests/layer_tests/common/tflite_layer_test_class.py
tests/layer_tests/tensorflow_lite_tests/test_tfl_FullyConnected.py
tests/layer_tests/tensorflow_tests/test_tf_OnesLike.py
tools/mo/requirements_tf.txt
tools/mo/requirements_tf2.txt

**Details:** Support TF 2.14 and add OnesLike translator. TF 2.14 requires OnesLike since RNN ops use this operation in the decomposition

[TF FE] Support TF 2.14 and add OnesLike translator

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *CPU Plugin Subgraph supports BRGEMM only with precisions `f32`, `bf16`, `i8`. If precision is `f16`, MHA should be executed with this precision as separate node set on plugin side. Thus, the PR enabled MHA tokenization only with infer precision `f32`, `bf16`*
- *N/A*

[Snippets][CPU] Disabled MHA tokenization with infer precision f16

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml
src/bindings/python/tests_compatibility/test_onnx/test_backend.py
src/frontends/onnx/tests/tests_python/test_backend.py

Reverts openvinotoolkit/openvino#20367

Revert "[CI] [GHA] Skip `test_div_uint8_cpu` on macOS only; unskip `test_onnx/test_backend.py` in GHA workflows"

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/normalize.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/data_utils.hpp

- Currently used `std::is_signed` always returns false for custom type (such as `ov::float16`) so we always have positive range generated for fp16 tensors which could increase representation error due to larger absolute values in accumulators/out tensors.
- cpp spec says `The behavior of a program that adds specializations for std::is_signed or std::is_signed_v is undefined.` while specializations for numeric_limits are allowed and we already have specializations for `float16` and `bfloat16`, so this PR switches to numeric_limits usage

[TESTS] Fix random generator for custom signed types

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/skip_configs/CPU/expected_failures_OP.csv

- *is sporadically killed by timeout:*
```
[ RUN      ] conformance_Convolution/ReadIRTest.Inference/Op=Convolution.1_Type=f32_IR=c301804445f273eef62f41f02204711d9d6e571da28c76ab447d7d90983b0032_Device=CPU_Shape=dynamic_Config=()
MEM_USAGE=53196KB
[ CONFORMANCE ] Influence coefficient: 0.000113281
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is started
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is finished successfully. Duration is 0.0524182s
[ REFERENCE   ] `SubgraphBaseTest::calculate_refs()` is started
[ REFERENCE   ] Calculate reference in runtime
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is started
[ PLUGIN      ] `SubgraphBaseTest::get_plugin_outputs()` is finished successfully. Duration is 0.0512713s
[ REFERENCE   ] …
```

[CONFORMANCE][PRECOMMIT] Add one sporadically interapted test to expected failures

---

samples/cpp/CMakeLists.txt

- Once this PR is merged, we don't need a check anymore https://github.com/conan-io/conan-center-index/pull/20420

Removed check for openvino::runtime::c in samples

---

src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py

- *Commit slider could have troubles writing to stdout non-unicode characters that it failed to decode. This patch fixes this behavior, so the non-decodable characters will be replaced with "?" now.*
- *-*

Improve Commit slider's handling of non-decodable characters

---

docs/nbdoc/consts.py
docs/nbdoc/nbdoc.py

Creating a direct link to a specific notebook in the `openvino_notebooks` Github repository.
This PR addresses Jira ticket: 121735
Porting:
https://github.com/openvinotoolkit/openvino/pull/20248

[DOCS] Direct Github link to a specific notebook for 22.3

---

src/plugins/intel_gpu/docs/memory_allocation_gpu_plugin.md

OV_GPU_Verbose should be 2 instead of 1 to dump memory info.

Small fix for GPU memory allocation documentation

---

src/core/include/openvino/op/logical_and.hpp
src/core/reference/include/openvino/reference/and.hpp
src/core/src/op/logical_and.cpp

- Migrate `LogicalAnd` to new API, remove old classes, namespaces, functions.
- Minor refactor of operator and reference implementation to reduce binary size.
- [CVS-118617](https://jira.devtools.intel.com/browse/CVS-118617)

[core]Migrate LogicalAnd to new API

---

src/core/include/openvino/op/logical_or.hpp
src/core/reference/include/openvino/reference/or.hpp
src/core/src/op/logical_or.cpp

- Migrate `LogicalOr` to new API, remove old classes, namespaces, functions.
- Minor refactor of operator and reference implementation to reduce binary size.
- [CVS-118620](https://jira.devtools.intel.com/browse/CVS-118620)

[core]Migrate LogicalOr to new API

---

src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/kernel_selector/kernel_base_opencl.cpp

- Added additional suffix `__sa` for shape agnostic kernels names for better clarity in profiling software:
```
/* Previous */
reorder_data_14821491574453208146_0,      1,      12700052,    0.15%,      12700052,      12700052,      12700052
reorder_data_16385396756226318839_0,     64,        193201,    0.00%,          3018,          1822,         12031
/* Now */
reorder_data_14821491574453208146_0,      1,      12700052,    0.15%,      12700052,      12700052,      12700052
reorder_data_16385396756226318839_0__sa,     64,        193201,    0.00%,          3018,          1822,         12031
```
- Added dump of `cl dump_ info` for `impl_types::any`, since `impl_types::any` implementation type may be associated with cldnn kernels as well
- *ticket-id*

[GPU] Minor debug fixes

---

src/plugins/intel_gpu/src/graph/scatter_nd_update.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/scatter_nd_update_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_nd_update_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/tensor_type.h
src/plugins/intel_gpu/tests/unit/test_cases/scatter_nd_update_gpu_test.cpp

- Fix input index calculation in scatter_nd_update kernel (for padded case input and output indexes are not the same)
- Allow to run only first stage of scatter_nd_update (copy stage) if `indices` or `updates` inputs are emtpy, but data modification is needed
- 118222

[GPU] Fix scatter_nd_update output paddings handling

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/skip_configs/CPU/expected_failures_OP.csv

Opset13 was enabled in https://github.com/openvinotoolkit/openvino/pull/20005
@mitruska Please, extend the conformance OP `expected_failures` in case of a new operation enabling and merge please latest master to the branch to have recently enabled checks in GHA:)
@dmitry-gorokhov Please remove the tests from the list in case of fix something from `expected_failures` list
@akashchi @ilya-lavrenov The PR as a point to enable merge queue :) 
CC @nshchego as first affected person

[CONFORMANCE][CPU] Add Expected failures for CPU Opset13 OP

---

src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/fusions/deconvolution_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/fusions/eltwise_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/fusions/fusion_test_common.hpp
src/plugins/intel_gpu/tests/unit/fusions/gemm_fusion_test.cpp

- *Previously, get_mem() method for f16 generated only three values: float16((uint16_t)x), where x = 0, 1, 65535/8*
- 94154

[GPU] Fixed data generation for f16 fusion tests

---

docs/dev/cmake_options_for_custom_compilation.md

Remove TREAT_WARNING option from the doc

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp

In this PR, f16 decompression support is provided through f16->f32 decompression constants conversion. Support without additional conversion will be provided in next PR
- *CVS-119180*

[CPU] Weights compression: f16 decompression support

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- Disable NormalizeL2LayerTest and NonZeroLayerTest f16 tests on MacOs Arm64
- CVS-122699

Disable NormalizeL2LayerTest and NonZeroLayerTest f16 tests on MacOs Arm64

---

src/plugins/intel_gpu/include/intel_gpu/primitives/gather.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp
src/plugins/intel_gpu/src/graph/include/layout_optimizer.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
src/plugins/intel_gpu/src/plugin/ops/gather.cpp
src/plugins/intel_gpu/tests/unit/fusions/gather_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/module_tests/primitive_comparison_test.cpp
src/plugins/intel_gpu/tests/unit/passes/add_required_reorders_test.cpp
src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
src/plugins/intel_gpu/tests/unit/passes/remove_redundant_reorders_tests.cpp
src/plugins/intel_gpu/tests/unit/passes/reorder_inputs_test.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/gather_si_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/canonicalization_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gather_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp

- because the parameters as indices, batch_dims and axis depend on the rank.
- add input_shape to gather primitive.

[GPU] Gather needs to keep the original input/output rank

---

src/frontends/onnx/tests/skip_tests_config.cpp
src/frontends/paddle/tests/skip_tests_config.cpp

- `BUILD_SHARED_LIBS` is not correct check in C++ files.

Enabled FrontendLibCloseTest FE test suite

---

src/core/include/openvino/op/constant.hpp

- *Clearer error message in the Constant::cast_vector*
- *CVS-121479*

Clear error message in the Constant::cast_vector

---

src/core/src/op/range.cpp
src/core/tests/eval.cpp

- GPU plugin uses Range4::evaluate with fp16 output data type and current impl casts range parameters to output type even for output shape calculation. That may lead to mismatch between shape produced by `range_shape_infer()` and actual size of tensor specified by reference implementation. That issue causes crash for LLMs with large context size.
- This patch changes start/stop/step initial data type to double for correct out shape compute, and then those values are converted into target data type.
- Minor evaluate_power -> evaluate_range rename

Fixed ngraph reference impl for Range operation

---

src/plugins/intel_cpu/src/nodes/tensoriterator.cpp
src/plugins/intel_cpu/src/nodes/tensoriterator.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/loop.cpp

There is a special case when a TI node has all the static shapes while the subgraph is dynamic. In that case the existing implementation can't run it properly. So a special treatment for this configuration has been introduced.
- 122993
- 123110

[CPU] Make static TI run a dynamic subgraph

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Improve OOOQ synchronizations between ShapeOf subgraph's CPU impls and GPU kernels
- Add ITT markup for primitive_inst
- 112408

[GPU] Improve OOOQ synchronization between ShapeOf subgraph's CPU impls and GPU kernels

---

src/plugins/intel_gpu/src/plugin/compiled_model.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/behavior/plugin/configuration_tests.cpp

- This PR fixes to create `Graph`s with different `stream_id`s when deserializing them for multiple streams.
- 123287

[GPU] fixed to create Graphs with different stream_ids

---

src/inference/include/openvino/runtime/intel_gpu/ocl/dx.hpp
src/inference/include/openvino/runtime/intel_gpu/ocl/ocl.hpp
src/inference/include/openvino/runtime/intel_gpu/ocl/va.hpp
src/plugins/intel_gpu/tests/functional/remote_blob_tests/gpu_remote_tensor_tests.cpp

- `create_tensor_nv12` helpers didn't work after plugin API 2.0 impl due to new shape compatibility checks added. This PR fixes surface shape to match expected dims order.
- *123049*

[GPU] Fixed surfaces shape in create_tensor_nv12 helpers

---

src/inference/dev_api/ie_ngraph_utils.hpp
src/plugins/intel_cpu/src/dnnl_extension_utils.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer.h
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp
src/tests/ov_helpers/ov_models/include/ov_models/builders.hpp

- This PR adds runtime acceleration for LLMs with compressed weights on x86 CPUs
-- Supported cases:
--- nodes: FullyConnected
--- weights compression: i4/u4/nf4
--- isa: avx2, avx512
- Additionally this PR improves performance of existing u8 weights decompression algorithm
- OneDNN PR: https://github.com/openvinotoolkit/oneDNN/pull/216
- Some corner cases fixes
- AMX support (can be done in separate PR)
- https://github.com/openvinotoolkit/openvino/pull/20371
- https://github.com/openvinotoolkit/openvino/pull/20503
- *[CVS-119154](https://jira.devtools.intel.com/browse/CVS-119154)*

[CPU] FullyConnected acceleration with 4bit weights decompression

---

cmake/dependencies.cmake

- *Update Linux oneTBB with version 2021.2.4*
- *Fix the LLM perf regression on LLM*
- *ticket-id*

Update linux oneTBB with version 2021.2.4

---

.github/workflows/linux_riscv.yml

- Example of canceled pipeline with over 15 minutes in length on a PR: https://github.com/openvinotoolkit/openvino/actions/runs/6651036317/job/18072259304

[CI] [GHA] Increase timeout for RISC-V workflow

---

src/bindings/python/src/openvino/runtime/utils/decorators.py
src/bindings/python/tests/test_graph/test_reduction.py

- allow to use `node` as keyword argument
- CVS-105065

[PyOV] fix set_node_friendly_name

---

src/core/src/runtime/itensor.cpp
src/core/tests/tensor.cpp
src/inference/src/dev/make_tensor.cpp
src/plugins/intel_gpu/src/plugin/remote_tensor.cpp
src/plugins/template/src/remote_context.cpp

Fixed issue: tensor shape={0,0,0,0} will get strides={0,0,0,4} or {0,0,0,8}, actually it should be {0,0,0,0} 
- *ticket-id*

Fix stride issue for ZeroDims

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/program_builder.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/compilation_context.hpp
src/plugins/intel_gpu/src/graph/compilation_context.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/plugin/ops/condition.cpp
src/plugins/intel_gpu/src/plugin/ops/loop.cpp
src/plugins/intel_gpu/src/plugin/program_builder.cpp
src/plugins/intel_gpu/tests/unit/module_tests/kernel_impl_params_relevance_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp

- Unique compilation context in each cldnn::program caused huge perf drop for dynamic models with sub-networks (with `If` or `Loop` operations) due to many host threads spawned for async kernels compilation tasks which consumed all CPU resources. 
- This PR changes compilation context creation logic in a similar way to task executor, so single context is used for the whole model.

[GPU] Share compilation context with sub-networks

---

src/common/snippets/src/pass/align_element_types.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp

- *Note that the Snippets have limitation: `Transpose` ops must be only after `Parameter` or before `Result`. Moreover, `Transpose` is supported only via `FuseTransposeToBrgemm` or `TransposeDecomposition`. To fuse `Transpose` into `Brgemm` there shouldn't be ops between `Transpose` and `Brgemm`*
- *When CPU Plugin enforce bf16 precision for f32 body,  `AlignElementTypes` insert `Convert[bf16->f32]` ops after `Parameter` to align input precisions of bodies (If there is `Transpose`, the pass inserts after `Parameter->Transpose`). Then the pass `EnforcePrecisions` inserts `Convert[f32->bf16]` before `Brgemms` to allow `Brgemm` be executed in `bf16`. These `Converts` are eliminated in the pass `EnforcePrecision` since they're redundant. However, the order of pases `AlignElementTypes` and …

[Snippets] Fixed Convert elimination in AlignElementType

---

src/bindings/c/src/CMakeLists.txt
src/common/preprocessing/tests/CMakeLists.txt
src/core/src/type.cpp
src/frontends/onnx/frontend/src/ops_bridge.hpp
src/inference/src/dev/make_tensor.cpp

- Fixed compilation with C++23 for core components
- Replaced `ov_deprecated_no_errors` with `ov_disable_deprecated_warnings` for deprecated components, because we don't plan to fix them

Fixed compilation with C++23

---

src/plugins/intel_gpu/src/graph/condition.cpp
src/plugins/intel_gpu/src/graph/impls/common/condition.cpp
src/plugins/intel_gpu/tests/unit/test_cases/condition_gpu_test.cpp

- condition primitive used memory in/out layouts which could be invalid from shape inference standpoint due to memory preallocation feature. This patch adds buffer reinterpret calls for input/output memory buffers in condition to 
- *123624*

[GPU] Adjust in/out layouts in condition prim to handle prealloc

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *Disabled SplitDimensionM CPU Func tests that are sporadic failed because of there is not enough thread count on testing machine*
- *[Example](https://github.com/openvinotoolkit/openvino/actions/runs/6667202715/job/18120713755) of failed tests*

[Snippets][CPU] Disabled SplitDimensionM CPU Func tests

---

docs/install_guides/installing-openvino-from-archive-windows.md

Fixing instructions in the `Install OpenVINO™ Runtime on Windows from an Archive File` article.
Porting:
https://github.com/openvinotoolkit/openvino/pull/20752

[DOCS] Fixing instructions for archive windows installation

---

.github/workflows/linux.yml
tests/model_hub_tests/torch_tests/test_hf_transformers.py

- *300 minutes is 5 hours, tests run slightly more, increase timeout to 400 which is higher then 6 hours internal timeout in GHA*
- *ticket-id*

Increase timeout for hub tests

---

src/frontends/paddle/src/frontend.cpp
src/frontends/paddle/tests/read_paddle_model_test.cpp

- *support model in ov::tensor format*
- *121052*
- https://github.com/openvinotoolkit/openvino/issues/19833

[PD FE] loading weight from ov::tensor

---

src/frontends/tensorflow_common/src/op/ctc_loss.cpp
tests/layer_tests/tensorflow_tests/test_tf_CTCLoss.py

**Details:** Fix CTCLoss translator. It helps to fix inference issue on one CTC model.

[TF FE] Fix CTCLoss translator

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/matmul_sparse.cpp

We get a segfault when using the **Sparse weights decompression feature** for large weights due to an overflow of the int16_t type, which is used to store comp tile len data.
PR to OneDNN fork: https://github.com/openvinotoolkit/oneDNN/pull/218
https://jira.devtools.intel.com/browse/CVS-122817

[CPU] Sparse weights decompression feature: changed comp_tile_len data type from int16_t to int

---

src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
src/plugins/intel_gpu/tests/unit/test_cases/reshape_gpu_test.cpp

- *In case reshape has an reorder user which truncation mode is true, the reorder should not be splited.*
- *110907*

[GPU] Fix handle reshape not to be applied for type conversion reorder user

---

docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-vcpkg.md

- This WA is not required anymore, because build with dynamic protobuf has been recently (almost) fixed
- We need to port it to 2023.1 as well

Removed WA for static protobuf for vcpkg installation path

---

src/common/transformations/src/transformations/smart_reshape/matmul_sr.cpp
src/inference/tests/functional/matmul_sr_tests.cpp

SmartReshape fix: avoid circular dependencies creation in ReshapeBMatMul and ReshapeAMatMul

---

src/core/include/openvino/op/sigmoid.hpp
src/core/reference/include/openvino/reference/sigmoid.hpp
src/core/src/op/sigmoid.cpp

- Migrate Sigmoid operator to new API, remove legacy classes, namespaces, includes.
- Refactor reference to reduce binary size.
- [CVS-118654](https://jira.devtools.intel.com/browse/CVS-118654)

[core]Migrate Sigmoid operator to new API

---

src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/reference.cpp
src/plugins/intel_cpu/src/nodes/reference.h
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/custom_op_scalar.cpp

- *Reference node was not executed if one of input tensor was empty.*
- *113021*

[CPU] Empty tensor used with a custom op leads to CPU plugin exception.

---

src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
src/common/transformations/tests/common_optimizations/simplify_second_input_of_reshape_test.cpp

SimplifySecondInputOfReshape detects ShapeOf->Gather->Concat subgraphs on Reshape's second input and replaces ShapeOf->Gather with a Constant with zero(s). Currently it works only with Reshapes that have special_zero set to true, but it can work for Reshapes with `special_zero == false` if non-Gather inputs to Concat are Constants and don't contain any zero.
Now for  `special_zero == false` case,  the transformation checks that all inputs Constants to Concat don't contain 0 values and sets `special_zero = true` flag to Reshape operation.
Ticket: CVS-123434

Handle Reshape's special zero in SimplifySecondInputOfReshape

---

src/plugins/intel_cpu/src/graph_optimizer.cpp

- This PR fixes port matching logic inside `FuseEltwiseAndSimple` graph optimization pass

[CPU] Fixed port mismatch in Eltwise fusion graph optimization

---

tools/ovc/openvino/tools/ovc/convert_impl.py

Description: 
Removed WA with double loading of FE in OVC, as the problem from 115994 does not reproduce anymore.
Ticket: 116177
Code:
Validation:
Documentation:

Remove WA with double loading of FE in OVC.

---

src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/op_support.py
src/frontends/pytorch/src/op/batch_norm.cpp
src/frontends/pytorch/src/op/cat.cpp
src/frontends/pytorch/src/op_table.cpp

Fixed issue with cat in fx backend that was causing perf degradation
Added new op batch_norm_legit_no_training which was introduced in Pytorch 2.1.0 which is just batch_norm op with no training argument
- https://jira.devtools.intel.com/browse/CVS-124095

Fixed issue with cat in fx backend

---

src/core/include/openvino/op/floor.hpp
src/core/reference/include/openvino/reference/floor.hpp
src/core/src/op/floor.cpp

- Migrate `Floor` operator to new API, remove legacy headers, classes namespace.
- Move reference logic selection into Floor reference implementation.
- [CVS-118584](https://jira.devtools.intel.com/browse/CVS-118584)

[core]Migrate Floor operator to new API

---

docs/articles_en/openvino_workflow/model_preparation/Convert_Model_From_TensorFlow.md

Description: 
- Added hub.load() example
- Moved TF function example to the top of the list
Ticket: 124070
Code:
Validation:
Documentation:

[DOC] Update list of TF formats imported from memory.

---

src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
src/common/transformations/tests/common_optimizations/simplify_second_input_of_reshape_test.cpp

* Handle Reshape's special zero in SimplifySecondInputOfReshape
Port (#20785) to Release branch
SimplifySecondInputOfReshape detects ShapeOf->Gather->Concat subgraphs on Reshape's second input and replaces ShapeOf->Gather with a Constant with zero(s). Currently it works only with Reshapes that have special_zero set to true, but it can work for Reshapes with special_zero == false if non-Gather inputs to Concat are Constants and don't contain any zero.
Now for special_zero == false case, the transformation checks that all inputs Constants to Concat don't contain 0 values and sets special_zero = true flag to Reshape operation.
Ticket: CVS-123434

Handle Reshape's special zero in SimplifySecondInputOfReshape (#20785)

---

src/core/shape_inference/include/tensor_data_accessor.hpp
src/core/shape_inference/include/utils.hpp
src/core/shape_inference/src/tensor_data_accessor.cpp
src/core/tests/type_prop/eye.cpp
src/tests/functional/shared_test_classes/src/subgraph/mul_conv_fusion.cpp

- Drop support of `HostTensor` in `TensorAccessor` class.
- Use default `Tensor{}` instead of `make_tensor_accessor()` as it better optimize regarding the size.
- [CVS-121711](https://jira.devtools.intel.com/browse/CVS-121711)

Api 2.0/drop host tensor support in ta

---

docs/articles_en/learn_openvino/openvino_samples/cpp_sample_sync_benchmark.md
docs/articles_en/learn_openvino/openvino_samples/python_sample_sync_benchmark.md
samples/cpp/benchmark/sync_benchmark/main.cpp
samples/python/benchmark/sync_benchmark/sync_benchmark.py

Added device name as the second CLI parameter with default CPU value for sync benchmark sample
Corresponding changes for `throughput` benchmark: https://github.com/openvinotoolkit/openvino/pull/20816

Extend sync benchmark with device CLI parameter

---

docs/articles_en/learn_openvino/openvino_samples/cpp_sample_throughput_benchmark.md
docs/articles_en/learn_openvino/openvino_samples/python_sample_throughput_benchmark.md
samples/cpp/benchmark/throughput_benchmark/main.cpp
samples/python/benchmark/throughput_benchmark/throughput_benchmark.py

Added device name as the second CLI parameter with default CPU value for throughput benchmark sample

Extend throughput benchmark with device CLI parameter

---

src/bindings/python/src/openvino/frontend/tensorflow/utils.py
tests/layer_tests/mo_python_api_tests/test_mo_convert_tf.py
tests/layer_tests/ovc_python_api_tests/test_tf.py

Auto-generating of example inputs by user shapes leads to issues like inability to generate dynamically-shaped inputs. 
Solution: 
Provide example_input every time when it is required and remove logic of auto-generating of example inputs.
Ticket: 119701
Code:
Validation:
Documentation:

[TF FE] Removed logic of building example input by user shape in TF decoder.

---

src/core/include/openvino/op/floor_mod.hpp
src/core/reference/include/openvino/reference/floor_mod.hpp
src/core/src/op/floor_mod.cpp

- Migrate `FloorMod` operator to new API, remove old headers, classes namespaces
- Refactor reference implementation to reduce binary size
- Remove `visit_attributes` member function as implementation is same as base class.
- 
- [CVS-118583](https://jira.devtools.intel.com/browse/CVS-118583)

[core]Migrate FloorMod operator to new API

---

src/core/include/openvino/op/grid_sample.hpp
src/core/reference/include/openvino/reference/grid_sample.hpp
src/core/src/op/grid_sample.cpp

- Migrate `GridSample` to new API.
- Minor change reference implementation to reduce binary size and remove interpolate algorithm selection from main data processing loop.
- [CVS-118592](https://jira.devtools.intel.com/browse/CVS-118592)

[core]Migrate GridSample operator to new API

---

src/core/include/openvino/op/erf.hpp
src/core/reference/include/openvino/reference/erf.hpp
src/core/src/op/erf.cpp

- Migrate Erf to new API.
- Remove `visit_attributes` is same implementation as base class.
- Optimize reference implementation for binary size.
- [CVS-118560](https://jira.devtools.intel.com/browse/CVS-118560)

[core]Migrate Erf operator to new API

---

src/core/include/openvino/op/sign.hpp
src/core/reference/include/openvino/reference/sign.hpp
src/core/src/op/sign.cpp

- Migrate `Sign` operator to new API
- Refactor operator and reference implementation for size reduction.
- [CVS-118655](https://jira.devtools.intel.com/browse/CVS-118655)

[core]Migrate Sign operator to new API

---

src/core/include/openvino/op/matmul.hpp
src/core/src/op/matmul.cpp

- Migrate `MatMul` operator to new API.
- Minor refactor operator to reduce binary size.
- [CVS-118624](https://jira.devtools.intel.com/browse/CVS-118624)

[core]Migrate MatMul operator to new API

---

src/core/include/openvino/op/relu.hpp
src/core/reference/include/openvino/reference/relu.hpp
src/core/src/op/relu.cpp

- Migrate `ReLU` operator to new API.
- Refactor operator and reference implementation for size reduction.
- [CVS-118643](https://jira.devtools.intel.com/browse/CVS-118643)

[core]Migrate ReLU operator to new API

---

src/common/transformations/src/transformations/convert_precision.cpp
src/common/transformations/tests/utils/convert_precision.cpp

If model contains NMS node and being executed on ARM CPU with f16 inference precision then output precision issues may occur: `The plugin does not support I64` or `While validating node ABC type of then_body output i32 is not equal type of else_body output i64`
The issue happens because NMS node wrapped by `TypeRelaxed` is not overridden output types while i32/i64 conversion.
The suggested fix is to change the order of checks: `TypeRelaxed` check initially, i32/i64 check then and `TypeRelaxed` creation at the end.
- 123909
- 123910

[nGraph Transformations] NMS convert precisions - change sequence of checks

---

src/common/transformations/src/transformations/common_optimizations/lin_op_sequence_fusion.cpp
src/common/transformations/tests/common_optimizations/lin_op_sequence_fusion_test.cpp
src/core/src/op/multiply.cpp
src/plugins/template/tests/functional/op_reference/multiply.cpp

- Fix constant folding in `MultiplyMultiplyFusion` transformation by add support fo `f64` precision in `Multiply` operator. This precision in failing model in e2e tests.
- `MultiplyMultiplyFusion` don't apply transformation if `Multiply` is created for not supported type.
- [CVS-121150](https://jira.devtools.intel.com/browse/CVS-121150)

Fix constant folding in MulMulMulFusion

---

src/core/include/openvino/op/mish.hpp
src/core/reference/include/openvino/reference/mish.hpp
src/core/src/op/mish.cpp

- Migrate `Mish` operator to new API.
- Refactor operator and its reference implementation for size reduction.
- [CVS-118630](https://jira.devtools.intel.com/browse/CVS-118630)

[core]Migrate Mish operator to new API

---

src/core/include/openvino/op/exp.hpp
src/core/reference/include/openvino/reference/exp.hpp
src/core/src/op/exp.cpp

- Migrate `Exp` operator to new API.
- Minor refactor to reduce binary size.
- [CVS-118561](https://jira.devtools.intel.com/browse/CVS-118561)

[core]Migrate Exp operator to new API

---

docs/articles_en/get_started.md

Porting https://github.com/openvinotoolkit/openvino/pull/20881
Addressing JIRA ticket: 124289
Replacing the binder link with a direct link to the `Monodepth Estimation with OpenVINO` notebook.

[DOCS] Fixing link in Get Started article for 23.2

---

docs/get_started.md

Porting https://github.com/openvinotoolkit/openvino/pull/20881
Addressing JIRA ticket: 124289
Replacing the binder link with a direct link to the `Monodepth Estimation with OpenVINO` notebook.

[DOCS] Fixing link in Get Started article for 23.1

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/cum_sum_partial_sum.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/cum_sum/cum_sum_kernel_partial_sum.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/cum_sum/cum_sum_kernel_ref.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/cum_sum.cpp
src/plugins/intel_gpu/tests/unit/test_cases/cum_sum_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/permute_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/resample_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_utils/test_utils.cpp
src/plugins/intel_gpu/tests/unit/test_utils/test_utils.h

- fix cum_sum_partial_sum kernel;
- add unit test and func test for big dimensions;
- add test to compare Partial vs Ref performance;
- change kernels' priorities according to performance measurements;
- move common profiling helpers to test_utils.
Tickets: 
CVS-123590

[GPU] Fix cum_sum_partial_sum implementation for dimensions >=16

---

.github/labeler.yml

This is to be able to skip pipelines for any changes in docs except snippets via Smart CI

Add separate label for docs snippets

---

src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/extract_image_patches.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/rnn_cell.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/detection_output.cpp

- Func test was using combination too much and generates tons of cases
- 124669

[GPU] Decompose test combination to reduce test time

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/sync_infer_request.hpp
src/plugins/intel_gpu/src/graph/impls/common/condition.cpp
src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

- Move ShapePredictor instance from cldnn::network to InferRequest to prevent shapes mixing up in case of multiple infer requests
- Fix PVC WA related to USM Host buffers usage (it was missed which unintentionally allowed the use of USM Host for plugin's tensors)
- *ticket-id*

[GPU] Make ShapePredictor instance unique for each InferRequest instead of the cldnn::network

---

src/plugins/intel_gna/src/transformations/pwl_approximation.hpp

- Fix using `std::true_type` and `std::false_type` as function parameter to remove compiler warning in GNA transformations.
- [CVS-124762](https://jira.devtools.intel.com/browse/CVS-124762)

[CI]Fix compile warning regarding ABI changes in GNA plugin transormations

---

src/common/transformations/tests/common_optimizations/convert_u4_weights_zero_point_to_scalar.cpp

-Werror=stringop-overflow= warning occurs in some new GCC versions (e.g. 11.4.0) because of the std::vector<std::int8_t> usage in the test code.
Since this is not necessary to use int8 vector in FuseU4WeightsAndZeroPoint tests, it is replaced with std::vector<int>.
PR to master branch: #20918 
- *CVS-124460*

FuseU4WeightsAndZeroPoint tests compilation fix

---

src/inference/dev_api/openvino/runtime/ivariable_state.hpp
src/inference/src/dev/converter_utils.cpp
src/inference/src/dev/ivariable_state.cpp
src/plugins/intel_gpu/include/intel_gpu/plugin/variable_state.hpp
src/plugins/intel_gpu/src/plugin/variable_state.cpp
src/tests/test_utils/unit_test_utils/mocks/openvino/runtime/mock_ivariable_state.hpp

This PR changes `ov::IVaraibleState` interface allowing return the internal state pointer by value rather than by a const reference. That gives more flexibility for the implementations for instancing the state tensor on the fly when `get_state()` is called in exchange to an almost negligible performance impact.
- *ticket-id*

[Inference] Return state ptr by value

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_group_convolution.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_group_convolution_backprop_data.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_convolution_backprop_data.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_group_convolution.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_group_convolution_backprop_data.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_mat_mul.hpp
src/tests/functional/shared_test_classes/src/subgraph/quantized_convolution_backprop_data.cpp
src/tests/functional/shared_test_classes/src/subgraph/quantized_group_convolution.cpp
src/tests/functional/shared_test_classes/src/subgraph/quantized_group_convolution_backprop_data.cpp
src/tests/functional/shared_test_classes/src/subgraph/quantized_mat_mul.cpp
src/tests/ov_helpers/ov_models/include/ov_models/utils/ov_helpers.hpp
src/tests/test_utils/common_test_utils/include/common_test_utils/test_enums.hpp

- remove ngraph::helpers::QuantizationGranularity, replaced with ov::test::utils::QuantizationGranularity
- *CVS-124431*

[Func Test] remove ngraph::helpers::QuantizationGranularity

---

src/inference/src/dev/make_tensor.cpp
src/plugins/intel_cpu/src/infer_request.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/input_output_tensor_reuse.cpp

Extend the existing Input Output binding tests with new test cases:
- binding once in a series after the first inference
- binding once in a series before the first inference
- *ticket-id*

[CPU] Extend the existing IO binding subgraph tests

---

src/plugins/intel_cpu/src/nodes/transpose.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/instances/x64/transpose.cpp

- *enable bf16 acdb layout for transpose*
- *add bf16 acdb layout testcase*
- *CVS-124873*
- *CVS-116557*

[CPU]enable bf16 acdb layout for transpose

---

src/common/low_precision_transformations/include/low_precision/fold_convert.hpp
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/move_fc_reshape_to_weights.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/move_fc_reshape_to_weights.hpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.h
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp
src/plugins/intel_cpu/tests/unit/ngraph_transformations/move_fc_reshape_to_weights.cpp

This PR contains changes which add decompression support for the models which have both compressed and quantized layers.
- *Zero point with convert is supported in CPU specific transformations and optimizations*
- *Decompression related passes in common transformations part moved to a separate manager*
- *Added decompression related callbacks for Cleanup LPT to avoid decompression subgraph folding at the LPT stage*
- *CVS-124535*

[CPU] Decompression support for hybrid models

---

src/bindings/python/src/pyopenvino/graph/ops/loop.cpp
src/bindings/python/tests/test_graph/test_loop.py

- Remove binding limitation for Loop operator that inputs can be only `Constant` or `Parameter`
- [CVS-122380](https://jira.devtools.intel.com/browse/CVS-122380)

Remove limit for Loop inputs in bindings

---

src/frontends/tests/frontend/shared/test_builtin_extensions/builtin_extensions.cpp

- If Paddle frontend is disabled the unused functions can make compile errors due to `-Werror=unused-function`
- N/A

Remove unused function from build to remove ``-Werror=unused-function``

---

.github/workflows/linux.yml
tests/model_hub_tests/models_hub_common/constants.py
tests/model_hub_tests/torch_tests/test_torchvision_models.py

- *Use system model cache when running torch hub tests locally. That helps to use tests for local validation without downloading all the models again.*
- *ticket-id*

[PT FE] Use system model cache when running torch hub tests locally

---

src/plugins/intel_gpu/src/graph/condition.cpp
src/plugins/intel_gpu/src/graph/impls/common/condition.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp

This PR improves synchronization in condition operation and integrates it more closely with main pipeline
Original If operator execution (it interrupts main flow with two waits at the very beginning and at the end of its execution):
Optimized version (well-integrated with main network w/o interruptions):
This optimization demonstrates the highest improvement in cases where condition statement is a member of ShapeOf subgraph and we can choose required branch w/o extra synchronization overheads
Fixes:
- Reuse stream from main network for sub-networks of IF operator
- Extend print for usm allocation type in verbose debug
- 125033

[GPU] Optimize Condition operation by better integrating its subnetwork primitives with the main network

---

src/plugins/intel_cpu/tests/functional/specific_tests.cmake

- *Fixed the error of linking of specific tests:*
```
/home/a-sidorova/projects/master/openvino/src/plugins/intel_cpu/tests/functional/test_utils/x64/filter_cpu_info.cpp:37: multiple definition of `CPUTestUtils::filterCPUInfoForDevice...
/home/a-sidorova/projects/master/openvino/src/plugins/intel_cpu/tests/functional/test_utils/arm/filter_cpu_info.cpp:15: first defined here
```

[CPU][Tests] Fixed linking of ov_cpu_func_tests_subset

---

src/common/snippets/include/snippets/lowered/expression.hpp
src/common/snippets/include/snippets/lowered/expression_port.hpp
src/common/snippets/include/snippets/lowered/linear_ir.hpp
src/common/snippets/include/snippets/lowered/loop_manager.hpp
src/common/snippets/src/lowered/expression.cpp
src/common/snippets/src/lowered/expression_factory.cpp
src/common/snippets/src/lowered/expression_port.cpp
src/common/snippets/src/lowered/linear_ir.cpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/insert_tail_loop.cpp
src/common/snippets/src/op/subgraph.cpp

- *During review of PR18563 it was established that it is hard to perform correct deep copy of LIR, because it owns a range of pointers that in turn needs to be deep copied. In this PR we introduce a convenient and safe way to copy LIR or deep_copy a range of expressions*
- *-*
PR between branches for review: https://github.com/IvanNovoselov/openvino/pull/14

[Snippets] Deep copy interface

---

src/core/include/openvino/op/prelu.hpp
src/core/reference/include/openvino/reference/prelu.hpp
src/core/src/op/prelu.cpp

- Migrate PReLU operator to new API
- Remove `visit_attributes` as is same as base class.
- Minor refactor to reduce binary size.
- [CVS-118640](https://jira.devtools.intel.com/browse/CVS-118640)

[core]Migrate PReLU operator to new API

---

src/plugins/hetero/src/subgraph_collector.cpp
src/plugins/hetero/tests/unit/subgraph_collector.cpp

- This issue was discovered when splitting the execution of LLama v2 7b on multiple GPUs
- The subgraphs can not be generated because some ops has parameter with different affinity
- CVS-124326

[HETERO] Fix split subgraphs with parameter of different affinity

---

docs/articles_en/openvino_workflow/model_optimization_guide/ptq_introduction/quantization_w_accuracy_control.md
docs/optimization_guide/nncf/ptq/code/ptq_aa_openvino.py
docs/optimization_guide/nncf/ptq/code/ptq_onnx.py
docs/optimization_guide/nncf/ptq/code/ptq_openvino.py
docs/optimization_guide/nncf/ptq/code/ptq_tensorflow.py
docs/optimization_guide/nncf/ptq/code/ptq_torch.py

- Update OV documentation with ov.save_model() instead of ov.serialize()
- 121310
Link to docs: http://openvino-doc.iotg.sclab.intel.com/asuslov-docs/home.html
Porting: https://github.com/openvinotoolkit/openvino/pull/20711

[DOCS] Update optimization docs with ov.save_model() instead of ov.serialize() - for 23.2

---

src/plugins/intel_cpu/src/nodes/executors/acl/acl_convert.cpp

The change is required to fix the build compilation with `DEBUG_CAPS` enabled:
```
no member named 'name' in 'ov::element::Type'
```

[CPU][ARM] Call `to_string()` method of ov::element::Type in ACL Convert executor

---

src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/src/utils/plain_tensor.hpp

- *Fix build failure on ubuntu18 after PR #20506 merged:*
- Error: dereferencing type-punned pointer will break strict-aliasing rules
- Error explanation: “Aliasing rules simply say that you can only access an object through its own type, its signed / unsigned variant type, or through a character type (char, signed char, unsigned char)”, from [SO](https://stackoverflow.com/a/8825257), additional reference: [C 2011 6.5 paragraph 7](https://port70.net/~nsz/c/c11/n1570.html#6.5), [strict-aliasing and type-punned](https://stackoverflow.com/a/51228315)
- Error analysis: compiler complained [line](https://github.com/openvinotoolkit/openvino/blob/a1416ed68f467eb0a2e0a11f22b382d9e59ba877/src/plugins/intel_cpu/src/utils/plain_tensor.hpp#L226) does not contain any type reinterpretation, and error …

[CPU] Fix ScaledDotProductAttention build failure on ubuntu18

---

src/core/include/openvino/op/power.hpp
src/core/reference/include/openvino/reference/power.hpp
src/core/src/op/power.cpp

- Migrate `Power` operator to new API.
- Refactor operator and reference implementation to reduce binary size.
- [CVS-118639](https://jira.devtools.intel.com/browse/CVS-118639)

[core]Migrate Power operator to new API

---

tests/conditional_compilation/test_config.yml

- mxnet is an abandoned package https://github.com/apache/mxnet
- we cannot expect updates and fixes
- it's using a Python feature which has been removed in Python 3.11
- it causes errors in our conditional compilation tests
- the model being removed is specifically an mxnet model, so the scope of other frameworks will not be affected
https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/octave-resnet-26-0.25/model.yml#L50
- **more details in the ticket**
- 124418

Remove a failing `mxnet` model from conditional compilation tests

---

.github/workflows/linux.yml

GitHub [does not allow](https://github.com/orgs/community/discussions/12395) specifying the whole workflow as required, so we have to manually add each job in a workflow to required in Branch settings (separately for each production branch), which is inconvenient. Plus, there are bugs with reporting statuses from [matrix jobs](https://github.com/actions/runner/issues/952) and [reusable workflows](https://github.com/actions/runner/issues/1917) that can block PR from merge if required checks are specified per job.
This PR tries another solution - adding a separate job for reflecting overall pipeline status. This way only this job can be added to required in Branch settings + less duplication is needed for each branch. Adding a new required job would still require adding its name to "needs" …

[GHA] Alternative way to handle required pipeline checks

---

src/bindings/python/src/pyopenvino/core/offline_transformations.cpp
src/bindings/python/tests/test_transformations/test_offline_api.py

- extend `apply_make_stateful_transformation` with `param-result` pair
- CVS-124574

[PyOV] add param-result to offline transformation

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/mvn.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/loop.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/slice.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/strided_slice.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/remove_convert.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/strided_slice_zero_dims.cpp
src/plugins/intel_gna/tests/functional/pass_tests/convolution_crop_axis_h.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/mvn.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/prior_box.cpp
src/tests/functional/shared_test_classes/src/single_layer/batch_to_space.cpp
src/tests/functional/shared_test_classes/src/single_layer/mvn.cpp
src/tests/functional/shared_test_classes/src/single_layer/slice.cpp
src/tests/functional/shared_test_classes/src/single_layer/space_to_batch.cpp
src/tests/functional/shared_test_classes/src/single_layer/strided_slice.cpp
src/tests/functional/shared_test_classes/src/subgraph/const_strided_slice_concat.cpp
src/tests/functional/shared_test_classes/src/subgraph/memory_fq_concat_prelu.cpp
src/tests/functional/shared_test_classes/src/subgraph/multi_crops_to_concat.cpp
src/tests/functional/shared_test_classes/src/subgraph/mvn_multiply_add.cpp
src/tests/functional/shared_test_classes/src/subgraph/strided_slice.cpp
src/tests/functional/shared_test_classes/src/subgraph/stridedslice_concat.cpp
src/tests/functional/shared_test_classes/src/subgraph/stridedslice_conv.cpp
src/tests/ov_helpers/ov_models/include/ov_models/builders.hpp
src/tests/ov_helpers/ov_models/src/strided_slice.cpp

- Remove or deprecate makeBatchToSpace, makeSpaceToBatch, makeStridedSlice, makeSlice makeMVN builders
- Suppress deprecation in legacy code. Remove usage in modern code
- CVS-117139

Refactor ngraph builders 2

---

src/plugins/intel_gpu/src/graph/crop.cpp
src/plugins/intel_gpu/src/graph/include/crop_inst.h
src/plugins/intel_gpu/src/graph/include/permute_inst.h
src/plugins/intel_gpu/src/graph/include/reorder_inst.h
src/plugins/intel_gpu/src/graph/include/reshape_inst.h
src/plugins/intel_gpu/src/graph/include/scatter_elements_update_inst.h
src/plugins/intel_gpu/src/graph/include/scatter_nd_update_inst.h
src/plugins/intel_gpu/src/graph/include/scatter_update_inst.h
src/plugins/intel_gpu/src/graph/permute.cpp
src/plugins/intel_gpu/src/graph/reorder.cpp
src/plugins/intel_gpu/src/graph/reshape.cpp
src/plugins/intel_gpu/src/graph/scatter_elements_update.cpp
src/plugins/intel_gpu/src/graph/scatter_nd_update.cpp
src/plugins/intel_gpu/src/graph/scatter_update.cpp

- Removed `reuse_input()` method of some primitives as it always calls `update_output_memory()`
- Simplified `on_execute()` impls in some cases to avoid duplicated conditions with `update_output_memory()`

[GPU] Cleanup buffer reuse code

---

src/tests/test_utils/functional_test_utils/include/functional_test_utils/summary/summary.hpp
src/tests/test_utils/functional_test_utils/src/summary/api_summary.cpp
src/tests/test_utils/functional_test_utils/src/summary/op_summary.cpp
src/tests/test_utils/functional_test_utils/src/summary/summary.cpp

- *Crash in reports appeared when it was being analyzed model with several ops. At the start of test it had set CRASH as status for all ops, after this status was deleted only for one ops, first in the list, and for all ops it was set right status, PASSED, for example.*
- *CVS-125419*

[op_conformance] Fix not removing of crash for cases with several ops

---

docs/api/ie_python_api/api.rst

- missed documentation for python submodules
- TODO: port to 2023.2
- *ticket-id*

[Docs][PyOV] add missing docs

---

src/frontends/paddle/src/op/unstack.cpp
src/frontends/paddle/src/op_table.cpp
src/frontends/paddle/tests/op_fuzzy.cpp
src/frontends/paddle/tests/test_models/gen_scripts/generate_unstack.py

add unstack operation in Paddle front end
- https://www.paddlepaddle.org.cn/documentation/docs/en/2.5/api/paddle/unstack_en.html#unstack
- https://github.com/PaddlePaddle/Paddle/issues/57262
- https://github.com/openvinotoolkit/openvino/pull/20078
- https://github.com/openvinotoolkit/openvino/pull/20161

【Hackathon 5th No.96】add paddle unstack op

---

src/plugins/intel_cpu/src/utils/plain_tensor.hpp

- Correct assertion in `PlainTensor` member functions
- `PlainTensor::size`
- `PlainTensor::stride`
- [CVS-125576](https://jira.devtools.intel.com/browse/CVS-125576)

[cpu]Correct assertion in `PlainTensor` member functions

---

src/bindings/python/CMakeLists.txt

`pip install patchelf` is more cross platform than apt, and does not require root access. Patchelf is needed to install a wheel, so the user will already have Python and pip installed.

Add CMake hint to install patchelf with pip

---

tests/layer_tests/ovc_python_api_tests/test_ovc_cli_tool.py
tools/ovc/openvino/tools/ovc/cli_parser.py

`argv.input_model` contains `list` after arguments parsing. If `--verbose` is used, `get_model_name_from_args()` method is launched after parsing with `list` in `argv.input_model`, which leads to crush, as `list` is passed to `os.path.abspath()`.
Solution: 
Get first element from list if `argv.input_model` is list.
Ticket: CVS-125731
Code:
Validation:
Documentation:

[OVC] Fixed bug related to verbose param.

---

.github/workflows/linux.yml

To estimate the amount of hardware needed to cover our needs, we need to collect real-life statistics from PRs that would require running GPU tests with Smart CI rules enabled (how many executions we have per hour, etc.)

[GHA] Add GPU stub job to collect statistics

---

src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/scaled_attn.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/scaled_attn.hpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/instances/x64/scaled_attn.cpp
tests/model_hub_tests/torch_tests/test_hf_transformers.py
tests/model_hub_tests/torch_tests/test_timm.py

- *Fix ScaledDotProductAttension accuracy problem*
- Error: many models from timm repo failed to pass its accuracy test
- Reason:
- original attn_mask assumed that its shape was like [B, 1, L0, L0+L1], this was not true in encoder-based models, these shapes are possible: [B/1, H/1, L0/1, L0+L1], [H/1, L0/1, L0+L1] or scalar
- k,v head number of model 'Rocketknight1/tiny-random-falcon-7b' is 1 which previously requires their head number must be equal to q
- *125517*

[CPU] Fix ScaledDotProductAttension accuracy problem

---

docs/articles_en/learn_openvino/openvino_samples.md
docs/articles_en/learn_openvino/openvino_samples/get_started_demos.md

* Moved the building part from Overview article to the Get Started
* Shortened the Samples links in the Overview article
* Renamed "Get Started with C++ Samples" to "Get Started with Samples"
* Rewritten the building steps paragraphs
* Removed outdated information from Get Started with Samples article
* Rewritten the Run Inference article to be more general
* Added Python instructions and code
Porting: https://github.com/openvinotoolkit/openvino/pull/20957

[DOCS] Samples articles update for 23.2

---

src/core/dev_api/validation_util.hpp
src/core/include/openvino/core/validation_util.hpp
src/core/shape_inference/include/convolution_shape_inference_util.hpp
src/core/shape_inference/include/pooling_shape_inference_util.hpp
src/core/shape_inference/include/scatter_elements_update_shape_inference.hpp
src/core/shape_inference/include/squeeze_shape_inference.hpp
src/core/shape_inference/include/unsqueeze_shape_inference.hpp
src/core/src/op/loop.cpp
src/core/src/validation_util.cpp

- Improve validation of inputs ranks.
- Move Loop into `ov::op::v5` namespace.
- Migrate `is_rank_compatible_any_of` to dev API and use new version.
- [CVS-118622](https://jira.devtools.intel.com/browse/CVS-118622)

[core]Remove deprecated function from Loop

---

src/core/include/openvino/op/result.hpp
src/core/src/op/result.cpp

- Remove `visit_attributes` as is same as base class.
- Minor re-factor of evaluate.
- [CVS-118645](https://jira.devtools.intel.com/browse/CVS-118645)

[core]Refactor leftovers after migration to new API

---

src/core/include/openvino/op/read_value.hpp
src/core/src/op/read_value.cpp

- Remove legacy namespace, classes and use of utils functions
- [CVS-118642](https://jira.devtools.intel.com/browse/CVS-118642)

[core]Migrate ReadValue operator to new API

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *skip 32 bit tests for i32 Bitwise*
- *CVS-123749*

[CPU] skip 32 bit tests for i32 Bitwise

---

src/plugins/intel_cpu/tests/functional/subgraph_tests/src/conv3d_reshape.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/conv_maxpool_activ.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/convs_and_sums.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fq_fused_with_ss.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fullyconnected_strided_inputs_outputs.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fuse_scaleshift_and_fakequantize.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fuse_split_concat_pair_to_interpolate.cpp

- Upgrade ConvPoolActivTest to 2.0
- Upgrade Conv3dReshapeTest to 2.0
- Upgrade ConvsAndSums to 2.0
- Upgrade FQScaleshiftWithConstantShiftTest to 2.0
- Upgrade FullyConnectedStridedInputsOutputsTest to 2.0
- Upgrade FuseScaleShiftAndFakeQuantizeTest to 2.0
- Upgrade FuseSplitConcatPairToInterpolateTest to 2.0
- 125924

Upgrade CPU func tests to 2.o

---

src/tests/functional/plugin/conformance/subgraphs_dumper/src/cache/op_cache.cpp
src/tests/test_utils/functional_test_utils/layer_tests_summary/conformance_helper_tools/find_models_for_subgraphs_dumper.py

- *if list of models include several similar models some with constant and some with parameter, but file with model with constant goes fist, all models with parameters will defined as new because in_info_is_matched will be false*
- *ticket-id*

[subgraphs_dumper] Fix sporadic cache volume growth

---

src/core/include/openvino/op/range.hpp
src/core/reference/include/openvino/reference/range.hpp
src/core/src/op/range.cpp

- Migrate Range operator to new API.
- Remove legacy function an duplicated shape inference.
- Minor change range reference implementation.
- [CVS-118642](https://jira.devtools.intel.com/browse/CVS-118641)

[core]Migrate Range operator to new API

---

src/bindings/python/src/openvino/frontend/tensorflow/node_decoder.py

When model weights are located on GPU weights sharing leads to memory loss.
Solution: 
Turn off memory sharing for variables which are located on GPU.
Ticket: 126201
Code:
Validation:
Documentation:

[TF FE] Disable memory sharing for GPU.

---

src/common/snippets/include/snippets/lowered/linear_ir.hpp
src/common/snippets/include/snippets/lowered/pass/allocate_buffers.hpp
src/common/snippets/include/snippets/lowered/pass/define_buffer_clusters.hpp
src/common/snippets/include/snippets/lowered/pass/enumerate_expressions.hpp
src/common/snippets/include/snippets/lowered/pass/identify_buffers.hpp
src/common/snippets/include/snippets/lowered/pass/init_buffers_default.hpp
src/common/snippets/include/snippets/lowered/pass/init_loops.hpp
src/common/snippets/include/snippets/lowered/pass/normalize_buffer_ids.hpp
src/common/snippets/include/snippets/lowered/pass/pass.hpp
src/common/snippets/include/snippets/lowered/pass/solve_buffer_memory.hpp
src/common/snippets/include/snippets/utils.hpp
src/common/snippets/src/lowered/pass/allocate_buffers.cpp
src/common/snippets/src/lowered/pass/define_buffer_clusters.cpp
src/common/snippets/src/lowered/pass/enumerate_expressions.cpp
src/common/snippets/src/lowered/pass/identify_buffers.cpp
src/common/snippets/src/lowered/pass/init_buffers_default.cpp
src/common/snippets/src/lowered/pass/normalize_bufer_ids.cpp
src/common/snippets/src/lowered/pass/solve_buffer_memory.cpp
src/common/snippets/src/op/subgraph.cpp
src/common/snippets/tests/include/lowered/pass/buffer_allocation.hpp
src/common/snippets/tests/src/lowered/pass/buffer_allocation.cpp
src/inference/dev_api/openvino/runtime/memory_solver.hpp
src/inference/tests/unit/memory_solver_test.cpp
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.hpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/lowered/buffer_allocation.cpp
src/plugins/intel_gna/src/memory/gna_mem_requests_queue.hpp
src/plugins/intel_gna/src/memory/gna_memory.hpp

- Now Buffer memory allocation is more accurate. The pipeline supports two modes: non-optimized (each Buffer has unique ID and offset) and optimized (the smallest possible buffer scratchpad size) - this mode is default. The mode can be adjusted by config parameter.
- Optimized mode of pipeline includes the following optimizations: `Enumeration` - enumerate expressions by exec order (should be rewritten in general!), `IdentifyBuffers` - identify Buffers by IDs where some of them may be the same, `DefineBufferClusters` - prerequisite for `MemorySolver` where buffers from one cluster have the same memory pointer and `SolveBufferMemory` - the pass optimally allocate buffer scratchpad and set offsets to Buffer using common `MemorySolver` API. For more details go to the header files with the …

[Snippets] Refactored Buffer memory allocation

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing_through.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
src/plugins/intel_gpu/tests/unit/fusions/eltwise_fusion_test.cpp

- *Prevent fusing for eltwise which is not broadcastable from input to fused output. If it doesn't prevent, the fused eltwise would have an assertion during MakeIndexJitConstants() to get idx_order with input1*
- *https://github.com/openvinotoolkit/openvino/issues/20871*

[GPU] Prevent fusing for eltwise which is not broadcastable from input to fused output

---

src/plugins/intel_gna/src/backend/gna_limitations.cpp
src/plugins/intel_gna/src/backend/gna_limitations.hpp
src/plugins/intel_gna/src/gna_plugin.cpp
src/plugins/intel_gna/tests/deprecated/unit/engines/gna/I8_quantisation_test.cpp
src/plugins/intel_gna/tests/deprecated/unit/engines/gna/i16_quantisation_test.cpp
src/plugins/intel_gna/tests/unit/backend/gna_limitations_test.cpp
src/plugins/intel_gna/tests/unit/gna_get_aligned_split_sizes.cpp
src/plugins/intel_gna/tests/unit/gna_memory_alignment.cpp
src/plugins/intel_gna/tests/unit/transformations/gna_decompose_2d_convolution.cpp
src/plugins/intel_gna/tests/unit/transformations/gna_insert_copy_layer.cpp
src/plugins/intel_gna/tests/unit/transformations/gna_split_convolution_with_large_buffer_size.cpp
src/plugins/intel_gna/tests/unit/transformations/gna_split_eltwise.cpp

- Use InferenceEngine::ThreadLocal instead of the local_thread variable to prevent AppVerifier from detecting a memory leak
- 124826

[GNA] Use OV thread_local implementation

---

src/common/transformations/src/transformations/common_optimizations/concat_fusion.cpp
src/common/transformations/tests/common_optimizations/concat_fusion.cpp

- *If Concat has more then 1 consumer like here: 
The transformation was unfolding each `Concat` which created performance inefficiencies: 
Solution: verify that fusing `Concat` has only 1 consumer*
- *126387*

ConcatFusion: check that replacing input has only 1 consumer

---

src/plugins/intel_gpu/src/graph/impls/common/condition.cpp
src/plugins/intel_gpu/src/graph/input_layout.cpp
src/plugins/intel_gpu/tests/unit/test_cases/condition_gpu_test.cpp

- This change fixes segmentation fault in case the condition's dependency doesn't have output memory due to an empty tensor. In such a case, memory reallocation will be skipped for dependency, and dummy simple_attached_memory with an empty tensor layout is created and passed to the inner network
- 126403

[GPU] Allow to set empty tensor for inner network of condition primitive

---

src/plugins/intel_gpu/src/graph/include/loop_inst.h
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/kernel_selector/common_types.h
src/plugins/intel_gpu/tests/unit/test_cases/scatter_update_gpu_test.cpp

- Fix scatter update axis name
- Remove _exec_deps control for backedge_from because this is not required after https://github.com/openvinotoolkit/openvino/pull/21333
- Previously, we organized execution order based on dependency for input-output buffer sharing from loop-body
- With PR-21333, we are not sharing buffer between input and output when loop input has multiple outputs.
- Therefore, there is no need to adjust exec order.
- 125865

[GPU] Fix scatter update axis name

---

src/frontends/tensorflow/src/graph_iterator_meta.cpp
src/frontends/tensorflow/src/graph_iterator_saved_model.cpp
src/frontends/tensorflow/src/tf_utils.cpp
tests/layer_tests/tensorflow_tests/test_tf_AddTypes.py

**Details:** Support constants of different types and dtype attribute values

[TF FE] Support different types: tf.i8, u8, i16, u16, i32, u32, i64, u64, f16, f32, bf16

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/data/default_re_to_find_models.lst

- *item1*
- *...*
- *ticket-id*

[CONFORMANCE] Fix reg exp to find models

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/select.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/shape_ops.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/shapeof.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/shuffle_channels.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/slice.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/space_to_batch.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/space_to_depth.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/split.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/strided_slice.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/tensor_iterator.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/tile.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/topk.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/unique.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/variadic_split.cpp

- migrate single layer test cases to be API 2.0 - part 5
- *...*
- *ticket-id*

[CPU tests] migrate single layer test cases to be API 2.0 - part 5

---

src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/tests/convert_model.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_2in_2out.py

**Details:** Allow conversion of models with names like `model.pb.frozen` so `pb` suffix is not required.
**Ticket:** 120009

[TF FE] Allow any model format extension

---

docs/articles_en/learn_openvino.md

Port from https://github.com/openvinotoolkit/openvino/pull/21539
- Removed link and description of API 2.0 Transition in Learn OpenVINO article.
- Added link and description of Generative AI Optimization and Deployment to the article.

[DOCS] Update of Learn OpenVINO article for 2023.2

---

src/inference/src/os/lin/lin_system_conf.cpp
src/inference/tests/unit/cpu_map_parser/freq_parser_linux.cpp

- *fix parse_freq_info_linux for wrong cpu frequency information*
- *126304*

fix parse_freq_info_linux for wrong cpu frequency information

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/rename_conformance_ir.py

- *add shape to name for hashing for Convolution, because some values of shape are important for comparation and if two irs have same attributes and shape type, they could have different kernels of shape and it will be deferent irs*
- *...*
- *ticket-id*

Add [rename conformance ir] input shape to hash name for Convolution

---

src/tests/functional/plugin/conformance/test_runner/README.md
src/tests/test_utils/functional_test_utils/layer_tests_summary/run_conformance.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/utils/file_utils.py
src/tests/test_utils/functional_test_utils/src/summary/op_summary.cpp

- *Split of conformance runner by entities as an optional command-line arg*
- *ticket-id*

[CONFORMANCE] Specify validation entity as arg of `run_conformance`

---

.github/workflows/coverity.yml

- Turns out, the Coverity platform accepts only 3 builds **per day**.

[CI] [GHA] Change Coverity trigger to nightly

---

src/plugins/intel_gna/src/gna_graph_compiler.cpp

- Properly obtain all subsequent layers to prevent the memory layer from being disconnected
- 146003

[GNA] Properly obtain all subsequent layers for memory layer connection

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/convolution_backprop_data.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/group_convolution.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/group_convolution_backprop_data.cpp

- Migrate convolution test to 2.0
- *...*
- *ticket-id*

[CPU tests] migrate single layer test cases to be API 2.0 - part 9

---

src/plugins/intel_gpu/include/intel_gpu/primitives/broadcast.hpp
src/plugins/intel_gpu/src/graph/broadcast.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/mark_shape_of_subgraphs.cpp
src/plugins/intel_gpu/src/graph/include/read_value_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/ops/broadcast.cpp
src/plugins/intel_gpu/src/plugin/variable_state.cpp
src/plugins/intel_gpu/tests/common/subgraphs_builders.hpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp

- Fixed state initializer handling in shape inference of read_value primitive
- Added an exception for shape_of subgraphs markup for read_value to terminate mark propagation for this node
- Extended KV cache func tests for the cases with gather (from beam search) and state initializer subgraph
- Added output partial shape parameter for broadcast to have better compile-time shape inference and less dynamic dimensions if ngraph was able to propagate part of the dimensions and make those static

[GPU] Fixed stateful KV cache issues + minor improvements

---

tests/model_hub_tests/torch_tests/hf_transformers_models

With the newest transformers-4.36.0 dinov-2-base started to pass
[CVS-124981](https://jira.devtools.intel.com/browse/CVS-124981)

Enable dinov2-base

---

.github/workflows/android_arm64.yml
.github/workflows/fedora.yml
.github/workflows/linux_arm64.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/linux_riscv.yml

Adding more "overall" status checks needed to make these workflows "required". Also fixes the common check name for linux_arm64 (overall status checks must be unique for each workflow, otherwise they're overwriting each other).
Sadly, there is no point in using reusable workflows to combine all our workflows and provide a single status check for all of them - we already almost hitting the [limits](https://docs.github.com/en/enterprise-server@3.11/actions/using-workflows/reusing-workflows#limitations) of 20 unique workflows reused, having 10 parent workflows (including mac & windows cc) + 9 reusable test workflows. Another option - create a separate workflow that waits for all other workflows to finish and checks their status - is not possible using …

[GHA] Add overall status check to more workflows

---

src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/move_fc_reshape_to_weights.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp
src/plugins/intel_cpu/tests/unit/transformations/move_fc_reshape_to_weights.cpp

- PR improves "first token" latency for 4bit compressed LLMs on AVX2/AVX512 HW targets. 
- OneDNN PR: https://github.com/openvinotoolkit/oneDNN/pull/221
- *[CVS-125052](https://jira.devtools.intel.com/browse/CVS-125052)*

[CPU] Improve first token latency for 4bit compressed models

---

src/frontends/pytorch/src/frontend.cpp
src/frontends/pytorch/src/node_context.cpp
src/frontends/pytorch/src/translate_session.cpp
src/frontends/pytorch/src/translate_session.hpp

- *Remove generating unique names from PyTorch FrontEnd, rely on `ResolveNameCollisions` transformation. This will create more stable names, since counter will be different for each collision.*
- *None*

[PT FE] Remove unique names from FE, rely on ResolveNameCollisions

---

src/bindings/python/tests/test_runtime/test_async_infer_request.py
src/bindings/python/tests/test_runtime/test_sync_infer_request.py

- *item1*
- *...*
- *ticket-id*

[PyOV] move rest of start_async tests to test_async

---

.github/workflows/coverity.yml

To be able to trigger it via GitHub API from Jenkins nightly, as we did in Azure

[GHA] Add workflow_dispatch trigger to coverity

---

src/common/snippets/include/snippets/lowered/pass/identify_buffers.hpp
src/common/snippets/src/lowered/pass/identify_buffers.cpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/lowered/buffer_allocation.cpp

- *The algorithm iterated by `buffer_neighbours` where were the both Buffer types (that are connected to Loop and are this Loop inside). So in some cases the Loops that in one Loop and may use the same GPR are analyzed with incorrect `ShiftDataPtrs` values (these values were used only for analyze case where one of Buffers is Loop inside and second is connected to this Loop. The PR splits `buffer_neighbours` to `buffer_neighbours` (Buffers are connected to the current Loop) and `inner_buffers` (Buffers are Loop inside)*
- *The test with the same behavior is introduced in https://github.com/openvinotoolkit/openvino/pull/19335*
- *N/A*

[Snippets] Fixed IdentifyBuffers for nested loop case

---

.github/workflows/linux_arm64.yml

- The workflow with tests was removed in #21654, it was not removed from the Linux ARM64 workflow. It is the cause of the broken workflow:

[CI] [GHA] Remove not-existing reusable workflow from Linux ARM64 workflow

---

src/bindings/python/src/pyopenvino/pyopenvino.cpp
src/bindings/python/tests/test_runtime/test_model.py

- Modified the `openvino.save_model()` function binding to perform a type check on the 'model' argument. If the argument is `None`, an `AttributeError` exception is now raised instead of segmentation fault.
- Closes #21086

[Python API] Added exception handling for 'None' model argument in save_model function

---

src/bindings/python/src/openvino/preprocess/torchvision/torchvision_preprocessing.py
src/bindings/python/tests/test_torchvision_to_ov/test_preprocessor.py

- Fix Resize for non-square images according to torchvision `size` [documentation](https://pytorch.org/vision/stable/generated/torchvision.transforms.Resize.html)
- Expose missing PILLOW interpolation modes to torchvision preprocessing
- Add tests
- 125609

[PyOV][torchvision] Fix Resize for non-square images and expose missing interpolation modes

---

.github/workflows/coverity.yml

Needed to be able to run coverity on a specific commit from nightly, like we did in Azure (workflow_dispatch [doesn't support](https://github.com/github/docs/issues/590) running workflow from sha by default).

[GHA] Add openvino ref input to workflow_dispatch for coverity

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/data.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.hpp
src/plugins/intel_gpu/tests/unit/module_tests/usm_memory_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/condition_gpu_test.cpp

- Speed up large data loading by overlapping blob file reading and data transfer
- Serialization of nodes allocation order
- Skip `check_names()` when building `cldnn::network` from cached `cldnn::program`
- 126609

[GPU] faster model caching

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/test_cases/condition_gpu_test.cpp

- all primitives generate event.
- remove reorder from test-case
- 125771

[GPU] parameter's event will be included execution args

---

cmake/features.cmake
src/common/snippets/docs/debug_capabilities/README.md
src/common/snippets/docs/debug_capabilities/perf_count.md
src/common/snippets/include/snippets/lowered/linear_ir.hpp
src/common/snippets/include/snippets/lowered/pass/insert_perf_count.hpp
src/common/snippets/include/snippets/op/perf_count.hpp
src/common/snippets/include/snippets/snippets_isa_tbl.hpp
src/common/snippets/src/generator.cpp
src/common/snippets/src/lowered/pass/insert_perf_count.cpp
src/common/snippets/src/op/perf_count.cpp
src/common/snippets/src/op/subgraph.cpp
src/common/snippets/src/shape_inference/shape_inference.cpp
src/common/snippets/tests/src/lowering_utils.cpp
src/plugins/intel_cpu/src/emitters/x64/cpu_generator.cpp
src/plugins/intel_cpu/src/emitters/x64/jit_perf_count_chrono_emitters.cpp
src/plugins/intel_cpu/src/emitters/x64/jit_perf_count_chrono_emitters.hpp
src/plugins/intel_cpu/src/emitters/x64/jit_perf_count_rdtsc_emitters.cpp
src/plugins/intel_cpu/src/emitters/x64/jit_perf_count_rdtsc_emitters.hpp
src/plugins/intel_cpu/src/extension.cpp
src/plugins/intel_cpu/src/nodes/subgraph.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/perf_count_rdtsc.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/perf_count_rdtsc.hpp
src/plugins/intel_cpu/src/transformations/snippets/x64/shape_inference.cpp

[snippets perf count](https://github.com/openvinotoolkit/openvino/pull/19493) follow-up:  
- *Binary size not increase.*
- *Executor cache is disabled by default if enable perf count.*
- N/A

[SnippetS] Binary size reduce, executor cache disabled if enable perf count

---

src/frontends/pytorch/src/op/scaled_dot_product_attention.cpp
tests/layer_tests/pytorch_tests/test_scaled_dot_product_attention.py

- *Scale input in torchscript ScaledDotProductAttention is scalar float, converted in OV to f32. Add ConvertLike in translation to match other dtypes, fixing other precisions.*
- *Extend tests to cover both f32 and f64.*
- *126534*

[PT FE] ScaledDotProductAttention fix issue with other float dtypes

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- Fix quantized models performance issue caused by unintentional applying is_non_decompression_multiply() callback to quantized constants
- 127833

[GPU] Apply is_non_decompression_multiply() callback only for compressed models

---

src/common/transformations/tests/op_conversions/scaled_dot_product_decomposition_test.cpp

- *Fix CI issue due to merging following 2 conflicting PR simultaneously*
- *https://github.com/openvinotoolkit/openvino/pull/21356*
- *https://github.com/openvinotoolkit/openvino/pull/21281*
- *ticket-id*

[CORE][TESTS] Fix ScaledDotProductAttention L shape in decomposition tests

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp

- This PR improves LLMs support on SPR platform:
-- Improved latency for int8 compressed models via using avx512 kernel for "second" token processing (small batch)
-- Support of 4 bit compressed models via using avx512 kernel for "second" token processing (small batch)
-- "First' token (big batch) is processed via amx kernel to satisfy huge compute requirements
-- Both avx512 and amx kernels are modified to use the same weights layout in order to minimize memory consumption
- OneDNN fork changes: https://github.com/openvinotoolkit/oneDNN/pull/223
- [CVS-125052](https://jira.devtools.intel.com/browse/CVS-125052)

[CPU] FullyConnected acceleration with 4bit weights decompression on SPR

---

src/bindings/python/src/openvino/runtime/ie_api.py
src/bindings/python/src/openvino/runtime/utils/data_helpers/data_dispatcher.py
src/bindings/python/src/openvino/runtime/utils/data_helpers/wrappers.py
src/bindings/python/tests/test_utils/test_data_dispatch.py

- Allowing single inputs in form of lists of simple types into inference calls (by extending the data dispatcher).
- Previously single-input models required additional wrapping for simple types like: `[["you shall not pass"]]`. New approach in data dispatcher checks if the model has one input and passed data is of simple type (`str`/`bytes`/`float`/`int`) and wraps the incoming list automatically, thus allowing simpler syntax of: `["you shall pass"]`.
- related to: 107409 per request from @slyalin

[PyOV] Allow single inputs in form of lists of simple types

---

src/plugins/intel_gpu/src/graph/gather.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/dynamic_shape_gather_opts.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/gather_inst.h
src/plugins/intel_gpu/src/graph/include/pass_manager.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/stateful_model.cpp

- Skip gather if it is just capturing the entire inputs
- Need to check all indices, so applied only for the target pattern (i.e., gather being used to collect beam idx)
- 127581

[GPU] Skip redundant gather in stateful model

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/variable_state.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/assign.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/read_value.hpp
src/plugins/intel_gpu/src/graph/assign.cpp
src/plugins/intel_gpu/src/graph/include/assign_inst.h
src/plugins/intel_gpu/src/graph/include/read_value_inst.h
src/plugins/intel_gpu/src/graph/include/variable.hpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/read_value.cpp
src/plugins/intel_gpu/src/plugin/ops/variable.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/src/plugin/variable_state.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp

- Allow precision conversion for ReadValue/Assign operations for `ConvertPrecision` pass and added corresponding handling of original precision (which is stored in rt info map) to return state tensor with expected data type.
- Fixed state reset logic for cases w/o ReadValue initializer
- Modified KV cache test: 
-  now it runs multiple iterations with state reset
- added state tensor check on the last iteration
- added test for fp32 model

[GPU] Enable state precision conversion to infer precision

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/base/ov_subgraph.hpp
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
src/tests/test_utils/functional_test_utils/layer_tests_summary/conformance_helper_tools/conformance_vs_accuracy_comparator.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

f32 before align with accuracy validation on 57.48 % , now 72.86 % 
f16 before align with accuracy validation on 55.56 % , now 81.20 % 
- *fixed method of calculating diffs between accuracy and conformance validation results, before skipped tests and models from tests was classified as failed, now is not (this change have the gravest result)*
- *have changed less_or_eq function, which check if threshold and value diff or not. It was fixed FAIL for cases of threshold and value are absolutely eq(without small errors of floating point numbers) and fixed PASS for cases with INF value and not INF threshold.*
- *defined abs threshold per type:*
-  boolean 0
-  int 1
-  f16/bf16 abs_median * 0.05 or 1e-3 
-  f32/f64 abs_median * 0.05 or  1e-5
- *changed approach for rel threshold, now rel …

Accuracy collect statistic 

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

[GPU] Fix for is_user_cpu() function

---

src/plugins/intel_cpu/src/cpu_memory.cpp
src/plugins/intel_cpu/src/infer_request.cpp

[CPU] StringMemory for the output tensor in the InferRequest

---

src/tests/functional/plugin/shared/include/preprocessing/yuv_to_grey_tests.hpp
src/tests/functional/plugin/shared/src/preprocessing/yuv_to_grey_tests.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/base/utils/generate_inputs.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp

- Get rid of `LayerTestsDefinitions` usage as preparation to drop `single_layer/` folder

Preprocessing tests - use new utils

---

src/plugins/intel_gpu/src/graph/graph_optimizer/dynamic_shape_gather_opts.cpp

- *In the case of a 0d partial_shape, accessing an element at index 0 results in an error*

[GPU] Small fix for dynamic_shape_gather_opts pass

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/conformance_helper_tools/conformance_vs_accuracy_comparator.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *fixed method of calculating diffs between accuracy and conformance validation results, before skipped tests and models from tests was classified as failed, now is not (this change have the gravest result)*
- *[CVS-124663](https://jira.devtools.intel.com/browse/CVS-124663)*

[op conformance] Made fixes to align with accuracy validation

---

src/bindings/python/src/openvino/frontend/tensorflow/utils.py
tests/layer_tests/ovc_python_api_tests/test_tf.py

In OVC `GraphDef` is converted to `tf.Graph` using method `tf.graph_util.import_graph_def()`. By default this method adds "`import/`" prefix to all nodes. This prefix result in mismatch of names comparing to original model.
Solution: 
To avoid adding this prefix `name=''` parameter can be set.
Ticket: 127904
Code:
Validation:
Documentation:

[OVC] Fixed tensor names for GraphDef format.

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/tests/unit/test_cases/reshape_gpu_test.cpp

- This PR restricts Activations fusions to dynamic Reshape primitive, it's needed because fused activation prevents Reshape's optimization, and due to lack of shape-agnostic kernel implementation for Reshape, causes kernel recompilation in runtime for every shape change (for small context sizes it consumes almost 1/4 of all 1st token time in case of Qwen model, and affects 2nd token time as well (fortunately, all other iters reuse impl from cache))
- *ticket-id*

[GPU] Do not allow Activation fusion to dynamic Reshape prim to prevent runtime Reshape kernel compilation

---

src/plugins/intel_cpu/src/nodes/transpose.cpp

Reference reorder (spec_reference) is selected by oneDNN if `performAsReorder` is true on ARM platforms.
To avoid reference code, `performAsReorder` set explicitly to false for non-fp32 precision on arm platforms.

[CPU][ARM] Disable transpose as reorder path for non-f32 precision

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/caching_tests.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp

- For ov::internal::compiled_model_runtime_properties, previous [PR-21492](https://github.com/openvinotoolkit/openvino/pull/21492) only contains core level test with mock plugin, it need more test to validate plugin's behavior.
- *ticket-id*

Add more tests for model cache new feature

---

src/common/snippets/include/snippets/lowered/linear_ir.hpp
src/common/snippets/include/snippets/op/subgraph.hpp
src/common/snippets/src/op/subgraph.cpp
src/common/snippets/tests/include/lowering_utils.hpp
src/common/snippets/tests/src/lowered/pass/optimize_domain.cpp
src/common/snippets/tests/src/lowering_utils.cpp
src/plugins/intel_cpu/src/nodes/subgraph.cpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/mul_add_to_fma.cpp

- *On the master branch if we create `Subgraph` and `LinearIR` and after that call `set_min_jit_work_amount` or `set_min_parallel_work_amount`, these values will be set only in `Subgraph`. Lowered config of `LinearIR` won't be updated. The CPU Plugin works so - it means that when the plugin update `min_jit_work_amount` and `min_parallel_work_amount`, the lowered pass `OptimizeDomain` has outdated (incorrect) values. It may affects performance of models. The PR removes the corresponding setters from `Subgraph` to avoid collisions*
- *N/A*

[Snippets] Propagate work amounts from Subgraph To LinearIR

---

src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/move_eltwise_up_data_movement.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/mha.cpp
src/plugins/intel_cpu/tests/unit/transformations/move_eltwise_up_data_movement_test.cpp

- *Move FakeQuantize up through data movement operations to make data movement operations executed in int8 precision. For example, modify "transpose-->FakeQuantize" to "FakeQuantize-->transpose" *
- *CVS-124005*

[nGraph Transformations]Move FakeQuantize up through data movement operations 

---

tests/model_hub_tests/tf_hub_tests/precommit_models

**Details:** Update precommit with model containing TensorListConcatV2 op. TensorListConcatV2 support was recently added in other PR.

[TF Hub] Update precommit with model containing TensorListConcatV2 op

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/permute_f_y_axes.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_f_y_axes.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_f_y_axes.h
src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_selector.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/transpose.cpp
src/plugins/intel_gpu/tests/unit/fusions/permute_fusion_test.cpp

This reverts commit 6719133af29d55477b5a1a0a271d177fecc5934f.
- Revert "[GPU] Fix accuracy problems brought by permute_f_y kernel (https://github.com/openvinotoolkit/openvino/pull/20241)" due to performance/accuracy regression
- 128142

Revert "[GPU] Fix accuracy problems brought by permute_f_y kernel (#20241)" 

---

src/plugins/intel_gpu/src/graph/impls/ocl/kv_cache.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Devices w/o USM support could face an exception in `check_allocatable` function due to hardcoded `usm_host` allocation type
- Reinterpret out buffer for kv_cache primitive to ensure that src and dst buffer sizes match in copy_from impl

[GPU] Fix allocation when usm is unavailable

---

src/plugins/intel_cpu/src/utils/gen_pattern.hpp

- when pattern contains attributes with empty initializer_list (like: `"new_axis_mask", {}`), it should only match graph node also with empty vector, otherwise should fail the match.
- CVS-127879

[CPU] fix gen_pattern::AttrAny::equal_to

---

src/common/snippets/include/snippets/lowered/pass/pass.hpp
src/common/snippets/include/snippets/lowered/pass/pass_config.hpp
src/common/snippets/include/snippets/op/subgraph.hpp
src/common/snippets/include/snippets/pass/manager.hpp
src/common/snippets/include/snippets/pass/positioned_pass.hpp
src/common/snippets/src/lowered/pass/pass.cpp
src/common/snippets/src/lowered/pass/pass_config.cpp
src/common/snippets/src/op/subgraph.cpp
src/common/snippets/src/pass/manager.cpp
src/common/snippets/src/pass/positioned_pass.cpp
src/common/snippets/tests/include/lowered/pass/buffer_allocation.hpp
src/common/snippets/tests/include/lowering_utils.hpp
src/common/snippets/tests/src/lowered/pass/buffer_allocation.cpp
src/common/snippets/tests/src/lowered/pass/loop.cpp
src/common/snippets/tests/src/lowering_utils.cpp
src/plugins/intel_cpu/src/nodes/subgraph.cpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/lowered/buffer_allocation.cpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/mul_add_to_fma.cpp

- *Added support of PassConfig to lowered PassPipeline to allow developers to enable/disable transformations*
- *Added support of PositionedPasses to lowered PassPipeline to allow developers to insert backend specific transformations in needed parts of pipeline without the common pipeline splitting*
- *Change `std::string m_pass_name` to `DiscreteTypeInfo m_pass_type_info` in Snippets Manager for data flow transformations*
- *113666, 126214*

[Snippets] Added PassConfig and PositionedPasses for PassPipeline

---

src/frontends/onnx/tests/tests_python/test_backend.py

Statistics
Out of 55 tests performed:
- test_split_variable_parts_default_axis_opset18_cpu failed 14 times 
- test_split_variable_parts_default_axis_opset13_cpu failed 8 times
- test_split_variable_parts_1d_opset18_cpu failed 6 times 
CVS-124587

[CI][ONNX] Disable backend tests

---

src/plugins/intel_gpu/src/graph/gather.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- *checkout input layout is zero count before calling dep_memory()*
- *add the case for input layout count is zero*
- *in gather_inst, run build_deps before checking is_the_same_buffer(output_memory(), input_memory())*
- *128412*
- *128626*

[GPU] Fix issue for skipping gather

---

.github/workflows/linux_arm64.yml
src/frontends/onnx/frontend/include/onnx_import/core/node.hpp
src/frontends/onnx/frontend/include/onnx_import/core/null_node.hpp
src/frontends/onnx/frontend/src/core/attribute.cpp
src/frontends/onnx/frontend/src/core/attribute.hpp
src/frontends/onnx/frontend/src/core/graph.cpp
src/frontends/onnx/frontend/src/core/graph.hpp
src/frontends/onnx/frontend/src/core/node.cpp
src/frontends/onnx/frontend/src/core/null_node.cpp
src/frontends/onnx/frontend/src/onnx_framework_node.hpp
src/frontends/onnx/frontend/src/op/if.cpp
src/frontends/onnx/frontend/src/op/loop.cpp
src/frontends/onnx/frontend/src/op/scan.cpp

- Cleanup nGraph symbols from graph.hpp/cpp
- 125501

[ONNX] Frontend refactoring

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp

- Fixed crash  in prepare_buffer_fusing for kv cache primitive when the concat axis is < 0
- 128111

[GPU] Fix minus axis case for kv cache primitive buffer fusing

---

.github/ISSUE_TEMPLATE/good_first_issue.yml
CONTRIBUTING.md
README.md

- Modify GFI template with link to Intel DevHub Discord server
- Add the link to the docs as well
- N/A

Add link to Intel DevHub Discord to GFI template and docs

---

src/inference/dev_api/openvino/runtime/iasync_infer_request.hpp
src/inference/src/dev/converter_utils.cpp
src/tests/functional/plugin/shared/include/behavior/infer_request/callback.hpp
src/tests/functional/plugin/shared/include/behavior/infer_request/wait.hpp

- After https://github.com/openvinotoolkit/openvino/pull/15096/files#diff-a90e98f27bb865c5cde6cf5589727b53d63595049b054c665fb7e0db44149788 InferenceEngine API uses OpenVINO API via converter. OpenVINO wait_for() returns only true/false, when InferenceEngine Wait() may return INFER_NOT_STARTED/RESULT_NOT_READY/OK. So the changes restore INFER_NOT_STARTED status returned by converter
- CVS-128850

Fix `INFER_NOT_STARTED` infer status code

---

src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/src/edge.h
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/input.cpp

- Change approach for updating node constant type (whether the Node is located on a constant path)
- Remove Unknown constant type
- Assign NoConst by default
- Update a constant type of the current node and its childs when a parent edge is added / removed

[CPU] Update Node constant type when adding or removing parent edges

---

src/tests/functional/plugin/shared/include/behavior/compiled_model/import_export.hpp

- *Relu is not supported with boolean*
- *also removed tests related to 1.0 api*
- *ovImportExportedFunction renamed to importExportedFunctionConvertPrecision*
- *CVS-124449*

[apiConformance] Move from Relu to double Concat function in import_export tests

---

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

- Previously prealloc for VariableState has been set prior to the reset preallocator which applied debug configs
- After this fix, debug config can be applied to VariableState too

[GPU] Fix debug config setup position prior to allocate memories.

---

src/plugins/intel_gpu/src/plugin/ops/gather.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp

- *Negative values of indices should be indexing from data.shape[axis]*
- *126925*

[GPU] fix Crop (Gather) in case of negative indices

---

samples/cpp/common/utils/src/args_helper.cpp
src/frontends/onnx/frontend/src/op/blackmanwindow.cpp
src/frontends/onnx/frontend/src/op/hammingwindow.cpp
src/frontends/onnx/frontend/src/op/hannwindow.cpp

M_PI using fix in MinGW
&
'direct.h' header is existed in MinGW

M_PI(math.h) using fix & dirent.h is existed in MinGW

---

src/bindings/c/tests/ov_infer_request_test.cpp

- Avoid some random timeout issue of ov_infer_request_wait_for()
- CVS-128831 CVS-128963

[CAPI] avoid random timeout issue in test cases

---

.github/workflows/job_python_unit_tests.yml
.github/workflows/py_checks.yml
.github/workflows/windows.yml
src/bindings/python/CMakeLists.txt
src/bindings/python/docs/test_examples.md

- *item1*
- *...*
- *ticket-id*

[PyOV] clean up after legacy python api removal

---

.github/ISSUE_TEMPLATE/good_first_issue.yml
CONTRIBUTING.md
README.md

- The previous link expired, the new link is permanent
- N/A

Update Discord links to permalinks

---

src/frontends/onnx/frontend/src/op/org.openvinotoolkit/deformable_conv_2d.cpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/deformable_conv_2d.hpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/detection_output.cpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/detection_output.hpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/fake_quantize.cpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/fake_quantize.hpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/generate_proposals.cpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/group_norm.cpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/group_norm.hpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/normalize.cpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/normalize.hpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/prior_box.cpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/prior_box.hpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/swish.cpp
src/frontends/onnx/frontend/src/op/org.openvinotoolkit/swish.hpp

- Updated operations in org.openvinotoolkit
- 125501

[ONNX] Frontend refactoring: operations

---

docs/articles_en/learn_openvino/tutorials.md
docs/nbdoc/consts.py
docs/openvino_sphinx_theme/openvino_sphinx_theme/directives/code.py

Replacing the source for the `Open in Colab` badge image.
Porting: https://github.com/openvinotoolkit/openvino/pull/22116

[DOCS] Fix images for notebooks for 23.2

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp

- Fixed dynamic pad handling in runtime gather opt. Before that fix pad could be lost in some cases which led to the wrong accuracy
- Updated realloc_if_needed logic to merge paddings to updated_shape to ensure correct buffer size is used for allocation. It's needed to avoid an issue when shape predictor uses ration based approach for prealloc and squeeze all dimensions into 1 while padding is not modified. So we could have `[N, C, H, W] + [0, PAD, 0, 0]` case transformed to `[N*C*H*W*RATIO] + [0, PAD, 0, 0]` and final alloc size being `N*C*H*W*RATIO*PAD` while `N*(C+PAD)*H*W*RATIO` was expected

[GPU] Fixed mem alloc size and pad propagation for kv cache opt

---

src/common/snippets/src/lowered/pass/allocate_buffers.cpp

- *We inited the pass pipeline in `AllocateBuffers` in condition body `if (m_is_optimized_mode)` where some passes has reference on `BufferClusters buffer_clusters` as class field. After `if` body execution we run the pass pipeline with saved reference on the `buffer_clusters` that already destroyed. The PR suggests to create `buffer_clusters` and run the pass pipeline in the one code block.*
- *129379*

[Snippets] Fixed access by expired reference

---

src/common/transformations/src/transformations/transpose_sinking/ts_general.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_unary.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp
src/common/transformations/tests/transpose_sinking/ts_unary_test.cpp

We consider HardSigmoid, LogSoftmax and ConvertLike as Unary operation in TransposeSinking transformation and have to ignore other inputs except 0th.
- *CVS-126737*

Fix TSUnary transformation

---

src/bindings/c/tests/ov_infer_request_test.cpp

- handle cancel() call after async infer & the infer finished
- Refer C++ API test
- [129394](https://jira.devtools.intel.com/browse/CVS-129394)

[CAPI][TEST] take account with cancel after the infer finished

---

src/common/snippets/docs/snippets_design_guide.md
src/common/snippets/include/snippets/lowered/expression.hpp
src/common/snippets/include/snippets/lowered/expression_port.hpp
src/common/snippets/include/snippets/lowered/linear_ir.hpp
src/common/snippets/include/snippets/lowered/loop_manager.hpp
src/common/snippets/src/lowered/expression.cpp
src/common/snippets/src/lowered/expression_port.cpp
src/common/snippets/src/lowered/linear_ir.cpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/assign_registers.cpp
src/common/snippets/src/lowered/pass/fuse_loops.cpp
src/common/snippets/src/lowered/pass/identify_buffers.cpp
src/common/snippets/src/lowered/pass/init_loops.cpp
src/common/snippets/src/lowered/pass/insert_broadcastmove.cpp
src/common/snippets/src/lowered/pass/insert_buffers.cpp
src/common/snippets/src/lowered/pass/insert_load_store.cpp
src/common/snippets/src/lowered/pass/insert_loops.cpp
src/common/snippets/src/lowered/pass/insert_perf_count.cpp
src/common/snippets/src/lowered/pass/insert_tail_loop.cpp
src/common/snippets/src/lowered/pass/load_movebroadcast_to_broadcastload.cpp
src/common/snippets/src/lowered/pass/move_result_out_of_loop.cpp
src/common/snippets/src/lowered/pass/softmax_decomposition.cpp
src/common/snippets/src/lowered/pass/split_loops.cpp
src/common/snippets/src/lowered/pass/validate_loops.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/fuse_load_store_and_convert.cpp

- *Removed `replace_input` from LinearIR since it's not responsibility of LinearIR and added this support to `Expression` and `ExpressionPort`*
- *Added helpers `replace_with_expr`, `replace_with_node` and `insert_node` to LinearIR to encapsulate common work with expression creation, insertion etc. Fore more details, please read briefs of the helpers in LinearIR*
- *122690, 126994*

[Snippets] Introduced helpers insert_node and replace_node

---

src/bindings/c/tests/ov_infer_request_test.cpp

- handle cancel() call after async infer & the infer finished
- Refer C++ API test
Ported https://github.com/openvinotoolkit/openvino/pull/22151
- [129394](https://jira.devtools.intel.com/browse/CVS-129394)

[CAPI][TEST] fix cancel api test with infer finished before cancel call

---

samples/python/benchmark/bert_benchmark/bert_benchmark.py
samples/python/benchmark/throughput_benchmark/throughput_benchmark.py

- Fix flake8-bugbear issue reported by newest release of the package.
- *N/A*

[PyOV][SAMPLES] Fix bugbear issue B038

---

docs/articles_en/openvino_workflow/torch_compile.rst

Replacing environment variables, as per request in the following ticket: 128406
Porting: [22006 ](https://github.com/openvinotoolkit/openvino/pull/22006)

[DOCS] Updating options for torch.compile for 23.3

---

src/plugins/intel_gpu/include/intel_gpu/plugin/variable_state.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/shape_predictor.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/kv_cache.cpp
src/plugins/intel_gpu/src/graph/include/kv_cache_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/read_value.cpp
src/plugins/intel_gpu/src/plugin/variable_state.cpp
src/plugins/intel_gpu/src/runtime/shape_predictor.cpp

- Fixed wrong behavior w.r.t skipped primitives' max_output_layout_size
- Increased can_be_optimized = true hit for kv cache ops 
- Enabled more prealloc for kv cache opts 
- Reduced peak memory required for stateful model by memory sharing b/w kv cache output and variable in the next iteration

[GPU] Optimization for kv cache op

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Excluded softmax from async compilation if it is using optimized shape agnosti kernel
- 129649

[GPU] Excluded softmax from async compilation if it is using optimized shape agnosti kernel

---

src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/plugin/transformations/fc_convert_fusion.cpp
src/plugins/intel_gpu/src/plugin/transformations/fc_convert_fusion.hpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/matmul_si_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/transformations/fc_convert_fusion_test.cpp

- Added internal transformation which fuse `Convert` with `FC` or `FC compressed`
- This is the initial work to finally optimize `FC->Convert->Reshape->Eltwise` pattern
- 128739

[GPU] Fuse type conversion only reorders to the prev FC nodes

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/github/skip_configs/CPU/expected_failures_OP.csv

- *conformance_Gather/ReadIRTest.Inference/Op=Gather.8_Type=i64_Shape=dynamic_IR=e255ef2321233444ce6e4fdeb513a9b271987457aa9bd456948b64f589de1e2b_Device=CPU_Config=(),9.4639279043362649e-05*
- *CVS-129831*

[OP CONFORMANCE] Extend expected_failures_CPU by sporadic failure test

---

src/plugins/intel_cpu/src/nodes/reshape.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/reshape_inplace.cpp

- *Reshape in place is not applicable when input is shared*
- *CVS-128618*

[CPU]Reshape in place is not applicable when input is shared

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/merge_xmls.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/utils/stat_update_utils.py

- *Fix situation when op has several tests with different wights and some of wights much bigger(0.1 and 1.0(-14)) for some of IRs then other. For example tests with big weight IRs are passed , then fail or crash will slightly influence on relative passrate and passrate will be close to 100. Before such values rounded to 100.00 and op could has several crash, but 100 passrate, now it is fixed*

[op conformance] Fix wrong rounding of passrate when it close to 100

---

src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp

- *gemm opt tile should be invalidate for non-simple layout format*
- *128626*

[GPU] gemm opt tile should be invalidate for non-simple layout format

---

.github/workflows/job_onnx_models_tests.yml

ONNX Model tests are consuming all available RAM on the node assigned, let's reduce number of parallel workers and see if they become any slower
- CVS-129447

Decrease number of workers for ONNX Model tests to prevent OOM kills

---

src/plugins/intel_cpu/tests/unit/gemm_api_test.cpp

- *Fix mlas thread partition with odd threads*
- *Ensure that ThreadsPerGemm % ThreadCountM == 0*
- MLAS PR is https://github.com/openvinotoolkit/mlas/pull/10
- *CVS-129832*

[CPU][MLAS]Fix mlas threading with odd threads

---

src/plugins/intel_cpu/src/cpu_shape.cpp
src/plugins/intel_cpu/src/cpu_shape.h
src/plugins/intel_cpu/src/nodes/matmul.cpp
src/plugins/intel_cpu/src/nodes/matmul.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/instances/x64/matmul.cpp

This is a bug fix, which introduces a proper post ops shapes processing when building MatMul primitive attributes.
- 121661

[CPU] Fix the shape processing of nodes fused to MatMul 

---

src/core/include/openvino/op/squared_difference.hpp
src/core/src/op/squared_difference.cpp

- *This pattern was not applied by `Constant folding transformation:`*
- The result after constant folding before fix:
- The result after constant folding after fix:
- *https://jira.devtools.intel.com/browse/CVS-129152*

[TRANSFORMATIONS -> CONSTANT FOLDING] Add evaluate for SqDiff due to using by constant folding

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/include/pass_manager.h
src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp

- We have [similar transformation](https://github.com/openvinotoolkit/openvino/blob/master/src/common/transformations/src/transformations/common_optimizations/swish_fusion.cpp#L42) in ngraph so that pass seem to be redundant

[GPU] Remove internal swish fusion pass

---

src/common/snippets/include/snippets/lowered/expression_factory.hpp
src/common/snippets/include/snippets/lowered/pass/insert_perf_count.hpp
src/common/snippets/src/lowered/expression_factory.cpp
src/common/snippets/src/lowered/pass/insert_perf_count.cpp
src/common/snippets/src/op/subgraph.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_perf_count_rdtsc_emitters.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/perf_count_rdtsc.hpp

- *When PerfCounters are inserted, output descriptors and connectors are automatically created based on the node number of outputs*
- *This leads to ShapeInfer exception "Check 'result.dims.size() == out_descriptors.size()' failed" and inability to use the PerfCounters feature*
- *This PR fixes this behavior*
- *129627*

[Snippets] Fix PerfCount infrastructure

---

src/tests/functional/shared_test_classes/include/shared_test_classes/base/benchmark.hpp

Currently, infer() is not called during `BenchmarkLayerTest` execution. This PR fixes this behavior by adding `infer()` call at the beginning of the overridden `validate()` method (as it is done in base `SubgraphBaseTest` class).

[TESTS] BenchmarkLayerTest base class fix

---

src/plugins/intel_cpu/src/nodes/subgraph.cpp

- *This PR fixes compilation error on Mac with enabled debug capabilities*
- *Error example*:
```
.../openvino/src/plugins/intel_cpu/src/nodes/subgraph.cpp:523:9: error: unknown type name '__sighandler_t'
```

[CPU][ARM] Fixed debug caps build on Mac

---

src/common/snippets/include/snippets/emitter.hpp
src/common/snippets/include/snippets/generator.hpp
src/common/snippets/include/snippets/lowered/expression.hpp
src/common/snippets/include/snippets/lowered/pass/assign_registers.hpp
src/common/snippets/include/snippets/lowered/pass/init_loops.hpp
src/common/snippets/include/snippets/lowered/pass/insert_loops.hpp
src/common/snippets/include/snippets/lowered/port_descriptor.hpp
src/common/snippets/src/emitter.cpp
src/common/snippets/src/generator.cpp
src/common/snippets/src/lowered/expression.cpp
src/common/snippets/src/lowered/linear_ir.cpp
src/common/snippets/src/lowered/pass/assign_registers.cpp
src/common/snippets/src/lowered/pass/cleanup_loop_offsets.cpp
src/common/snippets/src/lowered/pass/init_loops.cpp
src/common/snippets/src/lowered/pass/insert_loops.cpp
src/common/snippets/src/lowered/pass/insert_tail_loop.cpp
src/common/snippets/src/lowered/port_descriptor.cpp
src/common/snippets/src/op/serialization_node.cpp
src/common/snippets/tests/include/lowering_utils.hpp
src/plugins/intel_cpu/src/emitters/snippets/x64/cpu_generator.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/cpu_generator.hpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_container_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_kernel_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_kernel_emitter.hpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.hpp

- *Added `RegType` as part of PortDescriptor - description of expression ports. Now `RegType` is set by output ports and expressions can have different reg types on input and outputs.*
- *Removed non-`MemoryAccess` input `PortConnectors` filtering from `InsertLoops`. Now `LoopEnd` might have inputs with different reg types*
- *N/A*

[Snippets] Added RegType as part of PortDescriptor

---

src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_executable_network/properties.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_plugin/properties.cpp
src/tests/test_utils/functional_test_utils/layer_tests_summary/github/skip_configs/CPU/expected_failures_API.csv

- add ov::execution_devices property support for ov::intel_cpu::Engine
- Closes https://github.com/openvinotoolkit/openvino/issues/22153
- CVS-111344

[CPU][apiConformance] support EXECUTION_DEVICES in ov::intel_cpu::Engine

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/src/graph/include/kv_cache_inst.h
src/plugins/intel_gpu/src/graph/kv_cache.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- To release old variable memory (assigned to readvalue & gather) once the corresponding kv cache is executed)
- (To prevent memory peak for long sequence kv)
- 128982

[GPU] Garbage collection of kv cache memory 

---

src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
src/plugins/intel_cpu/tests/unit/streams_info/streams_e2e_test.cpp
src/plugins/intel_cpu/tests/unit/streams_info/streams_info_table_test.cpp

- *Change number of streams in latency mode on XEON to 1*
- *Update CPU unit test*
- *CVS-129895*

Change number of streams in latency mode on XEON to 1

---

src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp

- *item1*
- *...*
- *[CVS-124663](https://jira.devtools.intel.com/browse/CVS-124663)*

[Op Conformance] Update compare accuracy function

---

src/plugins/intel_cpu/src/emitters/plugin/x64/jit_bf16_emitters.hpp
src/plugins/intel_cpu/src/emitters/plugin/x64/jit_conversion_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/x64/jit_dnnl_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/x64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/x64/jit_emitter.cpp
src/plugins/intel_cpu/src/emitters/plugin/x64/jit_emitter.hpp
src/plugins/intel_cpu/src/emitters/plugin/x64/jit_load_store_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_copy_b_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_container_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_fill_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_horizon_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_kernel_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_memory_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_snippets_emitters.cpp
src/plugins/intel_cpu/src/emitters/utils.cpp
src/plugins/intel_cpu/src/emitters/utils.hpp

- *Added new files `name_` to `jit_emitter` to make exception messages more informative: now each emitter throws exception with prefix `The emitter <name_> ...`.*
- *The example:*
```
./bin/intel64/Release/ov_cpu_func_tests --gtest_filter='*smoke_Snippets*'
[ RUN      ] smoke_Snippets_Eltwise/Add.CompareWithRefImpl/IS[0]=[]_TS[0]=((1.16.29.31))_IS[1]=[]_TS[1]=((1.16.29.1))_T=f32_#N=1_#S=1_targetDevice=CPU
MEM_USAGE=773124KB
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp:90: Failure
Exception from src/inference/src/core.cpp:99:
[ GENERAL_ERROR ] Check 'false' failed at src/plugins/intel_cpu/src/emitters/plugin/x64/jit_emitter.cpp:182:
The emitter jit_nop_emitter throws test exception
unknown file: Failure
C++ exception with description "Exception from …
```

[CPU][Emitters] Add more informative exception messages in emitters

---

.github/workflows/android_arm64.yml
.github/workflows/coverity.yml
.github/workflows/fedora.yml
.github/workflows/job_onnx_runtime.yml
.github/workflows/linux.yml
.github/workflows/linux_arm64.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/webassembly.yml
.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

This should fix the following error during Windows Conditional Compilation build:
```
sccache: error: An attempt was made to access a socket in a way forbidden by its access permissions. (os error 10013)
```

[GHA] Change default port for sccache server to avoid collisions

---

src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
src/common/transformations/src/transformations/common_optimizations/optimize_strided_slice.cpp
src/common/transformations/tests/common_optimizations/optimize_strided_slice_test.cpp

This reverts commit e07602720cc71ffd684342430298d01e29579d6d due to the perf regression.
RoPE fusion pattern is based on StridedSlice.

Revert "Move SliceToStridedSlice conversion from MOC to Common transformations (#21556)"

---

src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_plugin/properties.cpp
src/tests/test_utils/functional_test_utils/layer_tests_summary/github/skip_configs/CPU/expected_failures_API.csv

- Add ov::device::type property support for ov::intel_cpu::Engine
- Add ov::device::architecture property support for ov::intel_cpu::Engine
- *CVS-111344*
- Closes https://github.com/openvinotoolkit/openvino/issues/22153

[CPU] Support DEVICE_TYPE and DEVICE_ARCHITECTURE in CPU plugin

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp

- Tuned FC int4 kernel targeting for LLM on next-gen hardware
- TILE_IFM is increased to 4 by default for int4 weight. If DECOMPRESSION_SCALE_GROUP_SIZE is smaller than TILE_IFM * SIMD, decompression_post_op should be performance in a finer way.
- 127440

[GPU][FC] Tuning for int4

---

.github/workflows/linux.yml

ONNX Model Tests stage in `linux.yml` GitHub Actions workflow has a few infrastructure-related issues, this PR removes the stage from required checks list until we'll stabilize it.

Disable ONNX Models tests until they'll become more stable

---

src/plugins/intel_gpu/include/intel_gpu/op/gemm.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/gemm.hpp
src/plugins/intel_gpu/src/graph/gemm.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/gemm.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.h
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
src/plugins/intel_gpu/src/plugin/transformations/op/gemm.cpp
src/plugins/intel_gpu/src/plugin/transformations/transpose_matmul_fusion.cpp
src/plugins/intel_gpu/src/plugin/transformations/transpose_matmul_fusion.hpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/unit/module_tests/primitive_comparison_test.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/matmul_si_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/transformations/transpose_matmul_fusion_test.cpp

- To fuse `transpose` layers into a `gemm` layer for faster LLM inference
- before: [`transpose`] --> `gemm` --> [`transpose`]
- after: `gemm`
- `gemm` is extended to have `input0_order`, `input1_order` and `output_order` from `transpose` layers
- 127590

[GPU] Extend gemm to fuse transpose layers

---

docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/NPU.rst

Removing the NPU plugin specific (private) properties from the article.
Porting: https://github.com/openvinotoolkit/openvino/pull/22506

[DOCS] Removing NPU plugin specific properties for 23.3

---

src/plugins/intel_cpu/src/nodes/rnn.cpp
src/plugins/intel_cpu/src/nodes/rnn.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/lstm_sequence.cpp

- In theory every input of the node can have distinct value for a dynamic batch size, even it does not make sense from the overall model perspective i.e:
- first input batch size is completely unknown -1
- second input batch size a range (1, 10)
- third input batch size is the concrete value 5
In this example inference will work only when batch size 5 is used for all the inputs, but a model with such configuration still should be able to compile.
- 115477

[CPU] Allow distinct batch size for 'sequence_length' RNN input

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
src/plugins/intel_gpu/tests/functional/dynamic_tests/gpu_dyn_huge_input_range.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/base/ov_subgraph.hpp
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp

missing case that the object allocation is larger than max_alloc_mem_size
| | Windows| Linux |
|--------|--------|--------|
| **Object allocation size is larger than max_alloc_mem_size** | assert | assert |
| Object allocation and allocated size is larger than max_mem_size  | print log | assert |
- 129494

[GPU] assert the allocation size of object is larger than max_alloc_mem_size

---

tools/mo/openvino/tools/mo/utils/telemetry_utils.py
tools/ovc/openvino/tools/ovc/telemetry_utils.py

Telemetry is a singleton class and if it was already initialized in another tool some parameters will be incorrect, including application name and version.
Solution: 
If Telemetry was initialized in another tool we need to force reinitialization of telemetry to set correct parameters.
Ticket: CVS-130856
Code:
Validation:
Documentation:

[Telemetry ] Fixed initialization of Telemetry.

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp

- Fixed kv cache primitive's crash when the execution sequence is as follows
- input shapes => reset variable => same input shapes
- 130849

[GPU] Fixed KV cache crash for a corner case

---

src/frontends/pytorch/src/op/leaky_relu.cpp
src/inference/src/dev/plugin.cpp

- Conditional compilation build fails due to multiple warnings: 
` src\inference\src\dev\plugin.cpp(34): warning C4101: 'ex': unreferenced local variable`
Fix these warnings + remove legacy ie exception handling
- Fix 
`src\frontends\pytorch\src\op\leaky_relu.cpp(19): warning C4305: 'initializing': truncation from 'double' to 'float'`
- *ticket-id*

Fix windows conditional compilation build

---

.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

[CI] [GHA] Download `ninja` from GitHub instead of installing through `choco` in Windows workflows

---

tests/model_hub_tests/torch_tests/test_timm.py

- *Tests start to take longer then 6h with export testing. Disable export in timm tests until problem with timeout is solved*
- *None*

[GHA] Disable export in timm tests until problem with timeout is solved

---

docs/dev/build_linux.md
docs/dev/build_windows.md

- Add a small note for users to adjust number of jobs in `cmake --build . --parallel <number_of_jobs>`
- for `build_linux.md` and `build_windows.md`
- Closes #22474

[DOCS] Specify number of jobs in build docs

---

src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/matrix_nms.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/multiclass_nms.cpp
src/plugins/template/tests/functional/op_reference/base_reference_test.cpp
src/tests/functional/plugin/shared/src/behavior/ov_infer_request/infer_correctness.cpp
src/tests/functional/shared_test_classes/src/single_op/generate_proposals.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/data_utils.hpp

- Add raw data comparison into test utils. It is now almost full copy of LayerTestsCommon::Compare
- Use this new comparator instead of legacy LayerTestsCommon::Compare
- CVS-131226

Add raw data comparison into test utils

---

.github/workflows/send_workflows_to_opentelemetry.yml

This PR introduces a GitHub Actions workflow which will be run after each of the specified workflow runs and send their telemetry to a third-party service (which can be replaced later) in OpenTelemetry format. This is not intended for production use yet.

[GHA] Testing solution for GitHub Actions workflows telemetry

---

docs/articles_en/documentation/openvino_ir/operation_sets/operations_specifications/quantization/FakeConvert_13.rst

- Aligned formula of scaling in FakeConvert spec with the [POC](https://github.com/andreyanufr/openvino/blob/57d566070997e6a6194bfa48323f9854327d0def/src/core/src/op/convert_fp8.cpp#L429-L436) by @andreyanufr and reference implementation:
https://github.com/openvinotoolkit/openvino/blob/cb679a73c9959c05e2c1ad0e01b12d13d71771a9/src/core/reference/include/openvino/reference/fake_convert.hpp#L43
- Aligned with: https://github.com/openvinotoolkit/openvino/pull/22433
- It was described in the reversed order unintentionally
- N/A

[Spec] Align order of scaling formula in FakeConvert spec

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/src/graph/include/kv_cache_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/kv_cache.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- If kv caches are reallocated and copied at one time, there will be a memory peak at that inference. 
- Distributed kv cahce allocation period to prevent that issue as a temporal quick solution
- 128982

[GPU] Distributed kv cache allocatio to prevent memory peak

---

src/core/docs/api_details.md
src/core/include/openvino/core/core.hpp
src/core/include/openvino/core/node.hpp
src/core/include/openvino/core/type.hpp
src/core/include/openvino/op/interpolate.hpp
src/core/include/openvino/op/util/variable_value.hpp
src/core/include/openvino/opsets/opset.hpp
src/core/include/openvino/pass/pass.hpp
src/core/include/openvino/pass/pass_config.hpp
src/core/include/openvino/pass/serialize.hpp
src/core/shape_inference/include/pooling_shape_inference_util.hpp
src/core/shape_inference/include/utils.hpp
src/core/src/op/experimental_detectron_topkrois.cpp
src/core/src/op/max_pool.cpp
src/core/src/op/non_max_suppression.cpp
src/core/src/op/proposal.cpp
src/core/src/op/reduce_logical_and.cpp
src/core/src/op/util/gather_base.cpp
src/core/src/op/util/variable_value.cpp
src/core/src/pass/manager.cpp
src/core/src/pass/serialize.cpp
src/core/src/pass/visualize_tree.cpp
src/core/src/pattern/matcher.cpp
src/core/tests/type_prop/batch_to_space.cpp
src/core/tests/type_prop/depth_to_space.cpp
src/core/tests/type_prop/variadic_split.cpp
src/core/tests/visitors/visitors.hpp

- Cleans up `src/core` from unneeded suppression switches, comments and such remains of legacy API drop.
- CVS-131716

[Core] Remove deprecated leftovers

---

.github/workflows/android_arm64.yml
.github/workflows/fedora.yml
.github/workflows/linux_arm64.yml
.github/workflows/webassembly.yml

To remove duplication while we don't need post-commit artifacts. Will need to notify people who are monitoring & reporting sporadic

[GHA] Remove push trigger from workflows running in full scope in merge queue

---

src/plugins/intel_gpu/src/graph/loop.cpp

- Get layout from prim_inst output layout instead of cldnn::memory to avoid getting wrong shape which is changed by faked alignment in fc.
- 114920

[GPU] get layout from prim_inst output layout instead of cldnn::memory

---

src/plugins/intel_cpu/tests/functional/custom/behavior/export_import.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

Disable the sporadically failing `ExportImportTest` test for AMX platforms.
- 131475

[CPU] Disable ExportImportTest for AMX platforms

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp

- This PR fixes the accuracy on dGPUs in LLMs compressed models. oneDNN can't handle dynamic paddings properly, so change impl back to ocl.
- 131241

[GPU] Do not use oneDNN impls with dynamic paddings

---

src/frontends/tensorflow_lite/src/graph_iterator_flatbuffer.cpp
src/frontends/tensorflow_lite/src/op/op_translation_utils.hpp

Fix names aka locations of operations in TFLite FrontEnd
Give different names to binary operations with fused activations
- *CVS-131328, CVS-111341*

Fix names aka locations of operations in TFLite FrontEnd

---

src/common/transformations/src/transformations/fp16_compression/mark_subgraphs_to_keep_in_mixed_precision.cpp
src/common/transformations/tests/common_optimizations/mark_subgraph_to_keep_in_mixed_precision_test.cpp

- *Exclude Gather from sensitive prc types *
- *Add handling of `Const fp16 ->Gather -> Pow` pattern*
- *https://jira.devtools.intel.com/browse/CVS-127678*

[TRANSFORMATIONS] Exclude Gather from Mixed prc propagation

---

src/plugins/intel_gpu/src/graph/gemm.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp

- Fixed `gemm::calc_output_layout()` to consider `output_order`
- Fixed `gemm_ref` for output transposed cases
- Fixed wrong matmul axis (K- axis) selection for 2/3 dim inputs
- Updated `gemm_tiled_opt` to support padded inputs
- 131014

[GPU] Fix gemm_ref and gemm_tiled_opt

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/unit/passes/add_required_reorders_test.cpp
src/plugins/intel_gpu/tests/unit/passes/reorder_inputs_test.cpp

- *Do not change the input layout going into RDFT node by adding inappropriate reorder to increase rank by 1 because RDFT will increase it*
- *Set preferred input format rather than leaving it as format::Any in get_preferred_format() of layout_optimizer*
- *Remove test case which has been implemented based on wrong behavior of RDFT* 
- *The test case was implemented assuming that when input and output dimension of RDFT are different, a reorder node should be added.*
- *But input and output dimension of RDFT are originally different depending on spec.*
- *130921*
- *131412*

[GPU] Don't increase rank by reorder before RDFT

---

src/common/transformations/include/transformations/utils/utils.hpp
src/common/transformations/src/transformations/op_conversions/convert_matrix_nms_to_matrix_nms_ie.cpp
src/common/transformations/src/transformations/op_conversions/convert_maxpool_downgrade.cpp
src/common/transformations/src/transformations/op_conversions/convert_multiclass_nms_to_multiclass_nms_ie.cpp
src/common/transformations/src/transformations/op_conversions/convert_nms9_to_nms_ie_internal.cpp
src/common/transformations/src/transformations/op_conversions/convert_nms_rotated_to_nms_ie_internal.cpp
src/common/transformations/src/transformations/op_conversions/convert_nms_to_nms_ie_internal.cpp
src/inference/src/dev/icompiled_model.cpp
src/inference/src/model_reader.cpp

- Such names are created as `operation_name.<port index>` which are not needed in OpenVINO 2.0, because it's legacy behavior.
- Plugins should migrate to `ov::ISyncInferRequest::find_port` which can return index and port type (input or output) and work with this index (if required) instead of port **_legacy_** names.

Deprecated functions to operate with legacy port names

---

src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/conv_sum_broadcast.cpp

`FuseConvolutionSumAndConvolutionSumActivation`: fixed a mistake in dynamic broadcast pattern check.
- *CVS-129631*

[CPU] FuseConvolutionSum: fixed a mistake in dynamic bcast pattern check

---

src/common/snippets/include/snippets/lowered/loop_manager.hpp
src/common/snippets/include/snippets/lowered/pass/insert_tail_loop.hpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/fuse_loops.cpp
src/common/snippets/src/lowered/pass/init_loops.cpp
src/common/snippets/src/lowered/pass/insert_buffers.cpp
src/common/snippets/src/lowered/pass/insert_loops.cpp
src/common/snippets/src/lowered/pass/insert_tail_loop.cpp
src/common/snippets/src/lowered/pass/move_result_out_of_loop.cpp
src/common/snippets/src/lowered/pass/split_loops.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.cpp

- *On the master we [create](https://github.com/openvinotoolkit/openvino/blob/03a5be788a82e1b50736947fba88c3002074e13d/src/common/snippets/src/lowered/pass/insert_tail_loop.cpp#L135) copy of subloop in `InsertTailLoop` and [compare](https://github.com/openvinotoolkit/openvino/blob/03a5be788a82e1b50736947fba88c3002074e13d/src/common/snippets/src/lowered/loop_manager.cpp#L367) with iterators of linear IR before copy [insertion](https://github.com/openvinotoolkit/openvino/blob/03a5be788a82e1b50736947fba88c3002074e13d/src/common/snippets/src/lowered/pass/insert_tail_loop.cpp#L199) to this LinearIR. It leads to comparison of iterators from the different collections. The PR changes the order of these action*
- *Adds brief descriptions to `LoopManager` interface*
- *Added interface …

[Snippets] Fixed iterator comparison from different lists

---

.github/workflows/linux.yml

- Temporarily increase the timeout for Conformance op tests (the root cause is to be investigated)
- 131820

[GHA] Increase timeout for Conformance tests

---

src/common/transformations/include/transformations/common_optimizations/compress_float_constants.hpp
src/common/transformations/src/transformations/common_optimizations/compress_float_constants.cpp

- It was required for old API only

Removed AddOldApiMapToParameters during FP16 weights compression

---

src/plugins/intel_gpu/src/graph/compilation_context.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Do not make spurious task. It caused memory leak from task_key and promise objects.
- keys are generated before queueing and it was not removed when cache entry is not added into lru impl cache.
- This mostly fix memory leak and reduces permanent cache size.
- Remaining issue for memory leak: futures are just added without freeing.
- 131417

[GPU] Exclude gemm from async compilation if the primimtive's dynamic impl is optimized kernel.  

---

src/inference/src/dev/core_impl.cpp
src/inference/tests/functional/import_model.cpp

- Throws when empty Remote Context is provided to `ov::CoreImpl::import_model(..)`
- CVS-128924

[IE] Throw if empty context on model import

---

src/bindings/python/src/openvino/runtime/utils/data_helpers/data_dispatcher.py
src/bindings/python/tests/test_utils/test_data_dispatch.py
src/bindings/python/tests/utils/helpers.py

- Add missing flag propagation in containers dispatchers for memory sharing scenarios.
- Expected boost in cases of already aligned memory storages with `__array__` interface, i.e. PyTorch tensors.
- Added testcases.
- *132092*

[PyOV] Add missing is_shared flag in memory sharing scenarios 

---

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/gather.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/strided_slice.cpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/stateful_model.cpp

- cpu impls that are skiped at runtime should not do anything because it may overwrite the parent node's memory which might be shared with other nodes 
- *ticket-id*

[GPU] Allow cpu impl to be skipped

---

src/plugins/intel_gpu/src/plugin/transformations/transpose_matmul_fusion.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp

- Some layers (e.g. VariadicSplit) does not have the default output index. This PR fixes the tr_matmul_tr transformation pass to use explicit output indexes.
- 131014
- 131032

[GPU] Use explicit output indexes in the tr_matmul_tr transformation pass

---

thirdparty/protobuf/CMakeLists.txt

- Required for compatibility with NPU repo, where dependencies can set `HAVE_ZLIB` cmake cache variables, which affects `protobuf` during rebuild.
- CVS-130134

Unset HAVE_ZLIB which can be set by external projects

---

src/plugins/intel_cpu/src/shape_inference/shape_inference.cpp

- Avoid memory copying during `ov::Constant` creation
- Important for very big inputs like in vLLM case

Fixed performance of CPU ShapeInferFallback case

---

src/inference/dev_api/openvino/runtime/threading/istreams_executor.hpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *After the https://github.com/openvinotoolkit/openvino/pull/22414 Snippets passes get incorrect thread count per stream in CPU Plugin  - `config.threadsPerStream` equals to `0` so plugin sets `concurrency = parallel_get_max_threads()`. The real count of threads per stream is inited in `streamExecutorConfig` on this stage. The PR returns the previous behavior*
- *N/A*

[CPU][Snippets] Fixed thread count per stream in tokenization config

---

tools/ovc/openvino/tools/ovc/convert.py
tools/ovc/openvino/tools/ovc/help.py

- "To disable all extensions including those that are placed at the default location, pass an empty string." - this line applies only to legacy MO.
- 132289

[OVC] Removed wrong text from extension parameter description.

---

.github/workflows/ovc.yml

Since OVC workflow uses path filters, the common status job is needed to make this workflow required

[GHA] Add common status for OVC pipeline

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/border_gpu_ref.cl
src/plugins/intel_gpu/src/plugin/transformations/transpose_matmul_fusion.cpp
src/plugins/intel_gpu/tests/unit/test_cases/border_gpu_test.cpp

- fixes the tr_matmul_tr transformation pass to use explicit output indexes to transpose layers
- fixes `border_gpu_ref` kernel to consider pad-info inputs with rank less than 4
- 131014
- 131032

[GPU] Fixes for gemm and border

---

docs/articles_en/openvino_workflow/running_inference_with_openvino/dldt_deployment_optimization_guide/dldt_deployment_optimization_latency/Model_caching_overview.rst

Removing the note about GPU support for static models only, as GPU now supports both type of shapes. Porting: https://github.com/openvinotoolkit/openvino/pull/22802

[DOCS] Removing the note about GPU support for static models only

---

src/plugins/intel_cpu/src/nodes/deconv.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/convolution_backprop_data_transformation.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/convolution_backprop_data_transformation.cpp
src/tests/functional/plugin/shared/src/low_precision_transformations/convolution_backprop_data_transformation.cpp
src/tests/ov_helpers/ov_lpt_models/src/convolution_backprop_data.cpp

- *Added supported ranks in `canBeExecutedInInt8`*
- *`getSupportedDescriptors`: added 3D case handling*
- *Added 3D ConvolutionBackpropData test cases to LPT plugin tests*
- *CVS-132070*

[CPU] Fixed descriptor creation bug for 3D quantized deconvolution

---

src/inference/include/openvino/runtime/core.hpp
src/inference/src/cpp/core.cpp
src/inference/tests/functional/ov_core_test.cpp

- It may be not secure for software vendors which are using OpenVINO if `custom_plugins.xml` will be loaded from CWD first over OV. So, for now, if `custom_plugins.xml` exists in OV folder, it will be used first. Otherwise, load `custom_plugins.xml` from CWD
Improvement for https://github.com/openvinotoolkit/openvino/pull/22525
- CVS-131048

Enhance searching of plugins XML configuration

---

src/frontends/onnx/frontend/src/op/layer_normalization.cpp
src/frontends/onnx/tests/tests_python/test_backend.py

- *LayerNormalization-17 translation got more compact*
- *Three output translation is unavailable anymore*
- *CVS-132128*

Supports onnx LayerNormalization-17 via opset6::MVN

---

src/plugins/intel_cpu/src/nodes/interpolate.cpp

Incorrect arguments were passed to the "store" emitter in the Interpolate JIT kernel generation program.
- 130883

[CPU] Fix store call in JIT Interpolate

---

docs/articles_en/openvino-workflow/model-preparation.rst

**Details:** Remove WA step in showcase for TF Hub model. Now it is no longer needed to use temporal directory for conversion. It can be passed directly from memory.

[DOC][TF FE] Remove WA step in showcase

---

src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/convolution.cpp

Bring back JIT convolution oneDNN primitives for avx2 platforms.

[CPU] Use JIT conv primitves for avx2

---

src/plugins/intel_cpu/src/compiled_model.cpp

Due to #22414 merge, number of streams in `CompiledModel` were unexpectedly changed. This PR restores the old logic: number of steams is taken from `m_cfg.streamExecutorConfig` instead of `m_cfg`.
- *CVS-132300*

Reverted wrong changes in CompiliedModel related to number of streams

---

src/common/transformations/include/ov_ops/type_relaxed.hpp
src/core/src/pass/serialize.cpp
src/plugins/intel_cpu/src/extension.cpp

- `TypeRelaxed` operations to have dedicated opset during serialize / deserialize to avoid mixing with official OpenVINO operations.
- CVS-130765

Fixed deserialization with type relaxed operations

---

src/plugins/intel_gpu/include/intel_gpu/primitives/gemm.hpp
src/plugins/intel_gpu/src/plugin/transformations/transpose_matmul_fusion.cpp

- Performance was degraded due to fusion of transpose and matmul in some models.
- This PR restricts fusion of transpose and matmul for static matmul layers.
- 131959

[GPU] Allow fusion of transpose and matmul only for dynamic layers

---

.github/actions/setup_python/action.yml
.github/workflows/android_arm64.yml
.github/workflows/build_doc.yml
.github/workflows/code_snippets.yml
src/bindings/python/src/openvino/runtime/utils/data_helpers/data_dispatcher.py
src/bindings/python/tests/test_utils/test_data_dispatch.py
src/bindings/python/tests/utils/helpers.py
src/plugins/intel_cpu/src/shape_inference/shape_inference.cpp
vcpkg.json

- https://github.com/openvinotoolkit/openvino/pull/22606
- https://github.com/openvinotoolkit/openvino/pull/22734
- https://github.com/openvinotoolkit/openvino/pull/22776
- https://github.com/openvinotoolkit/openvino/pull/22820
- https://github.com/openvinotoolkit/openvino/pull/22827

Ported several PRs from master to 2023.3 LTS

---

docs/articles_en/about-openvino/compatibility-and-support/supported-operations-framework-frontend.rst
docs/articles_en/learn-openvino/openvino-samples/benchmark-tool.rst
docs/dev/build_android.md
docs/dev/installing.md

Port from https://github.com/openvinotoolkit/openvino/pull/22852
Removing mentions of deprecated Inference Engine (API 1.0) in docs
Jira: 131850

[DOCS] Removal of Inference Engine from 2024.0

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *Moved lambda functions that are used in callbacks to the one visible area with manager. Before when callbacks of the passes called these lambda functions `is_supported_matmul` and `is_unsupported_parallel_work_amount`, these functions were destroyed with `If` body in `void Transformations::MainSnippets`*
- *132849*

[Snippets][CPU] Fixed AddressSanitizer: stack-use-after-scope

---

tests/stress_tests/.automation/memcheck_tests/nightly_configs/desktop_test_config.xml
tests/stress_tests/.automation/memcheck_tests/precommit_configs/desktop_test_config.xml
tests/stress_tests/.automation/memcheck_tests/weekly_configs/desktop_test_config.xml
tests/stress_tests/.automation/unittests/nightly_configs/desktop_test_config.xml
tests/stress_tests/.automation/unittests/weekly_configs/desktop_test_config.xml
tests/stress_tests/common/ie_pipelines/pipelines.cpp
tests/stress_tests/common/ie_pipelines/pipelines.h
tests/stress_tests/common/infer_api/infer_api.cpp
tests/stress_tests/common/infer_api/infer_api.h
tests/stress_tests/common/tests_utils.cpp
tests/stress_tests/common/tests_utils.h
tests/stress_tests/memcheck_tests/tests.cpp
tests/stress_tests/memleaks_tests/tests.cpp
tests/stress_tests/unittests/tests.cpp
tests/stress_tests/unittests/tests_pipelines/tests_pipelines.cpp
tests/stress_tests/unittests/tests_pipelines/tests_pipelines.h
tests/stress_tests/unittests/tests_pipelines/tests_pipelines_full_pipeline.cpp

Run of tests with `api_version=1` causes `Unsupported API version` runtime error
- CVS-129879

Get rid of API1.0 in `stress_tests`

---

.github/workflows/job_python_unit_tests.yml
.github/workflows/linux.yml
.github/workflows/windows.yml
tests/layer_tests/common/layer_utils.py
tests/layer_tests/common/utils/common_utils.py

**Details:** We are going to test OpenVINO Tokenizers conversion extensions by FE layer tests. It gives better quality integration between openvino and openvino-tokenizers. For example, operation on string tensors such as tf.raw_ops.StringLower, tf.raw_ops.StringSplitV2 will supported via OV tokenizers near feature until we move them into core part.
**Ticket:** 132667

[TF FE][OV Tokenizers] Deploy use of OpenVINO Tokenizers in FE layer tests

---

src/plugins/auto_batch/src/compiled_model.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- Observed functional test failure in auto-batch plugin and hetero plugin side in tickets-131699.
- Meta plugin not support DEVICE_ID property now.
- Auto-batch plugin should support SUPPORTED_PROPERTIES property.
- *131699*

[HETERO][AUTO BATCH] Fix properties test case

---

src/core/shape_inference/include/utils.hpp
src/core/tests/shape_inference_utils_test.cpp
src/core/tests/utils_tests.cpp

Fixed a bug in get_input_bounds(), where method tries to access input at specified port, but operator does not have anything attached at that port - the result was a crash. 
This situation was encountered when calling shape_infer() method with slice op, which did not have any attached inputs.

[BUGFIX][shapeinference]: Fixed a bug in get_input_bounds with op with no input on specifed port

---

docs/articles_en/about-openvino/release-notes-openvino.rst
docs/articles_en/openvino-workflow/deployment-locally.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference/high-level-performance-hints.rst
docs/sphinx_setup/api/api_reference.rst
samples/cpp/benchmark_app/main.cpp
src/bindings/python/src/openvino/__init__.py
tools/benchmark_tool/openvino/__init__.py
tools/mo/openvino/__init__.py
tools/openvino_dev/src/openvino/__init__.py
tools/ovc/openvino/__init__.py

Changing references from "OpenVINO API 2.0"  to "OpenVINO API", as mentioned in https://github.com/openvinotoolkit/openvino/pull/22873#discussion_r1492115073

[DOCS] Update OpenVINO API references

---

src/plugins/auto/tests/unit/compile_model_metric_test.cpp

- disable a invalid case, shouldn't make arbitrary assumptions when there is thread compiling in background
- 131628

fix sporadic failure in auto unit test

---

src/common/transformations/src/transformations/op_conversions/convert_sequences_to_tensor_iterator.cpp
src/common/transformations/tests/op_conversions/convert_sequences_to_ti_test.cpp

- Fix `convert_seq_to_ti` transformation  with enabled mask
- CVS-128000

[ TRANSFORMATIONS ] Fix `convert_seq_to_ti` transformation  with enabled mask

---

src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_items_class_optimized.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/softmax.cpp

- Disabled incorrect blocked IO usage for the cases when pitch over softmax axis dimension > 1 
- #22851

[GPU] Fix softmax class optimized kernel
