- docs/install_guides/installing-openvino-runtime.md
Porting: https://github.com/openvinotoolkit/openvino/pull/17353
Fixing broken links in the article
> [DOCS] Install OpenVINO™ Runtime - fixing links - for 23.0

- src/frontends/tensorflow/src/frontend.cpp
- src/frontends/tensorflow/tests/convert_unsupported.cpp
**Details:** Refer Frontend Extension page in case unsupported operations
> [TF FE] Refer Frontend Extension page in case unsupported operations

- src/common/low_precision_transformations/src/concat.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/concat_transformation.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/concat_transformation.cpp
- src/tests/functional/plugin/shared/include/low_precision_transformations/concat_transformation.hpp
- src/tests/functional/plugin/shared/src/low_precision_transformations/concat_transformation.cpp
- src/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/concat_function.hpp
- src/tests/ngraph_helpers/lpt_ngraph_functions/src/concat_function.cpp
- *Concat: different branch precisions support*
- *108256*
> [LPT] Concat: different branch precisions support

- src/frontends/pytorch/src/op/avg_poolnd.cpp
- src/frontends/pytorch/src/op/max_poolnd.cpp
- tests/layer_tests/pytorch_tests/test_pooling.py
- *Cherry-pick #17337 *
- *107347*
> [PT FE] Support default strides for avg and max pooling (#17337)

- src/bindings/python/src/openvino/frontend/pytorch/decoder.py
- tests/layer_tests/mo_python_api_tests/test_mo_convert_pytorch.py
- tools/mo/openvino/tools/mo/convert_impl.py
- *Cherry-pick #17338 *
- *109831*
> [PT FE] Improve exception when decoder cannot trace or script the model

- src/frontends/tensorflow_lite/src/op/space_to_depth.cpp
- src/frontends/tensorflow_lite/src/op_table.cpp
- *Segment Sum translator requests names now -- need a rename on tfl side*
> Segment Sum renamed in common lib

- docs/Extensibility_UG/Intro.md
- docs/MO_DG/Deep_Learning_Model_Optimizer_DevGuide.md
- docs/MO_DG/prepare_model/Model_Optimizer_FAQ.md
- docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_Object_Detection_API_Models.md
- docs/MO_DG/prepare_model/customize_model_optimizer/Customize_Model_Optimizer.md
- docs/MO_DG/prepare_model/customize_model_optimizer/Extending_Model_Optimizer_with_Caffe_Python_Layers.md
- docs/MO_DG/prepare_model/customize_model_optimizer/Model_Optimizer_Extensions.md
- docs/MO_DG/prepare_model/customize_model_optimizer/Model_Optimizer_Extractor.md
- docs/MO_DG/prepare_model/customize_model_optimizer/Model_Optimizer_Operation.md
- docs/MO_DG/prepare_model/customize_model_optimizer/Model_Optimizer_Ports_Connections.md
- docs/MO_DG/prepare_model/customize_model_optimizer/Model_Optimizer_Transformation_Extensions.md
- docs/_static/images/MO_connection_example_1.svg
- docs/_static/images/MO_conversion_pipeline.svg
- docs/_static/images/MO_graph_after_extractors.svg
- docs/_static/images/MO_graph_after_loader.svg
- docs/_static/images/MO_graph_before_partial_inference.svg
- docs/_static/images/MO_ports_example_1.svg
- docs/_static/images/MO_ports_example_2.svg
- docs/_static/images/MO_transformations_graph.svg
- docs/img/MO_connection_example_1.png
- docs/img/MO_conversion_pipeline.png
- docs/img/MO_graph_after_extractors.png
- docs/img/MO_graph_after_loader.png
- docs/img/MO_graph_before_partial_inference.png
- docs/img/MO_ports_example_1.png
- docs/img/MO_ports_example_2.png
- docs/img/MO_transformations_graph.png
**Port from https://github.com/openvinotoolkit/openvino/pull/15931**
* Divided MO Extensibility article into separate smaller articles,
* Applied the suggestion from https://github.com/openvinotoolkit/openvino/pull/15679
* Recreated images in svg format
* Fixing directives
> [DOCS] Legacy MO Extensibility update for 23.0

- docs/OV_Runtime_UG/auto_device_selection.md
- docs/OV_Runtime_UG/ov_dynamic_shapes.md
- docs/OV_Runtime_UG/performance_hints.md
- docs/OV_Runtime_UG/supported_plugins/CPU.md
- docs/OV_Runtime_UG/supported_plugins/GPU.md
- docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
- docs/snippets/ov_dynamic_shapes.c
- docs/snippets/ov_dynamic_shapes.cpp
- docs/snippets/ov_dynamic_shapes.py
Recreation of BDTI PRs for 23.0. Port from https://github.com/openvinotoolkit/openvino/pull/16913
Recreated PRs:
* https://github.com/openvinotoolkit/openvino/pull/15216
* https://github.com/openvinotoolkit/openvino/pull/14793
* https://github.com/openvinotoolkit/openvino/pull/12067
> [DOCS] Recreation of BDTI PRs - 23.0

- .ci/azure/linux.yml
- src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend.py
- tests/layer_tests/pytest.ini
- tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
- tests/layer_tests/pytorch_tests/test_adaptive_avg_pool3d.py
- tests/layer_tests/pytorch_tests/test_adaptive_max_pool_2d.py
- tests/layer_tests/pytorch_tests/test_add.py
- tests/layer_tests/pytorch_tests/test_batch_norm.py
- tests/layer_tests/pytorch_tests/test_convolution.py
- tests/layer_tests/pytorch_tests/test_relu.py
- Added torchscript backend to OpenVINO
- Added an environment variable to enable torchscript backend USE_TS_BACKEND
- *ticket-id*
> Added Torchscript backend

- src/frontends/tensorflow/src/frontend.cpp
- src/frontends/tensorflow/src/graph_iterator_meta.cpp
- src/frontends/tensorflow/src/graph_iterator_meta.hpp
- src/frontends/tensorflow/src/graph_iterator_proto.hpp
- src/frontends/tensorflow/src/graph_iterator_proto_txt.hpp
- tools/mo/unit_tests/moc_tf_fe/conversion_basic_models_test.py
- tools/mo/unit_tests/moc_tf_fe/conversion_incorrect_models_test.py
**Details:** Handle incorrect models (empty, fake) by TF FE
**Ticket:** 109938
> [TF FE] Handle incorrect models (empty, fake) by TF FE

- docs/MO_DG/prepare_model/Model_Optimizer_FAQ.md
- port of https://github.com/openvinotoolkit/openvino/pull/17222 to 2023.0
- xxx-99850
> renumber FAQ

- docs/Extensibility_UG/Intro.md
- docs/Extensibility_UG/frontend_extensions.md
- docs/snippets/CMakeLists.txt
- docs/snippets/ov_extensions.cpp
- docs/snippets/ov_extensions.py
- src/frontends/pytorch/src/node_context.cpp
- tests/layer_tests/py_frontend_tests/test_torch_frontend.py
> Update docs for frontend extensions

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
Now, we can support below dump naming rule.
- Exec_graph name
- Regular express
- Case-insensitive name searching
New introduces OV_GPU_xxx
- OV_GPU_ListLayers = 1 (Show layer names and exit)
- OV_GPU_VerboseColor = 1 (Show color verbose)
Add file, line, function in log prefix
- *106742*
> [GPU] Improve dump naming rule in debug feature.

- src/frontends/tensorflow/src/frontend.cpp
- src/frontends/tensorflow/src/graph_iterator_meta.cpp
- src/frontends/tensorflow/src/graph_iterator_meta.hpp
- src/frontends/tensorflow/src/graph_iterator_proto.hpp
- src/frontends/tensorflow/src/graph_iterator_proto_txt.hpp
- tools/mo/unit_tests/moc_tf_fe/conversion_basic_models_test.py
- tools/mo/unit_tests/moc_tf_fe/conversion_incorrect_models_test.py
**Details:** Handle incorrect models (empty, fake) by TF FE
**Ticket:** 109938
PR to master: https://github.com/openvinotoolkit/openvino/pull/17408
> [TF FE] Handle incorrect models (empty, fake) by TF FE (#17408)

- tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py
> benchmark_app/py fill batch dim correctly

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_kernel_ref.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gather_gpu_test.cpp
- *Gather layer in rnnt prediction model has out of order index and this cause random value for the input*
- *106886*
> [GPU] rnnt accuracy degradation

- src/tests/ie_test_utils/common_test_utils/graph_comparator.hpp
- Delete limitation for value size in graph comparator
- CVS-110146
> Fix IR comparison tests

- docs/optimization_guide/dldt_deployment_optimization_guide.md
- docs/optimization_guide/memory_optimization_guide.md
- From time to time we receives issues with "false positive memory leak" caused by allocator behavior. So I prepare document where describe ways to optimize memory usage and determine real application leaks
- [CVS-108277](https://jira.devtools.intel.com/browse/CVS-108277)
> Prepare "memory_optimization_guide.md"

- src/core/shape_inference/include/dimension_util.hpp
- src/core/tests/type_prop/binary_convolution.cpp
- src/core/tests/type_prop/convolution.cpp
- src/core/tests/type_prop/max_pool.cpp
- Cherry-pick from master to release: https://github.com/openvinotoolkit/openvino/pull/17197
- *CVS-109316*
> [Shape inference] Pooling: Dimension div fix (#17197)

- src/plugins/intel_gpu/src/graph/impls/ocl/eltwise.cpp
- Fix of windows fails of eltwise broadcast with one input. 
- 99025
> [GPU] fix eltwise with one input

- src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp
- fix CanPropagateForwardThrough add Concat to the list of supported operations
- 110506
> add Concat to CanPropagateForwardThrough

- src/inference/src/dev/threading/cpu_streams_executor.cpp
- src/inference/src/system_conf.cpp
- *disable set_cpu_used in 2023.0 release*
- *CVS-110077*
> HOT FIX: disable set_cpu_used in 2023.0 release

- src/inference/src/dev/threading/cpu_streams_executor.cpp
- src/inference/src/system_conf.cpp
- *disable set_cpu_used in master branch*
- *110077*
> HOT FIX: disable set_cpu_used in master branch

- src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/fetch_weights.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_weights.cl
- src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/reorder/reorder_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/tensor_type.cpp
- src/plugins/intel_gpu/src/kernel_selector/tensor_type.h
- src/plugins/intel_gpu/src/runtime/format.cpp
- *New format is required to accordance OneDNN requirements for Convolution*
> [GPU] Added os_is_yx_osv16_isv2 format

- src/plugins/intel_gna/src/backend/gna_limitations.cpp
- src/plugins/intel_gna/src/backend/gna_limitations.hpp
- src/plugins/intel_gna/src/common/graph_utils.hpp
- src/plugins/intel_gna/src/gna_graph_patterns.hpp
- src/plugins/intel_gna/src/gna_plugin.cpp
- src/plugins/intel_gna/src/gna_transformations_pipeline.cpp
- src/plugins/intel_gna/src/gna_transformations_pipeline.hpp
- src/plugins/intel_gna/src/pre_post_process/transposition_info.cpp
- src/plugins/intel_gna/src/transformations/insert_copy_layer.cpp
- src/plugins/intel_gna/src/transformations/insert_identity_layer.cpp
- src/plugins/intel_gna/src/transformations/markup_fusable_transpose.cpp
- src/plugins/intel_gna/src/transformations/pwl_approximation.cpp
- src/plugins/intel_gna/src/transformations/remove_in_out_processing.cpp
- src/plugins/intel_gna/src/transformations/remove_in_out_processing.hpp
- src/plugins/intel_gna/src/transformations/remove_pre_post_processing.cpp
- src/plugins/intel_gna/src/transformations/remove_pre_post_processing.hpp
- src/plugins/intel_gna/src/transformations/split_eltwise.cpp
- src/plugins/intel_gna/src/transformations/utils/transformation_helper.cpp
- src/plugins/intel_gna/src/transformations/utils/transformation_helper.hpp
- src/plugins/intel_gna/tests/functional/preprocess_tests/gather_transpose_cpu.cpp
- src/plugins/intel_gna/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
- src/plugins/intel_gna/tests/unit/gna_get_aligned_split_sizes.cpp
- src/plugins/intel_gna/tests/unit/ops/util_test.cpp
- Added transformation to remove gather and transpose layers connected to network's inputs and outputs
- Created pre/post processing  models with gather/transpose layers 
- Added tests
Depends on https://github.com/openvinotoolkit/openvino/pull/15691
- *97803*
- *82561*
> [GNA] Extract gathers and transposes

- .github/workflows/stale_prs_and_issues.yml
- Add `exempt-pr-labels` parameter with `keep_fresh` label value to Stale PRs and Issues GitHub Workflow
- The label hasn't been created yet - **maybe it should be called differently? Any suggestions?**
- The label is needed for https://github.com/openvinotoolkit/openvino/issues/17502, but is useful overall
- N/A
> Add `exempt-pr-labels` entry to `stale_prs_and_issues.yml` workflow

- docs/optimization_guide/dldt_deployment_optimization_guide.md
- docs/optimization_guide/memory_optimization_guide.md
port: https://github.com/openvinotoolkit/openvino/pull/17022
as suggested in: https://github.com/openvinotoolkit/openvino/pull/17022#issuecomment-1537757994
> [DOCS] port memory_optimization_guide (#17022)

- docs/optimization_guide/dldt_deployment_optimization_guide.md
- docs/optimization_guide/memory_optimization_guide.md
port: https://github.com/openvinotoolkit/openvino/pull/17022
> [DOCS] port memory_optimization_guide

- src/bindings/c/src/ie_c_api.cpp
- src/bindings/c/tests/ov_remote_context_test.cpp
- *change auto in for() to auto const &*
- *108938*
> AUTO_CAUSES_COPY in c bindings

- src/frontends/tensorflow/README.md
**Details:** Update TensorFlow Frontend developer guide.
> [TF FE] Update TensorFlow Frontend developer guide

- src/frontends/tensorflow/src/variables_index.cpp
- Fixed extending of char to requested type
- 110452
> [TF FE] Fix for wrong sign extending

- src/bindings/python/src/pyopenvino/core/common.cpp
- src/bindings/python/tests/test_runtime/test_tensor.py
> [PyOV][Backport] Remove numpy strides from Tensor creation

- src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp
- src/plugins/intel_gpu/tests/unit/passes/test_module_fusing_reorder.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/reorder_gpu_test.cpp
- Fixed several failed unit tests on dGPU after https://github.com/openvinotoolkit/openvino/pull/17351
> [GPU] Fixed unit tests for dGPU

- src/common/transformations/src/transformations/op_conversions/convert_reduce_to_reshape.cpp
- Fix smoke_Einsum/EinsumLayerTest.CompareWithRefs on windows
- *...*
- no
> [GPU] Fix convert reduce to reshape

- src/plugins/intel_cpu/src/transformations/cpu_opset/arm/pass/convert_group_conv.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/arm/pass/convert_group_conv1d.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/arm/pass/convert_reduce_multi_axis.cpp
Ticket: [CVS-101331](https://jira.devtools.intel.com/browse/CVS-101331)
> [CPU][ARM] Dynamic shapes support in ARM transformations

- src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
- Fix matmul with IS0=(5)_IS1=(5.1), when dimensions < 2
- *...*
- some random pre commit fails
> [GPU] fix matmul smoke test fail on windows

- src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h
- src/plugins/intel_gpu/tests/unit/fusions/gather_fusion_test.cpp
- dyn_shape_offset of shape_agnostic kernel for dynamic shape was not considering fused inputs
> [GPU] Fix bug in shape agnosic kernel for fused cases

- src/core/include/openvino/op/proposal.hpp
- src/core/reference/include/ngraph/runtime/reference/convolution.hpp
- src/core/reference/include/ngraph/runtime/reference/convolution_backprop_data.hpp
- src/core/reference/include/ngraph/runtime/reference/deformable_convolution.hpp
- src/core/reference/include/ngraph/runtime/reference/group_convolution.hpp
- src/core/reference/include/ngraph/runtime/reference/group_convolution_backprop_data.hpp
- src/plugins/intel_cpu/tests/functional/single_layer_tests/augru_cell.cpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/activation.hpp
- *Convolution reference time execution was improved in scope of task "Optimize CPU tests time".*
- *98677*
> [Core] Conv reference optimization.

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/tests/unit/passes/remove_redundant_reorders_tests.cpp
- *Remove unnecessary condition for permute in layout_optimizer*
- *Add unit test*
- *108730*
> [GPU] Fix layout optimizer removing reorder inappropriately in batch 2

- src/plugins/intel_gpu/include/intel_gpu/plugin/plugin.hpp
- src/plugins/intel_gpu/src/plugin/plugin.cpp
- src/plugins/intel_gpu/tests/functional/remote_blob_tests/dx11_remote_ctx_test.cpp
- src/plugins/intel_gpu/tests/functional/remote_blob_tests/gpu_remote_tensor_tests.cpp
- This PR enables the `ImportNetwork` with remote_context API.
- 110532
> [GPU] enables ImportNetwork with remote_context API

- src/core/reference/include/ngraph/runtime/reference/convolution.hpp
- src/core/reference/include/ngraph/runtime/reference/convolution_backprop_data.hpp
- *item1*
- *...*
- CVS-111135
> [Core][Ref] Conv postcommit compilation fix.

- src/core/include/openvino/core/any.hpp
- src/core/include/openvino/core/model.hpp
- src/core/src/any.cpp
- src/core/src/model.cpp
- src/core/tests/any.cpp
- src/tests_deprecated/unit/CMakeLists.txt
- Port #16757 from master to 2022.
- CVS-106375
> Fix copy constructor and assignment for ov::Any (#16757)

- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
**Details:** Document freezing as essential step for pruning SM format
> [MO][TF FE] Document freezing as essential step for pruning SM format

- src/inference/dev_api/cpp_interfaces/interface/ie_iplugin_internal.hpp
- src/inference/dev_api/openvino/runtime/icompiled_model.hpp
- src/inference/src/cpp_interfaces/interface/ie_iplugin_internal.cpp
- src/inference/src/dev/icompiled_model.cpp
- src/inference/src/dev/preprocessing/preprocessing.cpp
- src/inference/tests/unit/add_preprocessing.cpp
- *Fix version printed for new api: pointer is invalid in user application*
- *Fix case when layout set for input with number of dimensions > 5 (`Layout::BLOCKED`)*: it set to `[N,L,O,C,K,E,D]` for incompatible shape
- *Add method for setting task/callback executors in compiled model (required for nvidia plugin)*
- *ticket-id*
> Api2.0 fixes

- src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_ref.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- *Implement shape agnostic ref kernel for convolution*
- *106809*
> [GPU] Shape agnostic ref kernels implementation for convolution

- src/plugins/intel_gpu/include/intel_gpu/graph/serialization/binary_buffer.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/compiled_model.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/graph.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/program.hpp
- src/plugins/intel_gpu/src/graph/data.cpp
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/plugin/compiled_model.cpp
- src/plugins/intel_gpu/src/plugin/graph.cpp
- src/plugins/intel_gpu/src/plugin/plugin.cpp
- src/plugins/intel_gpu/src/plugin/program.cpp
- src/plugins/intel_gpu/tests/functional/dynamic_tests/gpu_dyn_batch_shape_tests.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/streams_test.cpp
- This PR fixes deserialization logic for dynamic batch
- 109497
> [GPU] Fixed deserialization logic for dynamic batch

- src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/activation.cpp
> [CPU][ARM32][TESTS] Expect ref implementation for GeluErf

- docs/dev/build_mac_arm.md
- Closes https://github.com/openvinotoolkit/openvino/issues/17523
> Updated macOS build instruction for arm64

- src/inference/src/dev/core_impl.cpp
- src/inference/src/dev/core_impl.hpp
- Allow to register plugin with new extensions
- *ticket-id*
> Register new plugin extensions

- docs/install_guides/installing-openvino-apt.md
- docs/install_guides/installing-openvino-yum.md
- Updated APT/YUM instructions with actual version
- Added instructions for Ubuntu22
- Updated subfolders naming for APT
> Updated APT/YUM install instructions

- cmake/packaging/debian.cmake
- cmake/packaging/rpm.cmake
- tools/deployment_manager/configs/darwin.json
- tools/deployment_manager/configs/linux.json
- tools/deployment_manager/configs/windows.json
- *item1*
- *...*
- *ticket-id*
> Upgrade versions to 2023.1 in packaging

- tools/deployment_manager/configs/darwin.json
- tools/deployment_manager/configs/linux.json
- tools/deployment_manager/configs/windows.json
- *item1*
- *...*
- *ticket-id*
> Added python 3.11 for deployment tool

- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- src/frontends/tensorflow/README.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] PORT Document freezing as essential step for pruning SM format

- cmake/dependencies.cmake
add tbb binaries versioning
tbb2020.3.3: https://github.com/oneapi-src/oneTBB/releases/tag/v2020.3.3
- *update tbb2020 package for windows*
- *110419*
> update tbb2020 package for windows

- tools/mo/openvino/tools/mo/ops/strided_slice.py
- tools/mo/openvino/tools/mo/utils/ir_engine/compare_graphs.py
- tools/mo/unit_tests/mo/middle/StridedSliceNormalizer_test.py
- masks "[0]" and "" should be treated as same for StridedSlice during graph comparrison
- xxx-98053
> [MO] fix IR graph comparator

- cmake/features.cmake
> [CPU][GPU] Fix ENABLE_DEBUG_CAPS configuration in cmake

- docs/OV_Runtime_UG/auto_device_selection.md
- docs/OV_Runtime_UG/ov_dynamic_shapes.md
- docs/OV_Runtime_UG/performance_hints.md
- docs/OV_Runtime_UG/supported_plugins/CPU.md
- docs/OV_Runtime_UG/supported_plugins/GPU.md
- docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
- docs/snippets/ov_dynamic_shapes.c
- docs/snippets/ov_dynamic_shapes.cpp
- docs/snippets/ov_dynamic_shapes.py
Recreation of BDTI PRs for master.
Recreated PRs:
* https://github.com/openvinotoolkit/openvino/pull/15216
* https://github.com/openvinotoolkit/openvino/pull/14793
* https://github.com/openvinotoolkit/openvino/pull/12067
Master PR: https://github.com/openvinotoolkit/openvino/pull/16913
> [DOCS] Recreation of BDTI PRs - 22.3

- scripts/install_dependencies/install_openvino_dependencies.sh
- Ported https://github.com/openvinotoolkit/openvino/pull/17653
> Install libtbb12 on U22

- tools/compile_tool/CMakeLists.txt
- Fixed master build
- Regression after https://github.com/openvinotoolkit/openvino/pull/17460
> Fixed compile_tool install

- src/bindings/python/src/compatibility/openvino/inference_engine/ie_api.pyx
- src/bindings/python/src/compatibility/openvino/inference_engine/ie_api_impl.cpp
- src/bindings/python/src/compatibility/openvino/inference_engine/ie_api_impl.hpp
- src/bindings/python/tests_compatibility/test_inference_engine/test_InferRequest.py
- A part of PR: https://github.com/openvinotoolkit/openvino/pull/17571
- *ticket-id*
> Remove legacy Python API

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reduce_gpu_b_fs_yx_fsv16.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/reduce/reduce_kernel_b_fs_yx_fsv16.cpp
- src/plugins/intel_gpu/tests/unit/fusions/reduce_fusion_test.cpp
+ Invalid calculation in reducing un-aligned feature axis for b_fs_yx_fsv16
- In reducing un-aligned feature axis, reduce calculation uses the whole 16 feature loaded by sub_group_block_read
- Enabled unit-tests of reduce_eltwise_activation_quantize.basic on dGPU (blocked by https://github.com/openvinotoolkit/openvino/pull/15873)
- 67491
> [GPU] BugFix reduce_b_fs_yx_fsv16 kernel

- docs/Extensibility_UG/frontend_extensions.md
- docs/snippets/ov_extensions.cpp
- *Add examples of using named outputs in extensions*
- *108007*
> [DOCS] Add examples of using named outputs in extensions

- .ci/azure/linux_arm64.yml
- src/bindings/python/wheel/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
> Enabled fdupes checks for Linux arm64

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/permute_tile_8x8_4x4.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_tile_8x8_4x4.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/permute_gpu_test.cpp
- Shape agnostic optimized Permute_tile_8x8_4x4 kernel implementation
- 104943
> [GPU] Added shape agnostic optimized Permute_tile_8x8_4x4 kernel

- src/core/src/op/random_uniform.cpp
- src/core/tests/type_prop/random_uniform.cpp
- *Let Random Uniform to propagate shape more precisely*
- *CVS-112019*
> Random Uniform: precise shape inference

- src/frontends/pytorch/src/op/sum.cpp
- tests/layer_tests/pytorch_tests/test_sum.py
- *update translator for aten::sum to support boolean input*
-  *TBD*
verified on oneformer model
> [PT FE]: support boolean data type in sum operation

- src/frontends/pytorch/src/op/unflatten.cpp
- src/frontends/pytorch/src/op_table.cpp
- src/frontends/pytorch/src/utils.cpp
- src/frontends/pytorch/src/utils.hpp
- tests/layer_tests/pytorch_tests/test_unflatten.py
- *support aten::unflatten op*
- *10817*
> [PT FE]: support aten::unflatten

- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_item.py
- *Add translation and tests for aten::item*
- *...*
- *110803*
> [PT FE] Add translation for aten::item

- .ci/azure/linux_arm64.yml
- *item1*
- *...*
- *ticket-id*
> Building Linux arm64 samples

- src/plugins/intel_cpu/tests/functional/single_layer_tests/mvn.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/mvn.cpp
- src/tests/functional/shared_test_classes/src/single_layer/mvn.cpp
- MVN skipconfig update
- Tests for 8d tensors enables
- Typos fixes
- no (sporadic fails)
> [GPU] Mvn skipconfig update and typos fix

- docs/OV_Runtime_UG/performance_hints.md
- docs/install_guides/configurations-for-intel-gpu.md
- docs/install_guides/configurations-for-ncs2.md
- samples/cpp/benchmark/sync_benchmark/README.md
- samples/cpp/benchmark/throughput_benchmark/README.md
- samples/python/benchmark/sync_benchmark/README.md
- samples/python/benchmark/throughput_benchmark/README.md
Addressing issues with correct indentation, code-blocks and numbering in lists.
Also, porting some changes from https://github.com/openvinotoolkit/openvino/pull/17603 that apply to this version as well.
> [DOCS] Fixing formatting issues in documentation - for 22.3

- src/frontends/pytorch/src/op/norm.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_norm.py
- *support aten::frobenius_norm*
- *101102*
tested on clip model
> [PT FE]: support frobenius norm and fix aten::norm

- src/frontends/tensorflow_common/tests/CMakeLists.txt
- src/frontends/tensorflow_common/tests/block_lstm_replacer.cpp
- src/frontends/tensorflow_common/tests/gru_block_cell_replacer.cpp
- src/frontends/tensorflow_lite/tests/basic_api.cpp
- src/frontends/tensorflow_lite/tests/convert_model.cpp
**Details:** Avoid ngraph in tensoflow common and lite parts
**Ticket:** 111370
> [TFC][TFL] Avoid ngraph in TensorFlow common and lite parts

- docs/OV_Runtime_UG/precision_control.md
- docs/OV_Runtime_UG/supported_plugins/CPU.md
- docs/OV_Runtime_UG/supported_plugins/Supported_Devices.md
- docs/snippets/cpu/ov_execution_mode.cpp
- docs/snippets/cpu/ov_execution_mode.py
PR to master branch: https://github.com/openvinotoolkit/openvino/pull/17784
> [DOC][CPU] documentation update

- docs/OV_Runtime_UG/supported_plugins/CPU.md
- docs/snippets/cpu/multi_threading.cpp
- docs/snippets/cpu/multi_threading.py
- *add multi threading for 2023.0 release in CPU plugin document*
- *ticket-id*
> [DOC] add multi threading for 2023.0 release in CPU plugin document

- src/frontends/pytorch/src/op/distance.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_distance.py
- *support translation aten::cdist operator*
- *support translation aten::pairwise_distance*
- *111693*
> [PT FE]: support aten::cdist and aten::pairwise_distance

- docs/install_guides/installing-openvino-apt.md
- docs/install_guides/installing-openvino-brew.md
- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-from-archive-macos.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/install_guides/installing-openvino-pip.md
- docs/install_guides/installing-openvino-raspbian.md
- docs/install_guides/installing-openvino-yum.md
- docs/install_guides/pypi-openvino-dev.md
- docs/install_guides/pypi-openvino-rt.md
- docs/install_guides/troubleshooting-steps.md
- docs/install_guides/uninstalling-openvino.md
port: https://github.com/openvinotoolkit/openvino/pull/17764
authored by @ilya-lavrenov
> Updated install docs for 2023.0 port (#17764)

- src/plugins/hetero/executable_network.cpp
- *HETERO: avoid duplicated results on the same output port, it will give performance improvement on such devices as NVIDIA GPU*
- *111877*
> [HETERO]: Avoid duplicated results

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
> [CPU] Some DefConv test cases are temporarily skipped 

- docs/OV_Runtime_UG/preprocessing_usecase_save.md
- *item1*
- *...*
- *ticket-id*
> DOCS Fix build links

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- src/plugins/intel_cpu/tests/functional/single_layer_tests/grid_sample.cpp
- *The default threshold became insufficient after the number generator changes in PR #17244*
- *111405*
> [CPU] GridSample tests threshold.

- src/bindings/c/include/openvino/c/ov_core.h
- src/bindings/c/include/openvino/c/ov_prepostprocess.h
- src/bindings/c/include/openvino/c/ov_remote_context.h
- *fix contents missed in doxygen*
- *111124*
> [C API] some contents missed in doxygen

- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_mmad_int8.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_mmad_int8.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_mmad_int8_slm.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_mmad_int8_slm.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_ref.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_ref.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.h
- src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp
- WA for CL_INVALID_KERNEL_ARGS exception thrown on kernel enqueue with big WG size
- Some fixes for required extension in the kernels
> [GPU] Some functional fixes for nvidia

- .ci/azure/android_arm64.yml
- cmake/features.cmake
- vcpkg.json
- *item1*
- *...*
- *ticket-id*
> Added vcpkg build to CI

- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-from-archive-macos.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/install_guides/installing-openvino-raspbian.md
- Update archive names in docs
> Update archive names for 2023.0 release

- docs/OV_Runtime_UG/supported_plugins/CPU.md
PR to master branch: https://github.com/openvinotoolkit/openvino/pull/17815
> [DOC] cpu documentation fixes

- src/plugins/intel_gna/legacy/src/convert_function_to_cnn_network.cpp
> [GNA] convertFunctionToICNNNetwork operation performance improovement

- docs/install_guides/installing-openvino-from-archive-macos.md
> [DOCS] Change downloads directory link 

- src/common/low_precision_transformations/src/strided_slice.cpp
- src/common/low_precision_transformations/tests/strided_slice_transformation.cpp
- src/tests/ngraph_helpers/lpt_ngraph_functions/src/strided_slice_function.cpp
- *StridedSlice dequantization improvement*
- *[108593](https://jira.devtools.intel.com/browse/CVS-108593)*
> [LPT] StridedSlice dequantization improvement

- docs/get_started.md
- docs/install_guides/configurations-for-intel-gpu.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/install_guides/installing-openvino-pip.md
> [DOCS] Change notebooks links

- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-macos-header.md
- Added section with info regarding compiling with OpenVINO from Conda-Forge
- Added conda-forge installation to MacOS install header
> [docs] Conda update

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/softmax_gpu_items_class_optimized.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_items_class_optimized.cpp
- *intel_sub_group_read/intel_sub_group_read are incorporated*
- *[CVS-91171](https://jira.devtools.intel.com/browse/CVS-91171)*
> [GPU] softmax_gpu_items_class_optimized kernel optimizations

- src/plugins/intel_gpu/include/intel_gpu/plugin/program.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/eltwise.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
- src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/eltwise/eltwise_kernel_base.h
- src/plugins/intel_gpu/src/plugin/ops/eltwise.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp
- *Eltwise div fused ops with int type*
- *105930*
> Apply m_pythondiv for fusing of eltwise div

- src/plugins/intel_gpu/src/graph/include/implementation_map.hpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/detection_output_test.cpp
- This PR makes the order of implementations addition important and decreases priority of CPU impls. Also, these changes highlighted accuracy problems with OCL implementation of Detection Output - need to check it (ticket 112473)
This PR is a part of https://github.com/openvinotoolkit/openvino/pull/17762
> [GPU] Change priority of CPU implementations

- src/plugins/intel_gpu/include/intel_gpu/plugin/plugin.hpp
- src/plugins/intel_gpu/src/plugin/plugin.cpp
- Fixed GPU remote context name in case if plugin was renamed in the runtime
- *ticket-id*
> Fix GPU remote context name initialization

- src/plugins/intel_cpu/tools/commit_slider/commit_slider.py
- src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py
- src/plugins/intel_cpu/tools/commit_slider/utils/modes.py
- *Because of incorrect exception handling in python file handling, we need explicitly check OS type while using shutil library*
- *Logger fixed in benchmark mode to print error message in fail case*
- *ticket-id*
> [Commit slider] Rmtree fixed

- src/plugins/intel_cpu/src/nodes/def_conv.cpp
- *Unified Jia and Ref offsets handling*
- *Remove unnecessary instructions*
- *Prepare ground for refactoring of jit impl. (use offsets as ignore-mark instead of zero weights)*
- *80529*
> [CPU] Align jit and ref offsets handling in Def.Conv.

- docs/_static/css/homepage_style.css
- docs/_static/js/graphs.js
- docs/conf.py
- docs/home.rst
- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-macos-header.md
- docs/install_guides/installing-openvino-overview.md
- docs/install_guides/installing-openvino-raspbian-removedfromtoc.md
- docs/install_guides/installing-openvino-runtime.md
port:
https://github.com/openvinotoolkit/openvino/pull/17874
https://github.com/openvinotoolkit/openvino/pull/17861
> Docs post release fixes port

- docs/_static/css/homepage_style.css
- docs/_static/js/graphs.js
- docs/conf.py
- docs/home.rst
- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-macos-header.md
- docs/install_guides/installing-openvino-overview.md
- docs/install_guides/installing-openvino-raspbian-removedfromtoc.md
- docs/install_guides/installing-openvino-runtime.md
Includes adjustments in various docs.
Ports: https://github.com/openvinotoolkit/openvino/pull/17861
> DOCS post-release adjustments

- src/frontends/paddle/src/op/set_value.cpp
- Regression after https://github.com/openvinotoolkit/openvino/commit/14da93c155300f6471f706aa5fb414f73e558d52
> Fixed compilation with clang

- src/common/snippets/src/pass/mha_tokenization.cpp
- src/plugins/intel_cpu/src/emitters/x64/jit_snippets_emitters.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp
- src/tests/ngraph_helpers/snippets_ngraph_functions/src/subgraph_mha.cpp
- *Allow Snippets to tokenize 3D MHA patterns*
- *96955*
> [Snippets] Added support of 3D MHA

- src/plugins/intel_cpu/src/nodes/reduce.cpp
- src/plugins/intel_cpu/tests/functional/single_layer_tests/reduce_ops.cpp
- *Improve parallelism of cases with small batch size in nspc layout*
- *Extend bf16 optimization in https://github.com/openvinotoolkit/openvino/pull/16829 to support int8*
- *CVS-110961*
> [CPU] Reduce node improve parallelism

- docs/optimization_guide/model_optimization_guide.md
- *item1*
- *...*
- *ticket-id*
> [DOCS]  Model optimization paragraph fix 

- docs/install_guides/installing-openvino-from-archive-linux.md
> [DOCS] Fix spaces in archive links

- src/plugins/intel_cpu/src/utils/shape_inference/shape_inference.cpp
- src/plugins/intel_cpu/tests/unit/shape_inference_test/interpolate_shape_inference_test.cpp
- Add all version of Interpolate operator to CPU shape inference factory.
- 97237
> Support all interpolate version by CPU shape inference

- cmake/templates/OpenVINOConfig.cmake.in
- We need at least 3.3 to allow `IN_LIST` statement in `if()` command
> Added cmake_policy call to allow IN_LIST in if()

- src/frontends/tensorflow/src/frontend.cpp
- src/frontends/tensorflow/tests/convert_saved_model.cpp
- src/frontends/tensorflow/tests/convert_tricky_models.cpp
- src/frontends/tensorflow/tests/test_models/gen_scripts/generate_saved_model_broadcast_issue.py
- Added transformation which removes Concat branches with empty tensors
- 107554
> [TF FE] Workaround for Broadcast/Concat issue with empty tensors

- docs/install_guides/uninstalling-openvino.md
> [DOCS]  Add sudo to uninstall

- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/uninstalling-openvino.md
- docs/optimization_guide/model_optimization_guide.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] Port release doc fixes

- docs/OV_Runtime_UG/deployment/deployment-manager-tool.md
- docs/_static/images/configuration_dialog.png
- docs/_static/images/selection_dialog.png
Porting: https://github.com/openvinotoolkit/openvino/pull/17903
Updating the image files with the print screens of Deployment Manager tool.
Fixing the path to deployment_manager.py file in a code for Windows installation.
> [DOCS] Updating "Deploying Your Application with Deployment Manager" article - for 23.0

- docs/OV_Runtime_UG/deployment/deployment-manager-tool.md
- docs/_static/images/configuration_dialog.png
- docs/_static/images/selection_dialog.png
Updating the image files with the print screens of Deployment Manager tool. 
Fixing the path to deployment_manager.py file in a code for Windows installation.
> [DOCS] Updating  "Deploying Your Application with Deployment Manager" article

- src/common/itt/CMakeLists.txt
- src/common/itt/cmake/ITTConfig.cmake
- thirdparty/dependencies.cmake
- thirdparty/itt_collector/sea_itt_lib/CMakeLists.txt
- thirdparty/ittapi/CMakeLists.txt
- See https://github.com/intel/ittapi/pull/88
> Support different names for ITTAPI

- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- Also, slight change in recent additions for conda Linux usage.
- *ticket-id*
> Align tabs in install archives Linux

- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- Ported https://github.com/openvinotoolkit/openvino/pull/17947
> Align tabs in install archives Linux (#17947)

- .ci/azure/linux.yml
- tools/deployment_manager/configs/darwin.json
- tools/deployment_manager/configs/linux.json
- tools/deployment_manager/configs/windows.json
- *item1*
- *...*
- *ticket-id*
> Fixes for deployment manager

- .ci/azure/linux_conditional_compilation.yml
- .ci/azure/linux_cuda.yml
- .ci/azure/windows_conditional_compilation.yml
- Issue https://github.com/openvinotoolkit/openvino/pull/17902/checks?check_run_id=14037206641
> Updated refs to dependency repositories

- src/plugins/intel_cpu/src/plugin.cpp
- *The PR fixes LPT mode internal property behavior for compiled model configuration (prefer model configuration over core configuration)*
- *[CVS-112723](https://jira.devtools.intel.com/browse/CVS-112723)*
> [CPU] Fixed KEY_LP_TRANSFORMS_MODE internal propery behavior

- cmake/templates/OpenVINOConfig.cmake.in
- samples/cpp/build_samples_msvc.bat
- src/plugins/intel_gpu/src/graph/impls/ocl/crop.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/gather_tree.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/range.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/roi_align.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/select.cpp
- src/plugins/intel_gpu/src/graph/select.cpp
- src/plugins/intel_gpu/src/plugin/infer_request.cpp
- Partially https://github.com/openvinotoolkit/openvino/pull/17900
- https://github.com/openvinotoolkit/openvino/pull/17312
- https://github.com/openvinotoolkit/openvino/pull/17916
> Ports fixes to 2022.3.1 LTS

- .ci/azure/android_arm64.yml
- src/plugins/intel_gpu/tests/unit/test_cases/resample_gpu_test.cpp
- See https://github.com/openvinotoolkit/oneDNN/pull/196
> Android debug build

- docs/OV_Runtime_UG/deployment/deployment-manager-tool.md
- docs/OV_Runtime_UG/hetero_execution.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/ops/activation/Mish_4.md
- tools/pot/docs/DefaultQuantizationUsage.md
Applying fixes to broken sphinx directives for handling code blocks.
> [DOCS] Fixing broken code blocks

- docs/OV_Runtime_UG/deployment/deployment-manager-tool.md
- docs/OV_Runtime_UG/hetero_execution.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/ops/activation/Mish_4.md
- tools/pot/docs/DefaultQuantizationUsage.md
Porting: https://github.com/openvinotoolkit/openvino/pull/17959
Applying fixes to broken sphinx directives for handling code blocks.
> [DOCS] Fixing broken code blocks for 23.0

- cmake/dependencies.cmake
> Move dependencies to the new share

- docs/Documentation/datumaro.md
- docs/Documentation/openvino_ecosystem.md
- docs/_static/images/datumaro.png
port: https://github.com/openvinotoolkit/openvino/pull/17944
* add Datumaro document
* add datumaro into toctree
> [DOCS] Adding Datumaro document into OV Ecosystems (#17944)

- src/bindings/python/tests/test_graph/test_manager.py
- src/common/transformations/src/transformations/op_conversions/unique_decomposition.cpp
- src/common/transformations/tests/op_conversions/unique_decomposition_test.cpp
- src/core/reference/src/runtime/reference/einsum.cpp
- src/core/tests/pass/serialization/const_compression.cpp
- src/frontends/onnx/frontend/src/core/model.cpp
- src/frontends/onnx/frontend/src/utils/arg_min_max_factory.cpp
- src/frontends/tensorflow_common/src/op/dynamic_partition.cpp
- src/plugins/intel_cpu/src/nodes/roi_align.cpp
- src/plugins/intel_gna/legacy/include/legacy/ie_layers.h
- thirdparty/fluid/modules/gapi/src/compiler/passes/intrin.cpp
- seperate->separate
- occurence->occurrence
- Serializatio->Serialization
- *ticket-id*
> fixing typos

- src/plugins/intel_gpu/src/graph/gather_nd.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/gather_nd.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_nd_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_nd_kernel_ref.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_nd_kernel_ref.h
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/gather_nd.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gather_nd_gpu_test.cpp
- gather nd shape agnostic kernel implementation
- 107778
> [GPU] gather nd shape agnostic kernel implementation

- src/common/snippets/README.md
- src/common/snippets/docs/snippets_design_guide.md
- *Update Snippets' documentation to reflect the present state of the pipeline*
- *75569*
> [Snippets] Documentation update

- src/bindings/python/src/pyopenvino/CMakeLists.txt
- src/bindings/python/src/pyopenvino/frontend/tensorflow/CMakeLists.txt
- src/bindings/python/wheel/setup.py
- Refactored setup.py
- Fixed issue that TE Python FE is missed in OpenVINO package
- Removed requirements.txt installation from python component, moved to component with openvino-dev requirements
> Refactored setup.py

- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Kaldi.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- docs/MO_DG/prepare_model/convert_model/mxnet_specific/Convert_GluonCV_Models.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_YOLACT.md
- docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_BERT_From_Tensorflow.md
- docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_CRNN_From_Tensorflow.md
- docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_DeepSpeech_From_Tensorflow.md
- docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_NCF_From_Tensorflow.md
- docs/OV_Runtime_UG/Model_caching_overview.md
- docs/OV_Runtime_UG/Python_API_inference.md
- docs/OV_Runtime_UG/ShapeInference.md
- docs/OV_Runtime_UG/supported_plugins/Device_Plugins.md
- docs/OV_Runtime_UG/supported_plugins/GNA.md
- docs/OV_Runtime_UG/supported_plugins/GPU_RemoteTensor_API.md
- docs/install_guides/configurations-for-intel-gna.md
- docs/install_guides/configurations-for-intel-gpu.md
- docs/install_guides/installing-openvino-brew.md
- tools/pot/openvino/tools/pot/api/README.md
Porting: https://github.com/openvinotoolkit/openvino/pull/17994
Fixing indentation, numbered lists and links.
> [DOCS] Fixing formatting issues in articles - for 23.0

- docs/_static/css/homepage_style.css
Porting: https://github.com/openvinotoolkit/openvino/pull/18011
Changing the size of image and on hover attributes of cards.
> [DOCS] Restyling elements on home page - for 23.0

- docs/_static/css/homepage_style.css
Changing the size of image and on hover attributes of cards.
> [DOCS] Restyling elements on home page

- src/plugins/intel_cpu/tools/commit_slider/utils/cfg.json
- src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py
- src/plugins/intel_cpu/tools/commit_slider/utils/modes.py
- *Tune shell flag while launghing app command on linux*
Correctness ensured by commit slider job №64
> [Commit slider] Tune shell settings for linux

- docs/install_guides/installing-openvino-docker-linux.md
- docs/install_guides/installing-openvino-from-archive-macos.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] Port docs 

- docs/dev/build_linux.md
Port from https://github.com/openvinotoolkit/openvino/pull/18035
Ticket: 101774
* Updated information on which driver to use for a specific version of Ubuntu.
* Moved information about -DENABLE_INTEL_GPU=OFF to the Additional Build Options.
> [DOCS] Build OpenVINO™ Runtime for Linux systems update for 23.0

- docs/install_guides/installing-openvino-docker-linux.md
> [DOCS] Fix doc reference link

- src/frontends/pytorch/src/op/transpose.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_transpose.py
- tests/layer_tests/pytorch_tests/test_trilu.py
- *support aten::t tensor operator*
- *support inplace cases for aten::tril and aten::triu*
tested on clip from huggingface
> [PT FE]: support aten::t and inplace tril/triu

- docs/_static/css/custom.css
Porting: https://github.com/openvinotoolkit/openvino/pull/18054
Introducing changes in `css` style for tabs from sphinx-design extension.
> [DOCS] Restyling tabs for 23.0

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/non_max_suppression_gpu_ref.cl
- *fix fp16 x fp16 overflow in NonMaxSuppression*
- *CVS-106890*
> [GPU] fix fp16 x fp16 overflow in NonMaxSuppression

- docs/_static/css/custom.css
> [DOCS] Restyling tabs fix

- src/bindings/python/tests/test_frontend/test_frontendmanager.py
- Fixed test_load_by_model() test.
-
> Fixed test_load_by_model() test.

- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bfyx_ref.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- *additional checks fixed for fully_connected*
- *99953*
> [GPU] additional checks fixed for fully_connected

- src/bindings/python/src/openvino/frontend/pytorch/decoder.py
- *Fix automatic scripting for quantized models*
- *None*
> [PT FE] Fix automatic scripting for quantized models

- src/bindings/c/src/ov_core.cpp
- Fix CAPI string copy to char* issue in Debug & Release mode
- Closes #18019
> [C API] Fix str copy to char* issue in debug & release mode,

- docs/OV_Runtime_UG/deployment/local-distribution.md
> [DOCS] Local distribution page improvements 

- src/frontends/onnx/frontend/src/core/graph.cpp
- src/frontends/onnx/frontend/src/utils/legacy_conversion_extension.hpp
- src/frontends/onnx/tests/op_extension.cpp
> [ONNX FE] Allow to mix new and legacy extensions

- src/inference/src/ie_network_reader.cpp
- Fixed behavior in case we are passing folder path on input for another frontends
- *CVS-113384*
> [IRv7] Fixed behavior if folder path on input

- src/frontends/tensorflow/src/checkpoint_utils.hpp
- src/frontends/tensorflow/src/frontend.cpp
- src/frontends/tensorflow/src/graph_iterator_saved_model.cpp
- src/frontends/tensorflow/src/graph_iterator_saved_model.hpp
- src/frontends/tensorflow/src/op/var_handle.cpp
- src/frontends/tensorflow/tests/convert_saved_model.cpp
- src/frontends/tensorflow/tests/test_models/gen_scripts/generate_saved_model_multi-graph.py
- tools/mo/openvino/tools/mo/moc_frontend/pipeline.py
- Added support of alternate MetaGraph tags
- Added support of variables without explicit RestoreV2
- 111260, 111262
> [TF FE] Extended support of tagged MetaGraphs and variables handling in SavedModel

- tools/pot/openvino/tools/pot/engines/ie_engine.py
- tools/pot/openvino/tools/pot/graph/graph_utils.py
- tools/pot/openvino/tools/pot/utils/launcher.py
> [POT] ENABLE_MMAP property pos (#17896)

- src/frontends/onnx/frontend/src/core/graph.cpp
- src/frontends/onnx/frontend/src/utils/legacy_conversion_extension.hpp
- src/frontends/onnx/tests/op_extension.cpp
Port of: https://github.com/openvinotoolkit/openvino/pull/18103
> [PORT TO 23.0][ONNX FE] Allow to mix new and legacy extensions

- src/plugins/intel_gpu/tests/unit/passes/kernels_cache_test.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/arg_max_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/deconvolution_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/scatter_nd_update_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/strided_slice_gpu_test.cpp
+ Resolved unit-tests failure on dGPU
+ Applied get_test_default_config for testing config
- resolved dGPU unit-tests failure related to config of queue order
-
> [GPU] Fix unit-tests for dGPU

- src/bindings/c/include/openvino/c/ov_common.h
- *rename group from ov_remote_context to "Remote Context"*
- **
> rename group from ov_remote_context to "Remote Context"

- src/plugins/intel_gna/tests/functional/pass_tests/convolution_crop_axis_h.cpp
- src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/convolution_relu_sequence.cpp
- Revert last unnecessary changes
> Remove fix for gna tests

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- [GPU] Skip all user format check when dynamic shape in get_preferred_format() to avoid endless recursive call
- 87559
> [GPU] Skip all user format check when dynamic shape in get_preferred_format() to avoid endless recursive call

- src/plugins/intel_cpu/src/emitters/x64/cpu_generator.cpp
- src/plugins/intel_cpu/src/emitters/x64/jit_snippets_emitters.cpp
- src/plugins/intel_cpu/src/emitters/x64/jit_snippets_emitters.hpp
- *Implement shuffling based horizontal reduction emitter.*
- *CVS-99703*
> [Snippets] Implement shuffling based horizontal reduction emitter

- src/plugins/intel_cpu/tests/functional/single_layer_tests/mvn.cpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/base/utils/ranges.hpp
- src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
See the comment in the changed code.
> [IE_TESTS] Correct random data generation for real numbers

- src/common/transformations/src/transformations/common_optimizations/space_to_batch_fusion.cpp
- src/common/transformations/tests/common_optimizations/space_to_batch_fusion.cpp
> Reject negative pads in SpaceToBatchFusion

- docs/ops/activation/GELU_2.md
- docs/ops/activation/GELU_7.md
- docs/ops/arithmetic/FloorMod_1.md
- docs/ops/arithmetic/Floor_1.md
- docs/ops/comparison/GreaterEqual_1.md
- docs/ops/comparison/Greater_1.md
- docs/ops/convolution/GroupConvolutionBackpropData_1.md
- docs/ops/convolution/GroupConvolution_1.md
- docs/ops/detection/GenerateProposals_9.md
- docs/ops/image/GridSample_9.md
- docs/ops/movement/GatherElements_6.md
- docs/ops/movement/GatherND_5.md
- docs/ops/movement/GatherND_8.md
- docs/ops/movement/GatherTree_1.md
- docs/ops/movement/Gather_1.md
- docs/ops/movement/Gather_7.md
- docs/ops/movement/Gather_8.md
- docs/ops/normalization/GRN_1.md
- docs/ops/quantization/FakeQuantize_1.md
- docs/ops/sequence/GRUCell_3.md
- docs/ops/sequence/GRUSequence_5.md
- docs/requirements.txt
- *item1*
- *...*
- *ticket-id*
> [DOCS] PORT shift to rst - opsets F,G (#17253)

- src/bindings/python/src/openvino/frontend/pytorch/decoder.py
- tests/layer_tests/mo_python_api_tests/test_mo_convert_pytorch.py
- tools/mo/openvino/tools/mo/convert_impl.py
- tools/mo/openvino/tools/mo/moc_frontend/extractor.py
- tools/mo/openvino/tools/mo/moc_frontend/pytorch_frontend_utils.py
- *use example_input for rank and input dtype detection*
- *support unordered dict inputs*
- *ticket-id*
> [PT FE]: use example input for dtype and rank detection

- scripts/install_dependencies/install_openvino_dependencies.sh
- Added the `ocl-icd` dependency for Intel GPU plugin on Linux.
- *ticket-id*
> Added ocl-icd as dependency for GPU to install_dependencies.sh

- src/plugins/auto_batch/src/async_infer_request.cpp
- src/plugins/auto_batch/src/async_infer_request.hpp
- src/plugins/auto_batch/src/compiled_model.cpp
- src/plugins/auto_batch/src/compiled_model.hpp
- src/plugins/auto_batch/src/plugin.cpp
- src/plugins/auto_batch/src/plugin.hpp
- src/plugins/auto_batch/src/sync_infer_request.cpp
- src/plugins/auto_batch/src/sync_infer_request.hpp
- src/plugins/auto_batch/tests/unit/auto_batch_infer_request_tests.cpp
- src/plugins/auto_batch/tests/unit/create_infer_request_tests.cpp
- src/plugins/auto_batch/tests/unit/exec_network_tests.cpp
- src/plugins/auto_batch/tests/unit/load_network_tests.cpp
- src/plugins/auto_batch/tests/unit/mock_auto_batch_plugin.hpp
- src/plugins/auto_batch/tests/unit/plugins_tests.cpp
- using ov::... namespace
- rename class, algin with template plugin naming style
- rename class member name
- 111940
> [AUTO BATCH PLUGIN] renaming the class name in auto batch plugin & remove namespace

- .ci/azure/linux_debian.yml
- .ci/azure/mac.yml
- unit test name changed
- *ticket-id*
> fix post ci failure

- docs/OV_Runtime_UG/supported_plugins/CPU.md
- docs/notebooks/001-hello-world-with-output.rst
- *item1*
- *...*
- *ticket-id*
> [DOCS] Port docs fixes

- src/plugins/intel_gpu/src/plugin/plugin.cpp
- Fix of debug assert in get_default_context
- Possible fix of 93914
- 93914
> [GPU] Fix windows debug fail in contexts

- src/common/util/include/openvino/util/file_util.hpp
- *in case file_size == 0 old `file_exists` returned `false`*
> [OV UTIL] Fix  method in case file_size == 0

- src/frontends/pytorch/src/frontend.cpp
- src/frontends/pytorch/src/transforms/tuple_unpack_replacer.cpp
- src/frontends/pytorch/src/transforms/tuple_unpack_replacer.hpp
- tests/layer_tests/pytorch_tests/test_tuple_construct.py
- *added transformation for tuple construct + tuple unpack pattern, occurs in non-frozen models*
- *added mark dequantize subgraph transformation on frontend side*
- *CVS-113593*
> [PT FE]: fix constant folding for dequantization

- cmake/developer_package/compile_flags/os_flags.cmake
Trivial fix to a duplicate flag.
> Fix duplicate -Wno-all

- src/inference/include/openvino/runtime/remote_context.hpp
- src/inference/src/cpp/ie_remote_context.cpp
- src/inference/src/dev/core_impl.cpp
- src/inference/src/dev/icompiled_model.cpp
- Add operate () method
- 111940
> [Remote Context] Add operate () overload method in class RemoteContext

- src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/run_parallel.py
- *Provide the same test name as for run to find not runned tests*
> [CONFORMANCE] Fix type to find not run tests

- src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/highlight_tables.py
- src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/template/highlight_tables_template.html
- src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/template/style.css
> Fix highlight_tables.py

- docs/install_guides/installing-model-dev-tools.md
- docs/install_guides/installing-openvino-apt.md
- docs/install_guides/installing-openvino-brew.md
- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-from-archive-macos.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/install_guides/installing-openvino-pip.md
- docs/install_guides/installing-openvino-raspbian.md
- docs/install_guides/pypi-openvino-dev.md
> [DOCS] 22.3.1 dist updates

- src/plugins/intel_gna/src/common/graph_utils.hpp
- src/plugins/intel_gna/src/transformations/gather_sinking_matmul.cpp
- src/plugins/intel_gna/src/transformations/gather_sinking_reshape.cpp
- src/plugins/intel_gna/src/transformations/gather_sinking_split.cpp
- src/plugins/intel_gna/src/transformations/gather_sinking_transpose_reshape.cpp
- src/plugins/intel_gna/src/transformations/ts_split.cpp
Fixed warnings introduced after this PR: https://github.com/openvinotoolkit/openvino/pull/17841
- 93715
> [GNA] Fix additional warnings introduced after removal of warning suppression

- src/common/transformations/src/transformations/common_optimizations/push_constant_to_subgraph.cpp
Tikcet: connected with 109208
There is possible scenario when the same input is connected to MultiSubGraphOp many times. In the current case, the constant folding during PushConstantToSubgraph transformation will be called many times, because the caching mechanism depends on input index instead of Output<Node>.
> Cache const-folded value for the same input connected to MultiSubGraphOp during PushConstantToSubgraph

- src/tests/functional/plugin/conformance/subgraphs_dumper_new/CMakeLists.txt
- src/tests/functional/plugin/conformance/subgraphs_dumper_new/src/single_op_matchers/base.cpp
- After https://github.com/openvinotoolkit/openvino/pull/17836
> Fixed compilation

- src/plugins/intel_gna/src/common/graph_utils.hpp
- src/plugins/intel_gna/src/gna_graph_tools.hpp
- Fix warnings as error on windows build
N/A
> [GNA]Fix conversion warning in gna plugin

- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_ONNX.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Paddle.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow_Lite.md
- *item1*
- *...*
- CVS-111588
> [DOCS] Add FrontEnd API note

- docs/OV_Runtime_UG/AutoPlugin_Debugging.md
- docs/notebooks-installation.md
- docs/tutorials.md
- Debugging Auto-Device Plugin article shift to rst
- Id alignment of the Installation of OpenVINO™ Notebooks article with the rest of the docs
> [DOCS] Debugging Auto-Device Plugin rst shift + Notebooks installation id align for 23.0

- docs/conf.py
> [DOCS] Change html_baseurl to canonical

- src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp
- src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
- src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/program.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/condition.hpp
- src/plugins/intel_gpu/src/graph/condition.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/update_inner_program_io_map.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/update_loop_primitive_map.cpp
- src/plugins/intel_gpu/src/graph/impls/common/condition.cpp
- src/plugins/intel_gpu/src/graph/include/condition_inst.h
- src/plugins/intel_gpu/src/graph/include/loop_inst.h
- src/plugins/intel_gpu/src/graph/include/pass_manager.h
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/include/roi_align_inst.h
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/graph/roi_align.cpp
- src/plugins/intel_gpu/src/plugin/ops/condition.cpp
- src/plugins/intel_gpu/src/plugin/program.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/condition.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/condition_gpu_test.cpp
- *Impl CreateIfOp*
- *Update calc_output_layouts and execute_impl*
- *Enable gpu unit / functional tests*
- *89336*
> [GPU] Impl cldnn::condition to support dynamic shape

- src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- Add condition check for dynamic shape and onednn_impl in concat_in_place_optimization::match()
- 112919
> [GPU] Add condition check for dynamic shape and onednn_impl in concat_in_place_optimization::match()

- docs/_static/css/custom.css
- docs/_static/css/homepage_style.css
- docs/index.rst
- tools/pot/docs/FrequentlyAskedQuestions.md
css adjusted
FAQ for pot gets drop-downs
> [Docs] top bar fixes port 22.3

- src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/matmul.cpp
Improved stable diffusion performance using gemm_tiled_opt by removing gemm transposed input and adding permute.
- *104516*
> [GPU] Optimize stable diffusion perf igpu

- docs/_static/css/custom.css
- docs/_static/css/homepage_style.css
- docs/home.rst
- docs/index.rst
- tools/pot/docs/FrequentlyAskedQuestions.md
port: https://github.com/openvinotoolkit/openvino/pull/18261
> Docs] top bar fixes port 23.0

- docs/_static/css/custom.css
- docs/_static/css/homepage_style.css
- docs/home.rst
- docs/index.rst
- tools/pot/docs/FrequentlyAskedQuestions.md
fixes in top bar styling 
pot faq change to .. dropdown:
> [DOCS] top bar fixes

- docs/home.rst
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/resources/prerelease_information.md
- docs/resources/release_notes.md
- docs/resources/resources.md
> DOCS reset the pre-release notes pages

- cmake/packaging/debian.cmake
- cmake/packaging/rpm.cmake
openvinotoolkit/openvino/pull/18268
> Update apt/yum conflict versions

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/src/graph/program_node.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_primitive_fusing_test.cpp
- Use pShape() when allow_new_shape_infer=1 and get_tensor() for allow_new_shape_infer=0
- Remove unnecessary condition about rank>4 in gemm-eltwise fusing 
-
> [GPU] Fix PR18171 regression

- src/common/transformations/include/transformations/op_conversions/convert_pad12_downgrade.hpp
- src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
- src/common/transformations/src/transformations/op_conversions/convert_pad12_downgrade.cpp
- src/common/transformations/tests/op_conversions/convert_pad12_downgrade_test.cpp
- The downgrade transformation registered in the common optimizations
- 111881
> Pad-12 to Pad-1 downgrade transformation

- scripts/install_dependencies/install_openvino_dependencies.sh
> Updated 3lvl domain for RPMs from fedoraproject.org

- docs/install_guides/configurations-for-intel-gpu.md
- docs/install_guides/installing-openvino-docker-linux.md
- docs/install_guides/installing-openvino-windows-header.md
Port from https://github.com/openvinotoolkit/openvino/pull/18292
- Added information about Docker for Windows/WSL2.
- Added Docker as an option to toctree in Install OpenVINO for Windows.
- Minor spelling/technical fixes..
> [DOCS] WSL2 Docker update for 23.0

- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_ONNX.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Paddle.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow_Lite.md
- docs/OV_Runtime_UG/deployment/local-distribution.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] Port docs to release branch

- src/core/src/op/space_to_batch.cpp
- src/plugins/intel_gpu/src/plugin/ops/batch_to_space.cpp
- src/plugins/intel_gpu/src/plugin/ops/space_to_batch.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/batch_to_space.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/space_to_batch.cpp
- src/plugins/template/tests/functional/op_reference/batch_to_space.cpp
- src/plugins/template/tests/functional/op_reference/space_to_batch.cpp
- *Fixed SpaceToBatch and BatchToSpace ops to use format order not rank*
- *Added functional testcases*
- *111074*
> Fixed SpaceToBatch and BatchToSpace for 3d case and add testcases

- docs/install_guides/installing-openvino-apt.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-from-archive-macos.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/install_guides/installing-openvino-yum.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] Update links to release notes

- src/bindings/python/tests/test_onnx/model_zoo_preprocess.sh
- src/bindings/python/tests_compatibility/test_onnx/model_zoo_preprocess.sh
> Fix model zoo preprocessing

- src/core/src/preprocess/preprocess_impls.cpp
> Preserve tensor legacy name in preprocessing

- .ci/azure/linux_debian.yml
- Added tools/ovc to PYTHONPATH for MO unit tests.
- 114408
> Added tools/ovc to PYTHONPATH for MO unit tests.

- src/plugins/intel_gpu/src/graph/border.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/pad_si_test.cpp
- *Calculate pad output shape with single pad_value in case pad mode is CONSTANT*
- *105930*
> [GPU] Update pad output shape for dynamic

- src/plugins/intel_gpu/include/intel_gpu/primitives/primitive.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
- *fix uninitialized scalar variable*
- *CVS-112759*
> [GPU] fix uninitialized scalar variable

- scripts/setupvars/setupvars.sh
- *item1*
- *...*
- *ticket-id*
> Added compile_tool to PATH

- src/plugins/intel_gpu/src/graph/space_to_depth.cpp
- * fix coverity block_size < 1 *
- *[CVS-112762](https://jira.devtools.intel.com/browse/CVS-112762)*
> [Coverity] fix coverity block_size < 1

- src/common/transformations/tests/common_optimizations/pad_fusion.cpp
- src/common/transformations/tests/op_conversions/convert_pad_to_group_conv.cpp
- fix duplicate symbols build error
- 112279
> fix ov_transformation_tests duplicates

- src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp
- *cast x_channel_idx to uint*
- *CVS-112753*
> [Coverity] fix type x_channel_idx

- cmake/developer_package/IEDevScriptsConfig.cmake
- cmake/developer_package/packaging/common-libraries.cmake
- cmake/developer_package/packaging/debian/debian.cmake
- cmake/developer_package/packaging/packaging.cmake
- cmake/developer_package/packaging/rpm/rpm.cmake
- Regression after https://github.com/openvinotoolkit/openvino/pull/17765
> Fixed RPATH issue for brew

- src/plugins/intel_cpu/tests/unit/ngraph_transformations/arm/convert_reduce_multi_axis.cpp
The transformation has been modified here: https://github.com/openvinotoolkit/openvino/pull/18006
This PR updates unit tests accordingly.
> [CPU] Fix multi-axis reduce transformation

- src/plugins/intel_gpu/src/graph/impls/cpu/concat.cpp
- src/plugins/intel_gpu/src/graph/include/roi_align_inst.h
- src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/roi_align_si_test.cpp
- *Fix issue to find kernel in choose_impl by adding roi_align get_shape_infer_dependencies()*
- *Fix concat cpu impl issue*
- *Add roi_align shape infer unit test*
- *100495*
> [GPU] Fix setting impl type / format issue on dGPU

- .ci/azure/mac.yml
- Disabled proxy tests on post commit
- *ticket-id*
> Fixed post commit on MacOS after proxy plugin

- src/plugins/intel_cpu/src/nodes/bin_conv.cpp
- src/plugins/intel_cpu/src/nodes/kernels/x64/registers_pool.hpp
- src/plugins/intel_cpu/src/nodes/mvn.cpp
> [CPU] Fix of coverity issues

- src/plugins/proxy/src/infer_request.cpp
- src/plugins/proxy/src/remote_context.hpp
- src/plugins/proxy/src/remote_tensor.hpp
- src/plugins/proxy/src/variable_state.hpp
- Add proxy variable state to hold shared object of low level plugin
- *ticket-id*
> Add variable state for proxy plugin

- src/plugins/intel_gpu/src/graph/roi_align.cpp
- *Apply ngraph shape infer for ROIAlign*
- *ROIAlgin shape infer test is already merged*
- *103940*
> [GPU] Apply ngraph shape infer for ROIAlign

- src/plugins/intel_gpu/src/graph/depth_to_space.cpp
- src/plugins/intel_gpu/src/graph/include/depth_to_space_inst.h
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/deth_to_space.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/depth_to_space_si_test.cpp
- Update `DepthToSpace` to use nGraph shape inference for requirement on dynamic model
- 100229
> [GPU] Update DepthToSpace to use nGraph shape inference

- src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/detection_output.cpp
- src/plugins/intel_gpu/src/graph/include/convolution_inst.h
- src/plugins/intel_gpu/src/graph/include/loop_inst.h
- src/plugins/intel_gpu/src/graph/loop.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/eye/eye_kernel_ref.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/multiclass_nms/multiclass_nms_kernel_ref.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/prior_box/prior_box_kernel_ref.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/strided_slice/strided_slice_kernel_ref.h
- *a few cases fixed*
- *CVS-112770*
- *CVS-112760*
- *CVS-112761*
> [Coverity] Fix coverity

- src/core/include/openvino/core/any.hpp
- src/core/include/openvino/runtime/tensor.hpp
- src/core/src/any.cpp
- src/core/src/runtime/ov_tensor.cpp
- src/inference/include/openvino/runtime/remote_context.hpp
- src/inference/include/openvino/runtime/variable_state.hpp
- src/inference/src/cpp/ie_remote_context.cpp
- src/inference/src/cpp/ie_variable_state.cpp
- src/inference/src/dev/converter_utils.cpp
- src/inference/src/infer_request.cpp
- Remove vector of so from
- Any
- Tensor
- RemoteContext
- VariableState
- *ticket-id*
> Remove vector of so objects from Tensor, Any, VariableState and RemoteContext

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- Null users protection
- *...*
- 114869
> [GPU] Fix DG2 units tests with null users

- docs/optimization_guide/nncf/ptq/basic_quantization_flow.md
- *item1*
- *...*
- CVS-111580
- CVS-111574
> [DOCS] Basic quantization flow additions

- src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/tests/unit/passes/reorder_inputs_test.cpp
- *Set preferred format to default format of out layout rank when the current node has reshape user node*
- *Add unit test*
- *100495*
> [GPU] Fix kernel selecting issue on dynamic model with static input shape

- .github/workflows/linux.yml
- Add missing stages (Conversion UT, Proxy Plugin Tests)
- fix executable name for Common Utils Tests
> [CI] [GHA] Add missing stages (Conversion UT, Proxy Plugin Tests) and fix executable name for Common Utils Tests

- src/core/include/ngraph/graph_util.hpp
- Fix deprecation warning for debian build
- *ticket-id*
> Fix for openvino-lin-debian build

- src/plugins/proxy/src/plugin.cpp
- Fix the issue if Nvidia plugin was found but system doesn't have cuda in environment
- *ticket-id*
> Catch errors in case if some plugin doesn't have environment on the system

- src/plugins/intel_cpu/src/nodes/reduce.cpp
- src/plugins/intel_cpu/src/nodes/reduce.h
- *Support dequantization fusing for Reduce node*
- *Support division directly in first JIT kernel for some cases of ReduceMean*
- *79072*
> [CPU] Fix performance issue for some cases of Reduce node

- docs/OV_Runtime_UG/ov_infer_request.md
- docs/OV_Runtime_UG/supported_plugins/GNA.md
> [DOCS] minor fixes

- src/plugins/intel_cpu/src/nodes/pad.cpp
- src/plugins/intel_cpu/src/nodes/pad.h
- src/plugins/intel_cpu/tests/functional/single_layer_tests/pad.cpp
- src/tests/functional/shared_test_classes/src/base/utils/compare_results.cpp
- *Support operation Pad-12 in the CPU plugin*
- *110244*
> [CPU] Support Pad-12.

- src/plugins/intel_gpu/src/graph/include/roi_pooling_inst.h
- src/plugins/intel_gpu/src/graph/roi_pooling.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/roi_pooling.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/roi_pooling_si_test.cpp
- Update ROIPooling to use nGraph shape inference for requirement on dynamic model
- 100231
> [GPU] Update ROIPooling to use nGraph shape inference

- .github/workflows/windows.yml
- tests/layer_tests/pytorch_tests/test_if.py
- tests/layer_tests/pytorch_tests/test_topk.py
- tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_upsampling2d.py
- tools/mo/unit_tests/mo/frontend_ngraph_test.py
This PR introduces the Windows pipeline that is executed in the GitHub Actions environment. It is similar to the Windows Azure pipeline in terms of stages: OV Build, Install; C++ tests, CPU Functional tests. Also, it adds the Python Tests that are not executed in Azure.
This pipeline utilizes the GitHub-provided runners both for building and testing. Also, it uses the GitHub Actions cache to speed up the build stage of the pipeline.
- *112120*
> [CI] Introduce Windows pipeline in GitHub Actions

- src/core/tests/ov_tensor_test.cpp
- src/inference/src/dev/make_tensor.cpp
Reverts openvinotoolkit/openvino#18479
> Revert "Fixed cases if cast data from Tensor to compatible type"

- thirdparty/dependencies.cmake
- Brew tests https://github.com/Homebrew/homebrew-core/pull/134935
- Conda-forge tests https://github.com/conda-forge/openvino-feedstock/pull/20
- *ticket-id*
> Rely on find_package(OpenCL)

- cmake/developer_package/packaging/common-libraries.cmake
- src/bindings/python/CMakeLists.txt
- src/bindings/python/wheel/setup.py
- Required for Python API distribution in conda-forge and brew
> Ability to configure setup.py via env variables

- src/common/snippets/include/snippets/pass/common_optimizations.hpp
- src/common/snippets/include/snippets/pass/tokenization.hpp
- src/common/snippets/src/pass/common_optimizations.cpp
- src/common/snippets/src/pass/tokenization.cpp
- src/common/snippets/tests/include/pass/mha_tokenization.hpp
- src/common/snippets/tests/src/pass/mha_tokenization.cpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/tests/ngraph_helpers/snippets_ngraph_functions/include/subgraph_mha.hpp
- src/tests/ngraph_helpers/snippets_ngraph_functions/src/subgraph_mha.cpp
- src/tests/test_utils/common_test_utils/src/ngraph_test_utils.cpp
- *Added SplitDimensionM optimization which split dimension M for MatMul to increase concurrency*
- *Enabled the optimization only when `SnippetsMode = Enabled` to not break tests with checks of node count*
- *111979*
> [Snippets] Added SplitDimensionM optimization

- cmake/developer_package/plugins/plugins.cmake
- src/plugins/hetero/src/plugin.cpp
- src/plugins/template/src/plugin.cpp
- File with version excludes from the main target, as a result we don't apply clang format for this file
- *ticket-id*
> Fixed clang format for plugin files with version

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/include/primitive_type_base.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- Add new debug config(OV_GPU_DisableAsyncCompilation) to disable async compilation
- Add debug log for layout calculation
- *ticket-id*
> [GPU] Add debug config for disabled async compilation

- src/plugins/intel_gpu/tests/unit/module_tests/weights_reorder_factory_test.cpp
> [GPU] move a test file.

- src/plugins/intel_gna/src/gna_device.cpp
- src/plugins/intel_gna/src/gna_device.hpp
- src/plugins/intel_gna/src/gna_plugin.cpp
- Added method to GNA device helper to check if HW is available
- Added check in QueueInference if GNA_HW mode can be executed
- 108937
> [GNA] Clear error message when GNA_HW mode is set, but HW is unavailable

- cmake/developer_package/compile_flags/sdl.cmake
> Enable `-pie` option for MacOS

- src/plugins/hetero/src/compiled_model.cpp
- src/plugins/hetero/src/compiled_model.hpp
- src/plugins/hetero/src/config.cpp
- src/plugins/hetero/src/plugin.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- Several changes after https://github.com/openvinotoolkit/openvino/pull/18429
- CVS-109770
> Hetero 2.0 leftovers

- src/plugins/hetero/src/compiled_model.cpp
- https://github.com/openvinotoolkit/openvino/pull/18559#discussion_r1264806877
> Remove excess ov::Model clone in Hetero

- src/plugins/intel_gpu/include/intel_gpu/runtime/stream.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
- src/plugins/intel_gpu/src/runtime/ocl/ocl_event.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_event.hpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.hpp
- src/plugins/intel_gpu/tests/unit/onednn/profiling_test.cpp
- src/plugins/intel_gpu/thirdparty/CMakeLists.txt
- Added device-time profiling support for OneDNN primitives
- *ticket-id*
> [GPU] Add oneDNN primitives profiling support

- tools/mo/openvino/tools/mo/convert_impl.py
- tools/mo/openvino/tools/mo/utils/check_ie_bindings.py
- tools/mo/openvino/tools/mo/utils/telemetry_params.py
- tools/mo/openvino/tools/mo/utils/telemetry_utils.py
- tools/ovc/openvino/tools/ovc/convert_impl.py
- tools/ovc/openvino/tools/ovc/telemetry_params.py
- tools/ovc/openvino/tools/ovc/telemetry_utils.py
Description: 
Use GA4 telemetry backend in MO and OVC.
Ticket: 110432
Code:
Validation:
Documentation:
> Use GA4 telemetry backend in MO and OVC.

- docs/install_guides/configurations-for-intel-gpu.md
Ticket: 105445
* Updated GPU install instruction for Linux
* Added Ubuntu 22.04 installation method with the link to the proper driver version
> [DOCS] GPU install for linux update for 22.3

- docs/install_guides/configurations-for-intel-gpu.md
Port from https://github.com/openvinotoolkit/openvino/pull/18610
Ticket: 105445
Updated GPU install instruction for Linux
> [DOCS] GPU install for linux update for master

- docs/install_guides/configurations-for-intel-gpu.md
Ticket: 105445
Updated GPU install instruction for Linux
> [DOCS] GPU install for linux update for 23.0

- tools/mo/openvino/tools/mo/convert.py
- tools/mo/openvino/tools/mo/convert_impl.py
- tools/mo/openvino/tools/mo/moc_frontend/pipeline.py
- tools/mo/unit_tests/mo/utils/cli_parser_test.py
- tools/ovc/openvino/tools/ovc/convert.py
- tools/ovc/openvino/tools/ovc/moc_frontend/pipeline.py
- tools/ovc/unit_tests/ovc/utils/cli_parser_test.py
> Changed name of enable_mmap flag for MO/OVC + implemented missing passing flag for mo/moc_frontend/pipeline.py

- src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/include/read_ir_test/read_ir.hpp
- src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir.cpp
- src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir_tests.cpp
> [confomance] Add import export tests to opset

- src/inference/tests/functional/get_supported_property_test.cpp
- src/inference/tests/functional/ov_register_plugin_test.cpp
- src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration_sw.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/file_utils.hpp
> [apiConformance] Move related to core tests from api to ov_inference_functional_tests

- src/common/transformations/include/transformations/common_optimizations/nop_elimination.hpp
- src/common/transformations/include/transformations/utils/utils.hpp
- src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
- src/common/transformations/src/transformations/utils/utils.cpp
- src/common/transformations/tests/common_optimizations/nop_elimination.cpp
- *Eliminates Nop Broadcast/Tile and Slice Before GatherElements*
- *Enhances performance of several LLMs*
> Eliminates Nop Broadcast/Tile and Slice Before GatherElements

- src/frontends/onnx/onnx_common/CMakeLists.txt
- src/frontends/onnx/onnx_common/src/utils.cpp
- thirdparty/dependencies.cmake
- *item1*
- *...*
- *ticket-id*
> Removed explicit linkage to protobuf in ONNX FE

- src/common/transformations/include/transformations/fp16_compression/mark_decompression_convert_constant_folding.hpp
- src/common/transformations/src/transformations/fp16_compression/mark_decompression_convert_constant_folding.cpp
- src/plugins/intel_cpu/src/graph_optimizer.cpp
- src/plugins/intel_cpu/src/graph_optimizer.h
- src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/convert_matmul_to_fc.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_decompress_convert.cpp
- src/plugins/intel_cpu/tests/unit/ngraph_transformations/convert_matmul_test.cpp
Issue: 105060
PR to oneDNN fork: https://github.com/openvinotoolkit/oneDNN/pull/199
> [CPU] f16 constant folding on cpu plug-in side for MatMul only

- src/plugins/intel_gpu/src/plugin/ops/split.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_model_static_split_layer.cpp
- *Set offset of split at CreateCommonSplitOp for static shaped layer*
- *114145*
> [GPU] Set offsets of variadic split for static

- docs/_static/css/custom.css
- docs/_static/css/homepage_style.css
- docs/_static/html/newsletter.html
- docs/_static/js/custom.js
- docs/_static/js/newsletter.js
- docs/_templates/layout.html
- docs/home.rst
- docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/footer.html
- *Restyle newsletter pop-up*
- *Add newsletter trigger button in footer*
- *Change footer to load from script instead of iframe*
- *Add carousel in homepage banner*
> [DOCS] Features update

- tests/layer_tests/tensorflow_tests/test_tf_LRN.py
> Disable sporadically failing tests

- src/inference/dev_api/openvino/runtime/make_tensor.hpp
- src/inference/src/dev/converter_utils.cpp
- src/inference/src/dev/make_tensor.cpp
- src/inference/src/dev/preprocessing/preprocessing.cpp
- src/plugins/template/tests/functional/shared_tests_instances/behavior/plugin/set_preprocess.cpp
- Restore layout from [Inputs/Outputs]Info to return Blob with correct layout
- CVS-113704
> Restore information about Blob layout for new plugins

- src/inference/src/os/mac/mac_system_conf.cpp
- *update numa_node id and socket id in proc_type_table for MacOS*
- *...*
- *ticket-id*
> update proc_type_table for MacOS

- src/frontends/pytorch/src/op/rand.cpp
- Fixed build after https://github.com/openvinotoolkit/openvino/pull/18616
- *ticket-id*
> Fix PyTorch FE build with clang compiler

- src/inference/src/os/cpu_map_info.hpp
- src/inference/src/os/mac/mac_system_conf.cpp
- *add socket id initialization in MacOS*
- *ticket-id*
> add socket id initialization in MacOS

- src/tests/functional/plugin/conformance/subgraphs_dumper_new/include/cache/graph_cache.hpp
- *item1*
- *...*
- *ticket-id*
> [CONFORMANCE] Fix compilation on Debian Post-commit

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- src/plugins/intel_gpu/src/runtime/execution_config.cpp
- Add new debug config(`OV_GPU_DisableDynamicImpl`) to disable dynamic implementation
- 115838
> [GPU] Add debug config for disabled dynamic implementation

- src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/prior_box.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/prior_box.cpp
- src/plugins/intel_gpu/src/graph/include/prior_box_inst.h
- src/plugins/intel_gpu/src/graph/prior_box.cpp
- src/plugins/intel_gpu/src/plugin/ops/prior_box.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/prior_box.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/prior_box_gpu_test.cpp
- Add dynamic shape support for priorbox/priorboxclustered
- 114498
- 100195
> [GPU] PriorBox dynamic shape support

- src/core/include/openvino/op/region_yolo.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/region_yolo.hpp
- src/plugins/intel_gpu/src/graph/include/region_yolo_inst.h
- src/plugins/intel_gpu/src/graph/region_yolo.cpp
- src/plugins/intel_gpu/src/plugin/ops/region_yolo.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/region_yolo.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/region_yolo_si_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/region_yolo_gpu_test.cpp
- Update `RegionYolo` to use ngraph shape inference for requirement on dynamic model
- 100234
> [GPU] Update RegionYolo to use nGraph shape inference

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/tests/unit/dynamic_execution/optimized_out_execution_test.cpp
- fix null impl case for optimized out concat
- 113114
> [GPU] fix null impl case for optimized out concat

- src/plugins/intel_gpu/src/graph/impls/ocl/activation.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/activation_simple_gpu_test.cpp
- Update to skip slop size check logic when `PReLU` is dynamic impl
- 101242
> [GPU] Minor fix for dynamic model

- tests/layer_tests/pytorch_tests/test_quantized_convnd.py
- tests/layer_tests/pytorch_tests/test_quantized_linear.py
> [PT FE] Enable quantized conv and linear tests

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- New debug config to disable runtime buffer fusing for dynamic shape
- 115838
> [GPU] Add new debug config "DisableRuntimeBufferFusing"

- src/core/include/openvino/op/reorg_yolo.hpp
- src/plugins/intel_gpu/src/graph/include/reorg_yolo_inst.h
- src/plugins/intel_gpu/src/graph/reorg_yolo.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/reorg_yolo.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/reorg_yolo_si_test.cpp
- Update `ReorgYolo` to use ngraph shape inference for requirement on dynamic model
- 100204
> [GPU] Update ReorgYolo to use nGraph shape inference

- docs/install_guides/installing-openvino-conda.md
- Plugin was recently added to conda-forge https://anaconda.org/conda-forge/libopenvino-intel-gpu-plugin/files?version=2022.3.1
> Remove note about GPU plugin absence

- src/core/tests/ov_tensor_test.cpp
- src/inference/src/dev/make_tensor.cpp
- Relax get_data() for tensor
- *ticket-id*
> Try to fix get_data() and lto

- docs/_static/html/newsletter.html
- docs/_static/js/newsletter.js
- add preloader to newsletter pop-up
> [DOCS] Port newsletter changes from nightly

- docs/_static/html/newsletter.html
- docs/_static/js/custom.js
- docs/_static/js/newsletter.js
- add preloader to newsletter pop-up
- add scroll nav to banner carousel
> [DOCS] Update newsletter and carousel

- docs/_static/html/newsletter.html
- docs/_static/js/custom.js
- docs/_static/js/newsletter.js
- add preloader to newsletter pop-up
- add scroll nav to banner carousel
> [DOCS] Port newsletter and carousel changes from nightly

- src/common/transformations/src/transformations/transpose_sinking/ts_gather.cpp
- src/common/transformations/tests/transpose_sinking/ts_gather_test.cpp
- fix transpose sinking backward through Gather for the case with scalar indexes
- add unit test
- 115754
> fix TSGatherBackward

- src/inference/src/dev/core_impl.cpp
- src/inference/src/dev/core_impl.hpp
- src/plugins/proxy/src/plugin.cpp
- Remove Core member and use `ov::proxy::configuration::internal_name` property instead
- *ticket-id*
> Removed core member remapped devices and use proxy config instead

- docs/get_started.md
Fixing links in Get Started article.
> [DOCS] Link fix for Get Started for master

- docs/get_started.md
Port from https://github.com/openvinotoolkit/openvino/pull/18798
Fixing links in Get Started article.
> [DOCS] Link fix for Get Started for 23.0

- src/common/util/CMakeLists.txt
- See https://github.com/microsoft/vcpkg/issues/32307
> Renamed util to openvino_util

- src/tests/test_utils/functional_test_utils/layer_tests_summary/template/filters_api.js
- *percentages for the Mandatory and Optional Scope have been swapped*
- *CVS-116515*
> [apiConformanceReport] Fix result passrate percentage

- docs/optimization_guide/memory_optimization_guide.md
- Extend guide after https://github.com/openvinotoolkit/openvino/pull/18026
> Note ONNX FE in `mem_optimization_guide.md`

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- DisableMemoryReuse config for debug purpose
- 115838
> [GPU] Add new debug config OV_GPU_DisableMemoryReuse

- src/plugins/intel_gpu/src/plugin/ops/constant.cpp
- *When the user is Convert for Constant node, and tensor is 1d, Set needBatchInterpretation to true*
- *111516*
> Modify the condition making batch interpretation true/false

- src/bindings/python/src/openvino/frontend/pytorch/fx_decoder.py
- src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
- src/bindings/python/src/openvino/frontend/pytorch/utils.py
- *item1*
- *...*
- *ticket-id*
> [PT FE]: cleanup unused imports

- src/tests/test_utils/common_test_utils/include/common_test_utils/postgres_helpers.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/postgres_link.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/test_common.hpp
- src/tests/test_utils/common_test_utils/src/postgres_helpers.cpp
- src/tests/test_utils/common_test_utils/src/postgres_link.cpp
- src/tests/test_utils/common_test_utils/src/test_common.cpp
- Aligned namespaces with an actual master
- N/A
> [CONF] Aligned namespaces with an actual master

- src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend.py
- src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/compile.py
- src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/execute.py
- Signature generation updates for in-memory caching and IR saving/loading in TorchFX backend.
- Added function to clear all caches in TorchFX backend.
> TorchFX caching fix

- src/frontends/tensorflow_lite/src/utils.cpp
- Fixed loading error when string type is detected
- 114332
> [TF Lite] Fixed loading error when string type is detected

- src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
- src/bindings/python/src/openvino/frontend/pytorch/utils.py
- src/frontends/pytorch/include/openvino/frontend/pytorch/decoder.hpp
- src/frontends/pytorch/src/translate_session.cpp
- *Partially disable freezing for int8 and uint8 weights*
- *115883*
> [PT FE] Partially disable freezing for int8 and uint8 weights

- src/bindings/python/CMakeLists.txt
- Solves https://github.com/openvinotoolkit/openvino/issues/18847
> Added a WA for running Python API in debug mode

- src/bindings/python/src/pyopenvino/core/properties/properties.cpp
- src/bindings/python/src/pyopenvino/utils/utils.cpp
- src/bindings/python/tests/test_runtime/test_properties.py
- src/inference/include/openvino/runtime/properties.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/device_info.hpp
- src/plugins/intel_gpu/src/plugin/plugin.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
- src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp
- src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp
- Added common luid property
- *115257*
> [GPU] LUID property added

- .ci/azure/linux.yml
- .ci/azure/linux_debian.yml
- .ci/azure/windows.yml
- .github/workflows/linux.yml
- .github/workflows/windows.yml
- *Added `ov_snippets_func_tests` validation to Azure and GitHub workflows CI*
> [Snippets][CI] Added ov_snippets_func_tests validation to Azure CI

- tools/mo/openvino/tools/mo/ops/group_norm.py
- tools/mo/openvino/tools/mo/ops/scatter.py
- tools/mo/unit_tests/mo/utils/ir_reader/ops_test.py
- *Add opset12 operations to MO IR Reader*
- *111055*
- *114905*
- *114907*
> [MO] Add opset12 operations to MO IR Reader

- src/plugins/auto_batch/tests/functional/skip_tests_config.cpp
- *all test can pass in latest master*
- *104865*
> remove AutoBatching_Test_DetectionOutput in skip config

- src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/resample.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/resample.cpp
- src/plugins/intel_gpu/src/graph/resample.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_pil_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/common_types.h
- src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_base.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_pil_ref.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_pil_ref.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_selector.cpp
- src/plugins/intel_gpu/src/plugin/ops/interpolate.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/interpolate.cpp
- src/tests/functional/plugin/shared/include/single_layer_tests/interpolate.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/interpolate.hpp
- src/tests/functional/shared_test_classes/src/single_layer/interpolate.cpp
- *Interpolate bilinear pillow kernel*
- *Interpolate bicubic pillow kernel*
- *Tests which cover Interpolate bilinear pillow mode functionality*
- *[CVS-109847](https://jira.devtools.intel.com/browse/CVS-109847)*
> [GPU] Interpolate v11 GPU reference implementation

- cmake/dependencies.cmake
- *enable canary for mac arm64 oneTBB2021.2.1*
- *115727*
> enable canary for mac arm64 oneTBB2021.2.1

- src/tests/functional/plugin/conformance/subgraphs_dumper_new/tests/skip_tests_config.cpp
@ilya-lavrenov Please merge these temporary changes
> [CONFORMANCE][TOOLS] Temporary skip part of  subgraphsDumper tests

- src/plugins/intel_gpu/tests/functional/concurrency/gpu_concurrency_tests.cpp
- src/plugins/intel_gpu/tests/functional/remote_blob_tests/gpu_remote_tensor_tests.cpp
- src/tests/functional/plugin/shared/include/multi/multi_remote_blob_multidevice_test.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/data_utils.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/ov_tensor_utils.hpp
- src/tests/test_utils/common_test_utils/src/data_utils.cpp
- src/tests/test_utils/functional_test_utils/include/functional_test_utils/blob_utils.hpp
- src/tests/test_utils/functional_test_utils/include/functional_test_utils/summary/op_info.hpp
- src/tests/test_utils/functional_test_utils/include/functional_test_utils/summary/summary.hpp
- src/tests/test_utils/functional_test_utils/src/summary/op_info.cpp
- src/tests/test_utils/functional_test_utils/src/summary/summary.cpp
- Eliminate code duplication in func and common test utils
- Remove unused code
- [CVS-116636](https://jira.devtools.intel.com/browse/CVS-116636)
> Refactor func test utils

- src/inference/src/core.cpp
- src/inference/src/dev/core_impl.hpp
- src/inference/src/ie_core.cpp
- src/inference/src/precomp.hpp
- *item1*
- *...*
- *ticket-id*
> Remove old API from Core implementation

- src/plugins/intel_cpu/src/nodes/reduce.cpp
- src/plugins/intel_cpu/src/nodes/reduce.h
- src/plugins/intel_cpu/tests/functional/single_layer_tests/instances/x64/reduce.cpp
- *Fix Reduce node bug regarding fusing with low precision.*
- *CVS-115506*
- *CVS-116115*
- *CVS-116792*
> Fix Reduce node bug regarding fusing with low precision

- src/plugins/proxy/src/plugin.cpp
- Add more information in error messages from proxy plugin
- *ticket-id*
> Extend error messages from proxy plugin

- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_expand.py
- *support aten::broadcast_to operator*
Ref: CVS-116862
> [PT FE]: support aten::broadcast_to

- cmake/dependencies.cmake
- *update sha256 of signed oneTBB2021.2.1 on mac(arm64)*
- *115727*
> update sha256 of oneTBB2021.2.1 on mac arm64

- .ci/azure/linux.yml
- .github/workflows/linux.yml
- src/bindings/python/setup.cfg
- src/bindings/python/tests/conftest.py
- src/bindings/python/tests/test_graph/test_node_factory.py
- src/bindings/python/tests/test_runtime/test_core.py
- src/bindings/python/tests_compatibility/conftest.py
- added run of python tests with extension on azure/github action jobs
- unskipped test
- 95983
> [PyOV] try to run add_extension_test

- cmake/features.cmake
- *item1*
- *...*
- *ticket-id*
> Use prebuilt TBB on macos arm64

- src/inference/dev_api/performance_heuristics.hpp
- src/plugins/intel_cpu/src/plugin.cpp
- *do streams calculation before UpToCpuSpecificOpSet() in CPU plugin*
- *ticket-id*
> do streams calculation before UpToCpuSpecificOpSet() in CPU plugin

- src/cmake/ie_parallel.cmake
- src/plugins/intel_cpu/CMakeLists.txt
- Solves https://github.com/openvinotoolkit/openvino/issues/18465
- Fix in vcpkg https://github.com/microsoft/vcpkg/pull/32773
> Fixed CPU build with standalone oneDNN

- src/frontends/tensorflow/src/op_table.cpp
- src/frontends/tensorflow_common/src/op/shape.cpp
- tests/layer_tests/tensorflow_tests/test_tf_ShapeN.py
**Details:** Support ShapeN operation
**Ticket:** 111309
> [TF FE] Support ShapeN operation

- src/plugins/intel_gpu/src/graph/impls/cpu/detection_output.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/detection_output.cpp
- Add num_classes=-1 support in cpu_impl of detection_output
- 101235
> [GPU] Add num_classes=-1 support in cpu_impl of detection_output

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/include/reorder_inst.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_redundant_reorder_at_runtime.cpp
- Skip reorder at runtime if it is needless to run
- 116688
> [GPU] Skip reorder at runtime if data type and format are not changed

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/include/strided_slice_inst.h
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/strided_slice_gpu_test.cpp
- Allow StridedSlice as predecessor for in place concat optimization during runtime
- Enable padding support for StridedSlice
- 112029
> [GPU] Allow StridedSlice as predecessor for in place concat

- src/frontends/common/src/plugin_loader.cpp
- Extended error message to provide an additional advice for the user
- CVS-106237
> Extend loading frontend error message

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/plugin/auto_batching_tests.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- src/tests/functional/plugin/shared/include/behavior/plugin/auto_batching_tests.hpp
> [ARM CPU] Skip autobatch tests on arm32 arch

- docs/dev/build_linux.md
- docs/dev/build_windows.md
- src/bindings/python/docs/test_examples.md
- the PYTHONPATH changed, so need to update docs
- *ticket-id*
> [DOCS] Update PYTHONPATH in docs

- .ci/azure/linux_debian.yml
- .github/ISSUE_TEMPLATE/pre_release_feedback.yml
- Fix for a failing postcommit check
- N/A
> Add MO to PYTHONPATH in lin-debian Azure job

- cmake/templates/InferenceEngineDeveloperPackageConfig.cmake.in
- cmake/templates/OpenVINODeveloperPackageConfig.cmake.in
- *item1*
- *...*
- CVS-111912
> Use OpenCV_DIR from cache only if user doesn't define OpenCV_DIR

- src/plugins/intel_gpu/src/graph/normalize.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/normalize_l2.cpp
- fix normalize dynamic shape support
- add dynamic shape test cases
- 101235
> [GPU] fix normalize dynamic shape support

- src/plugins/intel_gpu/src/graph/impls/ocl/prior_box.cpp
- src/plugins/intel_gpu/src/graph/include/prior_box_inst.h
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/graph/prior_box.cpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/prior_box/prior_box_kernel_ref.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/prior_box/prior_box_kernel_ref.h
- src/plugins/intel_gpu/src/plugin/ops/prior_box.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/prior_box.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/prior_box.cpp
- src/plugins/intel_gpu/tests/unit/dynamic_execution/priorbox_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/prior_box_gpu_test.cpp
- src/tests/functional/shared_test_classes/src/single_layer/prior_box.cpp
- Fix priorbox constant propagation
- Add priorbox kernel validate() to avoid clustered version which causes seg fault
- Add unit test for dynamic shape case
- Update existing unit test/func test for new flow
- 101235
> [GPU] Fix priorbox constant propagation

- src/plugins/intel_gpu/src/graph/grid_sample.cpp
- src/plugins/intel_gpu/src/graph/include/grid_sample_inst.hpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/grid_sample.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/grid_sample_si_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/grid_sample_gpu_test.cpp
- *Enable dynamism for grid_sample*
- *100222*
- *116385*
> [GPU Enable dynamism for grid_sample

- src/frontends/tensorflow/src/input_model.cpp
- src/frontends/tensorflow/src/tf_utils.cpp
- src/frontends/tensorflow/tests/convert_saved_model.cpp
- src/frontends/tensorflow/tests/test_models/gen_scripts/generate_saved_model_intermediate_output.py
**Details:** Handle intermediate outputs in SavedModel. The fix helps in conversion of UNet model.
**Ticket:** 116451
> [TF FE] Handle intermediate outputs in SavedModel

- src/plugins/intel_gpu/include/intel_gpu/plugin/infer_request.hpp
- src/plugins/intel_gpu/src/plugin/infer_request.cpp
- No need to do output memory copy with blocking
- 117086
> [GPU] Non blocking enqueMemCpy for copy output data

- src/frontends/pytorch/src/frontend.cpp
- tests/layer_tests/mo_python_api_tests/test_mo_convert_pytorch.py
- *Raise graceful exception when model has incorrect type*
- *116876*
> [PT FE] Raise graceful exception when model has incorrect type

- src/frontends/pytorch/src/op/outer.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_outer.py
- *isupported aten::outer op*
-  *CVS-116866*
> [PT FE]: support aten::outer op

- docs/dev/build_webassembly.md
> fix at docs/dev/build_webassembly.md

- src/inference/src/dev/preprocessing/mean_image.cpp
- src/inference/src/dev/preprocessing/mean_image.hpp
- src/inference/src/dev/preprocessing/preprocessing.hpp
- src/inference/src/dev/threading/istreams_executor.cpp
- Removed legacy components from some inference objects
- *ticket-id*
> Removed some deprecated API from inference component

- src/common/transformations/src/transformations/fp16_compression/mark_subgraphs_to_keep_in_mixed_precision.cpp
- src/common/transformations/tests/common_optimizations/mark_subgraph_to_keep_in_mixed_precision_test.cpp
- When `eps` goes through `Convert` `MarkSugraphsToKeepInMixedPrecision` was not triggered and we end up having `NaN` for LLM.
- [CVS-113800](https://jira.devtools.intel.com/browse/CVS-113800)
> Fix Division with eps marking

- src/common/low_precision_transformations/include/low_precision/layer_transformation.hpp
- src/common/low_precision_transformations/src/fake_quantize_decomposition.cpp
- src/common/low_precision_transformations/src/layer_transformation.cpp
- src/common/low_precision_transformations/src/recurrent_cell.cpp
- src/common/low_precision_transformations/src/weightable_layer_transformation.cpp
- src/common/low_precision_transformations/tests/unit/data_precision_check.cpp
- src/common/low_precision_transformations/tests/unit/layer_transformation_get_data_precision.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/convolution_transformation.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/convolution_transformation.cpp
- src/tests/functional/plugin/shared/src/low_precision_transformations/convolution_transformation.cpp
- src/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/common/fake_quantize_on_data.hpp
- *[LPT] Unexpected quantisation level fix*
- *CVS-112304*
> [LPT] Unexpected quantisation level fix

- .ci/azure/android_arm64.yml
- .ci/azure/linux.yml
- .ci/azure/linux_arm64.yml
- .ci/azure/linux_conditional_compilation.yml
- .ci/azure/linux_coverity.yml
- .ci/azure/linux_cuda.yml
- .ci/azure/linux_debian.yml
- .ci/azure/linux_ngraph_onnx.yml
- .ci/azure/linux_onnxruntime.yml
- .ci/azure/mac.yml
- .ci/azure/windows.yml
- cmake/templates/OpenVINOConfig.cmake.in
- Example of failure which is not caught https://dev.azure.com/openvinoci/dldt/_build/results?buildId=616188&view=logs&j=503d1592-119c-586f-46c7-e27f62244013&t=5c485c36-fdb0-57c3-3e29-d0672a642f19
- *ticket-id*
> Detect failures in multi-line steps in Azure

- docs/resources/prerelease_information.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] Delete GNA pre-release content

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- Add new debug config(`OV_GPU_DisablePrimitiveFusing`) to disable primitive fusing
- 115838
> [GPU] Add debug config for disabled primitive fusing

- src/plugins/intel_gpu/src/graph/crop.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/split.cpp
- *Support non constant input of split length for variadic split*
- *116385*
> [GPU] Support non constant input of split length for variadic split

- src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
- *update streams calculation for latency mode on MacOS to use all CPU on big core/small core platform*
- *ticket-id*
> update streams calculation for latency mode on MacOS

- src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
- src/plugins/intel_gpu/src/graph/include/program_node.h
- src/plugins/intel_gpu/src/graph/program_node.cpp
+ Added is_padded_spatial to program_node
+ Added reorder to remove padded input in spatial axis for mvn
+ case applied only for blocked formats of implemented mvn opt kernel
- *item1*
- *...*
- 115588
> [GPU] Add reorder to avoid perf drop by using mvn_ref kernel

- src/frontends/pytorch/src/op/masked_scatter.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_masked_scatter.py
- *support aten::masked_scatter*
tested on fastcomposer model
- *CVS-117242*
> [PT FE]: support aten::masked_scatter

- src/frontends/tensorflow/src/op_table.cpp
- src/frontends/tensorflow_common/include/common_op_table.hpp
- src/frontends/tensorflow_common/src/op/adjust_contrast.cpp
- tests/layer_tests/tensorflow_tests/test_tf_AdjustContrastv2.py
**Details:** Support AdjustContrastv2 operation
**Ticket:** 111317
> [TF FE][TF Hub] Support AdjustContrastv2 operation

- docs/resources/prerelease_information.md
Port from https://github.com/openvinotoolkit/openvino/pull/19000
> [DOCS] Delete GNA pre-release content for master

- src/plugins/intel_cpu/src/nodes/conv.cpp
- src/plugins/intel_cpu/tests/functional/subgraph_tests/src/conv_dw_conv.cpp
> [CPU] Fix initSupportedPrimitiveDescriptors for conv_dw_conv case

- src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
- *fix unused variable issue for PR 18818*
- *...*
- *ticket-id*
> fix unused variable issue for PR 18818

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- *is_padding_supported() should be checked even for static shape when buffer fusing*
- *112977*
> [GPU] Check if padding is supported for static shape when buffer fusing

- src/plugins/intel_gpu/include/intel_gpu/primitives/batch_to_space.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/space_to_batch.hpp
- src/plugins/intel_gpu/src/graph/batch_to_space.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/batch_to_space.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/space_to_batch.cpp
- src/plugins/intel_gpu/src/graph/include/batch_to_space_inst.h
- src/plugins/intel_gpu/src/graph/include/space_to_batch_inst.h
- src/plugins/intel_gpu/src/graph/space_to_batch.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/batch_to_space_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/space_to_batch_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/batch_to_space/batch_to_space_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/batch_to_space/batch_to_space_kernel_base.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/batch_to_space/batch_to_space_kernel_ref.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/space_to_batch/space_to_batch_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/space_to_batch/space_to_batch_kernel_base.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/space_to_batch/space_to_batch_kernel_ref.cpp
- src/plugins/intel_gpu/src/plugin/ops/batch_to_space.cpp
- src/plugins/intel_gpu/src/plugin/ops/space_to_batch.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/batch_to_space.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/space_to_batch.cpp
- *Support dynamism for BatchToSpace and SpaceToBatch op*
- *115847*
- *101355*
- *100219*
- *100230*
> [GPU] Support dynamic BatchToSpace and SpaceToBatch

- src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
- src/plugins/intel_gpu/tests/unit/passes/add_required_reorders_test.cpp
- Add reorder if the input format of eltwise is different from the output format during `add_required_reorders` pass
- 110281
> [GPU] Add reorder if the input format of eltwise is different from the output format

- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
> [GPU] Added gi_yxs_os_yxsv2_osv16 format to to_weights_layout map

- src/plugins/intel_gpu/src/graph/compilation_context.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/post_optimize_weights.cpp
- src/plugins/intel_gpu/src/graph/include/compilation_context.hpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/tests/unit/module_tests/kernel_impl_params_relevance_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
> [GPU] Fix premature termination of compilation task in tests

- .ci/azure/linux.yml
- .ci/azure/windows.yml
- *item1*
- *...*
- *ticket-id*
> Install local wheel packages instead of PYPI ones

- src/plugins/hetero/src/compiled_model.cpp
- src/plugins/hetero/src/properties.hpp
- src/plugins/hetero/tests/functional/compile_model_tests.cpp
- src/plugins/hetero/tests/functional/hetero_tests.cpp
- src/plugins/hetero/tests/functional/hetero_tests.hpp
- src/plugins/hetero/tests/functional/query_model_tests.cpp
- *Add ConstantFolding in compile model of HETERO plugin to avoid unexpected dynmism after model split*
- *Add new property, which shows number of subgraphs in HETERO*
- *105367*
> [HETERO] Avoid unexpected dynamism

- src/tests/functional/plugin/conformance/test_runner/conformance_infra/src/main.cpp
- Aligned naming to allow correct results posting
- N/A
> [CONF] Aligned naming for latest changes

- src/frontends/tensorflow_common/src/op/interpolate.cpp
**Details:** Simplify ResizeBilinear and ResizeNearestNeighbor translators
> [TF FE] Simplify ResizeBilinear and ResizeNearestNeighbor translators

- src/plugins/intel_gpu/src/graph/compilation_context.cpp
> [GPU] Fix data race in CompilationContext

- src/plugins/intel_gpu/include/intel_gpu/primitives/random_uniform.hpp
- src/plugins/intel_gpu/src/graph/include/random_uniform_inst.h
- src/plugins/intel_gpu/src/graph/random_uniform.cpp
- src/plugins/intel_gpu/src/plugin/ops/random_uniform.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/random_uniform.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/random_uniform_si_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/random_uniform_gpu_test.cpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/base/ov_subgraph.hpp
- src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
- src/tests/functional/shared_test_classes/src/single_layer/random_uniform.cpp
- RandomUniform new shape inference
- 117252
> [GPU] RandomUniform new shape inference for dynamic models support

- src/frontends/pytorch/src/op/fake_quantize.cpp
- src/frontends/pytorch/src/op/flatten.cpp
- src/frontends/pytorch/src/op/transpose.cpp
- src/frontends/pytorch/src/op/unflatten.cpp
- src/frontends/pytorch/src/utils.cpp
- src/frontends/pytorch/src/utils.hpp
- src/frontends/pytorch/src/utils_quantize.cpp
- tests/layer_tests/pytorch_tests/test_flatten.py
- tests/layer_tests/pytorch_tests/test_native_multi_head_attention.py
- *Refactor aten::flatten and aten::transpose conversion. Replace constant compare with subgraph to normalize axis.*
- *None*
> [PT FE] Refactor aten::flatten and aten::transpose conversion

- src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir_tests.cpp
- Updated opset version for reading IR test to the latest
- N/A
> [CONF] Updated opset version to the latest

- src/tests/functional/plugin/conformance/test_runner/conformance_infra/src/main.cpp
- Updated test name after latest changes in master
- N/A
> [CONF] Aligned test name with latest master

- docs/dev/build_linux.md
- docs/dev/build_windows.md
- *item1*
- *...*
-112769
Port from https://github.com/openvinotoolkit/openvino/pull/17922
> [DOCS] Adds Python wheel requirements info to docs for 23.0

- src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
- src/common/transformations/tests/common_optimizations/nop_elimination.cpp
- Same pr as [PR19012](https://github.com/openvinotoolkit/openvino/pull/19012) on master branch.
- [117464](https://jira.devtools.intel.com/browse/CVS-117464)
> [BUG] Fix bug on conversion of gather to sequeeze

- tools/mo/openvino/tools/mo/utils/get_ov_update_message.py
- tools/ovc/openvino/tools/ovc/get_ov_update_message.py
Update reminder message in MO and OVC.
Ticket: -
Code:
Validation:
Documentation:
> Update reminder message in MO and OVC.

- src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
- src/plugins/intel_cpu/src/cpu_streams_calculation.hpp
- src/plugins/intel_cpu/tests/unit/streams_info/streams_e2e_test.cpp
- src/plugins/intel_cpu/tests/unit/streams_info/streams_info_table_test.cpp
- *refactoring get_streams_info_table() for code reuse*
- *update stream info for mixing MAIN_CORE_PROC and HYPER_THREADING_PROC*
- *ticket-id*
> update stream info for mixing MAIN_CORE_PROC and HYPER_THREADING_PROC

- src/inference/src/dev/threading/cpu_streams_executor.cpp
- src/inference/src/system_conf.cpp
- src/plugins/intel_cpu/src/exec_network.cpp
- *fix socket id=-1 on macOS*
- *ticket-id*
> Xiaoxia/fix socket id=-1 on macOS

- src/core/reference/include/ngraph/runtime/reference/scatter_elements_update.hpp
- Regression after https://github.com/openvinotoolkit/openvino/pull/18231
> Fixed compilation with 32 bits

- src/plugins/intel_cpu/thirdparty/CMakeLists.txt
- See https://github.com/microsoft/vcpkg/pull/32773#issuecomment-1674156327
> [CPU] Give different output name for dnnl

- docs/install_guides/installing-openvino-apt.md
- docs/install_guides/installing-openvino-from-archive-windows.md
Implementing fixes for incorrect indentation and numbering within the installation articles.
> [DOCS] Fixing formatting issues in installation articles

- src/frontends/pytorch/src/op/cat.cpp
- src/frontends/pytorch/src/op_table.cpp
- src/frontends/pytorch/src/transforms/aten_cat_replacer.cpp
- tests/layer_tests/pytorch_tests/test_cat.py
- *support aten::concat*
verified with stable diffusion xl from optimum path
- *ticket-id*
> [PT FE] aten::concat

- src/frontends/common/include/openvino/frontend/frontend.hpp
The original comment is not correct for some time already.
> Fixed description for `convert_partially`

- src/frontends/tensorflow/src/op_table.cpp
- src/frontends/tensorflow_common/include/common_op_table.hpp
- src/frontends/tensorflow_common/src/op/fake_quant_min_max_vars.cpp
- tests/layer_tests/tensorflow_tests/test_tf_FakeQuantWithMinMaxVars.py
**Details:** Support FakeQuantWithMinMaxArgs operation
**Ticket:** 111277
> [TF FE][TF Hub] Support FakeQuantWithMinMaxArgs operation

- src/frontends/tensorflow/src/op_table.cpp
- src/frontends/tensorflow_common/include/common_op_table.hpp
- src/frontends/tensorflow_common/include/utils.hpp
- src/frontends/tensorflow_common/src/op/unsorted_segment_sum.cpp
- src/frontends/tensorflow_common/src/utils.cpp
- tests/layer_tests/tensorflow_tests/test_tf_UnsortedSegmentSum.py
**Details:** Support UnsortedSegmentSum operation
**Ticket:** 111311
> [TF FE][TF Hub] Support UnsortedSegmentSum operation

- src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
OneDNN does not support asymmetric weight.
- 116423
> [GPU] Do not select onednn format for asymmetric weight

- src/common/transformations/include/transformations/transpose_sinking/ts_utils.hpp
- src/common/transformations/src/transformations/transpose_sinking/ts_binary.cpp
- src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp
- src/common/transformations/tests/transpose_sinking/ts_binary_test.cpp
- fix TSBinaryBackward transformation
- add unit tests
- 102236
> TransposeSinking PRelu special slope fix input(1) 

- src/common/util/include/openvino/util/mmap_object.hpp
- src/common/util/src/os/lin/lin_mmap_object.cpp
- src/common/util/src/os/win/win_mmap_object.cpp
- src/frontends/onnx/frontend/src/core/attribute.hpp
- src/frontends/onnx/frontend/src/core/graph.cpp
- src/frontends/onnx/frontend/src/core/graph.hpp
- src/frontends/onnx/frontend/src/core/node.cpp
- src/frontends/onnx/frontend/src/core/sparse_tensor.hpp
- src/frontends/onnx/frontend/src/core/tensor.hpp
- src/frontends/onnx/frontend/src/editor.cpp
- src/frontends/onnx/frontend/src/editor.hpp
- src/frontends/onnx/frontend/src/onnx.cpp
- src/frontends/onnx/frontend/src/utils/onnx_internal.cpp
- src/frontends/onnx/frontend/src/utils/onnx_internal.hpp
- src/frontends/onnx/frontend/src/utils/tensor_external_data.cpp
- src/frontends/onnx/frontend/src/utils/tensor_external_data.hpp
- Implemented cache for MMAP handles
- 116326
> [ONNX] Implemented cache for MMAP handles

- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
> Fixed checks in snippets_mark_skipped for MatMul weights

- src/frontends/pytorch/src/op/rand.cpp
- src/frontends/pytorch/src/op_table.cpp
- src/frontends/pytorch/src/transforms/aten_index_put_replacer.cpp
- src/frontends/pytorch/src/transforms/listconstruct_replacer.cpp
- tests/layer_tests/pytorch_tests/test_index.py
- tests/layer_tests/pytorch_tests/test_index_put_.py
- *Support aten::randint and aten::index_put_ on mask*
- *115812*
> [PT FE] Support aten::randint and aten::index_put_ on mask

- src/plugins/intel_cpu/src/nodes/cum_sum.cpp
- Fix ARM post-commit
- 117784
> [CPU][ARM] Enable FP16 precision for CumSum node

- src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/graph/program_node.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/arg_max_gpu_test.cpp
- *Fix multiple output layout issue which only return first layout in get_output_layouts*
- *100495*
> [GPU] Fix multiple output issue in get_output_layout

- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
> Added giy_xs_os_xsv2_osv8__ao32 format to to_weights_layout map

- src/inference/src/dev/threading/cpu_streams_executor.cpp
- *port from [PR](https://github.com/openvinotoolkit/openvino/pull/18868)*
- *store CPUStreamsExecutor::Impl::stream in another map instead of tbb enumerable_thread_specific if the the thread is not created by CPUStreamsExecutor*
- *111490*
> [Core] fix Memory Leak caused by create/inference request consequently in separate thread

- src/frontends/onnx/frontend/src/utils/random_normal.cpp
- Removed randomization on frontend size for RandomNormal
- 117280
> [ONNX] Removed seed randomization on frontend size for RandomNormal

- src/common/transformations/include/transformations/utils/utils.hpp
- src/common/transformations/src/transformations/utils/utils.cpp
- src/plugins/intel_gpu/src/plugin/ops/pad.cpp
- This change fixes the issue happened if Pad's pad_value constant is equal to infinity 
- 117592
> [GPU] Allow to use infinity value as a Pad's fill value

- src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/convolution.cpp
- Fix to prevent unintentional expansion of pad's rank into 2D
- 116654
> [GPU] Fix unintentional expansion of pad's rank into 2D

- src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
- *fixes problems with type checking for conditionally freeze models in ts decoder*
- *CVS-117896*
> [PT FE]: fixes type checking for freezing conditions

- src/bindings/python/src/pyopenvino/frontend/extension.cpp
... and capture GIL.
- Fix a bug with hanging process while adding extensions.
- *115994*
> [PyOV] Accept Python functions as Extension attrs

- src/frontends/pytorch/src/op/avg_poolnd.cpp
- src/frontends/pytorch/src/op/pad.cpp
- src/frontends/pytorch/src/transforms/aten_getitem_replacer.cpp
- src/frontends/pytorch/src/transforms/aten_index_replacer.cpp
- src/frontends/pytorch/src/transforms/irfftn_complex_replacer.cpp
- src/frontends/pytorch/src/transforms/rfftn_complex_replacer.cpp
- src/frontends/pytorch/src/utils.cpp
- src/frontends/pytorch/src/utils.hpp
- *In majority of cases it is better to use `Output` instead of `Node`, especially when node has multiple outputs.*
- *None*
> [PT FE] Revise usage output vs node in frontend

- tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py
C++ version doesn't have this problem.
Ticket 99702
> benchmark_app: fix grayscale model and image

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/prior_box_ref.cl
- src/plugins/intel_gpu/src/plugin/ops/prior_box.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/prior_box.cpp
- fix priorbox legacy code in CreateOp()
- allow to use max_size is null
- 101235
> [GPU] fix priorbox legacy code in CreateOp() and allow to use max_size is null

- tests/layer_tests/ovc_python_api_tests/test_tf.py
- tools/ovc/openvino/tools/ovc/moc_frontend/moc_emit_ir.py
Description:
Reverted agressive static shape in ovc
Continuation of this PR: https://github.com/openvinotoolkit/openvino/pull/19203
Ticket: -
Code:
Validation:
Documentation:
> Reverted agressive static shape in ovc

- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-raspbian.md
Minor fixes for installation of `numpy` Python library.
> [DOCS] Fixes for numpy installation for 22.3

- src/common/snippets/src/lowered/pass/init_loops.cpp
- *This PR fixes a bug which is reproducible on Windows platform in debug mode*
- *CVS-117719*
> [Snippets] init_ptr_increments: removed useless computations for non incremented ports

- tests/stress_tests/common/ie_pipelines/pipelines.cpp
- tests/stress_tests/common/ie_pipelines/pipelines.h
- tests/stress_tests/memleaks_tests/tests.cpp
- tests/stress_tests/memleaks_tests/tests_pipelines/tests_pipelines.cpp
- tests/stress_tests/memleaks_tests/tests_pipelines/tests_pipelines.h
- Covers https://github.com/openvinotoolkit/openvino/issues/17609 and tests changes from https://github.com/openvinotoolkit/openvino/pull/18868
- CVS-111490
> Add `recreate_and_infer_in_thread` memleak test

- src/common/low_precision_transformations/src/move_fake_quantize.cpp
- *[LPT] MoveFakeQuantize: Q/DQ pattern identification generalization*
- *CVS-116983*
> [LPT] MoveFakeQuantize: Q/DQ pattern identification generalization

- src/frontends/onnx/frontend/src/editor.cpp
- src/frontends/onnx/frontend/src/editor.hpp
- src/frontends/onnx/tests/onnx_editor_topological_sort.cpp
- Fixed issue with missing sort when wstring path is using
- 117654
> [ONNX] Fixed issue with missing sort when wstring path

- src/tests/functional/plugin/conformance/subgraphs_dumper/src/utils/model.cpp
- *item1*
- *...*
- *ticket-id*
> [CONFORMANCE] Add progress bar to Subgraphs Dumper

- src/core/include/openvino/op/group_normalization.hpp
- src/core/src/op/group_normalization.cpp
> Fix uninit members in default `GroupNormalization()`

- src/common/transformations/src/transformations/low_precision/mark_dequantization_subgraph.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/convert_matmul_to_fc.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
- src/plugins/intel_cpu/tests/functional/subgraph_tests/src/split_matmul_concat.cpp
Issues: 117928, 117058
FIx for https://github.com/openvinotoolkit/openvino/pull/19141
PR to release branch: https://github.com/openvinotoolkit/openvino/pull/19256
> FIxed is_on_constant_path() using in all places

- src/plugins/intel_gna/src/gna_transformations_pipeline.cpp
* Disabled transformation introducing memory leak.
* Disabled transformation introducing memory leak.
- *116912*
> [GNA] Fix memory leak in GNA plugin.

- src/core/include/openvino/op/group_normalization.hpp
- src/core/src/op/group_normalization.cpp
- Port https://github.com/openvinotoolkit/openvino/pull/19244 to release branch
> [2023.1] Fix uninit members in default `GroupNormalization()` (#19244)

- CONTRIBUTING.md
- CONTRIBUTING_DOCS.md
- CONTRIBUTING_PR.md
Changes to the contribution guide, developed and approved by Devang
> [DOCS] contributing guidelines

- samples/cpp/classification_sample_async/README.md
- samples/python/classification_sample_async/README.md
> classification_sample_async: state that the samples support NCHW model layout only

- src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- This PR is a backport of https://github.com/openvinotoolkit/openvino/pull/19140 to 2023.0 Release branch
- *116423*
> [GPU] Do not select onednn format for asymmetric weight (#19140)

- src/frontends/pytorch/src/op/logical.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_or.py
- *Support non boolean inputs for __or__ and __and__ operations. This supports Spade model.*
- *118135*
> [PT FE] Support non boolean inputs for __or__ and __and__ operations

- src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
- *fix SDL issue (CID 1518457) for 2023.1 branch*
- *117997*
> fix SDL issue (CID 1518457) for 2023.1 branch

- src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
- *fix SDL issue (CID 1518457)*
- *117997*
> fix SDL issue (CID 1518457)

- src/frontends/tensorflow_common/src/op/ctc_loss.cpp
- tests/layer_tests/tensorflow_tests/test_tf_CTCLoss.py
**Details:** Fix support of CTCLoss and add tests to pre-commit
**Ticket:** 118098
> [TF FE] Fix support of CTCLoss and add tests to pre-commit

- src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
- *Fix SDL issue (CID 1518459)*
- *117994*
> Fix SDL issue (CID 1518459)

- .ci/azure/linux.yml
- cmake/dependencies.cmake
- updated lib GNA version to 2116
- *118232*
> [GNA] Switch GNA library to version 03.05.00.2116

- src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend.py
- src/bindings/python/src/openvino/torch/__init__.py
Changes for improving the import statement experience for torch.compile
> Added openvino/torch folder for simplyfing the import

- src/frontends/pytorch/src/utils_quantize.hpp
- *We need to insert `FakeQuantize` node after regular operations as well as after quantized operations.*
- *118224*
> [PT FE] Fix issue when FakeQuantize is not inserted after regular operations

- src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
- src/plugins/intel_gpu/src/graph/reshape.cpp
- src/plugins/intel_gpu/tests/unit/passes/handle_reshape.cpp
- Prohibit incorrect optimization for reshapes chain which leads to exception on shape infer in some cases
- *117969*
> [GPU] Fix reshape optimization

- src/plugins/intel_gna/src/gna_transformations_pipeline.cpp
- src/plugins/intel_gna/src/transformations/insert_copy_layer.cpp
- src/plugins/intel_gna/src/transformations/insert_copy_layer.hpp
- Added cleanup transformation for inert copy layer transformations
- 116912
> [GNA] Fix memory leak in insert_copy_layer.cpp

- src/plugins/intel_cpu/src/nodes/common/dnnl_executor.h
- src/plugins/intel_cpu/src/nodes/conv.cpp
- src/plugins/intel_cpu/src/nodes/conv.h
- src/plugins/intel_cpu/tests/functional/subgraph_tests/src/conv_sum_broadcast.cpp
Backport to the release branch. Original PR to master: https://github.com/openvinotoolkit/openvino/pull/19279
- 117937
> [CPU] Fix convolution plus sum layout alignment

- src/common/snippets/include/snippets/lowered/expression_port.hpp
- src/common/snippets/src/lowered/expression_factory.cpp
- src/common/snippets/src/lowered/expression_port.cpp
- *[PR](https://github.com/openvinotoolkit/openvino/pull/19316) to master*
- *117366*
> [Snippets] Fixed memory leak in LinearIR

- docs/MO_DG/prepare_model/convert_model/supported_model_formats.md
Adding tabbed content with code samples for each supported model format.
Porting:
https://github.com/openvinotoolkit/openvino/pull/18495
> [DOCS] Updating Supported Model Formats article for 23.1

- docs/MO_DG/prepare_model/convert_model/supported_model_formats.md
Adding tabbed content with code samples for each supported model format. 
Porting:
https://github.com/openvinotoolkit/openvino/pull/18495
> [DOCS] Updating Supported Model Formats article for 23.0

- .github/CODEOWNERS
- .github/workflows/linux.yml
- tests/model_hub_tests/CMakeLists.txt
- tests/model_hub_tests/models_hub_common/constants.py
- tests/model_hub_tests/models_hub_common/test_convert_model.py
- tests/model_hub_tests/models_hub_common/utils.py
- tests/model_hub_tests/tf_hub_tests/conftest.py
- tests/model_hub_tests/tf_hub_tests/precommit_models
- tests/model_hub_tests/tf_hub_tests/requirements.txt
- tests/model_hub_tests/tf_hub_tests/test_tf_hub_convert_model.py
**Details:** Introduce TF Hub Models Validation in GitHub Actions. This infrastructure can be extended to validate models from other hubs and frontends.
**Ticket:** 117711
> [TF Hub][GitHub Actions][TF FE] Introduce TF Hub Models Validation in GitHub Actions

- tools/mo/openvino/tools/mo/moc_frontend/pytorch_frontend_utils.py
- tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py
- *PR #19157 removed import nncf and that code will not work as expected. Fix to use version directly from `sys.modules`*
- *118525*
> [MO] Fix issue in nncf version verification

- src/plugins/intel_gpu/src/graph/impls/cpu/concat.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/scatter_update_ref.cl
- src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/scatter_update_gpu_test.cpp
- *[scatter_update] Use input index for input buffer instead of output index*
- *[concat cpu impl] Sync input layout and mem_ptr when input host tensor creation*
- *Add unit tests for scatter_update and concat cpu impl*
- *100495*
> [GPU] Fix accuracy issue

- src/plugins/intel_gpu/src/graph/graph_optimizer/concat_input_order.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp
- *7-dimension only supports plain format*
- *Skip concat_input_order opt in case dependancy is dynamic*
- *Add plain 7d 8d case for jitter pitch size*
- *116385*
> [GPU] 7-dimension only supports plain format

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/memory_test.cpp
- *Memory reuse false for dynamic and null impl case*
- *116385*
> [GPU] Memory reuse false for dynamic and null impl case

- src/tests/functional/plugin/conformance/test_runner/README.md
- *Update scopes information*
- *Update create report information*
- *ticket-id*
> [CONFORMANCE] Update runner readme

- src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir.cpp
- *item1*
- *...*
- *ticket-id*
> [conformance] Add shape mode and graph conv logic to test name

- src/frontends/pytorch/src/utils.cpp
- tests/layer_tests/pytorch_tests/test_add.py
- *Cherry-pick #19399*
- *117895*
> [PT FE] Align bool types and same bit int types

- docs/OV_Runtime_UG/supported_plugins/GNA.md
- samples/cpp/speech_sample/README.md
- samples/python/speech_sample/README.md
adding deprecation notices to the speech sample articles
adding info to GNA plugin deprecation notice
> [DOCS] speech sample deprecation

- src/plugins/intel_cpu/tests/functional/subgraph_tests/src/convert_range.cpp
- *follow up https://github.com/openvinotoolkit/openvino/pull/19226*
- *...*
- *117139*
> [fix] Remove makeDynamicParams

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/convolution.cpp
- Add check condition of input dynamic shape in conv fusing
- 101235
> [GPU] add check condition of input dynamic shape in conv fusing

- src/plugins/intel_gpu/src/graph/graph_optimizer/clamp_fp16_output.cpp
- src/plugins/intel_gpu/tests/unit/passes/clamp_fp16_output_test.cpp
+ Added condition when clamp activation is added to fused-ops for fp16 overflow
- Fix clamp_fp16_output
- CVS-118784
> [GPU] Resolve accuracy issue from clamp fused prims

- src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_smoke_test_reduce_deconvolution_concat.cpp
- Fix reduce perferred format selection
- reorder_input_and_weights_deconvolution layout for partial shape
- 101255
> [GPU] fix reduce perferred format selection and layout for partial shape

- src/plugins/intel_gpu/src/graph/impls/cpu/activation.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_smoke_test_shape_of_activation.cpp
- add sqrt activation support in cpu_impl
- 117829
> [GPU] add sqrt activation support in cpu_impl

- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_smoke_test_reduce_deconvolution_concat.cpp
- Follow up build error by https://github.com/openvinotoolkit/openvino/pull/19226
- 117139
- 119081
> [GPU] fix build error by removing makeDynamicParam

- .github/workflows/linux_debian.yml
This PR introduces the Linux Debian pipeline in the GitHub Actions environment. It is mirroring the [Azure Linux Debian pipeline](https://github.com/openvinotoolkit/openvino/blob/master/.ci/azure/linux_debian.yml).
- 117535
> [CI] [GHA] Introduce GHA Linux Debian Pipeline

- src/plugins/intel_cpu/tests/functional/behavior/ov_plugin/properties.cpp
- 119269
Release PR: https://github.com/openvinotoolkit/openvino/pull/19484
> [CPU][ARM] Fix inference precision for behaviour tests

- src/frontends/paddle/include/openvino/frontend/paddle/decoder.hpp
- src/frontends/paddle/src/CMakeLists.txt
- src/frontends/paddle/src/decoder.cpp
- src/frontends/paddle/src/op/generate_proposals_v2.cpp
- src/frontends/paddle/src/op/group_norm.cpp
- *Fix warnings and remove suppression for Paddle Frontend*
- *95176*
> Fix warnings for Paddle Frontend

- docs/OV_Runtime_UG/supported_plugins/Device_Plugins.md
- docs/OV_Runtime_UG/supported_plugins/NPU.md
- docs/install_guides/configurations-for-intel-npu.md
- docs/install_guides/configurations-header.md
- docs/resources/Supported_Devices.md
port: https://github.com/openvinotoolkit/openvino/pull/19340
> [DOCS] including NPU documents port 23.1

- src/plugins/hetero/src/sync_infer_request.cpp
- *Adds plugin so handle into the tensor*
- *118840*
> [HETERO] Adds plugin so handle into the tensor

- docs/optimization_guide/nncf/ptq/code/ptq_onnx.py
- docs/optimization_guide/nncf/ptq/code/ptq_openvino.py
- docs/optimization_guide/nncf/ptq/code/ptq_tensorflow.py
- docs/optimization_guide/nncf/ptq/code/ptq_torch.py
Improving code snippets for `Quantize a Model` section in the [article](https://docs.openvino.ai/nightly/basic_quantization_flow.html#quantize-a-model)
This PR addresses the following JIRA ticket: 111579
Porting: https://github.com/openvinotoolkit/openvino/pull/19479
> [DOCS] Improving code snippets for quantization for 23.1

- src/bindings/python/src/compatibility/openvino/CMakeLists.txt
- Backport of https://github.com/openvinotoolkit/openvino/pull/19473
- 119079
- 119312
> Skip CMake Cython version check

- docs/optimization_guide/nncf/ptq/code/ptq_onnx.py
- docs/optimization_guide/nncf/ptq/code/ptq_openvino.py
- docs/optimization_guide/nncf/ptq/code/ptq_tensorflow.py
- docs/optimization_guide/nncf/ptq/code/ptq_torch.py
Improving code snippets for `Quantize a Model` section in the [article](https://docs.openvino.ai/nightly/basic_quantization_flow.html#quantize-a-model)
This PR addresses the following JIRA ticket: 111579
Porting: https://github.com/openvinotoolkit/openvino/pull/19479
> [DOCS] Improving code snippets for quantization for 23.0

- tools/pot/openvino/tools/pot/api/samples/classification/README.md
- tools/pot/openvino/tools/pot/api/samples/classification/classification_sample.py
> [POT] Fix bug in classification sample

- src/tests/test_utils/common_test_utils/src/common_utils.cpp
- src/tests/test_utils/common_test_utils/src/test_common.cpp
- tests/memory_tests/src/memory_tests_helper/memory_counter.cpp
- tests/stress_tests/common/utils.cpp
> Fix `stoi` out_of_range issue

- src/plugins/intel_cpu/src/nodes/def_conv.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- src/plugins/intel_cpu/tests/functional/single_layer_tests/deformable_convolution.cpp
> [CPU] DefConv minor fixes

- README.md
- Old link is not rendered well
> Update PePy OpenVINO badge

- conanfile.txt
- Fixed https://dev.azure.com/openvinoci/dldt/_build/results?buildId=632161&view=logs&j=503d1592-119c-586f-46c7-e27f62244013&t=ab5166b1-d765-5711-214a-3525b4af7d3f&l=321
> Aligned protobuf version in conanfile.txt with onnx recipe

- src/common/snippets/include/snippets/lowered/pass/pass.hpp
- src/common/snippets/include/snippets/op/subgraph.hpp
- src/common/snippets/include/snippets/pass_manager.hpp
- src/common/snippets/src/lowered/pass/pass.cpp
- src/common/snippets/src/op/subgraph.cpp
- src/common/snippets/src/pass_manager.cpp
- src/common/snippets/tests/include/lowering_utils.hpp
- src/common/snippets/tests/src/lowering_utils.cpp
- src/core/include/openvino/pass/manager.hpp
- src/plugins/intel_cpu/src/nodes/subgraph.cpp
- src/plugins/intel_cpu/tests/unit/snippets_transformations/mul_add_to_fma.cpp
Customizable pass manager that allows to insert a new transformation before/after a particular pass in the pipeline. 
See a more detailed description in the ticket.
- *116645*
- Until the Prerequisites are merged, you can review the changes using [PR#11](https://github.com/IvanNovoselov/openvino/pull/11) in my fork repo
> Snippets pass manager

- .ci/azure/linux_conditional_compilation.yml
- .ci/azure/linux_cuda.yml
- .ci/azure/windows_conditional_compilation.yml
- Ported CI improvements https://github.com/openvinotoolkit/openvino/pull/19526
- Otherwise, these places are often forgotten to be updated when release branch is created.
> Ported CI improvements from #19526 to master

- src/common/transformations/include/transformations/op_conversions/convert_reduce_to_reshape.hpp
- src/common/transformations/src/transformations/op_conversions/convert_reduce_to_reshape.cpp
- src/common/transformations/tests/op_conversions/convert_reduce_to_reshape.cpp
- *Update ConvertReduceToReshape transformation to support ReduceProd*
- *Add tests*
**Note: required for NVIDIA plugin https://github.com/openvinotoolkit/openvino_contrib/pull/705**
- *106579*
> Update ConvertReduceToReshape transformation to support ReduceProd

- src/inference/tests/unit/variable_state_test.cpp
- *item1*
- *...*
- *ticket-id*
> Enable variable state unit tests

- src/common/transformations/src/transformations/common_optimizations/split_squeeze_concat_fusion.cpp
- src/common/transformations/tests/common_optimizations/split_squeeze_concat_fusion_test.cpp
> SplitSqueezeConcatFusion - handle Squeeze nodes without second input

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/roi_align_ref.cl
- src/plugins/intel_gpu/src/plugin/ops/constant.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/roi_align_gpu_test.cpp
- Fix input feature map indexing with padding for `ROIAlign`
- Fix batch indexing to use value of 3rd input(`batch indices`)
- 116597
> [GPU] Fix input feature map indexing with pad and batch indices for ROIAlign

- cmake/developer_package/frontends/frontends.cmake
- cmake/developer_package/packaging/packaging.cmake
- samples/c/common/opencv_c_wrapper/CMakeLists.txt
- Added `export(TARTET ..)` for private dependencies of public targets.
- CVS-118903
> Fixed static build from build tree

- docs/Documentation/openvino_workflow.md
- docs/Documentation/torch_compile.md
- docs/_static/css/homepage_style.css
- docs/_static/images/torch_compile_backend_openvino.svg
- docs/_static/images/torch_compile_backend_openvino_ts.svg
- docs/home.rst
Port from https://github.com/openvinotoolkit/openvino/pull/19447
Jira: 116794
Added an article about torch.compile() backend to the OpenVINO documentation.
> [DOCS] Torch.compile() documentation for 23.1

- docs/Documentation/openvino_workflow.md
- docs/Documentation/torch_compile.md
- docs/_static/css/homepage_style.css
- docs/_static/images/torch_compile_backend_openvino.svg
- docs/_static/images/torch_compile_backend_openvino_ts.svg
- docs/home.rst
Port from https://github.com/openvinotoolkit/openvino/pull/19447
Jira: 116794
Added an article about torch.compile() backend to the OpenVINO documentation.
> [DOCS] Torch.compile() documentation for 23.0

- src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp
- *item1*
- *...*
- *CVS-119559*
> [apiConformance] Fix some test results are not in report

- cmake/developer_package/frontends/frontends.cmake
- cmake/developer_package/packaging/packaging.cmake
- samples/c/common/opencv_c_wrapper/CMakeLists.txt
- Ported https://github.com/openvinotoolkit/openvino/pull/19556
- [CVS-118903](https://jira.devtools.intel.com/browse/CVS-118903)
> Fixed static build from build tree for 2023.1

- docs/install_guides/installing-openvino-docker-linux.md
Port from https://github.com/openvinotoolkit/openvino/pull/19505
- Removed duplicated note
- Fixed the link for Bare Metal
> [DOCS] Fix for Install from Docker Image for 23.1

- src/tests/test_utils/functional_test_utils/layer_tests_summary/merge_xmls.py
- *item1*
- *...*
- *CVS-119559*
> [apiConformance] Fix double numbers in results after merge xml

- src/common/snippets/tests/src/lowering_utils.cpp
- src/common/snippets/tests/src/pass/movebroadcast.cpp
- src/common/snippets/tests/src/pass/precision_propagation.cpp
- src/common/snippets/tests/src/pass/softmax_reshape_elimination.cpp
- src/common/snippets/tests/src/precomp.hpp
- *item1*
- *...*
- *ticket-id*
> Remove legacy API from snippets tests

- src/frontends/common/src/manager.cpp
- *item1*
- *...*
- *ticket-id*
> Added tflite to 'predefined_frontends' list

- tests/model_hub_tests/models_hub_common/multiprocessing_utils.py
- tests/model_hub_tests/models_hub_common/test_convert_model.py
- tests/model_hub_tests/models_hub_common/utils.py
- tests/model_hub_tests/tf_hub_tests/precommit_models
- tests/model_hub_tests/tf_hub_tests/test_tf_hub_convert_model.py
**Details:** Make TF Hub validation more robust and add convenient xfail test marking
**Ticket:** 117711
> [TF Hub][TF FE] Make TF Hub validation more robust and add convenient xfail test marking

- src/tests/test_utils/functional_test_utils/layer_tests_summary/analyze_confomance_fails.py
- *item1*
- *...*
- *ticket-id*
> [analyzeConfFails] Fix arm device and exclude analyzing some files

- src/plugins/intel_gpu/include/intel_gpu/op/fully_connected.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/program_builder.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/plugin/ops/fully_connected.cpp
- src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
- src/plugins/intel_gpu/src/plugin/transformations/convert_matmul_to_fc.cpp
- src/plugins/intel_gpu/src/plugin/transformations/convert_matmul_to_fc.hpp
- src/plugins/intel_gpu/src/plugin/transformations/move_fc_reshape_to_weights.cpp
- src/plugins/intel_gpu/src/plugin/transformations/move_fc_reshape_to_weights.hpp
- src/plugins/intel_gpu/src/plugin/transformations/op/fully_connected.cpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/matmul_weights_decompression.cpp
- src/plugins/intel_gpu/tests/unit/CMakeLists.txt
- src/plugins/intel_gpu/tests/unit/transformations/convert_matmul_to_fc_test.cpp
- src/plugins/intel_gpu/tests/unit/transformations/move_fc_reshape_to_weights.cpp
- Added internal FullyConnected op and MatMul -> FC transformation 
- Added transformation which removed Reshape op in compressed weights pattern
- Enabled transpose fusion into matmul (by changing matmul transpose flags)
- Added test for compressed Matmul
-  Part of *118099*
> [GPU] Add FullyConnected internal op and some related transformations

- docs/notebooks/120-tensorflow-object-detection-to-openvino-with-output.rst
- docs/notebooks/230-yolov8-optimization-with-output.rst
Fixed Optimize Preprocessing in notebooks 120 and 230 for master
> [DOCS] Fixing Optimize Preprocessing in notebooks 120 and 230 for master

- docs/notebooks/120-tensorflow-object-detection-to-openvino-with-output.rst
- docs/notebooks/230-yolov8-optimization-with-output.rst
Port from https://github.com/openvinotoolkit/openvino/pull/19624
Fixed Optimize Preprocessing in notebooks 120 and 230 for master
> [DOCS] Fixing Optimize Preprocessing in notebooks 120 and 230 for 23.0

- samples/cpp/benchmark_app/utils.hpp
- samples/cpp/common/utils/include/samples/common.hpp
- samples/cpp/model_creation_sample/main.cpp
- samples/cpp/speech_sample/main.cpp
- *item1*
- *...*
- *ticket-id*
> Remove legacy API from samples

- src/plugins/intel_cpu/tools/commit_slider/commit_slider.py
- src/plugins/intel_cpu/tools/commit_slider/utils/cfg.json
- src/plugins/intel_cpu/tools/commit_slider/utils/common_mode.py
- src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py
- src/plugins/intel_cpu/tools/commit_slider/utils/modes.py
- *item1*
- *...*
- *ticket-id*
> [Commit slider] Skipping for commits

- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
- *Update pytorch conversion docs*
- Port from https://github.com/openvinotoolkit/openvino/pull/19396
> [DOCS][PT FE] Update pytorch conversion docs for master

- src/bindings/python/wheel/CMakeLists.txt
- Ported https://github.com/openvinotoolkit/openvino/pull/19594
> Unlock custom creation of PLATFORM_TAG

- src/bindings/python/CMakeLists.txt
- src/bindings/python/src/pyopenvino/core/compiled_model.cpp
- moved python object creation outside of scoped gil release
- CVS-116655
> [PyOV] resolve gil issue

- src/frontends/common/src/manager.cpp
- Ported https://github.com/openvinotoolkit/openvino/pull/19599
- Otherwise, all frontends are searched => worse time to read the first model
> Added tflite to 'predefined_frontends' list (#19599)

- src/tests/test_utils/unit_test_utils/CMakeLists.txt
- src/tests/test_utils/unit_test_utils/mock.cpp
- src/tests/test_utils/unit_test_utils/mocks/cpp_interfaces/impl/mock_async_infer_request_default.hpp
- src/tests/test_utils/unit_test_utils/mocks/cpp_interfaces/impl/mock_executable_thread_safe_default.hpp
- src/tests/test_utils/unit_test_utils/mocks/cpp_interfaces/impl/mock_inference_plugin_internal.hpp
- src/tests/test_utils/unit_test_utils/mocks/cpp_interfaces/interface/mock_iexecutable_network_internal.hpp
- src/tests/test_utils/unit_test_utils/mocks/cpp_interfaces/interface/mock_iinfer_request_internal.hpp
- src/tests/test_utils/unit_test_utils/mocks/cpp_interfaces/interface/mock_iinference_plugin.hpp
- src/tests/test_utils/unit_test_utils/mocks/cpp_interfaces/interface/mock_ivariable_state_internal.hpp
- src/tests/test_utils/unit_test_utils/mocks/cpp_interfaces/mock_task_executor.hpp
- src/tests/test_utils/unit_test_utils/mocks/mock_engine/dllmain.cpp
- src/tests/test_utils/unit_test_utils/mocks/mock_icnn_network.hpp
- src/tests/test_utils/unit_test_utils/mocks/mock_iexecutable_network.hpp
- src/tests/test_utils/unit_test_utils/mocks/mock_iinfer_request.hpp
- src/tests/test_utils/unit_test_utils/mocks/mock_not_empty_icnn_network.hpp
- src/tests/test_utils/unit_test_utils/mocks/openvino/runtime/mock_isync_infer_request.hpp
- *item1*
- *...*
- *ticket-id*
> Enabled clang format for unit test utils

- .github/workflows/linux.yml
- tests/model_hub_tests/tf_hub_tests/nightly_models_tmp
- tests/model_hub_tests/tf_hub_tests/test_tf_hub_convert_model.py
**Details:** Establish regular validation for all TF Hub models in GitHub Actions
**Ticket:** 117711
> [TF Hub][TF FE][GA] Establish regular validation for all TF Hub models

- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_tile.py
- *Support aten::tile op*
- *119886*
> [PT FE] Support aten::tile op

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/tests/unit/passes/reorder_inputs_test.cpp
- *No need to add reorder after strided_slice*
- *116180*
> [GPU] No need to add reorder after strided_slice

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bs_f_bsv16_af8_vload.cl
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- This patch fixes an accuracy issue related to missed handling of input features in case of misaligned size
- https://github.com/openvinotoolkit/openvino/issues/19436
> [GPU] Add input feature leftovers processing for fully_connected_gpu_bs_f_bsv16_af8_vload kernel

- docs/install_guides/installing-openvino-apt.md
- docs/install_guides/installing-openvino-yum.md
- *item1*
- *...*
- *ticket-id*
> Update versions in apt, yum installation docs

- docs/MO_DG/prepare_model/convert_model/supported_model_formats.md
- docs/ops/shape/ShapeOf_3.md
Small fixes for ShapeOf-3 and Supported Model Formats
> [DOCS] ShapeOf-3 & Supported Model Formats fix for master

- docs/MO_DG/prepare_model/convert_model/supported_model_formats.md
- docs/ops/shape/ShapeOf_3.md
Port from https://github.com/openvinotoolkit/openvino/pull/19694
Small fixes for ShapeOf-3 and Supported Model Formats
> [DOCS] ShapeOf-3 & Supported Model Formats fix for 23.1

- docs/MO_DG/prepare_model/convert_model/supported_model_formats.md
- docs/ops/shape/ShapeOf_3.md
Port from https://github.com/openvinotoolkit/openvino/pull/19694
Small fixes for ShapeOf-3 and Supported Model Formats
> [DOCS] ShapeOf-3 & Supported Model Formats fix for 23.0

- docs/_static/images/torch_compile_backend_openvino.svg
- docs/_static/images/torch_compile_backend_openvino_ts.svg
Image fix for torch.compile documentation as mentioned in https://github.com/openvinotoolkit/openvino/pull/19540#pullrequestreview-1617354770
> [DOCS] Torch.compile() image fix for master

- .ci/azure/android_arm64.yml
- vcpkg.json
**Details:**
- After https://github.com/microsoft/vcpkg/pull/33586 we can use TBB with hwloc as a default feature.
> Updated vcpkg.json config with newer TBB version with default features

- src/frontends/common/src/utils.cpp
- src/frontends/paddle/src/input_model.cpp
- Ported https://github.com/openvinotoolkit/openvino/pull/19682
> Fixed compilation with C++17 on Windows

- src/plugins/intel_gpu/src/graph/strided_slice.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/strided_slice.cpp
- *Update strided_slice for partially dynamic shape case*
- *Update func test to test mixed input with constant and non-constant*
- *118757*
> [GPU] Update strided_slice for partially dynamic shape case

- src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir_tests.cpp
- *item1*
- *...*
- *ticket-id*
> [CONFORMANCE] Enable QM + IE tests in Opset Conformance

- tests/model_hub_tests/tf_hub_tests/precommit_models
- tests/model_hub_tests/tf_hub_tests/test_tf_hub_convert_model.py
**Details:** It helps to get 4 new models passed and other 2 models failed with accuracy issue.
**Ticket:** 119907
> [TF Hub] Fix compute output size issue in test

- docs/install_guides/installing-openvino-pip.md
Fix for link in PyPI install guide
> [DOCS] Link fix for PyPI install guide for master

- cmake/test_model_zoo.cmake
- src/core/tests/pass/serialization/read_ir.hpp
- src/frontends/paddle/tests/CMakeLists.txt
- src/frontends/tensorflow/tests/CMakeLists.txt
- src/frontends/tensorflow_lite/tests/CMakeLists.txt
> Gracefully fail if test models weren't generated

- docs/_static/images/model_conversion_diagram.svg
Update of model_conversion_diagram.svg according to changes in https://github.com/openvinotoolkit/openvino/pull/19555
> [DOCS] Update of model_conversion_diagram.svg for master

- docs/_static/css/custom.css
Changes primarily for the articles:
- Performance Information F.A.Q.
- Install OpenVINO
> [DOCS] Modify dropdowns css

- .github/workflows/linux.yml
- .github/workflows/linux_android_arm64.yml
- .github/workflows/linux_arm64.yml
- This PR addresses comments from #19246 & #19230.
- *117540*
> [CI] [GHA] Remove unnecessary steps and `cmake` options, use proper # of CPU cores for ARM64 pipeline

- .github/workflows/linux.yml
**Details:** Separate Workflow for TF Hub Tests Validation.
> [TF Hub][GA] Separate Workflow for TF Hub Tests Validation

- src/plugins/intel_cpu/tests/functional/subgraph_tests/src/custom_op_scalar.cpp
- *Fix for post commit* https://dev.azure.com/openvinoci/dldt/_build/results?buildId=638335&view=logs&j=e0e676f4-9664-538a-6d6b-aa53516aa09f&t=839cb6ab-4ea8-51d4-e102-9a106ad673bf
> Post commit fix for #19521.

- src/plugins/intel_gpu/thirdparty/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
> Removed CMAKE_INSTALL_LIBDIR from oneDNN GPU configuration

- docs/Documentation/model_introduction.md
- docs/MO_DG/Deep_Learning_Model_Optimizer_DevGuide.md
- docs/MO_DG/prepare_model/FP16_Compression.md
- docs/MO_DG/prepare_model/convert_model/supported_model_formats.md
- docs/OV_Converter_UG/Deep_Learning_Model_Optimizer_DevGuide.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_ONNX.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_Paddle.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_TensorFlow_Lite.md
- docs/OV_Converter_UG/prepare_model/convert_model/Converting_Model.md
- docs/OV_Converter_UG/prepare_model/convert_model/MO_OVC_transition.md
- docs/OV_Converter_UG/prepare_model/convert_model/supported_model_formats.md
- docs/get_started/get_started_demos.md
- docs/glossary.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/pypi-openvino-dev.md
- docs/model_zoo.md
port: https://github.com/openvinotoolkit/openvino/pull/19555
> [DOCS] OVC/convert_model Documentation (#19555)

- .ci/azure/linux.yml
- .ci/azure/linux_debian.yml
- .ci/azure/mac.yml
- .ci/azure/windows.yml
- .github/workflows/linux.yml
- .github/workflows/linux_debian.yml
- .github/workflows/windows.yml
- src/plugins/hetero/CMakeLists.txt
- src/plugins/hetero/src/compiled_model.cpp
- src/plugins/hetero/src/compiled_model.hpp
- src/plugins/hetero/src/graph_debug_dump.cpp
- src/plugins/hetero/src/plugin.cpp
- src/plugins/hetero/src/subgraph_collector.cpp
- src/plugins/hetero/src/subgraph_collector.hpp
- src/plugins/hetero/src/version.cpp
- src/plugins/hetero/tests/unit/CMakeLists.txt
- src/plugins/hetero/tests/unit/subgraph_collector.cpp
- *Refactor subgraph collection in HETERO plugin*
- *Add ov_hetero_unit_tests*
- *ticket-id*
> [HETERO] Hetero refactor subgraph collector. Adds unit tests.

- src/plugins/intel_gpu/src/graph/impls/ocl/border.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/strided_slice.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/border/border_kernel_base.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/border_gpu_test.cpp
- *Using fake input buffer for zero input*
- *Fixed dump graph failure in strided_slice*
- *100132*
> [GPU] Added zero input handling for Pad

- docs/IE_PLUGIN_DG/layout.xml
- docs/IE_PLUGIN_DG/plugin_transformation_pipeline/low_precision_transformations/lpt.md
- docs/IE_PLUGIN_DG/plugin_transformation_pipeline/low_precision_transformations/pipeline/step3_main.md
- docs/IE_PLUGIN_DG/plugin_transformation_pipeline/low_precision_transformations/transformations/step3_main/shape/batch_to_space.md
- docs/IE_PLUGIN_DG/plugin_transformation_pipeline/low_precision_transformations/transformations/step3_main/shape/space_to_batch.md
- src/common/low_precision_transformations/include/low_precision/batch_to_space.hpp
- src/common/low_precision_transformations/include/low_precision/common/fake_quantize_dequantization.hpp
- src/common/low_precision_transformations/include/low_precision/common/ie_lpt_exception.hpp
- src/common/low_precision_transformations/include/low_precision/space_to_batch.hpp
- src/common/low_precision_transformations/src/batch_to_space.cpp
- src/common/low_precision_transformations/src/fake_quantize_dequantization.cpp
- src/common/low_precision_transformations/src/low_precision.cpp
- src/common/low_precision_transformations/src/markup_precisions.cpp
- src/common/low_precision_transformations/src/space_to_batch.cpp
- src/common/low_precision_transformations/tests/batch_to_space_transformation.cpp
- src/common/low_precision_transformations/tests/layer_transformation.hpp
- src/common/low_precision_transformations/tests/simple_low_precision_transformer.hpp
- src/common/low_precision_transformations/tests/space_to_batch_transformation.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/batch_to_space_transformation.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/space_to_batch_transformation.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/batch_to_space_transformation.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/space_to_batch_transformation.cpp
- src/tests/functional/plugin/shared/include/low_precision_transformations/batch_to_space_transformation.hpp
- src/tests/functional/plugin/shared/include/low_precision_transformations/space_to_batch_transformation.hpp
- src/tests/functional/plugin/shared/src/low_precision_transformations/batch_to_space_transformation.cpp
- src/tests/functional/plugin/shared/src/low_precision_transformations/space_to_batch_transformation.cpp
- src/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/batch_to_space_function.hpp
- src/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/space_to_batch_function.hpp
- src/tests/ngraph_helpers/lpt_ngraph_functions/src/batch_to_space_function.cpp
- src/tests/ngraph_helpers/lpt_ngraph_functions/src/space_to_batch_function.cpp
- *New Low Precision Transformations implementation: SpaceToBatch & BatchToSpace*
- *CVS-119820*
> [LPT] SpaceToBatch & BatchToSpace implementation

- src/frontends/pytorch/src/op/nms.cpp
- tests/layer_tests/pytorch_tests/test_nms.py
- *Torchvision NMS can accept negative scores*
- *120449*
> [PT FE] Torchvision NMS can accept negative scores

- docs/optimization_guide/model_optimization_guide.md
- docs/optimization_guide/nncf/code/weight_compression_openvino.py
- docs/optimization_guide/nncf/weight_compression.md
- Added Weight Compression API description
> Introduce weight compression doc

- src/bindings/python/constraints.txt
- src/bindings/python/wheel/requirements-dev.txt
- Backport of https://github.com/openvinotoolkit/openvino/pull/19802
- N/A
> [Backport][PyOV] Remove upper bound on `setuptools`

- docs/Documentation/model_introduction.md
- docs/Extensibility_UG/Intro.md
- docs/MO_DG/prepare_model/MO_Python_API.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_ONNX.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Cascade_RCNN_res101.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_F3Net.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_QuartzNet.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RCAN.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_YOLACT.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
- docs/OV_Converter_UG/prepare_model/convert_model/supported_model_formats.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] Conversion docs changes 

- docs/Documentation/model_introduction.md
- docs/Extensibility_UG/Intro.md
- docs/MO_DG/prepare_model/MO_Python_API.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_ONNX.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Cascade_RCNN_res101.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_F3Net.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_QuartzNet.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RCAN.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md
- docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_YOLACT.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
- docs/OV_Converter_UG/prepare_model/convert_model/supported_model_formats.md
port: https://github.com/openvinotoolkit/openvino/pull/19837
> [DOCS] release adjustments pass 3 - conversion

- docs/tutorials.md
Notebooks Tutorials Page Update
> [DOCS] Notebooks Tutorials Page Update for master

- docs/tutorials.md
Port from https://github.com/openvinotoolkit/openvino/pull/19852
Notebooks Tutorials Page Update
> [DOCS] Notebooks Tutorials Page Update for 23.1

- src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/convert_fq_rnn_to_quantized_rnn.cpp
- by ensuring convert is placed after u8/i8 output
- 120347
> [CPU] Correct ConvertFqRnnToQuantizeRnn transformation

- docs/install_guides/troubleshooting.md
port: https://github.com/openvinotoolkit/openvino/pull/19855
> [DOCS] troubleshooting article port

- .ci/azure/linux_arm64.yml
- *item1*
- *...*
- *ticket-id*
> Enable tests for Conan ARM build

- src/bindings/python/src/openvino/properties/__init__.py
- src/bindings/python/src/openvino/properties/device/__init__.py
- src/bindings/python/src/openvino/properties/hint/__init__.py
- src/bindings/python/src/openvino/properties/intel_auto/__init__.py
- src/bindings/python/src/openvino/properties/intel_cpu/__init__.py
- src/bindings/python/src/openvino/properties/intel_gpu/__init__.py
- src/bindings/python/src/openvino/properties/intel_gpu/hint/__init__.py
- src/bindings/python/src/openvino/properties/log/__init__.py
- src/bindings/python/src/openvino/properties/streams/__init__.py
- src/bindings/python/tests/test_runtime/test_properties.py
- added `properties` folder and  subfolders (`hint`, `intel_cpu`, `intel_gpu`, `intel_auto`, `log`, `streams`, `device`) to the `openvino` folder.
- update `test_properties.py` with new imports
- CVS-119371
> [PyOV] Import properties from openvino

- docs/snippets/cpu/Bfloat16Inference.py
- docs/snippets/cpu/ov_execution_mode.py
- docs/snippets/cpu/ov_sparse_weights_decompression.py
- docs/snippets/gpu/compile_model.py
- docs/snippets/ov_auto.py
- docs/snippets/ov_auto_batching.py
- docs/snippets/ov_caching.py
- docs/snippets/ov_denormals.py
- docs/snippets/ov_hetero.py
- docs/snippets/ov_multi.py
- docs/snippets/ov_properties_api.py
- docs/snippets/ov_properties_migration.py
- Continue of https://github.com/openvinotoolkit/openvino/pull/19815
- Update snippets with new imports
- *ticket-id*
> [Docs] Update python snippets with new properties imports

- docs/_static/images/DEVELOPMENT_FLOW_V3_crunch.svg
- docs/_static/images/WHAT_TO_USE.svg
- docs/optimization_guide/model_optimization_guide.md
- docs/optimization_guide/nncf/code/weight_compression_openvino.py
- docs/optimization_guide/nncf/weight_compression.md
Ports from https://github.com/openvinotoolkit/openvino/pull/19680 & https://github.com/openvinotoolkit/openvino/pull/19849
> [DOCS] Introduce weight compression & Optimization images change for master

- docs/notebooks/234-encodec-audio-compression-with-output.rst
- docs/notebooks/236-stable-diffusion-v2-infinite-zoom-with-output.rst
- docs/notebooks/236-stable-diffusion-v2-text-to-image-with-output.rst
- docs/notebooks/237-segment-anything-with-output.rst
- docs/notebooks/240-dolly-2-instruction-following-with-output.rst
- docs/notebooks/241-riffusion-text-to-music-with-output.rst
- docs/notebooks/242-freevc-voice-conversion-with-output.rst
- docs/notebooks/244-named-entity-recognition-with-output.rst
- docs/notebooks/248-stable-diffusion-xl-with-output.rst
- docs/notebooks/251-tiny-sd-image-generation-with-output.rst
Port from https://github.com/openvinotoolkit/openvino/pull/19875
Putting in comments error returning iframes.
> [DOCS] Notebooks iframe update for 23.1

- docs/notebooks/234-encodec-audio-compression-with-output.rst
- docs/notebooks/236-stable-diffusion-v2-infinite-zoom-with-output.rst
- docs/notebooks/236-stable-diffusion-v2-text-to-image-with-output.rst
- docs/notebooks/237-segment-anything-with-output.rst
- docs/notebooks/240-dolly-2-instruction-following-with-output.rst
- docs/notebooks/241-riffusion-text-to-music-with-output.rst
- docs/notebooks/242-freevc-voice-conversion-with-output.rst
- docs/notebooks/244-named-entity-recognition-with-output.rst
- docs/notebooks/248-stable-diffusion-xl-with-output.rst
- docs/notebooks/251-tiny-sd-image-generation-with-output.rst
Putting in comments error returning iframes.
> [DOCS] Notebooks iframe update for master

- .github/ISSUE_TEMPLATE/good_first_issue.yml
- Add template for developers who want to create a Good First Issue
- Please add suggestions in the comments
- The template is currently loosely based on existing GFIs, such as https://github.com/openvinotoolkit/openvino/issues/17501
- N/A
> Add Good First Issue template

- src/plugins/intel_cpu/src/nodes/bin_conv.cpp
- src/plugins/intel_cpu/src/nodes/interpolate.cpp
- src/plugins/intel_cpu/tests/functional/single_layer_tests/interpolate.cpp
- *Fix CPU interpolate bug and add related test case*
- *CVS-97985*
> fix CPU interpolate bug and add related test case

- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-from-archive-macos.md
- docs/install_guides/installing-openvino-from-archive-windows.md
> Updated release folder link from 2023.1.0 to 2023.1

- docs/Documentation/openvino_ecosystem.md
- docs/OV_Runtime_UG/deployment/local-distribution.md
- docs/get_started/get_started_demos.md
- docs/install_guides/--installing-model-dev-tools.md
- docs/install_guides/installing-openvino-apt.md
- docs/install_guides/installing-openvino-brew.md
- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-from-archive-macos.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/install_guides/installing-openvino-pip.md
- docs/install_guides/installing-openvino-vcpkg.md
- docs/install_guides/installing-openvino-yum.md
- docs/snippets/export_compiled_model.cpp
port: https://github.com/openvinotoolkit/openvino/pull/19896
> [DOCS] updated archives for 2023.1 port master (#19896)

- .ci/azure/linux_debian.yml
- .github/workflows/linux_debian.yml
- cmake/packaging/debian.cmake
- cmake/packaging/rpm.cmake
> [Azure] Fix linux_debian.yml

- docs/Documentation/model_introduction.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
- docs/documentation.md
- docs/home.rst
- docs/install_guides/installing-openvino-linux-header.md
- docs/install_guides/installing-openvino-macos-header.md
- docs/install_guides/installing-openvino-windows-header.md
port: https://github.com/openvinotoolkit/openvino/pull/19914
> [DOCS] minor post release tweaks port 23.1

- docs/Documentation/model_introduction.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_Paddle.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] OVC docs adjustments 

- src/bindings/python/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
> Check only build requirements for Python API

- tests/layer_tests/tensorflow_tests/test_tf_CTCLoss.py
**Details:** Fix sporadic failure in CTCLoss test
> [TF FE][Tests] Fix sporadic failure in CTCLoss test

- src/plugins/intel_gpu/include/intel_gpu/primitives/condition.hpp
- src/plugins/intel_gpu/src/graph/impls/common/condition.cpp
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/plugin/ops/condition.cpp
- src/plugins/intel_gpu/src/plugin/ops/constant.cpp
- src/plugins/intel_gpu/src/plugin/ops/split.cpp
- src/plugins/intel_gpu/src/plugin/program_builder.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/shapeof.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/split.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/condition.cpp
- *Check output shape after op.is_dynamic()*
- *Fix zero dimension allocation, set {1} dims to zero dimension shape*
- *Add debug log for condition operation*
- *116928*
> bug fix update

- src/plugins/intel_cpu/src/emitters/x64/jit_load_store_emitters.cpp
- *unblock RAW dependency for loop of tails process*
- *1/2/3/4 byte tail number is unblocked previously, this pr extend to all tail number*
- *CVS-119576*
> [CPU] Eliminate dependency for emitters tails process

- docs/Documentation/model_introduction.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_Paddle.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
> [DOCS] OVC docs adjustments port

- src/plugins/template/src/compiled_model.cpp
- src/plugins/template/src/plugin.cpp
- src/plugins/template/tests/functional/op_reference/loop.cpp
- src/plugins/template/tests/functional/op_reference/memory.cpp
- src/plugins/template/tests/functional/subgraph_reference/preprocess_legacy.cpp
- *item1*
- *...*
- *ticket-id*
> Fix warning in template plugin

- tests/lib/src/common_utils.h
- tests/stress_tests/.automation/memleaks_tests/nightly_configs/desktop_test_config.xml
- tests/stress_tests/.automation/memleaks_tests/precommit_configs/desktop_test_config.xml
- tests/stress_tests/.automation/memleaks_tests/weekly_configs/desktop_test_config.xml
- Cover https://github.com/openvinotoolkit/openvino/pull/19316
- 117366
> Add `bert-base-ner` in MemLeak tests

- src/common/transformations/src/transformations/transpose_sinking/ts_gather.cpp
- src/common/transformations/tests/transpose_sinking/ts_gather_test.cpp
- src/common/transformations/tests/transpose_sinking/ts_test_utils.cpp
- src/common/transformations/tests/transpose_sinking/ts_test_utils.hpp
- fix TSGatherForward transformation
- add unit test
- 120085
> fix TSGatherForward transformation

- src/plugins/intel_cpu/src/nodes/mha.cpp
- See https://github.com/Homebrew/homebrew-core/issues/142161#issuecomment-1722135493
> Fixed compilation on macOS 14 with new core development tools

- src/plugins/intel_gpu/src/graph/impls/ocl/gather.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
- src/plugins/intel_gpu/tests/unit/test_cases/canonicalization_gpu_test.cpp
- Fix custom canonicalize shapes for Gather to avoid unintentional shape extension for 1D fused dep's shape
- 116597, 118222
> [GPU] Fix canonicalization for fused dep's shape

- docs/dev/cmake_options_for_custom_compilation.md
- *Explain the cmake option for MLAS*
- *CVS-120772*
> [Doc]Update cmake option for MLAS

- docs/dev/build_windows.md
- docs/dev/static_libaries.md
- *item1*
- *...*
- *ticket-id*
> Updated Windows build docs

- .github/dependabot.yml
- *item1*
- *...*
- *ticket-id*
> Updated dependabot config for GHA updates

- src/plugins/intel_cpu/src/graph.cpp
- *use omp section instead of task to avoid compilation issue*
- *CVS-120664*
> use omp section instead of task

- src/plugins/intel_gpu/src/graph/graph_optimizer/post_optimize_weights.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/fully_connected.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
> [GPU] Update weights reorder output shape for fully_connected

- tools/benchmark_tool/setup.py
> benchmark: drop python3.7

- samples/python/model_creation_sample/model_creation_sample.py
- Removed usage of ngraph in the sample
- N/A
> Updated model_creation_sample.py

- src/plugins/intel_cpu/src/nodes/reorder.cpp
- src/plugins/intel_cpu/src/nodes/reorder.h
- Since there is no optimized reorder for fp16 precision
- 118088
> [CPU][ARM][FP16] Use Transpose executor for layout Reorder

- tests/model_hub_tests/models_hub_common/constants.py
- tests/model_hub_tests/models_hub_common/utils.py
- tests/model_hub_tests/torch_tests/hf_transformers_models
- tests/model_hub_tests/torch_tests/test_timm.py
- tests/model_hub_tests/torch_tests/test_transformers.py
- *Add tests for timm models*
- *120265*
> [PT FE] Add tests for timm models

- src/frontends/pytorch/src/op/scatter.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_scatter.py
- supported *aten::scatter_reduce*, "aten::scatter_reduce_"
- *extended transaltor of aten::scatter with support out argument*
- *[CVS-117331](https://jira.devtools.intel.com/browse/CVS-117331)*
> [PT FE]: support aten::scatter_reduce and extend aten::scatter

- docs/optimization_guide/nncf/weight_compression.md
Port from https://github.com/openvinotoolkit/openvino/pull/19967
> [DOCS] Added cross links into weights compression for master

- src/core/reference/include/openvino/reference/cum_sum.hpp
- src/core/src/op/cum_sum.cpp
- src/plugins/template/backend/ops/cum_sum.cpp
- Refactor to reduce binary size. New API used already
- [CVS-118542](https://jira.devtools.intel.com/browse/CVS-118542)
> [core]Reduce binary size of CumSum implementation

- tests/model_hub_tests/models_hub_common/constants.py
- tests/model_hub_tests/torch_tests/hf_transformers_models
- tests/model_hub_tests/torch_tests/requirements.txt
- tests/model_hub_tests/torch_tests/test_transformers.py
- *Improve testing for hf models*
- *None*
> [PT FE] Improve testing for hf models

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/gather_elements.cpp
- src/tests/functional/plugin/shared/include/single_op_tests/gather.hpp
- src/tests/functional/plugin/shared/include/single_op_tests/gather_elements.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/gather.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/gather_elements.hpp
- src/tests/functional/shared_test_classes/src/single_op/gather.cpp
- src/tests/functional/shared_test_classes/src/single_op/gather_elements.cpp
- Refactor GatherLayerTest, GatherElementsLayerTest 
> Refactor GatherLayerTest, GatherElementsLayerTest

- src/plugins/intel_cpu/src/nodes/bin_conv.cpp
- *use std::shared_ptr instead of pointer*
- *CVS-120867*
> [cpu] fix memory leak in binconv

- .github/workflows/mo.yml
- This PR fixes MO workflow syntax error.
> [CI] [GHA] Fix MO workflow syntax error

- tools/ovc/openvino/tools/ovc/cli_parser.py
- tools/ovc/unit_tests/ovc/utils/cli_parser_test.py
Description: 
Removed unused code from OVC cli_parser.
Removed distutils dependency
Ticket: -
Code:
Validation:
Documentation:
> Removed unused code from OVC cli_parser.

- docs/ops/generation/Multinomial_13.md
Addressing comments from https://github.com/openvinotoolkit/openvino/pull/19866 
- *...*
- *ticket-id*
> [DOCS] Multinomial specification page fixes

- src/core/src/op/tensor_iterator.cpp
- Fix CI build due to reported warning as error.
- N/A
> [CI] Fix Azure openvino-lin build issues

- docs/dev/build_linux.md
- Modify wrong info in build_linux.md
> [Doc] Fix invalid info in bulid_linux.md

- tools/pot/openvino/tools/pot/algorithms/quantization/optimization/algorithm.py
- tools/pot/setup.py
- tools/pot/tests/data/reference_models/resnet_example_RangeSupervision_pytorch.xml
- tools/pot/tests/data/reference_models/resnet_example_range_supervision_pytorch.xml
- tools/pot/tests/utils/command.py
- Updated python version to 3.8+
- 118798
> [POT] Change python version to 3.8+

- .github/workflows/webassembly.yml
- *item1*
- *...*
- *ticket-id*
> Added WebAssembly workflow

- docs/articles_en/about_openvino/release_notes.md
Update for the Release Notes article to link to the 23.1 release notes.
> [DOCS] Release Notes version update for master

- .github/workflows/code_style.yml
- *item1*
- *...*
- *ticket-id*
> Fixed NCC style check

- .github/workflows/linux.yml
- Switch cpu func tests to 8 core runner to reduce execution time from 33 to 17 mins 
- *ticket-id*
> [GHA] Switch cpu func tests to 8 core runner

- src/bindings/python/src/pyopenvino/graph/model.cpp
- src/bindings/python/tests/test_runtime/test_model.py
- follow up of the https://github.com/openvinotoolkit/openvino/pull/20014
- *ticket-id*
> [PyOV] Fix docs and add test for Model._get_raw_address

- .github/workflows/code_style.yml
- Ported https://github.com/openvinotoolkit/openvino/pull/20121
> Fixed NCC style check (#20121)

- docs/install_guides/installing-openvino-vcpkg.md
> VCPKG docs for dynamic OpenVINO build

- src/frontends/pytorch/src/op/pixel_shuffle.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_pixel_shuffle.py
- *Add support for `aten::pixel_shuffle`*
- *121679, 112840*
> [PT FE] Add support for aten::pixel_shuffle

- tests/model_hub_tests/torch_tests/requirements.txt
- *item1*
- *...*
- *ticket-id*
> Restrict version of pytorch-quantization

- docs/install_guides/installing-openvino-vcpkg.md
Porting:
https://github.com/openvinotoolkit/openvino/pull/20127
> [DOCS] VCPKG docs for dynamic OpenVINO build for 23.1

- .github/workflows/linux_conditional_compilation.yml
This PR transfers the Linux CC to the AKS runners and enables it in precommit.
- *121733*
> [CI] [GHA] Transfer Linux CC to AKS runners

- src/frontends/tensorflow/src/input_model.cpp
- src/frontends/tensorflow/src/op/enter.cpp
- src/frontends/tensorflow/src/op/exit.cpp
- src/frontends/tensorflow/src/op/loop_cond.cpp
- src/frontends/tensorflow/src/op/next_iteration.cpp
- src/frontends/tensorflow/src/op/partitioned_call.cpp
- src/frontends/tensorflow/src/op/while.cpp
- src/frontends/tensorflow/src/op_table.cpp
- src/frontends/tensorflow/src/tf_utils.cpp
- src/frontends/tensorflow/src/tf_utils.hpp
- src/frontends/tensorflow/src/translate_session.cpp
- src/frontends/tensorflow/src/translate_session.hpp
- src/frontends/tensorflow/tests/convert_model.cpp
- src/frontends/tensorflow/tests/convert_unsupported.cpp
- src/frontends/tensorflow_common/include/helper_ops/enter.hpp
- src/frontends/tensorflow_common/include/helper_ops/exit.hpp
- src/frontends/tensorflow_common/include/helper_ops/loop_cond.hpp
- src/frontends/tensorflow_common/include/helper_ops/next_iteration.hpp
- src/frontends/tensorflow_common/include/place.hpp
- src/frontends/tensorflow_common/include/tf_framework_node.hpp
- src/frontends/tensorflow_common/src/place.cpp
- tests/layer_tests/tensorflow_tests/test_tf_While.py
- tools/mo/openvino/tools/mo/convert_impl.py
- tools/mo/unit_tests/moc_tf_fe/conversion_basic_models_test.py
**Details:** TensorFlow models can have low control flow While operation that is represented as cyclic graph with low control flow operations: Switch, Merge, NextIteration, Enter, Exit, and LoopCond.
Example - TF with Control flow While:
**Ticket:** 108581
> [TF FE] Support TF1 While Control flow

- docs/Documentation/model_introduction.md
- docs/MO_DG/prepare_model/MO_Python_API.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
- docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- docs/MO_DG/prepare_model/convert_model/supported_model_formats.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_PyTorch.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_TensorFlow_Lite.md
- docs/OV_Converter_UG/prepare_model/convert_model/supported_model_formats.md
- *item1*
- *...*
- *ticket-id*
> [DOCS]  Fix conversion docs comments

- src/core/src/runtime/blob_allocator.hpp
- src/inference/dev_api/remote_utils.hpp
- src/inference/include/openvino/runtime/common.hpp
- src/inference/src/core.cpp
- src/inference/src/dev/converter_utils.cpp
- src/inference/src/dev/core_impl.cpp
- src/inference/src/dev/core_impl_ie.cpp
- src/inference/src/dev/make_tensor.cpp
- src/inference/src/dev/plugin.cpp
- src/inference/src/dev/plugin.hpp
- src/inference/src/infer_request.cpp
- *item1*
- *...*
- *ticket-id*
> Removed ie:: namespace

- src/plugins/template/src/config.cpp
- src/plugins/template/src/config.hpp
- src/plugins/template/src/plugin.cpp
- src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp
- *Add ov::log::level and ov::hint::model_priority to property*
- *Fix fails of OVCheckChangePropComplieModleGetPropTests_DEVICE_ID , now we are checking device/full name/id only for tested plugin*
- *CVS-103948*
> [template] Fix log_level, model_priority, full_device_name tests

- docs/_static/images/BASIC_FLOW_IE_C.svg
- *item1*
- *...*
- *ticket-id*
> [DOCS] Change diagram to include OVC

- src/plugins/intel_gpu/include/intel_gpu/runtime/engine.hpp
- src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- src/plugins/intel_gpu/src/runtime/engine.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.hpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
- Disabled enqueue zero size memcpy 
- Allow host memory usage larger than physical memory for Windows 
- Added more debug prints
> [GPU] Fix gpu memory handling

- cmake/developer_package/IEDevScriptsConfig.cmake
- To pick up python from virtualenv
- *ticket-id*
> Explicitly set Python3_FIND_STRATEGY

- src/bindings/python/src/openvino/utils.py
- Ported patch https://github.com/conda-forge/openvino-feedstock/blob/main/recipe/patches/002-win32-python-search.patch
**Note:** please, ensure it's secure from vulnerability standpoint.
> Added python search path for Conda

- docs/_static/images/BASIC_FLOW_IE_C.svg
- docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/convert_python_model_objects.md
- docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/supported_model_formats.md
- docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/supported_model_formats/Convert_Model_From_PyTorch.md
- docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/supported_model_formats/Convert_Model_From_TensorFlow.md
- docs/articles_en/openvino_workflow/model_introduction.md
- docs/articles_en/openvino_workflow/model_introduction/supported_model_formats.md
- docs/articles_en/openvino_workflow/model_introduction/supported_model_formats/Convert_Model_From_PyTorch.md
- docs/articles_en/openvino_workflow/model_introduction/supported_model_formats/Convert_Model_From_TensorFlow.md
- docs/articles_en/openvino_workflow/model_introduction/supported_model_formats/Convert_Model_From_TensorFlow_Lite.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] Port doc conversion change

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/constant_result.cpp
- src/plugins/intel_gna/tests/functional/shared_tests_instances/subgraph_tests/constant_result.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/constant_result.cpp
- src/tests/functional/plugin/shared/include/subgraph_tests/constant_result_legacy.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/constant_result.hpp
- src/tests/functional/shared_test_classes/src/subgraph/constant_result.cpp
- *item1*
- *...*
- *ticket-id*
> Moved ConstantResultTest to new API

- src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py
- *item1*
- *...*
- *ticket-id*
> [GHA][CONFORMANCE] Init gtest filter for parallel runner in case not used arg

- docs/articles_en/get started/installing-openvino-overview.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-linux-header.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-apt.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-from-archive-linux.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-yum.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-macos-header/installing-openvino-from-archive-macos.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-conan.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-conda.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-docker-linux.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-pip.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-vcpkg.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-windows-header/installing-openvino-from-archive-windows.md
> [DOCS] conan fix

- tests/constraints.txt
**Details:** New release of Torch 2.1.0 introduced some changes breaking tests.
> [PyTorch FE] Set upper-bound for PyTorch

- README.md
- docs/articles_en/about_openvino/compatibility_and_support/Supported_Devices.md
- docs/articles_en/openvino_workflow/openvino_intro/Device_Plugins.md
- docs/articles_en/openvino_workflow/openvino_intro/Device_Plugins/CPU.md
Propagation of https://github.com/openvinotoolkit/openvino/pull/19464
> [CPU][ARM][DOC] ARM documentation 

- docs/install_guides/installing-openvino-apt.md
- docs/install_guides/installing-openvino-conan.md
- docs/install_guides/installing-openvino-conda.md
- docs/install_guides/installing-openvino-docker-linux.md
- docs/install_guides/installing-openvino-from-archive-linux.md
- docs/install_guides/installing-openvino-from-archive-macos.md
- docs/install_guides/installing-openvino-from-archive-windows.md
- docs/install_guides/installing-openvino-linux-header.md
- docs/install_guides/installing-openvino-macos-header.md
- docs/install_guides/installing-openvino-overview.md
- docs/install_guides/installing-openvino-pip.md
- docs/install_guides/installing-openvino-vcpkg.md
- docs/install_guides/installing-openvino-windows-header.md
- docs/install_guides/installing-openvino-yum.md
Adding Conan Package Manager guide to docs.
Port from: https://github.com/openvinotoolkit/openvino/pull/20205 & https://github.com/openvinotoolkit/openvino/pull/20216
> [DOCS] Adding Conan Package Manager guide with fixes for 23.1

- src/tests/functional/plugin/conformance/subgraphs_dumper/src/utils/model.cpp
- *item1*
- *...*
- *ticket-id*
> Fix SubgraphsDumper compilation Win

- docs/OV_Runtime_UG/openvino_intro.md
Port from: https://github.com/openvinotoolkit/openvino/pull/20237
Jira: 122008
Removed video part of the article, linked video is no longer available.
Added information about PyTorch support along with links to articles about using PyTorch.
> [DOCS] Inference with OpenVINO Runtime update for 23.1

- docs/resources/prerelease_information.md
port: https://github.com/openvinotoolkit/openvino/pull/20274
> [DOCS] prerelease notes update port

- docs/OV_Converter_UG/prepare_model/convert_model/Convert_Model_From_TensorFlow_Lite.md
- *item1*
- *...*
- *ticket-id*
> [DOCS] Fix typo

- src/tests/functional/plugin/conformance/subgraphs_dumper/src/matchers/subgraph/manager.cpp
- src/tests/functional/plugin/conformance/subgraphs_dumper/src/utils/model.cpp
- *Fix warning threated as error*
- *[ticket-id](https://jira.devtools.intel.com/browse/CVS-122216)*
> [CONFORMANCE][SUBGRAPHS DUMPER] Fix warning threated as error

- .github/workflows/windows.yml
- Fix issue caused by changing of test package directory structure (https://github.com/openvinotoolkit/openvino/pull/19841)
- *n/a*
> [GHA][HF] changed parallel script path

- docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-conan.md
- docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-vcpkg.md
- *item1*
- *...*
- *ticket-id*
> Small improvements in conan, vcpkg docs

- .github/workflows/linux.yml
- tests/model_hub_tests/torch_tests/test_timm.py
- Switched python nightly tests (TensorFlow and Torch) to github runners
- Excluded timm tests from nightly scope as requested by @mvafin 
- *122170*
> [GHA][HF] Switch python nightly tests to github runners

- samples/cpp/CMakeLists.txt
- samples/cpp/benchmark_app/main.cpp
- samples/cpp/benchmark_app/remote_tensors_filling.hpp
- *item1*
- *...*
- *ticket-id*
> Ability to compile samples without API 1.0 headers

- src/bindings/c/include/openvino/c/ov_core.h
- src/bindings/c/src/ov_core.cpp
- Add ov_shutdown API
- 122352
> [C API] add ov_shutdown API

- samples/cpp/classification_sample_async/main.cpp
> fix a wrong comment

- src/plugins/auto/tests/functional/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
> Fixed wrong target usage in auto func tests

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/mat_mul.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/minimum_maximum.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/mvn.cpp
- src/tests/functional/plugin/shared/include/single_op_tests/mat_mul.hpp
- src/tests/functional/plugin/shared/include/single_op_tests/minimum_maximum.hpp
- src/tests/functional/plugin/shared/include/single_op_tests/mvn.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/mat_mul.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/minimum_maximum.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/mvn.hpp
- src/tests/functional/shared_test_classes/src/single_op/mat_mul.cpp
- src/tests/functional/shared_test_classes/src/single_op/minimum_maximum.cpp
- src/tests/functional/shared_test_classes/src/single_op/mvn.cpp
- Refactor MatMulTest, MaxMinLayerTest, Mvn1LayerTest
> Refactor MatMulTest, MaxMinLayerTest, Mvn1LayerTest

- src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
- [120485](https://jira.devtools.intel.com/browse/CVS-120485)
> [CPU] FullyConnected: sparse weights fix

- src/bindings/c/src/ov_remote_context.cpp
- CID 1522435:  Performance inefficiencies  (COPY_INSTEAD_OF_MOVE)
-
> [C API] Fix coverity scan issue about GET_INTEL_GPU_PROPERTY_FROM_ARGS_LIST

- src/frontends/pytorch/src/op/min_max.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_clamp.py
- tests/layer_tests/pytorch_tests/test_min_max.py
- *supported aten::amax, aten::amin, aten::clip, aten::clip_, aten::clamp_*
- *ticket-id*
> [PT FE]: support aten::amax, aten::amin, aten::clip, aten::clamp_

- src/common/transformations/include/transformations/transpose_sinking/ts_cumsum.hpp
- src/common/transformations/include/transformations/transpose_sinking/ts_tile.hpp
- src/common/transformations/src/transformations/transpose_sinking/ts_cumsum.cpp
- src/common/transformations/src/transformations/transpose_sinking/ts_general.cpp
- src/common/transformations/src/transformations/transpose_sinking/ts_tile.cpp
- src/common/transformations/src/transformations/transpose_sinking/ts_unary.cpp
- src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp
- src/common/transformations/tests/transpose_sinking/ts_common_test.cpp
- src/common/transformations/tests/transpose_sinking/ts_unary_test.cpp
- add support of Selu, Swish, Tile, CumSum, HardSigmoid, LogSoftmax, ConvertLike to TransposeSinking
- add unit tests
- 120407
> Support new operations in TS: Selu, Swish, HSwish, Tile, CumSum, HardSigmoid

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- tests/samples_tests/smoke_tests/test_speech_sample.py
- This PR applies comments from #20212 that were not implemented before the merge.
> [CI] [GHA] mac pipeline review leftovers; small cleanup of the Linux pipeline

- README.md
- docs/resources/telemetry_information.md
- src/bindings/python/requirements.txt
- tools/constraints.txt
- tools/mo/openvino/tools/mo/utils/telemetry_utils.py
- tools/ovc/openvino/tools/ovc/telemetry_utils.py
Reverts openvinotoolkit/openvino#20290
**Reason:** python tests became 4x slower
> Revert "Switch telemetry to opt-out approach."

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/prior_box.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/prior_box_clustered.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/power.cpp
- src/tests/functional/plugin/shared/include/single_op_tests/power.hpp
- src/tests/functional/plugin/shared/include/single_op_tests/prior_box.hpp
- src/tests/functional/plugin/shared/include/single_op_tests/prior_box_clustered.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/power.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/prior_box.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/prior_box_clustered.hpp
- src/tests/functional/shared_test_classes/src/single_op/power.cpp
- src/tests/functional/shared_test_classes/src/single_op/prior_box.cpp
- src/tests/functional/shared_test_classes/src/single_op/prior_box_clustered.cpp
- Refactor PowerLayerTest, PriorBoxClusteredLayerTest, PriorBoxLayerTest
> Refactor PowerLayerTest, PriorBoxClusteredLayerTest, PriorBoxLayerTest

- tests/layer_tests/tensorflow_lite_tests/test_tfl_ScatterND.py
- tests/layer_tests/tensorflow_lite_tests/test_tfl_StridedSlice.py
- Similar to https://github.com/openvinotoolkit/openvino/pull/12824
- Reproduced https://github.com/openvinotoolkit/openvino/actions/runs/6472549224/job/17573765425?pr=20363#step:18:60
> Fixed numpy deprecation error

- src/core/reference/include/openvino/reference/multinomial.hpp
- src/core/src/op/multinomial.cpp
- src/plugins/template/tests/functional/op_reference/multinomial.cpp
- Fix incorrect shape filling for 1D tensor smaller than requested sample size
- None
> [BUGFIX][Core][Template] Multinomial shape filling for 1D input

- tools/mo/openvino/tools/mo/front/common/partial_infer/utils.py
- Error example https://github.com/openvinotoolkit/openvino/actions/runs/6475940607/job/17584108843?pr=20363#step:12:750
> Removed np.int usage

- src/plugins/intel_gpu/include/intel_gpu/plugin/remote_tensor.hpp
- src/plugins/intel_gpu/src/plugin/remote_tensor.cpp
- src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- src/plugins/intel_gpu/tests/functional/behavior/infer_request.cpp
- This PR fixes `m_plugin_outputs` reallocation for user's host tensor used at the second iteration after default tensors
- 121192
> [GPU] Fix device tensors reallocation

- docs/OV_Runtime_UG/openvino_intro.md
Fix for Note in Inference with OpenVINO Runtime article.
> [DOCS] Fix for Note in Inference with OpenVINO Runtime for 23.1

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_primitive_fusing_test.cpp
- *Fixed problem that occurred after https://github.com/openvinotoolkit/openvino/pull/18949*
> [GPU] Fix high latency for LLMs on dGPU

- src/inference/dev_api/ie_ngraph_utils.hpp
- src/inference/include/ie/ie_precision.hpp
- src/plugins/intel_cpu/src/dnnl_postops_composer.cpp
- src/plugins/intel_cpu/src/dnnl_postops_composer.h
- src/plugins/intel_cpu/src/graph_optimizer.cpp
- src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
- src/plugins/intel_cpu/src/nodes/fullyconnected.h
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/plugins/intel_cpu/tests/functional/subgraph_tests/src/matmul_weights_decompression.cpp
- src/tests/ov_helpers/ov_models/include/ov_models/builders.hpp
- *NF4 precision support in decompression related transformations*
- *Group decompression support in transformations*
- *Updated CPU test class with new instances to cover the changes*
This PR can be merged only after #19900
> [CPU] Group & NF4 decompression support

- .github/workflows/windows.yml
- To remove WA in GHA for Windows
> Updated ade submodule

- docs/notebooks/247-code-language-id-with-output.rst
Fixing a broken link to the installation guide for notebooks.
> [DOCS] Fix link to notebooks installation guide

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/windows.yml
- tools/openvino_dev/CMakeLists.txt
- MxNet is not available for macOS arm64
> Don't add mxnet extras for openvino-dev on macOS arm64

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_redundant_reorder_at_runtime.cpp
- fix issue of runtime reorder optimized out during event sync in dGPU
- 100495
> [GPU] fix issue of optimized out reorder during event sync

- docs/install_guides/installing-openvino-overview.md
Port of changes in installing-openvino-overview.md file from https://github.com/openvinotoolkit/openvino/pull/20352
> [DOCS] Port of changes from Install Overview article for 23.1

- docs/Documentation/gen_ai.md
- docs/Documentation/learn_openvino.md
- docs/home.rst
port: https://github.com/openvinotoolkit/openvino/pull/20253
> [DOCS ] Added Gen AI landing page (#20253) port

- .github/workflows/linux.yml
- .github/workflows/windows.yml
- Added test execution cache 
- Added collection of logs from temp dir (case when tests are crashed) 
- *ticket-id*
> [GHA] Extend cpu functional logs 

- cmake/templates/OpenVINODeveloperPackageConfigRelocatable.cmake.in
- src/bindings/python/CMakeLists.txt
- thirdparty/dependencies.cmake
- Removed WA for pugixml issue. Now, it's solved in pugixml https://github.com/zeux/pugixml/pull/585
- Returned `OpenVINO_SOURCE_DIR` variable in python runtime cmake scripts for better code readability
- *ticket-id*
> Relocatable OpenVINO Dev package improvements

- docs/install_guides/pypi-openvino-dev.md
> [DOCS] Add openvino-dev deprecation note

- src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/shape_predictor.hpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/concat_input_order.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/activation.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/detection_output.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/non_max_suppression.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/proposal.cpp
- src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/prior_box.cpp
- src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- src/plugins/intel_gpu/src/runtime/shape_predictor.cpp
- src/plugins/intel_gpu/tests/unit/module_tests/shape_predictor_test.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/random_uniform_si_test.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/range_si_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/permute_gpu_test.cpp
- Removed unused type traits methods
- Replaced some traits with common ov::element_type_traits
> [GPU] Type traits cleanup

- src/frontends/tensorflow/src/op_table.cpp
- src/frontends/tensorflow_common/include/common_op_table.hpp
- src/frontends/tensorflow_common/src/op/xlogy.cpp
- tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py
- Support Xlogy operation for TF Hub Models
- Closes #20452
> [TF FE][TF Hub] Support Xlogy operation

- .github/workflows/linux_conditional_compilation.yml
- cmake/developer_package/add_target_helpers.cmake
- src/frontends/paddle/tests/CMakeLists.txt
- src/frontends/tensorflow/tests/CMakeLists.txt
- src/frontends/tensorflow_lite/tests/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
> Added ctest labels for FE tests only if FW is found

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/pooling.cpp
- src/tests/functional/plugin/shared/include/single_op_tests/pooling.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/pooling.hpp
- src/tests/functional/shared_test_classes/src/single_op/pooling.cpp
- Copy of https://github.com/openvinotoolkit/openvino/pull/20321
> `Pooling` to API2.0

- src/plugins/intel_cpu/CMakeLists.txt
Addition to https://github.com/openvinotoolkit/openvino/pull/19993
> [CPU][ARM] Set OV_CPU_ARM_ENABLE_FP16 via `add_compile_definitions`

- docs/OV_Runtime_UG/auto_device_selection.md
- docs/snippets/AUTO0.cpp
- docs/snippets/ov_auto.py
- docs/snippets/ov_multi.py
- Update python example for `ov::device::properties` setting via AUTO plugin
- Update selection logic notice for dynamic and stateful models
- 104664
> [AUTO] Update python example and selection logic notice
