openvinotoolkit/openvino

samples/cpp/benchmark_app/README.md

Port from https://github.com/openvinotoolkit/openvino/pull/20449
Update of supported model formats list for Benchmark C++ Tool for master.
Jira: 122590

[DOCS] Supported formats update for Benchmark C++ Tool for 23.1

---

src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/xlog1py.cpp
tests/layer_tests/tensorflow_tests/test_tf_Xlog1py.py

- Support Xlog1py operation for TF Hub Models
- Closes #20493

[TF FE][TF Hub] Support Xlog1py operation

---

src/core/builder/src/builder/reshape.cpp
src/core/src/bound_evaluate.cpp
src/core/src/bound_evaluate.hpp
src/core/src/op/reduce_prod.cpp
src/core/tests/type_prop/reduce_prod.cpp

- Fixed behavior of ReduceProd
- 110906

Added coverage of "0" in bounds to ReduceProd

---

src/plugins/intel_gpu/src/runtime/execution_config.cpp

- Closes https://github.com/openvinotoolkit/openvino/issues/20475
- fix typo "Attepmpt" to "Attempt"
- *ticket-id*

fix typo of config check error message

---

src/core/src/bound_evaluate.hpp
src/core/src/op/reduce_prod.cpp

- Aligned names and actions, updated comments
- N/A

Fixed naming and comments in ReduceProd

---

README.md

- *item1*
- *...*
- CVS-122348

[DOCS] Update CPU readme with AMX

---

README.md

- *item1*
- *...*
- CVS-123048

[DOCS] Update components in readme

---

.github/workflows/linux.yml
tests/model_hub_tests/torch_tests/test_timm.py

- *Filter timm scope: 1249 -> 501 models*
- *None*

[GHA] Filter timm scope for model hub tests

---

docs/snippets/ov_auto.py

- *item1*
- *...*
- *ticket-id*

[AUTO][Python Unite Test]  fixing the issue of importing property from openvino.

---

src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/matmul.cpp
tests/layer_tests/tensorflow_tests/test_tf_MatMul.py

- Support BatchMatMulV3 operation for TF Hub models
- #20494

[TF FE][TF Hub] Support BatchMatMulV3 operation

---

src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/broadcast.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/bucketize.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/concat.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/data_utils.hpp

- *BroadcastLayer, Bucketize, Concat*
- *[CVS-111379](https://jira.devtools.intel.com/browse/CVS-111379)*

[GPU] Refactor BroadcastLayer, Bucketize, Concat

---

src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_weights.cl
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.cpp
src/plugins/intel_gpu/src/kernel_selector/tensor_type.cpp
src/plugins/intel_gpu/src/kernel_selector/tensor_type.h
src/plugins/intel_gpu/src/runtime/format.cpp

216-attention-center model in notebooks newly needs o_is_yx_isv2 from onednn3.3
- *123047*

[GPU] Support o_is_yx_isv2

---

docs/articles_en/openvino_workflow/openvino_intro/dldt_deployment_optimization_guide/preprocessing_overview/preprocessing_usecase_save.md
docs/snippets/ov_preprocessing.cpp
docs/snippets/ov_preprocessing.py

- *item1*
- *...*
- CVS-122782

[DOCS ] Fix doc snippet 

---

docs/OV_Runtime_UG/preprocessing_usecase_save.md
docs/snippets/ov_preprocessing.cpp
docs/snippets/ov_preprocessing.py

Port from https://github.com/openvinotoolkit/openvino/pull/20538

[DOCS ] Fix doc snippet for 23.1

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/fully_connected.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bfyx_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_base.cpp
src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.cpp
src/plugins/intel_gpu/src/plugin/transformations/convert_matmul_to_fc.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/matmul_weights_decompression.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp

- Added support for grouped decompression scale/zero point 
- Added bfyx->fbyx conversion for decompression parameters to improve memory access pattern

[GPU] Grouped decompression scale/zp support

---

cmake/developer_package/packaging/common-libraries.cmake

- Small regression after https://github.com/openvinotoolkit/openvino/pull/20297
- Tested via https://github.com/Homebrew/homebrew-core/pull/150080

Enabled LC_RPATH for brew

---

docs/dev/build_windows.md

Removing repeated parameter.
Porting: https://github.com/openvinotoolkit/openvino/pull/20605/

[DOCS] Fix command for Building with Ninja for 23.1

---

docs/dev/build_windows.md

Removing current directory from the command.
This PR addresses the following issue: 
Closes https://github.com/openvinotoolkit/openvino/issues/20603

[DOCS] Fix command for Building with Ninja

---

.github/workflows/linux_conditional_compilation.yml
.github/workflows/windows_conditional_compilation.yml

[CI] [GHA] Extend Win CC pipeline with tests, make it static

---

src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/truncate_mod.cpp
tests/layer_tests/tensorflow_tests/test_tf_TruncateMod.py

- Support TruncateMod operation for TF Hub Models
- Closes #20448

[TF FE][TF Hub] Support TruncateMod operation

---

src/frontends/common/src/manager.cpp
src/frontends/common/src/plugin_loader.cpp
src/frontends/common/src/plugin_loader.hpp
src/frontends/tests/frontend/shared/src/library_extension.cpp
thirdparty/dependencies.cmake

- Since current PR all frontends which are loaded, they are cached to prevent multiple loaded and issues with protobuf schemas registration.
- Part of https://github.com/openvinotoolkit/openvino/pull/18739

WA issues with dynamic protobuf usage in FEs

---

docs/requirements.txt

- *item1*
- *...*
- *ticket-id*

Updated urllib3 to resolve CVE

---

src/frontends/pytorch/README.md

- *Add readme for pytorch frontend*
- *None*

[PT FE] Add readme for pytorch frontend

---

src/frontends/pytorch/src/op/bitwise.cpp
src/inference/dev_api/ie_icore.hpp
src/inference/dev_api/openvino/runtime/icore.hpp
thirdparty/fluid/modules/gapi/include/opencv2/gapi/imgproc.hpp

- suppored->supported
- *ticket-id*

fixing typo

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml

- *item1*
- *...*
- *ticket-id*

[GHA][CONFORMANCE] Enable  and conformance  for Template in GHA

---

.github/workflows/mac.yml

- *item1*
- *...*
- *ticket-id*

Fix OpImplCheck in GHA

---

src/inference/src/dev/threading/cpu_streams_executor.cpp

- *fix compilation issue for openmp on windows*
- *ticket-id*

fix compilation issue for openmp on windows

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp

[GPU] Fix for reorder fusing in fuse_constant_transposes pass

---

src/common/transformations/include/transformations/common_optimizations/convert_u4_weights_zero_point_to_scalar.hpp
src/common/transformations/src/transformations/common_optimizations/convert_u4_weights_zero_point_to_scalar.cpp
src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/src/transformations/utils/utils.cpp
src/common/transformations/tests/common_optimizations/convert_u4_weights_zero_point_to_scalar.cpp
src/core/src/graph_util.cpp

- *ConvertU4WeightsZeroPointToScalar transformation converts U4 weights zero point to scalar if all values are equal*
- *The transformation added to MOC pipeline*

[Transformations] FuseU4WeightsAndZeroPoint transformation

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/activation.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/single_op_tests/activation.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/base/utils/ranges.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/activation.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
src/tests/functional/shared_test_classes/src/single_op/activation.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/data_utils.hpp

- Refaсtor ActivationLayerTest

Refaсtor ActivationLayerTest

---

tests/model_hub_tests/torch_tests/test_hf_transformers.py

- *item1*
- *...*
- *ticket-id*

[PT FE] Fix xmod model test

---

src/inference/src/dev/threading/cpu_streams_executor.cpp

- *fix coverity scan issue*
- *ticket-id*

fix coverity scan issue

---

.github/workflows/linux.yml
src/bindings/python/CMakeLists.txt
src/bindings/python/src/pyopenvino/test_utils/CMakeLists.txt
src/frontends/onnx/tests/CMakeLists.txt
tests/layer_tests/pytorch_tests/test_adaptive_avg_pool.py
tools/ovc/CMakeLists.txt

- Extended test package (added ovc and onnx unit tests)
- removed unnecessary deps
- *111297*

[GHA] Removed dependency on git repo in python tests

---

.github/workflows/android_arm64.yml
.github/workflows/fedora.yml
.github/workflows/linux.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/linux_riscv.yml
.github/workflows/mac.yml
.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

- set default job timeouts
- *122509*

[GHA] Jobs timeouts

---

src/plugins/intel_gpu/include/intel_gpu/plugin/sync_infer_request.hpp
src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
src/plugins/intel_gpu/tests/functional/remote_blob_tests/gpu_remote_tensor_tests.cpp

- The patch enables remote outputs functionally for dynamic models. Performance optimization is a subject of another patches.
- *112637*

[GPU] Allow setting remote output for dynamic model

---

src/inference/src/dev/threading/thread_affinity.cpp
src/inference/src/dev/threading/thread_affinity.hpp

- *fix memory leak of core binding on windows*
- *ticket-id*

fix memory leak on windows

---

.ci/azure/windows.yml
.github/workflows/linux_conditional_compilation.yml
src/bindings/python/constraints.txt

- Replaces https://github.com/openvinotoolkit/openvino/pull/20703

Dependabot/pip/src/bindings/python/paddlepaddle 2.5.2

---

src/frontends/pytorch/src/transforms/tuple_unpack_replacer.cpp

- *Previously transformation for internal body will not be triggered if outer body was changed.*
- *ticket-id*

[PT FE] Fix TupleUnpackInBodyReplacer transformation to run inside body

---

src/plugins/intel_cpu/src/cpu_types.cpp
src/plugins/intel_cpu/src/cpu_types.h
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/eltwise.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/instances/common/eltwise.cpp
src/plugins/intel_cpu/tests/functional/specific_tests.cmake
src/plugins/intel_cpu/tests/functional/test_utils/cpu_test_utils.cpp
src/tests/functional/shared_test_classes/src/base/utils/compare_results.cpp
src/tests/ov_helpers/ov_models/src/eltwise.cpp
src/tests/ov_helpers/ov_models/src/input_layer.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/test_enums.hpp
src/tests/test_utils/common_test_utils/src/test_enums.cpp
src/tests/test_utils/functional_test_utils/layer_tests_summary/skip_configs/CPU/expected_failures_OP.csv

- *bitwise and, not, or and xor operation implementation for X64*
- *CVS-118966*, *CVS-118974*, *CVS-118958*, *CVS-118950*

[CPU] Bitwise operations (reference implementation)

---

tests/layer_tests/pytorch_tests/test_convnd.py

- *item1*
- *...*
- *ticket-id*

[PT FE] Disable failing pytorch layer test

---

docs/articles_en/get started/installing-openvino-overview/installing-openvino-macos-header.md
docs/articles_en/get started/installing-openvino-overview/installing-openvino-windows-header.md

- *item1*
- *...*
- *ticket-id*

[DOCS] Fix headers in install

---

src/plugins/intel_gna/docs/transformations.md

- add md file with transformations documentation
- n/a

GNA plugin transformations documentation

---

docs/install_guides/installing-openvino-macos-header.md
docs/install_guides/installing-openvino-windows-header.md

Porting: https://github.com/openvinotoolkit/openvino/pull/20728

[DOCS] Fix headers - port for 23.1

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/int4_utils.cl

- Add fp16 extension check for int4 unpacks to half data type
- 123739

[GPU] cl_khr_fp16 check for int4->half unpacks

---

src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_base.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/softmax.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/memory_realloc_test.cpp

[GPU] Allow softmax_bf kernel for axis=X 4d case

---

docs/articles_en/get started/installing-openvino-overview/installing-openvino-windows-header/installing-openvino-from-archive-windows.md
docs/articles_en/openvino_workflow/model_preparation.md

Fixing indentation issue in `Model Preparation` article.
Fixing instructions in the `Install OpenVINO™ Runtime on Windows from an Archive File` article.

[DOCS] Fixing formatting in Model Preparation

---

src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/convolution.cpp

[GPU] fix axis for pad/stride/dilation when 1d conv

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/non_max_suppression_gpu_ref.cl

- add comments about origin of reference implementation
- 118943

[GPU] add comments about origin of reference implementation

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

[GPU] Added WA for MarkDequantizationSubgraph to work correctly in the plugin

---

src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
tests/model_hub_tests/torch_tests/hf_transformers_models
tests/model_hub_tests/torch_tests/test_hf_transformers.py

- *item1*
- *...*
- *ticket-id*

[PT FE]: fix  object has no attribute 'dtype'

---

src/bindings/python/src/pyopenvino/graph/ops/constant.cpp
src/bindings/python/tests/test_graph/test_ops.py

- add `get_byte_size` method
- CVS-123895

[PyOV] Add get_byte_size to const node

---

src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.cpp

- *Fixing the problem that arose after https://github.com/openvinotoolkit/openvino/pull/20699*

[GPU] Fix for SoftmaxKernel_bf in dynamic case

---

src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_executable_network/properties.cpp

- *support user setting num_streams=0*
- Closes https://github.com/openvinotoolkit/openvino/issues/20430

support user setting num_streams=0

---

src/plugins/intel_gpu/src/graph/include/reshape_inst.h

- Fix accuracy degradation by missing of padding adjustment of reshape
- *...*
- CVS-113645

[GPU] Bugfix adjust padding size for reshape optimizing

---

src/frontends/tensorflow/src/op/enter.cpp
src/frontends/tensorflow/src/op/loop_cond.cpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
tests/layer_tests/tensorflow_tests/test_tf_While.py
tools/mo/unit_tests/moc_tf_fe/conversion_basic_models_test.py

**Details:** This is a total switch off due to GPU limitation
**Ticket:** 123930

[TF FE] Switch off TF1 While support totally

---

src/frontends/tensorflow/docs/supported_ops.md

**Details:** Update TF FE dev docs with Inv after https://github.com/openvinotoolkit/openvino/pull/20720 merge

[TF FE] Update TF FE dev docs with Inv

---

docs/install_guides/installing-openvino-vcpkg.md

Porting: https://github.com/openvinotoolkit/openvino/pull/20784

[DOCS] Removed WA for static protobuf for vcpkg installation path - for 23.1

---

src/frontends/tensorflow/src/op/sparse_reshape.cpp
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/max_pool.cpp

**Details:** Fix translators for multiple output operations. In the body graphs, these operations use named output ports for connections.

[TF FE] Fix translators for multiple output operations

---

.github/workflows/android_arm64.yml
.github/workflows/linux.yml
.github/workflows/windows.yml

[CI] [GHA] Increase job timeouts

---

src/frontends/tensorflow/src/op/enter.cpp
src/frontends/tensorflow/src/op/loop_cond.cpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
tests/layer_tests/tensorflow_tests/test_tf_While.py
tools/mo/unit_tests/moc_tf_fe/conversion_basic_models_test.py

**Details:** This reverts https://github.com/openvinotoolkit/openvino/pull/20774

Revert "[TF FE] Switch off TF1 While support totally (#20774)"

---

.github/workflows/linux.yml
.github/workflows/mac.yml
.github/workflows/windows.yml
tests/layer_tests/pytorch_tests/test_loop.py
tests/layer_tests/tensorflow_tests/test_tf_NonMaxSupression.py

[CI] [GHA] Remove full cloning of the OV repository in the Python unittests job in the Win and Mac workflows

---

src/plugins/intel_cpu/src/nodes/kernels/x64/gather_uni_kernel.cpp

- *`vPremMask` is override in `shiftIdxAndGather`, the mask needs to be reload before permutation*
- *CVS-123217*

[CPU]Fix avx2 gather of bfloat16

---

src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp

- Call `get_tensor()` and `set_tensor()` once for many inference iterations to mimic real pipeline scenario

[GPU] Refactor KV cache test

---

src/plugins/intel_cpu/src/graph_optimizer.cpp

- Port of https://github.com/openvinotoolkit/openvino/pull/20782

[CPU] Fixed port mismatch in Eltwise fusion graph optimization

---

src/frontends/tensorflow/src/input_model.hpp
src/frontends/tensorflow/src/op/partitioned_call.cpp
src/frontends/tensorflow/src/tf_utils.cpp
src/frontends/tensorflow/src/tf_utils.hpp
src/frontends/tensorflow/src/translate_session.cpp
tests/model_hub_tests/tf_hub_tests/test_tf_hub_api_notebooks.py

**Details:** Fix conversion of FILM of keras.Model format
**Ticket:** 121106

[TF FE] Fix conversion of FILM in keras.Model format

---

docs/articles_en/openvino_workflow/model_preparation/Convert_Model_From_TensorFlow.md

Description: 
- Added hub.load() example
- Moved TF function example to the top of the list
Ticket: 124070
Code:
Validation:
Documentation:

[DOC] Update list of TF formats imported from memory.

---

src/plugins/intel_cpu/src/nodes/matrix_nms.cpp
src/plugins/intel_cpu/src/nodes/multiclass_nms.cpp

[CPU] Add FP16 support to MatrixNms

---

src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/reduce_ops.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/region_yolo.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/reorg_yolo.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/reshape.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/reverse_sequence.cpp

- *reduce_ops, region_yolo, reorg_yolo, reshape, reverse_sequence*
- *CVS-124001*

[GPU] Refactor 

---

docs/articles_en/documentation/openvino_ir/operation_sets/operations_specifications/generation/Multinomial_13.md

- Apply recommended changes to spec
- Fix `probs` shape at 2D
- Fix `output` shape at 2D
- Add a better CDF documentation
- Reflect shape changes in examples
- None

[SPEC] Multinomial spec update

---

src/core/include/openvino/op/hsigmoid.hpp
src/core/src/op/hsigmoid.cpp

- HSigmoid operator migrated to new API.
- CVS-118593

[core] Migrate HSigmoid operator to new API

---

src/frontends/pytorch/src/transforms/u4_block_repack.cpp
src/frontends/pytorch/src/utils_quantize.cpp

Fix GPTQ conversion. Consists of two fixes:
- for CVS-124125
- partial revert of https://github.com/openvinotoolkit/openvino/pull/20743

Fix GPTQ model conversion after two breaking changes

---

src/core/include/openvino/op/gelu.hpp
src/core/src/op/gelu.cpp

- Gelu operator migrated to new API.
- CVS-118587

[core] Migrate Gelu operator to new API

---

.github/workflows/linux_conditional_compilation.yml
.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

[CI] [GHA] Add missing `setup-python` action checkout; use custom action across all pipelines

---

src/plugins/template/backend/ops/convert.cpp
src/plugins/template/tests/functional/op_reference/convert_color_i420.cpp
src/plugins/template/tests/functional/op_reference/convert_color_nv12.cpp
src/plugins/template/tests/functional/op_reference/embedding_segments_sum.cpp
src/plugins/template/tests/functional/op_reference/embeddingbag_offsetssum.cpp
src/plugins/template/tests/functional/op_reference/embeddingbag_packedsum.cpp
src/plugins/template/tests/functional/op_reference/exp.cpp
src/plugins/template/tests/functional/op_reference/gelu.cpp
src/plugins/template/tests/functional/op_reference/hswish.cpp
src/plugins/template/tests/functional/op_reference/if.cpp
src/plugins/template/tests/functional/op_reference/log_softmax.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_executable_network/get_metric.cpp
src/plugins/template/tests/functional/shared_tests_instances/single_layer_tests/convolution.cpp
src/plugins/template/tests/functional/shared_tests_instances/single_layer_tests/reshape.cpp
src/plugins/template/tests/functional/shared_tests_instances/single_layer_tests/split.cpp
src/plugins/template/tests/functional/subgraph_reference/preprocess.cpp

Template plugin folder to API2.0

---

docs/install_guides/installing-openvino-apt.md
docs/install_guides/installing-openvino-brew.md
docs/install_guides/installing-openvino-conan.md
docs/install_guides/installing-openvino-conda.md
docs/install_guides/installing-openvino-from-archive-linux.md
docs/install_guides/installing-openvino-from-archive-macos.md
docs/install_guides/installing-openvino-from-archive-windows.md
docs/install_guides/installing-openvino-pip.md
docs/install_guides/installing-openvino-vcpkg.md
docs/install_guides/installing-openvino-yum.md

Port from https://github.com/openvinotoolkit/openvino/pull/20677
* Added the missing information about installation differences
* Updated the System Requirements link to the one in docs

[DOCS] Install Guide Update for 23.1

---

.github/workflows/android_arm64.yml
.github/workflows/linux_riscv.yml

- fixed timeout issues:
https://github.com/openvinotoolkit/openvino/actions/runs/6766725424/job/18388225455
https://github.com/openvinotoolkit/openvino/actions/runs/6766725423/job/18388225370
- *n/a*

[GHA] Aligned Linux build timeouts

---

docs/_static/images/ov_workflow_diagram_convenience.svg
docs/_static/images/ov_workflow_diagram_performance.svg
docs/articles_en/openvino_workflow.md
docs/articles_en/openvino_workflow/model_preparation.md

adjustments to conversion and workflow

[DOCS] improving the "conversion" section

---

tests/layer_tests/tensorflow_tests/test_tf_ComplexFFT.py
tests/model_hub_tests/tf_hub_tests/precommit_models

**Details:** Refine tests for complex tensors support

[TF FE] Refine tests for complex tensors support

---

tests/model_hub_tests/torch_tests/test_aliked.py

[PT FE] Add ALIKED to model tests

---

.github/labeler.yml

- *item1*
- *...*
- *ticket-id*

Updated labeler config

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/random_uniform.hpp

[CPU] Increase RandomUniform mean and variance thresholds 

---

src/bindings/python/requirements_test.txt
src/bindings/python/setup.cfg

- *item1*
- *...*
- CVS-124276

[PyOV] ngraph linter check update

---

src/core/include/openvino/op/softplus.hpp
src/core/src/op/softplus.cpp

- Softplus operator migrated to new API.
- CVS-118658

[core] Migrate Softplus operator to new API

---

docs/articles_en/get started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-yum.md

Fixing formatting of the list of operating systems.
Porting: https://github.com/openvinotoolkit/openvino/pull/20934

[DOCS] Fixing OS list in System Requirements for YUM - for 23.2

---

src/plugins/intel_gpu/include/intel_gpu/primitives/loop.hpp
src/plugins/intel_gpu/src/graph/CMakeLists.txt
src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
src/plugins/intel_gpu/src/graph/include/loop_inst.h
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/plugin/ops/loop.cpp
src/plugins/intel_gpu/tests/unit/test_cases/loop_gpu_test.cpp

- *Support dynamic tesnoriterator without trip_count and -1 num_iteration*
- *Modify memory copy calculation for slice and concat memory*
- *Refactoring memory handling methods for loop_inst*
- *114920*

Support dynamic tensor_iterator

---

src/bindings/python/src/compatibility/openvino/CMakeLists.txt
src/plugins/intel_gna/CMakeLists.txt

- *item1*
- *...*
- *ticket-id*

Disable warnings about API 1.0 in GNA, Python API 1.0

---

docs/_static/images/ov_workflow_diagram_convenience.svg
docs/_static/images/ov_workflow_diagram_performance.svg
docs/articles_en/openvino_workflow.md
docs/articles_en/openvino_workflow/model_preparation.md

port: https://github.com/openvinotoolkit/openvino/pull/20887

[DOCS] improving the "conversion" section port 23.2

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/memory.cpp
src/tests/functional/plugin/shared/include/single_op_tests/memory.h
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/memory.hpp
src/tests/functional/shared_test_classes/src/single_op/memory.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/test_enums.hpp
src/tests/test_utils/common_test_utils/src/test_enums.cpp

Refactor MemoryLayerTest

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/conformance_helper_tools/find_models_for_subgraphs_dumper.py

- *Fix to generate dlb based conformance ir cache* @ilya-lavrenov Could you please approve and merge?
- *ticket-id*

[CONFORMANCE] Partial cherry-pick of PR20756 to exclude  from model list for conformance

---

docs/articles_en/openvino_workflow/deployment_intro.md
docs/articles_en/openvino_workflow/model_optimization_guide/tmo_introduction.md

Port from https://github.com/openvinotoolkit/openvino/pull/20947
Fixing typos and missing bullet point in articles.

[DOCS] Small fixes in articles for 23.2

---

docs/OV_Runtime_UG/deployment/deployment_intro.md
docs/optimization_guide/nncf/introduction.md

Port from https://github.com/openvinotoolkit/openvino/pull/20947
Fixing typos and missing bullet point in articles.

[DOCS] Small fixes in articles for 23.1

---

docs/articles_en/openvino_workflow/gen_ai.md
docs/articles_en/openvino_workflow/model_optimization_guide/weight_compression.md
docs/optimization_guide/nncf/code/weight_compression_openvino.py

Port from https://github.com/openvinotoolkit/openvino/pull/20812
* Added docs for INT4

[DOCS] Added INT4 weight compression description for 23.2

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *item1*
- *...*
- *ticket-id*

[conformance] Skip empty test cache error

---

.github/workflows/fedora.yml
.github/workflows/linux.yml

- Increased CXX_Unit_Tests and RPM build timeouts to solve https://github.com/openvinotoolkit/openvino/actions/runs/6790372905/job/18460136181?pr=19825
- *n/a*

[GHA] Fixed timeouts

---

src/plugins/intel_gpu/tests/functional/single_layer_tests/loop.cpp
src/tests/functional/plugin/shared/include/single_op_tests/loop.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/loop.hpp
src/tests/functional/shared_test_classes/src/single_op/loop.cpp

- Refactor StaticShapeLoopLayerTest

Refactor StaticShapeLoopLayerTest

---

src/core/reference/include/openvino/reference/relu.hpp

- Fix compilation warning on Ubuntu20 in debug build.
- [CVS-124652](https://jira.devtools.intel.com/browse/CVS-124652)

[CI]Fix Ubuntu20 build error on ReLU operator

---

.github/actions/smart-ci/smart_ci.py
.github/workflows/linux.yml

- *item1*
- *...*
- *ticket-id*

Fixes for smart CI

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp

-added option: OV_GPU_PrintLayersInput
- 123974

[GPU] print datashape of input for benchmark_app

---

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp

[GPU] clean up for extend pad/stride/dilation

---

.github/workflows/linux.yml

- *item1*
- *...*
- *ticket-id*

Added more smart CI conditions

---

.github/workflows/windows.yml

- *Fix win run*
- *[ticket-id](https://jira.devtools.intel.com/browse/CVS-123572)*

[GHA] Check OpImplCheck conformance for template plugin (to make sure that all functions are checked by conformance)

---

docs/articles_en/about_openvino.md

- *item1*
- *...*
- *ticket-id*

[DOCS] Add content to about ov page

---

src/plugins/intel_gpu/src/graph/impls/ocl/lstm_elt.cpp
src/plugins/intel_gpu/src/graph/include/lstm_elt_inst.h
src/plugins/intel_gpu/src/graph/lstm_elt.cpp
src/plugins/intel_gpu/src/plugin/ops/rnn.cpp
src/plugins/intel_gpu/src/plugin/program_builder.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/tensor_iterator.cpp

- *Replace cldnn::tensor to ov::PartialShape in LSTMCell dynamic shape*
- *Remove redundant reorder / reshape in LSTMCell dynamic shape*
- *Implement lstm_elt::calc_output_layouts for dynamic shape*
- *Implement lstm_elt_impl::static_canonicalize_shapes for dynamic shape* 
- *114920*

Support LSTMSequence with -1 sequence length 

---

src/frontends/tensorflow_common/src/op/addN.cpp
src/frontends/tensorflow_common/src/op/arg_min_max.cpp
src/frontends/tensorflow_common/src/op/binary_op.cpp
src/frontends/tensorflow_common/src/op/cast.cpp
src/frontends/tensorflow_common/src/op/const.cpp
src/frontends/tensorflow_common/src/op/einsum.cpp
src/frontends/tensorflow_common/src/op/elu.cpp
src/frontends/tensorflow_common/src/op/fill.cpp
src/frontends/tensorflow_common/src/op/matmul.cpp
src/frontends/tensorflow_common/src/op/placeholder.cpp
src/frontends/tensorflow_common/src/op/relu_6.cpp
src/frontends/tensorflow_common/src/op/round.cpp
src/frontends/tensorflow_common/src/op/square.cpp
src/frontends/tensorflow_common/src/op/unary_op.cpp
src/frontends/tensorflow_common/src/utils.cpp

**Details:** Refactor ops translators to check complex type and speed-up compilation

[TF FE] Refactor ops translators to check complex type and speed-up compilation

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_quantization.cpp

Fixed prepare_quantization to use partial_shape when dynamic,
- *124361*

[GPU] Fix LCM notebook failure issue for int8 model.

---

tests/model_hub_tests/tf_hub_tests/precommit_models

**Details:** After fixing ov.Tensor creation for empty numpy array in https://github.com/openvinotoolkit/openvino/pull/20967, we are ready to support yamnet

[TF Hub] Add yamnet with complex tensors into precommit

---

src/bindings/c/tests/ie_c_api_test.cpp
src/bindings/python/tests/test_runtime/test_core.py
src/bindings/python/tests/test_utils/test_utils.py
src/bindings/python/tests_compatibility/test_inference_engine/test_IECore.py
src/common/util/CMakeLists.txt
src/common/util/include/openvino/util/file_util.hpp
src/common/util/src/file_util.cpp
src/common/util/src/os/lin/lin_shared_object_loader.cpp
src/inference/src/ie_core.cpp
src/inference/tests/unit/CMakeLists.txt
src/inference/tests/unit/core.cpp

- Port of https://github.com/openvinotoolkit/openvino/pull/15073 and https://github.com/openvinotoolkit/openvino/pull/15291
- [CVS-124148](https://jira.devtools.intel.com/browse/CVS-124148)

[2022.3] Safe plugins loading

---

src/plugins/intel_gpu/include/intel_gpu/primitives/loop.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/graph/lstm_dynamic_timeloop.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/plugin/ops/loop.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/tensor_iterator.cpp
src/plugins/intel_gpu/tests/unit/fusions/loop_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/loop_gpu_test.cpp

- *add output port for multiple outputs of node*
- *add functional test for lstm_sequence*
- *114920*

[GPU] Fix acc issue for LSTMSequence w/ -1 seq_length

---

src/plugins/intel_gpu/include/intel_gpu/primitives/shape_of.hpp
src/plugins/intel_gpu/src/graph/shape_of.cpp
src/plugins/intel_gpu/src/plugin/ops/shape_of.cpp
src/plugins/intel_gpu/tests/unit/passes/add_required_reorders_test.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
src/plugins/intel_gpu/tests/unit/passes/remove_redundant_reorders_tests.cpp
src/plugins/intel_gpu/tests/unit/test_cases/canonicalization_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/lru_caches_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/multiple_streams_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/reshape_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/shape_of_gpu_test.cpp

[GPU] Fix ShapeOf primitive

---

src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/convolution.cpp

[GPU] remove setting threshold manually for dynamic 1d conv

---

docs/articles_en/documentation/openvino_legacy_features.md
docs/articles_en/openvino_workflow/deployment_intro.md
docs/articles_en/openvino_workflow/deployment_intro/deployment-manager-tool.md

- *item1*
- *...*
- *ticket-id*

[DOCS] Deprecate deployment manager

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_convolution_backprop_data.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_convolution_backprop_data.cpp
src/tests/functional/plugin/shared/include/subgraph_tests/quantized_convolution_backprop_data.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_convolution_backprop_data.hpp
src/tests/functional/shared_test_classes/src/subgraph/quantized_convolution_backprop_data.cpp

- Upgrade func test of QuantConvBackpropDataLayerTest related to 2.0
- 124431

[Func Test] Upgrade func test of QuantConvBackpropDataLayerTest related to 2.0

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_group_convolution.cpp
src/tests/functional/plugin/shared/include/subgraph_tests/quantized_group_convolution.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_group_convolution.hpp
src/tests/functional/shared_test_classes/src/subgraph/quantized_group_convolution.cpp

- Upgrade func test of QuantGroupConvLayerTest related to 2.0
- 124431

[Func Test] Upgrade func test of QuantGroupConvLayerTest related to 2.0

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_group_convolution_backprop_data.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_group_convolution_backprop_data.cpp
src/tests/functional/plugin/shared/include/subgraph_tests/quantized_group_convolution_backprop_data.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_group_convolution_backprop_data.hpp
src/tests/functional/shared_test_classes/src/subgraph/quantized_group_convolution_backprop_data.cpp

- Upgrade func test of QuantGroupConvBackpropDataLayerTest related to 2.0
- 124431

[Func Test] Upgrade func test of QuantGroupConvBackpropDataLayerTest related to 2.0

---

src/core/reference/include/openvino/reference/multinomial.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/multinomial.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/slice.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/multinomial.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/register.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/register.hpp
src/plugins/intel_gpu/src/graph/include/multinomial_inst.h
src/plugins/intel_gpu/src/graph/include/slice_inst.h
src/plugins/intel_gpu/src/graph/multinomial.cpp
src/plugins/intel_gpu/src/graph/slice.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/multinomial_ref.cl
src/plugins/intel_gpu/src/kernel_selector/common_types.h
src/plugins/intel_gpu/src/kernel_selector/kernels/multinomial/multinomial_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/multinomial/multinomial_kernel_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/multinomial/multinomial_kernel_selector.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/multinomial/multinomial_kernel_selector.h
src/plugins/intel_gpu/src/plugin/ops/multinomial.cpp
src/plugins/intel_gpu/src/plugin/ops/slice.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/multinomial.cpp
src/plugins/intel_gpu/tests/unit/test_cases/slice.cpp
src/plugins/template/tests/functional/op_reference/multinomial.cpp
src/tests/functional/plugin/shared/include/single_layer_tests/multinomial.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/multinomial.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
src/tests/functional/shared_test_classes/src/single_layer/multinomial.cpp

- *Multinomial-13 GPU reference implementation*
- *Tests which cover Multinomial-13 implementation*
- *Fixes for Multinomial-13 reference*
- *Workaround for CumSum GPU implementation*
- *CVS-118987*

[GPU] Multinomial-13

---

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

Currently, we rely on tensor type to detect if user's buffer has usm_host type or not. This patch adds additional raw pointer check to detect if user's buffer can be reused with zero copy or not. (For some reason Python API prevents proper detection of tensor type's, so this change is supposed to improve memory reuse in case of Python API usage)
- 125156

[GPU] Add more flexible check if user's buffer is USM Host and can be reused

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/quantized_mat_mul.cpp
src/tests/functional/plugin/shared/include/subgraph_tests/quantized_mat_mul.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/quantized_mat_mul.hpp
src/tests/functional/shared_test_classes/src/subgraph/quantized_mat_mul.cpp

- Upgrade func test of QuantMatMulTest related to 2.0
- 124431

[Func Test] Upgrade func test of QuantMatMulTest related to 2.0

---

src/tests/functional/plugin/shared/include/behavior/compiled_model/compiled_model_base.hpp
src/tests/functional/plugin/shared/src/behavior/compiled_model/properties.cpp

- *https://github.com/openvinotoolkit/openvino/pull/19541*
- *[111377](https://jira.devtools.intel.com/browse/CVS-111377)*

remove similar test cases

---

.github/components.yml

- change dependencies of virtual plugin on smart CI
- *ticket-id*

resolve dependency on smart CI

---

docs/requirements.txt

- [CVS-124919](https://jira.devtools.intel.com/browse/CVS-124919)

Bump deps py versions to fix severity issues

---

docs/conf.py

[DOCS] Update version of conf.py

---

docs/articles_en/get started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-from-archive-linux.md
docs/articles_en/get started/installing-openvino-overview/installing-openvino-macos-header/installing-openvino-from-archive-macos.md
docs/articles_en/get started/installing-openvino-overview/installing-openvino-windows-header/installing-openvino-from-archive-windows.md

- *item1*
- *...*
- *ticket-id*

[DOCS] Add install links

---

docs/articles_en/documentation/openvino_legacy_features/--installing-model-dev-tools.md
docs/articles_en/get started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-apt.md
docs/articles_en/get started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-yum.md
docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-conan.md
docs/articles_en/get started/installing-openvino-overview/installing-openvino-shared/installing-openvino-conda.md

- *item1*
- *...*
- *ticket-id*

[DOCS] Update links to 23.2

---

docs/articles_en/about_openvino/releasenotes_for_openvino.md
docs/articles_en/about_openvino/system_requirements.md

Porting: https://github.com/openvinotoolkit/openvino/pull/21108

[DOCS] Final update of release notes - for master

---

cmake/developer_package/frontends/frontends.cmake
src/frontends/onnx/frontend/CMakeLists.txt
src/frontends/paddle/src/CMakeLists.txt
src/frontends/tensorflow/src/CMakeLists.txt
src/frontends/tensorflow_lite/src/CMakeLists.txt

- *item1*
- *...*
- CVS-125206

Fixed install rules for case when only ONNX FE is enabled

---

docs/articles_en/get started/installing-openvino-overview.md

[DOCS] Fixing versions in Install Openvino

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/highlight_tables.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/summarize.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/template/filters_api.js
src/tests/test_utils/functional_test_utils/layer_tests_summary/template/highlight_tables_template.html
src/tests/test_utils/functional_test_utils/layer_tests_summary/template/report_api_template.html
src/tests/test_utils/functional_test_utils/layer_tests_summary/template/style.css

[apiConformance] Update reports to avoid sw plugins over all devices

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/matrix_nms.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/multiclass_nms.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/non_max_suppression.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/non_max_suppression.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/single_op_tests/matrix_nms.hpp
src/tests/functional/plugin/shared/include/single_op_tests/multiclass_nms.hpp
src/tests/functional/plugin/shared/include/single_op_tests/non_max_suppression.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/matrix_nms.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/multiclass_nms.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/non_max_suppression.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
src/tests/functional/shared_test_classes/src/single_op/matrix_nms.cpp
src/tests/functional/shared_test_classes/src/single_op/multiclass_nms.cpp
src/tests/functional/shared_test_classes/src/single_op/non_max_suppression.cpp

- Refactor MatrixNmsLayerTest, MulticlassNmsLayerTest, NmsLayerTest

Refactor NMS shared tests

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/graph/impls/common/condition.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/tests/unit/test_cases/condition_gpu_test.cpp

- Skip subgraph of if operator, if it has only input and output nodes.
- 124832

[GPU] Skip empty subgraph of If operator

---

src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_clamp.py
tests/layer_tests/pytorch_tests/test_norm.py

- *Align types for aten::clamp_max and aten::clamp_min*
- #21066

[PT FE] Align types for aten::clamp_max and aten::clamp_min

---

src/frontends/tensorflow_common/src/op/argdef_ops.cpp
src/frontends/tensorflow_common/src/op/avg_pool.cpp
src/frontends/tensorflow_common/src/op/bias_add.cpp
src/frontends/tensorflow_common/src/op/binary_op.cpp
src/frontends/tensorflow_common/src/op/broadcast_args.cpp
src/frontends/tensorflow_common/src/op/broadcast_to.cpp
src/frontends/tensorflow_common/src/op/bucketize.cpp
src/frontends/tensorflow_common/src/op/clip_by_value.cpp
src/frontends/tensorflow_common/src/op/concat.cpp
src/frontends/tensorflow_common/src/op/conv_2d_backprop.cpp
src/frontends/tensorflow_common/src/op/conv_3d_backprop.cpp

**Details:** Avoid use of heavy header file for the whole opset.

[TF FE] Speed up compilation - part 1

---

docs/OV_Converter_UG/prepare_model/convert_model/MO_OVC_transition.md
docs/OV_Runtime_UG/supported_plugins/GNA.md

update npu mention
port: https://github.com/openvinotoolkit/openvino/pull/21147

[DOCS] fix npu mention port to 23.1

---

docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition.md
docs/articles_en/openvino_workflow/openvino_intro/Device_Plugins/GNA.md

update npu mention
port: https://github.com/openvinotoolkit/openvino/pull/21147

[DOCS] fix npu mention

---

src/frontends/pytorch/src/op/full.cpp
src/frontends/pytorch/src/op/norm.cpp
src/frontends/pytorch/src/op_table.cpp
src/frontends/pytorch/src/utils.cpp
src/frontends/pytorch/src/utils.hpp
tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
tests/layer_tests/pytorch_tests/test_norm.py

- *Support aten::_weight_norm*
- *Support aten::full with scalar size*
- *Contributes to 124970*

[PT FE] Support aten::_weight_norm and aten::full with scalar size

---

src/plugins/intel_gpu/src/graph/loop.cpp

+ Not to use reference::split
- Fix issue of reference::split in slice_mem implementation
- CVS-124829

[GPU] Fix perf regression from dynamic tensor iterator

---

src/frontends/tensorflow_common/src/op/crop_and_resize.cpp
src/frontends/tensorflow_common/src/op/ctc_greedy_decoder.cpp
src/frontends/tensorflow_common/src/op/depth_to_space.cpp
src/frontends/tensorflow_common/src/op/depthwise_conv_2d.cpp
src/frontends/tensorflow_common/src/op/dynamic_partition.cpp
src/frontends/tensorflow_common/src/op/expand_dims.cpp
src/frontends/tensorflow_common/src/op/extract_image_patches.cpp
src/frontends/tensorflow_common/src/op/fused_batch_norm.cpp
src/frontends/tensorflow_common/src/op/gather.cpp

**Details:** Speed up compilation of TF FE. Avoid use of heavy header.

[TF FE] Speed up compilation - part 2

---

.github/components.yml

- *item1*
- *...*
- *ticket-id*

Smart CI: CPU triggers tests for PT and TF FEs

---

src/plugins/intel_gpu/include/intel_gpu/plugin/program_builder.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/include/loop_inst.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/plugin/ops/loop.cpp
src/plugins/intel_gpu/src/plugin/program_builder.cpp

- Implementation of loop for new TF FE(PR#20270)
- Apply infinite trip count(-1)
- Apply _exec_deps for backedge
- Apply cached constant primitive id for loop construnction
- 123934
- 123651

[GPU] Fix issues in dynamic loops newly created by TF FE support

---

docs/nbdoc/consts.py
docs/nbdoc/nbdoc.py

Fix for Binder and Colab badges in notebooks.
Porting: https://github.com/openvinotoolkit/openvino/pull/21208

[DOCS] Fixing links in notebooks for 23.2

---

docs/ops/activation/Elu_1.md

Fixing a math formula in the article.
Addressing JIRA ticket: 125145
Porting: https://github.com/openvinotoolkit/openvino/pull/21203

[DOCS] Fix math formula in Elu_1 for 23.1

---

docs/articles_en/documentation/openvino_ir/operation_sets/operations_specifications/activation/Elu_1.md

Fixing a math formula in the article.
Addressing JIRA ticket: 125145
Porting: https://github.com/openvinotoolkit/openvino/pull/21203

[DOCS] Fix math formula in Elu_1 for 23.2

---

docs/articles_en/openvino_workflow/running_inference_with_openvino.md

Providing a link to the current version of the "Supported Model Formats" article.
Addressing the Jira ticket: 122172
Porting: https://github.com/openvinotoolkit/openvino/pull/21216

[DOCS] Update reference to Supported Model Formats for 23.2

---

docs/articles_en/openvino_workflow/running_inference_with_openvino.md

Providing a link to the current version of the "Supported Model Formats" article.
Addressing the Jira ticket: 122172

[DOCS] Update reference to Supported Model Formats

---

src/frontends/tensorflow_common/src/op/l2_loss.cpp
src/frontends/tensorflow_common/src/op/leaky_relu.cpp
src/frontends/tensorflow_common/src/op/linspace.cpp
src/frontends/tensorflow_common/src/op/list_diff.cpp
src/frontends/tensorflow_common/src/op/log1p.cpp
src/frontends/tensorflow_common/src/op/log_softmax.cpp
src/frontends/tensorflow_common/src/op/lrn.cpp
src/frontends/tensorflow_common/src/op/matrix_diag.cpp
src/frontends/tensorflow_common/src/op/no_op.cpp
src/frontends/tensorflow_common/src/op/non_max_suppression.cpp
src/frontends/tensorflow_common/src/op/one_hot.cpp
src/frontends/tensorflow_common/src/op/pack.cpp
src/frontends/tensorflow_common/src/op/pad.cpp
src/frontends/tensorflow_common/src/op/parallel_dynamic_stitch.cpp

**Details:** Avoid use of heavy header `opsetX.hpp`.

[TF FE] Speed up compilation - part 3

---

src/tests/functional/plugin/conformance/subgraphs_dumper/tests/matchers/single_op/matchers_config.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_infer_request/infer_request_dynamic.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/caching_tests.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/core_integration.cpp
src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/include/op_impl_check/single_op_graph.hpp
src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/op_impl_check/single_op_graph.cpp
src/tests/functional/plugin/shared/include/base/multi/multi_helpers.hpp
src/tests/functional/plugin/shared/include/base/ov_behavior_test_utils.hpp
src/tests/functional/plugin/shared/include/behavior/compiled_model/compiled_model_base.hpp
src/tests/functional/plugin/shared/include/behavior/compiled_model/import_export.hpp
src/tests/functional/plugin/shared/include/behavior/compiled_model/properties.hpp
src/tests/functional/plugin/shared/include/behavior/ov_executable_network/get_metric.hpp
src/tests/functional/plugin/shared/include/behavior/ov_infer_request/infer_request_dynamic.hpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/caching_tests.hpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/life_time.hpp
src/tests/functional/plugin/shared/src/behavior/ov_infer_request/infer_request_dynamic.cpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/life_time.cpp

- Legacy folders (like functional/plugin/shared/include/behavior/executable_network) are left as is

Refactor `functional/plugin/conformance/` and `functional/plugin/shared/`

---

src/plugins/intel_gpu/tests/unit/CMakeLists.txt
src/plugins/intel_gpu/tests/unit/shape_infer/broadcast_si_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/scatter_elements_update_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/transformations/convert_pooling_to_reduce_test.cpp
src/plugins/intel_gpu/tests/unit/transformations/decompose_reduce_for_false_keepdims_test.cpp

- [*CVS-123997*](https://jira.devtools.intel.com/browse/CVS-123997)

Remove legacy API from `ov_gpu_unit_tests`

---

src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
src/frontends/pytorch/src/node_context.cpp
tests/layer_tests/pytorch_tests/test_pooling.py

- *Recognize empty non-frozen lists*
- *Contributes to 124970*

[PT FE] Recognize empty non-frozen lists

---

docs/api/ie_python_api/api.rst

- cherry-picked https://github.com/openvinotoolkit/openvino/pull/21201
- *ticket-id*

[Docs][PyOV] add missing docs (#21201)

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/src/kernel_selector/kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp

- Changed blocking value for batch from 1 to 8 for INT4 cases (both static and dynamic)
- Added optimized branch for single batch case (dynamic INT4 case)
- 124042

[GPU] Update FC batch blocking for INT4 weights

---

src/frontends/pytorch/src/op/fmod.cpp
src/frontends/pytorch/src/op/prod.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_fmod.py
tests/layer_tests/pytorch_tests/test_prod.py

- *Support aten::prod and aten::fmod*
- #20928

[PT FE] Support aten::prod and aten::fmod

---

src/plugins/intel_cpu/src/utils/plain_tensor.hpp

- Update missed assertion to remove compile warning after merge of #21199 
- [CVS-125576](https://jira.devtools.intel.com/browse/CVS-125576)

[CI]Correct assertion in `PlainTensor::slice`  (-Wsign-compare)

---

.github/workflows/linux.yml

[GHA] Rename overall status check

---

tools/pot/openvino/tools/pot/api/samples/prune_and_quantize/resnet50_quantization_sparsity_POT_example.py

Adding a POT script for pruning and quantization

adding resnet_50_prune and quantize script for ov2023.1

---

src/frontends/pytorch/src/op/fmod.cpp
src/frontends/pytorch/src/op/prod.cpp
src/frontends/pytorch/src/op/round.cpp

- *Remove fp32 aligning for aten::round*
- *Tests: tested by existing layer tests*
- *None*

[PT FE] Remove fp32 aligning for aten::round

---

src/inference/src/dev/core_impl.cpp
src/plugins/proxy/tests/batch_compliance_test.cpp

- keep the auto batching setting for proxy deice with ID
- [PR19508](https://github.com/openvinotoolkit/openvino/pull/19508)

[PROXY] keep the batch setting for proxy device with ID

---

cmake/developer_package/frontends/frontends.cmake

- Keeps folder structure in Visual Studio projects
- N/A

[CMAKE] Keep frontend's folder structure for Visual Studio

---

src/frontends/pytorch/src/op/sum.cpp

- *Get input dtype for aten::sum from graph*
- *Contributes to 124970*

[PT FE] Get input dtype for aten::sum from graph

---

docs/_static/css/custom.css

Updated custom.css file with tabs

[DOCS] tabs styling

---

src/inference/src/dev/core_impl.cpp
src/plugins/proxy/tests/batch_compliance_test.cpp

Reverts openvinotoolkit/openvino#21248
Try to fix LTO

Revert "[PROXY] keep the batch setting for proxy device with ID"

---

src/frontends/tensorflow_common/src/op/random_uniform.cpp
src/frontends/tensorflow_common/src/op/range.cpp
src/frontends/tensorflow_common/src/op/rank.cpp
src/frontends/tensorflow_common/src/op/reciprocal.cpp
src/frontends/tensorflow_common/src/op/reduce.cpp
src/frontends/tensorflow_common/src/op/reshape.cpp
src/frontends/tensorflow_common/src/op/reverse.cpp
src/frontends/tensorflow_common/src/op/reverse_sequence.cpp
src/frontends/tensorflow_common/src/op/scatter_nd.cpp
src/frontends/tensorflow_common/src/op/segment_sum.cpp
src/frontends/tensorflow_common/src/op/select.cpp
src/frontends/tensorflow_common/src/op/size.cpp
src/frontends/tensorflow_common/src/op/slice.cpp
src/frontends/tensorflow_common/src/op/softmax.cpp
src/frontends/tensorflow_common/src/op/space_to_batch_nd.cpp
src/frontends/tensorflow_common/src/op/space_to_depth.cpp
src/frontends/tensorflow_common/src/op/sparse_to_dense.cpp
src/frontends/tensorflow_common/src/op/split.cpp
src/frontends/tensorflow_common/src/op/sqrt.cpp
src/frontends/tensorflow_common/src/op/squeeze.cpp
src/frontends/tensorflow_common/src/op/strided_slice.cpp

**Details:** Avoid use of heavy `opsetX.hpp` header.

[TF FE] Speed up compilation - part 4

---

src/plugins/intel_cpu/src/nodes/scaled_attn.cpp

- Fix the Coverity Scan Issue in CPU Plugin scaled_attn.cpp
- 125936

[Coverity Scan Issue] fix cs issues in scaled_attn.cpp

---

src/core/include/openvino/op/constant.hpp
src/frontends/tensorflow_common/src/op/tile.cpp
src/frontends/tensorflow_common/src/op/top_k.cpp
src/frontends/tensorflow_common/src/op/transpose.cpp
src/frontends/tensorflow_common/src/op/unique.cpp
src/frontends/tensorflow_common/src/op/unpack.cpp
src/frontends/tensorflow_common/src/op/where.cpp
src/frontends/tensorflow_common/src/op/xdivy.cpp
src/frontends/tensorflow_common/src/op/zeros_like.cpp
src/frontends/tensorflow_common/src/utils.cpp

**Details:** Avoid usage of heavy opsetX header

[TF FE] Speed up compilation - part 5

---

src/plugins/intel_cpu/src/nodes/interpolate.cpp
src/plugins/intel_cpu/src/nodes/interpolate.h
src/plugins/intel_cpu/tests/functional/single_layer_tests/interpolate.cpp

- *extend to support rank 3 input*
- *CVS-123800*

[CPU]Interpolate extend to rank 3 input support

---

src/bindings/python/src/pyopenvino/graph/dict_attribute_visitor.cpp
src/bindings/python/src/pyopenvino/graph/dict_attribute_visitor.hpp
src/bindings/python/src/pyopenvino/graph/model.cpp
src/bindings/python/src/pyopenvino/graph/node_factory.cpp

- `NGRAPH_CHECK` -> `OPENVINO_ASSERT`
- *ticket-id*

[PyOV] Replace legacy assert

---

src/plugins/intel_gpu/src/graph/impls/common/condition.cpp

[GPU] get layout from get_output_layout in primitive_inst

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/include/fuse_transpose_reorder.hpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fuse_transpose_reorder.cpp

- Migrate FuseTransposeAndReorderTest to API 2.0
- *ticket-id*

[CPU Tests] migrate FuseTransposeAndReorderTest to API 2.0

---

docs/_static/css/custom.css

[DOCS] tabs styling (#21272)

---

docs/snippets/ov_model_with_state_infer.cpp
src/bindings/python/tests/test_runtime/test_infer_request.py
src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/src/transformations/convert_precision.cpp
src/common/transformations/tests/utils/convert_precision.cpp
src/core/include/openvino/op/util/variable.hpp
src/core/tests/type_prop/assign.cpp
tools/mo/openvino/tools/mo/ops/read_value.py

+ leftovers from https://github.com/openvinotoolkit/openvino/pull/20404
- *CVS-125690*

ConvertPrecision transformation: handle Assign, ReadValue and Variable

---

src/plugins/intel_gpu/src/graph/program.cpp

[GPU] Added the ability to set enable_cpu_pinning property

---

src/plugins/intel_cpu/tests/functional/subgraph_tests/include/conv_concat.hpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/conv_concat.cpp

- Upgrade ConvConcatSubgraphTest to API 2.0
- 125924

[CPU Plugin][Func Test] Upgrade ConvConcatSubgraphTest to API 2.0

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_executable_network/properties.cpp

- *update model prefer threads for M1*
- *Remove hard-code "num_streams = 1" for ARM*
- *Remove WA for hard-code in test case*
- *110072*

update model prefer threads for M1

---

src/plugins/intel_cpu/tests/functional/subgraph_tests/include/conv_with_zero_point_fuse.hpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/conv_with_zero_point_fuse.cpp

- Upgrade ConvWithZeroPointFuseSubgraphTest to API 2.0
- 125924

[CPU Plugin][Func Test] Upgrade ConvWithZeroPointFuseSubgraphTest to API 2.0

---

docs/optimization_guide/nncf/ptq/code/ptq_aa_openvino.py
docs/optimization_guide/nncf/ptq/code/ptq_onnx.py
docs/optimization_guide/nncf/ptq/code/ptq_tensorflow.py
docs/optimization_guide/nncf/ptq/code/ptq_torch.py

- Migrate to openvino.convert_model(...) in the quantization code snippets
- 125779

[DOCS] Migrate to openvino.convert_model(...) in the quantization code snippets

---

src/core/include/openvino/op/reverse.hpp
src/core/src/op/reverse.cpp

- Migrate Reverse operator to hew API.
- Re-factor to drop usage of legacy functions.
- [CVS-118646](https://jira.devtools.intel.com/browse/CVS-118646)

[core]Migrate Reverse operator to new API

---

src/common/transformations/include/transformations/common_optimizations/concat_fusion.hpp
src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
src/common/transformations/src/transformations/common_optimizations/concat_fusion.cpp
src/common/transformations/tests/common_optimizations/concat_fusion.cpp

- *Add transformation to fuse Concat sequence*
- *Contributes to 124970*

Add transformation to fuse Concat sequence

---

src/core/src/op/reshape.cpp

- Remove legacy include.
- Use helper function to get tensors partial shapes.
- Use not deprecate label evaluator.
- [CVS-118644](https://jira.devtools.intel.com/browse/CVS-118644)

Remove old API leftovers in Reshape operator

---

src/plugins/intel_cpu/tests/functional/subgraph_tests/include/fuse_muladd_ewsimple.hpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fuse_muladd_ewsimple.cpp

- Upgrade FuseMulAddAndEwSimpleTest to API 2.0
- Rename makeEltwise to make_eltwise
- 125924

[CPU Plugin][Func Test] Upgrade FuseMulAddAndEwSimpleTest to API 2.0

---

tools/ovc/openvino/__init__.py
tools/ovc/openvino/tools/ovc/__main__.py
tools/ovc/openvino/tools/ovc/cli_parser.py
tools/ovc/openvino/tools/ovc/convert.py
tools/ovc/openvino/tools/ovc/convert_data_type.py
tools/ovc/openvino/tools/ovc/convert_impl.py
tools/ovc/openvino/tools/ovc/environment_setup_utils.py
tools/ovc/openvino/tools/ovc/error.py
tools/ovc/openvino/tools/ovc/help.py
tools/ovc/openvino/tools/ovc/logger.py
tools/ovc/openvino/tools/ovc/main.py
tools/ovc/openvino/tools/ovc/moc_frontend/analysis.py
tools/ovc/openvino/tools/ovc/moc_frontend/check_config.py
tools/ovc/openvino/tools/ovc/moc_frontend/extractor.py
tools/ovc/openvino/tools/ovc/moc_frontend/moc_emit_ir.py
tools/ovc/openvino/tools/ovc/moc_frontend/offline_transformations.py
tools/ovc/openvino/tools/ovc/moc_frontend/paddle_frontend_utils.py
tools/ovc/openvino/tools/ovc/moc_frontend/pipeline.py
tools/ovc/openvino/tools/ovc/moc_frontend/preprocessing.py
tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py
tools/ovc/openvino/tools/ovc/moc_frontend/shape_utils.py
tools/ovc/openvino/tools/ovc/moc_frontend/type_utils.py
tools/ovc/openvino/tools/ovc/ovc.py
tools/ovc/openvino/tools/ovc/telemetry_utils.py
tools/ovc/openvino/tools/ovc/utils.py
tools/ovc/openvino/tools/ovc/version.py

**Details:** Apply Python code formatting to OVC

[OVC] Apply Python code formatting to OVC

---

tests/model_hub_tests/torch_tests/requirements.txt
tests/model_hub_tests/torch_tests/test_edsr.py

- *Add EDSR models to GHA tests*
- *None*

[PT FE] Add EDSR models to GHA tests

---

docs/articles_en/openvino_workflow/model_optimization_guide/ptq_introduction/quantization_w_accuracy_control.md

- Update reference in quantization_w_accuracy_control.md to avoid 404
- 126089

[DOCS] Update reference in quantization_w_accuracy_control.md

---

src/plugins/intel_gpu/tests/unit/test_cases/condition_gpu_test.cpp

This case will check the layout of condition in these conditions.
- it re-allocated at primitive_inst::realloc_if_needed().
- it can be skip subgraph.
- 125771

[GPU] This case will check the layout of condition in these conditions.

---

src/frontends/pytorch/src/op/prod.cpp
tests/layer_tests/pytorch_tests/test_prod.py

- *Support bool in aten::prod*
- *None*

[PT FE] Support bool in aten::prod

---

src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_resolve_conj_neg.py

- *item1*
- *...*
- *ticket-id*

[PT FE]: support aten:resolve_neg, aten::resolve_conj

---

src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fq_layer_dq_bias.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fuse_conv_fq_with_shared_constants.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/fuse_non0_output_port.cpp

- Remove ngraph namespace
- Remove InferenceEnginenamespace
- 125924

[CPU Plugin][Func Test] Upgrade Fuse related to API 2.0

---

docs/articles_en/openvino_workflow/model_optimization_guide/ptq_introduction/quantization_w_accuracy_control.md
docs/optimization_guide/nncf/ptq/code/ptq_aa_openvino.py
docs/optimization_guide/nncf/ptq/code/ptq_onnx.py
docs/optimization_guide/nncf/ptq/code/ptq_tensorflow.py
docs/optimization_guide/nncf/ptq/code/ptq_torch.py

- *item1*
- *...*
- *ticket-id*

[DOCS] Port optimization doc changes to release docs

---

src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_softplus.py

- *Support aten::softplus*
- *None*

[PT FE] Support aten::softplus

---

src/frontends/pytorch/src/op/rand.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_rand.py
tests/model_hub_tests/torch_tests/requirements.txt
tests/model_hub_tests/torch_tests/test_gfpgan.py

- *Add support for GFPGAN model*
- *Support aten::normal, aten::normal_*
- *None*

[PT FE] Add support for GFPGAN model

---

src/plugins/auto/src/plugin.cpp
src/plugins/auto_batch/src/plugin.cpp
src/plugins/intel_cpu/src/plugin.cpp

- Fix some scan coverity issues
- *ticket-id*

[Fixing]Fix some scan coverity issues

---

.github/workflows/linux_riscv.yml

- *item1*
- *...*
- *ticket-id*

[GHA] Changed risc-v cache dir

---

src/frontends/common/include/openvino/frontend/complex_type_mark.hpp
src/frontends/tensorflow_common/include/helper_ops/complex_type_mark.hpp

**Details:** Move ComplexTypeMark into common frontend. PT FE can use for direct support of complex tensors.

[Common Frontend] Move ComplexTypeMark into common frontend

---

src/plugins/intel_gpu/src/plugin/ops/gather.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp

- *Support negative indice value for static shape*
- *...*
- *122745*

[GPU] Support negative indice for static

---

docs/articles_en/openvino_workflow/model_optimization_guide.rst

- *item1*
- *...*
- CVS-124578

[DOCS] Fix wording

---

.github/workflows/cleanup_pip_cache.yml

Updated 2-cores runner name
- *ticket-id*

[GHA] Updated 2-cores runner name

---

src/common/transformations/include/transformations/symbolic_transformations/dereshape_matmul.hpp
src/common/transformations/src/transformations/symbolic_transformations/dereshape_matmul.cpp
src/common/transformations/src/transformations/symbolic_transformations/symbolic_optimizations.cpp
src/common/transformations/tests/symbolic_transformations/dereshape_fullyconnected.cpp

- *Implements transformation for DeReshaping of FullyConnected*
- *CVS-125855*

[Symbolic Transformation] DeReshape FullyConnected

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- Partly reverted fix from #20924 which introduce regression in CI (The new cache will never be created)
- *ticket-id*

[GHA] Fixed initial cache creation

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/ctc_greedy_decoder.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/ctc_greedy_decoder_seq_len.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/ctc_loss.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/cum_sum.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/custom_op_internal_dyn.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/deformable_convolution.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/depth_to_space.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/detection_output.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/embedding_bag_offsets_sum.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/embedding_bag_packed_sum.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/embedding_segments_sum.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/extract_image_patches.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/eye.cpp
src/plugins/intel_cpu/tests/functional/single_layer_tests/fake_quantize.cpp

- migrate single layer test cases to be API 2.0 - part 3
- *...*
- *ticket-id*

[CPU tests] migrate single layer test cases to be API 2.0 - part 3

---

src/frontends/tensorflow/src/op/placeholder.cpp
src/frontends/tensorflow/src/op/var_handle.cpp

**Details:** Clean-up translator for Placeholder
**Ticket:** 109538

[TF FE] Avoid reinterpret_cast for non-standard types

---

tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_conv_lstm_2d.py

**Details:** Switch on ConvLSTM2D layer tests in pre-commit
**Ticket:** 108786

[TF FE] Switch on ConvLSTM2D layer tests in pre-commit

---

src/frontends/pytorch/src/frontend.cpp
src/frontends/pytorch/src/transforms/prim_unpack_parameter_replacer.cpp
src/frontends/pytorch/src/transforms/prim_unpack_parameter_replacer.hpp
tests/layer_tests/pytorch_tests/test_listunpack.py

- *Unroll lists in a same way as tuples when on input*
- *None*

[PT FE] Unroll lists in a same way as tuples when on input

---

src/plugins/intel_cpu/src/nodes/generic.cpp
src/plugins/intel_cpu/tests/functional/extension/extension.cpp

- *item1*
- *...*
- CVS-126073

[CPU] Fix XmlModelWithExtensionFromDSO test

---

.github/workflows/linux_conditional_compilation.yml

- *item1*
- *...*
- *ticket-id*

Fixed Linux CC

---

docs/articles_en/learn_openvino.rst

* Removed link and description of API 2.0 Transition in Learn OpenVINO article.
* Added link and description of Generative AI Optimization and Deployment to the article.

[DOCS] Update of Learn OpenVINO article for master

---

src/common/transformations/src/transformations/common_optimizations/convert_quantize_dequantize.cpp
src/frontends/onnx/frontend/src/op/dequantize_linear.cpp
src/frontends/onnx/frontend/src/op/quantize_linear.cpp
src/frontends/onnx/frontend/src/ops_bridge.cpp
src/frontends/onnx/tests/models/dequantize_linear_u16.prototxt
src/frontends/onnx/tests/models/quantize_linear_u16.prototxt
src/frontends/onnx/tests/onnx_import_quant.in.cpp

- Verification
- Adding support for int16/uint16 in ConvertQuantizeDequantize transformation
- CVS-126167

[ONNX] QDQ uint16 support

---

.github/workflows/job_python_unit_tests.yml
.github/workflows/windows.yml

[GHA] Add Smart CI to Windows pipeline

---

src/inference/src/os/cpu_map_info.hpp
src/inference/src/os/mac/mac_system_conf.cpp
src/inference/tests/unit/cpu_map_parser/parser_macos.cpp

- *update parse_processor_info_macos for macOS ver 11*
- *ticket-id*

update parse_processor_info_macos for macOS ver 11

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- Add callback function for MarkDequantizationSubgraph pass to skip non FC-related subgraphs
- 126784

[GPU] Add callback function for MarkDequantizationSubgraph pass to skip non FC-related subgraphs

---

.github/workflows/linux_arm64.yml
.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

- CPU tests were fixed in another PR before, so need to include to the list of required jobs

Add CPU tests as required for Linux arm64

---

src/plugins/intel_cpu/tests/functional/test_utils/arm/filter_cpu_info.cpp

- https://github.com/openvinotoolkit/openvino/pull/18061#discussion_r1419535404
- *ticket-id*

[CPU][ARM] Disable `gemm_acl` on 32-bit arm platforms

---

src/plugins/intel_cpu/tests/functional/test_utils/arm/filter_cpu_info.cpp

Comment fix for https://github.com/openvinotoolkit/openvino/pull/21551

[CPU][ARM] Disable gemm_acl on 32-bit arm platforms (comment fix)

---

src/frontends/pytorch/src/op/lstm.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_lstm.py
tests/model_hub_tests/torch_tests/hf_transformers_models
tests/model_hub_tests/torch_tests/test_timm.py
tests/model_hub_tests/torch_tests/test_torchbench.py
tests/model_hub_tests/torch_tests/timm_models
tests/model_hub_tests/torch_tests/torchbench_models

- *Support aten::lstm, aten::gru and aten::rnn_{relu,tanh} operations*
- *101064*

Support aten::lstm, aten::gru and aten::rnn_{relu,tanh} operations

---

src/frontends/pytorch/src/op/square.cpp
tests/layer_tests/pytorch_tests/test_square.py

- *Fix constant type in aten::square*
- *None*

[PT FE] Fix constant type in aten::square

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/src/graph/include/program_dump_graph.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp

`-filenaming: cldnn_program_exec_{network_id}_{program_id}_{iter}.graph`
-delete filter
- 125771

[GPU] dump graphs during execution

---

src/plugins/intel_gpu/src/graph/loop.cpp

- *item1*
- *...*
- CVS-124378

[GPU] bugfix optimized slice_mem

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/logical.cpp

- Migrate logical test to 2.0
- *...*
- *ticket-id*

[CPU tests] migrate single layer test about logical

---

.github/workflows/coverity.yml

- This PR introduces the Coverity pipeline adapted from [the existing Azure pipeline](https://github.com/openvinotoolkit/openvino/blob/master/.ci/azure/linux_coverity.yml).
It is set up to run on a post-commit basis.
The run was successful in the private repository, feel free to ask for details.
- *123587*

[CI] [GHA] Introduce Coverity pipeline

---

src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h

- Fix _-Winconsistent-missing-override_ build error 
- 127266

[GPU] Add missed override keyword in typed_primitive_onednn_impl struct

---

src/bindings/python/src/openvino/runtime/opset1/ops.py
src/bindings/python/tests/test_graph/test_basic.py

- Type as argument for convert op
- CVS-127091

[PyOV] support Type as arg in convert op

---

src/frontends/pytorch/src/transforms/aten_index_put_replacer.cpp

- *item1*
- *...*
- *ticket-id*

[PT FE]: fix aten::index_put type alignmnet

---

src/frontends/pytorch/src/op/erfc.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_erfc.py

Support aten::erfc op (https://pytorch.org/docs/stable/special.html#torch.special.erfc) for Pytorch in OpenVino.
- Closes #20577

support pytorch efrc op

---

.github/workflows/android_arm64.yml
.github/workflows/cleanup_pip_cache.yml
.github/workflows/fedora.yml
.github/workflows/linux.yml
.github/workflows/linux_arm64.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/linux_riscv.yml
.github/workflows/webassembly.yml

This PR changes mount directory to include all the shares we use for AKS runners

[workflows] Change volumes path to a more generic one

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- *Temporary enable GroupNormalizationDecomposition transformation due to poor performance on bulk inputs*
- *CVS-124280*

[GPU] Enable GroupNormalizationDecomposition transformation

---

src/frontends/pytorch/src/op/pow.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_pow.py

- *Support aten::pow_*
- *None*

[PT FE] Support aten::pow_

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp

- Added dynamic padding support for gemm_tiled_opt kernel
- Changed jitter code generation for cases "static dimension + dynamic padding"
- *ticket-id*

[GPU] Add dynamic padding support to gemm_tiled_opt kernel

---

docs/articles_en/get_started/installing-openvino-overview/installing-openvino-shared/installing-openvino-conan.rst

Escape pip command with apostrophe

---

src/common/transformations/src/transformations/common_optimizations/shared_ops_optimization.cpp
src/common/transformations/tests/common_optimizations/shared_ops_optimization.cpp

- *Enables SharedOpOptimization for v1 and v3 Broadcasts*
- *Verbal request from @vladimir-paramuzov*

Enables SharedOpOptimization for v1 and v3 Broadcasts

---

src/frontends/onnx/tests/conversion.cpp
src/frontends/onnx/tests/convert_partially_tests.cpp
src/frontends/onnx/tests/convert_tests.cpp
src/frontends/onnx/tests/load_from.cpp
src/frontends/onnx/tests/model_support_tests.cpp

- Refactoring tests using API 2.0
- 111368

[ONNX] Refactoring tests on API 2.0

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

[GPU] Using a cpu impl type for NMS in a dynamic case

---

.github/workflows/windows.yml

- Changed runner and enabled parallel test execution
- Enabled pip cache
- Removed installation of the same requirements 
- *ticket-id*

[GHA] Windows pytest optimizations

---

docs/articles_en/get_started/configurations-header/configurations-for-intel-npu.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/NPU.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/config_properties.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino/inference_modes_overview/auto_device_selection.rst
docs/sphinx_setup/_static/images/ov_homepage_diagram.png

Populate NPU articles with content for 23.3 and previous releases

[DOCS] NPU articles

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/tests/unit/test_cases/reorder_gpu_test.cpp

- *Skip remove reorder in case it has padding for output*
- *122082*

[GPU] Skip remove reorder in case it has padding for output

---

src/plugins/intel_gpu/src/graph/concatenation.cpp
src/plugins/intel_gpu/src/graph/strided_slice.cpp
src/plugins/intel_gpu/tests/unit/test_cases/strided_slice_gpu_test.cpp

- *The output shape size should be scaled according to new_axis_mask and shrink_axis_mask*
- *This solution applies only to the case of dynamic shape*
- *125328*

[GPU] fix strided_slice axis in case of dynamic shape

---

src/plugins/auto/src/plugin.cpp
src/plugins/auto/src/plugin_config.hpp
src/plugins/auto_batch/src/plugin.cpp

[AUTO Plugin] Coverity issue about the performance inefficiencies

---

src/plugins/auto/src/auto_compiled_model.cpp
src/plugins/hetero/src/compiled_model.cpp
src/plugins/intel_cpu/src/compiled_model.h
src/plugins/intel_gpu/include/intel_gpu/plugin/compiled_model.hpp

- Change exception message for CompiledModel::set_property
- [CVS-89628](https://jira.devtools.intel.com/browse/CVS-89628)

Change exception message for CompiledModel::set_property

---

src/frontends/tensorflow_lite/tests/test_models/gen_scripts/generate_pose_detector.py
src/frontends/tensorflow_lite/tests/test_models/gen_wrapper.py

- Allows failing gen_script in case it should stop build
- N/A

[TFLite] Allows failing when model isn't generated

---

src/frontends/tensorflow_lite/tests/test_models/gen_scripts/generate_bad_header.py

- Fixed message when building test models about conversion string to binary
- N/A

[TFLite] Fixed message about binary data

---

.github/workflows/windows_conditional_compilation.yml

- *item1*
- *...*
- *ticket-id*

Enable Windows CC in precommit

---

.github/workflows/job_cxx_unit_tests.yml
.github/workflows/linux_conditional_compilation.yml

- *item1*
- *...*
- *ticket-id*

Added smart CI condition for PDPD tests

---

src/frontends/tensorflow_lite/tests/test_models/gen_scripts/generate_pose_detector.py
src/frontends/tensorflow_lite/tests/test_models/gen_wrapper.py

Reverts openvinotoolkit/openvino#21621

Revert "[TFLite] Allows failing when model isn't generated"

---

src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/unique_with_counts.cpp
tests/layer_tests/tensorflow_tests/test_tf_UniqueWithCounts.py

Extend UniqueWithCounts (https://www.tensorflow.org/api_docs/python/tf/raw_ops/UniqueWithCounts) operator for OpenVino TF FE.
- Closes #20618

support UniqueWithCounts for TF FE

---

tests/model_hub_tests/torch_tests/hf_transformers_models
tests/model_hub_tests/torch_tests/test_hf_transformers.py

- resolved skipped HF tests: 3rd batch
- [CVS-124981](https://jira.devtools.intel.com/browse/CVS-124981)

[tests] resolves skipped HF tests: 3rd batch

---

.github/workflows/build_doc.yml
.github/workflows/fedora.yml
.github/workflows/job_cpu_functional_tests.yml
.github/workflows/job_cxx_unit_tests.yml
.github/workflows/job_debian_packages.yml
.github/workflows/job_onnx_runtime.yml
.github/workflows/job_python_unit_tests.yml
.github/workflows/job_pytorch_models_tests.yml
.github/workflows/job_samples_tests.yml
.github/workflows/job_tensorflow_hub_models_tests.yml
.github/workflows/linux.yml
.github/workflows/linux_arm64.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/mac.yml
.github/workflows/mac_arm64.yml
.github/workflows/py_checks.yml
.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

- Combination of https://github.com/openvinotoolkit/openvino/pull/21682 and https://github.com/openvinotoolkit/openvino/pull/21683, because versions must be updated together

Updated versions for upload / download artifacts actions

---

.github/workflows/windows_conditional_compilation.yml

- Preparation to include to required workflows

Enabled smart CI for Win CC

---

docs/dev/github_actions/smart_ci.md

This is going to be a part of the general GHA documentation (see https://github.com/openvinotoolkit/openvino/pull/20845), so I placed the file to the same folder as in this PR
- 127097

Add doc file for Smart CI

---

.github/workflows/job_onnx_models_tests.yml

- Fixed issue with downloading artifacts
- 127813

[CI][GHA] Fix for ONNX Models Tests

---

src/common/transformations/src/transformations/convert_precision.cpp

[Transformations] Support precision conversion for PriorBox

---

docs/CMakeLists.txt
docs/nbdoc/nbdoc.py

Fixing path to notebooks sections files.

[DOCS] Fix notebooks sections in menu

---

src/bindings/python/src/openvino/runtime/opset13/ops.py
src/bindings/python/tests/test_graph/test_constant.py
src/bindings/python/tests/test_transformations/test_compression_4bit.py

- Align to legacy behavior.
- *N/A* per request of @mitruska

[PyOV] Remove restrictions on opset13.constant to align with opset1-12

---

src/plugins/intel_cpu/src/nodes/reorder.cpp

- *item1*
- *...*
- *ticket-id*

[CPU][ARM] Fix build CPU ARM plugin

---

docs/articles_en/documentation/openvino_ir/operation_sets/operations_specifications/sequence/ScaledDotProductAttention.rst

- Explicitly mention broadcasting ability
- Include examples for broadcasting of batch dimensions
- Improve clarity
- 126325

[SPEC] Update ScaledDotProductAttention specification for broadcasting of batch dimensions

---

src/common/transformations/include/transformations/common_optimizations/lstm_cell_fusion.hpp
src/common/transformations/src/transformations/common_optimizations/lstm_cell_fusion.cpp
src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/tests/common_optimizations/lstm_cell_fusion.cpp

Partially fixes: CVS-125605 CVS-123630

Add LSTMCellFusion transformation

---

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_shape_of_subgraphs.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/register.cpp
src/plugins/intel_gpu/src/graph/impls/cpu/register.hpp
src/plugins/intel_gpu/src/graph/impls/cpu/select.cpp
src/plugins/intel_gpu/tests/unit/test_cases/select_gpu_test.cpp

- Include Select node to shape_of sub-graph and add CPU impl to avoid runtime synchronizations
- *ticket-id*

[GPU] Include Select node to shape_of sub-graph and add CPU impl to avoid runtime synchronizations

---

src/plugins/intel_gpu/src/graph/loop.cpp

- fix in slice_mem in loop
- CVS-126546

[GPU] bugfix slice mem calculation for batch iteration

---

src/core/reference/src/op/einsum.cpp
src/core/src/op/mvn.cpp

Fix Coverity issues:
- 1529136
- 1529124
- [CVS-127450](https://jira.devtools.intel.com/browse/CVS-127450)
- [CVS-127447](https://jira.devtools.intel.com/browse/CVS-127447)

Fix Coverity CID 1529136, 1529124

---

src/common/util/include/openvino/util/common_util.hpp
src/common/util/src/common_util.cpp
src/frontends/tensorflow/src/frontend.cpp
src/tests/test_utils/common_test_utils/tests/utils_tests.cpp

Description: 
Added error_info event to TF FE.
Ticket: CVS-98737,  CVS-105173
Code:
Validation:
Documentation:

[TF FE] [Telemetry] Added error_info event to TF FE.

---

src/core/src/model.cpp

- Fix for CID 1529130 
- [CVS-127449](https://jira.devtools.intel.com/browse/CVS-127449)

Fix Coverity CID 1529130 

---

docs/articles_en/openvino_workflow/openvino_intro/Device_Plugins/GPU.md

Port from https://github.com/openvinotoolkit/openvino/pull/21623
JIRA: 125613
Adding note about an issue with bad accuracy on GPU.

[DOCS] Troubleshooting note for WINOGRAD convolutions in GPU for 23.2

---

src/bindings/python/src/pyopenvino/core/common.cpp
src/bindings/python/tests/test_runtime/test_tensor_string.py

- Allow replacing of invalid bytes when converting to Python string.
- per request from @slyalin

[PyOV] Allow replacing of invalid bytes in string-based data

---

.github/workflows/build_doc.yml
.github/workflows/fedora.yml
.github/workflows/job_cpu_functional_tests.yml
.github/workflows/job_cxx_unit_tests.yml
.github/workflows/job_debian_packages.yml
.github/workflows/job_onnx_models_tests.yml
.github/workflows/job_onnx_runtime.yml
.github/workflows/job_python_unit_tests.yml
.github/workflows/job_pytorch_models_tests.yml
.github/workflows/job_samples_tests.yml
.github/workflows/job_tensorflow_hub_models_tests.yml
.github/workflows/linux.yml
.github/workflows/linux_arm64.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/mac.yml
.github/workflows/mac_arm64.yml
.github/workflows/py_checks.yml
.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

- Reason https://github.com/actions/download-artifact/issues/249

Downgrade GHA for upload / download back to @v3

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/analyze_confomance_fails.py

- *fix broken xlsx, if no content found, file will not be created*
- *ticket-id*

[apiConformance] Fix checks for finding logs in analyze_confomance_fails

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- Revert changes related to MarkDequantizationSubgraph passes order
- Apply callback only for non-quantized models
- 127933

[GPU] Revert transformation changes

---

src/bindings/js/node/CMakeLists.txt
thirdparty/onnx/CMakeLists.txt

- Fix for https://openvino-ci.toolbox.iotg.sclab.intel.com/blue/organizations/jenkins/private-ci%2Fie%2Fbuild-linux-debian_9_arm/detail/build-linux-debian_9_arm/122753/pipeline/
- CVS-128023
- CVS-128022

Fixed debian9 ARM for C++17 issue

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/base/ov_subgraph.hpp
src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
src/tests/test_utils/functional_test_utils/layer_tests_summary/conformance_helper_tools/conformance_vs_accuracy_comparator.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

Reverts openvinotoolkit/openvino#21347
After this PR being merged, we have issues with macos arm64 https://openvino-ci.toolbox.iotg.sclab.intel.com/blue/organizations/jenkins/private-ci%2Fie%2Fie-tests-linux-macos_arm64-cpu/detail/ie-tests-linux-macos_arm64-cpu/2192/pipeline

Revert "Accuracy collect statistic "

---

docs/articles_en/learn_openvino/tutorials.rst
docs/articles_en/learn_openvino/tutorials/notebooks_section_0.rst
docs/articles_en/learn_openvino/tutorials/notebooks_section_1.rst
docs/articles_en/learn_openvino/tutorials/notebooks_section_2.rst
docs/articles_en/learn_openvino/tutorials/notebooks_section_4.rst

Adding refurbished images as thumbnails for notebooks.

[DOCS] Updating thumbnails for notebooks

---

.github/workflows/coverity.yml
.github/workflows/linux.yml
.github/workflows/linux_arm64.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

- *item1*
- *...*
- *ticket-id*

Switched GHA branches to 2023.3

---

docs/articles_en/learn_openvino/tutorials.md
docs/articles_en/learn_openvino/tutorials/notebooks_section_0.md
docs/articles_en/learn_openvino/tutorials/notebooks_section_1.md
docs/articles_en/learn_openvino/tutorials/notebooks_section_2.md
docs/articles_en/learn_openvino/tutorials/notebooks_section_4.md

Adding refurbished images as thumbnails for notebooks.
Porting:  https://github.com/openvinotoolkit/openvino/pull/21781

{DOCS] Updating thumbnails for notebooks for 23.2

---

.github/CODEOWNERS
.github/components.yml
.github/labeler.yml

- *item1*
- *...*
- *ticket-id*

[JS OV] Specify JS API GitHub config

---

.github/workflows/windows.yml

- *item1*
- *...*
- *ticket-id*

Fixed GHA Windows workflow

---

docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api.rst
docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/Troubleshooting_ReshapeMethod.rst
docs/articles_en/openvino_workflow/model_preparation/setting_input_shapes.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino/ShapeInference.rst

Porting: https://github.com/openvinotoolkit/openvino/pull/21819

[DOCS] Move Troubleshooting Reshape article to legacy section

---

src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend.py
src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend_utils.py
src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/compile.py

- Fixed minor bugs in input validation for torch.compile options
- Ported https://github.com/openvinotoolkit/openvino/pull/21787
- *ticket-id*

Fixed a bug in input validation for torch.compile options

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Currently, we perform cloning of dynamic impl for every shape change, despite the facts that `_dynamic_impl ` already was cloned during primitive instance initialization and unique for each primitive instance. So, this PR implements swap mechanism instead of cloning - this allows to greatly reduce number of clone() calls
- *ticket-id*

[GPU] Reduce unnecessary dynamic impls cloning

---

src/frontends/tensorflow/docs/supported_ops.md

**Details:** 
- Atan2 was provided in https://github.com/openvinotoolkit/openvino/pull/21076
- MulNoNan - https://github.com/openvinotoolkit/openvino/pull/21459
- TensorListConcatV2 - https://github.com/openvinotoolkit/openvino/pull/21477
- UniqueWithCounts - https://github.com/openvinotoolkit/openvino/pull/21565

[TF FE] Document new supported operations

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration.hpp

- upgrade LoadNetworkActualWithThrow
- *...*
- *ticket-id*

[CPU Plugin][Func Test] upgrade LoadNetworkActualWithThrow to 2.0

---

src/frontends/pytorch/src/op/expand.cpp
src/frontends/pytorch/src/transforms/listconstruct_replacer.cpp

- *Optimizes Expand operation translator. [Link](https://pytorch.org/docs/stable/generated/torch.Tensor.expand.html) to operator specification*
- *Layer tests are already put in place for expand*
- *Contributes to LLM simplification and optimization*

Pytorch expand optimized

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/src/graph/concatenation.cpp
src/plugins/intel_gpu/src/graph/include/non_max_suppression_inst.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/runtime/memory.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.hpp

- Replace shared ptrs with raw ptrs in primitive_inst internal containers to avoid circular shared ptr dependencies
- Improve memory usage tracking to better handle buffer sharing case
- *122429*

[GPU] Memory usage and tracking fix

---

src/frontends/tensorflow_common/src/op/interpolate.cpp
tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_upsampling2d.py

**Details:** Extend Upsampling2D support for more input types: int16, uint16. And test more input types.
**Ticket:** https://github.com/openvinotoolkit/openvino/issues/20838

[TF FE][GitHub issue] Extend Upsampling2D support for more input types

---

src/plugins/intel_cpu/tools/commit_slider/README.md
src/plugins/intel_cpu/tools/commit_slider/commit_slider.py
src/plugins/intel_cpu/tools/commit_slider/utils/cfg.json
src/plugins/intel_cpu/tools/commit_slider/utils/common_mode.py
src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py
src/plugins/intel_cpu/tools/commit_slider/utils/modes.py

- *item1*
- *...*
- *ticket-id*

[Commit slider] Apppaths cashing

---

docs/articles_en/documentation/openvino_legacy_features.rst
docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/supported_model_formats.rst
docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/supported_model_formats/convert_model_tutorials/Convert_FaceNet_From_Tensorflow.rst
docs/articles_en/learn_openvino.rst
docs/articles_en/openvino_workflow.rst
docs/articles_en/openvino_workflow/model_preparation.rst
docs/articles_en/openvino_workflow/model_preparation/Convert_Model_IR.rst
docs/articles_en/openvino_workflow/model_preparation/conversion_parameters.rst
docs/articles_en/openvino_workflow/model_preparation/pytorch_vision.rst
docs/articles_en/openvino_workflow/model_preparation_tensorflow_pytorch_guide.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino.rst
docs/home.rst
docs/sphinx_setup/_static/images/img/import_pytorch.svg
docs/sphinx_setup/_static/images/img/import_tensorflow.svg
docs/sphinx_setup/_static/images/import_pytorch.svg
docs/sphinx_setup/_static/images/import_tensorflow.svg

Port from https://github.com/openvinotoolkit/openvino/pull/21815

[DOCS] PT and TF tutorial for 23.3

---

src/frontends/onnx/tests/__init__.py
src/frontends/onnx/tests/tests_python/test_backend.py

- *item1*
- *...*
- https://jira.devtools.intel.com/browse/CVS-124587

[CI] disable backend test - CVS-124587

---

src/inference/src/dev/core_impl.cpp

- Clean up cache and avoid processing of empty properties
- *...*
- [CVS-120574](https://jira.devtools.intel.com/browse/CVS-120574)

[Core] Fix proxy cache for 2 GPUs

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp

- If input shape of shape of is not changed, its subgraph's results are not changed too.
- CVS-128344

[GPU] Skip shape of subgraph if shape is not changed

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- *Fix for BERTmini and FinBERT models*

[GPU] Fix missed set_arguments() call for static inst (#21664)

---

src/plugins/intel_gpu/src/graph/graph_optimizer/dynamic_shape_gather_opts.cpp

[GPU] Small fix for dynamic_shape_gather_opts pass (#21807)

---

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp
src/plugins/intel_gpu/src/plugin/common_utils.cpp
src/plugins/intel_gpu/src/plugin/variable_state.cpp
src/plugins/intel_gpu/tests/functional/behavior/infer_request.cpp

- Add an ability to convert precision on set_state() call

[GPU] Fix set_state() when precision conversion is needed

---

src/frontends/pytorch/README.md

- *Add guide how to debug accuracy issues in th model*
- *None*

[PT FE] Add guide how to debug accuracy issues in th model

---

tests/model_hub_tests/torch_tests/test_hf_transformers.py
tests/model_hub_tests/torch_tests/test_timm.py
tests/model_hub_tests/torch_tests/timm_models
tests/model_hub_tests/torch_tests/torchbench_models

- *Prioritize smaller models when filtering timm models: should fix issues with timeout*
- *Fix bart model, which requires new attribute*
- *None*

[PT FE] Filter timm models prio smaller, adjust models failed in nightly

---

tests/model_hub_tests/tf_hub_tests/nightly_models

**Details:** Mark up tests failing with error "No signature found"

[TF Hub] Mark up tests failing with error "No signature found"

---

tests/model_hub_tests/tf_hub_tests/nightly_models

**Details:** Markup models failing due to inference results mismatch

[TF Hub] Markup models failing due to inference results mismatch

---

src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/src/edge.h
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/graph.h
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/graph_optimizer.h
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/tests/unit/graph/merge_transpose_reorder_test.cpp
src/plugins/intel_cpu/tests/unit/nodes/reorder_node_test.cpp

such as nodes / edges addition and removal
- use std algorithms where possible
- remove duplication and unnecessary calls 
This is a first part of the planning changes.
The second part would be rethinking the DropNode() method usage

[CPU] Refactor graph transformations interface

---

src/plugins/intel_cpu/src/graph.cpp

[CPU] Fix ARM build

---

src/plugins/intel_gpu/src/graph/loop.cpp

- *Fix concat / slicing memory calculation issue*
- *114920*

calculate concat/slicing using output layout instead of layout in memory

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp

- GPU fix for release branch https://github.com/openvinotoolkit/openvino/pull/21955
- *...*
- CVS-128111

Fix minus axis case for kv cache primitive buffer fusing

---

tests/model_hub_tests/tf_hub_tests/nightly_models

**Details:** Markup models failing with error "Model references undeclared parameters"

[TF Hub] Markup models failing with error "Model references undeclared parameters"

---

cmake/developer_package/ncc_naming_style/openvino.style
src/frontends/onnx/frontend/include/onnx_import/core/null_node.hpp
src/frontends/onnx/frontend/src/core/graph_cache.cpp
src/frontends/onnx/frontend/src/core/graph_cache.hpp
src/frontends/onnx/frontend/src/op/aten.cpp
src/frontends/onnx/frontend/src/op/clip.cpp
src/frontends/onnx/frontend/src/op/com.microsoft/attention.cpp
src/frontends/onnx/frontend/src/op/com.microsoft/embed_layer_normalization.cpp
src/frontends/onnx/frontend/src/op/com.microsoft/fusedgemm.cpp
src/frontends/onnx/frontend/src/op/constant_of_shape.cpp
src/frontends/onnx/frontend/src/op/conv.cpp
src/frontends/onnx/frontend/src/op/dequantize_linear.cpp
src/frontends/onnx/frontend/src/op/dft.cpp
src/frontends/onnx/frontend/src/op/dropout.cpp
src/frontends/onnx/frontend/src/op/gru.cpp
src/frontends/onnx/frontend/src/op/loop.cpp
src/frontends/onnx/frontend/src/op/lstm.cpp
src/frontends/onnx/frontend/src/op/non_max_suppression.cpp
src/frontends/onnx/frontend/src/op/pad.cpp
src/frontends/onnx/frontend/src/op/qlinear_conv.cpp
src/frontends/onnx/frontend/src/op/resize.cpp
src/frontends/onnx/frontend/src/op/scan.cpp
src/frontends/onnx/frontend/src/op/slice.cpp
src/frontends/onnx/frontend/src/op/stft.cpp
src/frontends/onnx/frontend/src/op/trilu.cpp
src/frontends/onnx/frontend/src/utils/dft.cpp
src/frontends/onnx/frontend/src/utils/onnx_internal.cpp
src/frontends/onnx/frontend/src/utils/recurrent.cpp

- Removed some exported symbols and part of ngraph namespace
- 125501

[ONNX] Frontend refactoring

---

.github/workflows/windows.yml
src/bindings/c/tests/test_model_repo.cpp

- Fix CAPI tests failure issues in Windows.
- 123594

[CAPI] Fix windows issue

---

tests/stress_tests/common/ie_pipelines/pipelines.cpp
tests/stress_tests/common/infer_api/infer_api.cpp
tests/stress_tests/common/infer_api/infer_api.h
tests/stress_tests/memcheck_tests/tests.cpp

- Unlock https://github.com/openvinotoolkit/openvino/pull/21985

Replace legacy config in stress_tests/ with Properties

---

src/frontends/onnx/frontend/src/core/transform.hpp
src/frontends/onnx/frontend/src/ops_bridge.cpp
src/frontends/onnx/tests/models/greater_or_equal_float.prototxt
src/frontends/onnx/tests/models/greater_or_equal_int.prototxt
src/frontends/onnx/tests/onnx_transformations.cpp

- Removed a transformation pipeline
- Changed tests and a supported operations
- N/A

[ONNX] Removed ONNX transformations for Less/GreaterOrEqual

---

docs/articles_en/openvino_workflow/model_preparation/Convert_Model_From_PyTorch.rst

- *Document new behavior for flattening dict at inputs*
- *None*

[DOCS] Describe dict support

---

src/frontends/tensorflow/CMakeLists.txt
src/frontends/tensorflow/docs/check_supported_ops.py
src/frontends/tensorflow/docs/supported_ops.md

**Details:** Check documented supported operations

[TF FE] Check documented supported operations

---

tests/model_hub_tests/tf_hub_tests/nightly_models

**Details:** Mark up models failing with InvalidArgumentError and AttributeError

[TF Hub] Mark up models failing with InvalidArgumentError and AttributeError

---

.github/CODEOWNERS
.github/components.yml
.github/labeler.yml
.github/workflows/linux_arm64.yml

- https://github.com/openvinotoolkit/openvino/pull/21785
- https://github.com/openvinotoolkit/openvino/pull/21798

Ported changes from master to 2023.3

---

src/bindings/c/src/ov_infer_request.cpp

- Ported https://github.com/openvinotoolkit/openvino/pull/22009

[CAPI] fixed ov_infer_request_wait_for return value issue

---

src/bindings/c/README.md
src/bindings/c/docs/api_overview.md
src/bindings/c/src/ov_infer_request.cpp

- ov_infer_request_wait_for return value
- documentation fixing
- *ticket-id*

[CAPI] tiny issues fixings

---

src/plugins/intel_cpu/src/memory_state.cpp
src/plugins/intel_cpu/src/memory_state.h
src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
src/plugins/intel_cpu/src/nodes/scaled_attn.h
src/plugins/intel_cpu/src/transformations/cpu_opset/common/op/sdpa.cpp
src/plugins/intel_cpu/tests/functional/subgraph_tests/src/sdpa_group_beam_search.cpp

- *Support group beam search*
- *...*
- *128111*
- *128815*

[CPU] Support group beam search

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.cpp

- Required for https://github.com/Homebrew/homebrew-core/pull/159190, where latest OpenCL is used

Migrate to OpenCL v2023.12.14

---

README.md

Add link to the Awesome OpenVINO repository to README.md

---

tests/model_hub_tests/tf_hub_tests/nightly_models

**Details:** Mark up models failing with timeout error

[TF Hub] Mark up models failing with timeout error

---

src/plugins/intel_gpu/tests/unit/test_cases/loop_gpu_test.cpp

- Added unit-tests for loop primitive
- CVS-127260

[GPU] Add unit-test for optimized slice_mem for loop primitive

---

src/plugins/intel_cpu/src/compiled_model.cpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_executable_network/properties.cpp
src/plugins/intel_cpu/tests/functional/behavior/ov_plugin/properties.cpp

- *add ov::log::level property*
- *CVS-111342*

[CPU][apiConformance] support  LOG_LEVEL

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.cpp

- Partially ported https://github.com/openvinotoolkit/openvino/pull/22011

Compatibility with newer OpenCL versions

---

src/frontends/onnx/frontend/src/op/com.microsoft/attention.cpp
src/frontends/onnx/frontend/src/op/com.microsoft/bias_gelu.cpp
src/frontends/onnx/frontend/src/op/com.microsoft/embed_layer_normalization.cpp
src/frontends/onnx/frontend/src/op/com.microsoft/fused_conv.cpp
src/frontends/onnx/frontend/src/op/com.microsoft/fusedgemm.cpp
src/frontends/onnx/frontend/src/op/com.microsoft/skip_layer_normalization.cpp

- Refactoring operations in com.microsoft domain
- 125501

[ONNX] Frontend refactoring: operations

---

.github/workflows/mac.yml
.github/workflows/mac_arm64.yml

[OV JS] Activate validation for mac x86

---

docs/dev/ci/github_actions/overview.md
docs/dev/ci/github_actions/reusable_workflows.md
docs/dev/ci/github_actions/runners.md

[GHA] [DOCS] Runners document

---

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_shape_of_subgraphs.cpp
src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp

- Exclude gather_compressed in shape_of subgraph
- 128410

[GPU] Exclude gather_compressed in shape_of subgraph

---

src/bindings/python/src/pyopenvino/graph/ops/if.cpp
src/bindings/python/tests/test_graph/test_if.py

- Add `get_then_body` to If operator.
- Add testcases to validate the change.
- *128682*

[PyOV] Add `get_then_body` to If operator

---

src/bindings/c/tests/ov_infer_request_test.cpp

- porting https://github.com/openvinotoolkit/openvino/pull/22056
- *ticket-id*

[CAPI] port fixing of test timeout issue

---

src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/src/edge.h
src/plugins/intel_cpu/tests/unit/graph/dummy_node.hpp
src/plugins/intel_cpu/tests/unit/graph/resolve_edge_conflicts_test.cpp

- *CPU collect inplace consumers with LOOK_UP case*
- *CVS-126876*

collect inplace consumers with LOOK_UP case

---

src/common/low_precision_transformations/src/mvn.cpp
src/common/low_precision_transformations/tests/mvn_transformation.cpp
src/common/low_precision_transformations/tests/normalize_l2_transformation.cpp

- *[LPT] [GPU] MVN fp16 support fix*
- *CVS-126195*

[LPT] [GPU] MVN fp16 fix

---

tests/model_hub_tests/tf_hub_tests/test_tf_hub_api_notebooks.py

**Details:** Move Notebooks tests to Kaggle links

[TF Hub] Move Notebooks tests to Kaggle links

---

src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/rnn_sequence.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/scatter_elements_update.cpp
src/tests/functional/plugin/shared/include/single_op_tests/scatter_elements_update.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/scatter_elements_update.hpp
src/tests/functional/shared_test_classes/src/single_op/scatter_elements_update.cpp

- *rnn_sequence, scatter_elements_update*
- *CVS-124001*

[GPU] Refactor

---

README.md

**Details:** Update the left Discord link to permanent one

[Discord] Update the left Discord link to permanent one

---

docs/articles_en/learn_openvino/tutorials.rst
docs/nbdoc/consts.py
docs/openvino_sphinx_theme/openvino_sphinx_theme/directives/code.py

Replacing the source for the `Open in Colab` badge image.

[DOCS] Fix images for notebooks

---

src/bindings/c/include/openvino/c/ov_property.h
src/bindings/c/src/ov_property.cpp
src/bindings/python/src/openvino/properties/__init__.py
src/bindings/python/src/openvino/runtime/properties/__init__.py
src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/bindings/python/src/pyopenvino/utils/utils.cpp
src/bindings/python/tests/test_runtime/test_properties.py

- Fixed get_property('CACHE_MODE') call for python api and added named constant for C API
- *129260*

Added missing cache_mode declarations for python and c API

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp

[GPU] New debug config ImplsCacheCapacity

---

src/plugins/intel_gpu/src/plugin/transformations/convert_matmul_to_fc.cpp
src/plugins/intel_gpu/tests/unit/transformations/convert_matmul_to_fc_test.cpp

- This patch fixes incorrect weights input selection in case of weights sharing between FC ops (previously, second and other dependent FC try to use Transpose instead of weights Constant data itself because first FC node modifies graph and inserts additional transpose during applying ConvertMatMulToFullyConnected transformation)
- 129283

[GPU] Fix convert_matmul_to_fc transformation pass for FC weights sharing case

---

docs/articles_en/learn_openvino/tutorials.rst
docs/nbdoc/consts.py
docs/openvino_sphinx_theme/openvino_sphinx_theme/directives/code.py

Replacing the source for the `Open in Colab` badge image.
Porting: https://github.com/openvinotoolkit/openvino/pull/22116

[DOCS] Fix images for notebooks for 23.3

---

.github/components.yml

**Details:** Update MO deps
**Ticket:** 129336

[GHA] Update MO deps

---

cmake/packaging/rpm.cmake
docs/dev/build_linux.md
docs/dev/build_raspbian.md
docs/dev/build_windows.md
src/bindings/python/CMakeLists.txt

- *item1*
- *...*
- *ticket-id*

Updated build docs for Python API

---

cmake/developer_package/OpenVINODeveloperScriptsConfig.cmake
cmake/developer_package/api_validator/api_validator.cmake

- Regression after https://github.com/openvinotoolkit/openvino/pull/16101

Fixed API validator search

---

docs/requirements.txt

- *item1*
- *...*
- *ticket-id*

Fixed GHSA-h5c8-rqwp-cp95

---

src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp

[api conformance] Move log level to optional properties

---

src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

[GPU] Reclaim memory for dynamic shape

---

src/plugins/intel_gpu/src/graph/eltwise.cpp
src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp

- *Add right-alignment for broadcastable check of eltwise NUMPY*
- *128626*

[GPU] Add right-alignment for broadcastable check of eltwise NUMPY

---

tests/model_hub_tests/models_hub_common/test_convert_model.py
tests/model_hub_tests/tf_hub_tests/precommit_models

**Details:** Add testing model with tokenizer to precommit

[TF FE] Add testing model with tokenizer to precommit

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_common.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_event.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_user_event.cpp

- *Add try catch error for expected cl::error to avoid just displaying as segmentation fault*
- *Replace ocl_error with OPENVINO_THORW*
- *124998*

[GPU] Add try catch error for expected cl::error

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *ARM32 bit: test disabling*
- *CVS-128238*

[CPU] [ARM32] bit: test disabling

---

src/common/offline_transformations/src/compress_quantize_weigths.cpp
src/common/transformations/tests/utils/compress_quantize_weights.cpp
src/core/src/op/fake_quantize.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/graph_comparator.hpp
src/tests/test_utils/common_test_utils/include/common_test_utils/ov_test_utils.hpp
src/tests/test_utils/common_test_utils/src/graph_comparator.cpp
src/tests/test_utils/common_test_utils/src/ov_test_utils.cpp

Support bf16 in CompressQuantizeWeights

---

docs/articles_en/openvino_workflow/torch_compile.rst
src/plugins/intel_cpu/src/graph.cpp

Replacing environment variables, as per request in the following ticket: 128406

[DOCS] Updating options for torch.compile

---

src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/graph.h
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/node.h

to simplify and get rid of extra Node class member variables
TODO:
- 129699

[CPU] Reimplement TopologicalSort

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp

- Add runtime concat condition to check  any static padding in non dyn_pad axis
- 117562

[GPU] Avoid runtime concat opt out if static padding exists in non in-axis and non dyn_pad mask

---

src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/caching_tests.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/core_threading_tests.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/properties.cpp
src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/version.cpp

[api conformance] Add version test to conformance

---

tests/model_hub_tests/tf_hub_tests/nightly_models

**Details:** Mark up models failing due to unsupported operations

[TF Hub] Mark up models failing due to unsupported operations

---

tests/model_hub_tests/torch_tests/hf_transformers_models

- uncommented green model: persimmon-8b-base,  tvp-base, pvt-tiny-224 
- CVS-124981

[tests] uncomment persimmon-8b-base,  tvp-base, pvt-tiny-224

---

src/frontends/pytorch/src/transforms/dict_resolver.cpp

- *Add dict key name to tensor name when decomposing*
- *None*

[PT FE] Add dict key name to tensor name when decomposing

---

src/plugins/auto/tests/functional/behavior/auto_func_test.cpp
src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_executable_network/core_integration.cpp
src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_executable_network/exec_network_base.cpp
src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_executable_network/ov_exec_net_import_export.cpp
src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_executable_network/properties.cpp
src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp

- Remove ie_plugin_config.hpp
- Remove "SUPPORTED_CONFIG_KEYS"
- Remove "SUPPORTED_METRICS"
- Remove InferenceEngine::PluginConfigParams
- [CVS-128363](https://jira.devtools.intel.com/browse/CVS-128363)

[AUTO Plugin][Func Test] Clean 1.0 related code in test

---

docs/articles_en/learn_openvino/openvino_samples/hello_classification.rst

Fixes the broken link to the CPP/C API.

[DOCS] Fix reference to CPP C API

---

docs/nbdoc/consts.py
docs/nbdoc/nbdoc.py

Updating Jinja templates that add Binder and Google Colab buttons to the contents of notebooks.
Porting: https://github.com/openvinotoolkit/openvino/pull/21888

[DOCS] Updating templates for Binder and Google Colab buttons for 23.3

---

src/plugins/auto_batch/tests/unit/async_infer_request_test.cpp
src/plugins/auto_batch/tests/unit/compile_model_create_infer_request_test.cpp
src/plugins/auto_batch/tests/unit/compile_model_get_property_test.cpp
src/plugins/auto_batch/tests/unit/compile_model_get_runtime_model_test.cpp
src/plugins/auto_batch/tests/unit/compile_model_set_property_test.cpp
src/plugins/auto_batch/tests/unit/mock_common.hpp
src/plugins/auto_batch/tests/unit/parse_batch_device_test.cpp
src/plugins/auto_batch/tests/unit/parse_meta_device_test.cpp
src/plugins/auto_batch/tests/unit/plugin_compile_model_test.cpp
src/plugins/auto_batch/tests/unit/plugin_get_property_test.cpp
src/plugins/auto_batch/tests/unit/plugin_query_model_test.cpp
src/plugins/auto_batch/tests/unit/plugin_set_property_test.cpp
src/plugins/auto_batch/tests/unit/sync_infer_request_test.cpp

- Remove 1.0 define
- Using 2.0 naming
- Clean code
- *ticket-id*

[AUTO BATCH Plugin][Unite Tests] remove 1.0 properties & using 2.0 property naming

---

src/frontends/onnx/frontend/src/input_model.cpp
src/frontends/onnx/tests/onnx_editor.cpp
src/frontends/onnx/tests/onnx_editor_topological_sort.cpp
src/frontends/onnx/tests/onnx_import_with_editor.in.cpp
src/frontends/onnx/tests/onnx_ops_registration.cpp
src/frontends/onnx/tests/onnx_transformations.cpp
src/frontends/onnx/tests/onnx_utils.cpp
src/frontends/onnx/tests/onnx_utils.hpp

- Updating tests for InputModel instead of ONNXEditor
- 125501

[ONNX] Frontend refactoring: ONNXEditor replacing by InputModel

---

src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Refactored update_shape_info part
- Make this method virtual to enable customization
- Extract common code for tensor filling.

[GPU] Make update_shape_info_tensor a virtual method

---

docs/articles_en/openvino_workflow/model_optimization_guide/ptq_introduction/quantization_w_accuracy_control.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Port Update quantizing with accuracy control 

---

src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/loop.cpp

- Add dynamic input shape support during iterations in loop body network
- 123865
- 129373
- 129375

[GPU] Add dynamic input shape support in loop body network

---

thirdparty/dependencies.cmake

- Ported patch from https://github.com/conda-forge/openvino-feedstock/pull/64

Ported conda-forge patch to work with latest protobuf

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/serialize.cpp

- remove OPENVINO_SUPPRESS_DEPRECATED_START/END
- CVS-130261

[CPU] remove OPENVINO_SUPPRESS_DEPRECATED_START/END

---

.github/workflows/job_python_unit_tests.yml
.github/workflows/windows.yml
src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
src/bindings/python/src/openvino/frontend/pytorch/utils.py
src/frontends/pytorch/src/node_context.cpp
src/frontends/pytorch/src/op/get_attr.cpp
tests/layer_tests/py_frontend_tests/test_torch_frontend.py

- *Save state_dict names in Constant name*
- *It is not guaranteed that all names will be present and all constants will have same values, because they may be fused. Also if using freezing or scripting names also may be lost.*
- *CVS-129558*

[PT FE] Save state_dict names in Constant name

---

src/inference/tests/functional/ov_core_threading.cpp

- Fix core threading by wait when read model ends on all threads before start next iteration of adding extensions.
- [CVS-130112](https://jira.devtools.intel.com/browse/CVS-130112)

[core][gha] Use second sync point in test to fix core dump

---

.github/workflows/job_cpu_functional_tests.yml

sometimes 20 minutes is not enough 
- CVS-130079

[GHA] increased cpu functional tests timeout

---

docs/articles_en/openvino_workflow/model_optimization_guide/weight_compression.rst

authored by alexander.kozlov@intel.com

[DOCS] Updated weight compression documentation (#22063)

---

.github/workflows/job_cpu_functional_tests.yml

[Merge][GHA] increased cpu functional tests timeout 

---

src/common/util/src/file_util.cpp

- https://github.com/openvinotoolkit/openvino/pull/22271

[Ported] Fix wstring join_paths (#22271)

---

docs/articles_en/get_started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-apt.rst
docs/articles_en/get_started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-from-archive-linux.rst
docs/articles_en/get_started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-yum.rst
docs/articles_en/get_started/installing-openvino-overview/installing-openvino-macos-header/installing-openvino-from-archive-macos.rst
docs/articles_en/get_started/installing-openvino-overview/installing-openvino-shared/installing-openvino-conan.rst
docs/articles_en/get_started/installing-openvino-overview/installing-openvino-shared/installing-openvino-conda.rst
docs/articles_en/get_started/installing-openvino-overview/installing-openvino-windows-header/installing-openvino-from-archive-windows.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Update OV version

---

docs/articles_en/openvino_workflow/running_inference_with_openvino/integrate_with_your_application/model_representation.rst

Removed broken ref links from Model Representation article.

[DOCS] Removing broken links from Model Representation article for 23.3

---

.github/workflows/android_arm64.yml
.github/workflows/coverity.yml
.github/workflows/fedora.yml
.github/workflows/job_onnx_runtime.yml
.github/workflows/linux.yml
.github/workflows/linux_arm64.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/webassembly.yml
.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

Should increase stability in case of networking issues. Will need to track build length more closely to spot major cache I/O issues.

[GHA] Set SCCACHE_IGNORE_SERVER_IO_ERROR

---

src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.h
src/plugins/intel_gpu/src/kernel_selector/kernels/concatenation/concatenation_kernel_base.cpp

- Reduced unnecessary barrier & set arguments
- Calculate flushing timing only considering gpu impls
- *ticket-id*

[GPU] Several optimization to reduce runtime host overhead

---

docs/articles_en/about_openvino/releasenotes_for_openvino.rst
docs/articles_en/about_openvino/system_requirements.rst

update for 23.3 ported from master

[DOCS] releasenotes 23.3 update

---

docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/NPU.rst

Removed leftover sentence from 23.3 update of NPU

[DOCS] Update NPU for 23.3

---

docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins.rst

Fixing records in NPU column for article in 23.3

[DOCS] NPU table fix for 23.3

---

src/inference/dev_api/openvino/runtime/performance_heuristics.hpp
src/plugins/intel_cpu/src/cpu_streams_calculation.cpp

- *update model prefer threads for Ampere*
- *ticket-id*

update model prefer threads for Ampere

---

src/frontends/onnx/frontend/src/core/transform.hpp
src/frontends/onnx/frontend/src/op/gelu.cpp
src/frontends/onnx/frontend/src/op/gelu.hpp
src/frontends/onnx/frontend/src/ops_bridge.cpp
src/frontends/onnx/tests/models/gelu_float.prototxt
src/frontends/onnx/tests/models/gelu_float_tanh.prototxt
src/frontends/onnx/tests/onnx_import.in.cpp

- Added function Gelu-20
- Added com.microsoft.Gelu-1 as an alias for Gelu-20
- 125486, 130329

[ONNX] Extended ONNX Frontend with Function Gelu-20

---

.github/workflows/build_doc.yml

[GHA] Add merge_group trigger for documentation job

---

docs/articles_en/get_started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-from-archive-linux.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Fix nightly link

---

cmake/dependencies.cmake

- *update oneTBB2021.2.4 for MACOS arm64*
- *CVS-130447*

update oneTBB2021.2.4 on macos arm64

---

src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp

- Added check of rank in AlignTransposeOrder.
-

Added check of rank in AlignTransposeOrder.

---

src/plugins/intel_cpu/src/cpu_streams_calculation.cpp

- *update latency configuration for M2 to Pcore only*
- *ticket-id*

update latency configuration for M2

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl
src/plugins/intel_gpu/src/kernel_selector/kernel_base_opencl.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
src/plugins/intel_gpu/src/kernel_selector/primitive_db_gen.py

- Disabled async compilation for int4 FC kernels (except batch_size == 1)
- Added branches to optimized FC int4 compressed kernel for beams num < 8
- 129757

[GPU] Add optimization for FC for beam search and beams number < 8

---

docs/articles_en/about_openvino/performance_benchmarks.rst
docs/articles_en/about_openvino/performance_benchmarks/performance_int8_vs_fp32.rst
docs/sphinx_setup/conf.py

port: https://github.com/openvinotoolkit/openvino/pull/22404

[DOCS] fix link port

---

src/frontends/pytorch/src/op/argmax_argmin.cpp
src/frontends/pytorch/src/op/as_tensor.cpp
src/frontends/pytorch/src/op/norm.cpp
src/frontends/pytorch/src/op/square.cpp
src/frontends/pytorch/src/op/var_mean.cpp
tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py

- *Check shapes in layer tests*
- *None*

[PT FE] Check shapes in layer tests

---

src/frontends/tensorflow/tests/convert_saved_model.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
src/frontends/tensorflow_common/tests/block_lstm_replacer.cpp
src/frontends/tensorflow_common/tests/gru_block_cell_replacer.cpp

**Details:** Remove use of heavy opset header in unit-tests

[TF FE] Remove use of heavy opset header in unit-tests

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Fix crash when _dynamic_impl is nullptr 
- 130910

[GPU] Fix crash when _dynamic_impl is nullptr

---

src/inference/include/openvino/runtime/properties.hpp

- *update description and add behavior example for enable_cpu_pinning*
- *CVS-129650*

[DOC] update description and add behavior example for enable_cpu_pinning

---

.github/workflows/windows_conditional_compilation.yml

This should fix the error:
```
fatal error LNK1102: out of memory
```
during Windows Conditional Compilation builds

[GHA] Run Windows Conditional Compilation on a node with 64 GB RAM

---

src/plugins/auto/tests/functional/shared_tests_instances/behavior/ov_infer_request/memory_states.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/auto_batching_tests.hpp

- AUTO Plugin add memory state tests
- CVS-130014

[AUTO Plugin] add memory_states tests 

---

docs/sphinx_setup/_static/css/banner.css

Docs fixed banner css file

---

src/frontends/tensorflow/src/input_model.cpp
src/frontends/tensorflow/src/op/if.cpp
src/frontends/tensorflow/src/op/iterator.cpp
src/frontends/tensorflow/src/op/queue_dequeue.cpp
src/frontends/tensorflow/src/op/sparse_reshape.cpp
src/frontends/tensorflow/src/op/variable.cpp
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow/src/translate_session.cpp

**Details:** Avoid use of heavy opset header - final part

[TF FE] Avoid use of heavy opset header - final part

---

docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/NPU.rst

Porting: https://github.com/openvinotoolkit/openvino/pull/22498

[DOCS] Fix Ubuntu version in NPU article for 23.3

---

docs/notebooks/106-auto-device-with-output.rst
docs/notebooks/220-cross-lingual-books-alignment-with-output.rst

Porting: https://github.com/openvinotoolkit/openvino/pull/22500

[DOCS] Updating reference to Inference Modes

---

docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/NPU.rst

Updating supported Ubuntu version in the article.

[DOCS] Fix Supported Ubuntu version in NPU Article

---

docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/NPU.rst

Removing the NPU plugin specific (private) properties from the article

[DOCS] Removing NPU plugin specific properties

---

src/frontends/pytorch/src/op/masked_fill.cpp
src/frontends/pytorch/src/transforms/aten_index_put_replacer.cpp
src/frontends/pytorch/src/transforms/aten_index_replacer.cpp
src/frontends/pytorch/src/utils.cpp
src/frontends/pytorch/src/utils.hpp
tests/layer_tests/pytorch_tests/test_index_put_.py

- Fix issue with `aten::index_put_` introduced by #22190 
- *CVS-130228*

[PT FE] Fix aten::index_put for masked_fill case

---

src/frontends/pytorch/src/op/convnd.cpp
src/frontends/pytorch/src/op/convolution.cpp
src/frontends/pytorch/src/op/convolution_mode.cpp
src/frontends/pytorch/src/op/min_max.cpp
src/frontends/pytorch/src/utils.cpp

- *Apply mark_node that was missing*
- *CVS-130915*

[PT FE] Apply mark_node that was missing

---

src/frontends/pytorch/src/op/to.cpp
tests/layer_tests/pytorch_tests/test_to.py

- *Ignore memory_format in aten::to*
- *CVS-130284*

[PT FE] Ignore memory_format in aten::to

---

src/plugins/intel_cpu/tests/functional/single_layer_tests/adaptive_pooling.cpp
src/plugins/intel_gpu/include/intel_gpu/primitives/adaptive_pooling.hpp
src/plugins/intel_gpu/src/graph/adaptive_pooling.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/adaptive_pooling.cpp
src/plugins/intel_gpu/src/graph/include/adaptive_pooling_inst.h
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/adaptive_pooling_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/adaptive_pooling/adaptive_pooling_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/adaptive_pooling/adaptive_pooling_kernel_ref.h
src/plugins/intel_gpu/src/plugin/ops/adaptive_pooling.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/adaptive_pooling.cpp

- AdaptiveAvgPool shape infer implementation
- AdaptiveMaxPool shape infer implementation
- Single layer test for dynamic shape
- 100221

[GPU] Update adaptive_pooling to use nGraph shape inference 

---

src/inference/src/os/win/win_system_conf.cpp

- *return correct socketid and numaid on windows*
- *ticket-id*

return correct socketid and numaid on windows

---

src/plugins/intel_gpu/src/graph/impls/common/wait_for_events.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/kernel_selector/kernel_base_opencl.cpp

- Removed unused primitive_impl methods
- Added missing `KERNEL_ID` undef

[GPU] Add missing undef and remove some outdated code

---

src/bindings/python/src/openvino/runtime/utils/decorators.py
src/bindings/python/tests/test_graph/test_affix_ops.py

- Fix edge-cases for https://github.com/openvinotoolkit/openvino/pull/22327
- *connected to: 131003*

[PyOV] Fix for affix decorator, allow Output instances

---

src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/fetch_weights.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_weights.cl
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.cpp
src/plugins/intel_gpu/src/kernel_selector/tensor_type.cpp
src/plugins/intel_gpu/src/kernel_selector/tensor_type.h
src/plugins/intel_gpu/src/runtime/format.cpp

os_is_zyx_isv8_osv16_isv2 has issue, output incorrect in lnl.
- *130448*

[GPU] Fix wrong weight conversion.

---

docs/articles_en/about_openvino/performance_benchmarks.rst
docs/articles_en/documentation/openvino_extensibility.rst
docs/articles_en/documentation/openvino_extensibility/GPU_Extensibility.rst
docs/articles_en/documentation/openvino_extensibility/add_openvino_ops.rst
docs/articles_en/documentation/openvino_extensibility/openvino_plugin_library/detailed_guides/low_precision_transformations/step2_markup.rst
docs/articles_en/documentation/openvino_extensibility/ov_transformations.rst
docs/articles_en/documentation/openvino_extensibility/ov_transformations/graph_rewrite_pass.rst
docs/articles_en/documentation/openvino_extensibility/ov_transformations/matcher_pass.rst
docs/articles_en/documentation/openvino_extensibility/ov_transformations/model_pass.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/GPU/GPU_RemoteTensor_API.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino/stateful_models_intro/ways_to_get_stateful_model.rst

* Fixed faulty :ref: directives
* Fixed the broken button link in benchmark article
* Fixed the wrong snippet name

[DOCS] Article directives fix for 23.3

---

docs/articles_en/get_started/installing-openvino-overview/installing-openvino-linux-header/installing-openvino-from-archive-linux.rst

port: https://github.com/openvinotoolkit/openvino/pull/22431
* fix nightly link
* change link

[DOCS] Fix nightly link port

---

src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
tests/layer_tests/py_frontend_tests/test_torch_frontend.py

- *Reuse constants obtained with `prim::GetAttr`*
- *CVS-130136*

[PT FE] Reuse constants obtained with prim::GetAttr

---

.github/workflows/windows.yml

We have several occurring errors in Windows and Windows Conditional Compilation workflow, this info should help us to debug them

[GHA] Add debug info to Windows workflow

---

docs/articles_en/documentation/openvino_legacy_features/api_2_0_transition_guide/deployment_migration.rst
docs/articles_en/get_started/installing-openvino-overview/installing-openvino-windows-header/installing-openvino-from-archive-windows.rst

Fixing faulty comment formatting in 23.3

[DOCS] Fixing comment formats in 23.3

---

docs/articles_en/learn_openvino/openvino_samples/bert_benchmark.rst
docs/articles_en/learn_openvino/openvino_samples/hello_classification.rst
docs/articles_en/learn_openvino/openvino_samples/hello_nv12_input_classification.rst
docs/articles_en/learn_openvino/openvino_samples/hello_reshape_ssd.rst
docs/articles_en/learn_openvino/openvino_samples/image_classification_async.rst
docs/articles_en/learn_openvino/openvino_samples/sync_benchmark.rst
docs/articles_en/learn_openvino/openvino_samples/throughput_benchmark.rst

[DOCS] Fixing reference to OMZ articles

---

docs/dev/ci/github_actions/reusable_workflows.md

[GHA] [DOCS] Reusable workflows and workflow organisation document

---

src/common/low_precision_transformations/include/low_precision/layer_transformation.hpp
src/common/low_precision_transformations/include/low_precision/low_precision.hpp
src/common/low_precision_transformations/include/low_precision/quantization_details.hpp
src/common/low_precision_transformations/src/low_precision.cpp
src/common/low_precision_transformations/src/quantization_details.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.h
src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/reshape_transformation.cpp
src/tests/functional/plugin/shared/include/low_precision_transformations/reshape_transformation.hpp
src/tests/functional/plugin/shared/src/low_precision_transformations/reshape_transformation.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/base/low_precision_transformations/layer_transformation.hpp
src/tests/functional/shared_test_classes/src/base/low_precision_transformations/layer_transformation.cpp

- *[CPU] [LPT] CPU limitation*
- tests will be added later
- *CVS-127419*

[CPU] [LPT] CPU limitation

---

src/plugins/intel_gpu/src/graph/include/shape_of_inst.h

- *add get_shape_info_dendencies() to shape_of node*
- *129281*

[GPU] Add get_shape_info_dependencies() to shape_of_node

---

src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/topk.cpp
src/tests/functional/plugin/shared/include/single_op_tests/topk.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/topk.hpp
src/tests/functional/shared_test_classes/src/single_op/topk.cpp

[GPU] Refactor: TopK

---

docs/articles_en/openvino_workflow/model_optimization_guide/ptq_introduction/basic_quantization_flow.rst
docs/dev/build_linux.md
docs/dev/build_windows.md

Fixing typo in NNCF quantize command line. Porting: https://github.com/openvinotoolkit/openvino/pull/21679
Specifying number of parallel jobs in build process. Porting: https://github.com/openvinotoolkit/openvino/pull/22571

[DOCS] Port docs patches for 23.3

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/nodes/deconv.cpp
src/plugins/intel_cpu/src/nodes/reference.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.h

f16-f32 cast brings performance drops: https://github.com/oneapi-src/oneDNN/pull/1588

[CPU][ARM] Disable f16 eltwise fusing

---

docs/sphinx_setup/_static/css/custom.css
docs/sphinx_setup/_static/html/banner_data.json
docs/sphinx_setup/_static/js/hide_banner.js

The change for 2024 version only

DOCS Fixed empty json file on baner load

---

src/frontends/onnx/frontend/CMakeLists.txt

- *item1*
- *...*
- *ticket-id*

Removed API 1.0 ONNX FE headers install

---

src/plugins/auto/src/auto_compiled_model.cpp
src/plugins/auto/tests/unit/compile_model_metric_test.cpp

- Remove redundant code and update the test case.
- 130726

[AUTO plugin] auto minor cleanup 

---

.github/actions/setup_python/action.yml

- Should mitigate things like [`Please select the geographic area in which you live.`](https://github.com/openvinotoolkit/openvino/actions/runs/7743932656/job/21117333861) from `tzdata` when installing Python.

[CI] [GHA] Preinstall `tzdata` and `gpg-agent` packages in the setup Python action

---

.github/workflows/job_onnx_models_tests.yml
src/frontends/onnx/frontend/src/op/acos.hpp
src/frontends/onnx/tests/tests_python/model_zoo_preprocess.ps1
src/frontends/onnx/tests/tests_python/model_zoo_preprocess.sh

[ONNX] Update ONNX models commit for tests

---

.github/workflows/job_cpu_functional_tests.yml
.github/workflows/job_cxx_unit_tests.yml

CPU tests seem to be stable now

[GHA] CPU tests to merge queue validation

---

src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected_primitive.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp

[CPU] Fix sparse compression weights check

---

.github/components.yml
.github/workflows/job_pytorch_models_tests.yml
.github/workflows/job_tensorflow_hub_models_tests.yml
.github/workflows/linux.yml
tests/model_hub_tests/models_hub_common/test_convert_model.py

**Details:** Use openvino-tokenizers in model hub tests.

[GHA][Model Hub Tests] Use openvino-tokenizers in model hub tests

---

src/core/include/openvino/core/descriptor/tensor.hpp
src/core/include/openvino/op/util/convolution_base.hpp
src/core/include/openvino/op/util/max_pool_base.hpp
src/core/src/descriptor/tensor.cpp

- Remove API set_adding_above() 
- Remove API tensor() with name
- *...*
- CVS-106449

[Deprecated API] Remove API set_adding_above() & tensor() with name

---

src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_infer_request/memory_states.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_infer_request/properties_tests.cpp
src/plugins/template/tests/functional/shared_tests_instances/behavior/ov_plugin/hetero_synthetic.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/hetero_synthetic.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/hetero_synthetic.cpp

- Add test instantiations for template plugin
- [CVS-130342](https://jira.devtools.intel.com/browse/CVS-130342)

Add test instantiations for template plugin

---

.github/workflows/linux_riscv.yml

- w/a to cleanup the cache
- *ticket-id*

[GHA] Reset Linux riscv cache

---

src/plugins/intel_gpu/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration_sw.hpp

[GPU] Resolved function test issue.

---

.github/workflows/coverity.yml

As the project has a limited number of daily runs, I suggest merging these changes and verifying them in the next nightly run.

[CI] [GHA] Add logs showing and uploading for Coverity

---

src/plugins/intel_gpu/src/graph/impls/ocl/strided_slice.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/strided_slice.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/common_utils.hpp

- Failed smoke_CLDNN_FP32/StridedSliceLayerTest.Inference/IS=([])_TS={(1.12.100)}_modelType=f32_begin=(0.n6.0)_end=(0.n8.0)_stride=(n1.n2.n1)_begin_m=(1.0.1)_end_m=(1.0.1)_new_axis_m=(0.0.0)_shrink_m=(0.0.0)_ellipsis_m=(0.0.0)_trgDev=GPU
- *...*
- 128235

[GPU] Fix issues from unexecuted func tests

---

src/common/low_precision_transformations/src/layer_transformation.cpp
src/common/low_precision_transformations/src/mat_mul.cpp
src/core/src/node.cpp

- *Dbug info was added for MatMul. Will be extended later.*

[LPT] debug info support

---

src/bindings/python/wheel/setup.py

- Allow to include NPU plugin as part of OpenVINO wheel.
- CVS-130134

Added NPU plugin to wheel

---

cmake/packaging/debian.cmake
cmake/packaging/rpm.cmake

- *item1*
- *...*
- CVS-130134

Don't use NPU in Debian / RPM logic

---

src/frontends/pytorch/src/op/sum.cpp
tests/layer_tests/pytorch_tests/test_sum.py

- *fix accuracy of aten::sum translation for uint8 inputs*
- *update aten::sum support with type and out arguments*
- *CVS-123277*

[PT FE]: fix aten::sum for uint8 input

---

src/plugins/intel_gpu/src/graph/lstm_elt.cpp
src/plugins/intel_gpu/src/plugin/ops/rnn.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/lstmcell.cpp

- *Support dynamic lstm_elt*
- *Support dynamic crop with dynamic reference_input*
- *122739*
- *100238*

[GPU] Support dynamic for LSTMCell

---

src/plugins/intel_gpu/include/intel_gpu/primitives/strided_slice.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/strided_slice_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/strided_slice.cpp
src/plugins/intel_gpu/src/plugin/ops/strided_slice.cpp

- Skip strided slice at runtime if all begin axes are zero, strides are one, end axes are full range
- Update strided slice prim API to get constant begin/end/strides data
- 131094

[GPU] Skip redundant strided slice in stateful model

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_kernel_ref.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gather_gpu_test.cpp

[GPU] Fix of the processing of negative indices in Gather in dynamic case

---

src/core/src/pass/visualize_tree.cpp

- *VisualizeTree fails for some models - fix in PR*

[COMMON] VisualizeTree: constant values reading is more stable

---

src/plugins/intel_cpu/tools/commit_slider/tests/commit_slider_test.py
src/plugins/intel_cpu/tools/commit_slider/tests/test_data.py
src/plugins/intel_cpu/tools/commit_slider/tests/test_util.py
src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/fbv_bm_no_deg_main.cpp
src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/fbv_bm_stable_main.cpp
src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/fbv_bm_unstable_dev_main.cpp
src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/fbv_bm_unstable_main.cpp
src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/tests_res.json
src/plugins/intel_cpu/tools/commit_slider/utils/break_validator.py
src/plugins/intel_cpu/tools/commit_slider/utils/cfg.json
src/plugins/intel_cpu/tools/commit_slider/utils/common_mode.py
src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py
src/plugins/intel_cpu/tools/commit_slider/utils/log_parser.py
src/plugins/intel_cpu/tools/commit_slider/utils/map_builder.py
src/plugins/intel_cpu/tools/commit_slider/utils/modes.py

[Commit slider] Benchmark result validation

---

src/common/low_precision_transformations/src/markup_precisions.cpp
src/common/low_precision_transformations/src/markup_quantization_granularity.cpp
src/common/low_precision_transformations/tests/markup_avg_pool_precisions_transformation.cpp
src/common/low_precision_transformations/tests/simple_low_precision_transformer.cpp
src/common/snippets/src/pass/hash.cpp
src/common/transformations/include/ov_ops/type_relaxed.hpp
src/frontends/paddle/src/frontend.cpp
src/frontends/tests/frontend/shared/gtest_main_manifest/main.cpp
src/tests/test_utils/common_test_utils/src/test_case.cpp

- The suppressions don't suppress deprecated code

Removed useless suppression for deprecation API

---

src/bindings/python/requirements_test.txt

- cherry-picked https://github.com/openvinotoolkit/openvino/pull/22546
- *ticket-id*

remove flake8-commas requirement

---

src/plugins/intel_gpu/src/plugin/ops/strided_slice.cpp

- Fix crash in the case when original constant of end data is i32::INT_MAX and it is converted to a normal bound of int64_t shape type.
- *ticket-id*

[GPU] Fix crash of strided_slice when input shape data is INT_MAX

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- LPT tests relax skiped tests
- 131981

LPT tests relax skiped tests

---

src/plugins/intel_gpu/src/graph/impls/ocl/rms.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_base.h
src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_bfyx_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_bfyx_opt.h
src/plugins/intel_gpu/src/plugin/transformations/rms_fusion.cpp
src/plugins/intel_gpu/src/plugin/transformations/rms_fusion.hpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/unit/transformations/rms_norm_decomposition_test.cpp

- Fix rms not to be fused if the size of target dimemnsion is > WGS
- 131958

[GPU] Fix rms not to be fused if the size of target dimension is > WGS

---

src/frontends/tensorflow/include/openvino/frontend/tensorflow/variable.hpp
src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/tests/convert_tricky_models.cpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_unitialized_variablev2.py
src/frontends/tensorflow/tests/tf_utils.cpp
src/frontends/tensorflow/tests/tf_utils.hpp

**Details:** Report uninitialised variable in case TFVariable remains
**Ticket:** CVS-131589

[TF FE] Report uninitialised variable in case TFVariable remains

---

tests/layer_tests/common/layer_test_class.py
tests/layer_tests/common/utils/common_utils.py
tests/layer_tests/tensorflow_tests/test_tf_Gather.py

**Details:** Update layer tests results comparator to check string tensors. We need this PR for 2024.0 to have LookupTableFindV2 to be validated for string values. It will unblock PR https://github.com/openvinotoolkit/openvino/pull/22679

[TF FE] Support Gather for string tensors

---

src/frontends/pytorch/src/op/all.cpp
tests/layer_tests/pytorch_tests/test_all.py

- *item1*
- *...*
- *ticket-id*

[PT FE]: support boolean input in aten::all

---

src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/permute_slice_n_interpolation.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/permute_slice_n_interpolation.hpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/unit/transformations/permute_slice_n_interpolation.cpp

- *Transformation Slice-Interpolation -> Interpolation-Slice*
- *124854*

[CPU] Slice & Interpolate preprocess optimization

---

docs/sphinx_setup/_static/images/img/subgraphs_dumper_arch_diaram.png
src/tests/functional/plugin/conformance/subgraphs_dumper/include/cache/graph_cache.hpp
src/tests/functional/plugin/conformance/subgraphs_dumper/include/matchers/subgraph/read_value_assign.hpp
src/tests/functional/plugin/conformance/subgraphs_dumper/include/utils/model.hpp
src/tests/functional/plugin/conformance/subgraphs_dumper/src/cache/graph_cache.cpp
src/tests/functional/plugin/conformance/subgraphs_dumper/src/matchers/subgraph/read_value_assign.cpp
src/tests/functional/plugin/conformance/subgraphs_dumper/src/utils/model.cpp
src/tests/functional/plugin/conformance/subgraphs_dumper/tests/base_test.hpp
src/tests/functional/plugin/conformance/subgraphs_dumper/tests/matchers/subgraph/read_value.cpp
src/tests/functional/plugin/conformance/subgraphs_dumper/tests/matchers/subgraph/repeat_pattern.cpp
src/tests/functional/plugin/conformance/subgraphs_dumper/tests/test_models/model_4.hpp
src/tests/functional/plugin/conformance/subgraphs_dumper/tests/test_models/model_5.hpp

- *item1*
- *...*
- *[CVS-129780](https://jira.devtools.intel.com/browse/CVS-129780)*

[ov_subgraphs_dumper] Add read_value_assign extractor

---

src/plugins/intel_gpu/src/plugin/ops/strided_slice.cpp

- Fix LONG_INT to a fixed number of 64bit value so that it does not depend on environement
- CVS-132275

[GPU] Fix LONG_INT to a fixed number of 64bit value 

---

.github/workflows/linux.yml
.github/workflows/windows.yml

- Tokenizers extension has been moved to dedicated rep - https://github.com/openvinotoolkit/openvino_tokenizers
- *ticket-id*

[GHA] Switch tokenizers to public repo

---

.github/workflows/android_arm64.yml
vcpkg.json

- *item1*
- *...*
- *ticket-id*

Fixed vcpkg baseline hash

---

tests/stress_tests/.automation/memleaks_tests/precommit_configs/desktop_test_config.xml

- *item1*
- *...*
- *ticket-id*

Update memleaks config

---

tests/layer_tests/py_frontend_tests/test_torch_frontend.py

- *Test fails sporadically, the test for shared weights do similar testing, but doesn't rely on downloading a model, so this test can be removed.*
- *CVS-131108*

Remove sporadic test

---

src/bindings/python/src/openvino/runtime/properties/__init__.py
src/bindings/python/src/openvino/runtime/properties/hint/__init__.py
src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/bindings/python/tests/test_runtime/test_properties.py
src/inference/include/openvino/runtime/properties.hpp
src/plugins/intel_cpu/src/compiled_model.cpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/config.h
src/plugins/intel_cpu/src/dnnl_postops_composer.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer.h
src/plugins/intel_cpu/src/dnnl_postops_composer_legacy.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer_legacy.h
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected_primitive.cpp
src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected_primitive.hpp
src/plugins/intel_cpu/src/nodes/executors/fullyconnected_config.hpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/gather.cpp
src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/custom/behavior/ov_executable_network/properties.cpp
src/plugins/intel_cpu/tests/functional/custom/behavior/ov_plugin/properties.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/matmul_weights_decompression.cpp

- *This PR adds activations dynamic quantization support for compressed FullyConnected*
- OneDNN PR: https://github.com/openvinotoolkit/oneDNN/pull/229
- *[CVS-128361](https://jira.devtools.intel.com/browse/CVS-128361)*

[CPU] Dynamic quantization for compressed FullyConnected

---

src/frontends/tensorflow/docs/check_supported_ops.py
src/frontends/tensorflow/docs/supported_ops.md

**Details:** Mark new operations with NEW mark. In release notes, we refer this documentation where user can find all NEW operation in the current release.

[TF FE][DOC] Mark new operations with NEW mark

---

src/frontends/tensorflow/docs/check_supported_ops.py
src/frontends/tensorflow/docs/supported_ops.md

**Details:** Mark new operations with NEW mark. In release notes, we refer this documentation where user can find all NEW operation in the current release.

[TF FE][DOC] Mark new operations with NEW mark (#22864)

---

src/common/low_precision_transformations/src/add.cpp
src/common/low_precision_transformations/src/avg_pool.cpp
src/common/low_precision_transformations/src/batch_to_space.cpp
src/common/low_precision_transformations/src/clamp.cpp
src/common/low_precision_transformations/src/concat.cpp
src/common/low_precision_transformations/src/convert.cpp
src/common/low_precision_transformations/src/convolution.cpp
src/common/low_precision_transformations/src/convolution_backprop_data.cpp
src/common/low_precision_transformations/src/fake_quantize_decomposition.cpp
src/common/low_precision_transformations/src/gather.cpp
src/common/low_precision_transformations/src/interpolate.cpp
src/common/low_precision_transformations/src/max_pool.cpp
src/common/low_precision_transformations/src/multiply_partial.cpp
src/common/low_precision_transformations/src/mvn.cpp
src/common/low_precision_transformations/src/normalize_l2.cpp
src/common/low_precision_transformations/src/pad.cpp
src/common/low_precision_transformations/src/prelu.cpp
src/common/low_precision_transformations/src/reduce_base_transformation.cpp
src/common/low_precision_transformations/src/relu.cpp
src/common/low_precision_transformations/src/reshape.cpp
src/common/low_precision_transformations/src/shuffle_channels.cpp
src/common/low_precision_transformations/src/space_to_batch.cpp
src/common/low_precision_transformations/src/split.cpp
src/common/low_precision_transformations/src/squeeze.cpp
src/common/low_precision_transformations/src/strided_slice.cpp
src/common/low_precision_transformations/src/transparent_base_transformation.cpp
src/common/low_precision_transformations/src/transpose.cpp
src/common/low_precision_transformations/src/unsqueeze.cpp

[LPT] Logging

---

src/plugins/intel_cpu/tools/commit_slider/tests/commit_slider_test.py
src/plugins/intel_cpu/tools/commit_slider/tests/test_data.py
src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/fbv_bm_first_fixed_main.cpp
src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/tests_res.json
src/plugins/intel_cpu/tools/commit_slider/utils/break_validator.py
src/plugins/intel_cpu/tools/commit_slider/utils/common_mode.py
src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py
src/plugins/intel_cpu/tools/commit_slider/utils/modes.py

- *item1*
- *...*
- *ticket-id*

[commit slider ] Preparation for AC-integration

---

src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_hadsigmoid.py

- *support aten::hardsigmoid_ (inplace variant)*
enables rtmdet model from mmyolo
- *CVS-132283*

[PT FE]: support aten::hardsigmoid_

---

tests/model_hub_tests/torch_tests/test_hf_transformers.py
tests/model_hub_tests/torch_tests/test_timm.py
tests/model_hub_tests/torch_tests/test_torchbench.py
tests/model_hub_tests/torch_tests/timm_models

- *Update torch models in GHA tests*
- *None*

Update torch models in GHA tests

---

src/bindings/python/src/openvino/__init__.py
src/bindings/python/src/pyopenvino/CMakeLists.txt
src/bindings/python/src/pyopenvino/core/core.cpp
src/bindings/python/src/pyopenvino/core/remote_context.cpp
src/bindings/python/src/pyopenvino/core/remote_context.hpp
src/bindings/python/src/pyopenvino/core/remote_tensor.cpp
src/bindings/python/src/pyopenvino/core/remote_tensor.hpp
src/bindings/python/src/pyopenvino/pyopenvino.cpp
src/bindings/python/src/pyopenvino/utils/utils.cpp
src/bindings/python/src/pyopenvino/utils/utils.hpp
src/bindings/python/tests/test_runtime/test_remote_api.py
tools/benchmark_tool/openvino/__init__.py
tools/mo/openvino/__init__.py
tools/openvino_dev/src/openvino/__init__.py
tools/ovc/openvino/__init__.py

- Port of https://github.com/openvinotoolkit/openvino/pull/22629
- *N/A*

[PyOV] Remote API support for Python

---

src/frontends/pytorch/src/op_table.cpp
tests/model_hub_tests/torch_tests/requirements.txt
tests/model_hub_tests/torch_tests/test_tpsmm.py

- *Add support for `aten::inverse`*
- *Tests: couldn't replicate the operation in layer tests, but it exists in TPSMM model, so test for this model is included*
- *CVS-123613*

[PT FE] Add support for aten::inverse

---

src/bindings/c/docs/api_overview.md
src/core/README.md
src/core/docs/api_details.md
src/core/docs/operation_enabling_flow.md
src/core/docs/tests.md
src/frontends/onnx/docs/tests.md
src/inference/README.md
src/tests/README.md

- Remove some api 1.0 names and mentions from dev docs
- CVS-132237

[DOCS] Remove some api 1.0 names and mentions from dev docs

---

src/plugins/template/tests/functional/subgraph_reference/preprocess_opencv.cpp

- [CVS-131498](https://jira.devtools.intel.com/browse/CVS-131498)
- [CVS-132878](https://jira.devtools.intel.com/browse/CVS-132878)

Restore `PreprocessOpenCVReferenceTest`

---

src/core/reference/include/openvino/reference/topk.hpp

- Reuse template function `U = int64_t` instantiation for `U = int32_t`
- CVS-119222

[core] Optimize TopK reference implementation binary size

---

tests/layer_tests/tensorflow_tests/test_tf_StringLower.py

**Details:** Add layer test for tf.raw_ops.StringLower operation

[TF FE] Add layer test for tf.raw_ops.StringLower operation

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *Port the PR https://github.com/openvinotoolkit/openvino/pull/22889 to the release 2024.0*
- *132849*

[Snippets][CPU][2024.0] Fixed AddressSanitizer: stack-use-after-scope

---

docs/sphinx_setup/_static/js/hide_banner.js
docs/sphinx_setup/_templates/search.html

Port from https://github.com/openvinotoolkit/openvino/pull/22916

DOCS Update banner config for 2024

---

docs/sphinx_setup/conf.py

Version renaming for release 2024

Docs update release version name for 2024

---

docs/articles_en/about-openvino/compatibility-and-support/supported-operations-framework-frontend.rst

- *Update list of supported ops for 2024.0*
- *None*

[DOCS] Update list of supported ops for 2024.0

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- Cherry-picks: https://github.com/openvinotoolkit/openvino/pull/22918

[CPU] Disabled zero-points folding for dynamic quantization case

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp

This PR updates kindly error messages for usm allocation failure.
- 130105

[GPU] add kindly error messages for usm allocation

---

src/tests/functional/plugin/conformance/subgraphs_dumper/README.md
src/tests/functional/plugin/conformance/test_runner/README.md

- *item1*
- *...*
- *ticket-id*

[ CONFORMANCE ] Update readme files to the new executable file names

---

docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/custom-module-template.rst
docs/sphinx_setup/api/ie_python_api/api.rst

Updating API reference with ``openvino`` namespace redesign changes.
This PR addresses the following ticket: 117329
Porting: https://github.com/openvinotoolkit/openvino/pull/22911

[DOCS] Update API reference for 24.0

---

docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/custom-module-template.rst
docs/sphinx_setup/api/ie_python_api/api.rst

Updating API reference with ``openvino`` namespace redesign changes.
This PR addresses the following ticket: 117329

[DOCS] Update API reference

---

src/bindings/c/docs/api_overview.md
src/core/README.md
src/core/docs/api_details.md
src/core/docs/operation_enabling_flow.md
src/core/docs/tests.md
src/frontends/onnx/docs/tests.md
src/inference/README.md
src/tests/README.md

- Remove some api 1.0 names and mentions from dev docs
- Cherry-picked from https://github.com/openvinotoolkit/openvino/pull/22873
- CVS-132237

[DOCS] Remove some api 1.0 names and mentions from dev docs (#22873)

---

tests/layer_tests/tensorflow_tests/test_tf_StaticRegexReplace.py

**Details:** Add layer test for tf.raw_ops.StaticRegexReplace operation

[TF FE] Add layer test for tf.raw_ops.StaticRegexReplace operation

---

src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/file_utils.hpp
src/tests/test_utils/common_test_utils/include/common_test_utils/unicode_utils.hpp
src/tests/test_utils/functional_test_utils/src/summary/api_summary.cpp
src/tests/test_utils/functional_test_utils/src/summary/op_summary.cpp

- *item1*
- *...*
- *ticket-id*

Remove duplicated common test util functions

---

tests/layer_tests/tensorflow_tests/test_tf_StringSplitV2.py

**Details:** Add layer test for StringSplitV2

[TF FE] Add layer test for StringSplitV2

---

src/frontends/pytorch/src/op/add.cpp
src/frontends/pytorch/src/op/mul.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_add.py
tests/layer_tests/pytorch_tests/test_mul.py

- finalization of https://github.com/openvinotoolkit/openvino/pull/22045
- for boolean inputs of Add and Mul use logical Or and And ops subsequently
- Closes #21971
- _Ticket:_ CVS-133316

[PT FE] add boolean support for mul and add

---

src/inference/src/dev/iplugin.cpp
src/inference/tests/unit/query_model_test.cpp

- *Check the ops to make sure Assign and ReadValue in pairs on the network*
- *95344*

Add check to the model to make sure Assign and ReadValue in pairs in query model

---

src/bindings/js/node/package.json

- Specify release version in package.json
- Set up production links to binaries
- 131978

[OV JS] Specify release version and binaries links in package.json

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/memory_pool.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/profiling.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/runtime/memory_pool.cpp

- Added more information for memory allocation in DumpProfilingData (new_alloc/reuse_buffer/can_be_optimized/from_pool)
- *ticket-id*

[GPU] Added more information for memory allocation in DumpProfilingData 

---

src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected.hpp
src/plugins/intel_cpu/src/nodes/executors/executor.hpp
src/plugins/intel_cpu/src/nodes/executors/executor_factory.hpp
src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
src/plugins/intel_cpu/src/nodes/executors/mlas/mlas_gemm.cpp
src/plugins/intel_cpu/src/nodes/executors/mlas/mlas_gemm.hpp

Backport https://github.com/openvinotoolkit/openvino/pull/22929
- 132558

[CPU] Fix selecting conv primitive for the FC node

---

docs/sphinx_setup/_static/js/graphs.js
docs/sphinx_setup/_templates/layout.html

port to https://github.com/openvinotoolkit/openvino/pull/23008

[DOCS] upgrade chart js to v4

---

src/bindings/js/node/package.json

Port of https://github.com/openvinotoolkit/openvino/pull/22960
- Specify release version in package.json
- Set up production links to binaries
- 131978

[OV JS] Specify release version and binaries links in package.json (#22960)

---

docs/articles_en/about-openvino/system-requirements.rst
docs/articles_en/learn-openvino/interactive-tutorials-python/notebooks-installation.rst
src/bindings/c/docs/api_overview.md

Port from https://github.com/openvinotoolkit/openvino/pull/22986
Updating min supported version of macOS to 12.6 in docs.
Jira: 130339

[DOCS] macOS version update to 12.6 for 2024.0

---

tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_text_vectorization.py
tests/layer_tests/tensorflow_tests/test_tf_LookupTableFind.py

**Details:** Add layer test for tf.keras.layers.TextVectorization and for LookupTableFindV2 with string key

[TF FE] Add layer test for tf.keras.layers.TextVectorization and for LookupTableFindV2 with string key

---

src/bindings/python/src/pyopenvino/core/remote_context.cpp
src/bindings/python/src/pyopenvino/core/remote_tensor.cpp

- Added documentation to Python Remote API functions and classes.
- *129478*

[PyOV] Add doc strings to Python Remote API functions

---

src/plugins/proxy/tests/CMakeLists.txt

- Fix for https://github.com/openvinotoolkit/openvino/issues/23021

Replace `func_test_utils` with `common` in `ov_proxy_plugin_tests`

---

.github/workflows/ovc.yml

- Removed paths checks from OVC workflow as we need to make this workflow required.
-

[OVC] Removed paths checks from OVC workflow.

---

tests/layer_tests/tensorflow_tests/test_tf_RaggedTensorToTensor.py

**Details:** Add layer test for tf.raw_ops.RaggedTensorToTensor

[TF FE] Add layer test for tf.raw_ops.RaggedTensorToTensor

---

docs/articles_en/about-openvino/performance-benchmarks/model-accuracy-int8-fp32.rst

Port for https://github.com/openvinotoolkit/openvino/pull/23062

[DOCS] Update model table for master

---

docs/articles_en/about-openvino/performance-benchmarks/model-accuracy-int8-fp32.rst

Port for https://github.com/openvinotoolkit/openvino/pull/23062

[DOCS] Update model table fix for 2024

---

tests/layer_tests/common/utils/tf_utils.py
tests/layer_tests/tensorflow_tests/test_tf_BiasAdd.py
tests/layer_tests/tensorflow_tests/test_tf_BinaryOps.py
tests/layer_tests/tensorflow_tests/test_tf_Eltwise.py
tests/layer_tests/tensorflow_tests/test_tf_Equal.py
tests/layer_tests/tensorflow_tests/test_tf_ReLU6.py
tests/layer_tests/tensorflow_tests/test_tf_Roll.py
tests/layer_tests/tensorflow_tests/test_tf_Rsqrt.py
tests/layer_tests/tensorflow_tests/test_tf_ScatterND.py
tests/layer_tests/tensorflow_tests/test_tf_Softsign.py
tests/layer_tests/tensorflow_tests/test_tf_Sub.py
tests/layer_tests/tensorflow_tests/test_tf_Swish.py
tests/layer_tests/tensorflow_tests/test_tf_TopK.py
tests/layer_tests/tensorflow_tests/test_tf_UnaryOps.py

**Details:** This legacy code previously was used for validation legacy FE in legacy inference API

[Layer Test] Remove legacy code from layer tests

---

docs/sphinx_setup/api/api_reference.rst
docs/sphinx_setup/api/nodejs_api/nodejs_api.rst

Adding article about Node.js API in the OpenVINO toolkit.

[DOCS] Add Node.js API to docs

---

docs/sphinx_setup/api/api_reference.rst
docs/sphinx_setup/api/nodejs_api/nodejs_api.rst

Porting:
https://github.com/openvinotoolkit/openvino/pull/23055
Adding article about Node.js API in the OpenVINO toolkit.

[DOCS] Add Node.js API to docs for 24.0

---

src/common/util/src/file_util.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/caching_tests.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp

- solve windows unicode inconsistent issue
- add more test case
- Closes https://github.com/openvinotoolkit/openvino/issues/23072
- CVS-128116

[UNICODE] solve windows unicode inconsistent issue

---

tests/model_hub_tests/pytorch/test_torchvision_models.py

- *item1*
- *...*
- *ticket-id*

Disable torch.export for nightly

---

src/common/util/src/file_util.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/behavior/ov_plugin/caching_tests.hpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp

- solve windows unicode inconsistent issue
- add more test case
- Closes https://github.com/openvinotoolkit/openvino/issues/23072
- CVS-128116

Port PR-23100 for Windows unicode issue

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/single_op_tests/gru_sequence.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/gru_sequence.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/lstm_sequence.hpp
src/tests/functional/shared_test_classes/src/single_op/gru_sequence.cpp
src/tests/functional/shared_test_classes/src/single_op/lstm_sequence.cpp

- Fix and enable some tests
- [CVS-121228](https://jira.devtools.intel.com/browse/CVS-121228)
- [CVS-122177](https://jira.devtools.intel.com/browse/CVS-122177)
- [CVS-122094](https://jira.devtools.intel.com/browse/CVS-122094)
- [CVS-121709](https://jira.devtools.intel.com/browse/CVS-121709)
- [CVS-121710](https://jira.devtools.intel.com/browse/CVS-121710)
- [CVS-121715](https://jira.devtools.intel.com/browse/CVS-121715)
- [CVS-120329](https://jira.devtools.intel.com/browse/CVS-120329)

Fix and enable some tests

---

tests/layer_tests/tensorflow_tests/test_tf_StringLower.py

**Details:** Switch on layer test for StringLower operation. Needs to be merged after https://github.com/openvinotoolkit/openvino_tokenizers/pull/44
**Ticket:** 132695

[TF FE] Switch on layer test for StringLower operation

---

src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp

This reverts commit 1e5d0e5beb0dee07d45e3e68da46b34255be45bf.
- *item1*
- *...*
- *ticket-id*

Revert "[op conformance] Fix threshold bugs in ov::test::utils::compare (#22972)

---

.github/workflows/windows.yml
.github/workflows/windows_conditional_compilation.yml

Backport change for Windows GitHub Actions Workflow https://github.com/openvinotoolkit/openvino/pull/22928/files

[chore] Backport sccache idle timeout

---

src/plugins/intel_gpu/src/graph/compilation_context.cpp

[GPU] CompilationContext refactoring

---

src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/plugin.h

- Remove Engine with Plugin
- *...*
- *ticket-id*

[CPU] Rename Engine with Plugin

---

src/inference/src/dev/make_tensor.cpp

- See error https://c3i.jfrog.io/c3i/misc-v2/logs/pr/22913/1-linux-gcc/openvino/2024.0.0//433781cf759d565cab6a71aaa51a755d86a83fd3-build.txt

Include mutex for std::call_once

---

docs/sphinx_setup/_static/js/graphs.js
docs/sphinx_setup/_static/js/hide_banner.js

- *item1*
- *...*
- *ticket-id*

[DOCS] Updated links to files for 2024 version

---

docs/articles_en/about-openvino/system-requirements.rst
docs/articles_en/openvino-workflow/running-inference/changing-input-shape.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection/debugging-auto-device.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device/remote-tensor-api-gpu-plugin.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/hetero-execution.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/multi-device.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/query-device-properties.rst
docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application/python-api-exclusives.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-latency.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-latency/model-caching-overview.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-memory-usage.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-throughput.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-throughput/advanced_throughput_options.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference/precision-control.rst
docs/articles_en/openvino-workflow/running-inference/stateful-models-intro.rst

related to: https://github.com/openvinotoolkit/openvino/pull/23094

[DOCS] 2024 linking issues run-inf

---

docs/articles_en/get-started/install-openvino/install-openvino-linux.rst
docs/articles_en/get-started/install-openvino/install-openvino-macos.rst
docs/articles_en/get-started/install-openvino/install-openvino-npm.rst
docs/articles_en/get-started/install-openvino/install-openvino-windows.rst
docs/sphinx_setup/api/nodejs_api/nodejs_api.rst

Adding npm distribution of OpenVINO™ Toolkit do install guides.
Porting: https://github.com/openvinotoolkit/openvino/pull/23164

[DOCS] Adding npm distribution to install guides for 24.0

---

docs/articles_en/about-openvino/compatibility-and-support/supported-devices.rst
docs/articles_en/documentation/openvino-ir-format/operation-sets/operations-specifications/infrastructure/assign-6.rst
docs/articles_en/documentation/openvino-ir-format/operation-sets/operations-specifications/infrastructure/read-value-6.rst
docs/articles_en/openvino-workflow/generative-ai-models-guide.rst
docs/articles_en/openvino-workflow/running-inference.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device.rst
docs/articles_en/openvino-workflow/running-inference/stateful-models.rst
docs/articles_en/openvino-workflow/running-inference/stateful-models/obtaining-stateful-openvino-model.rst
docs/articles_en/openvino-workflow/running-inference/string-tensors.rst
docs/articles_en/openvino-workflow/torch-compile.rst
docs/home.rst

relates to: https://github.com/openvinotoolkit/openvino/pull/23094

[DOCS] 2024 linking and adjustments

---

src/inference/src/dev/make_tensor.cpp

- Fix includes in dev api for conan integration
- *ticket-id*

Fix includes in dev api for conan integration

---

samples/js/node/README.md
samples/js/node/classification_sample_async/README.md
samples/js/node/hello_classification/README.md
samples/js/node/hello_reshape_ssd/README.md
src/bindings/README.md
src/bindings/js/README.md
src/bindings/js/docs/README.md
src/bindings/js/node/.npmignore
src/bindings/js/node/README.md
src/bindings/js/node/package-lock.json

Port of: https://github.com/openvinotoolkit/openvino/pull/23138
- Actualize JS API readme file for npm
- Fix link to node directory
- Fix .npmignore to do not include extra files into npm package

[DOCS][OV JS] Update JS API readme (#23138)

---

docs/articles_en/get-started/install-openvino/install-openvino-apt.rst
docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst
docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst
docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst
docs/articles_en/get-started/install-openvino/install-openvino-conan.rst
docs/articles_en/get-started/install-openvino/install-openvino-conda.rst
docs/articles_en/get-started/install-openvino/install-openvino-yum.rst

- *item1*
- *...*
- *ticket-id*

[DOCS]  Change install links

---

src/plugins/intel_cpu/src/extension.cpp

- *RoPE node from the CPU opset was added to the extensions list. That fixes model deserialization from cache.*
- *Part of the task 127331*

[CPU] RoPE added to extension list.

---

docs/articles_en/get-started/install-openvino.rst

Updating distribution comparison table.

[DOCS] Update distribution comparison table for 24.0

---

docs/articles_en/get-started/install-openvino/install-openvino-npm.rst

[DOCS] Update link to API for 24.0

---

src/inference/src/threading/ie_cpu_streams_executor.cpp

- Port of https://github.com/openvinotoolkit/openvino/pull/18868 and https://github.com/openvinotoolkit/openvino/pull/19832

[2022.3] Memory Leak fix (#18868)

---

docs/articles_en/get-started/install-openvino.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Update distribution comparison for 24.0

---

docs/articles_en/openvino-workflow/model-optimization-guide/compressing-models-during-training.rst
docs/articles_en/openvino-workflow/model-optimization-guide/compressing-models-during-training/filter-pruning.rst
docs/articles_en/openvino-workflow/model-preparation/convert-model-paddle.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/multi-device.rst
docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-latency.rst

* Fixed some lines in OpenVINO Workflow section
* Fixed a PaddlePaddle link

[DOCS] Fixes for OpenVINO Workflow for 2024

---

docs/sphinx_setup/_static/js/graphs.js

- *item1*
- *...*
- *ticket-id*

DOCS temporary benchmark update for 2024.0

---

src/common/transformations/src/transformations/op_conversions/batch_norm_decomposition.cpp
src/common/transformations/tests/op_conversions/batch_norm_decomposition_test.cpp

Support dyn shapes in BatchNormDecomposition transformation
- *CVS-133609*

Support dyn shapes in BatchNormDecomposition transformation

---

tests/model_hub_tests/tensorflow/model_lists/precommit

- sentence-transformers/paraphrase-mpnet-base-v2 randomly fails on accuracy.
- Ticket for fixing - 134787
-

[TF FE] Remove paraphrase model from precommit

---

src/bindings/python/src/pyopenvino/utils/utils.cpp
src/bindings/python/tests/test_runtime/test_core.py

- cherry-picked https://github.com/openvinotoolkit/openvino/pull/23284/
- [CVS-134484](https://jira.devtools.intel.com/browse/CVS-134484)

[PyOV] Cherry-picked convert  ExecutionMode enum to any

---

src/inference/src/dev/isync_infer_request.cpp
src/inference/tests/unit/iplugin_test.cpp

Port from https://github.com/openvinotoolkit/openvino/pull/23081 to 2023.3
- *item1*
- *...*
- 122932

Update port name checking logic to 2023.3

---

samples/js/node/package-lock.json
samples/js/node/package.json
src/bindings/js/node/package.json

Port of: https://github.com/openvinotoolkit/openvino/pull/23304
- Remove unnecessary run
- Fix run unit tests command
- Update min Node.js version in samples

[OV JS] Fix package.json files (#23304)

---

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection.rst

Fixed Async API docs link in Automatic Device Selection article

[DOCS] Link fix for Automatic Device Selection for 2024

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp

- *[CPU] [AARCH64] jit subtract*
- *CVS-134748*

[CPU] [ARM64] jit subtract

---

docs/home.rst

Jira: 133084
* Fixed the home page tab title name.
* Fixed the missing line in banner

[DOCS] Fix of home tab title for 2023.3

---

docs/sphinx_setup/api/api_reference.rst
docs/sphinx_setup/api/nodejs_api/addon.rst
docs/sphinx_setup/api/nodejs_api/nodejs_api.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Core.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CoreConstructor.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/types/SupportedTypedArray.rst
docs/sphinx_setup/api/nodejs_api/openvino-node/types/elementTypeString.rst

Adding docs for OpenVINO Node.JS API.
Porting: https://github.com/openvinotoolkit/openvino/pull/23189

[DOCS] Add Node.js docs to API for master

---

docs/articles_en/get-started/install-openvino.rst

Updating distribution comparison table.
Porting: 
https://github.com/openvinotoolkit/openvino/pull/23271
https://github.com/openvinotoolkit/openvino/pull/23277

[DOCS] Update distribution comparison table

---

docs/articles_en/documentation/openvino-ecosystem/openvino-security-add-on.rst

Fixing reference to an OMZ model.
Porting: https://github.com/openvinotoolkit/openvino/pull/23417

[DOCS] Fix face-detection-retail-0004 reference

---

docs/articles_en/learn-openvino/llm_inference_guide.rst
docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-hf.rst
docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-native-ov.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] PORT Fix llms article format

---

.github/components.yml

since AUTO is the default configuration for release
- *CVS-128897*

Build AUTO when CPU/GPU changes

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp

- *[CPU] [AARCH64] jit eltwise PReLU
- *CVS-134011*

[CPU] [ARM64] jit prelu

---

docs/CMakeLists.txt

CMakeLists.txt update, to be able to build right version of Python API.

[DOCS] Python API version fix

---

src/plugins/intel_cpu/src/nodes/executors/executor_factory.hpp
src/plugins/intel_cpu/src/nodes/executors/executor_implementation.hpp

- Put executor into the cache after it is created

[CPU] Fix caching executors in factory

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *Adjusted BF16 | INT8 MHA tokenization condition : removed this condition. The performance validation results are attached to the ticket*
- *130837*

[Snippets][CPU] Adjusted BF16 | INT8 MHA tokenization condition

---

src/plugins/intel_gpu/include/intel_gpu/plugin/graph.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/program_builder.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/sync_infer_request.hpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/plugin/graph.cpp
src/plugins/intel_gpu/src/plugin/ops/parameter.cpp
src/plugins/intel_gpu/src/plugin/ops/result.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/plugin/program_builder.cpp
src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

[GPU] Remove use of legacy names

---

src/bindings/c/tests/ov_infer_request_test.cpp

- [CAPI][TEST] fix ov_infer_request_test test error
- CVS-129394

[CAPI][TEST] fix ov_infer_request_test test error

---

src/frontends/pytorch/src/op/transpose.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_floor_divide.py
tests/layer_tests/pytorch_tests/test_transpose.py

- *aten::floor_divide*
- *aten::movedim*
- *ticket-id*

[PT FE]: support aten::floor_divide_ and aten::movedim

---

src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/graph.h
src/plugins/intel_cpu/src/infer_request.cpp
src/plugins/intel_cpu/src/infer_request.h
src/plugins/intel_cpu/src/nodes/if.cpp
src/plugins/intel_cpu/src/nodes/tensoriterator.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/insert_convert_after_extension.cpp
src/plugins/intel_cpu/src/utils/ngraph_utils.hpp

- *item1*
- *...*
- *CVS-132085*

[CPU Plugin] Clean legacy name

---

docs/sphinx_setup/_static/js/graphs.js

Port for 
https://github.com/openvinotoolkit/openvino/pull/23411

[DOCS] Added off on click for 2023.3

---

docs/sphinx_setup/_static/js/graphs.js

port for <html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr'>
https://github.com/openvinotoolkit/openvino/pull/23411
--
</div>
</body>
</html>

[DOCS] Added off on click for 2024.0

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp

- *[CPU] [AARCH64] jit divide*
- *CVS-134747*

[CPU] [ARM64] jit divide

---

src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_convolution_primitive.cpp
src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_convolution_primitive.hpp
src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected.hpp
src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_utils.hpp
src/plugins/intel_cpu/src/nodes/executors/executor.hpp
src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/matmul.cpp

- By providing correct output dimensions.
- 134466

[CPU] Fix primitive attributes creation for 1x1 Convolution as FC executor

---

thirdparty/dependencies.cmake

- Ported patch from vcpkg related to protobuf search
- See https://github.com/microsoft/vcpkg/pull/35781

Ported patch from vcpkg related to protobuf search

---

src/tests/functional/plugin/conformance/test_runner/README.md
src/tests/test_utils/functional_test_utils/layer_tests_summary/run_conformance.py
src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- *move re-run under flag*
- *move timeout under flag*
- *add interapted tests to fix_priority*
- *print failed tests*
- *[ticket-id](https://jira.devtools.intel.com/browse/CVS-134299)*

[CONFORMANCE] Add new flags for conformance + add interapted tests to `fix_priority`

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp

- *[CPU] [AARCH64] jit eltwise Clamp
- *CVS-133829*

[CPU] [ARM64] jit clamp

---

docs/sphinx_setup/_static/js/custom.js

- *item1*
- *...*
- *ticket-id*

[DOCS] Updated file

---

src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_mmad_b_fs_yx_fsv32.cpp

- Check is simd 8 is supported
- *[CVS-133769](https://jira.devtools.intel.com/browse/CVS-133769)*

[GPU] Fix SIMD for non supporting platforms

---

tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py

- *Relax quantized tests condition to remove sporadicity.*
- *CVS-129734*

[PT FE] Fix sporadic issue in quantized tests

---

docs/requirements.txt

[DOCS] remove py from docs/requirements

---

docs/requirements.txt

[DOCS] remove py dependency

---

src/bindings/python/src/openvino/frontend/pytorch/patch_model.py
tests/layer_tests/py_frontend_tests/test_torch_frontend.py

- *Make ModuleExtension patching in independent function scope*
- *ticket-id*

[PT FE] Make ModuleExtension  patching in independent function scope

---

docs/requirements.txt

[DOCS] jinja2 update to 3.1.3 for 2022/3

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp

- *[CPU] [AARCH64] jit select*
- *CVS-135445*

[CPU] [ARM64] jit select

---

docs/sphinx_setup/_templates/layout.html
docs/sphinx_setup/_templates/search.html

- *item1*
- *...*
- *ticket-id*

[Docs] restore banner information

---

docs/_templates/layout.html
docs/_templates/search.html

- *item1*
- *...*
- *ticket-id*

[DOCS] Update banner info for 2023.3

---

docs/articles_en/documentation/legacy-features.rst
docs/articles_en/openvino-workflow/model-preparation.rst

port: https://github.com/openvinotoolkit/openvino/pull/23512

[DOCS] improve legacy section formatting

---

docs/articles_en/about-openvino/additional-resources/legal-information.rst
docs/articles_en/about-openvino/release-notes-openvino.rst

port: https://github.com/openvinotoolkit/openvino/pull/23587

[DOCS] ai legal disclaimer

---

src/frontends/paddle/src/input_model.cpp

- *fix heap-buffer-overflow in paddle frontend*
- *CVS-135869*

fix heap-buffer-overflow in paddle frontend

---

src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/denormal_check.cpp
src/plugins/intel_cpu/tests/functional/utils/fusing_test_utils.hpp
src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
src/tests/test_utils/common_test_utils/include/common_test_utils/data_utils.hpp
src/tests/test_utils/common_test_utils/include/common_test_utils/node_builders/constant.hpp
src/tests/test_utils/common_test_utils/src/node_builders/fake_quantize.cpp

- Remove NGraphFunctions namespace
- CVS-133379

Remove NGraphFunctions namespace

---

src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp

Move ConvertConvertPromoteTypes transformation from Common to MOC
N/A

Move ConvertConvertPromoteTypes transformation from Common to MOC

---

docs/_templates/layout.html
docs/_templates/search.html

[DOCS] update banner for 2022.3

---

src/plugins/intel_gpu/include/intel_gpu/graph/serialization/layout_serializer.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/assign.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/kv_cache.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/read_value.hpp
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.h
src/plugins/intel_gpu/src/kernel_selector/tensor_type.h

- *[CVS-136535](https://jira.devtools.intel.com/browse/CVS-136535)*

[GPU] Coverity fixes

---

src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_gemm_like.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp

- *Add weight size limit for conv opt kernels*
- *135788*

[GPU] Add weight size limit for conv opt kernels

---

src/frontends/pytorch/src/op/full.cpp
src/frontends/pytorch/src/op_table.cpp
src/frontends/pytorch/src/transforms/aten_index_put_replacer.cpp
tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
tests/layer_tests/pytorch_tests/test_scatter.py
tests/model_hub_tests/pytorch/hf_transformers_models
tests/model_hub_tests/pytorch/torch_utils.py
tests/model_hub_tests/pytorch/torchbench_models

- *item1*
- *...*
- *ticket-id*

[PT FE] Add more operators for FX graph

---

docs/snippets/ov_caching.py

- *item1*
- *...*
- *ticket-id*

[DOCS] Include props import

---

cmake/features.cmake
src/plugins/intel_cpu/CMakeLists.txt
src/plugins/intel_gpu/CMakeLists.txt

- JS is not available on Android
- Closes https://github.com/openvinotoolkit/openvino/issues/23494

Fixed Android x86_64 build

---

docs/articles_en/about-openvino/performance-benchmarks.rst
docs/sphinx_setup/_static/js/graphs.js

- *item1*
- *...*
- *ticket-id*

DOCS Update benchmarks for 2024.0

---

src/frontends/pytorch/src/op/unique.cpp
src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/test_unique.py

- *Add support for aten::_unique2 op*
- *Add unit test for it*
- *No ticket id*
closes: #21972

[PT FE] Support aten::_unique2 op.

---

src/plugins/intel_gpu/src/graph/graph_optimizer/concat_input_order.cpp
src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp

- Fix argument of can_shuffle_features() function call in concat_input_order pass
- Update test to have pooling between concat and conv to trigger failed condition
- 137284

[GPU] Fix concat_input_order pass

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- *The previous value led to performance drops on dGPU*
- *[136266](https://jira.devtools.intel.com/browse/CVS-136266)*

[GPU] Changed zero point pad size for dGPU

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_emitter.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_emitter.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp

- *[CPU] [AARCH64] jit sigmoid*
- *CVS-132534*

[CPU] [ARM64] jit sigmoid

---

src/plugins/auto/src/plugin.cpp

- *fix QueryModelWithInvalidDeviceIDThrows is fail for AUTO*
- *CVS-130217*

fix QueryModelWithInvalidDeviceIDThrows is fail for AUTO

---

src/plugins/intel_gpu/include/intel_gpu/primitives/roll.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/roll.cpp
src/plugins/intel_gpu/src/graph/include/roll_inst.hpp
src/plugins/intel_gpu/src/plugin/ops/roll.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/roll.cpp

- Roll dynamic shape implementation
- Add single layer test for dynamic input shape
- 135486
- 101356
- 124503
- 135711

[GPU] Roll dynamic shape implementation

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp

- *[CPU] [AARCH64] jit abs*
- *CVS-136833*

[CPU] [ARM64] jit abs

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp

- Fixed crash and accuracy issue for n_tile_size 32 + transposed input for static shape 
- Fixed gemm_tiled_opt test to apply more various combinations & added more TCs 
- 137358

[GPU] Fix gemm_tiled_opt kernel bug for tile_n_size 32 

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/fusions/deconvolution_fusion_test.cpp

- *[137482](https://jira.devtools.intel.com/browse/CVS-137482)*

[GPU] Convolution supports fusings check fix

---

tests/layer_tests/pytorch_tests/test_scatter.py

- *Fix sporadic fail in scatter_reduce test*
- *CVS-137143*

[PT FE] Fix sporadic fail in scatter_reduce test

---

src/frontends/paddle/tests/op_fuzzy.cpp
src/frontends/paddle/tests/test_models/gen_scripts/generate_generate_proposal_v2.py

- *comment out the PDPD proposal v2_6 testcase*
- *130605*

comment out unstable proposal v2_6 testcase

---

docs/articles_en/about-openvino/compatibility-and-support/supported-operations-framework-frontend.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Update supported pytorch ops list for 24.1

---

docs/articles_en/about_openvino/system_requirements.rst
docs/articles_en/openvino_workflow/running_inference_with_openvino/Device_Plugins/NPU.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Port Add MS Windows version for NPU to 23.3

---

.github/CODEOWNERS
.github/components.yml
.github/labeler.yml

- Added NPU maintainers to config files in the `.github` folder

Added NPU maintainers

---

docs/articles_en/about-openvino/system-requirements.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Port Add MS Windows version for NPU

---

docs/articles_en/about-openvino/system-requirements.rst
docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Add specific MS Windows version for NPU

---

src/core/src/symbol.cpp
src/core/tests/dimension.cpp

- *fixes performance degradation introduces by https://github.com/openvinotoolkit/openvino/pull/23136*
- *CVS-137614*

Symbols equality fix

---

src/plugins/intel_npu/src/al/include/intel_npu/al/icompiler.hpp
src/plugins/intel_npu/src/al/include/intel_npu/al/prefix.hpp
src/plugins/intel_npu/src/al/include/sync_infer_request.hpp
src/plugins/intel_npu/src/al/src/sync_infer_request.cpp
src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp

- Added `shape` metadata
- Shape tensors have a special prefix to distinguish shape tensors from others.
- E-115058

[NPU] - Port plugin changes for dynamic shapes support

---

src/plugins/intel_myriad/myriad_dependencies.cmake

- Update tools package (CLTools)
- 135419

[releases/2022/3] Update tools package

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_emitter.cpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp

- *[CPU] [AARCH64] jit tanh*
- *CVS-134539*

[CPU] [ARM64] jit tanh

---

src/frontends/tensorflow/docs/check_supported_ops.py
src/frontends/tensorflow/docs/supported_ops.md
src/frontends/tensorflow/src/frontend.cpp
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow/src/op_table.hpp
src/frontends/tensorflow/tests/convert_unsupported.cpp
src/frontends/tensorflow/tests/test_models/gen_scripts/generate_string_lower.py

**Details:** Recommend openvino-tokenizers for some operations in case failed conversion
Port of https://github.com/openvinotoolkit/openvino/pull/23878 from master

[TF FE] Recommend openvino-tokenizers for some operations in case failed conversion

---

docs/articles_en/get-started/install-openvino/install-openvino-conda.rst

- Recommend to set LD_LIBRARY_PATH to point to conda libraries
- CVS-134534

Recommend to set LD_LIBRARY_PATH to point to conda libraries

---

docs/articles_en/get-started/install-openvino/install-openvino-conda.rst

Porting https://github.com/openvinotoolkit/openvino/pull/23897

[DOCS] Recommend to set LD_LIBRARY_PATH to point to conda libraries porting to 2024.1

---

src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp

[GPU] Enable dynamic int4 FC testing on dGPU

---

.github/scripts/collect_github_metrics.py
.github/workflows/send_workflows_to_opentelemetry.yml

This way to build queries correctly sanitizes and uses correct types for values passed to SQL.

[GHA] Place values correctly in queries in metrics script

---

.github/workflows/cleanup_caches.yml
.github/workflows/linux_riscv.yml

- fixed cleanup pattern
- Reduce ccache size
- *ticket-id*

[GHA] Risc-V pipeline ccache fixes

---

CONTRIBUTING.md
README.md
src/plugins/README.md

- *Add NPU in the supported hardware matrix*
- *Add NPU in the list of supported plugins*
- *Add NPU plugin in CONTRIBUTING.md*
- *EISW-119403*

Add links to NPU plugin in OpenVINO docs

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp

- *[CPU] [AARCH64] jit swish*
- *CVS-134100*

[CPU] [ARM64] jit swish

---

src/plugins/template/tests/functional/op_reference/base_reference_test.cpp

- Corrected abs_threshold setting.
- CVS-138026

[Tmpl test] Correct abs_threshold setting

---

src/frontends/pytorch/include/openvino/frontend/pytorch/node_context.hpp
src/frontends/pytorch/src/node_context.cpp
src/frontends/pytorch/src/op/if.cpp
src/frontends/pytorch/src/translate_session.cpp
tests/layer_tests/pytorch_tests/test_convnd.py

- *Resolve issue with `If` test*
- *CVS-123727*

[PT FE] Resolve issue with If test

---

.github/workflows/job_debian_packages.yml
.gitmodules
src/bindings/python/CMakeLists.txt

This reverts commit a7c7de4c65cdb683451d59bf207e93c444030d0d.
- PR #23913 introduced regression
- *138078*

Revert "Add openvino-telemetry to debian / rpm package (#23913)"

---

.github/workflows/android_arm64.yml
.github/workflows/linux_riscv.yml

- *item1*
- *...*
- *ticket-id*

Fixed RISC-V build

---

.github/workflows/android_arm64.yml
.github/workflows/job_debian_packages.yml
.github/workflows/linux_riscv.yml
.gitmodules
src/bindings/python/CMakeLists.txt

Reverts openvinotoolkit/openvino#23930

Revert "Revert "Add openvino-telemetry to debian / rpm package (#23913)""

---

docs/home.rst
docs/sphinx_setup/_static/css/custom.css
docs/sphinx_setup/_static/css/homepage_style.css
docs/sphinx_setup/_static/images/home_begin_tile_01.png
docs/sphinx_setup/_static/images/home_begin_tile_02.png
docs/sphinx_setup/_static/images/home_begin_tile_03.png
docs/sphinx_setup/_static/images/home_begin_tile_04.png
docs/sphinx_setup/_static/images/home_begin_tile_05.png
docs/sphinx_setup/_static/images/home_begin_tile_06.png
docs/sphinx_setup/_static/images/home_key_feature_01.png
docs/sphinx_setup/_static/images/home_key_feature_02.png
docs/sphinx_setup/_static/images/home_key_feature_03.png
docs/sphinx_setup/_static/images/home_key_feature_04.png
docs/sphinx_setup/_static/images/openvino-overview-diagram.jpg
docs/sphinx_setup/_static/images/ov_homepage_diagram.png
docs/sphinx_setup/_static/js/custom.js

Docs new home page for 2024 1 port

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/softmax_gpu_bf.cl

- *Use 8 block size for subgroup read / write on dynamic model at runtime*
- *133443*

[GPU] Use 8 subgroup block read /write functions on dynamic model

---

src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp

[GPU] gemm issue on dgpu

---

docs/sphinx_setup/conf.py

Fixing highlighting issues in code blocks in articles.
Fixing references to sections in other articles.

[DOCS] Fix highlighting issues in code blocks
