- .github/workflows/windows.yml
- .github/workflows/windows_conditional_compilation.yml
This should fix the following sporadic issues:
```
2024-02-16T21:40:26.9140419Z sccache: error: failed to execute compile
2024-02-16T21:40:26.9141391Z sccache: caused by: Failed to send data to or receive data from server
2024-02-16T21:40:26.9142455Z sccache: caused by: Failed to read response header
2024-02-16T21:40:26.9144951Z sccache: caused by: A connection attempt
failed because the connected party did not properly respond after a
period of time, or established connection failed because connected
host has failed to respond. (os error 10060)
```
and
```
2024-02-16T21:40:26.9140419Z sccache: error: failed to execute compile
2024-02-16T21:40:26.9141391Z sccache: caused by: Failed to send data to or receive data from server
2024-02-16T21:40:26.9142455Z sccache: caused by: Failed to read …
```
> [GHA] Fix for premature sccache server shutdown on Windows

- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- This PR disabled zero-points constant folding in case dynamic quantization is enabled. Dynamic quantization kernels requires zero-points to be in u4/u8 precision while constant folding converted them into fp32.
> [CPU] Disabled zero-points folding for dynamic quantization case

- src/common/util/src/file_util.cpp
- src/frontends/onnx/frontend/src/utils/onnx_internal.cpp
- src/frontends/onnx/frontend/src/utils/tensor_external_data.cpp
- src/tests/test_utils/common_test_utils/tests/utils_tests.cpp
- Store in ONNX graph model directory without get absolute path. The real `model_dir` path has to be resolved when used for example to load external model data. 
If symbolic links used the model real directory and exteranal data real directory can be different. The real path for model data is resolved after joining with model data location.
- Update `ov::utils::get_directory` function to resolve special cases such as empty string and current folder.
- #22736
> [ONNX][core] Fix resolving symlink for model external data

- src/plugins/intel_cpu/tests/functional/CMakeLists.txt
See the [ticket description](https://jira.devtools.intel.com/browse/CVS-132119). The solution was checked only on a local setup on Ubuntu, if there's a way to check that using the CI please let me know (or if you could run the job and paste the link in the comments I would be grateful).
Disclaimer: I'm not a CPU plugin developer, so I can't tell for sure if this is the ideal fix and no side effects are introduced. Please take that into account when reviewing/merging.
- [CVS-132119](https://jira.devtools.intel.com/browse/CVS-132119)
> [CPU] Solving the build failure caused by setting the "ENABLE_OV_ONNX_FRONTEND" option to "OFF"

- .github/workflows/job_onnx_models_tests.yml
ONNX Model Tests workflow job reads models from shared drive, but the IOPS and bandwidth requirements are so high that we need to spread the load between few replicas.
This approach assumes replicas are mounted to separate mount points in the filesystem, then a very simple Bash snippet is used to choose one of them.
> [GHA] Split test data storage for ONNX Model Tests into two replicas

- src/tests/ov_helpers/ov_models/src/precomp.hpp
- Restore src/tests/ov_helpers/ov_models/src/precomp.hpp, deleted in  https://github.com/openvinotoolkit/openvino/pull/22709
- Fix build with -DENABLE_FASTER_BUILD=ON key
- *ticket-id*
> Return precomp.hpp to ov_models to fix build

- docs/articles_en/openvino-workflow/deployment-locally.rst
- docs/articles_en/openvino-workflow/running-inference/optimize-inference/high-level-performance-hints.rst
- docs/sphinx_setup/api/api_reference.rst
- samples/cpp/benchmark_app/main.cpp
- src/bindings/python/src/openvino/__init__.py
- tools/benchmark_tool/openvino/__init__.py
- tools/mo/openvino/__init__.py
- tools/openvino_dev/src/openvino/__init__.py
- tools/ovc/openvino/__init__.py
Changing references from "OpenVINO API 2.0" to "OpenVINO API", as mentioned in https://github.com/openvinotoolkit/openvino/pull/22873#discussion_r1492115073
Porting: https://github.com/openvinotoolkit/openvino/pull/22884
> [DOCS] Openvino api ref update for 24.0

- src/frontends/onnx/tests/__init__.py
- src/frontends/onnx/tests/tests_python/test_backend.py
- OV uses ONNX >= `1.15.0` which got bug fix for disabled tests.
- CVS-91151
> [ONNX] Enable ONNX castlike tests

- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/automatic-batching.rst
- *Note that GPU may not trigger "auto_batch" if model or GPU memory size are not allowed.*
- *compile_model requires ov::model for GPU default BATCH*
- **
> Add note for GPU default BATCH

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_onnx.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_base.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/resample_gpu_test.cpp
- *By default rounding float to int does not match the implementation in the CPUPlugin*
- *Part of 127417*
> [GPU] Added rounding to nearest even for integer Interpolate output

- src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected.hpp
- src/plugins/intel_cpu/src/nodes/executors/executor.hpp
- src/plugins/intel_cpu/src/nodes/executors/executor_factory.hpp
- src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
- src/plugins/intel_cpu/src/nodes/executors/mlas/mlas_gemm.cpp
- src/plugins/intel_cpu/src/nodes/executors/mlas/mlas_gemm.hpp
Fix convolution primitive selection algorithm for the FC node implementation. This PR brings back the old behavior, where only `brgconv_avx512_1x1` were allowed to perform FC operations.
- 132558
> [CPU] Fix selecting conv primitive for the FC node

- src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
CPU plugin uses EnforceInferencePrecision routine for BF16 precision mark-up. Its logic assumes only activations precision is changed before Matmul op, while weights precision keeps w/o any changes. Since dnnlFCTypeMapping misses BF16 activation, FP32 weights optimized configuration for bf16, execution always happens in FP32 precision even user manually set infer_precision=bf16.
This bug is not visible on FP16 IRs (since BF16+FP16 config is present), so only FP32 IRs affected. SInce save_model and ovc apply FP16 compression be default, the issue mostly applicable for pipelines which use a model directly after convert_model call.
Cherry-picks: https://github.com/openvinotoolkit/openvino/pull/22994
> [CPU] Fixed BF16 Matmul inference precision

- src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
- *fixed problem, when all actual values are 0 -> rel_error 0, abs_error more then 0 -> but test is PASS*
- *fixed problem, when one threshold is set by user, another threshold is set to default values std::numeric_limits<double>::max and some problem appears in test -> but test is PASS, because one of thresholds is very big*
- *CVS-133173*
> [op conformance] Fix threshold bugs in ov::test::utils::compare

- src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_smoke_test_conv_reshape_fully_connected.cpp
239-image-bind-quantize notebook fails in GPU.
Target model has `Conv - Fakequantize - FC` pattern and FC was set fsv16 format. Currently FC shape agnostic kernel only support planar format, so enforce planar format in FC before supporting block format.
- *132364*
> [GPU] Fix FC shape agnostic kernel build failure issue.

- src/core/include/openvino/core/except.hpp
- src/core/include/openvino/core/node.hpp
- src/core/src/except.cpp
- src/core/src/node.cpp
- src/core/tests/check.cpp
- src/core/tests/frontend/frontend_manager.cpp
- src/core/tests/node_test.cpp
- src/frontends/common/include/openvino/frontend/exception.hpp
- src/frontends/common/src/exception.cpp
- Restore `create` member function in OV exception classes to be compatible with 2023.2 API.
- [CVS-133319](https://jira.devtools.intel.com/browse/CVS-133319)
> [core] Restore OV exception create function

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- Enable collecting profiling data only at iterations with requested range
- For example for dump profiling data only when iteration is from 10 to 20, you can use `OV_GPU_DumpProfilingDataIteration='10..20'`
- 133260
> [GPU] Add a new option for DumpProfilingData

- src/common/snippets/docs/snippets_design_guide.md
- *Refactored stages about data flow and control flow*
- *Added information about positioned passes for backend-specific pass registration*
- *Added information about `insert_node` and `replace_with_node` helpers*
- *Updated about `LinearIR` serialization methods*y
- *Added more information about `Buffer` management*
- *Updated `generator` passes description*
- *N/A*
> [Snippets][Doc] Updated the design guide

- src/plugins/intel_cpu/src/emitters/plugin/x64/jit_load_store_emitters.cpp
- src/plugins/intel_cpu/tests/unit/jit_kernel_test.cpp
- *Adjusted `get_aux_gpr` for Load and Store emitters to avoid extra `push` and `pop` for some cases. Example of one FP32 element loading on `AVX512` machine:*
- *N/A*
> [CPU] Updated aux GPR count for Load/Store emitters

- src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
- src/plugins/intel_gpu/src/kernel_selector/jitter.h
- src/plugins/intel_gpu/src/kernel_selector/kernel_base.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/depth_to_space_gpu_test.cpp
- *Convert the input to the output data type to fix that cl kernel build failed for an ambiguous issue of the fmax/fmin functions occurring by the different data types between input and output.*
- *133562*
> [GPU] Convert input to output data type in ActivationJitConstants

- src/plugins/intel_cpu/src/graph_context.h
*** CID 1534777:  Performance inefficiencies  (COPY_INSTEAD_OF_MOVE)
/agent/_work/1/openvino/src/plugins/intel_cpu/src/graph_context.h: 24 in ov::intel_cpu::GraphContext::GraphContext(const ov::intel_cpu::Config &, std::shared_ptr<ov::intel_cpu::WeightsSharing>, bool)()
18         typedef std::shared_ptr<const GraphContext> CPtr;
19     
20         GraphContext(const Config& config,
21                      WeightsSharing::Ptr w_cache,
22                      bool isGraphQuantized)
23             : config(config),
>>>     CID 1534777:  Performance inefficiencies  (COPY_INSTEAD_OF_MOVE)
>>>     "w_cache" is copied in call to copy constructor "std::shared_ptr<ov::intel_cpu::WeightsSharing>", when it could be moved instead.
24               weightsCache(w_cache),
25 …
> Fix CS issue

- src/bindings/python/requirements_test.txt
- src/bindings/python/tests/test_runtime/test_compiled_model.py
- src/frontends/paddle/tests/requirements.txt
- tests/constraints.txt
- tests/layer_tests/py_frontend_tests/test_torchvision_preprocessor.py
- tests/layer_tests/requirements.txt
- Removed frontend dependencies from Python API tests
- Moved torchvision preprocessing tests to pytorch layer tests folder.
- *ticket-id*
> Don't use complex dependencies in Python API tests

- .github/workflows/android_arm64.yml
- .github/workflows/build_doc.yml
- .github/workflows/coverity.yml
- .github/workflows/fedora.yml
- .github/workflows/job_cpu_functional_tests.yml
- .github/workflows/job_cxx_unit_tests.yml
- .github/workflows/job_debian_packages.yml
- .github/workflows/job_onnx_models_tests.yml
- .github/workflows/job_onnx_runtime.yml
- .github/workflows/job_openvino_js.yml
- .github/workflows/job_python_unit_tests.yml
- .github/workflows/job_pytorch_models_tests.yml
- .github/workflows/job_samples_tests.yml
- .github/workflows/job_tensorflow_models_tests.yml
- .github/workflows/linux.yml
- .github/workflows/linux_arm64.yml
- .github/workflows/linux_conditional_compilation.yml
- .github/workflows/mac.yml
- .github/workflows/mac_arm64.yml
- .github/workflows/py_checks.yml
- .github/workflows/windows.yml
- .github/workflows/windows_conditional_compilation.yml
- Should improve uploading and downloading stability of larger artefacts (e.g., test packages), and [improve speed](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/).
- *133744*
> [CI] [GHA] Transition to the v4 for `actions/upload` and `actions/download`-`artifact`

- docs/nbdoc/nbdoc.py
Fixing path to notebooks folder for `:glob:` parameter in toctree.
> [DOCS] Fix path to notebooks in toctree

- src/bindings/python/src/pyopenvino/utils/utils.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/reshape.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/eltwise/eltwise_kernel_blocked_opt.cpp
- src/plugins/intel_gpu/src/plugin/ops/scatter_elements_update.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/reshape_gpu_test.cpp
- `OPENVINO_ASSERT` takes boolean expression as first argument. In order to explicitly throw AssertFailure, need to specify `false`, non-empty string will be treated as `true`
> Fix use of `OPENVINO_ASSERT`

- docs/articles_en/get-started.rst
- docs/articles_en/get-started/configurations/configurations-intel-gpu.rst
- docs/articles_en/get-started/install-openvino/install-openvino-apt.rst
- docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst
- docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst
- docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst
- docs/articles_en/get-started/install-openvino/install-openvino-brew.rst
- docs/articles_en/get-started/install-openvino/install-openvino-conan.rst
- docs/articles_en/get-started/install-openvino/install-openvino-conda.rst
- docs/articles_en/get-started/install-openvino/install-openvino-docker-linux.rst
- docs/articles_en/get-started/install-openvino/install-openvino-pip.rst
- docs/articles_en/get-started/install-openvino/install-openvino-vcpkg.rst
- docs/articles_en/get-started/install-openvino/install-openvino-yum.rst
* Fixed links in Get Started section of documentation
* Hid the table with GPU drivers used for validation. Current list outdated, and the new one will be provided at later date.
> [DOCS] Linkfix for Get Started section + removal of GPU drivers table in configurations for 2024

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- src/plugins/template/tests/functional/skip_tests_config.cpp
- [CVS-55937](https://jira.devtools.intel.com/browse/CVS-55937)
- [CVS-123427](https://jira.devtools.intel.com/browse/CVS-123427)
> Enable skipped tests

- src/plugins/intel_cpu/tests/unit/streams_info/streams_info_table_test.cpp
- *add get_streams_info_table() test cases for 4 cores and 8 cores CPUs*
- *...*
- *ticket-id*
> add get_streams_info_table() test cases for 4 cores and 8 cores CPUs

- docs/articles_en/openvino-workflow/model-optimization-guide/quantizing-models-post-training/quantizing-with-accuracy-control.rst
- docs/optimization_guide/nncf/ptq/code/ptq_aa_onnx.py
Port from https://github.com/openvinotoolkit/openvino/pull/23096
- The quantize with accuracy control supports the ONNX backend. I have added information on how to use quantize with accuracy control for `onnx.ModelProto`.
- *133388*
> [DOCS] Add information about ONNX backend to the docs for 2024

- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-onnx-faster-r-cnn.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-onnx-gpt-2.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-onnx-mask-r-cnn.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-bert-ner.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-cascade-rcnn-r-101.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-f3-net.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-quartz-net.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-rcan.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-rnn-t.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-yolact.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-attention-ocr.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-bert.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-crnn.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-deep-speech.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-language-1b.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-ncf.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-object-detection.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-slim-library.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-xlnet.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-yolo.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensroflow-wide-and-deep-family.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-convert-paddle.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-convert-tensorflow.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-model-optimizer-extensibility/[legacy]-extending-model-optimizer-with-caffe-python-layers.rst
Fixing issues with references to articles and external resources in the `Legacy Features` section of the docs.
> [DOCS] Linking issues fix in Legacy Features for 24.0

- .github/workflows/job_tensorflow_models_tests.yml
- .github/workflows/linux.yml
- Removed usage of matrix param in TF models tests job, as the timeout is shared between jobs launched by matrix, which causes nightly jobs abortion by timeout.
-
> Removed usage of matrix param in TF models tests job.

- src/plugins/intel_cpu/src/graph_dumper.cpp
- OV Model API allows to create `ov::Model` with empty ResultVector. And it may cause segmentation fault on `graph.dump()` e.g. when `get_property("NETWORK_NAME")`
- [CVS-134517](https://jira.devtools.intel.com/browse/CVS-134517)
> [CPU] Fix segfault in `dump_graph_as_ie_ngraph_net()`

- src/bindings/python/src/pyopenvino/utils/utils.cpp
- src/bindings/python/tests/test_runtime/test_core.py
- ExecutionMode enum binding was missed to be added to `py_object_to_any` function that caused  segfault
- CVS-134484
> [PyOV] convert  ExecutionMode enum to any

- src/plugins/hetero/src/compiled_model.cpp
- src/plugins/hetero/tests/unit/subgraph_collector.cpp
constant folding been introduced to hetero, but this may bring other issue in quantized models , for example, in gpu plugin, precision conversion will be applied before constant folding, some ops can be operated in fp16 if hardware support, while direct constant folding in hetero doesn't take hardware capability into account and fold the constants directly, this will result in memory concerns, for example, OOM issue, or the performance issue because of different execution precision
CVS-127934
> [HETERO] Remove ConstantFolding of model in hetero

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/src/graph/select.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/select.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_primitive_fusing_test.cpp
- Skip Depth To Space fusing when dynamic shape
- Skip broadcastable check in select typed_primitive_inst() when new shape infer
- 130775
> [GPU] Skip Depth To Space fusing when dynamic shape and skip broadcastable check in select typed_primitive_inst() when new shape infer

- src/plugins/intel_gpu/include/intel_gpu/runtime/memory_pool.hpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/basic_memory_dependencies.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp
- src/plugins/intel_gpu/src/graph/include/pass_manager.h
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/include/program_node.h
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/graph/program_node.cpp
- src/plugins/intel_gpu/src/runtime/memory_pool.cpp
- src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_redundant_reorder_at_runtime.cpp
- Previously, memory conflict check was done using std::string (primitive_id), and it was time consuming 
- Fixed to use unique_id as mem_dep, instead of std::string 
- 131916
> [GPU] Improve memory pool access performance 

- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-convert-models-as-python-objects.rst
- docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations/step3-main.rst
- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.rst
- docs/articles_en/openvino-workflow/running-inference/stateful-models.rst
Fixing directives for linking and cross-reference.
> [DOCS] Fixing references to articles

- src/plugins/intel_cpu/tests/functional/single_layer_tests/convolution.cpp
- *fix bug in https://github.com/openvinotoolkit/openvino/pull/23179 , the flat condition is not right*
- *add test case for ic < 4 with layout nchw8c->nchw8c on sse42*
- the onednn PR https://github.com/openvinotoolkit/oneDNN/pull/235
- *[CVS-125793](https://jira.devtools.intel.com/browse/CVS-125793)*
> [CPU] fix bug in PR 23179

- src/plugins/intel_cpu/src/nodes/executors/executor_factory.hpp
By using a vector instead of a map.
To reduce an overhead of selecting an executor.
Since we know the exact mapping beforehand (by implementation Id): every executor corresponds to
a particular implementation.
> [CPU] Reduce overhead of the executor storage

- src/core/dev_api/openvino/core/constant_fold_utils.hpp
- src/core/src/constant_fold_utils.cpp
- src/core/src/pass/constant_folding.cpp
- src/core/tests/pass/constant_folding.cpp
If TypeRelaxed's origin input type is undefined let's temporarily override it with original input precision attribute value. During ConstantFolding, some nodes can have temporarily mismatched input types (e.g. Add(f16, f32)). If the node is TypeRelaxed - we're unable to clone it since TypeRelaxed::clone_with_new_inputs creates a clone with 'fake' inputs based on current inputs and that can trigger an exception for certain nodes if the inputs have mismatched types.
Ticket: CVS-134604
> Fix convert_to_supported_precision for TypeRelaxed types

- src/plugins/intel_gpu/src/graph/include/reshape_inst.h
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/graph/reshape.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/reshape_gpu_test.cpp
- *Added a condition to defer reshape memory update*
- *If the reshape is static shaped and has null dep memory, its memory update will be deferred*
- *125236*
> [GPU] Defer updating memory of reshape after execution if it is static-shaped and its input memory is null

- .github/components.yml
- *Add GPU build for CAPI RemoteContext tests*
- *CVS-129332*
> CAPI requires GPU plugin

- src/common/low_precision_transformations/include/low_precision/propagate_shared_value.hpp
- src/common/snippets/src/pass/propagate_precision.cpp
- src/common/transformations/include/transformations/utils/utils.hpp
- src/common/transformations/src/transformations/common_optimizations/fused_names_cleanup.cpp
- src/common/transformations/src/transformations/common_optimizations/optimize_strided_slice.cpp
- src/common/transformations/src/transformations/common_optimizations/reverse_shape_and_type_infer.cpp
- src/common/transformations/src/transformations/common_optimizations/shared_ops_optimization.cpp
- src/common/transformations/src/transformations/control_flow/unroll_tensor_iterator.cpp
- src/common/transformations/src/transformations/convert_precision.cpp
- src/common/transformations/src/transformations/fp16_compression/align_mixed_fp32_fp16_types.cpp
- src/common/transformations/src/transformations/init_node_info.cpp
- src/common/transformations/src/transformations/smart_reshape/lstm_states_broadcast.cpp
- src/common/transformations/src/transformations/symbolic_transformations/label_optimization.cpp
- src/common/transformations/src/transformations/symbolic_transformations/symbolic_optimizations.cpp
- src/common/transformations/src/transformations/utils/utils.cpp
- src/core/src/pass/constant_folding.cpp
- src/core/src/pass/low_latency.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/enforce_precision.cpp
- src/plugins/intel_cpu/src/utils/print_model.hpp
[Transformations] Make ov::ModelPass transformations execute recursively
Some ov::ModelPass transformations lack recursive execution for subgraphs leaving it not processed.
Add the required recursive call for MultiSubGraphOp operations.
Ticket: CVS-116659
> [Transformations] Make ov::ModelPass transformations execute recursively

- .github/ISSUE_TEMPLATE/good_first_issue.yml
- CONTRIBUTING.md
- CONTRIBUTING_PR.md
- PRs addressing GFIs are getting difficult to track, this PR aims to increase the community's awareness about this GitHub feature.
- The change to GFI template will also be introduced to GFI templates in `openvino_contrib`, `openvino.genai` and `nncf`.
- An additional reminder has been added to the GFI board:
- N/A
> Update GFI template and docs with information about linking PRs to issues 

- src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
- Move event completion wait to first of execute_impl
- 129373
> [GPU] Move event completion wait to first of execute_impl

- src/plugins/intel_gpu/src/graph/broadcast.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
- src/plugins/intel_gpu/src/graph/include/broadcast_inst.h
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- This PR makes some `Broadcast` layers to be skipped if input and output shapes are same.
- 135100
> [GPU] Skip broadcast when input and output shapes are identical

- src/common/snippets/src/pass/collapse_subgraph.cpp
- src/common/snippets/src/pass/mha_tokenization.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_copy_b_emitter.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_emitter.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_emitter.hpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_kernel_emitter.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_kernel_emitter.hpp
- src/tests/functional/plugin/shared/src/snippets/max_num_params_eltwise.cpp
- src/tests/ov_helpers/ov_snippets_models/include/subgraph_simple.hpp
- src/tests/ov_helpers/ov_snippets_models/src/subgraph_simple.cpp
- Currently, `amx_tile_configure` in brgemm emitter is called for each inference whereas reconfiguration can be called only when input shapes are differ from previous inference. This PR introduces `amx_tile_config` structure with the latest used dimensions. The structure is passed as a runtime argument in compiled kernel. Brgemm emitter gets the structure and checks if the current shapes are the same as previous. If they are the same, `amx_tile_configure` is skipped. Otherwise, the reconfiguration is called, and `amx_tile_config` is updated with new shapes.
- *CVS-125676*
> [Snippets][AMX] Perform amx_tile_configure only when necessary

- cmake/developer_package/target_flags.cmake
- src/cmake/openvino.cmake
- Added protogation of OpenVINO's _GLIBCXX_USE_CXX11_ABI to allow build on Ubuntu against binaries compiled on CentOS 7
> Added propogation of OpenVINO's _GLIBCXX_USE_CXX11_ABI

- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.hpp
- *The pass `isSuitableChildForFusingMatMul` first checked that the `node` has constant inputs, without checking what the `node` type is and what parent is. It leaded to infinity checks for constant path for the node which cannot be even fused to `MatMul`. Thus, no make sense to check that parent `MatMul` has `constant` path.*
- *The PR refactored check `isSuitableChildForFusingMatMul`*:
- *Firstly, we check for possible fusion `MatMul (FC)` with `Bias` and `DQScales` based on node type;*
- *Secondly, we add specific checks from `MatMul::CanFuse` for binary `Eltwise` and `FQ`. Moreover, this code has been updated for the first time since Snippets support!*
- *Thirdly, we check that the node is supported for fusion with `MatMul` (is `Eltwise` op at least) and only after that (!) we check …
> [Snippets][CPU] Fixed isSuitableChildForFusingMatMul

- src/common/transformations/src/transformations/common_optimizations/broadcast_transition.cpp
- src/common/transformations/tests/common_optimizations/broadcast_transition_test.cpp
`BroadcastTransition` matches on `ov::op::v1::Broadcast` and `ov::op::v3::Broadcast`. However, the matched Broadcast was always casted to `ov::op::v3::Broadcast`: this led to segfault. This PR fixes this issue and adds test cases for `BroadcastTransition` transformation with `ov::op::v1::Broadcast`
> [Transformations] BroadcastTransition: fix segfault

- docs/sphinx_setup/_static/js/graphs.js
The current behavior is that each subsequent click to "Edit graph settings" leads to more and more calls to click event listener. You can check it from browser's developer console. They all do the same thing, so from user's view nothing is wrong. This fix is ugly as well but removes listener before adding the new (same) one.
> Don't bind more and more event listeners

- src/frontends/onnx/frontend/src/op/reduce.cpp
- src/frontends/onnx/frontend/src/op/reduce.hpp
- src/frontends/onnx/tests/models/reduce_wrong_type_v1.prototxt
- src/frontends/onnx/tests/models/reduce_wrong_type_v2.prototxt
- src/frontends/onnx/tests/onnx_import_exceptions.cpp
- Refactored source code to be able co-work with others
- Removed unnecessary comments
- Added check for a wrong input type
- Added tests for an exception for wrong input type
- 125493
> [ONNX] Reduce* refactoring

- docs/ovsa/ovsa_get_started.md
- samples/c/hello_classification/README.md
- samples/c/hello_nv12_input_classification/README.md
- samples/cpp/benchmark/sync_benchmark/README.md
- samples/cpp/benchmark/throughput_benchmark/README.md
- samples/cpp/classification_sample_async/README.md
- samples/cpp/hello_classification/README.md
- samples/cpp/hello_nv12_input_classification/README.md
- samples/python/benchmark/sync_benchmark/README.md
- samples/python/benchmark/throughput_benchmark/README.md
- samples/python/classification_sample_async/README.md
- samples/python/hello_classification/README.md
removing links to two OMZ models - required to build 22.3 now, later may be restored in a different form.
> [DOCS] fix 22.3 build-issues

- src/plugins/intel_gpu/src/graph/gemm.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/oooq_memory_dependencies.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/activation.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/broadcast.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/concat.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/crop.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/detection_output.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/eltwise.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/gather.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/non_max_suppression.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/proposal.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/range.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/reorder.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/scatter_update.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/select.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/shape_of.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/strided_slice.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/tile.cpp
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/plugin/transformations/convert_gather_to_compressed.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/gather_weights_decompression.cpp
- fixed `GatherCompressed` not to reshape to 2d if there is no reshape layer
- fixed a bug in `gemm_inst::transform_output_layout`
- updated to propagate dependent events to its users if it is in `shape-of_subgraph`
> [GPU] Fix several errors

- src/common/transformations/include/transformations/utils/utils.hpp
- src/common/transformations/src/transformations/utils/utils.cpp
- src/plugins/intel_cpu/src/graph_optimizer.cpp
- src/plugins/intel_cpu/src/graph_optimizer.h
- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/fuse_transpose_reorder.cpp
- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/merge_transpose_reorder.cpp
- src/plugins/intel_cpu/tests/unit/graph/merge_transpose_reorder_test.cpp
- *MergeTransposeReorder: reverse operations order support*
- *MergeTransposeReorder: reshape between Transpose and Reorder is supported with the following limitations:*
- Direct order (Transpose -> Reshape -> Reorder): reshape which separates one of the dimension on 2 consecutive ones
- reverse order: (Reorder -> Reshape -> Transpose): reshape which fuses 2 consecutive dimensions into one
- Common code, which performs the fusion, is moved to a separate function.
- *CVS-113363*
> [CPU] MergeTransposeReorder extending

- tests/layer_tests/README.md
**Details:** Update layer test documentation. It will be used by external developers and mentioned in GFIs.
> [DOCS][Layer Tests] Update layer test documentation

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/loop.cpp
- src/plugins/intel_gpu/src/graph/reshape.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/loop_gpu_test.cpp
- *Fix the issue which second infer with updated shape in dynamic loop doesn't update sliced layout.*
- *Fix the issue that the optimized reshape doesn't reinterpret output memory in update_output_layout()*
- *122739*
- *131544*
> [GPU] Fix dynamic loop's not matched issue during multiple shapes are inferenced

- src/core/src/pattern/op/optional.cpp
- src/core/tests/pattern.cpp
[TRANSFORMATIONS] Fix Optional to match even with no inputs
The Optional pattern type may create a wrong pattern to match if no inputs are provided to the Optional node. If no inputs present to the Optional type, it will not create an alternative branch(es) to check against resulting in the incorrect matching.
Fix that by adding a check for the number of inputs being 0.
Do a minor refactoring/renaming for the readability purposes.
CSV-133523
> [TRANSFORMATIONS] Fix Optional to match even with no inputs

- src/common/transformations/src/transformations/smart_reshape/matmul_sr.cpp
- src/inference/tests/functional/matmul_sr_tests.cpp
- *`ReshapeAMatMul` worked incorrect in case of using shared nodes as reshape input* 
- *Fix: to reconnect reshape input to new `shape_of` pattern*
- *[CVS-134625](https://jira.devtools.intel.com/browse/CVS-134625)*
> [TRANSFORMATIONS] Fix ReshapeAMatMul pattern to work with shared node as reshape input

- src/frontends/pytorch/src/translate_session.cpp
- *Fix the typo of the code (then -> than)*
- *Improve the error info here, to let developer know the size of output if the assertion fails.*
- *No ticket id*
> [PT FE] Fix typo and improve the error info.

- src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_kernel_ref.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- This PR fixes `Gather` not to set GATHER_AXIS_SHAPE_INFO_INDEX when input0 is static.
- It enables some functional tests again.
> [GPU] Fixed not to set GATHER_AXIS_SHAPE_INFO_INDEX when input0 is static

- tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_text_vectorization.py
- tests/layer_tests/tensorflow_tests/test_tf_Equal.py
**Details:** Test `tf.keras.TextVectorization` on white-space string input and Equal on empty string tensor.
**Ticket:** 135749
> [TF FE] Test TextVectorization on white-space string input and Equal on empty string tensor

- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- Increased FC tile_B size for INT4 shape agnostic kernel for improving context processing 
- 133444
> [GPU] Increase FC tile_b size for INT4 shape agnostic kernel 

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- *Element by element read is the bottle-neck in gemm_tiled kernel. Enable block-read when N and K size are aligned 4byte with N and K are leftover*.
- *Increasing tile_n_size has performance improvement when m_size and n_size are not shallow and n_size is aligned at 32.*
- *Add GEMM_TILE_M/N/K/SIMD environment variables for convenience.*
- *134279*
> [GPU] In gemm_tile_kernel, applied to use block read when N and K byte-size is aligned 4.

- src/frontends/onnx/frontend/CMakeLists.txt
- src/frontends/onnx/frontend/src/op/reduce.cpp
- src/frontends/onnx/frontend/src/op/reduce.hpp
- src/frontends/onnx/frontend/src/ops_bridge.cpp
- src/frontends/onnx/tests/__init__.py
- src/frontends/onnx/tests/models/reduce_max_18.prototxt
- src/frontends/onnx/tests/models/reduce_wrong_type_v3.prototxt
- src/frontends/onnx/tests/models/reduce_wrong_type_v4.prototxt
- src/frontends/onnx/tests/onnx_import.in.cpp
- src/frontends/onnx/tests/onnx_import_exceptions.cpp
- src/frontends/onnx/tests/tests_python/test_backend.py
- Extended ReduceMax by opsets 13,18,20
- Updated a using opset for ONNX to 20
- Added tests for additional supported types
- Enabled backend tests
- Closes #20555
> [ONNX] Extended ReduceMax by opsets 13,18,20

- src/plugins/intel_cpu/src/nodes/concat.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/concat.cpp
- *enable concat nspc layout inplace for channel only cases, with these concat node use inplace impl, urlnet model  gain performance benefits, and this(intermediate concat node is nspc layout but actually is one dimension) could be common case especially for models with 1D input*
- *130282*
> [CPU] Enable concat nspc layout inplace for urlnet model cases

- src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/rope_fusion.cpp
- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/rotary_pos_emb.cpp
- *Support new RoPE pattern of GPT-J*
- *Local test shows 17 % improvement for 2nd token latency for BF16 in `Intel(R) Xeon(R) Platinum 8468`*
- *CVS-134949*
> [CPU]Fix GPT-J RoPE fusion

- docs/articles_en/openvino-workflow/running-inference/optimize-inference.rst
- docs/articles_en/openvino-workflow/running-inference/optimize-inference/high-level-performance-hints.rst
Port from https://github.com/openvinotoolkit/openvino/pull/23575
Jira: 133389
* Added an indication on Latency being the default use for OV devices
* Streamlined the Optimize Inference article for better clarity.
> [DOCS] Latency highlight for OV devices + update of Optimize Inference for 2024

- .github/scripts/collect_github_metrics.py
- .github/workflows/send_workflows_to_opentelemetry.yml
Improvements and fixes for the script which sends GitHub Workflow metrics to a database. See also: [23484](https://github.com/openvinotoolkit/openvino/pull/23484)
> New DB schema for GitHub metrics script

- src/plugins/intel_gpu/src/graph/impls/ocl/gemm.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/multi_stage_primitive.hpp
- Since #22726 gemm is derived from multi-stage impl which had memory reuse flag enforced to false for all sub-classes.
- This patch enables memory reuse back for gemm kernel to reduce memory consumption.
- *135361*
> [GPU] Re-enable memory reuse for gemm

- src/tests/functional/plugin/conformance/test_runner/op_conformance_runner/src/read_ir/read_ir.cpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/base/utils/generate_inputs.hpp
- src/tests/functional/shared_test_classes/src/base/utils/generate_inputs.cpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/ov_tensor_utils.hpp
- src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
- *Move static const range initialization to `InData` structure*
- *[125993](https://jira.devtools.intel.com/browse/CVS-125993)*
> [IE TESTS][OP CONFORMANCE] Move `ConstRanges` range calculation to `InGenData` constructor

- src/plugins/intel_gpu/src/graph/impls/ocl/non_zero.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/non_zero_gpu_test.cpp
- Adds buffer reset to 0 in `count_nonzero` impl in case of empty input tensor as currently we may try to allocate random amount of memory in subsequent `gather_nonzero` call
> [GPU] Fix count non zero for empty input

- src/inference/src/compilation_context.cpp
- Calculate model weights hash in parallel in case of reading model from buffer
- CVS-134771
> Calculate model weights hash in parallel

- src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/stateful_sdpa_fusion.cpp
Limit the Concat layer to have maximum 3 children. The third one is allowed to be a ShapeOf op only (to support Mixtral).
- 135375
> [CPU] Fix SDPA pattern matching

- .github/scripts/collect_github_metrics.py
- .github/workflows/send_workflows_to_opentelemetry.yml
We can switch log level for GitHub metrics script only when the workflow is restarted with debug logging
> [chore] Use debug loglevel for github metrics script

- src/plugins/intel_gpu/include/intel_gpu/op/gemm.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/gemm.hpp
- src/plugins/intel_gpu/src/graph/gemm.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/gemm.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.h
- src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
- src/plugins/intel_gpu/src/plugin/transformations/broadcast_reshape_matmul_fusion.cpp
- src/plugins/intel_gpu/src/plugin/transformations/broadcast_reshape_matmul_fusion.hpp
- src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.cpp
- src/plugins/intel_gpu/src/plugin/transformations/op/gemm.cpp
- src/plugins/intel_gpu/src/plugin/transformations/op/indirect_gemm.cpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/transformations/broadcast_reshape_matmul_fusion_test.cpp
- Fuse `broadcast` and `reshape` layers into `gemm` layer for LLM's 2nd latency optimization
- before : [`broadcast`] --> [`reshape`] --> `gemm`
- after : `gemm`
- `gemm` is extended to have `input0_target_shape`, `input1_target_shape`, `input0_output_pattern` and `input1_output_pattern` from `broadcast` and `reshape` layers
- 128343
> [GPU] Extend gemm to fuse broadcast and reshape layers

- src/plugins/intel_gpu/src/plugin/transformations/clamp_fp16_output.cpp
- src/plugins/intel_gpu/tests/unit/transformations/clamp_fp16_output_test.cpp
- By PR(https://github.com/openvinotoolkit/openvino/pull/22245), `clamp_fp16_output` opt pass was moved to ngraph
- Because nodes such as eltwise(`Add`, `Subtract`, `Multiply`, `Divide`) that were fused into target node `gemm` are not supported in pattern, corresponding pattern was extended for this purpose
- 135060
> [GPU] Extend pattern for ClampFP16Output

- src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
> [CPU] Correct type configuration for i8 inner_product with f16 output

- src/frontends/onnx/tests/tests_python/utils/model_importer.py
- Significantly reduced amount of using RAM while testing
- May introduce test regression in multi-worker scenario (-n auto), but it isn't detected while validation
- 129958
> [ONNX] Reduced memory consumption while running tests

- src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
- src/plugins/intel_cpu/src/nodes/executors/precision_translation.cpp
- src/plugins/intel_cpu/src/nodes/executors/precision_translation.hpp
- The FC changes made in scope of #20486 were missed when rebasing #20718
- The context is: Even the system and the node does support bf16 precision we have to fall back to f32 in/out precision
due to lack of support for decompression with bf16 avx2_vnni_2 in oneDNN fork.
- To cover this limitation an additional type mapping parameter in form of std::function was introduced for disabling particular type mapping entry using a runtime check (isa support in this case)
- 122347
- 136163
> [CPU] Prohibit fc avx2_vnni_2 decompression for bf16 input

- docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/convert_python_model_objects.rst
- docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/supported_model_formats.rst
- docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/supported_model_formats/Convert_Model_From_ONNX.rst
- docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition/legacy_conversion_api/supported_model_formats/Convert_Model_From_TensorFlow.rst
- docs/articles_en/openvino_workflow/model_preparation/Convert_Model_IR.rst
Updating code examples with imports for ``convert_model`` and adding an example of how to save a converted model. This PR addresses the 120254 ticket.
Porting: https://github.com/openvinotoolkit/openvino/pull/23654
> [DOCS] Update code examples with imports and save_model for for 23.3

- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-convert-models-as-python-objects.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-convert-onnx.rst
- docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-convert-tensorflow.rst
- docs/articles_en/openvino-workflow/model-preparation/convert-model-to-ir.rst
Updating code examples with imports for convert_model and adding an example of how to save a converted model. This PR addresses the 120254 ticket. 
Porting: https://github.com/openvinotoolkit/openvino/pull/23654
> [DOCS] Update code examples with imports and save_model for 24.0

- .github/workflows/android_arm64.yml
New cmake fails to be imported in our Android environment
> Restrict cmake on Android build

- src/plugins/intel_cpu/src/shape_inference/custom/matmul.cpp
Add a check for input shapes compatibility to the custom CPU matmul shape inference subroutine.
> [CPU] Add a sanity check to MM shape infer

- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
- src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
- src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
- src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp
- *[CPU] [AARCH64] jit sigmoid*
- *CVS-133071*
> [CPU] [ARM64] jit exp

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- *add new axis mode*
- *CVS-105897, CVS-129991*
> [GPU] add new unsqueeze mode

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp
- src/plugins/intel_gpu/tests/unit/fusions/deconvolution_fusion_test.cpp
- *Fixed the cause of sporadic accuracy drops on several models on dGPU*
- [*CVS-134878*](https://jira.devtools.intel.com/browse/CVS-134878)
> [GPU] Fix checking that convolution supports fusings in onednn case

- src/plugins/intel_cpu/CMakeLists.txt
- src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/attn_memcpy.cpp
- src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/attn_memcpy.hpp
- src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
- *Use specific kernel for 2d f32 to bf16 conversion instead of multiple calls to cpu_convert*
- there is an invocation of parallel_for inside cpu_convert, when copying count is small such as only a head size: 128, each core will only copy ~2 elements if core number is 60, this will result false sharing. The cost can reduce from ~1700ms to ~860ms after the fix. SDPA path will copy a block of heads such as 32*128, so it will not easily be impacted but very small prompt size should also suffer from the problem.
- *Change the loop order from B,H,L to B,L,H due to the physical layout, can reduce the cost from ~860ms to ~830ms.*
- *Changes in vLLM:  https://github.com/ilya-lavrenov/vllm/pull/15*
- *ticket-id*
> [CPU] Optimize first inference latency for PagedAttention when running bf16

- tools/ovc/openvino/tools/ovc/convert_impl.py
- tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py
- *Import ModuleExtension under try-except*
- *ticket-id*
> Import ModuleExtension under try-except in OVC

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
- src/plugins/intel_gpu/src/kernel_selector/tensor_type.h
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
-  Optimize gemm_tiled_opt kernel for large matmul in dynamic shape execution by 1) increase n tile size and 2) apply manual software pipelining with A matrix prefetch. 
- Also fixed issues in fused eltwise input data loading for vector data.  
- 133445
> [GPU] Optimize gemm kernels for dynamic shape 

- src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
- *Fixed the order of parameters in `error.update` call to avoid misunderstanding in error message.*
- *N/A*
> [Tests] Fixed Error update in output comparison

- src/cmake/ov_parallel.cmake
When cross-compiling against a sysroot, system headers will not be at a place that starts with /usr. Update conditional check to exclude directories which have "/usr/include" in them to not add <sysroot>/usr/include as well.
- *item1*
- *...*
- *ticket-id*
> cmake: fix build when using sysroot

- src/plugins/intel_cpu/src/compiled_model.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_convert.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_deconv.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_eltwise.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_ie_scheduler.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_interpolate.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_mvn.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_pooling.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_reduce.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_transpose.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_utils.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_utils.hpp
- src/plugins/intel_cpu/src/plugin.cpp
- src/plugins/intel_cpu/src/plugin.h
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- CVS-132497
- CVS-129036
- CVS-134932
> [ARM CPU] New version of scheduler enabling 

- tests/layer_tests/pytorch_tests/test_scatter.py
**Details:** Xfail scatter_reduce test due to sporadicity
**Ticket:**
> [PT FE] Xfail scatter_reduce test due to sporadicity

- src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
- src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/include/reshape_inst.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/reshape.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/broadcast_gpu_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/broadcast/broadcast_kernel_base.cpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/tests/common/subgraphs_builders.hpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/reshape_si_test.cpp
- Dynamic padding produced by kv_cache prim was omitted by reshape w/o memory copy (prim was marked as optimized) which caused accuracy issues.
- This patch adds propagation logic for unsqueeze/squeeze cases and disables optimization for generic reshape if input tensor has dynamic pad. 
- Reverted https://github.com/openvinotoolkit/openvino/pull/23385
- Added func test for grouped query attention subgraph
- Added perf improvement for some broadcast cases to speedup unfused version of GQA
- *135242*, *135241*
> [GPU] Added padding propagation logic for reshape primitive

- src/plugins/intel_gpu/src/graph/graph_optimizer/concat_input_order.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp
- *Skip concat_input_order for an element which lies outside of the buffer range*
- *135790*
> [GPU] Skip concat_input_order

- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_emitter.cpp
- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_emitter.hpp
- src/plugins/intel_cpu/src/emitters/plugin/x64/jit_emitter.cpp
- src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp
- *[CPU] [ARM64] jit emitter pipeline fix*
> [CPU] [ARM64] jit emitter pipeline fix

- src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/mha_single_token.cpp
- *In the SDPA of bloom model, the beam table may be nullptr and should not directly be used.*
- *...*
- *ticket-id*
> [CPU] Fix segmentfault when there is no beam_table

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- Fixes accuracy issue for fc_bf_tiled kernel in for the cases with input tensor rank = 3 and padding along axis 1
> [GPU] Fixed fc bf_tiled kernel for the case with input padding

- src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/group_convolution.cpp
- *Reverse the weight spatial kernel shape when autopadding*
- *130861*
> [GPU] Reverse kernel shape when autopadding

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
Reorder is main bottle-neck(roughly 40%) in SD1.5(vae_decoder) on MTL.
Reorder in target pattern is always added at Reshape primitive creation, because of Reshape's in/out dimens are different.
We can get huge improvement to remove heavy Reorders from Using planner format in Conv.
Target pattern(Conv - Reorder - Reshape -MVN) repeats 14times  in vae_decoder.
- *134278*
> [GPU] Remove heavy Reorder in target pattern(Conv - Reorder - Reshape -MVN)

- src/common/low_precision_transformations/src/convolution.cpp
- src/common/low_precision_transformations/src/convolution_backprop_data.cpp
- src/common/low_precision_transformations/tests/convolution_backprop_data_transformation.cpp
- src/common/low_precision_transformations/tests/convolution_qdq_transformation.cpp
`ConvolutionTransformation` propagates multiplies from data and weights paths, and then fuses these 2 scales into one.
The bug was In mixed precision scenario (which is used on GPU device) when data dequantization was not produced by LPT but existed in the model. The propagated scales from data and weights had different precisions: scale from data did not change precision (f16), whereas precision of scale from weights was set to `deqPrecision=f32` - this led to element type inconsistency error at the scales fusion stage. In this PR, both scales are converted to `deqPrecision` to align scales element types and avoid precisions incosistency.
The same issue existed in `ConvolutionBackpropDataTransformation`: it was fixed too.
- *CVS-130598*
> [LPT] ConvolutionTransformatin: mixed precision fix

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_padding_test.cpp
- add reorder to avoid inserting padding to mvn before ocl conv.
- mvn does not support padding.
- 136385
> [GPU] add reorder between mvn and conv.

- src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/mha_single_token.cpp
- Since PagedAttention usage model assumes each sequence have arbitrary length we are leveraging TBB dynamic partitioning to balance CPU utilization
> [CPU] PagedAttention dynamic partitioning

- src/frontends/onnx/frontend/src/op/batch_norm.cpp
- src/frontends/onnx/frontend/src/op/batch_norm.hpp
- src/frontends/onnx/frontend/src/ops_bridge.cpp
- src/frontends/onnx/tests/models/batchnorm_opset1.prototxt
- src/frontends/onnx/tests/models/batchnorm_opset14.prototxt
- src/frontends/onnx/tests/models/batchnorm_opset15.prototxt
- src/frontends/onnx/tests/models/batchnorm_opset6.prototxt
- src/frontends/onnx/tests/models/batchnorm_opset7.prototxt
- src/frontends/onnx/tests/models/batchnorm_opset9.prototxt
- src/frontends/onnx/tests/onnx_import.in.cpp
- *Addition of Batchnorm opset 1 6 7 9 14 & 15*
- *Creation of the tests CPP for the respective opset, and their prototxt models.*
- 20554 : [20554](https://github.com/openvinotoolkit/openvino/issues/20554)
- 18485 :  [18485](https://github.com/openvinotoolkit/openvino/issues/18485)
> [ONNX] Extended BatchNorm to support opsets 1-6-7-9-14-15

- .github/workflows/coverity.yml
- .github/workflows/linux.yml
- .github/workflows/linux_arm64.yml
- .github/workflows/mac.yml
- .github/workflows/mac_arm64.yml
- .github/workflows/windows.yml
Reverts openvinotoolkit/openvino#23706
Probably causes Windows JS API job failure
> Revert "Use only Java API, Custom ops in contrib build"

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/softmax_gpu_bf.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_bf.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/softmax_gpu_test.cpp
- *Support sub_group_read for the case with SUB_GROUP_BLOCK_SIZE 1*
- *Rearrange leftovers to support 16 bytes aligned for sub group block write*
- *Use float value for summation in softmax kernel for accuracy issue*
- *Increase STACK_SIZE of my_chunk to support aligned_offset and leftovers*
- *Add unit test" 
- *133443*
> [GPU] Optimize softmax kernels

- src/plugins/hetero/src/compiled_model.cpp
- src/plugins/hetero/src/graph_debug_dump.cpp
- src/plugins/hetero/src/plugin.cpp
- src/plugins/hetero/src/subgraph_collector.cpp
- Fix some scan coverity issues
- CVS-137445
> [HETERO] Fix some scan coverity issues

- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/matmul_weights_decompression.cpp
- *This PR fixes dynamic quantization accuracy for MatMuls with unaligned src and weights group sizes*
- *OneDNN fork PR: https://github.com/openvinotoolkit/oneDNN/pull/239*
> [CPU] Fixed dynamic quantization accuracy issue

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- This PR fixes gemm_tiled_opt kernel for the dynamic case when TILE_N=32 and output is transposed (and X is not the last dim). This case requires proper X-dim offset calculation for each WI in the subgroup. This PR partially fixes gemma models accuracy.
136260, 137141
> [GPU] Fix gemm_tiled_opt kernel accuracy for the dynamic case with TILE_N=32 and transposed output shape

- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/nms_rotated.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/base/ov_subgraph.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/base/utils/compare_results.hpp
- src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
- src/tests/functional/shared_test_classes/src/base/utils/compare_results.cpp
- src/tests/functional/shared_test_classes/src/single_op/generate_proposals.cpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/ov_tensor_utils.hpp
- src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
- *Inference precision is added as an argument to tensor comparation for calculation of default values for `abs_threshold` and `rel_threshold`*
- *Extend tensor comparation by `topk_threshold`*
-  - *Extend tensor comparation by `mvn_threshold`*
- *[136679](https://jira.devtools.intel.com/browse/CVS-136679)*
> [ IE TESTS ] Extend tensor comparation

- src/tests/functional/plugin/shared/include/behavior/ov_plugin/query_model.hpp
- src/tests/functional/plugin/shared/src/behavior/ov_plugin/life_time.cpp
- src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp
- *Skip some tests  based on  Import/Export/QueryModel in API conformance*
- *[136558](https://jira.devtools.intel.com/browse/CVS-136558)*
> [IE TESTS] Skip Import/Export/QueryModel tests for SW plugin from API Conformance

- src/bindings/python/tests/test_graph/test_dyn_attributes.py
- src/bindings/python/tests/test_graph/test_manager.py
- src/bindings/python/tests/test_graph/test_node_factory.py
- src/bindings/python/tests/test_runtime/test_core.py
- Fix new linter errors introduced with newly released [flake8-pytest-style](https://pypi.org/project/flake8-pytest-style/#history)
- N/A
> Fix Python linter errors introduced by new `flake8-pytest-style` version

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_padding_test.cpp
- add reorder to avoid inserting padding to mvn before ocl conv.
- mvn does not support padding.
- 136385
> [GPU] add reorder between mvn and conv. (#23670)

- src/core/src/op/logical_not.cpp
- src/plugins/template/tests/functional/op_reference/logical_not.cpp
- Add u8 support in op evaluate of logical_not. It is called in cpu_impl of GPU plugin and GPU plugin is using u8 as boolean from transformed graph.
- 124503
> [GPU] add u8 support in evaluate of logical_not

- src/plugins/intel_gpu/src/runtime/execution_config.cpp
- src/plugins/intel_gpu/tests/functional/behavior/inference_precision.cpp
Changed `ExecutionMode::ACCURACY` mode behaviour on GPU. This patch forces `ov::hint::inference_precision` to `ov::element::undefined` if `ExecutionMode::ACCURACY` mode was configured by user and allows to keep original model's precision unchanged.
Additionally, this change allows users to specify `ov::element::undefined` as inference precision.
Note: `ov::hint::inference_precision` has higher priority than `ov::hint::execution_mode` for all of the cases
- 136166, 131808
> [GPU] Changed ExecutionMode::ACCURACY mode behaviour on GPU

- src/plugins/intel_gpu/src/plugin/variable_state.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp
- Fix accuracy issue due to wrong pad size after set_state call
> [GPU] Remove paddings on set_state() call

- src/common/transformations/include/ov_ops/gather_compressed.hpp
- src/core/dev_api/openvino/runtime/string_aligned_buffer.hpp
- src/core/include/openvino/op/constant.hpp
- src/core/src/runtime/string_aligned_buffer.cpp
- src/core/tests/constant.cpp
- src/core/tests/string_align_buffer_test.cpp
Fix segfault in Constant when destroy not initialized string buffer:
- Initialize buffer in Constant before exception throw to avoid segfault.
- Improve default ctor of` StringAlignedBuffer`.
- Set only required members in `SharedStringAlignedBuffer`'s dtor.
- Add unit test for `StringAlignedBuffer`.
- Use template `get_ptr` instead cast.
- Optimize assertion error message.
- Relate to [CVS-119224](https://jira.devtools.intel.com/browse/CVS-119224)
> [core] Fix segfault in Constant when destroy not initialized string buffer

- src/bindings/python/src/openvino/runtime/op/__init__.py
- src/bindings/python/src/pyopenvino/graph/ops/paged_attention_extension.cpp
- src/bindings/python/src/pyopenvino/graph/ops/paged_attention_extension.hpp
- src/bindings/python/src/pyopenvino/pyopenvino.cpp
PagedAttention operation exposed in Python API only for easier vLLM openvino integration. It is not intended to be used outside our integration work in vLLM and similar applications where we can use PagedAttention. Exposed as a hidden part of API, will not be documented. Connected to already existing implementation in CPU plugin.
Operation is not a part of any public opset.
> PagedAttention experimental operation

- src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
- *dnnlFCTypeMapping: fixed output precision for INT8 case*
- *CVS-137666*
> [CPU] FC executor config fix for INT8 case

- src/common/transformations/src/transformations/low_precision/mark_dequantization_subgraph.cpp
- src/common/transformations/src/transformations/op_conversions/convert_gather_to_compressed.cpp
- src/core/src/op/transpose.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/reorder.cpp
- src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
- src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
- src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernel_selector.cpp
- src/plugins/intel_gpu/src/plugin/ops/fully_connected.cpp
- src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.cpp
- src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.hpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- Compressed int4 weight is now supported with OneDNN
- transpose.cpp change for int4 support from ngraph transform is a temporal solution. To be handled from GPU plugin.
- 124115
> [GPU] int4 weight compression for onednn

- src/plugins/intel_cpu/src/node.cpp
- src/plugins/intel_cpu/src/node.h
- src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
- src/plugins/intel_cpu/src/nodes/fullyconnected.h
- Shapes inference can result into an appearance of the zero shape memory on the node inputs. Such nodes are considered as non-executable, so no prepareParams are called for them, thus no
executors are created. So, it is necessary to avoid setting numa id for non-executable nodes.
- Currently seg fault happens when node gets zero shape memory on the inputs.
Issue introduced in scope of:
- https://github.com/openvinotoolkit/openvino/pull/23593
- *CVS-137763*
> [CPU] Do not assign Numa id to a node with zero shape input

- tests/constraints.txt
- tests/model_hub_tests/pytorch/hf_transformers_models
- tests/model_hub_tests/pytorch/requirements.txt
- tests/model_hub_tests/pytorch/test_gfpgan.py
- tests/model_hub_tests/pytorch/test_lightglue.py
- *Added `kornia` dependency for lightglue model*
- *Disable GFPGAN since it doesn't support latest `torchvision`*
- *Remove `transfo-xl-wt103` as not supported on latest `transformers`*
- *Remove XFAIL from `facebook/levit-128S`*
- *ticket-id*
> [PT FE] Fix GHA model tests

- docs/articles_en/openvino-workflow/model-preparation/conversion-parameters.rst
Port from https://github.com/openvinotoolkit/openvino/pull/23864
Added missing comma in Python code in the Conversion Parameters article.
Jira: 137610
> [DOCS] Typo fix in Conversion Parameters article for 2024.1

- docs/articles_en/openvino-workflow/model-preparation/conversion-parameters.rst
Port from https://github.com/openvinotoolkit/openvino/pull/23864
Added missing comma in Python code in the Conversion Parameters article.
Jira: 137610
> [DOCS] Typo fix in Conversion Parameters article for 2024

- src/plugins/intel_npu/src/al/include/npu.hpp
- src/plugins/intel_npu/src/al/src/npu.cpp
- src/plugins/intel_npu/src/backend/include/zero_backend.hpp
- src/plugins/intel_npu/src/backend/include/zero_device.hpp
- src/plugins/intel_npu/src/backend/include/zero_init.hpp
- src/plugins/intel_npu/src/backend/src/zero_backend.cpp
- src/plugins/intel_npu/src/backend/src/zero_device.cpp
- src/plugins/intel_npu/src/backend/src/zero_init.cpp
- src/plugins/intel_npu/src/plugin/include/backends.hpp
- src/plugins/intel_npu/src/plugin/include/metrics.hpp
- src/plugins/intel_npu/src/plugin/src/backends.cpp
- src/plugins/intel_npu/src/plugin/src/metrics.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- *Moving getDriverVersion to the backend makes more sense, and creating a new helper, getDriverExtVersion that would be used for plugin batching feature to decide when to use batching on auto mode or only on compile.*
- *Because of E-117498 we need to decide when Compiler or Auto mode for batching to be used.*
- *DriverExtVersion should be also updated by the driver team for this to work as expected.*
- *E-117498*
> Move driver version to backend and create getDriverExtVersion method

- .github/workflows/job_debian_packages.yml
- .gitmodules
- src/bindings/python/CMakeLists.txt
- Install openvino-telementry as part of `python3-openvino` debian package
- Ported https://github.com/openvinotoolkit/openvino/pull/23913
- Closes https://github.com/openvinotoolkit/openvino/issues/23876
> Add openvino-telemetry to debian / rpm package

- src/frontends/tensorflow/docs/supported_ops.md
- src/frontends/tensorflow/src/op_table.cpp
- tests/layer_tests/tensorflow_tests/test_tf_StringToHashBucketFast.py
**Details:** Support StringHashBucketFast operation. Needed for several models from TF Hub. Merge after https://github.com/openvinotoolkit/openvino_tokenizers/pull/115
**Ticket:**
> [TF FE] Support StringHashBucketFast operation

- .github/workflows/linux_arm64.yml
After the latest release https://pypi.org/project/h5py/#history stopped being installed as a Python module on arm - it tries to be built from sources and there is a missing dependency for this. Trying to fix it without restricting the module version...
> [GHA] Possible workaround for the latest h5py issue on arm

- src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_update_kernel_ref.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/scatter_update_gpu_test.cpp
- The rule of filling data into shape_info[] is to skip it for static shape input 
- However, in scatter_update kernel, that skipping has not been applied
- If there are static shape inputs among the inputs, the number of static shape input should be applied to the index calculation of shape_info[]
- 135859
> [GPU] fix scatter_update in case of mixed input with dynamic and static

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_bfyx_gemm_like_fp16.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_gemm_like.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/convolution.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- Change acceptable filter x size of convolution_bfyx_gemm_like kernel to avoid kernel build error and slower performance than ref kernel from 64 to 32
- 137837
> [GPU] Change acceptable filter x size of convolution_bfyx_gemm_like kernel to avoid kernel build error and slower performance than ref kernel

- .github/workflows/linux_arm64.yml
Porting https://github.com/openvinotoolkit/openvino/pull/23959 to releases/2024/1 branch
> (port #23959) [GHA] Possible workaround for the latest h5py issue on arm

- src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/shape_predictor.hpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- src/plugins/intel_gpu/src/plugin/variable_state.cpp
- src/plugins/intel_gpu/src/runtime/shape_predictor.cpp
- src/plugins/intel_gpu/tests/unit/module_tests/shape_predictor_test.cpp
- *Disable predict_preallocation_shape for blocked format*
- *Fix to use layout instead of shape and data_type*
- *132334*
> [GPU] Disable predict_preallocation_shape for blocked format

- src/core/reference/include/openvino/reference/autobroadcast_binop.hpp
- Split `autobroadcast_binop` to dedicated broadcast functions.
- Minor size optimizations.
-[CVS-127056](https://jira.devtools.intel.com/browse/CVS-127056)
> [core] Split autobroadcast_binop function to dedicated functions

- src/bindings/python/wheel/setup.py
- *The PR adds RISCV64 arch for python wheel setup to fix the following error during build on the target machine:*
```
[100%] Building Python wheel openvino-2024.2.0-14978-cp310-cp310-manylinux_2_36_riscv64.whl
Processing /home/sipeed/openvino/openvino/src/bindings/python/wheel
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/home/sipeed/openvino/openvino/src/bindings/python/wheel/setup.py", line 50, in <module>
OV_RUNTIME_LIBS_DIR = os.getenv("OV_RUNTIME_LIBS_DIR", f"runtime/{LIBS_DIR}/{ARCH}/{CONFIG}")
NameError: name 'ARCH' is not defined …
```
> [Python][Wheel] Added RISCV64 support for wheel setup

- src/plugins/template/tests/functional/op_reference/reshape.cpp
- Used actual shape for expected output tensor.
- CVS-137202
> [Tmpl test] Reshape: enable whole Tensor comparison

- src/plugins/template/tests/functional/op_reference/grn.cpp
- Used actual shape in expected output tensor.
- CVS-137166
> [Tmpl test] GRN: enable whole Tensor comparison

- src/frontends/tensorflow/tests/requirements.txt
- tensorflow package depends on h5py and starting from 3.11 version this package could not be installed on linux arm64 systems due to absent libraries (libhdf5-dev), see https://github.com/openvinotoolkit/openvino/actions/runs/8631731088/job/23660776687?pr=23909
- 
- *ticket-id*
> [GHA] Freeze h5py version

- src/plugins/intel_cpu/src/cpu_memory.cpp
- src/plugins/intel_cpu/src/cpu_memory.h
- src/plugins/intel_cpu/src/cpu_shape.cpp
- src/plugins/intel_cpu/src/cpu_types.cpp
- src/plugins/intel_cpu/src/cpu_types.h
- src/plugins/intel_cpu/src/infer_request.cpp
- src/plugins/intel_cpu/src/memory_desc/cpu_blocked_memory_desc.cpp
- src/plugins/intel_cpu/src/memory_desc/cpu_blocked_memory_desc.h
- src/plugins/intel_cpu/src/memory_desc/cpu_memory_desc.h
- src/plugins/intel_cpu/src/memory_desc/cpu_memory_desc_utils.cpp
- src/plugins/intel_cpu/src/memory_desc/cpu_memory_desc_utils.h
- src/plugins/intel_cpu/src/memory_desc/dnnl_blocked_memory_desc.cpp
- src/plugins/intel_cpu/src/memory_desc/dnnl_blocked_memory_desc.h
- src/plugins/intel_cpu/src/memory_desc/empty_memory_desc.h
- src/plugins/intel_cpu/src/memory_state.cpp
- src/plugins/intel_cpu/src/nodes/common/arbitrary_order_desc_creator.cpp
- src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_convolution_primitive.cpp
- src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected.hpp
- src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected_primitive.cpp
- src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
- src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
- src/plugins/intel_cpu/src/nodes/fullyconnected.h
- src/plugins/intel_cpu/src/nodes/memory.cpp
- src/plugins/intel_cpu/src/nodes/non_max_suppression.cpp
- src/plugins/intel_cpu/src/nodes/rnn.cpp
- src/plugins/intel_cpu/tests/unit/memory_desc/empty_memory_desc.cpp
- The example use case is to generalize processing of the operation
with and without bias.
When the operation has no bias, it is possible to create memory
using empty memory descriptor, and use the exact same code as if bias
actually exists.
- Many headers are affected to break the chain of implicit intersecting includes
- 131590
> [CPU] Introduce empty undefined memory descriptor

- src/core/src/pass/visualize_tree.cpp
- *Skip visualizing symbols on static dimensions*
> [VISUALIZE_TREE] Skip visualizing symbols on static dimensions

- src/plugins/intel_cpu/src/cpu_memory.cpp
- If a process lacks CAP_SYS_NICE capability, mbind fails with an error "Operation not permitted". We should either ignore the result (just log) or throw an exception. Also, as an option, we could check if CAP_SYS_NICE is set before performing any mbind related logic.
- For now just log to the debug
> [CPU] Avoid printing mbind errno message to stderr

- src/plugins/intel_gpu/src/graph/impls/ocl/strided_slice.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/strided_slice/strided_slice_kernel_ref.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/strided_slice.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/strided_slice.cpp
- Add proper handling of ellipsis mask for static and dynamic scenarios for Strided Slice operation
- 138037
> [GPU] Add ellipsis mode support for strided slice

- .github/scripts/external_pr_labeller.py
- .github/scripts/external_pr_labeller/labeller.py
- .github/workflows/labeler.yml
- This PR introduces a PR labeller for external PRs. It will add the `ExternalPR` label to a PR whose author is not in the `openvino` collaborator list.
It will not work from a PR as it has a `pull_request_target` trigger for the secrets. I've tested it locally.
- *135090*
> [CI] [GHA] Introduce external PR labeller

- tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_conv_3d.py
- tests/layer_tests/tensorflow_tests/test_tf_BinaryOps.py
**Details:** Xfail Mod and FloorDiv tests due to sporadic inference mismatch results. Correct Conv3D test to decrease workload to pass timeout.
**Tickets:** 138904, 138713
> [TF FE] Xfail Mod and FloorDiv tests and correct Conv3D test

- src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
Changes in intel-npu plugin:
- Removing ov::internal properties from public supported_properties list
- publishing model_priority property in supported_properties
> [intel-npu] Unpublishing ov::internal properties

- src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/fetch_weights.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/int4_utils.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_weights_int4.cl
- src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/reorder/reorder_weights_int4.cpp
- src/plugins/intel_gpu/src/kernel_selector/tensor_type.cpp
- src/plugins/intel_gpu/src/kernel_selector/tensor_type.h
- src/plugins/intel_gpu/src/runtime/format.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- Currently, in dynamic shape, ofm size is fixed as 2 because it is is tightly coupled by weight layout (i.e., tile_ofm == 2 requires os_iyx_osv32 weight format)
- For Vec*Mat case (b==1, used for 2nd+ token generation in LLMs) with small output size N, this configuration is not good because of the limited # of gpu threads. 
- To increase GPU threads, needed to 1) reduce the ofm size to 1 2) But still share the weight format with first token case where ofm=2 is good. 
- Previously the os_iyx_osv32 weight format was packing int4 weight with the following order:
k0_f0f16 | k0_f1f17 | .... | k0_f15f31 || k1_f0f16 | k1_f1f17 | ... | k1_f15f31
- To use common weight format for ofm=1 and ofm=2, implemented a new weight format for int4 dtype,  where the weight is stored int the following order: …
> [GPU] Optimize FC kernels for INT4 vector * matrix with short output size

- src/inference/src/dev/threading/cpu_streams_executor_internal.cpp
- src/inference/src/os/cpu_map_info.hpp
- src/inference/src/os/lin/lin_system_conf.cpp
- src/inference/src/os/mac/mac_system_conf.cpp
- src/inference/src/os/win/win_system_conf.cpp
- src/inference/tests/unit/cpu_reserve_test.cpp
- Fix wrong binding to 6E+1P cores on MTL windows with command "-pin HYBRID_AWARE -nthreads 7"
- Correct binding cores: 6P+1E
- Add test case
- Add CPU debug on Windows and Mac
- *CVS-138630*
> Correct the CPU pinning on platforms which P/E Cores are in interleave sequence

- docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application/model-representation.rst
Port from https://github.com/openvinotoolkit/openvino/pull/23482
* Fixed examples of Tensor Names,
* Added an example of ov::element::Type for both Python and C++
> [DOCS] Fixing Tensor Names examples in Model Representation for 2024.0

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
_Dynamic convolutions with explicit padding run planar bfyx format in clDNN.
But this limitation is only for clDNN NOT oneDNN. Because unexpected format selection in dynamic convolution, SD1.5 in platform used dpas always run clDNN and it caused bad performance._
- *138632*
> [GPU] Fix wrong dynamic convolution selection in SD1.5 dynamic dpas platform

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
Dynamic convolution with padding run cldnn NOT onednn. cldnn test run with onednn and it caused can't find kernel selection issue.
- *item1*
- *...*
- *ticket-id*
> [GPU] Hotfix dgpu unit-test failure.

- src/plugins/intel_gpu/src/plugin/transformations/unsqueeze_broadcast_reshape_matmul_fusion.cpp
- src/plugins/intel_gpu/tests/unit/transformations/unsqueeze_broadcast_reshape_matmul_fusion_test.cpp
- Generalize `UnsqueezeBroadcastReshapeMatmulFusion` pass for non-const broadcast's input support
- Update test case for `UnsqueezeBroadcastReshapeMatmulFusion` pass
- 136386
> [GPU] Update UnsqueezeBroadcastReshapeMatmulFusion pass for non-constant input pattern support

- src/plugins/intel_npu/src/al/include/intel_npu/al/config/common.hpp
- Adding f32 to supported values of INFERENCE_PRECISION_HINT
[ - *ticket-id*](https://jira.devtools.intel.com/browse/CVS-138219)
> [intel-npu] Adding f32 to supported values of INFERENCE_PRECISION_HINT

- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- Register BACKEND_COMPILATION_PARAMS in properties
- *[EISW-112824](https://jira.devtools.intel.com/browse/EISW-112824)* The option was added to compiler as part of this ticket. But we also need this option registered to properties in order to start using it with single image test
> [EISW-112824] Register missing compiler option

- .github/workflows/code_style.yml
Reverts openvinotoolkit/openvino#24214
The original issue should be fixed now: https://github.com/microsoft/linux-package-repositories/issues/130#issuecomment-2074910628
> Revert "Workaround apt issues on ubuntu 22"

- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- tile_ofm should be set as 1 only when the weight layout is os_is_yx_osv32_isv2
- *ticket-id*
> [GPU] Fix crash in fc tiled kernel

- .github/workflows/code_style.yml
- cmake/developer_package/clang_format/clang_format.cmake
- src/bindings/c/include/openvino/c/deprecated.h
- src/bindings/js/node/src/compiled_model.cpp
- src/bindings/python/src/pyopenvino/core/compiled_model.cpp
- src/common/itt/include/openvino/itt.hpp
- src/core/include/openvino/core/deprecated.hpp
- src/core/include/openvino/core/extension.hpp
- src/core/include/openvino/core/rtti.hpp
- src/core/src/itt.hpp
- src/core/src/opsets/opset.cpp
- src/core/tests/type_prop/generate_proposals.cpp
- src/frontends/ir/src/ir_deserializer.cpp
- src/inference/src/cpp/core.cpp
- src/inference/src/dev/threading/parallel_custom_arena.cpp
- src/inference/tests/unit/cpu_map_parser/parser_windows.cpp
- src/plugins/intel_npu/src/al/include/intel_npu/al/config/config.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/graph_comparator.hpp
- Migration to clang-format-15 which is available in Ubuntu 22.04
> Migration to clang-format-15

- src/common/snippets/src/lowered/pass/cleanup_loop_offsets.cpp
- src/common/snippets/src/lowered/pass/fuse_loops.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_copy_b_emitter.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_copy_b_emitter.hpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_emitter.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_emitter.hpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/verbose.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_copy_b.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_copy_b.hpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.hpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/set_brgemm_copy_b_buffers_shape.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/set_brgemm_cpu_blocking_params.cpp
- src/plugins/intel_cpu/src/transformations/tpp/x64/pass/lowered/set_tpp_leading_dim.cpp
- src/plugins/intel_cpu/tests/unit/snippets_transformations/lowered/buffer_allocation.cpp
- *Added brgemm blocking support for bf16 and int8 precisions: in this case blocking loops are shared between BrgemmCopyB and BrgemmCPU nodes*
- *Reduced allocation shapes of input brgemm buffers in case of low precision*
- *CVS-115165*
> [Snippets] MHA: blocking by K and N for bf16/int8 precisions

- src/plugins/intel_gpu/src/plugin/program_builder.cpp
SD1.5 weight compressed model's Perf issue in a770.
Even though static model, set formats likes dynamic mode. It cause huge performance issues.
- *138632*
> [GPU] Fix unintentional allow_new_shape_infer true in static model.

- src/plugins/intel_npu/thirdparty/CMakeLists.txt
The commit eb025fad1e800280746eb2d543818bece701c9c6 breaks the build when `CXXFLAGS` or `CFLAGS` have a specific `-Werror` flag.
For example, when `CXXFLAGS` have `-Werror=format-security`, the build fails with this message:
```
c++: warning: =format-security: linker input file unused because linking not done
c++: error: =format-security: linker input file not found: No such file or directory
```
That's because every occurrence of the `-Werror` string is being replaced in the original `CXXFLAGS` and `CFLAGS` variables. So, if they contain `-Werror=<something>`, it will become just `=<something>`, which will be an unrecognized option.
The current commit fixes this by appending `-Wno-error` to `CXXFLAGS` and `CFLAGS` to properly disable errors on warnings.
> [intel-npu] Fix build when using specific Werror

- cmake/developer_package/target_flags.cmake
- Should help with https://github.com/conan-io/conan-center-index/pull/23754
- Taken from https://github.com/openvinotoolkit/openvino/pull/23534
> Fixed case when users explicitly pass different gcc ABI via cxx flags

- src/plugins/intel_npu/src/plugin/include/compiled_model.hpp
- src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- The first requirement from the attached ticket: "Move call of transformations to CompiledModel constructor. Since the CompiledModel constructor requires input and output ports, such ports should be passed before transformations are called, otherwise we can have issues when transformation mistakenly changed names of tensors and we have issues like https://jira.devtools.intel.com/browse/CVS-122932"
- Moving the compilation step inside the `intel_npu::CompiledModel` constructor led to the divergence of the function signature required by the two methods calling the constructor: [`intel_npu::Plugin::compile_model`](https://github.com/razvanapetroaie/openvino/blob/60dec94dc466ca41002cf5a996b005c00264af91/src/plugins/intel_npu/src/plugin/src/plugin.cpp#L510-L516) and …
> [CVS-132132][NPU] Move the model transformations to the "CompiledModel" constructor

- cmake/developer_package/compile_flags/os_flags.cmake
- Ubuntu 24.04 support with gcc 13.0
- CVS-138654
> Use -Wabi only for gcc less 13.0

- docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst
Fixing code snippet for 4-bit compression in `Weight Compression` article. 
Porting: https://github.com/openvinotoolkit/openvino/pull/24306
> [DOCS] Fixing code snippet in Weight Compression

- src/plugins/intel_gpu/include/intel_gpu/runtime/internal_properties.hpp
- src/plugins/intel_gpu/src/plugin/program_builder.cpp
- src/plugins/intel_gpu/src/runtime/execution_config.cpp
- src/plugins/intel_gpu/src/runtime/kernels_cache.cpp
- We found a performance issue when multiple `gemm_tiled_opt` kernels are built as a single program.
- This PR adds a WA to lower the kernel batch size to four in the case of dynamic models.
> [GPU] smaller kernel batch size for dynamic models

- src/common/snippets/src/op/serialization_node.cpp
- *Added `subtensor` serialization to `SerializationNode`. It's really helpful for work with tailed `Brgemm` nodes.*
- *N/A*
> [Snippets] Added subtensors to SerializationNode::visit_attributes

- src/plugins/intel_gpu/include/intel_gpu/runtime/device_info.hpp
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp
- Recent iGPU has separate cache. In such case, it is necessary to use usm_device if possible.
- 139455
> [GPU] Transfer to usm_device if GPU architecture has separate cache

- src/plugins/intel_npu/src/plugin/src/backends.cpp
- *Return false in case the backend is not available when using offline compilation without having a backend*
- *ticket-id*
> [NPU] Return false in case backend is not available

- src/plugins/intel_cpu/src/graph.cpp
- src/plugins/intel_cpu/src/node.cpp
- src/plugins/intel_cpu/src/node.h
- By combining move and execute into single function, so
isExecutable() check is performed only once
- It turned out isExecutable() check is not that lightweight. For some models it adds noticeable (about 5%+) latency overhead. So, the solution is to group 'execute' and 'toNumaNode' into a single function and perform the check only once.
- fixes overhead introduced by another fix:
https://github.com/openvinotoolkit/openvino/pull/23849
- 138220
> [CPU] Reduce overhead of moving to a numa node

- cmake/developer_package/api_validator/api_validator.cmake
`CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION` is supposed to be set by CMake when Windows SDK is installed in the system, but it works only for Visual Studio generators. As we use Ninja, we set this variable manually, trying to mimic the default behavior.
> Manually define CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION

- src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
- src/plugins/intel_gpu/src/graph/fully_connected.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/mark_shape_of_subgraphs.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/adaptive_pooling.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/broadcast.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/ctc_greedy_decoder.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/dft.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/eltwise.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/fully_connected.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
- src/plugins/intel_gpu/src/graph/impls/ocl/kv_cache.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/range.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/softmax.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/strided_slice.cpp
- src/plugins/intel_gpu/src/graph/include/program_node.h
- src/plugins/intel_gpu/src/graph/kv_cache.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/graph/program_node.cpp
- src/plugins/intel_gpu/src/graph/reshape.cpp
- src/plugins/intel_gpu/src/runtime/format.cpp
- src/plugins/intel_gpu/src/runtime/layout.cpp
- Reuse kernel selector params object created on impl init in update_dispatch_data() function for some primitives and just update shapes of in/out/fused tensors.
- Small improvements for `fill_shape_info_data`
- Slightly improves host code execution time (~2-3ms)
- Save new_shape_infer flag once in program to avoid config access overhead in runtime
- CVS-140264, CVS-140267
> [GPU] Optimize update dispatch data for few primitives

- src/plugins/intel_cpu/src/nodes/reduce.cpp
- src/plugins/intel_cpu/src/nodes/reduce.h
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/reduce.cpp
- *Avoid broadcast for depthwise fusion with a shape pattern where channel is the only non-one dimension, e.g., [1, C], [1, C, 1, ..., 1].*
- *Add test cases that can reproduce this issue beforehand.*
- *[CVS-138063](https://jira.devtools.intel.com/browse/CVS-138063)*
> [CPU] Fix issue on depthwise fusion for Reduce node

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- *[138780](https://jira.devtools.intel.com/browse/CVS-138780)*
> [GPU] Disabling use OneDNN for FC with zero_point_scalar and group size that is not a power of two

- src/plugins/intel_gpu/include/intel_gpu/runtime/memory_pool.hpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/runtime/memory_pool.cpp
- Not to assign a memory slot for a memory request < 50% of the available memory
- 137490
> [GPU] Remove redundant usage of memory pool 

- src/core/tests/model.cpp
- Disable add_output_performance test
- CVS-140440
- CVS-140158
- CVS-134286
> Disable add_output_performance test

- docs/articles_en/get-started/install-openvino/install-openvino-conda.rst
Adding instructions for installation of `opencl-icd-system` package which enables users to select a GPU device for OpenVINO inference.
> [DOCS] Enabling GPU for inference on systems with conda-forge

- docs/articles_en/get-started/install-openvino/install-openvino-conda.rst
Adding instructions for installation of `opencl-icd-system` package which enables users to select a GPU device for OpenVINO inference.
Porting: https://github.com/openvinotoolkit/openvino/pull/24390
> [DOCS] Enabling GPU for inference on systems with conda-forge - port to 24.1

- src/plugins/intel_gpu/src/runtime/layout.cpp
- src/plugins/intel_gpu/tests/unit/module_tests/layout_test.cpp
- This PR updates the shortcut logic in `layout::transform` for 3D layouts.
- 3D layouts are handled as `bfy`, not as `bfx` in the GPU plugin.
> [GPU] Update of the shortcut in layout::transfrom for 3D layouts

- tools/mo/openvino/tools/mo/front/tf/extractors/utils.py
- tools/mo/unit_tests/moc_tf_fe/test_models/model_add_with_undefined_constant.pbtxt
- tools/mo/unit_tests/moc_tf_fe/test_models/model_add_with_undefined_constant.py
- tools/mo/unit_tests/moc_tf_fe/test_models/model_mul_with_undefined_constant.pbtxt
- tools/mo/unit_tests/moc_tf_fe/test_models/model_mul_with_undefined_constant.py
**Details:** Since TF 2.10 the native model freezing can produce constants with undefined value, i.e. tensor shape can be any and value is []. In this case the tensor just fills up with the default value (0 - for numerics, "" - for strings)
**Ticket:** 140458
Porting of https://github.com/openvinotoolkit/openvino/pull/17311
> [MO][TF FE] Handle constant with undefined value (#17311)

- src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- Certain `execution devices` tests for `compiled_model` would fail like:
```
src\tests\functional\plugin\shared\src\behavior\compiled_model\properties.cpp(329): error: Expected equality of these values:
expectedTargets
Which is: { "NPU.XXXX" }
exeTargets
Which is: { "NPU.AUTO_DETECT" }
```
To overcome this problem, tests' `expectedTargets` were updated to `NPU` only, but the value got from `ov::execution_devices` config had to be updated to `NPU` as well.
- Other problem occurred for `NPU_TILES` config where prefixed values for `NPU_PLATFORM` config e.g. `NPUXXXX` were not standardized to digits only, causing `NPU_STEPPING` and `NPU_MAX_TILES` to be missing from local config.
- Instantiation of shared compiled model tests is being tracked in *EISW-109425*
> [`EISW-109425`] [`NPU plugin`] [`ov::execution_devices`] Fix bad execution devices value for NPU plugin

- src/plugins/template/src/compiled_model.cpp
- src/plugins/template/src/config.cpp
- src/plugins/template/src/plugin.cpp
- src/plugins/template/src/sync_infer_request.cpp
- Fix in main source files in Template plugin the Coverity issues:
- copy instead of move,
- auto causes copy,
- uninitialized members.
- 1525722,1530205, 1509949, 1509659, 1509865, 1509902, 1509934, 1521451, 1527821
- 1543955, 1527899, 1505765, 1527792
> [TEMPLATE] Fix some Coverity issue in Template plugin

- src/common/transformations/src/transformations/sdpa_to_paged_attention/state_management_pattern.cpp
- src/core/src/op/paged_attention.cpp
Deduce the number of KV heads and head_size from the model without relying on HF config, and set the deduced values as KV cache input dimension. Applied HW specific layout rearagement based on the current expectations from CPU and GPU preserving those deduced dimensions.
> @CuriousPanCake, Please provide the status for the same set of models that was mentioned in #24336.
Yep, I've run the tests for all the models available in the testing script and that's what I've got. Some models have given a gibberish answer to the prompt.
I'll attach the logs in a second.
_RuntimeError: Check '(axis_range_min <= axis) && (axis <= axis_range_max)' failed at src/core/src/validation_util.cpp:386:
Concat Parameter axis 2 out of the tensor rank range [0, 0]._
_ValueError: The model's max seq len (32768) is …
> Deduce the number of KV heads and head_size from the model

- src/plugins/intel_npu/src/al/include/intel_npu/al/config/common.hpp
- *A default value should be provided when the property is used by the caching mechanism if the property was not provided by the user*
- *ticket-id*
> [NPU] Set default value for batch mode property

- src/bindings/js/node/include/helper.hpp
- src/bindings/js/node/src/helper.cpp
- src/bindings/js/node/tests/basic.test.js
- Join two existing functions  for converting Napi::Value to ov::Any:
ov::Any js_to_cpp<ov::Any>(const Napi::Value&, const std::vector<napi_types>& acceptable_types) 
and
ov::Any js_to_any(const Napi::Env& env, const Napi::Value& value)
- `template <typename TargetType>
TargetType js_to_cpp(const Napi::Value&, const std::vector<napi_types>& acceptable_types);` is set to be removed (_140428_)
- *140426*
> [OV JS] Join conversion functions for ov::Any

- src/plugins/intel_gpu/include/intel_gpu/op/indirect_gemm.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/gemm.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/gemm.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kv_cache.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/beam_table_update_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/beam_table_update/beam_table_update_kernel_ref.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/beam_table_update/beam_table_update_kernel_ref.hpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_base.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
- src/plugins/intel_gpu/src/plugin/ops/matmul.cpp
- src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.cpp
- src/plugins/intel_gpu/src/plugin/transformations/op/indirect_gemm.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/transformations/indirect_kv_cache_test.cpp
- Currently `indirect Gemm` is implemented with an assumption of `KV Cache`'s gather axis is 0
- Update `KV Cache` and `indirect Gemm` to support non-batch gather axis support
- 137142
> [GPU] Enable Indirect gemm for non-batch gather axis support

- src/frontends/onnx/frontend/src/op/org.openvinotoolkit/deformable_conv_2d.cpp
- src/frontends/onnx/tests/models/org.openvinotoolkit/deformable_conv_2d_with_mask.prototxt
- src/frontends/onnx/tests/onnx_import_org_openvino.in.cpp
- src/frontends/onnx/tests/runtime/interpreter/unit_test.manifest
- This pull request improves [`openvino.convert_model`](https://docs.openvino.ai/2024/api/ie_python_api/_autosummary/openvino.convert_model.html) in Python, so that `DeformableConv2D` can handle the 4th input as `mask` parameter, which is described in [DeformableConvolution-**8**](https://docs.openvino.ai/2023.3/openvino_docs_ops_convolution_DeformableConvolution_8.html).
- Closes #24346
> Support "mask" parameter passed as 4th input of `DeformableConv2D` node.

- src/frontends/tensorflow_lite/src/op_table.cpp
**Details:**  Clean up op_table
> [TFL FE] Clean up op_table

- src/plugins/intel_npu/src/al/include/npu.hpp
- src/plugins/intel_npu/src/al/src/npu.cpp
- src/plugins/intel_npu/src/backend/include/zero_device.hpp
- src/plugins/intel_npu/src/backend/src/zero_device.cpp
- src/plugins/intel_npu/src/plugin/include/metrics.hpp
- src/plugins/intel_npu/src/plugin/src/metrics.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- Implemeting DEVICE_GOPS metric for intel-npu plugin
- EISW-123380
> [intel-npu] Implementing DEVICE_GOPS metric

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- *Fix for https://github.com/openvinotoolkit/openvino/pull/24308*
> [GPU] Fixed eltwise fusing check in onednn case

- src/common/snippets/src/lowered/pass/fuse_loops.cpp
- *In FuseLoops pass, update the state of current_loop_info after loop fusion, so that the state of port connections will be updated and some other loops may fuse to the current loop.*
- *[CVS-141023](https://jira.devtools.intel.com/browse/CVS-141023)*
> [CPU] [Snippets] Update the state of current_loop_info after loop fusion

- src/common/transformations/src/transformations/sdpa_to_paged_attention/prev_sequence_length_pattern.cpp
- src/core/src/pass/sdpa_to_paged_attention.cpp
Fix PagedAttention PrevSequenceLengthPattern pattern
Fix pattern of PrevSequenceLengthPattern that makes it match twice than needed resulting in the incorrect inference.
Provide the correct version of Gather (v8::Gather) and amend PrevSequenceLengthPattern pattern for the correct matching.
- *item1*
- *...*
- *ticket-id*
> Fix PagedAttention PrevSequenceLengthPattern pattern

- install_build_dependencies.sh
- Added Alpine Linux dependencies to install list
- #24368
> Added Alpine Linux dependencies to install list

- samples/cpp/benchmark_app/main.cpp
- *get the correct batch size when running with pre-compiled models*
- *CVS-140703*
> [SAMPLES] Get the correct batch size when running with pre-compiled models

- src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm.hpp
- *If there are several MHA-patterns with the same Brgemms inside (the same configs), first Brgemm calls `compile_kernel` using executor: initializes `palette` and compile `kernel`. The brgemm from the second MHA finds in the cache this `kernel` by the config that is equal to first Brgemm has. Hovewer, previously `palette` was stored in `config` - this `config` is not cached and not shared between emitters. Thus, second Brgemm had cached `kernel` and config with empty `palette` since it's inited `compile_kernel` that is not called for this `Brgemm`. The PR introduces new structure that contains `compiled_kernel` and `palette` - these values are cached together and can be shared between nodes and emitters*
- *140771*
> [CPU] Created BrgemmCompiledKernel to cache palette with kernel

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/fully_connected.cpp
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- src/plugins/intel_gpu/thirdparty/CMakeLists.txt
- Update OneDNN to v3.5
- Fix OOB memory access with fake alignment
- Do not fake-align if input-memory is not allocated properly (it impacts test cases where FC gets input from data node)
- This fix is applied only to some hardware because of performance concern
- 141215
- 138012
> [GPU] OneDNN v3.5 update and fix for OOB memory access

- src/inference/src/dev/iplugin.cpp
- src/plugins/hetero/src/subgraph_collector.cpp
- src/plugins/hetero/tests/unit/subgraph_collector.cpp
- When there are some submodels need to be merged into one model, if there is a independent submodel in the submodels, such as `chatglm, qwen-7b-chat`:
submodel A (independent )
submodel B
submodel C
B and C will be the same because they have connection(input/output), so when merge C into A after B merged, it will throw  `parameters already added` errior in add_parameters().
So add a distinct_submodels_index set to store the distinct submodels will be merged.
- When split `baichuan-13b` into 2 parts, it will has error: Model references undeclared parameters: opset1::Parameter input_ids () -> (i64[?,?]), because there are some ops not removed correctly.
- *CVS-140527*
> Fix the error of splitting chatglm, qwen-7b-chat and baichuan-13b

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/grid_sample_ref.cl
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- Use float for intermediate calculation of grid sample op
- Adjust data ranges for fc unit test to avoid huge numbers
- *CVS-134015*
> [GPU] Unit test fixes

- src/common/transformations/tests/op_conversions/convert_gather_to_compressed_test.cpp
- src/plugins/intel_cpu/src/graph_optimizer.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/convert_to_power_static.cpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/matmul_decompress_convert.cpp
- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/matmul_weights_decompression.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/gather_weights_decompression.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/shared_matmul_gather_weights_decompression.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/shared_matmul_weights_decompression.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/gather_weights_decompression.cpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/gather_weights_decompression.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/shared_matmul_gather_weights_decompression.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/shared_matmul_weights_decompression.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/weights_decompression_builders.hpp
- src/tests/functional/shared_test_classes/src/subgraph/gather_weights_decompression.cpp
- src/tests/functional/shared_test_classes/src/subgraph/shared_matmul_gather_weights_decompression.cpp
- src/tests/functional/shared_test_classes/src/subgraph/shared_matmul_weights_decompression.cpp
- src/tests/functional/shared_test_classes/src/subgraph/weights_decompression_builders.cpp
- *Shared decompression between 2 Matmuls is supported for 8bits and 4bits weights*
- *Shared decompression between Matmul and Gather is supported for 8bits and 4bits weights*
- *Added CPU subgraph test*
- *CVS-140442* <= Validation results can be found there
- *CVS-137591*
- *CVS-136594*
> [CPU] Shared compressed weights support

- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- Adding EXECUTION_DEVICES read-only property for intel-npu plugin.
- EISW-112990
> [intel-npu] Adding EXECUTION_DEVICES read-only property

- src/bindings/python/tests/test_runtime/test_async_infer_request.py
- Do not skip the test of `InferReuqest.cancel()`
- *CVS-95967*
> [PyOV] Reenable test_cancel

- src/common/transformations/include/transformations/common_optimizations/simplify_shape_of_sub_graph.hpp
- src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
- src/common/transformations/tests/common_optimizations/simplify_shape_of_sub_graph.cpp
- src/core/dev_api/openvino/core/tensor_util.hpp
- src/core/include/openvino/op/abs.hpp
- src/core/src/bound_evaluate.cpp
- src/core/src/bound_evaluate.hpp
- src/core/src/op/abs.cpp
- src/core/src/op/mod.cpp
- src/core/src/op/reduce_prod.cpp
- src/core/src/tensor_util.cpp
- src/core/tests/type_prop/abs.cpp
PyTorch semantic of Expand operation requires Abs operation for translation which is usually a no-op.
1. partial value and symbol propagation for Abs operation
2. optimize out the Abs with nonnegative input
3. for this case Abs(Concat([Gather(ShapeOf), -1, 1, -1])) pulls Abs and tries to const-fold it. Resulting in Concat([Abs(Gather(ShapeOf)), 1, 1, 1]). Applies (2) to the graph and gets Concat([Gather(ShapeOf), 1, 1, 1]) because ShapeOf's lower bound is 0.
- *CVS-141274*
> Abs value inference and optimization

- src/plugins/intel_gpu/src/runtime/kernels_cache.cpp
- This PR updates the `kernels_cache` to build the selected kernels in separate batches.
- This is a temporary WA to resolve performance degradation when some kernels are built with other kernels in the same batch
- Currently, the selected kernel includes `gemm_tiled_opt`.
- The impacted scenario : Qwen INT4 first token latency for > 1K input  in MTL 
- GSD-8910
> [GPU] updates to build some selected kernels in separate batches

- src/plugins/intel_cpu/tests/unit/shape_inference_test/concat_shape_inference_test.cpp
- Add new tests to cover case with reuse of pre-created operator
- *[CVS-94507](https://jira.devtools.intel.com/browse/CVS-94507)*
> [CORE] Test opset1::Concat shape inference with op reuse

- src/frontends/tensorflow_common/src/op/gelu.cpp
- src/frontends/tensorflow_lite/src/decoder_flatbuffer.cpp
Sometimes the approximate attribute is not specified in the .tflite file, we need to check its availability before retriving it, otherwise we might hit the 'Check 'opts != nullptr' failed' failure with calling get_attribute() directly.
> [TFL FE]: gelu: fix issue when approximate is not specified

- src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/convolution_qdq_transformation.cpp
- Fix the issue where `conv_params.quantization` was not correctly identified as a quantization case when using U8 weights data (which is allowed by ConvertConvolutionToInternal transformation pass)
- 139740
> [GPU] Fix U8 weights identification as a quantization case

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
* Use block read in 4byte aligned left-over case. Static was already used (https://github.com/openvinotoolkit/openvino/pull/23400) This PR will apply in dynamic.
- *141032*
> [GPU] gemm_tile supports block read when leftover with 4byte-size align in dynamic.

- src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- *Update `zero_infer_request.cpp` with `u4` and `i4`* for intel_npu.
- *...*
- *E#121561*
> Extend network precision with `u4`, `i4` for L0 backend

- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device.rst
- docs/articles_en/openvino-workflow/running-inference/optimize-inference/precision-control.rst
Creating  `Limitation of the bf16 inference precision` section to describe an issue of higher accuracy loss than the pre-determined threshold of 0.5%  and present possible solutions.
This PR addresses JIRA ticket: 138832.
> [DOCS] Limitation of BF16 inference precision for LLMs

- src/plugins/intel_gpu/CMakeLists.txt
Remove stringop overflow warning as a temporal workaround for oneDNN warning issue, which caused compilation issues on Ubuntu 24.04 (GCC 13 + LTO)
- Remove warning from intel-gpu link flag properties
- CVS-141874
> [GPU] Remove link-time stringop overflow warning

- src/plugins/intel_cpu/tools/dump_check/dump_check.py
66a860056458090d50ff3b93a4ad05b2cb263f40 switched precision field in dump header from ePrecision  to ov::element::Type_t. update dump_check.py to parse precision correctly.
> [CPU]Align dump_check.py with blob dump header precision switch from deprecated ePrecision to ov::element::Type_t.

- src/plugins/auto/src/auto_schedule.cpp
- src/plugins/auto/src/common.hpp
- src/plugins/auto/src/plugin.cpp
- src/plugins/auto/tests/functional/behavior/caching_test.cpp
- update logic of only loading cached model to GPU with AUTO if GPU cached blob exists and `ov::intel_auto::enable_startup_fallback` is enable
- CVS-138574
> [AUTO] Load cached model to target device W/O CPU accelerating

- src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- removing ENABLE_CPU_PINNING from command string passed to CiD, for older compiler versions to enable backwards compatibility
- EISW-124233
> [intel-npu] removing cpu_pinning string from CID command string

- src/bindings/python/tests/test_runtime/test_async_infer_request.py
Reverts openvinotoolkit/openvino#24590
Sporadically fails https://github.com/openvinotoolkit/openvino/actions/runs/9189693102/job/25273009310
Looks like tests relies on certain execution time of model inference, while it depends on machine
> Revert "[PyOV] Reenable test_cancel"

- docs/articles_en/assets/snippets/ov_hetero.cpp
- docs/articles_en/assets/snippets/ov_hetero.py
- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/hetero-execution.rst
This reverts commit 03aad66230596e8a86e9363b0e8189149967baf2.
Revert the commit because there are some models with stateful OPS (assign/readvalue) not in same attention node, hetero pipeline parallelism does not work.
- *CVS-141771*
> Revert "[DOCS] Update the document of HETERO pipeline parallelism"

- cmake/templates/OpenVINOConfig.cmake.in
- It can be useful when other targets within user project need to be linked with _GLIBCXX_USE_CXX11_ABI=0
> Set _GLIBCXX_USE_CXX11_ABI globally in OV cmake

- .github/workflows/linux.yml
- If the GPU job is skipped, the UI shows:
The jobs created by `matrix` will have the necessary distinguishable properties in the `()` after the job name, e.g., for `Conformance`:
so we do not need `matrix`.
> [CI] [GHA] Fix GPU job display name if the job is skipped

- src/plugins/intel_cpu/src/graph.cpp
- src/plugins/intel_cpu/src/graph.h
- To reduce Infer overhead
- The new flow is:
1) Define sync points from all the nodes perspective.
2) Use sync points in scope of Allocate
3) Define executable sync points from overall sync points but considering only executable nodes.
4) Keep executable sync points ordered to avoid additional logic in scope of Infer call.
- *ticket-id*
> [CPU] Avoid extra processing of the sync nodes in scope of Infer call

- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/classes/undefined_et.cpp
- *To receive determined output of RandomUniform operation, need to set `global_seed` or `op_seed`*
- *CVS-142075*
> [CPU] smoke_/UndefinedEtSubgraphTest sporadic fail on SPR

- src/frontends/tensorflow/src/frontend.cpp
- src/frontends/tensorflow/tests/convert_unsupported.cpp
- tests/layer_tests/common/utils/common_utils.py
- tests/layer_tests/tensorflow_tests/test_tf_StringLower.py
- tools/ovc/openvino/tools/ovc/main.py
- tools/ovc/openvino/tools/ovc/utils.py
**Details:** Previously, we were able to convert models requiring openvino-tokenizers extensions (like with string operations, ragged tensors) only in Python by `convert_model`. Now we add option to convert using `ovc` tool. The tool internally imports extensions if they are installed.
> [OVC] Import openvino-tokenizers extensions from ovc tool

- src/core/include/openvino/op/scaled_dot_product_attention.hpp
- src/plugins/intel_gpu/include/intel_gpu/op/indirect_sdpa.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/scaled_dot_product_attention.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp
- src/plugins/intel_gpu/src/graph/include/scaled_dot_product_attention_inst.h
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_ref.cpp
- src/plugins/intel_gpu/src/plugin/ops/scaled_dot_product_attention.cpp
- src/plugins/intel_gpu/src/plugin/plugin.cpp
- src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.cpp
- src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.hpp
- src/plugins/intel_gpu/src/plugin/transformations/op/indirect_sdpa.cpp
- src/plugins/intel_gpu/src/plugin/transformations/op/sdpa.cpp
- src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.cpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- Added indirect inputs support for SDPA kernel
- Added setter for causal flag for ScaledDotProductAttention operation
- Added `ov::intel_gpu::hint::enable_sdpa_optimization` to `ov::supported_properties` list
- Removed unused `TARGET_SEQ_LEN_BLOCK_SIZE > 1` check from kernel for single token processing
- Minor refactoring
- Added `OV_GPU_EnableSDPA` debug option (which allows to force SDPA kernel for any ScaledDotProductAttention operation _(=1)_ / or completely disable SDPA kernel _(=0)_, ignoring `ov::intel_gpu::hint::enable_sdpa_optimization` property) 
- *CVS-141213*
> [GPU] SDPA indirect inputs

- src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_f_y_axes.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/permute_gpu_test.cpp
- when tile_size < vector_size then JTIMES == 0
- 142398
> [GPU] fix for permute_f_y kernel 

- .github/workflows/windows_conditional_compilation.yml
This PR moves Windows Conditional Compilation build to a self-hosted runner in Azure with 32 cores and 128 GB of RAM
> Bigger runner for Windows Conditional Compilation build

- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
- *reduce post ops only support f32 precision*
- *CVS-142322*
- *https://github.com/openvinotoolkit/openvino/pull/24724*
> [CPU] Reduce post ops as subgraph when output is not f32 precision

- .github/actions/cache/dist/save-only/index.js
- .github/actions/cache/dist/save/index.js
- .github/actions/cache/src/saveImpl.js
- Port of #24703
- The issue that was present on the release branches does not affect the master branch yet but it could if, for example, a new folder is added to the cache path.
- *142372*
> [CI] [GHA] Create cache directory recursively

- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/compiled_model/properties.cpp
- *To align newly added behavior tests with other plugins, `OVClassCompiledModelPropertiesDefaultTests` should not be tested with `HETERO` device, as it is in `intel_cpu` plugin: https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/compiled_model/properties.cpp#L63-L67*
- *E-120273*
> Update `CompiledModel` tests after `ov::model_name` prop was fixed

- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/compiled_model/properties.cpp
- *This is a duplicate of PR #24705 *
- *To align newly added behavior tests with other plugins, `OVClassCompiledModelPropertiesDefaultTests` should not be tested with `HETERO` device, as it is in `intel_cpu` plugin: https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/compiled_model/properties.cpp#L63-L67*
- *E-120273*
> [DUPLICATE] [RELEASES/2024/2] Update `CompiledModel` tests after `ov::model_name` prop was fixed

- src/plugins/intel_npu/src/backend/include/zero_profiling.hpp
ze_device_properties_t has pNext pointer and if it's not nullptr then it's assumed that it points to a different structure. pNext being uninitialized can lead to a crash during zeDeviceGetProperties.
> [NPU] Zero-initialize NpuInferProfiling::_dev_properties

- src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
- src/common/transformations/tests/common_optimizations/nop_elimination.cpp
Handle the case when 2nd input of Transpose op is empty
https://github.com/openvinotoolkit/openvino/pull/23950
> Fix TransposeElimination transformation

- src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- Reduce the condition for not-using usm-host input buffer
- This is to reduce the overhead in next-gen GPU performance where usm_host is the input buffer
- 141493
> [GPU] Reduce the condition for not-using usm-host input buffer

- src/bindings/python/src/pyopenvino/core/offline_transformations.cpp
- src/core/src/pass/visualize_tree.cpp
As a result, you can use this code for most of your needs:
- in a Jupiter notebook
- as a cmd tool
- with model weights being far away
```
def configure_visualizer(enable=True, max_const_elements=7):
import os
envs_to_set = [
'OV_VISUALIZE_TREE_IO',
'OV_VISUALIZE_TREE_OUTPUT_SHAPES',
'OV_VISUALIZE_TREE_OUTPUT_TYPES',
'OV_VISUALIZE_TREE_EDGE_LABELS',
'OV_VISUALIZE_APPLY_SYMBOLIC_PROPAGATION',
'OV_VISUALIZE_PARTIAL_VALUES_AND_LABELS'
]
for e in envs_to_set:
os.environ[e] = '1' if enable else '0'
os.environ["OV_VISUALIZE_TREE_CONST_MAX_ELEMENTS"] = str(max_const_elements) if enable else "7"
def serialize_model_to_svg(model, output_name='serialized_model.svg'):
from openvino.runtime.passes import VisualizeTree
configure_visualizer(True)
VisualizeTree(output_name).run_on_model(model) …
```
> [PyOV] Added symbolic propoagation to model visualization to enhance OV developer experience

- src/common/transformations/include/transformations/common_optimizations/nop_elimination.hpp
- src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
- src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
- src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
- src/common/transformations/src/transformations/symbolic_transformations/symbolic_optimizations.cpp
- src/common/transformations/tests/common_optimizations/moc_transformations.cpp
Disable EliminateSqueeze/EliminateUnsqueeze passes in SymbolicOptimizations
- *CVS-141814*
> Do not convert Squeeze/Unsqueeze to Reshape in Symbolic transformations

- src/common/snippets/include/snippets/lowered/loop_info.hpp
- src/common/snippets/include/snippets/lowered/pass/identify_buffers.hpp
- src/common/snippets/include/snippets/lowered/pass/insert_loops.hpp
- src/common/snippets/include/snippets/op/loop.hpp
- src/common/snippets/src/lowered/loop_info.cpp
- src/common/snippets/src/lowered/pass/clean_repeated_ptr_shifts.cpp
- src/common/snippets/src/lowered/pass/cleanup_loop_offsets.cpp
- src/common/snippets/src/lowered/pass/define_buffer_clusters.cpp
- src/common/snippets/src/lowered/pass/identify_buffers.cpp
- src/common/snippets/src/lowered/pass/init_loops.cpp
- src/common/snippets/src/lowered/pass/insert_loops.cpp
- src/common/snippets/src/lowered/pass/insert_specific_iterations.cpp
- src/common/snippets/src/lowered/pass/iter_handler.cpp
- src/common/snippets/src/lowered/pass/optimize_loop_single_evaluation.cpp
- src/common/snippets/src/lowered/pass/split_loops.cpp
- src/common/snippets/src/lowered/pass/validate.cpp
- src/common/snippets/src/lowered/pass/validate_expanded_loops.cpp
- src/common/snippets/src/op/loop.cpp
- src/common/snippets/src/shape_inference/shape_inference.cpp
- src/common/snippets/tests/src/lowered/pass/loop.cpp
- src/common/snippets/tests/src/lowering_utils.cpp
- src/plugins/intel_cpu/src/emitters/snippets/aarch64/cpu_generator.cpp
- src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_loop_emitters.cpp
- src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_loop_emitters.hpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/cpu_generator.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.hpp
- src/plugins/intel_cpu/src/extension.cpp
- *United `LoopEndStatic` and `LoopEndDynamic`  into one node `LoopEnd` to avoid extra conditions in the code and improve performance since some pointer data shifts might be known and compiled in JIT code*
- *Removed dynamic aarch64 loop emitters since they don't work anyway CVS-141550*
- *Added support dynamism to `IdentifyBuffers` and `DefineBufferClusters`. It's not efficient algorithm since we don't know exact values of data pointer shifts and cannot be sure that they will be proportionally in runtime. It should be implemented as the separate feature based on some judgments, for example*
- *141268*
- *https://github.com/openvinotoolkit/openvino/pull/21922*
> [Snippets] United Static and Dynamic Loops into one node

- src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
- src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- WA of out-of-bound access for fc kernel.
- Use OneDNN FC kernel for fp16 FC when possible. It hides the issue because the target platform can use OneDNN.
- For shape-agnostic kernel, TILE_B=8 is chosen. It causes out-of-bound memory access for LLM 2nd token.
- 142277
> [GPU] Do not use shape-agnostic kernel for OneDNN FC fp16

- src/tests/functional/plugin/shared/include/behavior/ov_plugin/core_integration_sw.hpp
- *item1*
- *...*
- *ticket-id*
> [ov_api_conformance] Remove hetero tests as it will be covered by sw device run over template

- src/tests/functional/shared_test_classes/src/base/utils/ranges.cpp
- *Removed Debug info printing by default from https://github.com/openvinotoolkit/openvino/pull/23428*
```
[ RUN      ] smoke_Snippets_Softmax/Softmax.CompareWithRefImpl/IS=[?.?]_TS=((1.16))_((1.32))_((1.1))_((1.9))_((1.17))_((1.19))_((1.49))_((1.50))_((5.16))_((1.16))_((1.9))_Axis=-1_#N=1_#S=1_targetDevice=CPU
MEM_USAGE=3007144KB
RANGE FOR PARAMETER: Parameter_1590025  start from: 0.000000  range: 8  resolution: 32  seed: 1
RANGE FOR PARAMETER: Parameter_1590025  start from: 0.000000  range: 8  resolution: 32  seed: 1
RANGE FOR PARAMETER: Parameter_1590025  start from: 0.000000  range: 8  resolution: 32  seed: 1
RANGE FOR PARAMETER: Parameter_1590025  start from: 0.000000  range: 8  resolution: 32  seed: 1
RANGE FOR PARAMETER: Parameter_1590025  start from: 0.000000  range: 8 …
```
> [Tests] Fixed debug info about ranges

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- kv cache opt was disabled due to the wrongly detected beam table size. Fixed this issue.
- *ticket-id*
> [GPU] Fixed unexpected kv cache optimization turned off

- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- src/plugins/intel_npu/tests/functional/internal/overload/compiled_model/property.cpp
- `ov::intel_npu::create_executor` is declared a supported property only for the `intel_npu::CompiledModel` class. The current PR adds an entry inside `intel_npu::Plugin` as well.
- *CVS-143060*
> [NPU] Add the "create_executor" property inside the Plugin's list as well

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- In case when scale tensor was used by multiple compressed FCs we had an exception on attempt to insert reorder between them. This patch changes reorder name so now multiple reorders are inserted for each Scale+FC pair, and then on later stages we merge them if they do same tensor transform.
> [GPU] Fix decompression scales reorder when data is reused

- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
- Adding missing property tests to npuFuncTests: EXECUTION_MODE_HINT, DEVICE_TYPE, PCI_INFO and DEVICE_GOPS
- none
> [intel-npu] Adding new properties to tests

- src/plugins/intel_gpu/src/plugin/ops/split.cpp
- Currently we insert crop primitive for each out port of (Variadic)Split ops, and if some of them are not used we just waste some execution time. This patch modifies converter for Split to process ports with real users only.
> [GPU] Don't add crop for unused out ports of Split op

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
Remove the limitation that oneDNN convolution doesn't support dynamic input and output.
With this limitation, clDNN convolution will run forever in dpas platform.
Because oneDNN Opt convolutions require blocked-format and current shape agnostic convolution doesn't support block-format, convolution do nothing in compile_graph stage and actual kernel compilation will happen at first inference.
- *141040*
> [GPU] Fix wrong condition for dynamic onednn convolution impl-type.

- src/common/snippets/src/lowered/pass/fuse_loops.cpp
- *Fixed Invalid Read in FuseLoops pass. Before we save loop ports by reference from `current_loop_info`. However, this `current_loop_Info` might be changed (another shared pointer) and the previous saved loop ports by reference are invalid (the original `current_loop_info` is expired)*
- *`Valgrind` doesn't throw exception anymore with this fix*
- *N/A*
> [Snippets] Fixed Invalid Read in FuseLoops pass

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
- Move scaling from QK dot product to Q input for better SDPA accuracy with high-value ranges
- [CVS-143256](https://jira.devtools.intel.com/browse/CVS-143256)
> [GPU] Move scaling from QK dot product to Q

- src/common/transformations/include/transformations/common_optimizations/lstm_cell_fusion.hpp
- src/common/transformations/src/transformations/common_optimizations/lstm_cell_fusion.cpp
- src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
- src/common/transformations/tests/common_optimizations/lstm_cell_fusion.cpp
**Details:** Implement LSTMCell fusion for Keras LSTM layers. Such sub-graph with split weights appears for bi-directional LSTM layer.
For custom model, we managed to fuse 6 LSTMCell sub-graphs and obtained 19% performance gain on CPU.
**Ticket:** 142924
> [MOC] Implement LSTMCell fusion for Keras LSTM layers

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
We only check whether shape of subgraph is changed or not in dynamic node. But static node also need to be skipped. The node after shape_of can be static.
- *142892*
> [GPU] Fix to skip shape_of_subgraph when input shape is not changed.

- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
- src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
- src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/activation.cpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/activation.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/test_enums.hpp
- src/tests/test_utils/common_test_utils/src/node_builders/activation.cpp
- src/tests/test_utils/common_test_utils/src/node_builders/eltwise.cpp
Hello maintainers,
I've implemented the IsInf JIT emitter for the ARM64 SIMD platform, as outlined in the OpenVINO CPU plugin JIT emitters documentation.
This PR addresses [#24419](https://github.com/openvinotoolkit/openvino/issues/24419).
Please let me know if any further adjustments are needed.
Thank you!
> Implement IsInf JIT Emitter for ARM64 SIMD in OpenVINO

- src/frontends/pytorch/src/pt_framework_node.hpp
- src/frontends/pytorch/src/utils.cpp
- tests/layer_tests/pytorch_tests/test_upsample.py
- *When scripting upsample creates `prim::If` depending from input shape, to determine which version of upsample to use: 1d, 2d or 3d. This is not supported by openvino, but this PR fixes segfault that happen in this case.*
- *#24270*
> [PT FE] Fix segfault when prim::If can't be converted

- src/core/include/openvino/core/type/float4_e2m1.hpp
- src/core/tests/float4_e2m1.cpp
- Add custom std::numeric limits for `ov::float4_e2m1`
- [CVS-141576](https://jira.devtools.intel.com/browse/CVS-141576)
> [core] Integrate f4e2m1 with std::numeric_limits

- .github/scripts/workflow_rerun/errors_to_look_for.json
> [CI] [GHA] Add `Timeout was reached` to the list of errors in rerunner

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- Relax SDPA head size limitations for LLMs from 128 only to a range of 64 to 256
- Fix accuracy issue in SDPA first token processing for `TARGET_SEQ_LEN_BLOCK_SIZE % SUBGROUPS_PER_WG != 0` case
> [GPU] Relax SDPA head size limitations for LLMs

- tests/layer_tests/tensorflow_tests/test_tf_HSVToRGB.py
- Currently, the unit test for HSVToRGB is creating a tensor of all ones in the Grayscale special case as mentioned in [#24875](https://github.com/openvinotoolkit/openvino/pull/24875). Since the images are expected to be in HSV and not RGB format, this will create images that are green, and not gray. Grayscale in HSV can be achieved by creating a tensor with HSV entries of [0, 0, .5].
- N/A
> [TF FE Tests] Change HSVToRGB Unit Test To Test Grayscale Image

- src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/plugin/transformations/print_model_statistics.cpp
- src/plugins/intel_gpu/src/plugin/transformations/print_model_statistics.hpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
- Added dev pass to log operations statistics when VERBOSE=1
- Added debug knob to collect network::execute() time to measure time required to schedule all primitives
- Updated common results comparison routine to print coordinate and to show first mismatched element info in release build
> [GPU] Model stat print, host time measurement debug knob

- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- Fix to resolve perf issue in the platforms with small # of EUs than 128. 
- *ticket-id*
> Let ocl FC to use tile size 1 only when the # of threads is less than the w/ minimal # of threads

- src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp
- src/common/transformations/src/transformations/symbolic_transformations/symbol_optimization.cpp
- src/common/transformations/tests/symbolic_transformations/label_optimization.cpp
This reverts commit 395d6b7e0972c742e062f7e701bceac82fc2c18b.
- *CVS-143648, CVS-142953*
To be merged after: https://github.com/openvinotoolkit/openvino/pull/24954
> Revert "Revert "More accurate shape of optimization" (#24941)"

- src/plugins/intel_gpu/src/graph/impls/cpu/reduce.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/register.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/register.hpp
- src/plugins/intel_gpu/src/graph/include/scatter_nd_update_inst.h
- src/plugins/intel_gpu/src/graph/scatter_nd_update.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/reduce_gpu_test.cpp
- Added reduce cpu impl to handle this op in shapes flow
- override `get_shape_infer_dependencies` method for scatter_nd_update prim
- Allows to avoid redundant synchronizations during shape inference for llama3
> [GPU] CPU Reduce impl + ScatterNDUpdate fixes to avoid shape flow synchronizations

- src/plugins/intel_cpu/src/utils/precision_support.cpp
WA was implemented to avoid ACL issue: https://github.com/ARM-software/ComputeLibrary/issues/1096
> [CPU][ARM] Remove WA in `hasFP16HardwareSupport`

- docs/sphinx_setup/_static/llm_models.csv
Porting: https://github.com/openvinotoolkit/openvino/pull/24981
> [DOCS] LLm benchmarks update for 24.2

- src/common/low_precision_transformations/src/reduce_sum.cpp
- src/common/low_precision_transformations/tests/reduce_sum_transformation.cpp
- src/core/src/op/multiply.cpp
- *[LPT] ReduceSum: zero point support*
- *CVS-142256*
> [LPT] ReduceSum: zero point support

- src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp
- src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
- src/plugins/intel_gpu/src/graph/include/gemm_inst.h
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/src/runtime/format.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp
Current Gemm in dpas always compile and use onednn kernel in 1st inference.
Shape agnostic Gemm kernel is not used. So PR enable SA Gemm in dpas for reducing 1st inference latency.
- *143315*
> [GPU] Enable shape agnostic Gemm in dpas platform.

- src/plugins/auto/tests/unit/compile_model_metric_test.cpp
- src/plugins/intel_npu/tests/functional/common/utils.cpp
- src/plugins/intel_npu/tests/functional/common/utils.hpp
- src/tests/functional/plugin/shared/include/behavior/ov_infer_request/properties_tests.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/test_constants.hpp
- src/tests/test_utils/common_test_utils/src/test_constants.cpp
- *Align OV with latest renaming in `vpux-plugin`*
- After [PR #5738](https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-plugin/pull/5738) in `vpux-plugin` was merged, we are ready to update `ov::test::utils::DEVICE_KEEMBAY` to `ov::test::utils::DEVICE_NPU` on openvino side.
- *[EISW-89683](https://jira.devtools.intel.com/browse/EISW-89683)*
> [EISW-89683] Switch `DEVICE_KEEMBAY` to `DEVICE_NPU`

- src/plugins/intel_npu/src/backend/src/zero_device.cpp
- zero-backend/pci information: Older drivers return errors not covered by current error managment, leading to Throw in zero_device intitialization, leading to total incompatibility with certain old drivers. Since pci information is not essential for the correct functioning of the plugin, i am removing throws completely, falling back to error message and default values.
- none
> [intel-npu] Fix for pci_info throw with old drivers

- src/plugins/intel_gpu/include/intel_gpu/primitives/crop.hpp
- src/plugins/intel_gpu/src/graph/crop.cpp
- src/plugins/intel_gpu/src/plugin/ops/rnn.cpp
- src/plugins/intel_gpu/src/plugin/ops/split.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/crop_si_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/crop_gpu_test.cpp
- Add axis attribute to crop for `VariadicSplit` and `Split` dynamic support
- This attribute is required to apply dynamic padding by `prepare_buffer_fusing` opt pass at build time
- 143096
> [GPU] Add axis attribute to crop for VariadicSplit and Split dynamic support

- src/plugins/intel_gpu/include/intel_gpu/op/swiglu.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/swiglu.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/swiglu.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/swiglu_gpu_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/swiglu/swiglu_kernel_ref.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/swiglu/swiglu_kernel_ref.h
- src/plugins/intel_gpu/src/plugin/ops/swiglu.cpp
- src/plugins/intel_gpu/src/plugin/transformations/op/swiglu.cpp
- src/plugins/intel_gpu/src/plugin/transformations/swiglu_fusion.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/swiglu_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/transformations/swiglu_fusion_test.cpp
- This PR extends the current `SwiGLU` primitive to support `GeGLU` that has Gelu activations instead of Swish.
- This GeGLU patterns can be found in stable diffusion models.
- 143486
> [GPU] Adding GeGLU

- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
All skips were related to lack of `fp16` support in ARM.
- CVS-122769
> [ARM][CPU] Enable tests skipped to pass GHA

- src/plugins/intel_npu/src/plugin/include/metrics.hpp
- src/plugins/intel_npu/src/plugin/src/metrics.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
Stepping and max_tiles will only get populated in compile (be it manual config or driver value). As a result, if queried before model compilation, both will return -1 default values. This change initializes globalConfig with driver values, while leaving localconfig (and compiled_model config) untouched. This way, the behaviour will be as follows:
-  core.get will return actual stepping number and max tiles of the actual device (driver populated)
- compiled_model.get will return stepping number and max tiles the model was compiled with (be it user-supplied or driver populated)
- none
> [intel-npu] initializing stepping and max_tiles default values

- src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv32.cpp
- MTL iGPU running convolution_gpu_byfx_os_iyx_osv32 kernel with filter size >=32x32 will get very poor performance due to need read too much input data in each thread to sync data with other threads in the same subgroup. 
- For ViT B/32 model with bs=1,16,32,128, we can get quit low performance comparing to IPEX
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr'>
  |   |   | Input shape | Conv kernel | OV master | IPEX
-- | -- | -- | -- | -- | -- | --
ViT B/32 | FP16 | ViT B/32 | 1 *3*384*384 | …
> [GPU][MTL] choose better conv kernel for filter size 32x32 in iGPU case

- src/common/snippets/src/pass/collapse_subgraph.cpp
- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
- src/plugins/intel_cpu/src/emitters/snippets/aarch64/cpu_generator.cpp
- src/plugins/intel_cpu/src/nodes/subgraph.cpp
- src/plugins/intel_cpu/src/transformations/snippets/aarch64/pass/snippets_mark_skipped.cpp
- src/plugins/intel_cpu/src/transformations/snippets/aarch64/shape_inference.cpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.hpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/eltwise.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/eltwise.hpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/extremum.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/extremum.hpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/activation.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/eltwise.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/extremum.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/activation.cpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/minimum_maximum.hpp
- src/tests/test_utils/common_test_utils/include/common_test_utils/node_builders/extremum.hpp
- src/tests/test_utils/common_test_utils/src/node_builders/extremum.cpp
- *Add subgraph tokenization for more Eltwise operations, such as Abs, Clamp, Elu, Floor, GeluErf, etc.*
- *Add corresponding test cases.*
- *CVS-142847*
> [Snippets] [ARM] Add subgraph tokenization for more Eltwise operations

- src/frontends/onnx/frontend/src/core/tensor.cpp
- src/frontends/onnx/frontend/src/core/tensor.hpp
- src/frontends/onnx/frontend/src/utils/common.cpp
- src/frontends/onnx/onnx_common/src/utils.cpp
- src/frontends/onnx/tests/models/string_constant.prototxt
- src/frontends/onnx/tests/models/string_input.prototxt
- src/frontends/onnx/tests/onnx_import.in.cpp
- src/tests/test_utils/common_test_utils/src/test_case.cpp
- Added support for accepting string as inputs and constants
- 139685
> [ONNX] Added translation for string constants/inputs

- src/plugins/intel_cpu/src/nodes/reduce.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/reduce.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/reduce.hpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/reduce.cpp
- *Apply int32 instructions directly for ReduceProd with int32 precision.*
- *CVS-141153*
> [CPU] Apply int32 instructions directly for ReduceProd-int32

- src/plugins/intel_gpu/src/graph/graph_optimizer/post_optimize_weights.cpp
- src/plugins/intel_gpu/tests/unit/passes/post_optimize_weights.cpp
- Fix issue of _in_layout update from onednn weights param when reorder fusing happens during post optimize weights
- 143641
> [GPU] Fix issue of _in_layout update from onednn weights param when reorder fusing happens during post optimize weights

- src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
When Node_A and Node_B has two connections as in dynamic quantization or kv_cache, the port information was not properly printed.
> [GPU] Show duplicated connection properly

- src/inference/dev_api/openvino/runtime/threading/cpu_streams_executor.hpp
- src/inference/src/dev/threading/cpu_streams_executor.cpp
- src/plugins/intel_cpu/src/compiled_model.cpp
- src/plugins/intel_cpu/src/node.cpp
- src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_utils.cpp
- src/plugins/intel_cpu/src/nodes/executors/mlas/mlas_gemm.cpp
- src/plugins/intel_cpu/src/nodes/input.cpp
- *Weights caching enabled in single stream mode*
- *Avoid unnecessary weights repacking on single socket machines*
- *CVS-139671*
> [CPU] Avoid shared weights double repacking in latency mode

- src/core/include/openvino/op/roi_align_rotated.hpp
- src/core/src/op/assign.cpp
- src/core/src/op/concat.cpp
- src/core/src/op/convert.cpp
- src/core/src/op/eye.cpp
- src/core/src/op/if.cpp
- src/core/src/op/loop.cpp
- src/core/src/op/max_pool.cpp
- src/core/src/op/mod.cpp
- src/core/src/op/non_zero.cpp
- src/core/src/op/parameter.cpp
- src/core/src/op/result.cpp
- src/core/src/op/space_to_batch.cpp
- src/core/src/op/type_relaxed.cpp
- src/core/src/op/unique.cpp
- src/core/src/op/util/broadcast_base.cpp
- src/core/src/op/util/framework_node.cpp
- src/core/src/op/util/index_reduction.cpp
- Fix issues reported by Coverity in core operators.
Use move or reference to avoid not required object copies.
- Part of [CVS-141674](https://jira.devtools.intel.com/browse/CVS-141674)
> [core] Fix Coverity issues in core operators

- src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
- src/plugins/intel_gpu/src/graph/program.cpp
Node may be replaced during graph compilation pass. (e.g. prepare_primitive_fusing)
In that case, port number of connection were lost.
> [GPU] keep output port as it was when node is replaced

- tools/mo/openvino/tools/mo/convert_impl.py
- tools/mo/openvino/tools/mo/front/caffe/detection_output_ext.py
- tools/mo/openvino/tools/mo/front/kaldi/extractors/convolutional_1d_component_ext.py
- tools/mo/openvino/tools/mo/front/kaldi/replace_lstm_nonlinearity.py
- tools/mo/openvino/tools/mo/middle/MXNetSplitMultiLayers.py
- tools/mo/openvino/tools/mo/middle/StridedSliceNormalizer.py
- tools/mo/openvino/tools/mo/ops/one_hot.py
- tools/mo/openvino/tools/mo/utils/get_ov_update_message.py
- tools/mo/openvino/tools/mo/utils/logger.py
Port of https://github.com/openvinotoolkit/openvino/pull/24512 to 2023.3.
> Made MO deprecation message more explicit, PyLint errors fixed.

- src/plugins/intel_gpu/src/graph/rope.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/rope/rope_kernel_base.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/rotary_pos_emb.cpp
- src/tests/functional/plugin/shared/include/subgraph_tests/rotary_pos_emb.hpp
- src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/rotary_pos_emb.hpp
- src/tests/functional/shared_test_classes/src/subgraph/rotary_pos_emb.cpp
- This PR addresses the issue with RoPE kernel GWS configuration. Previously, it was configured considering that input is always transposed (0213 order, so {B, Y, F * X) is used), which led to the actual order being {B, F, Y * X} for transposed case and incorrect {B, Y, F * X} order for non-transposed case. The change in this PR uses the output shape for GWS calculation instead. This allows for proper configuration regardless of whether the inputs are transposed or not. 
- [*CVS-144014*](https://jira.devtools.intel.com/browse/CVS-144014), [*CVS-143741*](https://jira.devtools.intel.com/browse/CVS-143741)
> [GPU] Fix RoPE for non-transposed input cases

- src/plugins/intel_cpu/src/nodes/reduce.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/reduce.cpp
- *vdivps instruction rounds to the nearest value. Here we append vroundps instruction to make the result round towards zero, to align behavior with Plugins/Frameworks.*
- *Add the test case that can reproduce the issue beforehand.*
- *[issue#20815](https://github.com/openvinotoolkit/openvino/issues/20815)*
> [CPU] Round towards zero for ReduceMean

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- use byte counts for checking prealloc pre-req
> [GPU]use bytes for mem compare

- src/plugins/intel_npu/tests/functional/behavior/infer_request_run.cpp
- src/plugins/intel_npu/tests/functional/behavior/npu_driver_compiler_adapter/downgrade_interpolate11.cpp
- src/plugins/intel_npu/tests/functional/behavior/npu_driver_compiler_adapter/inputs_outputs.cpp
- src/plugins/intel_npu/tests/functional/behavior/npu_driver_compiler_adapter/query_network.cpp
- src/plugins/intel_npu/tests/functional/behavior/ov_plugin/internal_properties_tests.cpp
- src/plugins/intel_npu/tests/functional/internal/overload/compiled_model/property.cpp
- src/plugins/intel_npu/tests/functional/internal/overload/ov_plugin/core_integration.hpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/compiled_model/compiled_model_base.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/compiled_model/import_export.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/compiled_model/properties.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/batched_tensors.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/callback.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/cancellation.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/compile_and_infer.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/inference.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/multithreading.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/perf_counters.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/properties_tests.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/wait.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_threading_tests.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/life_time.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/query_model.cpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/version.cpp
- *We need a new validation job where `ov_npu_func_tests` will be run with older `NPU drivers`. By this we will ensure backward compatibility between ov `master` branch and older drivers.*
- *The requirement above can be fulfilled by adding a new keyword (e.g. <s>`backwardDrvComp`</s> `compatibility`) to all the test suites that passed with older drivers and new validation will use this new keyword as for `gtest_filter`.*
- *CVS-142863*
> [intel-npu] Add pre/post commit validation for NPU plugin with `PV driver`

- src/frontends/jax/src/op_table.cpp
- tests/layer_tests/jax_tests/test_div.py
- tests/layer_tests/jax_tests/test_mul.py
- tests/layer_tests/jax_tests/test_sub.py
Add `sub`, `mul` and `div`, and corresponding unit tests.
No ticket
> [JAX FE] Add arithmetic operations for JAX frontend.

- src/plugins/auto/src/auto_schedule.cpp
- src/plugins/auto/tests/functional/behavior/caching_test.cpp
- port from https://github.com/openvinotoolkit/openvino/pull/25025 to 2024.2
- *...*
- _N/A_
> [AUTO] fix the crash when passing model path to AUTO with model cache enabled

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
This PR is a backport of original https://github.com/openvinotoolkit/openvino/pull/24930 to OV 2024.2 version
- Relax SDPA head size limitations for LLMs from 128 only to a range of 64 to 256
- Fix accuracy issue in SDPA first token processing for `TARGET_SEQ_LEN_BLOCK_SIZE % SUBGROUPS_PER_WG != 0` case
> [GPU] Relax SDPA head size limitations for LLMs - backport to OV 2024.2

- src/plugins/intel_cpu/src/nodes/conv.cpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/classes/undefined_et.cpp
- *Restrict usage of f16 in transformations pipeline if it's not supported by hardware for ACCURACY MODE*
- *145051*
> [CPU] Limit f16 in Accuracy mode by hardware support

- cmake/developer_package/api_validator/api_validator.cmake
- Regression after https://github.com/openvinotoolkit/openvino/pull/25069
- With `function` some vars are bounded to its scope, while they are required for functions below
> Fixed regression with apiValidator search

- .github/labeler.yml
- src/bindings/python/src/openvino/frontend/jax/utils.py
**Details:** Correct creation of numpy dtypes dictionary. `dtypes` looks not accessible for some numpy versions. And it leads to error: AttributeError: module 'numpy' has no attribute 'dtypes'. Example: https://github.com/openvinotoolkit/openvino/actions/runs/9709509944/job/26799144381#step:25:12135
So I simplify creation of types mapping and checking.
> [JAX FE] Correct creation of numpy dtypes

- src/bindings/python/src/openvino/runtime/opset13/ops.py
- src/bindings/python/tests/test_graph/test_constant.py
- Expand `opset13.constant` to support more custom OV float8 types
- CVS-145378
> [pybind] Add float8 support in opset13 constant binding

- src/inference/src/cache_guard.cpp
> [ie] Fix Coverity issues in CacheGuard

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
Disallow usage of FP32 input with compressed weights and zero point on FC layer, since it's currently not supported
- Disallow usage of FP32 input with compressed weights and zero point on FC layer
- 138360
> [GPU] Disallow OneDNN usage of FP32 input with compressed weights on FC

- docs/dev/build_linux.md
- Identified an issue where enabling the oneAPI environment during the compilation of OpenVINO from source code on Linux causes the compilation to fail.
- This issue seems to occur due to conflicts between the oneAPI environment and the OpenVINO build process.
- To address this, I have added a warning in the building document advising users to disable the oneAPI environment during the build process.
- This change will help users avoid compilation failures and ensure a smoother build process.
- I have tested the build process with the oneAPI environment disabled and confirmed that the compilation completes successfully.
> update build linux readme

- src/common/transformations/src/transformations/op_conversions/convert_ti_to_sequences.cpp
- src/frontends/tensorflow_common/src/helper_transforms/tensor_list_ops_resolver.cpp
**Details:** Fix leftovers for Keras LSTM fusion transformation https://github.com/openvinotoolkit/openvino/pull/25170
> [TF FE][MOC] Fix leftovers for Keras LSTM fusion transformation

- src/bindings/js/node/include/type_validation.hpp
- src/bindings/js/node/src/core_wrap.cpp
- src/bindings/js/node/src/type_validation.cpp
- src/bindings/js/node/tests/basic.test.js
- src/bindings/js/node/tests/read_model.test.js
- Each error msg concerned the 'compiledModelSync' method. 
- A new parameter with method name was added to `get_parameters_error_msg`
> [OV JS] Fix hardcoded error msg

- src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_1x1.cpp
It's the regression from SA Conv fsv16 enable.
- *ticket-id*
> [GPU] Fix SD1.5 2.1 dynamic failure.

- .github/workflows/linux.yml
All GPU hosts are unexpectedly offline, so we have to wait for lab maintainers
> [GHA] Temporarily remove GPU tests from mandatory

- src/plugins/intel_gpu/include/intel_gpu/graph/serialization/cl_kernel_data_serializer.hpp
- src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp
- src/plugins/intel_gpu/src/kernel_selector/micro_utils.hpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- Add microkernels settings serialization/deserialization logic to be able to use it after model import in update dispatch data functions
- Limit head size for micro SDPA by 256.
- *CVS-145786*
- *CVS-145787*
> [GPU] Serialize micro kernel settings

- src/common/snippets/include/snippets/pass/tokenization.hpp
- src/common/snippets/src/pass/mha_tokenization.cpp
- src/common/snippets/tests/include/utils.hpp
- src/common/snippets/tests/src/pass/mha_tokenization.cpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/plugins/intel_cpu/tests/unit/snippets_transformations/arm/snipptes_mark_skipped.cpp
- src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/fake_quantize_tokenization_test.cpp
- src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/snipptes_mark_skipped.cpp
- *CP Plugin disabled MHA tokenization with only dynamic MatMuls. However, there are some MHA patterns with static MatMuls but with dynamic inputs of intermediate ops. It was not covered by the current implementation - Snippets tokenized these patterns and couldn't execute.*
- *Added the field `is_dynamic_mha_supported` to `SnippetsTokenization::Config` to adjust dynamic MHA tokenization for backends - now we check for dynamic shapes all tokenized operations in MHA pattern*
- *Added unit test with pattern from the ticket*
- *143406*
> [Snippets] Disabled tokenization of MHA pattern with dynamic  ops

- src/plugins/intel_gpu/src/graph/fully_connected.cpp
- src/plugins/intel_gpu/tests/unit/fake_alignment/fc_fake_alignment_test.cpp
- Skip fc fake alignment when fused desc has full tensor input
- 144293
> [GPU] Skip fc fake alignment when fused desc has full tensor input

- src/frontends/pytorch/src/op/layer_norm.cpp
- tests/layer_tests/pytorch_tests/test_layer_norm.py
- *aten::layer_norm support extended for support normalized shapes represented as non constant and multiple dims*
tested with stable-audio model
- TBD
> [PT FE]: update layer norm for support non-static normalized shape

- src/plugins/intel_gpu/src/kernel_selector/kernels/adaptive_pooling/adaptive_pooling_kernel_ref.cpp
- Add TensorOffset support key in adaptive pooling ref kernel as the kernel is using INPUT0_GET_INDEX() macro
- 144826
> [GPU] Add TensorOffset support key in adaptive pooling ref kernel

- src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_1x1.cpp
- This PR fixed the `convolution_gpu_bfyx_f16_1x1` kernel to set the vector size of fused ops to updated `blockWidth`.
> [GPU] fixed to update dispatchData.blockWidth instead of jit constant

- tests/layer_tests/common/layer_test_class.py
- Difference in boolean results was causing an unexpected issue while validation. We don't need to know max difference of a boolean array, just highlight it exists.
- 137495
> [LayerTests] Added handling of a boolean results

- src/plugins/intel_gpu/src/graph/crop.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.h
- src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/include/reshape_inst.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/reshape.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- Apply in place crop for dynamic shape at runtime
- 143096
> [GPU] Enable runtime buffer fusing for crop

- src/plugins/template/backend/ops/gather.cpp
- Added u64 support for the indices of Gather. 
- https://github.com/openvinotoolkit/openvino/issues/23545
> [==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from conformance_Gather/ReadIRTest
[ RUN      ] conformance_Gather/ReadIRTest.Inference/Op=Gather.8_Type=f32_Shape=dynamic_IR=1c727cc96123227a9fe6c3079a497fd64a04f273bff45b5ea56a3c0d577eca8e_Device=TEMPLATE_Config=()
MEM_USAGE=31860KB
[ CONFORMANCE ] Influence coefficient: 4.72987e-05
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is started
[ PLUGIN      ] `SubgraphBaseTest::compile_model()` is finished successfully. Duration is 0.143964s
RANGE FOR PARAMETER: Gather-8_0  start from: 0.000000  range: 8  resolution: 32  seed: 1
RANGE FOR PARAMETER: Gather-8_1  start …
> [GoodFirstIssue][OP CONFORMANCE][TEMPLATE] Added u64 support for the indices of Gather

- src/frontends/common/src/random_normal_helper.cpp
- src/frontends/onnx/frontend/src/op/multinomial.cpp
- src/frontends/onnx/frontend/src/op/random_uniform.cpp
- src/frontends/onnx/frontend/src/op/random_uniform_like.cpp
- src/frontends/onnx/frontend/src/utils/common.hpp
- src/frontends/onnx/tests/onnx_import.in.cpp
- src/frontends/onnx/tests/tests_python/test_ops_random.py
- Removed workaround which caused unexpected collisions in case seed -1 < seed < 1
- 123003
> Fixed behavior of a seed interpretation when it is float

- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- Previously, any node that had an `optimized_out` node in its dependencies, which in turn had an input `dynamic` node in their dependencies (something like: `dynamic_node -> optimized_out_node -> current_node`), could be marked as mutable due to the `is_mutable_input()` check in the `network::allocate_primitive_instance()` call. This forced `set_arguments()` call at every iteration (because of `has_mutable_input()`), despite the fact that the actual buffers remained the same. This change narrows the `is_mutable_input()` check to only actual mutable nodes, moving the optimized_out node dynamic dependencies check to runtime, thus allowing us to avoid unnecessary `set_arguments()` calls
- Additionally, this change allows us to determine a little earlier whether `update_impl()` is really …
> [GPU] Reduce the number of set_arguments() and update_impl() calls

- tests/layer_tests/tensorflow_tests/test_tf_ApproximateEqual.py
- tests/layer_tests/tensorflow_tests/test_tf_BinaryOps.py
- Skipping test on GPU with FP16 precision due to sporadic misalignment in a results between original framework and OV
- 137495
> [TF] Layer tests has a GPU mismatch

- docs/articles_en/get-started/configurations/configurations-intel-gpu.rst
- docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst
- docs/articles_en/get-started/install-openvino/install-openvino-genai.rst
- docs/articles_en/openvino-workflow/deployment-locally.rst
Removing mentions of Ubuntu 24.04 from 24.2.
24.2 doesn't support Ubuntu 24.04.
> [DOCS] Removing Ubuntu 24.04 from 24.2

- src/core/src/pass/serialize.cpp
- src/core/tests/pass/serialization/rt_info_serialization.cpp
- src/frontends/ir/src/ir_deserializer.cpp
- src/frontends/ir/tests/rt_info_deserialization.cpp
- tools/mo/openvino/tools/mo/utils/ir_engine/ir_engine.py
- Fixed an xml serialization/deserialization in case name isn't xml-compatible
- 131514
> [IR] Changed RT Info nodes naming (compatible with an old)

- src/plugins/intel_npu/src/plugin/npuw/partitioning/online/snapshot.cpp
Change sorting order to prioritize fusing tail (instead of head) of the subgraph of the original model
> [NPUW] Change sorting order in online partitioning

- src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
This PR defines public and private properties in `npuw::CompiledModel`:
- All public properties and hints from `intel_npu::CompiledModel` become public properties in `npuw::CompiledModel`
- All `*NPUW*` properties are private
- *ticket-id*
> [NPUW] Properties for npuw::CompiledModel are split to private and public

- src/bindings/js/node/include/helper.hpp
- src/bindings/js/node/include/model_wrap.hpp
- src/bindings/js/node/include/read_model_args.hpp
- src/bindings/js/node/lib/addon.ts
- src/bindings/js/node/src/async_reader.cpp
- src/bindings/js/node/src/core_wrap.cpp
- src/bindings/js/node/src/helper.cpp
- src/bindings/js/node/src/model_wrap.cpp
- src/bindings/js/node/tests/read_model.test.js
- Add `readModel(model: string, weights: Tensor): Promise<Model>` and `readModelSync(model: string, weights: Tensor): Model`
- Improve error reporting and parameter validation for readModel
- Fix wrapping up Model in readModel(); on js side instanceof always operator gave false 
- Change static ModelWrap::wrap method to function similar to other functions for conversion
- *CVS-134817*
> [OV JS] Add readModel(model:str, weights: Tensor) sync&async

- docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/movement/scatter-nd-update-15.rst
- *Update ScatterNDUpdate-15 description for duplicated indices that update order is unspecified*
- *Fix to py example*
Change is motivated by issues with developing plugin implementation that wouldn't introduce performance regressions compared to previous version.
> [OP][Spec] Update ScatterNDUpdate-15 duplicated indices behavior

- src/plugins/intel_cpu/src/graph_optimizer.cpp
- src/plugins/intel_cpu/src/graph_optimizer.h
- src/plugins/intel_cpu/src/nodes/reorder.cpp
- src/plugins/intel_cpu/tests/unit/graph/merge_transpose_reorder_test.cpp
MergeReorderAndTranspose fuses Reorder->Reshape->Transpose sequences into one Reorder, which can be optimized or not (depending on inplace characteristics of the nodes). In case of non optimized reorder OneDNN primitive is used, which doesn't support reordering in case of different ranks on input and output. This PR adds the corresponding logic which prevents reorder fusions in non optimized case and different ranks.
- *CVS-144935*
> [CPU] Avoid Reorder->Reshape->Transpose fusion in case of non optimized Reorder

- src/plugins/intel_gpu/include/intel_gpu/primitives/fully_connected.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/concatenation_onednn.cpp
- `concatenation_onednn` may have no `_prim`. In this case, some class variables were not set properly with model caching.
- This PR fixes this bug by calling `primitive_impl`'s `save()` and `load()` to set some variables, such as `cldnn::primitive_impl::_is_dynamic` and so on.
- 145734
- 146050
> [GPU] fixed onednn_concat to save and load primitive_impl's info when it has no _prim

- .gitmodules
- cmake/toolchains/riscv64-071-thead-gnu.toolchain.cmake
- src/plugins/intel_cpu/CMakeLists.txt
- src/plugins/intel_cpu/thirdparty/CMakeLists.txt
- *Support THead C910v (`rv64gcv0p7_zfh_xtheadc`)*
- *Added the separate cmake toolchain for T-Head CPUs with rvv071*
- *N/A*
> [RISCV64] Added SHL submodule support and T-Head toolchain

- src/common/transformations/src/transformations/op_conversions/convert_maxpool_downgrade.cpp
- src/common/transformations/tests/op_conversions/convert_maxpool_downgrade_test.cpp
- The workaround subgraph, which previously was in PT FE, was enabled for dynamic input shapes. When moving it to transformations it was decided it does not fully support dynamic shapes, but it broke some models. This PR fully aligns previous behavior of PT FE with the transformation.
- The same workaround subgraph was applied for dynamic shapes as well, which can be seen in https://github.com/openvinotoolkit/openvino/pull/24846
- CVS-145719
> Align the behavior of CEIL_TORCH workaround subgraph with previous PT FE implementation

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/softmax_gpu_bf.cl
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/softmax.cpp
- Use output buffer as intermediate buffer instead of my_chunk to avoid buffer overfill when dynamic shape
- 136398
- 124503
> [GPU] Use output buffer as intermediate buffer in softmax_gpu_bf kernel

- docs/sphinx_setup/api/api_reference.rst
Changing labels of items in the `API Reference` section. Adding mention of JavaScript language.
> [DOCS] Fix API items in menu

- docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/shape/squeeze-1.rst
- Updated note about 2024.3 changes (no throw on non-squeezable dims)
- Additional note clarifying dynamic dimension cases, it describes behavior before and after the changes.
It was implemented this way before the 2024.3 update, and is needed for backward compatibility.
Related PR:
- https://github.com/openvinotoolkit/openvino/pull/24715
- related to 142387
> [Op][Spec] Squeeze - additional notes for behavior clarification 

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/tile_ops.cl
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp
- Fixed compiler failure for micro sdpa with head size = 256 due to missing block read/write declarations with vec size = 16
- Added missing indirect flags check for onednn gemm
> [GPU] Fix micro sdpa with head size 256

- src/inference/include/openvino/runtime/intel_npu/properties.hpp
- src/plugins/intel_npu/src/al/include/intel_npu/al/config/compiler.hpp
- src/plugins/intel_npu/src/al/include/npu_private_properties.hpp
- src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- src/plugins/intel_npu/tests/functional/behavior/npu_driver_compiler_adapter/properties_compatibility.cpp
- src/plugins/intel_npu/tests/functional/behavior/ov_plugin/internal_properties_tests.cpp
There are new added options for NPU_COMPILATION_MODE_PARAMS, need to skip for old driver compiler.
- *146197*
> Skip new params for old driver compiler

- src/common/transformations/src/transformations/convert_precision.cpp
- src/common/transformations/tests/utils/convert_precision.cpp
- src/core/reference/include/openvino/reference/convert.hpp
- src/core/reference/src/op/convert.cpp
- Use vectorized version of bf16 -> f16 in `ConvertPrecision`.
- N/A
> [Transformations] Convert precision use optimized version for bf16 -> f16

- src/plugins/intel_gpu/src/graph/impls/ocl/group_normalization.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/group_normalization_gpu_b_fs_yx_fsv16.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/group_normalization/group_normalization_kernel_b_fs_yx_fsv16.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/group_normalization/group_normalization_kernel_b_fs_yx_fsv16.h
- src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp
- Currently, the `group_normalization_gpu_ref` kernel shows poor performance compared to other ones. So, it should not be selected if possible.
- The purpose of this PR is to prevent the situation where the ref kernel is selected as much as possible by using a combination of reorder and opt kernels.
> [GPU] fix regression by group_norm_ref kernel

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
This reverts commit 5cfbd06bd2dcda6db93e420ccc99f390cf940d1f.
Not needed anymore since missing functionality is now implemented in OneDNN
- Revert commit disallowing OneDNN usage of FP32 input with compressed weights on FC
- 138360
> Revert "[GPU] Disallow OneDNN usage of FP32 input with compressed weights on FC (#25232)"

- docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst
Port from https://github.com/openvinotoolkit/openvino/pull/25549
Jira: 146689
Fixing command line in the "Install on Windows from the archive file" article.
> [DOCS] Command Line fix - Windows Archive for 24.2

- src/common/util/CMakeLists.txt
- src/common/util/include/openvino/util/file_util.hpp
- src/inference/src/model_reader.cpp
- src/inference/tests/functional/ov_core_test.cpp
- This reverts commit a904d9b94520ecc074a838ea23d69478d4e5b60f.
- In the #24864, the FEs check if file can be opened at given path. If not possible then there is exception.
- CVS-146678
- Relates to CVS-142055
> Revert "OVCore to check for symlinks before opening files (#24781)"

- src/tests/functional/plugin/shared/CMakeLists.txt
- src/tests/functional/plugin/shared/include/behavior/ov_infer_request/properties_tests.hpp
- "canSetExclusiveAsyncRequests" & "withoutExclusiveAsyncRequests" do the same thing. Will remove one
- Clean code used for API 1.0
- [29948](https://jira.devtools.intel.com/browse/CVS-129948)
> Remove redundant test

- src/plugins/intel_cpu/src/graph.cpp
- src/plugins/intel_cpu/src/graph.h
to reduce infer overhead.
Even dnnl stream is very lightweight object, it is not actually
allocated on stack but performs dynamic memory allocation in constructor
- *ticket-id*
> [CPU] Create dnnl stream once per graph

- src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
- *Replace "," to "." in InputShapes ostream insertion op (<<)
-  As a result, InputShapes will be printed in the tests output as []_([1.16.384.64]) instead of []_([1,16,384,64])*
- *This is needed to improve developer experience, so the tests output will be displayed correctly in IDEs.*
- *This is an example on how tests output is displayed now in Clion IDE:*
- *This is how tests output will be displayed after the proposed changes:*
- *-*
> [IE TESTS] Change InputShapes ostream insertion op delimiter

- src/bindings/python/tests/test_graph/test_constant.py
- skip randomly failing test: test_float_to_f8e8m0_convert
- [*145281*](https://jira.devtools.intel.com/browse/CVS-145281)
- https://github.com/openvinotoolkit/openvino/pull/25403
> skip randomly failing test: test_float_to_f8e8m0_convert

- src/bindings/python/src/openvino/runtime/ie_api.py
- src/bindings/python/src/openvino/runtime/opset6/ops.py
- src/bindings/python/src/openvino/runtime/opset8/ops.py
- src/bindings/python/src/openvino/runtime/utils/decorators.py
- src/bindings/python/tests/test_graph/test_create_op.py
- cherry-picked https://github.com/openvinotoolkit/openvino/pull/25583
-[CVS-146848](https://jira.devtools.intel.com/browse/CVS-146848)
>  [PyOV]  Cherry-picked "Support kwargs in overloading"

- src/inference/dev_api/openvino/runtime/threading/cpu_streams_executor.hpp
- src/inference/src/dev/threading/cpu_streams_executor.cpp
- src/plugins/intel_cpu/src/compiled_model.cpp
- src/plugins/intel_cpu/src/node.cpp
- src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_utils.cpp
- src/plugins/intel_cpu/src/nodes/executors/mlas/mlas_gemm.cpp
- src/plugins/intel_cpu/src/nodes/input.cpp
This reverts commit 446b2f08ed99c536c60e15497aeccf371af9403b.
PR #24386 led to the issues with CPU plugin weights caching, this sporadically affected accuracy in a negative way. This PR reverts PR #24386 changes in order to restore stability.
- *CVS-146939*
> Revert "[CPU] Avoid shared weights double repacking in latency mode"

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/group_normalization_gpu_b_fs_yx_fsv16.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/group_normalization_gpu_bfyx_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/group_normalization/group_normalization_kernel_b_fs_yx_fsv16.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/group_normalization/group_normalization_kernel_bfyx_opt.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp
- This PR fixes a issue of `group_normalization` for group sizes larger than max local work group size (such as 1024 or 512).
- 138954
> [GPU] fixed group_normalization for large group sizes

- src/core/include/openvino/pass/pattern/op/pattern.hpp
- src/core/include/openvino/pass/pattern/op/wrap_type.hpp
- src/core/src/pattern/matcher.cpp
- src/core/src/pattern/op/pattern.cpp
- src/core/src/pattern/op/wrap_type.cpp
- Make pattern matcher logs a little bit more readable. Example:
Before:
```
matcher.cpp 143	[MATCHER] Match arguments at opset1::MatMul MatMul_67 (opset1::Parameter in_matmul[0]:f16[1,32,1,30], opset1::Concat Convert_65[0]:f16[1,32,30,80]) -> (f16[1,32,1,80]) for pattern util::patternAnyType patternAnyType_27359 (util::patternLabel patternLabel_27357[0]:dynamic[...], util::patternAnyType patternAnyType_27358[0]:dynamic[...]) -> (dynamic[...])
matcher.cpp 143	[MATCHER] Match arguments at opset1::Reshape Transpose_63 (opset1::Parameter new_token_input[0]:f16[1,1,32,80], opset1::Constant Constant_27953[0]:i64[4]) -> (f16[1,32,1,80]) for pattern util::patternAnyType patternAnyType_27618 (util::patternAnyType patternAnyType_27615[0]:dynamic[...], util::patternLabel …
```
> [TRANSFORMATIONS] Improve pattern matcher debug logs

- src/plugins/intel_cpu/src/nodes/reduce.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/reduce.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- *Following the IEEE 754 standard for floating-point arithmetic, instructions that operate on floating-point numbers (e.g., vdivps and cvtps2dq) rounds to the nearest value by default. On the other hand, C++ standard requires the result of division round toward zero if both operands are integers. To comply with both standards, Reduce node will round the floating point result toward zero before storing, only when both input and output precisions are integers.*
- *The patch for CVS-142465 is also included in this PR, because they share the same revised test suite. In this part, I exchange the order of the two logic blocks about revising output precision. Because output precision should be settled before the final precision check with post ops.*
- *Regarding test cases, the arguments of …
> [CPU] Fix rounding and fusing with FQ issues for Reduce node

- src/plugins/intel_cpu/CMakeLists.txt
- src/plugins/intel_cpu/src/graph_optimizer.cpp
- src/plugins/intel_cpu/src/node.cpp
- src/plugins/intel_cpu/src/nodes/executors/executor.cpp
- src/plugins/intel_cpu/src/nodes/executors/executor.hpp
- src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
- src/plugins/intel_cpu/src/nodes/executors/shl/shl.hpp
- src/plugins/intel_cpu/src/nodes/executors/shl/shl_fullyconnected.cpp
- src/plugins/intel_cpu/src/nodes/executors/shl/shl_fullyconnected.hpp
- src/plugins/intel_cpu/src/nodes/executors/shl/shl_utils.hpp
- src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
- src/plugins/intel_cpu/src/onednn/iml_type_mapper.cpp
- src/plugins/intel_cpu/src/onednn/iml_type_mapper.h
- src/plugins/intel_cpu/tests/functional/CMakeLists.txt
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/riscv64/shl/matmul.cpp
- *Reused FC RVV from SHL*
- *The PR  to SHL dev branch with accuracy fix for FC f32: https://github.com/openvinotoolkit/shl/pull/3*
- *N/A*
> [RISCV64][SHL] Added FC FP32 executor

- src/plugins/intel_gpu/include/intel_gpu/runtime/shape_predictor.hpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/runtime/shape_predictor.cpp
- Fixed two issues 
- 1) KV cache was allocating redundant memory when it requires new memory
- 2) At a new inference, KV cache was setting a padding value as the one used in the previous execution (last token for the previous generation), which caused memory usage inefficiency. 
- After fixing above issues, in some cases, memory is more frequently allocated because 
- 1) switching shape 1024 => 32 : happens reclaiming (previously due to the wrong padding, it is not reclaimed.)
- 2) switching shape 32 => 1024 : new alloc needed at the first infer, but shape history is not tracked yet. So during 3 iteration, it is allocating new memory. 
- Additional fix to resolve above issues: 
- 1) For initial allocation of kv cache, enforce prealloc with custom prealloc count (known value of 128 + …
> [GPU] Improve kv cache memory allocation efficiency

- .github/workflows/linux.yml
> Return GPU tests to mandatory 2024.3

- src/common/transformations/src/transformations/common_optimizations/reshape_sequence_fusion.cpp
- src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
- src/common/transformations/src/transformations/symbolic_transformations/symbol_optimization.cpp
- src/core/dev_api/openvino/core/bound_evaluation_util.hpp
- src/core/shape_inference/include/utils.hpp
- src/core/src/bound_evaluate.cpp
- src/core/src/op/divide.cpp
- src/core/src/op/mod.cpp
- src/core/tests/bound_evaluate.cpp
-  Align approach -- some of evaluate_* functions already are under ov::util namespace.
- CVS-147171
> [Core] move evaluate_* from ov to ov::util namespace

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- Previously there was an issue in accumulator with half precision in SLM kernel of fc_tiled_opt kernel.: It was accumulating fp16 value in the innermost loop, however, when the accumulated value becomes bigger but newly added values are still small, the small added values are being ignored. Fixed this issue by accumulating for more values to be added. 
- *138438*
> [GPU] Fix accumulate issue in FC

- src/plugins/intel_npu/src/al/include/npu.hpp
- src/plugins/intel_npu/src/al/src/npu.cpp
- src/plugins/intel_npu/src/backend/include/zero_device.hpp
- src/plugins/intel_npu/src/backend/include/zero_host_tensor.hpp
- src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp
- src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp
- src/plugins/intel_npu/src/backend/include/zero_wrappers.hpp
- src/plugins/intel_npu/src/backend/src/zero_device.cpp
- src/plugins/intel_npu/src/backend/src/zero_host_tensor.cpp
- src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
- src/plugins/intel_npu/src/backend/src/zero_wrappers.cpp
- src/plugins/intel_npu/src/plugin/include/remote_context.hpp
- src/plugins/intel_npu/src/plugin/src/remote_context.cpp
- src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_api.hpp
- src/plugins/intel_npu/src/utils/src/zero/zero_api.cpp
- src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp
- src/plugins/intel_npu/tests/functional/behavior/remote_tensor_tests/remote_run.hpp
- *Allocate a Host L0 buffer when the create host tensor method is used*
- *Do not chain the mutable descriptor, call the update mutable command list after each descriptor instead*
- *Do not throw an error if using an older ze_loader only if the unsupported functions are going to be called*
- *Call updateMutableCommandList after set_tensor method is used*
- *Add extra test cases for batching flow using MCL*
- *EISW-131915*
> [NPU] Adding support for the remote tensor feature - [Part II - leftovers]

- src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp
- src/plugins/intel_npu/src/backend/include/zero_memory.hpp
- src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- src/plugins/intel_npu/src/backend/src/zero_memory.cpp
- From a design perspective, the allocator is meant to allocate a pool of tensors, not to represent a single allocated tensor. The current PR aims to change the NPU plugin's `HostMemAllocator` as to comply with this rule.
- No real improvement is brought in terms of functionality/performance, except for reusing some allocators inside the `ZeroInferRequest` ctor.
- *EISW-130249*
> [NPU] Modifying the "HostMemAllocator" class such that it won't hold the last allocated buffer anymore

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- Fix issue to calculate present layout's padding for KVCache
- 146876
> [GPU] Fix issue to calculate present layout's padding for KVCache

- src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/matmul.cpp
- src/plugins/intel_cpu/tests/functional/utils/fusing_test_utils.cpp
- src/plugins/intel_cpu/tests/functional/utils/fusing_test_utils.hpp
- Add a check to reject non-supported FakeQuantize from fusing into FC node, so they can run in standalone mode w/o causing exceptions when composing oneDNN postOps.
- port from https://github.com/openvinotoolkit/openvino/pull/23009
- add test case
- *CVS-131890*
> [CPU] only allow per-oc or per-tensor FQ fusing into FC 

- docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
[mixtral-8x7b-instruct-v0.1-int4-ov](https://huggingface.co/OpenVINO/mixtral-8x7b-instruct-v0.1-int4-ov/) didn't have `generation_config.json` therefore generation continued ininitely. EOS_TOKEN_ID was red correctly but during generation it was not met.
Updated docs so in every generate call max_new_tokens is set either in arguments or via default generation config
`pipe.set_generation_config({'max_new_tokens': 100, 'num_beam_groups': 3, ...)`
tickets: CVS-146933 CVS-146324
> Add max_new_tokens to every generate call in genai-guilde

- src/plugins/intel_gpu/src/graph/crop.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- Add condition for dynamic shape split_lengths for in place crop buffer fusing
- 146739
> [GPU] Add condition for dynamic shape split_lengths for in place crop buffer fusing

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- Use get_output_pshape() in crop_in_place_optimization::match() to check user output dynamic shape because user would have valid_output_layouts=false
- 146725
> [GPU] Use get_output_pshape() in crop_in_place_optimization::match() to check user output dynamic shape

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- Avoid crop buffer fusing when dynamic shape and squeeze/unsqueeze reshape mode
- 146626
> [GPU] Avoid crop buffer fusing when dynamic shape and squeeze/unsqueeze reshape mode

- src/plugins/intel_npu/tools/single-image-test/main.cpp
Cherrypicked changes from here PR: pull/11621.
- *item1*
- *...*
- *ticket-id*
> Single Image Test: Maintaining blob file name order in Single-Image-Test dump reference output

- src/plugins/intel_npu/CMakeLists.txt
- Build NPU internal tools only if tests are enabled
> NPU CMakeLists.txt: Build NPU internal tools only if tests are enabled

- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- [GPU] Fixed fc tile size for better perf for small N size (4096) kernels in MTL
- To get 3-5% gain on 2nd token latency on MTL
- *ticket-id*
> [GPU] Fixed fc tile size for better perf for small N size (4096) kernels 

- docs/scripts/tests/suppress_warnings.txt
- docs/sphinx_setup/api/genai_api/api.rst
Fixed building of GenAI Python API. Now all methods are shown.
> [DOCS] OV GenAI Python API template fix

- src/plugins/intel_gpu/include/intel_gpu/runtime/engine.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/memory_caps.hpp
- src/plugins/intel_gpu/src/runtime/engine.cpp
- Any additional locking and synchronization on memory allocation might have negative impact on MT execution.
- `std::map` has very slow access are requires lock on every access. We can use `std::array` instead to hold compile time known number of buckets.
- `array` container has lower access latency and memory overhead.
- We might me able to remove mutex lock on stat collection.
> [GPU] Use array for tracking memory usage instead of map

- src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
- *Useless reorders lead to incorrect propagation of weights formats*
- *[146165](https://jira.devtools.intel.com/browse/CVS-146165)*
> [GPU] Disabled adding reorders for runtime weights in reorder_inputs pass

- src/plugins/intel_cpu/src/graph_optimizer.cpp
- *ShlFCExecutor supports only f32 weights for now. If there is Convert to FP32 between FP16 Weights and FC, these Convert+Weights should be constant-folded on CPU Plugin side. Otherwise, ShlFCExecutor won't be choosen. This PR disables the optimization `FuseFCAndConvertOnWeights` in SHL case*
- *N/A*
> [RISCV64] Disabled FuseFCAndConvertOnWeights in SHL case

- src/frontends/tensorflow/src/tf_utils.cpp
- tests/layer_tests/tensorflow_tests/test_tf_BinaryOps.py
- tests/layer_tests/tensorflow_tests/test_tf_Bitwise.py
**Details:** Fix u16 bug "Tensor data with element type u16, is not representable as pointer to i32"
**Ticket:** 122716
> [TF FE] Stabilize Bitwise layer tests on all platforms and fix u16 bug

- src/plugins/intel_gpu/src/graph/impls/ocl/group_normalization.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/group_normalization_gpu_b_fs_yx_fsv16.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/group_normalization_gpu_bfyx_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/group_normalization/group_normalization_kernel_b_fs_yx_fsv16.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/group_normalization/group_normalization_kernel_bfyx_opt.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/group_normalization/group_normalization_kernel_selector.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp
- This PR updates the `group_normalization_bfyx` kernel to support bfzyx format.
- Additionally, this PR fixes the output feature calculation logic of the group_norm_fsv16 kernel and a model caching related logic for dynamic model.
- 147841
> [GPU] group_normalization for bfzyx

- cmake/extra_modules.cmake
-  To allow to select developer package of specific version
- Required for GenAI build as part of OpenVINO extra modules
> Added version for OpenVINO developer package local version

- src/plugins/intel_cpu/src/nodes/executors/acl/acl_transpose.hpp
- src/plugins/intel_cpu/src/nodes/executors/transpose_list.cpp
- The latest performance reports on Ampere show ACL transpose executor provides better performance rather than MLAS Transpose executor (details are in the ticket). Therefore,  MLAS Transpose executor priority has been decreased.
- Redundant check has been deleted in ACL Transpose executor.
- CVS-148625
> [CPU][ARM] MLAS transpose executor deprioritised

- src/tests/test_utils/common_test_utils/include/common_test_utils/ov_tensor_utils.hpp
- *Commented out debug prints in input range generation in test infrastructure to avoid large outputs during test executions:*
- *N/A*
> [Tests] Commented out debug prints in input range generation

- src/plugins/intel_npu/tools/single-image-test/main.cpp
- Adding a new optional parameter for SIT to specify a directory with reference outputs. So instead of running NetsVal-CalcRef on CPU or TEMPLATE we can re-use predefined reference outputs. However, their names must comply with the existing name convention
- E-131878
> Add folder parameter for reference blobs in SIT

- src/plugins/intel_cpu/src/graph.cpp
- src/plugins/intel_cpu/src/graph_dumper.cpp
- src/plugins/intel_cpu/tests/unit/graph/resolve_edge_conflicts_test.cpp
- *Align cpu execution order before/after ResolveComplexInplaceConflicts()*
- *Keep order information of Results and Parameters when dump CPU graph to ov::Model*
- *Let MemoryInput always execute first to avoid potential issue because it will update its sibling MemoryOutput memory after execution*
- *CVS-134638*
- *CVS-148497*
- CPU execution order of some nodes may changes after https://github.com/openvinotoolkit/openvino/blob/2024.2.0.dev20240513/src/plugins/intel_cpu/src/graph.cpp#L285. Sometimes that may give ResolveComplexInplaceConflicts() incorrect execution order information. That may lead to  ResolveComplexInplaceConflicts() get the wrong conclusion which edge memory should be shared. So this PR add SortTopologically() right before ResolveComplexInplaceConflicts() to let …
> [CPU] Align cpu execution order before/after ResolveComplexInplaceConflicts()

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.h
- src/plugins/intel_gpu/src/graph/include/reshape_inst.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/reshape.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/rope_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/rope/rope_kernel_base.cpp
- src/plugins/intel_gpu/src/plugin/ops/reshape.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- src/plugins/intel_gpu/tests/unit/shape_infer/reshape_si_test.cpp
These changes fix a significant accuracy issue (reducing perplexity from 120 000 to 17) for Llama models with precalculated constant sin/cos values. However, there is still a problem with sin/cos representation in FP16 precision, which will be addressed in a separate PR.
- Fixed Crop->Reshape (Squeeze/Unsqueeze modes) buffer optimization
- Update rope_ref kernel to support dynamic paddings for cos/sin inputs
- Fix propagate_padding() function and update shape infer tests
- [CVS-148220](https://jira.devtools.intel.com/browse/CVS-148220), [CVS-146283](https://jira.devtools.intel.com/browse/CVS-146283)
> [GPU] Fix Crop->Reshape (Squeeze/Unsqueeze modes) buffer optimization

- src/plugins/intel_cpu/src/nodes/executors/acl/acl_mvn.hpp
- This configuration (initAcrossChannels is true and NHWC is used) was disabled for ACL executor to enable `yolo_v3_tiny`. The last check shows this restriction is not required anymore. 
- *ticket-id*
> [CPU][ARM] Enable ACL MVN executor for `initAcrossChannels` option in NHWC layout

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- This revert https://github.com/openvinotoolkit/openvino/pull/25700
- As support for Crop->Reshape(Squeeze/Unsqueeze modes) buffer optimization was added by https://github.com/openvinotoolkit/openvino/pull/25836
- 146626
> Revert "[GPU] Avoid crop buffer fusing when dynamic shape and squeeze/unsqueeze reshape mode"

- src/common/transformations/src/transformations/fp16_compression/mark_subgraphs_to_keep_in_mixed_precision.cpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- Disable per pass validation for GPU specific passes and mixed precision markup to improve model loading time
> [GPU][TRANSFORMATIONS] Disable per pass validation in some cases

- src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/reorder/reorder_kernel_bfyx_to_blocked_format.cpp
- *Useless reorders lead to incorrect propagation of weights formats -> disabled adding reorders for runtime weights in reorder_inputs pass*
- *Fix lws calculation for reorder_kernel_bfyx_to_blocked_format kernel*
- *[146165](https://jira.devtools.intel.com/browse/CVS-146165)*
> [GPU] Runtime weights fix and reorder_kernel_bfyx_to_blocked_format kernel fix

- src/inference/include/openvino/runtime/intel_npu/level_zero/level_zero.hpp
- src/plugins/intel_npu/src/backend/src/zero_init.cpp
- src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
- *The UD28 Windows driver version doesn't support as expected the MutableCommandList feature - just disable this feature from the plugin in case this driver is used*
- *EISW-133845*
> [NPU] Disable MCL in case of UD28

- src/plugins/intel_gpu/src/graph/kv_cache.cpp
- *Fixed extra `std::move()` warning-error from https://github.com/openvinotoolkit/openvino/pull/25886*
- *N/A*
> [GPU] Fixed moving a temporary object

- src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp
- Cleaning up unnecessary std::moves from the patterns.
- *ticket-id*
> NPUW: Removing unnecessary std::moves from the decompression patterns

- src/bindings/js/node/include/model_wrap.hpp
- src/bindings/js/node/lib/addon.ts
- src/bindings/js/node/src/model_wrap.cpp
- src/bindings/js/node/tests/unit/model.test.js
Changes as part of this PR include:
* Add a ModelWrap::clone function: Calls the underlying Model.clone function
* Add a ModelWrap::Wrap function to return the cloned model as a Napi::Value
* Update the addon.ts file with the clone method
* Add unit tests for the clone Api
resolves #25402 
- #25402
> [OV JS] Expose Model.clone to Node.js Api

- src/frontends/onnx/frontend/CMakeLists.txt
ONNX frontend has code generation when `BUILD_SHARED_LIBS=OFF` which targets a file inside source directory.
When configuring the project, the generated file is written to the sources directory.
If two configurations are running at the same time (i.e. when trying to build the package with `vcpkg` it configures debug and release builds concurrently), both `cmake` instances append lines to the same file inside source directory which leads to corrupted file content and cryptic build errors.
This change makes the script write generated header file to a directory inside build directory, so that two different configuration processes don't interfere with each other.
> Fix ONNX frontend code generation

- src/common/snippets/include/snippets/generator.hpp
- src/common/snippets/include/snippets/kernel_executor_table.hpp
- src/common/snippets/include/snippets/lowered/linear_ir.hpp
- src/common/snippets/include/snippets/op/subgraph.hpp
- src/common/snippets/include/snippets/runtime_configurator.hpp
- src/common/snippets/src/generator.cpp
- src/common/snippets/src/kernel_executor_table.cpp
- src/common/snippets/src/op/subgraph.cpp
- src/common/snippets/src/runtime_configurator.cpp
- src/plugins/intel_cpu/src/emitters/snippets/cpu_runtime_configurator.cpp
- src/plugins/intel_cpu/src/emitters/snippets/cpu_runtime_configurator.hpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm.hpp
- src/plugins/intel_cpu/src/nodes/subgraph.cpp
- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/subgraph_caching.cpp
- *The Kernel Executor table maps on Expression execution numbers instead of Expressions to avoid dependency between `LinearIR` and binary code*
- *Added Kernel Executor table to `SubgraphCodeGenerator` to be cached with binary code*
- *Added Subgraph caching test*
- *N/A*
> [Snippets][CPU] Added Kernel Executor table caching with binary code

- src/plugins/intel_cpu/src/nodes/executors/shl/shl_fullyconnected.cpp
- src/plugins/intel_cpu/src/nodes/executors/shl/shl_fullyconnected.hpp
- *Moved FullyConnected RVV weights repacking from execution stage to compilation model stage*
- *PR to the SHL repository: https://github.com/openvinotoolkit/shl/pull/6*
- *N/A*
> [RISCV64] Moved FC weights repacking to model compilation stage

- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- When "NPU_USE_NPUW" : "NO"/`false` is passed to `intel_npu::Plugin::compile_model(...)`, it is not removed from incoming OV properties and passes on right to npu plugin's `intel_npu::Config` config causing:
```
[ NOT_FOUND ] Option 'NPU_USE_NPUW' is not supported for current configuration
```
- However, workaround for issue is available: just not passing "NPU_USE_NPUW" : "NO" will result in right behavior is you don't need NPUW.
- *ticket-id*
> Fixed "NPU_USE_NPUW" : "NO" case

- src/plugins/intel_npu/tests/functional/CMakeLists.txt
- src/plugins/intel_npu/tests/functional/behavior/npuw/behavior_tests.cpp
- src/plugins/intel_npu/tests/functional/behavior/npuw/behavior_tests.hpp
- src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/mock_plugins.cpp
- src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/mock_plugins.hpp
- src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/register_in_ov.cpp
- src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/register_in_ov.hpp
- This PR adds mock plugins to test NPUW against
- This PR adds 9 functional behavior tests for NPUW
- *ticket-id*
> Added MockNPU/CPU, FakeNPU/CPU and functional tests

- src/core/CMakeLists.txt
- src/core/src/pass/serialize.cpp
- *Multithreading implementation of the fn OstreamHashWrapper::xsputn()*
- *127331*
> [CORE][CACHE_DIR] xsputn parallel optimization

- src/plugins/intel_gpu/src/runtime/ocl/ocl_event.cpp
- When ocl_user_event is used, it threw exception. Ignore such event during profiling.
> [GPU] Do not throw exception during profiling

- docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/bitwise/bitwise-left-shift-15.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/bitwise/bitwise-right-shift-15.rst
- BitwiseLeftShift & BitwiseRightShift specification
- The API (and broadcast rules) are aligned with frameworks and other binary ops 
for example [logical-and-1.rst](https://github.com/openvinotoolkit/openvino/blob/master/docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/logical/logical-and-1.rst) [bitwise-and-13.rst](https://github.com/openvinotoolkit/openvino/blob/master/docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/bitwise/bitwise-and-13.rst)
- 148533
> [SPEC][Op] BitwiseLeftShift & BitwiseRightShift specification

- src/plugins/intel_gpu/src/plugin/transformations/increase_position_ids_precision.cpp
- src/plugins/intel_gpu/src/plugin/transformations/increase_position_ids_precision.hpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/tests/unit/transformations/increase_position_ids_precision_test.cpp
- This pass adds additional convert nodes on the position_ids input branch (around MatMul and sin/cos operations), targeting to improve rotary position embeddings calculation for FP16 models. Lack of these converts leads to lower accuracy in case if long input sequences (larger than 2048) due to position_ids representation in the FP16 data type, and sin/cos calculation error.
- [CVS-148220](https://jira.devtools.intel.com/browse/CVS-148220), [CVS-146283](https://jira.devtools.intel.com/browse/CVS-146283)
> [GPU] Add IncreasePositionIdsPrecision transformation to improve LLM accuracy in fp16

- docs/dev/cmake_options_for_custom_compilation.md
- docs/dev/static_libaries.md
- *item1*
- *...*
- *ticket-id*
> Updated OpenVINO build docs

- src/core/shape_inference/include/col2im_shape_inference.hpp
- src/core/tests/type_prop/col2im.cpp
- src/plugins/intel_cpu/src/nodes/col2im.cpp
- tests/model_hub_tests/pytorch/hf_transformers_models
- tests/model_hub_tests/pytorch/test_timm.py
- tests/model_hub_tests/pytorch/timm_models
- `trace` case has been fixed, `export` case is still failing for PT FE affected models, but now with an error unrelated to `Col2Im`
- CVS-148673
> Fix `output_size` dynamic dimensions support for `Col2Im-15` for CPU `StaticShape`

- src/plugins/intel_gpu/src/graph/fully_connected.cpp
- src/plugins/intel_gpu/src/graph/include/fully_connected_inst.h
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/include/primitive_type.h
- src/plugins/intel_gpu/src/graph/include/primitive_type_base.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/tests/unit/fake_alignment/fc_fake_alignment_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp
- Revert a part of https://github.com/openvinotoolkit/openvino/pull/25886 related to fake alignment changes to avoid OOR exception
> [GPU] Revert changes for fake alignment

- cmake/developer_package/options.cmake
- Otherwise, options are duplicated with new cmake reruns
> Unset OV_OPTIONS on each cmake run

- src/plugins/intel_gpu/src/graph/include/program_node.h
- src/plugins/intel_gpu/src/graph/program_node.cpp
- This PR updates non-onednn layers not to initialize `onednn_attrs`.
- 149028
> [GPU] updated not to set OneDNN related variables for cldnn layers

- src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/quantize.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/reorder.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/quantize_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/reorder_gpu_test.cpp
- Currently, b_fs_yx_fsv16 blocked format is enabled for convolution operations, but the lack of it for reorder and quantize operations causes runtime static version kernel recompilation. This change enables support for the b_fs_yx_fsv16 format to allow shape-agnostic kernel selection.
- [CVS-145296](https://jira.devtools.intel.com/browse/CVS-145296)
> [GPU] Enable b_fs_yx_fsv16 format for shape-agnostic quantize and reorder kernels

- thirdparty/dependencies.cmake
- They were used only by speech sample which was removed before 2024.0
> Remove installation of cnpy, zlib as part of samples

- src/inference/include/openvino/runtime/intel_gpu/properties.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/kernel.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/custom_primitive.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/multi_stage_primitive.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/include/primitive_type_base.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/runtime/execution_config.cpp
- src/plugins/intel_gpu/src/runtime/kernels_cache.cpp
- src/plugins/intel_gpu/src/runtime/kernels_cache.hpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_kernel.hpp
- src/plugins/intel_gpu/tests/unit/passes/kernels_cache_test.cpp
- This PR adds an ability to reuse single kernel between multiple implementations, resulting in much lower memory pressure in some cases. It can be enabled with `ov::intel_gpu::hint::enable_kernels_reuse(true)` property
- [CVS-145296](https://jira.devtools.intel.com/browse/CVS-145296)
> [GPU] Add an ability to reuse single kernel between multiple implementations

- cmake/dependencies.cmake
- src/inference/tests/unit/CMakeLists.txt
- *update oneTBB 2021.13.0 (https://github.com/oneapi-src/oneTBB/releases/tag/v2021.13.0) for linux/mac*
- *remove debug files for linux and mac (arm64)*
- *147579*
- *143793*
> update oneTBB2021.13.0 on linux/mac

- src/plugins/intel_cpu/docs/debug_capabilities/verbose.md
- src/plugins/intel_cpu/src/graph.cpp
- src/plugins/intel_cpu/src/utils/verbose.cpp
- src/plugins/intel_cpu/src/utils/verbose.h
Levels enable printing of:
- 1 - executable nodes only
- 2 - same as `1` plus `Input` and `Output` nodes
- 3 - same as `2` plus constant path nodes (executed in scope of `compile_model()`)
> [CPU] Introduce additional OV_CPU_VERBOSE levels

- src/frontends/pytorch/src/op/group_norm.cpp
- *Use GroupNormalization for `aten::group_norm` instead of MVN*
- *ticket-id*
> [PT FE] Use GroupNormalization for aten::group_norm instead of MVN

- src/common/snippets/include/snippets/lowered/pass/init_loops.hpp
- src/common/snippets/include/snippets/pass/split_dimension_m.hpp
- src/common/snippets/include/snippets/runtime_configurator.hpp
- src/common/snippets/include/snippets/utils/utils.hpp
- src/common/snippets/src/lowered/pass/init_loops.cpp
- src/common/snippets/src/pass/split_dimension_m.cpp
- src/common/snippets/src/runtime_configurator.cpp
- src/common/snippets/src/utils/utils.cpp
- src/plugins/intel_cpu/src/emitters/snippets/cpu_runtime_configurator.cpp
- src/plugins/intel_cpu/src/emitters/snippets/cpu_runtime_configurator.hpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp
- *Introduced `ParallelWAOptimizer` class, which is used in RuntimeConfigurator to split M dimension of LIR with brgemms in order to optimize parallel work amount*
- *147834*
> [Snippets] Dynamic SplitDimensionM via runtime configurator

- src/plugins/intel_gpu/src/graph/graph_optimizer/mark_shape_of_subgraphs.cpp
- Relaxed condition set in https://github.com/openvinotoolkit/openvino/pull/25601
- Checked with actual model which contains 128x1024 size strided_slice (baichuan 7b) 
- For both platform with small EU count and many EU count, using gpu impl was better
- *ticket-id*
> [GPU] Relaxed condition to select strided_slice impl with gpu

- src/plugins/intel_cpu/src/graph.cpp
- src/plugins/intel_cpu/src/graph.h
- Current version does not clean extra edge in case Convert + Reorder is inserted. In this case we need to remove an edge, which is replaced with Convert node first, and then remove childEdge of the newly inserted Convert node, after Reorder is inserted.
- The idea is to simplify this logic and do one thing at a time:
1. Insert Convert.
2. If Reorder is still necessary for the new inserted edge, it will be handled later in the loop.
It seems to be impossible to write a test for x86 platform, since there is no reorder which does not support precision conversion.
> [CPU] Fix resolve edge conflicts Convert insertion

- src/plugins/intel_gpu/src/plugin/transformations/decompose_reduce_scalar_output.cpp
- Fix CS issues:
Performance inefficiencies  (AUTO_CAUSES_COPY)
Using the "auto" keyword without an "&" causes the copy of an object of type "ov::PartialShape".
- *ticket-id*
> Fix Coverity Scan issue

- src/plugins/intel_cpu/src/nodes/executors/acl/acl_mvn.cpp
- src/plugins/intel_cpu/src/nodes/executors/acl/acl_mvn.hpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/mvn.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/mvn.hpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/mvn.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/mvn.cpp
- Reverts PR https://github.com/openvinotoolkit/openvino/pull/25905
- Fixed layout check in `isSupported` method to cover both 4D and 5D cases
- Removed workaround that skips unsupported cases (NHWC\NDHWC + `across_channels` = false) on ARM
- Moved tests with unsupported cases from common to x64 dir
- *ticket-id*
> [CPU][ARM] Disable ACL MVN executor for NHWC and `across_channels` = false

- src/plugins/intel_gpu/src/graph/include/reshape_inst.h
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- Fix accuracy issue from runtime buffer fusing for crop(https://github.com/openvinotoolkit/openvino/pull/25060)
- If user is MVN and dynamic padding exists, output padding propagation is not supported in the base mode reshape
- oneDNN supports padded input of outer axis only for buffer fusing on static shape
- [CVS-149472](https://jira.devtools.intel.com/browse/CVS-149472)
> [GPU] Fix accuracy issue for StableDiffusion3

- src/common/transformations/src/transformations/convert_precision.cpp
- src/common/transformations/src/transformations/fp16_compression/mark_subgraphs_to_keep_in_mixed_precision.cpp
- src/common/transformations/tests/common_optimizations/mark_subgraph_to_keep_in_mixed_precision_test.cpp
- Fixed accuracy loss in the Range operation due to high value generation for the attention mask in cases of long input sequences
- [CVS-146283](https://jira.devtools.intel.com/browse/CVS-146283)
> [GPU] Fix accuracy loss in Range due to high value generation for attention mask

- src/inference/src/cpp/remote_context.cpp
This patch updates `create_host_tensor()` and `create_tensor()` of `RemoteContext` to update _so to std::shared_ptr of the created remote tensor, preventing the dynamically loaded library from unloading before all remote tensors are destroyed
> [GPU] Fix segmentation fault during remote tensor destruction in the Python API

- src/common/snippets/include/snippets/lowered/loop_info.hpp
- src/common/snippets/include/snippets/lowered/loop_manager.hpp
- src/common/snippets/include/snippets/lowered/pass/iter_handler.hpp
- src/common/snippets/include/snippets/lowered/pass/split_loops.hpp
- src/common/snippets/include/snippets/lowered/specific_loop_iter_handlers.hpp
- src/common/snippets/include/snippets/pass/analyze_broadcastable_inputs.hpp
- src/common/snippets/include/snippets/runtime_configurator.hpp
- src/common/snippets/src/generator.cpp
- src/common/snippets/src/lowered/loop_info.cpp
- src/common/snippets/src/lowered/loop_manager.cpp
- src/common/snippets/src/lowered/pass/brgemm_blocking.cpp
- src/common/snippets/src/lowered/pass/compute_buffer_allocation_size.cpp
- src/common/snippets/src/lowered/pass/extract_loop_invariants.cpp
- src/common/snippets/src/lowered/pass/fuse_loops.cpp
- src/common/snippets/src/lowered/pass/init_loops.cpp
- src/common/snippets/src/lowered/pass/insert_specific_iterations.cpp
- src/common/snippets/src/lowered/pass/iter_handler.cpp
- src/common/snippets/src/lowered/pass/optimize_loop_single_evaluation.cpp
- src/common/snippets/src/lowered/pass/split_loops.cpp
- src/common/snippets/src/lowered/pass/validate_expanded_loops.cpp
- src/common/snippets/src/lowered/specific_loop_iter_handlers.cpp
- src/common/snippets/src/runtime_configurator.cpp
- src/common/snippets/tests/src/lowered/pass/extracted_loop_invariants.cpp
- src/common/snippets/tests/src/lowered/pass/loop.cpp
- src/plugins/intel_cpu/src/emitters/snippets/cpu_runtime_configurator.cpp
- src/plugins/intel_cpu/src/emitters/snippets/cpu_runtime_configurator.hpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.cpp
- *Introduced the class `InnerSplittedUnifiedLoopInfo` which describes inner splitted Loop after `SplitLoops`. Work amount of thus Loop is equal to increment of outer splitted loop. Removed the attribute `is_work_amount_const` from `LoopInfo`*
- *Enabled `SplitLoops` optimization for dynamic loops/*
- *Fixed finalization offset calculation for dynamic case*
- *Fixed `increment = 1` for dynamic innermost Loops with only Eltwise ops inside - now all dynamic `Last` Loop iterations has `increment = work_amount` (`evaluate_once = true`) by default. If there is innermost Loop with only Eltiwse ops, the pass `SetLoopIncrementOne` will be registered in last iteration handler by default*
- *Fixed LoopManager cloning: now all LoopInfo are cloned recursively and fully - with UnifiedLoopInfo in …
> [Snippets] Added SplitLoops support for dynamic loops

- src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/softmax_kernel.hpp
- src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
- *Reuse Q*K buffer to optimize SDPA first inference latency 
- *Unroll softmax to avoid data dependency*
- *...*
- *[150094](https://jira.devtools.intel.com/browse/CVS-150094)*
> [CPU] Reuse Q*K buffer to optimize SDPA first inference latency

- src/common/snippets/include/snippets/lowered/pass/pass.hpp
- src/common/snippets/include/snippets/utils/utils.hpp
- src/common/snippets/src/lowered/expression.cpp
- src/common/snippets/src/lowered/pass/brgemm_blocking.cpp
- src/common/snippets/src/lowered/pass/iter_handler.cpp
- src/common/snippets/src/lowered/pass/propagate_subtensors.cpp
- src/common/snippets/src/pass/mha_tokenization.cpp
- src/common/snippets/src/utils/utils.cpp
- src/common/snippets/tests/include/utils/broadcast_dim_merge.hpp
- src/common/snippets/tests/src/utils/broadcast_merge_dim.cpp
- src/plugins/intel_cpu/src/node.h
- src/plugins/intel_cpu/src/nodes/subgraph.cpp
- src/plugins/intel_cpu/src/nodes/subgraph.h
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- *The PR enables dynamic FP32 MHA tokenization on x64 platforms :tada:*
- *`std::vector.resize()` which was used for buffer scratchpad allocation is very expensive operation due to default constructor of elements. This PR replace `std::vector.resize()` with CPU Node Scratchpad memory which can be shared between nodes. Also since each thread must have the own scratchpad memory, we allocated `size * threads_max` - however, in execution thread count can be less (depends on parallel work amount). Now we allocate only `size * n_threads` where `nthreads` is real count of working threads.*
- *Fixed dimension K validation in `BrgemmBlocking` pass: one of inputs can have dynamic value of this dimension*
- *Fixed `utils::broadcast_merge_dim()` and supported broadcasting of integer values in …
> [Snippets][CPU] Enabled dynamic MHA FP32 tokenization on x64

- .github/workflows/job_build_linux.yml
- GPU tests are only enabled for U20. Checking out the latest oneDNN via https://github.com/openvinotoolkit/openvino/blob/0b8eb87e0efa9030be47d661fe94b3c8beb655fd/.github/workflows/job_build_linux.yml#L71 breaks the build on U22: [like this one](https://github.com/openvinotoolkit/openvino/actions/runs/10481070002/job/29030046664) and prevents other nightly tests from executing.
- This PR limits the checkout of the latest oneDNN to U20 only. This will unblock the nightly tests that run on U22 for now.
- Later, it might be better to separate the builds for GPU/other test jobs.
- *149805*
> [CI] [GHA] Do not checkout latest oneDNN on U22 in nightly

- src/plugins/intel_npu/src/backend/src/zero_remote_tensor.cpp
Commit ad4eb09 introduced dynamic loading of ze_loader so that it is loaded only when really needed.
Recent changes in `ZeroRemoteTensor` caused NPU plugin binary to import from ze_loader directly.
This commit should fix that and the NPU binary should have no longer dependency on ze_loader.
- None
> [NPU] Fix ze_loader dependency

- docs/dev/build.md
- docs/dev/build_riscv64.md
- *add `build_riscv64.md` file giving instructions on how to build OV on RISC-V devices*
- *N/A*
> [DOCS] [GSoC] add docs about how to build OV on RISC-V devices

- tools/mo/requirements_caffe.txt
- tools/mo/requirements_kaldi.txt
- tools/mo/requirements_mxnet.txt
- tools/mo/requirements_onnx.txt
- tools/mo/requirements_tf.txt
- tools/mo/requirements_tf2.txt
- `numpy==1.27` is the first version to support Python 3.12
- kaldi, mxnet and caffee will most likely fail with Python 3.12, TBD how to handle it
- cc @culhatsker 
- CVS-150017
> Allow `numpy==1.26` in MO for Python 3.12 enablement

- src/plugins/intel_gpu/src/plugin/transformations/dynamic_quantize_fully_connected.cpp
- src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_fc_horizontal_fusion.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/matmul_weights_decompression.cpp
- When FC output type is undefined, propagate the original input type
- Otherwise, dynamic_quantized type is propagated
- 149663
> [GPU] propagate fc output type for dynamic quantization case

- src/common/snippets/src/pass/mha_tokenization.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.cpp
- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.hpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp
- src/tests/functional/plugin/shared/include/snippets/mha.hpp
- src/tests/functional/plugin/shared/src/snippets/mha.cpp
- src/tests/ov_helpers/ov_snippets_models/include/subgraph_mha.hpp
- src/tests/ov_helpers/ov_snippets_models/src/subgraph_mha.cpp
- *If Loop emitters need aux GPR and have empty `aux_gpr_pool`, now we take any (unused by this emitter) GPR, push on stack before using and pop it from stack explicitly  after using*
- *N/A*
> [Snippets] Fixed aux GPR using in Loop emitters

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/fetch_weights.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/int4_utils.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_weights_int4.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/reorder/reorder_weights_int4.cpp
- Optimize fc_bf_tiled kernel for large K + small N case by setting K_TILE_SIZE 4
- Perf gain on MTL (U7 155H +  32GB RAM + driver 31.0.101.5333)
(No regression and on par on llama3 INT4 default and phi-3 mini INT4 default)
- 149212
> [GPU] Optimize fc_bf_tiled kernel for large K + small N case

- scripts/setupvars/setupvars.sh
Both 'cd' and 'pwd -P' print the directory name
Installation directory should be printed only once
> [INSTALL] Fix setupvars.sh corrupted installation directory

- docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
- docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst
- *item1*
- *...*
- *ticket-id*
> [DOCS] Port API ref link

- src/bindings/python/src/pyopenvino/core/remote_tensor.cpp
- src/bindings/python/src/pyopenvino/core/tensor.cpp
- src/bindings/python/tests/test_runtime/test_remote_api.py
- src/core/dev_api/openvino/runtime/itensor.hpp
- src/core/src/runtime/itensor.cpp
- src/inference/dev_api/openvino/runtime/iremote_tensor.hpp
- src/inference/include/openvino/runtime/remote_tensor.hpp
- src/inference/src/cpp/remote_tensor.cpp
- src/inference/src/dev/make_tensor.cpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/remote_context.hpp
- src/plugins/intel_gpu/include/intel_gpu/plugin/remote_tensor.hpp
- src/plugins/intel_gpu/include/intel_gpu/primitives/data.hpp
- src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
- src/plugins/intel_gpu/src/plugin/common_utils.cpp
- src/plugins/intel_gpu/src/plugin/remote_tensor.cpp
- src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.hpp
- src/plugins/intel_gpu/tests/functional/CMakeLists.txt
- src/plugins/intel_gpu/tests/functional/remote_tensor_tests/gpu_remote_tensor_tests.cpp
- src/plugins/intel_gpu/tests/unit/module_tests/usm_memory_test.cpp
The idea of these changes is to allow more flexible interaction between remote tensors and host tensors, enabling the implementation of features like swap_blocks in vLLM
- Made `ITensor::copy_to()` function virtual to allow proper underlying implementation call of `copy_to()` for ov::Tensor
- Added `copy_to(const std::shared_ptr<ov::ITensor>& dst)` and `copy_from(const std::shared_ptr<const ov::ITensor>& src)` functions to `IRemoteTensor` class, and pure virtual functions `copy_to(const std::shared_ptr<ov::ITensor>& dst, size_t src_offset, size_t dst_offset, ov::Shape roi_shape)` and `copy_from(const std::shared_ptr<const ov::ITensor>& src, size_t src_offset, size_t dst_offset, ov::Shape roi_shape)`, which are supposed to be defined in the RemoteTensor implementation itself
- Allowed …
> [GPU] Extend RemoteTensor API

- cmake/features.cmake
- cmake/toolchains/riscv64-071-thead-gnu.toolchain.cmake
- cmake/toolchains/riscv64-100-thead-gnu.toolchain.cmake
- docs/dev/build_riscv64.md
- src/plugins/intel_cpu/src/nodes/executors/shl/shl_fullyconnected.cpp
- src/plugins/intel_cpu/src/nodes/executors/shl/shl_fullyconnected.hpp
- *Added parallelism support for FC*
- *Enabled OpenMP on rv64 by default*
- *PR to oneDNN: https://github.com/openvinotoolkit/oneDNN/pull/260*
- *N/A *
> [RISCV64] Added parallelism support for FC

- tests/layer_tests/tensorflow_tests/test_tf_SparseTensorDenseAdd.py
**Details:** Switch on SparseTensorDenseAdd test on GPU. It was fixed since downgrading transformation for ScatterNDUpdate was merged https://github.com/openvinotoolkit/openvino/pull/26113
> [TF FE] Switch on SparseTensorDenseAdd test on GPU

- docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/quantized-models.rst
- docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/plugin-api-references.rst
- src/inference/dev_api/openvino/runtime/exec_model_info.hpp
Port: https://github.com/openvinotoolkit/openvino/pull/26129
* Removed unused toctree.
* Added explanation of Microseconds (JIRA: 149717)
> [DOCS] Fixes in Plugin API articles for 24.3

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp
Recently fixed FC bad groups size bug PR(https://github.com/openvinotoolkit/openvino/pull/26145) has the regression in qwen.
need_reorder function is used both decompression_scale and zero_point, but only consider scale NOT ZP.
- *150515*
> [GPU] Fix qwen run failure regression.

- docs/articles_en/get-started/install-openvino/install-openvino-conda.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/26225
> [DOCS] Reorganize conda forge installation article for 24.3

- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- *Disabled Quantized MHA tokenization on AVX2_VNNI_2 since it's not fully supported yet*
- *150510*
> [Snippets][CPU] Disabled Quantized MHA tokenization on AVX2_VNNI_2

- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
- src/inference/include/openvino/runtime/intel_npu/properties.hpp
- src/plugins/intel_npu/README.md
- src/plugins/intel_npu/src/al/include/npu_private_properties.hpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- publishing NPU_TILES (RW) property to enable setting the number of npu tiles to compile the model for.
- publishing NPU_MAX_TILES (RW) property to set (in case of offline compilation) or get (from current device) the maximum number of tiles the hardware we compile for supports.
- [*ticket-id*](https://jira.devtools.intel.com/browse/CVS-147058)
> [intel-npu] Publishing properties NPU_TILES (RW) and NPU_MAX_TILES

- src/plugins/intel_npu/src/plugin/npuw/partitioning/online/snapshot.cpp
- This PR fixes minor coverity issue in NPUW component: switches usage of copy to reference
- *ticket-id*
> Switched to use of reference to fix minor coverity issue

- src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_emitter.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_utils.cpp
- src/plugins/intel_cpu/src/transformations/snippets/x64/pass/brgemm_to_brgemm_cpu.hpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- *Added  Quantized MHA tokenization support on `avx2_vnni_2` platforms. `i8|i8` Brgemms don't need to have compensations on archs with this ISA*
- *PR to oneDNN: https://github.com/openvinotoolkit/oneDNN/pull/262*
- *150531*
> [Snippets][CPU] Added avx2_vnni_2 support for Quantized MHA

- src/bindings/python/src/pyopenvino/core/tensor.cpp
- src/bindings/python/src/pyopenvino/utils/utils.cpp
- src/bindings/python/src/pyopenvino/utils/utils.hpp
- src/bindings/python/tests/test_graph/test_gather.py
- src/bindings/python/tests/test_runtime/test_tensor.py
- src/bindings/python/tests/test_runtime/test_tensor_string.py
- if `shared_memory=True` and for other ctors which create Tensor with `shared_memory` added ability to keep host memory.
- if `shared_memory=False` still creates a copy and doesn't tie arrays lifetime to Tensor
- implemented `custom_keep_alive` (custom calling policy) which adds such ability 
- CVS-121493
> [PyOV] make Tensor responsible for keeping numpy memory

- src/frontends/pytorch/src/op/scaled_dot_product_attention.cpp
- *Fail gracefully if GQA is used for SDPA*
- *ticket-id*
> [PT FE] Fail gracefully if GQA is used for SDPA

- src/plugins/intel_gpu/src/plugin/plugin.cpp
update properties list that affect the compilation process of GPU.
- Append property `ov::hint::performance_mode` 
- Append property `ov::hint::dynamic_quantization_group_size`
- 150566
> [GPU Plugin] Fix the same cache hashID generated with different property setting

- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
- src/inference/include/openvino/runtime/intel_npu/properties.hpp
- src/plugins/intel_npu/README.md
- src/plugins/intel_npu/src/al/include/intel_npu/al/config/runtime.hpp
- src/plugins/intel_npu/src/al/src/config/runtime.cpp
- src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- src/plugins/intel_npu/tests/functional/behavior/ov_plugin/internal_properties_tests.cpp
- Adding new intel-npu plugin specific property to optionally bypass driver caching of compiled models (on/off, default:off)
- piggybacking a quickfix for private properties tests broken by PR #26161 
- *EISW-135607*
> [intel-npu] Adding property to optionally bypass UMD caching  (default: disabled)

- src/plugins/intel_cpu/src/nodes/batch_to_space.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/batch_to_space.cpp
size_t underflow might happen for the second dimension as well, for example when layout is ndhwc.
New test cases extended for `ndhwc` layout as well
- 14877
> [CPU] Fix BatchToSpace size_t underflow for the second dimension

- cmake/templates/OpenVINOConfig.cmake.in
- Currently, threading library like TBB is provided by openvino::runtime itself. It does not work well when multiple find_package(OpenVINO) are used within the project and with different `COMPONENTS`
- E.g. here https://github.com/openvinotoolkit/openvino.genai/pull/794 we have to add Threading component even for cases, when it's not really used, because find_package within nested subdirectory populates properties of openvino::runtime which is found in internal directory.
- Example of usage https://github.com/openvinotoolkit/openvino_tokenizers/pull/236
> Expose explicit openvino::threading target for parallel.hpp backend

- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp
- src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp
- This PR fixes incorrect default buffers sizes configuration for static model in sdpa_opt kernel
- [CVS-150773](https://jira.devtools.intel.com/browse/CVS-150773)
> [GPU] Fix default internal buffers sizes for SDPA

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/permute_tile_8x8_4x4.cl
- Fix out-of-bound access from permute kernel
- It happened because the kernel loaded with vload even at the boundary
- 150360
> [GPU] out-of-bound access fix for permute_tile_8x8_4x4

- src/plugins/intel_npu/src/plugin/CMakeLists.txt
- Use OpenVINO-provided flags to enable AVX2 for NPUW
- 136004
> [NPUW] Use OpenVINO-provided flags to enable AVX2

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- *Do not set shape_changed to true when shape is not changed.*
- *Fix output layout does not have updated data_padding which is calculated by calc_output_layouts in update_shape*
- *149773*
> [GPU] Fix the issue missing data padding info in update_shape

- src/common/transformations/include/transformations/low_precision/mark_dequantization_subgraph.hpp
- src/common/transformations/src/transformations/low_precision/mark_dequantization_subgraph.cpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- The PR restores MarkDequantizationSubgraph transformation behavior to the state before https://github.com/openvinotoolkit/openvino/pull/25783. This is required to avoid compressed zero-points constant folding during model conversion. 
- *[CVS-150686](https://jira.devtools.intel.com/browse/CVS-150686)*
> [Common] MarkDequantizationSubgraph: avoid modification of RT Info for fold_multiply_const=true option

- src/bindings/python/src/openvino/frontend/jax/utils.py
- src/frontends/jax/src/op/concatenate.cpp
- src/frontends/jax/src/op/integer_pow.cpp
- src/frontends/jax/src/op/reduce.cpp
- src/frontends/jax/src/op_table.cpp
- src/frontends/jax/src/utils.cpp
- src/frontends/jax/src/utils.hpp
- tests/layer_tests/jax_tests/test_concatenate.py
- tests/layer_tests/jax_tests/test_integer_pow.py
- tests/layer_tests/jax_tests/test_reduce.py
**Details:** This PR finalizes and allows to infer JAX ViT model
> [JAX FE] Support concatenate, integer_pow, reduce ops

- src/plugins/intel_gpu/src/kernel_selector/kernels/softmax/softmax_kernel_base.cpp
- src/plugins/intel_gpu/tests/unit/fusions/softmax_fusion_test.cpp
- *Significantly speed up LogSoftmax operation*
- *[148550](https://jira.devtools.intel.com/browse/CVS-148550)*
> [GPU] Enable activation fusing for softmax_gpu_bf kernel

- src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp
- src/plugins/intel_gpu/src/graph/include/paged_attention_inst.h
- src/plugins/intel_gpu/src/graph/paged_attention.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_kv_cache_update_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_update_kernel_ref.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_update_kernel_ref.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp
- Add prefix support for PagedAttention operation via existing pa_sdpa_opt kernel by processing subsequence's tokens in sequential mode, one by one for
- Moved responsibility for intermediate buffers reallocation from the sdpa_opt kernel to kv_cache_update kernel (they both use the same data, but now one of these buffers can be reused by the pa_sdpa_opt kernel, so everything was moved to one place)
> [GPU] Add prefix support for PagedAttention operation

- src/plugins/intel_npu/src/al/include/intel_npu/al/icompiler.hpp
- src/plugins/intel_npu/src/backend/include/zero_backend.hpp
- src/plugins/intel_npu/src/backend/include/zero_init.hpp
- src/plugins/intel_npu/src/backend/include/zero_types.hpp
- src/plugins/intel_npu/src/backend/src/zero_backend.cpp
- src/plugins/intel_npu/src/backend/src/zero_executor.cpp
- src/plugins/intel_npu/src/backend/src/zero_init.cpp
- src/plugins/intel_npu/src/compiler/CMakeLists.txt
- src/plugins/intel_npu/src/compiler/include/driver_compiler_adapter.hpp
- src/plugins/intel_npu/src/compiler/include/zero_compiler_in_driver.hpp
- src/plugins/intel_npu/src/compiler/src/driver_compiler_adapter.cpp
- src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- src/plugins/intel_npu/src/plugin/include/backends.hpp
- src/plugins/intel_npu/src/plugin/include/compiled_model.hpp
- src/plugins/intel_npu/src/plugin/include/compiler.hpp
- src/plugins/intel_npu/src/plugin/src/backends.cpp
- src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- src/plugins/intel_npu/src/plugin/src/compiler.cpp
- src/plugins/intel_npu/src/plugin/src/plugin.cpp
- share the same L0 context from backend to compiler
- and perform zeDestroy(context) in backend only 
- *ticket-id*
> Zero backend and compiler adapter to share single L0 context

- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
This patch adds Validate pass call after IncreasePositionIdsPrecision to ensure proper data type propagation
With this change the accuracy of llama-3-8b INT8 (and other LLMs probably) can be restored to expected level
Before:
```
| Tasks  |Version|Filter|n-shot|    Metric     |   |Value |   |Stderr|
|--------|------:|------|-----:|---------------|---|-----:|---|------|
|wikitext|      2|none  |     0|bits_per_byte  |↓  |0.6030|±  |N/A   |
|        |       |none  |     0|byte_perplexity|↓  |1.5189|±  |N/A   |
|        |       |none  |     0|word_perplexity|↓  |9.3472|±  |N/A   |
```
After:
```
| Tasks  |Version|Filter|n-shot|    Metric     |   |Value |   |Stderr|
|--------|------:|------|-----:|---------------|---|-----:|---|------|
|wikitext|      2|none  |     0|bits_per_byte  |↓ …
```
> [GPU] Add Validate pass call after IncreasePositionIdsPrecision to ensure proper data type propagation

- src/plugins/intel_gpu/src/graph/compilation_context.cpp
- Use recursive_mutex instead of mutex in compilation context. Because deadlock happens in context compilation(push_tash() -> remove_keys() in single thread) when CPU_PINNING=ON
- 150220
> [GPU] Use recursive_mutex instead of mutex in compilation context

- src/plugins/intel_gpu/include/intel_gpu/primitives/resample.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/resample.cpp
- src/plugins/intel_gpu/src/plugin/ops/interpolate.cpp
- Fix interpolate 11 op case when sizes or scales are not constant. The additional argument shadowed TensorAccessor underlying tensor on port 2 and therefore shape inference was reading wrong values
- 146022
> [GPU] Fix Interpolate 11 axes reading

- thirdparty/onnx/CMakeLists.txt
- Fixed ONNX FE debug build
- ONNX proto is base library and must be compiled with newer standard, otherwise onnx and onnx_proto are compiled with different C++ standard.
- CVS-149644
> [CVS-149644] Fixed ONNX FE debug build

- src/plugins/intel_cpu/tools/aggregate-average-counters/README.md
- src/plugins/intel_cpu/tools/aggregate-average-counters/aggregate-average-counters.py
- src/plugins/intel_cpu/tools/aggregate-average-counters/requirements.txt
Example output:
| Node type                            |   Count |   Sum (ms) |      % |
|:-------------------------------------|--------:|-----------:|-------:|
| FullyConnected                       |     197 |     77.812 |  91.77 |
| ScaledDotProductAttentionWithKVCache |      28 |      3.7   |   4.36 |
| RoPE                                 |      56 |      0.687 |   0.81 |
| Reorder                              |     161 |      0.473 |   0.56 |
| Multiply                             |      31 |      0.443 |   0.52 |
| Transpose                            |      56 |      0.431 |   0.51 |
| PowerStatic                          |     115 |      0.313 |   0.37 |
| Add                                  |      59 |      0.227 |   0.27 |
| ReduceMean                           |      57 | …
> [CPU] Add script for benchmark average counters aggregation

- src/plugins/intel_cpu/src/graph.cpp
- src/plugins/intel_cpu/src/graph.h
- src/plugins/intel_cpu/src/node.cpp
- src/plugins/intel_cpu/src/node.h
- Execute node with exception handling in all scenarios
- Move all the profiling macros under ExecuteNode
- Get numaId outside the main loop
- Few minor changes
> [CPU][REFACTORING] Align inference pipeline for all scenarios

- cmake/developer_package/features.cmake
- Gcc 8.x has multiple bug for LTO
- Let's have 9.x and higher as required for LTO
- CVS-150950
> Disabled LTO for gcc older than 9.0

- src/frontends/tensorflow/src/op_table.cpp
- src/frontends/tensorflow_common/include/common_op_table.hpp
- src/frontends/tensorflow_common/src/op/binary_op.cpp
- tests/layer_tests/tensorflow_tests/test_tf_Sub.py
- Support complex tensors for Sub operation + tests
- [None](https://github.com/openvinotoolkit/openvino/issues/22948)
> [TF FE]: Support complex tensors for Sub operation

- src/plugins/intel_gpu/src/runtime/shape_predictor.cpp
- src/plugins/intel_gpu/tests/unit/module_tests/shape_predictor_test.cpp
- This patch fixes an issue where requested buffer meets the requirements of the maximum buffer allocation size, but applying preallocation causes the limits to be reached, resulting in an OpenCL error
> [GPU] Do not preallocate memory if desired size reaches the maximum supported buffer size

- src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
- *item1*
- *...*
- *ticket-id*
> [PT FE] Set target name as PythonOp name

- tests/constraints.txt
- tests/layer_tests/jax_tests/jax_layer_test_class.py
**Details:** It is required for validation of Python 3.12 support.
**Tickets:** 150860
> [JAX FE] Update JAX version to latest one for testing

- src/common/transformations/src/transformations/sdpa_to_paged_attention/state_management_pattern.cpp
[TRANSFORMATIONS] Fix Alibi slopes handling for Jais-13b model
The Jais-13b model uses different approach for forming the attention mask using negative values of Alibi slopes for positional embedding. The current implementation of extracting the Alibi slopes and inserting it to PA results into model producing incorrect output.
Detect the Jais-13b-like pattern with the negative Alibi constant and multiply it by -1 to use the "raw" (positive) Alibi values before inserting into PA.
- CVS-142320
> [TRANSFORMATIONS] Fix Alibi slopes handling for Jais-13b model

- cmake/developer_package/features.cmake
- Gcc 8.x has multiple bug for LTO
- Let's have 9.x and higher as required for LTO
- CVS-150950
- *item1*
- *...*
- *ticket-id*
> Disabled LTO for gcc older than 9.0 (#26330)

- src/bindings/js/node/tests/unit/basic.test.js
- src/bindings/js/node/tests/unit/compiled_model.test.js
- src/bindings/js/node/tests/unit/core.test.js
- src/bindings/js/node/tests/unit/infer_request.test.js
- src/bindings/js/node/tests/unit/model.test.js
- src/bindings/js/node/tests/unit/pre_post_processor.test.js
- src/bindings/js/node/tests/unit/read_model.test.js
- src/bindings/js/node/tests/unit/tensor.test.js
- Avoid dependencies between tests and unexpected behaviours
- Add `beforeEach`
- [CVS-146340](https://jira.devtools.intel.com/browse/CVS-146340)
> [OVJS] Avoid of usage global variables in tests

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/scatter_elements_update_ref.cl
- Fix ocl build confliction of MAX() in scatter elements update ref kernel. It causes ocl build error when other kernel which uses MAX() macro is generated together in same batch. Scatter elements update ref kernel used #define MAX again.
- 151113
> [GPU] Fix ocl build confliction of MAX() in scatter elements update ref kernel

- src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.cpp
- src/plugins/intel_gpu/tests/unit/transformations/transpose_matmul_fusion_test.cpp
- Avoid unwanted MatMul->Gemm conversion for static shapes as MatMul handler can produce more performance subgraph
- Fixes perf regression for stable diffusion unet on non-xmx platforms
- PR to master: https://github.com/openvinotoolkit/openvino/pull/26429
- *CVS-151481*
> [GPU] Disable transpose fusion in case of no transpose found on both branches

- src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/properties.cpp
- src/tests/functional/plugin/shared/src/behavior/ov_plugin/properties_tests.cpp
- *DEVICE_ID is optional for SW plugin and mandatory for HW plugin*
- *N/A*
> [conformance] Mark DEVICE_ID mandatory for HW plugin

- src/plugins/intel_cpu/src/transformations/cpu_opset/x64/op/qkv_proj.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/x64/pass/qkv_proj_fusion.cpp
- prevent QKVProjFusion from mistakenly fusing patterns with integer input (happens in bert-INT8 models with smooth-quant)
- *CVS-151213*
> [CPU] fix QKVProjection fake-matching for accuracy with bert models

- src/common/low_precision_transformations/src/mat_mul.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/mat_mul_with_constant_transformation.cpp
- src/tests/ov_helpers/ov_lpt_models/include/ov_lpt_models/common/dequantization_operations.hpp
- src/tests/ov_helpers/ov_lpt_models/src/common/builders.cpp
- src/tests/ov_helpers/ov_lpt_models/src/common/dequantization_operations.cpp
This PR handles Matmul dequantization subgraphs with convert on scales.
In general, LPT don't expect Convert on dequantization scale: the convert is usually folded at the previous transformation pipeline steps. However, such subgraphs may arise on Matmul weights (in CPU plugin) since decompression handling logic keeps these subgraphs unchanged. Since decompression handling logic concerns only MatMuls, the changes in MatMul LPT is enough.
- *CVS-151589*
> [LPT] Handle scale with convert in MatMulTransformation

- src/common/low_precision_transformations/src/add.cpp
- src/common/low_precision_transformations/src/concat.cpp
- src/common/low_precision_transformations/src/multiply.cpp
- src/common/low_precision_transformations/src/multiply_partial.cpp
- src/common/low_precision_transformations/src/mvn.cpp
- src/common/low_precision_transformations/src/network_helper.cpp
- src/common/low_precision_transformations/src/reduce_base_transformation.cpp
- src/common/low_precision_transformations/tests/separate_in_standalone_branch_transformation.cpp
- *Added `normalizeDequantization` in `separateInStandaloneBranch`: it is needed since `separateInStandaloneBranch` works correctly only with normalized dequantization*
- *Handle all inputs (not only 0's as before) in `separateInStandaloneBranch`*
- *Removed `normalizeDequantization` in transformations since this logic is placed inside `separateInStandaloneBranch` now*
- *CVS-150001*
> [LPT] separateInStandaloneBranch fix

- src/plugins/intel_gpu/src/plugin/transformations/increase_position_ids_precision.cpp
- src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.cpp
- src/plugins/intel_gpu/tests/unit/transformations/increase_position_ids_precision_test.cpp
- src/plugins/intel_gpu/tests/unit/transformations/transpose_matmul_fusion_test.cpp
- Fix lack of support for 3D (and smaller) shapes in TransposeFusion pass
- Update IncreasePositionIdsPrecision to support both MatMul and Gemm operations
- [CVS-146889](https://jira.devtools.intel.com/browse/CVS-146889)
> [GPU] Fix lack of support for 3D (and smaller) shapes in TransposeFusion pass

- src/common/low_precision_transformations/src/markup_precisions.cpp
When GatherTransformation was implemented, the necessary handling in LPT Markup transformations was skipped. This PR adds gather layers handling in LPT Markup transformations
- *CVS-151590*
> [LPT] Handle Gather in markup transformation

- src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/handle_reshape.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
- src/plugins/intel_gpu/src/graph/include/layout_optimizer.h
- src/plugins/intel_gpu/src/graph/include/paged_attention_inst.h
- src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- src/plugins/intel_gpu/src/graph/kv_cache.cpp
- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/graph/paged_attention.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/program.cpp
- src/plugins/intel_gpu/src/graph/slice.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/gru_sequence.cpp
- src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp
- src/plugins/intel_gpu/tests/unit/fusions/deconvolution_fusion_test.cpp
- src/plugins/intel_gpu/tests/unit/fusions/gemm_fusion_test.cpp
- src/plugins/intel_gpu/tests/unit/module_tests/graph_manipulation_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- src/plugins/intel_gpu/tests/unit/passes/select_preferred_formats_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/pooling_gpu_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/reduce_gpu_test.cpp
- Added explicit layout recalc after some graph modifications to avoid full invalidation of layouts later on random attempt to call `get_output_layout()`
- Remove i64 data type handling in add_required_reorder pass as ConvertPrecision is supposed to convert everything into i32.
- Move shape info tensor alloc to `update_shape_info_tensor` call to avoid allocation in case if the buffer is not needed for selected impl
- Fixed impl forcing in some unit tests  + other minor test changes
> [GPU] Update gpu passes to keep valid layouts more often

- src/inference/src/dev/threading/parallel_custom_arena.cpp
- src/inference/src/dev/threading/parallel_custom_arena.hpp
- *`binding_observer` is defined but not implemented when USE_TBBBIND_2_5 is not defined. So add `USE_TBBBIND_2_5` before the definition of `binding_observer`*
- *151706*
> Add USE_TBBBIND_2_5 before the definition of binding_observer

- .github/actions/openvino_provider/action.yml
To call the action via a single step "- uses: openvinotoolkit/openvino/.github/actions/openvino_provider@master" w/o extra checkout
> [GHA] Enable more convenient OV provider call from other repos

- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- *To reduce overheads of ShapeInference and CodeGeneration of dynamic Subgraphs, CPU node Subgraph uses Runtime Cache of the plugin. If Runtime Cache capacity is zero, dynamic subgraphs should not be tokenized - it will lead to performance degradations. This PR disables dynamic MHA tokenization if `config.rtCacheCapacity == 0`*
- *150951*
> [Snippets][CPU] Disabled dynamic MHA tokenization if rtCache is not used

- src/plugins/intel_npu/tools/single-image-test/main.cpp
- `ii.get_index` can return same index for different inputs:
```
(gdb) p inputInfo
$1 = std::vector of length 2, capacity 2 = {{
m_node = std::shared_ptr<ov::Node> (use count 3, weak count 2) = {get() = 0x555555872860}, m_index = 0}, {
m_node = std::shared_ptr<ov::Node> (use count 3, weak count 2) = {get() = 0x555555873fa0}, m_index = 0}}
```
- This may result in the collision of names.
- When different inputs are referred by the same name, single image test will populate only one such input.
- Append `id` to the name to assure its uniqueness.
- E-137973
> Append input index to input names

- src/common/low_precision_transformations/src/network_helper.cpp
- src/common/low_precision_transformations/tests/normalize_dequantization_transformation.cpp
- src/tests/ov_helpers/ov_lpt_models/include/ov_lpt_models/normalize_dequantization.hpp
- src/tests/ov_helpers/ov_lpt_models/src/normalize_dequantization.cpp
- *Correct NormalizeDequantization behavior in order to avoid eltwise inputs reshuffle in case if both inputs are constant*
- *Added converts on constant path support in NormalizeDequantization*
- *CVS-151869*
- *CVS-79740*
> [LPT] NormalizeDequantization correction

- src/plugins/intel_cpu/src/transformations/cpu_opset/arm/pass/convert_reduce_multi_axis.cpp
- The fix of https://github.com/openvinotoolkit/nncf/issues/2943 
- The error `Default output not supported` could be raised in `ConvertReduceMultiAxisBase` transformation because output of Reduce input node was not specified. It works well if the node has default output, but for some nodes (like `VariadicSplit`) it leads to the error.
- The fix is to explicitly specify needed output. 
- *ticket-id*
> [CPU][ARM] Fix output detection in `ConvertReduceMultiAxisBase` transformation

- .github/actions/openvino_provider/action.yml
For some cases (e.g. during tokenizers build via pip wheel) we need only wheel source argument, not the input for pip install
> [GHA] Add ov_wheel_source output for ov provider

- cmake/developer_package/plugins/plugins.cmake
OpenVino fails to compile if it's used as a subdirectory in CMakeLists.txt. For example, below scenario:
```
$ git clone https://github.com/openvinotoolkit/openvino --recursive
$ cat CMakeLists.txt
project(testing)
add_subdirectory(openvino)
$ mkdir build
$ cmake -B build -S .
$ make -C build openvino_runtime_obj
```
ends with compilation error:
```
core_impl.cpp:32:10: fatal error: ov_plugins.hpp: No such file or directory
32 | #include "ov_plugins.hpp"
|          ^~~~~~~~~~~~~~~~
```
because of incorrect include path.
openvino_runtime_obj target expects ov_plugins.hpp to be present in ${CMAKE_CURRENT_BINARY_DIR} (which is build/openvino/src/inference in this case), but ov_plugins.hpp is generated to ${CMAKE_BINARY_DIR}/src/inference (which is build/src/inference). To fix that, …
> Fix path to generated ov_plugins.hpp

- src/plugins/intel_cpu/src/cpu_types.cpp
- src/plugins/intel_cpu/src/cpu_types.h
- src/plugins/intel_cpu/src/graph.cpp
- src/plugins/intel_cpu/src/graph.h
- src/plugins/intel_cpu/src/node.cpp
- src/plugins/intel_cpu/src/node.h
- src/plugins/intel_cpu/src/nodes/composite.cpp
- src/plugins/intel_cpu/src/nodes/composite.h
- src/plugins/intel_cpu/src/nodes/executors/graph_emitter.hpp
- src/plugins/intel_cpu/src/nodes/input.cpp
- src/plugins/intel_cpu/src/nodes/input.h
- src/plugins/intel_cpu/src/nodes_factory.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/common/op/submodel.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/common/op/submodel.hpp
with the idea of wrapping up (grouping) parts of the model / graph
into a inner model / graph without any (almost) runtime overhead.
SubModel op and Compoisite node are expected to perform no extra logic
and to only execute an inner model / graph
- The naming "Composite node and SubModel operation" are discussable. A convenient option for the Composite node would be "SubGraph", but it is taken by snippets, which seems logical as well.
- the Composite node is not yet used by plugin
- single layer tests are to be added later. The problem is that currently it is impossible to use cpu plugin specific transformations and operations in scope of cpu func tests.
- 
- *ticket-id*
> [CPU] Introduce SubModel op and Composite node

- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
- Fixed bug in fc_tiled_opt kernel + eltwise fusion 
- Allow fc (fp precision) + eltwise fusion for dynamic case & unfuse if unsupported kernel is selected 
- CVS-151537
> [GPU] Fix fc_tiled kernel for eltwise fusion and allow fusion for dynamic shape 

- tools/mo/requirements_tf.txt
- tools/mo/requirements_tf2.txt
- Fixes MacOS CI on Python 3.8
- Full investigation in the ticket
- Related PR to OMZ: https://github.com/openvinotoolkit/open_model_zoo/pull/3974
- CVS-151865
> [PyOV] Exclude a specific `tensorflow` version which does not support Python 3.8 on MacOS

- .github/workflows/send_workflows_to_opentelemetry.yml
This will prevents the metrics workflow from begin run on openvinotoolkit/openvino forks.
> Limit metrics workflow to openvino repository only

- .github/workflows/ubuntu_20.yml
- Switch off GPU tests in GHA
- 152280
> [GHA] Switch off GPU tests in precommit, post-commit and nightly

- .github/workflows/android_arm64.yml
- .github/workflows/android_x64.yml
- .github/workflows/coverity.yml
- .github/workflows/job_build_linux.yml
- .github/workflows/job_build_windows.yml
- .github/workflows/job_tokenizers.yml
- .github/workflows/linux_arm64.yml
- .github/workflows/linux_conditional_compilation.yml
- .github/workflows/linux_sanitizers.yml
- .github/workflows/ubuntu_22.yml
- .github/workflows/windows_conditional_compilation.yml
To avoid manual updates where we can (in repos with the same branching systems as OV)
> [GHA] Dynamic refs for third-party OV-related repos

- src/bindings/python/src/pyopenvino/core/compiled_model.cpp
- src/bindings/python/tests/test_runtime/test_async_infer_request.py
- src/bindings/python/tests/test_runtime/test_compiled_model.py
- src/bindings/python/tests/test_runtime/test_sync_infer_request.py
- src/bindings/python/tests/utils/helpers.py
- add release_memory method and test for it
- move `generate_concat_compiled_model` and `generate_abs_compiled_model_with_data` to separate file
- CVS-152395
> [PyOV] Add release_memory to comp model

- docs/articles_en/documentation/legacy-features/install-dev-tools.rst
- docs/articles_en/documentation/openvino-security.rst
- docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst
- docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst
- docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst
- docs/articles_en/get-started/install-openvino/install-openvino-npm.rst
- docs/articles_en/get-started/install-openvino/install-openvino-pip.rst
- docs/articles_en/learn-openvino/openvino-samples/get-started-demos.rst
Removing references to internal resources of IoT Devkit found in OpenVINO documentation. This PR addresses the following JIRA ticket: 105801
> [DOCS] Removing IOT Devkit references

- src/plugins/intel_cpu/thirdparty/ACLConfig.cmake
- ACL should use OpenMP scheduler if OpenVINO is built with `THREADING=OMP` option
- *ticket-id*
> [ARM] Use OpenMP in ACL build if `THREADING=OMP`

- src/common/transformations/src/transformations/op_conversions/convert_ti_to_sequences.cpp
- src/common/transformations/tests/op_conversions/convert_ti_to_sequences_test.cpp
**Details:** In customer model, there is a sub-graph under ShapeOf that is equivalent to multiplication by one. It can be eliminated and make LSTMSequence fusion possible
**Ticket:** 149687
> [Transformations] Extend LSTMSequenceFusion transformation with multiply-by-one pattern

- .github/workflows/job_python_unit_tests.yml
- .github/workflows/windows_vs2019_release.yml
- tests/layer_tests/common/tflite_layer_test_class.py
- tests/layer_tests/common/utils/tflite_utils.py
- tests/layer_tests/tensorflow_lite_tests/test_tfl_ArgValue.py
- tests/layer_tests/tensorflow_lite_tests/test_tfl_Binary.py
- tests/layer_tests/tensorflow_lite_tests/test_tfl_BinaryWithActivation.py
- tests/layer_tests/tensorflow_lite_tests/test_tfl_Pool.py
- tests/layer_tests/tensorflow_lite_tests/test_tfl_Reduce.py
- tests/layer_tests/tensorflow_lite_tests/test_tfl_Resize.py
- tests/layer_tests/tensorflow_lite_tests/test_tfl_Unary.py
- Enabled parallel call
- Fixed tests to be compatible with pytest-xdist plugin (pass function name instead of reference)
- `os.path.dirname` caused saving model in `/out` directory instead of `/out/{temp_dir}` beacause it didn't have '/' char at the end and it treated `temp_dir` like a file
- [None](https://github.com/openvinotoolkit/openvino/issues/20920)
Without parallel execution
With parallel execution (8 cpu cores)
> [GHA] Enable parallel execution of TensorFlow Lite Layer python tests

- src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_ref.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- For fp model, some convolutions may not be compressed to fp16 depending on the transformation policy and those convolutions may have the fused node which is of fp16. Then convolution node input data type will be fp32 while output data type fp16. Convolution needs to support  this case.
- 147689
> [GPU] Support different input and output data type in convolution ref

- src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.cpp
- src/plugins/intel_gpu/tests/unit/transformations/horizontal_fc_fusion_test.cpp
- Target pattern: FCs to be fused by horizontal fusing pass and they have Add users which can be regarded as bias add. Here if we fuse the FCs as is, the fused pattern will be fused_fc -> VariadicSplit -> Add so the Adds cannot be fused to the FCs. 
- This PR sets such Add users as the FC's bias inputs so that the fused FC can handle them as fused bias. 
- CVS-151841
> [GPU] Fuse more eltwises for horizontally fused FC

- src/common/snippets/include/snippets/runtime_configurator.hpp
- src/common/snippets/src/lowered/pass/insert_specific_iterations.cpp
- src/common/snippets/src/runtime_configurator.cpp
- *Currently, `loops_to_split` in `MHAParallelWAOptimizer` are stored in unordered_map, so elements order is not determined. This sporadically leads to the situation when loop last iteration has work_amount more than main body's increment. This might lead to failures*
- *In this PR, 'loops_to_split' are stored in vector, so loop information updates are always called for expanded loop infos in determined order: FIRST_ITER->MAIN_BODY->LAST_ITER*
- *Also, the corresponding assert is added to `InsertSpecificIterations::get_decomposed_loop_work_amount` in order to throw an exception on early stage in case of incorrect configuration. This assert also allows to cover the changes by the existing tests (some of them fail if assert is added but the fix is not applied)*
- *N/A*
> [Snippets] Fix sporadic issue in MHAParallelWAOptimizer

- src/plugins/template/tests/functional/op_reference/mish.cpp
- Enabled whole tensor comparison.
- Fixed function template argument deduction.
- Code improvements.
- CVS-137185
> [Templ test] Mish: Enable whole Tensor comparison

- .github/workflows/job_python_unit_tests.yml
- install_build_dependencies.sh
- src/bindings/python/CMakeLists.txt
- tools/mo/unit_tests/mock_mo_frontend/mock_mo_python_api/CMakeLists.txt
- problem with tests was caused due-to old pybind11 version is installed ((2.11.1-2)). 
- CVS-152242
> [PyOV] return back testing of PyAPI tests for py3.12

- src/plugins/intel_cpu/tests/unit/CMakeLists.txt
- *Fixed "ov_cpu_unit_tests" linking with SHL for RISC-V devices*
- *Before the changes:*
```
[build] [100%] Linking CXX executable /openvino/bin/riscv64/Release/ov_cpu_unit_tests
[build] /Xuantie-900-gcc-linux-5.15.0-glibc-x86_64-V2.8.1/lib/gcc/riscv64-unknown-linux-gnu/10.4.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../CMakeFiles/openvino_intel_cpu_plugin_obj.dir/src/nodes/executors/shl/shl_eltwise.cpp.o:(.text._ZN2ov9intel_cpu18ShlStructureTraitsIP13csinn_sessionE10destructorES3_[_ZN2ov9intel_cpu18ShlStructureTraitsIP13csinn_sessionE10destructorES3_]+0x0): undefined reference to `csinn_free_session'
[build] /Xuantie-900-gcc-linux-5.15.0-glibc-x86_64-V2.8.1/lib/gcc/riscv64-unknown-linux-gnu/10.4.0/../../../../riscv64-unknown-linux-gnu/bin/ld: …
```
> [RISC-V][Tests] Fixed ov_cpu_unit_tests linking with SHL

- src/plugins/intel_gpu/src/graph/program_node.cpp
- src/plugins/intel_gpu/tests/functional/remote_tensor_tests/gpu_remote_tensor_tests.cpp
- We had an exception on attempt to set remote tensor if input had multiple GPU users and ShapeOf node with CPU impl. This patch adds special handling for shape_of node to avoid it's requirement for lockable inputs as it doesn't touch tensor.
- Note: Likely it will still fail for other CPU node types, so need to investigate that further.
> [GPU] Fix lockable requirement check for shape_of consumer

- src/bindings/python/src/pyopenvino/core/infer_request.cpp
- src/plugins/intel_gpu/src/graph/program_node.cpp
- src/plugins/intel_gpu/tests/functional/remote_tensor_tests/gpu_remote_tensor_tests.cpp
- Cherry pick https://github.com/openvinotoolkit/openvino/pull/26723 and https://github.com/openvinotoolkit/openvino/pull/26726
> Fix set_tensor with remote tensor in python

- src/plugins/intel_gpu/src/plugin/transformations/fc_convert_fusion.cpp
- *pass::FullyConnectedConvertFusion support symmetric quantized FC... This removes a bunch of type-converting Reorder nodes that follows FullyConnectedCompress node in QWen decoder layers.*
- *143169*
> [GPU] pass::FullyConnectedConvertFusion support symmetric quantized FC.

- src/bindings/python/src/pyopenvino/core/infer_request.cpp
- Add binding for set_tensor with RemoteTensorWrapper arg to have a way to set remote tensors in python API.
- This solution may be changes in the future, but currently it's impossible to set remote tensor from python and this patch enables it.
> [PyOV] Add set_tensor binding for RemoteTensor

- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device/remote-tensor-api-gpu-plugin.rst
Adding info on support for sharing of D3D11 surfaces in `Remote Tensor API of GPU Plugin`. Addressing JIRA Ticket: 120077
> [DOCS] D3D11 surface sharing support

- docs/articles_en/assets/snippets/ov_extensions.py
- *item1*
- *...*
- *ticket-id*
> [DOCS] change mo command

- tests/constraints.txt
- tests/model_hub_tests/pytorch/requirements.txt
- *item1*
- *...*
- *ticket-id*
> [TESTS] Fix issue with new version of easyocr

- src/plugins/intel_npu/src/al/include/intel_npu/al/icompiler.hpp
- src/plugins/intel_npu/src/backend/include/zero_types.hpp
- src/plugins/intel_npu/src/compiler/include/driver_compiler_adapter.hpp
- src/plugins/intel_npu/src/compiler/include/zero_compiler_in_driver.hpp
- src/plugins/intel_npu/src/compiler/src/driver_compiler_adapter.cpp
- src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- *Add support for new L0 API 1.7*
- *Change return type of `getCompiledNetwork` to new custom `CompiledNetwork` container*
- *[151912](https://jira.devtools.intel.com/browse/CVS-151912)*
> [`intel_npu`] [`releases/2024/4`] [`reduce memory consumption`] Avoid creating a blob copy while exporting a compiled model

- src/common/snippets/src/lowered/pass/extract_loop_invariants.cpp
- src/common/snippets/tests/src/lowered/pass/extracted_loop_invariants.cpp
- *Porting the fix https://github.com/openvinotoolkit/openvino/pull/26590 to the release branch*
- *N/A*
> [Snippets] Fixed the pass ExtractLoopInvariants

- tests/model_hub_tests/transformation_tests/models/hf-tiny-random-models-precommit
**Details:** Disable paged attention tests for tiny-random-GPTNeoForCausalLM
**Ticket:** CVS-153620
> [Transformation Tests] Disable paged attention tests for tiny-random-GPTNeoForCausalLM

- src/bindings/python/src/openvino/runtime/__init__.py
- src/bindings/python/src/pyopenvino/graph/node.cpp
- src/bindings/python/tests/test_graph/test_create_op.py
- src/bindings/python/tests/test_graph/test_ops_binary.py
- src/bindings/python/tests/test_runtime/test_model.py
- https://github.com/openvinotoolkit/openvino/pull/26613 caused backward incompatible changes, so decided to deprecate comparison overloads for comparison operations as the usage of them confuse users
- suppress deprecation warnings in tests
- added bindings for `get_instance_id()` to Node class 
- result of discussion [CVS-131039](https://jira.devtools.intel.com/browse/CVS-131039)
> [PyOV] Deprecate comparison for operations

- docs/dev/build_windows.md
Fixing broken reference to a guide for LLVM setup on WoA. This PR addresses the following JIRA ticket: 153631
> [DOCS] Fixing broken link to external resources

- docs/dev/build_windows.md
Porting: https://github.com/openvinotoolkit/openvino/pull/26831
> [DOCS] Fixing broken link to external resources for 24.4

- src/core/include/openvino/pass/manager.hpp
- Fix format and typo for ov::pass::Manager register_pass() function:
Original link for OV 24.5 nightly
https://docs.openvino.ai/nightly/api/c_cpp_api/classov_1_1pass_1_1_manager.html#_CPPv4I0_bDpEN2ov4pass7Manager13register_passENSt10shared_ptrI1TEEDpRR4Args
- Reference: https://github.com/openvinotoolkit/openvino/blob/77dfb1de59debe9c59cb45c44de520bb781db81c/src/plugins/template/backend/executable.cpp#L70
> [Docs]Fix OV pass manager API doc

- tests/model_hub_tests/transformation_tests/models/hf-tiny-random-models-precommit
This reverts commit 1ab0448b196ef8f0ef6a685ee6eb068eaa64813f which disabled the tests in the pre-commit
The fix has been merged to optimum-intel https://github.com/huggingface/optimum-intel/pull/917, so we can restore the test
- *CVS-153620*
> [Transformation Tests] Enable paged attention tests for tiny-random-GPTNeoForCausalLM

- tools/mo/requirements_kaldi.txt
**Details:** Work around conversion for stateful Kaldi models with Python>3.8. Now it fails for unknown reason on higher numpy versions. Since this is quite legacy stuff and will removed in 2025.0. we decided not to invest our time for proper resolution. So we proceed with easy-fix.
**Ticket:** 153367
> [Kaldi] Work around conversion for stateful Kaldi models with Python>3.8

- src/plugins/intel_cpu/src/nodes/eltwise.cpp
- *change Eltwise layout selection logic for x86 non-CNN ModelType, several llm models gain performance benefits from this change since additional reorder operators have been avoided, e.g. phi3 and bloomz*
- *details can be found in the [ticket discussion](https://jira.devtools.intel.com/browse/CVS-148780).)*
- *148780*
> [CPU] change Eltwise layout selection logic for x86 non-CNN ModelType

- src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/post_input_reorder.cpp
- To skip primitive if it has shapeof users only unless it should be executed to know the shapes such as non-zero.
- Currently such case is observed only for permute + shapeof in Qwen model. 
- CVS-146842
> [GPU] Skip primitive if it has only shapeof users

- src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
- src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_weights_int4.cl
- src/plugins/intel_gpu/src/kernel_selector/kernel_selector_common.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_base.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/reorder/reorder_weights_int4.cpp
- src/plugins/intel_gpu/src/kernel_selector/tensor_type.cpp
- src/plugins/intel_gpu/src/kernel_selector/tensor_type.h
- src/plugins/intel_gpu/src/runtime/format.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- Optimize fc_bf_tiled kernel for large N + small K case by setting TILE_OFM=4 w/ os_is_yx_osv64_isv2 weight format
- Perf gain on MTL (U7 155H + 32G RAM + driver 31.0.101.5522)
- 148076
> [GPU] Optimize fc_bf_tiled kernel for large N + small K case

- src/plugins/intel_npu/cmake/features.cmake
- src/plugins/intel_npu/src/CMakeLists.txt
- src/plugins/intel_npu/src/utils/src/CMakeLists.txt
- *zero utils depend on level-zero-ext, the target only open if we set ENABLE_ZEROAPI_BACKEND to ON now*
- "Add check of ENABLE_ZEROAPI_BACKEND and ENABLE_DRIVER_COMPILER_ADAPTER"
- *153228*
> [NPU] Only use zero utils when ENABLE_ZEROAPI_BACKEND be ON

- tools/benchmark_tool/openvino/tools/benchmark/main.py
- In the case reported in the ticket the config was given for a device `BATCH:GPU.1(128)`, which was also specified in the CLI as `-d BATCH:GPU.1(128)`
- The previous code first found `BATCH:GPU.1(128)` as an available device and assigned the config correctly, but afterwards it also found `BATCH` device and overwrote the `device_config` variable with incorrect value
- Prioritizing the device given in the CLI solves the issue
- CVS-130165
> [Benchmark App] Prioritize the config for device given in CLI when multiple are available

- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
- docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device/batching-on-npu-plugin.rst
- *Add documentation for batching on NPU plugin*
- *...*
- *EISW-118045*
> [NPU] Add documentation for batching on NPU plugin

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- Update `fc_bf_tiled_kernel_dyn_quan` for osv_is_yx_osv64_isv2 support
- 153232
> [GPU] Support large N FC optimization for dynamic quantization case

- src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
- src/plugins/intel_gpu/src/graph/debug_helper.cpp
- src/plugins/intel_gpu/src/graph/debug_helper.hpp
- src/plugins/intel_gpu/src/graph/include/program_dump_graph.h
- src/plugins/intel_gpu/src/graph/network.cpp
- src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
- Debug code in network::execute() method is extracted to separate class/file to improve code readability
> [GPU] Extract debug code from network::execute()

- tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_dot.py
- tests/requirements_tensorflow
**Details:** New Keras Dot operation does not support integer operands
> [TF FE][Keras] Use latest Keras for TF FE validation and adopt tests

- docs/sphinx_setup/api/nodejs_api/nodejs_api.rst
- docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst
- docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst
Fixing references to new methods introduced in the 2024.4 release.
> [DOCS] Fixing references in Node.js API docs

- .github/actions/store_artifacts/store_artifacts.py
This will make sure that "latest available" link is pointing to the complete set of artifacts
> [GHA] Don't update latest available artifacts link when copy failed

- CONTRIBUTING.md
- docs/articles_en/get-started/install-openvino/install-openvino-pip.rst
- docs/sphinx_setup/conf.py
port: https://github.com/openvinotoolkit/openvino/pull/26883
> [DOCS] technical adjustments for the build 24.4

- tests/requirements_pytorch
**Details:** Optimum-intel will install the required version. Since we primarily validate compatibility OV with `optimum-intel`, let us leave only `optimum-intel`
**Ticket:** 154283
> [PT FE] Remove explicit optimum deps from validation

- src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- In the case of dynamic shapes, we need to call get_partial_shape, because `get_shape` will throw if called on dynamic shape
- E88902
> Use get_partial_shape to get dynamic shape

- src/plugins/intel_npu/src/al/include/sync_infer_request.hpp
- src/plugins/intel_npu/src/al/src/sync_infer_request.cpp
- src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp
- src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp
- src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
- src/plugins/intel_npu/tests/functional/behavior/batched_tensors_tests/batched_run.cpp
- src/plugins/intel_npu/tests/functional/behavior/batched_tensors_tests/batched_run.hpp
- src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- *Adding support for the set_tensor method*
set_tensors works differently in case the plugin or the compiler handles the batch:
- in case the compiler handles batching we need to create a continuous L0 tensor and copy all the tensors into that big tensor even when tensors are part of the same L0 context
- in case the plugin handles batching and the remote tensor feature is supported copy is not used if the tensors are part of the same L0 context.
- *EISW-116494*
> [NPU] Adding support for the set_tensors method

- src/common/snippets/src/utils/tokenization_utils.cpp
- src/common/snippets/tests/src/pass/collapse_subgraph.cpp
- src/common/snippets/tests/src/pass/mha_tokenization.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/arm/convert.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/x64/convert.cpp
- src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/snipptes_mark_skipped.cpp
- src/tests/ov_helpers/ov_snippets_models/include/subgraph_converts.hpp
- src/tests/ov_helpers/ov_snippets_models/src/subgraph_convert.cpp
- src/tests/ov_helpers/ov_snippets_models/src/subgraph_mha.cpp
- src/tests/ov_helpers/ov_snippets_models/src/subgraph_simple.cpp
- *Stub convert related logic is removed from tokenization helper, since it is not actual anymore*
- *Skipped tokenization tests are reenabled, reference builders are fixed*
- *CVS-142098*
- *CVS-114607*
- *CVS-114336*
> [Snippets] Tokenization helper cleanup and tokenization tests reenabling

- src/plugins/intel_npu/src/backend/include/zero_executor.hpp
- src/plugins/intel_npu/src/backend/include/zero_remote_tensor.hpp
- src/plugins/intel_npu/src/backend/include/zero_types.hpp
- src/plugins/intel_npu/src/backend/src/zero_executor.cpp
- src/plugins/intel_npu/src/backend/src/zero_remote_tensor.cpp
- src/plugins/intel_npu/src/compiler/include/zero_compiler_in_driver.hpp
- src/plugins/intel_npu/src/compiler/src/driver_compiler_adapter.cpp
- src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- *Use different graph init in case graph file schema or elf is used*
- *CVS-154233*
> [NPU] Use different graph init

- .github/actions/openvino_provider/action.yml
4.4.1 breaks symlinks handling causing uploaded OV archives to be corrupted
> [GHA] Pin upload-artifact version in provider

- src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- src/plugins/intel_gpu/src/plugin/ops/convolution.cpp
- src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/convolution.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_smoke_test_with_static_conv.cpp
- *Conv should not extend strides and dilations for 3d output*
- *Update not to call get_dims() for dynamic shape*
- *150680*
> [GPU] Conv should not extend strides and dilations for 3d output

- src/plugins/intel_gpu/src/graph/fully_connected.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- *Fixed for onednn to work with the original fc*
- *Added unit test*
- *150433*
> [GPU] Fix fc 4d for onednn

- src/plugins/intel_gpu/src/graph/impls/ocl/dynamic_quantize.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_opt.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_ref.h
- *DynamicQuantize requires the FC ifm size to generate the kernel.*
- *But it cannot be obtained with fully dynamic input shape, so it has been queried from fc.*
- *152019*
> [GPU] Use ifm size of fc for dynamic quantize

- tests/layer_tests/tensorflow_tests/test_tf_Bucketize.py
- There is sporadic accuracy issue occurred in the certain machine when boundaries_size is 0 on GPU
- It needs to skip until the issue will be solved
- 152562
- 154261
> Skip test_tf_Bucketize for boundaries_size is 0 on GPU

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/select_gpu_ref.cl
- src/plugins/intel_gpu/tests/unit/fusions/select_fusion_test.cpp
When the input is f16 and the output is u8, the non-fused select-reorder will execute convert_uchar(convert_long(res)). However, the fused select-reorder will execute convert_uchar(res), resulting in different outputs in some cases.
For example:
convert_uchar(-1.0) = 0, but convert_uchar(convert_long(-1.0)) = 255
CVS-152175
> [GPU] fix fused_select_reorder

- .github/workflows/linux_sanitizers.yml
Even if parent build skipped in forks it continues to wait for it 'cause of "always()" condition
> [GHA] Fix sanitizers tests trigger in forks

- src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
- Changes the constructor used from primitive_impl to use one that already assigns a nullptr rather than passing in an empty array, which currently leads to an empty array comparison to nullptr
- 112755
> [GPU] switch onednn primitive to use other primitive_impl constructor

- tests/layer_tests/py_frontend_tests/test_torchvision_preprocessor.py
- tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
- *Will restart any `RuntimeError` as the searching text in the exception class is not reliable enough*
- *CVS-151277*
> [TESTS] Remove restart condition as it happens in nested exception

- src/bindings/python/src/openvino/frontend/pytorch/gptq.py
- *`QUANT_TYPE == "cuda"` is not supported, but claimed as supported and produce incorrect model.*
- *CVS-154376*
> [PT FE] Disable support for cuda GPTQ type, since it was never supported

- tools/mo/unit_tests/mo/utils/simple_proto_parser_test.py
- tools/mo/unit_tests/moc_tf_fe/conversion_basic_models_test.py
Disabled test_incorrect_proto_reader_from_string_1, it's not much of a big deal, it's one of a bunch of cases when we check that we report informative message when prototxt was invalig, all other cases work just fine.
Also disabled test which fails with segfault. When test device is changed to GPU tests is green, this mean issue is in plugin.
https://github.com/openvinotoolkit/openvino/blob/c0d02e9188e3fc40a28a0552890b3e0fe01f687a/tools/mo/unit_tests/moc_tf_fe/conversion_basic_models_test.py#L35
- CVS-154263
> temporarily disable sample proto unit-test

- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
- src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
- src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp
- Added a jit_soft_sign_emitter derived class in aarch64/jit_eltwise_emitters
- Created entry Algorithm::EltwiseSoftSign in the get_supported_precisions in nodes/kernels/aarch64
- Add the EltwiseSoftSign entry in the aarch64 executors supported algorithms
- Closes #24114
> [CPU][ARM64] Add JIT emitter for Eltwise SoftSign operation

- .github/workflows/job_build_linux.yml
Calling store_artifacts twice in a row is excessive and causes improper artifacts storage due to dir rotation
> [GHA] Fix wheels storage handling

- src/plugins/intel_gpu/src/graph/gemm.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/graph/program_node.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
1. Fixed a bug where dynamic tensor value would disappear when using dynamic and static inputs together.
2. Fixed onednn gemm post-op wrong dims in case spatial 1x1.
3. Fixed side effect for can_be_optimized condition in  allocate_output . Skippable should be true for using mem pool.
- *149836*
> [GPU] Fix sd1.5_controlnet_lora bad image.

- src/plugins/intel_cpu/src/node.cpp
- src/plugins/intel_cpu/src/nodes/memory.cpp
Add a short path for "empty" state tensors processing in the MemoryInput and MemoryOutput nodes.
- CVS-152850
- CVS-153035
> [CPU] Optimize MemoryInput/Output for empty shapes

- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/denormal_check.cpp
- *try to fix the SEH abort in windows test*
- *CVS-150527*
> [CPU]Fix heap buffer overflow in DenormalNullifyCheck

- cmake/developer_package/ncc_naming_style/ncc_naming_style.cmake
**Problem:** When a project includes both OpenVINO (via the OpenVINO developer package) and LLVM as an in-tree dependency, it can lead to conflicts between different versions of LLVM.
**Solution:**
* One way to resolve this is by including clang directly using `find_library`, rather than relying on `find_package`.
* This approach avoids the implicit call to `find_package(LLVM)` that occurs when using `find_package(CLANG)`, thus preventing version conflicts.
- E-78260
> Use find_library to find clang on linux

- src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.cpp
- Aligns memory format between prefill and kvcache 
- Recommended to be disabled by default when sharing is in place (e.g, when DQ is applied to both models)
- E-143367
> NPUW: Enable PMM for prefill by default

- src/common/util/include/openvino/util/mmap_object.hpp
- src/common/util/src/os/win/win_mmap_object.cpp
- src/core/dev_api/openvino/runtime/shared_buffer.hpp
- src/inference/src/cache_manager.hpp
- src/inference/src/dev/core_impl.cpp
- src/inference/src/dev/core_impl.hpp
- src/plugins/intel_cpu/src/plugin.cpp
- src/plugins/intel_cpu/src/utils/serialize.cpp
- src/plugins/intel_cpu/src/utils/serialize.hpp
- src/plugins/intel_gpu/src/plugin/plugin.cpp
- Enable mmap for reading model from cache
- CVS-152423
> Enable mmap for reading  model from cache

- src/frontends/onnx/frontend/CMakeLists.txt
- src/frontends/onnx/frontend/src/op/dequantize_linear.cpp
- src/frontends/onnx/tests/models/dequantize_linear_21.prototxt
- src/frontends/onnx/tests/onnx_import_quant.in.cpp
- Added initial support of operation DequantizeLinear-21 from default opset
- 152784
> [ONNX] Added initial support of DequantizeLinear-21

- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
- src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
- src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
- src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp
- Added a jit_sqrt_emitter derived class in aarch64/jit_eltwise_emitters
- Created entry Algorithm::EltwiseSqrt in the get_supported_precisions in nodes/kernels/aarch64
- Add the EltwiseSqrt entry in the aarch64 executors supported algorithms
- Add the ActivationType::Sqrt in the getPrimitiveType in activations
- #24446
> [CPU][ARM64] Add JIT emitter for Eltwise Sqrt operation

- src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
- src/plugins/intel_gpu/src/graph/crop.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- src/plugins/intel_gpu/src/graph/impls/cpu/read_value.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/gemm.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl/non_zero.cpp
- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/slice_ref.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/slice/slice_kernel_ref.cpp
- src/plugins/intel_gpu/src/plugin/ops/variable.cpp
- src/plugins/intel_gpu/src/plugin/variable_state.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.hpp
- src/plugins/intel_gpu/tests/unit/test_cases/non_zero_gpu_test.cpp
- *Added functional support of empty LoRA adapters*
- *Added fusing support for `crop` operation*
- *Removed unnecessary `Assign` after `ReadValue`*
- *Use enqueue_fill_mem instead enqueue_memcpy in gpu_usm::fill()*
- *[152852](https://jira.devtools.intel.com/browse/CVS-152852)*
> [GPU] Added empty LoRA adapters support

- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_nd_ref.cl
- src/plugins/intel_gpu/tests/unit/test_cases/gather_nd_gpu_test.cpp
There is a bug in the GPU plugin's GatherND kernel where the output indices are incorrect for 5D index inputs when the 4th dimension of the index input is not of size 1 and `batch_dims == 0`.
- When `batch_dims <= 1` the current implementation of GatherND in the GPU plugin does not shift the output indices as expected. For example, `out_x` is set to `idx_x` (the x index for the second input). However, this is not correct since the last dimension of the second input to GatherND is the indices to use and does not contribute to the shape of the output tensor (beyond deciding how many of the original input dimensions to keep). The current logic happens to work in most cases, but is not generally correct.
- This PR adds a test case that demonstrates the bug (it fails on main), and the changes …
> [GPU] Fix bug in GatherND reference GPU kernel

- src/plugins/intel_cpu/src/nodes/rope.cpp
- src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/rotary_pos_emb.cpp
- *Support Rope kernel of GLM4*
- *the input data order has changed from (**[seq_length, batch, 4608]**) in **ChatGLM3** to (**[batch, seq_length, 4608]**) in **ChatGLM4**. Within RoPE process, the data order changes from (**[seq_length, batch, head_count, head_size]**) to (**[batch, head_count, seq_length, head_size]**) by permute operation added in **ChatGLM4**.*
- *the RoPE cache data order has changed from (**[seq_length, batch, head_count, 2]**) in ChatGLM3 to (**[batch, head_count, seq_length, 2]**) in **ChatGLM4**.*
- *Consequently, the output of RoPE has also changed from (**[seq_length, batch, head_count, head_size]**) in **ChatGLM3** to (**[batch, head_count, seq_length, head_size]**) in **ChatGLM4***
- *Due to these changes, the RoPE pattern matching needs to create something …
> [CPU]support glm4 rope

- src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
- Fix weight reorder src format to avoid inconsistancy ndims of src/dst in weight reorder
- 154614
> [GPU] Fix weight reorder src format to avoid inconsistency ndims of src/dst in weight reorder

- src/plugins/intel_npu/src/plugin/src/backends.cpp
- src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
[log.error of  NPUbackend](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_npu/src/plugin/src/backends.cpp#L130) will confuse the user, thought NPU backend does not impact the compilation and just impact the inference stage.
Now [in the inference stage in compiledmodel part](https://github.com/openvinotoolkit/openvino/pull/27073/files#diff-74bc81bb7b258118f04e81468e3ec3b05e65e714546d32246bae45eb892f6abcR125-R130), will get a log.error output when no npu device is checked.
- 153439
> [NPU]Change NPUBackend log

- src/common/transformations/src/transformations/convert_precision.cpp
- *Read value node without input source on FP16 precision would raise exception. The PR fix this.*
- *CVS-153067*
> [Transformations] Fix exception when converting precision on Read_Value node without inputs.

- src/plugins/intel_gpu/src/graph/debug_helper.cpp
- Fixed dump file name to not have layer ID twice.
> [GPU] Removed redundant part for dump file name

- src/frontends/tensorflow_lite/include/openvino/frontend/tensorflow_lite/decoder.hpp
- src/frontends/tensorflow_lite/include/openvino/frontend/tensorflow_lite/graph_iterator.hpp
- src/frontends/tensorflow_lite/include/openvino/frontend/tensorflow_lite/quantization_info.hpp
- src/frontends/tensorflow_lite/include/openvino/frontend/tensorflow_lite/sparsity_info.hpp
**Details:** We need to properly export public API in tensorflow_lite_frontend shared library so that TFLite delagate can import them. All abstract classes that TFLite Delegate implements on its own should be exported. `QuantizationInfo` also should be exported to avoid duplications/re-definitions in binaries.
> [TFL FE] Export public API symbols for TFLite Delegate

- src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- src/plugins/intel_gpu/src/runtime/execution_config.cpp
- src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- It is applied only to int4 compressed model, non-systolic path
- Though it is a global configuration, systolic hardware will ignore it
- 151708
> [GPU] Enable dynamic quantization gs32 as default for non-systolic

- src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
- src/plugins/intel_gpu/src/runtime/memory_pool.cpp
- Fix not to check _dynamic_dims_mask when get_from_padded_pool()
- 154329
- 155099
- 154137
> [GPU] Fix not to check _dynamic_dims_mask when get_from_padded_pool()

- src/cmake/ov_parallel.cmake
- *Fix Conan Debug Build*
A failed compilation look like this
```
cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="F:/.conan2/p/b/openvdff378fa94719/p" -DENABLE_INTEL_CPU="ON" -DENABLE_INTEL_GPU="ON" -DENABLE_ONEDNN_FOR_GPU="ON" -DENABLE_INTEL_GNA="OFF" -DENABLE_AUTO="ON" -DENABLE_MULTI="ON" -DENABLE_AUTO_BATCH="ON" -DENABLE_HETERO="ON" -DENABLE_OV_IR_FRONTEND="ON" -DENABLE_OV_PADDLE_FRONTEND="ON" -DENABLE_OV_TF_FRONTEND="ON" -DENABLE_OV_TF_LITE_FRONTEND="ON" -DENABLE_OV_ONNX_FRONTEND="ON" -DENABLE_OV_PYTORCH_FRONTEND="ON" -DENABLE_SYSTEM_TBB="ON" -DENABLE_TBBBIND_2_5="OFF" -DENABLE_SYSTEM_PUGIXML="ON" -DENABLE_SYSTEM_PROTOBUF="ON" -DENABLE_SYSTEM_SNAPPY="ON" -DENABLE_SYSTEM_FLATBUFFERS="ON" -DENABLE_SYSTEM_OPENCL="ON" …
```
> [Conan Build]Fix Debug Build

- src/plugins/intel_cpu/src/emitters/plugin/x64/jit_dnnl_ext_emitters.hpp
- src/plugins/intel_cpu/src/emitters/plugin/x64/jit_eltwise_emitters.cpp
- src/plugins/intel_cpu/src/emitters/plugin/x64/jit_eltwise_emitters.hpp
- src/plugins/intel_cpu/src/nodes/eltwise.cpp
- *Previously, we used dnnl-injector for `Exp` op which require 2 `aux_vec_regs`. The snippets kernel have some pool of aux vec registers which can be used by emitters in their implementations. However, dnnl cannot work with user-provided aux registers and always spill them on stack while plugin emitters can do it. To avoid extra push-pop in Snippets kernel (it leads to performance degradations), we implemented own emitter for `Exp` with the same logic to have opportunity to pass free aux vec registers*
- *Updated `jit_erf_emitter`: reused new `jit_exp_emitter` to compute exponent and now we work only with `vmm_dst` to avoid `vmm_src` data corruption (input registers must not be corrupted)*
- *155236*
> [CPU] Implemented "jit_exp_emitter"

- tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_embedding.py
- tests/layer_tests/tensorflow_tests/test_tf_BiasAdd.py
**Details:** Skip one test case for keras Embedding on CPU due to timeout issue
**Ticket:** 155622
> [TF FE] Skip one test case for keras Embedding on CPU due to timeout issue

- src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
- *support new isa avx2_vnni_2 in threading scheduling*
- *154908*
> support new isa avx2_vnni_2 in threading scheduling

- src/bindings/js/node/tests/e2e/demo-electron-app/index.js
- src/bindings/js/node/tests/e2e/electron-app.test.js
- Extend e2e test of Node.js API by performing test inference
- 154192
> [OV JS] Perform inference in electron app in nodejs e2e test

- tests/layer_tests/py_frontend_tests/test_torch_decoder.py
- *Skip signature test for older torch*
- *CVS-155238*
> [TESTS] Skip signature test for older torch

- src/plugins/auto/src/auto_schedule.cpp
- src/plugins/auto/src/schedule.cpp
- Get time points from list only if not empy to avoid exception ` Assertion failed: front() called on empty list` reported by MSVC in debug.
- CVS-155400
> [auto] Fix time calculation when time points lists are empty

- src/core/include/openvino/core/parallel.hpp
- src/plugins/intel_cpu/src/nodes/interpolate.cpp
- src/plugins/intel_cpu/src/nodes/interpolate.h
- *Fix threads number*
- *...*
- *152606*
> [CPU][OMP] Fix for Interpolate node

- src/plugins/intel_cpu/src/nodes/eltwise.cpp
- src/plugins/intel_cpu/src/nodes/executors/shl/shl_eltwise.cpp
- src/plugins/intel_cpu/src/nodes/executors/shl/shl_utils.hpp
- src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/concat_conv_sum_inplace.cpp
- src/plugins/intel_cpu/tests/functional/utils/riscv64/filter_cpu_info.cpp
- *Add `nhwc` layout support for shl eltwise executor*
- *Enable some tests with `nhwc` layout*
- *N/A*
> [RISCV64] add nhwc layout support for eltwise executor

- src/plugins/intel_gpu/tests/functional/behavior/model_cache.cpp
Currently the tests have weightless caching enabled, but the models tested contain no constants eligible for weightless caching. This fixes the situation.
To elaborate - all the models have f32 dtype constants by default. In these particular models all of the constants which would otherwise be eligible for weightless caching undergo some precision transformation which invalidates this eligibilty. The PR changes the dtype of the constants to prevent that and deletes the models which contain no constants eligible for weightless caching even after the dtype change.
> [GPU][TESTS] Fix weightless caching tests

- src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h
- src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp
- src/plugins/intel_gpu/src/plugin/ops/paged_attention.cpp
- Add support for non-constant scale input, as the current Paged Attention specification does not require this value to be strictly constant
> [GPU] Handle runtime scale value for PagedAttention

- docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
- docs/articles_en/learn-openvino/llm_inference_guide/genai-guide/genai-use-cases.rst
Creating an article with use case scenarios for using OpenVINO GenAI. This PR addresses the following
JIRA ticket: CVS-153319
> [DOCS] Adding GenAI Use Cases

- src/bindings/python/src/openvino/runtime/opset15/__init__.py
- src/bindings/python/src/openvino/runtime/opset15/ops.py
- src/bindings/python/tests/test_graph/test_create_op.py
- *[PyOV] Extend Python API with SearchSorted-15*
- *...*
- *CVS-155961*
> [PyOV] Extend Python API with SearchSorted-15

- src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.hpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- set LPT callbacks to handle compression and avoid constant folding for it (taken from https://github.com/openvinotoolkit/openvino/pull/20973)
- Allow u8/i8 output data type for compressed onednn FC
- Disable Dequantize propagation through Transpose if it's a dependency of SDPA to keep Transpose+SDPA fusion
> [GPU] Fixes for hybrid quantization

- tests/constraints.txt
- tests/model_hub_tests/pytorch/requirements.txt
- *Port #27126 into release 24.4*
- *ticket-id*
> [TESTS] Fix version for huggingface_hub

- src/common/transformations/src/transformations/common_optimizations/shared_ops_optimization.cpp
- src/common/transformations/src/transformations/symbolic_transformations/symbol_optimization.cpp
- src/common/transformations/tests/common_optimizations/shared_ops_optimization.cpp
- src/common/transformations/tests/symbolic_transformations/symbol_optimization.cpp
- src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/ngram_fusion.cpp
- SharedOpOptimization: optimization keeps the same topological order. It allows for seamless optimization in one run over the model
- OptimizeSymbolsUsedAsValues: partial values containing symbols and constant values are now participating in the value optimization too
- Continuation of  PR 27153 to fix tests
- N/A
- #27153
> [Transformations] SharedOpOptimization and SymbolicOptimization update

- src/plugins/intel_npu/src/al/include/intel_npu/npuw_private_properties.hpp
- src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.cpp
- src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp
- src/plugins/intel_npu/src/plugin/npuw/util.cpp
- src/plugins/intel_npu/src/plugin/npuw/util.hpp
- The problem is that for different networks the number of NPUW's detected block may be different and it is hard to tell what the last block number will be. Now 'last' option can be used to tell NPUW to dump tail block without setting specific number.
- E-139857
> NPUW: Introduce 'last' keyword for dump options

- src/bindings/python/constraints.txt
- src/bindings/python/requirements_test.txt
- tools/constraints.txt
- tools/mo/requirements_dev.txt
- `py` package has a high CVE on it
- it's also in maintenance mode
- there are seemingly no usages of that package in the codebase, so it can be dropped
- let's wait for CI results to confirm
- CVS-156002
> [PyOV] Remove `py` package

- src/plugins/intel_npu/thirdparty/CMakeLists.txt
- no need to build dynamic yaml-cpp library. Overlooked while moving it from npu project https://github.com/openvinotoolkit/npu_plugin/blob/develop/thirdparty/CMakeLists.txt#L27
- before 
```
Creating library C:/Users/mdoronin/work/openvino/bin/intel64/Release/yaml-cpp.lib and object C:/Users/mdoronin/work/openvino/bin/intel64/Release/yaml-cpp.exp
yaml-cpp.vcxproj -> C:\Users\mdoronin\work\openvino\bin\intel64\Release\yaml-cpp.dll
```
- after 
```
yaml-cpp.vcxproj -> C:\Users\mdoronin\work\openvino\bin\intel64\Release\yaml-cpp.lib
```
- *ticket-id*
> Build yaml-cpp statically

- tests/layer_tests/ovc_python_api_tests/test_pytorch.py
- tools/ovc/openvino/tools/ovc/moc_frontend/pipeline.py
- *`output` argument cannot be used for pytorch as it is unclear what behavior is expected in this case.*
- *#26457 *
> [OVC] Fail with unsupported message when output argument is used for pytorch

- src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp
- src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- Support activation zero points for i32 in convolution onednn
- 155423
> [GPU] Support convolution onednn activation zero points for i32

- src/plugins/intel_cpu/src/nodes/kernels/x64/rms_kernel.cpp
- src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/rms_norm.cpp
- *Add "if" statement for loop unrolling in rms kernel to fix Segmentation Fault in tiny-random-sd3 model*
- *CVS-152057*
> Add "if" statement for loop unrolling in rms kernel.

- src/plugins/intel_cpu/src/config.cpp
- *SHL library uses static global variables as flags and counters. It means that multi-stream execution can be unsafe when SHL is used - there can be data racing. The PR manually sets `streams = 1` to avoid possible functional issues in tput scenario with using SHL*
- *N/A*
> [RV64] Disabled multi-stream mode when SHL is used

- src/common/transformations/src/transformations/common_optimizations/gelu_fusion.cpp
- src/common/transformations/tests/common_optimizations/gelu_fusion.cpp
- Previously GeLU Tanh was supported only for x * (0.5 * (1 + tanh))
- Support pattern with (x * 0.5) * (1 + tanh)) too.
- 155576
> [GPU] Support GeLU Tanh for Phi-2

- src/plugins/intel_npu/src/backend/include/zero_types.hpp
- src/plugins/intel_npu/src/backend/src/zero_backend.cpp
- src/plugins/intel_npu/src/backend/src/zero_init.cpp
- src/plugins/intel_npu/src/compiler/include/zero_compiler_in_driver.hpp
- src/plugins/intel_npu/src/compiler/src/driver_compiler_adapter.cpp
- src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- *use ze_graph_dditable_ext_t to replace local ze_graph_dditable_ext_last_t*
- *use ze_graph_ext_version_t as template parameter instead of ze_graph_dditable_ext_1_x*
- *update commit of level-zero-ext to use one ddi table*
Plugin with current driver and driver released later, will use ze_graph_dditable_ext_t and ZE_extension_graph, the version is ZE_GRAPH_EXT_VERSION_CURRENT inside current level-zero-ext commit, 1.8 now
Plugin with old driver, will use ze_graph_dditable_ext_t to reinterpret old ddi table, use largest version supported by driver, , backend work on ze_graph_ext_version_t, compiler will work based on ze_graph_ext_version_t. Fpr example, largest ext version supported by driver is 1.7. plugin will use 1.7.
- *155313*
> []NPU] Update adapter and backend to use new level zero ext table

- src/common/transformations/src/transformations/convert_precision.cpp
- src/common/transformations/tests/utils/convert_precision.cpp
[TRANSFORMATIONS] Check if Select is 'relaxed' only if 0th input is not boolean in ConvertPrecision
The ConvertPrecision transformation wraps Select node (its 0th input in particular) into RelaxedType to accept tensors with other element types than boolean. Add a check to perform the appearance of RelaxedType only if the 0th input is not boolean.
Tickets:
* CVS-155745
* CVS-155990
> [TRANSFORMATIONS] Check if FROM types are different from a node's type in ConvertPrecision

- src/frontends/pytorch/src/op/lerp.cpp
- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_lerp.py
- *Support `aten::lerp` and `aten::lerp_`*
- *CVS-156191*
> [PT FE] Support aten::lerp and aten::lerp_

- .github/actions/smart-ci/action.yml
For easier usage in 3rd-party repos
> [GHA] Use action_path in default smart ci config path

- src/common/transformations/src/transformations/common_optimizations/reverse_shape_and_type_infer.cpp
- src/frontends/tensorflow/src/transformations/switch_merge_resolve.cpp
- tests/layer_tests/tensorflow_tests/test_tf_SwitchMerge.py
**Details:** It helps to convert some TF models out-of-the-box with static rank tensors that are required by plugins for inference.
**Ticket:** 156204
> [TF FE] Deduce Switch-Merge predicate shape

- docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sort/search-sorted-15.rst
- *Align SearchSorted tensor/attribute names with ones used in core*
- *Minor improvements for descriptions*
- *Fix SliceScatter missing opset number*
- *ticket-id*
> [SPEC][Op] Align SearchSorted specification with core

- src/plugins/intel_cpu/src/nodes/ctc_loss.cpp
- src/plugins/intel_cpu/src/nodes/eltwise.cpp
- src/plugins/intel_cpu/src/nodes/gather.cpp
- src/plugins/intel_cpu/src/nodes/gather.h
- src/plugins/intel_cpu/src/nodes/grid_sample.cpp
- src/plugins/intel_cpu/src/nodes/grid_sample.hpp
- src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/mha_single_token.cpp
- src/plugins/intel_cpu/src/nodes/llm_mlp.cpp
- src/plugins/intel_cpu/src/nodes/mha.cpp
- src/plugins/intel_cpu/src/nodes/mha.h
- src/plugins/intel_cpu/src/nodes/mvn.cpp
- src/plugins/intel_cpu/src/nodes/qkv_proj.cpp
- src/plugins/intel_cpu/src/nodes/reduce.cpp
- src/plugins/intel_cpu/src/nodes/roi_align.cpp
- src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
- src/plugins/intel_cpu/src/nodes/strided_slice.cpp
- src/plugins/intel_cpu/src/nodes/strided_slice.h
- *Function `parallel_get_max_threads()` may returns ether core number or threads number. That can affect buffers access which size depends on threads number.*
- *...*
- *152606*
> [CPU][OMP] Safe usage of threads num with buffers

- src/plugins/intel_npu/src/backend/src/zero_device.cpp
- Bugfix in zero_device to return correct maximum allocable memory size in NPU_DEVICE_TOTAL_MEM_SIZE property.
- For old drivers we return hardcoded 2GB value (compiler limitation)
- For graph_ext 1.8 windows drivers we just convert KB to B
- For graph_ext >1.9 drivers we return values from driver as is
- *EISW-143246*
> [intel-npu] Bugfix for total allocable memory property

- tests/layer_tests/pytorch_tests/test_lerp.py
- *Disable `lerp_` test for `torch.export` on older versions of `torch`*
- *CVS-156278*
> [TESTS] Disable lerp test for torch.export on older versions

- src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend.py
- Torch 2.5.0 enabled regional compilation by default which degrades the performance of openvino backend
- (https://jira.devtools.intel.com/browse/CVS-156251)
> Disabled regional compilation

- src/bindings/python/src/openvino/runtime/properties/hint/__init__.py
- src/bindings/python/src/pyopenvino/core/properties/properties.cpp
- src/bindings/python/tests/test_runtime/test_properties.py
- src/inference/include/openvino/runtime/intel_gpu/properties.hpp
- src/inference/include/openvino/runtime/properties.hpp
- src/plugins/intel_gpu/src/plugin/compiled_model.cpp
- src/plugins/intel_gpu/src/plugin/plugin.cpp
- src/plugins/intel_gpu/src/plugin/transformations/fc_per_layer_scaling.cpp
- src/plugins/intel_gpu/src/plugin/transformations/fc_per_layer_scaling.hpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/src/runtime/execution_config.cpp
- src/plugins/intel_gpu/tests/unit/transformations/fc_per_layer_scaling_test.cpp
- Fix LLM accuracy issue due to fp16 overflow when using decompression_post_opt in fully_connected_gpu_bf_tiled_opt kernel
- In the fc kernel, to optimize grouped scale, we calculate acc first as mad of activation (fp16) * weight (int4) first , and then apply scale value. This can cause accuracy issue when only multiply of activation and weight overflows. 
- In this case we can resolve the issue by applying scale down to the activation. 
- Implement per layer scaling for FCs
- 154583
> [GPU] Add per layer scaling for FC to fix accuracy issue regarding fp16 overflow

- src/plugins/intel_gpu/include/intel_gpu/primitives/scaled_dot_product_attention.hpp
- model cache was not working because of load/save mismatch
> [GPU] model cache fix from kv cache compression

- src/plugins/intel_npu/src/backend/src/zero_device.cpp
- another quickfix for maximum memory allocation property, to enable UD44 windows drivers too
- addition to https://github.com/openvinotoolkit/openvino/pull/27270
- *EISW-143246*
> [intel-npu] max memalloc quickfix for grext 1.8 windows drivers

- tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py
**Details:** Before the fix, conversions of ExportedProgram from memory and disk use different decomposition sets
> [PT FE] Unify conversion pipeline for ExportedProgram from memory and disk

- src/plugins/intel_gpu/src/graph/impls/onednn/concatenation_onednn.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/deconvolution_onednn.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/pooling_onednn.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/reduce_onednn.hpp
- src/plugins/intel_gpu/src/graph/impls/onednn/reorder_onednn.hpp
- src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp
- This patch enforces dpas availability flag to false when HW architecture is unknown to onednn to fallback to OCL kernels which are supposed to be more generic and more forward compatible.
- Also, added an architecture check in each onednn-based impl if in the future we'll stop relying on `supports_immad` flag when decide whether to use onednn or not.
> [GPU] Disable OneDNN for unknown arch via dpas flag faking

- src/frontends/pytorch/src/op_table.cpp
- tests/layer_tests/pytorch_tests/test_bitwise_ops.py
- *add support `aten::__ior__`, `aten::__iand__`, `aten::__ixor__`*
- *CVS-156301*
> add support aten::__ior__

- src/bindings/python/src/pyopenvino/core/common.cpp
- src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- tests/layer_tests/tensorflow_tests/test_tf_LookupTableSize.py
- In case the element type is string produces the segmentation fault when input data is an empty string, unless the each element of tensor.data is initialized.
- 148921
> [GPU] Init tensor.data when allocating inputs for string type

- docs/articles_en/about-openvino/performance-benchmarks/generative-ai-performance.rst
- docs/sphinx_setup/_static/js/openVinoDataTables.js
- *item1*
- *...*
- *ticket-id*
> Docs Unhide columns in datatableJs

- src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_opt.cpp
- src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_ref.cpp
- Allow the DynamicQuantizeKernelOpt kernel to be selected with the default scales order
- Relax DynamicQuantizeKernelRef kernel validation function
> [GPU] Fix per-token dynamic quantization 

- src/plugins/intel_gpu/src/graph/impls/registry/gemm_impls.cpp
- src/plugins/intel_gpu/tests/unit/fusions/gemm_fusion_test.cpp
- src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- *Performance improvement for LoRA*
> [GPU] Use onednn impl for dynamic gemm

- src/bindings/python/src/openvino/runtime/opset13/ops.py
- src/bindings/python/tests/test_graph/test_constant.py
- using of singledispatch breaks the scenario where a user pass keywords arguments only
- CVS-153553
> [PyOV] allow constant accept keyword args

- src/frontends/onnx/frontend/src/op/dequantize_linear.cpp
Aligned with the canonical form of the dequantization subgraph.
Reshape op has been moved up right after the Constant, it will be const folded in MOC, this is ok, Reshape const folding doesn't copy a constant, just copies a pointer.
And ConvertLike were replaced with Convert. Perhaps that's a pretty rough change and we need to add a check here that the scale is a contant. And in that case use Convert instead of ConvertLike, if scale is not a constant, maybe we should leave ConvertLike.
- *https://jira.devtools.intel.com/browse/CVS-156329*
> [ONNX] Update DequantizeLinear21 converter

- tests/layer_tests/tensorflow_tests/test_tf_LookupTableFind.py
- tests/layer_tests/tensorflow_tests/test_tf_RaggedTensorToSparse.py
- tests/layer_tests/tensorflow_tests/test_tf_RaggedTensorToTensor.py
- tests/layer_tests/tensorflow_tests/test_tf_StaticRegexReplace.py
- tests/layer_tests/tensorflow_tests/test_tf_StringLower.py
- tests/layer_tests/tensorflow_tests/test_tf_StringSplitV2.py
- tests/layer_tests/tensorflow_tests/test_tf_StringToHashBucketFast.py
**Details:** Since openvino-tokenizers is build for ARM in the precommit, we are ready to switch on String ops tests
> [TF FE] Run string ops tests on ARM

- src/frontends/onnx/frontend/src/op/dequantize_linear.cpp
- Disabled constant folding for Subtract branch of DequantizeLinear-21
- 156329
> [ONNX] Disabled constant folding for Subtract branch of DequantizeLinear-21

- src/core/include/openvino/op/util/broadcast_base.hpp
- src/core/src/op/util/broadcast_base.cpp
- *Improves symbol propagation in LLMs and allows for better ShapeOf optimization*
> Broadcast: symbol propagation

- tests/layer_tests/requirements.txt
- Updated required version of ONNXRuntime for layer tests, because otherwise they may not be able to read fresh onnx files
- N/A
> [ONNX] Updated a required version of ONNXRuntime for layer tests

- src/core/include/openvino/op/stft.hpp
- Fix OPENVINO_OP macro for STFT with opset15 (without that it is registered and serialized with version="extension" by default, and can't be deserialized)
- It follows all of the other ops OPENVINO_OP macro, the "opset15" has been missed for STFT
Example: https://github.com/openvinotoolkit/openvino/blob/4d8ff86bd2e853b84a28acd2ece1836d28523f9e/src/core/include/openvino/op/slice_scatter.hpp#L17
- 156667
> [Fix][STFT] OPENVINO_OP macro for STFT with opset15

- src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_permutes_at_runtime.cpp
- Fix error found in mixtral model for shape [8, 2, 8] and permute order [2, 1, 0], which was optimized out unexpectedly
- Reimplemented skipping algorithm 
- 154591
> [GPU] Fix unexpected runtime skip permute

- src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.cpp
- src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/matmul_weights_decompression.cpp
Flux.1 text_encoder_2_int4 model has unusual WC pattern. (Needs extra multiply)
Add this in the target matcher.
- *154194*
> [GPU] Fix issue for Flux.1 int4 WC model memory overuse.

- src/core/include/openvino/op/concat.hpp
- Remove deprecated members of Concat operator:
* get_concatenation_axis
* set_concatenation_axis
- CVS-156181
> [core] Remove deprecated members of Concat operator

- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset1.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset10.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset11.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset12.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset13.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset14.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset15.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset2.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset3.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset5.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset6.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset7.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset8.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/available-opsets/opset9.rst
- docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/lstm-sequence-5.rst
- Align LSTM sequence version in specification, after LSTM sequence v0 removal from OV opset.
- #27330 
- CVS-156182
> [docs] Update LSTM sequence specification (version update)
