openvinotoolkit/openvino

src/bindings/python/src/openvino/frontend/pytorch/fx_decoder.py, src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/compile.py, tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py, tests/model_hub_tests/pytorch/torch_utils.py, tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py
- *Remove unused code from FX decoder*
- *ticket-id*
=> [FX] Remove unused code from FX decoder

src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp, src/plugins/intel_gpu/tests/functional/dynamic_tests/gpu_dyn_huge_input_range.cpp, src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/softmax.cpp
- Return false when dynamic shape in check_allocatable() to aviod asstion by big upper bound
- Add excessive upper bound test case in softmax dynamic shape test
- 135307
=> [GPU] Return false when dynamic shape in check_allocatable() to aviod asstion by big upper bound

src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_base.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_base.h, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_direct_10_12_16.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_gemm_like.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp
- *Add only necessary LOOP unroll params for jit constants*
- *Disable union for dispatchData*
- *135788*
=> [GPU] Add only necessary LOOP unroll params for jit constants

src/plugins/template/tests/functional/op_reference/elu.cpp
- Used actual shape in expected output tensor.
- CVS-137157
=>  [Tmpl test] Elu: enable whole Tensor comparison

src/plugins/template/tests/functional/op_reference/maximum.cpp
- Used actual shape in expected output tensor.
- CVS-137184
=> [Tmpl test] Maximum: enable whole Tensor comparison

.github/workflows/job_python_unit_tests.yml, .github/workflows/windows.yml, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_add.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_elu.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_maximum.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_minimum.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_multiply.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_relu.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_softmax.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_softplus.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_subtract.py, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_swish.py, tests/layer_tests/tensorflow_tests/test_tf_Pooling.py, tests/layer_tests/tensorflow_tests/test_tf_ReLU6.py, tests/layer_tests/tensorflow_tests/test_tf_Resample_pattern_new.py
**Details:** Remove MO legacy deps for TF FE layer tests
=> [TF FE] Remove MO legacy deps for TF FE layer tests

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp
- *Only add reorder between MVN and Conv when MVN is default format*
- *138238*
=> [GPU] Only add reorder between MVN and Conv when MVN is default format

src/plugins/template/tests/functional/op_reference/generate_proposals.cpp
- Used actual shape in expected output tensor.
- CVS-137165
=> [Tmpl test] GenerateProposals: enable whole Tensor comparison

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp, src/plugins/intel_gpu/src/graph/include/program_node.h, src/plugins/intel_gpu/src/graph/include/reorder_inst.h, src/plugins/intel_gpu/src/graph/include/reshape_inst.h, src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- *Implement primitive_node method to check runtime skippable*
- *137650*
=> [GPU] Implement primitive_node method to check runtime skippable

src/plugins/template/tests/functional/op_reference/nonzero.cpp
- Added actual shape to expected output tensor.
- CVS-137191
=> [Tmpl test] NonZero: enable whole Tensor comparison

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp, src/plugins/intel_gpu/src/plugin/common_utils.cpp, src/plugins/intel_gpu/src/plugin/program_builder.cpp
- Validate element type on each port of operation to ensure that it's supported by the plugin
=> [GPU] Add per operation precision check for query_model

docs/articles_en/learn-openvino/llm_inference_guide.rst, docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-native-ov.rst, docs/articles_en/learn-openvino/llm_inference_guide/ov-tokenizers.rst, docs/sphinx_setup/_static/images/tokenization.svg
Port from https://github.com/openvinotoolkit/openvino/pull/23749
=> [DOCS] Tokenizer article for 2024.1

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/strided_slice_ref.cl, src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- *fix new axis mode*
- *ticket-id*
=> [GPU] fix kernel new axis mode

src/frontends/tests/frontend/shared/test_builtin_extensions/builtin_extensions.cpp, src/inference/tests/functional/caching_test.cpp, src/inference/tests/functional/ov_extension_test.cpp
- Fix build of extensions tests for frontends when build of fronded is disabled. 
- Remove the warnings as error for unused functions.
- N/A
=> [tests] Fix build of extensions test for FEs if FEs disabled

src/plugins/intel_cpu/src/utils/gen_pattern.hpp
Backport https://github.com/openvinotoolkit/openvino/pull/21890 from master
- CVS-133621
=> [CPU] fix gen_pattern::AttrAny::equal_to

docs/home.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Fix a typo

src/plugins/intel_cpu/src/emitters/README.md
- *JIT Emitters documentation*
- *CVS-137892*
=> [CPU] JIT Emitters documentation

docs/articles_en/about-openvino.rst, docs/articles_en/about-openvino/compatibility-and-support/supported-devices.rst, docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/about-openvino/release-notes-openvino/release-policy.rst, docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst, docs/articles_en/get-started/install-openvino/install-openvino-apt.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-brew.rst, docs/articles_en/get-started/install-openvino/install-openvino-conan.rst, docs/articles_en/get-started/install-openvino/install-openvino-conda.rst, docs/articles_en/get-started/install-openvino/install-openvino-pip.rst, docs/articles_en/get-started/install-openvino/install-openvino-vcpkg.rst, docs/articles_en/get-started/install-openvino/install-openvino-yum.rst, docs/articles_en/learn-openvino/openvino-samples/get-started-demos.rst, docs/articles_en/openvino-workflow/torch-compile.rst
Port from https://github.com/openvinotoolkit/openvino/pull/22881
* Created new article about Release Policy,
* Moved System Requirements Article under Release Notes.
* Removed environment variables info from torch.compile article.
Jira: 132590
=> [DOCS] Release Policy + torch.compile updates for 2024.1

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp, src/plugins/intel_gpu/tests/functional/behavior/infer_request.cpp
- Add shape check condition for need_output_update in SyncInferRequest::wait()
- 138395
=> [GPU] Add shape check condition for need_output_update in SyncInferRequest::wait()

src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/unit/test_cases/reshape_gpu_test.cpp
- *Fix to keep reshape data padding of padded input*
- *137553*
=> [GPU] Reshape keeps data padding of padded input

src/plugins/intel_gpu/src/plugin/transformations/bcast_and_pad_zp_buffers.cpp
- *[138263](https://jira.devtools.intel.com/browse/CVS-138263)*
=> [GPU] Added dynamic check in BroadcastAndPadZeroPointBuffers

src/plugins/intel_gpu/include/intel_gpu/primitives/roll.hpp
- *Add conditions to roll operator==.*
- *The conditions affected operations on Windows only.*
- *137794*
=> [GPU] Add conditions to roll operator==

docs/articles_en/openvino-workflow/model-optimization-guide/quantizing-models-post-training.rst
port: https://github.com/openvinotoolkit/openvino/pull/24075
=> [DOCS] language in Quantization article 24.0

docs/articles_en/openvino-workflow/model-optimization-guide/quantizing-models-post-training.rst
port: https://github.com/openvinotoolkit/openvino/pull/24075
=> [DOCS] language in Quantization article 24.1

src/plugins/intel_npu/src/al/include/sync_infer_request.hpp, src/plugins/intel_npu/src/al/src/sync_infer_request.cpp, src/plugins/intel_npu/src/backend/include/zero_executor.hpp, src/plugins/intel_npu/src/backend/include/zero_memory.hpp, src/plugins/intel_npu/src/backend/include/zero_utils.hpp, src/plugins/intel_npu/src/backend/src/zero_executor.cpp, src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/backend/src/zero_memory.cpp, src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp, src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp
- *Use friendly name of the tensor instead of legacy name of it*
- *...*
- *ticket-id*
=> [NPU] Use the friendly name of the tensor instead of the legacy name of it

src/plugins/intel_gpu/src/graph/program_node.cpp
- *Add runtime_skippable to load / store APIs for model-cache*
- *137650*
=> [GPU] Add runtime_skippable to load / store APIs for model-cache

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
=> Remove skip of `RNNSequenceTest` CPU test

.github/workflows/linux_riscv.yml, conan.lock, conanfile.txt, src/bindings/python/CMakeLists.txt, src/bindings/python/src/pyopenvino/frontend/manager.cpp, tools/mo/unit_tests/mock_mo_frontend/mock_mo_python_api/CMakeLists.txt
- Removed WA for cross-compilation case
- It's possible because fix https://github.com/pybind/pybind11/pull/4856 is included to latest released version
=> Updated pybind11 to 2.12.0

README.md, docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device.rst, docs/dev/build_raspbian.md
=> [CPU][ARM] Update ARM documentation in 24.1 release

src/bindings/python/src/openvino/runtime/opset1/ops.py, src/bindings/python/src/openvino/runtime/opset10/ops.py, src/bindings/python/src/openvino/runtime/opset11/ops.py, src/bindings/python/src/openvino/runtime/opset12/ops.py, src/bindings/python/src/openvino/runtime/opset13/ops.py, src/bindings/python/src/openvino/runtime/opset14/ops.py, src/bindings/python/src/openvino/runtime/opset2/ops.py, src/bindings/python/src/openvino/runtime/opset3/ops.py, src/bindings/python/src/openvino/runtime/opset4/ops.py, src/bindings/python/src/openvino/runtime/opset5/ops.py, src/bindings/python/src/openvino/runtime/opset6/ops.py, src/bindings/python/src/openvino/runtime/opset7/ops.py, src/bindings/python/src/openvino/runtime/opset8/ops.py, src/bindings/python/src/openvino/runtime/opset9/ops.py, src/bindings/python/tests/test_graph/test_convolution.py, src/bindings/python/tests/test_graph/test_create_op.py, src/bindings/python/tests/test_graph/test_data_movement.py, src/bindings/python/tests/test_graph/test_detection_output.py, src/bindings/python/tests/test_graph/test_dyn_attributes.py, src/bindings/python/tests/test_graph/test_gather.py, src/bindings/python/tests/test_graph/test_inverse.py, src/bindings/python/tests/test_graph/test_multinomial.py, src/bindings/python/tests/test_graph/test_nms_rotated.py, src/bindings/python/tests/test_graph/test_ops_reshape.py, src/bindings/python/tests/test_graph/test_pooling.py
- *Extended the calls to as_node and as_nodes with the name parameter in all the opsets.*
- *Added tests for the involved operations.*
- #24030 
- part of [CVS-133139](https://jira.devtools.intel.com/browse/CVS-133139)
=> [PyOV] Extend name appending functionality in all opsets

src/common/transformations/src/transformations/symbolic_transformations/reshape_optimizations.cpp
- *ReshapeOptimizations: made dynamic-rank-proof*
- *CVS-138858*
=> ReshapeOptimizations: made dynamic-rank-proof

docs/articles_en/about_openvino.rst, docs/articles_en/about_openvino/release_policy.rst
Added Release Policy article to docs. Updated with changes from the https://github.com/openvinotoolkit/openvino/pull/24145
=> [DOCS] release policy for 2023.3

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
- *Add links to driver installation guides*
- *Add short context about compiler in driver*
- *Update the list of supported properties*
- *Remove invalid limitations*
- *E-119403*
PR on the master branch: https://github.com/openvinotoolkit/openvino/pull/24204
=> Update NPU Device documentation

docs/articles_en/about-openvino/release-notes-openvino/release-policy.rst
Port from https://github.com/openvinotoolkit/openvino/pull/24145
=> [DOCS] release policy adjustment for 2024.0

src/core/reference/include/openvino/reference/scatter_elements_update.hpp, src/core/reference/include/openvino/reference/scatter_nd_update.hpp
- *Reduction has been conflicting in builds, remove using from reference to fix conflict*
- *...*
- *139721*
=> [OP][Reference] Fix conflict in references of ScatterNdUpdate and ScatterElementsUpdate

src/bindings/python/src/openvino/runtime/opset15/__init__.py, src/bindings/python/src/openvino/runtime/opset15/ops.py, src/bindings/python/tests/test_graph/test_ops_scatter_nd_update.py
- *Add ScatterNDUpdate-15 to PyAPI*
- *Parametrize to test both ScatterND versions + add test for reduce attribute*
- *111092*
=> [PyAPI][OP]Add ScatterNDUpdate-15 to PyAPI

docs/articles_en/about-openvino/release-notes-openvino.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Add a known issue

README.md
**Details:** Fix leftovers for README.md
=> [DOCS] Fix leftovers for README.md

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- *Change condition to set reusability of memory in realloc_if_needed*
- *138396*
=> Increase memory reuse

src/frontends/onnx/frontend/src/op/gelu.cpp, src/frontends/onnx/tests/models/gelu_float_none.prototxt, src/frontends/onnx/tests/onnx_import.in.cpp
- Fixed default value of approximate attribute for Gelu
- 135354
=> [ONNX] Fixed default value of approximate attribute for Gelu

src/plugins/intel_gpu/src/graph/network.cpp
- High perf gain was observed in dGPU too.
- 139931
=> [GPU] Apply manual flush for in-order queue too

src/bindings/python/CMakeLists.txt
- Port #24060 to release 2024.1
- *ticket-id*
=> [MERGE] Port 24060 to release 2024.1

docs/articles_en/get-started/install-openvino.rst, docs/articles_en/get-started/install-openvino/install-openvino-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-zypper.rst
@ilya-lavrenov 
Thank you very much for your patience and support.
It took a while to complete the official publication in the science repository of the openSUSE Tumbleweed distribution.
The result is gratifying, as it was a lot of work to make Intel and openSUSE technical policies compatible (it took 3 months of work).
Evidence: 
Upcoming tasks
- Add 15.4. 15.5 and 15.6 (This will be faster)
- Add to default repository in progress.
https://build.opensuse.org/request/show/1168442
https://software.opensuse.org/package/openvino
https://software.opensuse.org/download/package?package=openvino&project=science
=> Support and compatibility with official openSUSE repository

.github/workflows/android_arm64.yml, .github/workflows/job_debian_packages.yml, .github/workflows/linux_riscv.yml, .gitmodules, src/bindings/python/CMakeLists.txt, src/bindings/python/tests/test_graph/test_dyn_attributes.py, src/bindings/python/tests/test_graph/test_manager.py, src/bindings/python/tests/test_graph/test_node_factory.py, src/bindings/python/tests/test_graph/test_pooling.py, src/bindings/python/tests/test_runtime/test_core.py
- https://github.com/openvinotoolkit/openvino/pull/23917
- https://github.com/openvinotoolkit/openvino/pull/24060
- https://github.com/openvinotoolkit/openvino/pull/23816
=> Port openvino-telemetry support in Debian package to 2023.3

cmake/developer_package/packaging/packaging.cmake, cmake/packaging/debian.cmake, cmake/packaging/rpm.cmake
- Added check for conflicting DEB / RPM versions
=> Added check for conflicting DEB / RPM versions

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_fb_io_block_fp16.cl, src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/mat_mul.cpp, src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- Fix syntax error of fully_connected_gpu_fb_io_block_fp16 kernel
- Add related func test
- 139622
=> [GPU] Fix syntax error of fully_connected_gpu_fb_io_block_fp16 kernel

docs/articles_en/get-started/install-openvino.rst, docs/articles_en/get-started/install-openvino/install-openvino-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-zypper.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/24208
=> [DOCS] Support and compatibility with official openSUSE - porting to 24.1

.github/ISSUE_TEMPLATE/build.yml
Just fixes a small typo in the build issue template.
=> Fix typo in build issue template

src/plugins/intel_cpu/tools/commit_slider/utils/common_mode.py, src/plugins/intel_cpu/tools/commit_slider/utils/e2e_preparator.py, src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py
- *item1*
- *...*
- *ticket-id*
=> [Commit slider] AC job improvements

.github/labeler.yml
For https://github.com/openvinotoolkit/openvino/pull/23064
=> Labeler configuration for docker env

src/frontends/common/include/openvino/frontend/manager.hpp, src/inference/CMakeLists.txt, src/inference/dev_api/openvino/runtime/threading/executor_manager.hpp
- *fix warning 4273*
- *CVS-93719*
=> fix warning 4273

src/core/tests/type_prop/interpolate.cpp, src/core/tests/visitors/visitors.hpp, src/frontends/ir/tests/frontend_test_basic.cpp
- Fixed remaining issues with Ubuntu 24.04 support
- CVS-138654
=> Fixes for Ubuntu 24.04

src/plugins/intel_gpu/src/graph/impls/ocl/gemm.cpp
-   Fix transposed shape calculation for static model where the transposed order is less then canonicalized shape
- 140091
=> [GPU] Fix transposed shape calculation for static model 

CMakeLists.txt, cmake/developer_package/OpenVINODeveloperScriptsConfig.cmake
- *item1*
- *...*
- *ticket-id*
=> Use latest Windows SDK by default

docs/sphinx_setup/api/nodejs_api/addon.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Core.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CoreConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/SupportedTypedArray.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/elementTypeString.rst
Updating nodejs_api with new methods. Improving readability of contents.
=> [DOCS] Update nodejs_api with new methods

README.md, docs/dev/index.md
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Fix links to components

.github/workflows/dependency_review.yml
Needed to make the stage required for merge
=> Run dependency review workflow on merge group event

tests/layer_tests/tensorflow_tests/test_tf_AddN.py, tests/layer_tests/tensorflow_tests/test_tf_DynamicPartition.py, tests/layer_tests/tensorflow_tests/test_tf_Eye.py, tests/layer_tests/tensorflow_tests/test_tf_IsFinite.py, tests/layer_tests/tensorflow_tests/test_tf_IsInf.py, tests/layer_tests/tensorflow_tests/test_tf_IsNan.py, tests/layer_tests/tensorflow_tests/test_tf_L2Loss.py, tests/layer_tests/tensorflow_tests/test_tf_ParallelDynamicStitch.py, tests/layer_tests/tensorflow_tests/test_tf_SegmentSum.py, tests/layer_tests/tensorflow_tests/test_tf_Select.py, tests/layer_tests/tensorflow_tests/test_tf_SelectV2.py, tests/layer_tests/tensorflow_tests/test_tf_UnaryOps.py, tests/layer_tests/tensorflow_tests/test_tf_Unique.py, tests/layer_tests/tensorflow_tests/test_tf_UnsortedSegmentSum.py
**Details:** Currently they are switched on for legacy frontend that is incorrect.
=> [TF FE] Get back tests switched off by mistake

docs/sphinx_setup/api/nodejs_api/addon.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Core.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CoreConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/SupportedTypedArray.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/elementTypeString.rst
Updating nodejs_api with new methods. Improving readability of contents.
Porting: https://github.com/openvinotoolkit/openvino/pull/24303
=> [DOCS] Update nodejs_api with new methods - port to master

src/core/include/openvino/op/roi_align.hpp
- *fix ROIAlign op Coverity issue*
- *139809*
=> [Op] fix ROIAlign op Coverity issue

src/inference/src/dev/core_impl.cpp, src/plugins/proxy/tests/proxy_tests.cpp
- Port PR2418 to release 2023.3
- *...*
- *CVS-132745*
=> Port PR 24018 to release/2023/3

docs/sphinx_setup/_static/benchmarks_files/OVMS-benchmark-data.csv
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Fixed undefined units

src/core/reference/include/openvino/reference/avg_pool.hpp, src/core/reference/include/openvino/reference/max_pool.hpp
- Used 3D kernel for 1D and 2D cases.
- CVS-119226
=> [Core] Optimize MaxPool reference implementation binary size 

src/bindings/python/src/openvino/utils.py
- *item1*
- *...*
- *ticket-id*
=> [PyOV] remove deprecated add_openvino_libs

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- *Check the first dimension each time for any layout*
- *Get batch size only when inputs/outputs of the compiled model are equal to 1*
- *E#103116*
=> Check the first dimension each time for any layout

docs/install_guides/installing-model-dev-tools.md, docs/install_guides/installing-openvino-conda.md, docs/install_guides/installing-openvino-from-archive-linux.md, docs/install_guides/installing-openvino-from-archive-macos.md, docs/install_guides/installing-openvino-from-archive-windows.md, docs/install_guides/installing-openvino-pip.md, docs/install_guides/installing-openvino-raspbian.md, docs/install_guides/pypi-openvino-dev.md
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Change links to install lts

src/plugins/intel_npu/src/plugin/include/metrics.hpp
- *Update caching properties with batch mode*
- *ticket-id*
=> [NPU] Update caching properties with batch mode

cmake/developer_package/OpenVINODeveloperScriptsConfig.cmake, docs/Doxyfile.config, src/cmake/ov_parallel.cmake, src/core/template_extension/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
=> Dropped old macro usage

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp, src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp, src/plugins/intel_gpu/include/intel_gpu/runtime/memory_pool.hpp, src/plugins/intel_gpu/src/graph/network.cpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/src/runtime/debug_configuration.cpp, src/plugins/intel_gpu/src/runtime/memory_pool.cpp
- *Set iterations to dump runtime memory pool*
- *Set csv file path to dump runtime memory pool*
- *Update runtime memory pool dump data*
- *138484*
=> [GPU] implement additional debug features to dump runtime memory pool

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp, src/plugins/intel_gpu/tests/unit/test_cases/crop_gpu_test.cpp
_For Stable Diffusion Unet performance improvement,_
- _Support implicit crop for all axis in simple format_
- _Enable Eltwise fusion in fs_byx_fsv32 format for special pattern.(Actually Eltwise run simple format)_
- *137950*
=> [GPU] Support implicit crop in simple format.

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- *Let quantize fusion valid in dynamic model when executing model*
- *134678*
=> [GPU] Enable fakequantize fusion in dynamic model

docs/sphinx_setup/api/nodejs_api/addon.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Core.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CoreConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/SupportedTypedArray.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/elementTypeString.rst
Updating docs with partial changes from:
https://github.com/openvinotoolkit/openvino/pull/24441
=> [DOCS] Update addon in nodejs_api for 2024.1

.github/components.yml
- Updating revalidation for MO, ONNX FE and Template plugin
Ticket: _CVS-129324_
=> update dependencies for MO, ONNX and TEMPLATE

src/plugins/intel_npu/src/al/src/config/config.cpp, src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp, src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- *Fix Coverity issues*
- *CVS#141058*
=> [NPU] Fix coverity issues

src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bfyx_ref.cpp, src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/matmul.cpp, src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- *Add i32 output type for FC*
- *100911*
=> [GPU] Add i32 output type for FC

.github/workflows/windows.yml
- Based on this issue: https://github.com/openvinotoolkit/openvino/issues/24015
=> [OV JS] Add test of installation openvino-node package

src/bindings/python/src/pyopenvino/graph/node_output.cpp, src/bindings/python/tests/test_runtime/test_output_const_node.py, src/bindings/python/tests/test_runtime/test_output_node.py
- Add `set_names`/`add_names` to Output
- CVS-141246
=> [PyOV] add set/add_names to Output

.github/workflows/build_doc.yml, docs/requirements.txt, docs/sphinx_setup/conf.py
- *item1*
- *...*
-  CVS-104198
=> Docs long build fix

src/plugins/intel_npu/src/al/include/intel_npu/al/config/compiler.hpp, src/plugins/intel_npu/src/al/include/intel_npu/al/config/config.hpp, src/plugins/intel_npu/src/al/src/config/compiler.cpp, src/plugins/intel_npu/src/al/src/config/config.cpp, src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp, src/plugins/intel_npu/src/plugin/include/metrics.hpp, src/plugins/intel_npu/src/plugin/src/compiled_model.cpp, src/plugins/intel_npu/src/plugin/src/plugin.cpp
- implementing EXECUTION_MODE_HINT property for intel-npu plugin
- *...*
- EISW-120263
- EISW-112993
- https://jira.devtools.intel.com/browse/CVS-131808
=> [intel-npu] implementing EXECUTION_MODE_HINT property

docs/articles_en/get-started/install-openvino/install-openvino-zypper.rst
@tadamczx and @ilya-lavrenov  It took a while but I delivered what was promised, openVINO at the official openSUSE factory. It took more than 6 months of work to get approval from the community...
=> OpenVINO at the openSUSE Factory - cabelo@opensuse.org

src/plugins/intel_npu/src/al/include/npu.hpp, src/plugins/intel_npu/src/al/src/npu.cpp, src/plugins/intel_npu/src/backend/include/zero_device.hpp, src/plugins/intel_npu/src/backend/src/zero_device.cpp, src/plugins/intel_npu/src/plugin/include/metrics.hpp, src/plugins/intel_npu/src/plugin/src/metrics.cpp, src/plugins/intel_npu/src/plugin/src/plugin.cpp
- Implementing DEVICE_TYPE property for intel-npu plugin
- *...*
- EISW-112992
=> [intel-npu] Implementing DEVICE_TYPE property

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/reorder.cpp, src/plugins/intel_gpu/src/graph/include/primitive_inst.h, src/plugins/intel_gpu/src/graph/include/reorder_inst.h, src/plugins/intel_gpu/src/graph/network.cpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/src/graph/reorder.cpp, src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_redundant_reorder_at_runtime.cpp, src/plugins/intel_gpu/tests/unit/test_cases/reorder_gpu_test.cpp
- * Set needs_completion_event when current node has runtime skippable users in primitive_inst ctor*
- * Add marking runtime skippable for reorder in build time*
- *CVS-135257*
=> [GPU] Fix execution order corrupted issue on dGPU

src/core/reference/include/openvino/reference/add.hpp, src/core/reference/include/openvino/reference/and.hpp, src/core/reference/include/openvino/reference/bitwise_and.hpp, src/core/reference/include/openvino/reference/bitwise_or.hpp, src/core/reference/include/openvino/reference/bitwise_xor.hpp, src/core/reference/include/openvino/reference/divide.hpp, src/core/reference/include/openvino/reference/or.hpp, src/core/reference/include/openvino/reference/scatter_nd_update.hpp, src/core/reference/include/openvino/reference/select.hpp, src/core/reference/include/openvino/reference/squared_difference.hpp, src/core/reference/include/openvino/reference/subtract.hpp, src/core/tests/visitors/visitors.hpp
- Custom function used in binary element wise operators to reduce bin size (around 130k).
- [CVS-138266](https://jira.devtools.intel.com/browse/CVS-138266)
=> [core] Use custom functions in reference binary ops impl

.github/workflows/build_doc.yml, docs/documentation_build_instructions.md, docs/requirements.txt
- *item1*
- *...*
- *ticket-id*
=> [DOCS] fix openvino_custon_sphinx_sitemap installation

src/common/transformations/include/transformations/transpose_sinking/ts_base.hpp, src/common/transformations/include/transformations/transpose_sinking/ts_utils.hpp, src/common/transformations/src/transformations/transpose_sinking/ts_base.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_binary.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_concat.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_cumsum.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_data_movement.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_gather.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_interpolate.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_reduction.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_shape_of.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_slice.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_split.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_squeeze.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_tile.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_unary.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_unsqueeze.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp, src/common/transformations/tests/transpose_sinking/ts_binary_test.cpp, src/common/transformations/tests/transpose_sinking/ts_common_test.cpp, src/common/transformations/tests/transpose_sinking/ts_unary_test.cpp
- check constant is not empty
- CVS-138875
=> [transpose sinking] fix SIGSEGV TSDataMovement

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp, src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp, src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp, src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp
- *[CPU] [ARM] JIT Elu*
- *CVS-139593*
=> [CPU] [ARM] JIT Elu

src/plugins/intel_gpu/thirdparty/CMakeLists.txt
- GPU plugin binary size reduction
=> [GPU] Reduce binary size by disabling unused isa

src/frontends/pytorch/src/op/all.cpp, src/frontends/pytorch/src/op/any.cpp, src/frontends/pytorch/src/op/upsample.cpp, src/frontends/pytorch/src/op_table.cpp, tests/layer_tests/pytorch_tests/test_all.py, tests/layer_tests/pytorch_tests/test_any.py, tests/layer_tests/pytorch_tests/test_isfinite.py, tests/layer_tests/pytorch_tests/test_isinf.py, tests/layer_tests/pytorch_tests/test_isnan.py
- *Support torch.any and torch.all on both FX and TS side*
- *Support aten::isfinite, aten::isinf and aten::isnan*
- *ticket-id*
=> [PT FE] Support torch.any and torch.all on both FX and TS side

src/plugins/intel_cpu/tools/commit_slider/utils/cfg_manager.py, src/plugins/intel_cpu/tools/commit_slider/utils/cfg_samples/bm_perf_for_CI.json
- *item1*
- *...*
- *ticket-id*
=> [Commit slider] bm template extended

src/plugins/intel_gpu/src/graph/impls/cpu/non_max_suppression.cpp
- In case of multiple images and iterations, the calculation of NMS output shape was incorrect
- 136451
=> [GPU] Fix NMS cpu impl

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp, src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h, src/plugins/intel_gpu/src/runtime/ocl/ocl_common.hpp, src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp
- Improved CL_OUT_OF_RESOURCES exception handling to avoid force exit when device is lost
=> [GPU] Avoid force exit for out of resource exception if device is lost

src/bindings/python/src/openvino/frontend/pytorch/patch_model.py, src/frontends/pytorch/src/op/linear.cpp, tests/layer_tests/py_frontend_tests/test_torch_frontend.py
- *Add patch function to make 16bit models traceable. This reduce memory consumption and time spent during conversion of models that are natively saved in 16bit precision*
- *CVS-136828*
=> [PT FE] Support converting 16bit models by patching

src/plugins/auto/CMakeLists.txt
- *fix compilation issue on ubuntu24*
- *141313*
=> fix compilation issue on ubuntu24

docs/sphinx_setup/_static/css/custom.css
=> Docs update main page for master

docs/sphinx_setup/_static/css/custom.css
- *item1*
- *...*
- *ticket-id*
=> [Docs] Button styling

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp, src/plugins/intel_gpu/src/plugin/common_utils.cpp, src/plugins/intel_gpu/src/plugin/variable_state.cpp, src/plugins/intel_gpu/tests/functional/behavior/infer_request.cpp
- In set_state of gpu plugin, the src Tensor can have padding, which has not handled by set_state 
- Fixed set_state to handle src Tensor's padding properly 
- 140418
=> [GPU] Fix set_state to handle original Tensor's padding 

src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.cpp, src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_blocking.hpp
- *Extract BrgemmCopyB from M blocking if there are no KN blocking loops*
- *Tests will be added after #24152 merge*
- *CVS-140751*
=> [Snippets] Extract BrgemmCopyB from M blocking if there are no KN blocking

src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
- *WA for pass::Manager bug*
- temporary workarounds CVS-141764
=> WA for pass::Manager bug

src/plugins/template/tests/functional/op_reference/base_reference_test.cpp, src/plugins/template/tests/functional/op_reference/memory.cpp, src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
- *[CVS-138757](https://jira.devtools.intel.com/browse/CVS-138757)*
=> [template] Fix debug build for linux

src/plugins/intel_cpu/src/emitters/snippets/jit_snippets_call_args.cpp, src/plugins/intel_cpu/src/emitters/snippets/jit_snippets_call_args.hpp
=> [Snippets] Ubuntu 24.0 build fix

src/plugins/intel_cpu/src/nodes/executors/acl/acl_pooling.cpp, src/plugins/intel_cpu/src/nodes/pooling.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/pooling.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/pooling.hpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/pooling.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/pooling.cpp
PR has to be merge after https://github.com/openvinotoolkit/openvino/pull/24491 since ACL 24.04 contains needed fix for Pooling.
CVS-130054
=> [CPU][ARM] Enable NHWC Pooling

src/bindings/c/docs/api_overview.md, src/bindings/c/include/openvino/c/ov_common.h, src/bindings/c/src/common.h, src/bindings/c/src/ov_node.cpp, src/bindings/c/src/ov_tensor.cpp
- *item1*
- *...*
- *ticket-id*
=> [C API] fix element type mismatch issue

src/plugins/intel_npu/src/backend/include/zero_backend.hpp, src/plugins/intel_npu/src/backend/src/zero_backend.cpp, src/plugins/intel_npu/src/backend/src/zero_device.cpp, src/plugins/intel_npu/src/backend/src/zero_executor.cpp, src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/backend/src/zero_init.cpp, src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
[NPU] Add logger in src/plugins/intel_npu/src/backend/ to Increase verbosity of errors returned
Improve log and debug message
- src/plugins/intel_npu/src/backend/include/zero_backend.hpp
- src/plugins/intel_npu/src/backend/src/zero_backend.cpp
- src/plugins/intel_npu/src/backend/src/zero_device.cpp
- src/plugins/intel_npu/src/backend/src/zero_executor.cpp
- src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- src/plugins/intel_npu/src/backend/src/zero_init.cpp
- src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
- *ticket-id*
=> [NPU] Add logger in src/plugins/intel_npu/src/backend/

src/bindings/python/src/openvino/frontend/pytorch/fx_decoder.py, src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend.py, src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/compile.py, src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/execute.py, src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/op_support.py, src/frontends/pytorch/src/op/expand.cpp, src/frontends/pytorch/src/op/reshape.cpp, src/frontends/pytorch/src/op/slice.cpp, src/frontends/pytorch/src/op_table.cpp, tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py, tests/layer_tests/pytorch_tests/test_expand.py, tests/layer_tests/pytorch_tests/test_reshape.py
- Enabling dynamic shapes with aot_autograd
- CVS-139182
=> Torchfx dynamic shapes initial (CVS-139182)

src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/common.hpp, src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/executor_pa.cpp, src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/transpose_kernel.hpp
- *Fix segment fault for PagedAttention when head size is multiple of 16*
- *...*
- *ticket-id*
=> [CPU] Fix segment fault for PagedAttention when head size is multiple of 16

docs/sphinx_setup/_static/css/custom.css, docs/sphinx_setup/_static/js/modern.js, docs/sphinx_setup/conf.py
=> [Docs] Page styling

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/utils.hpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- Apply dynamic padding for onednn gemm
- Update memory descriptor to handle the padded dims and strides
- 140516
=> [GPU] Apply dynamic padding for onednn gemm

src/plugins/intel_gpu/tests/unit/CMakeLists.txt
- The same https://github.com/openvinotoolkit/openvino/pull/24628 for GPU Unit tests
=> Added  -Wno-stringop-overflow for GPU unit tests as well

src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- Add i8 data type to list of supported dequantization types for woq
- *CVS-131044*
=> [GPU] Allow signed int8 for WOQ

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/permute_f_y_axes.cl
- fix mixing IN and OUT vec type
- 140728
=> [GPU] fix for mixing types in permute_f_y

src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp
Convolution which has u8 AvgPool layer as input0 is handled as quantized in transformation and it has zp constants in transformed graph. But gpu plugin has changed AvgPool output data type to fp32 due to accuracy issue. The change causes convolution ocl impl doesn't recognize quantized convolution.
- Add Workaround in convolution ocl impl for fp32 output hack of avgpool when u8/i8 input
- 141396
=> [GPU] Workaround in convolution ocl impl for fp32 output hack of avgpool when u8/i8 input

docs/dev/pypi_publish/pre-release-note.md, docs/dev/pypi_publish/pypi-openvino-dev.md, docs/dev/pypi_publish/pypi-openvino-rt.md
- *item1*
- *...*
- *ticket-id*
=>  [DOCS]  Remove pre-release note

tests/layer_tests/pytorch_tests/test_expand.py
=> Unit test for dynamic expand fixed

cmake/developer_package/coverage/coverage.cmake, cmake/developer_package/options.cmake, cmake/extra_modules.cmake, docs/articles_en/assets/snippets/template_pattern_transformation.hpp, src/common/transformations/include/transformations/common_optimizations/nop_elimination.hpp, src/common/transformations/include/transformations/op_conversions/convert_avgpool_downgrade.hpp
- *item1*
- *...*
- *ticket-id*
=> Removed deprecated cmake vars

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- Coverity Fix as a line of the code is not reachable 
- Remove the line of dead code and add different log message for 3 different possible return 
- E-125476
=> [NPU] Fix coverity issue

docs/dev/build_raspbian.md
Add a note about swap according to the comment https://github.com/openvinotoolkit/openvino/issues/24445#issuecomment-2116366405
=> [CPU][ARM][DOC] Add swap note into Raspberry build procedure

docs/dev/build_linux.md, docs/dev/debug_capabilities.md
- *Fix broken url link*
- *Remove unnecessary step in Linux build env*
- *N/A*
=> [DOCS] Fix broken url link and remove unnecessary step in Linux build env

src/common/transformations/src/transformations/smart_reshape/matmul_sr.cpp, src/inference/tests/functional/matmul_sr_tests.cpp
Handled a case when "Other" input to MatMul is 1D
- *CVS-141638*
=> Fix MatMul SmartReshape in case of 1D input

src/common/transformations/include/transformations/sdpa_to_paged_attention/prev_sequence_length_pattern.hpp, src/common/transformations/src/transformations/sdpa_to_paged_attention/prev_sequence_length_pattern.cpp, src/common/transformations/src/transformations/sdpa_to_paged_attention/total_sequence_length_pattern.cpp
Reapplied #24690 to the release branch.
=> PagedAttention Transformation: Rank alignment for replacements (#24690)

src/inference/src/dev/plugin.cpp
- *Exception handling: exception message logging*
- *NotSupported exception can have message, let's display it. For example this ticket will be clear in this case: CVS-139934*
- *Part of CVS-142409*
=> [CPU] Exception handling: exception message logging

.github/actions/cache/dist/save-only/index.js, .github/actions/cache/dist/save/index.js, .github/actions/cache/src/saveImpl.js, .github/workflows/windows.yml
- Should resolve `Error: ENOENT: no such file or directory, mkdir 'C:\mount\caches\ccache\windows2022_x86_64\releases\2024\2'` found on the release branch.
- *142372*
=> [CI] [GHA] Create cache directory recursively

src/frontends/pytorch/src/transforms/dict_resolver.cpp, tests/layer_tests/ovc_python_api_tests/test_pytorch.py
- *item1*
- *...*
- *ticket-id*
=> [PT FE]: fix segfault when resolving nested dict as model input

tests/layer_tests/pytorch_tests/test_expand.py
- Ported https://github.com/openvinotoolkit/openvino/pull/24684
=> Unit test for dynamic expand fixed (#24684)

src/bindings/python/tests/test_graph/test_op.py
- During investigation I found out that it hangs in AUTO plugin but with directly specified CPU plugin passes.
- CVS-141744
- https://github.com/openvinotoolkit/openvino/pull/24706
- *ticket-id*
=> [PyOV] Hot-fix for hanging test (#24706)

src/inference/src/dev/threading/cpu_streams_executor.cpp, tests/stress_tests/common/ie_pipelines/pipelines.cpp, tests/stress_tests/common/ie_pipelines/pipelines.h, tests/stress_tests/common/infer_api/infer_api.cpp, tests/stress_tests/common/infer_api/infer_api.h, tests/stress_tests/memleaks_tests/tests.cpp, tests/stress_tests/unittests/tests.cpp, tests/stress_tests/unittests/tests_pipelines/tests_pipelines.cpp, tests/stress_tests/unittests/tests_pipelines/tests_pipelines.h
- *port PR #24562 to release 2023.3*
- *add support for InferAPI1 and api_version*
- *[issue-24509](https://github.com/openvinotoolkit/openvino/issues/24509)*
=>  port PR 24562 to  release/2023/3

docs/dev/ci/github_actions/overview.md, docs/dev/ci/github_actions/runners.md
=> [CI] [GHA] [DOCS] Add section on GPU

src/common/transformations/src/transformations/smart_reshape/matmul_sr.cpp, src/inference/tests/functional/matmul_sr_tests.cpp
Porting https://github.com/openvinotoolkit/openvino/pull/24701
Handled a case when "Other" input to MatMul is 1D
- *CVS-141638*
=> Fix MatMul SmartReshape in case of 1D input (#24701)

src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
=> [TEST] Tensor comparation fix

src/plugins/intel_gpu/src/graph/impls/common/loop.cpp, src/plugins/intel_gpu/src/graph/include/loop_inst.h, src/plugins/intel_gpu/tests/unit/test_cases/loop_gpu_test.cpp
- *Update loop inst ids instead of getting from prim*
- *137277*
=> [GPU] Update loop inst ids instead of getting from prim

src/plugins/intel_gpu/src/graph/reshape.cpp, src/plugins/intel_gpu/tests/unit/test_cases/reshape_gpu_test.cpp
- *Update reshape's output padding by merging current padding and input's padding*
- *137277*
=> [GPU] Fix reshpae output padding

src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/rope_fusion.cpp, src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/rotary_pos_emb.cpp
- *Extend Qwen Rope Fusion*
- PR to master branch https://github.com/openvinotoolkit/openvino/pull/24750
- *CVS-142523*
=> [CPU]Fix qwen rope fusion with special_zero

src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp, src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/rotary_pos_emb.cpp
- *Extend Qwen Rope Fusion*
- *PR to 2024.2 release https://github.com/openvinotoolkit/openvino/pull/24727*
- *Migrate from original PR https://github.com/openvinotoolkit/openvino/pull/24725*
- *CVS-142523*
=> [CPU]Fix Qwen Rope Fusion

src/frontends/tensorflow/docs/supported_ops.md
**Details:** Mark new operations for latest release and unmark old ones.
=> [DOC][TF FE] Mark new operations for latest release

src/frontends/tensorflow/docs/supported_ops.md
**Details:** Mark new operations for latest release and unmark old ones.
Port of https://github.com/openvinotoolkit/openvino/pull/24759
=> [DOC][TF FE] Mark new operations for 2024.2 release (#24759)

src/common/snippets/src/pass/gn_decomposition.cpp, src/common/snippets/src/pass/gn_tokenization.cpp, src/common/snippets/tests/include/pass/gn_decomposition.hpp, src/common/snippets/tests/include/pass/gn_tokenization.hpp, src/common/snippets/tests/src/lowering_utils.cpp, src/common/snippets/tests/src/pass/gn_decomposition.cpp, src/common/snippets/tests/src/pass/gn_tokenization.cpp, src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/group_normalization.cpp, src/tests/functional/plugin/shared/include/snippets/group_normalization.hpp, src/tests/functional/plugin/shared/src/snippets/group_normalization.cpp, src/tests/ov_helpers/ov_snippets_models/include/subgraph_group_normalization.hpp, src/tests/ov_helpers/ov_snippets_models/src/subgraph_group_normalization.cpp
- *GroupNormalization decomposition test*
- *GroupNormalization tokenization test*
- *GroupNormalization snippets func test*
- *[CVS-136159](https://jira.devtools.intel.com/browse/CVS-136159)*
- *[CVS-137359](https://jira.devtools.intel.com/browse/CVS-137359)*
=> GN decomposition/tokenization test and snippets func test

src/core/include/openvino/op/scaled_dot_product_attention.hpp, src/plugins/intel_gpu/include/intel_gpu/op/indirect_sdpa.hpp, src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp, src/plugins/intel_gpu/include/intel_gpu/primitives/scaled_dot_product_attention.hpp, src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp, src/plugins/intel_gpu/src/graph/include/scaled_dot_product_attention_inst.h, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_ref.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_ref.cpp, src/plugins/intel_gpu/src/plugin/ops/scaled_dot_product_attention.cpp, src/plugins/intel_gpu/src/plugin/plugin.cpp, src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.cpp, src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.hpp, src/plugins/intel_gpu/src/plugin/transformations/op/indirect_sdpa.cpp, src/plugins/intel_gpu/src/plugin/transformations/op/sdpa.cpp, src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.cpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp, src/plugins/intel_gpu/src/runtime/debug_configuration.cpp, src/plugins/intel_gpu/src/runtime/execution_config.cpp, src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp
- Enabled SDPA by default
- Added indirect inputs support (copy of https://github.com/openvinotoolkit/openvino/pull/24665)
- Updated SDPA decomposition rule to cover only well-checked cases
- Updated functional tests accordingly
=> [GPU] Enable SDPA by default

src/core/reference/include/openvino/reference/roi_align.hpp
- Fix coverity 1544154
- CVS-140934
=> Fix coverity 1544154

src/common/low_precision_transformations/include/low_precision/layer_transformation.hpp, src/common/low_precision_transformations/src/eliminate_fake_quantize.cpp, src/common/low_precision_transformations/tests/eliminate_fake_quantize_transformation.cpp, src/tests/ov_helpers/ov_lpt_models/src/fuse_fake_quantize.cpp
- *[LPT] EliminateFakeQuantizeTransformation: bf16 support*
- *CVS-138910*
=> [LPT] EliminateFakeQuantizeTransformation: bf16 support

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp, src/plugins/intel_gpu/src/runtime/execution_config.cpp, src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp
This PR is a copy of https://github.com/openvinotoolkit/openvino/pull/24757 from release branch, it includes:
- Enabled SDPA by default
- Updated SDPA decomposition rule to cover only well-checked cases
- Updated functional tests accordingly
=> [GPU] Enable SDPA optimization by default

src/tests/functional/plugin/conformance/subgraphs_dumper/src/matchers/single_op/single_op.cpp, src/tests/functional/plugin/conformance/subgraphs_dumper/src/matchers/subgraph/repeat_pattern.cpp
- *item1*
- *...*
- *CVS-134419*
=> [ov_subgraphs_dumper_tests] Fix memory leaks

src/plugins/intel_cpu/src/graph.cpp, src/plugins/intel_cpu/src/node.cpp, src/plugins/intel_cpu/src/node.h
=> [CPU] Nodes errors handling moved to graph

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add `Unable to fetch some archives` to errors to look for file

src/common/util/include/openvino/util/file_util.hpp, src/common/util/src/file_util.cpp, src/inference/dev_api/file_utils.h, src/inference/src/dev/core_impl.cpp, src/inference/src/file_utils.cpp, src/inference/src/ie_cache_manager.hpp, src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp, src/tests/test_utils/common_test_utils/include/common_test_utils/file_utils.hpp
- Port to 202303 ttps://github.com/openvinotoolkit/openvino/pull/24606
- *...*
- *ticket-id*
=> Port 24606 to release 202303

src/bindings/js/node/lib/addon.ts
- Add method descriptions to TS for Core
- *141290*
=> [OV JS] Add method descriptions for Core

src/plugins/intel_gpu/include/intel_gpu/op/indirect_sdpa.hpp, src/plugins/intel_gpu/include/intel_gpu/op/sdpa.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp, src/plugins/intel_gpu/src/graph/scaled_dot_product_attention.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.cpp, src/plugins/intel_gpu/src/plugin/transformations/op/indirect_sdpa.cpp, src/plugins/intel_gpu/src/plugin/transformations/op/sdpa.cpp, src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.cpp, src/plugins/intel_gpu/src/plugin/transformations/unsqueeze_broadcast_reshape_sdpa_fusion.cpp, src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp, src/plugins/intel_gpu/tests/unit/transformations/indirect_kv_cache_test.cpp, src/plugins/intel_gpu/tests/unit/transformations/transpose_sdpa_fusion_test.cpp, src/plugins/intel_gpu/tests/unit/transformations/unsqueeze_broadcast_reshape_sdpa_fusion_test.cpp
- Change the default softmax accumulator type from FP16 to FP32 (this doesn't affect performance, as well as accuracy at first glance; however, let's stick to higher precision here)
- Applied review comments from PR https://github.com/openvinotoolkit/openvino/pull/24466 
- Minor internal operations refactoring (SDPA and IndirectSDPA)
- Add new tests for GQA optimization and for indirect inputs
=> [GPU] SDPA minor improvements

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/rms_gpu_bfyx_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_base.h, src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_bfyx_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_bfyx_opt.h, src/plugins/intel_gpu/tests/unit/test_cases/rms_gpu_test.cpp
- Optimize RMS kernel by subgroup block IO
- Compute maximum possible LWS and the number of data in subgroups
- Add test cases which covers leftover handling and unaligned data shape
- 141845
=> [GPU] Optimize RMS kernel

src/frontends/tensorflow_lite/src/sparsity_info.cpp
- Added an implementation details for sparse-tensors reading
- N/A
=> [TFLite] Added implementation details

.github/workflows/windows.yml, .github/workflows/windows_conditional_compilation.yml
- Pinned MSVC toolset version
- removed hardcoded jobs count
- *ticket-id*
=> [GHA] Pinned MSVC toolset version

.github/workflows/windows_conditional_compilation.yml
Without thread limitation win-cc pipeline fails with run out of memory error:
https://github.com/openvinotoolkit/openvino/actions/runs/9384908136
set 16 threads
- *ticket-id*
=> [GHA] Win-CC decrease build jobs

.github/workflows/windows_conditional_compilation.yml, src/plugins/intel_cpu/src/node.cpp
Ported from master:
- https://github.com/openvinotoolkit/openvino/pull/24718
- https://github.com/openvinotoolkit/openvino/pull/24849
- *ticket-id*
=> [MERGE] Port 24718 and 24849

src/plugins/intel_gpu/src/graph/loop.cpp, src/plugins/intel_gpu/tests/unit/test_cases/loop_gpu_test.cpp
- Handle the case where from_mem is null at the first iteration 
- 141652
=> [GPU] Fix Loop to cover the case where memory is null at the first iteration

docs/sphinx_setup/api/nodejs_api/addon.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Core.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CoreConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst
Adding descriptions of methods to Node.js API.
=> [DOCS] Updating Nodejs API with descriptions

tests/model_hub_tests/pytorch/test_hf_transformers.py
- *item1*
- *...*
- *ticket-id*
=> Change opt-125m-gptq model

src/plugins/intel_cpu/src/nodes/unique.cpp
- *Optimize  unique using HashMap when sorted=false*
- *...*
- *ticket-id*
=> [CPU] Optimize the unique operator

src/common/snippets/src/pass/mha_tokenization.cpp, src/common/snippets/tests/src/pass/mha_tokenization.cpp, src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp, src/tests/ov_helpers/ov_snippets_models/include/subgraph_mha.hpp, src/tests/ov_helpers/ov_snippets_models/src/subgraph_mha.cpp
- *Updated `MHATokenization` pass to support dynamic nodes tokenization*
- *Added MHATokenization unit tests*
- *Disabled dynamic MHA tokenization in CPU Plugin*
- *123329*
=>  [Snippets] Added dynamism support to MHA Tokenization pass

src/common/transformations/src/transformations/common_optimizations/shared_ops_optimization.cpp
- *Relaxes SharedOpOptimization restrictions on Constant comparison*
- *@vladimir-paramuzov*
=> Relaxes SharedOpOptimization restrictions

.github/workflows/linux.yml
These tests require more memory
=> Switch ONNX model tests and TF nightly tests to a bigger runner

src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp, src/common/transformations/src/transformations/symbolic_transformations/symbol_optimization.cpp, src/common/transformations/tests/symbolic_transformations/label_optimization.cpp
Reverts openvinotoolkit/openvino#24845
Issue CVS-143648
=> Revert "More accurate shape of optimization"

src/common/low_precision_transformations/src/network_helper.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/convolution_transformation.cpp, src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/convolution_transformation.cpp
- *Quaintization to point support*
- Tests: wip
- *CVS-139557*
=> [LPT] Quantization to point support

docs/articles_en/assets/snippets/multi_threading.py, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device/performance-hint-and-thread-scheduling.rst
Fixing reference and formatting. Proofreading.
=> [DOCS] Performance hint and thread scheduling update

docs/CMakeLists.txt, docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/custom-class-template.rst, docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/custom-module-template.rst, docs/scripts/install_appropriate_openvino_version.py, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] OpenVINO Python API docs build fix

src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
- *Gather -> ShapeOf simplification*
- *CVS-143648*
=> Gather -> ShapeOf simplification

docs/articles_en/documentation/openvino_legacy_features/mo_ovc_transition.rst
Port from https://github.com/openvinotoolkit/openvino/pull/24624
=> [DOCS] Direct to Python tab in the ovc transition guide for 23.3

.github/workflows/job_python_unit_tests.yml, docs/articles_en/assets/snippets/__init__.py, docs/articles_en/assets/snippets/main.py, docs/articles_en/assets/snippets/utils.py, docs/snippets/main.py
- Snippets were moved in this PR https://github.com/openvinotoolkit/openvino/pull/24510 and didn't test anymore.
- Updated the path to them in GA config file
- Return back files needed for testing.
- *ticket-id*
=> Update path to python snippets

README.md
**Details:** Install latest one instead of cached version
=> [README] Install latest and greatest version

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- Remove feature depth limitation in is_node_for_onednn() for deconvolution
- 136045
=> [GPU] Reduce limitation for choosing onednn deconvolution

samples/js/node/package-lock.json, src/bindings/js/node/package-lock.json
- Update js dependencies to fix npm audit warnings
Port of: https://github.com/openvinotoolkit/openvino/pull/24957
=> [OV JS] Update js deps to fix audit, LTS port of #24957

samples/js/node/package-lock.json, src/bindings/js/node/package-lock.json
- Update js dependencies to fix npm audit warnings
Port of: https://github.com/openvinotoolkit/openvino/pull/24957
=> [OV JS] Update js deps to fix audit, port of #24957

samples/js/node/package-lock.json, src/bindings/js/node/package-lock.json
- Update js dependencies to fix `npm audit` warnings
=> [OV JS] Update js deps to fix audit

docs/sphinx_setup/_static/css/custom.css, docs/sphinx_setup/_static/html/footer.html
Porting: https://github.com/openvinotoolkit/openvino/pull/24708
=> [DOCS] Updating footer file - port to 2024.2

docs/openvino_sphinx_theme/openvino_sphinx_theme/static/css/openvino_sphinx_theme.css, docs/sphinx_setup/_static/css/custom.css
Port from https://github.com/openvinotoolkit/openvino/pull/24884
=> [DOCS] fix back to top button for 24.2

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_elements_ref.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_elements_kernel_ref.cpp, src/plugins/intel_gpu/tests/functional/single_layer_tests/gather_elements_padding_input.cpp
- Use INPUT0_GET_INDEX macro in cl kernel
- 142805
=> [GPU] Fix gather_elements ref kernel for padding input

docs/articles_en/assets/snippets/ov_patterns.cpp
Fixing failing snippets in `Transformation Patterns with OpenVINO API` article.
=> [DOCS] Fixing Transformation Patterns snippets

docs/articles_en/openvino-workflow/deployment-locally.rst, docs/articles_en/openvino-workflow/deployment-locally/integrate-openvino-with-ubuntu-snap.rst
port: https://github.com/openvinotoolkit/openvino/pull/24903
=> DOCS-snap-deployment-port-24.2

docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Update system-requirements.rst

docs/articles_en/documentation/openvino-extensibility/transformation-api/patterns-python-api.rst
Adding tabs to the Transformation Patterns article.
=> [DOCS] Adding tabs to the Transformation Patterns article for master

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/sphinx_setup/_static/css/custom.css
port: https://github.com/openvinotoolkit/openvino/pull/24986 & https://github.com/openvinotoolkit/openvino/pull/24988
=> Docs releasenotes 24.2 first pass port 24.2

docs/articles_en/documentation/openvino-extensibility.rst, docs/articles_en/documentation/openvino-extensibility/custom-openvino-operations.rst
Port from https://github.com/openvinotoolkit/openvino/pull/25010
Fixing snippets.
=> [DOCS] Snippets fix for 24.2

docs/CMakeLists.txt, docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/custom-class-template.rst, docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/custom-module-template.rst, docs/requirements.txt, docs/scripts/install_appropriate_openvino_version.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] OpenVINO Python API fix for 2024.2

docs/articles_en/about-openvino/performance-benchmarks/performance-benchmarks-faq.rst, docs/articles_en/documentation/legacy-features.rst, docs/articles_en/documentation/legacy-features/install-dev-tools.rst, docs/articles_en/documentation/legacy-features/model-zoo.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-efficient-det.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-object-detection.rst, docs/articles_en/documentation/openvino-extensibility/custom-gpu-operations.rst, docs/articles_en/get-started/install-openvino/install-openvino-apt.rst, docs/articles_en/get-started/install-openvino/install-openvino-brew.rst, docs/articles_en/get-started/install-openvino/install-openvino-vcpkg.rst, docs/articles_en/get-started/install-openvino/install-openvino-yum.rst, docs/articles_en/get-started/install-openvino/install-openvino-zypper.rst, docs/articles_en/learn-openvino/llm_inference_guide.rst, docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-hf.rst, docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-native-ov.rst, docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst, docs/articles_en/openvino-workflow/model-optimization.rst, docs/articles_en/openvino-workflow/model-preparation/conversion-parameters.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-onnx.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-paddle.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-pytorch.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-tensorflow-lite.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-tensorflow.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-to-ir.rst, docs/articles_en/openvino-workflow/model-preparation/setting-input-shapes.rst, docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application.rst
Adding reference to Hugging Face in documentation.
=> [DOCS] Reference to Hugging Face 

docs/articles_en/about-openvino/performance-benchmarks/performance-benchmarks-faq.rst, docs/articles_en/documentation/legacy-features.rst, docs/articles_en/documentation/legacy-features/install-dev-tools.rst, docs/articles_en/documentation/legacy-features/model-zoo.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-efficient-det.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-object-detection.rst, docs/articles_en/documentation/openvino-extensibility/custom-gpu-operations.rst, docs/articles_en/get-started/install-openvino/install-openvino-apt.rst, docs/articles_en/get-started/install-openvino/install-openvino-brew.rst, docs/articles_en/get-started/install-openvino/install-openvino-vcpkg.rst, docs/articles_en/get-started/install-openvino/install-openvino-yum.rst, docs/articles_en/get-started/install-openvino/install-openvino-zypper.rst, docs/articles_en/learn-openvino/llm_inference_guide.rst, docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-hf.rst, docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-native-ov.rst, docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst, docs/articles_en/openvino-workflow/model-optimization.rst, docs/articles_en/openvino-workflow/model-preparation/conversion-parameters.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-onnx.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-paddle.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-pytorch.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-tensorflow-lite.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-tensorflow.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-to-ir.rst, docs/articles_en/openvino-workflow/model-preparation/setting-input-shapes.rst, docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/24961
=> [DOCS] Reference to Hugging Face

src/tests/test_utils/functional_test_utils/layer_tests_summary/data/default_re_to_find_models.lst
- *item1*
- *...*
- *ticket-id*
=> [subgraph dumper] Change model package patterns

.github/workflows/linux.yml, cmake/developer_package/cross_compile/python_helpers.cmake, cmake/developer_package/features.cmake, cmake/developer_package/options.cmake, src/bindings/python/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
=> Move python configuration to common function

src/plugins/intel_cpu/src/graph.cpp
=> [CPU] Do not add Input / Output to executable nodes

.github/workflows/job_tokenizers.yml, cmake/developer_package/features.cmake
- *item1*
- *...*
- *ticket-id*
=> Use ZIP cpack generator on Windows

docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Release links update port

src/core/src/op/multiply.cpp
- *[LPT] ReduceSum: zero point support*
- *Original PR: https://github.com/openvinotoolkit/openvino/pull/24977*
- *CVS-142256*
=> [LPT] ReduceSum: zero point support: core update rollback

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- skip random error in KV Cache test (This is to fix original test, no new test needed) 
- 142899
=> [GPU] Fix random error in KV Cache test of changing batch

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- Run tests 1000 times and can't reproduce it
- CVS-123019
=> [CPU][ARM] Remove skip tests for transpose

.github/scripts/workflow_rerun/rerunner.py
=> [CI] [GHA] Rerun only failed jobs via rerunner

.github/workflows/job_python_unit_tests.yml
Checking if CVS-127101 still reproduces (it doesn't: https://github.com/openvinotoolkit/openvino/actions/runs/9550495926/job/26323459000?pr=25079, see passing MO unit tests)
=> [GHA] Return Smart CI condition for Python unit tests

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.h, src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- Previously do_runtime_buffer_fusion was examined even though input shape is not changed. 
- 144387
=> [GPU] Reduce redundant buffer fusion at runtime

src/plugins/intel_gpu/src/plugin/transformations/swiglu_fusion.cpp
- This PR sets an initial value for `glu_type`.
- 144400
=> [GPU] Set an initial value for glu_type

samples/js/node/README.md, src/bindings/js/node/README.md
- Extend README of node js bindings and samples by link to live sample of openvino-node usage
- 137670
=> [OV JS] Add link to live sample of openvino-node usage

src/bindings/python/src/pyopenvino/graph/symbol.cpp, src/bindings/python/tests/test_runtime/test_dimension.py
- Made ov::Symbol hashable in python api
- CVS-142455
=> [PyOV] Hashable Symbol

src/docs/performance_analysis_ITT_counters.md
Port from https://github.com/openvinotoolkit/openvino/pull/24925
Jira: 121504
Update of the ITT Performance Analysis docs:
* Removed info on the delisted SEAPI tool,
* Moved the file to the higher level in the repo tree.
=> [DOCS] ITT Performance Analysis update for 24.2

src/frontends/onnx/frontend/src/op/trilu.cpp
- *trilu.cpp*
- *appropiate -> appropriate*
=> [ONNX] update trilu.cpp

src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp
Functional regression happens in static because recent gemm and permute optimization in dynamic.
Fix cannot find transpose format problem in 5 dims.
- *144395*
=> [GPU] Fix twin network failure on dGPU.

src/plugins/intel_npu/README.md, src/plugins/intel_npu/src/backend/src/zero_device.cpp
- Adding npu4000 id string temporarily for 2024.3 since PR #24607 still needs work
- Will be replaced once PR #24607 gets merged
- none
=> [intel-npu] Adding npu4000 string to zero device

docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst
Adding info on support for tensor constructor from arrays of strings.
=> [DOCS] Update nodejs_api docs

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection.rst
=> fix auto-device-selection doc

src/plugins/intel_cpu/src/emitters/plugin/x64/jit_load_store_emitters.cpp, src/plugins/intel_cpu/tests/unit/jit_kernel_test.cpp
- *fix store emitter from f32 to bf16/fp16 aux gpr count*
- *CVS-143452*
=> [CPU] fix store emitter from f32 to bf16/fp16 aux gpr count

samples/cpp/benchmark_app/inputs_filling.cpp, tests/samples_tests/smoke_tests/test_benchmark_app.py, tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py
=> benchmark_app: fix npy batch

src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp, src/plugins/intel_gpu/src/graph/graph_optimizer/add_onednn_optimization_attributes.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/concatenation_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/deconvolution_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/pooling_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/reduction_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/reorder_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp, src/plugins/intel_gpu/src/graph/include/program_node.h, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/src/graph/program_node.cpp, src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
- *Create onednn attribute after update_shape *
- *142661*
=> Enable onednn eltwise fusing

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
=> [CPU] Sporadically failing roialign test disabled

docs/sphinx_setup/_static/css/custom.css, docs/sphinx_setup/_static/html/footer.html
Updated css and html files
- adjusted footer width
- styling newsletter button
- styling benchmark banner
=> Docs after release fixes

docs/articles_en/learn-openvino.rst
Removing redundant file paths of articles from the content.
=> [DOCS] Removing redundant paths

docs/articles_en/learn-openvino.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25206
=> [DOCS] Removing redundant paths for 2024.2

docs/sphinx_setup/_static/css/custom.css, docs/sphinx_setup/_static/html/footer.html
- *item1*
- *...*
- *ticket-id*
=> [Docs] port for master

scripts/setupvars/setupvars.bat
- Fix after https://github.com/openvinotoolkit/openvino/pull/24870
- 145190
=> setupvars.bat: Fixed set for OpenVINOGenAI_DIR

src/plugins/template/src/compiled_model.cpp, src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_compiled_model/properties.cpp, src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/properties.cpp
- *item1*
- *...*
- *ticket-id*
=> [api conformance] Add check of def value for PERFORMANCE_HINT

src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/unit/test_cases/gather_gpu_test.cpp
- *The empty layout is regareded as 1 dim with value 1*
- *137277*
=> [GPU] Add condition which empty layout is regareded as 1 dim with value 1 at check memory

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- Fix coverity warning
- [*CVS-145046*](https://jira.devtools.intel.com/browse/CVS-145046)
=> [GPU] Coverity fix

src/plugins/intel_gpu/tests/functional/remote_tensor_tests/gpu_remote_tensor_tests.cpp
- Fix for data size for copied tensor
- *...*
- [*CVS-141401*](https://jira.devtools.intel.com/browse/CVS-141401)
=> [GPU] Test fix size of copied data

docs/articles_en/openvino-workflow/running-inference.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device/performance-hint-and-thread-scheduling.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst, docs/sphinx_setup/index.rst
=> [DOCS] Address DX Comments

docs/sphinx_setup/_static/html/footer.html
- *item1*
- *...*
- *ticket-id*
=> [Docs] The footer update

src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- Disable sporadically failed tests
- *142900*
=> [GPU][TESTS] Disable sporadically failed tests

src/frontends/pytorch/src/op/im2col.cpp
=> [PT FE] Fix typos in im2col convertor

src/core/src/pass/pass.cpp
- Default initialize m_name member variable
- [*CVS-145084*](https://jira.devtools.intel.com/browse/CVS-145084)
=> [CORE] PassBase initialize all members

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- *need to fix gha*
- *ticket-id*
=> [CPU] All smoke_roialign tests disabled

docs/sphinx_setup/_static/html/footer.html
- *item1*
- *...*
- *ticket-id*
=> [DOCS] fixed footer file

src/plugins/intel_cpu/tools/commit_slider/tests/commit_slider_test.py, src/plugins/intel_cpu/tools/commit_slider/utils/cfg_manager.py, src/plugins/intel_cpu/tools/commit_slider/utils/cfg_samples/AC_for_CI.json, src/plugins/intel_cpu/tools/commit_slider/utils/cfg_samples/bm_output.json, src/plugins/intel_cpu/tools/commit_slider/utils/cfg_samples/e2e_for_CI.json, src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py
- *tool - specific substitutions moved to config*
=> [Commit Slider] AC / e2e compatibility

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py, docs/requirements.txt
=> [DOCS] Build speedup 2024.2

src/common/snippets/include/snippets/lowered/loop_manager.hpp, src/common/snippets/src/lowered/loop_manager.cpp, src/common/snippets/src/lowered/pass/validate_expanded_loops.cpp
- *Fixed coverity issues: `Null pointer dereferences` and `Performance inefficiencies`*
- *140933*
- *139702*
=> [Snippets][Coverity] Fixed 139702 and 140933

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp, src/plugins/intel_gpu/src/graph/layout_optimizer.cpp, src/plugins/intel_gpu/src/graph/select.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/broadcast_gpu_ref.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/generic_eltwise_ref.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/select_gpu_ref.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/broadcast/broadcast_kernel_ref.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/broadcast/broadcast_kernel_ref.h, src/plugins/intel_gpu/src/kernel_selector/kernels/eltwise/eltwise_kernel_ref.h, src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_kernel_ref.h, src/plugins/intel_gpu/src/kernel_selector/kernels/select/select_kernel_ref.h, src/plugins/intel_gpu/tests/unit/fusions/eltwise_fusion_test.cpp, src/plugins/intel_gpu/tests/unit/fusions/gather_fusion_test.cpp, src/plugins/intel_gpu/tests/unit/fusions/select_fusion_test.cpp, src/plugins/intel_gpu/tests/unit/test_cases/broadcast_gpu_test.cpp
- Reorder which is only converting type can be fused to the prior node
- 144957
=> [GPU] Fuse more 'type conversion only' reorders

.github/workflows/linux.yml
Reverts openvinotoolkit/openvino#25324
=> Revert "[GHA] Temporarily remove GPU tests from mandatory"

.github/components.yml, src/common/snippets/include/snippets/lowered/loop_info.hpp, src/common/snippets/include/snippets/lowered/loop_manager.hpp, src/common/snippets/include/snippets/lowered/pass/extract_loop_invariants.hpp, src/common/snippets/include/snippets/utils.hpp, src/common/snippets/src/lowered/loop_info.cpp, src/common/snippets/src/lowered/loop_manager.cpp, src/common/snippets/src/lowered/pass/define_buffer_clusters.cpp, src/common/snippets/src/lowered/pass/extract_loop_invariants.cpp, src/common/snippets/src/lowered/pass/init_loops.cpp, src/common/snippets/src/lowered/pass/load_movebroadcast_to_broadcastload.cpp, src/common/snippets/src/op/subgraph.cpp, src/common/snippets/src/utils.cpp, src/common/snippets/tests/include/lir_test_utils.hpp, src/common/snippets/tests/src/lir_comparator.cpp, src/common/snippets/tests/src/lir_test_utils.cpp, src/common/snippets/tests/src/lowered/pass/extracted_loop_invariants.cpp
- *recreation for PR https://github.com/openvinotoolkit/openvino/pull/24044*
- *fix post commit fail(will be added in pre commit soon)*
- *CVS-136160*
=> [Snippets] Extract loop invariants

docs/sphinx_setup/_static/html/footer.html
- *item1*
- *...*
- *ticket-id*
=> Docs footer update x4

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
During this fix https://github.com/openvinotoolkit/openvino.genai/pull/563 found some errors in the docs. Updated them.
- CVS-145154 CVS-145218
=> Update OpenVINO GenAI guide

src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- Temporarily add CoreThreadingTest.smoke_QueryModel test to skip config
- [CVS-145926](https://jira.devtools.intel.com/browse/CVS-145926)
=> [GPU] Add CoreThreadingTest.smoke_QueryModel test to skip config

src/plugins/intel_gpu/src/graph/include/primitive_inst.h, src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- *[GPU]optimize id() and get_kernel_name() by returning reference to const*
- *144417*
=> [GPU]optimize id() and get_kernel_name() by returning reference to const

src/core/reference/src/op/concat.cpp, src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp, src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.cpp, src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.hpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp, src/plugins/intel_gpu/src/runtime/debug_configuration.cpp, src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_fc_horizontal_fusion.cpp, src/plugins/intel_gpu/tests/unit/transformations/horizontal_fc_fusion_test.cpp
- Fuse QKV FCs to one FC 
- 142815
=> [GPU] Horizontal fusion for FC 

src/plugins/intel_gpu/tests/unit/test_cases/roi_align_rotated_gpu_test.cpp
- Fixed mem leak in cl engine in roi align rotated test.
- *CVS-145836*
=> [GPU][unittest]: Fixed mem leak in roi align rotated unittests.

src/plugins/intel_gpu/src/plugin/transformations/convert_stridedslices_to_variadicsplit.cpp, src/plugins/intel_gpu/src/plugin/transformations/convert_stridedslices_to_variadicsplit.hpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp, src/plugins/intel_gpu/tests/unit/transformations/convert_stridedslices_to_variadicsplit_test.cpp
- Convert QKV FC + StridedSlices pattern to QKV FC + VariadicSplit for potential optimization regarding crop runtime buffer fusing
- 144394
=> [GPU] Convert multiple StridedSlices to single VariadicSplit after fused QKV FC

.github/workflows/job_pytorch_models_tests.yml, tests/model_hub_tests/pytorch/models/hf-tiny-random-models-precommit, tests/model_hub_tests/pytorch/requirements.txt, tests/model_hub_tests/pytorch/test_pa_transformation.py
Add unique models to precommit PA tests
Change the list of models covering all the big real models.
Removed:
hf-tiny-model-private/tiny-random-GPT2LMHeadModel
hf-tiny-model-private/tiny-random-BartForCausalLM,xfail
hf-tiny-model-private/tiny-random-BigBirdForCausalLM,xfail
hf-tiny-model-private/tiny-random-BigBirdPegasusForCausalLM,xfail
hf-tiny-model-private/tiny-random-BlenderbotSmallForCausalLM,xfail
hf-tiny-model-private/tiny-random-ErnieForCausalLM,xfail
hf-tiny-model-private/tiny-random-GPTNeoXJapaneseForCausalLM,xfail
hf-tiny-model-private/tiny-random-MBartForCausalLM,xfail
hf-tiny-model-private/tiny-random-MvpForCausalLM,xfail
hf-tiny-model-private/tiny-random-PLBartForCausalLM,xfail
PrunaAI/hf-tiny-model-private-tiny-random-BloomForCausalLM-bnb-4bit-smashed,xfail …
=> Add unique models to precommit PA tests

docs/sphinx_setup/_static/css/custom.css
=> [DOCS] Breadcrumbs alignment fix

src/plugins/intel_cpu/src/nodes/rnn.cpp
Incorrect check resulted into a decomposition of different RNN operations
=> [CPU] Fix RNN node isSupported check

src/frontends/pytorch/src/op/col2im.cpp, src/frontends/pytorch/src/op_table.cpp, tests/layer_tests/pytorch_tests/test_col2im.py, tests/layer_tests/pytorch_tests/test_im2col.py, tests/model_hub_tests/pytorch/timm_models
- *Support `aten::col2im`*
- *CVS-101054*
=> [PT FE] Support aten::col2im

.github/workflows/job_tokenizers.yml
- Added path to tokenizers build to find ov wheel (https://github.com/openvinotoolkit/openvino_tokenizers/pull/183)
- *ticket-id*
=> [GHA] Fixed tokenizers build

src/common/conditional_compilation/include/openvino/cc/factory.h, src/common/util/src/common_util.cpp, src/common/util/src/file_util.cpp
- Remove unnecessary copies from Conditional Compilation an common util components.
- N/A
=> [core] Fix Coverity issues in common CC and util

src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/unit/dynamic_execution/memory_realloc_test.cpp
- Fix layout count comparison by using actual byte value
- 144293
=> [GPU]Fix layout count comparison by using actual byte value in realloc_if_needed

src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected_primitive.cpp
- *Disable avx2 asymmetric dynamic quantization*
- *...*
- *ticket-id*
=> [CPU] Disable avx2 asymmetric dynamic quantization

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
This reverts commit 01dc53ac2deb437c644b63a633e0a7780ddf848c. Reverting this PR because it is causing LLM failures
- 145784
=> Revert "[GPU] update shape for fused prims (#25363)"

src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp
=> [GPU] Stable Diffusion failure using sdpa_kernel_opt.

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
- *item1*
- *...*
- *ticket-id*
=> Port Update OpenVINO GenAI guide

docs/articles_en/assets/snippets/compile_model_npu.cpp, docs/articles_en/assets/snippets/compile_model_npu.py, docs/articles_en/openvino-workflow/running-inference.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device/performance-hint-and-thread-scheduling.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst, docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application.rst, docs/sphinx_setup/index.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port DX changes

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp, src/plugins/intel_gpu/src/graph/loop.cpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/unit/test_cases/loop_gpu_test.cpp
- *Requesting 0 bytes memory allocation to OpenCL returns error -61. Plugin should not request 0 bytes memory allocation.*
- *143586*
- *143335*
- *142909*
=> [GPU] Reinterpret from 1 dim mem to 0 dim mem instead of allocating 0 bytes layout to OpenCL

docs/articles_en/get-started/install-openvino/install-openvino-conda.rst
Added information on how to install selected components of OpenVINO from Conda Forge. This PR addresses JIRA ticket: CVS-112511
=> [DOCS] Update deployment with Conda Forge

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_micro.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp
- Fix `PREFETCH_K0` path to avoid page fault
=> [GPU] Fix for micro SDPA to avoid page fault

src/plugins/intel_gpu/src/graph/resample.cpp, src/plugins/intel_gpu/tests/unit/shape_infer/resample_si_test.cpp
- Added fused op type handling to resample calc_output_layouts() impl
- *CVS-146270*
=> [GPU] Fix resample type infer

docs/articles_en/about-openvino/compatibility-and-support/supported-devices.rst, docs/articles_en/about-openvino/performance-benchmarks.rst, docs/sphinx_setup/_static/html/footer.html
port: https://github.com/openvinotoolkit/openvino/pull/25443
=> [DOCS] tweaks in footer and menu

src/bindings/python/tests/test_graph/test_constant.py
- GPU bug test_float_to_f8e8m0_convert repro 
- [*CVS-145281*](https://jira.devtools.intel.com/browse/CVS-145281)
=> [CORE] [GPU] nan to inf bug repro test

src/plugins/intel_gpu/src/graph/graph_optimizer/fuse_primitives_with_layout.cpp, src/plugins/intel_gpu/src/graph/include/pass_manager.h, src/plugins/intel_gpu/src/graph/program.cpp, src/plugins/intel_gpu/tests/unit/passes/fuse_primitives_with_layout.cpp, src/plugins/intel_gpu/tests/unit/test_cases/quantize_gpu_test.cpp
- *Don't fuse eltwise for fs_b_yx_fsv32_network*
- *133378*
=> [GPU] Add fusing false condition for fs_b_yx_fsv32_network at eltwise and quantize pattern

src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp
This PR assigns `device_it` of subgraphs that are functions to the device iterator of main compiled function.
- *ticket-id*
=> [NPUW] Fix distribution statistics

src/core/reference/include/openvino/reference/utils/phillox_converter.hpp, src/core/reference/src/op/random_uniform.cpp, src/core/reference/src/utils/phillox_converter.cpp
- Fix srand unsafe cryptography error [(changed 2 lines)](https://github.com/openvinotoolkit/openvino/pull/25375/files#diff-5050a79a508a33aef16000f07f1e2e49544219324e48519ad66302d38f060519R33-R34)
- Fix copy instead of move for generated numbers [(changed 2 lines)](https://github.com/openvinotoolkit/openvino/pull/25375/files#diff-5050a79a508a33aef16000f07f1e2e49544219324e48519ad66302d38f060519R53-R54)
- Rename all Phillox -> Philox to match across all files (every other affected file except for the one lined above is this rename operation)
- None
=> [COVERITY] Fix RandomUniform coverity issues

docs/articles_en/about-openvino/compatibility-and-support/supported-models.rst
port: https://github.com/openvinotoolkit/openvino/pull/25468
=> [DOCS] fix wording around 500 models port24

docs/dev/ov_dependencies.txt
Updated filename for HuggingFace dependency checks to get rid of versioning in name
=> Updated filename for HF dependency check

docs/dev/conditional_compilation.md
- Modify the dev doc for cc limitation.
- *CVS-136255*
=> [DOC][CC] Only IR model is supported by CC for now, other model format need to convert to IR first for enabling CC

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- Minor changes to fix regression issue from https://github.com/openvinotoolkit/openvino/pull/25060
- 137277
=> [GPU] Minor fixes for regression from runtime buffer fusing for crop

src/plugins/auto/src/auto_compiled_model.cpp, src/plugins/auto/src/auto_schedule.cpp, src/plugins/auto/src/cumulative_schedule.cpp
=> [Coverity] Fix AUTO plugin issues

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- Minor fix for missing or wrong debug info for memalloc
- *ticket-id*
=> [GPU] Minor fix for missing or wrong debug info for memalloc

.github/actions/cache/package-lock.json
- Run `npm audit fix`
- CVS-146051
=> [GHA] Update dependecies

src/plugins/intel_npu/tools/compile_tool/main.cpp, src/plugins/intel_npu/tools/single-image-test/main.cpp
Fix coverity issue for compile_tool.
Support template plugin for single-image-test.
- *ticket-id*
=> [NPU] Update tools

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Add LLM output

src/bindings/js/node/README.md
- Extend readme of `openvino-node` package by note about usage in Electron application
- 144938
=> [OV JS] Add note about usage in development of Electron applications

src/core/include/openvino/pass/pattern/op/pattern.hpp, src/core/shape_inference/include/convolution_backprop_shape_inference.hpp, src/core/shape_inference/include/reverse_sequence_shape_inference.hpp, src/core/src/graph_util.cpp, src/core/src/node.cpp, src/core/src/opsets/opset.cpp, src/core/src/partial_shape.cpp, src/core/src/pass/stateful_to_stateless.cpp, src/core/src/rt_info.cpp
- Fix `COPY_INSTEAD_OF_MOVE` in multiple core component files.
- N/A
=> [COVERITY] Fix COPY_INSTEAD_OF_MOVE in core

docs/articles_en/about-openvino.rst, docs/articles_en/about-openvino/compatibility-and-support/supported-devices.rst, docs/dev/index.md
Reference and formatting fixes.
=> [DOCS] Minor fixes for docs

docs/articles_en/about-openvino.rst, docs/articles_en/about-openvino/compatibility-and-support/supported-devices.rst, docs/dev/index.md
Porting: https://github.com/openvinotoolkit/openvino/pull/25489
=> [DOCS] Minor fixes for docs - for 2024.2

src/plugins/intel_cpu/src/nodes/reduce.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/reduce.cpp
This reverts commit cbd06e2601c05468c52e3f84a083e82bb3b577b5.
Revert https://github.com/openvinotoolkit/openvino/pull/25217
- CVS-146321
=> [CPU] Revert "[CPU] Round towards zero for ReduceMean (#25217)"

src/plugins/intel_cpu/tools/commit_slider/tests/commit_slider_test.py, src/plugins/intel_cpu/tools/commit_slider/tests/test_data.py, src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/fbv_ac_mode.cpp, src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/tests_res.json, src/plugins/intel_cpu/tools/commit_slider/utils/cfg.json, src/plugins/intel_cpu/tools/commit_slider/utils/modes.py
- *item1*
- *...*
- *ticket-id*
=> [Commit Slider] AC mode 

src/inference/include/openvino/runtime/properties.hpp
- Using capital letters for workload type
- CVS-143714
=> [NPU] Capitalizing Workload Type enum

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- *Transpose Sinking before SDPA fusion*
- *CVS-144513*
=> Transpose Sinking before SDPA fusion

.github/workflows/mac.yml, .github/workflows/mac_arm64.yml, src/common/util/include/openvino/util/file_util.hpp, src/inference/src/model_reader.cpp, src/inference/tests/functional/ov_core_test.cpp
- Caused by the <filesystem> supporting in MAC OS, disable symlink checking for now.
- CVS-146532
=> Disable symlink check on MAC OS for now

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp, src/tests/functional/shared_test_classes/src/base/layer_test_utils.cpp, src/tests/ov_helpers/ov_models/src/utils/ov_helpers.cpp
Port https://github.com/openvinotoolkit/openvino/pull/25253 from master
- CVS-145166
=> Add Clamp to convert to bool when replaced with u8

.github/workflows/linux_cpu_dev.yml
- *enable manually triggered developer workflow for cpu-plugin needs*
- *142428*
=> [GHA] CPU developer workflow

docs/dev/pypi_publish/pre-release-note.md, docs/dev/pypi_publish/pypi-openvino-dev.md, docs/dev/pypi_publish/pypi-openvino-rt.md
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Delete Pre-release note

docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst
Jira: 146689
Fixing command line in the "Install on Windows from the archive file" article.
=> [DOCS] Command Line fix - Windows Archive for master

docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst
Port from https://github.com/openvinotoolkit/openvino/pull/25549
Jira: 146689
Fixing command line in the "Install on Windows from the archive file" article.
=> [DOCS] Command Line fix - Windows Archive for 24.3

src/plugins/intel_gpu/src/graph/include/kv_cache_inst.h, src/plugins/intel_gpu/src/graph/kv_cache.cpp
- Added detailed description about the kv cache prealloc policy 
- *ticket-id*
=> [GPU] Minor change (Added comment for kv cache prealloc policy)

src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- Fixing Coverity issues related to Workload Type
=> [NPU] Fixing Coverity issues related to Workload Type

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
- *item1*
- *...*
- *ticket-id*
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port LLM output 

src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/partitioning.cpp
- Fixes for NPUW coverity into release branch
- *ticket-id*
=> Fix coverity issues for NPUW component

src/plugins/intel_gpu/tests/common/subgraphs_builders.hpp, src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache_sdpa.cpp, src/plugins/intel_gpu/tests/unit/transformations/sdpa_opt_test.cpp
- Added multi iteration func test for KV Cache + SDPA subgraph
- Added unit tests for SDPA optimization passes
=> [GPU] KV Cache + SDPA test

src/plugins/intel_npu/tests/functional/behavior/infer_request_run.cpp
- *Having a new driver version in the CI job, batch plugin mode could be enabled for functional tests*
- *ticket-id*
=> [NPU] Enable batch plugin mode for functional tests

tests/model_hub_tests/performance_tests/nightly_models.skip
- add failed models to skip list
- 146773
=> add failed models to skip list

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection.rst
- *Document the AUTO accuracy behavior*
- *CVS-144747*
=> [DOC][AUTO] Note for accuracy

.github/workflows/job_python_unit_tests.yml, src/bindings/python/CMakeLists.txt, src/bindings/python/constraints.txt, src/bindings/python/requirements.txt, src/bindings/python/src/openvino/runtime/utils/data_helpers/data_dispatcher.py, src/bindings/python/tests/test_graph/test_create_op.py, src/bindings/python/tests/test_transformations/test_pattern_ops.py, src/bindings/python/tests/test_utils/test_data_dispatch.py, tools/benchmark_tool/requirements.txt
- based on https://github.com/openvinotoolkit/openvino/pull/24889
- + Added workflow which runs Python API tests specifically using numpy>=2.0.0
- [CVS-143476](https://jira.devtools.intel.com/browse/CVS-143476)
=> [PyOV] numpy2.0

tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py
- *item1*
- *...*
- *ticket-id*
=> [OVC] Remove debug print

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
- adding newly supported properties to npu-device documentation
- addig section describing compilation-mode-params to npu-device documentation
- *ticket-id*
=> [intel-npu] Updating npu-device properties in documentation

src/bindings/python/src/openvino/runtime/ie_api.py, src/bindings/python/src/openvino/runtime/opset6/ops.py, src/bindings/python/src/openvino/runtime/opset8/ops.py, src/bindings/python/src/openvino/runtime/utils/decorators.py, src/bindings/python/tests/test_graph/test_create_op.py
- Problem was that my previous `@overloading` solution could work only with positional arguments. Added support for key-word arguments and mixed.
- CVS-146848
=> [PyOV] Support kwargs in overloading

src/plugins/intel_npu/src/plugin/npuw/partitioning/partitioning.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.hpp
Added pattern for CWAI for Phi-3 model to preserve Scale tensors in the function bodies
=> [NPUW] Fix scales processing for Phi-3 in CWAI

src/common/transformations/src/transformations/op_conversions/scaled_dot_product_attention_decomposition.cpp, src/plugins/intel_cpu/CMakeLists.txt, src/plugins/intel_cpu/src/nodes/kernels/acl/gemm_kernel.cpp, src/plugins/intel_cpu/src/nodes/kernels/acl/gemm_kernel.hpp, src/plugins/intel_cpu/src/nodes/scaled_attn.cpp, src/plugins/intel_cpu/src/nodes/scaled_attn.h
- This PR aims to add ACL implementation for scaled attention
=> [GSOC][CPU][ARM] ACL scaled attention

docs/sphinx_setup/api/api_reference.rst
Changing labels of items in the `API Reference` section. Adding mention of JavaScript language. Porting: https://github.com/openvinotoolkit/openvino/pull/25482
=> [DOCS] Fix API items in menu

.github/workflows/linux.yml
Reverts openvinotoolkit/openvino#25337
We have issues with GPU runners again
=> Revert "Revert "[GHA] Temporarily remove GPU tests from mandatory""

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
Port from https://github.com/openvinotoolkit/openvino/pull/25590
* adding newly supported properties to npu-device documentation
* addig section describing compilation-mode-params to npu-device documentation
=> [DOCS] NPU properties in documentation for master

samples/c/common/opencv_c_wrapper/src/bmp_reader.c, samples/cpp/common/utils/include/samples/common.hpp
=> samples: handle corner cases

samples/c/common/opencv_c_wrapper/src/bmp_reader.c, samples/cpp/common/utils/include/samples/common.hpp
=> samples: handle corner cases (#25604)

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- 
- reverting some changes made by 138396
- affects 131596 by 50GB mem usage instead 10GB
=> [GPU] too big cn_unet memory consumption

docs/CMakeLists.txt, docs/sphinx_setup/api/api_reference.rst, docs/sphinx_setup/api/genai_api/api.rst, docs/sphinx_setup/conf.py
=> [DOCS] OV GenAI API 2024.3 docs additions

.github/workflows/linux.yml
Reverts openvinotoolkit/openvino#25605
Runners are online
=> Revert "Revert "Revert "[GHA] Temporarily remove GPU tests from mandatory"""

src/inference/dev_api/openvino/runtime/threading/istreams_executor.hpp, src/inference/include/openvino/runtime/properties.hpp, src/inference/src/cpp/core.cpp, src/inference/src/cpp/infer_request.cpp, src/inference/src/dev/core_impl.cpp, src/inference/src/dev/iplugin.cpp, src/inference/src/dev/performance_heuristics.cpp, src/inference/src/dev/threading/cpu_streams_executor_internal.cpp, src/inference/src/dev/threading/istreams_executor.cpp, src/inference/src/model_reader.cpp, src/inference/src/os/lin/lin_system_conf.cpp
Reverts openvinotoolkit/openvino#25548
Probably breaks MacOS debug
=> Revert "apply fixes for issues spotted by coverity"

.github/workflows/linux.yml
Reverts openvinotoolkit/openvino#25620
Again incident with runners
=> [GHA] Temporarily remove GPU tests from mandatory

tests/model_hub_tests/pytorch/requirements.txt
- *item1*
- *...*
- *ticket-id*
=> Restrict python-bidi to fix easyocr dependencies

src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/convolution_backprop_data_transformation.cpp, src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/fq_with_dq_not_optimal_transformation.cpp, src/plugins/intel_gpu/tests/functional/shared_tests_instances/low_precision_transformations/groupconvolution_qdq_transformation.cpp
- *GPU: Low Precision Transformations: tests fix*
=> [LPT] [GPU] tests fix

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
- *CPU ARM: JIT GeluTanh emitter fix*
=> [CPU] [ARM] JIT GeluTanh emitter fix

docs/articles_en/assets/snippets/ov_caching.cpp, docs/articles_en/assets/snippets/ov_caching.py, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-latency/model-caching-overview.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25670
=> [DOCS] Update model caching for GPU for 24.3

docs/CMakeLists.txt, docs/sphinx_setup/api/api_reference.rst, docs/sphinx_setup/api/genai_api/api.rst, docs/sphinx_setup/conf.py
OpenVINO GenAI Python API docs addition.
=> [DOCS] Add OV GenAI Python API

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp, src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
- *[CPU] [ARM] JIT Tanh & Mod (GFI) fix*
=> [CPU] [ARM] JIT Tanh & Mod (GFI) fix

docs/articles_en/openvino-workflow/model-preparation.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing/integrate-save-preprocessing-use-case.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing/preprocessing-api-details.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing/preprocessing-api-details/integrate-save-preprocessing-use-case.rst
* Removed info on the Model Optimizer from the article.
* Moved the article to the new location in repo.
=> [DOCS] Preprocessing Use Case update for master

src/bindings/c/tests/ov_core_test.cpp
- *enable ov_core_compile_model_with_property*
- *CVS-126283*
=> enable ov_core_compile_model_with_property

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- Follow up remaining issue from https://github.com/openvinotoolkit/openvino/pull/25682
- Fix issue where kvcache was optimized out even if calculated present layout's padding was negative
- 146876
=> [GPU] Fix remaininig issue to calculate present layout's padding for KVCache

src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp, src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/src/runtime/layout.cpp
- Refactor according to the comments in PR25449
- *ticket-id*
=> [GPU] Minor refactoring

tests/constraints.txt, tests/e2e_tests/requirements.txt, tools/constraints.txt
- took changes from https://github.com/openvinotoolkit/openvino/pull/25661
- *ticket-id*
=> Checkout OMZ

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp, src/plugins/intel_gpu/src/graph/reshape.cpp, src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- *[146165](https://jira.devtools.intel.com/browse/CVS-146165)*
=> [GPU] Fix incorrect selection of preferred formats for weights in case of OneDNN

src/plugins/intel_npu/src/plugin/src/plugin.cpp
- MAX_TILES and STEPPING should be initialized with the default values from the used backend if the user does not set them.
- these two properties will be initialized by the driver if L0 backend is used.
- *E#130074*
=> [intel-npu] Adding fix for max_tiles and stepping initializations

docs/articles_en/openvino-workflow/model-preparation.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing/preprocessing-api-details.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimize-preprocessing/preprocessing-api-details/integrate-save-preprocessing-use-case.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25634
=> [DOCS] Preprocessing Use Case update

docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application.rst, docs/snippets/src/main.py
- *item1*
- *...*
-CVS-145108
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port Auto Description 

docs/articles_en/assets/snippets/main.py, docs/articles_en/assets/snippets/ov_stateful_model_intro.py, docs/articles_en/assets/snippets/ov_stateful_models_intro.cpp, docs/articles_en/openvino-workflow/running-inference/stateful-models/obtaining-stateful-openvino-model.rst
- Snippet was removed here https://github.com/openvinotoolkit/openvino/issues/24510
- Returned it back and aligned it with C++ one (generally took it from this https://github.com/openvinotoolkit/openvino/pull/15978)
- Added it to documentation
- *ticket-id*
=> [Docs][PyOV] return back snippet for stateful model

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
Adding info on `performance-hint-override` and `npu_turbo` NPU features.
=> [DOCS] Updating NPU device article

docs/articles_en/about-openvino.rst, docs/articles_en/about-openvino/contributing.rst, docs/articles_en/about-openvino/contributing/code-contribution-guide.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/23650
=> [DOCS] Add Contribute to OpenVINO articles

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25727
=> [DOCS] Updating NPU device article for master

docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst
- *item1*
- *...*
- *ticket-id*
=> Update NNCF documentation

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25705
=> [DOCS] Add max_new_tokens to every generate call in GenAI guide

docs/articles_en/assets/images/quantization_scheme.svg, docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations.rst, docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations/quantization-scheme.rst
=> [DOC] Quantization Scheme

docs/articles_en/assets/images/quantization_scheme.svg, docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations.rst, docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations/quantization-scheme.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25295
=> [DOCS] Quantization Scheme for 24.3

docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25667
=> [DOCS] Updating NNCF documentation

docs/articles_en/assets/snippets/main.py, docs/articles_en/assets/snippets/ov_stateful_model_intro.py, docs/articles_en/assets/snippets/ov_stateful_models_intro.cpp, docs/articles_en/openvino-workflow/running-inference/stateful-models/obtaining-stateful-openvino-model.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25694
=> [DOCS] Reintroducing the snippet for stateful models for 2024.3

src/common/transformations/src/transformations/transpose_sinking/ts_concat.cpp
Fixed a dyn rank handling
Fixed positive case
- *CVS-147730*
=> Fix concat axis handling in TSConcat transformation

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add `502: Bad Gateway` to errors to look for in workflow rerunner

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
- *Add some ITT traces for better visibility over memcpy vs update mutable command list features*
- **
=> Add some ITT traces for better visibility

.github/CODEOWNERS, .github/components.yml, .github/github_org_control/config.json, .github/labeler.yml
- Added OVC to github labels and updated code owners.
- 144781
=> Added OVC to github labels and updated code owners.

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp, src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- *Fix gemm_tiled_opt to support B_VEC_SIZE>1 at static shape*
- *139840*
=> [GPU] Fix gemm_tiled_opt kernel to support B_VEC_SIZE > 1 for static

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add `Unexpected HTTP response: 520` to errors to look for in workflow rerunner

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst, docs/sphinx_setup/index.rst
port: https://github.com/openvinotoolkit/openvino/pull/25710
=> [DOCS] relnotes 24.3 first pass

src/frontends/tensorflow/src/frontend.cpp, src/frontends/tensorflow_common/include/helper_ops/tensor_list_ops.hpp, src/frontends/tensorflow_common/include/helper_transforms/tensor_list_ops_resolver.hpp, src/frontends/tensorflow_common/src/helper_transforms/tensor_list_ops_resolver.cpp, src/frontends/tensorflow_common/src/op/tensor_list_operations.cpp, tests/layer_tests/tensorflow_tests/test_tf_TensorListPushBack.py
**Details:** Deduce dynamic element type for TensorList on latter stage when replacing TensorList container with a constant.
**Ticket:** 145614
=> [TF FE] Deduce dynamic element type for TensorList. Fix for deepspeech2

src/frontends/tensorflow/docs/supported_ops.md
**Details:** Document new supported ops in 2024.3 release
=> [TF FE] Document new supported ops in 2024.3 release

src/common/util/src/os/win/win_shared_object_loader.cpp, src/core/dev_api/openvino/core/so_extension.hpp, src/core/tests/extension.cpp
- Fixed add_extension() for Unicode paths on Windows.
- 146200
=> Fixed add_extension() for Unicode paths on Windows.

src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h, src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp
=> [GPU] update offset for dynamic padding of fused_inputs

docs/articles_en/documentation/openvino-ecosystem.rst
port: https://github.com/openvinotoolkit/openvino/pull/25776
=> [DOCS] OV ecosystem update

docs/articles_en/about-openvino/release-notes-openvino.rst
port: https://github.com/openvinotoolkit/openvino/pull/25804
=> [DOCS] relnotes 24.3 second pass

docs/sphinx_setup/_static/js/graphs.js
Porting: https://github.com/openvinotoolkit/openvino/pull/25796
=> [DOCS] Ensure ieType exists before calling includes

src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- unskipping tests which pass now
- *E#108600*
=> [NPU] Unskip properties tests

docs/articles_en/documentation/openvino-ecosystem.rst
https://github.com/openvinotoolkit/openvino/pull/25824
=> [DOCS] Updating Tool Ecosystem article for 2024.3

src/frontends/tensorflow_common/src/op/tensor_list_operations.cpp, tests/layer_tests/tensorflow_tests/test_tf_TensorListConcatV2.py, tests/model_hub_tests/tensorflow/model_lists/precommit_convert_model, tests/model_hub_tests/tensorflow/model_lists/precommit_read_model
**Details:** Support TensorListConcatV2 operation for multiple undefined dims in element_shape
**Ticket:** 105671
=> [TF FE] Support TensorListConcatV2 operation for multiple undefined dims in element_shape

src/common/low_precision_transformations/include/low_precision/common/fake_quantize_dequantization.hpp, src/common/low_precision_transformations/include/low_precision/layer_transformation.hpp, src/common/low_precision_transformations/include/low_precision/network_helper.hpp, src/common/low_precision_transformations/src/fake_quantize_dequantization.cpp, src/common/low_precision_transformations/src/multiply_partial.cpp, src/common/low_precision_transformations/src/network_helper.cpp
- *NNCF quantized fp16 model on GPU support*
- *CVS-126300*
=> [LPT] Dequantization precision reusage

docs/openvino_sphinx_theme/openvino_sphinx_theme/__init__.py, docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/edit-this-page.html
Porting: https://github.com/openvinotoolkit/openvino/pull/25831
=> [DOCS] Updating Edit Button for articles for master

src/plugins/intel_npu/tools/common/CMakeLists.txt, src/plugins/intel_npu/tools/compile_tool/CMakeLists.txt, src/plugins/intel_npu/tools/compile_tool/cmake/standalone.cmake, src/plugins/intel_npu/tools/single-image-test/CMakeLists.txt, src/plugins/intel_npu/tools/single-image-test/cmake/standalone.cmake
- Fix sing-image-test and compile_tool standalone build when OpenVINO project and ov_add_target is not reachable 
- E-132977
=> Fix SIT standalone build

.github/labeler.yml
- Mark changes under "src/plugins/intel_npu/src/plugin/npuw" with NPUW label
- n/a
=> Add NPUW to labeler

CMakeLists.txt, cmake/developer_package/target_flags.cmake
- *item1*
- *...*
- Closes https://github.com/openvinotoolkit/openvino/issues/25420
=> Fixed compilation with clang and libc++

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- Rollback while-loop structure for 2nd stage of optimize all crops because it has regression for reshape case which has padding.
- 146653
=> [GPU] Rollback whlie-loop structure for 2nd stage of optimize all crops

src/bindings/js/node/package-lock.json, src/bindings/js/node/package.json
- update openvino-node package version to 2024.3.0
=> [OVJS] Update openvino-node package version to 2024.3.0

src/bindings/js/node/package-lock.json, src/bindings/js/node/package.json
- update openvino-node package version to 2024.3.0 in master branch
=> [OVJS] Update openvino-node binaries to 2024.3 in master

.github/workflows/send_workflows_to_opentelemetry.yml
New workflows were introduced in https://github.com/openvinotoolkit/openvino/pull/25234 but were not added to the workflow that gathers statistics.
- *144917*
=> [CI] [GHA] Gather statistics on newly added Ubuntu workflows

.github/workflows/android_arm64.yml
=> [CI] [GHA] Get VCPKG version from repository

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
- Add crop check in optimize check of buffer fusing to pass through simple dynamic shape crop case
- Follow up PR25737
=> [GPU] Add crop check in optimize check of buffer fusing

src/bindings/python/requirements_test.txt
=> Changed dependency types-setuptools

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/mvn_gpu_bfyx_opt.cl
Optimize MVN BFYX OPT kernel
- Use parallel sum reduction in order to improve efficiency
- 148585
=> [GPU] Use parallel sum reduction in MVN BFYX OPT kernel

src/plugins/intel_cpu/src/nodes/executors/acl/acl_interpolate.cpp
- Added debug logs to ACL Interpolate executor to debug easier
- Remove redundant check (since it duplicates the check https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_cpu/src/nodes/executors/acl/acl_interpolate.cpp#L135_L136)
- *ticket-id*
=> [CPU][ARM] Added debug logs to ACL Interpolate executor

src/frontends/tensorflow_common/src/op/unsorted_segment_sum.cpp, tests/layer_tests/tensorflow_tests/test_tf_UnsortedSegmentSum.py
**Details:** This extension is needed for some customer model
**Ticket:** 148750
=> [TF FE] Extend UnsortedSegmentSum for ND indices

src/frontends/tensorflow_common/src/helper_transforms/tensor_list_ops_resolver.cpp, src/frontends/tensorflow_common/src/op/tensor_list_operations.cpp
**Details:** Fix performance inefficiencies
**Ticket:** 148599
=> [TF FE][SDL] Fix performance inefficiencies

src/bindings/python/wheel/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
=> Fixed compatibility with new version of 'wheel'

src/frontends/onnx/frontend/src/op/reduce.cpp, src/frontends/onnx/tests/models/reduce_prod_18.prototxt, src/frontends/onnx/tests/onnx_import.in.cpp, src/frontends/onnx/tests/tests_python/test_backend.py
- Aligned behavior of ReduceProd operation
- 143347
=> [ONNX] Aligned behavior for ReduceProd-11,13,18

src/inference/src/cpp/compiled_model.cpp
=> fix for confused input with output in assert error message

src/common/transformations/include/transformations/common_optimizations/move_eltwise_up_data_movement.hpp, src/common/transformations/src/transformations/common_optimizations/move_eltwise_up_data_movement.cpp, src/common/transformations/tests/common_optimizations/move_eltwise_up_data_movement_test.cpp, src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
- Added pass to swap Reshape/Squeeze/Unsqueeze -> Eltwise (per channel)
=> [Transformations] Extend MoveEltwiseUpThroughData pass with per channel case

docs/articles_en/get-started/configurations.rst, docs/articles_en/get-started/configurations/genai-dependencies.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst
Port from https://github.com/openvinotoolkit/openvino/pull/25908
Adding information on the OpenVINO GenAI Dependencies and ref-link to the GenAI building in user docs.
=> [DOCS] Dependencies and Building for OpenVINO GenAI article for 24.3

docs/dev/build_linux.md, docs/dev/build_windows.md
- Corrected build guides in docs.
-
=> [DOCS] Corrected build guides in docs.

docs/articles_en/assets/images/deployment_full.svg, docs/articles_en/assets/images/deployment_simplified.svg, docs/articles_en/openvino-workflow/deployment-locally/local-distribution-libraries.rst
Updating diagrams and adding info on support for NPU. Addressing JIRA ticket: 148996
=> [DOCS] Update local distribution docs

.github/workflows/dev_cpu_linux_snippets_libxsmm.yml, .github/workflows/linux_cpu_snippets_libxsmm.yml
- *Renamed GHA workflow for Snippets with TPP validation*
- *N/A*
=> [TPP][GHA] Renamed workflow

docs/articles_en/assets/images/deployment_full.svg, docs/articles_en/assets/images/deployment_simplified.svg, docs/articles_en/openvino-workflow/deployment-locally/local-distribution-libraries.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/25948
=> [DOCS] Update local distribution docs for 2024.3

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
- *Minor fix for https://github.com/openvinotoolkit/openvino/pull/25697*
- *[148722](https://jira.devtools.intel.com/browse/CVS-148722)*
=> [GPU] Fix selection of preferred formats for onednn for weights

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
- *Make the input format of concatenation same as output format*
- *147692*
=> [GPU] Match concat input format

src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- Removing redundant skip rule as test name was already changed
- EISW-116762
=> [IE-MDK] Remove redundant skip rule

src/plugins/intel_cpu/src/nodes/input.cpp
And see what happens
- *item1*
- *...*
- *ticket-id*
=> [CPU] Remove weights clone WA for FullyConnected with not aligned size

docs/articles_en/assets/images/quantization_scheme.svg
Fixing a typo and adding the background.
=> [DOC] Updating Quantization Scheme Diagram

src/frontends/tensorflow/src/input_model.cpp, src/frontends/tensorflow/src/translate_session.cpp, src/frontends/tensorflow_common/include/place.hpp, src/frontends/tensorflow_common/src/place.cpp, tests/model_hub_tests/tensorflow/model_lists/precommit_convert_model
**Details:** Need to use Parameter nodes created preliminary in translate graph
**Ticket:** 142814
=> [TF FE] Fix conversion of body graph from memory

docs/articles_en/learn-openvino/openvino-samples/benchmark-tool.rst
Updating info on the use of `benchmark_app`
=> [DOCS] Updating Benchmark Tool Article

src/core/reference/include/openvino/reference/scatter_elements_update.hpp, src/plugins/intel_gpu/tests/unit/test_cases/scatter_elements_update_gpu_test.cpp
- *item1*
- *...*
- *ticket-id*
=> Fixed static build for gcc

docs/articles_en/assets/images/quantization_scheme.svg
Porting: https://github.com/openvinotoolkit/openvino/pull/25977
=> [DOCS] Updating Quantization Scheme Diagram for 2024.3

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add `Unable to make request: ECONNRESET` to errors to look for in workflow rerunner

src/plugins/intel_npu/src/plugin/src/plugin.cpp, src/plugins/intel_npu/tests/functional/behavior/remote_tensor_tests/remote_run.hpp
- *Adding support for the import_model path with using a remote context*
- *Adding extra test case for it*
- **
=> [NPU] Adding support for the import_model path with remote context

docs/articles_en/learn-openvino/openvino-samples/benchmark-tool.rst
Port https://github.com/openvinotoolkit/openvino/pull/25974
Updating info on the use of `benchmark_app`
=> [DOCS] Updating Benchmark Tool Article for 24.3

src/plugins/intel_gpu/src/plugin/transformations/convert_matmul_to_fc.cpp, src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/matmul_conversion.cpp, src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/convert_fc_to_matmul.cpp, src/plugins/intel_gpu/tests/unit/transformations/convert_matmul_to_fc_test.cpp
+ Resolved execution failure of segnext model
- *item1*
- *...*
- 146597
=> [GPU] Bugfix mis-match axes size in ConvertMatMulToFullyConnected

src/plugins/intel_cpu/src/nodes/interpolate.cpp
- Lack of f16 Interpolation leads to additional Converts in `fastseg`.
- *ticket-id*
=> [CPU][ARM] Enable f16 Interpolate on ARM

src/common/transformations/src/transformations/common_optimizations/lstm_cell_fusion.cpp
My Windows gave a more reasonable error: `src/common/transformations/src/transformations/common_optimizations/lstm_cell_fusion.cpp(53): error C2872: 'op': ambiguous symbol C:\Users\vzlobin\r\openvino\src\common\transformations\include\transformations/utils/utils.hpp(24): note: could be 'ov::op' C:\Users\vzlobin\r\openvino\src\core\include\openvino/pass/pattern/op/wrap_type.hpp(13): note: or 'ov::pass::pattern::op'`.
Ticket 149408
=> Fix -DENABLE_FASTER_BUILD

tests/model_hub_tests/pytorch/test_hf_transformers.py, tests/model_hub_tests/pytorch/test_timm.py, tests/model_hub_tests/transformation_tests/test_pa_transformation.py, tests/model_hub_tests/transformation_tests/test_stateful_to_stateless_transformation.py
- *item1*
- *...*
- *CVS-149231*
- *CVS-149229*
=> [PT FE] Retry hf related tests

src/bindings/python/wheel/setup.py
- Current patterns don't work for TBB properly
=> Fixed TBB usage inside openvino wheel

samples/cpp/benchmark_app/benchmark_app.hpp, samples/cpp/benchmark_app/main.cpp, samples/cpp/benchmark_app/remote_tensors_filling.cpp, samples/cpp/benchmark_app/remote_tensors_filling.hpp, tests/samples_tests/smoke_tests/test_benchmark_app.py
- *Add support for the NPU remote tensor feature in the benchmark app*
- *EISW-131917*
=> Add support for the NPU remote tensor feature in the benchmark app

.github/workflows/dev_cpu_linux_snippets_libxsmm.yml
- *[GHA-SNIPPETS]* added as trigger of workflow with push-events
- *...*
- *ticket-id*
=> [CPU][GHA] PR trigger added

src/plugins/intel_npu/src/plugin/src/plugin.cpp
- When "NPU_USE_NPUW" : "NO"/`false` is passed to `intel_npu::Plugin::compile_model(...)`, it is not removed from incoming OV properties and passes on right to npu plugin's `intel_npu::Config` config causing:
```
[ NOT_FOUND ] Option 'NPU_USE_NPUW' is not supported for current configuration
```
- However, workaround for issue is available: just not passing "NPU_USE_NPUW" : "NO" will result in right behavior is you don't need NPUW.
- *ticket-id*
=> Fixed "NPU_USE_NPUW" : "NO" case

src/plugins/intel_npu/src/al/src/remote_tensor.cpp, src/plugins/intel_npu/src/backend/src/zero_host_tensor.cpp, src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/backend/src/zero_remote_tensor.cpp, src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp, src/plugins/intel_npu/src/plugin/include/metrics.hpp, src/plugins/intel_npu/src/plugin/src/compiled_model.cpp, src/plugins/intel_npu/src/plugin/src/metrics.cpp
- *Fix the NPU coverity issues*
- *EISW-134105*
=> [NPU] Fix NPU coverity issues

src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp, src/plugins/intel_gpu/tests/unit/onednn/utils_test.cpp, src/plugins/intel_gpu/tests/unit/passes/post_optimize_weights.cpp
- Consider group weight format when block inner index of custom traits is created
- 148549
=> [GPU] Consider group weight format when block inner index of custom traits is created

.github/workflows/job_build_linux.yml
- *item1*
- *...*
- *ticket-id*
=> Removed GHA WA for old ONNX versions

.github/workflows/fedora.yml, cmake/features.cmake, cmake/packaging/rpm.cmake, src/bindings/python/CMakeLists.txt, thirdparty/dependencies.cmake
- *item1*
- *...*
- *ticket-id*
=> Updated RPM packages build

cmake/developer_package/packaging/archive.cmake
- *item1*
- *...*
- *ticket-id*
=> Allow to keep RPATH for install tree

src/plugins/intel_gpu/src/plugin/ops/reshape.cpp
- *[149721](https://jira.devtools.intel.com/browse/CVS-149721)*
=> [GPU] Fixed axes normalization for squeeze

.github/workflows/windows_conditional_compilation.yml
=> [CI] [GHA] Add check for `FASTER_BUILD=ON` on Windows

.github/workflows/dev_cpu_linux_snippets_libxsmm.yml, src/plugins/intel_cpu/tests/unit/CMakeLists.txt, src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/lowered/brgemm_blocking.cpp
- *Fixes `Linux CPU Plugin Snippets with LIBXSMM` GHA job*
- *Fixes BrgemmBlocking unit tests when the `ENABLE_SNIPPETS_LIBXSMM_TPP` is set*
- *-*
=> [Snippets][TPP] Fix ov_cpu_unit_tests build & status for LIBXSMM

src/common/low_precision_transformations/include/low_precision/slice.hpp, src/common/low_precision_transformations/src/low_precision.cpp, src/common/low_precision_transformations/src/slice.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/slice_transformation.cpp, src/tests/functional/plugin/shared/include/low_precision_transformations/slice_transformation.hpp, src/tests/functional/plugin/shared/src/low_precision_transformations/slice_transformation.cpp, src/tests/ov_helpers/ov_lpt_models/include/ov_lpt_models/slice.hpp, src/tests/ov_helpers/ov_lpt_models/src/slice.cpp
- *Slice transformation (per-tensor quantization)*
- *CVS-149909*
=> [LPT] Slice transformation

docs/articles_en/learn-openvino/llm_inference_guide/ov-tokenizers.rst
Jira: 149945
Fixed mentioned issues in code snippets in OV Tokenizers article.
=> [DOCS] Fixing code snippet in OV Tokenizers article for master

docs/articles_en/learn-openvino/llm_inference_guide/ov-tokenizers.rst
Port: https://github.com/openvinotoolkit/openvino/pull/26114
Jira: 149945
Fixed mentioned issues in code snippets in OV Tokenizers article.
=> [DOCS] Fixing code snippet in OV Tokenizers article for 24.3

tests/model_hub_tests/pytorch/test_torchvision_models.py
- *Retry torchvision tests on OSError*
- *CVS-149743*
=> Retry torchvision tests on OSError

src/frontends/common/include/openvino/frontend/hash_table.hpp, src/frontends/common/include/openvino/frontend/node_context.hpp, src/frontends/common/include/openvino/frontend/variable.hpp, src/frontends/common/src/hash_table.cpp, src/frontends/common/src/variable.cpp, src/frontends/tensorflow/include/openvino/frontend/tensorflow/hash_table.hpp, src/frontends/tensorflow/include/openvino/frontend/tensorflow/node_context.hpp, src/frontends/tensorflow/include/openvino/frontend/tensorflow/variable.hpp
**Details:** All required routines (Variable, HashTable) are moved to common FE API
**Ticket:** 148101
=> [TF FE][Tokenizers] Avoid dependency from TF FE in tokenizers

src/frontends/tensorflow/docs/supported_ops.md, src/frontends/tensorflow/src/op_table.cpp, src/frontends/tensorflow_common/include/common_op_table.hpp, src/frontends/tensorflow_common/include/utils.hpp, src/frontends/tensorflow_common/src/op/sparse_tensor_dense_add.cpp, src/frontends/tensorflow_common/src/op/sparse_tensor_dense_mat_mul.cpp, src/frontends/tensorflow_common/src/utils.cpp, tests/layer_tests/tensorflow_tests/test_tf_SparseTensorDenseAdd.py
- Support `SparseTensorDenseAdd` operation
- None
=> [TF FE] Support SparseTensorDenseAdd operation

src/common/util/CMakeLists.txt, src/common/util/include/openvino/util/file_util.hpp, src/common/util/src/file_util.cpp, src/core/dev_api/openvino/core/so_extension.hpp, src/frontends/common/src/manager.cpp, src/inference/src/dev/core_impl.cpp, src/inference/tests/functional/ov_core_test.cpp
Reverts openvinotoolkit/openvino#25958
=> Revert "Don't allow to load library linking to another folder"

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/int4_utils.cl, src/plugins/intel_gpu/tests/unit/test_cases/dynamic_quantize_gpu_test.cpp, src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- bugfix fully_connected_bf_tiled kernel to resolve a customer issue 
- CVS-149215
=> [GPU] Bugfix dynamic quantized fully_connected_bf_tiled kernel

.github/workflows/linux_arm64.yml
There are currently test failures
=> Temporarily remove TF layer tests from required on ARM

src/plugins/intel_gpu/src/graph/include/reshape_inst.h
- This issue occurs after https://github.com/openvinotoolkit/openvino/pull/26032
- Fix segfault in layer tests for onnx_tests.test_lstm.TestLSTM
- [CVS-150221](https://jira.devtools.intel.com/browse/CVS-150221)
=> [GPU] Fix segfault in layer tests for onnx_tests.test_lstm.TestLSTM

src/bindings/python/wheel/setup.py
- To fix issues with tokenizers build
- See https://github.com/openvinotoolkit/openvino_tokenizers/pull/229
=> Fixed pattern for patching TBB config files

src/frontends/common/include/openvino/frontend/node_context.hpp
**Details:** Document get_input_by_reference better
=> [Common FE] Document get_input_by_reference better

src/plugins/intel_gpu/src/graph/fully_connected.cpp, src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- *Enable fc 4d for MatMul to calculate 4x2*
- *132334*
=> [GPU] Enable fc 4d for MatMul

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst, docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Minor docs fixes

src/common/transformations/src/transformations/common_optimizations/move_eltwise_up_data_movement.cpp, src/common/transformations/tests/common_optimizations/move_eltwise_up_data_movement_test.cpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- Fixes regression after #24401
- *CVS-150278*
- *CVS-149636*
- *CVS-149620*
=> [GPU] Fix move per channel eltwise pass

cmake/dependencies.cmake, cmake/developer_package/packaging/archive.cmake, cmake/developer_package/packaging/common-libraries.cmake, cmake/developer_package/packaging/debian/debian.cmake, cmake/developer_package/packaging/npm.cmake, cmake/developer_package/packaging/nsis.cmake, cmake/developer_package/packaging/rpm/rpm.cmake, cmake/features.cmake, cmake/templates/OpenVINOConfig.cmake.in, cmake/templates/OpenVINODeveloperPackageConfig.cmake.in, cmake/templates/OpenVINODeveloperPackageConfigRelocatable.cmake.in, src/bindings/python/CMakeLists.txt, src/bindings/python/wheel/CMakeLists.txt, src/bindings/python/wheel/setup.py, src/cmake/ov_parallel.cmake, src/common/util/src/file_util.cpp
- *item1*
- *...*
- *ticket-id*
=> Cmake: generalized THREADING=OMP to work on supported platforms

src/frontends/pytorch/include/openvino/frontend/pytorch/node_context.hpp, src/frontends/pytorch/src/node_context.cpp, src/frontends/pytorch/src/op/log_softmax.cpp, src/frontends/pytorch/src/op/native_multi_head_attention.cpp, src/frontends/pytorch/src/transforms/prim_list_unpack_replacer.cpp, src/frontends/pytorch/src/utils.cpp
- *Remove usage of opset*
- *ticket-id*
=> [PT FE] Remove opset usage

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_quantization.cpp, src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
SD3.int4 static bad accuracy problem, fixed it.
- *146778*
=> [GPU] Fix to get bad groups size bug in compressed_fc static shape.

src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- Removing a ref to fix workload type testing errors
=> [NPU] Removing a ref to fix workload type testing errors

src/core/dev_api/openvino/core/meta_data.hpp, src/core/src/pass/serialize.cpp, src/core/tests/pass/serialization/rt_info_serialization.cpp, src/frontends/ir/src/ir_deserializer.cpp
- Optimization of raw meta data serialization
- Fix legacy meta data creation
- CVS-123381
=> Optimization of raw meta data serialization

docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Simplified snippets setting to work in every environment

docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/bitwise/bitwise-left-shift-15.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/bitwise/bitwise-right-shift-15.rst
- Updated spec of bitwise shift operation for cases where result is undefined.
=> [Spec]: Updated bitwise shift operation specification.

src/plugins/intel_npu/src/plugin/npuw/partitioning/partitioning.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.hpp, src/plugins/intel_npu/src/plugin/npuw/util.cpp
There has a case emerged where now there are vectors of zero points instead of a single value. Adding the support for unpacking such asymmetric zeropoints.
- *134720*
=> NPUW: Support asymmetric weights quantization (Opt B)

tests/layer_tests/tensorflow_tests/test_tf_BinaryComparison.py, tests/layer_tests/tensorflow_tests/test_tf_BinaryOps.py
**Details:** Stabilize binary comparison ops (Equal, NonEqual, Less, etc.) tests on all platforms
**Ticket:** 145795
=> [TF FE] Stabilize binary comparison ops (Equal, NonEqual, Less, etc.) tests on all platforms

src/plugins/intel_gpu/src/plugin/transformations/convert_matmul_to_fc.cpp
+ Added comments what condition should not be converted to fc
- Applied comments from PR#25570
- CVS-146597
=> [GPU] Add detailed explanation about matmul conversion

src/bindings/python/src/openvino/runtime/opset15/__init__.py, src/bindings/python/src/openvino/runtime/opset15/ops.py, src/bindings/python/tests/test_graph/test_ops_binary.py
- Add Python API for `BitwiseLeftShift-15` and `BitwiseRightShift-15`
- 148537
=> [PyOV] Extend Python API with BitwiseLeftShift-15 and BitwiseRightShift-15

docs/requirements.txt
Porting: https://github.com/openvinotoolkit/openvino/pull/26179
=> [DOCS] Bump zipp in docs for 24.3

docs/articles_en/get-started/install-openvino/install-openvino-conda.rst
Changing the order of installation steps.
=> [DOCS] Reorganizing article on installation of OpenVINO from Conda Forge

src/bindings/python/src/openvino/frontend/jax/utils.py, src/frontends/jax/src/translate_session.cpp, src/frontends/jax/src/utils.cpp, src/frontends/jax/src/utils.hpp
**Details:** Report all unsupported operations during conversion by JAX FE. 
**Ticket:** 145586
=> [JAX FE] Report all unsupported operations during conversion

.github/workflows/job_onnx_models_tests.yml
- Set -n to 4 to reduce issues with r2r fails
- 148922
=> [GHA] Reduced amount of workers for ONNXModels test

tests/model_hub_tests/pytorch/hf_transformers_models, tests/model_hub_tests/pytorch/test_llm.py
- *Remove some big models from hf scope*
- *ticket-id*
=> Remove some big models from hf scope

src/frontends/onnx/frontend/src/core/tensor.cpp, src/frontends/onnx/frontend/src/core/tensor.hpp, src/frontends/onnx/frontend/src/utils/common.cpp, src/frontends/onnx/onnx_common/CMakeLists.txt, src/frontends/onnx/onnx_common/src/utils.cpp, src/frontends/onnx/tests/CMakeLists.txt, src/frontends/onnx/tests/models/int4_const.prototxt, src/frontends/onnx/tests/models/int4_input.prototxt, src/frontends/onnx/tests/models/uint4_const.prototxt, src/frontends/onnx/tests/models/uint4_input.prototxt, src/frontends/onnx/tests/onnx_import.in.cpp, src/tests/test_utils/common_test_utils/include/common_test_utils/test_case.hpp, src/tests/test_utils/common_test_utils/src/all_close.cpp, src/tests/test_utils/common_test_utils/src/test_case.cpp
- Added support for accepting int4/uint4 as constant/input
- 139934
=> [ONNX] Added translation for int4/uint4 constants/inputs

src/plugins/intel_gpu/src/runtime/memory_pool.cpp
- Fixed issue of not properly releasing padded memory in the memory pool
- 148552
=> [GPU] Fixed issue of not properly releasing padded memory in the memory pool

tests/model_hub_tests/pytorch/hf_transformers_models, tests/model_hub_tests/pytorch/test_llm.py
- *jais is gated now*
- *aquila already tested in LLM tests*
- *ticket-id*
=> Update models in hub tests

.github/workflows/job_build_windows.yml
=> [CI] [GHA] Correctly set remote cache path if in merge queue

tests/layer_tests/tensorflow_tests/test_tf_AdjustHue.py
**Details:** Stabilize AdjustHue tests on all platforms (ARM, GPU)
=> [TF FE] Stabilize AdjustHue tests on all platforms

docs/articles_en/assets/images/caching_enabled.svg, docs/articles_en/assets/images/caching_times.svg
Fixed alignment in model caching graphs.
=> [DOCS] Fix for issues with alignment in Model Caching graphs for master

docs/articles_en/assets/images/caching_enabled.svg, docs/articles_en/assets/images/caching_times.svg
Port from https://github.com/openvinotoolkit/openvino/pull/26273
Fixed alignment in model caching graphs.
=> [DOCS] Fix for issues with alignment in Model Caching graphs for 24.3

src/plugins/intel_gpu/src/graph/crop.cpp, src/plugins/intel_gpu/src/graph/include/reshape_inst.h, src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- Do not apply crop optimization for squeeze if the crop axis matches the squeeze axis
=> [GPU] Do not apply crop optimization for squeeze if the crop axis matches the squeeze axis

src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/src/ov_plugin/properties.cpp, src/tests/functional/plugin/shared/include/base/ov_behavior_test_utils.hpp
- *item1*
- *...*
- *ticket-id*
=> Fix crash caused by empty string

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- *Change log level to debug*
- *...*
- *ticket-id*
=> [NPU] Change log level to debug

src/frontends/paddle/tests/CMakeLists.txt
- To avoid cmake warnings when PDPD is not installed
=> Don't call paddle module if it's not found

src/plugins/intel_gpu/tests/unit/passes/prepare_primitive_fusing_test.cpp
- Fix data size in test
- [*CVS-148605*](https://jira.devtools.intel.com/browse/CVS-148605)
=> [GPU] Fix data size in test

src/frontends/pytorch/src/frontend.cpp, src/frontends/pytorch/src/translate_session.cpp
- *Fix issue with not set decoder type rt_info*
- *Remove frontend rt_info from model*
- *ticket-id*
=> [PT FE] Fix rt_info for decoder type

docs/dev/pypi_publish/pre-release-note.md, docs/dev/pypi_publish/pypi-openvino-dev.md, docs/dev/pypi_publish/pypi-openvino-rt.md
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Remove pre-release note 

docs/dev/pypi_publish/pypi-openvino-rt.md
Port from https://github.com/openvinotoolkit/openvino/pull/25746
A proposition of changes to the pypi page
=> [DOCS] pypi publishing page adjustment - 24.4

src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
- backporting https://github.com/openvinotoolkit/openvino/pull/26284 to releases/2024/4
- 146778
=> [GPU] unfusing invalid eltwise fused onednn fc layers on release branches

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp, src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
- New debug config for dumping verbose log into file
=> [GPU] dump verbose log to file

tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_stackedrnncells.py
**Details:** Stabilize TF2 Keras layer test for StackedRNNCells
=> [TF FE] Stabilize TF2 Keras layer test for StackedRNNCells

.github/workflows/job_pytorch_models_tests.yml
=> [GHA] Increase timeout for PyTorch Models tests in precommit

src/bindings/c/src/common.h, src/plugins/intel_cpu/src/plugin.cpp, src/plugins/intel_cpu/src/serialize.cpp
- Fix CS issues
- *...*
- *ticket-id*
=> Fix CS issues

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/softmax_gpu_bf.cl
- Add reqd_work_group_size attribute to softmax bf kernel
- Slight performance improvement
- 151211
=> [GPU] Add reqd_work_group_size attribute to softmax bf kernel

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp, src/plugins/intel_gpu/src/graph/graph_optimizer/add_onednn_optimization_attributes.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/basic_memory_dependencies.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/fuse_primitives_with_layout.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/oooq_memory_dependencies.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/pre_replace_deconv.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/select_preferred_formats.cpp, src/plugins/intel_gpu/src/graph/graph_optimizer/skipped_branch_memory_dependencies.cpp, src/plugins/intel_gpu/src/graph/include/pass_manager.h, src/plugins/intel_gpu/src/graph/include/program_node.h, src/plugins/intel_gpu/src/graph/program.cpp, src/plugins/intel_gpu/tests/unit/dynamic_execution/bounded_shape_mem_alloc.cpp, src/plugins/intel_gpu/tests/unit/passes/add_onednn_optimization_attributes_test.cpp, src/plugins/intel_gpu/tests/unit/passes/fuse_primitives_with_layout.cpp, src/plugins/intel_gpu/tests/unit/passes/handle_reshape.cpp, src/plugins/intel_gpu/tests/unit/passes/post_optimize_weights.cpp, src/plugins/intel_gpu/tests/unit/passes/prepare_padding_test.cpp, src/plugins/intel_gpu/tests/unit/passes/prepare_primitive_fusing_test.cpp, src/plugins/intel_gpu/tests/unit/passes/prepare_quantization.cpp, src/plugins/intel_gpu/tests/unit/passes/remove_redundant_reorders_tests.cpp, src/plugins/intel_gpu/tests/unit/passes/reorder_inputs_test.cpp, src/plugins/intel_gpu/tests/unit/passes/select_preferred_formats_test.cpp, src/plugins/intel_gpu/tests/unit/passes/test_module_fusing_reorder.cpp, src/plugins/intel_gpu/tests/unit/test_cases/canonicalization_gpu_test.cpp
- Layout optimizer is made a member of program class to be able to use it during implementation selection
=> [GPU] Layout optimizer as program member

src/frontends/tensorflow_common/src/op/leaky_relu.cpp, tests/layer_tests/tensorflow_tests/test_tf_LeakyRelu.py, tests/layer_tests/tensorflow_tests/test_tf_Softmax.py
**Details:** Handle correctly scalar case for LeakyRelu.
=> [TF FE] Fix LeakyRelu translator and stabilize tests for it

src/plugins/intel_gpu/src/plugin/ops/gather.cpp, src/plugins/intel_gpu/tests/functional/single_layer_tests/gather_indices_input.cpp
- Add indices constant check for crop primitive selection in CreateGatherOpBase
- 150120
=> [GPU] Add indices constant check for crop primitive selection in CreateGatherOpBase

docs/optimization_guide/nncf/ptq/code/ptq_aa_onnx.py, docs/optimization_guide/nncf/ptq/code/ptq_onnx.py
- Updated documentation on onnx quantization ### Tickets:
- https://github.com/openvinotoolkit/openvino/issues/26192
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port onnx changes

src/common/snippets/src/pass/softmax_reshape_elimination.cpp, src/common/snippets/tests/src/pass/softmax_reshape_elimination.cpp
- *Added dynamic case support in the pass "SoftmaxReshapeElimination" when last (reduction) dimension is static - aligned with "MHATokenization" pass*
- *Covered by unet test*
- *151134*
=> [Snippets] Supported dynamic case in SoftmaxReshapeElimination

.github/workflows/job_pytorch_models_tests.yml, tests/model_hub_tests/pytorch/test_edsr.py
- *item1*
- *...*
- *ticket-id*
=> [PT FE] Run EDSR tests in parallel

tests/model_hub_tests/pytorch/test_llm.py
- *Update LLm hub tests*
- *ticket-id*
=> [PT FE] Update LLm hub tests

tests/model_hub_tests/pytorch/test_torchvision_models.py, tests/model_hub_tests/pytorch/torchvision_models
- *item1*
- *...*
- *ticket-id*
=> [PT FE] Update torchvision tests with quantized and detection models

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_bfyx_os_iyx_osv16.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp, src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
=> [GPU] out-of-bound access of convolution kernel

src/plugins/intel_npu/src/al/include/npu_private_properties.hpp, src/plugins/intel_npu/src/backend/include/zero_executor.hpp, src/plugins/intel_npu/src/backend/include/zero_memory.hpp, src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp, src/plugins/intel_npu/src/backend/src/zero_device.cpp, src/plugins/intel_npu/src/backend/src/zero_executor.cpp, src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/backend/src/zero_memory.cpp, src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp, src/plugins/intel_npu/src/plugin/src/plugin.cpp, src/plugins/intel_npu/tests/functional/behavior/work_with_devices.hpp, src/plugins/intel_npu/tests/functional/common/npu_test_env_cfg.cpp, src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp, src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp, src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- *Remove dKmb support from plugin*
- *CVS-150846*
=> [NPU] Remove dKmb support from the plugin

.github/workflows/coverage.yml, .github/workflows/linux_conditional_compilation.yml, .github/workflows/windows_conditional_compilation.yml
- *item1*
- *...*
- *ticket-id*
=> GHA: removed hardcoded build type

src/common/snippets/include/snippets/lowered/pass/brgemm_blocking.hpp, src/common/snippets/src/lowered/pass/brgemm_blocking.cpp, src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_cpu_blocking.cpp, src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_cpu_blocking.hpp, src/plugins/intel_cpu/src/transformations/tpp/x64/pass/lowered/brgemm_tpp_blocking.cpp, src/plugins/intel_cpu/src/transformations/tpp/x64/pass/lowered/brgemm_tpp_blocking.hpp, src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/lowered/brgemm_blocking.cpp
- *Set `n_blk=24` on avx2 for `BrgemmCPU`*
- *151064*
=> [Snippets][CPU] Set N_blk=24 for BRGEMM on AVX2

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_bfyx_os_iyx_osv16.cl, src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- out-of-bound access from convolution kernel for input and weight
- Dynamic test case was updated to compare against reference kernel
- 150360
=> [GPU] out-of-bound access from convolution kernel

tests/layer_tests/jax_tests/jax_layer_test_class.py, tests/layer_tests/jax_tests/test_add.py, tests/layer_tests/jax_tests/test_broadcast_in_dim.py, tests/layer_tests/jax_tests/test_concatenate.py, tests/layer_tests/jax_tests/test_copy.py, tests/layer_tests/jax_tests/test_device_put.py, tests/layer_tests/jax_tests/test_div.py, tests/layer_tests/jax_tests/test_exp.py, tests/layer_tests/jax_tests/test_integer_pow.py, tests/layer_tests/jax_tests/test_mul.py, tests/layer_tests/jax_tests/test_reduce.py, tests/layer_tests/jax_tests/test_reshape.py, tests/layer_tests/jax_tests/test_rsqrt.py, tests/layer_tests/jax_tests/test_slice.py, tests/layer_tests/jax_tests/test_sqrt.py, tests/layer_tests/jax_tests/test_squeeze.py, tests/layer_tests/jax_tests/test_stop_gradient.py, tests/layer_tests/jax_tests/test_sub.py, tests/layer_tests/jax_tests/test_tanh.py, tests/layer_tests/jax_tests/test_transpose.py
**Details:** We ensure that more JAX operations are supported via TF FE path
=> [TF FE] Extend JAX layer tests precommit via TF FE path

src/plugins/intel_npu/src/plugin/src/backends.cpp
- *Change log level from error to warning if backend is not found*
- *...*
- *CVS-149734*
=> Change log level from error to warning if backend is not found

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl, src/plugins/intel_gpu/src/plugin/ops/paged_attention.cpp
- This PR is a copy of https://github.com/openvinotoolkit/openvino/pull/26389 from 2024.4 release branch
- It fixes functional issue of Qwen1.5-7b due to unexpected dynamic dimension of query input, and fixes the accuracy of Qwen2 model caused by the order of QK*Scale calculation
- [CVS-151304](https://jira.devtools.intel.com/browse/CVS-151304)
=> [GPU] Fix accuracy issue of Qwen2 model

src/bindings/python/wheel/CMakeLists.txt
- Split wheel build and build cleanup
- Do not fail build if cleanup step unsuccessful 
- *150518*
=> [WHEEL] Split wheel build and build cleanup

.github/workflows/mac.yml
- *item1*
- *...*
- *ticket-id*
=> Fixed macOS GHA build

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp
- *legacy of https://github.com/openvinotoolkit/openvino/pull/25716*
- *...*
- *146712*
=> [GPU] minor fix for paddings

tests/layer_tests/tensorflow_tests/test_tf_ComplexAbs.py, tests/layer_tests/tensorflow_tests/test_tf_ComplexFFT.py
**Details:** Stabilize layer tests for ComplexFFT ops and ComplexAbs on all platforms
=> [TF FE] Stabilize layer tests for ComplexFFT ops and ComplexAbs on all platforms

.github/workflows/linux_conditional_compilation.yml, .github/workflows/windows_conditional_compilation.yml
- *item1*
- *...*
- *ticket-id*
=> Properly use OneCore toolchain in Windows CC

src/core/dev_api/openvino/core/so_extension.hpp, src/core/include/openvino/core/op_extension.hpp, src/core/src/so_extension.cpp
- Ported https://github.com/openvinotoolkit/openvino/pull/26437
=> Fixed extensions (tokenizers) loading on Android

tests/layer_tests/ovc_python_api_tests/test_tf_output_order.py
**Details:** Established a bug in TF itself.
**Ticket:** 124436
=> [TF FE] Change a root-cause for failing cases

src/bindings/python/src/pyopenvino/graph/node.cpp, src/bindings/python/tests/test_graph/test_loop.py, src/bindings/python/tests/test_graph/test_node_factory.py
- *item1*
- *...*
- *ticket-id*
=> [PyOV] remove deprecated api

docs/articles_en/get-started/install-openvino/install-openvino-npm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst
Adding info on: `Model.getOutputElementType`, `Model.clone`, `CompiledModel.getProperty`, `CompiledModel.setProperty`.
=> [DOCS] Updating NodeJS API docs

docs/articles_en/get-started/install-openvino/install-openvino-npm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst
Porting:
https://github.com/openvinotoolkit/openvino/pull/26445
=> [DOCS] Updating NodeJS docs for 2024.4

tests/layer_tests/pytorch_tests/test_quantize.py
- *Use static seed for quantized tests*
- *CVS-151071*
=> [PT FE] Use static seed for quantized tests

docs/articles_en/assets/snippets/ov_matcher_pass.py, docs/articles_en/assets/snippets/ov_model_pass.py, docs/articles_en/documentation/openvino-extensibility/transformation-api/matcher-pass.rst, docs/articles_en/documentation/openvino-extensibility/transformation-api/model-pass.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/26008
=> [DOCS] Updating Transformation API docs

docs/articles_en/assets/snippets/ov_matcher_pass.py, docs/articles_en/assets/snippets/ov_model_pass.py
Backporting: https://github.com/openvinotoolkit/openvino/pull/26461
=> [DOCS] Updating Transformations API docs

.github/workflows/dev_cpu_linux_snippets_libxsmm.yml, src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- *Enable functional and unit tests in the Libxsmm GHA job*
- *151223*
=> [Snippets] Enable libxsmm GHA job

tests/model_hub_tests/performance_tests/nightly_models.skip
- added cientnet/b2/feature-vector to skip list due to url error
- 151259
=> add failed model to the skip list

docs/articles_en/assets/snippets/ov_caching.cpp, docs/articles_en/assets/snippets/ov_caching.py, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-latency/model-caching-overview.rst, src/bindings/c/include/openvino/c/ov_property.h, src/inference/include/openvino/runtime/properties.hpp
- *add example of cache_encryption_callbacks in document*
- *CVS-123336*
=> [DOC] add cache_encryption_callbacks example in guide

tests/layer_tests/common/utils/tf_utils.py, tests/layer_tests/tensorflow_tests/test_tf_Xlog1py.py, tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py
**Details:** Stabilize layer tests for Xlogy and Xlog1py on all platforms
=> [TF FE] Stabilize layer tests for Xlogy and Xlog1py on all platforms

src/frontends/tensorflow_common/src/op/linspace.cpp, tests/layer_tests/tensorflow_tests/test_tf_LinSpace.py
**Details:** Fix translator for LinSpace operation and stabilize tests for it on all platforms
=> [TF FE] Fix translator for LinSpace operation and stabilize tests for it on all platforms

src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp, src/plugins/intel_gpu/tests/unit/passes/prepare_primitive_fusing_test.cpp, src/plugins/intel_gpu/tests/unit/test_cases/border_gpu_test.cpp
* Fix out of bound memory in tests cases, phase1
=> [GPU] Fix random tests

src/plugins/intel_gpu/tests/unit/module_tests/network_test.cpp
- Check for zero intermediate buffers
- N/A
=> [GPU] fix zero array in network unit test

docs/articles_en/get-started/install-openvino/install-openvino-docker-linux.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port Docker images note

docs/articles_en/get-started/install-openvino/install-openvino-docker-linux.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] GenAI Docker images note

docs/articles_en/about-openvino.rst, docs/articles_en/about-openvino/key-features.rst, docs/sphinx_setup/_static/css/homepage_style.css, docs/sphinx_setup/index.rst
New Key Features article for the documentation.
=> [DOCS] New Key Features in docs - master

docs/articles_en/about-openvino.rst, docs/articles_en/about-openvino/key-features.rst, docs/sphinx_setup/_static/css/homepage_style.css, docs/sphinx_setup/index.rst
Porting:
https://github.com/openvinotoolkit/openvino/pull/26308
=> [DOCS] Adding Key Features article to docs

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_b_fs_yx_fsv_16_32_imad_dw.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_yx_fsv_16_32_imad_dw.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_yx_fsv_16_32_imad_dw.hpp, src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- *[148550](https://jira.devtools.intel.com/browse/CVS-148550)*
=> [GPU] Added support fsv16/32 depthwise shape agnostic convolution

docs/articles_en/openvino-workflow/model-preparation.rst, docs/articles_en/openvino-workflow/model-preparation/conversion-parameters.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-jax.rst, docs/articles_en/openvino-workflow/model-preparation/convert-model-to-ir.rst
**Details:** Document Support of JAX/Flax models by OpenVINO
**Ticket:** 150970
=> [JAX FE][DOCS] Document Support of JAX/Flax models by OpenVINO

src/common/snippets/include/snippets/lowered/pass/init_loops.hpp, src/common/snippets/include/snippets/runtime_configurator.hpp, src/common/snippets/include/snippets/utils/loop_utils.hpp, src/common/snippets/include/snippets/utils/utils.hpp, src/common/snippets/src/lowered/loop_info.cpp, src/common/snippets/src/lowered/pass/init_loops.cpp, src/common/snippets/src/lowered/pass/split_loops.cpp, src/common/snippets/src/runtime_configurator.cpp, src/common/snippets/src/utils/loop_utils.cpp
=> [Snippets] Dynamic SplitDimensionM leftovers

src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
- Fix out of bound access in reorder
=> [GPU] Fix OOB access in reorder

src/plugins/intel_gpu/tests/unit/test_cases/condition_gpu_test.cpp
=> [GPU] Fix unit tests ph2

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/documentation/legacy-features/model-zoo.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-efficient-det.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-retina-net.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-yolo.rst, docs/articles_en/documentation/openvino-ecosystem/openvino-security-add-on.rst, docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations.rst, docs/articles_en/documentation/openvino-security.rst, docs/articles_en/learn-openvino/openvino-samples/bert-benchmark.rst, docs/articles_en/learn-openvino/openvino-samples/hello-reshape-ssd.rst, docs/articles_en/learn-openvino/openvino-samples/sync-benchmark.rst, docs/articles_en/learn-openvino/openvino-samples/throughput-benchmark.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/general-optimizations.rst, docs/notebooks/explainable-ai-1-basic-with-output.rst, docs/notebooks/handwritten-ocr-with-output.rst, docs/notebooks/hello-detection-with-output.rst, docs/notebooks/hello-segmentation-with-output.rst, docs/notebooks/hello-world-with-output.rst, docs/notebooks/optical-character-recognition-with-output.rst, docs/notebooks/person-tracking-with-output.rst, docs/notebooks/tensorflow-classification-to-openvino-with-output.rst, docs/notebooks/vision-monodepth-with-output.rst
Updating reference to Open Model Zoo repository.
=> [DOCS] Updating references to OMZ in docs

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/documentation/legacy-features/model-zoo.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-efficient-det.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-retina-net.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-tensorflow-yolo.rst, docs/articles_en/documentation/openvino-ecosystem/openvino-security-add-on.rst, docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations.rst, docs/articles_en/documentation/openvino-security.rst, docs/articles_en/learn-openvino/openvino-samples/bert-benchmark.rst, docs/articles_en/learn-openvino/openvino-samples/hello-reshape-ssd.rst, docs/articles_en/learn-openvino/openvino-samples/sync-benchmark.rst, docs/articles_en/learn-openvino/openvino-samples/throughput-benchmark.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/general-optimizations.rst, docs/notebooks/explainable-ai-1-basic-with-output.rst, docs/notebooks/handwritten-ocr-with-output.rst, docs/notebooks/hello-detection-with-output.rst, docs/notebooks/hello-segmentation-with-output.rst, docs/notebooks/hello-world-with-output.rst, docs/notebooks/optical-character-recognition-with-output.rst, docs/notebooks/person-tracking-with-output.rst, docs/notebooks/tensorflow-classification-to-openvino-with-output.rst, docs/notebooks/vision-monodepth-with-output.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/26523
=> [DOCS] Updating references to OMZ in docs for 24.4

tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_dot.py
**Details:** Stabilize tf.keras.layers.Dot layer tests on all platforms
**Ticket:** 151986
=> [TF FE] Stabilize tf.keras.layers.Dot layer tests on all platforms

.github/actions/common/artifact_utils.py, .github/actions/common/constants.py
To avoid sudden breaking of CI's in repos retrieving these artifacts via OV provider or Jenkins
- 152261
=> [GHA] Artifact folder names consistency check

src/plugins/intel_gpu/docs/gpu_plugin_driver_troubleshooting.md
- *item1*
- *...*
- *[CVS-138065](https://jira.devtools.intel.com/browse/CVS-138065)*
=> [GPU] OpenCL headers compatibility comment

.github/labeler.yml, .github/workflows/job_jax_models_tests.yml, .github/workflows/ubuntu_22.yml, src/bindings/python/src/openvino/frontend/jax/utils.py, src/frontends/jax/src/op_table.cpp, tests/constraints.txt, tests/layer_tests/jax_tests/test_erf.py, tests/model_hub_tests/jax/conftest.py, tests/model_hub_tests/jax/hf_transformers_models, tests/model_hub_tests/jax/jax_utils.py, tests/model_hub_tests/jax/requirements.txt, tests/model_hub_tests/jax/test_hf_transformers.py
**Details:** Add JAX Model Hub tests into GHA
**Ticket:** 142882
=> [JAX FE][GHA] Add JAX/Flax Model Hub tests into GHA

.github/workflows/ubuntu_20.yml
- Switch off GPU tests in GHA
- 152280
=> [GHA] Switch off GPU tests in precommit, post-commit and nightly

src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp, src/plugins/intel_gpu/src/graph/include/primitive_inst.h, src/plugins/intel_gpu/src/graph/paged_attention.cpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_kv_cache_update_ref.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp
- This PR adds additional kernel variation for proper speculative decoding handling and minor improvements of paged attention
- [CVS-138903](https://jira.devtools.intel.com/browse/CVS-138903)
=> [GPU] Fixes for speculative decoding

.github/workflows/android_arm64.yml
- Fix for https://github.com/openvinotoolkit/openvino/pull/26546
- CVS-152409
=> [GHA] Remove GenAI build from Android arm64

docs/CMakeLists.txt, docs/scripts/tests/suppress_warnings.txt, docs/sphinx_setup/api/api_reference.rst, docs/sphinx_setup/api/genai_api/api.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Add GenAI OV API reference

src/plugins/intel_gpu/src/graph/impls/cpu/broadcast.cpp
- Fixes sporadic crash of `KVCacheTests.smoke_multipleIterations_stateful_gather_with_initializer_cached` test
- https://jira.devtools.intel.com/browse/CVS-133748
=> [GPU] Fix broadcast save/load impls

tests/layer_tests/tensorflow_tests/test_tf_ReduceArithmeticOps.py
**Details:** Skip layer test for Prod on complex tensors on ARM due to accuracy issue
=> [TF FE] Skip layer test for Prod on complex tensors on ARM due to accuracy issue

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/swiglu_gpu_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/swiglu/swiglu_kernel_base.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/swiglu/swiglu_kernel_base.h, src/plugins/intel_gpu/src/kernel_selector/kernels/swiglu/swiglu_kernel_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/swiglu/swiglu_kernel_opt.h, src/plugins/intel_gpu/src/kernel_selector/kernels/swiglu/swiglu_kernel_selector.cpp
- Implement Swiglu OPT kernel
- Use fast erf function instead of slow OpenCL erf
- 149484
=> [GPU] Swiglu OPT kernel implementation

src/plugins/intel_cpu/tools/commit_slider/tests/commit_slider_test.py, src/plugins/intel_cpu/tools/commit_slider/tests/test_data.py, src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/fbv_bm_latency.cpp, src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/tests_res.json, src/plugins/intel_cpu/tools/commit_slider/utils/cfg.json, src/plugins/intel_cpu/tools/commit_slider/utils/cfg_samples/bm_arm_mac.json, src/plugins/intel_cpu/tools/commit_slider/utils/helpers.py, src/plugins/intel_cpu/tools/commit_slider/utils/modes.py
- *item1*
- *...*
- *ticket-id*
=> [Commit slider] ARM + MAC support

tests/layer_tests/py_frontend_tests/test_torchvision_preprocessor.py, tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
- *Rerun tests if sporadic issue in tracing happens*
- *CVS-151277*
=> [TEST] Rerun tests if sporadic issue in tracing happens

src/plugins/intel_gpu/src/graph/fully_connected.cpp, src/plugins/intel_gpu/tests/unit/fake_alignment/fc_fake_alignment_test.cpp
- *[148550](https://jira.devtools.intel.com/browse/CVS-148550)*
=> [GPU] Increasing conditions for using fake_aligned shapes

docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port ov archive release version 

docs/articles_en/documentation/legacy-features/install-dev-tools.rst, docs/articles_en/documentation/openvino-security.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-npm.rst, docs/articles_en/get-started/install-openvino/install-openvino-pip.rst, docs/articles_en/learn-openvino/openvino-samples/get-started-demos.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/26620
=> [DOCS] Remove IoT Devkit references from docs for 24.4

src/plugins/intel_npu/src/al/include/intel_npu/al/config/npuw.hpp, src/plugins/intel_npu/src/al/include/npuw_private_properties.hpp, src/plugins/intel_npu/src/al/src/config/npuw.cpp, src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/partitioning.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.hpp, src/plugins/intel_npu/src/plugin/npuw/util.cpp, src/plugins/intel_npu/src/plugin/npuw/util.hpp
- When possible, do horizontal fusion for 2-3 MMs connected to the same source.
- Also reword the GQ pattern for non-GPTQ models, now it is as performant as the MLIR one.
- E-137604 (merge)
- E-138565 (DQ update)
=> NPUW: Merge parallel MMs, if possible + Update GQ transformation

.github/workflows/windows_conditional_compilation.yml
- Set timeout for CC_Build Windows job
- *150783*
=> [GHA] Set CC_Build timeout

tests/layer_tests/pytorch_tests/test_fake_quantize.py, tests/layer_tests/pytorch_tests/test_floor_divide.py, tests/layer_tests/pytorch_tests/test_quantized_add.py, tests/layer_tests/pytorch_tests/test_quantized_add_relu.py, tests/layer_tests/pytorch_tests/test_quantized_cat.py, tests/layer_tests/pytorch_tests/test_quantized_convnd.py, tests/layer_tests/pytorch_tests/test_quantized_hardswish.py, tests/layer_tests/pytorch_tests/test_quantized_linear.py, tests/layer_tests/pytorch_tests/test_quantized_mul.py
- *Use fixed seed for quantized tests*
- *CVS-152410*
- *CVS-138583*
=> [TESTS] Use fixed seed for quantized tests

docs/openvino_sphinx_theme/openvino_sphinx_theme/templates/layout.html, docs/sphinx_setup/_static/css/custom.css, docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] PORT Page adjustments for 24 4

.github/workflows/job_build_windows.yml, .github/workflows/job_samples_tests.yml, .github/workflows/windows_conditional_compilation.yml
- *item1*
- *...*
- *ticket-id*
=> [GHA] Use explicitly 2019 / 2022 toolsets

docs/sphinx_setup/_static/css/custom.css
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Fix css

docs/sphinx_setup/_static/css/custom.css
- *item1*
- *...*
- *ticket-id*
=> [Docs] Css fix

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add JSON parsing error to errors to look for in rerunner 

src/plugins/intel_npu/src/al/include/npu.hpp, src/plugins/intel_npu/src/al/src/npu.cpp, src/plugins/intel_npu/src/backend/include/zero_backend.hpp, src/plugins/intel_npu/src/backend/include/zero_device.hpp, src/plugins/intel_npu/src/backend/include/zero_executor.hpp, src/plugins/intel_npu/src/backend/include/zero_init.hpp, src/plugins/intel_npu/src/backend/include/zero_profiling.hpp, src/plugins/intel_npu/src/backend/include/zero_types.hpp, src/plugins/intel_npu/src/backend/include/zero_wrappers.hpp, src/plugins/intel_npu/src/backend/src/zero_backend.cpp, src/plugins/intel_npu/src/backend/src/zero_device.cpp, src/plugins/intel_npu/src/backend/src/zero_executor.cpp, src/plugins/intel_npu/src/backend/src/zero_init.cpp, src/plugins/intel_npu/src/backend/src/zero_profiling.cpp, src/plugins/intel_npu/src/backend/src/zero_wrappers.cpp, src/plugins/intel_npu/src/compiler/include/zero_compiler_in_driver.hpp, src/plugins/intel_npu/src/compiler/src/driver_compiler_adapter.cpp, src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp, src/plugins/intel_npu/src/plugin/include/backends.hpp, src/plugins/intel_npu/src/plugin/include/metrics.hpp, src/plugins/intel_npu/src/plugin/src/backends.cpp, src/plugins/intel_npu/src/plugin/src/metrics.cpp, src/plugins/intel_npu/tests/functional/internal/overload/compile_and_infer.hpp
- *Implement extension versions properly for each method*
- *EISW-61724*
=> [NPU] Implement extension versions properly for each method

docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst, docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression/microscaling-quantization.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device.rst
Providing info about support for MXFP4 data format in quantization on CPU. This PR addresses JIRA ticket no. 151042.
=> [DOCS] Documenting the support for MXFP4 data format.

docs/articles_en/about-openvino/additional-resources/terms-of-use.rst, docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst, docs/sphinx_setup/api/api_reference.rst, docs/sphinx_setup/api/nodejs_api/nodejs_api.rst
port:
https://github.com/openvinotoolkit/openvino/pull/26529
https://github.com/openvinotoolkit/openvino/pull/26659
=> Docs release notes 24.4 mstr

docs/sphinx_setup/api/ie_python_api/api.rst
- *item1*
- *...*
- *ticket-id*
=> [Docs] Add ov.experimental to docs

src/plugins/intel_cpu/src/extension.cpp
- *Could not deserialize RMS node during reading model from cache*
- *...*
- *152740*
=> [CPU] Could not deserialize the RMS node

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add `lost communication with the server` to errors to look for in rerunner

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device/remote-tensor-api-gpu-plugin.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/26632
=> [DOCS] Add snippets for remote tensor creation for 24.4

docs/sphinx_setup/api/ie_python_api/api.rst
- cherry-pick https://github.com/openvinotoolkit/openvino/pull/26677
- *ticket-id*
=> [Docs] Add ov.experimental to docs (#26677)

docs/sphinx_setup/_static/js/hide_banner.js, docs/sphinx_setup/_templates/baner.html
- *item1*
- *...*
- *ticket-id*
=> DOCS Port for Fix path to hidden.json to 24 4

.github/workflows/linux_sanitizers.yml
- Tested in https://github.com/openvinotoolkit/openvino/pull/26634
- *144163*
=> [GHA] Enable UndefinedBehavior sanitizer

src/frontends/tensorflow_common/src/op/arg_min_max.cpp, tests/layer_tests/tensorflow_tests/test_tf_ArgMinMax.py
**Details:** Fix ArgMin and ArgMax translators and stabilize tests
=> [TF FE] Fix ArgMin and ArgMax translators and stabilize tests

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device/remote-tensor-api-gpu-plugin.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/26744
=> [DOCS] D3D9 and D3D11 surface sharing support

docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst, docs/articles_en/learn-openvino/llm_inference_guide/genai-guide-npu.rst, docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst, docs/sphinx_setup/_static/download/supported_models.csv
port: https://github.com/openvinotoolkit/openvino/pull/26742
=> [DOCS] post-release pass2-mstr

src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.cpp, src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_fc_horizontal_fusion.cpp, src/plugins/intel_gpu/tests/unit/transformations/horizontal_fc_fusion_test.cpp
- Fixed error on fused fc with biases when all the bias shapes are the same 
- Also restricted fusing only to the case when the bias is channel only 
- *ticket-id*
=> [GPU] Fixed error on fused fc with fused bias when all the bias shapes are same

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp, src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- *item1*
- *...*
- CVS-150930
=> [GPU] Modify fc_gpu_bf_tiled kernel to enable weight zp

docs/sphinx_setup/_static/css/banner.css, docs/sphinx_setup/_static/css/custom.css, docs/sphinx_setup/_static/html/banner_data.json, docs/sphinx_setup/_static/js/custom.js, docs/sphinx_setup/_static/js/hide_banner.js
=> [DOCS] changes for port to master

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add `Upload progress stalled` to errors to look for in rerunner

src/plugins/intel_npu/src/al/include/intel_npu/al/icompiler.hpp, src/plugins/intel_npu/src/backend/include/zero_types.hpp, src/plugins/intel_npu/src/compiler/include/driver_compiler_adapter.hpp, src/plugins/intel_npu/src/compiler/include/zero_compiler_in_driver.hpp, src/plugins/intel_npu/src/compiler/src/driver_compiler_adapter.cpp, src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp, src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
- *Duplicates PR https://github.com/openvinotoolkit/openvino/pull/26754*
- *Add support for new L0 API 1.7*
- *Change return type of `getCompiledNetwork` to new custom `CompiledNetwork` container*
- *[151912](https://jira.devtools.intel.com/browse/CVS-151912)*
=> [`intel_npu`] [`DUPLICATE`] [`master`] [`reduce memory consumption`] Avoid creating a blob copy while exporting a compiled model

src/plugins/intel_npu/src/plugin/npuw/partitioning/online/compiler.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/snapshot.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/compute.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/compute.hpp
Following up with i4 patterns on https://github.com/openvinotoolkit/openvino/pull/25679
=> [NPUW] Support i4 patterns for compute pipeline

src/plugins/intel_npu/src/al/include/intel_npu/al/config/common.hpp, src/plugins/intel_npu/src/backend/include/zero_device.hpp, src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp, src/plugins/intel_npu/tools/single-image-test/main.cpp
Extend BF16 logic in NPU plugin.
To what it's worth, functional tests on NPU side are running with these changes, although there are some opens in NPU compiler which cause an accuracy;
Until then this PR should be merged to ease up integration on our side.
[ - *ticket-id*](https://jira.devtools.intel.com/browse/EISW-140090)
=> Extend support to BF16 in npu plugin

.github/workflows/code_style.yml, .github/workflows/labeler.yml
Continuation of https://github.com/openvinotoolkit/openvino/pull/26749
=> [GHA] Avoid running actions in forks - leftovers

src/plugins/intel_cpu/src/nodes/interpolate.cpp, src/plugins/intel_cpu/src/nodes/mvn.cpp, src/plugins/intel_cpu/src/nodes/roi_align.cpp
- *Overflowed integer argument (INTEGER_OVERFLOW)*
- *CVS-153060*
=> [CPU]Fix coverity scan issues

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Resolved an error with Splider

src/plugins/intel_npu/README.md, src/plugins/intel_npu/tests/functional/README.md
- *Remove any reference to dKmb from the doc*
- **
=> [NPU] Remove any reference to dKmb from the doc

tests/constraints.txt, tests/model_hub_tests/pytorch/requirements.txt
Ported https://github.com/openvinotoolkit/openvino/pull/26769/ 
- *ticket-id*
=> [MERGE][TESTS] Fix issue with new version of easyocr 

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Quick Fix

src/plugins/intel_cpu/src/sub_memory_manager.hpp
- *avoid member dangling by setting default value*
- *...*
- *153060*
=> fix uninitialized object

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [Docs] Port for Splider bug to 24 4

.github/workflows/workflow_rerunner.yml
Another leftover of https://github.com/openvinotoolkit/openvino/pull/26749
=> [GHA] Skip tests rerunner in forks

src/plugins/intel_npu/src/plugin/npuw/partitioning/partitioning.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.hpp
- Nothing special, just a couple new patterns
- Reduce via Add with Multiply under loop is used for N-tok cases as opposed to 1-tok case
- E-138545
=> NPUW: Support DQ for GQ & GPTQ prefills

docs/sphinx_setup/_static/js/custom.js
Port for 
https://github.com/openvinotoolkit/openvino/pull/26802/files
=> [DOCS] Main changes

src/bindings/python/src/openvino/runtime/opset13/ops.py, src/bindings/python/tests/test_graph/test_constant.py
- When const is created from opset, it couldn't be created from Tensor. Added an "overloading".
- CVS-153553
=> [PyOV] Consts ops from Tensor

src/frontends/jax/src/op/binary_op.cpp, src/frontends/jax/src/op_table.cpp, tests/layer_tests/jax_tests/test_binary_comparison.py, tests/layer_tests/jax_tests/test_negative.py
- support jax.lax.lt, jax.lax.le and jax.lax.neg operation
- enable unit tests for new operations
- #26577
=> [JAX FE] Support lt, le, and neg operations

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Splider fix

docs/sphinx_setup/_static/html/banner_data.json
- *item1*
- *...*
- *ticket-id*
=> Docs Update banner change for nightly

.github/workflows/windows_vs2019_release.yml
- Disabled repeating of failed tests
- *135039*
=> [GHA] Do not repeat failed tests

.github/workflows/windows_conditional_compilation.yml
- Clone step might be longer as on Linux , need to adjust timeout
- *153781*
=> [GHA] Increase cc_build timeout

docs/articles_en/assets/snippets/ov_extensions.py
- *item1*
- *...*
- *ticket-id*
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port extensions command 

src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
- Fix double constant definition
=> [GPU] Fix double jit constants

src/frontends/tensorflow_common/src/op/expand_dims.cpp, tests/layer_tests/tensorflow_tests/test_tf_ExpandDims.py
- Support complex tensors for `ExpandDims` operation + tests
- [None](https://github.com/openvinotoolkit/openvino/issues/22950)
=> [TF FE]: Support complex tensors for ExpandDims operation

src/plugins/intel_gpu/src/graph/program_node.cpp
=> [GPU] Fix unit tests ph4

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
=> [GPU] Fix empty oneDnn users

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
- Adjust usm_host memory usage for InferRequest tensors
=> [GPU] Adjust usm_host memory usage for InferRequest tensors

docs/articles_en/documentation/openvino-extensibility.rst, docs/articles_en/get-started/install-openvino/install-openvino-pip.rst, docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application.rst, docs/snippets/CMakeLists.txt, src/core/template_extension/CMakeLists.txt
Porting: https://github.com/openvinotoolkit/openvino/pull/26695
=> [DOCS] Using OpenVINO from wheel for 24.4

tests/requirements_pytorch
**Details:** Fix torchaudio dependency for MacOS x86
**Ticket:** 154146
=> [PT FE] Fix torchaudio dependency for MacOS x86

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device/batching-on-npu-plugin.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/26865
=> [NPU] Batching on NPU plugin

docs/sphinx_setup/api/nodejs_api/nodejs_api.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/26927
=> [DOCS] Fixing references to Node.js methods

src/frontends/pytorch/src/op/bitwise.cpp, tests/layer_tests/pytorch_tests/test_bitwise_ops.py
**Details:** Fix Bitwise translators with 3 inputs
**Ticket:** 154082
=> [PT FE] Fix Bitwise translators with 3 inputs

docs/articles_en/about-openvino/release-notes-openvino.rst
port: https://github.com/openvinotoolkit/openvino/pull/26876
=> [DOCS] release notes one more adjustment

src/frontends/onnx/frontend/src/op/com.microsoft/matmulnbits.cpp
- Added option to receive an input with dynamic shape, shape must be calculated later while shape inference
- N/A
=> [ONNX] Added support for dynamic input shapes in com.microsoft.MatMulNBits

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py
- *item1*
- *...*
- *ticket-id*
=> QF Sitemap Url wrapper

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS Port Sitemap for coveo to 24 4

src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
- Fix setting dependency input when unfusing subgraph
- 152578
=> [GPU] Fix setting dependency input when unfusing subgraph

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernel_selector_utils.h, src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp, src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- *Fix accuracy issue at gemm_tiled_opt kernel with dynamic padding*
- *147262*
=> [GPU] Fix accuracy issue at gemm_tiled_opt kernel with dynamic padding

.github/workflows/job_build_linux.yml, .github/workflows/job_onnx_runtime.yml
- Make sure onnxruntime does not go to openvino_package
- *153215*
=> [GHA] Exclude onnx runtime files from package

src/core/include/openvino/core/parallel.hpp, src/plugins/intel_cpu/src/graph.cpp, src/plugins/intel_cpu/src/nodes/interpolate.cpp, src/plugins/intel_cpu/src/nodes/mvn.cpp, src/plugins/intel_cpu/src/nodes/non_zero.cpp, src/plugins/intel_cpu/src/nodes/roi_align.cpp
- *Fix for functional tests with OMP*
- *...*
- *152606*
=> [CPU][OMP] Fix for functional tests

.github/workflows/job_pytorch_layer_tests.yml
=> [GHA] Increase timeout for Pytorch layer tests

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/lrn_within_channel_byxf_opt.cl
=> [GPU] Fix OOB in lrn

src/frontends/onnx/frontend/src/op/abs.cpp, src/frontends/onnx/frontend/src/op/com.microsoft/matmulnbits.cpp, src/frontends/onnx/frontend/src/utils/common.cpp, src/frontends/onnx/frontend/src/utils/common.hpp
- Added initial implementation of common function for checking common parameters of nodes (like in other frontends)
- N/A
=> [ONNX] Added default_op_checks function

src/bindings/python/src/openvino/frontend/pytorch/fx_decoder.py, tests/layer_tests/py_frontend_tests/test_torch_decoder.py, tests/model_hub_tests/pytorch/hf_transformers_models, tests/model_hub_tests/pytorch/test_hf_transformers.py, tests/model_hub_tests/pytorch/torch_utils.py
- *Extract signature from `forward`*
- *Remove `gpt2` from hf tests as it was moved to `test_llm.py`*
- *ticket-id*
=> [PT FE] Extract signature for FX scenario

src/common/transformations/include/transformations/utils/gen_pattern.hpp
=> [core] fix bug in values_info::predicate

.github/labeler.yml
**Details:** Update labels with reqs files
=> [TF FE][PT FE] Update labels with reqs files

src/core/shape_inference/include/search_sorted_shape_inference.hpp, src/core/src/op/search_sorted.cpp, src/core/tests/type_prop/search_sorted.cpp
- Fixed bugs with dynamic type and 1d input
- Added more tests
=> [SearchSortedDef]: Bugfixes in shape_infer.

docs/CMakeLists.txt, docs/scripts/install_appropriate_openvino_version.py, docs/scripts/tests/suppress_warnings.txt, docs/sphinx_setup/api/api_reference.rst, docs/sphinx_setup/api/genai_api/api.rst, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] OV GenAI Python API for master

docs/CMakeLists.txt, docs/articles_en/openvino-workflow.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port for adding folder for OVMS files

docs/CMakeLists.txt, docs/articles_en/openvino-workflow.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Add Ovem files to folder

.github/actions/openvino_provider/action.yml
To test archives from pre-commits when needed
=> [GHA] Configurable event name for provider

.github/actions/restore_artifacts/restore_artifacts.py
Quick fix for restored wheel files
=> [GHA] Include files in plain subfolders to restore

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/articles_en/documentation/openvino-ecosystem/openvino-security-add-on.rst, docs/articles_en/openvino-workflow.rst, docs/articles_en/openvino-workflow/running-inference/stateful-models.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port changes for Ovms tests to 24.4

tools/ovc/openvino/tools/ovc/convert.py, tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py
**Details:** Cover leftovers for ExportedProgram support
=> [OVC][PT FE] Cover leftovers for torch.export.ExportedProgram support

src/plugins/intel_npu/tests/functional/behavior/npuw/behavior_tests.cpp, src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/mock_plugins.cpp, src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/mock_plugins.hpp
- *Fixed tests for changes in FUNCALL_ASYNC and calls to get_default_method()*
- *EISW-143057*
- *CVS-154787*
=> Fixed tests for NPUW

.github/labeler.yml, src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/mock_plugins.cpp, src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/mock_plugins.hpp
- *Added comments on test infrastructure changes*
- *Added tests paths to labeler*
- *EISW-143057*
- *[CVS-154787](https://jira.devtools.intel.com/browse/CVS-154787)*
=> [NPUW] Polished NPUW tests fix and added NPUW tests paths to labeler

src/plugins/intel_gpu/src/graph/program.cpp
OOR in LNL or Perf drop in A770 with cache.
- *152249*
=> [GPU] Fix SD3 int4 OOR or Perf drop issue in LNL

src/plugins/intel_npu/src/al/include/intel_npu/al/config/npuw.hpp, src/plugins/intel_npu/src/al/include/npuw_private_properties.hpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/compiler.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/group.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/group.hpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/snapshot.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/snapshot.hpp
- Introduce a pattern-guided REG pipeline and make it default. If there's no known patterns, it falls back into REP.
- *E-142355*
=> NPUW: Regularized REP pipeline

src/plugins/intel_cpu/src/emitters/plugin/x64/jit_eltwise_emitters.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/convert_to_plugin_specific_node.cpp
- *Improve instruction generating algorithm for pow(a, N), where N is very large. Besides, fix overflow during converting from float to int32.*
- *[154601](https://jira.devtools.intel.com/browse/CVS-154601)*
=> [CPU] Improve instruction generating algorithm for pow(a, large_N)

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp, src/plugins/intel_gpu/src/graph/input_layout.cpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/lora_pattern.cpp
- *[152852](https://jira.devtools.intel.com/browse/CVS-152852)*
=> [GPU] Added tests for LoRA with empty adapters and handling of incorrect fusings

src/bindings/python/src/openvino/runtime/opset15/__init__.py, src/bindings/python/src/openvino/runtime/opset15/ops.py, src/bindings/python/tests/test_graph/test_create_op.py
- *Extend Python API with SliceScatter-15*
- *...*
- *CVS-155151*
=> [PyOV] Extend Python API with SliceScatter-15

src/frontends/pytorch/src/node_context.cpp
**Details:** Handle None-value case
=> [PT FE] Handle None-value case among inputs

src/plugins/intel_gpu/src/graph/program.cpp, src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
- This is needed to have correct runtime impl selection of imported model
- *CVS-154891*
=> [GPU] Save use_onednn attribute in the blob

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp, src/plugins/intel_gpu/tests/functional/behavior/infer_request.cpp
- Treat USMHost tensor from another context as non-sharable
=> [GPU] Fix USMHost tensor sharing between models from different Cores
