docs/sphinx_setup/assets/versions_raw.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Moved versioning to repo

src/bindings/python/src/openvino/frontend/pytorch/gptq.py, src/frontends/pytorch/src/transforms/u4_block_repack.cpp, tests/model_hub_tests/pytorch/test_llm.py
- *Fix sym GPTQ pattern to have consistent graph*
- *ticket-id*
=> [PT FE] Fix sym GPTQ pattern to have consistent graph

CONTRIBUTING.md, src/bindings/js/docs/CODESTYLE.md, src/bindings/js/docs/README.md, src/bindings/js/docs/code_examples.md, src/bindings/js/docs/test_examples.md, src/bindings/js/node/CONTRIBUTING.md, src/bindings/js/node/README.md, src/bindings/js/node/package.json
Porting: https://github.com/openvinotoolkit/openvino/pull/26875
=> [OV JS][DOCS] Edits in JS API docs

src/bindings/python/src/openvino/runtime/opset15/__init__.py, src/bindings/python/src/openvino/runtime/opset15/ops.py, src/bindings/python/tests/test_graph/test_create_op.py
- Extend Python API with STFT-15
- 147160
=> [PyOV] Extend Python API with STFT-15

src/plugins/intel_gpu/src/graph/impls/onednn/pooling_onednn.hpp, src/plugins/intel_gpu/src/graph/impls/registry/pooling_impls.cpp
=> [GPU] Disable onednn pool in some cases due to the bug

src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
- *[152852](https://jira.devtools.intel.com/browse/CVS-152852)*
=> [GPU] Added empty LoRA adapters support for onednn case

src/frontends/onnx/frontend/src/editor.cpp, src/frontends/onnx/frontend/src/editor.hpp, src/frontends/onnx/frontend/src/frontend.cpp, src/frontends/onnx/frontend/src/input_model.cpp, src/frontends/onnx/frontend/src/input_model.hpp, src/frontends/onnx/tests/CMakeLists.txt, src/frontends/onnx/tests/load_from.cpp
- Direct loading from ModelProto object
- 155265
=> [ONNX] Direct loading from ModelProto object

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> Docs rename ovcategory in sitemap

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] port

src/tests/functional/plugin/conformance/subgraphs_dumper/include/utils/model.hpp
- Fix `Assertion failed: vector iterators incompatible`, by correct elements erase from map.
- CVS-155346
=> [tests] MSVC debug asserts on vector iterators incompatible in test

src/bindings/python/constraints.txt, src/bindings/python/requirements.txt
- *item1*
- *...*
- *ticket-id*
=> [PyOV] update numpy <2.2.0

.github/workflows/workflow_rerunner.yml
=> [CI] [GHA] Update list of workflows for rerunner, add step for statistics

src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- Skips bf16 Inference tests in Behavior Test category 
- CVS-155237
=> [NPU][ov_integration] Skip BF16 tests

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS Main change

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port changes for sitemap category renaming 24.4

src/bindings/python/src/openvino/frontend/pytorch/patch_model.py
- *Save args on meta device when patching*
- *Remove warning when patching twice*
- *ticket-id*
=> [PT FE] Save args on meta device when patching

src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.hpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/dynamic_quantize_gpu_opt.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/dynamic_quantize_gpu_ref.cl
- Accuracy fix with _rte type conversion
- Fix to enable dyn_quan
=> [GPU] Dynamic quantization fix for systolic case

src/plugins/intel_gpu/src/kernel_selector/micro_utils.hpp
- Update onednn 3.7pc
- *ticket-id*
=> [Do not merge][GPU] Update onednn to 3.7pc

src/plugins/intel_gpu/src/graph/fully_connected.cpp, src/plugins/intel_gpu/tests/unit/fake_alignment/fc_fake_alignment_test.cpp
This reverts commit 03aaa413702e6c107a83faae453b6a1ff1af93fe.
- *[155861](https://jira.devtools.intel.com/browse/CVS-155861)*
=> Revert "[GPU] Increasing conditions for using fake_aligned shapes (#26450)"

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Restore change

src/plugins/intel_npu/src/backend/include/zero_backend.hpp, src/plugins/intel_npu/src/backend/include/zero_device.hpp, src/plugins/intel_npu/src/backend/include/zero_init.hpp, src/plugins/intel_npu/src/backend/src/zero_backend.cpp, src/plugins/intel_npu/src/backend/src/zero_device.cpp, src/plugins/intel_npu/src/backend/src/zero_init.cpp, src/plugins/intel_npu/src/common/include/intel_npu/common/npu.hpp, src/plugins/intel_npu/src/common/src/npu.cpp, src/plugins/intel_npu/src/plugin/include/backends.hpp, src/plugins/intel_npu/src/plugin/include/metrics.hpp, src/plugins/intel_npu/src/plugin/src/backends.cpp, src/plugins/intel_npu/src/plugin/src/metrics.cpp, src/plugins/intel_npu/src/plugin/src/plugin.cpp
- Implements ov::device::LUID property in npu_plugin (works on windows only)
- EISW-140889
=> [intel-npu] Implementing LUID property in npu plugin

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- Allow checking impls cache & running async compile when primitive shape is changed to improve the performance
- *CVS-155869*
=> [GPU] Use impls cache in case when shape changed

src/core/src/pass/serialize.cpp, src/frontends/ir/src/frontend.cpp, src/frontends/ir/src/input_model.cpp, src/frontends/ir/src/input_model.hpp, src/plugins/intel_gpu/include/intel_gpu/plugin/plugin.hpp, src/plugins/intel_gpu/src/plugin/plugin.cpp, src/plugins/intel_gpu/tests/functional/behavior/model_cache.cpp
This PR is an implementation of an idea requested in this discussion: https://github.com/openvinotoolkit/openvino/pull/25731#discussion_r1802669119.
=> [GPU] Weightless caching - propagate weights_path from IR FE to the plugin

src/plugins/intel_gpu/CMakeLists.txt, src/plugins/intel_gpu/include/intel_gpu/runtime/device_info.hpp, src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp, src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp, src/plugins/intel_gpu/thirdparty/CMakeLists.txt
- update cmake to add xe3
- update onednn rls-v3.7-pc
=> [GPU] add XE3 to build

src/plugins/intel_npu/tools/protopipe/CMakeLists.txt
- winmm is Windows only dependency
- E-144853
=> Fix protopipe dependencies for Linux

SECURITY.md
- Added new section with security badges
- 155982
=> [docs] Security badges addition

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
- *item1*
- *...*
- *ticket-id*
=> NPU: Don't update command list if set_tensor is called with the same tensor

.github/workflows/job_pytorch_models_tests.yml, .github/workflows/ubuntu_22.yml, tests/constraints.txt, tests/model_hub_tests/pytorch/test_timm.py, tests/model_hub_tests/pytorch/timm_models, tests/model_hub_tests/pytorch/torchvision_models, tests/requirements_pytorch
- *Update timm to 1.0.11 and the model list accordingly*
- *Update marks in accordance with recent improvements in export support*
- *ticket-id*
=> [TESTS] Update torch hub tests for export scenario

src/bindings/python/docs/build.md
=> [DOCS] Wheels section python build docs for 24.4

docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/signals/stft-15.rst
- Update STFT-15 spec to describe 1D signal input support
- Add more representative examples
- Fix "transpose_frames" attr name typo
- 155996
Related PR for implementation:
- https://github.com/openvinotoolkit/openvino/pull/27274
=> [STFT][Op][Spec] Update STFT-15 spec to describe 1D signal input support

tests/requirements_tensorflow
**Details:** Update tensorflow-text version and fix jax version for MacOS x86
**Ticket:** 156277
=> [TF FE] Update tensorflow-text version and fix jax version for MacOS x86

cmake/developer_package/frontends/frontends.cmake
- Regression after https://github.com/openvinotoolkit/openvino/pull/26610
- CVS-156317
=> [Wheel] return back JAX FE

src/bindings/python/src/openvino/runtime/opset15/ops.py, src/bindings/python/tests/test_graph/test_create_op.py
- Fix STFT Python API to pass "transpose_frames" attribute
- 147160
=> [STFT][Op][Python] Fix STFT Python API to pass attribute

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
- Fix accuracy for sdpa_opt 
- 154583
=> [GPU] Fix sdpa opt accuracy 

src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.hpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
This reverts commit c21f572cc45193232d76aa21e821e92445b18725.
=> Revert "[GPU] Fixes for hybrid quantization (#27127)"

docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/signals/stft-15.rst
Fixing formatting issues in the `Short Time Fourier Transformation for real-valued input` article.
=> [DOCS] Fixing formatting in the STFT article.

tests/layer_tests/tensorflow_tests/test_tf_UnsortedSegmentSum.py
**Details:** Stabilize tests for UnsortedSegmentSum operation on all platforms
=> [TF FE] Stabilize tests for UnsortedSegmentSum operation on all platforms

tests/constraints.txt, tests/requirements_pytorch
- *Support torch 2.5.1*
- *Update test requirements*
- *ticket-id*
=> [PT FE] Support torch 2.5.1

src/frontends/onnx/frontend/src/op/com.microsoft/quick_gelu.cpp, src/frontends/onnx/tests/models/com.microsoft/quick_gelu.prototxt, src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp
- Microsoft Contrib Operator "QuickGelu" for ONNX RT
- CVS-152783
=> [ONNX] Added QuickGelu from com.microsoft domain

src/plugins/intel_npu/src/plugin/npuw/just_sync_infer_request.cpp
https://github.com/openvinotoolkit/openvino/pull/27313
=> [NPUW] Revert check in preemptive tensor set

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp, src/plugins/intel_gpu/src/graph/include/reshape_inst.h, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_kv_cache_update_ref.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/rope_ref.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/rope/rope_kernel_base.cpp, src/plugins/intel_gpu/src/plugin/transformations/optimize_subsequent_reshapes.cpp, src/plugins/intel_gpu/src/plugin/transformations/optimize_subsequent_reshapes.hpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp, src/plugins/intel_gpu/tests/unit/transformations/optimize_subsequent_reshapes_test.cpp
- Added subsequent reshapes optimization
- Added dynamic paddings support for RoPE and PagedAttention
- [CVS-156124](https://jira.devtools.intel.com/browse/CVS-156124)
=> [GPU] Add subsequent reshapes optimization and dynamic paddings support for RoPE and PagedAttention

src/plugins/intel_gpu/src/plugin/variable_state.cpp
- *[156193](https://jira.devtools.intel.com/browse/CVS-156193)*
=> [GPU] Handling the case where get_state was called before set_state

docs/articles_en/about-openvino/performance-benchmarks/generative-ai-performance.rst, docs/sphinx_setup/_static/js/openVinoDataTables.js
- *item1*
- *...*
- *ticket-id*
=> [Docs] Changes for Port

src/plugins/intel_npu/src/compiler_adapter/src/driver_graph.cpp, src/plugins/intel_npu/src/compiler_adapter/src/plugin_graph.cpp
- *Add zero_api when zero functions are used*
- *ticket-id*
=> [NPU] Add zero_api when zero functions are used

docs/sphinx_setup/_static/js/openVinoDataTables.js, docs/sphinx_setup/index.rst
port: https://github.com/openvinotoolkit/openvino/pull/27382
=> [DOCS] unhide columns in datatable 24.4

src/plugins/intel_gpu/src/plugin/common_utils.cpp, src/plugins/intel_gpu/src/runtime/execution_config.cpp
- Added support for bf16 LoRA adapters
- Minor debug code cleanup
- *[153069](https://jira.devtools.intel.com/browse/CVS-153069)*
=> [GPU] Enable bf16 state conversions

src/bindings/c/include/openvino/c/ov_prepostprocess.h, src/bindings/c/src/ov_prepostprocess.cpp, src/bindings/c/tests/ov_preprocess_test.cpp, src/common/util/include/openvino/util/weights_path.hpp, src/common/util/src/weights_path.cpp
- Add image padding support in PrePostProcessor for C API
- #26730 
- CVS-152252
=> [c-api] PPP add pad step

src/common/transformations/include/transformations/utils/utils.hpp, src/common/transformations/src/transformations/control_flow/unroll_if.cpp, src/common/transformations/src/transformations/control_flow/unroll_tensor_iterator.cpp, src/common/transformations/src/transformations/convert_precision.cpp, src/common/transformations/src/transformations/op_conversions/convert_maxpool_downgrade.cpp, src/common/transformations/src/transformations/transpose_sinking/ts_utils.cpp, src/common/transformations/tests/control_flow/unroll_tensor_iterator_test.cpp, src/common/transformations/tests/utils/convert_precision.cpp, src/core/dev_api/openvino/core/descriptor_tensor.hpp, src/core/include/openvino/core/descriptor/tensor.hpp, src/core/src/descriptor/tensor.cpp, src/core/src/graph_util.cpp, src/core/src/node.cpp, src/core/src/node_output.cpp, src/core/src/preprocess/preprocess_impls.cpp, src/frontends/onnx/frontend/src/core/graph.cpp, src/plugins/intel_cpu/src/utils/serialize.cpp, src/tests/ov_helpers/ov_snippets_models/src/subgraph_simple.cpp
- Remove legacy name from tensor descriptor
- #26855
- CVS-156182
=> [core] Remove legacy tensor name

src/core/include/openvino/core/type/element_type.hpp, src/core/src/type/element_type.cpp
- Removed deprecated and not used element Type constructor
- CVS-156179
=> [core] Remove deprecated element Type ctor

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- *Disable crop fusing that was enabled in the https://github.com/openvinotoolkit/openvino/pull/26951*
- *[156367](https://jira.devtools.intel.com/browse/CVS-156367)*
=> [GPU] Disable crop fusing

docs/dev/pypi_publish/pre-release-note.md, docs/dev/pypi_publish/pypi-openvino-dev.md, docs/dev/pypi_publish/pypi-openvino-rt.md
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Remove pre-release note

src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/convolution.hpp, src/plugins/intel_gpu/src/graph/program.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_b_fs_zyx_fsv16_imad.cl, src/plugins/intel_gpu/src/kernel_selector/jitter.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16_imad.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16_imad.h, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_base.h, src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- *[148550](https://jira.devtools.intel.com/browse/CVS-148550)*
=> [GPU] Added convolution_gpu_b_fs_zyx_fsv16_imad shape agnostic kernel

src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_types.hpp
- *Fix clang issue*
- *...*
- *ticket-id*
=> [NPU] Fix clang issue

src/bindings/python/wheel/CMakeLists.txt
- Backport of https://github.com/openvinotoolkit/openvino/pull/27429
- EISW-146038
=> Backport NPU wheel build fix for Windows

.github/workflows/coverity.yml
- Fixed regression introduced by https://github.com/openvinotoolkit/openvino/pull/27422
- *ticket-id*
=> [GHA] Coverity build regression fix

.github/workflows/coverity.yml
- sccache doesn't properly work with Coverity
- *ticket-id*
=> [GHA][Coverity] Disable sccache

src/bindings/python/src/openvino/frontend/pytorch/patch_model.py, tests/layer_tests/py_frontend_tests/test_torch_frontend.py
- *Inherit signature from forward while patching*
- *ticket-id*
=> [PT FE] Inherit signature from forward while patching

.github/workflows/fedora_29.yml
We need that to have build artifacts stored from pushes
=> [GHA] Enable Fedora trigger in post-commit

.github/workflows/linux_arm64.yml
Needed to have post-commit artifacts for packaging
=> [GHA] Enable Ubuntu 20 arm in postcommits

src/plugins/intel_gpu/src/graph/scaled_dot_product_attention.cpp
Fix SDPA shape inference issue
- *CVS-151301*
=> [GPU] Fix SDPA shape inference issue

src/plugins/intel_cpu/src/nodes/executors/acl/acl_deconv.cpp
- Perf degradation - Noise Suppression Poconet-Like FP16
- CVS-156953
=> [CPU][ARM] Fix performance issues in deconvolution layer

.github/actions/setup_python/action.yml, .github/workflows/job_build_windows.yml, .github/workflows/job_pytorch_layer_tests.yml, .github/workflows/job_tensorflow_layer_tests.yml, .github/workflows/job_tokenizers.yml, .github/workflows/windows_vs2019_release.yml
=> [CI] [GHA] Set pip cache directory correctly on Windows

src/frontends/tensorflow_common/src/op/depthwise_conv_2d.cpp
**Details:** Remove unused vars for DepthwiseConv2d operation
=> [TF FE] Remove unused vars for DepthwiseConv2d operation

.github/workflows/fedora.yml, .github/workflows/webassembly.yml
- See https://github.com/openvinotoolkit/openvino/actions/runs/11799055929/job/32866710829?pr=27474
=> [GHA]: use Azure docker images

src/plugins/intel_gpu/src/graph/network.cpp, src/plugins/intel_gpu/src/graph/reshape.cpp, src/plugins/intel_gpu/src/plugin/common_utils.cpp
- *[152882](https://jira.devtools.intel.com/browse/CVS-152882)*
=> [GPU] Minor state fixes

docs/articles_en/about-openvino/performance-benchmarks/performance-benchmarks-faq.rst, docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/documentation/legacy-features.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-onnx-faster-r-cnn.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-onnx-gpt-2.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-quartz-net.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-rnn-t.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-convert-tensorflow.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-model-optimizer-extensibility.rst, docs/articles_en/documentation/openvino-ecosystem/openvino-security-add-on.rst, docs/articles_en/documentation/openvino-ecosystem/openvino-training-extensions.rst, docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/infrastructure/loop-5.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/gru-cell-3.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/gru-sequence-5.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/lstm-sequence-5.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/rnn-sequence-5.rst, docs/articles_en/get-started/configurations/configurations-intel-gpu.rst, docs/articles_en/get-started/install-openvino/install-openvino-yocto.rst, docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-native-ov.rst, docs/articles_en/learn-openvino/llm_inference_guide/ov-tokenizers.rst, docs/articles_en/openvino-workflow/model-optimization-guide/compressing-models-during-training/filter-pruning.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-throughput/advanced_throughput_options.rst, docs/articles_en/openvino-workflow/running-inference/stateful-models.rst, docs/articles_en/openvino-workflow/running-inference/string-tensors.rst, docs/articles_en/openvino-workflow/torch-compile.rst
Fixing broken links in documentation.
=> [DOCS] Fixing reference in documentation

docs/articles_en/about-openvino/performance-benchmarks/performance-benchmarks-faq.rst, docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/documentation/legacy-features.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-onnx-faster-r-cnn.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-onnx-gpt-2.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-quartz-net.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-conversion-tutorials/convert-pytorch-rnn-t.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-conversion-api/[legacy]-supported-model-formats/[legacy]-convert-tensorflow.rst, docs/articles_en/documentation/legacy-features/transition-legacy-conversion-api/legacy-model-optimizer-extensibility.rst, docs/articles_en/documentation/openvino-ecosystem/openvino-security-add-on.rst, docs/articles_en/documentation/openvino-ecosystem/openvino-training-extensions.rst, docs/articles_en/documentation/openvino-extensibility/openvino-plugin-library/advanced-guides/low-precision-transformations.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/infrastructure/loop-5.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/gru-cell-3.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/gru-sequence-5.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/lstm-sequence-1.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/rnn-sequence-5.rst, docs/articles_en/get-started/configurations/configurations-intel-gpu.rst, docs/articles_en/get-started/install-openvino/install-openvino-yocto.rst, docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-native-ov.rst, docs/articles_en/learn-openvino/llm_inference_guide/ov-tokenizers.rst, docs/articles_en/openvino-workflow/model-optimization-guide/compressing-models-during-training/filter-pruning.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes.rst, docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.rst, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-throughput/advanced_throughput_options.rst, docs/articles_en/openvino-workflow/running-inference/stateful-models.rst, docs/articles_en/openvino-workflow/running-inference/string-tensors.rst, docs/articles_en/openvino-workflow/torch-compile.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/27531
=> [DOCS] Fixing references in docs for 2024.5

docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst
=> [DOCS] Updating NNCF Weight Compression 

docs/sphinx_setup/_static/html/modal.html, docs/sphinx_setup/_static/html/modalLLM.html, docs/sphinx_setup/_static/js/graphs.js
for:
https://github.com/openvinotoolkit/openvino/pull/27538
=> [DOCS] Port for ordering and preselection to 24.5

docs/articles_en/get-started/install-openvino/install-openvino-pip.rst
- Fixed import example
- *ticket-id*
=> [DOCS] fixed get_cmake_path import instructions

docs/dev/ci/github_actions/overview.md, docs/dev/ci/github_actions/security.md
Security guidelines for GitHub Actions workflows developers
=> [DOCS] Security best practices for GitHub Actions workflows development

src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.h
- Fix memory leak and improve memory usage with continuous inference
- 148552
=> [GPU] Fix memory leak

docs/articles_en/get-started/install-openvino/install-openvino-pip.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/27542
=> [DOCS] Update import get_cmake_path instruction

.github/workflows/job_tensorflow_layer_tests.yml, tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_gru.py
**Details:** Stabilize layer tests for Keras GRU layer on all platforms
**Ticket:** 156967
=> [TF FE] Stabilize layer tests for Keras GRU layer on all platforms

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide-npu.rst
Updating the `Run LLMs with OpenVINO GenAI Flavor on NPU` article - adding info about new config options. 
This PR addresses JIRA ticket: 156503.
=> [DOCS] Updating NPU GenAI docs

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py, docs/sphinx_setup/conf.py
Port for hierarchical field to 24.4
https://github.com/openvinotoolkit/openvino/pull/27569
=> [DOCS] changes for port to 24.4

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py, docs/sphinx_setup/conf.py
Port for https://github.com/openvinotoolkit/openvino/pull/27569
=> [DOCS] Port for New hierarchical field for Coveo to 24.5

docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst, docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression/4-bit-weight-quantization.rst
Rearranging information in the `LLM Weight Compression` article.
=> [DOCS] Updating Weight Compression Article

docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst, docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression/4-bit-weight-quantization.rst
=> [DOCS] Updating Weight Compression article for 24.5

tests/layer_tests/tensorflow2_keras_tests/test_tf2_keras_conv_2d_transpose.py
**Details:** Stabilize tf.keras.layers.Conv2DTranspose layer test on all platforms
**Ticket:** 155121
=> [TF FE] Stabilize tf.keras.layers.Conv2DTranspose layer test on all platforms

src/tests/functional/shared_test_classes/src/subgraph/perm_conv_perm_concat.cpp
=> [TESTS] PermConvPermConcat: adjust abs_threshold for f32 case

docs/sphinx_setup/api/nodejs_api/addon.rst, docs/sphinx_setup/api/nodejs_api/nodejs_api.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Core.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CoreConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/OVAny.rst
Updating API docs: adding OVAny type.
=> [DOCS] Updating Nodejs API docs for 24.5

docs/sphinx_setup/api/nodejs_api/addon.rst, docs/sphinx_setup/api/nodejs_api/nodejs_api.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/element.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/enums/resizeAlgorithm.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CompiledModel.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Core.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/CoreConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InferRequest.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputModelInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/InputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Model.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Output.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/OutputTensorInfo.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShape.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PartialShapeConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PrePostProcessorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/PreProcessSteps.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/Tensor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/interfaces/TensorConstructor.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/Dimension.rst, docs/sphinx_setup/api/nodejs_api/openvino-node/types/OVAny.rst
=> [DOCS] Adding OVAny type to Nodejs API

.github/workflows/job_cxx_unit_tests.yml
=> [GHA] Increase timeout for C++ unit tests in precommit

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Update ovCategory field

docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst
Updating archive installation packages' versions.
=> [DOCS] Update release version of OV archive packages

docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/27637
=> [DOCS] Updating archive packages for 2024.5

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Update ovcategory in sitemap

src/bindings/js/node/package-lock.json, src/bindings/js/node/package.json
- update openvino-node package version to 2024.5.0
=> [OV JS] Update openvino-node package version to 2024.5.0

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py
- *item1*
- *...*
- *ticket-id*
=> Docs Update ovcategory to short version to 24.5

src/plugins/intel_npu/src/utils/src/zero/zero_wrappers.cpp
- *Update level zero to 1.19.1 and level zero ext*
=> Update level zero and level zero ext 

CMakeLists.txt, cmake/features.cmake, src/cmake/ov_parallel.cmake, src/plugins/intel_npu/src/backend/CMakeLists.txt, src/plugins/intel_npu/src/compiler_adapter/CMakeLists.txt, src/plugins/intel_npu/src/utils/src/zero/CMakeLists.txt, thirdparty/dependencies.cmake
- https://github.com/conda-forge/openvino-feedstock/pull/110#discussion_r1849117753
=> [NPU] Allow to use system level-zero

src/bindings/js/node/.npmignore, src/bindings/js/node/package-lock.json
- Fix .npmignore to keep ./scripts/lib folder
- Fix audit by update dependencies
=> [OV JS] Fix .npmignore

src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_init.hpp, src/plugins/intel_npu/src/utils/src/zero/zero_init.cpp, src/plugins/intel_npu/src/utils/src/zero/zero_wrappers.cpp
- *Use ZE_STRUCTURE_TYPE_MUTABLE_GRAPH_ARGUMENT_EXP_DESC from level zero*
=> Use ZE_STRUCTURE_TYPE_MUTABLE_GRAPH_ARGUMENT_EXP_DESC from level zero

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> Docs fix url in sitemap

docs/sphinx_setup/_static/js/graphs.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Graph Title Fix

docs/sphinx_setup/_static/js/graphs.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] QF for graph

docs/sphinx_setup/_static/js/custom.js, docs/sphinx_setup/_templates/search.html
- *item1*
- *...*
- *ticket-id*
=> Docs Fixed search mechanism with category 24.5

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py
=> [DOCS] Port Changes for sitemap generating to master

src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/tests/unit/dynamic_execution/update_shape_test.cpp
- Consider the node which is shape_of subgraph and ocl_impl in update_shape()
- 154135
=> [GPU] Consider the node which is shape_of subgraph and ocl_impl in update_shape() (cherrypick from PR#27551)

src/frontends/onnx/frontend/src/op/com.microsoft/simplified_layer_normalization.cpp, src/frontends/onnx/tests/models/com.microsoft/simplified_layer_normalization.prototxt, src/frontends/onnx/tests/models/com.microsoft/simplified_layer_normalization_2x2x8.prototxt, src/frontends/onnx/tests/models/com.microsoft/simplified_layer_normalization_3x8.prototxt, src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp
Details:
Microsoft Contrib Operator "SimplifiedLayerNormalization" for ONNX RT
Tickets:
N/A
=> [ONNX] Added SimplifiedLayerNormalization from com.microsoft domain

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
-  Fix double copying in case if lockable memory is needed
=> [GPU] Fix double copying in case if lockable memory is needed

src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp
=> [GPU] Allow micro_sdpa when inputs have different transpose order

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst, docs/articles_en/learn-openvino/llm_inference_guide/genai-guide-npu.rst
port: 
https://github.com/openvinotoolkit/openvino/pull/27643
https://github.com/openvinotoolkit/openvino/pull/27682
https://github.com/openvinotoolkit/openvino/pull/27684
=> Docs post release polishes port mstr

docs/articles_en/openvino-workflow/model-optimization-guide/quantizing-models-post-training/basic-quantization-flow.rst, docs/optimization_guide/nncf/ptq/code/ptq_torch_fx.py
port: https://github.com/openvinotoolkit/openvino/pull/26997
=> [Docs][NNCF] TorchFX backend docs (#26997) port

src/plugins/intel_npu/tests/unit/npuw/online_partitioning.cpp
=> [NPUW] Disable failing unit test

.github/workflows/job_cxx_unit_tests.yml, .github/workflows/job_pytorch_models_tests.yml
- Cherry-picked from the master branch to avoid CI failures
- 155619, 158008
=> [GHA] Increase timeouts for PyTorch models tests and C++ unit tests in precommit

src/bindings/python/src/pyopenvino/graph/ops/constant.cpp, src/bindings/python/src/pyopenvino/graph/strides.cpp, src/bindings/python/tests/test_graph/test_constant.py
- Add `get_tensor_view` and `get_strides` methods to for Constant
- Add `__eq__` overloadings for Strides
- *ticket-id*
=> [PyOV] new methods for Constant

src/plugins/intel_cpu/docs/debug_capabilities/README.md, src/plugins/intel_cpu/docs/debug_capabilities/average_counters.md, src/plugins/intel_cpu/src/config.cpp, src/plugins/intel_cpu/src/graph.cpp, src/plugins/intel_cpu/src/graph_dumper.cpp, src/plugins/intel_cpu/src/graph_dumper.h, src/plugins/intel_cpu/src/utils/debug_caps_config.cpp, src/plugins/intel_cpu/src/utils/debug_caps_config.h
called OV_CPU_AVERAGE_COUNTERS
=> [CPU][DEBUG_CAPS] Add env option to collect average counters to a file

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst, docs/articles_en/learn-openvino/llm_inference_guide/genai-guide/genai-use-cases.rst
Adding info on Vision Language Models and Speculative Decoding.
=> [DOCS] Vision Language Models and Speculative Decoding for 2024.5

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst, docs/articles_en/learn-openvino/llm_inference_guide/genai-guide/genai-use-cases.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/27760
=> [DOCS] Adding info on VLMS and Speculative Decoding

src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_api.hpp, src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_init.hpp, src/plugins/intel_npu/src/utils/src/zero/zero_init.cpp
- *Add support for zeInitDrivers*
=> [NPU] Add support for zeInitDrivers

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ovms-genai.json, docs/sphinx_setup/_static/benchmarks_files/graph-config.json
- *item1*
- *...*
- *ticket-id*
=> [DOCS] GenAi data update for 24.5

docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ovms-genai.json
- *item1*
- *...*
- *ticket-id*
=> Docs Branch cleaning 24.5

src/plugins/intel_gpu/src/graph/strided_slice.cpp
- Add input memory nullptr check in update_output_memory() of strided_slice
- 157643
=> [GPU] Add input memory nullptr check in update_output_memory() of strided_slice

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst, src/inference/include/openvino/runtime/intel_npu/properties.hpp, src/plugins/intel_npu/README.md, src/plugins/intel_npu/src/al/include/intel_npu/npu_private_properties.hpp, src/plugins/intel_npu/src/plugin/src/plugin.cpp
- Moving NPU_DEFER_WEIGHTS_LOAD property from private to public
- adding it to the documentation
- *none*
=> [intel-npu] Publishing NPU_DEFER_WEIGHTS_LOAD property

docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ovms-genai.json
- *item1*
- *...*
- *ticket-id*
=> Docs Branch update for GenAi to master

src/plugins/intel_npu/src/plugin/npuw/lazy_tensor.cpp, src/plugins/intel_npu/src/plugin/npuw/lazy_tensor.hpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/partitioning.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp
Mirror of https://github.com/openvinotoolkit/openvino/pull/27108
=> [NPUW] LazyTensor refactoring

docs/articles_en/about-openvino/performance-benchmarks.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Update date for ovms to 24.5

src/plugins/intel_npu/src/plugin/npuw/just_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/compute.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.cpp, src/plugins/intel_npu/src/plugin/npuw/spatial.cpp, src/plugins/intel_npu/src/plugin/npuw/util.cpp
- *Fixed `AUTO_CAUSES_COPY` issues found in NPUW by Coverity*
- *EISW-146516*
=> Fixed Coverity issues found in NPUW

tools/ovc/openvino/tools/ovc/__init__.py, tools/ovc/openvino/tools/ovc/telemetry_utils.py
- Send telemetry if openvino is used from torch.compile().
- CVS-134112
=> Telemetry for torch.compile()

src/plugins/intel_npu/src/plugin/include/compiled_model.hpp, src/plugins/intel_npu/src/plugin/src/compiled_model.cpp, src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp
Mirror of https://github.com/openvinotoolkit/openvino/pull/27777
=> NPUW Deref: NPU plugin - drop the reference to ov::Model

src/plugins/intel_npu/src/al/include/intel_npu/config/npuw.hpp, src/plugins/intel_npu/src/al/include/intel_npu/npuw_private_properties.hpp, src/plugins/intel_npu/src/al/src/config/npuw.cpp, src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.hpp, src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/compiled_model.hpp, src/plugins/intel_npu/src/plugin/npuw/just_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/just_sync_infer_request.hpp, src/plugins/intel_npu/src/plugin/npuw/unfold_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/unfold_sync_infer_request.hpp
Chery-picked PR:  https://github.com/openvinotoolkit/openvino/pull/27319
=> NPUW: Unfold infer requests (#27319)

src/plugins/intel_cpu/tools/commit_slider/tests/commit_slider_test.py, src/plugins/intel_cpu/tools/commit_slider/tests/test_data.py, src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/fbv_ac_mode_bitwise.cpp, src/plugins/intel_cpu/tools/commit_slider/tests/tests_res/tests_res.json, src/plugins/intel_cpu/tools/commit_slider/utils/modes.py
- *item1*
- *...*
- *ticket-id*
=> [Commit Slider] AC mode extended

src/plugins/intel_npu/src/plugin/npuw/just_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.cpp, src/plugins/intel_npu/src/plugin/npuw/spatial.cpp, src/plugins/intel_npu/src/plugin/npuw/util.cpp
- *Mirrored https://github.com/openvinotoolkit/openvino/pull/27552*
- *Fixed `AUTO_CAUSES_COPY` issues found in NPUW by Coverity*
- *EISW-146516*
=> Fixed Coverity issues found in NPUW 

tests/layer_tests/tensorflow_tests/test_tf_BinaryOps.py, tests/layer_tests/tensorflow_tests/test_tf_LogicalBinaryOps.py
**Details:** Decouple tests for Logical binary ops into separate suite and run on all platforms
=> [TF FE] Decouple tests for Logical binary ops into separate suite and run on all platforms

.github/workflows/android_arm64.yml, .github/workflows/workflows_scans.yml
This PR introduces a workflow with syntax checks for GitHub Actions Workflows. There's only `semgrep` scan for now, but more can be added later, if needed
=> A workflow to scan GitHub Actions Workflows

src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp, src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp, src/plugins/intel_gpu/src/graph/include/primitive_inst.h, src/plugins/intel_gpu/src/graph/include/program_node.h, src/plugins/intel_gpu/src/graph/primitive_inst.cpp, src/plugins/intel_gpu/src/graph/scatter_elements_update.cpp, src/plugins/intel_gpu/src/graph/scatter_nd_update.cpp, src/plugins/intel_gpu/src/graph/scatter_update.cpp, src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_gather_at_runtime.cpp, src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_scatter_update_at_runtime.cpp
- *Fix accuracy issue for reset output memory of optimized prim*
- original PRs:
- https://github.com/openvinotoolkit/openvino/pull/27695
- https://github.com/openvinotoolkit/openvino/pull/27439
- https://github.com/openvinotoolkit/openvino/pull/27517
- *154591*
=> Fix reset output memory issue

docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application/model-representation.rst
=> [DOCS] Fixing formatting in Model Representation

docs/articles_en/openvino-workflow/running-inference/integrate-openvino-with-your-application/model-representation.rst
=> [DOCS] Fixing formatting model representation for 24.5

docs/sphinx_setup/_static/css/custom.css, docs/sphinx_setup/_static/html/modal.html, docs/sphinx_setup/_static/html/modalLLM.html, docs/sphinx_setup/_static/js/graphs.js, docs/sphinx_setup/_templates/layout.html
=> [DOCS] Port changes for Make One Legend to master

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp, src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
- *It need to shift padding of crop created during buffer fusing in case the user of crop is gemm*
- *151186*
=> [GPU] Shift padding of crop created during buffer fusing

src/plugins/intel_npu/src/plugin/npuw/weights_bank.cpp
- Since recently (after #27767 ), NPUW drops links to the original weights to avoid memory duplication;
- The drop happens after the LazyTensor evaluation which supposedly creates a new tensor;
- It is not always the case, as sometimes tensors stay in the original format/precision and all that needs to be done is to copy the buffer into L0 memory as is;
- Previously, the `.detach()` only destroyed the associated `Constant` node that held the weight buffer, but in case of memory-mapped weights, the buffer was kept alive until the reference to `ov::Model` was destroyed in the end of the `ov::npuw::CompiledModel` constructors;
- There was found a case when, before reaching the NPUW partitioning & transformation pipeline, the model weights were first altered - from `BF16` to `FP16` precision. …
=> NPUW: Hotfix - delay the original weight memory deallocation

src/bindings/python/src/openvino/frontend/pytorch/gptq.py, src/bindings/python/src/openvino/frontend/pytorch/quantized.py, src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py, src/frontends/pytorch/src/op/linear.cpp, src/frontends/pytorch/src/op_table.cpp, src/frontends/pytorch/src/utils.cpp, tests/model_hub_tests/pytorch/detectron2_precommit, tests/model_hub_tests/pytorch/test_llm.py, tests/requirements_pytorch
- *Cherry-pick #27624 to release*
- *CVS-136653*
=> [PT FE] Support AWQ models with GEMM module (#27624)

src/plugins/intel_gpu/src/graph/debug_helper.cpp, src/plugins/intel_gpu/src/graph/include/pass_manager.h, src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/split_reshape_eltwise.cpp
- Cherry-pick of the changes from https://github.com/openvinotoolkit/openvino/pull/27827
=> [GPU] Fix memory reuse

src/plugins/intel_npu/src/plugin/npuw/weights_bank.cpp, src/plugins/intel_npu/src/plugin/npuw/weights_bank.hpp
- *Fixed "Data race condition" (Medium) Coverity issue*
- *Mirrored part of https://github.com/openvinotoolkit/openvino/pull/27916*
- *EISW-149544*
=> Fix for coverity issue of medium impact: Possible data race

docs/articles_en/documentation/openvino-security.rst
=> [DOCS] Loading compiled encrypted models

docs/sphinx_setup/assets/versions_raw.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Update versions_raw.js

src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
- *item1*
- *...*
- *ticket-id*
=> [CPU] fix an assert check for fc tensor parallel

src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/deconvolution_onednn.cpp
- test deconvolution_gpu_onednn.spatial_1d on LNL
- *...*
=> [GPU] fix onednn deconvolution

cmake/packaging/debian.cmake, cmake/packaging/rpm.cmake
https://github.com/openvinotoolkit/openvino/pull/27929/files#r1871180640
=> Add 2024.6 to conflicting versions

src/core/include/openvino/core/except.hpp, src/core/src/except.cpp
- We need to export virtual functions to fix RTTI
=> Fixed RTTI for exceptions

docs/articles_en/documentation/openvino-ecosystem.rst, docs/articles_en/documentation/openvino-ecosystem/openvino-test-drive.rst, docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst, docs/sphinx_setup/_static/benchmarks_files/llm_models_7-155H.csv, docs/sphinx_setup/_static/benchmarks_files/llm_models_7-258V.csv, docs/sphinx_setup/_static/benchmarks_files/llm_models_9-288V.csv, docs/sphinx_setup/_static/download/supported_models.csv
port: https://github.com/openvinotoolkit/openvino/pull/27933
=> [DOCS] test drive doc

docs/articles_en/about-openvino/performance-benchmarks.rst
- *item1*
- *...*
- *ticket-id*
=> Docs Remove OVMS Button

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/sphinx_setup/assets/versions_raw.js
- *item1*
- *...*
- *ticket-id*
=> Docs Versions update to 2024.6

src/plugins/intel_gpu/include/intel_gpu/runtime/execution_config.hpp, src/plugins/intel_gpu/src/plugin/plugin.cpp, src/plugins/intel_gpu/src/runtime/execution_config.cpp, src/plugins/intel_gpu/tests/functional/behavior/properties.cpp
- Added conversion logic from RT Info attributes to plugin property for limited set of properties.
=> [GPU] Parse runtime_options from model RT info and apply to config

tests/layer_tests/tensorflow_tests/test_tf_HSVToRGB.py
**Details:** Run HSVToRGB tests on all platforms
=> [TF FE] Run HSVToRGB tests on all platforms

docs/sphinx_setup/api/nodejs_api/addon.rst
=> [DOCS] Adding info on saveModelSync method in Node.js

docs/sphinx_setup/api/nodejs_api/addon.rst
=> [DOCS] saveModelSync method in Node.js addon

tests/layer_tests/tensorflow_tests/test_tf_If.py
**Details:** Run If tests on all platforms
=> [TF FE] Run If tests on all platforms

.github/actions/openvino_provider/get_s3_package.py
To filter out automatically picking unwanted custom release builds like https://storage.openvinotoolkit.org/repositories/openvino/packages/2024.5/windows_vc_mt
=> [GHA][ov-provider] Exclude custom release packages from matching (#27979)

src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp, src/plugins/intel_gpu/tests/unit/test_cases/dft_gpu_test.cpp, src/plugins/intel_gpu/tests/unit/test_cases/pooling_gpu_test.cpp
- Fixes in unit tests failures
=> [GPU] Fix tests errors, phase 7

src/frontends/jax/src/op/square.cpp, src/frontends/jax/src/op_table.cpp, tests/constraints.txt, tests/layer_tests/jax_tests/test_square.py
**Details:** It appears since JAX 0.4.36
**Ticket:** 158994
=> [JAX FE] Support square operation

src/plugins/intel_npu/src/backend/include/zero_backend.hpp, src/plugins/intel_npu/src/backend/src/zero_backend.cpp, src/plugins/intel_npu/src/common/include/intel_npu/common/icompiler_adapter.hpp, src/plugins/intel_npu/src/common/include/intel_npu/common/npu.hpp, src/plugins/intel_npu/src/common/src/npu.cpp, src/plugins/intel_npu/src/compiler_adapter/include/compiler_adapter_factory.hpp, src/plugins/intel_npu/src/compiler_adapter/include/driver_compiler_adapter.hpp, src/plugins/intel_npu/src/compiler_adapter/include/plugin_compiler_adapter.hpp, src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp, src/plugins/intel_npu/src/compiler_adapter/src/plugin_compiler_adapter.cpp, src/plugins/intel_npu/src/plugin/include/plugin.hpp, src/plugins/intel_npu/src/plugin/src/plugin.cpp
Clean-up code - create compiler adapter factory class to create the proper compiler adapter.
- *CVS-158848*
=> [NPU] Create compiler adapter factory

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- Disable swiglu fusion which was removed from the previous PR https://github.com/openvinotoolkit/openvino/pull/27831 by accident..
- *ticket-id*
=> [GPU] Not to apply swiglu fusion for onednn

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py
=> [DOCS] Port for Update Sitemap to 24.5

src/frontends/pytorch/src/op/stft.cpp, tests/layer_tests/pytorch_tests/test_stft.py
- Add support for `normalize` attribute of torch `aten::stft` by post op subgraph in PT Frontend
- 159159
=> [STFT][PT FE] Add support for normalize attr in STFT conversion

src/plugins/intel_cpu/tools/commit_slider/commit_slider.py, src/plugins/intel_cpu/tools/commit_slider/tests/test_util.py, src/plugins/intel_cpu/tools/commit_slider/utils/modes.py
- *item1*
- *...*
- *ticket-id*
=> [Commit Slider] Fix logs absence

docs/articles_en/about-openvino/performance-benchmarks/generative-ai-performance.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Update date on AI benchmarks

docs/articles_en/get-started/configurations/configurations-intel-gpu.rst, src/plugins/intel_gpu/docs/gpu_plugin_driver_troubleshooting.md
=> [DOC][GPU] Described to add user to render group in gpu configuration

docs/articles_en/about-openvino/performance-benchmarks/generative-ai-performance.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port for update date on benchmarks for master

.github/workflows/export_workflow_metrics.yml, .github/workflows/send_workflows_to_opentelemetry.yml, .github/workflows/workflows_to_track.txt
Metrics workflow doesn't work after recent changes made in https://github.com/openvinotoolkit/openvino/pull/28010
=> Fixing metrics workflow

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] fix link

docs/articles_en/get-started/install-openvino.rst
=> [DOCS] Fix LTS version number

docs/articles_en/about-openvino/compatibility-and-support/supported-devices.rst, docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/get-started/configurations/genai-dependencies.rst, docs/articles_en/get-started/install-openvino.rst, docs/dev/ov_dependencies.txt, docs/sphinx_setup/index.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/27963 
and 
https://github.com/openvinotoolkit/openvino/pull/28057
=> [DOCS] Preparing docs for 24.6 release - port to master

src/core/tests/frontend/frontend_manager.cpp, src/frontends/common/include/openvino/frontend/frontend.hpp, src/frontends/tests/frontend/shared/src/conversion.cpp
- Extend frontend API to support cpp path class.
- CVS-158888
=> [FE] Add support for cpp17 path in frontend API

src/plugins/intel_cpu/src/graph_dumper.cpp
csv file was generated by default by mistake
=> [CPU][DEBUG_CAPS] Fix average counters csv generation

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/get-started/install-openvino.rst
=> [DOCS] Updating release notes

.github/dependabot.yml
- *item1*
- *...*
- *ticket-id*
=> [GHA] Enable dependabot for docker images

docs/sphinx_setup/_static/js/custom.js
=> Docs Port for new coveo token implementation to 24.6

docs/articles_en/about-openvino/performance-benchmarks/generative-ai-performance.rst
Port for https://github.com/openvinotoolkit/openvino/pull/28093
=> Docs Port for Datatable implementation to 24.6

docs/articles_en/assets/snippets/ov_caching.cpp, docs/articles_en/assets/snippets/ov_caching.py, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-latency/model-caching-overview.rst
Temporary Reverts openvinotoolkit/openvino#28035 to restore GHA CI
=> Revert "Private/tkrupa/cache encryption docs"

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
Updating code snippets in the `Inference with OpenVINO GenAI` article.
=> [DOCS] Updating GenAI samples

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide-npu.rst, docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
Adding missing code for pipeline generation. Addressing the JIRA ticket: 159433
=> [DOCS] Fixing code snippet for GenAI inference on NPU

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
=> [DOCS] Updating samples in GenAI Guide - port from 2024.6

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide-npu.rst, docs/articles_en/learn-openvino/llm_inference_guide/genai-guide.rst
=> [DOCS] Fixing code snippet for GenAI on NPU

docs/articles_en/about-openvino/release-notes-openvino.rst
=> [DOCS] Update Release Notes

docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ov.json
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Benchmarks update for ov v2 to 24.6

docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ov.json
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Benchmark data update for  24.6 v2 

docs/articles_en/openvino-workflow/torch-compile.rst
port: https://github.com/openvinotoolkit/openvino/pull/27934
=> [Docs][torch.compile] NNCF quantization/compression (#27934)

docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst
Updating links to the archive packages in the `Install OpenVINO™ ... from an Archive File` articles.
=> [DOCS] Updating Versions of Archive Installation Packages

docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ov.json, docs/sphinx_setup/_static/benchmarks_files/graph-config.json, docs/sphinx_setup/_static/js/graphs.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Resolves issue with sorting platforms

docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst
port: https://github.com/openvinotoolkit/openvino/pull/28104
=> [DOCS] Updating Versions of Archive Installation Packages (#28104)

docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ov.json, docs/sphinx_setup/_static/benchmarks_files/graph-config.json, docs/sphinx_setup/_static/js/graphs.js
Port for https://github.com/openvinotoolkit/openvino/pull/28146
=> [DOCS] Port for Graph refactoring  to master

src/plugins/intel_npu/src/common/include/intel_npu/common/igraph.hpp, src/plugins/intel_npu/src/common/src/igraph.cpp, src/plugins/intel_npu/src/common/src/sync_infer_request.cpp, src/plugins/intel_npu/tests/functional/behavior/infer_request_run.cpp, src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp
- *Fail if non continuous tensor is set*
=> [NPU] Fail for non continuous tensors

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- Follow-up from #28077 for an additional comment
=> [GPU] minor comment

src/plugins/intel_gpu/src/runtime/layout.cpp, src/plugins/intel_gpu/tests/unit/module_tests/layout_test.cpp
- *[159060](https://jira.devtools.intel.com/browse/CVS-159060)*
=> [GPU] Extend the cases where layouts are compatible

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp, src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- *Add acc_tmp in general calc in fc funcion in common include file*
- *158460*
=> Add missing code in dynamic fc impl

src/core/include/openvino/op/fake_convert.hpp, src/core/src/op/fake_convert.cpp, src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp, src/plugins/intel_gpu/include/intel_gpu/primitives/fake_convert.hpp, src/plugins/intel_gpu/src/graph/fake_convert.cpp, src/plugins/intel_gpu/src/graph/impls/cpu/fake_convert.cpp, src/plugins/intel_gpu/src/graph/impls/cpu/register.cpp, src/plugins/intel_gpu/src/graph/impls/cpu/register.hpp, src/plugins/intel_gpu/src/graph/impls/registry/fake_convert_impls.cpp, src/plugins/intel_gpu/src/graph/impls/registry/registry.hpp, src/plugins/intel_gpu/src/graph/include/fake_convert_inst.h, src/plugins/intel_gpu/src/plugin/ops/fake_convert.cpp, src/plugins/intel_gpu/tests/functional/single_layer_tests/fake_convert.cpp, src/plugins/intel_gpu/tests/unit/module_tests/impls_registry_test.cpp
- *implement fake_convert*
- *add functional test for fake convert*
- *159263*
=> [GPU] Implement fake_convert

docs/articles_en/openvino-workflow/model-preparation/convert-model-pytorch.rst
**Details:** Document conversion of PyTorch models from disk
=> [PT FE][DOCS] Document conversion of PyTorch models from disk

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_bfyx_f16_1x1.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_1x1.cpp, src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- Fix ConvolutionKernel_b_fs_yx_fsv16_1x1 to support input0 feature dynamic case
- 146681
=> [GPU] Fix ConvolutionKernel_b_fs_yx_fsv16_1x1 to support input0 feature dynamic case

docs/articles_en/openvino-workflow/model-preparation/convert-model-pytorch.rst
port:
https://github.com/openvinotoolkit/openvino/pull/28175
by R. Kazantsev
=> [PT FE][DOCS] Document conversion of PyTorch models from disk (#28175)

src/core/src/pass/manager.cpp
Replacement for https://github.com/openvinotoolkit/openvino/pull/27782
=> Added missed chrono include to manager.cpp

.github/scripts/workflow_rerun/errors_to_look_for.json
- *159323*
- *159398*
- *159547*
=> [CI] [GHA] Add network-related error messages to the rerunner

src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.hpp, src/plugins/intel_npu/src/plugin/npuw/llm_infer_request.cpp
- *Copy-pasted Unroll SDPA implementation from GenAI into NPUW ov::npuw::LLMCompiledModel*
- *EISW-149347*
=> [NPUW] Port unroll SDPA optimization from GenAI

src/plugins/intel_gpu/include/intel_gpu/primitives/paged_attention.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp, src/plugins/intel_gpu/src/graph/include/paged_attention_inst.h, src/plugins/intel_gpu/src/graph/paged_attention.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_update_kernel_ref.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.h, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.h, src/plugins/intel_gpu/src/plugin/ops/paged_attention.cpp, src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp
- Added scores output support for PagedAttention
- Added PagedAttention unit tests
- [CVS-153660](https://jira.devtools.intel.com/browse/CVS-153660)
=> [GPU] Add scores output support for PagedAttention

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Sitemap - quick fix

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Port for Enabled button for GenAI benchmarks

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/sphinx_setup/conf.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Enabled button for GenAI benchmarks

src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/insert_brgemm_copy_buffers.cpp
- This PR fixes coverity issue with CID 1566608
- [CVS-158856](https://jira.devtools.intel.com/browse/CVS-158856)
=> Fix coverity scan issue CID 1566608

src/plugins/intel_cpu/src/nodes/unique.cpp
- Fix potential null dereference issue in Unique node implementation in CPU plugin (CID: 1546910)
- [CVS-145092](https://jira.devtools.intel.com/browse/CVS-145092)
=> Fix coverity scan issue CID 1546910

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/mvn_gpu_bfyx_opt.cl
=> [GPU] remove code duplication in mvn_gpu_bfyx_opt kernel

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_b_fs_zyx_fsv16_imad.cl
- *Fix work group sync issue for convolution_kernel_b_fs_zyx_fsv16_imad by sub_group_barrier.*
- *160203*
=> [GPU] Fix deconvolution unit tests issue.

samples/python/benchmark/bert_benchmark/bert_benchmark.py, samples/python/benchmark/sync_benchmark/sync_benchmark.py, samples/python/benchmark/throughput_benchmark/throughput_benchmark.py, samples/python/model_creation_sample/model_creation_sample.py
- Replace `openvino.runtime` with `openvino` in samples
- [CVS-159526](https://jira.devtools.intel.com/browse/CVS-159526)
=> [Py OV] Update samples with import from openvino directly 

src/plugins/intel_gpu/src/plugin/graph.cpp
- *item1*
- *...*
- *ticket-id*
=> [GPU]: Fix perf counter segment fault issue on nodes without event ptr.

docs/notebooks/latent-consistency-models-image-generation-with-output.rst, docs/notebooks/multilora-image-generation-with-output.rst
-They were moved in PR https://github.com/openvinotoolkit/openvino.genai/pull/1504
=> [DOCS] Updated link to image generation models

src/bindings/python/src/openvino/properties/intel_npu/__init__.py, src/bindings/python/src/pyopenvino/core/properties/properties.cpp, src/bindings/python/src/pyopenvino/core/properties/properties.hpp, src/bindings/python/tests/test_runtime/test_properties.py
- Add NPU properties to Python API
- *ticket-id*
=> [PyOV] Add npu properties

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide-npu.rst, docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst
port: https://github.com/openvinotoolkit/openvino/pull/28365
=> [DOCS] fix typo in npu llm inference guide and update wwb link port

src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp
- *Remove log for `GENERATE_HINT` as it can be not passed by user*
- *https://github.com/openvinotoolkit/openvino.genai/pull/1526*
=> [NPUW] Polished GENERATE_HINT

src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/strided_slice.cpp, src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_fc_horizontal_fusion.cpp
Skip the func-test from not reproducible local side. 
Only reproduce in validation team, probably environment problem. Will be investigate and re enable test.
- *160053*
=> [GPU] Skip several failed func tests with the latest driver

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add another error message for artefact downloading to the rerunner

src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py, src/bindings/python/src/openvino/frontend/pytorch/utils.py, tests/layer_tests/ovc_python_api_tests/test_pytorch.py, tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py
- *Support `None` in example*
- *CVS-156684*
=> [PT FE] Support None in example

docs/articles_en/learn-openvino/llm_inference_guide/ov-tokenizers.rst, docs/articles_en/openvino-workflow/running-inference/string-tensors.rst, docs/notebooks/openvino-tokenizers-with-output.rst
- Update links to genai samples
- related to https://github.com/openvinotoolkit/openvino.genai/pull/1411
- *ticket-id*
=> Update links to genai samples

src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_fc_horizontal_fusion.cpp
=> [GPU] Skip failed func test with the latest driver.

src/frontends/onnx/frontend/src/op/com.microsoft/fusedmatmul.cpp
Details:
Corrected attribute definitions in FusedMatMul to be optional
Tickets:
N/A
=> [ONNX] Fix errors in  FusedMatMul from com.microsoft domain

src/frontends/onnx/frontend/src/op/com.microsoft/qlinear_ops.cpp, src/frontends/onnx/tests/models/com.microsoft/q_linear_add.prototxt, src/frontends/onnx/tests/models/com.microsoft/q_linear_mul.prototxt, src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp
Details:
Microsoft Contrib Operator "QLinearAdd" and "QLinearMul" for ONNX RT
Tickets:
N/A
=> [ONNX] Added QLinear add and mul from com.microsoft domain

src/common/snippets/docs/debug_capabilities/README.md, src/common/snippets/docs/debug_capabilities/perf_count.md, src/common/snippets/docs/mha_optimization_guide.md, src/common/snippets/docs/snippets_design_guide.md
Fix invalid file links in snippet documentation
- N/A
=> [Snippets][Docs] Fix broken links

src/frontends/tensorflow/docs/supported_ops.md, src/frontends/tensorflow/src/op_table.cpp, src/frontends/tensorflow_common/include/common_op_table.hpp, src/frontends/tensorflow_common/src/op/tensor_scatter_add.cpp, tests/layer_tests/tensorflow_tests/test_tf_TensorScatterAdd.py
**Overview**:
This pull request fixes #25050
All testcases passed
Continuation of PR #26481
**Dependencies**:
- No dependencies on other pull requests.
**CC**:
@rkazants, @mlukasze
=> [TF FE] Add support for TensorScatterAdd in TF FE

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/rms_gpu_bfyx_opt.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/rms_gpu_ref.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_bfyx_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_bfyx_opt.h, src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_ref.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_ref.h, src/plugins/intel_gpu/tests/unit/fusions/rms_fusion_test.cpp
- This PR enables primitive fusion to RMS.
=> [GPU] Enable eltwise primitive fusion to RMS

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
Fix functional issue when checks data type during DynamicQuantizeFullyConnected callback. Target model has two output node, it caused the error.
- *160518*
=> [GPU] Fix SD3 hybrid static failure.

docs/articles_en/assets/snippets/lpt_intel_cpu_plugin.cpp, docs/articles_en/assets/snippets/ov_model_snippets.cpp, docs/articles_en/assets/snippets/ov_stateful_models_intro.cpp, docs/articles_en/assets/snippets/template_model_transformation.hpp, docs/articles_en/assets/snippets/template_pattern_transformation.cpp, docs/articles_en/assets/snippets/template_pattern_transformation.hpp
- Applied dedicated RTTI macros
- Replace standard dynamic cast with ov specific.
- CVS-160571
=> [Docs] Apply OpenVINO RTTI in Docs

src/common/snippets/include/snippets/op/serialization_node.hpp
- Fix OpenVINO RTTI for SerializationNode
- Fix control flow graph serialization
- 160593
=> [Snippets][CPU] Fix RTTI for SerializationNode

src/core/src/pass/sdpa_to_paged_attention.cpp
- *item1*
- *...*
- *ticket-id*
=> Added missed space in error message

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/mvn.cpp, src/plugins/intel_gpu/tests/unit/fusions/mvn_fusion_test.cpp
- *When shape flattening is required, change blocked format to plain format if reduction axis is not blocked axis.*
- *158306*
=> [GPU] Fix mvn unit test fails

src/plugins/intel_npu/tools/protopipe/main.cpp
- *item1*
- *...*
- *ticket-id*
=> Protopipe: Fix warnings in main.cpp

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- backport of https://github.com/openvinotoolkit/openvino/pull/28487
- 158017
=> [GPU] fix memory conflict for multi iteration in loop.

.github/workflows/linux_arm64.yml, .github/workflows/ubuntu_22.yml, .github/workflows/ubuntu_24.yml, .github/workflows/windows_vs2019_release.yml
=> Temporarily remove TF layer tests & TF models tests from required

.github/workflows/linux_arm64.yml, .github/workflows/ubuntu_22.yml, .github/workflows/ubuntu_24.yml, .github/workflows/windows_vs2019_release.yml
Reverts openvinotoolkit/openvino#28533
=> Revert "Temporarily remove TF layer tests & TF models tests from required"

.github/actions/setup_python/action.yml
- Should resolve things like in https://github.com/openvinotoolkit/openvino/actions/runs/12865943628/job/35867555790
=> [CI] [GHA] Remove `pip cache info` from `setup_python` action

src/plugins/hetero/tests/functional/shared_tests_instances/behavior/ov_plugin/core_threading_tests.cpp
- *item1*
- *...*
- *ticket-id*
=> [Hetro][Func Test] only the nightly tests can use hw plugin

docs/articles_en/openvino-workflow/model-preparation/convert-model-pytorch.rst
port: https://github.com/openvinotoolkit/openvino/pull/28492 by M. Vafin
=> [DOCS] Remove "experimental" note for torch.export port 

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
- fix yolov3 dynamic inference
- CVS-157866
=> [GPU] added missing info about conv autopad

src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp
=> [NPUW] Fix scales processing in CWAI for nf4

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add more download errors to rerunner

src/inference/dev_api/openvino/runtime/threading/istreams_executor.hpp, src/inference/src/dev/threading/cpu_streams_executor.cpp, src/inference/src/dev/threading/istreams_executor.cpp, src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
- *fix CID issue1590313, 1590213, 1588539, 1588497, 1588220*
- *ticket-id*
=> fix CID issue1590313, 1590213, 1588539, 1588497, 1588220

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_imad.cl, src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
=> [GPU] Fix a group conv unit test fail.

src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/matmul_weights_decompression.cpp
- Cherry-picks: https://github.com/openvinotoolkit/openvino/pull/28553
=> [CPU] Fixed FC dynamic quantization accuracy issue

src/plugins/intel_cpu/src/utils/plain_tensor.hpp
- Fix uninitialized array class member field in PlainTensor class 
- 160817
=> [CPU] Fix uninitialized array filed coverity issue with CID 1590270

src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp
=> NPUW: Fix long tensors names

src/plugins/intel_npu/src/backend/include/zero_host_tensor.hpp, src/plugins/intel_npu/src/backend/include/zero_remote_tensor.hpp, src/plugins/intel_npu/src/backend/src/zero_host_tensor.cpp, src/plugins/intel_npu/src/backend/src/zero_remote_tensor.cpp
- *High CPU overhead in ZeroHostTensor::data*
- *CVS-160977*
=> [NPU] Fix High CPU overhead in ZeroHostTensor::data

src/plugins/intel_gpu/src/plugin/transformations/convert_stridedslices_to_variadicsplit.cpp, src/plugins/intel_gpu/src/plugin/transformations/unsqueeze_broadcast_reshape_matmul_fusion.cpp, src/plugins/intel_gpu/src/plugin/transformations/unsqueeze_broadcast_reshape_sdpa_fusion.cpp
=> [GPU][Transformations] Fixed up predicates

src/frontends/common/include/openvino/frontend/decoder.hpp, src/frontends/common/include/openvino/frontend/graph_iterator.hpp, src/frontends/common/src/decoder.cpp, src/frontends/common/src/graph_iterator.cpp, src/frontends/common/src/hash_table.cpp, src/frontends/pytorch/src/frontend.cpp
- Regression after https://github.com/openvinotoolkit/openvino/pull/28555
=> Fixed C++ RTTI for header only classes

tools/ovc/openvino/tools/ovc/__init__.py, tools/ovc/openvino/tools/ovc/telemetry_utils.py
- Port of PR: https://github.com/openvinotoolkit/openvino/pull/28613
- CVS-160667
=> Telemetry for keras3.

src/plugins/intel_gpu/thirdparty/CMakeLists.txt
- Ported https://github.com/openvinotoolkit/openvino/pull/28629
=> GPU: fixed debug build on non-Windows

src/plugins/intel_gpu/src/plugin/plugin.cpp, src/plugins/intel_gpu/src/runtime/execution_config.cpp
- to resolve accuracy issues, disabled activations scaling for LLMs on all platforms
=> [GPU] disabling activations scaling for LLMs on all platforms

.github/workflows/ubuntu_20.yml
=> [GHA] C++ unit to required on Ubuntu 20

.github/workflows/ubuntu_20.yml
=> [GHA] C++ unit to required on Ubuntu 20 (#28649)

src/frontends/tensorflow_common/src/op/select.cpp, tests/layer_tests/tensorflow_tests/test_tf_Select.py
**Overview:**
- This pull request fixes #23243.
**Testing:**
- Tested the implementation & verified the results.
- No dependencies on other pull requests.
- TODO: Improve the test cases.
**CC:**
- @rkazants
=> [TF FE] Feat: implement complex type support for select

src/inference/src/dev/threading/cpu_streams_executor.cpp
- *org_proc_type_table is const in this function*
- *ticket-id*
=> update CID fix in PR 28541

CMakeLists.txt, cmake/developer_package/OpenVINODeveloperScriptsConfig.cmake, src/bindings/python/wheel/CMakeLists.txt
- *item1*
- *...*
- *ticket-id*
=> Fixed warnings with cmake 3.31

docs/articles_en/about-openvino/compatibility-and-support/supported-models-onnx.rst, docs/sphinx_setup/_static/download/supported_models.csv, docs/sphinx_setup/_static/download/supported_models_onnx.csv
port: https://github.com/openvinotoolkit/openvino/pull/28693
=> [DOCS] hidden page for ONNX supported models

tests/requirements_jax, tests/requirements_tensorflow
**Details:** Test with latest JAX 0.5.0 and Keras 3.8.0
=> [TF FE][JAX FE] Test with JAX 0.5.0 and Keras 3.8.0

.github/workflows/merge_queue_stub.yml
=> [CI] [GHA] Add missing topLevel token permissions

src/plugins/intel_cpu/src/nodes/kernels/x64/mlp_kernel.cpp
Fix "-Wsign-compare" warning in CPU plugin debug build
- *N\A*
=> [CPU] Fix warning in debug build

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add runner-related errors to rerunner

.github/workflows/workflow_rerunner.yml
Forgot to do it in scope of https://github.com/openvinotoolkit/openvino/pull/28705
=> Move workflow_rerunner workflow to smallrunner as well

src/plugins/intel_cpu/src/nodes/reduce.cpp
- Cherry-picks: https://github.com/openvinotoolkit/openvino/pull/28731
=> [CPU] Fixed Reduce kernel with bf16 destination precision

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/get-started/learn-openvino/openvino-samples/get-started-demos.rst, docs/notebooks/convert-to-openvino-with-output.rst, docs/notebooks/cross-lingual-books-alignment-with-output.rst, docs/notebooks/ct-segmentation-quantize-nncf-with-output.rst, docs/notebooks/ddcolor-image-colorization-with-output.rst, docs/notebooks/depth-anything-v2-with-output.rst, docs/notebooks/depth-anything-with-output.rst, docs/notebooks/fast-segment-anything-with-output.rst, docs/notebooks/gpu-device-with-output.rst, docs/notebooks/hello-npu-with-output.rst, docs/notebooks/image-classification-quantization-with-output.rst, docs/notebooks/knowledge-graphs-conve-with-output.rst, docs/notebooks/language-quantize-bert-with-output.rst, docs/notebooks/latent-consistency-models-image-generation-with-output.rst, docs/notebooks/llm-chatbot-generate-api-with-output.rst, docs/notebooks/llm-chatbot-with-output.rst, docs/notebooks/llm-rag-langchain-with-output.rst, docs/notebooks/llm-rag-llamaindex-with-output.rst, docs/notebooks/mllama-3.2-with-output.rst, docs/notebooks/model-server-with-output.rst, docs/notebooks/multilora-image-generation-with-output.rst, docs/notebooks/music-generation-with-output.rst, docs/notebooks/optimize-preprocessing-with-output.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Fixing references for 2025.0 - porting 28765

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/get-started/learn-openvino/openvino-samples/get-started-demos.rst, docs/notebooks/convert-to-openvino-with-output.rst, docs/notebooks/cross-lingual-books-alignment-with-output.rst, docs/notebooks/ct-segmentation-quantize-nncf-with-output.rst, docs/notebooks/ddcolor-image-colorization-with-output.rst, docs/notebooks/depth-anything-v2-with-output.rst, docs/notebooks/depth-anything-with-output.rst, docs/notebooks/fast-segment-anything-with-output.rst, docs/notebooks/gpu-device-with-output.rst, docs/notebooks/hello-npu-with-output.rst, docs/notebooks/image-classification-quantization-with-output.rst, docs/notebooks/knowledge-graphs-conve-with-output.rst, docs/notebooks/language-quantize-bert-with-output.rst, docs/notebooks/latent-consistency-models-image-generation-with-output.rst, docs/notebooks/llm-chatbot-generate-api-with-output.rst, docs/notebooks/llm-chatbot-with-output.rst, docs/notebooks/llm-rag-langchain-with-output.rst, docs/notebooks/llm-rag-llamaindex-with-output.rst, docs/notebooks/mllama-3.2-with-output.rst, docs/notebooks/model-server-with-output.rst, docs/notebooks/multilora-image-generation-with-output.rst, docs/notebooks/music-generation-with-output.rst, docs/notebooks/optimize-preprocessing-with-output.rst, docs/sphinx_setup/_static/html/banner_data.json
- *item1*
- *...*
- *ticket-id*
=> [DOCs] Fixing references for 2025.0

src/frontends/common/include/openvino/frontend/extension/conversion.hpp, src/frontends/common/src/extension/conversion.cpp
- *item1*
- *...*
- *ticket-id*
=> Fixed C++ RTTI for ConversionExtensionBase

docs/articles_en/get-started/install-openvino/install-openvino-apt.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-conda.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst, docs/articles_en/get-started/install-openvino/install-openvino-yum.rst, docs/articles_en/get-started/install-openvino/install-openvino-zypper.rst, docs/articles_en/openvino-workflow-generative.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] 2025.0 install guide update

src/frontends/tensorflow_common/src/op/squeeze.cpp
**Details:** Move the functionality from tokenizers to openvino
=> [TF FE] Support Squeeze for string tensors

docs/articles_en/about-openvino.rst, docs/articles_en/about-openvino/openvino-ecosystem.rst, docs/articles_en/about-openvino/openvino-ecosystem/openvino-adoptions.rst, docs/articles_en/about-openvino/openvino-ecosystem/openvino-integrations.rst, docs/articles_en/about-openvino/openvino-ecosystem/openvino-project.rst, docs/articles_en/about-openvino/openvino-ecosystem/openvino-project/datumaro.rst, docs/articles_en/about-openvino/openvino-ecosystem/openvino-project/openvino-security-add-on.rst, docs/articles_en/about-openvino/openvino-ecosystem/openvino-project/openvino-test-drive.rst, docs/articles_en/about-openvino/openvino-ecosystem/openvino-project/openvino-training-extensions.rst, docs/articles_en/assets/images/deploy_encrypted_model.svg, docs/articles_en/documentation.rst, docs/articles_en/documentation/compatibility-and-support/supported-devices.rst, docs/articles_en/documentation/openvino-security.rst
port: https://github.com/openvinotoolkit/openvino/pull/28780
=> [DOCS] ecosystem restructuring 25.0

docs/articles_en/get-started/install-openvino/install-openvino-apt.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-conda.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst, docs/articles_en/get-started/install-openvino/install-openvino-yum.rst, docs/articles_en/get-started/install-openvino/install-openvino-zypper.rst, docs/articles_en/openvino-workflow-generative.rst
port: https://github.com/openvinotoolkit/openvino/pull/28784
=> [DOCS] 2025.0 install guide update port mstr

src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.cpp, src/plugins/intel_gpu/tests/unit/transformations/horizontal_fc_fusion_test.cpp
- merging multiple scalar multiply layers connected to horizontal fused fc, and fusing it to the horizontal fused fc
160900
=> [GPU] merging multiple scalar multiply layers connected to horizontal fused fc

src/plugins/intel_gpu/src/plugin/ops/paged_attention.cpp
- Currently GenAI library sets fully dynamic shapes for Key/Value cache buffers, which causes GPU Plugin to fail during compile_model() call. Therefore, update PagedAttention creation logic to use head_size and heads_num parameters from the rt_info if available
- GenAI related PR: https://github.com/openvinotoolkit/openvino.genai/pull/1666
=> [GPU] Update PagedAttention creation logic

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/articles_en/about-openvino/performance-benchmarks/model-accuracy-int8-fp32.rst, docs/articles_en/about-openvino/performance-benchmarks/performance-benchmarks-faq.rst, docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ov.json
- *item1*
- *...*
- *ticket-id*
=> DOCS OV Benchmark update v3

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/generation/random-uniform-8.rst
port: https://github.com/openvinotoolkit/openvino/pull/28819
=> [DOCS] 25.0 final touches

cmake/developer_package/compile_flags/os_flags.cmake, src/cmake/ov_parallel.cmake, src/plugins/intel_gpu/src/graph/CMakeLists.txt, src/plugins/intel_gpu/src/runtime/CMakeLists.txt, vcpkg.json
- Reorder includes to have headers in OpenVINO source tree to come first.
- Closes https://github.com/openvinotoolkit/openvino/issues/28790
=> CMAKE: fixed GPU plugin build within vcpkg infra

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add sccache server startup error to rerunner

docs/articles_en/about-openvino/release-notes-openvino.rst
port: https://github.com/openvinotoolkit/openvino/pull/28837
=> [DOCS] remove models from release notes 25.0

samples/js/node/package-lock.json, samples/js/node/package.json, src/bindings/js/node/package-lock.json, src/bindings/js/node/package.json
- update `openvino-node` package version to 2025.0.0
- update `openvino-node` to 2025.0.0 in samples
=> [OV JS] Update openvino-node package version to 2025.0.0

src/core/src/pass/sdpa_to_paged_attention.cpp
- *item1*
- *...*
- *ticket-id*
=> [GPU] Added missed space in error message

.github/workflows/coverage.yml, .github/workflows/job_cxx_unit_tests.yml, .github/workflows/linux_sanitizers.yml
- *Some HETERO func test cases for nightly have "nighlty_*smoke*" pattern, exclude them in the smoke test*
- *...*
- *CVS-161093*
=> [HETERO] Exclude nightly test cases in smoke

src/frontends/pytorch/src/op/log.cpp
**Details:** Implement numerically stable logsumexp support
=> [PT FE] Implement numerically stable logsumexp support

src/plugins/intel_gpu/src/kernel_selector/CMakeLists.txt
- Extra fix in addition to https://github.com/openvinotoolkit/openvino/pull/28816
- Closes https://github.com/openvinotoolkit/openvino/issues/28790
=> GPU: fixed build with oneDNN from vcpkg - part 2

src/bindings/python/src/pyopenvino/utils/utils.cpp, src/inference/include/openvino/runtime/properties.hpp
- followup to https://github.com/openvinotoolkit/openvino/pull/28808
=> Python API: is_mutable() fix

src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.hpp, src/plugins/intel_npu/src/plugin/npuw/just_sync_infer_request.hpp
- *Fixed dumping of inputs and outputs of spatial subgraphs*
- *N/A*
=> Fixed dump of spatial inputs/outputs

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py
- *item1*
- *...*
- *ticket-id*
=> [DOCS Port for sitemap google

src/plugins/intel_gpu/include/intel_gpu/primitives/reverse_sequence.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/reverse_sequence.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reverse_sequence_ref.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/reverse_sequence/reverse_sequence_kernel_ref.cpp, tests/layer_tests/tensorflow_tests/test_tf_Reverse.py
- Add bfzyx format support to reverse_sequence kernel and host code for 4 dims inputs
- *105895*
=> [GPU] Fix reverse_sequence for 4 dims inputs

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/rope_opt.cl
- enabled gather in rope_opt kernel (for Qwen)
- small part of  ticket 161090
- 161090
=> [GPU] Enable gather in rope kernel

.github/workflows/build_doc.yml, .github/workflows/py_checks.yml
Support of Ubuntu 20.04 ends in April
=> [GHA] Get rid of Ubuntu 20 runners

src/plugins/intel_cpu/src/utils/verbose.cpp
Local variable was shadowed.
Also always use dim2str to print dimensions
=> [CPU][DEBUG_CAPS] Fix OV_CPU_VERBOSE missing shapes

docs/notebooks/flux.1-image-generation-with-output.rst, docs/notebooks/hugging-face-hub-with-output.rst, docs/notebooks/internvl2-with-output.rst, docs/notebooks/llava-multimodal-chatbot-genai-with-output.rst, docs/notebooks/llava-multimodal-chatbot-optimum-with-output.rst, docs/notebooks/llava-next-multimodal-chatbot-with-output.rst, docs/notebooks/minicpm-v-multimodal-chatbot-with-output.rst, docs/notebooks/modelscope-to-openvino-with-output.rst, docs/notebooks/nano-llava-multimodal-chatbot-with-output.rst, docs/notebooks/outetts-text-to-speech-with-output.rst, docs/notebooks/phi-3-vision-with-output.rst, docs/notebooks/pixtral-with-output.rst, docs/notebooks/qwen2-vl-with-output.rst, docs/notebooks/sana-image-generation-with-output.rst
**Details:** Fix typos in documentation
=> [DOC] Fix typos in documentation

.github/workflows/android_x64.yml
- *item1*
- *...*
- *ticket-id*
=> GHA: temporary disable GenAI build on Android x64

docs/articles_en/openvino-workflow-generative/inference-with-genai.rst, docs/articles_en/openvino-workflow-generative/inference-with-genai/inference-with-genai-on-npu.rst
port: [DOCS] NPU update for whisper
=> [DOCS] NPU update for whisper port

docs/articles_en/assets/snippets/ov_caching.cpp, docs/articles_en/assets/snippets/ov_caching.py, docs/articles_en/openvino-workflow/running-inference/optimize-inference/optimizing-latency/model-caching-overview.rst
=> [DOCS] Add weightless caching docs - porting 28253

src/plugins/intel_npu/src/al/src/config/config.cpp, src/plugins/intel_npu/src/backend/include/zero_tensor.hpp, src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/backend/src/zero_profiling.cpp, src/plugins/intel_npu/src/backend/src/zero_remote_tensor.cpp, src/plugins/intel_npu/src/backend/src/zero_tensor.cpp, src/plugins/intel_npu/src/common/include/intel_npu/common/igraph.hpp, src/plugins/intel_npu/src/common/src/device_helpers.cpp, src/plugins/intel_npu/src/compiler_adapter/src/ir_serializer.cpp, src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp, src/plugins/intel_npu/src/plugin/src/plugin.cpp, src/plugins/intel_npu/src/utils/src/zero/zero_init.cpp
- *Fix SDL issues*
- *E#155833*
=> [NPU] Fix SDL issues

src/common/snippets/include/snippets/op/perf_count.hpp, src/tests/functional/plugin/conformance/subgraphs_dumper/src/matchers/subgraph/manager.cpp
=> [CPU] Fix Windows build issues

src/plugins/intel_gpu/src/graph/deconvolution.cpp, src/plugins/intel_gpu/src/plugin/ops/convolution.cpp, src/plugins/intel_gpu/tests/unit/fusions/deconvolution_fusion_test.cpp
- Add new_shape_infer support in deconvolution
- 101276
- 160258
=> [GPU] Add new_shape_infer support in deconvolution

src/core/src/runtime/compute_hash.cpp
- *Some customers can set policy ProcessDynamicCodePolicy to prohibit dynamic code. So need to disable JIT in such cases.*
- *162440*
=> [CORE][CACHE][HASH] DYNAMIC_CODE_POLICY check on Windows

src/frontends/onnx/frontend/src/op/com.microsoft/bias_add.cpp, src/frontends/onnx/tests/models/com.microsoft/bias_add.prototxt, src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp
Details:
Microsoft Contrib Operator "BiasAdd" for ONNX RT
Tickets:
N/A
=> [ONNX] Added BiasAdd from com.microsoft domain

samples/cpp/benchmark_app/inputs_filling.cpp, src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp, src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_utils.hpp
- Fix for https://github.com/openvinotoolkit/openvino/pull/27903
- Update NF4 precision conversions in NPU plugin
- *...*
=> [NPU] Update NF4 precision conversions in NPU plugin

src/plugins/intel_gpu/src/graph/reshape.cpp, src/plugins/intel_gpu/src/plugin/ops/strided_slice.cpp, src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/stridedslice_eltwise.cpp, src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp, src/tests/functional/plugin/shared/include/subgraph_tests/stridedslice_eltwise.hpp, src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/stridedslice_eltwise.hpp, src/tests/functional/shared_test_classes/src/subgraph/stridedslice_eltwise.cpp
- *static strided_sliced crop to use tensor*
- *160254*
=> [GPU] static strided_sliced crop to use tensor

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- we have some nodes which is target to be optimized during runtime, the memory status can be corrupted among iterations for these nodes
- CVS-161830
=> [GPU] fix possible memory corruption with skippable nodes

.github/workflows/manylinux_2014.yml
Required for internal tests using requirement files packed here
=> [GHA] Save Manylinux openvino_tests archive on share

docs/requirements.txt
- *item1*
- *...*
- *ticket-id*
=> DOCS Port for Update packages to master

src/plugins/intel_npu/tools/single-image-test/main.cpp
- *Extend mean_iou metric in single-image-test for semantic segmentation networks that have ArgMax at the end.*
- *EISW-158075*
=> [NPU][SIT] Extand mean_iou metric for networks with ArgMax

src/plugins/intel_npu/src/utils/src/zero/zero_wrappers.cpp
- *Fix turbo mode*
- *E#156694*
=> [NPU] Fix turbo mode

src/plugins/intel_cpu/src/.clang-tidy, src/plugins/intel_cpu/src/nodes/matrix_nms.cpp, src/plugins/intel_cpu/src/nodes/non_zero.cpp
- Fix "bugprone-fold-init-type" remarks reported by clang-tidy
- Enable "bugprone-fold-init-type" clang-tidy checks on CI by default
- N/A
=> [CPU] Fix bugprone-fold-init-type clang-tidy remarks

.github/actions/store_artifacts/store_artifacts.py
=> [GHA] Store sha-256 checksums for artifacts

cmake/developer_package/add_target_helpers.cmake, src/plugins/intel_gpu/src/graph/CMakeLists.txt, src/plugins/intel_gpu/src/graph/impls/cm/CMakeLists.txt, src/plugins/intel_gpu/src/graph/impls/common/CMakeLists.txt, src/plugins/intel_gpu/src/graph/impls/cpu/CMakeLists.txt, src/plugins/intel_gpu/src/graph/impls/ocl/CMakeLists.txt, src/plugins/intel_gpu/src/graph/impls/onednn/CMakeLists.txt, src/plugins/intel_gpu/src/graph/impls/sycl/CMakeLists.txt
- Build different backends (impl types) as object libraries using common ov cmake utils
=> [GPU] Update cmake scripts for impls

.github/workflows/workflow_rerunner.yml
=> [CI] [GHA] Add Ubuntu 22 DPC++ workflow to rerunner

.github/actions/common/artifact_utils.py, .github/actions/common/constants.py
For convenience (solves build type case conflicts)
=> [GHA] Auto-convert artifact keys to lower-case

README.md, samples/c/hello_nv12_input_classification/README.md, samples/cpp/benchmark/sync_benchmark/README.md, samples/cpp/benchmark/throughput_benchmark/README.md, samples/cpp/classification_sample_async/README.md, samples/cpp/hello_classification/README.md, samples/cpp/hello_nv12_input_classification/README.md, samples/cpp/hello_query_device/README.md, samples/cpp/hello_reshape_ssd/README.md, samples/cpp/model_creation_sample/README.md, samples/python/benchmark/sync_benchmark/README.md, samples/python/benchmark/throughput_benchmark/README.md, samples/python/classification_sample_async/README.md, samples/python/hello_classification/README.md, samples/python/hello_query_device/README.md, samples/python/hello_reshape_ssd/README.md, samples/python/model_creation_sample/README.md
**Details:** Correct supported devices link overall
=> [DOCS] Correct supported devices link overall

src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp
- Fixes of unit test errors on BMG, phase10
=> [GPU] Unit tests fixes, ph10

README.md
- Fixed system documentation requirements link
- Fixed supported documentation devices link
=> Fix links to supported devices

.github/workflows/mac.yml
- Set build id properly to use in the provider later
- *ticket-id*
=> [GHA] Set build id before the build step

src/common/snippets/src/lowered/linear_ir.cpp, src/common/snippets/src/lowered/pass/assign_registers.cpp, src/common/snippets/src/lowered/pass/fuse_loops.cpp, src/common/snippets/src/lowered/pass/init_live_ranges.cpp, src/common/snippets/src/lowered/pass/insert_broadcastmove.cpp, src/common/snippets/src/lowered/pass/insert_buffers.cpp, src/common/snippets/src/lowered/pass/insert_loops.cpp, src/common/snippets/src/lowered/pass/mark_invariant_shape_path.cpp, src/common/snippets/src/lowered/pass/mark_loops.cpp, src/common/snippets/src/lowered/pass/propagate_subtensors.cpp, src/common/snippets/src/lowered/pass/validate.cpp, src/common/snippets/src/op/subgraph.cpp, src/common/snippets/src/pass/collapse_subgraph.cpp, src/common/snippets/src/pass/mha_tokenization.cpp, src/common/snippets/src/pass/transform_convert.cpp, src/common/snippets/src/pass/validate.cpp, src/common/snippets/src/shape_inference/shape_inference.cpp, src/common/snippets/src/utils/tokenization_utils.cpp
- Use ov::is_type_any_of where applicable in snippets common component
- N/A
=> [Snippets] Use ov::is_type_any_of for ov::is_type chains

src/common/snippets/include/snippets/pass/propagate_precision.hpp, src/common/snippets/src/pass/propagate_precision.cpp
- Fix "Uncaught exception" coverity remarks with CID 1590971 and 1590972
- 162506
=> [Snippets] Fix uncaught exception coverity issues

src/plugins/intel_gpu/src/graph/impls/common/condition.cpp
- when memory changed set memory changed flag to set_arguments in primitive_inst::prepare_primitive()
- 155709
=> [GPU] condition prim - set memory changed flag

src/plugins/intel_gpu/include/intel_gpu/primitives/paged_attention.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/plugin/ops/paged_attention.cpp, src/plugins/intel_gpu/src/plugin/transformations/increase_position_ids_precision.cpp, src/plugins/intel_gpu/tests/unit/transformations/increase_position_ids_precision_test.cpp
- Extended IncreasePositionIdsPrecision to support Matmul followed by Reshape, improving accuracy for large context sizes
- Added support for sliding window size PA parameter
- Fixed PA caching: added missing scale and fixed PA primitive descriptor comparator
=> [GPU] PagedAttention improvements and fixes

.github/workflows/job_build_windows.yml, .github/workflows/job_samples_tests.yml, .github/workflows/windows_conditional_compilation.yml
- Use 14.42 toolset to be aligned with genai ci
- *ticket-id*
=> [GHA] VS 14.42 toolset

.github/workflows/job_build_windows.yml, .github/workflows/windows_vs2022_debug.yml, .github/workflows/windows_vs2022_release.yml
=> [CI] [GHA] [WIN] Separately build contrib, use Python 3.11 as the default one after building additional wheels

src/plugins/intel_gpu/src/graph/CMakeLists.txt
- Regression after https://github.com/openvinotoolkit/openvino/pull/29137
- CVS-161069
=> Fixed GPU plugin debug build

src/plugins/intel_gpu/src/graph/impls/common/wait_for_events.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/border.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/multi_stage_primitive.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h, src/plugins/intel_gpu/src/graph/impls/sycl/primitive_sycl_base.h, src/plugins/intel_gpu/src/graph/include/primitive_inst.h, src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- Updated internal buffers interface and added BufferDescriptor struct for internal buffers description
- Applied review comments from https://github.com/openvinotoolkit/openvino/pull/29137
=> [GPU] Update internal buffers interface

src/common/transformations/src/transformations/common_optimizations/lin_op_sequence_fusion.cpp, src/common/transformations/tests/common_optimizations/lin_op_sequence_fusion_test.cpp
- fix AddAddFusion transformation.  don't allow AddAddFusion to work with all types that are not supported
- add unit test
- 163022
=> [TRANSFORMATIONS] don't allow AddAddFusion to work with f64

src/plugins/intel_gpu/src/graph/impls/ocl/border.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/multi_stage_primitive.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp, src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp, src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h, src/plugins/intel_gpu/src/graph/include/paged_attention_inst.h, src/plugins/intel_gpu/src/graph/include/primitive_inst.h
- Minor improvement for a patch added in https://github.com/openvinotoolkit/openvino/pull/29263
=> [GPU] Improve BufferDescriptor API for internal buffers

src/plugins/intel_npu/src/backend/include/zero_host_tensor.hpp, src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp, src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp, src/plugins/intel_npu/src/backend/include/zero_remote_tensor.hpp, src/plugins/intel_npu/src/backend/src/zero_device.cpp, src/plugins/intel_npu/src/backend/src/zero_host_tensor.cpp, src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp, src/plugins/intel_npu/src/backend/src/zero_remote_tensor.cpp, src/plugins/intel_npu/src/common/include/intel_npu/common/igraph.hpp, src/plugins/intel_npu/src/common/src/igraph.cpp, src/plugins/intel_npu/src/compiler_adapter/include/ze_graph_ext_wrappers.hpp, src/plugins/intel_npu/src/compiler_adapter/src/driver_graph.cpp, src/plugins/intel_npu/src/compiler_adapter/src/plugin_graph.cpp, src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp, src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_utils.hpp
- *Optimize findCommandQueueGroupOrdinal method and get only once device properties*
=> [NPU] Optimize findCommandQueueGroupOrdinal method and get only once device properties

src/cmake/install_tbb.cmake
- *fix custom tbb's installation path to runtime/3rdparty/tbb*
- *add tbb_dev component to cpack for custom tbb*
- *ticket-id*
=> fix installation path and add tbb_dev to cpack

.github/workflows/job_pytorch_models_tests.yml, .github/workflows/ubuntu_22.yml
=> [CI] [GHA] Remove usage of `sudo` from workflows

src/bindings/python/src/openvino/frontend/pytorch/patch_model.py, src/bindings/python/src/openvino/frontend/pytorch/utils.py, tests/layer_tests/py_frontend_tests/test_torch_decoder.py
- *Support F8 constants*
- *Allow to set patch condition externally*
- *ticket-id*
=> [PT FE] Support F8 constants

licensing/third-party-programs.txt
Leftover of https://github.com/openvinotoolkit/openvino/pull/29271
=> [CPU][ARM] Update kleidiai licence

src/frontends/pytorch/src/op/linear.cpp, src/frontends/pytorch/src/op_table.cpp, tests/layer_tests/py_frontend_tests/test_torch_frontend.py
- *Make patched matmuls fp32*
- *CVS-163207*
=> [PT FE] Make patched matmuls fp32

src/common/transformations/include/transformations/utils/utils.hpp, src/common/transformations/src/transformations/common_optimizations/lin_op_sequence_fusion.cpp, src/common/transformations/src/transformations/common_optimizations/weights_dequantize_to_fake_quantize.cpp, src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.cpp
- change eltwise_fold to make_try_fold
- 163022
=> [TRANSFORMATIONS] change eltwise_fold to make_try_fold

src/bindings/python/src/openvino/frontend/pytorch/utils.py, src/frontends/common/include/openvino/frontend/complex_type_mark.hpp, src/frontends/common/src/complex_type_mark.cpp, src/frontends/pytorch/src/op/abs.cpp, src/frontends/pytorch/src/op/exp.cpp, src/frontends/pytorch/src/op_table.cpp, src/frontends/pytorch/src/utils.hpp, src/frontends/tensorflow_common/src/op/complex_abs.cpp, tests/layer_tests/pytorch_tests/test_unary_ops.py
- *Support complex `aten::abs` and `aten::exp`*
- *CVS-160711*
=> [PT FE] Support complex aten::abs and aten::exp

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl, src/plugins/intel_gpu/src/runtime/execution_config.cpp
- Enable KV-cache compression for systolic platforms by default for PagedAttention-based models
- Small fix for large head_size configuration in case of applied SG_SCALE
=> [GPU] Enable KV-cache compression for systolic platforms by default

src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
- *Create event pool only when needed*
=> [NPU] Create event pool only when needed

src/plugins/intel_gpu/src/graph/program_helpers.cpp, src/plugins/intel_gpu/tests/unit/passes/add_onednn_optimization_attributes_test.cpp
- Criteria for sum_post_op was too restrictive
- For a residual connection as in resnet-50, we can use sum where the parent has two children.
- 160300
=> [GPU] More sum post op

src/common/util/include/openvino/util/weights_path.hpp, src/common/util/src/weights_path.cpp, src/inference/src/dev/core_impl.cpp, src/inference/src/dev/core_impl.hpp, src/plugins/intel_gpu/include/intel_gpu/primitives/data.hpp, src/plugins/intel_gpu/include/intel_gpu/runtime/options.inl, src/plugins/intel_gpu/src/graph/program.cpp, src/plugins/intel_gpu/src/plugin/compiled_model.cpp, src/plugins/intel_gpu/src/plugin/plugin.cpp, src/plugins/intel_gpu/tests/functional/behavior/model_cache.cpp
- Contains base change https://github.com/openvinotoolkit/openvino/pull/29107
- CVS-163449
=> [GPU] Support weightless blob when ov::Model is passed to compile_model

src/frontends/pytorch/src/op/repeat_interleave.cpp, tests/layer_tests/pytorch_tests/test_repeat_interleave.py
- *Support aten::repeat_interleave when repeats are tensor*
- *CVS-160711*
=> [PT FE] Support aten::repeat_interleave when repeats are tensor

cmake/dependencies.cmake
- *fix flags for tbbbind library on mac os*
- *161107*
=> update oneTBB 2021.13.0 for mac os

src/frontends/pytorch/src/op/slice.cpp
- *Fold Reshape during Slice axis translation*
- *DeepSeek R1 related*
=> [Py FE] Try folding slice axis

docs/articles_en/about-openvino/openvino-ecosystem/openvino-project/openvino-test-drive.rst, docs/articles_en/assets/images/TestDrive_image_generation.gif, docs/articles_en/assets/images/TestDrive_rag_1.gif, docs/articles_en/assets/images/TestDrive_rag_2.gif, docs/articles_en/assets/images/TestDrive_rag_base.gif, docs/articles_en/assets/images/TestDrive_st_import.gif, docs/articles_en/assets/images/TestDrive_ts_video.gif, docs/articles_en/assets/images/TestDrive_vlm_1.gif, docs/articles_en/assets/images/TestDrive_vlm_2.gif
Porting: https://github.com/openvinotoolkit/openvino/pull/29213
=> [DOCS] Update OpenVINO Test Drive article for 25.0

src/plugins/intel_npu/tools/omz_version.json
- To include https://github.com/openvinotoolkit/open_model_zoo/pull/4002 in the default configuration
- E-159926
=> Update OMZ version for NPU tools 25ww11

src/bindings/python/src/openvino/frontend/pytorch/patch_model.py, src/common/transformations/include/transformations/fp16_compression/mark_decompression_convert_constant_folding.hpp, src/common/transformations/src/transformations/fp16_compression/mark_decompression_convert_constant_folding.cpp, src/frontends/pytorch/src/frontend.cpp, src/frontends/pytorch/src/op/embedding.cpp, src/frontends/pytorch/src/op/linear.cpp, tests/layer_tests/py_frontend_tests/test_torch_frontend.py
- *Support converting f8 compressed models*
- *CVS-164161*
=> [PT FE] Support converting f8 compressed models

src/bindings/python/src/openvino/_ov_api.py, src/bindings/python/tests/test_runtime/test_model.py
- Previously it showed some default error.
- Since 2025.0 `Model` implementation changed inside, it doesn't show any error
- So added it
- *ticket-id*
=> [PyOV] Throw error if model is created without arguments

src/frontends/ir/src/ir_deserializer.cpp, src/frontends/ir/tests/frontend_test_basic.cpp
- Replace regex usage by standard iteration as on MSVC is not working correctly
- EISW-157577
=> [core] Fix regex out of memory error

src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_threading_tests.cpp
- *Changing func test config for CoreThreadingTest*
=> [NPU] Changing func test config for CoreThreadingTest

src/core/include/openvino/runtime/tensor.hpp, src/core/src/runtime/tensor.cpp, src/core/tests/tensor_utils.cpp
- Make mmap an option for read_tensor_data
- [CVS-162941](https://jira.devtools.intel.com/browse/CVS-162941)
=> Make mmap an option for read_tensor_data

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/plugin/src/remote_context.cpp
- *Get value or default value in case of std::optional is not set*
=> [NPU] Get value or default value in case of std::optional is not set

src/plugins/intel_cpu/src/utils/debug_caps_config.cpp
Fix for compilation issue on master branch
- N/A
=> [CPU][DEBUG_CAPS] Hotfix for env vars handling

tests/requirements_jax
**Details:** Test JAX support against latest version
=> [JAX FE] Test JAX support against latest version

src/core/src/op/constant.cpp
https://github.com/openvinotoolkit/openvino/pull/29451
=> Cherry-pick #29451

src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/attn_quant.cpp, src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/executor_pa.cpp
- *Fix dot_product kernel with avx2 support*
- *ticket-id*
=> [CPU]Fix by_channel quant for avx2

src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
=> [GPU] minor code style fixes

.github/workflows/linux_conditional_compilation.yml
=> [CI] [GHA] Increase timeout for CC job in Linux CC

.github/workflows/debian_10_arm.yml, .github/workflows/job_cpu_functional_tests.yml, .github/workflows/linux_arm64.yml, .github/workflows/mac.yml, .github/workflows/mac_arm64.yml, .github/workflows/ubuntu_22.yml, src/plugins/intel_cpu/tests/functional/custom/extension/extension.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/compiled_model/cpu_reservation_test.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- *item1*
- *...*
- *ticket-id*
=> [GHA][CPU]Test filter for precommit fixed

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/quantize_gpu_scale_shift_vload8_opt.cl, src/plugins/intel_gpu/tests/unit/test_cases/quantize_gpu_test.cpp
- adding missing macro definition
- backport of https://github.com/openvinotoolkit/openvino/pull/29561
- 164533
=> fix error in kernel

src/core/src/op/constant.cpp
This reverts commit d18619a6b7fb47fe5bdcb657cb6731a081f2e3ca.
=> Revert Cherry-pick #29451 (#29481)

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/quantize_gpu_scale_shift_vload8_opt.cl, src/plugins/intel_gpu/tests/unit/test_cases/quantize_gpu_test.cpp
- adding missing macro definition
- CVS-164533
=> fix missing macro defs in kernel

src/plugins/intel_gpu/src/graph/impls/cm/xetla_lstm_gemm.cm, src/plugins/intel_gpu/src/graph/impls/cm/xetla_lstm_loop.cm, src/plugins/intel_gpu/src/graph/impls/ocl/kernels_cache.hpp
- In https://github.com/openvinotoolkit/openvino/pull/26985 special processing of batch headers for micro-kernel based impls was accidentally removed. This patch restores it.
=> [GPU] Restore separate processing for micro headers

src/plugins/intel_npu/tools/protopipe/src/utils/utils.hpp
- *Fix protopipe build on windows*
=> [NPU] Fix protopipe build on windows

.github/actions/common/artifact_utils.py, .github/actions/create_manifest/create_manifest.py, .github/actions/restore_artifacts/action.yml, .github/actions/restore_artifacts/restore_artifacts.py, .github/actions/store_artifacts/action.yml, .github/actions/store_artifacts/store_artifacts.py
Required since we're handling artifacts from different repositories as separate product components now
=> [GHA] Separate folder structure for artifacts from different repos

.github/workflows/job_cpu_functional_tests.yml, .github/workflows/job_tensorflow_layer_tests.yml, .github/workflows/ubuntu_22.yml
- *163677*
- *160104*
- *159397*
=> [CI] [GHA] Increase TF Layer tests, CPU Functional, and Conformance timeouts

.github/actions/openvino_provider/action.yml
Needed after https://github.com/openvinotoolkit/openvino/pull/29635
Checking now both "openvino" and "dldt" variants in manifest (for backward compatibility)
=> [GHA] Fix for getting version in provider

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp, src/plugins/intel_gpu/src/graph/impls/cpu/shape_of.cpp, src/plugins/intel_gpu/tests/unit/test_cases/shape_of_gpu_test.cpp
- *Support 7 dimension case for shape of input*
- *164660*
=> Support 7dim shape of

docs/articles_en/about-openvino/performance-benchmarks/performance-benchmarks-faq.rst, docs/articles_en/openvino-workflow.rst, docs/articles_en/openvino-workflow/model-preparation.rst, docs/sphinx_setup/index.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/29623
=> [DOCS] Wording alignment for 25.1

src/plugins/intel_npu/src/plugin/src/backends_registry.cpp
=> [NPU] Fix typo

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] update atomic initialization to 25.1

src/bindings/python/README.md, src/bindings/python/docs/stubs.md
Related to https://github.com/openvinotoolkit/openvino/pull/29139
- CVS-163067
=> [PyOV] Add Python stub files developer documentation

docs/sphinx_setup/_static/js/custom.js
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Update Atomic initialization 

.github/workflows/linux_riscv_xuantie_dev_cpu.yml
- *item1*
- *...*
- *ticket-id*
=> [GHA][CPU] Triggering events expanded for xuantie job

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp, src/plugins/intel_gpu/src/graph/impls/cpu/shape_of.cpp, src/plugins/intel_gpu/tests/unit/test_cases/shape_of_gpu_test.cpp
- *Support 7 dimension case for shape of input*
- *164660*
=> Support 7dim shape of (#29669)

src/plugins/intel_npu/src/plugin/src/plugin.cpp, src/plugins/intel_npu/tests/functional/main.cpp
- *Create a copy of the model when compiling a model since this will suffer some changes*
- *Increase the time out for the functional tests to 30 minutes on Linux platforms*
- *E#148189*
=> [NPU] Create a copy to the model for the compilation path

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
Backport of (https://github.com/openvinotoolkit/openvino/pull/29767) to releases/2025/1
=> [GPU] Fix clEnqueueCopyBuffer error in RemoteTensor use case

src/bindings/python/src/openvino/_ov_api.py
- Port of https://github.com/openvinotoolkit/openvino/pull/29785
- [CVS-164395](https://jira.devtools.intel.com/browse/CVS-164395)
=> [Py OV] Fix openvino.Model documentation

src/inference/src/dev/core_impl.cpp
- backport from https://github.com/openvinotoolkit/openvino/pull/29804
- 164342
=> Updated to set cacheContent.model only for OPTIMIZE_SIZE mode

docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/generation/random-uniform-8.rst
Fixing math equations and formatting of code blocks.
=> [DOCS] Fixing math equations and code blocks in RandomUniform

src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp, src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp, src/plugins/intel_npu/src/backend/include/zero_profiling.hpp, src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp, src/plugins/intel_npu/src/backend/src/zero_profiling.cpp
- *Refactoring Pipeline object*
- *CVS-164942*
=> [NPU] Refactoring Pipeline object

.github/workflows/ubuntu_22.yml, .github/workflows/ubuntu_24.yml
=> [CI] [GHA] Add `HF_TOKEN` to jobs working with HuggingFace

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
- Define get_node function to use template again in reorder_inputs
=> [GPU] reduce code duplication

src/common/snippets/include/snippets/lowered/port_descriptor.hpp, src/common/snippets/src/lowered/pass/propagate_subtensors.cpp, src/common/snippets/src/lowered/port_descriptor.cpp, src/plugins/intel_cpu/src/transformations/snippets/x64/pass/brgemm_to_brgemm_cpu.cpp, src/plugins/intel_cpu/src/transformations/tpp/x64/pass/eltwise_to_eltwise_tpp.cpp, src/plugins/intel_cpu/src/transformations/tpp/x64/pass/fuse_tpp_to_equations.cpp, src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/lowered/buffer_allocation.cpp
- Fix full dim subtensor value that is being set in BrgemmToBrgemmCPU pass for 1D scenario
- Add check that subtensor shape is less or equal to tensor shape
- 163738
=> [Snippets][CPU] Fix full dim subtensor setting for port descriptor

docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/generation/random-uniform-8.rst
Porting:
https://github.com/openvinotoolkit/openvino/pull/29812
=> [DOCS] Fixing math and code blocks in RandomUniform article

docs/articles_en/openvino-workflow-generative/inference-with-genai/inference-with-genai-on-npu.rst
Porting: https://github.com/openvinotoolkit/openvino/pull/29397
=> [DOCS] Updating optimum-intel version for 25.1

src/plugins/intel_cpu/src/emitters/plugin/x64/jit_conversion_emitters.cpp, src/plugins/intel_cpu/src/emitters/plugin/x64/jit_conversion_emitters.hpp, src/plugins/intel_cpu/src/graph_optimizer.cpp, src/plugins/intel_cpu/src/graph_optimizer.h, src/plugins/intel_cpu/src/nodes/gather.cpp, src/plugins/intel_cpu/src/nodes/gather.h, src/plugins/intel_cpu/src/nodes/kernels/x64/gather_uni_kernel.cpp, src/plugins/intel_cpu/src/nodes/kernels/x64/gather_uni_kernel.hpp, src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp, src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.hpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/gather_weights_decompression.cpp, src/tests/functional/plugin/shared/include/single_op_tests/gather.hpp, src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/gather.hpp, src/tests/functional/shared_test_classes/src/single_op/gather.cpp
- *Gather node support mixed precision real16 to f32*
- *Fuse precision convert to gather node in cpu plugin transformation*
- *The convert in this pattern should be skipped in snippets tokenization*
- *CVS-163987*
=> [CPU] Gather node support mixed precision real16 to f32

src/common/transformations/docs/README.md, src/common/transformations/docs/debug_capabilities/transformation_statistics_collection.md
Add OV Transformation statistics doc file
Fixed links
- *CVS-151320*
=> Add OV Transformation statistics doc file

src/common/transformations/include/transformations/common_optimizations/gelu_fusion.hpp, src/common/transformations/src/transformations/common_optimizations/gelu_fusion.cpp, src/common/transformations/tests/common_optimizations/gelu_fusion.cpp
Add multiple Multiply pattern instead of Pow.
- *155289*
=> [GPU] Support GeLU Tanh for SD

CMakeLists.txt
- WA to allow building OpenVINO with Cmake >= 4.0
-
=> WA for cmake >= 4.0

.github/workflows/ubuntu_22.yml
Refreshing our statistics for a new host number estimation
=> [GHA] Temporarily return GPU stub check

docs/articles_en/openvino-workflow/running-inference/optimize-inference/precision-control.rst
- Clarifed the behavior of accuracy mode
- 165376
=> [doc] update doc for execution_mode

docs/requirements.txt
- *item1*
- *...*
- *ticket-id*
=> DOCS Upgade jinja package

.github/scripts/workflow_rerun/errors_to_look_for.json
=> [CI] [GHA] Add network-related requirements installation fail message to rerunner 

src/plugins/intel_npu/tests/functional/internal/overload/ov_plugin/core_integration.hpp, src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_threading_tests.cpp
- *Update and add new func tests*
=> [NPU] Update and add new func tests

src/frontends/tensorflow_lite/src/tflite_transformations/tflite_quantize_resolver.cpp
- Added clarification about using quantization/dequantization approach
- N/A
=> [TFLite] Added quantization details

src/frontends/tensorflow_common/include/utils.hpp, src/frontends/tensorflow_common/src/op/squeeze.cpp, src/frontends/tensorflow_common/src/utils.cpp
**Details:** Avoid extra StringTensorPack operation during conversion. Otherwise, it can lead to performance degradation
=> [TF FE] Avoid extra StringTensorPack operation during conversion

docs/articles_en/openvino-workflow/torch-compile.rst
Minor fix in torch compile nncf quantization docs
=> [Docs][NNCF] torch-compile.rst minor fix

src/inference/src/dev/core_impl.cpp, src/inference/src/dev/core_impl.hpp, src/inference/tests/functional/ov_core_threading.cpp
- Add sync on existing extensions in read_model
- CVS-133087
=> Add sync on existing extensions in read_model.

docs/articles_en/openvino-workflow/torch-compile.rst
port: https://github.com/openvinotoolkit/openvino/pull/29098
=> [Docs][NNCF] torch-compile.rst minor fix (#29098)

src/tests/test_utils/common_test_utils/src/graph_comparator.cpp
- Removed restriction for subgraph result and output shapes comparison that these have to be either both static or both dynamic. There are valid subgraph nodes (Loop, TI) which pass node's validation where such assumption is inaccurate.
- CVS-110435
=> [Test] Graph comparator: Do not validate result and output when num_of_item is unknown

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/get-started/install-openvino/configurations/configurations-intel-gpu.rst
port: https://github.com/openvinotoolkit/openvino/pull/29927
=> [DOCS] release notes 25.1 port

docs/articles_en/openvino-workflow-generative/inference-with-optimum-intel.rst
port: https://github.com/openvinotoolkit/openvino/pull/29133/files
=> [GPU][Doc] Doc update for dyn_quan default configuration port 25.1

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/articles_en/about-openvino/performance-benchmarks/model-accuracy-int8-fp32.rst, docs/articles_en/about-openvino/performance-benchmarks/performance-benchmarks-faq.rst, docs/sphinx_setup/_static/css/custom.css, docs/sphinx_setup/_static/download/benchmarking_OV_platform_list.pdf, docs/sphinx_setup/_static/download/benchmarking_OV_system_info_detailed.xlsx
Port to: https://github.com/openvinotoolkit/openvino/pull/29979
=> [DOCS] benchmark files update - Port to master

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/dynamic_quantize_gpu_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_opt.cpp, src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/matmul_weights_decompression.cpp, src/plugins/intel_gpu/tests/unit/test_cases/dynamic_quantize_gpu_test.cpp
- Optimized dynamic_quanize kernel for gs128 and gs256 case
- Now the performance is on-par with per-token dyn_quan kernel
- 148732
=> [GPU] Optimize dynamic quantize kernel

docs/articles_en/get-started/install-openvino/configurations/genai-dependencies.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-linux.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-macos.rst, docs/articles_en/get-started/install-openvino/install-openvino-archive-windows.rst, docs/articles_en/get-started/install-openvino/install-openvino-conda.rst, docs/articles_en/get-started/install-openvino/install-openvino-genai.rst, docs/articles_en/get-started/install-openvino/install-openvino-zypper.rst
port: https://github.com/openvinotoolkit/openvino/pull/30009
=> [DOCS] update installation package links 25.1

src/plugins/intel_gpu/src/graph/impls/ocl_v2/rope_opt.cl, src/plugins/intel_gpu/src/graph/impls/ocl_v2/utils/jitter.cpp
- Support 2d input1/input2 in rope ocl_v2 kernel
- 165071
- 165072
=> [GPU] Support 2d input1/2(cos/sin) in rope ocl_v2 kernel

samples/cpp/common/format_reader/src/bmp.cpp, src/common/util/src/wstring_convert_util.cpp, src/core/dev_api/openvino/core/type/nf4.hpp, src/core/include/openvino/core/type/bfloat16.hpp, src/core/include/openvino/core/type/float16.hpp, src/core/include/openvino/core/type/float4_e2m1.hpp, src/core/include/openvino/core/type/float8_e4m3.hpp, src/core/include/openvino/core/type/float8_e5m2.hpp, src/core/include/openvino/core/type/float8_e8m0.hpp, src/core/reference/include/openvino/reference/gru_cell.hpp, src/inference/src/dev/iasync_infer_request.cpp, src/plugins/intel_cpu/src/nodes/rnn.cpp, src/plugins/intel_cpu/src/shape_inference/custom/one_hot.cpp, src/plugins/intel_gpu/src/graph/impls/cpu/proposal.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/graph.hpp, src/plugins/intel_npu/src/plugin/npuw/serialization.hpp, src/plugins/intel_npu/tools/single-image-test/semantic_segmentation_helpers.hpp
- Fix build issues for OpenVINO when using docker image with Fedora and gcc-15
- CVS-164531
- #29410
=> [build] Fix build issue using Fedora and gcc-15

docs/articles_en/about-openvino/release-notes-openvino.rst
port: https://github.com/openvinotoolkit/openvino/pull/30015
=> [DOCS] release notes update 2-25.1

src/plugins/intel_cpu/src/shape_inference/custom/one_hot.cpp
Fix issues appeared on master branch that fail clang-tidy verification
- 165753
=> [CPU] Hotfix for master branch build with clang-tidy issues

docs/dev/ci/github_actions/overview.md
=> [CI] [GHA] [DOCS] Add section on Merge Queue settings

src/plugins/intel_cpu/src/nodes/scaled_attn.cpp, src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/concat_transpose_sdp_transpose.cpp
- *Check beam index during kernel preparation phase*
- *Throw exception when beam_index is not valid*
- *Add test cases*
- *CVS-165496*
=> [CPU]Check beam index during init

samples/c/common/opencv_c_wrapper/src/bmp_reader.c
- Fix Coverity issue CID-1548298, `Overflowed integer argument`
- CVS-165565
=> [Coverity] Fix coverity in issue `Overflowed integer argument` in samples

src/common/snippets/src/pass/split_dimension_m.cpp, src/common/snippets/tests/include/utils/split_dim_m.hpp, src/common/snippets/tests/src/utils/split_dim_m.cpp, src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
Prevent `std::accumulate` to take an element under `shape.rbegin() + 2` iterator if size is `< 3`
- 164530
=> [Snippets][CPU] Fix out-of-bounds access in parallel work amount check

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gather_ref.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_kernel_ref.cpp
- when there is fused op it rely on indexes calculated before. On gather axis disappear in output
- 140654
=> [GPU] added proper index calculation for fused op in gather_ref

samples/js/node/package-lock.json, samples/js/node/package.json, src/bindings/js/node/package-lock.json, src/bindings/js/node/package.json
- Set released 2025.1.0 version to samples
- Update next version of js package to 2025.2.0
=> [JS] Update versions of js packages

tests/layer_tests/common/layer_utils.py, tests/layer_tests/common/mo_convert_test_class.py, tests/layer_tests/common/utils/common_utils.py, tests/layer_tests/jax_tests/jax_layer_test_class.py, tests/layer_tests/ovc_python_api_tests/test_complex_params.py, tests/layer_tests/ovc_python_api_tests/test_extensions.py, tests/layer_tests/ovc_python_api_tests/test_onnx.py, tests/layer_tests/ovc_python_api_tests/test_ovc_cli_tool.py, tests/layer_tests/ovc_python_api_tests/test_paddle.py, tests/layer_tests/ovc_python_api_tests/test_pytorch.py, tests/layer_tests/ovc_python_api_tests/test_tf.py, tests/layer_tests/py_frontend_tests/test_paddle_frontend.py, tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py, tests/layer_tests/tensorflow2_keras_tests/conftest.py, tests/layer_tests/tensorflow_tests/conftest.py, tests/model_hub_tests/models_hub_common/test_convert_model.py, tests/model_hub_tests/models_hub_common/test_performance_model.py, tests/model_hub_tests/pytorch/test_aliked.py, tests/samples_tests/smoke_tests/common/samples_common_test_class.py, tests/samples_tests/smoke_tests/test_benchmark_app.py
**Details:** It is needed to avoid multiple warnings in test logs.
=> [Layer tests] Remove legacy code and use of deprecated modules

src/common/transformations/src/transformations/common_optimizations/reverse_shape_and_type_infer.cpp
Add return status check for PartialShape::merge_into()
- [CVS-158857](https://jira.devtools.intel.com/browse/CVS-158857)
=> Add return status check for PartialShape::merge_into()

src/plugins/intel_gpu/include/intel_gpu/plugin/primitives_list.hpp, src/plugins/intel_gpu/src/plugin/ops/non_max_suppression.cpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- Support NMS op natively
- 158627
=> [GPU] Support NMS op natively

.github/workflows/job_pytorch_models_tests.yml
- *item1*
- *...*
- *ticket-id*
=> [TESTS] Increase timeout for model tests

tests/layer_tests/pytorch_tests/test_scaled_dot_product_attention.py
- *Fix seed for SDPA layer tests and remove FP64 from precommit*
- *CVS-157116*
=> [TESTS] Fix seed for SDPA layer tests and remove FP64 from precommit

src/core/src/op/convert.cpp
- *Not optimized version of the data type converter is called*
- *166017*
=> [CORE] Model compilation time regression related to the DT conversion.

src/common/snippets/src/pass/mha_tokenization.cpp, src/common/snippets/tests/src/pass/mha_tokenization.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha.cpp, src/tests/functional/plugin/shared/include/snippets/mha.hpp, src/tests/functional/plugin/shared/src/snippets/mha.cpp, src/tests/ov_helpers/ov_snippets_models/include/subgraph_mha.hpp, src/tests/ov_helpers/ov_snippets_models/src/subgraph_mha.cpp
=> [Snippets] Fix MHA 2D patterns tokenization and add MHA 2D pattern generator

src/plugins/intel_gpu/include/intel_gpu/primitives/dynamic_quantize.hpp, src/plugins/intel_gpu/src/graph/eltwise.cpp, src/plugins/intel_gpu/src/plugin/transformations/decompose_reduce_scalar_output.cpp
=> [GPU] fix coverity issues

src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h, src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_opt_kv_cache.cpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
- Use correct type for variable
- 165942
=> [GPU] Use correct type for variable

src/bindings/python/src/openvino/_ov_api.py, src/bindings/python/tests/test_runtime/test_model.py
- ![image](https://github.com/user-attachments/assets/1fc59b80-5de7-4716-834c-be44a4f55cd3)
- [CVS-164194](https://jira.devtools.intel.com/browse/CVS-164194)
=> [PyOV] Improve error message in Model init in _ov_api.py

docs/snippets/CMakeLists.txt, src/common/low_precision_transformations/CMakeLists.txt, src/common/snippets/src/pass/collapse_subgraph.cpp, src/common/transformations/CMakeLists.txt, src/common/transformations/src/transformations/common_optimizations/activations_scaling.cpp, src/common/transformations/src/transformations/common_optimizations/convert_pagedattn_inputs.cpp, src/common/transformations/src/transformations/common_optimizations/fq_reshape_fusion.cpp, src/common/transformations/src/transformations/common_optimizations/lstm_cell_fusion.cpp, src/common/transformations/src/transformations/common_optimizations/mark_rope_input_to_keep_in_mixed_precision.cpp, src/common/transformations/src/transformations/common_optimizations/pull_transpose_through_fq.cpp, src/common/transformations/src/transformations/common_optimizations/rms_fusion.cpp, src/common/transformations/src/transformations/common_optimizations/sdpa_fusion.cpp, src/common/transformations/src/transformations/common_optimizations/sdpa_scale_fusion.cpp, src/common/transformations/src/transformations/op_conversions/convert_ti_to_sequences.cpp, src/frontends/jax/src/CMakeLists.txt, src/frontends/paddle/src/CMakeLists.txt, src/frontends/pytorch/src/CMakeLists.txt, src/plugins/intel_gpu/CMakeLists.txt, src/plugins/intel_gpu/src/plugin/transformations/convert_stridedslices_to_variadicsplit.cpp, src/plugins/intel_gpu/src/plugin/transformations/dynamic_quantize_fully_connected.cpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
Fix `implicit capture of 'this' with a capture default of '=' is deprecated` warnings
- N/A
=> Remove -Wno-error=deprecated suppression

src/plugins/intel_gpu/docs/gpu_plugin_ops_enabling.md
- Changed deprecated API, definitions
- Updated broken link : operation specification, other source tree, test guide
- Modified adding(extending) GPU primitive (ocl_v2)
- Modified description about testing
- *ticket-id*
=> [GPU] Update docs for gpu_plugin_ops_enabling

src/plugins/intel_gpu/src/graph/impls/ocl/convolution.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_pil_ref.cpp, src/plugins/intel_gpu/src/kernel_selector/tensor_type.cpp
- Channel index cannot be negative value
- 165941
=> [GPU] Prevent channel index from becoming negative

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/articles_en/about-openvino/release-notes-openvino.rst
port: https://github.com/openvinotoolkit/openvino/pull/30126
=> [DOCS] post-release polishing 25.1 port

src/plugins/intel_cpu/src/nodes/input.cpp
=> [CPU] Remove redundant NOLINT comments in Input node implementation

docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ovms-genai.json
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Fix

src/frontends/onnx/frontend/src/core/transform.hpp, src/frontends/onnx/frontend/src/op/neg_log_like_loss.cpp, src/frontends/onnx/tests/__init__.py, src/frontends/onnx/tests/tests_python/test_backend.py
- Added a native translator for function NegativeLogLikelihoodLoss
- N/A
=> [ONNX] Added native translator for NegativeLogLikelihoodLoss

tests/layer_tests/tensorflow_tests/test_tf_Swish.py
**Details:** Test Swish function in precommit
=> [TF FE] Test Swish function in precommit

src/bindings/python/src/openvino/frontend/jax/jaxpr_decoder.py, src/bindings/python/src/openvino/frontend/jax/utils.py, tests/requirements_jax, tools/ovc/openvino/tools/ovc/convert_impl.py
**Details:** Support JAX 0.6.0
**Ticket:** 166559
=> [JAX FE] Support JAX 0.6.0

src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/compute.cpp
Fixing https://github.com/openvinotoolkit/openvino/pull/29456
=> [NPUW] Fix FakeConvert patterns

src/common/snippets/include/snippets/pass/extract_reshapes_from_mha.hpp, src/common/snippets/src/pass/extract_reshapes_from_mha.cpp, src/common/snippets/tests/src/pass/mha_tokenization.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha_extracted_reshape.cpp, src/tests/functional/plugin/shared/include/snippets/mha.hpp, src/tests/functional/plugin/shared/src/snippets/mha.cpp, src/tests/ov_helpers/ov_snippets_models/include/subgraph_mha.hpp, src/tests/ov_helpers/ov_snippets_models/src/subgraph_mha.cpp
- *Shift rank upgrade reshape from mha body to rank reduction reshape in mha input branch*
- *CVS-162708*
=> [Snippets] Shift rank upgrade reshape from mha body to rank reduction reshape in mha input branch

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
=> [GPU] added deconvolution missing info

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_emitter.cpp, src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_emitter.cpp
Moved changes from https://github.com/openvinotoolkit/openvino/pull/30296 to other platforms
=> [CPU][RV64][ARM64] Replace assert with static_assert in jit_emitter

src/tests/test_utils/functional_test_utils/include/functional_test_utils/skip_tests_config.hpp
Scheduled to be removed when it becomes unused in #19663
- N/A
=> [TESTS] Remove unused 'currentTestIsDisabled' wrapper

src/plugins/intel_npu/src/plugin/npuw/partitioning/partitioning.cpp
=> [NPUW] Fix clang sort in partitioning

src/bindings/python/src/pyopenvino/graph/op.cpp, src/bindings/python/tests/test_graph/test_custom_op.py
- *item1*
- *...*
- CVS-164354
=> [PyOV] Fix custom op test which hangs on win

src/frontends/onnx/frontend/src/editor.cpp
- Fixed issue which caused a hang in case of empty inputs/outputs provided to a Node
- 164919
=> [ONNX] Fixed behavior of unspecified inputs/outputs while sorting

src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected_primitive.cpp, src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/matmul_weights_decompression.cpp
Apply oneDNN patch: https://github.com/openvinotoolkit/oneDNN/pull/280
- 165186
=> [CPU] Fix oneDNN dynamic quantization enabling on small shapes

src/plugins/intel_gpu/src/plugin/ops/convolution.cpp
=> [GPU] added deconv missing info

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst, src/bindings/python/src/pyopenvino/core/properties/properties.cpp, src/bindings/python/tests/test_runtime/test_properties.py, src/inference/include/openvino/runtime/intel_npu/properties.hpp, src/plugins/intel_npu/README.md, src/plugins/intel_npu/src/al/include/intel_npu/npu_private_properties.hpp, src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp, src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp, src/plugins/intel_npu/src/compiler_adapter/src/driver_graph.cpp, src/plugins/intel_npu/src/compiler_adapter/src/plugin_graph.cpp, src/plugins/intel_npu/src/plugin/src/properties.cpp, src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_types.hpp, src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_wrappers.hpp, src/plugins/intel_npu/src/utils/src/zero/zero_wrappers.cpp, src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp
- *Adding support for in-order execution based on the driver implementation*
- *E#159513*
=> [NPU] Adding support for in-order execution

.github/workflows/android_arm64.yml, .github/workflows/android_x64.yml, .github/workflows/fedora_29.yml, .github/workflows/linux_arm64.yml, .github/workflows/linux_conditional_compilation.yml, .github/workflows/linux_riscv.yml, .github/workflows/manylinux_2014.yml, .github/workflows/ubuntu_20.yml, .github/workflows/ubuntu_22.yml, .github/workflows/ubuntu_22_dpcpp.yml, .github/workflows/ubuntu_24.yml, .github/workflows/webassembly.yml
- Should fix issues like https://github.com/openvinotoolkit/openvino/actions/runs/14763785167/job/41473078922?pr=30383#step:3:29
=> [CI] [GHA] Add missing skip for the build jobs if their pipeline should be skipped

.github/workflows/ubuntu_22.yml
- Should fix https://github.com/openvinotoolkit/openvino/actions/runs/14775757124?pr=30383
=> [CI] [GHA] Fix json for mock Docker images in Linux 22.04 workflow

src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/attn_quant.cpp
- *PA with dynamic_split_fuse may split the prompt into multiple chunks*
- *The quant by channel kernel has wrong index selection under this situation*
- *CVS-166874*
=> [CPU]fix by_channel quant with past

src/plugins/intel_npu/src/plugin/npuw/partitioning/online/group.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/snapshot.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/avoid.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/avoid.hpp
=> [NPUW] Add SinCos pattern to avoid

src/common/snippets/src/pass/hash.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/convolution.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/gather.cpp
=> [CPU] Fix deprecation warnings and remove deprecated warning suppression

.github/workflows/android_arm64.yml, .github/workflows/android_x64.yml, .github/workflows/coverity.yml, .github/workflows/debian_10_arm.yml, .github/workflows/fedora_29.yml, .github/workflows/job_build_linux.yml, .github/workflows/job_build_windows.yml, .github/workflows/job_tokenizers.yml, .github/workflows/linux_arm64.yml, .github/workflows/linux_conditional_compilation.yml, .github/workflows/linux_riscv.yml, .github/workflows/linux_riscv_xuantie_dev_cpu.yml, .github/workflows/linux_sanitizers.yml, .github/workflows/mac.yml, .github/workflows/mac_arm64.yml, .github/workflows/manylinux_2014.yml, .github/workflows/ovc.yml, .github/workflows/ubuntu_20.yml, .github/workflows/ubuntu_22.yml, .github/workflows/ubuntu_22_dpcpp.yml, .github/workflows/ubuntu_24.yml, .github/workflows/webassembly.yml, .github/workflows/windows_conditional_compilation.yml, .github/workflows/windows_vs2022_debug.yml, .github/workflows/windows_vs2022_release.yml
Enabling manual builds from an arbitrary revision
=> [GHA] Add target-branch input for workflow_dispatch trigger

src/plugins/intel_cpu/src/nodes/dft.cpp
- CPU DFT `createPrimitve` code refactor (no logic changes intended)
- follow up: https://github.com/openvinotoolkit/openvino/pull/29940
=> [CPU][DFT] CPU DFT createPrimitve code refactor

src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/causal_mask_preprocess_fusion.cpp
Fix Coverity remark 1542737
- 165923
=> [CPU] Fix Coverity remarks related to nullptr dereference and invalid iterator

src/common/snippets/include/snippets/op/subgraph.hpp, src/common/snippets/src/lowered/expressions/buffer_expression.cpp, src/common/snippets/src/op/subgraph.cpp
- *Fixed coverity issues: "dead code" and "Uncaught exception"*
- *CVS-167168*
=> [Snippets] Fixed coverity issues 167168

src/plugins/intel_gpu/include/intel_gpu/primitives/fully_connected.hpp, src/plugins/intel_gpu/include/intel_gpu/primitives/primitive.hpp, src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp, src/plugins/intel_gpu/src/graph/program.cpp
- Previously, we had member-by-member copy for bias fusion, which is error-prone
- Added clone() method to copy FC primitive
- Removed const from primitive id because it can be changed after creation
=> [GPU] Code refactoring for cloning fc primitive

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp, src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp
- Fixed wrong eltwise handling as bias 
- CVS-166697
=> [GPU] Fixed wrong eltwise handling as bias 

.github/workflows/android_arm64.yml, .github/workflows/android_x64.yml, .github/workflows/debian_10_arm.yml, .github/workflows/fedora_29.yml, .github/workflows/job_build_linux.yml, .github/workflows/job_build_windows.yml, .github/workflows/job_gpu_tests.yml, .github/workflows/job_jax_models_tests.yml, .github/workflows/job_pytorch_models_tests.yml, .github/workflows/job_tensorflow_models_tests.yml, .github/workflows/linux_arm64.yml, .github/workflows/linux_conditional_compilation.yml, .github/workflows/linux_riscv.yml, .github/workflows/linux_sanitizers.yml, .github/workflows/manylinux_2014.yml, .github/workflows/ubuntu_20.yml, .github/workflows/ubuntu_22.yml, .github/workflows/ubuntu_22_dpcpp.yml, .github/workflows/ubuntu_24.yml, .github/workflows/webassembly.yml, .github/workflows/windows_vs2022_debug.yml, .github/workflows/windows_vs2022_release.yml
- Port of #30305, #30398, #30401, and #29619
=> [CI] [GHA] Correctly report statuses of skipped jobs that have `inputs` from `needs`

src/frontends/paddle/src/internal/pass/transform_if.cpp
- *Fix coverity issues*
- *CVS-167178*
=> [CPU]Fix coverity check issues

src/plugins/intel_cpu/src/utils/blob_dump.cpp
=> [CPU][DEBUG CAPS] Add support for boolean and string types in blob dumping

src/frontends/onnx/CMakeLists.txt, src/frontends/onnx/docs/check_supported_ops.py, src/frontends/onnx/docs/how_to_add_op.md, src/frontends/onnx/docs/supported_ops.md, src/frontends/onnx/docs/tests.md, src/frontends/onnx/frontend/src/op/reduce.cpp
- Updated ONNX Frontend documentation
- Added list of available operators and when it was originally defined
- Added script for auto-check for registration correctness and supported ops list generation
- 161016
=> [ONNX] Updated frontend's documentation

src/core/include/openvino/core/type/element_type.hpp, src/core/src/op/paged_attention.cpp, src/core/tests/type_prop/paged_attention.cpp
It's getting harder to review and maintain validate method of PagedAttention op.
Updated unit tests
- *N/A*
=> PagedAttention op, validate refactoring 

src/core/include/openvino/runtime/allocator.hpp, src/core/src/runtime/allocator.cpp, src/core/tests/ov_tensor_test.cpp, src/inference/src/dev/make_tensor.cpp
- Do not throw from ~AllocatedTensor
- fix coverity 1506561
- CVS-165950
=> Do not throw from ~AllocatedTensor

src/frontends/paddle/tests/test_models/gen_scripts/generate_embedding.py
- try to fix CI for https://github.com/openvinotoolkit/openvino/pull/29418
- *ticket-id*
=> Try to update some pdpd tests to numpy2.0

.github/workflows/linux_arm64.yml, .github/workflows/mac_arm64.yml, .github/workflows/ubuntu_22.yml, .github/workflows/ubuntu_24.yml, .github/workflows/windows_vs2022_release.yml
Leftover after https://github.com/openvinotoolkit/openvino/pull/30419
=> [GHA] Pass target-branch input to Tokenizers workflow

tools/commit_slider/common_architecture.md, tools/commit_slider/dev_guideline.md
- *item1*
- *...*
- *ticket-id*
=> [CS] Developer's guideline for CS

src/plugins/template/backend/int_executable.cpp
- Template plugin - update intexecutable.
- Fix coverity
- CVS-167170
=> Template plugin - update intexecutable. Fix coverity

.github/actions/create_manifest/action.yml, .github/actions/create_manifest/create_manifest.py, .github/workflows/job_build_linux.yml, .github/workflows/job_build_windows.yml, .github/workflows/mac.yml, .github/workflows/manylinux_2014.yml
=> [GHA] Fix manifest trigger repo branch for manual builds

.github/workflows/job_build_linux.yml
- *incorrect passing of cmake options via context https://github.com/openvinotoolkit/openvino/actions/runs/14905138314/job/41865930016 (reproduced on arm jobs)*
=> [GHA] Cmake options passing for tests fixed

src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_convolution_primitive.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/convolution.cpp
Autopading should be applied even if padding inputs are non-zero.
- 166078
=> [CPU] Fix Convolution auto padding handling

src/core/reference/include/openvino/reference/gather.hpp, src/plugins/template/backend/ops/gather.cpp
- Fix Coverity 2355517
- CVS-167169
=> Coverity 2355517

src/plugins/intel_cpu/src/nodes/conv.cpp, src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/conv_u8_fuse_sum_i8.cpp
- Allow different sum types with the equal size
=> [CPU] Correct sum input data type for INT8 Convolution sum fusing

.github/workflows/windows_vs2022_release.yml, src/bindings/js/node/scripts/lib/binary-manager.js
- Add bin directory search when installing a package from an archive on windows
- CVS-167473
=> [JS] Add windows support to search bin directory

src/plugins/intel_npu/src/plugin/src/plugin.cpp
- fixing issue detected by coverity check where we erase by iterator from different maps. Changing to erase by key
- EISW-167586
=> [intel-npu] fixing issue with erasing by iterator from differing maps

src/plugins/intel_npu/src/plugin/src/plugin.cpp
- *New `import_model` design:*
```mermaid
flowchart TD;
A["import_model(stream)"]-->B["orig_stream"];
B["orig_stream"]-->C["stream"];
D["import_model(stream, {{compiled_blob(tensor)}})"]-->E["tensor"];
E["tensor"]-->D1{"if tensor && !loaded_from_cache"};
L1@{ shape: text, label: "We want to allow applications to provide a tensor through the property alongside an empty/dummy stream"};
D1-->F["tmp_stream"];
F["tmp_stream"]-->C["stream"];
C["stream"]-->D2{"Is NPUW?"};
D2-- Yes -->G["NPUW"];
D2-- No -->H["ReadMetadata(stream)"];
H-->I["Create Tensor if not available"];
E-->I;
```
- *ticket-id*
=> [`intel_npu`] [`import_model`] Update `import_model` flow based on new design proposal

src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp, src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
- Add common scale support for oneDNN FC weights
- [CVS-167293](https://jira.devtools.intel.com/browse/CVS-167293)
=> [GPU] Fix oneDNN FC common scale for weights

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp, src/plugins/intel_gpu/src/graph/impls/cpu/shape_of.cpp, src/plugins/intel_gpu/tests/unit/test_cases/shape_of_gpu_test.cpp
- *Support 8 dimension input for shape_of primitive*
- *...*
- *167150*
=> [GPU] Support 8dims for shape_of

src/plugins/intel_cpu/src/nodes/qkv_proj.cpp
=> [CPU] reduce QKV fusion threshold to avoid regression on Qwen1.5B

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
- Resolve register spill on value loading for sdpa_opt w/ unaligned head size 
- CVS-167485
=> [GPU] Resolve sdpa_opt perf issue for unaligned HEAD_SIZE due to register spill 

src/plugins/intel_cpu/src/nodes/kernels/x64/registers_pool.hpp, src/plugins/intel_cpu/src/nodes/paged_attn.cpp, src/plugins/intel_cpu/src/nodes/paged_attn.h
Fix Coverity remarks:
- 2360980: Uncaught exception
- 167164
=> [CPU] Fix exception handling Coverity remark

.github/scripts/workflow_rerun/tests/integration_test.py
- Should fix: https://github.com/openvinotoolkit/openvino/actions/runs/14971387968/job/42075849860?pr=30379
- *167758*
=> [CI] [GHA] Do not check for found error in the integration test for rerunner

src/frontends/pytorch/src/frontend.cpp, src/frontends/pytorch/src/op/cat.cpp, src/frontends/pytorch/src/op/expand.cpp, src/frontends/pytorch/src/op/list_unpack.cpp, src/frontends/pytorch/src/op/slice.cpp, src/frontends/pytorch/src/op/split.cpp, src/frontends/pytorch/src/op_table.cpp, src/frontends/pytorch/src/transforms/prim_list_unpack_replacer.cpp, tests/layer_tests/pytorch_tests/test_cat.py, tests/layer_tests/pytorch_tests/test_expand.py, tests/layer_tests/pytorch_tests/test_slice.py, tests/layer_tests/pytorch_tests/test_split.py
- *Support complex tensors in operations: `aten::split_with_sizes`, `aten::slice`, `aten::cat`, `aten::expand`*
- *Support complex Rope pattern*
- *CVS-166647*
=> [PT FE] Support complex Rope pattern

src/plugins/intel_cpu/tests/functional/custom/behavior/ov_executable_network/properties.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/matmul_sparse.cpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/compiled_model/cpu_reservation_test.cpp, src/plugins/intel_cpu/tests/unit/shape_inference_test/static_shape_test.cpp
=> [CPU] Clean up redundant debug prints in tests

src/frontends/onnx/frontend/src/ops_bridge.cpp
- Fixed a possible iterator mismatch and simplified code using previously declared iterators
- 167179
=> [ONNX] Refactored possible iterator mismatch

tests/constraints.txt, tests/requirements_pytorch
- *Remove MacOS requirements*
- *CVS-167763*
=> Remove MacOS requirements

src/frontends/tensorflow/src/op/variable.cpp, src/frontends/tensorflow_common/src/op/addN.cpp, src/frontends/tensorflow_common/src/op/bias_add.cpp, src/frontends/tensorflow_common/src/op/pad.cpp
**Details:** Fix coverity issues
**Ticket:** 167176
=> [TF FE] Fix coverity issues

src/plugins/intel_gpu/include/intel_gpu/primitives/paged_attention.hpp, src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp, src/plugins/intel_gpu/src/graph/include/paged_attention_inst.h, src/plugins/intel_gpu/src/graph/paged_attention.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/plugin/ops/paged_attention.cpp, src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp
- Add scores window calculation support
- *ticket-id*
=> [GPU] Add PA scores window calculation support

docs/requirements.txt, src/common/transformations/src/transformations/common_optimizations/convolution_to_group_convolution.cpp, src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
- CID 2361330 Out-of-bounds access
- CID 2361331 Dereference null return value
- *CVS-167822*
=> [Transformations] Coverity fixes

src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp
- *Modified paged_attention_impl to use sdpa_micro kernel for prefill when seq_len is less than sliding window.*
- *167248*
=> [GPU] Use sdpa_micro if seq len is less than sliding window size

src/bindings/python/wheel/CMakeLists.txt
- *item1*
- *...*
- CVS-166974
=> [PyOV] Fix compatibility with MacOS 15.4

src/common/low_precision_transformations/src/clamp.cpp, src/common/low_precision_transformations/src/convolution.cpp, src/common/low_precision_transformations/src/convolution_backprop_data.cpp, src/common/low_precision_transformations/src/eliminate_fake_quantize.cpp, src/common/low_precision_transformations/src/fake_quantize.cpp, src/common/low_precision_transformations/src/reshape.cpp, src/common/low_precision_transformations/src/rt_info/intervals_alignment_attribute.cpp, src/common/low_precision_transformations/src/weightable_layer_transformation.cpp
=> [LPT] Coverity fixes: dereference null return value

samples/c/common/opencv_c_wrapper/src/bmp_reader.c
- CID 2354064, by add the check of values read from files after processing.
- CVS-167172
=> [coverity][samples] Overflowed integer argument bmp_reader

src/core/src/runtime/tensor.cpp
- fix: Overflowed integer argument
- [*167882*](https://jira.devtools.intel.com/browse/CVS-167882)
=> [Coverity Enterprise][Core][Samples]Denial of service, unreliable execution

src/plugins/intel_npu/src/plugin/npuw/llm_infer_request.cpp
This reverts commit c993cfacd75e900ff6c2fbc2f861d7a575bc7e93.
- *item1*
- *...*
- *ticket-id*
=> [NPUW] Revert "Raise exception if passed prompt exceeds its configured max size on NPU (#29890)"

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_base.hpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_bfyx_opt.hpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.hpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_ref.hpp, src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp
- *Convert group_normalization scale and bias formats from block format to planar format*
- *Add a unit test*
- *163770*
=> [GPU] Convert group_normalization scale and bias formats

src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp
Move paged_attention config to begin to avoid choose other config which causing issue to initialize microkernel.
CVS-167990
=> [GPU] Avoid use other configs in sdpa_micro for paged_attention

src/tests/test_utils/common_test_utils/src/ov_tensor_utils.cpp
since it is very rarely necessary to see all the elements
and this clutters the terminal every time with a huge output.
Added a threashold (32) for number of elements to print.
Also the output format is a bit restructured
<details>
<summary>Debug output after:</summary>
``` sh
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from smoke_Reduce_OneAxis_CPU/ReduceCPULayerTest
[ RUN      ] smoke_Reduce_OneAxis_CPU/ReduceCPULayerTest.CompareWithRefs/IS=([]_)_TS=((2.19.2.9)_)_axes=(0)_opType=SCALAR_type=Max_KeepDims=true_netPRC=f32_inPRC=dynamic_outPRC=dynamic_PluginConf_INFERENCE_PRECISION_HINT=f32
MEM_USAGE=91224KB
Coordinate:  1 Expected: 8 Actual: 6 Diff: 2 abs_threshold: 0.000800119
Coordinate:  2 Expected: 9 Actual: 5 Diff: 4 …
```
=> [TESTS][DEBUG] Avoid printing every single element diff in func tests

src/tests/ov_helpers/ov_snippets_models/src/subgraph_mha.cpp
=> [Snippets] Remove unused constant in MHASelect builder

src/bindings/python/scripts/generate_pyapi_stubs.py, src/bindings/python/src/openvino/_pyopenvino/properties/intel_gpu/hint.pyi
- Remove multiple entries in `INVALID_EXPRESSIONS` which have been fixed since introducing the script
- Add example errors to be able to see which xfails could prevent which stubs from generating updates
- CVS-167923
=> [PyOV] Cleanup stub generation scipt

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst, src/plugins/intel_npu/README.md
- Mentioning implications of NPU_TURBO usage, in documentation
- *ticket-id*
=> [intel-npu] Notes in npu documentation regarding NPU turbo

src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp
Fixes NPUW caching for models with bf16 weights
https://github.com/openvinotoolkit/openvino/pull/30677
=> [NPUW] Apply preprocessing to MODEL_PTR cached model

docs/dev/pypi_publish/pre-release-note.md, docs/dev/pypi_publish/pypi-openvino-rt.md
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Remove note

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/tile_ops.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_micro.cl, src/plugins/intel_gpu/tests/unit/test_cases/sdpa_gpu_test.cpp
- *Fix attn mask tile loading issue when attn mask shape has single query dimension [batch, num_heads, 1, sequence_length of k]*
- *166691*
=> [GPU] Fix accuracy issues for sdpa_micro (#30698)

src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/compiled_model/properties.cpp
- *item1*
- *...*
- *ticket-id*
=> [intel_npu] Cleanup of duplicated `properties` tests

src/core/dev_api/openvino/core/type/element_type_info.hpp, src/core/dev_api/openvino/runtime/itensor.hpp, src/core/include/openvino/runtime/tensor.hpp, src/core/src/runtime/itensor.cpp, src/core/src/runtime/tensor.cpp, src/core/src/type/element_type.cpp, src/inference/dev_api/openvino/runtime/iremote_tensor.hpp, src/inference/src/dev/make_tensor.cpp, src/plugins/intel_cpu/src/cpu_tensor.cpp, src/plugins/intel_cpu/src/cpu_tensor.h, src/plugins/intel_gpu/include/intel_gpu/plugin/remote_tensor.hpp, src/plugins/intel_gpu/include/intel_gpu/plugin/usm_host_tensor.hpp, src/plugins/intel_gpu/src/plugin/remote_tensor.cpp, src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp, src/plugins/intel_gpu/src/plugin/usm_host_tensor.cpp, src/plugins/intel_npu/src/backend/include/zero_tensor.hpp, src/plugins/intel_npu/src/backend/src/zero_tensor.cpp, src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_host_tensor.hpp, src/plugins/intel_npu/src/utils/src/zero/zero_host_tensor.cpp
- port of #30673 
- CVS-167986
=> Fix ov::Tensor::data access perfomance

src/plugins/intel_npu/README.md, src/plugins/intel_npu/docs/example-adding-property.patch, src/plugins/intel_npu/docs/example-removing-property.patch, src/plugins/intel_npu/docs/img/properties_class_hierarchy.png, src/plugins/intel_npu/docs/img/properties_init_sequence.png, src/plugins/intel_npu/docs/npu-properties-howto.md
-Adding detailed documentation for NPU properties, including:
-glossary
-class hierarchy description and diagram
-instructions for "How to add a new public property" (also applies for removal)
-description of dynamic properties with logic diagram
-difference between plugin and compiled_model properties
- adding patches to demonstrate with diffs what is described in "how to add a property"
Release port of #30724 
- *ticket-id*
=> [intel-npu] Adding documentation for NPU properties

src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp
Backport of (https://github.com/openvinotoolkit/openvino/pull/30779) to releases/2025/2
=> [GPU] Use sdpa_opt kernel for 3D sdpa and num_heads=1

src/bindings/python/src/openvino/preprocess/torchvision/requirements.txt
- *Set lower bound for torch as 2.6.0*
- *CVS-167763*
=> Set lower bound for torch as 2.6.0

docs/articles_en/openvino-workflow-generative/inference-with-genai.rst
**Details:** Document direct GGUF model inference support by OpenVINO GenAI
=> [GGUF] Document direct GGUF model inference support by OpenVINO GenAI

.github/actions/install_ov_wheels/action.yml
=> [CI] [GHA] Add more logs to `install-ov-wheels` actions 

docs/articles_en/about-openvino/performance-benchmarks/getting-performance-numbers.rst
- *item1*
- *...*
- *[167085](https://jira.devtools.intel.com/browse/CVS-167085)*
=> [DOCs] Add link to llm_bench

.github/workflows/windows_vs2022_release.yml
=> [GHA] Increase timeout for C++ unit tests on Windows in precommit

src/plugins/intel_gpu/src/graph/impls/ocl_v2/lora.cpp
Fix of broken  GHA ASAN jobs https://github.com/openvinotoolkit/openvino/actions/runs/15455576544/job/43507436932
=> [GHA] Code style check fix

src/plugins/intel_cpu/src/nodes/executors/convolution_config.hpp, src/plugins/intel_cpu/src/nodes/executors/convolution_implementations.cpp, src/plugins/intel_cpu/src/nodes/executors/debug_messages.hpp, src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_convolution_primitive.cpp, src/plugins/intel_cpu/src/nodes/executors/fullyconnected_config.hpp, src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/conv_u8s8f32.cpp
Includes:
- https://github.com/openvinotoolkit/openvino/pull/30870
- https://github.com/openvinotoolkit/openvino/pull/30875
- https://github.com/openvinotoolkit/openvino/pull/30872
- https://github.com/openvinotoolkit/openvino/pull/30871
=> [CPU] Convolution fixes combined

docs/articles_en/about-openvino/release-notes-openvino.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Release notes

docs/articles_en/openvino-workflow-generative/inference-with-genai/inference-with-genai-on-npu.rst
cherry pick (#30661)
- *item1*
- *...*
- *ticket-id*
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Option "--disable-stateful" note

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/get-started/install-openvino/install-openvino-docker-linux.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCs] Change what's new

docs/articles_en/about-openvino/openvino-ecosystem/openvino-project.rst, docs/articles_en/about-openvino/openvino-ecosystem/openvino-project/openvino-test-drive.rst
port: https://github.com/openvinotoolkit/openvino/pull/30947
=> [DOCS] rebrand Geti

src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_yx_fsv16.cpp, src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
- `MULTIPLE_GROUPS_INPUT_PRELOAD` has meaning only when `params.groups` > 1.
- 167440
=> [GPU] Set multiple groups input preload only if groups > 1

src/common/snippets/src/generator.cpp, src/common/snippets/src/lowered/linear_ir.cpp, src/plugins/intel_cpu/src/emitters/snippets/x64/cpu_generator.cpp
- N/A
Related discussion: https://github.com/openvinotoolkit/openvino/pull/30752#discussion_r2144568816
=> [Snippets] Use 'ov::is_type_any_of' where applicable

samples/js/node/package-lock.json, src/bindings/js/node/package-lock.json, src/bindings/js/node/package.json
https://github.com/openvinotoolkit/openvino/pull/30933
- *ticket-id*
=> [OV JS] Dependency update and fix for brace-expansion from 1.1.11 to 1.1.12 in /src/bindings/js/node

samples/js/node/benchmark/README.md, samples/js/node/benchmark/asynchronous_benchmark.js
Basic benchmark that will be treated as reference point.
Python API [benchmarks](https://github.com/openvinotoolkit/openvino/tree/master/samples/python/benchmark)
- [CVS-167240](https://jira.devtools.intel.com/browse/CVS-167240)
=> [OV JS] Add async benchmark

docs/articles_en/about-openvino/release-notes-openvino.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] change date

src/plugins/intel_gpu/src/graph/program_node.cpp
- *[169220](https://jira.devtools.intel.com/browse/CVS-169220)*
=> [GPU] Extended stored values ​​for program_node serialization

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/col2im.hpp, src/plugins/intel_gpu/src/kernel_selector/kernels/grid_sample/grid_sample_kernel_opt_bilinear_zeros.cpp, src/plugins/intel_gpu/tests/unit/passes/prepare_padding_test.cpp
+ Blocked adding padding to col2im kernel's output
+ Added exception for spatial padding to grid_sample opt kernel
+ Fixed vload8 padding handling
- *item1*
- *...*
- CVS-168813
=> [GPU] Resolve invalid padding for simple format convolution

src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp
- Backport https://github.com/openvinotoolkit/openvino/pull/30858
=> [GPU] Fix issue regarding PA's update_dispatch_data for prefill

samples/cpp/common/utils/src/args_helper.cpp, src/plugins/intel_npu/tools/compile_tool/main.cpp
- *Added `U2` precision parsers for **compile_tool** and other type parsers*
=> Added U2 precision parsers for compile_tool

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_padding.cpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/col2im.hpp, src/plugins/intel_gpu/src/kernel_selector/kernels/grid_sample/grid_sample_kernel_opt_bilinear_zeros.cpp, src/plugins/intel_gpu/tests/unit/passes/prepare_padding_test.cpp
- Blocked adding padding to col2im kernel's output
- Added exception for spatial padding to grid_sample opt kernel
- Fixed vload8 padding handling
- CVS-168813
=> Resolve invalid padding for simple format convolution

docs/requirements.txt
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Requirements temp fix

src/plugins/intel_cpu/src/shape_inference/static_shape.hpp, src/plugins/intel_cpu/src/utils/plain_tensor.hpp
=> [CPU] Remove extra `[nodiscard]`

src/inference/include/openvino/runtime/core.hpp, src/inference/tests/functional/ov_core_test.cpp, src/inference/tests/functional/ov_extension_test.cpp, src/tests/test_utils/common_test_utils/src/file_utils.cpp, src/tests/test_utils/functional_test_utils/include/functional_test_utils/test_model/test_model.hpp, src/tests/test_utils/functional_test_utils/src/test_model/test_model.cpp
This PR ports the following changes from `master` to `releases/2025/2`:
- Ports the changes from [PR#30843](https://github.com/openvinotoolkit/openvino/pull/30843) and [PR#30938](https://github.com/openvinotoolkit/openvino/pull/30938)
- All tests passed locally
- [CVS-168219](https://jira.devtools.intel.com/browse/CVS-168219)
=> [Core][Unicode] Unicode path support

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_ref.cl, src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp
- Backport https://github.com/openvinotoolkit/openvino/pull/31074
=> [GPU] Fix sdpa_opt single token kernel to support scalar input for scale

src/frontends/tensorflow_lite/src/schema/schema.fbs
Update StableHLO ops in schema.fbs file
=> Update TfLite schema.fbs for StableHlo ops

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/bf16_utils.cl
=> [GPU] fix warnings from _convert_as_bfloat16_float and _convert_bfloat16_as_ushort

src/plugins/intel_npu/src/plugin/src/properties.cpp
- Fix formatting for newly introduced changes in https://github.com/openvinotoolkit/openvino/pull/31125
- N/A
=> [NPU] Hotfix after clang-format-18 changes

src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/just_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/llm_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/logging.cpp, src/plugins/intel_npu/src/plugin/npuw/logging.hpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/graph.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/graph.hpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/online/snapshot.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/partitioning.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.cpp, src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.hpp, src/plugins/intel_npu/src/plugin/npuw/serialization.hpp
Fixing Coverity issues. Most of the issues are caused by missing reference specifiers resulting in redundant copies made.
=> [NPUW] Fix coverity issues

src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/interpolate.cpp
- found when working on https://github.com/openvinotoolkit/openvino/pull/30819
=> [GPU] added missing interpolate TEST_P

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
=> [CPU] Disable sporadically failing ARM func tests

src/plugins/intel_npu/src/al/include/intel_npu/config/options.hpp, src/plugins/intel_npu/src/common/src/filtered_config.cpp, src/plugins/intel_npu/src/plugin/src/plugin.cpp
- *Support Turbo config for offline compilation*
- *E#171370*
=> [NPU] Support Turbo config with offline compilation

src/plugins/intel_npu/src/compiler_adapter/src/graph.cpp
- *Do not throw if driver doesn't support turbo*
=> [NPU] Do not throw if driver doesn't support turbo

src/frontends/onnx/docs/supported_ops.md, src/frontends/onnx/frontend/src/op/com.microsoft/rotary_embedding.cpp, src/frontends/onnx/tests/models/com.microsoft/rotary_embedding.prototxt, src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp
add basic implementation for RotaryEmbedding op, https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.RotaryEmbedding
=> [ONNX] Added RotaryEmbedding from com.microsoft domain

.github/workflows/ubuntu_22.yml
=> [CI] [GHA] Increase timeout for the Nvidia job

src/common/low_precision_transformations/include/low_precision/layer_transformation.hpp, src/common/low_precision_transformations/include/low_precision/low_precision.hpp, src/common/low_precision_transformations/src/layer_transformation.cpp, src/common/low_precision_transformations/src/low_precision.cpp, src/common/low_precision_transformations/tests/is_function_quantized_transformation.cpp
- *LPT pipeline is adjusted for FakeConvert operations*
- *Minor refactoring of base LPT classes: removed unused methods + cleanup*
- *CVS-170204*
=> [LPT] Adapt LPT pipeline for FakeConvert ops

src/common/snippets/tests/CMakeLists.txt, src/common/snippets/tests/include/lowered/pass/buffer_allocation.hpp, src/common/snippets/tests/src/lowered/pass/buffer_allocation.cpp, src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/lowered/buffer_allocation.cpp
=> [Snippets][CPU][TESTS] Refactor BufferAllocation test to reduce code duplication

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ovms-genai.json, docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ovms.json
- *Added OVMS-2025.2 statics results*
- *Added OVMS-GenAI 2025.2 results*
- *Updated release date*
- *n/a*
=> Ovms 2025.2 new results

src/common/low_precision_transformations/src/broadcast.cpp, src/common/low_precision_transformations/tests/broadcast_transformation.cpp, src/tests/ov_helpers/ov_lpt_models/src/broadcast.cpp
=> [LPT] BroadcastTransformation: broadcast with 2 inputs support

src/plugins/intel_gpu/src/kernel_selector/kernels/lora/lora_kernel_opt.cpp, src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/lora_pattern.cpp
- *[170166](https://jira.devtools.intel.com/browse/CVS-170166)*
=> [GPU] Added optimized LoRA kernels for small prompts

src/plugins/intel_npu/tools/protopipe/README.md, src/plugins/intel_npu/tools/protopipe/src/parser/config.cpp, src/plugins/intel_npu/tools/protopipe/src/utils/data_providers.cpp, src/plugins/intel_npu/tools/protopipe/src/utils/data_providers.hpp
- Add seed option to random generator
- EISW-175412
=> [Protopipe] Add seed option to random generator

.github/actions/setup_python/action.yml
=> [CI] [GHA] Remove usage of the `deadsnakes` action

src/plugins/intel_cpu/src/nodes/executors/acl/acl_eltwise.hpp, src/plugins/intel_cpu/src/nodes/executors/acl/acl_reduce.hpp, src/plugins/intel_cpu/src/nodes/kernels/x64/mlp_kernel.hpp, src/plugins/intel_cpu/src/nodes/kernels/x64/mlp_utils.cpp, src/plugins/intel_cpu/src/utils/verbose.cpp
=> [CPU] Get rid of relative include directives

cmake/features.cmake, src/core/include/openvino/core/parallel.hpp, src/plugins/intel_cpu/src/graph.cpp, src/plugins/intel_cpu/src/nodes/mvn.cpp, src/plugins/intel_cpu/src/plugin.cpp
- *Fix for performance of MVN node with Intel OMP*
- *152606*
=> [CPU][OMP] Fix for MVN performance

src/common/transformations/src/transformations/common_optimizations/sdpa_fusion.cpp, src/common/transformations/tests/common_optimizations/sdpa_fusion_test.cpp
Handled a case when attention mask rank > inputs ranks
Added a unit test
- *CVS-170071*
=> Fix SDPAFusion: attention mask rank > inputs ranks

src/plugins/intel_gpu/src/graph/common_utils/jitter.cpp, src/plugins/intel_gpu/src/graph/common_utils/jitter.hpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/utils/fused_ops_jitter.cpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/utils/fused_ops_jitter.hpp, src/plugins/intel_gpu/tests/unit/fusions/lora_fusion_test.cpp
- *[169334](https://jira.devtools.intel.com/browse/CVS-169334)*
=> [GPU] Support new infra fused ops in dynamic case

src/plugins/intel_cpu/tools/dump_jit_disassm/__main__.py
- Add support for `aarch64` platform in dump_jit_disassm tool
- Integrate oneDNN patch that enables kernel text dump in `xbyak_aarch64`: https://github.com/openvinotoolkit/oneDNN/pull/283
- N/A
=> [CPU] Add support for aarch64 in JIT code disasm tool

src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.cpp, src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.hpp, src/plugins/intel_cpu/src/nodes/eltwise.cpp, src/plugins/intel_cpu/src/nodes/kernels/riscv64/jit_uni_eltwise_generic.cpp, src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp
- Implemented elu emitter similar to the aarch64 implementation.
- #30228
=> [CPU][RV64] Implement jit_elu_emitter

src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_fc_horizontal_fusion.cpp
- *[170827](https://jira.devtools.intel.com/browse/CVS-170827)*
=> [GPU] Disable LoRA_HorizontalFusion tests for Linux

src/common/snippets/src/lowered/pass/init_live_ranges.cpp, src/common/snippets/src/lowered/pass/reduce_decomposition.cpp
Fix AddressSanitizer "container-overflow on address ..." errors reported on macOS arm64
- N/A
=> [Snippets] Fix address sanitizer errors reported on PortConnector usage

docs/articles_en/about-openvino/release-notes-openvino.rst, docs/articles_en/get-started/install-openvino/install-openvino-brew.rst
install-openvino-brew: Added note that recent OpenVINO releases currently unavailable via Homebrew
=> Added note that recent OpenVINO releases currently unavailable via Homebrew

src/plugins/intel_gpu/include/intel_gpu/runtime/internal_properties.hpp, src/plugins/intel_gpu/src/plugin/plugin.cpp
- Support pci_info and device_id metric 
- CVS-170986
=> [GPU] Support pci_info / device_id metric

CMakeLists.txt
- Bump minimum cmake version to 3.18
- CVS-171014
=> Bump minimum cmake version

docs/articles_en/openvino-workflow-generative/inference-with-genai.rst, docs/articles_en/openvino-workflow-generative/inference-with-genai/inference-with-genai-on-npu.rst
- *item1*
- *...*
- *ticket-id*
=> [Docs] Fix genai typo and add npu note

src/plugins/intel_npu/src/al/include/intel_npu/config/npuw.hpp, src/plugins/intel_npu/src/al/include/intel_npu/npuw_private_properties.hpp, src/plugins/intel_npu/src/al/src/config/npuw.cpp, src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.hpp, src/plugins/intel_npu/src/plugin/npuw/llm_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/llm_infer_request.hpp, src/plugins/intel_npu/src/plugin/npuw/serialization.hpp
- *Separated Vocab MatMul into additional model*
- *Called infer for additional model in LLMInferRequest*
- *OpenVINO GenAI PR* : https://github.com/openvinotoolkit/openvino.genai/pull/2317
- *EISW-165218*
- *Regression was found with the PR in the previous merge, PR was reverted, this regression got fixed in current PR*
=> NPUW: Three-model pipeline

src/inference/dev_api/openvino/runtime/internal_properties.hpp, src/inference/include/openvino/runtime/properties.hpp, src/plugins/intel_cpu/src/config.cpp, src/plugins/intel_cpu/src/config.h, src/plugins/intel_cpu/src/internal_properties.hpp, src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/executor_pa.cpp, src/plugins/intel_cpu/src/nodes/paged_attn.cpp, src/plugins/intel_cpu/src/nodes/scaled_attn.cpp, src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/concat_transpose_sdp_transpose.cpp, src/plugins/intel_gpu/include/intel_gpu/primitives/paged_attention.hpp, src/plugins/intel_gpu/include/intel_gpu/runtime/internal_properties.hpp, src/plugins/intel_gpu/include/intel_gpu/runtime/options.inl, src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp, src/plugins/intel_gpu/src/graph/paged_attention.cpp, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_kv_cache_update_ref.cl, src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_update_kernel_ref.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_update_kernel_ref.h, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp, src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h, src/plugins/intel_gpu/src/plugin/compiled_model.cpp, src/plugins/intel_gpu/src/plugin/ops/paged_attention.cpp, src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp, src/plugins/intel_gpu/src/runtime/execution_config.cpp, src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp
- Enable "by_channel" key cache quantization mode for GPU plugin
- CVS-164906
=> [GPU]  Enable by_channel mode for key cache compression 

docs/articles_en/about-openvino/performance-benchmarks.rst, docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ovms-genai.json, docs/sphinx_setup/_static/benchmarks_files/data/graph-data-ovms.json
- *Added OVMS-2025.2 statics results*
- *Added OVMS-GenAI 2025.2 results*
- *Updated release date*
- *n/a*
- *item1*
- *...*
- *ticket-id*
=> Ovms 2025.2 new results (#31267)

src/plugins/intel_npu/src/plugin/CMakeLists.txt, src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/compiled_model.hpp, src/plugins/intel_npu/src/plugin/npuw/lazy_tensor.cpp, src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp, src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.hpp, src/plugins/intel_npu/src/plugin/npuw/serialization.cpp, src/plugins/intel_npu/src/plugin/npuw/serialization.hpp, src/plugins/intel_npu/tests/unit/CMakeLists.txt, src/plugins/intel_npu/tests/unit/npuw/serialization.cpp
E-167378
* Mirror of #30913
* Mirror of #31115
=> [NPUW] Fix importing weightless blob with bf16 constants

.github/workflows/update_pyapi_stubs.yml
Avoid creating automatic stubs generation pull requests in fork repos
- N/A
=> [GHA][PyOV] Create automatic stubs generation PRs only in the original repo

docs/articles_en/openvino-workflow/model-preparation/convert-model-keras.rst
@rkazants 
Adding documentation for Keras model export support to OpenVINO IR format.
https://github.com/keras-team/keras/pull/21486
=> [DOC] Export Keras 3 Model to OpenVINO IR

cmake/developer_package/cross_compile/python_helpers.cmake, cmake/features.cmake, src/bindings/python/src/pyopenvino/CMakeLists.txt, src/bindings/python/src/pyopenvino/frontend/frontend_module.cmake
- Result of discussion in https://github.com/openvinotoolkit/openvino.genai/pull/2515
- N/A
=> [PyOV] Rename free threaded Python CMake option

src/bindings/js/node/package-lock.json
https://github.com/openvinotoolkit/openvino/pull/31513
- *ticket-id*
=> [OV JS] Bump @eslint/plugin-kit

src/plugins/intel_cpu/src/nodes/kernels/x64/jit_uni_eltwise_generic.cpp
jit_uni_eltwise_generic: precision related exceptions messages are extended to simplify debugging
- *N\A*
=> [CPU] jit_uni_eltwise_generic: exception messages are extended

src/bindings/python/tests/test_graph/test_custom_op.py, src/bindings/python/tests/test_runtime/test_async_infer_request.py, src/bindings/python/tests/test_runtime/test_deprecated_runtime.py, src/bindings/python/wheel/fdupes_check.cmake
- Python 3.13t is experimental and I don't think we should be worried about fixing these issues until official, full support for free threaded Python is out
- This PR is needed for enablement of building 3.13t wheels on Jenkins
- 170718
=> [PyOV] Skip some tests failing on experimental free-threaded Python

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp, src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp
- Recent onednn requires at least 64-byte align memory pointer.
- Implicit concat uses memory pointer in onednn input, so only enable implicit concat when at least 64-byte alignments.
- Clean up dummy check conditions.
- No OV side. onednn changes.
- benchmark_app -d GPU.1 -m INT8/1/ov/optimized/googlenet-v4.xml -hint none -nstreams 1 -niter 1  -use_device_mem -inference_only=false
- No graph related.
- [O] Is it a proper fix? (not a workaround) 
- [O] Did you include test case for this fix, if necessary? 
- [O] Did you review existing test that can be extended to cover this scenario? Which test did you review? concatenation_gpu_test.cpp
- *170847*
=> [GPU] Fix misaligment issue in onednn.

src/plugins/intel_npu/tests/functional/shared_tests_instances/npu_skip_func_tests.xml
- *Enable previously skipped func behavior tests:*
- *`InferRequestCheckTensorPrecision.*type=u2`*
- *Tests intended to run on other NPU platforms which will be added in OV CI*
- *E-176909*
=> [NPU] Unskip func behavior tests after driver update

src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp
Related to https://github.com/openvinotoolkit/openvino/pull/31543
=> [NPUW] Fix 3-model pipeline deserialization

src/plugins/intel_npu/src/plugin/npuw/llm_infer_request.cpp
Removed extra 'prepare_for_new_conversation()' from 'infer_whole_prefill()'
=> Removed extra 'prepare_for_new_conversation()' from 'infer_whole_prefill()'

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/src/common/src/sync_infer_request.cpp, src/plugins/intel_npu/tests/functional/behavior/infer_request_dynamic.cpp, src/plugins/intel_npu/tests/functional/behavior/infer_request_dynamic.hpp
- *Check if set_shape is out of bounds*
- *CVS-171667*
=> [NPU] Check if set shape is out of bounds

src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp
Chunking (#31294 ) introduced a new requirement that `MAX_PROMPT_LEN` should be a multiple of the `CHUNK_SIZE`.
As there were cases where people passed various odd `MAX_PROMPT_LEN`'s, e.g. in benchmarking, the default alignment by 64 couldn't pass this limitation.
This PR aligns the `MAX_PROMPT_LEN` by the `CHUNK_SIZE` if the chunking is enabled.
```
(env20250809) C:\dmitry\ov253-debug>type test.yml
MAX_PROMPT_LEN: 300
(env20250809) C:\dmitry\ov253-debug>python ..\chat.py -d NPU -m TinyLlama-1.1B-Chat-v1.0_int4_sym_group128_dyn_stateful -c test.yml
Traceback (most recent call last):
File "C:\dmitry\chat.py", line 95, in <module>
Chat(args).run()
^^^^^^^^^^
File "C:\dmitry\chat.py", line 40, in __init__
self.pipeline = ov_genai.LLMPipeline(args.model_dir, args.device, …
```
=> NPUW: Automatically align MAX_PROMPT_LENGTH to CHUNK_SIZE

cmake/dependencies.cmake, src/inference/src/dev/threading/cpu_streams_executor.cpp, src/inference/src/dev/threading/parallel_custom_arena.hpp
- *Add tbb new interface set_core_types() call which support P cores and E cores binding on PTL*
- *change tbb lib path*
- *ticket-id*
=> Add tbb new interface set_core_types() call which support P cores and E cores binding on PTL

src/plugins/intel_cpu/src/emitters/snippets/aarch64/kernel_executors/gemm_copy_b.cpp, src/plugins/intel_cpu/src/emitters/snippets/aarch64/kernel_executors/gemm_copy_b.hpp, src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
- Fix strides behavior to enable MatMul + Transpose tests
- invert skip_tests_config logic
- required for 167005
=> [Snippets][CPU] Fix stride issues in jit_gemm_copy_b_emitter

.github/scripts/workflow_rerun/errors_to_look_for.json, .github/scripts/workflow_rerun/log_analyzer.py, .github/scripts/workflow_rerun/tests/integration_test.py
=> [CI] [GHA] Add `OperationStopped:` to known errors

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.rst, src/bindings/python/src/pyopenvino/core/properties/properties.cpp, src/bindings/python/tests/test_runtime/test_properties.py, src/inference/include/openvino/runtime/intel_gpu/properties.hpp, src/plugins/intel_gpu/src/plugin/plugin.cpp
- *[172315](https://jira.devtools.intel.com/browse/CVS-172315)*
=> [GPU] Added max_alloc_mem_size property to api

src/plugins/intel_gpu/src/graph/impls/ocl_v2/paged_attention_opt.cl
- Types added for forgotten uints
- [*CVS-163554*](https://jira.devtools.intel.com/browse/CVS-163554)
=> [GPU] Implicit int fix

src/plugins/intel_gpu/src/graph/impls/ocl_v2/sdpa/sdpa_base.cpp
- *item1*
- *...*
- *CVS-172169*
- *...*
=> [GPU][BUG] fix incorrect transpose_order

cmake/features.cmake
- Restore the previously disabled TBB build (https://github.com/openvinotoolkit/openvino/pull/26175)
- N/A
=> Enable build with TBB on Android

src/plugins/intel_gpu/src/graph/impls/ocl_v2/sdpa/paged_attention_opt.cpp, src/plugins/intel_gpu/src/graph/impls/ocl_v2/sdpa/sdpa_base.cpp
- port https://github.com/openvinotoolkit/openvino/pull/31651 to 25.3
- port https://github.com/openvinotoolkit/openvino/pull/31804 to 25.3
- *CVS-171882*
- *CVS-172169*
=> [GPU][BUG] Fix macro multiple registered and micro kernel block size issue

src/plugins/intel_gpu/src/graph/impls/ocl_v2/pa_kv_cache_update_ref.cl
- This PR adds a missed `block_read` related include
- 172478
=> [GPU] adding a missed block_read related include

src/plugins/intel_npu/src/compiler_adapter/include/ze_graph_ext_wrappers.hpp, src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp, src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp
- *Fix Turbo option*
- *E#180553*
=> [NPU] Fix Turbo option

cmake/dependencies.cmake
- *Update oneTBB package without -flto*
- *[CVS-172477](https://jira.devtools.intel.com/browse/CVS-172477),[CVS-171525](https://jira.devtools.intel.com/browse/CVS-171525)*
=> update onetbb package

.github/workflows/job_python_unit_tests.yml
=> [GHA] Enable real-time output for Python unit tests

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
=> [Snippets][CPU] Enable MHA tokenization in transformation pipeline

docs/articles_en/about-openvino/release-notes-openvino.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Release notes 25.3

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp
- *Don't destroy previous tensor if the same data is set for another tensor*
=> [NPU] Fix importing deallocation issue

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
Nullptr error in node selected_impl is null.
Related regression: https://github.com/openvinotoolkit/openvino/pull/31140
- *173291*
=> [GPU] Fix Yolo8, Yolo11 failure.

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp, src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp
- *Use the correct path for dynamic batching*
- *Don't re-create the pipeline if the batch size didn't change*
- *ticket-id*
=> [NPU] Use the correct path for dynamic batching

src/plugins/intel_cpu/src/nodes/subgraph.cpp
=> [Snippets][DEBUG_CAPS][CPU] Enable InsertPerfCountVerbose pass on ARM64

docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] Sysreqs support change

src/common/snippets/include/snippets/utils/utils.hpp, src/common/snippets/src/pass/collapse_subgraph.cpp, src/common/snippets/src/pass/mha_tokenization.cpp, src/common/snippets/src/pass/mlp_seq_tokenization.cpp, src/common/snippets/src/pass/softmax_decomposition.cpp, src/common/snippets/src/pass/softmax_reshape_elimination.cpp, src/common/snippets/src/pass/validate.cpp, src/common/snippets/src/utils/utils.cpp
Remove code duplications related to v1::Softmax and v8::Softmax handling
- N/A
=> [Snippets] Add softmax axis normalization helper

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/auto-device-selection.rst
- *Stateful model will be loaded based on device priority rather than directly onto the CPU now*
- *ticket-id*
=> update auto doc for loading stateful model

src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp
- *1.5 graph ext version is the first one that must be supported*
=> [NPU] 1.5 graph ext version is the first one that must be supported

src/plugins/intel_gpu/src/graph/impls/ocl_v2/primitive_ocl_base.hpp, src/plugins/intel_gpu/src/graph/primitive_inst.cpp
- Explicitly set `SHAPE_CHANGED` flag for PA update, else it may lead to incorrect gws/lws
- This issue is found when notebook to run [speculative-sampling](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/266-speculative-sampling)
- *CVS-172385*
=> [GPU][BUG] fix ocl_v2 dispatch data update issue

src/plugins/intel_gpu/src/kernel_selector/micro_utils.hpp, src/plugins/intel_gpu/thirdparty/CMakeLists.txt
- onednn: commit_id f1832d20d1
- fix build issues.
- 173136
=> [GPU] integration onednn/main to ov/master

src/tests/test_utils/common_test_utils/src/test_case.cpp
=> [TESTS] Provide fp32 inference precision hint for tests

docs/articles_en/openvino-workflow/running-inference/optimize-inference/precision-control.rst
- This PR add a brief explanation of activations scaling.
=> brief explanation of Activations Scaling

docs/articles_en/about-openvino/release-notes-openvino/system-requirements.rst
- *item1*
- *...*
- *ticket-id*
=> [DOCS] sys reqs for lts changes

src/plugins/intel_npu/tests/functional/common/utils.hpp, src/plugins/intel_npu/tests/functional/internal/overload/ov_plugin/life_time.hpp
- *Fix test to not align tensor for import*
- *E#179607*
=> [NPU] Fix test to not align tensor for import

src/common/snippets/include/snippets/pass/extract_constants.hpp, src/common/snippets/include/snippets/pass/extract_unsupported_transposes.hpp, src/common/snippets/include/snippets/pass/split_dimension_m.hpp, src/common/snippets/include/snippets/pass/subgraph_pass.hpp
Fix lack of names in subgraph passes (used for debug purposes)
- N/A
=> [Snippets] Set names for subgraph passes on create

src/common/low_precision_transformations/src/move_fake_convert_up_through_kv_cache_concat.cpp, src/common/low_precision_transformations/tests/kv_cache_static_quantization.cpp
- *`MoveFakeConvertUpThroughKVCacheConcat`: support SDPA without multi query subgraph*
- *CVS-174233*
=> [LPT] MoveFakeConvertUpThroughKVCacheConcat matcher extending

src/plugins/intel_npu/src/utils/src/zero/zero_init.cpp
- *Set the stype for the ze_init_driver_type_desc_t as well*
- *CVS-174292*
=> [NPU] Set the stype for the ze_init_driver_type_desc_t as well

src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.cpp, src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.hpp
=> NPUW: Allocate infer request's I/O tensors based on subgraph affinity

.github/workflows/job_pytorch_models_tests.yml
- Tests started using snapshot_download() function in #32282 
- *ticket-id*
=> [GHA] Reset HF cache for test_pa_transformation tests

src/common/low_precision_transformations/src/network_helper.cpp
=> [LPT] Coverity fix
