src/plugins/intel_gpu/include/intel_gpu/plugin/compiled_model.hpp
src/plugins/intel_gpu/src/plugin/compiled_model.cpp

- Partial fix for https://jira.devtools.intel.com/browse/CVS-156022
- explicit call for release memory is required
- *ticket-id*

[GPU] clean oneDNN cache by release memory method

---

src/bindings/python/src/pyopenvino/utils/utils.cpp
src/bindings/python/tests/test_graph/test_custom_op.py
src/bindings/python/tests/test_graph/test_manager.py
src/bindings/python/tests/test_runtime/test_compiled_model.py
src/bindings/python/tests/test_runtime/test_core.py
src/bindings/python/tests/test_runtime/test_model.py
src/bindings/python/tests/test_transformations/test_compression.py
src/bindings/python/tests/test_transformations/test_offline_api.py
src/bindings/python/tests/test_transformations/test_public_transformations.py
src/bindings/python/tests/utils/helpers.py

- add a test where exported model saved to file and then imported from file
- fix a problem with `inc_ref` and `dec_ref` when python callbacks are passed 
- *ticket-id*

[PyOV] Test for export-import via file

---

src/common/snippets/include/snippets/lowered/pass/init_loops.hpp
src/common/snippets/include/snippets/lowered/pass/validate_unified_loops.hpp
src/common/snippets/include/snippets/utils/loop_utils.hpp
src/common/snippets/src/lowered/loop_manager.cpp
src/common/snippets/src/lowered/pass/init_loops.cpp
src/common/snippets/src/lowered/pass/validate_unified_loops.cpp
src/common/snippets/src/utils/loop_utils.cpp

- *To remind, `LoopPort` is expression port  connected to another expression port which is not in the same Loop. It's like entry (of exit) point of the Loop. It means that some expression port cannot be port of the Loop if all consumers (or sources) are from the same Loop. However, the method `LoopManager::update_loop_ports` sometimes creates these situation. This PR fixes this method. The screenshot below describes this situation: red loop is inner loop and blue loops is outer loop. However, some of output ports of this Loop is inside (green question sign) - invalid situation which is fixed by these changes.*
- *Added the corresponding checks to validate pass*
- *Remove parts in `init_is_incremented` which handle invalid case by `is_incremented=false`.*
- *CVS-156299*

[Snippets] Fixed LoopManager::update_loop_ports

---

src/bindings/python/wheel/CMakeLists.txt

- An alternative to https://github.com/openvinotoolkit/openvino/pull/27426
- The functionality branching based on pip version has recently been removed in https://github.com/openvinotoolkit/openvino/pull/27190
- This fix has originated from discussion at https://github.com/openvinotoolkit/openvino/pull/27190/files#r1830707810
- Fix for issues with NPU building on Windows machines
- A disadvantage is that we need to have `build` as a dependency no matter what, there's no environment marker for `pip` version which would allow us to install it conditionally
- EISW-146038

[PyOV] Use `python -m build` only for old `pip` versions

---

.github/workflows/android_arm64.yml
.github/workflows/android_x64.yml
.github/workflows/coverity.yml
.github/workflows/dev_cpu_linux_snippets_libxsmm.yml
.github/workflows/job_build_linux.yml
.github/workflows/job_build_windows.yml
.github/workflows/job_onnx_runtime.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/linux_riscv.yml
.github/workflows/mac.yml
.github/workflows/mac_arm64.yml
.github/workflows/ubuntu_22.yml
.github/workflows/windows_conditional_compilation.yml

- To address the issue mentioned [here](https://unix.stackexchange.com/questions/316644/is-make-j-with-no-argument-dangerous), we need to set the number of parallel jobs explicitly
- *156361*

[GHA] WA parallel make issue

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl

- Fix accuracy issue in PagedAttention kernel for large prompts (4K/8K tokens) by correcting index calculation in sub_group_broadcast function to ensure accurate data broadcasting within the subgroup
- Copy of https://github.com/openvinotoolkit/openvino/pull/27433 
- [CVS-154881](https://jira.devtools.intel.com/browse/CVS-154881)

[GPU] Fix accuracy issue in PagedAttention kernel for large prompts

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/dynamic_quantize_gpu_kv_cache.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_opt_kv_cache.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache_sdpa.cpp
src/plugins/intel_gpu/tests/unit/test_cases/dynamic_quantize_gpu_test.cpp

- Enable KV-cache compression by default for non-systolic platforms
- Change accumulator type to FP32 in dynamic quantize kernel

[GPU] Enable KV-cache compression by default for non-systolic platforms

---

src/common/snippets/include/snippets/lowered/expressions/buffer_expression.hpp
src/common/snippets/include/snippets/lowered/loop_info.hpp
src/common/snippets/include/snippets/lowered/pass/define_buffer_clusters.hpp
src/common/snippets/include/snippets/lowered/pass/mark_invariant_shape_path.hpp
src/common/snippets/include/snippets/lowered/pass/set_buffer_reg_group.hpp
src/common/snippets/include/snippets/utils/utils.hpp
src/common/snippets/src/lowered/expression.cpp
src/common/snippets/src/lowered/expressions/buffer_expression.cpp
src/common/snippets/src/lowered/loop_info.cpp
src/common/snippets/src/lowered/pass/allocate_buffers.cpp
src/common/snippets/src/lowered/pass/define_buffer_clusters.cpp
src/common/snippets/src/lowered/pass/mark_invariant_shape_path.cpp
src/common/snippets/src/lowered/pass/set_buffer_reg_group.cpp
src/common/snippets/src/pass/mha_tokenization.cpp
src/plugins/intel_cpu/src/transformations/tpp/x64/pass/lowered/set_tpp_leading_dim.cpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/lowered/buffer_allocation.cpp

- *Added memory inplace support for Buffer with different precision (it's supported only when output Buffer has data size not more than input Buffer) - it's needed for BF16 and INT8 MHA*
-  *Added memory inplace support for dynamic Buffers with the marking pass "MarkInvariantShapePath"*
- *154732, 150148*

[Snippets] Added dynamic memory sharing support

---

src/plugins/intel_cpu/src/nodes/deconv.cpp

- *temporal WA limiting Deconv acb Layout to avx512_core_amx_fp16 platform before oneDNN fix the performance regression issue of related primitive creation*
- *CVS-156640*

[CPU] Roll back deconv 3rd rank layout order for non AMX

---

src/common/snippets/src/lowered/loop_port.cpp
src/plugins/intel_cpu/src/emitters/snippets/cpu_runtime_configurator.cpp
src/plugins/intel_cpu/src/emitters/snippets/cpu_runtime_configurator.hpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_kernel_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm_copy_b.cpp
src/plugins/intel_cpu/src/nodes/subgraph.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_utils.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_utils.hpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/adjust_brgemm_copy_b_loop_ports.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/adjust_brgemm_copy_b_loop_ports.hpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_cpu_blocking.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_cpu_blocking.hpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/lowered/brgemm_blocking.cpp

- *Perform weights repacking outside of the blocking cycles*
- *Functionally enable blocking for I8,U8 and BF16*
- *The blocking will be temporary disabled until blocking heuristic is updated in 156014*
- *154729*

Sns enable lp kn blocking

---

src/core/shape_inference/include/one_hot_shape_inference.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/one_hot.hpp
src/plugins/intel_gpu/src/graph/include/one_hot_inst.h
src/plugins/intel_gpu/src/graph/one_hot.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/plugin/ops/one_hot.cpp

- *Get the 'depth' value from 'Select' node instead of a Constant node*
This happens when the second input of **OneHot** node is not a **Constant** node (**Select** node in this PR).
- *[CVS-155564](https://jira.devtools.intel.com/browse/CVS-155564)*

[GPU] Fix one hot seg fault when the second input node is not a Constant node

---

samples/cpp/benchmark_app/main.cpp
tools/benchmark_tool/openvino/tools/benchmark/main.py

While investigating the problem raised by the E-117106 ticket, turned out that, in fact, a problem lies within the Benchmark App. When choosing the sync API, it is not possible to run more inference requests than specified iterations. Later on, if `-pc` flag was given, the app still tries to display the profiling data for the never launched inferences.  This PR detects this situation and rejects the application execution after writing an explanatory message to the console output. Changes are applied for both C++ and Python versions of the benchmark app.
- CVS-156823

[Benchmark App] Reject -nireq > -niter when using sync API

---

src/plugins/intel_gpu/src/graph/program_helpers.cpp

- Don't select add_fusing_type::sum when dependency is input_layout in  loop body network. sum op could contaminate memory buffer. 
- 154020

[GPU] Don't select add_fusing_type::sum when dependency is input_layout in  loop body network

---

src/plugins/intel_npu/src/backend/include/zero_device.hpp
src/plugins/intel_npu/src/backend/include/zero_host_tensor.hpp
src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp
src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp
src/plugins/intel_npu/src/backend/include/zero_profiling.hpp
src/plugins/intel_npu/src/backend/include/zero_remote_tensor.hpp
src/plugins/intel_npu/src/backend/src/zero_device.cpp
src/plugins/intel_npu/src/backend/src/zero_host_tensor.cpp
src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
src/plugins/intel_npu/src/backend/src/zero_profiling.cpp
src/plugins/intel_npu/src/backend/src/zero_remote_tensor.cpp
src/plugins/intel_npu/src/common/include/intel_npu/common/remote_tensor.hpp
src/plugins/intel_npu/src/common/src/remote_tensor.cpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_graph.cpp
src/plugins/intel_npu/src/compiler_adapter/src/plugin_graph.cpp
src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp
src/plugins/intel_npu/src/plugin/include/remote_context.hpp
src/plugins/intel_npu/src/plugin/src/remote_context.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_wrappers.hpp
src/plugins/intel_npu/src/utils/src/zero/zero_wrappers.cpp

- *Use init structure instead of raw pointers to make sure the methods are still available*
- *Use the same design in case of shared_ptr*
- *EISW-94929*

[NPU] Use level zero init structure/ Follow same code design

---

src/plugins/intel_npu/src/al/include/intel_npu/config/compiler.hpp
src/plugins/intel_npu/src/al/include/intel_npu/npu_private_properties.hpp
src/plugins/intel_npu/src/al/src/config/compiler.cpp
src/plugins/intel_npu/src/plugin/include/metrics.hpp
src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp
src/plugins/intel_npu/tests/functional/behavior/ov_plugin/internal_properties_tests.cpp
src/plugins/intel_npu/tests/functional/internal/overload/compiled_model/property.cpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/compiled_model/properties.cpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- After GF schema removal https://jira.devtools.intel.com/browse/EISW-129562 there is no need to have use_elf_compiler_backend option as ELF backend set by default.
- https://jira.devtools.intel.com/browse/EISW-136980

[EISW-136980][NPU] Remove use_elf_compiler_backend option

---

src/plugins/intel_npu/src/plugin/npuw/weights_bank.cpp

After CompiledModel object is deleted, shared_ptr<Bank> is reset - thus expiring weak_ptr in bank manager class. If we try to create a CompiledModel object again with the same bank name - it was trying to utilize already empty bank ptr. This PR fixes such case
Release branch PR https://github.com/openvinotoolkit/openvino/pull/27486

[NPUW] Fix bank weak_ptr

---

src/frontends/tensorflow/docs/supported_ops.md
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/exp1m.cpp
src/frontends/tensorflow_common/src/op/expm1.cpp
tests/layer_tests/tensorflow_tests/test_tf_Expm1.py

**Details:** Support Expm1 operation

[TF FE] Support Expm1 operation

---

src/plugins/intel_npu/src/backend/src/zero_profiling.cpp

While investigating the problem raised by the EISW-117106 ticket, turned out that, in fact, a problem lies within the Benchmark App. For that problem, we've filed a separate ticket CVS-156823 and here we adjust the wording, aiming to reduce end-user confusion.
- E-117106

[NPU] Adjust wording to avoid confusion when running benchmarks

---

src/plugins/intel_gpu/include/intel_gpu/graph/kernel_impl_params.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/scatter_elements_update.cpp
src/plugins/intel_gpu/src/graph/scatter_nd_update.cpp
src/plugins/intel_gpu/src/graph/scatter_update.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_scatter_update_at_runtime.cpp

- *Fix the memory corruption error found runtime skipped nodes for scatter element update*
- *Implement do_runtime_scatter_update_skippable*
- *Add scatter_update to mark_runtime_skippable_nodes*
- *Update memory clearing codes to support the following cases:*
- ***Issued case1***
- *iter0: node1(executed) -> node2(skipped) -> node3(skipped)*
- *iter1: node1(skipped)  -> node2(skipped) -> node3(executed)*
- ***Issued case2***
- *iter0: node1(skipped)  -> node2(skipped) -> node3(skipped)*
- *iter1: node1(executed) -> node2(skipped) -> node3(executed)*
- *154591*

Implement runtime scatter update skippable

---

src/core/shape_inference/include/range_shape_inference.hpp
src/core/tests/type_prop/range.cpp

- *Symbol propagation for Range [0:A:1]*

[Range] Symbol propagation for range from 0 to A

---

README.md

update notebooks list in README

---

src/bindings/python/src/pyopenvino/core/core.cpp
src/bindings/python/src/pyopenvino/frontend/frontend.cpp
src/bindings/python/src/pyopenvino/utils/utils.hpp

- Writing to stringstream caused additional copy
- Usage of fstream also caused extra memory usage. Also we needed to proper handle saving/removal of the tmp_file.
- So I've squeezed two `import_model` methods to one and I've implemented/reused custom buffer that wraps interactions with python memory without extra copies
- EISW-137436

[PyOV] Improve import_model memory consumption

---

docs/articles_en/learn-openvino/openvino-samples/benchmark-tool.rst
samples/cpp/benchmark_app/benchmark_app.hpp
samples/cpp/benchmark_app/main.cpp
tests/samples_tests/smoke_tests/test_benchmark_app.py
tools/benchmark_tool/openvino/tools/benchmark/benchmark.py
tools/benchmark_tool/openvino/tools/benchmark/main.py
tools/benchmark_tool/openvino/tools/benchmark/parameters.py

- Add parameter to execute inference requests at a fixed frequency
- *ticket-id*

Add parameter to execute inference requests at a fixed frequency

---

src/inference/src/dev/core_impl.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/tests/functional/behavior/model_cache.cpp

Requested in https://jira.devtools.intel.com/browse/CVS-126606?focusedId=25564110&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25564110

Enable weightless caching with compile_model() API without providing weights_path property

---

src/inference/src/cpp/compiled_model.cpp

- Optimize Linux process using OV memory consumption by returning not used memory to the system when compiled model is destroyed.
- It should optimize memory usage by C++ and Python applications, as Linux avoid reclaim memory until process end especially for small chunks of allocations.
- CVS-149497

[core] On Linux try return not used memory to system on compile model destructor

---

tools/ovc/openvino/tools/ovc/__init__.py
tools/ovc/openvino/tools/ovc/__main__.py
tools/ovc/openvino/tools/ovc/convert_impl.py
tools/ovc/openvino/tools/ovc/ovc.py
tools/ovc/openvino/tools/ovc/telemetry_utils.py

- Fixed the issue, that '`Model Conversion API`' telemetry category includes `OVC` and all other tools, now `OVC` has a separate category "`OVC`".
- Refactored `send_params_info()` method and fixed naming of telemetry init method.

Fixed OVC app name in telemetry.

---

src/plugins/intel_gpu/src/plugin/plugin.cpp

It needs to be readable (e.g. to be queried by hello_query_device sample) and writable for plugin to set the default value.
https://jira.devtools.intel.com/browse/CVS-157364

[GPU] Change weights_path mutabilibity to RW

---

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py
docs/sphinx_setup/_templates/search.html
docs/sphinx_setup/conf.py

- *item1*
- *...*
- *ticket-id*

[DOCS Added new hierarchical field for Coveo

---

src/common/transformations/src/transformations/transpose_sinking/ts_unsqueeze.cpp
src/common/transformations/tests/transpose_sinking/ts_common_test.cpp
src/common/transformations/tests/transpose_sinking/ts_general_test.cpp

- fix TSUnsqueezeBackward
- CVS-111560

fix TSUnsqueezeBackward Reshape does nothing

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/update_shape_test.cpp

- Consider the node which is shape_of subgraph and ocl_impl in update_shape()
- 154135

[GPU] Consider the node which is shape_of subgraph and ocl_impl in update_shape()

---

docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/sequence/lstm-sequence-5.rst

- Align LSTMSequence specification attributes order with constructor
- #27355 
- CVS-156182

[docs] Align LSTMSequence specification attributes order with constructor

---

src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/matmul_quantized_subgraph.cpp

- *Matmul node support quantized outputs for f16 bias to avoid unnecessary reorder following*
- *CVS-156727*

[CPU] Matmul node support quantized outputs for f16 bias to avoid unnecessary reorder following

---

src/plugins/intel_npu/tools/protopipe/README.md
src/plugins/intel_npu/tools/protopipe/src/parser/config.cpp
src/plugins/intel_npu/tools/protopipe/src/scenario/inference.hpp
src/plugins/intel_npu/tools/protopipe/src/simulation/ov_layers_reader.cpp
src/plugins/intel_npu/tools/protopipe/src/simulation/simulation.cpp

Support for model reshape in protopipe
Added new OpenVINO parameter in config.yaml `-reshape` able to reshape input layers.
For ONNX models dynamic dimensions are set to `1`. This is consistent with the behavior of onnxruntime_perf_test.

Support for model reshape in protopipe

---

src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp

- Fixed query input remainder calculation
- Rejected sdpa_micro kernel in case of scalar-value attention mask, as specs say that attention mask could also be a scalar
- Fixed all SDPA functional tests passed on LNL
- [CVS-157371](https://jira.devtools.intel.com/browse/CVS-157371)

[GPU] sdpa_micro kernel minor fixes

---

src/frontends/onnx/frontend/src/frontend.cpp
src/frontends/paddle/src/frontend.cpp

- Due to https://github.com/protocolbuffers/protobuf/commit/009078df7a6c741d4e72a7471d1df41a58cc4070, `PROTOBUF_VERSION` is not defined in `google/protobuf/port_def.inc`

Fix build with protobuf >= 27

---

src/plugins/template/tests/functional/op_reference/lstm_sequence.cpp

- Remove LSTM Sequence v0 leftovers from test
- N/A

[tests] Remove LSTMSequence v0 leftovers from test

---

src/plugins/intel_gpu/src/plugin/plugin.cpp

- Initializes a variable in plugin.cpp. Requested by Coverity.
- https://jira.devtools.intel.com/browse/CVS-156975

[GPU] Initialize cache_mode

---

docs/articles_en/openvino-workflow/model-optimization-guide/quantizing-models-post-training/basic-quantization-flow.rst
docs/optimization_guide/nncf/ptq/code/ptq_torch_fx.py

https://openvino-doc.iotg.sclab.intel.com/nncf-docs/openvino-workflow/model-optimization-guide/quantizing-models-post-training/basic-quantization-flow.html
- *item1*
- *...*
- *ticket-id*

[Docs][NNCF] TorchFX backend docs

---

.github/workflows/android_arm64.yml
.github/workflows/android_x64.yml
.github/workflows/coverity.yml
.github/workflows/dev_cpu_linux_snippets_libxsmm.yml
.github/workflows/job_build_linux.yml
.github/workflows/job_build_windows.yml
.github/workflows/job_onnx_runtime.yml
.github/workflows/linux_conditional_compilation.yml
.github/workflows/linux_riscv.yml
.github/workflows/mac.yml
.github/workflows/mac_arm64.yml
.github/workflows/ubuntu_22.yml
.github/workflows/windows_conditional_compilation.yml

- To address the issue mentioned [here](https://unix.stackexchange.com/questions/316644/is-make-j-with-no-argument-dangerous), we need to set the number of parallel jobs explicitly
- #27422
- #27445

[MERGE][GHA] WA parallel make issue (#27422)

---

src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp

- Backport of PR https://github.com/openvinotoolkit/openvino/pull/27493
- *ticket-id*

[GPU] Fix unexpectedly turned off Small N case optimization 

---

src/plugins/intel_gpu/include/intel_gpu/plugin/sync_infer_request.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp

- For dGPU including A770, when network output size is large, performance is better with explicit copy then writing data to usm_host.
- Allow usm_host access for input
- Next-gen dGPU, write to usm_device and copy it to usm_host
- For DG2, write to usm_device only for large output
- 157439

[GPU] Do not use usm_host when network output tensor size is large

---

.github/workflows/merge_queue_stub.yml

Allows to keep Jenkins running in pre-commits, but not in merge queue without paralyzing queue when Jenkins is offline

[GHA] Add merge queue stub check for ci/jenkins

---

src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/utils/debug_capabilities.h

There is a case, when a node is a static one and it has 0 dim in one of its input shapes.
In this case we must not execute this node, but performing
additional isExecutable() check in runtime for all the static nodes
would be to expensive

[CPU][DEBUG_CAPS] Do not include all the nodes to executable ones

---

src/core/shape_inference/include/one_hot_shape_inference.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/one_hot.hpp
src/plugins/intel_gpu/src/graph/include/one_hot_inst.h
src/plugins/intel_gpu/src/graph/one_hot.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/plugin/ops/one_hot.cpp

- *Get the 'depth' value from 'Select' node instead of a Constant node*
- *[CVS-155564](https://jira.devtools.intel.com/browse/CVS-155564)*
Migrated from PR https://github.com/openvinotoolkit/openvino/pull/27442.

[GPU] Fix OneHot segmentation fault when the second input node is not a Constant node 

---

src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/src/edge.h
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/infer_request.cpp
src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/nodes/concat.cpp
src/plugins/intel_cpu/src/nodes/memory.cpp
src/plugins/intel_cpu/src/utils/debug_capabilities.cpp
src/plugins/intel_cpu/src/utils/debug_capabilities.h

by replacing "name()" with ostream operator.
Also include "status" to the printed information.

[CPU] Enchant Edge "to string" logic

---

src/plugins/intel_gpu/src/plugin/transformations/dynamic_quantize_fully_connected.cpp
src/plugins/intel_gpu/src/plugin/transformations/increase_position_ids_precision.cpp

- Regarding CID: 1559222 and 1559203. This could be false positive since the class IncreasePositionIdsPrecision does not have any member variables that need initialization.  I updated line 50 to ensure 'this' pointer is properly captured.
- Regarding CID: 1559220 and 1559209. This could also be a false positive. To address this issue I'm proposing to explicitly call the base class constructor in the initializer list of the constructor.
Need to re-run the Coverity scan to confirm fix.
- CVS-149659

[Coverity] Uninitialized members

---

src/plugins/intel_gpu/src/plugin/transformations/op/kv_cache.cpp
src/plugins/intel_gpu/src/plugin/transformations/op/sdpa.cpp
src/plugins/intel_gpu/src/plugin/transformations/unsqueeze_broadcast_reshape_sdpa_fusion.cpp

- By relaxing UnsqueezeBroadcastReshapeSDPAFusion, GQA pattern is enabled and Broadcasting nodes overheads in paths of key and value are removed, thus improves performance of GLM4 model significantly.
- Fix for GLM4V, which has initial state shape (-1, 0, 0, 0), and shape infer failed.
- *CVS-157263*

[GPU] Relax UnsqueezeBroadcastReshapeSDPAFusion (#27515)

---

src/common/transformations/include/ov_ops/rotary_positional_embeddings.hpp
src/common/transformations/include/transformations/common_optimizations/fuse_rotary_positional_embeddings.hpp
src/common/transformations/src/ov_ops/rotary_positional_embeddings.cpp
src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp
src/common/transformations/tests/common_optimizations/fuse_rotary_positional_embeddings.cpp
src/plugins/intel_cpu/src/nodes/rope.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_gpu/include/intel_gpu/primitives/rope.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/rope.cpp
src/plugins/intel_gpu/src/graph/rope.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/rope_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/rope/rope_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/rope/rope_kernel_base.h
src/plugins/intel_gpu/src/plugin/ops/rope.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/rotary_pos_emb.cpp
src/tests/functional/plugin/shared/include/subgraph_tests/rotary_pos_emb.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/rotary_pos_emb.hpp
src/tests/functional/shared_test_classes/src/subgraph/rotary_pos_emb.cpp

- Enabled ROPE op fusion for flux.1 model on GPU to improve the performance
- New mode for RoPE is added which enables the case when coordinates and angles are interleaved and sin/cos tables are separate inputs. It's activated when `is_interleaved=true` and `output_trans0213=false`

[GPU][TRANSFORMATIONS] Rope for flux

---

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp

This reverts commit 9a5d3a5051e52a1c81837b0f901af5e215f9fcb3.
- The WA causes accuracy issue in mixtral model
- 157374

Revert "[GPU] WA to avoid too long consecutive runtime skippable nodes (#27635)"

---

src/plugins/intel_cpu/src/nodes/scatter_update.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/scatter_ND_update.cpp

Instead of corrupting the memory.
To align the behavior with the documentation.
- 154239
A port for release branch 2024/5 
Fix for master:
- https://github.com/openvinotoolkit/openvino/pull/27483

[CPU] Throw when ScatterNDUpdate indices are out of bounds

---

docs/articles_en/learn-openvino/llm_inference_guide/llm-inference-hf.rst
src/plugins/intel_gpu/src/plugin/transformations/kv_cache_compression.cpp

- Update docs related to KV-cache quantization on GPU
- Allow to use `element::u8` as data type for KV-cache quantization to be aligned with CPU Plugin

[GPU] Update docs related to KV-cache quantization

---

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_runtime_skippable_nodes.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/primitive_base.hpp
src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/skip_gather_at_runtime.cpp

- *Fix invalid output memory usages by reset output  memory*
- *At the previous iteration, gather primitive has output memory which is refer input memory because it is optimized out but it also use input memory as output without reallocation memory at the next iteration which turns to executed from optimized out. it makes memory corruption issue.*
- *Reset output memory when the current prim status is changed from optimized / skipped to executed*
- *154591*

[GPU] Fix reset output issue

---

src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/transpose_matmul_fusion.cpp

- *The gemm onednn requires non-transposed output shape and transposed order info. But the current impl uses output-transposed shape itself. It needs to use non-transposed output shape.*
- *155222*

[GPU] Enable output transposed gemm for onednn

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp

[GPU] set output from variable's memory if kv-cache

---

.github/workflows/debian_10_arm.yml
.github/workflows/linux_arm64.yml

- Switch Docker images builds to smaller runners
- Switch compilation to newer generation of ARM VMs
- Switch tests to newer generation of ARM VMs and/or smaller runners, where applicable

Optimize ARM runners in AKS

---

src/plugins/intel_npu/src/al/include/intel_npu/config/runtime.hpp
src/plugins/intel_npu/src/al/include/intel_npu/npu_private_properties.hpp
src/plugins/intel_npu/src/al/src/config/runtime.cpp
src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp
src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp
src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
src/plugins/intel_npu/src/common/include/intel_npu/common/igraph.hpp
src/plugins/intel_npu/src/common/src/igraph.cpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_graph.cpp
src/plugins/intel_npu/src/compiler_adapter/src/plugin_graph.cpp
src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp
src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_utils.hpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_wrappers.hpp
src/plugins/intel_npu/src/utils/src/zero/zero_wrappers.cpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.cpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp

- In-order to activate it, the NPU_RUN_INFERENCES_SEQUENTIALLY property should be set to true when compiling a model. This feature works only for the inferences from a compiled model.
- It doesn't support scheduling inferences from different compiled models.
- Inferences should be run each time in the same order they were called the first time

[NPU] In-order async execution

---

src/frontends/tensorflow/src/checkpoint_v1_reader.cpp
src/frontends/tensorflow/src/op/var_handle.cpp
src/frontends/tensorflow/src/op/xla_conv_v2.cpp
src/frontends/tensorflow/src/variables_index.cpp

**Details:** Fix coverity issues to avoid uninitialized vars
**Tickets:** 157252

[TF FE] Fix coverity issues to avoid uninitialized vars

---

src/inference/dev_api/openvino/runtime/icompiled_model.hpp
src/inference/src/cpp/compiled_model.cpp
src/inference/src/dev/icompiled_model.cpp

- The `malloc_trim` in `CompileModel` class cause to often trigger not when real implementation is removed but on each destruction of wrapper. Now the destructor of `ICompileModel` trigger it should be called after all inference related to this model.
- CVS-158427

[core] Move malloc_tim to compile model implementation

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pooling_gpu_int8_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/pooling/pooling_kernel_gpu_int8_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/pooling/pooling_kernel_gpu_ref.cpp
src/plugins/intel_gpu/tests/unit/test_cases/pooling_gpu_test.cpp

- *Support fs_b_yx_fsv32 and int8 case for pooling*
- *157507*

[GPU] Support fs_b_yx_fsv32 and int8 case for pooling

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/tests/functional/custom/behavior/ov_executable_network/properties.cpp

- *Prioritize the user setting for kvcache type/group size over rt_info, port from  #27583 in releases/2024/5*
- *ticket-id*

[CPU] Port for prioritizing the user setting for kvcache type/group size

---

src/plugins/intel_gpu/src/kernel_selector/kernels/eltwise/eltwise_kernel_blocked_opt.cpp
src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp

Improve yolo_v5m peformance by using eltwise_blocked_opt for batchNormalization which help for platforms has XMX.  Besides, improve performance for faceboxes model.
- cvs- 157435

Add more mixed type of bfyx to eltwise_blocked_opt

---

docs/articles_en/documentation/openvino-security.rst

Adding info on importing compiled models in OpenVINO Security.

[DOCS] Loading encrypted compiled_blob

---

tests/requirements_tensorflow

Fix one of the blockers for dropping openvino-dev in internal CI

[tests/requirements_tensorflow] Fix jax version for python 3.9 & NumPy conflict on Py 3.12 on MacOS

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/reduce_ops.cpp

- *This is a fix about some of the test cases of https://github.com/openvinotoolkit/openvino/pull/27603. The test cases are modified so that all of them will cover the new added functionality in Reduce layer, i.e., input tensor is empty while output tensor is not empty.* The PR is cherry-picked from the last commit in https://github.com/openvinotoolkit/openvino/pull/27813.

[Test] Fix test cases of Reduce node with empty input

---

docs/sphinx_setup/api/nodejs_api/addon.rst

Adding info on the saveModelSync method.

[DOCS] Update nodejs addon save model method for 24.5

---

src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected.hpp
src/plugins/intel_cpu/src/nodes/executors/executor_factory.hpp
src/plugins/intel_cpu/src/nodes/executors/fullyconnected_implementations.cpp
src/plugins/intel_cpu/src/nodes/executors/graph_emitter.hpp
src/plugins/intel_cpu/src/nodes/executors/variable_executor.hpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h

Depending on the parameters a `FullyConnected` node can
use one or multiple executors.
With the current approach, even when just a single executor
is used, every `prepareParams()` (executor::update())
call goes through executor selection routine.
The idea is to avoid such `prepareParams()` overhead for a single executor scenarious,
which are probably the most common ones.
Thus, split the pipeline input two branches:
- only single simple executor is used and updated
- a `VariableExecutor` is used and updated. `VariableExecutor` contains
two or more simple executors

[CPU][Refactoring] Introduce VariableExecutor

---

tests/llm/accuracy_conformance.py

There is an issue with ONNX>=1.17 which causes DLL load failures on Windows. Previously it caused WWB import to fail (CVS-158774), it was fixed in https://github.com/openvinotoolkit/openvino.genai/pull/1301. Now this llm tests failure comes from the next import, optimum.intel.openvino, and it doesn't reproduce locally if optimum.intel.openvino is imported before WWB.

[tests/llm] Reorder imports to avoid onnx-related DDL load fail

---

.github/actions/openvino_provider/action.yml

Will require switching env.GITHUB_WORKSPACE workaround to github.workspace mount in pipelines using OV provider

[GHA][ov-provider] Use github.workspace for upload-artifact (#27820)

---

src/plugins/intel_gpu/include/intel_gpu/runtime/debug_configuration.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/fully_connected.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/graph/include/pass_manager.h
src/plugins/intel_gpu/src/graph/include/swiglu_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.h
src/plugins/intel_gpu/src/kernel_selector/kernels/swiglu/swiglu_kernel_base.h
src/plugins/intel_gpu/src/plugin/ops/swiglu.cpp
src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.cpp
src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.hpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/src/runtime/debug_configuration.cpp
src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/fusions/fusion_test_common.hpp

- 2 FCs + swiglu in MLP pattern are fused
- Only applied to cldnn && #EUs > 128 && glu type with swiglu 
- 152163

[GPU] MLP : 2fcs + swiglu fusion 

---

src/core/shape_inference/include/ov_optional.hpp
src/core/tests/pattern.cpp
src/inference/include/openvino/runtime/core.hpp
src/inference/tests/functional/ov_core_test.cpp
src/inference/tests/functional/ov_extension_test.cpp

- The `ov::Core` accepts `std::filesytem::path` in functions where string as path is used.
- CVS-157908

[core] Extend Core API to accept std::filesystem::path when build with cpp17

---

src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp

- fixed crash happens in minicpm-1b-sft int4 model 
- *ticket-id*

[GPU] Fix  crash on swiglu fused case (due to outer_ofm == 1)

---

.github/components.yml
tests/requirements_pytorch

There are failures with newer commits, e.g.
https://github.com/openvinotoolkit/openvino/actions/runs/12240792041/job/34146426674

[tests/requirements_pytorch] Temporarily fix optimum-intel version on last stable commit (#27985)

---

src/inference/dev_api/openvino/runtime/internal_properties.hpp
src/inference/src/cache_manager.hpp
src/inference/src/dev/core_impl.cpp
src/inference/tests/functional/caching_test.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/utils/serialize.cpp
src/plugins/intel_cpu/src/utils/serialize.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp

- Replacement for https://github.com/openvinotoolkit/openvino/pull/27644
- CVS-154602
- CVS-157192

New plugins property to pass mmap buffer

---

src/plugins/intel_gpu/include/intel_gpu/runtime/execution_config.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp
src/plugins/intel_gpu/tests/functional/behavior/properties.cpp

- GPU with systolic ignores some of rt_info to avoid performance regression
- FC scaling
- kv cache compression
- 159040, 159047

[GPU] Disable KV cache compression and FC scaling for GPU with systolic

---

src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
src/common/transformations/tests/common_optimizations/nop_elimination.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

NOP-elimination doesn't allow the removal of unnecessary data-movement
operations stacked on top of each other if their shapes are dynamic, even
though certain cases of dynamic shapes can be covered by
NOP-elimination.
Allow NOP-elimination for dynamic shapes if they have only the 0th
dimension dynamic and other static, making this case compatible for
such a fusion.
- Tickets:
* CVS-158394

[TRANSFORMATIONS] Allow NOP-elimination for shapes with dynamic 0th dimension

---

src/plugins/intel_gpu/src/kernel_selector/kernels/resample/resample_kernel_onnx.cpp
src/plugins/intel_gpu/tests/unit/test_cases/resample_gpu_test.cpp

- *Fix gws value of resample onnx kernel with fs_b_yx_fsv32 format*
- *158837*

[GPU] Fix gws of Resample onnx kernel

---

samples/python/benchmark/bert_benchmark/bert_benchmark.py

When OV is built with VS2022 and imported after datasets module, ov.Core() call fails with access violation error.
- CVS-158167

Workaround for sample failure with OV built by VS2022

---

src/plugins/intel_gpu/src/kernel_selector/kernels/group_normalization/group_normalization_kernel_bfyx_opt.cpp
src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp

- In group normalization, there can be a case requiring input bfyx and output fsv16 in bfyx opt kernel.
- 156608

[GPU] support fsv16 for output of group norm bfyx opt kernel

---

src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/opt.cpp

- Add optional convert after multiply for pattern match
- Add optional logic when transpose weights for miniCPM.
- [EISW-131455](https://jira.devtools.intel.com/browse/EISW-131455)

[NPUW] Add optional convert when transpose weights for miniCPM.

---

src/core/include/openvino/core/graph_util.hpp
src/core/include/openvino/pass/serialize.hpp
src/core/tests/pass/serialization/deterministicity.cpp
src/core/tests/pass/serialization/serialize.cpp

- Extend `Serialize` and `save_model` API to support cpp17 path class
- CVS-158889

[core] Extend model serialize API to support std::filesystem::path

---

src/bindings/js/node/package.json

- To better indexing openvino-node npm package we have to add more related keywords into package.json

[OV JS] Extend npm package keywords

---

.github/workflows/job_python_api_tests.yml

- Now Python API tests are running with numpy2.x by default, so still neeed to test them with numpy 1.x
- *ticket-id*

[GHA][numpy] test python api & numpy 1.26.x

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- Add ConvolutionBackpropData in target_consumers,convolutions of is_decompression_multiply()
- 159207

[GPU] Add ConvolutionBackpropData in is_decompression_multiply() of MarkDequantizationSubgraph callback

---

src/plugins/intel_gpu/include/intel_gpu/runtime/device_info.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp

Details:
Existing method for cache size calculation was static and need continious updates to the sku table which was already being missed for latest skus e.g DG2.
This update introduces a new member variable, max_global_cache_size, to store the GPU's global cache size, obtained via the OpenCL property CL_DEVICE_GLOBAL_MEM_CACHE_SIZE. The existing hard coded cache calculations are removed.  Additionally, the closest_pow_of_2 function has been enhanced to return the nearest power of 2, favoring the upper value if the input is within 30% of the range for the upper bound. These changes improve memory management and ensure better utilization of GPU resources towards bottle neck situations.
Tickets:
CVS-159076

[GPU] Updated GPU cache size retrieval and refined closest_pow_of_2

---

docs/articles_en/openvino-workflow/torch-compile.rst

https://openvino-doc.iotg.sclab.intel.com/nncf-docs/openvino-workflow/torch-compile.html#model-quantization-and-weights-compression
- NNCF quantization / compression is added to `torch.compile` documentation

[Docs][torch.compile] NNCF quantization/compression

---

src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/mat_mul.cpp

- *Set fc format to bfyx when its spatial pitches are not one to avoid to select fb_io_block kernel*
- *155068*

[GPU] Set fc format to bfyx when its spatial pitches are not one

---

src/bindings/js/node/package-lock.json
src/bindings/js/node/package.json

- update openvino-node package version to 2024.6.0
- port of keywords extension from https://github.com/openvinotoolkit/openvino/pull/28047

[OV JS] Update openvino-node package version to 2024.6.0

---

src/plugins/intel_cpu/src/emitters/snippets/aarch64/cpu_generator.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/eltwise.cpp

- *The PR enabled Snippets tokenization for ops `Ceiling` (activation) and `FloorMod` (eltwise):*
- *Updated tokenization callback*
- *Registered the operations with the corresponding emitters in `CPUGenerator`*
- *Added tests*
- *This PR is example for the further GFIs'*
- *N/A*

[Snippets][AArch64] Enabled Ceiling and FloorMod tokenization

---

src/frontends/onnx/frontend/src/core/tensor.cpp
src/frontends/onnx/frontend/src/core/tensor.hpp
src/frontends/onnx/frontend/src/utils/tensor_external_data.hpp

- Removed a redundant memory copying for data types less than 4 bytes when MMAP is using
- Implementation verified by a previously added tests named onnx_external_data_*
- 159161

[ONNX] Removed redundant memory copying for small data types when MMAP is using

---

src/plugins/intel_cpu/tools/commit_slider/utils/cfg.json
src/plugins/intel_cpu/tools/commit_slider/utils/cfg_samples/llm_bench.json
src/plugins/intel_cpu/tools/commit_slider/utils/modes.py

- *item1*
- *...*
- *ticket-id*

[Commit slider] LLM bench support

---

docs/snippets/CMakeLists.txt
src/core/template_extension/CMakeLists.txt

- See https://github.com/microsoft/vcpkg/pull/42259#issuecomment-2528701658

Find python in extensions safely

---

cmake/developer_package/compile_flags/os_flags.cmake

- This issue is a MSVC compiler bug affecting certain versions of Visual Studio 2022. When using std::mutex a null dereference may occur, leading to a silent crash in Release mode.
- Adding the compiler option "/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR" serves as a workaround for this problem.
Reference:
https://hydrogenaud.io/index.php/topic,126070.0.html
https://github.com/microsoft/STL/wiki/Changelog#vs-2022-1710
- CVS-159684

Add WA for MSVC compiler mutex constructor issue with VS2022

---

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_shape_of_subgraphs.cpp
src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp

- Fix ”Assertion `static_impl != nullptr' failed“ issue for reorder (Convolution_0_reorder_1) node by skipping mark node in shape flow.
- [CVS-154336](https://jira.devtools.intel.com/browse/CVS-154336)

[GPU] Fix static_impl != nullptr assertion for reorder node

---

src/plugins/intel_gpu/src/graph/program.cpp

- *Enable can_use_fsv16 and can_use_bs_fs_yx_bsv16_fsv16 for group_normalization in pytorch version timm_mobilevitv2_150 OV model to get better performance*
- *[CVS-154913](https://jira.devtools.intel.com/browse/CVS-154913)*

[GPU] Enable can_use_fsv16 and can_use_bs_fs_yx_bsv16_fsv16 for group_normalization

---

src/common/transformations/include/transformations/common_optimizations/sdpa_fusion.hpp
src/common/transformations/include/transformations/common_optimizations/sdpa_scale_fusion.hpp
src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/src/transformations/common_optimizations/sdpa_fusion.cpp
src/common/transformations/src/transformations/common_optimizations/sdpa_scale_fusion.cpp
src/common/transformations/tests/common_optimizations/sdpa_fusion_test.cpp
src/common/transformations/tests/common_optimizations/sdpa_scale_fusion_test.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- Added basic SDPA fusion pass and QK scaling fusion into SDPA
T5 case

[TRANSFORMATIONS][GPU] SDPA Fusion passes

---

.github/workflows/cleanup_caches.yml
.github/workflows/export_workflow_metrics.yml
.github/workflows/workflow_rerunner.yml

Metrics collection generates a lot of workflows, and they fight for runners with regular test jobs. This PR fixes that.

Switch metrics collection to a separate runner

---

src/inference/src/os/lin/lin_system_conf.cpp

- *fix below coverity scan issue*
*** CID 1568450: Concurrent data access violations (MISSING_LOCK)
/openvino/src/inference/src/os/lin/lin_system_conf.cpp: 225 in ov::CPU::CPU()::[lambda() (instance 2)]::operator ()() const()
219 return -1;
220 } else if (valid_cpu_mapping_table.size() == (unsigned)_processors) {
221 return 0;
222 } else {
223 _processors = valid_cpu_mapping_table.size();
224 _cpu_mapping_table.swap(valid_cpu_mapping_table);
CID 1568450:  Concurrent data access violations  (MISSING_LOCK)
Accessing "this->this->_proc_type_table" without holding lock "ov::CPU._cpu_mutex". Elsewhere, "ov::CPU._proc_type_table" is written to with "CPU._cpu_mutex" held 2 out of 3 times.
225 update_valid_processor_linux(std::move(phy_core_list),
226 _numa_nodes,
227 _cores,
228 …

update fix for coverity scan issue 1568450

---

tests/requirements_pytorch
tests/requirements_tensorflow

To align with internal tests requirements and avoid E2E failures (AttributeError: 'Config' object has no attribute '_metadata')

[tests/requirements] Newer pytest for python >=3.10

---

src/frontends/onnx/tests/__init__.py
src/plugins/intel_cpu/src/dnnl_extension_utils.cpp
src/plugins/intel_cpu/src/nodes/common/cpu_convert.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/conversion.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/conversion.hpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/arm/conversion.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/conversion.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/conversion.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/conversion.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/shared_test_classes/src/single_op/conversion.cpp

- *Implement fp8 conversion with the following combinations:*
_fp32<->f8e4m3, fp16<->f8e4m3, bf16<->f8e4m3_
_fp32<->f8e5m2, fp16<->f8e5m2, bf16<->f8e5m2_
- *[CVS-156962](https://jira.devtools.intel.com/browse/CVS-156962)*

[CPU] Implement fp8 conversion

---

src/inference/src/os/lin/lin_system_conf.cpp

- *item1*
CID 1529754: (#1 of 1): COPY_INSTEAD_OF_MOVE (COPY_INSTEAD_OF_MOVE)
1. copy_constructor_call: node_info_table is passed-by-value as parameter to parse_freq_info_linux when it could be moved instead.
Use std::move(node_info_table) instead of node_info_table.
221                                  node_info_table,
222                                  _processors,
223                                  _numa_nodes,
224                                  _sockets,
225                                  _cores,
226                                  _proc_type_table,
227                                  _cpu_mapping_table);
- *ticket-id*

fix coverity scan issue CID 1529754

---

src/common/transformations/src/transformations/sdpa_to_paged_attention/position_ids_replacer.cpp

The "current len" pattern might be created in 2 different ways in the Qwen model.
After one of the comments in the review (https://github.com/openvinotoolkit/openvino/pull/28067/files) was resolved, we made the pattern stricter, it stopped covering one of the cases.
- *CVS-157308*

Fix PositionIdsReplacer for Qwen

---

tests/constraints.txt
tests/layer_tests/requirements.txt

**Details:** We no longer need jax reqs in common requirements files after separation into requirements_jax

[JAX FE] Remove jax reqs from common requirements file

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_data_bfyx_to_blocked_format.cl

- Fix for border_gpu.zyx_bsv16fsv16 case
- case when x size less than tile size was not handled

[GPU] Fix oob in reorder for BMG

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/reorder_data_b_fs_yx_fsv16_fsv32_to_bfyx.cl

- Fix OOB in reorder_data_b_fs_yx_fsv16_fsv32_to_bfyx
- railed in next units tests with -58 memory errors

[GPU] Fix oob in bfyx reorder for BMG

---

src/common/transformations/include/transformations/op_conversions/fake_convert_decomposition.hpp
src/common/transformations/src/transformations/op_conversions/fake_convert_decomposition.cpp
src/common/transformations/tests/op_conversions/fake_convert_decomposition_test.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/single_layer_tests/fake_convert.cpp
src/tests/functional/plugin/shared/include/single_op_tests/fake_convert.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/single_op/fake_convert.hpp
src/tests/functional/shared_test_classes/src/single_op/fake_convert.cpp

- *Implement FakeConvert decomposition transformation.*
- *[CVS-156963](https://jira.devtools.intel.com/browse/CVS-156963)*
- *https://github.com/openvinotoolkit/openvino/pull/27949*

[CPU] [TRANSFORMATIONS] FakeConvert decomposition transformation

---

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device/performance-hint-and-thread-scheduling.rst

- *update doc for using one socket with latency hint instead of one numa node*
- *ticket-id*

update doc for using one socket with latency hint instead of one numa node

---

docs/openvino_custom_sphinx_sitemap/openvino_custom_sphinx_sitemap/__init__.py

- *item1*
- *...*
- *ticket-id*

Docs port for sitemap fix to 24.6

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/passes/post_optimize_weights.cpp

SD3 dynamic has FC unfusion pattern, and needs sub graphs. It caused bad performance.
- *152851, 157100*

[GPU] Use onednn gemm instead of inner product

---

src/plugins/intel_cpu/src/cpu_streams_calculation.cpp

- *fix coverity scan issue CID 1537543*
config.streamExecutorConfig = IStreamsExecutor::Config{"CPUStreamsExecutor",
706                                                           config.streams,
707                                                           config.threadsPerStream,
708                                                           ov::hint::SchedulingCoreType::ANY_CORE,
709                                                           false,
710                                                           cpu_pinning,
CID 1537543: (#1 of 1): COPY_INSTEAD_OF_MOVE (COPY_INSTEAD_OF_MOVE)
1. copy_constructor_call: streams_info_table is passed-by-value as parameter to ov::threading::IStreamsExecutor::Config::Config(std::string, int, int, ov::hint::SchedulingCoreType, bool, bool, …

fix coverity scan issue CID 1537543

---

src/plugins/intel_cpu/src/nodes/conv.cpp

- *brdgmm_dw_conv kernels support only bia_type the same as src_type or dst_type*
- *CVS-157009*

[CPU] enable brdgmm_dw_conv kernels with non f32 bias

---

src/core/include/openvino/pass/pattern/op/pattern.hpp
src/core/src/pattern/op/pattern.cpp
src/core/tests/pattern.cpp
src/plugins/intel_gpu/src/plugin/transformations/clamp_fp16_output.cpp
src/plugins/intel_gpu/src/plugin/transformations/convert_convolution.cpp
src/plugins/intel_gpu/src/plugin/transformations/optimize_subsequent_reshapes.cpp

- *Enables operator || and && for pass predicates*
- *N/A: Transformations enhancement*

Enables operator || and && for pass predicates

---

src/plugins/intel_npu/src/utils/src/zero/CMakeLists.txt
thirdparty/dependencies.cmake

- When system level-zero is used, we cannot rely on submodule.
- It's a regression after https://github.com/openvinotoolkit/openvino/pull/27659

Fixed build with system level-zero

---

src/plugins/intel_npu/src/al/include/intel_npu/config/npuw.hpp
src/plugins/intel_npu/src/al/include/intel_npu/npuw_private_properties.hpp
src/plugins/intel_npu/src/al/src/config/npuw.cpp
src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp

- *Refactoring LLMCompiledModel according to comments in https://github.com/openvinotoolkit/openvino.genai/pull/1240*
- *ticket-id*

Refactoring LLMCompiledModel according to review comments in GenAI static_llm::StatefulLLMPipeline

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_unfusion.cpp

- Add check of multiple axis broadcasting in is_valid_fusion() when dynamic shape
- Current ocl fused_op jit constant doesn't support multiple axis boradcase.
- 159939

[GPU] Add check of multiple axis broadcasting in is_valid_fusion() when dynamic shape

---

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp
src/plugins/intel_gpu/src/graph/loop.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_memory.cpp

- Fix many unittest failures due to the zero byte allocation of ocl memory
- Removed unnecessary function to allocate 1 byte for zero byte layout
- CVS-160053

[GPU] Fix many unittest failures due to the zero byte allocation of ocl memory

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp

- Migrate to OpenCL v2024.10.24
- Required for integration with open source package managers
- Replacement for https://github.com/openvinotoolkit/openvino/pull/27698

Migrate to OpenCL v2024.10.24

---

src/plugins/intel_cpu/src/nodes/kernels/x64/rms_kernel.cpp
src/plugins/intel_cpu/src/nodes/llm_mlp.cpp
src/plugins/intel_cpu/src/nodes/qkv_proj.cpp
src/plugins/intel_cpu/src/nodes/scaled_attn.cpp

- Fix medium severity coverity issues:
* Division or modulo by float zero: 1565219
* Uninitialized scalar field: 1565060
* Uninitialized pointer field: 1565135
* Identical code for different branches: 1565044
- [CVS-157247](https://jira.devtools.intel.com/browse/CVS-157247)

Fix medium severity issues reported in CPU plugin

---

cmake/developer_package/api_validator/api_validator.cmake
cmake/developer_package/features.cmake
cmake/features.cmake
src/common/util/CMakeLists.txt

- Required to merge https://github.com/openvinotoolkit/openvino.genai/pull/1402
- For some reason we have recursion if we have 2 functions with name `ov_add_api_validator_post_build_step` and `_ov_add_api_validator_post_build_step`

[CMAKE] Fix to Api validator for older cmake versions

---

src/plugins/intel_npu/src/plugin/npuw/weights_bank.cpp
src/plugins/intel_npu/src/plugin/npuw/weights_bank.hpp

Previous PR https://github.com/openvinotoolkit/openvino/pull/28282

[NPUW] Fix for weights bank UIDs

---

src/plugins/intel_cpu/src/compiled_model.cpp
src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/cpu_memory.cpp
src/plugins/intel_cpu/src/cpu_memory.h
src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/graph_context.cpp
src/plugins/intel_cpu/src/infer_request.cpp
src/plugins/intel_cpu/src/memory_control.cpp
src/plugins/intel_cpu/src/nodes/composite.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/llm_mlp.cpp
src/plugins/intel_cpu/src/nodes/pad.cpp
src/plugins/intel_cpu/src/nodes/reorder.cpp
src/plugins/intel_cpu/src/nodes/rms_norm.h
src/plugins/intel_cpu/src/nodes/rnn.cpp
src/plugins/intel_cpu/src/nodes/string_tensor_pack.cpp
src/plugins/intel_cpu/src/nodes/string_tensor_unpack.cpp
src/plugins/intel_cpu/src/partitioned_mem_blk.h
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/proxy_mem_blk.cpp
src/plugins/intel_cpu/src/proxy_mem_blk.h
src/plugins/intel_cpu/src/shape_inference/custom/rms_norm.hpp

- Fix "COPY_INSTEAD_OF_MOVE" coverity scans: 1560671, 1560670, 1560668, 1560667, 1560666, 1560059, 1560057, 1560055, 1560054, 1560052, 1560051, 1560050, 1560047, 1560046, 1560045, 1560043, 1560042, 1560041, 1559840, 1559804, 1559802, 1559777, 1559761, 1559697, 1559559, 1559558, 1559557, 1559556, 1559553, 1559552, 1559549, 1559547, 1559545, 1559543, 1559542, 1559539
- Fix "Use of auto that causes a copy" coverity scans: 1560673, 1560669, 1560044, 1559820, 1559817, 1559561, 1559560, 1559555, 1559544, 1559540
- [CVS-153062](https://jira.devtools.intel.com/browse/CVS-153062)

Fix performance inefficiencies coverity scan issues in CPU plugin

---

src/common/transformations/tests/utils/convert_precision.cpp
src/core/include/openvino/op/result.hpp
src/core/src/model.cpp
src/core/src/node_vector.cpp
src/core/src/op/result.cpp
src/core/tests/preprocess.cpp
src/core/tests/type_prop/result.cpp
src/frontends/ir/src/ir_deserializer.cpp
src/frontends/onnx/frontend/src/input_model.cpp
src/inference/src/model_reader.cpp

- The Result node may use inputs names when created. Creation such Result assume as previous layer is model output.
- The model when created from outputs and the outputs are note Result node, then create results and take its names as model output names.
- The Result has option to enable/disable use inputs names as it owns. If names not used they still be visible as output names if Result has no dedicated names but if Result is connect to other input these names stay on origin input.
- CVS-159672

[core] Result node may uses inputs names on creation

---

src/common/snippets/src/pass/split_dimension_m.cpp
src/common/snippets/tests/src/pass/mha_tokenization.cpp

- *Currently, the pass `SplitDimensionM` supports only static inputs of Subgraphs because the pass inserts `Reshape` ops with const shapes. In some cases (the case from the ticket), MatMul may have static output shape but some parameters - dynamic shape. Then `SplitDimensionM` should not call `split` method. The PR added check with early `return` to cover such cases*
- *159661*

[Snippets] Fixed SplitDimensionM pass for Subgraphs with dynamic params

---

src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/mha_single_token.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/arm/concat_sdp.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/concat_sdp.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/concat_sdp.cpp

- This PR fixes incorrect cvt_copy rountine behavior inside mha_single_token kenrel on ARM platforms. In case __ARM_FEATURE_FP16_VECTOR_ARITHMETIC is defined on the system and fp32 inference scalar code path is chosen.
- Additionally cvt_copy impl is refactored via template specialization for better readability 
- Follow-up after https://github.com/openvinotoolkit/openvino/pull/28182

[CPU][ARM] Fixed cvt_copy fast path for mha_single_token_kernel

---

cmake/developer_package/compile_flags/os_flags.cmake

- Fix MSVC version to cover all compiler versions of v143 toolset
https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html
- CVS-158167
- CVS-159653

Fix msvc version to cover v143 toolset

---

cmake/templates/OpenVINODeveloperPackageConfig.cmake.in
cmake/templates/OpenVINODeveloperPackageConfigRelocatable.cmake.in

- In case of GenAI we include developer packages two times: GenAI and Tokenizers

Don't include developer package multiple times

---

samples/cpp/benchmark_app/main.cpp
tools/benchmark_tool/openvino/tools/benchmark/main.py

- This disables nireq check in case execution time is specified when using the sync API
- CVS-159638

[benchmark] Do not check nireq if sync and time is specified

---

src/bindings/python/src/openvino/frontend/pytorch/fx_decoder.py
src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py
src/bindings/python/src/pyopenvino/frontend/pytorch/decoder.hpp
src/frontends/pytorch/include/openvino/frontend/pytorch/decoder.hpp
src/frontends/pytorch/include/openvino/frontend/pytorch/node_context.hpp
src/frontends/pytorch/src/node_context.cpp
src/frontends/pytorch/src/op/as_strided.cpp
src/frontends/pytorch/src/op/cat.cpp
src/frontends/pytorch/src/op/expand.cpp
src/frontends/pytorch/src/op/full.cpp
src/frontends/pytorch/src/op/index.cpp
src/frontends/pytorch/src/op/repeat.cpp
src/frontends/pytorch/src/op/repeat_interleave.cpp
src/frontends/pytorch/src/op/reshape.cpp
src/frontends/pytorch/src/op_table.cpp
src/frontends/pytorch/src/translate_session.hpp
src/frontends/pytorch/src/utils.cpp
src/frontends/pytorch/src/utils.hpp
tests/model_hub_tests/pytorch/test_timm.py
tests/model_hub_tests/pytorch/test_torchvision_models.py
tests/model_hub_tests/pytorch/timm_models
tests/model_hub_tests/pytorch/torch_utils.py

- *Support dynamic shapes torch.export*
- *Improve support for `list` as inlined inputs. Previously we decomposed lists to many inputs, now we use decoder to make it a list and resolve it in a same way we resolve lists in TS graph.*
- *CVS-138565*

[PT FE] Support dynamic shapes torch.export

---

src/bindings/python/src/openvino/_ov_api.py
src/bindings/python/tests/test_runtime/test_model.py

- Overload `dir()` method for class objects. Add meta class `ModelMeta` and overload `dir()`
- Add test for checking model attributes usind `dir()`
- [CVS-160178](https://jira.devtools.intel.com/browse/CVS-160178)

[Py OV] Fix openvino.Model mocked object parameters

---

src/bindings/python/src/openvino/frontend/pytorch/ts_decoder.py

- *Allow setting kwargs for tracing in TS decoder*
- *This will allow disabling `check_trace` in `optimum-intel`*
- *ticket-id*

[PT FE] Allow setting kwargs for tracing in TS decoder

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *Updated tokenization callback in CPU Plugin to enable dynamic INT8,BF16,FP16 MHA tokenization*
- *Attached the perf validation results to the ticket: 147260*
- *150840*
- *150842*
- *147260*

[Snippets][CPU] Enabled dynamic INT8,BF16,FP16 MHA tokenization

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/dynamic_unfusion.cpp

- Add different rank case in is_valid_fusion() for gemm - eltwise unfusing for below case
- 160213

[GPU] Add different rank case in is_valid_fusion() for gemm - eltwise unfusing

---

src/plugins/intel_cpu/src/nodes/executors/x64/subgraph.cpp

- Fix "Overflowed return value" coverity scan issue: 1566368
- 158073

[CPU] Fix potential integer overflow coverity scan issue in subgraph implementation

---

src/bindings/python/constraints.txt
src/frontends/paddle/tests/requirements.txt

- I can't see any usages of `six` package in the repo (besides docs, but these have their own requirements)
- `six` is a package for compatibility between Python 2 and Python 3
- **Running CI to make sure it's not used anywhere, seems to be a leftover**
- N/A

[PyOV] Remove `six` package

---

docs/notebooks/multilora-image-generation-with-output.rst

- We plan to move this file in GenAI
- Secondly, it should point to releases/2024/6 as on master we support more models

DOCS: updated link to GenAI to point to release 2024.6 branch

---

src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp

- *Correctly ported GenAI logic to extract npu descriptor*
- *N/A*

NPUW: Fix non-NPU execution in the new pipeline

---

src/plugins/intel_npu/src/utils/src/zero/CMakeLists.txt

- To pick up several patches required for OpenVINO

NPU: migrate to v1.20.0 level-zero

---

.github/actions/setup_python/action.yml

Should eliminate:
The `pip cache info` command should display the cache size, no need to use `du`.
- *160388*

[CI] [GHA] Simplify cache info display for `setup-python` action

---

docs/articles_en/learn-openvino/llm_inference_guide/genai-guide-npu.rst
docs/articles_en/openvino-workflow/model-optimization-guide/weight-compression.rst

- *fixed optimum-cli arguments formatting in NPU llm inference guide*
- *updated link for who_what_benchmark* that was moved to tools directory sometime ago

[DOCS] fix typo in npu llm inference guide and update wwb link

---

src/plugins/intel_gpu/tests/unit/fusions/mvn_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/reduce_gpu_test.cpp

Unit-test failed in U24.04 because of wrong reference, unexpected error.
Fix and clean up code. And blocked other unit-tests failure, will be fixed by next PR.
- *158306*

[GPU] Fix wrong reference unit-test case in ubuntu24.04 latest driver.

---

src/plugins/intel_gpu/include/intel_gpu/graph/network.hpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

- When kv cache variable is reset, it is allocating a new memory.
- However, if the variable mem is not changed from previous iteration, we can reuse previsouly allocated memory
- *ticket-id*

[GPU] Reuse kv cache mem if it is not changed from previous infer

---

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/bindings/python/tests/test_runtime/test_properties.py
src/inference/include/openvino/runtime/intel_npu/properties.hpp
src/plugins/intel_npu/README.md
src/plugins/intel_npu/src/al/include/intel_npu/icompiler.hpp
src/plugins/intel_npu/src/common/include/intel_npu/common/icompiler_adapter.hpp
src/plugins/intel_npu/src/compiler_adapter/include/driver_compiler_adapter.hpp
src/plugins/intel_npu/src/compiler_adapter/include/plugin_compiler_adapter.hpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp
src/plugins/intel_npu/src/compiler_adapter/src/plugin_compiler_adapter.cpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_init.hpp
src/plugins/intel_npu/src/utils/src/zero/zero_init.cpp

- extending compiler adapter interfaces with getApiVersion functions
- adding new public read-only property to expose compiler api version
- *EISW-151484*

[intel-npu] Adding new read-only property: NPU_COMPILER_VERSION

---

src/plugins/intel_cpu/src/nodes/string_tensor_pack.cpp
src/plugins/intel_cpu/src/nodes/string_tensor_pack.h
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/string_tensor_pack.cpp
src/plugins/intel_cpu/tests/unit/shape_inference_test/string_tensor_pack_shape_inference_test.cpp
src/plugins/template/tests/functional/op_reference/string_tensor_pack.cpp

- Override the default `isExecutable()` method in `StringTensorPack-15`
- This fixes incorrect packing of empty strings (see reproducer in the ticket)
- CVS-159636

Override the default `isExecutable()` method in `StringTensorPack-15`

---

src/bindings/python/requirements_test.txt
src/bindings/python/tests/test_graph/test_create_op.py
tests/constraints.txt
tests/stress_tests/scripts/requirements.txt
tools/constraints.txt

- Update of `flake8-pytest-style` breaks linters job [here](https://github.com/openvinotoolkit/openvino/pull/28400), so required separate PR
- *ticket-id*

Update reqs: remove fastjsonschema, networkx and new version of flake8-pytest-style

---

src/bindings/python/src/openvino/opset13/ops.py
src/bindings/python/src/pyopenvino/graph/ops/constant.cpp
src/bindings/python/tests/test_graph/test_constant.py

- change `shared_memory` from False to True by default for the case when Const is created from Tensor (to be aligned here with C++ behavior)
- *ticket-id*

[PyOV] Create constant from Tensor with shared_memory

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/convolution_gpu_bfyx_os_iyx_osv16.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp

- From https://github.com/openvinotoolkit/openvino/pull/23621 conv is selecting ref kernel when filter size is large
- Reverted the change in 23621 and instead fixed opt kernel impl not to use manual unroll if the filter size is large 
-  CVS-157998

[GPU] Fix conv kernel to select opt kernel even though filter size is large

---

src/plugins/intel_npu/tests/functional/behavior/infer_request_run.cpp
src/plugins/intel_npu/tests/functional/behavior/remote_tensor_tests/remote_run.cpp
src/plugins/intel_npu/tests/functional/behavior/work_with_devices.cpp
src/plugins/intel_npu/tests/functional/internal/overload/compiled_model/property.cpp
src/plugins/intel_npu/tests/functional/internal/overload/ov_plugin/core_integration.hpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/npu_test_tool.cpp

- Functional tests logs will now only print Error logs instead of Debug and Info
- CVS-160452 [IE-MDK] Cleanup debug error logs

[IE-MDK] Cleanup debug error logs

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/dynamic_quantize_gpu_kv_cache.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/dynamic_quantize_gpu_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_ref.cpp
src/plugins/intel_gpu/tests/unit/test_cases/dynamic_quantize_gpu_test.cpp

- If the inner most dim values of the input are all zero, the issue of scale/zp calculation as inf/nan occurs because min and max_value calculation also becomes zero.
- Fix scale and zp calculation as inf/nan for `dynamic_quantize_gpu_kv_cache`_kernel
- Update accumulator type to prevent overflow for scale/zp calculation for `dynamic_quantize_gpu_ref` kernel
- Fix existing typo for kernels
- 160043

[GPU] Fix scale and zp calculation as inf/nan for dynamic_quantize_gpu_kv_cache kernel

---

src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/arm/matmul_weights_decompression.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/classes/matmul_weights_decompression.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/classes/matmul_weights_decompression.hpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/matmul_weights_decompression.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/subgraph_tests/shared_matmul_weights_decompression.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/subgraph_tests/shared_matmul_weights_decompression.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/shared_matmul_weights_decompression.hpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/weights_decompression_builders.hpp
src/tests/functional/shared_test_classes/src/subgraph/shared_matmul_weights_decompression.cpp
src/tests/functional/shared_test_classes/src/subgraph/weights_decompression_builders.cpp

- This PR fixes accuracy of compressed Matmuls with scalar scale
- The issue was on micro-kernel level: incorrect offset during scales load
oneDNN PR: https://github.com/openvinotoolkit/oneDNN/pull/270
- [CVS-143420](https://jira.devtools.intel.com/browse/CVS-143420)

[CPU] Fixed accuracy of compressed matmul with scalar scale

---

src/plugins/intel_npu/tools/omz_version.json

OMZ versioning is needed for accuracy_checker and Demo build in internal NPU builds and drops 
- *ticket-id*

Add OMZ config for NPU tools

---

src/plugins/intel_npu/src/al/include/intel_npu/npuw_private_properties.hpp
src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.cpp
src/plugins/intel_npu/src/plugin/npuw/compiled_model.cpp
src/plugins/intel_npu/src/plugin/npuw/util.cpp
src/plugins/intel_npu/src/plugin/npuw/util.hpp

Added new possible value for dump options to let NPUW decide which subgraphs need to dump.
With "MIN" option it will dump all non-repeating blocks and just one instance of the repeating block.
- *E-139858*

NPUW: Add new option to dump representative subset

---

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_shape_of_subgraphs.cpp

- False mark shapeof subgraph when shapeof has multiple user
- This is workaround for regression from https://github.com/openvinotoolkit/openvino/pull/27786.
- Partial revert of https://github.com/openvinotoolkit/openvino/pull/27786 for multiple user shapeof case.
- 159953

[GPU] False mark shapeof subgraph when shapeof has multiple user

---

src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/convert_matmul_to_fc.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/matmul_decompress_convert.cpp
src/plugins/intel_cpu/tests/unit/transformations/convert_matmul_test.cpp

- *Previously, if `MatMul` has `transposed_b=false` and decompressed convert on weights, the pass `ConvertMatMulToFC` inserted `Transpose` before this `Convert`. It means that if `Convert` has another consumer (`Result` or even `MatMul` with `transposed=true`), the inserted `Transpose` could break the shapes of `Convert` consumers (please see details in the mentioned ticket).
The current PR inserts `Transpose` after existing `Convert` and updates CPUGraph-pass `FuseFCAndConvertOnWeights`.*
- *160215*

[CPU] Transpose insertion before FC in ConvertMatMulToFC

---

src/plugins/intel_npu/src/compiler_adapter/include/compiler_adapter_factory.hpp

- Fix `Segmentation fault (core dumped)`  issue when running `compile_tool` without a device.
- *E151581*

[NPU] fix segfault in compile_tool

---

src/plugins/intel_npu/src/backend/include/zero_tensor.hpp
src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/backend/src/zero_tensor.cpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.cpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp

- *Hotfix GenAI*
- *Re-create the internal level zero tensor for internal usage if this has already been shared with the user. And do not re-use the shared memory*
- *CVS-160546*

[NPU] Re-create zero tensor for internal usage if it was shared with user

---

src/frontends/pytorch/src/op/permute.cpp
src/frontends/pytorch/src/op_table.cpp
src/frontends/pytorch/src/transforms/listconstruct_replacer.cpp
tests/layer_tests/pytorch_tests/test_permute.py

- *Support negative orders in `aten::permute`*
- *ticket-id*

[PT FE] Support negative orders in aten::permute

---

src/core/src/op/if.cpp
src/core/tests/type_prop/if.cpp

- *if "then" and "else" subgraph output shape are scalar, the  if node output shape should be static and a scalar*
- *...*
- *[28235](https://github.com/openvinotoolkit/openvino/issues/28235)*

Add scalar case if "then" and "else" subgraph output are scalar.

---

docs/articles_en/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.rst
src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/bindings/python/tests/test_runtime/test_properties.py
src/inference/include/openvino/runtime/intel_npu/properties.hpp
src/plugins/intel_npu/README.md
src/plugins/intel_npu/src/al/include/intel_npu/config/compiler.hpp
src/plugins/intel_npu/src/al/include/intel_npu/icompiler.hpp
src/plugins/intel_npu/src/al/src/config/compiler.cpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp
src/plugins/intel_npu/src/plugin/include/metrics.hpp
src/plugins/intel_npu/src/plugin/include/plugin.hpp
src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp
src/plugins/intel_npu/tests/functional/internal/overload/compiled_model/property.cpp

- Adding NPU_DYNAMIC_QUANTIZATION public RW boolean property
- *EISW-148716*

[intel-npu] Adding NPU_DYNAMIC_QUANTIZATION property

---

src/core/include/openvino/op/util/symbolic_info.hpp

All othe headers files in `src/core/include/` all quotes include instead of brackets includes to include `openvino/op/util/symbolic_info.hpp`.
This commit changes the only brackets include to quotes include. This allows user not need to install headers into the system path or need to pollute their system include.

Use quotes include instead of brackets include

---

src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp

- New LLM pipeline compile process happens in two stages, first for generate, second for the prompt parts
- Each of these stages runs a convertBF16toFP16 pass which (on certain models) swaps the BF16 constants with FP16. That is, every stage gets its own personal set of new constants during its compilation
- When generate model finishes its compilation, it routes its tensors to the bank, and after copying those to L0 memory, bank detaches the Constant nodes from the associated LazyTensors.
- Since the newly-added FP16 constants are only referred to the model that is being compiled, they are destroyed immediately, freeing the CPU-side memory.
- When the process is repeated for the 2nd model, it seems that the newly-allocated converted FP16 tensors sometimes get the same addresses as the …

NPUW: Fix BF16 tensor collision in weight bank in new LLM pipeline

---

src/plugins/intel_gpu/include/intel_gpu/runtime/execution_config.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp

- allows to read `ACTIVATIONS_SCALE_FACTOR` from rt_info for non-LLMs, such as FLUX.1 and SDXL.
- assumes that LLMs have `ReadValue` layers and non-LLMs does not.

[GPU] allow to read activations scale factor from rt_info for non-LLMs

---

.github/workflows/build_doc.yml

Old versions of `cache-apt-pkgs-action` used `upload-artifact@v3` action, which is deprecated and going to be disable on January 30.
I wonder why Dependabot didn't do this 🤔

Bump cache-apt-pkgs-action in documentation workflow

---

src/plugins/intel_npu/src/plugin/src/plugin.cpp

- Quickfix for core.get_available_devices exception on hosts with no NPU compiler
- get_available_devices calls get_property(supported_properties), which throws exception if there is no compiler. catching that exception.
- [*CVS-160690*](https://jira.devtools.intel.com/browse/CVS-160690)

[intel-npu]  Quickfix for core.get_available_devices exception on hosts with no NPU compiler

---

src/common/transformations/tests/offline_transformations/pruning_test.cpp
src/core/src/pass/visualize_tree.cpp

Check for dot tool availability in PATH before execution:
- Ensure the Graphviz `dot` tool is installed and accessible in the system PATH before attempting to execute it
- If the dot tool is not found, fail gracefully with a clear error message instead of producing the uninformative output: `sh: 1: dot: not found`
- Make external 'dot' process call only when `ENABLE_OPENVINO_DEBUG` define is on
- Add missing `if (VISUALIZE_TESTS_TREE)` in tests where `VisualizeTree` pass is invoked
- N/A

Check for 'dot' tool presence in PATH before calling in VisualizeTree pass and make it debug only

---

src/plugins/intel_npu/src/plugin/npuw/llm_infer_request.cpp

- *item1*
- *...*
- *ticket-id*

NPUW: LLMInferRequest - not copy kvcache for last generated token

---

src/common/snippets/src/lowered/pass/serialize_data_flow.cpp

Add property to serialized data flow graph to be treated as exec_graph in order to apply type substitution from runtime info
- 160593

[Snippets][CPU] Mark serialized data flow graph as exec_graph

---

src/core/reference/include/openvino/reference/interpolate.hpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- This PR fixes Interpolate reference implementation: missed padding resizing is added. This logic was transferred from [interpolate shape inference implemetation](https://github.com/openvinotoolkit/openvino/blob/master/src/core/shape_inference/include/interpolate_shape_inference.hpp) (for the details, please see `interpolate::resize_padding` implementation and usage).
- [The specification](https://github.com/openvinotoolkit/openvino/blob/master/docs/articles_en/documentation/openvino-ir-format/operation-sets/operation-specs/image/interpolate-4.rst) have no hard limitation that paddings size must be equal to input shape rank
- LPT tests, that were affected by the issue, are reenabled
- *CVS-119648*

[REFERENCE] Fix Interpolate reference implementation

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

Cause is shown in graph below.
The black, green, and dotted line donates the primitive dependency, memory buffer reuse, and memory conflict (at the second iteration) respectively.
The body of the loop is compiled as a separate model and is not aware the data reuse in backedge in multiple iteration.
Tickets:
[CVS-158017](https://jira.devtools.intel.com/browse/CVS-158017)

[GPU] fix memory conflict for multi iteration in loop.

---

tests/model_hub_tests/transformation_tests/models/hf-tiny-random-vl-models-precommit
tests/model_hub_tests/transformation_tests/sdpa2pa_ref_diff.py
tests/requirements_pytorch

Update transformers version to 4.47.1
Update the version of the transformers module to support latest models in precommit testing like katuni4ka/tiny-random-nanollava
Adjust reference values for other models that were affected by the changes in transformers.
Ticket:
*  CVS-157416

Update transformers version to 4.47.1

---

docs/articles_en/openvino-workflow/model-preparation/convert-model-pytorch.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Remove "experimental" note for torch.export

---

.github/workflows/build_doc.yml

The same as https://github.com/openvinotoolkit/openvino/pull/28495 , but for releases/2025/0 branch

Bump cache apt pkgs action in  releases 2025 0

---

src/frontends/pytorch/src/op_table.cpp

- *Support `aten::concatenate`*
- *CVS-160777*

[PT FE] Support aten::concatenate

---

src/plugins/intel_cpu/src/nodes/depth_to_space.cpp
src/plugins/intel_cpu/src/nodes/eye.cpp
src/plugins/intel_cpu/src/nodes/gather.cpp
src/plugins/intel_cpu/src/nodes/gather_elements.cpp
src/plugins/intel_cpu/src/nodes/gather_nd.cpp
src/plugins/intel_cpu/src/nodes/grid_sample.cpp
src/plugins/intel_cpu/src/nodes/interaction.cpp
src/plugins/intel_cpu/src/nodes/mha.cpp
src/plugins/intel_cpu/src/nodes/normalize.cpp
src/plugins/intel_cpu/src/nodes/priorbox.cpp
src/plugins/intel_cpu/src/nodes/space_to_depth.cpp
src/plugins/intel_cpu/src/nodes/split.cpp
src/plugins/intel_cpu/src/nodes/tensoriterator.cpp
src/plugins/intel_cpu/src/nodes/unique.cpp

Replace custom THROW_ERROR macros usage for error reporting in nodes implementation with THROW_CPU_NODE_ERR to unify error handling infrastructure in CPU plugin
- 160275

[CPU] Replace custom THROW_ERROR macros usage with THROW_CPU_NODE_ERR

---

src/common/transformations/src/transformations/sdpa_to_paged_attention/position_ids_replacer.cpp
src/common/transformations/tests/op_conversions/sdpa_to_paged_attention_test.cpp

Qwen-7b-Chat has a decompression if the model is executed in lower
precision resulting into the model having additional Converts (i.e. FP16
to FP32).
Handle this case of optional Convert in PositionIDsReplacerQwen
Added a unit test for it.
- *[CVS-157308](https://jira.devtools.intel.com/browse/CVS-157308)*
Signed-off-by: Ivan Tikhonov <ivan.tikhonov@intel.com>

[TRANSFORMATIONS] SDPAToPagedAttention transformation: support decompression case in the Qwen-7b-Chat pattern

---

src/common/low_precision_transformations/include/low_precision/common/fake_quantize_dequantization.hpp
src/common/low_precision_transformations/include/low_precision/rt_info/quantization_granularity_attribute.hpp
src/common/low_precision_transformations/src/assign_and_read_value.cpp
src/common/low_precision_transformations/src/clamp.cpp
src/common/low_precision_transformations/src/eliminate_fake_quantize.cpp
src/common/low_precision_transformations/src/fake_quantize_dequantization.cpp
src/common/low_precision_transformations/src/markup_quantization_granularity.cpp
src/common/low_precision_transformations/src/network_helper.cpp
src/common/low_precision_transformations/src/pull_reshape_through_dequantization.cpp
src/common/low_precision_transformations/src/pull_transpose_through_dequantization.cpp

- *CVS-1521493*
- *CVS-130703*
- *CVS-121616*
- *CVS-121618*

[LPT] Fix medium static code analyzer issues

---

.github/actions/setup_python/action.yml
.github/workflows/job_build_windows.yml
docs/dev/ci/github_actions/custom_actions.md

[CI] [GHA] Remove `pip cache info` from `setup_python` action

---

.github/workflows/build_doc.yml

Reverts openvinotoolkit/openvino#28354
Original PR is not needed anymore. The culprit was `cache-apt-pkgs-action`, it used `upload-artifact@v3` action which caused the original workflow failure, but now it's fixed https://github.com/awalsh128/cache-apt-pkgs-action/pull/140 and `upload-artifact@v3` will be working till January 30 (https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)

Revert "[GHA] Use upload-artifact with tag in Build Doc"

---

src/common/low_precision_transformations/src/concat.cpp
src/common/low_precision_transformations/tests/concat_transformation.cpp

Currently, `ConcatTransformation` doesn't support DQ propagation if `concat->get_out_partial_shape()[axis}.is_dynamic()`. However, it is theoretically possible to propagate the DQ if all dequantization constants are **scalar and equal**. This PR introduces this support.
- *CVS-160325*

[LPT] ConcatTransformation: support scalar equal DQ propagation through dynamic dimension

---

src/inference/src/os/lin/lin_system_conf.cpp

- *skip HBM numa node on XEON HBM platform*
- *[issues-28335](https://github.com/openvinotoolkit/openvino/issues/28335)*

fix openvino panic when run CPU inference on XEON HBM platform

---

src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/matmul_weights_decompression.cpp

- This PR fixes registers allocation for InnerProduct with dynamic quantization.
- Regressions was introduced with oneDNN 3.6 migration. These changes is needed to restore DQ IP behavior prior the migration.
- oneDNN PR: https://github.com/openvinotoolkit/oneDNN/pull/271
- [CVS-160384](https://jira.devtools.intel.com/browse/CVS-160384)
- [CVS-160733](https://jira.devtools.intel.com/browse/CVS-160733)

[CPU] Fixed FC dynamic quantization accuracy issue

---

src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp
src/plugins/intel_npu/src/backend/include/zero_variable_state.hpp
src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
src/plugins/intel_npu/src/backend/src/zero_variable_state.cpp
src/plugins/intel_npu/src/common/include/intel_npu/common/sync_infer_request.hpp
src/plugins/intel_npu/src/common/include/intel_npu/common/variable_state.hpp
src/plugins/intel_npu/src/common/src/sync_infer_request.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_utils.hpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.cpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp
src/plugins/intel_npu/tests/functional/behavior/remote_tensor_tests/remote_run.cpp
src/plugins/intel_npu/tests/functional/behavior/remote_tensor_tests/remote_run.hpp
src/plugins/intel_npu/tests/functional/common/utils.cpp
src/plugins/intel_npu/tests/functional/common/utils.hpp

Add the last features to the state tensors:
- Update MutableCommandList instead of memcpy if memory was allocated in the same L0 context
- set_shape is available for state tensors as well.
- *CVS-160364*

[NPU] Adding extra features for the state tensors

---

src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/convolution.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/pooling.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/group_convolution.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/convolution.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/convolution.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/pooling.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/x64/softmax.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/conv_concat.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/conv_concat.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/memory_sharing_test.cpp
src/plugins/intel_cpu/tests/functional/utils/convolution_params.hpp

Seems to not worth to verify them considering how slow they are

[CPU][TESTS] Remove sse4 instances from oneDNN related tests

---

src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl
src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp

- This change removes unused PagedAttention inputs that were accidentally added during the rebase of the original PR, which caused a set_arg error in the case of a zero buffer
- Added related test with a dummy activation function to simulate this behavior

[GPU] Remove unused PagedAttention inputs causing set_arg error in case of zero buffer

---

src/core/include/openvino/core/type.hpp
src/core/tests/rtti.cpp

- Used standard dynamic casting under the hood of OV dynamic casting. It drops dependency on OPENVINO_RTTI. Applies to non Android.
- CVS-160749

[RTTI] Use OV dynamic cast on Android only

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/graph/include/kv_cache_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/transformations/op/kv_cache.cpp
src/plugins/intel_gpu/tests/common/subgraphs_builders.hpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache_sdpa.cpp

- This change restores the original logic of axis calculation for scales/zp and fixes the shape inference of KV-Cache operation. Previously, it needed to be adjusted with concat_axis, but after the introduction of independent macros for key and value scale/zp offsets calculation in micro_sdpa kernel, this adjustment is no longer needed and causes incorrect indexing. Therefore, this change reverts to the original fixed scale/zp axis equal to 2.

[GPU] Fix compressed KV-cache shape infer for QKV order {1,2,0,3}

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *The second inference in LLM is usually single token inference. It means that `M` dimension of MatMuls in SDPA pattern will have the value `1` (during compilation model this dimension is dynamic (unknown)). Snippets cannot provide efficient execution for single token inference. So we decided to disable MHA tokenization by Snippets in CPU Plugin on LLMs'.  We consider the presence of `ScaledDotProductAttentionWithKVCache` op in the model as a sign that this model is LLM.*
- *Cherry-picked from https://github.com/openvinotoolkit/openvino/pull/28601*
- *160634*
- *160978 (contains performance validation results)*

[Snippets][CPU][Port to 2025.0] Disable MHA tokenization in LLM

---

tests/requirements_pytorch

- Ported https://github.com/openvinotoolkit/openvino/pull/28627
- We can see here https://github.com/openvinotoolkit/openvino/pull/28630, that releases/2025/0 is affected as well.

Pin triton version

---

src/plugins/intel_gpu/thirdparty/CMakeLists.txt

- oneDNN headers incorrectly use `_MSVC_LANG` w/o any checks that platform is Windows
- CVS-161069

GPU: fixed debug build on non-Windows

---

src/plugins/intel_npu/src/backend/include/zero_remote_tensor.hpp
src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
src/plugins/intel_npu/src/backend/src/zero_remote_tensor.cpp
src/plugins/intel_npu/src/backend/src/zero_variable_state.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_utils.hpp

- *Get remote tensors info from methods and not through properties to avoid CPU overhead*
- *CVS-160977*

[NPU] Get remote tensors info from methods and not through properties to avoid CPU overhead

---

src/plugins/intel_gpu/include/intel_gpu/runtime/execution_config.hpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache_sdpa.cpp

- Set default precision of kv cache as fp16 to match inference precision
- Update logic which handles multiple apply_user_properties() call for same object to skip everything if config is already finalized.
- For platforms with xmx support set `kv_cache_precision` as `inference_precision` to provide correct property query result

[GPU] Changed default value for kv cache precision

---

src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp

- Fix synchronization in PagedAttention operation when KV-cache rotation is enabled but skipped for the current iteration.
Previously, `dep_events` was always replaced with `res_events` if `has_rotated_blocks=true`, leading to empty events vector being passed to the next kernels and causing accuracy deviations in cases of out_of_order queue due to missing synchronization
- PR to master: https://github.com/openvinotoolkit/openvino/pull/28645

[GPU] Fix kernels synchronization in PagedAttention operation

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *The second inference in LLM is usually single token inference. It means that `M` dimension of MatMuls in SDPA pattern will have the value `1` (during compilation model this dimension is dynamic (unknown)). Snippets cannot provide efficient execution for single token inference. So we decided to disable MHA tokenization by Snippets in CPU Plugin on LLMs'.  We consider the presence of `ScaledDotProductAttentionWithKVCache` op in the model as a sign that this model is LLM.*
- *160634*
- *160978*

[Snippets][CPU] Disable MHA tokenization in LLM

---

src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp
src/common/transformations/tests/common_optimizations/fuse_rotary_positional_embeddings.cpp
src/plugins/intel_cpu/src/nodes/rope.cpp

Update RopeFusion for gpt-j models
- *CVS-161066*

Update RopeFusion to support gpt-j model after SDPA to PA conversion

---

src/plugins/intel_cpu/src/dnnl_postops_composer.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer.h
src/plugins/intel_cpu/src/graph_context.cpp
src/plugins/intel_cpu/src/nodes/common/cpu_convert.cpp
src/plugins/intel_cpu/src/nodes/executors/mlas/mlas_gemm.cpp
src/plugins/intel_cpu/src/nodes/random_uniform.cpp
src/plugins/intel_cpu/src/nodes/rnn.h
src/plugins/intel_cpu/src/nodes/roi_pooling.cpp

Fix medium severity issues in CPU plugin reported by coverity tool
- Logically dead code: 1590308
- Uninitialized pointer field: 1590284
- Uninitialized scalar field: 1567790, 1590248
- Missing break in switch: 1568687, 1568688
- Result is not floating-point: 1568461
- Unintentional integer overflow: 1568371, 1568372, 1568374
- Macro compares unsigned to 0: 1567805
- 160879

[CPU] Fix medium coverity issues

---

.github/workflows/debian_10_arm.yml
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/custom_op_insert_convert_i64.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/src/behavior/ov_plugin/caching_tests.cpp

- Enable running CPU unit tests on Debian ARM 32 bit
- Disable all failing tests
- Fix tests that ignore test skip mechanism
- 153289

[CPU] Enable Debian 10 ARM tests

---

src/plugins/intel_gpu/src/plugin/compiled_model.cpp

- kv_cache_precision hint was missing in the list of supported_properties for compiled model impl while get_property call actually worked.
- *CVS-161323*

[GPU] Added missing kv_cache_precision property to supported list

---

src/plugins/intel_npu/src/compiler_adapter/include/driver_compiler_adapter.hpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_init.hpp
src/plugins/intel_npu/src/utils/src/zero/zero_init.cpp

- *FEIL/FIL was increased with https://github.com/openvinotoolkit/openvino/pull/28314. Querying compiler properties forces UMD to load the compiler DLL. To optimize the memory consumption UMD will also unload the the compiler DLL.*
- *By reusing graph properties in the compiler adapter we remove one (load + read + unload) cycle from FEIL/FIL*
-  *Rename private member names to _compiler_properties_: even if we use a common graph ext API to query graph properties we only store ZE_STRUCTURE_TYPE_DEVICE_GRAPH_PROPERTIES - which are compiler properties.*
- *CVS-161294*

Use graph properties from ZeroInitStruct in compiler adapter

---

tests/requirements_pytorch

Backporting https://github.com/openvinotoolkit/openvino/pull/28627 because releases/2024/6 is also affected https://github.com/openvinotoolkit/openvino/actions/runs/13008272704/job/36281346446

Pin triton version (#28627)

---

src/bindings/python/src/openvino/preprocess/torchvision/requirements.txt

Old dependencies started to cause issues after Torch 2.6.0 got released

More strict dependencies for PyTorch in torchvision preprocess

---

docs/articles_en/about-openvino/compatibility-and-support/supported-models-onnx.rst
docs/sphinx_setup/_static/download/supported_models.csv
docs/sphinx_setup/_static/download/supported_models_onnx.csv

port: https://github.com/openvinotoolkit/openvino/pull/28693

[DOCS] hidden page for ONNX supported models

---

samples/python/benchmark/bert_benchmark/README.md
samples/python/benchmark/bert_benchmark/bert_benchmark.py
samples/python/benchmark/sync_benchmark/README.md
samples/python/benchmark/sync_benchmark/sync_benchmark.py
samples/python/benchmark/throughput_benchmark/README.md
samples/python/benchmark/throughput_benchmark/throughput_benchmark.py

- Change `get_version()` to `__version__`
- Discussed [here](https://github.com/openvinotoolkit/openvino/pull/28341#discussion_r1908609241)
- [CVS-160332](https://jira.devtools.intel.com/browse/CVS-160332)

[Py OV] Update samples to use __version__ instead of get_version()

---

src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/utils/debug_capabilities.h

The logic was reverted due to the issues with making all the nodes
executable in some scenarious.
The problem is that without this functionality debug capabilities became
less usable.
So bring back the logic and try to cover problematic scenarios,
i.e. static nodes with empty shapes, which should never be executed
even with debug caps.

[CPU][DEBUG_CAPS] Bring back an execution of all nodes for debug caps

---

src/bindings/python/src/openvino/preprocess/torchvision/requirements.txt

Backport of https://github.com/openvinotoolkit/openvino/pull/28722

Backport to 2025.0 - More strict dependencies for PyTorch in torchvision preprocess

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/low_precision_transformations/x64/fq_with_dq_not_optimal_transformation.cpp

[CPU][LPT] Removed legacy PrecisionRestriction limitations for Multiply

---

src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm_copy_b.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm_copy_b.hpp

- *BrgemmCopyBKernel is JIT compiled kernel which emits blocking loop by `N` dimension with binary call of the kernel `dnnl::x64::brgemm_copy_b_kernel` inside. Currently, we spill all registers before the each call of this kernel. It means that if the dimension `N` is quite big, there will be many binary calls and reg spills. These regular reg spills may lead to perf degradation for Subgraphs with small `M`, `K,`  and big `N` dimensions. This PR uses feature of binary call optimizations - spills only live registers*
- *N/A*

[Snippets][CPU] Optimized reg spills in BrgemmCopyBKernel

---

.github/workflows/merge_queue_stub.yml
.github/workflows/windows_vs2019_release.yml
.github/workflows/workflows_scans.yml

This PR adds an additional job to `workflow_scans` workflow to scan GitHub Actions Workflows themselves using CodeQL

Add CodeQL scans to GitHub Actions Workflows

---

src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp

- This change fixes incorrect broadcast axis calculation for static SDPA operations (dynamic case wasn't affected because the only static dimensions were head_size and heads_num, which allowed the proper setting of broadcast axis)
- [CVS-160643](https://jira.devtools.intel.com/browse/CVS-160643)

[GPU] Fix incorrect broadcast axis for static SDPA case

---

.github/workflows/build_doc.yml

Old versions of `cache-apt-pkgs-action` used `upload-artifact@v3` action, which is deprecated and going to be disable on January 30.

Bump cache-apt-pkgs-action in documentation workflow (#28495)

---

src/common/transformations/tests/op_conversions/sdpa_to_paged_attention_test.cpp
src/core/src/pass/sdpa_to_paged_attention.cpp

VLMs have tokens and their generation already served as the "inputs_embeds" input, so there's no need to transform the input in the way this is done for "input_ids".
Tickets:
* [CVS-160598](https://github.com/CuriousPanCake/openvino/tree/CVS-160598)

Fix support of "inputs_embeds" input of VLMs in SDPAToPA transformation

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/fake_quantize_decomposition_test.cpp
src/tests/functional/plugin/shared/src/snippets/fake_quantize_decomposition_test.cpp

- **Enabled tests for FakeQuantizeDecomposition** in `src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp`
- **Enabled FakeQuantize op tokenization** by adding it in `is_supported_op` in `transformation_pipeline.cpp`
- Updated `FakeQuantizeDecompositionTest::SetUp()`, replaced MaxPool ops (`makePrerequisitesOriginal()`) with empty vector due to outdated limitations in Snippets, to support the operation in AArch64 platforms. 
-  Adjusted expected node counts in tests since `reorder` ops are missed in AArch64 platforms and disabled `legacyFuse` tests for non-x64 platforms.
Passed local tests
- Closes #28508

[CPU][ARM64] Enable FakeQuantize tokenization and decomposition

---

src/plugins/intel_cpu/src/dnnl_extension_utils.cpp
src/plugins/intel_cpu/src/dnnl_extension_utils.h
src/plugins/intel_cpu/src/utils/verbose.cpp

Not all the ov types are supported in oneDNN. This fact leads to an exception being thrown if the CPU graph contains tensors of such data types.
This PR enables verbose mode to dump such tensor descriptors.
N/A

[CPU][DEBUG_CAPS] Enable verbose mode for ov data types

---

src/common/transformations/include/transformations/common_optimizations/activations_scaling.hpp
src/common/transformations/src/transformations/common_optimizations/activations_scaling.cpp
src/common/transformations/tests/common_optimizations/activations_scaling_test.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- follow-up task of https://github.com/openvinotoolkit/openvino/pull/28350
- updates to use `ConcatTransformation` of LPT instead of custom `MulConcatTransformation`

[GPU] updates to use ConcatTransformation of LPT for activations scaling

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/fusions/gemm_fusion_test.cpp

- allows fusion of scalar eltwise layers with gemm to prevent unfusion for some LLMs
- 161678

[GPU] allow scalar eltwise primitive fusion with gemm

---

src/plugins/intel_gpu/src/graph/paged_attention.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl
src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp

- Under certain circumstances `pa_sdpa_opt` kernel should be able to handle dynamic paddings for query input, so this change modifies query index calculation calls
- Update PA layout calculation, removing padding unintentionally reused from the query input for the output layout
- Add related tests

[GPU] Dynamic paddings support for mixed kernel mode execution of PagedAttention

---

src/plugins/intel_gpu/src/graph/impls/ocl/crop.cpp
src/plugins/intel_gpu/tests/unit/test_cases/crop_gpu_test.cpp

- This change fixes the issue with incorrect `runtime_offset` calculation when the crop can't be optimized out
- Added related tests

[GPU] Fix crop primitive execution with dynamic paddings input

---

src/plugins/intel_gpu/src/graph/impls/onednn/concatenation_onednn.cpp

- *Insert scratchpad memory in concat when it's not null*
- *159065*

[GPU] Insert scratchpad memory in concat when it's not null

---

.github/workflows/build_doc.yml
.github/workflows/job_cpu_functional_tests.yml
.github/workflows/ovc.yml
.github/workflows/windows_conditional_compilation.yml
.github/workflows/windows_vs2019_release.yml

4.1.2 is not v4 enough (?): https://github.com/openvinotoolkit/openvino/actions/runs/13141204138/job/36668972865

[GHA] Bump actions/cache to 4.2.0

---

cmake/developer_package/compile_flags/os_flags.cmake
src/cmake/ov_parallel.cmake
src/plugins/intel_gpu/src/graph/CMakeLists.txt
src/plugins/intel_gpu/src/runtime/CMakeLists.txt

- Ported https://github.com/openvinotoolkit/openvino/pull/28816

CMAKE: fixed GPU plugin build within vcpkg infra

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_micro.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp

- Add support of per-head attention mask for sdpa_micro kernel, as some models have different mask configurations for each head
- CVS-161777
- Closes https://github.com/openvinotoolkit/openvino/issues/28445

[GPU] Add support of per-head mask for sdpa_micro kernel

---

src/bindings/js/node/package-lock.json
src/bindings/js/node/package.json

- Bump OV nodejs recipe to 2025.0.0 version

[OV JS] Update openvino-node package version to 2025.0.0

---

src/frontends/onnx/frontend/include/openvino/frontend/onnx/node_context.hpp
src/frontends/onnx/frontend/src/node_context.cpp

- Added a get_name() method's implementation for onnx::NodeContext to be more compatible with other FrontEnds
- N/A

[ONNX] Extended NodeContext interface

---

src/frontends/pytorch/src/op_table.cpp

- Revert of #27909  as benchmark job has confirmed the reasons behind the performance degradation is not related to this fix.
- 158719

[Torch frontend] aten._unsafe_index.Tensor support

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- Fix default return value in snippets callback on unhandled type (disable if the type is not explicitly supported)
- Fix check for 8 bit integer values (handle both signed and unsigned)
- 160487

[Snippets][CPU] Fix int8 handling and disable snippets for unhandled types in callbacks

---

src/plugins/intel_cpu/src/node.cpp
src/plugins/intel_cpu/src/nodes/common/cpu_convert.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/conversion.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/conversion.hpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/instances/common/conversion.cpp

- This PR adds FP32/BF16/FP16 to NF4 support for Convert op in CPU Plugin
-  
- [CVS-153213](https://jira.devtools.intel.com/browse/CVS-153213)

[CPU] Enabled float (fp32/fp16/bf16) to nf4 precision conversion

---

src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected_primitive.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/matmul_weights_decompression.cpp

- Enables FC dynamic quantization on systems with AVX2 ISA
- Speed-ups for LLMs with asym compressions on LNL vs master: 2x in average for prompt processing and 1.5x in average for generation stage. 
- OneDNN fork PR: https://github.com/openvinotoolkit/oneDNN/pull/272
- [CVS-146064](https://jira.devtools.intel.com/browse/CVS-146064) <- perf numbers
- [CVS-134037](https://jira.devtools.intel.com/browse/CVS-134037)
- [CVS-134034](https://jira.devtools.intel.com/browse/CVS-134034)

[CPU] Optimize DQ FC with stack allocated aux accum registers

---

src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp

- *In the int8 model, if the batch size of the FC layer is 1025 (which is aligned to 1040), the FC layer can't use SLM because 1040 is not aligned to 64. The reason for this misalignment is that 64 alignment is only applied for i4 weights in the fake alignment function.*
- *Modified to allow 64 alignment for i8/u8 weights to use SLM for 1045 batch size.*
- *161596*

[GPU] support 64 alignment for 8bit weights layout

---

src/plugins/intel_cpu/src/nodes/composite.cpp
src/plugins/intel_cpu/src/nodes/concat.cpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/fake_quantize.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/gather.cpp
src/plugins/intel_cpu/src/nodes/if.cpp
src/plugins/intel_cpu/src/nodes/lora.cpp
src/plugins/intel_cpu/src/nodes/matmul.cpp
src/plugins/intel_cpu/src/nodes/memory.cpp
src/plugins/intel_cpu/src/nodes/paged_attn.cpp
src/plugins/intel_cpu/src/nodes/qkv_proj.cpp
src/plugins/intel_cpu/src/nodes/rope.cpp
src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
src/plugins/intel_cpu/src/nodes/scatter_update.cpp
src/plugins/intel_cpu/src/nodes/shapeof.cpp
src/plugins/intel_cpu/src/nodes/split.cpp
src/plugins/intel_cpu/src/nodes/tensoriterator.cpp

- Replace custom OPENVINO_ASSERT macros usage for error reporting in nodes implementation with CPU_NODE_ASSERT
- Add assertion message where it is missing
- 160275

[CPU] Replace OPENVINO_ASSERT macros usage in nodes with CPU_NODE_ASSERT

---

src/plugins/intel_npu/src/plugin/include/metadata.hpp
src/plugins/intel_npu/src/plugin/src/metadata.cpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp

- a flaw has been noticed in the current code. The compatibility check skip won't work if the blob contains no NPU metadata. Therefore, I moved the skip inside plugin.cpp.
- none

[NPU] Move compatibility check skip before reading metadata

---

.github/workflows/job_build_linux.yml
src/bindings/python/src/openvino/preprocess/torchvision/requirements.txt

Trying to get more information about git clone hangs in Fedora 29 workflow
- *160901*

Enable GIT_TRACE for clone step in Fedora 29 workflow

---

src/common/snippets/src/lowered/linear_ir.cpp

Fix input and output ports replacement when expression is being replaced by another one in linear IR.
In some cases replacement can produce incorrect (bigger) amount of ports
- N/A

[Snippets][CPU] Fix loop ports replacement in LIR

---

src/bindings/python/src/pyopenvino/core/tensor.cpp
src/bindings/python/tests/test_runtime/test_tensor.py

Add support of `deepcopy()` and `copy()` for ov.Tensor Python API
`copy()` returns a shallow copy, `deepcopy()` a new object with its own data buffer
161969

[PYTHON] add __deepcopy__, __copy__ for Tensor

---

src/common/snippets/include/snippets/lowered/linear_ir.hpp
src/common/snippets/include/snippets/op/subgraph.hpp
src/common/snippets/include/snippets/utils/linear_ir_pass_dumper.hpp
src/common/snippets/src/lowered/pass/insert_perf_count_verbose.cpp
src/common/snippets/src/op/subgraph.cpp
src/plugins/intel_cpu/src/nodes/subgraph.cpp

Disable verbose performance count logging only when `OV_SNIPPETS_DUMP_BRGEMM_PARAMS` environment variable is set
- N/A

[Snippets][CPU] Enable verbose perf count insertion pass conditionally

---

src/plugins/intel_cpu/src/nodes/kernels/x64/brgemm_kernel.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- fix the copy_a init in brgemm: https://github.com/oneapi-src/oneDNN/commit/59513f7c211e6c7d36ebe5ebc10dff2ebc221fef
- relax the rnn tests
test onednn branch is https://github.com/openvinotoolkit/oneDNN/tree/xiuchuan/dev-v3.6
but without permission of pushing cherry-pick commits to branch https://github.com/openvinotoolkit/oneDNN/tree/v3.6_for_ie_master
oneDNN fork PR: https://github.com/openvinotoolkit/oneDNN/pull/273

[CPU] oneDNN3.6 cherry-pick backports

---

src/common/snippets/CMakeLists.txt
src/common/snippets/include/snippets/kernel_executor_table.hpp
src/plugins/intel_cpu/CMakeLists.txt
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/fc_bias_fusion.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/x64/pass/mlp_fusion.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/x64/pass/qkv_proj_fusion.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/eliminate_brgemm_copy_b.cpp
src/plugins/intel_cpu/src/transformations/tpp/x64/pass/brgemm_to_brgemm_tpp.cpp
src/plugins/intel_cpu/src/transformations/tpp/x64/pass/eltwise_to_eltwise_tpp.cpp
src/plugins/intel_cpu/src/transformations/tpp/x64/pass/scalar_to_scalar_tpp.cpp

- Fix deprecated warnings related to implicit `this` capturing in lambdas
- Remove `-Wno-error=deprecated` from CXX flags for Intel CPU plugin and common snippets directories
- N/A

[Snippets][CPU] Remove deprecation warnings ignore

---

src/common/transformations/tests/op_conversions/sdpa_to_paged_attention_test.cpp
src/core/src/pass/sdpa_to_paged_attention.cpp

VLMs working in the Continuous Batching mode with PA take "inputs_embeds" input in the following shape: [batch_size_in_tokens, hidden_size]
Adjust the model to take the input in the described shape and handle the input properly to make it consistent with the other parts of the transformation and model.

[TRANSFORMATIONS] Set proper of VLM's "inputs_embeds" input

---

src/common/low_precision_transformations/tests/mark_dequantization_subgraph_transformation.cpp
src/common/transformations/include/transformations/low_precision/mark_dequantization_subgraph.hpp
src/common/transformations/src/transformations/low_precision/mark_dequantization_subgraph.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

The MarkDequantization transformation finds and marks nodes of a certain subgraph as dequantization nodes, enable/disable constant folding for some nodes and swaps nodes in the Convert -> Reshape to allow for Constant folding.
However, in some cases the Convert may have more than one consumer. In these cases the swapping is not always possible as this may break the consistency of the graph.
Allow for swapping only in cases when we are sure it's not going to break the consistency of the graph.
Make KeepConstPrecision to handle more patterns not seen before.
Tickets:
* CVS-161437

[LPT TRANSFORMATIONS] Enable MarkDequantization & KeepConstPrecision to process more complex patterns

---

src/plugins/intel_gpu/src/plugin/transformations/increase_position_ids_precision.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- Input precisions of some layers could be different from inference precision.
- `IncreasePositionIdsPrecision` updates some `MatMul` layers to be executed in f32 precision.
- other examples: hybrid-quantized models, precision sensitive layers, and so on.
- Activations scaling should not be applied to these cases.
- in the case of f32, we don't need activations scaling.
- in the case of int8, we can't apply activations scaling.
- So. this PR updates the activations scaling to be applied only to layers whose 1st input precision is the same as infer precision.
- 161681

[GPU] applying activations scaling only to layers whose 1st input precision is the same as infer precision.

---

src/plugins/intel_npu/src/common/include/intel_npu/common/igraph.hpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_graph.cpp
src/plugins/intel_npu/src/compiler_adapter/src/plugin_graph.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_api.hpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_init.hpp
src/plugins/intel_npu/src/utils/src/zero/zero_api.cpp
src/plugins/intel_npu/src/utils/src/zero/zero_init.cpp

- *In the case of a static CORE object, it will be destroyed after the application exits. In this case, the libs will be detached in the reverse order of how they were created. We need to make sure that the 'ze_loader' lib is alive and to understand if the context was already destroyed by detaching the lib or not*
- *E#150895*

[NPU] If context is already destroyed it will not return success

---

src/plugins/intel_cpu/src/emitters/plugin/x64/jit_load_store_emitters.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *avx512 target should use evex encoded instructions in load store emitters, which could work with 16-31 vmms. The index is assigned by AssignRegisters*
- *The most instructions could be both vex encoded and evex encoded. If ymm index is in [16,31], it will be [automatically identified](https://github.com/openvinotoolkit/oneDNN/blob/157fb8153d8c54cf37311d95a63ed63e66b14ac5/src/cpu/x64/xbyak/xbyak.h#L670-L671), and [evex encoded](https://github.com/openvinotoolkit/oneDNN/blob/157fb8153d8c54cf37311d95a63ed63e66b14ac5/src/cpu/x64/xbyak/xbyak.h#L2535-L2536)*
- *For instructions only work with vex encode, such as vinsertf128 and vmovdqu, use equivalent instructions that support evex encode, such as vinsertf32x4 and vmovdqu16, on avx512 target*
- *CVS-160737*

[CPU]avx512 target use evex encoded instructions in load store emitters

---

src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_f_y_axes.cpp
src/plugins/intel_gpu/tests/unit/test_cases/permute_gpu_test.cpp

- After prepare_primitive_fusing, if static node has fused nodes which has dynamic shape, then requireKey for the static node should contain the key for the dynamic shape.
- 113414

[GPU] Check if fused op has dynamic shape in GetParamsKey()

---

src/plugins/intel_cpu/src/nodes/kernels/x64/mlp_kernel.cpp
src/plugins/intel_cpu/src/nodes/kernels/x64/mlp_kernel.hpp
src/plugins/intel_cpu/src/nodes/qkv_proj.cpp

- *MSVC on win32 platform has x64 calling conversion different from Linux, this change added a fix to jit kernel to support win32 system*
- 
- *CVS-151107*

[CPU] fix qkv_proj/mlp jit kernel's win32 support

---

src/inference/dev_api/openvino/runtime/threading/thread_local.hpp

Fix ARM 32-bit build with `-DENABLE_DEBUG_CAPS=ON` CMake configuration flag. Make `ThreadLocal` class implementation copyable where TBB threading is not enabled. Original `tbb::enumerable_thread_specific<T>` has copyable interface.
- N/A

Make custom ThreadLocal implementation copyable

---

src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/executors/aarch64/jit_eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/eltwise.cpp

- Implemented and added jit_squared_difference_emitter derived class for element wise squared difference operation
- Added entry Algorithm::EltwiseSquaredDifference, in executors/aarch64 as one of the supported algorithms
- Added entry in the get_supported_precisions and create_eltwise_emitters in kernel/aarch64
- Added `utils::EltwiseTypes::SQUARED_DIFF` in `jit` kernel check in the tests
Passed local tests using `./bin/arm64/Release/ov_cpu_func_tests --gtest_filter="*smoke*Eltwise*SqDiff*"`
- Closes #27502 
CC:
@a-sidorova

[CPU][ARM64] Implemented JIT Emitter for Eltwise Squared Difference Operation

---

src/core/src/runtime/itensor.cpp
src/core/tests/ov_tensor_test.cpp
src/plugins/intel_npu/tests/functional/behavior/remote_tensor_tests/remote_run.hpp

- *If data is a contiguous memory area, return true*
- *Strides can be different and data can still be contiguous in memory. Extra checks are needed in this case*
- *E#156237*

[CORE] Fix tensor is_continuous method 

---

src/common/transformations/tests/op_conversions/scaled_dot_product_decomposition_test.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

Fix failing clang-format in pre-commit
- N/A

[Transformations] Hotfix for clang-format remarks

---

src/plugins/hetero/tests/functional/CMakeLists.txt

Fix dependencies issue when hetero tests dependent on CPU and GPU plugins fail if ov_hetero_func_tests are built as the only target:
```bash
$ cmake -S . -B build -DENABLE_TESTS=ON
$ make -j$(nproc) ov_hetero_func_tests
```
- N/A

[HETERO] Add CPU and GPU plugins to tests dependencies if exists

---

src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm_copy_b.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/external_repacking_adjuster.cpp

- Fix coverity issues related to insecure data handling (overflowed integer argument) with CID 1591120 and 1591118
- CVS-162505

[Snippets][CPU] Fix overflowed integer argument coverity issues

---

.github/workflows/linux_sanitizers.yml

- *CPU func. tests added to ASAN workflow*
- *Func. and Unit. scopes divided into 2 matrices.*
- *Inputs added for ASAN type and test filters (Default behavior doesn't change)*
- *149629*

[GHA] CPU sanitizers for functional tests.

---

.github/dependency_review.yml

Update of whitelist for dependency checker.
Required for PR:  https://github.com/openvinotoolkit/openvino/pull/28349

License whitelist for dependency checker update

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl

- Use FP32 accumulator for QK multiplication for 2nd+ token calculation in PagedAttention
- TODO: Evaluate performance impact of this change
- [CVS-162692](https://jira.devtools.intel.com/browse/CVS-162692)

[GPU] Use FP32 accumulator for QK multiplication for 2nd+ token calculation in PagedAttention

---

src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
src/plugins/intel_gpu/tests/unit/shape_infer/broadcast_si_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/broadcast_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/deconvolution_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/depth_to_space_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/dynamic_quantize_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/eltwise_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gather_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/permute_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/pooling_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/reorder_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/reshape_gpu_test.cpp

- (refer to GSD-10054) Not to use usm_host for large output buffer in BMG
- Perf check done 
- After this PR, MiniCPM 2.6V first token latency reduced to 1/2
- CVS-161158

[GPU] Use usm_device for output buffer for BMG

---

src/core/src/type/float8_e4m3.cpp
src/core/tests/float8_e4m3.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/conversion.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *Implement reference conversion from fp16 to f8e4m3, and apply 2-step conversion, i.e., apply fp32->fp16, then fp16->fp8 for conversions from fp32 to fp8.*
- *[CVS-160375](https://jira.devtools.intel.com/browse/CVS-160375)*

Implement 2-step conversion from fp32 to fp8

---

src/frontends/onnx/frontend/src/op/com.microsoft/matmulnbits.cpp

This PR is doing some optimization work on onnxfrontend com.microsoft.MatMulNbits operators
with this changes:
1. it disabled const folding with use 75GB for phi3 INT4 model and 200+GB for llama3 INT4 model.
2. it trigger oneDNN matmul primitives, much benefits the GPU performance
we tested this changes along with another PR #28163 , and confirmed phi3/llama3 INT4 model run well in LNL.

optimize com.microsoft.MatMulNbits operator

---

src/common/util/include/openvino/util/common_util.hpp
src/common/util/src/common_util.cpp
src/core/reference/src/op/convert.cpp
src/core/src/runtime/compute_hash.cpp

- *Some customers can set policy ProcessDynamicCodePolicy to prohibit dynamic code. So need to disable JIT in such cases.*
- *162440*

[CORE][CACHE][HASH] DYNAMIC_CODE_POLICY check on Windows

---

src/common/util/include/openvino/util/file_util.hpp

Make an additional conversion from std::string to std::wstring at uv::util::to_file_path function when OPENVINO_ENABLE_UNICODE_PATH_SUPPORT was set
Tickets:
[162461](https://jira.devtools.intel.com/browse/CVS-162461)
[146659](https://jira.devtools.intel.com/browse/CVS-146659)

[CORE] Make an additional conversion from std::string to std::wstring

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp

+ Add reorder to change input format from blocked to plain for dGPU to select onednn kernel for gemm.
- *162459*

[GPU] Add input reorder for onednn gemm

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/permute_f_y_axes.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_f_y_axes.cpp
src/plugins/intel_gpu/tests/unit/fusions/permute_fusion_test.cpp

Implicit casting error when different input and output data type.
Use in_type instead of out_type during FUSED_OPS_VEC.
- *160534*

[GPU] Fix resmlp-12-distilled-224 failure.

---

src/plugins/intel_cpu/src/graph.cpp

By utilizing the fact, that the base edge is always the first edge in the cluster.
This helps to avoid unnecessary looping when updating the referencing edges.
Also allocated dynamic output edges before the regions are created, so there is no need to create those regions and then removed them anyway.

[CPU] Simplify edge clusters collection procedure

---

.github/dependency_review.yml

Reverts openvinotoolkit/openvino#29031 because it introduced sporadic failures (e.g.: https://github.com/openvinotoolkit/openvino/actions/runs/13432909164/job/37528579365?pr=29086) 
The licenses whitelist should not contain AND expressions (see https://github.com/actions/dependency-review-action/issues/842)

Revert "License whitelist for dependency checker update"

---

src/frontends/pytorch/src/op/index.cpp
src/frontends/pytorch/src/op/masked_scatter.cpp
src/frontends/pytorch/src/transforms/aten_index_put_replacer.cpp
src/frontends/pytorch/src/transforms/aten_index_replacer.cpp
src/frontends/pytorch/src/utils.cpp

- *Return default NonZero type where possible. This allows to merge two NonZero nodes.*
- *CVS-160578*

[PT FE] Return default NonZero type where possible

---

src/bindings/python/src/openvino/__init__.py
src/bindings/python/src/openvino/package_utils.py
tools/benchmark_tool/openvino/__init__.py
tools/ovc/openvino/__init__.py

- In current approach for lazy import, we use `importlib.util.LazyLoader`. This approach first creates a module, adds it to python `sys.module`s, and then LazyLoader executes the module when sb tries to access e.g. `openvino.runtime` attribute.
- The issue is that in this approach `openvino.runtime` might be initialized too early, e.g. by [`inspect` module](https://github.com/python/cpython/blob/140e69c4a878d7a0a26d4406bdad55e56ddae0b7/Lib/inspect.py#L915) which iterates over modules present in `sys.modules`, e.g.:
Proposal: 
- Change the lazy loading approach. Import `openvino.runtime` and add it to `sys.modules` only when an attribute is accessed. Possible thanks to overloading `__getattr__` and `__dir__` methods. 
- *ticket-id*

[Py OV] Change approach to openvino.runtime lazy loading

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl

- In the current `fc_bf_tiled_forced_tile_b` kernel, when `TILE_OFM=1`, `acc_tmp` becomes a one-dimensional array rather than two-dimensional array that process vector type, so issue may occur in the process of obtaining `acc` from `acc_tmp` and initializing `acc_tmp`
- Fix this issued case for `fc_bf_tilied_forced_tile_b` kernel
- 162831

[GPU] Fix boundary case for fc_bf_tiled_forced_tile_b kernel

---

src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/executor_pa.cpp

- *Fix avx2 of int8 kvcache incorrect output for PagedAttention*
- *...*
- *[161786](https://jira.devtools.intel.com/browse/CVS-161786)*

[CPU] Fix avx2 of int8 kvcache incorrect output for PagedAttention

---

docs/dev/index.md

**Details:** Correct a link with supported devices

[DOCS] Correct a link with supported devices

---

src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/convert_range.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *there are some test case skipped in CVS-129703 https://github.com/openvinotoolkit/openvino/pull/22339 when enable ov_cpu_function_test on SPR*
- *move left bf16 test case to CVS-157596*
- *move left fp16 test case to CVS-143852*
- *CVS-130463*
- *CVS-130466*
- *CVS-130467*
- *CVS-130473*
- *CVS-130471*

[CPU] do with the left skipped tests of enabling CPU funtion test on SPR

---

src/plugins/intel_npu/src/plugin/src/compiled_model.cpp

- *Add `cpu_reset` in `intel_npu::CompiledModel::dtor`*
- *E158043*

[intel_npu] Compiled model destructor was not reseting pinned cores from CPU

---

src/core/include/openvino/core/type.hpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_kernel_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_kernel_emitter.cpp
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/dft.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/pooling.cpp
src/plugins/intel_cpu/src/nodes/strided_slice.cpp
src/plugins/intel_cpu/src/shape_inference/shape_inference.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/stateful_sdpa_fusion.cpp
src/plugins/intel_cpu/src/transformations/snippets/aarch64/pass/snippets_mark_skipped.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
src/plugins/intel_cpu/src/transformations/tpp/x64/op/eltwise.cpp
src/plugins/intel_cpu/src/transformations/tpp/x64/pass/fuse_tpp_to_equations.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/src/transformations/utils.cpp

- Add `ov::is_type_any_of` that chains `ov::is_type` calls for better code readability
- Reuse new function for applicable cases in CPU plugin
- N/A

[CPU] Introduce ov::is_type_any_of for chaining ov::is_type calls

---

src/plugins/intel_cpu/src/cpu_memory.cpp
src/plugins/intel_cpu/src/cpu_memory.h
src/plugins/intel_cpu/src/dnnl_postops_composer.cpp
src/plugins/intel_cpu/src/emitters/plugin/x64/jit_bf16_emitters.hpp
src/plugins/intel_cpu/src/graph.cpp
src/plugins/intel_cpu/src/memory_state.cpp
src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/input.cpp
src/plugins/intel_cpu/src/nodes/kernels/jit_eltwise_common.hpp
src/plugins/intel_cpu/src/nodes/kernels/x64/jit_uni_eltwise_generic.cpp
src/plugins/intel_cpu/src/nodes/kernels/x64/jit_uni_eltwise_generic.hpp
src/plugins/intel_cpu/src/nodes/memory.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/bf16_convert_saturation.cpp
src/plugins/intel_cpu/tests/unit/cpu_tensor_test.cpp

- *bf16 constant saturation during model compilation stage to fix the 'inf'/'nan' out issue when using bf16 inferencePrecision*
- *CVS-159589*

[CPU] bf16 constant saturation during model compilation stage

---

src/common/transformations/include/transformations/utils/utils.hpp
src/common/transformations/src/transformations/utils/utils.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp

- *Extracted `is_LLM` check from GPU plugin to common part to reuse in other plugins*
- *Used extracted `is_large_language_model` function in check for LLM in MHATokenization in CPU Plugin*
- *CVS-160999*

[Snippets][CPU] Added KVCacheMatcher check for LLM in MHATokenization

---

src/plugins/intel_gpu/src/graph/program.cpp

- Add SDPA to white list for fsv16 so that fsv16 format is available for the nodes in the model, that will increase performance.
- 160317

[GPU] Add sdpa to white list for fsv16

---

src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_common.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp

[GPU] Remove force exit

---

src/plugins/intel_gpu/src/graph/CMakeLists.txt
src/plugins/intel_gpu/src/graph/impls/cm/CMakeLists.txt
src/plugins/intel_gpu/src/graph/impls/common/CMakeLists.txt
src/plugins/intel_gpu/src/graph/impls/cpu/CMakeLists.txt
src/plugins/intel_gpu/src/graph/impls/ocl/CMakeLists.txt
src/plugins/intel_gpu/src/graph/impls/onednn/CMakeLists.txt
src/plugins/intel_gpu/src/graph/impls/sycl/CMakeLists.txt

- Use `macro` instead of `function` to omit ROOT argument setting for each backend
- Added BYPASS argument which handles all args not processed by `ov_gpu_add_backend_target` to avoid any multi-value args parsing issues

[GPU] macro instead of function and bypass arg

---

src/core/include/openvino/core/graph_util.hpp
src/core/include/openvino/pass/serialize.hpp
src/core/tests/file_util.cpp
src/core/tests/frontend/frontend_manager.cpp
src/core/tests/pass/serialization/deterministicity.cpp
src/core/tests/pass/serialization/serialize.cpp
src/frontends/common/include/openvino/frontend/frontend.hpp
src/frontends/tests/frontend/shared/src/conversion.cpp
src/inference/include/openvino/runtime/core.hpp
src/inference/tests/functional/ov_core_test.cpp
src/inference/tests/functional/ov_extension_test.cpp

Clean up redundant macro after switch to C++17 standard by default
- N/A

Remove OPENVINO_CPP_VER_AT_LEAST_17 macro usage

---

src/bindings/python/tests/test_runtime/test_async_infer_request.py
src/bindings/python/tests/test_runtime/test_sync_infer_request.py
src/bindings/python/tests/test_utils/test_data_dispatch.py

- From https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword:
> For any __array__ method on a non-NumPy array-like object, dtype=None and copy=None keywords must be added to the signature - this will work with older NumPy versions as well
- *ticket-id*

[PyOV] Fix deprecation warnings from numpy in tests

---

.github/workflows/workflow_rerunner.yml

Try to fix parsing issue:
https://github.com/openvinotoolkit/openvino/actions
```
Encountered an issue parsing workflow trigger(s) "linux (ubuntu 22.04, python 3.11, intel dpc++ compiler)" in a workflow ".github/workflows/workflow_rerunner.yml".
```
Escape `\\+\\+` the same way as in https://github.com/openvinotoolkit/openvino/blob/master/.github/workflows/export_workflow_metrics.yml#L18

[GHA] Fix parsing special characters

---

src/plugins/intel_npu/tools/protopipe/README.md
src/plugins/intel_npu/tools/protopipe/src/parser/config.cpp

- *Fixed parse of 'metric' and 'random' entries when they are specified for all layers*
- *They are always presented as maps, so `convert<LayerVariantAttr<T>>` should be extended to check if they passed as maps of maps*
- *ticket-id*

[Protopipe] Fixed parse of 'metric' and 'random' entries when they are specified for all layers

---

src/plugins/intel_gpu/src/runtime/execution_config.cpp

- 'RMS' does not work correctly for static layers when input rank is smaller than 4.
- closes #29017, #29113

[GPU] fixing RMS for static layers

---

src/common/transformations/src/transformations/op_conversions/fake_convert_decomposition.cpp
src/common/transformations/tests/op_conversions/fake_convert_decomposition_test.cpp
src/core/reference/include/openvino/reference/fake_convert.hpp
src/core/reference/src/op/fake_convert.cpp
src/core/src/type/float8_e5m2.cpp
src/core/tests/eval.cpp
src/core/tests/float8_e5m2.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/shared_test_classes/src/single_op/fake_convert.cpp

- *Ngraph FakeConvert layer applies clamp for f8 (f8e4m3 applies clamp, f8e5m2 partially applies clamp), while ngraph Convert layer doesn't apply clamp. So the idea is to add Clamp layer in FakeConvertDecomposition to assure the clamp behavior of FakeConvert is still included for plugins after decomposition.*
- *Ngraph reference emulate_f8e4m3_on_fp16 applies clamp for  overflowed value as well as for NaN(f8e4m3 does not have INF in Specification). However, it seems emulate_f8e5m2_on_fp16 only applies clamp for overflowed value (by the flag can_round), but not for INF. To align behavior between f8e4m3 and f8e5m2, clamp for INF is added in emulate_f8e5m2_on_fp16.*
- *Test cases are added to reproduce the issue beforehand.*
- *[CVS-160719](https://jira.devtools.intel.com/browse/CVS-160719)* …

[CPU] Add Clamp for FakeConvertDecomposition

---

src/common/transformations/src/transformations/op_conversions/convert_gather_to_compressed.cpp
src/common/transformations/tests/op_conversions/convert_gather_to_compressed_test.cpp

- fix ConvertGatherToGatherCompressed to use Output explicitly instead of implicit conversion from Node
- add unit test
- 159389
- 138242

[TRANSFORMATIONS] Fix ConvertGatherToGatherCompressed to use Output explicitly instead of implicit conversion from Node

---

src/common/transformations/src/transformations/common_optimizations/activations_scaling.cpp
src/common/transformations/tests/common_optimizations/activations_scaling_test.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- scales down epsilon values of RMS, MVN and GroupNormalization layers to improve accuracy.
- updates not to apply activations scaling to layers marked as `decompressed_to_f32`.
- 161987

[GPU] improving accuracy of activations scaling

---

.github/workflows/job_pytorch_layer_tests.yml
src/bindings/python/src/openvino/frontend/pytorch/fx_decoder.py
src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/decompositions.py
tests/layer_tests/pytorch_tests/test_arange.py
tests/layer_tests/pytorch_tests/test_trilu.py
tests/requirements_pytorch
tools/ovc/openvino/tools/ovc/moc_frontend/pytorch_frontend_utils.py

- *Support `torch==2.6.0`*
- *CVS-162009*

[PT FE] Support torch==2.6.0

---

docs/articles_en/get-started/learn-openvino/openvino-samples/benchmark-tool.rst
samples/cpp/benchmark_app/main.cpp
tests/samples_tests/smoke_tests/test_benchmark_app.py
tools/benchmark_tool/openvino/tools/benchmark/main.py

- Report memory usage for `ov::Core::compile_model`/`ov::Core::import_model` methods
- E#157655

Add "Load model ram used (KB)" metric for BAPP

---

src/plugins/intel_cpu/src/utils/node_dumper.h

- Create directory specified in `OV_CPU_BLOB_DUMP_DIR` environment variable if blob dumping debug capability is enabled
- N/A

[CPU][DEBUG_CAPS] Create directory for input/output blobs automatically

---

src/plugins/intel_cpu/src/graph_dumper.cpp
src/plugins/intel_cpu/src/utils/ngraph_transformation.hpp
src/plugins/intel_cpu/src/utils/platform.h

Disable exec graph ".bin" file dump when execution graph is being dump. This file is redundant, because execution graph does not provide any binaries.
- N/A

[CPU][DEBUG_CAPS] Disable .bin file dump on exec graph serialization

---

src/common/transformations/src/transformations/common_optimizations/convert_pagedattn_inputs.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *Fix conflict between CommonOptimizations and ConvertPagedAttnInputs*
- *Move ConvertPagedAttnInputs after CommonOptimizations*
- *CVS-163373*

[CPU]Fix conflict between CommonOptimizations and ConvertPagedAttnInputs

---

.gitmodules

- ARM's gitlab is less stable than github, so it's more robust to fetch KleiaiAI from github

[CPU][ARM] Change KleidiAI repo source

---

samples/cpp/benchmark_app/main.cpp
tests/samples_tests/smoke_tests/test_benchmark_app.py
tools/benchmark_tool/openvino/tools/benchmark/main.py

The description of the PR and the fix for python are taken here:
https://github.com/openvinotoolkit/openvino/pull/29238
Faulty PR: https://github.com/openvinotoolkit/openvino/pull/28931
- macos samples tests are failing after https://github.com/openvinotoolkit/openvino/pull/28931 was merged (there is no "/proc/self/status" on macos)
Example failed jobs:
- https://github.com/openvinotoolkit/openvino/actions/runs/13620712150/job/38072447907
- https://github.com/openvinotoolkit/openvino/actions/runs/13620737535/job/38071526701
- CVS-163441

Fix mem_peak_usage on macos

---

src/plugins/intel_gpu/include/intel_gpu/runtime/device_info.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/kernel_base_opencl.cpp
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp

- Seems that result of this query is not used for a long time, so removing that completely to accelerate model loading time.

[GPU] Removed local_block_io queries as those are not used

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/gemm_tiled_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp
src/plugins/intel_gpu/tests/unit/fusions/gemm_fusion_test.cpp

Revert some earlier PR 28252 and PR 28764.  These PR causing memory increase as well as 2X performance drop. 
Instead to fix the issue primitive_inst, update gemm_kernel_tiled_opt kernel to convert to use fuse with scalar for innermost broadcasting.
Remove unit test from PR 28252 as that is not valid use case. …

[GPU] Update gemm_tiled_opt dynamic support

---

.github/workflows/debian_10_arm.yml
.github/workflows/job_cpu_functional_tests.yml
.github/workflows/linux_arm64.yml
.github/workflows/mac.yml
.github/workflows/mac_arm64.yml
.github/workflows/ubuntu_22.yml
src/plugins/intel_cpu/tests/functional/custom/extension/extension.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/compiled_model/cpu_reservation_test.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *smoke filter for nightly cpu func. test removed*
- *161534*

[GHA] [CPU] Extend nightly scope for CPU func. tests

---

src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp

- Use sdpa config for shape agnostic kernel assuming that the Seq len is > 64
- Perf check done for BMG/LNL/DG2 
- LNL:
- DG2 
- BMG
- (Currently there is perf issue when attn_mask is used.
Since PA uses causal mask, there is no perf issue.
Once perf issue w.r.t the attn_mask is resolved, we can apply this change for non-PA case too)
-  CVS-163029

[GPU] Improve micro_sdpa perf for PA case

---

src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.hpp

- skip because looks more optimal to run yolov12 on ocl
- adbc transpose out format not fused to matmul in onednn src/plugins/intel_gpu/thirdparty/onednn_gpu/src/graph/backend/dnnl/passes/transform.cpp:3891 tells about it
- without it assert fail on src\plugins\intel_gpu\src\graph\impls\onednn\gemm_onednn.cpp:202
- 163418

[GPU] skip onednn impl when transpose out has bxfy format 

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp

Compressed onednn FC with eltwise 4D and quantize u8 caused accuracy problem. Current FC always uses 2Dim output tensor and if FC has 4D eltwise in post-op, eltwise should be 2D in case onednn ocl:gemm_with_po.
- *157491*

[GPU] Fix SD1.5 hybrid accuracy issue.

---

src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm_copy_b.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_utils.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_utils.hpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/eliminate_brgemm_copy_b.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/expressions/brgemm_copy_b_buffer_expressions.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/external_repacking_adjuster.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/external_repacking_adjuster.hpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *Currently, if `MatMul` has `transposed_b=true`, this attribute is extracted from `MatMul` as the separate op `Transpose`. The PR enables the processing `transposed_b=true* via `BrgemmCopyB` to avoid extra ops in Graph`*
- *Fixed seg fault in `i8i8 MatMuls` with `transposed_b=true` on platforms without AMX instructions (scenario with compensations) - there were not-initialized attributes in `brgemm_config` which were interpreted as `true` (incorrect behavior). The PR initializes them with `False` values*
- *The performance results are attached to the ticket 161514*
- *161514*
- *148527*

[Snippets][CPU]Process transposed_b=true of MatMuls via BrgemmCopyB

---

src/common/transformations/include/transformations/common_optimizations/convert_pagedattn_inputs.hpp
src/common/transformations/src/transformations/common_optimizations/convert_pagedattn_inputs.cpp
src/common/transformations/tests/common_optimizations/convert_pagedattn_inputs.cpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp
src/plugins/intel_gpu/src/graph/paged_attention.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_kv_cache_rotate_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_kv_cache_update_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_rotate_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_rotate_kernel_ref.h
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_update_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp

- Enabled INT8_ASYM KV-cache compression for PagedAttention
- Improved `pa_sdpa_opt` kernel with `scale_factor` to increase bandwidth utilization for compressed KV-cache
- Updated kv_cache_update kernel to perform data quantization
- Updated kv_cache_rotate kernel to rotate compressed cache (performing: Dequantization -> Rotation -> Quantization)
- Enabled ConvertPagedAttnInputs transformation pass to allow plugin to configure PA inputs directly
- Added related PA unit tests
- Minor fixes of sdpa_micro to reject the kernel in case of unsupported sliding windows

[GPU] Enable KV-cache compression in PagedAttention OCL kernel

---

cmake/developer_package/packaging/npm.cmake

- Required for GenAI JS API as GenAI will depend on C API after https://github.com/openvinotoolkit/openvino.genai/pull/1778

CPACK: added C API component to JS component

---

src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
src/plugins/intel_cpu/src/nodes/fullyconnected.h
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/classes/matmul_weights_decompression.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/matmul_weights_decompression.cpp

- *For fp8 LLM, we have compilation time overheads due to slow ngraph constant folding. Here we disable constant folding for Convert + Multiply + MatMul pattern on fp8 LLM through MarkDequantization pass to improve compilation time.*
- *[CVS-160147](https://jira.devtools.intel.com/browse/CVS-160147)*

[CPU] Improve compilation time of fp8 LLM

---

src/plugins/intel_cpu/src/cpu_memory.cpp
src/plugins/intel_cpu/tests/unit/dnnl_memory_test.cpp

dnnl::memory created with an empty dnnl::memory_desc is not empty.
Default constructor should be used instead.
Adjust rest of memory logic to allow an empty dnnl::memory object

[CPU] Fix empty memory creation

---

src/plugins/intel_npu/tools/compile_tool/main.cpp

fix the minor typo in the compile_tool help message, from "-ionl" to "-ioml".

intel_npu: compile_tool: fix typo in help message

---

.github/workflows/debian_10_arm.yml
.github/workflows/job_cpu_functional_tests.yml
.github/workflows/linux_arm64.yml
.github/workflows/mac.yml
.github/workflows/mac_arm64.yml
.github/workflows/ubuntu_22.yml
src/plugins/intel_cpu/tests/functional/custom/extension/extension.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/compiled_model/cpu_reservation_test.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

Reverts openvinotoolkit/openvino#28751
After this PR was merged CPU Functional Tests job lasts for a few seconds because all the tests are filtered out

Revert "[GHA] [CPU] Extend nightly scope for CPU func. tests"

---

.github/actions/store_artifacts/store_artifacts.py

Quick fix for latest links overwrites from tokenizers, e.g. https://github.com/openvinotoolkit/openvino.genai/actions/runs/13773578761/job/38517620256?pr=1880

[GHA] Update latest artifacts link from openvino builds only

---

src/core/src/op/constant.cpp
src/core/tests/pass/serialization/const_compression.cpp

- That is simplified fix for #29329, just to fix the particular issue with empty constant in PA transformation
- Need to be reverted when #29329 is merged
- CVS-162291

Set allocated for empty constant byte to zero

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- *After enabling Continuous Batching, the order of dimensions in the shape has changed ({1, b..} -> {b, 1..}) and is no longer consistent for fusion check, which led to a significant performance drop*

[GPU] Relaxing check for valid fusion in OneDNN case

---

src/plugins/intel_npu/tools/compile_tool/CMakeLists.txt
src/plugins/intel_npu/tools/protopipe/CMakeLists.txt
src/plugins/intel_npu/tools/single-image-test/CMakeLists.txt
tests/time_tests/CMakeLists.txt

- There is a customer's requirement to build NPU package with statically linked MS RT.
- `CMAKE_MSVC_RUNTIME_LIBRARY` is supported since 3.15
- E-159926

Bump Cmake min version for npu tools & time tests

---

src/plugins/intel_cpu/src/.clang-tidy
src/plugins/intel_cpu/src/nodes/kernels/x64/jit_kernel.hpp

Remove bugprone suppression of any kinds of exceptions in `if_expression` destructor and `make_shared` call for registers in jit_kernel.h
- N/A

[CPU] Remove empty catch blocks in jit_kernel.h

---

cmake/developer_package/compile_flags/sanitizer.cmake

clang (including clang-tidy) does not have support for `-fno-var-tracking-assignments` flag. When build with sanitizer is enabled along with clang-tidy it leads to compilation error.
- N/A

Do not use -fno-var-tracking-assignments flag for sanitizer build if clang-tidy is enabled

---

tests/layer_tests/pytorch_tests/test_norm.py

- *Skip RMSNorm tests on older torch*
- *CVS-163922*

[TESTS] Skip RMSNorm tests on older torch

---

src/core/src/preprocess/pre_post_process.cpp
src/core/tests/preprocess.cpp

In specific cases of Gelu pattern, Mul(input, const(0.5)) might be fused to Conv weights, the pattern can't be detected after that.
We have to add Gelu to the preprocessing transformation pipeline.
- *CVS-163672*

Add GeluFusion to PreProcessing transformations pipeline

---

src/plugins/intel_gpu/src/plugin/transformations/optimize_subsequent_reshapes.cpp
src/plugins/intel_gpu/tests/unit/transformations/optimize_subsequent_reshapes_test.cpp

- Extend OptimizeSubsequentReshapes pass to support any cases with a single dynamic dimension. This allows to optimize two subsequent Reshape nodes and propagate properly dynamic padding, preventing explicit Reshape execution (and runtime static kernel compilation) and improving performance. This change fixes chatglm-3 model performance for CB pipeline 
- [CVS-162284](https://jira.devtools.intel.com/browse/CVS-162284)

[GPU] Extend OptimizeSubsequentReshapes pass to support any cases with a single dynamic dimension

---

src/common/transformations/src/transformations/symbolic_transformations/dereshape_matmul.cpp
src/common/transformations/src/transformations/transpose_sinking/ts_slice.cpp
src/core/src/bound_evaluate.cpp

- *Current rt_info propagation function doesn't do what it says it should do. And it works in a predictably bad manner.*
- *DeepSeek R1 related: CVS-162883,CVS-164161*

[SI] Removes unpredictable rt_info copying from partial value propagation

---

src/plugins/intel_gpu/src/graph/graph_optimizer/mark_shape_of_subgraphs.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp

- Extend shape_of subgraphs markup logic to include PagedAttention's `max_context_len` input
- This patch fixes qwen-7b-chat performance issue, which is caused by the fact that it relies on `max_context_len` data input which is treated as "ShapeOf" subgraph data source. Considering that it isn't used anywhere except PagedAttention itself as a direct input, or some simple shape-flow calculations, add such input and its users to ShapeOf-subgraph as well. Otherwise, such subgraphs are calculated on GPU, introducing runtime synchronization and significantly dropping performance.
Qwen model:
Qwen-2 model:
- [CVS-164134](https://jira.devtools.intel.com/browse/CVS-164134)

[GPU] Extend shape_of subgraphs markup logic to include PagedAttention input

---

src/plugins/intel_npu/tests/functional/CMakeLists.txt
src/plugins/intel_npu/tests/functional/common/npu_test_env_cfg.cpp
src/plugins/intel_npu/tests/functional/common/npu_test_env_cfg.hpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests.xml
src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- Adds a mechanism to load and parse an xml file containing all test skips
- Defines skip enabling "rules": a user can select if a skip is applied depending on OS, Platform number or Backend type
- Rules are optional. Users can negate a rule by using "!" and they can add as many rules as needed
- Skip filters and rules are grouped in the following format:
```
<skip_config>
<message> Provide reason why these tests are skipped </message>
<enable_rules> <-- rules section starts here -->
<backend>LEVEL0</backend>
<backend>IMD</backend>
<backend></backend>  (empty backend)
<device>3720</device>
<device>4000</device>
<operating_system>windows</operating_system>
<operating_system>linux</operating_system>
</enable_rules>
<filters> <-- skip filters section starts here -->
<filter>skip this test …
```

[NPU][IE-MDK] Load testing skip config at runtime

---

src/plugins/intel_cpu/src/.clang-tidy
src/plugins/intel_cpu/src/emitters/snippets/cpu_kernel_executor_table.hpp
src/plugins/intel_cpu/src/memory_state.h
src/plugins/intel_cpu/src/nodes/input.cpp
src/plugins/intel_cpu/src/nodes/memory.hpp
src/plugins/intel_cpu/src/shape_inference/shape_inference_cpu.hpp

- allow using "override" and "final" keywords at the same time in clang-tidy checks
- remove NOLINTs that can be avoided
- N/A

[CPU] Remove redundant NOLINT comments

---

src/core/src/op/constant.cpp

- *Skip Constant data copy during partial value propagation*
- *DeepSeek R1 related: CVS-162883,CVS-164161*

Skip Constant data copy during partial value propagation

---

src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp
src/common/transformations/tests/common_optimizations/fuse_rotary_positional_embeddings.cpp

RoPEFusionChatGLM pattern on GPU uses a Constant as a stop value for StridedSlice instead of a subgraph as on CPU. Cover this is pattern.
- [CVS-164016](https://jira.devtools.intel.com/browse/CVS-164016)

[TRANSFORMATIONS] Fix RoPEFusion pattern for GLM4 model on GPU

---

src/plugins/intel_gpu/src/graph/input_layout.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/update_shape_test.cpp

- Fix shape infer optimziation of shape_of subgraphs in case of data input usage
- After extending shape_of subgraphs in PR https://github.com/openvinotoolkit/openvino/pull/29445 some of the new subgraphs' shapes were not recalculated between iterations because of the assumption that the shape of the shape_of subgraph root hadn't changed. However, in case of data inputs, we have to recalculate shape_of subgraphs at each iteration because the data input value might change even if the shape itself remains unchanged
- [CVS-164246](https://jira.devtools.intel.com/browse/CVS-164246)

[GPU] Fix shape infer optimziation of shape_of subgraphs in case of data input usage

---

src/frontends/pytorch/src/op/add.cpp
src/frontends/pytorch/src/op/sub.cpp
tests/layer_tests/py_frontend_tests/test_torch_frontend.py

**Details:** Fix aten::add decomposition for i4 weights
Cherry-pick of https://github.com/openvinotoolkit/openvino/pull/29511
**Ticket:** 164397

[PT] Fix aten::add decomposition for i4 weights

---

src/plugins/intel_cpu/src/cache/multi_cache.h
src/plugins/intel_cpu/src/graph.cpp

Remove old branches of code that depends on `__cplusplus` macro
- `std::result_of` is deprecated in C++17 and removed in C++20
- `std::memory_order_*` is directly accessible in the std namespace as enum fields as well. It is the correct way for both C++17 and C++20
- N/A

[CPU] Remove code supporting only C++17 standard and older

---

samples/cpp/benchmark_app/inputs_filling.cpp

Support for random fill (`-i random`) for `bf16` type input tensors in the model.
- N/A

Add support for bf16 random input filling in benchmark_app

---

src/inference/src/dev/core_impl.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp

[CORE] Add MODEL_PTR to config only if plugin supports it

---

src/plugins/intel_gpu/include/intel_gpu/runtime/memory.hpp
src/plugins/intel_gpu/tests/unit/module_tests/usm_memory_test.cpp

- Use src buffer size for copy_to() call when called for two cldnn::memory objects
- Simplified backport of https://github.com/openvinotoolkit/openvino/pull/29534
- [CVS-164403](https://jira.devtools.intel.com/browse/CVS-164403)

[GPU] Use src buffer size for copy_to() call when called for two cldnn::memory objects

---

src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
src/common/transformations/tests/common_optimizations/nop_elimination.cpp

Make EliminateConcatStridedSlice transformation more strict, add an additional concat axis check.
Fixed the compile_model regression on GPU.
- CVS-164273

[Pass][EliminateConcatStridedSlice] Add issue fix for pass EliminateConcatStridedSlice

---

src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp

- Increasing npu compiler support version for NPU_QDQ_OPTIMIZATION property to 7.20
- *ticket-id*

[intel-npu] Increasing qdq_optimization's compiler support version

---

cmake/developer_package/features.cmake

- Enable clang-tidy by default on platforms where it is verified on CI (x86 only for now) to prevent build errors
- N/A

Make clang-tidy build enabled by default on x86 only

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/tests/unit/fusions/gemm_fusion_test.cpp

This reverts commit c202882011202b4731b0bb7254c18cececc071ba
- *Reverts due to perf regression*
- *[CVS-164331](https://jira.devtools.intel.com/browse/CVS-164331)*

Revert "[GPU] Enable fusing dynamic eltwise with gemm in onednn case"

---

src/common/transformations/src/transformations/common_optimizations/activations_scaling.cpp

- The `EliminateScalarMul` pass eliminates scalar multiplication layers before normalization layers. But
- if 0 < activations scale factor < 1, epsilon value of normalization becomes large.
- if activations scale factor < 0, the output of normalization layers is different.
- 164333

[GPU] not to apply EliminateScalarMul for scalar const less than 1

---

src/plugins/intel_npu/src/plugin/src/compiled_model.cpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_threading_tests.cpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests.xml
src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *Fix conformance tests by returning a dummy model in case of get_runtime_model method*
- *Reduce the number of iterations for core threading tests and change the config for caching*
- *CVS-161541*

[NPU] Return a dummy model in case of get_runtime_model method

---

src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp

- *The PR https://github.com/openvinotoolkit/openvino/pull/29564 added `LeakyRelu` op for testing. Since `LeakyRelu` is supported by JIT kernel on RV64, the CPU tests should return `jit` in such cases.*
```
qemu-riscv64 -cpu rv64,x-v=true,vext_spec=v1.0  ./bin/riscv64/Release/ov_cpu_func_tests_subset --gtest_filter='*LeakyRelu*' 
....
[==========] 252 tests from 5 test suites ran. (25422 ms total)
[  PASSED  ] 252 tests.
```
- *N/A*

[RV64] Fixed LeakyRelu CPU tests

---

src/plugins/intel_gpu/CMakeLists.txt
src/plugins/intel_gpu/src/kernel_selector/kernel_base_opencl.cpp

... and pass `-cl-std=3.0` to OpenCL C compilation when CL_TARGET_OPENCL_VERSION >= 300. This enables running OpenVINO on PoCL without `POCL_IGNORE_CL_STD=1` environment variable (except perhaps for parts that use kernels from `src/plugins/intel_gpu/thirdparty/onednn_gpu` submodule).

[GPU] Set CL_TARGET_OPENCL_VERSION=300 as default

---

src/common/snippets/src/utils/debug_caps_config.cpp
src/plugins/intel_cpu/src/utils/debug_caps_config.h

Fix parser failure on multiple spaces in debug caps env var options
- N/A

[CPU][DEBUG_CAPS] Skip empty options in property groups

---

src/inference/include/openvino/runtime/properties.hpp
src/inference/src/dev/core_impl.cpp
src/inference/src/dev/core_impl.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/data.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp

- The `ov::hint::model` stores shared pointer to constant `ov::Model`
- CVS-164473

[core] Make const ov::Model in hint::model property

---

src/common/snippets/src/lowered/pass/insert_perf_count.cpp
src/common/snippets/src/op/perf_count.cpp
src/common/snippets/src/op/subgraph.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/cpu_generator.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_perf_count_chrono_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_perf_count_chrono_emitters.hpp

- *Added missed dumping in `InsertPerfCount` and copy of dumpers in `PerfCountEnd::clone_with_new_inputs()`.*
- *Added only live register spills in JIT emitters of perf counters to avoid extra overheads*
- *N/A*

[Snippets][CPU] Fixed and Improvements for PerfCounters

---

src/common/transformations/src/transformations/common_optimizations/gelu_fusion.cpp
src/common/transformations/tests/common_optimizations/gelu_fusion.cpp

In the GeluFusionWithErfTwo transformation "input" may appear to be a VariadicSplit node with multiple outputs. Using the default output of the node is incorrect and leads to an exception if used as an input to another node because of an implicit conversion to ov::Output. Use the output of the VariadicSplit node explicitly to avoid the exception.
- [CVS-164465](https://jira.devtools.intel.com/browse/CVS-164465)

[TRANSFORMATIONS] Fix implicit conversion of ov::Node with multiple outputs to ov::Output

---

src/tests/test_utils/functional_test_utils/layer_tests_summary/run_parallel.py

- Set unsuccessful exit code run_parallel.py if no tests are found
- *CVS-163981*

[GHA] Fail if there are no tests in the suite

---

src/bindings/python/src/pyopenvino/utils/utils.cpp
src/bindings/python/tests/test_runtime/test_model.py

- Cause: `openvino_tokenizers` Python object  `constants.UTF8ReplaceMode`, which inherits from python `enum.Enum`, is set on C++ `openvino.Model` using `model.set_rt_info()`. It fails when GIL is released in `model.compile_model()`
- Fix: Use `std::shared_ptr` to properly manage python object reference lifetime on C++ side.
- Accordind to [docs](https://docs.python.org/3/library/enum.html#module-contents) `Enum` is "Base class for creating enumerated constants."
- What may need discussion? 
- <s>I added the fix to `py_object_to_any()`/`from_ov_any()` methods. Maybe it should be narrowed specifically to `model.set_rt_info()` and `model.get_rt_info()`</s>
To reproduce use openvino in Debug mode:
```python
model = generate_add_model()
from enum import Enum
class EnumInfo(Enum):
INFO_A: str = …
```

[Py OV] Core().compile_model(tokenizer, "CPU") fails

---

src/common/snippets/src/lowered/pass/init_live_ranges.cpp

Fix skipped register type assignment for  in `InitLiveRanges` pass for expressions that don't affect lifetime of registers (list is defined in `pass_through_expr` function of this pass)
- N/A

[Snippets] Fix register type assignment for pass through expressions

---

src/common/snippets/include/snippets/pass/split_dimension_m.hpp
src/common/snippets/src/pass/split_dimension_m.cpp
src/common/snippets/tests/src/pass/mha_tokenization.cpp
src/tests/ov_helpers/ov_snippets_models/src/subgraph_mha.cpp

- *Fixed handling of `Parameters` with 1D shapes in `SplitDimensionM` pass. No need to insert `Reshape` op on input with 1D shape since `M` dimension has index `1` from the end.*
- *149846*

[Snippets] Fixed handling of `Parameters` with 1D shapes in `SplitDimensionM` pass

---

src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/adjust_brgemm_copy_b_loop_ports.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_cpu_blocking.cpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/lowered/brgemm_blocking.cpp

- *Enabled N, K blocking for MatMul FP32 with transposed_b=true*
- *Fixed `AdjustBrgemmCopyBLoopPorts` for the case FP32 `Brgemm` with `repacking`*
- *164966*

[Snippets][CPU] Enabled N, K blocking for MatMul FP32 with transposed_b=true

---

src/plugins/intel_gpu/src/plugin/transformations/clamp_fp16_output.cpp
src/plugins/intel_gpu/src/plugin/transformations/clamp_fp16_output.hpp
src/plugins/intel_gpu/tests/unit/transformations/clamp_fp16_output_test.cpp

- Extend `ClampFP16Output` pass to add clamp primitive between `Add` and `RMS` operation which is targeting language model in VLM models which may have an fp16 overflow on Add output tensor which could lead to Inf Value and affecting the result of RMS 
- 164349

[GPU] Extend ClampFP16Output pass to support clippling input for RMS

---

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

- Since PR(https://github.com/openvinotoolkit/openvino/pull/29061), even if the network is dynamic, if user tensor's shape is static, remote tensor can be set as plugin's output tensor, and output prim reuse remote tensor's memory
- However, even though it is remote tensor use case, there is a possibility that the user output tensor will be reallocated to the predicted shape by shape predictor
- Therefore this code block has been updated to not perform shape prediction in remote tensor use case
- 163470

[GPU] Fix clEnqueueCopyBuffer error in RemoteTensor use case

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/passes/add_onednn_optimization_attributes_test.cpp
src/plugins/intel_gpu/tests/unit/passes/reorder_inputs_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/depth_concatenate_gpu_test.cpp

- get_target_output_format was checking wrong output port index
- insert_reorders_in_dir was skipping based on fmt_map. But fmt_map may not be up-to-date.
- It did not happen so far because it happens only when new_shape_infer is enabled and the node has reshape as a sibling.
- 163143

[GPU] reorder_inputs fixed

---

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

-   https://github.com/openvinotoolkit/openvino/pull/29795 to release branch 
- Allow different output mem size with actual node size when user tenso is set and the port is remote
- Fix crash in the wwb vlm test for phi-3.5 vision model
- *ticket-id*

[GPU] Fix crash on set_output_memory due to shape difference b/w actual shape & user tensor 

---

src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp

- Allow different output mem size with actual node size when user tenso is set and the port is remote
- Fix crash in the wwb vlm test for phi-3.5 vision model
- *ticket-id*

[GPU] Fix crash on set_output_memory due to shape difference b/w actual shape & user tensor

---

src/plugins/intel_npu/src/al/include/intel_npu/config/common.hpp

- *Update `INFERENCE_PRECISION_HINT` supported values f16, i8 for NPU* 
- *[C#163813](https://jira.devtools.intel.com/browse/CVS-163813)*

[NPU] Remove unsupported `f32` from `INFERENCE_PRECISION_HINT`

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp

- blocked fusing condition conv+prelu
- CVS-163143

Resolve accuracy issue from fusing prelu

---

src/plugins/intel_gpu/src/graph/gemm.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/gemm.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/gemm_onednn.cpp
src/plugins/intel_gpu/src/graph/include/gemm_inst.h
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/matmul.cpp

- Separate input and weight rank check for reordered case in gemm to avoid exception from non reordered input (input0 in below layer)
- convert_data_tensor() returns wrong data tensor when size of format.dims_order() is not same with shape.size(). So gemm need to set proper format for shape.size() in input/output layout.
- 163982

[GPU] Separate input and weight rank check for reordered case in gemm

---

src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

Disable sporadically failing ConvPoolRelu_i32_batch1 on ARM 32 bit platforms
- 164799

[CPU][ARM] Disable ConvPoolRelu_i32_batch1 test on 32-bit system

---

.github/workflows/build_doc.yml
.github/workflows/job_cpu_functional_tests.yml
.github/workflows/mo.yml
.github/workflows/ovc.yml
.github/workflows/windows_conditional_compilation.yml
.github/workflows/windows_vs2019_release.yml

- Should fix https://github.com/openvinotoolkit/openvino/actions/runs/14084226528/job/39688190518?pr=29752

[CI] [GHA] Bump `actions/cache` to 4.2.2

---

.github/dependabot.yml

- `dependabot` supports listing several directories and using the wildcards: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--
- I tried it in my fork, and it seems to be working

[CI] [GHA] Provide paths to Dockerfiles to `dependabot`

---

src/plugins/intel_cpu/src/nodes/qkv_proj.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/qkv_proj_fusion.cpp

- *the AMX optimization of QKVProjection Node is only efficient on large input channel cases(which was true for most LLM models), but on some recent models with small QKV input channel, it actually causes regression, we simply disable this node and fallback to normal FullyConnected*
- *...*
- *CVS-157051*

[CPU] limit QKVProjection to only work on large K dim case

---

src/core/reference/src/op/reshape.cpp

In current implementation for reshape_2d for element transpose, each element will be processed one by one  after 2d data is divided into each thread with store-prioritized algorithm, this is not efficient when the shape is large for lots of cache miss will happen. Divide data into smaller block and then process the block in each thread will improve the memory locality and reduce transpose time especially for LLM models with large shape data to transpose. tbb::blocked_range2d API has implemented this algorithm, this PR use the tbb::blocked_range2d to improve the transpose reshape_2d performance
- *https://jira.devtools.intel.com/browse/CVS-165232*

Update transpose reshape_2d algorithm to block structure

---

src/plugins/intel_gpu/src/graph/program_node.cpp

- Additional check to disable optimizations for ops whose mem allocation type is usm_device. The optimization code attempts to do a read-write mem_lock which throws an exception with usm_device mem which works only with read-only mem_lock.
- CVS-163828

[GPU] Disable onednn post-op optimization for ineligible nodes

---

src/plugins/intel_gpu/src/plugin/ops/batch_to_space.cpp
src/plugins/intel_gpu/src/plugin/ops/space_to_batch.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/batch_to_space.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/space_to_batch.cpp

- *Update creating SpaceToBatch and BatchToSpace for dynamic and static case*
- *101355*
- *164591*

[GPU] Update creating SpaceToBatch and BatchToSpace for dynamic and static

---

src/plugins/intel_gpu/include/intel_gpu/runtime/engine.hpp
src/plugins/intel_gpu/src/runtime/engine.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp

- due to https://github.com/openvinotoolkit/openvino/pull/25269 map is empty when memory is zero (no only before any allocation (as before) but now also after cleanup)
- it fix gpu func test OVGetMetricPropsTest_GPU_MEMORY_STATISTICS_CHECK_VALUES.GetMetricAndPrintNoThrow
- part of 164932

[GPU] fix of memory statistic test

---

src/plugins/intel_cpu/tools/dump_jit_disassm/README.md
src/plugins/intel_cpu/tools/dump_jit_disassm/__main__.py

In some cases using `llvm-addr2line` enables with dramatic tool performance improvement with the same output
This patch introduces an option to specify the path to desired `addr2line` tool binary (`addr2line` remains default)
```
$ time python ~/openvino/src/plugins/intel_cpu/tools/dump_jit_disassm/ dnnl_traces_cpu_jit_brgemm_kernel_t.5.txt dnnl_dump_cpu_jit_brgemm_kernel_t.5.bin
real    3m4.886s
user    3m3.696s
sys     0m1.172s
$ time python ~/openvino/src/plugins/intel_cpu/tools/dump_jit_disassm/ dnnl_traces_cpu_jit_brgemm_kernel_t.5.txt dnnl_dump_cpu_jit_brgemm_kernel_t.5.bin --addr2line=llvm-addr2line-15
real    0m0.938s
user    0m0.767s
sys     0m0.158s
```
Output after `addr2line` and `llvm-addr2line` execution remains the same
- N/A

[CPU] Provide an option to customize addr2line binary in JIT code disasm tool

---

src/plugins/intel_cpu/src/config.cpp
src/plugins/intel_cpu/src/emitters/snippets/utils/debug_caps_config.cpp
src/plugins/intel_cpu/src/graph_dumper.cpp
src/plugins/intel_cpu/src/utils/debug_caps_config.cpp
src/plugins/intel_cpu/src/utils/debug_caps_config.h

Fix `OV_CPU_SUMMARY_PERF` and `OV_CPU_SNIPPETS_SEGFAULT_DETECTOR` environment variables parsing reusing `ov::util::getenv_bool` function that handles bool flags properly (allowing standard values like "0", "false", "off" for `false` and "1", "true", "on" for `true`, etc.)
- N/A

[CPU][DEBUG_CAPS] Parse boolean flags properly

---

src/plugins/intel_cpu/src/.clang-tidy
src/plugins/intel_cpu/src/cpu_streams_calculation.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer.cpp
src/plugins/intel_cpu/src/dnnl_postops_composer_legacy.cpp
src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/src/emitters/plugin/x64/jit_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_loop_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_emitters.cpp
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/infer_request.cpp
src/plugins/intel_cpu/src/nodes/broadcast.cpp
src/plugins/intel_cpu/src/nodes/bucketize.cpp
src/plugins/intel_cpu/src/nodes/concat.cpp
src/plugins/intel_cpu/src/nodes/dft.cpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/gather.cpp
src/plugins/intel_cpu/src/nodes/grn.cpp
src/plugins/intel_cpu/src/nodes/multiclass_nms.cpp
src/plugins/intel_cpu/src/nodes/non_zero.cpp
src/plugins/intel_cpu/src/nodes/rdft.cpp
src/plugins/intel_cpu/src/nodes/reduce.cpp
src/plugins/intel_cpu/src/nodes/reorg_yolo.cpp
src/plugins/intel_cpu/src/nodes/scatter_update.cpp
src/plugins/intel_cpu/src/nodes/softmax.cpp
src/plugins/intel_cpu/src/nodes/split.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/shape_inference/custom/reshape.cpp
src/plugins/intel_cpu/src/shape_inference/shape_inference.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/move_readvalue_inputs_to_subgraph.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/x64/pass/mha_fusion.cpp

- Fix "readability-container-size-empty" remarks reported by clang-tidy
- Enable "readability-container-size-empty" clang-tidy checks on CI by default
- N/A

[CPU] Apply 'readability-container-size-empty' clang-tidy remarks

---

src/plugins/intel_cpu/CMakeLists.txt
src/plugins/intel_cpu/src/nodes/executors/deconv.hpp
src/plugins/intel_cpu/src/nodes/executors/eltwise.hpp
src/plugins/intel_cpu/src/nodes/executors/interpolate.hpp
src/plugins/intel_cpu/src/nodes/executors/mvn.hpp
src/plugins/intel_cpu/src/nodes/executors/pooling.hpp
src/plugins/intel_cpu/src/nodes/executors/reduce.hpp
src/plugins/intel_gpu/CMakeLists.txt

- Do not suppress -Wdelete-non-abstract-non-virtual-dtor/-Wdelete-non-virtual-dtor warnings in CPU and GPU plugins
- Fix related issues in CPU plugin 
- N/A

[CPU][GPU] Do not suppress virtual destructor related warnings

---

cmake/developer_package/cross_compile/native_compile.cmake

Set explicit limitation for parallel jobs in `ov_native_compile_external_project` to the actual processors count retrieved from cmake.
Motivation of this change: `--parallel` without arguments may be interpreted as unlimited amount of threads. For example, it uses `make -j0` on ARM 32-bit build for `protobuf` library, as a result it overflows RAM and hangs the system.
- N/A

Limit parallel build jobs based on actual processor count for external projects

---

src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp

- Temporarily disable convolution test for XMX platforms due to sporadic failures
- [CVS-156160](https://jira.devtools.intel.com/browse/CVS-156160)

[GPU] Temporarily disable convolution test for XMX platforms due to sporadic failures

---

src/bindings/python/constraints.txt

- The new wheel version (0.46.0) throws an error: Failed to detect Python Tag via wheel.vendored.packaging.tags
- *ticket-id*

[CI] Limit wheel package version

---

src/plugins/intel_npu/src/al/include/intel_npu/config/options.hpp

- Increasing compiler support version of NPU_QDQ_OPTIMIZATION property to 7.20
- This was already merged once in https://github.com/openvinotoolkit/openvino/pull/29581 but accidentally removed in https://github.com/openvinotoolkit/openvino/pull/27955
- *ticket-id*

[intel-npu] Increasing qdq optimization support version to 7.20

---

src/plugins/intel_npu/src/al/include/intel_npu/config/options.hpp

- Adding compiler support version for NPU_TILES (it was formerly renamed to NPU_DPU_GROUPS regardless to version) for legacy support
- *ticket-id*

[intel-npu] compilerSupportVersion for NPU_TILES

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- For dynamic model, the preferred format for `convolution` is selected to "b_fs_yx_fsv16" unconditionally. But the input channel is small (e.g. IC=3), the input tag of onednn conv is selected as blocked format w/ b16, which causes unnecessary computation cost.
- Update format selection logic to select planar format in this case based on the maximum obtainable shape or attribute information.
- 162854

[GPU] Fix dynamic onednn convolution format selection for VLMs

---

src/plugins/intel_gpu/include/intel_gpu/primitives/scaled_dot_product_attention.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_micro.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_ref.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_ref.cpp
src/plugins/intel_gpu/src/plugin/ops/scaled_dot_product_attention.cpp

- Previoulsy sdpa_micro was not supporting scalar value scale / attn_mask 
- Fixed sdpa_micro to support scalar scale/attn_mask so that the VLM models such as llava-llama3 can use sdpa_micro for encoder 
- CVS-162856

[GPU] Fix sdpa_micro to support scalar inputs for attn_mask and scale

---

src/bindings/python/src/openvino/_pyopenvino/properties/intel_gpu/__init__.pyi
src/bindings/python/src/pyopenvino/core/properties/properties.cpp
src/bindings/python/tests/test_runtime/test_properties.py
src/inference/include/openvino/runtime/intel_gpu/properties.hpp
src/plugins/intel_gpu/docs/gpu_plugin_driver_troubleshooting.md
src/plugins/intel_gpu/src/plugin/plugin.cpp

- Currently if the user does not provide shared object handle params for remote tensor creation, GPU plugin directly allocated remote tensor and since `ocl buffer` is selected as the default value for shared memory type
- Expose `USM MEMORY` as supported in device capabilities(`OPTIMIZATION_CAPABILITIES`). And from the user side, check if `USM_MEMORY` is listed as supported, allocate remote tensor as usm memory type selected by the shared object handle params for further performance gain.
- 163996

[GPU] Expose USM memory as supported in device capabilities

---

src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp

- it skip unit test group_normalization.input_bfyx_output_fsv16
-

[GPU] skip one group_normalization test as it produces in out, out reference nan

---

src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gemm_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_utils/network_test.h

- fix fails introduced by using device memory on output which can't do read-write lock
- fails introduced by 6db49399ba762c7b838c0ad07a6561c5e96fcac0
- 164934

[GPU] Fix unit tests failing for BMG

---

src/plugins/intel_gpu/src/plugin/compiled_model.cpp
src/plugins/intel_gpu/tests/functional/behavior/model_cache.cpp
src/tests/functional/plugin/shared/include/behavior/compiled_model/compiled_model_base.hpp

- There are some cases where weights_path doesn't exists and model_ptr is not propagated to CompiledModel::export_model().
- Instead of fixing propagation I decided to remove the check during export because it's only relevant during the importing stage.

[GPU] Remove weightless cache checks during export

---

src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/executor_pa.cpp
src/plugins/intel_cpu/src/nodes/scaled_attn.cpp
src/plugins/intel_cpu/src/utils/plain_tensor.hpp

- *In the q @ k operation of PA and SDPA, need to use [q_len, s] @ [s, kv_len] =  [q_len, kv_len] memory to save the result. If there is multi batch size and multi heads, the memory shape is [B, H, q_len, kv_len], but in the implementation of CPU plugin, the operation will be split into multi tasks, every task only calculate a block size, so every task need memory [block_size, kv_len], the tasks will be scheduled to many different threads by tbb, so need to malloc [threads_num, block_size, kv_len] memory to save all the results. The temporary result will be used to do softmax operation and @ v in the same thread,  so it's safe to use [threads_num, block_size, kv_len] instead of [threads_num, H,  block_size, kv_len]*
- *when loop_hk = true in PA, dim H became Hk, so the temporary weight …

[CPU] reduce temporary weight memory of PA and SDPA

---

src/core/include/openvino/core/model.hpp
src/core/src/model.cpp

- Use new cpp features in template member functions
- Clean-up ov::Model ctors to re-use as much as possible (bin-size reduction)
- part of CVS-72662

[core] OV model class clean-up

---

src/bindings/c/docs/api_overview.md
src/bindings/c/include/openvino/c/gpu/gpu_plugin_properties.h
src/bindings/c/include/openvino/c/ov_core.h
src/bindings/c/src/ov_core.cpp
src/bindings/c/src/ov_property.cpp
src/bindings/c/tests/CMakeLists.txt
src/bindings/c/tests/ov_core_test.cpp
src/bindings/c/tests/ov_test.hpp

This is to implement the c-api discussed in https://github.com/openvinotoolkit/openvino/issues/26645 and based on the previous PR (now closed) https://github.com/openvinotoolkit/openvino/pull/26670 which was failing some CI tests.
- Add `ov_core_add_extension`
- Update c-api tests
- Implemented CPU as well as GPU plugin's extension
Closes https://github.com/openvinotoolkit/openvino/issues/26645

[C API] Implement `ov_core_add_extension` c-api

---

src/inference/tests/functional/ov_core_threading.cpp

- Fix file name prefix to unique in tests
- CVS-133087

Fix file name prefix to unique in tests

---

src/bindings/python/constraints.txt

Reverts openvinotoolkit/openvino#29913
Those versions are marked in yanked 
https://pypi.org/project/wheel/#history

Revert "[CI] Limit wheel package version"

---

src/plugins/intel_gpu/src/graph/gather.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/gather.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/gather.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/register.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/register.hpp
src/plugins/intel_gpu/src/graph/registry/gather_impls.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/gather/gather_kernel_ref.cpp
src/plugins/intel_gpu/tests/unit/test_cases/gather_gpu_test.cpp

There were two problems with gather :
1. Allowing unnecessary reorder
By the definition of gather, the input and output dimensions can be different. Forcing the input and output dimensions to match using reorder node will lead to unintended results. It needs to prevent the reorder by `GatherImplementationManager`.
2. Hard-coded index order for 5D, 6D
The hard-coded index order for 5D, 6D created by `GetFinalIndexOrder()` seems assuming the wrong indices (2nd input). see below the problematic case.
> Problematic case : `data.shape=[3,4,12,12,6,3]`, `indices.shape=[3,4,1,12,12,1]`, `batch_dims=4`, `axis=4`, `output.shape=[3,4,12,12,1,3]`  
Actually it must be `indices.shape=[3,4,12,12,1]`. But `indices.shape=[3,4,1,12,12,1]` was created due to the unnecessary reorder. According to the …

[GPU] Fix wrong index order in Gather

---

src/plugins/intel_cpu/src/.clang-tidy
src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_emitter.cpp
src/plugins/intel_cpu/src/emitters/tpp/common/kernel_executors/brgemm.cpp
src/plugins/intel_cpu/src/nodes/kernels/riscv64/jit_uni_eltwise_generic.cpp
src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/attn_quant.cpp
src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/executor_pa.cpp
src/plugins/intel_cpu/src/transformations/tpp/common/pass/lowered/set_tpp_leading_dim.cpp

- Fix "readability-braces-around-statements" remarks reported by clang-tidy
- Enable "readability-braces-around-statements" clang-tidy checks on CI by default
- Configure "readability-braces-around-statements.ShortStatementLines" with the value "1" to enforce one-line statements be wrapped with curly braces
- N/A

[CPU] Apply 'readability-braces-around-statements' clang-tidy remarks

---

src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp

Recent change to sdpa_micro to convert scalar buffer to scalar value has mismatch the key/value scale shape programming which use the wrong input index.
This affect qwen2-7 model that generate the garbage output.
CVS-165877

[GPU] Fix incorrect key/value cache scale shape does not program correctly

---

src/plugins/intel_gpu/src/kernel_selector/kernels/dynamic_quantize/dynamic_quantize_kernel_opt.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- gs256 did not work with opt kernel due to wrong assertion
- CVS-148732

[GPU] dyn_quan bugfix

---

src/bindings/c/docs/api_overview.md
src/bindings/c/include/openvino/c/ov_tensor.h
src/bindings/c/src/ov_tensor.cpp
src/bindings/c/tests/ov_tensor_test.cpp

Related to https://github.com/openvinotoolkit/openvino/issues/26906
This implements c-api for setting string tensor data for previously initialized string type tensor.
This API is needed since string data can't be set using existing `ov_tensor_data`

[C API] Implement `ov_tensor_set_string_data` c-api

---

docs/articles_en/openvino-workflow-generative/inference-with-optimum-intel.rst

- For GPU without XMX support, dynamic quantization is turned on by default
- Example of GPU without XMX support: integrated GPU on Tigerlake, Alderlake or Raptorlake

[GPU][Doc] Doc update for dyn_quan default configuration

---

.github/ISSUE_TEMPLATE/good_first_issue.yml

- AI generated, low-effort PRs are becoming a significant problem
- A warning allows us to have more freedom in closing PRs which are clearly AI generated and don't show any improvement over the review process
- Let's hope this helps a little :)
- N/A

[GFI] Add an AI usage notice to GFI template

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp

- Currently for per-channel quantized models, FC(two FCs already fused)+SwiGLU fusion causes accuracy issue. 
- 2FCs+SwiGLU fusion is disabled until `fully_connected_bf_tiled` opt kernel supports that case.
- 165528

[GPU] Disable 2FCs+SwiGLU fusion for per-channel quantized models

---

src/bindings/python/src/openvino/frontend/tensorflow/utils.py
tests/model_hub_tests/tensorflow/model_lists/precommit_convert_model
tests/model_hub_tests/tensorflow/test_tf_convert_model.py
tests/model_hub_tests/tensorflow/utils.py

**Details:** Correct input names for TF Keras model converted from memory.
**Ticket:** https://github.com/openvinotoolkit/openvino/issues/30056

[TF FE] Correct input names for TF Keras model converted from memory

---

src/core/dev_api/openvino/op/ops_decl.hpp
src/core/dev_api/openvino/opsets/opset10_decl.hpp
src/core/dev_api/openvino/opsets/opset11_decl.hpp
src/core/dev_api/openvino/opsets/opset12_decl.hpp
src/core/dev_api/openvino/opsets/opset13_decl.hpp
src/core/dev_api/openvino/opsets/opset14_decl.hpp
src/core/dev_api/openvino/opsets/opset15_decl.hpp
src/core/dev_api/openvino/opsets/opset16_decl.hpp
src/core/dev_api/openvino/opsets/opset1_decl.hpp
src/core/dev_api/openvino/opsets/opset2_decl.hpp
src/core/dev_api/openvino/opsets/opset3_decl.hpp
src/core/dev_api/openvino/opsets/opset4_decl.hpp
src/core/dev_api/openvino/opsets/opset5_decl.hpp
src/core/dev_api/openvino/opsets/opset6_decl.hpp
src/core/dev_api/openvino/opsets/opset7_decl.hpp
src/core/dev_api/openvino/opsets/opset8_decl.hpp
src/core/dev_api/openvino/opsets/opset9_decl.hpp
src/frontends/ir/tests/frontend_test_basic.cpp
src/frontends/ir/tests/frontend_test_mmap.cpp
src/frontends/ir/tests/frontend_test_with_extensions.cpp
src/frontends/ir/tests/partial_shape_deserialization.cpp
src/frontends/ir/tests/tensor_iterator_deserialization.cpp

- Introduced operators' forward declarations file.
- Introduced opset declaration files. It allows using `opsetN::op` without including _heavy_ `opsetN.hpp` file, but related op `.hpp` and `opsetN_decl.hpp`.
- Removed unnecessary include ops.hpp
- Added missing includes
- CVS-166054

[Core][IR FE] Remove unnecessary ops.hpp usage from IR FE

---

src/bindings/c/include/openvino/c/ov_property.h
src/bindings/c/tests/ov_core_test.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp

- Fix ov_core_set_get_property_gpu tests, add config_file as supported property for GPU
- CVS-166069

Fix ov_core_set_get_property_gpu tests, add config_file as supported property for GPU

---

src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cpp

- *primitive_inst tries to allocate output memory and it can alloc by using virtual memory even if physical memory is full on Windows. So the check_allocatable() func needs to return true.*
- *...*
- *161457*

[GPU] Allocate output mem using virtual memory in Windows even if physical memory is full

---

src/plugins/intel_cpu/src/nodes/memory.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/stateful_init_graph.cpp

- *Revise MemoryInput node to use its own input config. Otherwise for infer_precision=bf16, the leading FullyConnected node in MemoryInput's subgraph could have unsupported data_precision f32, as in (data_precision, weight_precision, output_precision)=(f32, f32, bf16), because of precision dependencies during Graph::ResolveEdgeConflicts(), Graph::AllocatedReferencingEdges() etc.*
- *A subgraph test case is added to reproduce this issue beforehand.*
- *[CVS-163281](https://jira.devtools.intel.com/browse/CVS-163281)*

[CPU] Fix compilation issue for FullyConnected node

---

samples/cpp/benchmark_app/main.cpp
src/bindings/c/src/ov_tensor.cpp

- Fix CID 1538735, constant expression result
- Fix CID-1491551, explicit null dereferenced
- CVS-165930

[Coverity] Integer handling issues and null pointer dereferences

---

src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
src/common/transformations/tests/common_optimizations/nop_elimination.cpp

Fix errors 
- 1) the concat & StridedSlice all can be eliminated;
- 2) the inputs of concat have dim value = 1 in concat axis
- 2) Fix the bug caused by EliminateConcatStridedSlice Pass which did not consider the Nodes which do not have default output index, such as TopK.
- CVS-165105
- CVS-164371
- CVS-165403

Fix issue in EliminateConcatStridedSlice with compilation problem

---

src/common/transformations/src/transformations/common_optimizations/augru_cell_fusion.cpp
src/common/transformations/tests/common_optimizations/augru_cell_fusion.cpp

The DIEN_Alibaba  model now has different shapes for parameters of a Loop inputs preventing it from fusing a part of the graph into AUGRUCell. Add Transposes and Unsqueezes to obtain parameters in the expected shapes.
- [CVS-159221](https://jira.devtools.intel.com/browse/CVS-159221)

[TRANSFORMATIONS] Support AUGRUCell fusion differences in the DIEN_Alibaba model

---

src/plugins/intel_cpu/src/nodes/random_uniform.cpp

- Replace `rand()`, `srand()` and `time()` C calls with `std::random_device` to fix "Calling risky function" Coverity concerns
- Coverity issues: 1568465, 1523761
- 165940

[CPU][Coverity] Replace C random functions with C++ in RandomUniform node 

---

src/bindings/python/requirements_test.txt
src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/execute.py

- dependabot tries to update flake8 and linters job failed
- *ticket-id*

Update flake8 + ignore F824

---

src/common/snippets/include/snippets/op/scalar.hpp

Snippets nodes normally do not have reference implementation. Disable it for ones that do have one inherited from the parent operation class
- 163186

[Snippets] Disable reference implementation for Scalar node

---

src/plugins/intel_npu/src/backend/src/zero_backend.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_init.hpp
src/plugins/intel_npu/src/utils/src/zero/zero_init.cpp
src/plugins/intel_npu/tests/functional/behavior/remote_tensor_tests/remote_run.hpp

- *Do not reinitialize driver and device for each ov::Core object*

[NPU] Get same zero context for different CORE

---

src/plugins/intel_gpu/src/graph/impls/ocl/fully_connected.cpp

- enable u8,i8 with bfzyx format in FC
- has_impl_for function checked FC layer's original input which is 5-dim. But In runtime, the FC layer executed as bfyx by optimizing out its dependency node, Reshape, which changes bfyx to bfzyx.
As has_impl_for is in add_required_reorders pass, it could not know whether its dependency node would be optimized out or not. 
- CVS-165888

[GPU] enable u8,i8 for fc 5 dims

---

src/plugins/intel_gpu/src/graph/fully_connected.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/unit/fake_alignment/fc_fake_alignment_test.cpp
src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/fully_connected_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/hash_key_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/memory_test.cpp

- This PR updates fc_onednn_impl to use original dims instead of squashing input layout to 2D.
- It resolves layout mismatch problems between fc and post-ops.
- 164104, 164106

[GPU] to use original dims for fc_onednn_impl

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/fully_connected_gpu_bf_tiled.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl
src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp

- Update fc_bf_tiled opt kernels to support 2FCs+SwiGLU fusion for per-channel quantized models (`DECOMPRESSION_SCALE/ZP_GROUP_SIZE`==`IFM_SIZE`  && `OUTER_OFM`>1) 
- Revert temporary solution from https://github.com/openvinotoolkit/openvino/pull/30065
- 165887

[GPU] Support 2FCs+SwiGLU fusion for per-channel quantized models 

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp

- Fixed sdpa_opt to support unaligned head_size
- Previously, SDPA was decomposed for unaligned head_size such as 72 because sdpa_opt did not support that shape 
- Now SDPA is not decomposed for unaligned head_size
- CVS-164179

[GPU] Update sdpa opt to support unaligned head size

---

src/plugins/intel_cpu/src/nodes/paged_attn.cpp
src/plugins/intel_cpu/src/nodes/paged_attn.h
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp

- *Fix the layout check with float cache type*
- *Port the fix from https://github.com/openvinotoolkit/openvino/pull/29763*
- *ticket-id*

[CPU]fix by-channel key cache layout check

---

src/plugins/intel_gpu/src/graph/impls/ocl/resample.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- For yolo v5m b16 case, resample should run in bsv16_fsv32. It was missing in supported layout.
- Allow OneDNN asym_dyn_quan for i8 weight case. (not related to resample, but a minor change)
- 166362

[GPU] resample supports bsv16_fsv32

---

src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/utils.hpp
src/plugins/intel_gpu/src/graph/program_node.cpp

- Currently, when a quantize layer is fused as postop of the previous layer, its layout is converted to 2D.
- This PR updates the quantize layer to keep its original layout when it fused.

[GPU] updates quantize to use original layout in postop of onednn impl

---

src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/mha_single_token.cpp
src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/softmax_kernel.hpp

- Don't use FP16 instructions w/o guard
- Closes https://github.com/openvinotoolkit/openvino/issues/30098

CPU: fixed issue #30098

---

src/frontends/onnx/frontend/src/op/com.microsoft/qlinear_activation.cpp
src/frontends/onnx/tests/models/com.microsoft/qlinear_softmax_opset12.prototxt
src/frontends/onnx/tests/models/com.microsoft/qlinear_softmax_opset13.prototxt
src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp

Details:
Microsoft Contrib Operator "QLinearSoftmax" for ONNX RT
Tickets:
N/A

[ONNX] Added QLinearSoftmax from com.microsoft domain

---

src/common/snippets/src/lowered/pass/move_scalar_to_consumer.cpp
src/common/snippets/tests/src/lowered/pass/move_scalar_to_consumer.cpp

Remove the limitation that restricted `Scalar` snippets operation to a single consumer
- required by: 163186
- part of: 166528

[Snippets] Support multiple consumers for Scalar operation

---

src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/matmul_weights_decompression.cpp

- Fixed issue on fc_tiled kernel when only dyn_quant kernel exists  and slm kernel is not generated
- In that case, all kernels were skipped because the skipping kernel idx was calculated assuming that there is all three kernels exist
- CVS-165900

[GPU] Fixed issue on fc kernel when dyn_quant kernel exists but slm kernel is not generated 

---

tools/commit_slider/tests/commit_slider_test.py
tools/commit_slider/tests/test_data.py
tools/commit_slider/tests/test_util.py
tools/commit_slider/tests/tests_res/fbv_blb_cmp_automatch_main.cpp
tools/commit_slider/tests/tests_res/fbv_blb_cmp_main.cpp
tools/commit_slider/tests/tests_res/fbv_blb_cmp_mul_out_main.cpp
tools/commit_slider/tests/tests_res/tests_res.json
tools/commit_slider/utils/cfg.json
tools/commit_slider/utils/cfg_samples/blob_cmp_automatch.json
tools/commit_slider/utils/helpers.py
tools/commit_slider/utils/modes.py
tools/commit_slider/utils/preprocess/replace.py

- *Preprocess registered as utility *
- *Blob compar. improved*
- *Test coverity*
- *Amplified blb comparation with multiple files*
- *Auto mapping for output files*
- *ticket-id*

[CS] Blob-compare job preparation

---

src/plugins/intel_gpu/src/graph/graph_optimizer/compile_graph.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing_through.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/reduce.cpp

- *Fixed the reorder added for squeezing the output of reduce to not be removed.*
- *165886*

[GPU] Avoid raising up the reorder added for reshaping the output of reduce.

---

cmake/developer_package/compile_flags/sdl.cmake

This reverts commit 37d055e477d743c10a05e27c55e153506c8e784e.
```bash
clang++: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
```
`-pie` is enable by default on `macOS` and this flag is not supported:
- https://github.com/swiftlang/swift/issues/48291#issuecomment-1108257194
- https://hg-edge.mozilla.org/integration/autoland/rev/6087ce1bca59
- N/A

Revert "Enable `-pie` compile option for MacOS (#18568)"

---

src/plugins/intel_cpu/src/nodes/dft.cpp
src/plugins/intel_cpu/src/nodes/tensoriterator.cpp
src/plugins/intel_cpu/src/shape_inference/custom/scaled_attn.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/causal_mask_preprocess_fusion.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/x64/pass/convert_to_interaction.cpp

Fix Coverity remarks:
- 1502517 - Dereference after null check
- 1538950, 1538782 - Improper use of negative value
- 1542737, 1511142 - Using invalid iterator
- 165923

[CPU] Fix Coverity remarks regarding potential null pointer dereference and out-of-bounds access

---

src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/common/broadcast_eltwise.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

`smoke_BroadcastEltwise/BroadcastEltwise.smoke_CompareWithRefs/precision=f32IS=([?.?.?.?])_TS=((1.3.16.16)_)_target_shape=(16.16)` and other BroadcastEltwise related tests fail with the exception: `to_shape was called on a dynamic shape`
- 166771

[CPU] Disable failing smoke_BroadcastEltwise test on ARM64

---

src/bindings/js/node/CMakeLists.txt

Xcode 15 introduced a new linker and all types of behavior in case of undefined symbols in dynamic library (except the default one `-undefined dynamic_lookup`) have been deprecated:
```
ld: warning: -undefined suppress is deprecated
```
`-bundle` option is used to produce shared object (`.node` file) instead of `.dylib`
- N/A

[JS] Replace deprecated '-undefined suppress' flag on macOS

---

cmake/developer_package/features.cmake

The checks take too long to be enabled by default

[CMAKE] Disable clang-tidy by default for all the platforms

---

src/plugins/intel_npu/tools/compile_tool/main.cpp

Currently, `compile_tool` ignores missing config files if it's passed in using `-c` parameter.
This fix will check if the config file given by the user can be opened and exists, and will throw an exception if it doesn't.
- E-164501

[NPU] Add error handling for missing configuration file in parseConfigFile

---

src/common/snippets/src/lowered/pass/propagate_subtensors.cpp
src/common/snippets/src/pass/softmax_decomposition.cpp
src/common/snippets/src/utils/utils.cpp

- fix for: Use of auto that causes a copy at utils.cpp 
- fix for: COPY_INSTEAD_OF_MOVE at softmax_decomposition.cpp
- fix for: Use of auto that causes a copy at propagate_subtensors.cpp 
- [*CVS-148602*](https://jira.devtools.intel.com/browse/CVS-148602)

[CORE]Coverity performance inefficiencies

---

src/frontends/pytorch/src/op_table.cpp
tests/layer_tests/pytorch_tests/pytorch_layer_test_class.py
tests/layer_tests/pytorch_tests/test_neg.py

- *Support `<built-in function neg>` which appears on the shape path only in FX graph*
- *ticket-id*

[PT FE] Add support for built-in neg in FX graph

---

src/plugins/intel_npu/src/plugin/src/plugin.cpp

- On systems without NPU device and offline-mode NPU driver (i.e. MLIR+IMD) IE_NPU_COMPILER_TYPE envinronment variable needs to be picked up (if set) before options filtering, in order construct straight away with the correct compiler. 
- Without this a corner-case occurs on aforementioned setups, where compiler options get marked as unsupported (because there is no valid compiler @ filtering stage) and get stuck there because compiler-change logic will not get triggered either
- EISW-165899

[intel-npu] Quickfix for specific development usecase when used w/o driver and mlir

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/rms_gpu_bfyx_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_bfyx_opt.cpp
src/plugins/intel_gpu/tests/unit/test_cases/rms_gpu_test.cpp

- Add support of dynamic input paddings to rms_bfyx_opt kernel for Qwen3 model
- Test case borrowed from https://github.com/openvinotoolkit/openvino/pull/29835 
- *CVS-165116*

[GPU] Add support of dynamic paddings to rms_bfyx_opt kernel for Qwen3 model

---

src/inference/src/dev/plugin_config.cpp
src/inference/tests/unit/config_test.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp

- Currently, env option is only available in build with DEBUG_CAPS
- Enable it for release build as well
- Document was already updated that it is supported on all builds

Expose env option to release build as well

---

src/plugins/intel_gpu/include/intel_gpu/primitives/paged_attention.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/paged_attention.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp
src/plugins/intel_gpu/src/graph/paged_attention.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_kv_cache_update_ref.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_rotate_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_kv_cache_update_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/pa_sdpa_kernel_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_base.h
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_ref.cpp
src/plugins/intel_gpu/src/plugin/ops/paged_attention.cpp
src/plugins/intel_gpu/src/plugin/transformations/op/sdpa.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/common/subgraphs_builders.hpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/kv_cache_sdpa.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/update_shape_test.cpp
src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/transformations/indirect_kv_cache_test.cpp
src/plugins/intel_gpu/tests/unit/transformations/kv_cache_compression.cpp
src/plugins/intel_gpu/tests/unit/transformations/sdpa_opt_test.cpp

In continue batching, head size for key and value will be different. Add support for it for sdpa.
CVS-162339 and CVS-161089

[GPU] Enable multi head size support for KV cache

---

src/frontends/pytorch/src/transforms/aten_index_put_replacer.cpp
tests/layer_tests/pytorch_tests/test_index_copy_.py

**Details:** It allows to support tiny-llama for torch.export mode
**Ticket:** 165932

[PT FE] Support torch.index_copy_ for export mode

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- *Slight speedup for LoRA, which uses a huge amount of `read_value`*
- *With the same checks, when executing a impl, nothing happens except overheads, which means we can skip execution in advance*

[GPU] Skip ReadValue execution if its already set

---

src/frontends/pytorch/src/op_table.cpp

**Details:** With latest torch version, this operation is not reproduced in layer tests.
**Ticket:** Addresses https://github.com/openvinotoolkit/openvino/issues/30356 but inference on GPU

[PT FE] Support aten::special_expit

---

src/common/transformations/include/transformations/utils/utils.hpp
src/common/transformations/src/transformations/utils/utils.cpp
src/plugins/intel_gpu/include/intel_gpu/runtime/execution_config.hpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp

- Allow kv_cache_precision property to be read from rt_info for PagedAttention models on any GPUs
- Previously, kv_cache_precision was read from rt_info only on non-systolic platforms due to the poor performance of  sdpa_micro kernel. However, since PagedAttention does not use sdpa_micro, this restriction can now be removed
- [CVS-165096](https://jira.devtools.intel.com/browse/CVS-165096
)

[GPU] Allow kv_cache_precision property to be read from rt_info for PagedAttention models on any GPUs

---

src/plugins/intel_cpu/src/utils/blob_dump.cpp

Fix blob dumping output issues like:
```
u8 1D shape: 75 (75) by address 0x0x13f6a1380
```
- N/A

[CPU][DEBUG CAPS] Remove extra '0x' in blob dumping

---

src/plugins/intel_gpu/src/kernel_selector/kernels/permute/permute_kernel_f_y_axes.cpp

Fixes Coverity using invalid operator issue, simplifies code and improves performance
- Replace usage of std::find_if and std::vector with a simple for loop
- 167165

[GPU][Coverity] Rework GetDivisor in permute kernel f y axes

---

src/common/snippets/src/lowered/pass/mark_invariant_shape_path.cpp
src/common/snippets/src/op/memory_access.cpp
src/common/snippets/src/pass/transform_convert.cpp

Fix Coverity remarks:
- 2360985, 2360976, 2360969: Using invalid iterator
- 2356388: Dereference null return value
- 167167

[Snippets] Fix invalid iterator and null pointer dereference Coverity remarks

---

src/plugins/intel_gpu/src/graph/impls/ocl_v2/utils/jitter.cpp

Fix coverity issue with usage of invalid iterator
- Check for end() iterator before jumping to loop which increments the iterator
- 167165

[GPU][Coverity] Avoid incrementing end() iterator in LayoutJitter

---

src/plugins/intel_npu/src/plugin/src/plugin.cpp

- Moving backend options registration upper in the init sequence so it will properly catch env var parsing
- *ticket-id*

[intel-npu] Moving backend options registration up in the init sequence

---

src/inference/src/dev/iasync_infer_request.cpp

- Added missing lock protections
- Coverity issues: 1530042, 1530340
- CVS-165933

[IE] Avoid race condition in IAsyncInferRequest

---

src/plugins/intel_gpu/include/intel_gpu/op/kv_cache_compressed.hpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16_imad.cpp

- Fixing 1565213, 1565100, 1565332
- Other issues are already fixed
- Initialized the default `m_compressed` value to false
- Null pointer dereferences: ensure `compressed_cache_variable` is not NULL
- Ensure result is float
- *CVS-157248*

[Coverity] Medium issues in GPU Plugin

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- Update condition of NMSIEInternal op convert callback in transformation for legacy static models
- Some models have performance regression when allow_new_shape_infer is changed to true by PR#30043. This PR fixes it.
- 166611
- 166613
- 167154

[GPU] Update condition of NMSIEInternal op convert callback in transformation for legacy static models

---

src/plugins/intel_npu/src/al/include/intel_npu/config/options.hpp
src/plugins/intel_npu/src/plugin/include/properties.hpp
src/plugins/intel_npu/src/plugin/src/properties.cpp
src/plugins/intel_npu/tests/functional/behavior/compiled_model/property.cpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/compiled_model/properties.cpp

- breaking unified properties registration function into 2 separate ones, dedicated for Plugin properties and dedicated for Compiled_model properties
- revisiting compiled_model properties
- adding macro to be used with particular properties for compiled_model which checks first if the option was set or is on default value
- for compiled model, all compiler-specific properties are now only registered if they were previously set
- EISW-75326

[intel-npu] Compiled model properties: include only properties that had been set

---

src/common/transformations/src/transformations/fp16_compression/mark_subgraphs_to_keep_in_mixed_precision.cpp
src/common/transformations/tests/common_optimizations/align_mixed_fp32_fp16_types_test.cpp
tests/layer_tests/tensorflow_tests/test_tf_RandomUniform.py

- Add flag that disables FP16 compression for `RandomUniform` node
- Remove precision loss due to FP32->FP16->FP32 conversions
- 156055

[CPU][ARM] Fix RandomUniform TF node precision issue

---

src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/executors/convolution_implementations.cpp
src/plugins/intel_cpu/src/onednn/iml_type_mapper.cpp
src/plugins/intel_cpu/src/onednn/iml_type_mapper.h

Before refactoring:
- Convolution was created with 8c blocking right away
After refactoring:
1) Convolution was created with 'any' layout, then some primitive implementation (not fork dw conv) returned 8c layout
2) 8c layout is used to create fork dw conv implementation (not the one, which returned this layout).
3) Essentially the same primitive is created but performance is worse
Solution - prevent fallback to 'any' layout in the first place
- 166651

[CPU] Fix Convolution primitive creation when dw conv post op is fused

---

src/plugins/intel_npu/src/al/include/intel_npu/config/options.hpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp

- Molding NPU_TURBO into a shared option between driver and compiler compiler. 
If compiler supports it, will send it to compiler too. Else we send it to driver only.
Changes required to obtain this:
- changing OptionMode for Turbo to OptionMode::Both
- optionMode::Both will make Turbo to be included in compiler arguments even if it doesn't support it > need to add compiler argument string filtering with compiler support verification to remove it if the compiler doesn't support it (but without effecting setting it in driver)
- since Turbo became OptionMode::Both, it will fall into properties initialization (and reinitialization) logic, which will ask about compiler support for it. If compiler doesn't report it supported, the logic marks it disabled. However, we still want to use it for …

[intel-npu] Molding NPU_TURBO into a shared option between driver and compiler

---

src/common/util/include/openvino/util/common_util.hpp
src/common/util/include/openvino/util/os.hpp
src/common/util/src/common_util.cpp
src/common/util/src/os/win/os.cpp
src/core/reference/src/op/convert.cpp
src/core/src/runtime/compute_hash.cpp

- *The GetProcessMitigationPolicy  function has been implemented since Windows 8, thus need to check Windows version first.*
- *CVS-166811*

[CORE] Check Windows version for fn GetProcessMitigationPolicy

---

src/core/src/op/util/weightless_caching_attributes.cpp

- fix: Dereference null return value
- [*167180*](https://jira.devtools.intel.com/browse/CVS-167180)

[Coverity Enterprise][Core] Execute unauthorized code

---

src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp
src/plugins/intel_gpu/src/kernel_selector/micro_utils.hpp
src/plugins/intel_gpu/thirdparty/CMakeLists.txt

- onednn commit a42b47ff2c (origin/rls-v3.9-pc)
- fix build issue: ngen
-- update cmake: add definition: NGEN_CONFIG
-- update cmake: add include directory src/gpu/intel/jit/configm, src/gpu/intel/jit/gemm/include
-- update header path from gpu/intel/jit/gemm/include to gpu/intel/jit/gemm/include/gemmstone
-- replace namespace from dnnl::impl::gpu::intel::jit to gemmstone
-- data_type_size() to size() of gemmstone::Type
- 165696

[GPU] onednn rls-3.9pc integration

---

src/plugins/intel_gpu/include/intel_gpu/runtime/device_info.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/kernel_base_opencl.cpp
src/plugins/intel_gpu/src/kernel_selector/kernel_selector_params.h
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp

[GPU] choose kernel compile option for work_group_(OPS)

---

src/plugins/intel_npu/src/plugin/src/properties.cpp

- INFERENCE_PRECISION_HINT property is exposed in compiled model properties ONLY if it was set previously
- this commit changes it into being permanently exposed
- *ticket-id*

[intel-npu] Moving inference_precision hint to permanent compiled model property

---

src/plugins/intel_gpu/src/graph/impls/ocl_v2/utils/fused_ops_jitter.cpp
src/plugins/intel_gpu/src/graph/impls/ocl_v2/utils/kernel_generator.cpp

- *Fixed `get_arguments_desc(..)` function, in case of existence of a fused dependency an additional input primitive descriptor was added in the previous version*
- *Removed unused code*

[GPU] Several new infra fixes

---

src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/input_layout.cpp
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Follow member variable naming convention to start with underbar
- Move do_runtime methods to private scope as it is an implementation detail
- Changed some names for clarity: check_memory_to_set, set_shape_info_memory_subbuffer

[GPU] Trivial cleanup for primitive_inst

---

src/plugins/intel_npu/src/backend/src/zero_backend.cpp

- return empty device in case there are no devices present - for offline compilation usecase
- *ticket-id*

[intel-npu] getDevice quickfix for off-device compilation

---

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp
src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_utils.hpp

- *Add FP8 precision support for NPU.*
- *Update L0 extension which include FP8 graph arg precision.*
- *Tests can't be enabled because FP8 is not fully supported in NPU compiler at this moment.*
- *E-163770*

[NPU] Add FP8 precision support in NPU plugin

---

src/common/transformations/include/ov_ops/type_relaxed.hpp
src/common/transformations/include/transformations/utils/print_model.hpp
src/plugins/intel_cpu/src/extension.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/behavior/compiled_model/import_export.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- Fix export/import models which has TypeRelaxed operators by adding original operator opset version to TypeRelaxed operator version passed as runtime info
- The proper info would be set this correct version in TypeRelaxed operator version but it still used in `ov::snippets::TargetMachine ` class in jitter map.
- CVS-166815

[transformations][CPU] Add opset version to TypeRelaxed operators rt info

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/pa_sdpa_opt.cl
src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp

Currently, pa_sdpa_scores_calculation doesn't handle seq len may have different num of partition.  As a result, it may read in garbage data and generate incorrect output.

[GPU] Handle different partition size for different seq_len in pa sdpa

---

src/tests/test_utils/common_test_utils/src/graph_comparator.cpp

Add debug log for `NodeAndInputDescription` parameters and and `NodeAndOutputDescription` result debugging when two subgraphs are being compared
- N/A

[IE TESTS] Add input/output descriptor dumps for subgraph descriptions debugging

---

src/common/transformations/include/transformations/utils/gen_pattern.hpp
src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp
src/core/src/pattern/op/pattern.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/causal_mask_preprocess_fusion.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/stateful_sdpa_fusion.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/x64/pass/mlp_fusion.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/x64/pass/qkv_proj_fusion.cpp

Details:
Rewrite the RoPEFusionGPTJ transformation using new Symbolic approach allowing for greater flexibility and more convenient pattern design.
Tickets:
[CVS-165966](https://jira.devtools.intel.com/browse/CVS-165966)
Signed-off-by: Andrii Staikov [andrii.staikov@intel.com](mailto:andrii.staikov@intel.com)

[TRANSFORMATIONS] Rewrite RoPEFusionGPTJ using new Symbolic approach

---

src/core/reference/include/openvino/reference/segment_max.hpp
src/core/src/op/segment_max.cpp
src/frontends/tensorflow/docs/supported_ops.md
src/frontends/tensorflow/src/op_table.cpp
src/frontends/tensorflow_common/include/common_op_table.hpp
src/frontends/tensorflow_common/src/op/segment_max.cpp
src/plugins/template/tests/functional/op_reference/segment_max.cpp
tests/layer_tests/tensorflow_tests/test_tf_SegmentMax.py

- Extend TF FE with `SegmentMax-16` needed for BST model enablement
- When generating data for TF FE tests I noticed a discrepancy between implementations when all values in a segment are negative
- Fixed the issue, added tests
- N/A

Extend TF FE with `SegmentMax-16` and fix an edge case bug

---

src/common/snippets/src/pass/hash.cpp
src/common/transformations/include/transformations/rt_info/fused_names_attribute.hpp
src/common/transformations/src/transformations/rt_info/fused_names_attribute.cpp
src/core/include/openvino/core/runtime_attribute.hpp
src/core/src/pass/serialize.cpp
src/core/src/runtime_attribute.cpp
src/inference/src/dev/compilation_context.cpp
src/inference/tests/unit/compilation_context_test.cpp

- Add new member to RuntimeAttribute to give information if attribute should be taken into hash calculation. Default value is true which means it should be used for hash. 
- Some runtime attribute if have no deterministic values (base on some auto/random values) or have no impact on model behavior maybe considered to exclude from hash calculation to avoid multiple entries of same model in cache. The new attribute will allow OpenVINO internal or defined by user attributes to be include or excluded from hash computation.
- Set `FusedNames` attribute to be not deterministic as stored names can be auto generated names and will not change model but will cause generating multiple entries in cache of same model.
- CVS-167799

[core] Expand RuntimeAttribute with member is_deterministic()

---

src/plugins/intel_gpu/src/graph/impls/common/loop.cpp
src/plugins/intel_gpu/tests/unit/test_cases/loop_gpu_test.cpp

- *Use mem_lock type read for loop read_scalar*
- *167031*

[GPU] Prevent using usm_device write lock_type in Loop

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/tile_ops.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_micro.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/sdpa/sdpa_kernel_micro.cpp

Update better config for thin_q and DG2 to achieve 5%-19% improvement in
token rate.  This patch only verified performance for non quantization.
Quantization option is not turn on yet.
CVS-162044

[GPU] Port SDPA micro config and some delta from oneDNN

---

src/plugins/intel_gpu/src/graph/primitive_inst.cpp

- Skip dyn_quan for unsupported case from onednn
- When FC has binary post op and it has broadcasting in f-axis, gemm generates incorrect result
- 152994

[GPU] WA: SD3.5 accuracy fix with dynamic quantization

---

src/plugins/intel_npu/src/plugin/src/properties.cpp

- marking internal_supported_properties private, mistakenly marked publish by recent refactoring
- *ticket-id*

[intel-npu] marking internal_supported_properties private

---

src/plugins/intel_npu/src/al/include/intel_npu/config/options.hpp

- marking defer_weights_load property public (made private by mistake)
- *ticket-id*

[intel-npu] marking defer_weights_load property public 

---

src/frontends/onnx/frontend/src/op/com.microsoft/matmulnbits.cpp

- Explicitly cast operand to float to prevent misalignment
- 157249

[ONNX] Fixed floating point workflow

---

src/frontends/onnx/frontend/src/op/dequantize_linear.cpp
src/frontends/onnx/tests/models/dequantize_linear_21_cw.prototxt
src/frontends/onnx/tests/models/dequantize_linear_21_no_zero_point_cw.prototxt
src/frontends/onnx/tests/onnx_import_quant.in.cpp

- when DequantizeLinear OP met requirements of NPU (sym INT4, channel-wised Quantization) the performance raised a lot
// For NPU Optimization
// reference: https://github.com/openvinotoolkit/openvino.genai/tree/master/samples/python/text_generation#npu-support
//  1. model must be exported with symmetric INT4 quantization.
//  2. The quantized LLM MatMul Op need to use Channel-wised quantization for better performance. (block_size = K)
// with the limitation, the NPU vpux-plugin compiler could use mix-precision matmul with i4 weight input.
// it raised the performance a lot in NPU.
This PR is going to optimize the decomposition OPs in ONNX frontend (DequantizeLinear) to match the NPU optimize pattern, before this PR, the INT4 phi3 onnx model using NPUW runs:
`1st token 8000ms, 2nd token …

[ONNX] Added dequantize linear channel wise pattern

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/functional/remote_tensor_tests/gpu_remote_tensor_tests.cpp

- Some models have a dequantization pattern like
input(constant) --> reshape --> convert --> multiply
- `KeepConstPrecision` pass cannot work for the input due to the reshape.
- So, this PR updated to execute `KeepConstPrecision` one more time after `ConstantFolding`
- 167671

[GPU] support for 4bit qdq models

---

.github/workflows/clang_tidy.yml

- Should fix https://github.com/openvinotoolkit/openvino/actions/runs/15119713191/job/42499011503#step:6:1
- *167893*

[CI] [GHA] Skip the `handle_docker` step if the pipeline should be skipped

---

src/plugins/intel_npu/tools/protopipe/src/simulation/ov_layers_reader.cpp

- *Modified 'extractLayerNames' so it also sets a name to tensors in case they don't have one*
- *EISW-167740*

[Protopipe] Workaround for nameless tensors

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_micro.cl

When using with paged_attention option, the sdpa_micro kernel crash with out of resources.
CVS-162044

[GPU] Fix sdpa_micro kernel crash in BMG

---

src/plugins/intel_gpu/src/kernel_selector/kernels/scatter_update/scatter_elements_update_kernel_ref.cpp

- Redundant cast removed
- [*CVS-167165*](https://jira.devtools.intel.com/browse/CVS-167165)

[GPU] Coverity fixes

---

src/plugins/intel_gpu/include/intel_gpu/plugin/plugin.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/remote_context.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/device.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/device_info.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/device_query.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_gpu/src/plugin/remote_context.cpp
src/plugins/intel_gpu/src/runtime/device_query.cpp
src/plugins/intel_gpu/src/runtime/engine.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.hpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp
src/plugins/intel_gpu/tests/unit/module_tests/device_test.cpp
src/plugins/intel_gpu/tests/unit/module_tests/usm_memory_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/cl_mem_input_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convert_color_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/variable.cpp
src/plugins/intel_gpu/tests/unit/test_utils/test_utils.cpp
thirdparty/dependencies.cmake
thirdparty/ocl/CMakeLists.txt

- Implement on-demand device initialization to prevent unused devices from being active
- These changes adjust the logic to obtain device information once during plugin initialization step, then remove cl::Device and cl::Context handles to avoid keeping devices in active mode. cl::Device and cl::Context will be initialized only when the device is used for inference by matching the device UUID with all available devices (and will remain active afterward in current implementation)
- [CVS-166110](https://jira.devtools.intel.com/browse/CVS-166110)

[GPU] Implement on-demand device initialization

---

docs/articles_en/openvino-workflow-generative/inference-with-optimum-intel.rst
src/plugins/intel_gpu/include/intel_gpu/runtime/internal_properties.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/options.inl
src/plugins/intel_gpu/src/graph/dynamic_quantize.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp
src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp

- Enable per-token dynamic quantization on GPU with systolic array
- Skip dynamic quantization when batch size <= 64 because it has performance overhead.
- 152994

[GPU] Enable per-token dynamic quantization by default

---

src/common/transformations/include/transformations/op_conversions/group_query_attention_decomposition.hpp
src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
src/core/dev_api/openvino/op/group_query_attention.hpp
src/core/src/op/group_query_attention.cpp

The KV cache handling logic differs between dynamic and static shapes.
In the case of dynamic shapes, the KV cache buffer only holds valid data. So it only needs a ConcatOP
For static shapes, the valid data is stored at the end of the buffer, with the beginning of the buffer being set to 0. So the ConcatOP will make the buffer greater than buffer size, it need slice the real size data.
The following scripts work for both CPU GPU (dynamic) and NPU (static)
```
import onnxruntime as rt
import os
import numpy as np
import time
import onnxruntime.tools.add_openvino_win_libs as utils
utils.add_openvino_libs_to_path()
from transformers import PreTrainedTokenizerFast
LOOP_TIME = 2
NUM_INFERENCE = 16 # how many 2nd token
def get_average_time(time_list):
return (sum(time_list) - max(time_list) - …
```

[Op][Transformations] Adjustment of internal GQA op shape infer and decomposition to Enable NPU

---

.github/workflows/clang_tidy.yml

Unblock clang-tidy build pipeline after changes in `openvino/core/version.hpp`
- N/A

[CI] Disable faster build on clang-tidy job

---

src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/common/src/sync_infer_request.cpp
src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_utils.hpp

- *Treat the boolean type as u8*
- *If ZE_GRAPH_ARGUMENT_PRECISION_BOOLEAN is reported by the driver, the plugin will fail to convert to an element type*
- *Too many type conversions to keep updated when a new type is supported. Removing unnecessary conversions*
- *E#167996*

[NPU] Treat the boolean type as u8 and remove unnecessary type conversions

---

src/plugins/intel_cpu/src/nodes/executors/convolution_implementations.cpp
src/plugins/intel_cpu/src/nodes/executors/debug_messages.hpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/conv_u8s8f32.cpp

It is expected that int8 convolution should always use nspc layout

[CPU] Always select nspc layout for int8 Convolution

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/include/batch_headers/tile_ops.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_micro.cl
src/plugins/intel_gpu/tests/unit/test_cases/sdpa_gpu_test.cpp

- *Fix attn mask tile loading issue when attn mask shape has single query dimension [batch, num_heads, 1, sequence_length of k]*
- *166691*

[GPU] Fix accuracy issues for sdpa_micro

---

src/common/low_precision_transformations/tests/mark_dequantization_subgraph_transformation.cpp
src/common/transformations/src/transformations/low_precision/mark_dequantization_subgraph.cpp

- This PR updates the matching logic of KeepDequantizationPrecision transformation pass to be applied only to constant nodes

[GPU] Limit KeepDequantizationPrecision transformation to subgraphs containing only constant nodes

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- Currently, when feature size of convolution's input or output is 4, OneDNN's ocl_ref kernel is used, and it degrades performance of some models (e.g. Stable Diffusion 1.5)
- This PR updates `layout_optimizer` to select `bfyx` and makes the convolution layers to use OneDNN's jit kernel in this case.
- 161941

[GPU] select bfyx for OneDNN convolution when feature size is 4

---

src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/riscv64/jit_uni_eltwise_generic.cpp
src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/classes/activation.cpp

- *Create fp32 Sqrt operation JIT Emitter for RISCV64 platform with RVV1.0 support*
- *Implement JIT Emitter in the JIT Executor*
- *Modify RISCV64 kernel to apply developed JIT emitter*
- ***Pass**: Verified with QEMU test ../bin/riscv64/Release/ov_cpu_func_tests --gtest_filter="*smoke*Activation*Sqrt*"
https://github.com/openvinotoolkit/openvino/issues/30246

[RISCV64] Implement CPU plugin just-in-time emitter for Sqrt operation

---

cmake/developer_package/vs_version/vs_version.cmake

- OV_VS_VER_COPYRIGHT_STR update to dynamic string based on OpenVINO_VERSION_MAJOR, so we don't need to manually update it every year

vs_version.cmake: OV_VS_VER_COPYRIGHT_STR update to dynamic string

---

src/plugins/intel_cpu/src/emitters/snippets/x64/jit_brgemm_emitter.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_utils.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_utils.hpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/enforce_precision.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/remove_converts.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/remove_converts.hpp
src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/mha.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/fully_connected.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/matmul.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/mha_wo_transpose.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/transpose_matmul.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/utils.hpp
src/tests/ov_helpers/ov_snippets_models/src/subgraph_matmul.cpp

- *Added support BF16, FP16 MHA tokenization on x64 platforms with `avx2_vnni_2` ISA*
- *150682*

[Snippets][CPU] Supported bf16, fp16 MHA on LNL

---

docs/articles_en/get-started/install-openvino/install-openvino-linux.rst

- The links provided for installing OpenVINO via Docker and Conan Package Manager were swapped. This change fixes this issue.
- N/A

[DOCs] Correct OpenVINO install links for Docker and Conan

---

src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.cl
src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.cpp
src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp

- This PR updates group_normalization_fsv16 to use SIMD32 for better performance.
- 161941

[GPU] updates group_normalization_fsv16 to use SIMD32

---

src/plugins/intel_npu/tests/functional/behavior/compiled_model/blob_compatibility.cpp
src/plugins/intel_npu/tests/functional/behavior/compiled_model/import_export.cpp
src/plugins/intel_npu/tests/functional/behavior/ov_plugin/internal_properties_tests.cpp
src/plugins/intel_npu/tests/functional/common/npu_test_env_cfg.hpp
src/plugins/intel_npu/tests/functional/common/utils.hpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_plugin/core_threading_tests.cpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests.xml
src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp

- *The following tests will be activated:*
- *`CoreThreadingTest.smoke_QueryModel` (Windows + Linux, but not Windows with PV driver)*
- *`CoreThreadingTestsWithIter.smoke_CompileModel` (Windows only)*
- *`CoreThreadingTestsWithIter.nightly_AsyncInfer_ShareInput` (Windows only)*
- *112064*

[`intel-npu`] [`Functional Shared Behavior Tests`] Activate skipped core threading tests

---

src/plugins/intel_cpu/src/nodes/kernels/scaled_attn/executor_pa.cpp

- *LLMPipeline shows Non deterministic CPU inference results on Xeon(e.g. GNR) platforms, the output difference comes from CPU PA implement kernels, currently it use threads number to split processing data blocks which may variant during inference iterations*
- *CVS-164155*

fix LLMPipeline Non deterministic CPU inference issue

---

src/inference/include/openvino/runtime/core.hpp
src/inference/tests/functional/ov_core_test.cpp
src/tests/test_utils/functional_test_utils/include/functional_test_utils/test_model/test_model.hpp
src/tests/test_utils/functional_test_utils/src/test_model/test_model.cpp

- Enhance read_model function overloads to support wchar_t paths
- [CVS-168219](https://jira.devtools.intel.com/browse/CVS-168219)

[Core][Unicode] read_model supports std::filesystem::path initialized with type std::wstring

---

docs/articles_en/get-started/install-openvino/configurations/configurations-intel-gpu.rst
docs/articles_en/get-started/install-openvino/install-openvino-docker-linux.rst

- *item1*
- *...*
- *ticket-id*

[DOCS] Add docker link

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
src/plugins/intel_gpu/tests/unit/test_cases/paged_attention_gpu_test.cpp

There is some mismatch between sliding window implementation in pagedAttention with SDPA attention mask.  The pagedAttention for multi token is off by one row.

[GPU] Match sliding window calculation between pagedAttention and SDPA

---

src/inference/tests/functional/ov_core_threading.cpp

- Disable CoreThreadingTests.RegisterPlugins test, because it sporadically crashes on Windows. Obvious solution was not found. Disabled until is fixed
- CVS-133087

Disable sporadicaly failing test on Windows

---

docs/documentation_build_instructions.md
docs/scripts/install_appropriate_openvino_version.py

- Script for building Python API documentation was using the deprecated [openvino-nightly](https://pypi.org/project/openvino-nightly/) PyPI module.
- Replace old command with `pip install --pre openvino --extra-index-url
https://storage.openvinotoolkit.org/simple/wheels/nightly`
- Download Python GenAI nightly from Simple PyPI if `-DENABLE_GENAI_API=ON`
- [CVS-165961](https://jira.devtools.intel.com/browse/CVS-165961)

[Py OV] [DOCS] Remove use of openvino-nightly PyPI module

---

src/plugins/intel_npu/tools/single-image-test/main.cpp

* Introduced a new function `parseInputFiles` to match model input names with input file specifications. This ensures all inputs are specified or none, and detects duplicates. The function returns a semicolon-delimited string of input file values ordered to match the model inputs. 
- E-166781

[NPU] Single Image Test - Add possibility to pass input files using input layer names

---

src/frontends/ir/src/ir_deserializer.cpp

Avoids possible stack overflow on large models by using a non-recursive depth-first search.

Avoid using recursion for search to prevent stack overflow

---

cmake/developer_package/cross_compile/python_helpers.cmake
src/bindings/python/src/pyopenvino/CMakeLists.txt
src/bindings/python/src/pyopenvino/frontend/frontend_module.cmake
src/bindings/python/src/pyopenvino/pyopenvino.cpp

- Introduce a new cmake option `ENABLE_NO_GIL_PYTHON_API`, which allows to build free-threaded OV Python API.
- Requires python3.13t+
- CVS-164541

[PyOV] Enable free-threaded python build

---

tests/requirements_pytorch

**Details:** optimum interface has been changed and no longer compatible with the current optimum-intel version. Need to update optimum-intel.
**Ticket:** 169173

Update optimum-intel for validation

---

src/inference/include/openvino/runtime/core.hpp
src/inference/tests/functional/ov_core_test.cpp
src/inference/tests/functional/ov_extension_test.cpp
src/tests/test_utils/common_test_utils/src/file_utils.cpp
src/tests/test_utils/functional_test_utils/include/functional_test_utils/test_model/test_model.hpp
src/tests/test_utils/functional_test_utils/src/test_model/test_model.cpp

- Using `if constexpr`  instead additional template function for `read_model ` API
- CVS-168219

[Core][Unicode] Refactor model path handling for read_model

---

src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm_copy_b.cpp

Fix "Conditional jump or move depends on uninitialised value(s)" error
```
==2061018== Thread 4:
==2061018== Conditional jump or move depends on uninitialised value(s)
==2061018==    at 0x8D46DC3: dnnl::impl::cpu::x64::matmul::jit_brgemm_matmul_copy_b_transposed_t<Xbyak::Ymm>::generate()::{lambda(bool, bool)#1}::operator()(bool, bool) const (brgemm_matmul_copy_utils.cpp:4312)
==2061018==    by 0x8D474BE: dnnl::impl::cpu::x64::matmul::jit_brgemm_matmul_copy_b_transposed_t<Xbyak::Ymm>::generate() (brgemm_matmul_copy_utils.cpp:4367)
==2061018==    by 0x8D0AD86: dnnl::impl::cpu::x64::jit_generator::create_kernel() [clone .part.0] (jit_generator.hpp:2835)
```
- 169031

[Snippets][CPU] Fix uninitialized value jump reported by valgrind

---

src/plugins/intel_gpu/src/kernel_selector/kernels/mvn/mvn_kernel_bfyx_opt.cpp
src/plugins/intel_gpu/tests/unit/test_cases/mvn_gpu_test.cpp

- *When fused ops and MVN have different shapes, such as MVN input0 [2, 990, 2048] and fused ops [2, 1, 2048], fused indices may result in out-of-bounds access for fused inputs, causing accuracy issues.*
- *To resolve this, enable boundary checks when fused ops and MVN have different shapes or when the MVN kernel is a shape-agnostic kernel.*
- *Add unit test*
- *166691*

[GPU] Fix MVN fusion accuracy issue

---

src/plugins/intel_gpu/src/graph/reorder.cpp
src/plugins/intel_gpu/tests/unit/passes/reorder_inputs_test.cpp

- Add bzyxf input format for tensor transform in reorder calc output layout
- 168257

[GPU] Add bzyxf input format for tensor transform in reorder calc output layout

---

cmake/developer_package/features.cmake
cmake/developer_package/plugins/plugins.cmake

Usage:
```bash
$ cmake -DENABLE_CLANG_TIDY=ON -DENABLE_CLANG_TIDY_FIX=ON ..
```
- N/A

[CLANG-TIDY] Add cmake option to automatically apply clang-tidy remarks if possible

---

src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.hpp
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/kernels/riscv64/jit_uni_eltwise_generic.cpp

- *Implement Jit Emitter for LessEqual*
- #30252
-  Test Result

[RISCV64]: Implement CPU plugin just-in-time emitter for LessEqual operation 

---

tests/e2e_tests/requirements.txt

- Instead of https://github.com/openvinotoolkit/openvino/pull/31025, which can't be rebased
- https://github.com/openvinotoolkit/open_model_zoo/pull/4016 has been merged, which should fix the pip conflicts check
- N/A

[PyOV] Bump pytest to `8.4.1`

---

src/common/transformations/src/transformations/sdpa_to_paged_attention/position_ids_replacer.cpp
src/common/transformations/tests/op_conversions/sdpa_to_paged_attention_test.cpp

- Extended `PositionIDsReplacerQwen` pattern to optionally match Convert and Reshape node that may appear between negation constant and Multiply operation. This handles cases where ConstantFolding has not removed these intermediate nodes.
- *[CVS-168361](https://jira.devtools.intel.com/browse/CVS-168361)*

[TRANSFORMATIONS] Extended PositionIDsReplacerQwen pattern to optionally match Convert and Reshape nodes

---

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
src/plugins/intel_gpu/tests/unit/passes/add_required_reorders_test.cpp

- It needs to call `recalc_output_layout(false)` after `invalidate()` by `recalc_output_layout(true)` from a new reorder node so that it prevents `valid_output_layouts` of the next node to be false.
- 168629

[GPU] Fix runtime error when mvn requires alignment

---

src/common/snippets/tests/src/pass/collapse_subgraph.cpp
src/common/snippets/tests/src/pass/mha_tokenization.cpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/aarch64/snipptes_mark_skipped.cpp
src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/snipptes_mark_skipped.cpp
src/tests/ov_helpers/ov_snippets_models/include/snippets_helpers.hpp

- Add `execute_and_validate_function` function to apply common subgraph operations across the tests
- Get rid of model setting code duplications in snippets tests
- N/A

[Snippets] Simplify subgraph tests body

---

src/plugins/intel_gpu/src/graph/impls/ocl/scaled_dot_product_attention.cpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp

- Add canonicalization check for attention mask shape. Previously, using an attention mask with rank less than 4 could lead to kernel compilation errors and incorrect indexing. However, according to SDPA specification, it can be either at least 2-dimensional or empty if it is to be ignored
- Related transformation PRs that squeeze attention mask in some cases: https://github.com/openvinotoolkit/openvino/pull/31089 and https://github.com/openvinotoolkit/openvino/pull/30659 
- [CVS-165700](https://jira.devtools.intel.com/browse/CVS-165700)
- [CVS-169359](https://jira.devtools.intel.com/browse/CVS-169359)

[GPU] Add canonicalization for attention mask shape with rank less than 4

---

src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/dynamic/transpose_matmul_fusion.cpp

- Fix mismatched transpose order in transpose fusion of transformation to align with onednn gemm input/output transpose
- 168234

[GPU] Fix mismatched transpose order in transpose fusion of transformation

---

src/plugins/intel_cpu/tests/unit/snippets_transformations/x64/fuse_brgemm_cpu_postops.cpp
src/tests/ov_helpers/ov_snippets_models/src/subgraph_mha.cpp

Replace deprecated `ov::Model` constructor that uses `NodeVector` for outputs with `ov::Model` constructor that uses `OutputVector`
- N/A

[Snippets] Replace deprecated ov::Model ctor in tests

---

src/bindings/js/node/src/compiled_model.cpp
src/bindings/js/node/src/core_wrap.cpp
src/bindings/js/node/tests/unit/basic.test.js

- It was not possible to check the type of `CompiledModel` object returned by `core.compileModel()`, because it was incorrectly wrapped.
- Unskip test `it.skip('compileModel() returns a Promise of CompiledModel', async () => {`
- [CVS-167943](https://jira.devtools.intel.com/browse/CVS-167943)

[OV JS] Fix compileModel() return type

---

src/plugins/intel_gpu/src/graph/impls/onednn/reduce_onednn.hpp
src/plugins/intel_gpu/tests/unit/fusions/reduce_fusion_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/reduce_gpu_test.cpp

- Add plain format support in reduce onednn impl manager
- Because current onednn uses non-ref kernel for plain format input.
- After this change, reduce layer is selected to ocl:combine_u8 from ocl_impl ref kernel and performance improved 8 times in the model of 169226.
- 169226

[GPU] Add plain format support in reduce onednn impl manager

---

src/frontends/onnx/frontend/src/op/com.microsoft/simplified_layer_normalization.cpp

current implementation will failed when stash_type not match X's element type, for example stash type is fp32, X is fp16

[ONNX] Fixed type casting issue in SimplifiedLayerNormalization

---

src/common/transformations/src/transformations/common_optimizations/sdpa_fusion.cpp
src/common/transformations/tests/common_optimizations/sdpa_fusion_test.cpp

Rewritten and parameterized SDPA unit tests.
Significantly increased test coverage.
Fixed an issue when Q or V are outputs of a multi-output operation (e.g., Split).
Fixed an issue where a Transpose was replaced with a Reshape operation.
- *CVS-169415*
- *CVS-166822*

SDPAFusion: bug fix and testing

---

src/plugins/intel_gpu/src/graph/registry/convolution_impls.cpp

This reverts commit 8e4cc9eb2e55f4f2504f755f46d7a67eb936f710.
- Currently implicit padding is not updated in shape agnostic kernel.
- For convolution, shape agnostic kernel is available only for explicit padding.
- 169416

Revert "[GPU] enable dynamic shape conv on compile graph pass (#30944)"

---

src/plugins/intel_gpu/src/graph/include/program_helpers.h
src/plugins/intel_gpu/src/graph/network.cpp
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/graph/program_helpers.cpp

There is a strategy to reuse memory for some intermediate outputs. However, it is recognized after the allocation of memory for all intermediate outputs. Therefore, the peak memory is not actually reduced. This PR is to address this problem which can reduce memory footprint for some models, for example 35% memory reduction for SD1.5 vae_decoder model when generating 512*512 images.
- [CVS-169229](https://jira.devtools.intel.com/browse/CVS-169229)

[GPU] Avoid memory allocation for any node can reuse previous memory

---

src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/deconvolution_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/impls/onednn/reorder_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/utils.hpp
src/plugins/intel_gpu/src/runtime/layout.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/deconvolution_gpu_test.cpp

- Previously, 3D tensors for oneDNN 1D convolution were forcefully expanded to 4D.
- This caused shape mismatches between node and impl, breaking model cache.
- Modified to keep 3D tensors as-is when both input and output are 3D.
- Excluding cases where input/output is already blocked.
- src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp:
- src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
convolution_gpu_onednn.spatial_1d
deconvolution_gpu_onednn.spatial_1d
- *168091*

[GPU] Use 3D shape for onednn 1D convolution

---

src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/convolution.cpp

- Add a functional test for implicit padding in dynamic convolutions.
- The implicit padding is updated after calling `update_shape_info_tensor()` in primitive_inst.cpp.
- That means a shape agnostic kernel of convolution doesn't work well with implicit padding.
- For this reason, if a shape agnostic kernel is selected when there is implicit padding, the accuracy drop occurs. 
- So this test is to ensure that `dynamic_impls` is not chosen for implicit padding in convolution.
- [convolution_impls.cpp](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/graph/registry/convolution_impls.cpp#L28)
- [PR#31185](https://github.com/openvinotoolkit/openvino/pull/31185)
- 169416

[GPU] Add func test for implicit padding in dynamic convolution

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp

- If crop is buffer-fused with data padding, the user, gemm node would select ref kernel instead of tiled_opt which is better for performance.
- Hot to solve: Add a condition to check possibly crop padding at match step of crop buffer fusing
- openvino/src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp program_helpers::do_for_types<crop>() could add paddings when crop buffer optimized out is done
- openvino/src/plugins/intel_gpu/src/kernel_selector/kernels/gemm/gemm_kernel_tiled_opt.cpp validate() func doesn't support paddings for f,x,y
- onenote: "GPU-Dev3.one#timm_eca_halonext26ts"
- *166822*

[GPU] Disable crop buffer fusing for better perf

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl
src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_ref.cl
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/scaled_dot_product_attention.cpp

- After this PR(https://github.com/openvinotoolkit/openvino/pull/31159) is applied, SDPA block of cross attention for Whisper decoder is fused. Accordingly, attention mask input is added as scalar value, but there is an issue that SDPA kernel does not properly handle the input argument index when the scale has input
- Fix to handle runtime scale value with scalar attention mask and scale input for SDPA
- [sdpa_opt.cl#L145](https://github.com/openvinotoolkit/openvino/blob/81b12888af9ca39b18e1a13dca49428f9437acfd/src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl#L145)
- [sdpa_opt.cl#L728](https://github.com/openvinotoolkit/openvino/blob/81b12888af9ca39b18e1a13dca49428f9437acfd/src/plugins/intel_gpu/src/kernel_selector/cl_kernels/sdpa_opt.cl#L728)
- …

[GPU] Handle runtime scale value with scalar attention mask and scale input for SDPA

---

src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/execute.py

[execute(executor="strictly_openvino")](cci:1://file:///d:/Github/openvino/src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/execute.py:46:0-59:25) crashed with  
`TypeError: openvino_execute() missing 1 required positional argument: 'partition_id'`.
The internal helper [openvino_execute()](cci:1://file:///d:/Github/openvino/src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/execute.py:73:0-116:19) expected `partition_id` but its sole external caller (strictly-openvino path) didn’t supply one. This made the “strictly_openvino” mode unusable.
Added a default value (`partition_id: int = 0`) to the function signature:
```python
def openvino_execute(
gm: GraphModule,
*args,
executor_parameters=None,
partition_id: int = 0,   # new default
options=None,
):
```
No logic …

Fix missing default partition_id in openvino_execute

---

src/plugins/intel_gpu/include/intel_gpu/graph/fused_primitive_desc.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/include/to_string_utils.h
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/unit/fusions/convolution_fusion_test.cpp

- Add binary_div post-op for oneDNN because oneDNN v3.9.0 supports it.
> RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:223:
> Check 'false' failed at src/plugins/intel_gpu/src/graph/program_node.cpp:1640:
> Unsupported eltwise mode: 4. divide:__module.model.git.encoder.layer.0.attention.self/aten::div/Divide is fused node of gemm:__module.model.git.encoder.layer.0.attention.self/aten::matmul/MatMul
- Pytorch frontend has disabled divide conversion since [PTFE div translation](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/pytorch/src/op/div.cpp#L49).
- This was not a problem on iGPU because GPU Plugin supported eltwise fusion for division.
- On the other hand, it was being handled as an exception for oneDNN in …

[GPU] Add binary_div post-op for oneDNN

---

src/plugins/intel_gpu/src/plugin/ops/reshape.cpp
src/plugins/intel_gpu/tests/functional/subgraph_tests/reshape_group_convolution.cpp

- Fix create reshape op to avoid different input/output rank of onednn weight reorder
- reorder node has different input dim(4d) and output dim(5d) during graph optimization. It causes reorder onednn primitive descriptor creation failure.
- IR has reshape(4d->5d) in group convolution weight branch. In this case, current CreateReshapeOp() adds reorder primitive  prior to reshape to handle format change. As bfzyx format means 5d shape, reorder output has 5d shape and reshape becomes to have identical input/output layout. After that reshape was removed.
-  (https://github.com/openvinotoolkit/openvino/blob/d93f4edf7206ac513447e6e9cb58ace6918bf2a9/src/plugins/intel_gpu/src/plugin/ops/reshape.cpp#L76)
- ./benchmark_app -d GPU.1 -m ONNX_Runtime_MobileNet_qlinear_IR_v11_FP16_batch_1.xml
- Issue …

[GPU] Fix create reshape op to avoid different input/output rank of onednn weight reorder

---

src/common/snippets/tests/include/pass/movebroadcast.hpp
src/common/snippets/tests/src/pass/movebroadcast.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/codegen_gelu.cpp
src/tests/functional/plugin/shared/include/snippets/codegen_gelu.hpp
src/tests/functional/plugin/shared/src/snippets/codegen_gelu.cpp
src/tests/ov_helpers/ov_snippets_models/include/subgraph_gelu.hpp
src/tests/ov_helpers/ov_snippets_models/include/subgraph_movebroadcast.hpp
src/tests/ov_helpers/ov_snippets_models/src/subgraph_gelu.cpp
src/tests/ov_helpers/ov_snippets_models/src/subgraph_movebroadcast.cpp

- Extract `movebroadcast` and `codegen_gelu` test subgraphs to the common snippets subgraphs location
- Unify these tests with snippets tests infra to resolve corresponding "todo" remarks
- N/A

[Snippets][TESTS] Refactor movebroadcast and codegen_gelu tests

---

.github/workflows/cleanup_caches.yml

Small runner doesn't have docker installed; while cleanup workflows use it.

[GHA] Switch cleanup_caches to medium runners & Ubuntu 24 base image

---

.github/workflows/clang_tidy.yml

Include the `-k 0` option in every clang-tidy invocation in `.github/workflows/clang_tidy.yml` so that checks continue through all clang-tidy remarks and emit a complete set of diagnostics in CI.
- N/A

[GHA][CLANG-TIDY] Add `-k 0` flag for build commands

---

.github/workflows/update_pyapi_stubs.yml

- Testing the `openvino_provider` util in fork is not possible, PRs to master are needed
- The current implementation fails with `FileNotFoundError: [Errno 2] No such file or directory: '/mount/.../master/commit/latest_public_linux_ubuntu_22_04_x86_64_release.txt'`
- This PR closely matches the usage of `openvino_provider` to example given in https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/ci/github_actions/openvino_provider.md
- N/A

[PyOV][GHA] Change stubgen runner to Azure

---

src/common/snippets/.clang-tidy
src/plugins/intel_cpu/src/.clang-tidy
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/def_conv.cpp
src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_convolution_primitive.hpp
src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_fullyconnected_primitive.hpp
src/plugins/intel_cpu/src/nodes/executors/dnnl/dnnl_matmul_primitive.hpp
src/plugins/intel_cpu/src/nodes/executors/executor.hpp
src/plugins/intel_cpu/src/nodes/executors/executor_implementation.hpp
src/plugins/intel_cpu/src/nodes/eye.h
src/plugins/intel_cpu/src/nodes/fake_quantize.h
src/plugins/intel_cpu/src/nodes/kernels/x64/brgemm_kernel.hpp
src/plugins/intel_cpu/src/nodes/scaled_attn.h
src/plugins/intel_cpu/src/utils/ngraph_utils.hpp

- Fix "readability-const-return-type" remarks reported by clang-tidy
- Enable "readability-const-return-type" clang-tidy checks on CI by default
- N/A

[CPU] Apply 'readability-const-return-type' clang-tidy remarks

---

tests/layer_tests/tensorflow_tests/test_tf_RandomUniform.py

- enabled tests, since GPU works
- *CVS-156056*

[bug][GPU]: RandomUniform inference results do not match TF ones on GPU

---

src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm_copy_b.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/external_repacking_adjuster.cpp

- *`compute_K_blocked_stride` returns `uint` value in updated code lines - so no need to compare returned `LDB` value with `0` since `uint` is always greater or equal to zero*
- *170135*

[Snippets][CPU] Fixed coverities <compares unsigned to 0>

---

src/plugins/intel_cpu/src/utils/debug_capabilities.cpp

- Fix unused exception variable warning during the build with debug caps on Windows platform 
- N/A

[CPU][DEBUG CAPS] Fix Windows build w/ debug caps

---

src/plugins/intel_cpu/src/memory_desc/cpu_blocked_memory_desc.cpp
src/plugins/intel_cpu/src/memory_desc/dnnl_blocked_memory_desc.cpp

- *If `BlockedDims` have rank less than `Shape` in constructors in CPU/DNNL BlockedMemoryDesc, we will get out-of-bounds access in check for dynamic blocks. The PR adds the checks `blockedDims.size() < shape.getRank()` with exception throwing in the   CPU/DNNL BlockedMemoryDesc ctors*
- *N/A*

[CPU] Added rank check in CPU/DNNL BlockedMemoryDesc constructors

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- After this PR(https://github.com/openvinotoolkit/openvino/pull/30993), the preferred format of convolution is selected to `b_fs_yx_fsv16` and the input tag of onednn conv is selected as blocked format w/ b16 even if the input channel is small (e.g. IC<=4), which causes unnecessary computation cost.
- Update preferred format selection logic to select planar format for input and output respectively
```
benchdnn.exe --verbose=5 --mode=p --cold-cache=wei --memory-kind=usm_device --conv --reset --allow-enum-tags-only=0 --engine=gpu --dir=FWD_I --alg=direct --dt=f16:f16:f16 --bia-dt=f16 --stag=aBcd16b --wtag=any --dtag=abcd --attr-scales= --attr-zero-points= --attr-scratchpad=user mb1_ic3oc1152_ih896oh64kh14sh14dh0ph0_iw896ow64kw14sw14dw0pw0
```
```
benchdnn.exe --verbose=5 --mode=p …
```

[GPU] Update preferred format selection for dynamic onednn convolution for VLMs

---

src/plugins/intel_cpu/src/emitters/plugin/x64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/nodes/kernels/jit_eltwise_common.cpp

- The current `selectOP` needs to do type conversions: int32 -> fp32 -> int32.
- Those convertion are not necessary
- INT_MAX will be INT_MIN after this conversion. This will cause accuracy issue.
- *CVS-169898*

[CPU] Fix the select OP parameter convert wrong value issue

---

src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp

Details:
Rewrite the RoPEFusionIOSlicing transformation using new Symbolic approach allowing for greater flexibility and more convenient pattern design.
Tickets:
CVS-170021
Signed-off-by: Andrii Staikov [andrii.staikov@intel.com](mailto:andrii.staikov@intel.com)

[TRANSFORMATIONS] Rewrite RoPEFusionIOSlicing using new Symbolic approach

---

.github/workflows/clang_tidy.yml

"Build-aarch64" and "Build-riscv64" jobs are switched from "Ninja Multi-Config" to "Unix Makefiles" generator and add `-DCMAKE_RULE_MESSAGES=OFF` to suppress Make rule messages
These changes are temporary solution related to TODO comments about adding `--quiet` after switching to Ubuntu 24.04+ (with newer ninja version that have this flag) by providing an alternative solution for Ubuntu 22.04 environments. The `-DCMAKE_RULE_MESSAGES=OFF` flag reduces build log verbosity by suppressing the rule messages that Make normally prints during compilation. `-DCMAKE_RULE_MESSAGES=OFF` is not applicable for ninja
- N/A

[GHA][CLANG-TIDY] Make workflow log less verbose in Ubuntu 22.04 scenarios

---

src/plugins/intel_cpu/src/nodes/conv.cpp
src/plugins/intel_cpu/src/nodes/executors/convolution_implementations.cpp

- *fix int8 models crash issue during inference on the GNR platform with fp16 inference_precision. int8 convolution with f16 bias is not supported in oneDNN. When bias type is f16, we need force it to f32 to ensure compatibility.*
- *CVS-169361*

[CPU] fix int8 models crash issue during inference on the GNR platform with fp16 inference_precision

---

src/common/snippets/src/lowered/pass/assign_registers.cpp

Replace linear scan through active intervals with priority queue-based approach for performance improvement. The optimization reduces algorithmic complexity while maintaining identical functionality and correctness.
Go from O(n^2) to O(n log n):
- Replace std::map<LiveInterval, Reg> with std::priority_queue for active intervals
- Eliminate O(k) linear scan in favor of O(log k) heap operations
- N/A

[Snippets] Optimize register assignment linear scan algorithm

---

src/plugins/intel_npu/src/al/include/intel_npu/icompiler.hpp

- The latest version of the compiler can't be built with the latest version of OV due to some changes brought in [this PR](https://github.com/openvinotoolkit/openvino/pull/27084). Here I'm introducing some small tweaks that re-enable this build.
- *CVS-170096*

[NPU] Fix the compiler build after merging the "weights separation" changes

---

src/inference/dev_api/openvino/runtime/iplugin.hpp
src/inference/src/dev/iplugin.cpp
src/inference/src/dev/plugin.cpp
src/inference/src/dev/plugin.hpp
src/inference/tests/functional/caching_test.cpp
src/plugins/auto/src/plugin.cpp
src/plugins/auto/src/plugin.hpp
src/plugins/auto/tests/functional/behavior/auto_func_test.cpp
src/plugins/auto_batch/src/plugin.cpp
src/plugins/auto_batch/src/plugin.hpp
src/plugins/auto_batch/tests/unit/mock_common.hpp
src/plugins/hetero/src/plugin.cpp
src/plugins/hetero/src/plugin.hpp
src/plugins/hetero/tests/functional/hetero_tests.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_cpu/src/plugin.h
src/plugins/intel_gpu/include/intel_gpu/plugin/plugin.hpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_npu/src/plugin/include/plugin.hpp
src/plugins/intel_npu/src/plugin/src/plugin.cpp
src/plugins/intel_npu/tests/functional/behavior/npuw/mocks/mock_plugins.hpp
src/plugins/proxy/src/plugin.cpp
src/plugins/proxy/src/plugin.hpp
src/plugins/proxy/tests/proxy_tests.cpp
src/plugins/template/src/plugin.cpp
src/plugins/template/src/plugin.hpp
src/tests/test_utils/common_test_utils/include/common_test_utils/file_utils.hpp
src/tests/test_utils/unit_test_utils/mocks/mock_engine/mock_plugin.cpp
src/tests/test_utils/unit_test_utils/mocks/mock_engine/mock_plugin.hpp
src/tests/test_utils/unit_test_utils/mocks/openvino/runtime/mock_iplugin.hpp

- Change plugin::import_model to get constant ov::Tensor
- Fix for https://github.com/openvinotoolkit/openvino/pull/31137
- [CVS-166953](https://jira.devtools.intel.com/browse/CVS-166953)

Change plugin::import_model to get constant ov::Tensor

---

src/plugins/intel_gpu/src/graph/impls/onednn/reduce_onednn.cpp

- The purpose of PR #31050 was to allow oneDNN convolution to directly handle 3D input tensors without expanding them to 4D.
- However, oneDNN reduce should be excluded from this change, as it is closely tied to cldnn implementation, which expects 3D tensors to be expanded to 4D.
- This PR resolves the issue by rollback the behavior of oneDNN reduce to its previous state before PR #31050.
- https://github.com/openvinotoolkit/openvino/blob/fe702efe5064fd9dd765d3eebca0cb4b3fd5d162/src/plugins/intel_gpu/src/graph/impls/onednn/reduce_onednn.cpp#L60
→ A test case is not required, as this change is a rollback to the original behavior.
→ It doesn't need.
- *170856*

[GPU] Handle 3D tensors by expanding to 4D in onednn reduce

---

src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp
src/plugins/intel_npu/src/backend/include/zero_pipeline.hpp
src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/backend/src/zero_pipeline.cpp
src/plugins/intel_npu/src/common/include/intel_npu/common/igraph.hpp
src/plugins/intel_npu/src/common/src/igraph.cpp
src/plugins/intel_npu/src/compiler_adapter/src/graph.cpp
src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp
src/plugins/intel_npu/src/utils/include/intel_npu/utils/zero/zero_utils.hpp
src/plugins/intel_npu/tests/functional/behavior/batched_tensors_tests/batched_run.cpp
src/plugins/intel_npu/tests/functional/behavior/batched_tensors_tests/batched_run.hpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.cpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/npu_skip_func_tests.xml

The clone of https://github.com/openvinotoolkit/openvino/pull/30723
Ticket: 168772
Managed to infer this case:
`./benchmark_app.exe -m <resnet-v1-50.xml> -d NPU -load_config plugin_batch_dynamic.json -shape [1..3,3,244,244] -data_shape [2,3,244,244] `
Where _plugin_batch_dynamic.json_:
```
{
        "NPU": {"NPU_BATCH_MODE": "PLUGIN"}
} 
```
Compiled with batch resized to 1:
```
func.func @main(%arg0: tensor<1x3x244x244xui8>) -> tensor<1x1000xf32> {
```
Result:
```
[ INFO ] data  ([N,C,H,W], u8, [2,3,244,244], dyn:[1..3,3,244,244]):    random (image/numpy array is expected)
...
[WARNING] 12:13:57.69 [IGraph] Networks using dynamic batch are handled by the plugin
IGraph::determine_batch_size tensors candidateBatchSize 2
[DEBUG] 12:13:57.69 [IGraph] Batching is handled by the plugin
... …
```

[NPU] Dynamic batching via BatchMode::PLUGIN 

---

src/plugins/intel_cpu/src/graph_optimizer.cpp

- *this kind of segment fault issue during model Compile comes from 'DropDoubleReorders' pass stage, during the process a new reorder node may be inserted, that will led to an UB since the range based for loop is used and the nodes vector is modified at the same time. for this kind of cases, we should switch to index based nodes vector traversal. This approach will avoids iterator invalidation issues, ensuring safe handling of nodes during the optimization process.*
- *CVS-170814 CVS-170818 CVS-170815 CVS-170816 CVS-170817*

[CPU] fix segment fault issue during model Compile

---

src/core/src/pass/manager.cpp
src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.cpp
src/plugins/intel_gpu/tests/unit/transformations/transpose_matmul_fusion_test.cpp

-  Add one condition in TransposeMatmulTranspose function to avoid fusion if Matmul is connected to more than one nodes.
- If we have Tranpose + Matmul + Tranpose pattern, the fusion happens and the ops are replaced with one gemm op with reorder inputs and reorder outputs. However, we have one case where the pattern is Transpose + Matmul + Transpose and ShapeOf. The pattern cannot be fused and the function needs to return false. 
- The subgraph consist of "ShapeOf" cannot be simplified because of dynamic shapes.
The command below with dynamic shape cause the error intoroduced in the attached jira ticket. 
`benchmark_app.exe -d GPU -niter 1 --data_shape input_points[1,3,2,2],input_labels[1,3,2],image_embeddings[1,256,64,64],image_positional_embeddings[1,256,64,64] -m …

Fix TransposeMatmulTranspose fusion for cases where Matmul is connected to more than one node.

---

src/frontends/onnx/frontend/src/op/leaky_relu.cpp
src/plugins/intel_gpu/src/plugin/ops/constant.cpp
src/plugins/intel_gpu/tests/functional/shared_tests_instances/single_layer_tests/activation.cpp

PRelu Inputs from the SPEC: https://docs.openvino.ai/2025/documentation/openvino-ir-format/operation-sets/operation-specs/activation/prelu-1.html
1: data. A tensor of type T and arbitrary shape. Required.
2: slope. A tensor of type T and rank greater or equal to 1. Tensor with negative slope values. Required.
Note: Channels dimension corresponds to the second dimension of data input tensor. If slope input rank is 1 and its dimension is equal to the second dimension of data input, then per channel broadcast is applied. Otherwise slope input is broadcasted with numpy rules, description is available in Broadcast Rules For Elementwise Operations.
JIRA: [CVS-165844](https://jira.devtools.intel.com/browse/CVS-165844)

[GPU] Fix GPU Plugin for Leaky Relu with 1D Slope Input Parameter

---

src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

- After this PR(https://github.com/openvinotoolkit/openvino/pull/30979) is applied,  runtime assertion error always occurs for 4D FC with weight compression during onednn FC impl creation
- Accuracy issue also occurs if dynamic quantization is applied to 4D FC
- Disable onednn FC dynamic quantization for 4D FC
- https://github.com/openvinotoolkit/openvino/blob/6cf44c3fc52ca27504341e0e4ad9f5aa97e8c643/src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp#L376
- https://github.com/openvinotoolkit/openvino/blob/6cf44c3fc52ca27504341e0e4ad9f5aa97e8c643/src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp#L379
- ./benchmark_app -m swin_small_patch4_window7_224-int8.xml -d GPU -hint none -niter 1 -nireq 1 -shape input[1,3,224,224]
- 170864

[GPU] Disable onednn FC dynamic quantization for 4D FC

---

src/frontends/onnx/docs/supported_ops.md
src/frontends/onnx/frontend/src/op/quantize_linear.cpp
src/frontends/onnx/frontend/src/utils/common.cpp
src/frontends/onnx/frontend/src/utils/common.hpp
src/frontends/onnx/tests/models/quantization/quantize_linear_blocksize.prototxt
src/frontends/onnx/tests/onnx_import_quant.in.cpp

- This PR tries to support the `blocksize` attribute with `reshape` operator
- *CVS-169477*

[ONNX] Added QuantizeLinear-21 operator with blocksize support

---

src/plugins/intel_gpu/src/graph/impls/cm/primitive_cm_base.hpp

- *Previous behavior of the `to_code_string()` for floating point numbers used `as_float()/as_double()` functions, which is not supported by CM kernels.*

[GPU] Added make_jit_constant override for CM kernels

---

src/plugins/intel_gpu/src/graph/include/primitive_inst.h
src/plugins/intel_gpu/src/graph/primitive_inst.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
src/plugins/intel_gpu/tests/unit/test_utils/primitive_inst_test_helper.h

This PR addresses the issue of the optimized out concat primitive where incorrect memory reuse could occur due to improper handling of the `allocation_done_by_other` flag. The affected subgraph looks like this:
```
Conv   Add
\    /
Concat (optimized_out)
```
The issue arises due to improper management of the `allocation_done_by_other` flag across iterations:
_Iteration N_: Input shape changes. Conv calls concat's `reallocate_if_needed()` and sets `allocation_done_by_other = true`. During `execute()` call, Concat resets the flag to false.
_Iteration N+1_: Input shape remains the same. Conv calls Concat's `reallocate_if_needed()` and sets the flag again, but Concat does not reset it since shape wasn't changed.
_Iteration N+2_: Input shape increases. Since the flag was not reset in the …

[GPU] Fix memory reallocation logic for optimized out concat

---

src/plugins/intel_gpu/src/kernel_selector/cl_kernels/arg_max_min_axis.cl
src/plugins/intel_gpu/src/kernel_selector/kernels/arg_max_min/arg_max_min_kernel_axis.cpp
src/plugins/intel_gpu/tests/unit/test_cases/arg_max_gpu_test.cpp

Arg max min fail to compile due to not sufficient hardware registers. There are about 4K registers per thread, switch to use global memory if result buffer exceeds register counts.
CVS-170417

[GPU] arg max min use internal buffer for large result buffer

---

src/plugins/intel_npu/src/compiler_adapter/src/weightless_graph.cpp

- Title. Just added some version checks in order to avoid calling L0 functions that are not supported by older drivers.
- *EISW-177459*

[NPU] Enabling inferences on weightless compiled models when older drivers are used

---

src/plugins/intel_npu/src/al/include/intel_npu/config/npuw.hpp
src/plugins/intel_npu/src/al/include/intel_npu/npuw_private_properties.hpp

- *Enable three-model pipeline by default*
- *EISW-177462*

Enable 3-model pipeline by default

---

src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.cpp
src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.hpp

- *Added missed checks for supported execution precision in JIT eltwise precisions*
- *Replaced `OPENVINO` macros with `OV_CPU_JIT_EMITTER` for more informative error messages*
- *Fixed JIT emitter for `LogicalAnd` for more complex kernels where `LogicalAnd` might be along other ops in the kernel*
- *Moved some instructions which might corrupt `src` register when input and output registers are the same (`src == dst`) in JIT Eltwise emitters*
- *N/A*

[RV64] Set of fixes for JIT Eltwise emitters

---

src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/graph/rms.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_bfyx_opt.h
src/plugins/intel_gpu/src/kernel_selector/kernels/rms/rms_kernel_ref.h
src/plugins/intel_gpu/tests/unit/fusions/rms_fusion_test.cpp

- Some reorders are not being optimized out due to RMS nodes which are not supporting fusing type conversion only reorders
- Allow type conversion reorder fusion for RMS
- 171226

[GPU][Qwen3-8B] Fuse type conversion only reorders to previous RMS nodes 

---

src/plugins/intel_gpu/include/intel_gpu/graph/program.hpp
src/plugins/intel_gpu/include/intel_gpu/plugin/plugin.hpp
src/plugins/intel_gpu/include/intel_gpu/primitives/data.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/internal_properties.hpp
src/plugins/intel_gpu/include/intel_gpu/runtime/options.inl
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/plugin/graph.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp

Weightless cache attributes are added when the weights are not coming from bin file. That happens for non-IR inputs like ORT.
https://jira.devtools.intel.com/browse/CVS-167691

Added weightless cache attributes for intel GPU plugin.

---

src/common/snippets/.clang-tidy

Enable clang-tidy checks that were planned to be enabled and do not require any additional changes to do so
- N/A

[Snippets] Enable desired clang-tidy checks not requiring additional changes

---

src/common/snippets/include/snippets/lowered/expression.hpp
src/common/snippets/include/snippets/lowered/loop_info.hpp
src/common/snippets/include/snippets/lowered/pass/pass.hpp
src/common/snippets/include/snippets/runtime_configurator.hpp

Replace manual `get_type_info_static` and `get_type_info` implementations with `OPENVINO_RTTI_BASE` macro in 4 snippets framework classes:
- RuntimeConfig
- LoopInfo (LoopInfoBase)
- Expression
- PassBase
- N/A

[Snippets] Replace manual RTTI implementations with `OPENVINO_RTTI_BASE`

---

src/common/transformations/include/transformations/utils/utils.hpp
src/common/transformations/src/transformations/common_optimizations/fuse_rotary_positional_embeddings.cpp
src/common/transformations/src/transformations/utils/utils.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/causal_mask_preprocess_fusion.cpp
src/plugins/intel_cpu/src/transformations/cpu_opset/common/pass/causal_mask_preprocess_fusion.hpp

Details:
Rewrite the CausalMaskPreprocess transformation using new Symbolic approach allowing for greater flexibility and more convenient pattern design.
Tickets:
[CVS-170029](https://jira.devtools.intel.com/browse/CVS-170029)
Signed-off-by: Andrii Staikov [andrii.staikov@intel.com](mailto:andrii.staikov@intel.com)

[TRANSFORMATIONS] Rewrite CausalMaskPreprocess using new Symbolic approach

---

src/plugins/intel_gpu/include/intel_gpu/primitives/resample.hpp
src/plugins/intel_gpu/tests/functional/single_layer_tests/dynamic/interpolate.cpp

- benchmark_app crashed when cache_dir is enabled due to 'scales_port' in resample is missing at save/load functions.
- 'scales_port' was fixed to 2 in old code. but it updated in [PR#26260](https://github.com/openvinotoolkit/openvino/pull/26260)
- src/plugins/intel_gpu/include/intel_gpu/primitives/resample.hpp
- $ benchmark_app -m models/ch_PP-OCRv4_det_infer/inference.xml -d GPU.1 -data_shape x[1,3,960,960] -api sync -niter 1 --cache_dir ./model_cache
- model is attached in ticket
- 171152

[GPU] apply scales_port to save/load/hash/compare functions in resample

---

src/plugins/intel_cpu/src/nodes/common/cpu_convert.cpp

- *Replace gen.movdqu(f16vec, gen.xword[src]); with gen.uni_vmovdqu(f16vec, gen.xword[src]); for better SIMD instruction set compatibility and performance. The uni_vmovdqu generates the most suitable vector move instruction (e.g., VMOVDQU, VMOVDQU32, VMOVDQU64) depending on the target architecture and register width, ensuring optimal code generation for both AVX/AVX2/AVX512.*
- *-*

[CPU] Optimize CPU convert: replace movdqu with uni_vmovdqu for better SIMD compatibility

---

src/plugins/intel_gpu/include/intel_gpu/runtime/options.inl
src/plugins/intel_gpu/src/graph/impls/ocl_v2/pa_kv_cache_update_ref.cl
src/plugins/intel_gpu/src/graph/impls/ocl_v2/sdpa/paged_attention_opt.cpp
src/plugins/intel_gpu/src/runtime/execution_config.cpp
src/plugins/intel_gpu/tests/unit/dynamic_execution/update_shape_test.cpp
src/plugins/intel_gpu/tests/unit/passes/mark_shape_of_subgraphs_test.cpp

- Improve pa_kv_cace_update 2nd+token perf (use more parallel threads for requantization)
- Set key_by_channel quantization as default mode 
- perf regression checked on BMG/DG2/LNL/MTL and it was okay
- CVS-171482

[GPU] Set key_by_channel mode as default key quantization mode

---

src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/eltwise.h
src/plugins/intel_cpu/tests/functional/custom/subgraph_tests/src/x64/powerstatic_bf16_saturation.cpp

- *Add bf16 saturation for powerStatic gamma if input precision is bf16*
- *[CVS-165421](https://jira.devtools.intel.com/browse/CVS-165421)*

[CPU]Add bf16saturation for powerStatic gamma

---

src/core/dev_api/openvino/op/paged_attention.hpp
src/plugins/intel_cpu/src/extension.cpp

- *The PagedAttentionExtension operation is created during transformations routine and serialized into the cached model. To enable deserialization of this operation need to add it to the extensions list.*
- *168337*

[CPU] Model cache. Add PagedAttentionExtension to enable deserialization of the model

---

src/plugins/intel_cpu/src/.clang-tidy
src/plugins/intel_cpu/src/edge.cpp
src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/node.h
src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/eltwise.h

- Fix detected range-loop copies in CPU graph implementation
- Mark `Node::fuseInto` as `const` (header and impl) to allow calls on `const` node pointers
- N/A

[CPU] Enable `performance-for-range-copy.WarnOnAllAutoCopies` parameter in clang-tidy

---

src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp

- *Name of the LM head model became in the same format as prefill and kvcache one*

Align name of the LM head model with prefill and kvcache

---

src/common/snippets/.clang-tidy
src/common/snippets/src/lowered/linear_ir_builder.cpp
src/core/include/openvino/core/node_output.hpp
src/core/src/node_output.cpp

- Fix detected range-loop copies in LIR builder
- Mark `Output<Node>::for_node` as `const` (header and impl) to allow calls on `const` outputs (no functional change)
- N/A

[Snippets][Core] Enable `performance-for-range-copy.WarnOnAllAutoCopies` parameter in clang-tidy

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp

- Fix PR for https://github.com/openvinotoolkit/openvino/pull/31452 regression.
- Onednn implicit concat uses memory offset. So concat axis should be always outer dimension(only F in onednn). but the white list has been removed during code clean.
- The missing ambiguous whitelist
- check_image_accuracy.py -m /mnt/shared/models/ -a ~/work/openvino1/bin/intel64/Release/benchmark_app -d GPU.1 -t unet-2d
- No graph related.
- [O] Is it a proper fix? (not a workaround) 
- [O] Did you include test case for this fix, if necessary? 
- [O] Did you review existing test that can be extended to cover this scenario? Which test did you review? concatenation_gpu_test.cpp
- *171710*

[GPU] Fix unet-2d ACC regression because of missing whitelist.

---

src/frontends/onnx/frontend/src/op/split.cpp
src/frontends/onnx/frontend/src/utils/split.cpp
src/frontends/onnx/tests/__init__.py
src/frontends/onnx/tests/tests_python/test_backend.py

- The ONNX SplitOP's split input is `optional`, and ONNX frontend didn't handle this case.
- The ONNX SplitOP allows the `(split dim % split number) != 0`. OV need to be 0.
- *CVS-169063*

[ONNX] Aligned SplitOP's expected behavior between ONNX and OpenVINO

---

src/plugins/intel_cpu/src/emitters/snippets/aarch64/kernel_executors/gemm.cpp
src/tests/functional/plugin/shared/include/snippets/matmul.hpp
src/tests/functional/plugin/shared/src/snippets/matmul.cpp

- Fix handling negative values in Gemm executor that uses KleidiAI on aarch64
- Enable testing of Matmul on randomly generated tensor data including negative numbers
- required for 167005

[Snippets][CPU] Fix handling negative numbers in Gemm executor, adjust its testing scenarios

---

src/plugins/intel_npu/tests/functional/shared_tests_instances/npu_skip_func_tests.xml

- Enables perfCountWereNotEnabledExceptionTest and canRun3AsyncRequestsConsistently
- E#125086

[IE-MDK][NPU] Enable canRun3RequestsConsistently tests

---

src/plugins/intel_cpu/src/emitters/snippets/x64/kernel_executors/brgemm_copy_b.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/external_repacking_adjuster.cpp

- *2399-806, 2399-910. Underflow: The cast of LDB to a signed type could result in a negative number.*
- *172042*

Fix "Overflowed integer argument (INTEGER_OVERFLOW)" Coverity remarks

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/impls/ocl_v2/utils/fused_ops_jitter.cpp
src/plugins/intel_gpu/src/kernel_selector/jitter.cpp
src/plugins/intel_gpu/src/kernel_selector/kernels/activation/activation_kernel_opt.cpp
src/plugins/intel_gpu/tests/unit/test_cases/activation_simple_gpu_test.cpp
tests/llm/accuracy_conformance.py

- Typecast for `ActivationTypes::SoftPlus` to perform `exp(x)` on fp16.
- Do not use `activation_opt` when  `ActivationTypes` is `SoftPlus` and input data type is fp16 at the same time.
- SoftPlus : `f(x) = ln(exp(x) + 1.)`
- When performing `exp(x)` in `f(x)`, it can be overflowing the maximum of fp16.
- So it needs to typecast for `exp(x)` when input data type is fp16.
- By the way, `activation_opt` is hardcoded to loads 4 elements at a time by re-defining variable types such as `half4`.
- For this reason, typecasting in `jitter.cpp` doesn't resolve for `half4`.
- Thus, it needs not to use `activation_opt` when `ActivationTypes` is `SoftPlus` and input data type is fp16 at the same time.
- Also `SoftPlus` should not be fused for now because the node that `SoftPlus` is fused to may use …

[GPU] Fix nan values in SoftPlus

---

src/plugins/intel_cpu/src/transformations/transformation_pipeline.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
src/plugins/intel_cpu/tests/functional/shared_tests_instances/snippets/matmul.cpp

Since there is no MatMul kernel version that accepts transposed B matrix on ARM64, Transpose operation is extracted outside of MatMul
- required for 167005

[Snippets][CPU] Enable Matmul with transposed B matrix tests

---

src/plugins/intel_npu/tools/opencv_version.json
src/plugins/intel_npu/tools/protopipe/README.md
src/plugins/intel_npu/tools/protopipe/src/parser/config.cpp
src/plugins/intel_npu/tools/protopipe/src/scenario/inference.hpp
src/plugins/intel_npu/tools/protopipe/src/simulation/simulation.cpp
src/plugins/intel_npu/tools/protopipe/version.hpp.in

- *Implement output clamping based on configured output precision for all model outputs. Clamping can be enabled by setting `clamp_outputs: true` in the model parameters.*
- *EISW-168451*

[Protopipe] Add output clamping option for OpenVINO models

---

tests/llm/accuracy_conformance.py
tests/llm/conftest.py

- GPU tests are disabled due to intermittent failures
- Added harness to run test on local environment with cmdline option
- Do not setup test environment globally. It is setup when the case is about to be executed
- Ignore error during rmtree
- 172236
- 171887

Test accuracy_conformance fix

---

src/frontends/onnx/frontend/src/core/tensor.cpp
src/frontends/onnx/frontend/src/core/tensor.hpp
src/frontends/onnx/frontend/src/utils/tensor_external_data.cpp
src/frontends/onnx/frontend/src/utils/tensor_external_data.hpp
src/frontends/onnx/tests/onnx_reader_external_data.cpp

- ONNX Runtime has a magic tag \*/\_ORT_MEM_ADDR\_/\* as data location for in-memory external data, while usually the data location is a file path. OpenVINO EP only handles the file path case, if the data location is set to \*/\_ORT_MEM_ADDR\_/\* an error will be thrown.
- `D:\onnxruntime\onnxruntime\core\providers\openvino\ov_interface.cc:68 class std::shared_ptr {}cdecl onnxruntime::openvino_ep::OVCore::ReadModel(const class std::basic_string<char,struct std::char_traits,class std::allocator > &,const class std::basic_string<char,struct std::char_traits,class std::allocator > &) const [OpenVINO-EP] [OpenVINO-EP] Exception while Reading network: invalid external data: ExternalDataInfo(data_full_path: {}/{}ORT_MEM_ADDR{}/, offset: 69492618936064, data_length: 1536)`
- *CVS-163902*
- …

[ONNX FE] fix data location tag */_ORT_MEM_ADDR_/* for ORT in memory data

---

src/plugins/intel_npu/src/plugin/src/plugin.cpp

- Inside the _compile()_ method, the verbosity level of the logger is always the default one, regardless of the level registered inside the configuration file. Therefore, message such as [this one](https://github.com/openvinotoolkit/openvino/blob/aa18900396ce778dfdad611d75c5f6c1111de88a/src/plugins/intel_npu/src/compiler_adapter/src/plugin_compiler_adapter.cpp#L82) are never displayed. The expectation is that, the verbosity level passed to [_Plugin::compile_model()_](https://github.com/openvinotoolkit/openvino/blob/aa18900396ce778dfdad611d75c5f6c1111de88a/src/plugins/intel_npu/src/plugin/src/plugin.cpp#L398) matches the value used within the adapter.
- The same issue is encountered in the _Plugin::query_model()_ & _Plugin::import_model()_ methods.
- This PR fixes this issue by updating …

[NPU] Fix the logger verbosity level used within the compiler adapter

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp

- Fix PR for https://github.com/openvinotoolkit/openvino/pull/31452 regression.
- Solves a problem when using a mix of ocl and onednn impl in concat's input.
- In case of concat that uses impl type mixed together, byte offset calculation is incorrect. Earlier always calculate byte offset only all onednn impl inputs.
- ./benchmark_app -d GPU.1 -m ww21_weekly_23.0.0-10926-b4452d56304-API2.0/densenet-121/tf/tf_meta/FP16/
INT8/1/dldt/optimized/densenet-121.xml -nstreams 1 -nireq 2 -niter 1 --hint none -infer_precision f32
- No graph related.
- [O] Is it a proper fix? (not a workaround) 
- [O] Did you include test case for this fix, if necessary? 
- [O] Did you review existing test that can be extended to cover this scenario? Which test did you review? concatenation_gpu_test.cpp
- *170847*

[GPU] Fix implicit onednn concat for 64 byte misalignment regression.

---

.github/workflows/clang_tidy.yml

Optimize clang-tidy CI runs by enabling clang-tidy checks only when they are needed
- N/A

[GHA] Build clang-tidy only if files under checks are changed

---

docs/dev/build_android.md

Update build_android.md to support both Linux and macOS by:
- Add HOST_OS_TYPE variable for OS detection
- Use dynamic OS type in Android NDK/SDK download URLs
- Fix STL library path for cross-platform compatibility
- N/A

[DOCS] Make Android build instructions cross-platform compatible

---

src/bindings/python/src/pyopenvino/pyopenvino.cpp

- Fixes "Python API Stubs" in GHA
> pybind11_stubgen - [  ERROR] In openvino._pyopenvino.TensorVector.__getitem__ : Invalid expression 'ov::Tensor'
pybind11_stubgen - [  ERROR] In openvino._pyopenvino.TensorVector.__iter__ : Invalid expression 'ov::Tensor'
pybind11_stubgen - [  ERROR] In openvino._pyopenvino.TensorVector.__setitem__ : Invalid expression 'ov::Tensor'
pybind11_stubgen - [  ERROR] In openvino._pyopenvino.TensorVector.append : Invalid expression 'ov::Tensor'
pybind11_stubgen - [  ERROR] In openvino._pyopenvino.TensorVector.insert : Invalid expression 'ov::Tensor'
pybind11_stubgen - [  ERROR] In openvino._pyopenvino.TensorVector.pop : Invalid expression 'ov::Tensor'
Warning: stubgen - [WARNING] Raw C++ types/values were found in signatures extracted from docstrings.
Please …

[Py OV] Declare TensorVector after Tensor

---

src/inference/src/cache_manager.hpp
src/inference/src/dev/core_impl.cpp
src/inference/tests/functional/caching_test.cpp
src/plugins/intel_cpu/src/utils/serialize.cpp
src/plugins/template/src/plugin.cpp

- When MMAP feature disabled open model from cache as stream and don't read into tensor on core level. This read may trigger additional consumption as plugin may try read stream again.
- #31774 
- CVS-171329

[port, core] Open compiled model as file stream when MMAP disabled. 

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp
src/plugins/intel_gpu/tests/unit/test_cases/concatenation_gpu_test.cpp

- PR for release 2025.3
- symptom:
1.  Accuracy issue : regression observed in output image file
- root-cause:  Convolution recently changed its preferred formats to default formats if it has small IC or OC. By format propagation of Convolution-Concat layers, a Concat layer, 'concat:aten::cat/Concat_3', has bfzyx format with the fix. This concat optimized out as implicit concat even though its concat-axis is 2 with [1x3x17x?x?]. 
`GPU_Debug: ^[[1;34mprimitive_inst.cpp:^[[1;35m1700:^[[1;36mdo_runtime_in_place_concat: ^[[0m[In place concat] concat:aten::cat/Concat_3: can_be_optimized`
- how resolved: 
Onednn implicit concat is only selected for feature axis
- Accuracy issue : primitive_inst.cpp:1700
Missing logic to keep concat explicit
- Execute openvino notebooks/wan2.1-text-to-video
- …

[GPU] Resolve accuracy issue by implicit concat

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp

- When both input and output tensors have rank 5, applying format intended for rank 4 tensors leads to incorrect behavior.
- Although the issue could have been resolved in the referenced PR, the lack of 3D convolution handling prevented a complete fix.
- Related PR: https://github.com/openvinotoolkit/openvino/pull/30993
- https://github.com/openvinotoolkit/openvino/blob/7cc4b1a59a07ca9478373d2ebb62d88dcbd2e69e/src/plugins/intel_gpu/src/graph/layout_optimizer.cpp#L936-L972
- [V] Is it a proper fix? (not a workaround)
- [V] Did you include test case for this fix, if necessary?
- [V] Did you review existing test that can be extended to cover this scenario? Which test did you review?
- quantized_onednn_convolution_u8s8f32_weights_zp/convolution_gpu_onednn_both_shapes.quantized_onednn_convoluti …

[GPU] Enable int8 oneDNN 3D convolution in dynamic model.

---

src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
src/plugins/intel_gpu/tests/unit/onednn/utils_test.cpp

- When convolution constant weights are transposed via permute, the graph optimization replaces it with reorder.
- This causes issues for onednn reorder due to non-default format changes.
- The fix ensures format consistency when replacing permute with reorder.
https://github.com/openvinotoolkit/openvino/blob/689ab8b0685723dcd44176c468631e416b0146c3/src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp#L718-L757
- [V] Is it a proper fix?
- [V] Did you include test case for this fix? 
- [V] Did you review existing test that can be extended to cover this scenario?
- No eligible test for this.
- *168091*

[GPU] Fix reorder format mismatch in convolution weights.

---

src/plugins/intel_npu/src/plugin/npuw/llm_compiled_model.cpp

- A performance regression found on 1K prompts only when running `GENERATE_HINT : BEST_PERF` (a single submission) when RoPE caching gets enabled.
- While the actual issue should be fixed in the compiler, disable this feature for now for the shorter prompts to avoid performance degradation
- EISW-180374

NPUW: Condition RoPE caching to the cases where it is really required

---

src/plugins/intel_gpu/src/kernel_selector/kernels/fully_connected/fully_connected_kernel_gemv.cpp

- MTL run t5-small_4BIT model, fc's activation will use fmax, it will report below error, fix it by aligning the 2 input data types of fmax
- *...*
- *CVS-172483*

[GPU][MTL] fix ambiguous data type for fmax in gemv

---

src/plugins/intel_gpu/src/graph/impls/ocl_v2/pa_kv_cache_update_ref.cl

- This PR adds a missed `block_read` related include
- Backporting of https://github.com/openvinotoolkit/openvino/pull/31809
- 172478

[GPU] adding a missed block_read related include

---

src/plugins/intel_npu/src/compiler_adapter/src/plugin_compiler_adapter.cpp

- Title. The "one shot" implementation works only for the compiler-in-plugin flow atm and it is superior in terms of compilation time.
- *EISW-180294*

[NPU][WS] Use the "ONE_SHOT" weights separation version as default when the compiler-in-plugin is used

---

.github/workflows/ubuntu_22_dpcpp.yml

This is one of the most expensive build workflows we have in cloud; as discussed with @p-durandin we don't really need it now

[GHA] Disable Intel DPC++ Compiler build in pre-commits

---

src/common/transformations/src/transformations/fp16_compression/mark_subgraphs_to_keep_in_mixed_precision.cpp
src/common/transformations/tests/common_optimizations/mark_subgraph_to_keep_in_mixed_precision_test.cpp

The MarkRandomUniform transformation disables compression to FP16 on a RandomUniform node and marks target inputs of consumer nodes as precision sensitive (only target inputs). The other inputs of the consumer nodes are untouched allowing for FP32 to FP16 conversion. Because of that the following graph may take place after ConvertPrecision with the FP32 Constant being converted to FP16 causing the element types mismatch (taken from the real model):
```
Constant ───f16────┐ 
│ 
Random  ───f32──Less
Uniform            
```
Adjust the transformation to mark not only the target inputs of the RandomUniform node as precision sensitive, but also the other nodes of the consumers to prevent the type change in ConvertPrecision.
[CVS-168643](https://jira.devtools.intel.com/browse/CVS-168643) …

[TRANSFORMATIONS] Mark all inputs of RandomUniform's consumers in the MarkRandomUniform transformation

---

src/common/snippets/src/lowered/linear_ir.cpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/cpu_generator.cpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_binary_call_emitter.cpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_binary_call_emitter.hpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_perf_count_chrono_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_perf_count_chrono_emitters.hpp

- Add support for perf count snippets debug capability on ARM
- Implement perf count chrono emitters on ARM
- N/A

[Snippets][CPU] Implement perf count chrono emitters for ARM64

---

src/plugins/intel_npu/src/plugin/src/plugin.cpp

- *CID (compiler in driver) **was** used as default NPU compiler.*
- ***Update default NPU compiler to CIP (compiler in plugin).***
- *Print warning if compiler library not found.*
- *CVS-173116*

[NPU] Set CIP default compiler

---

src/plugins/intel_npu/tools/protopipe/src/parser/config.cpp
src/plugins/intel_npu/tools/protopipe/src/utils/utils.cpp

- *Protopipe throws exception if I64 is specified as input precision type in config file*
- *OpenCV 4.x which is used by protopipe does not support INT64. As a workaround we use INT32 instead of INT64*
- *EISW-140587*

[Protopipe] Workaround for INT64 input type

---

src/plugins/intel_npu/tests/functional/behavior/batched_tensors_tests/batched_run.hpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp

- Batching and RandomTensor tests use EXPECT_EQ as a check for test pass/fail. This is fine, but if tensor calculations are wrong then the test will report **each element** that doesn't match expected output. Issue is that log files can become extremely large if all elements are incorrect in these output tensors.
- Proposal is to replace EXPECT_ with ASSERT_, meaning that the test will fail when the first incorrect element is detected, it will log only that element and then proceed to the next test
- E182100

[NPU][IE-MDK] Refine Batching and Random test failure logging

---

src/plugins/intel_npu/src/backend/include/zero_infer_request.hpp
src/plugins/intel_npu/src/backend/src/zero_infer_request.cpp
src/plugins/intel_npu/src/common/include/intel_npu/common/sync_infer_request.hpp
src/plugins/intel_npu/src/common/src/sync_infer_request.cpp
src/plugins/intel_npu/tests/functional/behavior/infer_request_run.hpp

- *Diagram:*
```mermaid
flowchart TD;
subgraph SG1["intel_npu::SyncInferRequest"]
A["intel_npu::SyncInferRequest"]~~~A1["allocate_tensor"]
A~~~A2["create_tensor"]
style A1 fill:#808080,stroke:#000,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
style A2 fill:#808080,stroke:#000,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
end
subgraph SG2["ZeroInferRequest"]
B["ZeroInferRequest"]-->B1["set_tensor_data"]
B~~~B2["create_tensor"]
B1--xA1
A1--xB2
B~~~B3["allocate_tensor"]
B3-.->B2
B1-.->B3
style B3 fill:#f96
style B2 fill:#808080,stroke:#000,stroke-width:2px,color:#fff,stroke-dasharray: 5 5
end
```
- *Added `CpuVaTensorsTests` tests:*
- <s>*CpuVaCorrectlyDeallocatedAfterAllInferRequests (disabled)*</s>
- <s>*SetAlignedDifferentTensorTwiceForSameInferRequestsNoThrow* (throws when import …

[`NPU`] Move `allocate_tensor` and `create_tensor` into `ZeroInferRequest` class

---

src/common/snippets/include/snippets/op/perf_count.hpp
src/common/snippets/src/op/perf_count.cpp

If `PerfCountEnd` is being cloned then `clone_with_new_inputs` function loses parameters preserved for further dumping to CSV.
- N/A

[Snippets][DEBUG_CAPS] Fix PerfCountEnd op param cloning

---

src/plugins/intel_npu/src/plugin/npuw/base_sync_infer_request.cpp

Follow-up on https://github.com/openvinotoolkit/openvino/pull/31792/

[NPUW] Extend remote memory check in set_tensor() with sliced tensor case

---

src/plugins/intel_npu/src/compiler_adapter/src/weightless_graph.cpp

- The resources were released too early, leading to failure when multiple init schedules were used.
- *EISW-182934*

[NPU][WS] Fix for the multiple init schedules & a single thread scenario

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp
src/plugins/intel_gpu/src/graph/reorder.cpp
src/plugins/intel_gpu/tests/unit/passes/prepare_buffer_fusing_test.cpp

- Currently buffer fusing of reorder+permute is allowed if the input dimension order of reorder is the same as the permute order
- However, even if permute has a fused prim, it is optimized out, which causes accuracy issue where the actual expected result is different
- Fix to skip buffer fusing if permute has a fused prim
- https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp#L1023
- python gaia.py -i GaiaBlur/gaia-in-1st/%06d.jpg -o GaiaBlur/gaia-out-1st/GPU-2x-%06d.png -d GPU -m ghq-v5-gaia-fp16-576x672-2x.onnx
- ./ov_gpu_unit_tests --gtest_filter=*prepare_buffer_fusing.reorder_permute_with_fused_prim*
- https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/tests/unit/passes/prepare_buff …

[GPU] Fix an issue with reorder+permute buffer fusing

---

src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/tests/unit/fusions/fully_connected_fusion_test.cpp

Normally onednn FC(matmul) run 2 dimension and follow post-op should be the same dimension. But some missed conversion in input based quantization.
./benchmark_app -d GPU.1 -m googlenet-12-qdq.onnx -nireq 1 -nstreams 1 --hint none -niter 1
model: [googlenet-12-qdq.onnx](https://github.com/onnx/models/blob/main/validated/vision/classification/inception_and_googlenet/googlenet/model/googlenet-12-qdq.onnx)
No graph related. It's related conversion dimension to onednn.
- [O] Is it a proper fix? (not a workaround)
- [O] Did you include test case for this fix, if necessary? 
- [O] Did you review existing test that can be extended to cover this scenario? Which test did you review? fully_connected_fusion_test.cpp
- *CVS-173501*

[GPU] Fix onednn FC quantize for input range based.

---

src/bindings/js/node/lib/addon.ts
src/bindings/js/node/tests/unit/infer_request.test.js
src/bindings/js/node/tests/unit/tensor.test.js

this fixes issue #32106 
Added support BigInt64Array and BigUint64Array 
- Add BigInt64Array and BigUint64Array to the [SupportedTypedArray](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/js/node/lib/addon.ts#L1).
- Add tests for using the new types in Tensor and InferRequest.infer()
Ticket: CVS-168014

[OV JS]: Add BigInt64/Uint64 support to Tensor and InferRequest

---

src/common/snippets/include/snippets/lowered/expression.hpp
src/common/snippets/src/lowered/expression.cpp
src/common/snippets/src/lowered/pass/assign_registers.cpp
src/common/snippets/src/lowered/pass/clean_repeated_ptr_shifts.cpp
src/common/snippets/src/lowered/pass/extract_loop_invariants.cpp
src/common/snippets/src/lowered/pass/load_movebroadcast_to_broadcastload.cpp
src/common/snippets/src/lowered/pass/mha_parallel_wa_optimizer.cpp
src/common/snippets/src/lowered/pass/move_result_out_of_loop.cpp
src/common/snippets/src/lowered/pass/serialize_data_flow.cpp
src/common/snippets/src/lowered/pass/validate.cpp
src/common/snippets/src/utils/utils.cpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_loop_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/aarch64/jit_memory_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_loop_base_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_memory_emitters.cpp
src/plugins/intel_cpu/src/emitters/snippets/x64/jit_reg_spill_emitters.cpp
src/plugins/intel_cpu/src/transformations/snippets/aarch64/op/gemm_utils.cpp
src/plugins/intel_cpu/src/transformations/snippets/aarch64/pass/lowered/expressions/gemm_copy_b_buffer_expressions.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/op/brgemm_utils.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/brgemm_cpu_blocking.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/expressions/brgemm_copy_b_buffer_expressions.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/insert_brgemm_copy_buffers.cpp
src/plugins/intel_cpu/src/transformations/snippets/x64/pass/lowered/parallelize_gated_mlp_n_loops.cpp

Introduced an additional helper `Expression::get_input_expr_ptr` for syntactic sugar.
- *N\A*

[Snippets] Introduced Expression::get_input_expr_ptr

---

src/plugins/intel_cpu/src/emitters/plugin/riscv64/jit_eltwise_emitters.cpp

Optimize instruction count and register usage for the chosen emitter
- N/A

[CPU][RV64] Optimize jit_round_half_away_from_zero_emitter

---

src/plugins/intel_gpu/src/graph/registry/reorder_impls.cpp

- b_fs_zyx_fsv16 cldnn ref-kernel is enabled for dynamic shape by PR#31221. This caused perf regression by using ref-kernel which previously had used onednn kernel.
target model unet3d_mlperf
- Before PR#31221 : throughput 1.8 FPS
- Wtih PR#31221 : throughput 0.59 FPS  
- Disabled b_fs_zyx_fsv16 in reorder impl : reorder_impls.cpp 
- Can be reproduced by benchmark_app
`benchmark_app -m unet3d_mlperf\onnx\onnx\FP16\1\ov\unet3d_mlperf.xml -d GPU -nstreams 2 -nireq 4 -t 10 -b 1 -hint none -data_shape input[1,4,224,224,160] -shape input[?,4,?,?,160]`
- CVS-173587

Disable b_fs_zyx_fsv16 not to use cldnn ref kernel

---

src/plugins/intel_npu/src/compiler_adapter/include/driver_compiler_adapter.hpp
src/plugins/intel_npu/src/compiler_adapter/include/ir_serializer.hpp
src/plugins/intel_npu/src/compiler_adapter/include/ze_graph_ext_wrappers.hpp
src/plugins/intel_npu/src/compiler_adapter/src/driver_compiler_adapter.cpp
src/plugins/intel_npu/src/compiler_adapter/src/ir_serializer.cpp
src/plugins/intel_npu/src/compiler_adapter/src/ze_graph_ext_wrappers.cpp

- Moving `serializeIR`, `serializeIOInfo`, `serializeConfig`, `checkedMemcpy`, `ovPrecisionToLegacyPrecisionString`, and `rankToLegacyLayoutString` from `driver_compiler_adapter` to `ir_serializer`.
- Having these standalone functions allows us to call them in other places in a simpler manner.
- *C-174108*

[NPU] Move serialize functions to ir_serializer

---

src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.cl
src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.cpp
src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.hpp
src/plugins/intel_gpu/tests/unit/test_cases/group_normalization_gpu_test.cpp

- choosed the group normalization ref kernel. It has some known issues.
- src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.cl
- src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.cpp
- src/plugins/intel_gpu/src/graph/impls/ocl_v2/group_normalization_fsv16.hpp
- benchmark_app -d GPU -m restoreformerpp_fp16.xml -hint none -nstreams 2 -nireq 4 -niter 1 -data_shape input[1,3,512,512]
- 173364

[GPU] calc index with padded size at first kernel in GroupNormalization

---

src/frontends/onnx/frontend/src/editor.cpp

- *#30282 introduced regression. If node have optional inputs or any other reason when input doesn't exist, but have more inputs after this one, those inputs would be skipped, resulting in failed conversion.*
- *CVS-174291*

[ONNX FE] Fix regression introduced for FP16 models

---

src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.cpp
src/plugins/intel_npu/src/plugin/npuw/partitioning/patterns/dcoff.hpp

Performance impact of ~15ms per chunk (16 total chunks per inference) is seen, netting a E2E inference runtime reduction of ~240ms.
This patch expands CWAI3 to include additional generalized pattern matching for keeping weight scales as const. Performance benefit is seen, outlined above. A regression is introduced with this patch for gaussian_topk_sub and general performance for some ops seemed less efficient when doing a FW Trace comparison. Additional savings can be brought in once resolved, tracked in Ticket bellow. 
- [EISW-183592](https://jira.devtools.intel.com/browse/EISW-183592)  -  Bug this PR is related to.
- [EISW-185933](https://jira.devtools.intel.com/browse/EISW-185933) - Bug that PR introduces. Performance benefit is still seen, but larger benefit will be seen once this …

Expand CWAI to Keep the Weight scales as Constants

---

src/common/snippets/src/lowered/linear_ir.cpp
src/common/snippets/tests/src/lowered/linear_ir.cpp

Ensure LinearIR::replace_with_node clones correct port descriptor instead of reusing the descriptor under the index 0 unconditionally 
- N/A

[Snippets] Fix port descriptor index in LinearIR::replace_with_node

---

src/plugins/intel_npu/tests/functional/internal/backend/zero_tensor_tests.cpp
src/plugins/intel_npu/tests/functional/internal/backend/zero_tensor_tests.hpp
src/plugins/intel_npu/tests/functional/internal/overload/ov_infer_request/io_tensor.hpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
src/plugins/intel_npu/tests/functional/shared_tests_instances/npu_skip_func_tests.xml

- *Extend ZeroTensorTests. Add new test `CopyZeroTensorAndCheckTensorDataType` to check all supported tensor data types.*
- *Update func tests `OVInferRequestIOTensorSetPrecisionTestNPU`. Use model with same type as precision tested, so that `set_tensor` is called for all tested precisions.*
- *Update skip config with supported precision tests.*
- *CVS-174265*

[NPU] Extend functional tests to cover sub-byte element types
