inference-engine/src/gna_plugin/gna_device.cpp
inference-engine/src/gna_plugin/gna_device.hpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/behavior/infer_request_config.cpp

- Use compile target in export tests for SUE
- Fix tests with GNA 2.1 library (Some tests in gnaFuncTest Failed when replacing 1047 with 1095 GNA Library)
- CVS-54602

[GNA] Use compile target in export tests for SUE

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_fake_quantize_node.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/fake_quantize.cpp

Some topologies after onnx importer have following input shapes for FakeQuantizes:
`data_shape = [ 1, C ]`, `quantization_intervals_shape = [ C ]`
This PR adds support for the specified case in the CPU plugin.
Issues: 54783 55668
Validation:
- developer-services/job/accuracy/1971/ (reference: developer-services/job/accuracy/1972/)

[CPU] FakeQuantize: new cases support

---

inference-engine/tests/functional/plugin/shared/include/behavior/exec_graph_info.hpp

Need to check how it will be work for other plug-ins

Disable check on result in CheckExecGraphInfoBeforeExecution

---

model-optimizer/CMakeLists.txt

- Updated CMakeList.txt to remove unit_tests directory from the MO package created for the installer.
- 55855

Fixed MO CMakeList to remove unit_tests directory

---

ngraph/frontend/onnx_import/src/op/reduce.cpp

This PR changes the behaviour of Reduce ops to use the ShapeOf approach for inputs with static rank in order to enable reshaping.
I haven’t provided any new tests because we already have many tests that check the behaviour of Reduce ops when getting inputs with static rank. 
- *46578*

[ONNX] For Reduce operators use ShapeOf approach even when input rank is static

---

ngraph/CMakeLists.txt

- RPATH usage is not recommended by security reasons
- CVS-55110

Removed rpath for ngraph

---

inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/gna_plugin_config.cpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/src/legacy_api/src/cnn_network_impl.cpp
inference-engine/src/transformations/include/transformations/op_conversions/conv2d_decomposition.hpp
inference-engine/src/transformations/src/transformations/op_conversions/conv2d_decomposition.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/conv2d_decomposition.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/padded2valid_conv.cpp
inference-engine/tests_deprecated/unit/engines/gna/gna_matcher.cpp
inference-engine/tests_deprecated/unit/engines/gna/i16_quantisation_test.cpp

- add 2d convolution with 1d kernel to 1d convolution decomposition transform to allow it to run on GNA 2.0
- add multiple test models covering all scenarios
- add multiple test cases using all models and padding options.
- 48062

Gna conv2d decompose

---

inference-engine/src/inference_engine/cnn_network_ngraph_impl.cpp
inference-engine/src/inference_engine/cnn_network_ngraph_impl.hpp
inference-engine/tests/functional/inference_engine/cnn_network/cnn_ngraph_impl_tests.cpp

In cases when user calls reshape method and it fails we got invalid nGraph Function. In this PR I changed a logic in reshape method to restore original shapes if reshape has failed.
XXX-39136

Update reshape to restore original shapes if reshape has failed

---

ngraph/python/src/ngraph/opset3/ops.py
ngraph/python/tests/__init__.py
ngraph/python/tests/test_ngraph/test_ops_fused.py

- There was a mismatch between `groups` vs `group` attribute name, so op factory and attribute visitor didn't handle it correctly.
It was a root cause of the error message: 
`RuntimeError: Check 'm_group >= 1' failed at /openvino/ngraph/core/src/op/shuffle_channels.cpp:77:` 
marked as `xfail_issue_36485`
- 36485

Fix ng python ShuffleChannels group attribute

---

model-optimizer/mo/front/kaldi/extractors/max_pooling_ext.py
model-optimizer/unit_tests/mo/front/kaldi/extractors/max_pooling_ext_test.py

Root cause analysis: For 1D maxpooling in Kladi we set 1d kernel but 2d stride
Solution: set 1d stride
Ticket: 54749
Code:
Validation:
Documentation:

fix stride for 1d maxpooling

---

inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/topk.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp

- *Remove unnecessary test cases, in which output mismatch is expected, because according to spec the permutation of topk elements is undefined when SortType is NONE*.
- *38841*

Fix topk failure

---

inference-engine/thirdparty/movidius/mvnc/src/mvnc_api.c

- Copy a string with an address of the booted device only when the device has been successfully been booted. Otherwise, we should free allocated by `strdup` memory or we will get a memory leak.
- 55626

[IE][VPU]: Write info about booted device only on success

---

inference-engine/src/mkldnn_plugin/mkldnn_descriptor.cpp
inference-engine/src/mkldnn_plugin/mkldnn_descriptor.h
inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp
inference-engine/src/mkldnn_plugin/mkldnn_plugin.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_deconv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_deconv_node.h
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp

- *48331*
PR in oneDNN: openvinotoolkit/oneDNN#50
PR with tests: #5348
Builds: 624, 625

[CPU] Deconvolution int8 support

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_mvn_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_mvn_node.h
inference-engine/src/transformations/include/transformations/common_optimizations/mvn_fusion.hpp
inference-engine/src/transformations/src/transformations/common_optimizations/mvn_fusion.cpp
inference-engine/tests/functional/inference_engine/transformations/mvn_fusion_test.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/mvn.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/subgraph_tests/mvn_multiply_add.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/mvn.cpp
inference-engine/tests/functional/plugin/shared/include/subgraph_tests/mvn_multiply_add.hpp
inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/mvn_multiply_add.hpp
inference-engine/tests/functional/shared_test_classes/src/subgraph/mvn_multiply_add.cpp

- Added MVN fusion for specific case when constants are inside subgraph
- Removed creating shape5D from MVN ctor and added it to `createPrimitive` because node initializing is before `CommonOptimization` in `MKLDNNGraph`. So when we changed parameter `across_channels` in MVN ctor in method `tranformTo5DCase` for 1D and 2D shapes, there were [incorrect result](https://github.com/a-sidorova/openvino/blob/15ffe41cec807a0177e25cff4044f080815a2ada/inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.cpp#L1131) of condition in fusing MVN and eltwise nodes (`beta` and `gamma`) in `FuseMVNAndSimpleOperations` 
- 48955

Added MVN fusion for case with constants inside

---

licensing/third-party-programs.txt

updated third-party-programs.txt

---

model-optimizer/mo/back/ie_ir_ver_2/emitter.py

Root cause analysis: According to https://phabricator.wikimedia.org/T213814, the method `xml.etree.ElementTree.Element.getchildren()` is deprecated from Python 3.2 and has been removed in Python 3.9. As a result, we have failure of conversion of some ONNX models, if the Python version is greater or equal than 3.9.
Solution: Replace `element.getchildren()` with `list(element)` in the file `model-optimizer\mo\back\ie_ir_ver_2\emitter.py`.
Ticket: 55705
Code:
Validation:
Documentation:

Failed conversion from ONNX to IR

---

ngraph/core/include/ngraph/runtime/aligned_buffer.hpp

- AlignedBuffer doesn't have virtual destructor
- NA

Fixed AlignedBuffer destructor

---

ngraph/test/backend/ctc_greedy_decoder_seq_len.in.cpp
ngraph/test/runtime/interpreter/evaluates_map.cpp

- *Fix segfault in evaluates_map for CTCGreedyDecoderSeqLen caused by OPs with two inputs only*
- *52561*

Handle 3rd optional input in CTCGreedyDecoderSeqLen evaluate

---

inference-engine/src/cldnn_engine/CMakeLists.txt
inference-engine/thirdparty/clDNN/kernel_selector/CMakeLists.txt
inference-engine/thirdparty/clDNN/src/CMakeLists.txt

- Currently rebuild of the project with Ninja generator will lead to circle dependency for kernel_selector cpplint target. This patch fixes it.
- 50495

[IE CLDNN] Fixed cpplint issue with cpplint for CLDNN with Ninja generator

---

inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp

- Identity insertion into LSTM cell can change the order of inputs for the next LSTM cell. Its inputs should be just replaced without order change.
- The problem is reproduced by MultipleLSTMCellTest with low latency transformation when TI unrolling is done inside this transformation before network loading to GNA plugin (after implementation of ticket 48754).
56397

[GNA] Fix identity insertion into LSTMCell

---

ngraph/core/reference/include/ngraph/runtime/reference/transpose.hpp
ngraph/test/op_eval/transpose.cpp

Transpose reference template function was marked as deprecated during revision task (https://github.com/openvinotoolkit/openvino/pull/5315)
and can be removed after update usage of reference::transpose in ARM plugin (done with https://github.com/openvinotoolkit/openvino_contrib/pull/135).
- 56499

Remove deprecated legacy Transpose ref function

---

inference-engine/src/offline_transformations/src/pruning/propagate_masks.cpp
inference-engine/src/offline_transformations/src/pruning/pruning.cpp
inference-engine/src/offline_transformations/src/pruning/shrink_weights.cpp
inference-engine/tests/functional/inference_engine/transformations/pruning_test.cpp

Replaced ConstantFolding pass with local constant folding using `get_constant_from_source` method to avoid constant sub-graph folding. Also dynamic checks were added to the Pruning transformation to avoid failures when dynamic shape occurs.
@jane-intel I checked IR generation with dynamic model and now ShapeOf operations remain in IR.

Fix constant sub-graph folding and dynamic shape issues inside Pruning transformation

---

inference-engine/src/inference_engine/cpp_interfaces/interface/ie_iinfer_request_internal.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/set_preprocess.hpp

- Added preprocessing test which check that precision and layout cannot be changed after network is compiled. E.i. SetBlob checks that format of passed blob is the same as format of compiled network.
- CVS-56515

Added more preprocessing tests

---

inference-engine/src/low_precision_transformations/include/low_precision/transformer.hpp
inference-engine/src/low_precision_transformations/src/transformer.cpp
inference-engine/src/mkldnn_plugin/mkldnn_extension_utils.cpp
inference-engine/src/mkldnn_plugin/mkldnn_extension_utils.h
inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp
inference-engine/src/mkldnn_plugin/mkldnn_graph.h
inference-engine/src/mkldnn_plugin/mkldnn_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_conv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_conv_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_eltwise_node.cpp
inference-engine/tests/functional/plugin/cpu/bfloat16/elt_x3.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/convolution.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/convolution_backprop_data.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/eltwise.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/group_convolution.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/group_convolution_backprop_data.cpp
inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/conv_concat.cpp
inference-engine/tests/functional/plugin/cpu/test_utils/convolution_params.hpp
inference-engine/tests/functional/plugin/cpu/test_utils/cpu_test_utils.hpp

Enabling nspc layout support in all the FP32/BF16 convolution primitives
- Fixed jit planar convolution init_conf subroutine to select the right layout label
- Add planar -> blocked convolutions for IC = 2
- Fixed eltwise node to work properly with 1D nspc input
- SSE41 convolution kernels do not support nspc layout ( 52736 )
- GEMM BF16 ncsp convolution unexpectedly crushes during multithreaded execution  ( 53618 )
- GEMM FP32/BF16 nspc depthwise post ops fusing implementation is not optimal ( 52737 )
- 52738
OneDNN PR: https://github.com/openvinotoolkit/oneDNN/pull/47

[CPU BF16] Nspc layout enabling in the FP32/BF16 convolutions

---

inference-engine/src/inference_engine/file_utils.cpp

- On non-root Android systems OpenVINO .so libraries can't be loaded because file exist check failed
- File exist check failed because `FileUtils::fileSize` can't open `ifstream` using file path with "!" character
- Character "!" divides the path to apk file and the path to a file within apk archive, for instance: `/data/app/com.example.ovapp-wX6xOF5_h2XQiYI4shqLyg==/base.apk!/lib/arm64-v8a/libinference_engine_ir_reader.so`
- PR suggests a workaround to handle such Android-specific file paths with "!" delimiter.
- N/A

Handle Android-specific file paths

---

docs/MO_DG/img/compressed_int8_Convolution_weights.png
docs/MO_DG/img/expanded_int8_Convolution_weights.png
docs/MO_DG/prepare_model/convert_model/IR_suitable_for_INT8_inference.md

- *We have changed the form of the weights, so the main doc change is the replacement of pictures. Also, I've changed INT8 everywhere to low precision due to future extension of supported low precision data types.*
- Added NNCF mentioning
- *51615*

Low Precision IR documentation

---

inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.hpp
inference-engine/tests/functional/plugin/gna/pass_tests/broadcast_const_with_fq.cpp

**Details:**
- Broadcast is failed in case of const->fq->add.
**Tickets:**
56491

[GNA] Fix bug with broadcasting constant layer with fq layer

---

ngraph/test/type_prop/squeeze.cpp

Ticket was complaining that the code is impossible to run, but it is not true and I formulated it in the form of a shape infer test
- *33970*

Squeeze with scalar axis

---

inference-engine/include/ie_precision.hpp

Related PR #5654
Our VS2015 build has failed due to some unsupported template constructs:
```
c:\deployment_tools\inference_engine\include\ie_precision.hpp(440): error C2891: 'T': cannot take the address of a template parameter (compiling source file dnn.cpp)  
c:\deployment_tools\inference_engine\include\ie_precision.hpp(439): note: see declaration of 'T' (compiling source file dnn.cpp)
```
I understand that VS2015 is quite old and is not officially supported by OpenVINO, but since the fix is not too complex, I hope it won't break anything and can be accepted.
This patch is more naive version of the original code and I hope someone can propose better and more elegant solution in review comments. [Other idea](https://github.com/openvinotoolkit/openvino/compare/master...mshabunin:fix-vs2015 …

ie_precision: added FloatTrait to fix VS2015 client compilation

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_transpose_node.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/transpose.cpp

- *Changed the switch case logic by the precision to by data size for Transpose*
- *Continuation of [PR#5724](https://github.com/openvinotoolkit/openvino/pull/5724)*

[CPU] Changed switch case logic by precision for Transpose

---

model-optimizer/mo/utils/find_ie_version.py

In find_ie_version we have two paths for finding IE Python API. And when running install_prerequisites on linux we was searching for  IE in Windows paths first and only then on Linux paths. So that was the reason of confusing warning message. This PR includes fix where IE Python API search was updated to check platform.
XXX-53583

Fix IE API search to check platform

---

inference-engine/src/offline_transformations/src/pruning/propagate_masks.cpp

Removed cycle shared_ptr dependency between lambda functions inside Pruning transformation. Now sanitizer shows no issues.
XXX-55676

Fix memory leak inside Pruning transformation

---

inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/region_yolo_gpu_ref.cl

Signed-off-by: Kim, SungEun <sungeun.kim@intel.com>
- wrong output index
- 51761

[IE CLDNN] Fixed a region_yolo bug (#51761)

---

inference-engine/src/mkldnn_plugin/mkldnn_edge.cpp
inference-engine/src/mkldnn_plugin/mkldnn_edge.h
inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp
inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.cpp
inference-engine/src/mkldnn_plugin/mkldnn_memory.h
inference-engine/src/mkldnn_plugin/mkldnn_node.cpp
inference-engine/src/mkldnn_plugin/mkldnn_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_conv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_conv_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_deconv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_eltwise_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_input_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_input_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_rnn.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_strided_slice_node.cpp
inference-engine/src/transformations/src/transformations/rt_info/fused_names_attribute.cpp

- Redundant copying of weights and biases removed for convolution layer.
- Some legacy code removed from MKLDNN convolution layer
- CVS-46997

Redundant copying of weights and biases for convolution layer

---

inference-engine/ie_bridges/python/wheel/setup.py

- *filter files for patchelf/install_name_tool:  skip symlinks and linker scripts*
- *CVS-51355*

Python wheel: failed to set RPATH for 3rd parties

---

inference-engine/samples/common/utils/include/samples/classification_results.h

- Fix Klocwork issue: Potentially untrusted data 'id' can be used to read arbitrary data beyond boundary of array 'this->_results' at line 163 in speculative branch execution.
- 50356

samples: fix klocwork beyond boundary issue

---

inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/reorder/reorder_kernel_b_fs_yx_fsv16_fsv32_to_bfyx.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/reorder/reorder_kernel_b_fs_yx_fsv16_fsv32_to_bfyx.h
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/reorder/reorder_kernel_bfyx_to_blocked_format.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/reorder/reorder_kernel_bfyx_to_blocked_format.h
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/reorder/reorder_kernel_selector.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/reorder_data_b_fs_yx_fsv16_fsv32_to_bfyx.cl
inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/reorder_data_bfyx_to_blocked_format.cl
inference-engine/thirdparty/clDNN/tests/test_cases/reorder_gpu_test.cpp

Signed-off-by: Kelvin Choi <kelvin.choi@intel.com>
- Optimize reorder [non blocked formats (bfyx, bfzyx)=> blocked formats (b_fs_yx_fsv4, b_fs_yx_fsv16, b_fs_yx_fsv32 ,fs_b_yx_fsv32, b_fs_zyx_fsv16, b_fs_zyx_fsv32, bs_fs_yx_bsv16_fsv16, bs_fs_zyx_bsv16_fsv16)]
- Optimize reorder [blocked formats ( b_fs_yx_fsv16, b_fs_yx_fsv32) => non blocked formats (bfyx, bfzyx)]
- *48366*

[IE_CLDNN] Optimize reorder between blocked formats and non blocked formats

---

inference-engine/src/gna_plugin/backend/make_pwl.cpp
inference-engine/src/gna_plugin/round_float_define.hpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/conv_fq_eltwise.cpp
inference-engine/tests/functional/plugin/shared/include/subgraph_tests/conv_fq_eltwise.hpp
inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/conv_fq_eltwise.hpp
inference-engine/tests/functional/shared_test_classes/src/subgraph/conv_fq_eltwise.cpp

- FQ low/high values can overflow during pwl calculation, it causes negative values which completely break the result.
56826

[GNA] Avoid integers overflow during pwl calculation for FakeQuantize

---

inference-engine/ie_bridges/python/tests/test_InputInfoPtr.py

- *In test_InputInfoPtr.py test_preprocess_info, preprocess_info is using after input_info has deallocated - that is not corrects*
- *AddressSanitizer detect heap-use-after-free*
- *53920*

[IE PYTHON] Fixed test_InputInfoPtr, that leads to heap-use-after-free

---

ngraph/python/tests/__init__.py
ngraph/python/tests/test_ngraph/test_basic.py

Obsolete nGraph python test removal

---

inference-engine/thirdparty/clDNN/src/gpu/crop_gpu.cpp

This patch adds support of i8/u8 inputs for b_fs_yx_fsv16 format for crop primitive
55548

[IE CLDNN] Crop fsv16 i8/u8 input support

---

model-optimizer/mo/utils/find_ie_version.py

IE Python API search wasn't working for Windows platform for local build type. This PR includes the fix for MO which specifies necessary paths to python modules and libs for Windows platform.

Fix IE Python API search inside MO for Windows platform

---

model-optimizer/mo/middle/passes/fusing/fuse_linear_ops.py
model-optimizer/unit_tests/mo/middle/passes/fusing/fuse_linear_ops_test.py

Root cause analysis:
_fuse_add transformation finds MatMul node and a Mul node that goes after it, than removes Mul node and inserts a new Mul node before the MatMul using set_source() method. set_source() copies attributes from the data node of old connection to the new data node and it leads to appearance of two data nodes with the same name.
After the constant folding and graph cleanup the operation that goes to the new data node is deleted as const producer and the new Const op is created with the name obtained from data node which leads to the error, that graph contains two nodes with the same name.
Solution: 
Manually set unique name to the new data node.
Ticket: 54845
Code:
Validation:
Documentation:

Fixed duplicate names appearance in graph after fuse mul transformation.

---

inference-engine/src/mkldnn_plugin/emitters/jit_load_store_emitters.cpp
inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_mvn_node.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/mvn.cpp

- *MVN_accuracy_fix_on_avx512*
- *fusion conditions extension*
- *55184*
- *55340*

MVN_accuracy_fix_on_avx512

---

inference-engine/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/select.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/select/select_kernel_base.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/select/select_kernel_ref.cpp

- *Add Select int32/int16 input support*
- *CVS-51063*

[IE CLDNN] Add Select int32/int16 input support

---

inference-engine/src/inference_engine/threading/ie_cpu_streams_executor.cpp
inference-engine/src/inference_engine/threading/ie_parallel_custom_arena.cpp
inference-engine/src/inference_engine/threading/ie_parallel_custom_arena.hpp

There are several logic errors in `custom::task_arena` interface implementation. This patch reworks the custom arena construction and initialization logic to fix them.
Discovered errors:
- Several calls of concurrent unsafe `tbb::task_arena::initialize(constraints c)` via `custom::task_arena::execute()` may cause logic data race and assertion failure when using debug TBB binaries. The impact is low since may be reproduced only when using oneTBB 2021.
- When OpenVINO creates an observer for pinning threads to cores it calls the `tbb::task_scheduler_observer::observe(bool)` method, which initializes the `task_arena` instance that was passed to the observer during the construction as an argument. But we should initialize `custom::task_arena` instead of `tbb::task_arena` since …

Rework custom::task_arena initialization logic

---

inference-engine/samples/common/utils/include/samples/classification_results.h

- Fix Potentially untrusted data 'id' can be used to read arbitrary data beyond boundary of array 'this->_results' at line 170 in speculative branch execution

samples: fix klocwork beyond boundary of array issue

---

inference-engine/src/gna_plugin/frontend/quantization.h
inference-engine/src/gna_plugin/frontend/quantized_layer_params.hpp
inference-engine/src/gna_plugin/layers/gna_fake_quantize_layer.hpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/fake_quantize.cpp

- Replace int32_t type by size_t for levels in GNA quantization classes
56549

[GNA] Replace int32_t type by size_t for levels in GNA quantization classes

---

inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pxd
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api_impl.cpp
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api_impl.hpp
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api_impl_defs.pxd
inference-engine/ie_bridges/python/tests/test_ExecutableNetwork.py
inference-engine/ie_bridges/python/tests/test_InputInfoCPtr.py

- *InputInfo and Data created in the Plugin should deallocate before deleting the Plugin*
- *A shared pointer to the ExecutableNetwork that holds the plugin is bound to InputInfoCPtr, DataPtr and CDataPtr*
- *28996*

[IE PYTHON] FIX InputInfoCPtr, DataPtr and CDataPtr deallocation

---

cmake/toolchains/ia32.linux.toolchain.cmake

- Looks like ONNX imported is fixed for ia32
- CVS-48064

Enabled ONNX importer part on ia32 arch

---

inference-engine/src/mkldnn_plugin/mkldnn_extension_utils.cpp
inference-engine/src/mkldnn_plugin/mkldnn_extension_utils.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_concat_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_concat_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_shuffle_channels_node.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/concat.cpp
inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/fuse_transpose_reorder.cpp

Concatenation node logic for selecting optimal primitive descriptor was changed to prevent fallback on slow ref implementation.
The main ticket with the problem description is 47423.

[CPU] Extend Concat node logic to avoid fallback on slow ref implementation.

---

docs/IE_DG/supported_plugins/MULTI.md

- *Use "stands for" in multi-device doc*
- *[5905](https://github.com/openvinotoolkit/openvino/issues/5905)*

Fix wrong word in multi-device doc

---

inference-engine/src/mkldnn_plugin/mkldnn_weights_cache.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp

Prevent destruction of the shared memory object if the last stream that holds the memory was destroyed between checking the week pointer expiration and acquisition by a new stream.
- 42538

[CPU] Fix for  CoreThreadingTestsWithIterations tests

---

inference-engine/src/mkldnn_plugin/mkldnn_exec_network.cpp

- Otherwise they are initialized concurrently in scope of MKLDNNNode
constructor without thread safety
- CVS-56762

[CPU] Add workaround for Ngraph OPs friendly name initialization

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_eltwise_node.cpp

- Fix input precision of fused eltwise node, when fusing occurs on non-zero port
- 55889
- 56104

[CPU] Fix eltwise precision fusing on non-zero ports

---

inference-engine/src/low_precision_transformations/src/split.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/split_transformation.cpp
inference-engine/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/split_function.hpp
inference-engine/tests/ngraph_helpers/lpt_ngraph_functions/src/split_function.cpp

- SplitTransformation WA: avoid propagation of dequantization operations if after Split all consumers are the same unsupported Concat
- 55548
- 56781
- Accuracy: developer-services/job/accuracy/2083/ (reference: developer-services/job/accuracy/2084/)

[LPT] SplitTransformation WA for unsupported concat

---

docs/ops/sequence/CTCGreedyDecoder_1.md

- Removed link to tensorflow documentation
- Added *Types* section
- Added backticks to types
- Refactor input/output tensor description to refer types section.
- *56032*

CTCGreedyDecoder operation specification refactoring

---

inference-engine/src/mkldnn_plugin/mkldnn_weights_cache.cpp
inference-engine/src/mkldnn_plugin/mkldnn_weights_cache.hpp

- Fix for data race in MKLDNNSharedMemory::valid
- CVS-55643

Fix for data race in MKLDNNSharedMemory::valid

---

inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/param_result_custom_blob.cpp

Fix mem leak in ParameterResultCustomBlobTest. 
- 57106

[CPU] Fix mem leak in ParameterResultCustomBlobTest

---

inference-engine/src/low_precision_transformations/src/weightable_layer_transformation.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/convolution_backprop_data_transformation.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/low_precision_transformations/convolution_backprop_data_transformation.cpp

- ConvolutionBackpropDataTransformation: handled incorrect dequantization on weights (dq by zero dimension)
- 56886
- Accuracy: developer-services/job/accuracy/2108/ (reference: developer-services/job/accuracy/2109/)

[LPT] ConvolutionBackpropData Transformation fix

---

scripts/install_dependencies/install_openvino_dependencies.sh

- remove POT dependencies
- Checked on Docker PR: https://github.com/openvinotoolkit/docker_ci/pull/112

scripts: remove pot dependencies

---

model-optimizer/extensions/front/onnx/elementwise_ext.py

Root cause analysis: Extractor for ONNX operations [GreaterOrEqual](https://github.com/onnx/onnx/blob/master/docs/Operators.md#GreaterOrEqual) and [LessOrEqual](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LessOrEqual) not exist, but operations marked as supported in our documentation.
Solution: Implement appropriate extractors.
Ticket: 57109
Code:
Validation:
Documentation:

[MO] Add extractor for ONNX *OrEqual operations

---

docs/ops/activation/PReLU_1.md

PReLU spec was wrongly updated with 1D slope intput restriction during last revision.
The following fixes are needed:
- 45954

[Spec] Prelu - Remove 1D slope restriction and update broadcast info

---

inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/basic_lstm.cpp
inference-engine/tests/functional/plugin/shared/include/subgraph_tests/basic_lstm.hpp
inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/basic_lstm.hpp
inference-engine/tests/functional/shared_test_classes/src/subgraph/basic_lstm.cpp

- *Insert AffineFilter after the split when padding is needed for the input of the child layer (input should be multiple of 8).*
- *Fix CompareWithRefImpl_LowLatencyTransformation test: reference was calculated before setting of inputs generation what was causing non deterministic failures.*
- *56171*

[GNA]  Insert AffineFilter after split when padding is needed.

---

tools/benchmark/benchmark.py
tools/benchmark/parameters.py
tools/benchmark/utils/utils.py

-  *Fix bug, which was introduced by PRs https://github.com/openvinotoolkit/openvino/pull/4318 https://github.com/openvinotoolkit/openvino/pull/4994 Don't set U8 precision by default for non-image inputs. It is unacceptable for image info input*
- *Call wait on request for the first inference to propagate exception (workaround)*
- *56288*

Fix python benchmark_app hanging on faster rcnn

---

ngraph/python/src/pyngraph/partial_shape.cpp
ngraph/python/tests/test_ngraph/test_core.py

- This method is needed for new nGraph Frontend feature integration with MO.
- For '--batch' option MO code will create first dimension according to specified batch size. To keep other dimensions, these will be obtained from old partial_shape via 'get_dimension' method, and will be copied to new partial_shape object
- 57266

Exposing 'PartialShape::get_dimension' method to Python nGraph API

---

docs/install_guides/installing-openvino-docker-linux.md
docs/install_guides/installing-openvino-docker-windows.md

- Add link to openVINO Docker tutorials located on GitHub openvinotoolkit/docker_ci repo

doc: add link to docker tutorials

---

inference-engine/src/transformations/src/transformations/serialize.cpp
inference-engine/tests/functional/inference_engine/ir_serialization/const_compression.cpp

The hash function that is used inside Serialization pass for weights compression is weak and gives the same hash values for `{2, 2}` and `{0, 128}` arrays. So such collisions could lead to undefined behavior. To prevent wrong weights compression we took an approach from Model Optimizer where we check not only hashes but also values.
XXX-57224

Fix weights compression

---

inference-engine/src/transformations/src/transformations/common_optimizations/algebraic_simplification.cpp

- *Took Shape Of output type into account while applying the transformation*
- *57277*

Gather->ShapeOf optimization fix

---

model-optimizer/extensions/front/RollWithEmptyAxesReplacer.py
model-optimizer/unit_tests/extensions/front/RollWithEmptyAxesReplacer_test.py

Roll operation returns wrong shape in MxNet when axis input is not specified. This case is processed by RollWithEmptyAxesReplacer transformation, which adds Reshape nodes before and after Roll node and second Reshape should return original input shape using ShapeOf. But this ShapeOf is connected with wrong node which causes wrong Reshape result.
Solution: 
Connect ShapeOf  with correct original input node.
Ticket: 57130
Code:
Validation:
Documentation:

Fix of RollWithEmptyAxesReplacer transformation.

---

tests/stress_tests/CMakeLists.txt
tests/stress_tests/memcheck_tests/CMakeLists.txt
tests/stress_tests/memleaks_tests/CMakeLists.txt
tests/stress_tests/unittests/CMakeLists.txt
tests/time_tests/CMakeLists.txt
tests/time_tests/README.md
tests/time_tests/src/timetests/CMakeLists.txt
tests/time_tests/src/timetests_helper/CMakeLists.txt

Stress and Time tests are suffered from sporadic issues caused by fail on building of `gflags_nothreads_shared`. Possible rootcause is a network issue while downloading `gflags` sources via cmake FetchContent. With aim to resolve that rootcause and unify `gflags` source for OpenVINO, `gflags` will be consumed as OpenVINO git submodule 
- Time tests now based on IEDevScripts. InferenceEngineDeveloperPackage dependency left in order to provide backward compatibility
- Stress tests based on InferenceEngineDeveloperPackage because it requires gtest from IE tests
- 55465

Make stress and time tests build dependent from gflags from samples

---

inference-engine/thirdparty/clDNN/src/graph_optimizer/prepare_buffer_fusing.cpp

crop + NMS should not be merged because optimizing out crop will add padding input for NMS while NMS is not supporting padding currently
- 52279

[IE CLDNN] disabled crop optimization prior to NMS

---

inference-engine/tests/functional/plugin/cpu/single_layer_tests/batch_to_space.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/space_to_batch.cpp

- *Reduced the number of tests for BatchToSpace and SpaceToBatch*

Decreasing cpuFuncTests execution time

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_mvn_node.cpp

- *MVN decomposition **callback** didn't properly dealt with dynamically shaped input*
- *57347*

Dynamic shape support for MKLDNNMVNNode::isSupportedOperation

---

inference-engine/src/gna_plugin/backend/dnn_types.h
inference-engine/src/gna_plugin/layers/gna_fake_quantize_layer.hpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp

- fix multiple static code analysis issues.
- 57190.

Gna fix sca issues

---

inference-engine/tests/functional/inference_engine/transformations/convert_precision.cpp
ngraph/core/src/pass/convert_precision.cpp

ConvertPrecision pass was recently updated to avoid unnecessary Function validations. And this functionality relies on returned status from functions that perform precision change. And for Constant operation this function was always returning false so Function validation wasn't applied and new precisions wasn't propagated.
XXX-55848

Fix ConvertPrecision for Constants

---

inference-engine/src/cldnn_engine/cldnn_engine.cpp

- force loop unrolling when iteration count is 1 regardless enable_loop_unrolling cldnn configuration.
- 42111

[IE CLDNN] force loop unrolling when iteration count is 1

---

inference-engine/tests_deprecated/functional/vpu/common/layers/myriad_layers_rfcn_test.cpp

Added check that output blob is not nullptr to avoid memory leaks in tests
- *57114*

[IE][VPU][TESTS] Check that output blob is not nullptr for deprecated rfcn tests

---

inference-engine/tests/functional/plugin/myriad/shared_tests_instances/skip_tests_config.cpp

- Turns back on `CTCGreedyDecoderSeqLen` layer tests with `(1, 1, 1)` size, since they were fixed by #5867
- CVS-48183

[VPU][TEST] turns back on CTCGreedyDecoderSeqLen tests

---

inference-engine/src/offline_transformations/include/mask_attribute.hpp
inference-engine/src/offline_transformations/include/pruning.hpp
inference-engine/src/offline_transformations/src/pruning/init_const_mask.cpp
inference-engine/src/offline_transformations/src/pruning/init_masks.cpp
inference-engine/src/offline_transformations/src/pruning/propagate_masks.cpp
inference-engine/src/offline_transformations/src/pruning/pruning.cpp
inference-engine/src/offline_transformations/src/pruning/shrink_weights.cpp
inference-engine/tests/functional/inference_engine/transformations/pruning_test.cpp
model-optimizer/mo/back/offline_transformations.py

**Ticket:** XXX-42179
In this PR:
- Added FQ pruning support (and quantized weights for Convolution/GroupConvolution)
- Eltwise pruning extended by Multiply and fixes for other cases
- Added Concat pruning support 
- Added tests for new cases

Pruning with FQ support

---

model-optimizer/mo/middle/passes/fusing/fuse_grouped_conv.py
model-optimizer/unit_tests/mo/middle/passes/fusing/fuse_grouped_conv_test.py

When network has NCHW layout in TF grouped_convolutions_fusing() concatenates weights value of grouped convolutions by wrong dimension. The concatenation should be performed by the dimension corresponding to output channels. For Conv2D weights layout is HWIO, where O - output channels, I - input channels, H - filter height, W - filter width. So concatenation should be performed by 3-rd dimension.
But output channels dimension index is calculated depending on graph "layout" attribute. In TF graph may have NCHW and NHWC layout and in both cases output feature dimension index for Conv2D = 3, so this calculation is wrong for NCHW graph. 
Solution: 
Calculate output channels dimension index using permutation attribute which stores information of weights layout. Weights …

Fixed feature dimension calculation in grouped_convolutions_fusing().

---

inference-engine/src/legacy_api/src/transformations/convert_opset1_to_legacy/convert_strided_slice_to_crop.cpp
inference-engine/tests/functional/inference_engine/transformations/convert_strided_slice_to_crop_test.cpp

Normally in StridedSclie begin values should be ignored if begin_mask is set. But in SS->CropIE transformation there was a typo [convert_strided_slice_to_crop.cpp#L140](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/legacy_api/src/transformations/convert_opset1_to_legacy/convert_strided_slice_to_crop.cpp#L140) because of which `offset` was updated with the incorrect (not latest) lower bound (`lb`) which was taken from begin. 
Fixed that by moving `offset.emplace_back(lb)` to the place where begin_mask is already processed.
- 48211

fix strided_slice_to_crop

---

inference-engine/src/transformations/src/transformations/op_conversions/convert_interpolate1_to_interpolate4.cpp
inference-engine/tests/functional/inference_engine/transformations/convert_interpolate1_to_interpolate4_test.cpp

Issue: 56943
For Interpolate1 we computed coordinate in original tensor in the following way:
https://github.com/openvinotoolkit/openvino/blob/e9969112affd6a103e657fb55d16e1e2eaeb4379/inference-engine/src/mkldnn_plugin/nodes/interp.cpp#L310-L316
https://github.com/openvinotoolkit/openvino/blob/e9969112affd6a103e657fb55d16e1e2eaeb4379/inference-engine/src/mkldnn_plugin/nodes/interp.cpp#L352-L353
which corresponds ```coordinate_transformation_mode == asymmetric``` for Interpolate4
Also we have tests in which reference value for ```coordinate_transformation_mode```  == ```asymmetric``` in Interpolate4
https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/inference_engine/transformations/convert_interpolate1_to_interpolate4_test.cpp#L57
But test didn't …

ConvertInterpolate1ToInterpolate4 fixes

---

inference-engine/src/auto_plugin/auto_exec_network.cpp
inference-engine/src/auto_plugin/auto_exec_network.hpp
inference-engine/src/auto_plugin/auto_infer_request.cpp
inference-engine/src/auto_plugin/auto_infer_request.hpp
inference-engine/src/auto_plugin/auto_plugin.cpp
inference-engine/src/auto_plugin/auto_plugin.hpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/infer_request_config.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/infer_request_input.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/infer_request_output.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/perf_counters.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/test_plugin.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/infer_request_input.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/infer_request_output.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/perf_counters.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/test_plugin.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/config.hpp
inference-engine/tests/functional/plugin/shared/include/behavior/infer_request_config.hpp

- *Auto plugin only support its config "IE::KEY_AUTO_DEVICE_LIST", no more*
- *Auto will use the config from LoadNetwork("AUTO", config) to extract the "IE::KEY_AUTO_DEVICE_LIST", but for other devices like CPU, AUTO will ignore the configuration, and will be "executableNetwork = GetCore()->LoadNetwork(param, selectedDevice, {});"*
- *If User need set those devices config, they should set by "ie.SetConfig(config, CPU);" *
- *57233*

[AUTO plugin] AUTO plugin will ignore other plugins' configuration

---

cmake/features.cmake
ngraph/test/CMakeLists.txt

OpenVINO build is slow and unit-test is on a critical path. Removing plugin dependencies so
unit-test build can start earlier.

Cleanup ngraph unit test dependencies

---

model-optimizer/extensions/front/onnx/top_k_ext.py

**Root cause analysis:** For ONNX* models MO always produces TopK with int32 indices output that will lead to type conflicts during type inference, for example, if some eltwise node consumes its TopK output of int32 and ShapeOf output of int64 type.
**Solution:** Specify *index_element_type* to int64 explicitly. It is valid because ONNX* TopK operation always produces int64 indices output according ONNX* specification (for TopK-1, 10, 11).
**Ticket:** 55596
Code:
Validation:
Documentation:

Use int64 for TopK indices output

---

inference-engine/src/gna_plugin/backend/gna_limitations.hpp
inference-engine/src/gna_plugin/frontend/scale_factor_calc.hpp
inference-engine/src/gna_plugin/gna_graph_compiler.cpp
inference-engine/src/gna_plugin/gna_graph_tools.hpp
inference-engine/src/gna_plugin/gna_groups.hpp
inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/src/gna_plugin/transformations/convert_matmul_to_pointwise_convolution.cpp
inference-engine/src/gna_plugin/transformations/convert_matmul_to_pointwise_convolution.hpp
inference-engine/src/gna_plugin/transformations/split_convolution_with_large_buffer_size.cpp
inference-engine/src/gna_plugin/transformations/split_convolution_with_large_buffer_size.hpp
inference-engine/tests/functional/plugin/gna/pass_tests/convert_matmul_to_pointwise_conv.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/eltwise_split_over_channels_pass.cpp

- Convert Matmul with batch size > 8 to pointwise convolution
- Support Eltwise split to more than 2 parts
- Throw an exception if output/input name isn't found during infer request instead of segmentation fault
- Support activation FakeQuantize which previous layer has more than 1 output
- Support FakeQuantize  fusion with weights for a layer without bias
- Recognize Transpose - ... - Conv - ... - Transpose patterns with Split inside them
- Fix scale factor calculation for weightable identity without source quantization stats followed by FakeQuantize or Identity with  destination quantization stats
- Fix scale factors calculation for Eltwise followed by a bias (add eltwise with a const)
- Fix setting of destination levels for FakeQuantize layer itself (should be MAX_UINT16 instead of …

[GNA] Convert Matmul with batch size > 8 to pointwise convolution

---

inference-engine/thirdparty/clDNN/src/program.cpp

This reverts commit 9de861d2e195a8301dc9aaf166cc9b0db1bdaeed.
Because of other optimizations, we don't need this patch anymore.
- Previously, fsv4 has perf gain in some network. However, fsv16 performance was optimized for deconv and eltwise. We do not need this anymore.
- *33870*

Revert "[IE CLDNN] Use fsv4 when feature-depth is shallow (#4398)"

---

ngraph/frontend/onnx_import/src/utils/convpool.cpp
ngraph/python/tests/__init__.py
ngraph/python/tests/test_onnx/test_ops_convpool.py

- The "paddings" attribute name is different in opset1 and all other opsets. It was not handled correctly in the helper. https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Pad-1
- The test did not catch the correct exception type.
- 35911

Fix for the paddings attribute handling for ONNX Pad@1

---

inference-engine/cmake/templates/InferenceEngineConfig.cmake.in

- If `InferenceEngineConfig.cmake` is used in `include()`, then `CMAKE_FIND_PACKAGE_NAME` is not defined.

Fixed InferenceEngineConfig.cmake usage in include()

---

docs/template_plugin/tests/functional/shared_tests_instances/single_layer_tests/reshape.cpp
inference-engine/tests/functional/inference_engine/serialization/single_layer/reshape.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/reshape.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/reshape.cpp
inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/reshape.hpp
inference-engine/tests/functional/shared_test_classes/src/single_layer/reshape.cpp

- *add SLT for special `-1` value in new shape dimensions*
This PR contains new `ReshapeLayerTestRevise` class because ARM plugin use `ReshapeLayerTest` and it can't be changed at one PR but this required multi-PR approach. 
- *45956*

Reshape OP: add SLT for special `-1` value in new shape dimensions

---

.github/workflows/mo.yml
inference-engine/ie_bridges/python/CMakeLists.txt
model-optimizer/CMakeLists.txt
model-optimizer/mo/main.py
model-optimizer/mo/utils/check_ie_bindings.py
model-optimizer/mo/utils/cli_parser.py
model-optimizer/unit_tests/mo/utils/cli_parser_test.py

In this PR I finally enable IE/NG python API dependency inside Model Optimizer. This is a prerequisite for nGraph transformations execution inside Model Optimizer backend which is targeted for the 22.1 release.
* "Build Python wheel" test was removed as it became obsolete after we published openvino-dev package. This change is aligned with @dkurt and we agreed that new tests for MO packaging will be implemented as a part of openvino-dev package validation.
* Added `_pyngraph` dependency to the ie_api target to simplify python APIs building process.
* Model Optimizer was updated to require IE and NG python APIs as a strong dependencies. And now it throws an exception if one of APIs is missing.
* Model Optimizer fallback path (which was used to produce an IR when IE wasn't available) was …

Turn on IE and NG python APIs by default inside Model Optimizer

---

model-optimizer/extensions/ops/einsum.py
model-optimizer/unit_tests/extensions/ops/einsum_test.py
ngraph/core/src/op/einsum.cpp
ngraph/test/type_prop/einsum.cpp

**Ticket:** 57791
**Root cause analysis:** There is a bug in recovery of output subscript in case of *Einsum-7* implicit mode.
The repeated labels in input subscripts except of ellipsis must not be included into recovered output subscript.
Example 1: equation="i,i" in implicit mode is equivalent to "i,i->" in explicit mode. Now nGraph and MO recover "i,i->i" that is incorrect.
Example 2: equation="a...b,b..." in implicit mode is equivalent to "a...b,b...->...a" in explicit mode.
**Solution:** Fix both Einsum implementation in both nGraph core and MO. Check if the label is met in other input subscripts
before to include into the recovered output subscript.

Fix recovery of output subscript in Einsum implicit mode

---

inference-engine/src/vpu/common/src/ngraph/operations/static_shape_broadcast.cpp
inference-engine/src/vpu/common/src/ngraph/utilities.cpp
ngraph/core/include/ngraph/validation_util.hpp

- *new value propagation mechanism is more reliable -- so we deprecate the legacy method which is unused currently in the product to delete it in the future with all the custom MaxValue structures*
- *58089*

Deprecated legacy maximum_value method

---

inference-engine/src/transformations/src/transformations/serialize.cpp
inference-engine/tests/functional/inference_engine/ir_serialization/tensor_iterator.cpp

- external_port_id for TI/Loop ops takes into account number of op inputs instead of input descriptors size.
- 55420

Fix external_port_id serialization for loop op.

---

ngraph/core/src/op/sqrt.cpp
ngraph/test/constant_folding.cpp

It's required for t2t-vit models.

Add support for fp64 in Sqrt's evaluate method

---

ngraph/core/src/op/convert.cpp
ngraph/test/constant_folding.cpp

It's required for t2t-vit models.

Add support for fp64 in Convert's evaluate

---

inference-engine/src/mkldnn_plugin/emitters/jit_load_store_emitters.cpp
inference-engine/src/mkldnn_plugin/emitters/jit_load_store_emitters.hpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_mvn_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_roi_pooling_node.cpp

- New load_emitter_context constructor arguments order
seems to be more convenient.
Store emitter now emits bf16 emu.
- CVS-53128

[CPU] Refactor load_emitter_context semantic. Update store emitter

---

inference-engine/src/offline_transformations/src/moc_transformations.cpp

Pruning transformation affects FP16 public models so we see unexpected performance degradation on some platforms. The decision was made to disable Pruning inside Model Optimizer in 21.4.

Disable Pruning Inside Model Optimizer

---

inference-engine/src/gna_plugin/gna_groups.hpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/convert_matmul_to_pointwise_conv.cpp

- Allow 2d reshape of a diagonal layer which is the functional first layer in the network (it's possible after batch size correct serialization during the model export)

[GNA] Allow 2d reshape of the first diagonal layer

---

inference-engine/thirdparty/clDNN/src/engine.cpp
inference-engine/thirdparty/clDNN/src/graph_optimizer/prepare_buffer_fusing.cpp
inference-engine/thirdparty/clDNN/src/include/engine_impl.h
inference-engine/thirdparty/clDNN/src/include/loop_inst.h
inference-engine/thirdparty/clDNN/src/include/program_impl.h
inference-engine/thirdparty/clDNN/src/program.cpp

- Corresponding PR : https://github.com/openvinotoolkit/openvino/pull/6192
- Previously crop optimization was disabled to improve cldnn::loop body networks performance, however this caused perf degradation of unrolled loop.
- Fix: Prevent crop optimization only when the node is inside a loop operation
- 57872

[IE CLDNN] Revert performance of unrolled loops

---

ngraph/core/src/op/util/gather_base.cpp

To fix Gather with compressed weights constant folding *i8, u8* precisions were added to Gather reference implementation.
- *58004*

Fix Gather constant folding for pruning

---

ngraph/core/include/ngraph/node.hpp
ngraph/core/include/ngraph/op/add.hpp
ngraph/core/include/ngraph/op/avg_pool.hpp
ngraph/core/include/ngraph/op/binary_convolution.hpp
ngraph/core/include/ngraph/op/convolution.hpp
ngraph/core/include/ngraph/op/cum_sum.hpp
ngraph/core/include/ngraph/op/divide.hpp
ngraph/core/include/ngraph/op/group_conv.hpp
ngraph/core/include/ngraph/op/log_softmax.hpp
ngraph/core/include/ngraph/op/max_pool.hpp
ngraph/core/include/ngraph/op/pad.hpp
ngraph/core/include/ngraph/op/reduce_l1.hpp
ngraph/core/include/ngraph/op/reduce_l2.hpp
ngraph/core/include/ngraph/op/reduce_mean.hpp
ngraph/core/include/ngraph/op/reduce_prod.hpp
ngraph/core/include/ngraph/op/reduce_sum.hpp
ngraph/core/include/ngraph/op/reshape.hpp
ngraph/core/include/ngraph/op/reverse.hpp
ngraph/core/include/ngraph/op/softmax.hpp
ngraph/core/include/ngraph/op/strided_slice.hpp
ngraph/core/include/ngraph/op/topk.hpp
ngraph/core/src/op/reverse.cpp
ngraph/core/src/op/softmax.cpp
ngraph/core/src/op/topk.cpp
ngraph/test/runtime/op/avg_pool.hpp
ngraph/test/runtime/op/convolution.hpp

- The get_default_value node is a leftover from the old ngraph repository and has been marked as deprecated in this PR
- Obsolete and incorrect get_version() overrides have been removed from the op classes that still had those implementations
- Follow-up task: 26703
- 58140

Deprecation of Node::get_default_value and some cleanup

---

docs/doxygen/ie_docs.xml
docs/ops/sort/MatrixNMS_8.md

- *Specification of a new operator called MatrixNMS.*
- *This Op functionally equivalent to NonMaxSuppression-5, with an non max suppression algorithm called matrix_nms, and perform more post-processing phases, and lay out the detection outputs in the way of PaddlePaddle detection.*
- *55968*

MatrixNMS-8 spec.

---

inference-engine/src/transformations/src/transformations/op_conversions/convert_nms_to_nms_ie_internal.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/execution_graph_tests/nms_transformation_for_last_node.cpp
inference-engine/tests/functional/plugin/shared/include/execution_graph_tests/nms_transformation_for_last_node.hpp
inference-engine/tests/functional/plugin/shared/src/execution_graph_tests/nms_transformation_for_last_node.cpp

Details:
- NMS transformation changes name of NMS node output (adds '/convert' suffix)
In case NMS transformation is the last node before Output, it leads to
the situation when InferRequest's network Outputs do not match any
graph's Output nodes.
Tickets:
- 57695

Correct output nodes naming in scope of NMS transformation

---

ngraph/core/include/ngraph/op/adaptive_avg_pool.hpp
ngraph/core/include/ngraph/op/adaptive_max_pool.hpp
ngraph/core/include/ngraph/ops.hpp
ngraph/core/include/ngraph/opsets/opset.hpp
ngraph/core/include/ngraph/opsets/opset8_tbl.hpp
ngraph/core/src/op/adaptive_avg_pool.cpp
ngraph/core/src/op/adaptive_max_pool.cpp
ngraph/test/CMakeLists.txt
ngraph/test/type_prop/adaptive_avg_pool.cpp
ngraph/test/type_prop/adaptive_max_pool.cpp
ngraph/test/visitors/op/adaptive_avg_pool.cpp
ngraph/test/visitors/op/adaptive_max_pool.cpp

- *Add AdaptiveMaxPool-8 and AdaptiveAvgPool-8 to ngraph*
- *56360*

Extend ngraph for AdaptivePool operations

---

inference-engine/tools/cross_check_tool/utils.py

- Device config is failed to parse

[Python Tools] Fix cross_check_tool device config parsing

---

inference-engine/src/cldnn_engine/cldnn_engine.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/resample/resample_kernel_opt.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/reduce_gpu_b_fs_yx_fsv16.cl

primitive performance better than decomposed transformations.
- Currently reduce operations with axis=1(feature) is decomposed to reshape+pooling+reshape. Use primitive reduce performance is better without accuracy difference.

[IE CLDNN] Use single primitive reduce when axis=1(feature)

---

inference-engine/thirdparty/clDNN/api/cldnn/graph/network.hpp
inference-engine/thirdparty/clDNN/src/network.cpp

- If network was deleted before getting memory from `network_output`, then we had invalid memory access to stream reference
- *58418*

[IE CLDNN] Fixed invalid stream reference in network_output

---

docs/ops/activation/Swish_4.md
inference-engine/tests/functional/inference_engine/serialization/single_layer/activation.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/activation.cpp
ngraph/core/include/ngraph/op/swish.hpp
ngraph/core/src/op/swish.cpp
ngraph/test/CMakeLists.txt
ngraph/test/backend/swish.in.cpp
ngraph/test/type_prop/swish.cpp
ngraph/test/visitors/op/swish.cpp

Add description into Swish spec.
Add more check when constructing Swish OP in NGraph.
Change to use RTTI declear/define for Swish OP.
Add type prop , visitor (attributes), SSLT, backend , serialization tests for Swish OP.
37560

Revise swish

---

ngraph/test/visitors/op/round.cpp

fix mistake in b68166fc
issue:test_mode always use one type
Signed-off-by: Hu, Yuan2 <yuan2.hu@intel.com>
- fix mistake in b68166fc, issue:test_mode always use one type
- 37565

Revise Round operation reference implementation

---

inference-engine/thirdparty/clDNN/runtime/CMakeLists.txt
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_common.hpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_engine.cpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_engine.hpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_ext.hpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_kernels_factory.cpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_memory.cpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_stream.hpp
inference-engine/thirdparty/clDNN/tests/module_tests/usm_memory_test.cpp

- Added `UsmHelper` class which loads and holds all function ptrs to work with USM
- `UsmHelper` is created once for each `ocl_engine` instance
- enabled cpplint for runtime component
- used `load_entry_point` function for other extensions (surface sharing)
-  suppressed warning from old GCC about pointer-to-object to pointer-to-function cast.
- 46420
- 28579

[IE CLDNN] USM refactoring

---

model-optimizer/extensions/load/tf/loader.py
model-optimizer/unit_tests/extensions/load/tf/loader_test.py

Root cause analysis: Some TF models does not have Convolution operations with inputs in NHWC layout. For these models users must specify `\-\-disable_nhwc_to_nchw` command line parameter to disable model conversion from NHWC to NCHW layout. If user does not specify it then the model will be converted incorrectly.
Solution: Add code which traverses the model and looks for convolution operations in NHWC layout. If these operations are not found then the model is considered in NCHW layout. In this case the MO shows a message that an additional parameter is needed to convert the model. We cannot change the way how MO converts the model because it will be a backward incompatible change.
Ticket: 51259
Code:
Validation:
Documentation:

MO now shows a hint when --disable_nhwc_to_nchw is needed

---

inference-engine/thirdparty/movidius/XLink/shared/src/XLinkSemaphore.c

- changed calling of sem_timedwait() to account for EINTR  error code, so it would be restarted.
- CVS-58042

[VPU] changed calling of sem_timedwait() to account for EINTR  error

---

ngraph/python/src/pyngraph/frontend/frontend_manager.cpp
ngraph/python/tests/test_ngraph/test_frontendmanager.py

Original issue was discovered in Model Optimizer with command:
> mo.py --framework tf --saved_model_dir path_to_saved_model
Root cause is that FrontEndManager is created and added to 'argparse' which then is serialized using pickle.dumps.
Pickle GetState/SetState shall be supported for FrontEndManager, empty implementation is enough
- 58670

[Frontend] pickle.dumps support for FrontEndManager

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_deconv_node.cpp

- *jit_avx512_core_x8s8s32x_deconv_fwd_kernel doesn't support BF16 output and this fix sets the deconvolution node in FP32 precision. This is a reason of error on model unet-camvid-int8-onnx-0001/caffe2. In future, we have to extend jit_avx512_core_x8s8s32x_deconv_fwd_kernel from oneDNN to support BF16 output data type*
- *55902*

[INT8+BF16] x8s8s32x_deconv_fwd bf16 output case elimination

---

inference-engine/tests/functional/plugin/myriad/shared_tests_instances/skip_tests_config.cpp

- IEClassNetworkTestP.LoadNetworkActualNoThrow fails on Ununtu20. Disabled it and added TODO
- *...*
- 58621

Disable IEClassNetworkTestP.LoadNetworkActualNoThrow test

---

CMakeLists.txt
cmake/templates/ngraphConfig.cmake.in
inference-engine/src/snippets/CMakeLists.txt
inference-engine/src/transformations/CMakeLists.txt
ngraph/frontend/CMakeLists.txt
ngraph/frontend/frontend_manager/CMakeLists.txt
ngraph/frontend/onnx_common/CMakeLists.txt
ngraph/frontend/onnx_editor/CMakeLists.txt
ngraph/frontend/onnx_import/CMakeLists.txt
ngraph/frontend/paddlepaddle/CMakeLists.txt
ngraph/test/frontend/CMakeLists.txt

- Added install for PDPD FE headers
- Proper folder location for `frontend_manager`
- Updated `ngraphConfig.cmake.in` to reflect FE manager and PDPD FE
- Used `ngraph_dev` component for frontends headers

Fixed / improved cmake for ngraph frontends

---

inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/binary_convolution/binary_convolution_kernel_1x1.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/binary_convolution/binary_convolution_kernel_1x1_b_fs_yx_fsv16.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/binary_convolution/binary_convolution_kernel_generic.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/convolution/convolution_kernel_b_fs_zyx_fsv16.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/eltwise/eltwise_kernel_b_fs_yx_fsv16.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/eltwise/eltwise_kernel_b_fs_yx_fsv4.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/eltwise/eltwise_kernel_base.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/gemm/gemm_kernel_tiled_opt.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/permute/permute_kernel_ref.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/permute/permute_kernel_tile_8x8_4x4.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/permute/permute_kernel_tile_8x8_4x4_fsv.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/reduce/reduce_kernel_b_fs_yx_fsv16.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/select/select_kernel_base.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/common/jitter.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/common/jitter.h
inference-engine/thirdparty/clDNN/kernel_selector/core/common/kernel_base_opencl.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/kernel_base.cpp

- Floating point numbers with custom global locale could be converted with comma as separator which led to invalid OCL code generation and compilation error. So replaced all usages of `std::to_string` (which respects locale) with custom `toCodeString` function which serialize float as hex value without any separators.
- Related PR to release branch #6243
- *57885*

[IE CLDNN] Fixed code gen with custom locale

---

inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/reshape.hpp
inference-engine/tests/functional/shared_test_classes/src/single_layer/reshape.cpp

- *remove ReshapeLayerTestRevise*
- *57976*
- https://github.com/openvinotoolkit/openvino_contrib/pull/162
- https://github.com/openvinotoolkit/openvino/pull/6276

remove temporary ReshapeLayerTestRevise

---

inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.cpp

[CPU] fixed conv + dw conv fusing

---

inference-engine/src/auto_plugin/auto_plugin.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/infer_request.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/infer_request_config.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/infer_request.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/infer_request_config.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/config.hpp
inference-engine/tests/functional/plugin/shared/include/behavior/infer_request_config.hpp

- Will not skip test cases for auto-device plugin, `ASSERT_THROW` exception when using incorrectConfig;
- *57552*

[AUTO][IE TESTS] Fix IE test issue for auto-device plugin

---

inference-engine/src/gna_plugin/transformations/insert_transpose_before_matmul.cpp
inference-engine/tests/unit/gna/ngraph/transformations/gna_insert_transpose_before_matmul.cpp

[GNA] add ngraph-based transformations tests
- all new tests will be put into gnaFuncTests executable binary
- create dir  inference-engine/tests/unit/gna/ngraph/transformations for all ngraph-based transformations tests
- add test on InsertTransposeBeforeMatmul transformation
- fix InsertTransposeBeforeMatmul transformation copying runtime info
- 57583

GNA add InsertTransposeBeforeMatmul unit tests

---

docs/IE_DG/Deep_Learning_Inference_Engine_DevGuide.md
docs/IE_DG/supported_plugins/MULTI.md
docs/MO_DG/Deep_Learning_Model_Optimizer_DevGuide.md
docs/MO_DG/prepare_model/Config_Model_Optimizer.md
docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
docs/doxygen/doxy_md_filter.py
docs/get_started/get_started_dl_workbench.md
docs/how_tos/how-to-links.md

- *item1*
- *...*
- *ticket-id*

automatic insertion of htmlonly

---

model-optimizer/mo/main.py
model-optimizer/mo/subprocess_main.py
model-optimizer/requirements_dev.txt
model-optimizer/unit_tests/mo/frontend_ngraph_test.py

- Add error message when InferenceEngine or nGraph Python API is not found to beginning of subprocess_main
- Show graceful error message before doing anything if IE or nGraph Python API is not found
Root cause analysis: It was assumed that Inference Engine or nGraph API is always available when inner 'subprocess' is being executed. So developer is able to 'import ngraph' in beginning of file. However the real check if ngrpah/ie python API existence is done after parsing command line parameters. So invalid imports show unfriendly messages about import errors inside Model-optimizer. Before PR #6001 there were no such situations and graceful error message was shown
Solution:
- Add error message when InferenceEngine or nGraph Python API is not found to beginning of subprocess_main
- Show …

[MO] Fix showing graceful error message when no ngraph case

---

inference-engine/src/inference_engine/os/lin/lin_shared_object_loader.cpp

- We should check all symbols in library in loading time, not in runtime to dispatch cases when dependencies of loadable library can't be resolved

Сheck all symbols in dload, not lazy

---

inference-engine/src/gna_plugin/gna_graph_compiler.cpp
inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/transformations/convert_padded2valid_conv.cpp
inference-engine/src/gna_plugin/transformations/convert_padded2valid_conv.hpp
inference-engine/tests/functional/plugin/gna/pass_tests/padded2valid_conv.cpp

- Add transformation of padded convolutions to valid ones
- The network needs to be in NHWC order and the following cases are supported:
Transpose(NHWC>NCHW) => conv => Transpose(NCHW->NHWC)
Transpose(NHWC->NCHW) => conv => broadcasted add (BIAS) => Transpose(NCHW->NHWC)
Transpose(NHWC->NCHW) => conv => broadcasted add (BIAS) => MaxPooling => Transpose(NCHW->NHWC) (2d max pool case)
Transpose(NHWC->NCHW) => conv => broadcasted add (BIAS) => ActivationFunction => Transpose(NCHW->NHWC)
Transpose(NHWC->NCHW) => conv => broadcasted add (BIAS) => MaxPool => ActivationFunction => Transpose(NCHW->NHWC)
Transpose(NHWC->NCHW) => conv => Transpose(NCHW->NHWC) => BIAS => Transpose(NCHW->NHWC)
Transpose(NHWC->NCHW) => conv => Transpose(NCHW->NHWC) => BIAS => AF => Transpose(NCHW->NHWC).
The last two …

[GNA] Add transformation of padded to valid convolutions

---

model-optimizer/extensions/front/tf/ObjectDetectionAPI.py
model-optimizer/extensions/front/tf/ssd_support_api_v2.4.json
model-optimizer/mo/utils/graph.py
model-optimizer/unit_tests/mo/utils/graph_test.py

Root cause analysis: Box coordinates in TensorFlow models are calculated as "YXYX", but IE expects them to be calculated in "XYXY" order. When MO inserts DetectionOutput operation instead of a sub-graph of operations it finds a closest Conv2D node and updates the weights to calculate box coordinates in "XYXY" order. The node is found using bfs algorithm in counter edge direction. There is a ShapeOf sub-graph which calculates shape for some Reshape operation in the provided model. This ShapeOf takes shape of the Conv2D node in a side branch and the current bfs algorithm adds this convolution node to the list for updating weights which is wrong.
Solution: Change the bfs algorithm to stop at the ShapeOf nodes. Updated transformation configuration files to correctly work for all SSD models. …

Updated conversion of TF OD API 2.4 SSD models

---

model-optimizer/CMakeLists.txt

- Exclude "openvino_mo.egg-info" and "build" folders (generated during wheels building) from cpack archives
- Add unit_tests folder to tests cpack component
- 58434
- 58695

[MO] exclude build artifacts and add unit_tests to cpack

---

inference-engine/ie_bridges/c/src/ie_c_api.cpp

- Fix InferenceEngine::Core initialization. Previously IE::Core was
default constructed first, then overwritten by another instance.
This causes problems if the library user attempts to opt-out of the
default "plugins.xml" plugin loading mechanism.

Fix an initialization issue in `ie_core_create`

---

inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/deformable_convolution.cpp
ngraph/core/reference/include/ngraph/runtime/reference/deformable_convolution.hpp

I think there is a error about the reference implementation of deformable_convolution.
The two parameters group and deformable_group is independent, and there are details about the parameter deformable_group in [MXNet](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/nn/deformable_im2col.h#L230)
Suppose that the shape of input data is (1,6,5,5), the shape of filter is (2,3,3,3), the shape of the offset is (1,54,3,3), group is 2, deformable_group is 3. And an error will occur on line 256 when group_idx equals 1.

Fix deformable_convolution

---

inference-engine/tests/functional/plugin/gna/shared_tests_instances/skip_tests_config.cpp

- One test showed instability, returned back to the skip list
- Updated ticket in the test description
- 58039

[GNA] Functional test returned to the skip list due to instability

---

inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.h
inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/convolution_gpu_bfyx_os_iyx_osv16.cl

- Improve computation inefficiency and cache efficiency for bfyx convolution with shallow output feature size
- 57942

 [IE CLDNN] Improve bfyx convolution performance for shallow output ch

---

docs/IE_DG/Int8Inference.md
docs/IE_DG/img/cpu_int8_flow.png

cherry-pick to release: https://github.com/openvinotoolkit/openvino/pull/5949
- INT8 inference documentation update
- 56490

[Runtime] INT8 inference documentation update

---

model-optimizer/extensions/back/compress_quantized_weights.py
model-optimizer/unit_tests/extensions/back/compress_quantized_weights_test.py

Description: TensorFlow FakeQuantize operation has different dequantize part than in the Model Optimizer so we optimize zero point in this case.
```
TensorFlow dequantization scheme:
[1; 2^num_bits - 1] for narrow_range==true 
and
[0; 2^num_bits - 1] for narrow_range==false
Model Optimizer dequantization scheme:
[-levels // 2; levels + (-levels // 2) - 1]
```
Ticket: 59063
Code:
Validation:
Documentation:

Zero point optimization

---

ngraph/python/setup.py
ngraph/python/src/ngraph/__init__.py
ngraph/python/src/ngraph/opset8/__init__.py
ngraph/python/src/ngraph/opset8/ops.py
ngraph/python/src/pyngraph/node_factory.cpp
ngraph/python/tests/test_ngraph/test_create_op.py
ngraph/test/util/engine/ie_engines.cpp

- *python api for MulticlassNms/MatrixNms*
- *56923*
- *56907*

MulticlassNms/MatrixNms: ngraph python api

---

inference-engine/thirdparty/clDNN/api/cldnn/runtime/engine.hpp
inference-engine/thirdparty/clDNN/api/cldnn/runtime/memory_caps.hpp
inference-engine/thirdparty/clDNN/api/cldnn/runtime/memory_pool.hpp
inference-engine/thirdparty/clDNN/runtime/engine.cpp
inference-engine/thirdparty/clDNN/runtime/memory.cpp
inference-engine/thirdparty/clDNN/runtime/memory_pool.cpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_engine.cpp
inference-engine/thirdparty/clDNN/src/include/network_impl.h
inference-engine/thirdparty/clDNN/src/network.cpp
inference-engine/thirdparty/clDNN/src/primitive_inst.cpp

- Memory pool was moved from engine to `network_impl`. 
- Memory usage tracking was moved from memory pool to engine.
- Added allocation/free logging with Verbose option
- *59666*

[GPU] Moved memory pool to network

---

inference-engine/src/gna_plugin/backend/am_intel_dnn.cpp
inference-engine/src/gna_plugin/backend/am_intel_dnn.hpp
inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/gna_plugin_config.cpp
inference-engine/src/gna_plugin/transformations/convert_padded2valid_conv.cpp
inference-engine/src/gna_plugin/transformations/convert_padded2valid_conv.hpp
inference-engine/tests/functional/plugin/gna/pass_tests/convert_padded2valid_conv.cpp
inference-engine/tests/unit/gna/ngraph/transformations/gna_convert_padded2valid_conv.cpp

- combine seven ngraph matcher passes into two
- remove max pool size checking
- add ngraph reference tests for subgraphs which were processed by POT
- fix remaining issues with Max Pooling output calculations
- add setting of default compile target based on execution target
- 57977

Add fake quantize support for convolution padding

---

inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp

- *[PR#6195](https://github.com/openvinotoolkit/openvino/pull/6195) with i8/u8 support for reference was merged. So we can launch Gather-7 CPU tests for i8*
- *N/A*

[CPU][IE TESTS] Added Gather-7 I8 test support

---

tests/stress_tests/CMakeLists.txt
tests/stress_tests/common/CMakeLists.txt
tests/stress_tests/memcheck_tests/CMakeLists.txt
tests/stress_tests/memleaks_tests/CMakeLists.txt
tests/stress_tests/unittests/CMakeLists.txt
tests/time_tests/CMakeLists.txt
tests/time_tests/src/timetests/CMakeLists.txt

- Parallel build of stress and time tests lead to race while rebuild libgflags_nothreads.a (gflags isn't available in IE installed via installer, so targets should build it from sources by itself). As a solution each target will build artifacts to it's own folder, and it will be copied to a correct place via installation
- In addition move `gflags` to `StressTestsCommon` library to pass dependency to each target via library
- 55465

Develop installation rules for time and stress tests

---

inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/skip_tests_config.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/eltwise_reshape_activation.cpp

- Deprecated check has been removed in `SubstituteScaleShiftBroadCastPass`
- Changed order of passes in `gna_lugin.cpp` due to dimensions inconsistency and memory errors in `TransposeWeightsFromNCHWToNHWCPass`
- Added check in `TransposeWeightsFromNCHWToNHWCPass` to avoid memory errors in future
- Added 4d shape in `EltwiseReshapeActivation` test
- Removed string related to `KSOFunction` test in GNA skip config
- *51525*

[GNA] KSOFunction test fix

---

scripts/CMakeLists.txt
scripts/deployment_manager/configs/darwin.json
scripts/deployment_manager/configs/linux.json
scripts/deployment_manager/configs/windows.json
scripts/deployment_manager/deployman/config.py
scripts/deployment_manager/deployman/logger.py
scripts/deployment_manager/deployman/main.py
scripts/deployment_manager/deployman/ui.py
scripts/deployment_manager/deployment_manager.py

- Moved Deployment Manager tool to Open Source

Migrate Deployment Manager tool to Open Source

---

inference-engine/src/transformations/src/transformations/common_optimizations/transpose_sinking.cpp
inference-engine/tests/functional/inference_engine/transformations/transpose_sinking_test.cpp

- *TransposeFuse transformation wasn't preserving node names after replacing. Issue was introduced by #5854*
- *60327*

Fix node name issue introduced by #5854

---

inference-engine/src/gna_plugin/gna_graph_patterns.hpp
inference-engine/tests/functional/plugin/gna/pass_tests/remove_permutations_NHWC_to_NCHW_pass.cpp

- Reshape-Conv-Transpose pattern isn't recognized for 2d Convolution, check is corrected
- Added RemovePermutations test for 2d case
60601

[GNA] Fix Reshape-Conv-Transpose pattern recognition for 2d convolution

---

model-optimizer/mo/utils/check_ie_bindings.py
model-optimizer/mo/utils/find_ie_version.py

Root cause analysis: It was not taken into account that user may have old version of OpenVINO installed but trying to use latest Model-Optimizer
Solution:
- Add 'import ngraph.frontend' to check_ie_bindings to ensure correct version of ngraph Python API is installed
- Inside setup_env - join PYTHONPATH candidate to beginning of existing PYTHONPATH 
Ticket: 60606
Code:
* [N/A ]  Comments (code is self-explained)
* [N/A]  Transformation generates reshape-able IR
* [N/A]  Transformation preserves original framework node names
Validation:
* [N/A]  Framework operation tests
* [N/A]  Transformation tests
* [N/A]  Model Optimizer IR Reader check
Documentation:
* [N/A]  Supported frameworks operations list
* [N/A]  Guide on how to convert the **public** model
* [N/A]  User guide update
Build …

MO: ensure ngraph.frontend is installed

---

inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/deformable_convolution.cpp

- *decrease input_shape and kernal in CPU functional tests to to reduce the time spent on tests.*

DeformableConv: decrease input_shape and kernal in CPU functional tests

---

cmake/features.cmake
inference-engine/src/cldnn_engine/CMakeLists.txt
inference-engine/thirdparty/CMakeLists.txt
inference-engine/thirdparty/clDNN/CMakeLists.txt
inference-engine/thirdparty/clDNN/runtime/debug_configuration.cpp

- Allowed `SNAKE_CASE_WITH_CAPITALS` and `CamelCase` for env debug options.
- Allowed multiple possible prefixes for some options `OV_GPU` and `OV`
- Added common cmake option for debug caps for any OV component
- Renamed cmake option for GPU

[GPU] Allowed more complex syntax for debug config options.

---

ngraph/frontend/paddlepaddle/src/proto/framework.proto

- Added optimization for Protobuf-lite runtime (don't include unnecessary features)
- Binary size for libpaddlepaddle_frontend.so is reduced from 1.6MB to 740KB
- Unit-tests are working now with NGRAPH_USE_PROTOBUF_LITE=ON option
- 60823

PDPD frontend - support of protobuf_lite

---

inference-engine/samples/benchmark_app/README.md
inference-engine/samples/benchmark_app/benchmark_app.hpp
inference-engine/samples/benchmark_app/main.cpp
tools/benchmark_tool/openvino/tools/benchmark/benchmark.py
tools/benchmark_tool/openvino/tools/benchmark/main.py
tools/benchmark_tool/openvino/tools/benchmark/parameters.py

Now the `benchmark_app` tool also reports median(50 percentile) for latency metric. But for some benchmarks reporting other percentiles may be useful too. This patch introduces the new flag for the `benchmark_app` tool, which allows specifying the percentile which should be calculated during the measurements.

Intoduce -latency_percentile flag for the benchmark_app tool

---

tests/conditional_compilation/tools/infer_tool.py

- Removed print results of inference from `infer_tool` due to `sea_runtool` freeze when `infer_tool.py` try to print a long line with results
- *59427*

Removed print results of inference from infer_tool

---

.ci/azure/linux.yml
ngraph/test/CMakeLists.txt
ngraph/test/frontend/paddlepaddle/basic_api.cpp
ngraph/test/frontend/paddlepaddle/cut_specific_model.cpp
ngraph/test/frontend/paddlepaddle/load_from.cpp
ngraph/test/frontend/paddlepaddle/op_fuzzy.cpp
ngraph/test/frontend/paddlepaddle/partial_shape.cpp
ngraph/test/frontend/paddlepaddle/places.cpp
ngraph/test/frontend/paddlepaddle/set_element_type.cpp
ngraph/test/frontend/shared/include/utils.hpp
ngraph/test/frontend/shared/src/basic_api.cpp
ngraph/test/frontend/shared/src/cut_specific_model.cpp
ngraph/test/frontend/shared/src/load_from.cpp
ngraph/test/frontend/shared/src/op_fuzzy.cpp
ngraph/test/frontend/shared/src/partial_shape.cpp
ngraph/test/frontend/shared/src/set_element_type.cpp

- Install generated PDPD test models as 'test' component
- Needed when test package is installed on another machine which don't have generated models
- To search installed models, when build folder doesn't exist, 'FE_TEST_MODELS' env variable is introduced
- CI script for openvino-lin is updated to set 'FE_TEST_MODELS' before tests execution
- Build OpenVINO with tests
- Install OpenVINO and tests using cmake_install.cmake
- Verify that `<install_dir>/tests/` folder contains pdpd_test_models
- Remove `<cmakeDir>/ngraph/test/pdpd_test_models` dir
- Verify that 'unit-test' is now failed
- Do `export FE_TEST_MODELS=<install_dir>/tests`
- Verify that unit tests can be executed now
- *ticket-id*

PDPD: Install generated PDPD test models as 'test' component

---

inference-engine/src/offline_transformations/src/moc_transformations.cpp

Enable additional plugin independent fusions into MOC backend phase. Validation shows that this transformations additionally optimize graphs. For example MVN fusion pass fuse a lot of sub-graphs in bert models family. Also Clamp fusion sucessfully works on some super resolution networks. All other passes have implementation inside MO legacy frontends so they currently doesn't optimize graphs but they will be necessary for new frontends.
<details>
<summary>Click to expand!</summary>
|FINAL MOC PIPELINE|CURRENT MOC PIPELINE|
|---|---|
|InitNodeInfo|InitNodeInfo|
|ConstantFolding| |
|SimplifyShapeOfSubGraph|SimplifyShapeOfSubGraph|
|RemoveFilteringBoxesBySize|RemoveFilteringBoxesBySize|
|ConvertQuantizeDequantize|ConvertQuantizeDequantize|
| | |
|TransposeFQReduction| |
|TransposeReduction| …

Add more passes to the MOC backend

---

ngraph/test/util/visitor.hpp

- *initialize NodeBuilder registry by IIFE*
- *NONE*

initialize NodeBuilder registry by IIFE instead of double lock pattern

---

inference-engine/src/offline_transformations/src/moc_transformations.cpp

Enable TransposeSyncing and BroadcastElementwiseFusion (plugin independent fusions) into MOC backend phase. Some of this passes doesn't have analogs in MO so we expect that IR will be changed (optimized).
Validation shows positive changes in IR. In most cases changes relates to Transpose syncing transformations that were missing in MO pipeline.
<details>
<summary>Click to expand!</summary>
|Final MOC Pipeline|Enabled|
|---|:---:|
|InitNodeInfo|:white_check_mark:|
|ConstantFolding| |
|SimplifyShapeOfSubGraph|:white_check_mark:|
|RemoveFilteringBoxesBySize|:white_check_mark:|
|ConvertQuantizeDequantize|:white_check_mark:|
| | |
|**TransposeFQReduction**|:tada:|
|**TransposeReduction**|:tada:|
|**TransposeFuse**|:tada:|
|**SplitSqueezeConcatFusion**|:tada:|
| | | …

Enable TransposeSyncinc and BroadcastElementwiseFusion in MOC Backend

---

cmake/developer_package/compile_flags/sanitizer.cmake

Use default linker for sanitizer builds
Compiler out of memory tracking variables in GPU tests.
This trigger recompilation without tracking. Disabling
tracking globally as not required option.
UBSan build is failing on maybe uninitialized variable.
Temporarily disable the check.

Fix sanitizer build

---

model-optimizer/extensions/back/ReverseInputChannels.py
model-optimizer/extensions/front/tf/pad_tf_to_pad.py
model-optimizer/unit_tests/extensions/back/ReverseInputChannels_test.py
model-optimizer/unit_tests/extensions/front/tf/pad_tf_to_pad_test.py

Ticket: 59156
The is copy of code from MR https://github.com/openvinotoolkit/openvino/pull/6506 for release branch.
Pattern Split->Concat was added before Pad op.
As a part of optimizations ReverseChannels operation was replacing to pattern Split->Сoncat. Earlier if the pattern inserted before Pad layer we fused it to Pad. But it was wrong and the optimization was removed. So the root cause is that before Pad we insert  Split->Сoncat pattern and it leads to regression for some topologies.
The fix moves ReverseChannels after Pad layer. It allows optimize reverse input channels propagation and avoid work around with insert Split->Сoncat subgraph.
Validation:
Documentation:

Fixing Split-Concat reverse input channel

---

.ci/azure/linux.yml
.ci/azure/windows.yml
cmake/developer_package/IEDevScriptsConfig.cmake

- Win+Lin: add "clean build dir" step to ensure generated test models are taken from installation
- Windows fix: execute "pip show" on same drive where python is installed. On CI machines Python is installed on "C:" drive, but build dir is on "D:" drive
- Windows: execute tests with FE_TEST_MODELS env variable
- 59502

[PaddlePaddle] Unit tests run on CI fixes (Win+Lin)

---

inference-engine/src/inference_engine/cnn_network_ngraph_impl.cpp
inference-engine/tests/functional/inference_engine/cnn_network/cnn_ngraph_impl_tests.cpp

Do not throw an exception if we have 2 result op for one tensor

---

inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api_impl_defs.pxd
inference-engine/ie_bridges/python/tests/test_IECore.py

- *Some functions in python api don't release GIL, when come into cpp, where GIL is needn't.  We can release GIL in these functions, using the the nogil keyword. It will speed up code, which using multithreading in  python.*
- *57119*

[IE PYTHON] Release GIL in some functions 

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_normalize_node.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/normalize_l2.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/normalize.cpp
ngraph/test/runtime/ie/unit_test.manifest

- *Added sorting of axes*
- *59794*

[CPU] NormalizeL2 - unsorted axes are not supported

---

inference-engine/src/offline_transformations/src/pruning/propagate_masks.cpp
ngraph/core/include/ngraph/op/constant.hpp
ngraph/core/src/op/constant.cpp
ngraph/core/src/op/reshape.cpp
ngraph/core/src/op/squeeze.cpp
ngraph/core/src/op/unsqueeze.cpp
ngraph/test/constant_folding.cpp

This change optimizes Reshape operation constant folding. In more cases Constant which goes to Reshape has more than one consumer (because we make function copy with shared constants) so the previous optimization wasn't efficient in most cases. But with this changes we don't make Constant data copy anymore because we now create Constant with shared data but with different shape.

Avoid Constant data copy inside Reshape constant folding

---

ngraph/core/include/ngraph/enum_names.hpp
ngraph/core/include/ngraph/interval.hpp
ngraph/core/include/ngraph/partial_shape.hpp
ngraph/core/src/dimension.cpp
ngraph/core/src/interval.cpp
ngraph/core/src/partial_shape.cpp
ngraph/core/src/type/element_type.cpp

- *move some method to headers which allow it to be inline*
- *`PartialShape` c-tors will consume (move) vector of `Dimension`*
- *initialize map returning by `get_type_info_map` before `main` - purge static function member "mutex"*
- *find in map and `terminate` if not found `TypeInfo`*
- *61261*
- *FakeQuantize::validate_and_infer_types* approximately speedup: 20%

Validate speedup

---

cmake/dependencies.cmake

It seems that it's not necessary to define `CMAKE_STAGING_PREFIX` for cross-compilation build.
The installation path is defined by config `CMAKE_INSTALL_PREFIX`.

Remove CMAKE_STAGING_PREFIX initialization 

---

ngraph/frontend/onnx/onnx_import/src/editor.cpp
ngraph/test/onnx/onnx_editor.cpp

Fixed problem with model_inputs method in ONNX Editor

---

ngraph/core/reference/include/ngraph/runtime/reference/logical_reduction.hpp

- *Remove deprecated reduce logical reference implementation signatures*
- *58946*

Remove deprecated API for ReduceLogicalAnd and ReduceLogicalOr reference implementations

---

ngraph/frontend/paddlepaddle/src/op/deformable_conv.cpp
ngraph/frontend/paddlepaddle/src/op/matrix_nms.cpp
ngraph/frontend/paddlepaddle/src/op/multiclass_nms.cpp
ngraph/frontend/paddlepaddle/src/op_table.cpp

enable 3 op conversions for PDPD frontend. They are opset8 operations asked by PaddlePaddle detection NN.
- *matrix_nms*
- *multiclass_nms*
- *deformable_convolution*
- *54689*
- *53847*
- *57133*
recreated as https://github.com/openvinotoolkit/openvino/pull/6619 is unintentionally closed.

[FrontEnd]enable pdpd ops conversion part4: deformable_convolution, multiclass_nms and matrix_nms.

---

inference-engine/samples/common/utils/include/samples/classification_results.h
inference-engine/src/cldnn_engine/cldnn_graph.h
inference-engine/src/cldnn_engine/cldnn_infer_request.cpp
inference-engine/src/cldnn_engine/cldnn_infer_request.h
inference-engine/src/cldnn_engine/cldnn_remote_context.cpp
inference-engine/src/cldnn_engine/cldnn_remote_context.h
inference-engine/tests/functional/plugin/gpu/remote_blob_tests/cldnn_remote_blob_tests.cpp
inference-engine/thirdparty/clDNN/api/cldnn/graph/network.hpp
inference-engine/thirdparty/clDNN/api/cldnn/runtime/memory_caps.hpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_memory.cpp
inference-engine/thirdparty/clDNN/src/include/loop_inst.h
inference-engine/thirdparty/clDNN/src/include/mutable_data_inst.h
inference-engine/thirdparty/clDNN/src/include/primitive_inst.h
inference-engine/thirdparty/clDNN/src/loop.cpp
inference-engine/thirdparty/clDNN/src/mutable_data.cpp
inference-engine/thirdparty/clDNN/src/network.cpp
inference-engine/thirdparty/clDNN/src/primitive_inst.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/loop_gpu_test.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/set_output_memory_gpu_test.cpp

The patch replaces host blobs with mappable ClBlobs in all InferRequests.
Details:
- Ensures that each InferRequest has its own set of input/output GPU memory objects
- Fixes memory corruptions when multiple InferRequests are ran simultaneously
- Enables correct video surfaces sharing when multiple streams are used
- Should enable correct mapping of input/result blobs on dGPUs
Will be merged instead of #5319

[GPU] Replace internal TBlobs with mappable ClBlobs 

---

.ci/azure/linux.yml
ngraph/python/CMakeLists.txt
ngraph/python/tests/mock/mock_py_ngraph_frontend/CMakeLists.txt
ngraph/python/tests/mock/pyngraph_fe_mock_api/CMakeLists.txt

- Added install rules for 'pyngraph' tests  mock frontends
- Add execution of pyngraph-tests to Azure-Linux CI
- There are some tests which take long time to execute (onnx_zoo models + onnx_backend)
- Also some tests are failed from onnx_zoo and onnx_backend but since these are ignored anyway this doesn't block this CI task
- *ticket-id*

Pyngraph tests: Install & run on Azure-Linux CI

---

ngraph/core/reference/include/ngraph/runtime/reference/fake_quantize.hpp

- *remove legacy fake quantize reference implementation API*
- *60665*

remove legacy fake quantize reference implementation API

---

inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp
inference-engine/src/mkldnn_plugin/mkldnn_infer_request.cpp

- Seem to be more convenient than checking and updating batch limit
in scope of Infer request call.
- 57143

[CPU] Update batch limit right after setting it

---

model-optimizer/mo/utils/summarize_graph.py

Root cause analysis: For some TF saved_model, we have a framework error after running the script `summarize_graph.py`.
> python3 /opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer/mo/utils/summarize_graph.py --input_model resnet_v2_50_inference_graph.pb
Traceback (most recent call last):
File "/opt/intel/openvino_2021.4.582/deployment_tools/model_optimizer/mo/utils/summarize_graph.py", line 75, in <module>
model_dir=argv.saved_model_dir, saved_model_tags=argv.saved_model_tags)
ValueError: too many values to unpack (expected 2)
Solution: to write 
```python3
tags = argv.saved_model_tags.split(",")
graph_def, _, _ = load_tf_graph_def(graph_file_name=argv.input_model, is_binary=not argv.text,
checkpoint=argv.input_checkpoint,
model_dir=argv.saved_model_dir, …
```

Fix for summarize_graph.py.

---

inference-engine/thirdparty/clDNN/src/program.cpp

This PR fixes invalid memory access when `old_node` may be used after removing

[GPU] Fix invalid memory access in replace_all_usage fucntion

---

inference-engine/samples/CMakeLists.txt

Fix to https://github.com/openvinotoolkit/openvino/pull/6840
It sets armv7 instruction set to x32 only. Previous PR affects ARM64 as well.

Define armv7 instruction set for IE samples built natively on x32 ARM

---

inference-engine/src/offline_transformations/include/disable_shapeof_constant_folding.hpp
inference-engine/src/offline_transformations/src/disable_shapeof_constant_folding.cpp
inference-engine/src/offline_transformations/src/moc_transformations.cpp
inference-engine/src/transformations/include/transformations/low_precision/disable_convert_constant_folding_on_const_path.hpp
inference-engine/src/transformations/include/transformations/rt_info/disable_constant_folding.hpp
inference-engine/src/transformations/src/transformations/low_precision/disable_convert_constant_folding_on_const_path.cpp
inference-engine/src/transformations/src/transformations/rt_info/disable_constant_folding.cpp
inference-engine/tests/functional/inference_engine/transformations/disable_shapeof_constant_folding_tests.cpp
ngraph/core/include/ngraph/validation_util.hpp
ngraph/core/include/ngraph/variant.hpp
ngraph/core/src/pass/constant_folding.cpp
ngraph/core/src/rt_info.cpp
ngraph/core/src/validation_util.cpp
ngraph/core/src/variant.cpp

Enable ConstantFolding transformation as a part of MOC Transformation pipeline. 
Validation on DL Benchmark model scope shows positive changes in IR. A lot of rank-like shapeof sub-graph were folded (this is doesn't affect models reshapability).
<details>
<summary>Click to expand!</summary>
|Final MOC Pipeline|Enabled|
|---|:---:|
|InitNodeInfo|:white_check_mark:|
|**ConstantFolding**|:tada: |
|SimplifyShapeOfSubGraph|:white_check_mark:|
|RemoveFilteringBoxesBySize|:white_check_mark:|
|ConvertQuantizeDequantize|:white_check_mark:|
| | |
|TransposeFQReduction|:white_check_mark:|
|TransposeReduction|:white_check_mark:|
|TransposeFuse|:white_check_mark:|
|SplitSqueezeConcatFusion|:white_check_mark:|
| | |
|EliminateUnsqueezeGather|:white_check_mark:|
|NopElimination|:white_check_mark: |
| | …

Enable ConstantFolding inside MO Backend

---

inference-engine/src/mkldnn_plugin/mkldnn_edge.cpp
inference-engine/src/mkldnn_plugin/mkldnn_memory.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reorder_node.cpp

In the most part of the legacy SSE, operations memory operands (m128) must be aligned on a 16-byte boundary, therefore we have to ensure that all memory pointers passed to the sse primitives are properly aligned. Since some constants are used directly from ngraph allocated memory, we cannot guarantee that all the pointers are properly aligned, so the `needReorder()` has been updated to handle such cases. If the constant address is not aligned, a reorder is inserted to copy the data to the properly aligned region. 
- 60959

[CPU] Add reorder if the constant memory is not aligned, and isa is SSE

---

inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp

- InsertIdentityToLSTMCellPass is highly likely a workaround for the problem 34350. The problem is actually in InsertIdentity transformation
- check is node final non-functional for grouping
- remove InsertIdentityToLSTMCellPass
- 52095
- 34350

remove InsertIdentityToLSTMCellPass and fix InsertIdentity 

---

ngraph/core/reference/include/ngraph/runtime/reference/fake_quantize.hpp
ngraph/test/runtime/interpreter/evaluates_map.cpp

- *Remove `v0` namespace in reference implementation (introduce temporary)*
- *60667*

remove `v0` namespace from reference implementation of fake quantize.

---

inference-engine/src/gna_plugin/transformations/convert_matmul_to_pointwise_convolution.cpp
inference-engine/tests/unit/gna/CMakeLists.txt
inference-engine/tests/unit/gna/ngraph/transformations/gna_convert_matmul_to_pointwise_convolution.cpp

**Details:**
During the transformation, the input data is transposed to NCHW before Convolution, and the bias data is not. This leads to an error when adding data from the Convolution layer and the bias.
**Ticket**
CVS-60486

[GNA] Transpose bias

---

inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/transpose_conv_transpose_squeeze.cpp
inference-engine/tests/functional/plugin/shared/include/subgraph_tests/transpose_conv_transpose_squeeze.hpp
inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/transpose_conv_transpose_squeeze.hpp
inference-engine/tests/functional/shared_test_classes/src/subgraph/transpose_conv_transpose_squeeze.cpp

- Fixed case when the model includes convolution layer and transpose layers before and after it. Those transpose layers should not be removed by TransposeReduction
- Added the new tests
- 56722

[GNA] Disabled TransposeReduction  (#7011)

---

inference-engine/src/gna_plugin/backend/gna_limitations.hpp
inference-engine/src/gna_plugin/gna_graph_compiler.cpp
inference-engine/src/gna_plugin/gna_groups.hpp
inference-engine/src/gna_plugin/layers/gna_split_layer.hpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/src/gna_plugin/transformations/split_convolution_with_large_buffer_size.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/eltwise_split_over_channels_pass.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/activation.cpp
inference-engine/tests/unit/gna/gna_get_2d_reshaped_data.cpp
inference-engine/tests/unit/gna/gna_get_aligned_split_sizes.cpp

- if Eltwise layer buffer exceeds limitations it is splited into parts. These parts should be 64-aligned to avoid align filters insertion.
- Some layers which shape isn't sufficient for calculations (SyntheticScaleShift, Copy, Power) are reshaped to have the most optimized batch size and 8-aligned elements size to avoid padding. But in some cases shapes which allow to avoid padding don't allow to fit them into input buffer. Allow to create shapes required padding in the case if they can't be fit into the buffer otherwise.
- Added tests for these changes.
CVS-62284

[GNA] Fixed Eltwise split and batch size selection during 2d reshape

---

model-optimizer/mo/utils/versions_checker.py

fix getting imported module version, for e.g.
old behaviuor was failed with fastjsonschema pkg
**mo log**:
"Detected not satisfied dependencies:
fastjsonschema: not installed, required:  ~= 2.15.1"
**venv**: " Collecting fastjsonschema ~=2.15.1
helper.cmd_exec INFO:   Downloading fastjsonschema-2.15.1-py3-none-any.whl
pip freeze -> fastjsonschema==2.15.1"
**missing __version__ attr:** "dir(sys.modules['fastjsonschema'])
['CodeGeneratorDraft04', 'CodeGeneratorDraft06', 'CodeGeneratorDraft07', 'JsonSchemaDefinitionException', 'JsonSchemaException', 'JsonSchemaValueException', 'RefResolver', 'VERSION', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_factory', '_get_code_generator_class', 'compile', …

fix mo module version check

---

inference-engine/src/gna_plugin/backend/gna_limitations.hpp
inference-engine/src/gna_plugin/gna_graph_compiler.cpp
inference-engine/src/gna_plugin/gna_groups.hpp
inference-engine/src/gna_plugin/layers/gna_split_layer.hpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/src/gna_plugin/transformations/convert_matmul_to_pointwise_convolution.cpp
inference-engine/src/gna_plugin/transformations/split_convolution_with_large_buffer_size.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/eltwise_split_over_channels_pass.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/activation.cpp
inference-engine/tests/unit/gna/CMakeLists.txt
inference-engine/tests/unit/gna/gna_get_2d_reshaped_data.cpp
inference-engine/tests/unit/gna/gna_get_aligned_split_sizes.cpp
inference-engine/tests/unit/gna/ngraph/transformations/gna_convert_matmul_to_pointwise_convolution.cpp

- During the transformation, the input data is transposed to NCHW before Convolution, and the bias data is not. This leads to an error when adding data from the Convolution layer and the bias.
- if Eltwise layer buffer exceeds limitations it is splited into parts. These parts should be 64-aligned to avoid align filters insertion.
- Some layers which shape isn't sufficient for calculations (SyntheticScaleShift, Copy, Power) are reshaped to have the most optimized batch size and 8-aligned elements size to avoid padding. But in some cases shapes which allow to avoid padding don't allow to fit them into input buffer. Allow to create shapes required padding in the case if they can't be fit into the buffer otherwise.
- Added tests for these changes.
62284

Fixed Eltwise split and batch size selection during 2d reshape, transpose bias

---

ngraph/core/include/ngraph/op/max_pool.hpp
ngraph/core/src/op/max_pool.cpp

Adjusting the op to match latest specification changes https://github.com/openvinotoolkit/openvino/pull/5359

MaxPool-8: pads_value attribute removal from the operator definition

---

tests/time_tests/scripts/run_timetest.py
tests/time_tests/test_runner/requirements.txt
tests/time_tests/test_runner/test_timetest.py

* Fixed return in `run_timetest`
* Fixed `parse_stats()` argument type notation
* Pass message from `timetest` exe to test error msg to be uploaded to DB

fixed several issues in time tests

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_strided_slice_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_strided_slice_node.h

- *Moved preparations from execution to network loading*
- *United two execution options into one*
- *56313*

[CPU] Added improvements for StridedSlice

---

inference-engine/src/gna_plugin/gna_plugin.cpp

- Invalid order of SwapMatMulInput  transformations (one with the longest matcher pattern should be the first)

[GNA] Fix order of SwapMatMulInput transformations

---

inference-engine/thirdparty/clDNN/src/include/loop_inst.h

- *Fix Klockwork issues in loop_inst.h*
- *Klockwork issue:* [*Variable 'initial_mem' is assigned to self*](https://klocwork-inn4.devtools.intel.com:8090/review/insight-review.html#issuedetails_goto:offset=0,problemid=48471,project=openvino_develop_windows,searchquery=owner%253A%252B%2522Ahn%252C+Paul+Y%2522+status%253AAnalyze%252C%252BFix+-file%253A%255C_deps%255C%252C%255Cpugixml%255C%252C%255Cgflags%255C%252C%255Cade%255C%252C%255Cfluid%255C%252C%255Cmkl-dnn%255C%252C%255Cprotobuf%255C%252C%255Cstb_lib%255C%252C%255Cie_bridges%255C%252C%255Cgapi_sipp%255C%252C%255Cdldt-tests-closed%255C%252C%255Ctests%255C%252C%255Ctest%255C%252C%255Copencv%255C%252C%255Ctests_deprecated%255C%252C%255Cgtest%255C%252C%255Conednn-plugin%255Cdnnl%255C%252C%255CCMakeFiles%255C%252C%255Cinference_engine%255C …

[GPU] Fix Klockwork issue in loop_inst.h

---

inference-engine/thirdparty/clDNN/api/cldnn/runtime/utils.hpp

- Added missing include for `std::runtime_error`

[GPU] Fix GPU plugin build for gcc 10

---

inference-engine/samples/speech_sample/main.cpp
inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/gna_plugin_config.cpp
inference-engine/src/gna_plugin/gna_plugin_config.hpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/import_export_tests/import_reshape_permute_conv.cpp
inference-engine/tests/functional/plugin/shared/include/base/import_export_base/import_export_base.hpp
inference-engine/tests/functional/plugin/shared/src/base/import_export_base/import_export_base.cpp
inference-engine/tests/functional/shared_test_classes/src/base/layer_test_utils.cpp

Merge #7139
- Those changes allow GNA customers to correct the input scale factor for the old models (previously exported) using speech sample, because they don't have the latest version IR.
- If scale factors for inputs were defined in the plugin configuration we should change them for the imported model
- Ignoring default scale factors (1.0f), they should be replaced my imported values
- Modified tests to cover all cases.

[GNA] Set input scale factors for imported model (#7139)

---

inference-engine/src/mkldnn_plugin/mkldnn_plugin.cpp
inference-engine/src/offline_transformations/src/moc_transformations.cpp
inference-engine/src/transformations/include/transformations/op_conversions/normalize_l2_decomposition.hpp
inference-engine/src/transformations/src/transformations/common_optimizations/common_optimizations.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/leaky_relu_fusion.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/normalize_l2_fusion.cpp
inference-engine/src/transformations/src/transformations/op_conversions/normalize_l2_decomposition.cpp
inference-engine/tests/functional/inference_engine/transformations/normalize_l2_decomposition_test.cpp
inference-engine/tests/functional/inference_engine/transformations/normalize_l2_fusion_test.cpp

* Refactored NormlaizeL2 fusions to use single pattern
* Enabled NormalizeL2Fusion and LeakyReluFusion inside MO transformation pipeline
Ticket: XXX-62414
* Functional validation shows no regressions
* IR comparison validation shows no difference in IRs which is expected
<details>
<summary>Click to expand!</summary>
|Final MOC Pipeline|Enabled|
|---|:---:|
|InitNodeInfo|:white_check_mark:|
|ConstantFolding|:white_check_mark: |
|SimplifyShapeOfSubGraph|:white_check_mark:|
|RemoveFilteringBoxesBySize|:white_check_mark:|
|ConvertQuantizeDequantize|:white_check_mark:|
| | |
|TransposeFQReduction|:white_check_mark:|
|TransposeReduction|:white_check_mark:|
|TransposeFuse|:white_check_mark:|
|SplitSqueezeConcatFusion|:white_check_mark:|
| | |
|EliminateUnsqueezeGather|:white_check_mark:| …

Enable NormalizeL2Fusion and LeakyReluFusion inside MOC

---

inference-engine/src/low_precision_transformations/include/low_precision/concat.hpp
inference-engine/src/low_precision_transformations/src/concat.cpp
inference-engine/src/low_precision_transformations/src/markup_can_be_quantized.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/concat_transformation.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/concat_with_different_precision_on_children.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/concat_with_unsupported_axis_transformation.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/low_precision_transformations/concat_with_different_precision_on_children.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/low_precision_transformations/concat_with_different_precision_on_children.cpp
inference-engine/tests/functional/plugin/shared/include/low_precision_transformations/concat_with_different_precision_on_children.hpp
inference-engine/tests/functional/plugin/shared/src/low_precision_transformations/concat_with_different_precision_on_children.cpp
inference-engine/tests/ngraph_helpers/lpt_ngraph_functions/include/lpt_ngraph_functions/concat_function.hpp
inference-engine/tests/ngraph_helpers/lpt_ngraph_functions/src/concat_function.cpp

Added check on unsupported concat (axis != 1) to the MarkupCanBeQuantized pass.
- 61691
- accuracy: developer-services/job/accuracy/2604/ (reference: developer-services/job/accuracy/2605/)
- performance: developer-services/job/performance/953/ (reference: developer-services/job/performance/954/)

[LPT] MarkupCanBeQuantized: handled unsupported concat

---

inference-engine/tests/functional/plugin/conformance/test_runner/skip_configs/skip_config_cpu.lst

- remove from skip_config_cpu.lst disabled OMZ tests
- CVS-56144

CVS-56144 Enable all OMZ scope

---

docs/ops/movement/ReverseSequence_1.md

ReverseSequence specification refactored

---

model-optimizer/extensions/middle/MarkSubgraphsWithCorrectLayout.py
model-optimizer/mo/ops/convolution.py
model-optimizer/mo/ops/deconvolution.py

TF model StyleGAN2 was not converted because of wrong layout permutation. Additional changes were done around Reshape node because Convolution infer function manually inserts `'layout'` attribute to weights data node.
Convolution data input is already in NCHW layout and in the whole graph it's needed only to transpose Convolution weights from to `[C_OUT, C_IN, H, W]` from original TF `[H, W, C_IN, C_OUT]`  leaving other parts of the graph unchanged.
If TF model in NCHW contains Deconvolution nodes need to transpose weights from `[H, W, C_OUT, C_IN]`) into `[C_IN, C_OUT, H, W]` without any other changes for layout permutation.
There is already a transformation which marks nodes that are not needed to permute.
- [extensions/middle/MarkSubgraphsWithCorrectLayout.py#L25](https://github.com/ope …

[MO] turn on MarkSubGraphsWithCorrectLayout for TF NCHW

---

inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp

Some MatMulTransformation tests was disabled in the cpuFunctionalTests.
Root cause was fixed in #5226, but tests is still skipped.
This PR removes these tests from the skip config.
- 63019

[CPU][TESTS][LPT] MatMulTransformations test-cases removed from skip config

---

cmake/templates/ngraphConfig.cmake.in

for cmake < 3.11 (e.g. 3.10 in Ubuntu 18)
related PR #6825
- adds ngraph_onnx_importer target using CMake's `INTERFACE IMPORTED` target instead of `ALIAS`
- 62740
**cc** @ilyachur @mateusztabaka @mbencer @generalova-kate

Fixed ngraph_onnx_importer compatibility target creation for older cmake

---

inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/detection_output/detection_output_kernel_ref.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/detection_output_gpu_ref.cl

- Update LWS for detection_output_stage_final_caffe kernel and remove barrier for global memory
- Update local memory usage from each work group to fix exceeding the maximum local memory 
- *ticket-id*

[GPU] Fix clBuildProgram failure with ssd_mobilnet_v1_coco and batch=256

---

ngraph/core/include/ngraph/op/mvn.hpp
ngraph/core/src/op/mvn.cpp

- Fix v0::MVN default constructor 
(Issue: 'this->m_eps' is not initialized in this constructor.)
- N/A

Fix v0::MVN default constructor

---

inference-engine/src/cldnn_engine/cldnn_remote_context.cpp
inference-engine/thirdparty/clDNN/src/network.cpp

- *fixes device name for remote blobs - necessary for correct MULTI scenarios on ATS*
- *re-assign clDNN primitive arguments if needed*

[GPU] Fixes for correct MultiDevice plugin and inference request behavior

---

inference-engine/src/vpu/graph_transformer/src/frontend/frontend.cpp

- This pr adds `ConvertGather7ToGather1` pass to frontend before `MergeGatherGatherElements` pass, to make it so that when `MergeGatherGatherElements` is ran, any `v7::Gather` will be replaced with `v1::Gather`
- CVS-58466

[VPU] Added ConvertGather7ToGather1 pass to frontend

---

inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.cpp
inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.h
inference-engine/src/mkldnn_plugin/ngraph_transformations/rnn_sequences_optimization.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reshape_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reshape_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_rnn.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_rnn.h
inference-engine/tests/functional/plugin/cpu/single_layer_tests/gru_sequence.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/lstm_sequence.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/rnn_sequence.cpp
inference-engine/tests/functional/plugin/cpu/test_utils/cpu_test_utils.cpp

- *Reorders before and after RNN Sequences were removed for case batch == 1*
- *nGraph transformation reshape-transpose-reshape after RNN Sequences was replaced by plugin's optimization*
- *55822*

[CPU] Avoid inserting additional transpose + reorder after RNN node.

---

model-optimizer/extensions/front/tf/reduce_ext.py
tests/layer_tests/tensorflow_tests/test_tf_Reduce.py

Root cause analysis: There was no extractor for the TF Min operation
Solution: Add extractor for the operation.
Ticket: 62307
Code:
Validation:
Documentation:

Enable TensorFlow Min operation

---

inference-engine/samples/speech_sample/main.cpp

Merge #7227 
- Speech sample crashes if oname option is used with an imported network. This option can be used to get the results from specific output ports.
- 63230

[Samples] Enabled oname for imported models (#7227)

---

inference-engine/samples/speech_sample/main.cpp

- Speech sample crashes if oname option is used with an imported network. This option can be used to get the results from specific output ports.
- 63230

[Samples] Enabled oname for imported models

---

inference-engine/src/inference_engine/src/ie_network_reader.cpp
ngraph/frontend/frontend_manager/include/frontend_manager/frontend_manager.hpp
ngraph/frontend/frontend_manager/src/frontend_manager.cpp
ngraph/frontend/onnx/frontend/src/frontend.cpp

Tikcet: N/A
Leftovers after https://github.com/openvinotoolkit/openvino/pull/7031 merge

Use ONNX FE instead of ONNX Reader leftovers

---

inference-engine/src/inference_engine/src/compilation_context.cpp

`Win32` may be undefined when MSVC is used, see:
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?redirectedfrom=MSDN&view=msvc-160
Signed-off-by: Karol Trzcinski <karolx.trzcinski@intel.com>

IE: Fix Windows compilation on MSVC

---

inference-engine/src/cldnn_engine/cldnn_config.h
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/config.hpp

- Changed default value for DEVICE_ID key from "" to "0" to allow passing default value back to plugin in `SetConfig` call
- *62004*

[GPU] Fixed default device id

---

inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/import_export_tests/import_export_multi_inputs.cpp

- Merge #7277 
- Corrected exception condition to support configurations with fewer inputs than the network has.
- Added tests
- 63426

[GNA] Fixed import of model with several inputs (#7277)

---

model-optimizer/mo/utils/cli_parser.py

**Root cause analysis:** We keep obsolete MO parameter (for generation of IRv7) for several releases that can confuse customers.
**Solution:** Use argparse.SUPPRESS for obsolete MO params help
**Ticket:** 61180
Code:
Validation:
Documentation:

Suppress obsolete MO parameters in help

---

inference-engine/src/cldnn_engine/cldnn_config.h
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/config.hpp

- This reverts commit b235f5e4523496400c777d165a99eb3d495c5a06 as multi plugin works incorrectly with "GPU.0" device id

[GPU] Revert #7155

---

inference-engine/src/gna_plugin/frontend/scale_factor_calc.hpp
inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/fq_maxpool_reordering.cpp

- Accuracy degradation is caused by using max_uint16 value instead of max_uint16 + 1 as maximum levels for int16 quantization
63423

[GNA] Fixed accuracy degradation caused by the input quantization restriction

---

inference-engine/tests/unit/gna/ngraph/transformations/gna_split_convolution_with_large_buffer_size.cpp

- [GNA] Fixes for GNA 3.0 library causes to work in split_convolution_with_large_buffer_size transformation only with 1D convolution
- 63541

use 1D convolution in split_convolution_with_large_buffer_size unit test

---

docs/IE_DG/Integrate_with_customer_application_new_API.md
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx
inference-engine/samples/benchmark_app/benchmark_app.hpp
inference-engine/src/inference_engine/include/ie/ie_core.hpp
inference-engine/src/inference_engine/include/openvino/runtime/core.hpp
tests/time_tests/scripts/run_timetest.py
tests/time_tests/src/timetests_helper/cli.h
tools/benchmark_tool/openvino/tools/benchmark/parameters.py

- since we switched to using Protobuf Lite by default in the ONNX importer, we will no longer have support for reading `*.prototxt` files for ONNX models.
- This PR aims to remove references to reading ONNX `*.prototxt` models from documentation strings.
- *63216*

Remove references to prototxt from documentation and docstrings

---

ngraph/test/frontend/paddlepaddle/CMakeLists.txt
ngraph/test/frontend/paddlepaddle/test_models/gen_wrapper.py

Currently ~50 separate commands are executed to generate PDPD test models. It can have some negative impact on machines where expensive python environment created for each python command. E.g. 'python' require 1GB of memory, and on 32 cores it can execute 32 python scripts in parallel allocating 32GB of memory. This significantly impacts memory usage and can fail
Solution: create only one Python command which will execute all scripts. In this case 'cmake' will execute only 1 command allocating 1 core.
Cons:
- Total time of generation existing 150 models is increased on my machine from ~6 seconds to ~35 seconds
- If only one sub-script is changed, 'paddlepaddle_test_models' target will execute re-generation of all models
- N/A

[Paddle] Combine all PDPD test models generation scripts into one cmake command

---

.ci/azure/windows.yml

Issue with VMem overflow due to PDPD tests has been fixed in master, restoring IncrediBuild
This reverts commit 1aca3019eca6fa27f94a366a6265220711e2c2e7.

Revert "Azure CI: Remove IncrediBuild on Windows (#7085)"

---

inference-engine/ie_bridges/python/sample/speech_sample/speech_sample.py

- *The python version of this sample doesn't crash but it ignored `-oname` when a model was imported*
- *63230*

[IE Python Speech Sample] Enable `-oname` for a imported model (`-rg` option)

---

inference-engine/ie_bridges/python/sample/speech_sample/README.md
inference-engine/ie_bridges/python/sample/speech_sample/arg_parser.py
inference-engine/ie_bridges/python/sample/speech_sample/speech_sample.py

- *There is the similar PR (#6650) that was opened earlier than mine, but it has some issues*
- *59516 (partly)*

[IE Python Speech Sample] Add `--scale_factor` and `--performance_counter` options

---

inference-engine/tests/functional/plugin/shared/include/single_layer_tests/mvn.hpp
inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/single_layer/mvn.hpp
inference-engine/tests/functional/shared_test_classes/src/single_layer/mvn.cpp

- *Deprecated MVNLayerTest class, removed from code base*
- *60420*

Remove deprecated MVNLayerTest class for SLTs

---

ngraph/python/src/ngraph/utils/node_factory.py

- *Added a warning message*
- *57525*

Deprecate passing nodes to op constructor

---

inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/transformations/remove_single_input_concat.cpp
inference-engine/src/gna_plugin/transformations/remove_single_input_concat.hpp
inference-engine/tests/unit/gna/ngraph/transformations/gna_remove_single_input_concat.cpp

- Rewrite RemoveSingleInputConcatPass using ngraph
- write unit tests
- 56249

[GNA] Rewrite RemoveSingleInputConcatPass using ngraph

---

model-optimizer/requirements_dev.txt

**Root cause analysis:** CI fails during installation of modules from `requirements_dev.txt` on Ubuntu 20 with python 3.8.
**Solution:** Extend coverage versions in `requirements_dev.txt`. Coverage 5.5 is the latest version for which I have successfully tested the MO unit-tests coverage.
Code:
Validation:
Documentation:

Extend coverage versions in requirements_dev.txt

---

inference-engine/src/gna_plugin/frontend/layer_quantizer.hpp
inference-engine/src/gna_plugin/frontend/scale_factor_calc.hpp
inference-engine/src/gna_plugin/gna_graph_compiler.cpp
inference-engine/tests/functional/plugin/gna/scale_factors_tests/const_input_add.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/behavior/caching/caching_tests.cpp
inference-engine/tests/unit/gna/gna_get_scale_factor.cpp

- Fixed scale factors propagation for Eltwise with very different inputs ranges
- Exception is thrown in the case of not positive scale factor
- Tests are added
63395

[GNA] Fixed scale factors propagation for Eltwise with very different inputs ranges

---

thirdparty/cnpy/README.md

- Readme contained incorrect link to example1.cpp

Removed incorrect link from cnpy readme

---

ngraph/core/src/preprocess/pre_post_process.cpp

- *item1*
- *...*
- *ticket-id*

Hot fix: rename OV_CHECK to OPENVINO_ASSERT

---

inference-engine/ie_bridges/python/src/openvino/__init__.py

- *According to packaging [guides](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages) every distribution that uses the namespace package must include an identical __init__.py:*
`__path__ = __import__('pkgutil').extend_path(__path__, __name__)`
- *60366*

Add support of pkgutil-style namespace packages

---

inference-engine/src/inference_engine/src/cpp_interfaces/interface/ie_iexecutable_network_internal.cpp
inference-engine/src/inference_engine/src/cpp_interfaces/interface/ie_iplugin_internal.cpp
inference-engine/src/multi_device/multi_device_plugin.cpp
inference-engine/src/plugin_api/cpp_interfaces/interface/ie_iexecutable_network_internal.hpp
inference-engine/src/plugin_api/cpp_interfaces/interface/ie_iplugin_internal.hpp
inference-engine/tests/functional/inference_engine/caching_test.cpp
inference-engine/tests/functional/plugin/myriad/shared_tests_instances/skip_tests_config.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/core_integration.hpp
inference-engine/tests/functional/plugin/shared/include/behavior/exec_graph_info.hpp
inference-engine/tests/ie_test_utils/unit_test_utils/mock.cpp
inference-engine/tests/ie_test_utils/unit_test_utils/mocks/mock_not_empty_icnn_network.hpp

- By default `GetExecGraphInfo` implementation returns parameters->Node()->results graph.
- New `IExecutableNetworkInternal::_function` member can be used to store exec graph to eliminate graph construction on each call of `GetExecGraphInfo`

Added default executable graph result

---

inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp

if port > port_num, the behavior of res[port] is undefined.
Signed-off-by: fengyi.sun <fengyi.sun@intel.com>
Reviewed-by: Wu, Jiangming <jiangming.wu@intel.com>

Fixed sort port bug in SortTopologically

---

model-optimizer/mo/middle/passes/convert_data_type.py

**Root cause analysis:** during quantization MO was failing with the error `mo.utils.error.Error: Destination type "u32" is not supported`. This was happening because of the introduced transformation which marks gather-NMS path to be unsigned (#6474) while uint32 was not mentioned in `SUPPORTED_DATA_TYPES` of MO
**Solution**: Add  uint32 into `SUPPORTED_DATA_TYPES`
- xxx-63537

[MO] add uint32/uint8 into list of supported data types

---

inference-engine/src/inference_engine/include/openvino/runtime/common.hpp
inference-engine/src/inference_engine/include/openvino/runtime/executable_network.hpp
inference-engine/src/inference_engine/include/openvino/runtime/infer_request.hpp
inference-engine/src/inference_engine/src/cpp/ie_executable_network.cpp
inference-engine/tests/functional/inference_engine/ov_executable_network_test.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/ov_core_integration.hpp

based on https://github.com/openvinotoolkit/openvino/pull/7189/files

Moved executable network into ov::runtime namespace

---

inference-engine/src/vpu/graph_transformer/src/utils/runtime_graph.cpp

- When serializing execGraph, milliseconds were actually written to the execTimeMcs field
- 63275

[IE][VPU] Fix execTimeMcs for VPU

---

inference-engine/tests/functional/shared_test_classes/src/subgraph/softsign.cpp

- PowerIE has considered as legacy op type, it was changed to ops from pset6
- change legacy types of ops
- XXX-55373

Change PowerIE to ops chain

---

inference-engine/src/mkldnn_plugin/mkldnn_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_generic_node.cpp
inference-engine/src/mkldnn_plugin/utils/general_utils.h

- *The mechanism of NotImplemented exceptions in MKLDNN NodesFactory is deprecated and should be removed to prevent probable linking issues*
- *61707*

[CPU] Disable NotImpelmented exceptions mechanism for generic node.

---

ngraph/frontend/paddlepaddle/src/op/slice.cpp

- *StridedSlice should set beg/end_mask to {0} instead of {}*. If beg/end_mask={} will generate incorrect IR: \<data begin_mask="" ellipsis_mask="" end_mask="" new_axis_mask="" shrink_axis_mask=""/\>, which cause MO assertion error on the IR.
- *add [review comment](https://github.com/openvinotoolkit/openvino/pull/6636#discussion_r681797059) to the slice source code*
- *62791*

Paddle 'slice' should set correct beg_mask and end_mask paramters

---

inference-engine/tests/functional/inference_engine/CMakeLists.txt
inference-engine/tests/functional/shared_test_classes/CMakeLists.txt

- Removed some ticket number which are already fixed

Removed some ticket number which are already fixed

---

inference-engine/src/inference_engine/include/ie/ie_api.h
ngraph/core/include/openvino/core/deprecated.hpp

Double parentheses break some other compilers which pretend to be gcc.
Single set doesn't seem to break anything.

Use one set of parentheses around gcc attribute deprecated arg

---

inference-engine/src/inference_engine/include/ie/details/ie_so_loader.h
inference-engine/src/inference_engine/include/openvino/runtime/core.hpp
inference-engine/src/inference_engine/include/openvino/runtime/executable_network.hpp
inference-engine/src/inference_engine/include/openvino/runtime/infer_request.hpp
inference-engine/src/inference_engine/include/openvino/runtime/remote_context.hpp
inference-engine/src/inference_engine/include/openvino/runtime/variable_state.hpp
inference-engine/src/inference_engine/src/cpp/ie_executable_network.cpp
inference-engine/src/inference_engine/src/cpp/ie_infer_request.cpp
inference-engine/src/inference_engine/src/cpp/ie_plugin.hpp
inference-engine/src/inference_engine/src/cpp/ie_variable_state.cpp
inference-engine/src/inference_engine/src/cpp_interfaces/interface/ie_iplugin_internal.cpp
inference-engine/src/inference_engine/src/ie_core.cpp
inference-engine/src/inference_engine/src/os/lin/lin_shared_object_loader.cpp
inference-engine/src/inference_engine/src/os/win/win_shared_object_loader.cpp
inference-engine/src/inference_engine/src/remote_context.cpp
inference-engine/src/multi_device/multi_device_async_infer_request.cpp
inference-engine/src/plugin_api/cpp_interfaces/interface/ie_iplugin_internal.hpp
inference-engine/src/plugin_api/shared_object.hpp
inference-engine/src/plugin_api/so_ptr.hpp
inference-engine/tests/functional/inference_engine/ov_shared_object_test.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/ov_core_integration.hpp

* based on: https://github.com/openvinotoolkit/openvino/pull/7230
* Added `OpenVINO` plugin
* All `OpenVINO` entities are connected to `ov::Core` class

Created openvino plugin c++ wrapper

---

inference-engine/src/gna_plugin/layers/gna_layer_info.hpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/transpose_add.cpp
inference-engine/tests/functional/plugin/shared/include/subgraph_tests/transpose_add.hpp
inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/transpose_add.hpp
inference-engine/tests/functional/shared_test_classes/src/subgraph/transpose_add.cpp

- Permute output precision isn't specified in LayerInfo functions, as a result a diagonal layer isn't inserted between it and Eltwise layer.
- Permute output precision should be marked as int16.
- Functional test is added.
65238

[GNA] Fix permute precision handling

---

tests/lsan/suppressions.txt

When executed with PYTHONMALLOC=malloc lot of leaks
reported on the 3rd parties of the python tests.
Muting those leaks.

Exclude 3rd  party python packages  from lsan

---

ngraph/core/reference/include/ngraph/runtime/reference/random_uniform.hpp
ngraph/core/reference/src/runtime/reference/random_uniform.cpp

**Root cause analysis:** 
Using memcpy() for coping bf16 type is unsafe.
**Solution:** 
Use helper struct with union type for conversion of values between types instead of memcpy(). 
- 65098

Fixed issue with memcpy().

---

inference-engine/src/gna_plugin/backend/am_intel_dnn.cpp
inference-engine/src/gna_plugin/backend/dnn_types.h
inference-engine/src/gna_plugin/backend/gna_limitations.cpp
inference-engine/src/gna_plugin/backend/gna_limitations.hpp
inference-engine/src/gna_plugin/gna_graph_compiler.cpp
inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/gna_plugin_config.cpp
inference-engine/src/gna_plugin/transformations/convert_padded_to_valid_convolution.cpp
inference-engine/src/gna_plugin/transformations/convert_padded_to_valid_convolution.hpp
inference-engine/src/gna_plugin/transformations/decompose_2d_convolution.cpp
inference-engine/src/gna_plugin/transformations/decompose_2d_convolution.hpp
inference-engine/src/gna_plugin/transformations/utils/transformation_helper.cpp
inference-engine/src/gna_plugin/transformations/utils/transformation_helper.hpp
inference-engine/tests/functional/plugin/gna/pass_tests/convert_padded_to_valid_conv.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/decompose_2d_conv.cpp
inference-engine/tests/unit/gna/ngraph/transformations/gna_convert_padded_to_valid_convolution.cpp
inference-engine/tests/unit/gna/ngraph/transformations/gna_decompose_2d_convolution.cpp

- port padding and 2d convolution support from master branch
- skip decomposition of convolutions supported on GNA 3.0
- add some required fixes when backporting from master to releases/2021.4
- 63938

Gna 2dconv30 releases

---

inference-engine/src/multi_device/multi_device_exec_network.cpp
inference-engine/src/multi_device/multi_device_exec_network.hpp
inference-engine/src/multi_device/multi_device_plugin.cpp
inference-engine/src/multi_device/multi_device_plugin.hpp
inference-engine/tests/functional/plugin/conformance/test_runner/src/behavior/infer_request/perf_counters.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/infer_request/config.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/infer_request/perf_counters.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/test_plugin.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/infer_request/callback.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/infer_request/perf_counters.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/infer_request/wait.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/preprocessing/set_preprocess.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/test_plugin.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/version.cpp

- *Enable CPU accelerate FIL in MULTI*
- *PR [7076](https://github.com/openvinotoolkit/openvino/pull/7076) can't trigger jenkins ci，create  this new  PR*
- *62140*

Enable CPU accelerate FIL in MULTI

---

inference-engine/thirdparty/clDNN/kernel_selector/core/auto_tuner.cpp

- Add mutex lock for thread safety during loading offline kernel
- 59937

[GPU] Fix RapidJSON assertion failure during loading offline kernel

---

inference-engine/src/low_precision_transformations/src/fake_quantize_dequantization.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/get_dequantization_transformation.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/multiply_to_group_convolution_transformation.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/reshape_transformation.cpp

- *NetworkHelper::getDequantization: added precision limitation for mul/sub constants to avoid LPT running on the i32 subgraphs*
- *63658*
- *64992*
- *63344*
- *Validation: 65812*

[LPT] getDequantization: added precision limitation for mul/sub constants

---

.ci/openvino-onnx/watchdog/src/watchdog.py
model-optimizer/extensions/front/tf/non_max_suppression_ext.py
model-optimizer/extensions/load/tf/loader.py
model-optimizer/extensions/middle/StridedSliceNormalizer.py
model-optimizer/extensions/middle/TensorIteratorInput.py
model-optimizer/extensions/ops/If.py
model-optimizer/mo/front/caffe/extractor.py
model-optimizer/mo/front/caffe/loader.py
model-optimizer/mo/utils/cli_parser.py
model-optimizer/unit_tests/mo/front/caffe/loader_test.py
model-optimizer/unit_tests/mo/frontend_ngraph_test_actual.py
model-optimizer/unit_tests/mo/moc_frontend/moc_extractor_test_actual.py
runtime/bindings/python/tests/__init__.py
tests/stress_tests/scripts/run_memcheck.py
tools/benchmark_tool/openvino/tools/benchmark/main.py
tools/benchmark_tool/openvino/tools/benchmark/parameters.py
tools/deployment_manager/deployman/main.py

When breaking up long sentences into multiple consecutive string literals, it's easy to forget to add a space at the end of the first literal (or at the beginning of the second literal), which results in words being jammed together in the final sentence. This fixes a bunch of such errors.
I found these by using the following script:
```python
#!/usr/bin/env python3
import ast
import token
import tokenize
import sys
def main():
for path in sys.argv[1:]:
with open(path, 'rb') as f:
previous_had_no_space = False
for t in tokenize.tokenize(f.readline):
if t.type == tokenize.NL: continue
current_has_no_space = False
if t.type == token.STRING:
try:
string_value = ast.literal_eval(t.string)
except ValueError:
pass
else:
if isinstance(string_value, str) and string_value:
if previous_had_no_space …
```

Add missing spaces between words in string literals

---

inference-engine/src/low_precision_transformations/include/low_precision/layer_transformation.hpp
inference-engine/src/low_precision_transformations/include/low_precision/low_precision.hpp
inference-engine/src/low_precision_transformations/include/low_precision/rt_info/precisions_attribute.hpp
inference-engine/src/low_precision_transformations/src/fake_quantize_decomposition.cpp
inference-engine/src/low_precision_transformations/src/fake_quantize_dequantization.cpp
inference-engine/src/low_precision_transformations/src/layer_transformation.cpp
inference-engine/src/low_precision_transformations/src/low_precision.cpp
inference-engine/src/low_precision_transformations/src/network_helper.cpp
inference-engine/src/low_precision_transformations/src/quantization_details.cpp
inference-engine/src/low_precision_transformations/src/rt_info/precisions_attribute.cpp
inference-engine/src/mkldnn_plugin/mkldnn_plugin.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_fake_quantize_node.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/fake_quantize_transformation.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/low_precision_transformations/fake_quantize_transformation.cpp

- *Support INT16, INT32 quantization pipeline through Low Precision Transformations*
- *Computing Quantization/Dequantization scales and shifts in double precision under macros `FQ_DOUBLE_PRECISION`*
- 40265

[LPT] INT16, INT32 Quantization support

---

inference-engine/src/mkldnn_plugin/emitters/jit_eltwise_emitters.cpp
inference-engine/src/mkldnn_plugin/emitters/jit_load_store_emitters.cpp
inference-engine/src/mkldnn_plugin/nodes/common/permute_kernel.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_bin_conv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_eltwise_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_fake_quantize_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_input_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_interpolate_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_mvn_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_normalize_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reduce_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_region_yolo_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_roi_pooling_node.cpp

-  Quote:
The Skylake microarchitecture implements a different state
machine than prior generations to manage the YMM state transition
associated with mixing SSE and AVX instructions.
It no longer saves the entire upper YMM state when executing
an SSE instruction when in “Modified and Unsaved” state,
but saves the upper bits of individual register.
As a result, mixing SSE and AVX instructions will experience
a penalty associated with partial register dependency of
the destination registers being used and additional blend
operation on the upper bits of the destination registers.
Such type of penalties have a huge impact on openvino's and oneDNN's kernels.
Basically the mixing of VEX and non-VEX instructions should be avoided.
- openvino oneDNN PR: …

[CPU] Fix mixing VEX and non-VEX instructions

---

inference-engine/ie_bridges/python/tests/conftest.py
inference-engine/ie_bridges/python/tests/test_Blob.py
inference-engine/ie_bridges/python/tests/test_CDataPtr.py
inference-engine/ie_bridges/python/tests/test_DataPtr.py
inference-engine/ie_bridges/python/tests/test_IENetwork.py
inference-engine/ie_bridges/python/tests/test_InferRequest.py
inference-engine/ie_bridges/python/tests/test_NGraph.py

- *[test_blob_set_shape_after_async_infer](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/python/tests/test_Blob.py#L142) and [test_set_blob_after_async_infer](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/ie_bridges/python/tests/test_InferRequest.py#L786) fail sporadic due to very simple model for inference, because inference finish too fast and exception don't throw*
- *Adding a more complex ngraph function for these tests can solve it*
- *65553*

[IE PYTHON] add new ngraph function for dynamic shape tests

---

docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md

- *conversion script for RNNT does not contain names for output nodes, which leads to producing different nresult from run to run. It can confuse users, which does not expect changes, for avoiding confusion, I added names for outputs in exporting function*
- *Besides that give more descriptive names for inputs*
- *65737*

Update rnnt conversion instruction with named outputs

---

inference-engine/src/inference_engine/include/ie/ie_common.h

- *typo in NC Layout description*
`NC` layout described as `HC`

fix typo in `NC` layout description

---

inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp
inference-engine/src/mkldnn_plugin/mkldnn_graph.h
inference-engine/src/mkldnn_plugin/mkldnn_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_concat_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_input_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_memory_node.hpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reorder_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reshape_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_split_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_split_node.h

- *Added method `isExecutable()` to remove non-executable (optimized out) nodes from infer stage*
- *65291*

[CPU] Removed optimized out nodes from infer stage

---

inference-engine/src/cldnn_engine/cldnn_config.cpp
inference-engine/src/cldnn_engine/cldnn_engine.cpp
inference-engine/src/cldnn_engine/cldnn_engine.h
inference-engine/src/mkldnn_plugin/mkldnn_plugin.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/config.hpp

Surprisingly we had never test for that, so e.g. Hints may override the customer settings

Tests that config set via ie.SetConfig or LoadNetwork return via exe_net.GetConfig + align plugin impl to that

---

inference-engine/samples/benchmark_app/main.cpp

- benchmark_app incorrectly fills in the inputs for cached models
- CVS-65635

benchmark_app incorrectly fills in the inputs for cached models

---

inference-engine/src/cldnn_engine/cldnn_config.h
inference-engine/src/inference_engine/src/ie_core.cpp
inference-engine/src/multi_device/multi_device_async_infer_request.cpp
inference-engine/src/multi_device/multi_device_exec_network.cpp
inference-engine/src/multi_device/multi_device_exec_network.hpp
inference-engine/src/multi_device/multi_device_plugin.cpp
inference-engine/src/plugin_api/ie_icore.hpp
inference-engine/src/plugin_api/ie_performance_hints.hpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/behavior/config.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/multi/gpu_remote_blob_tests.cpp
inference-engine/tests/functional/plugin/shared/include/behavior/config.hpp
inference-engine/tests/ie_test_utils/unit_test_utils/mocks/cpp_interfaces/interface/mock_icore.hpp

- [GPU] Changed default value for DEVICE_ID key from "" to "0" to allow passing default value back to plugin in SetConfig call
- [MULTI] Fixed device name comparison logic in multi plugin to process device ID correctly.
- *62004*

[MULTI] Fixed devices comparison to respect default device id

---

docs/doxygen/ie_docs.xml
docs/ops/image/NV12toBGR_8.md
docs/ops/image/NV12toRGB_8.md
docs/ops/opset8.md

- NV12toRGB and NV12toBGR operations specification
- It was decided to split this into 2 separate operations to be able to maintain their behavior separately. Also in futurethere may be needed to perform conversion from NV21, and this extension shall not affect users which use old operations (e.g. NV12toRGB-8 will be the same even if there is new NV21toRGB operation is introduced)
- 62174

[OV20] NV12toRGB and NV12toBGR operations specification

---

docs/MO_DG/prepare_model/convert_model/Converting_Model_General.md
model-optimizer/mo/utils/cli_parser.py

Signed-off-by: Andrei Kochin <andrei.kochin@intel.com>
Solution: Replace word 'quantized' with 'compressed' in --data_type help description to avoid confusions.
Code:
Validation:
Documentation:
- None

Replace 'quantized' with 'compressed' in MO help

---

ngraph/core/src/layout.cpp
ngraph/core/src/op/util/logical_reduction.cpp
ngraph/core/src/preprocess/preprocess_steps_impl.cpp

- When ENABLE_FASTER_BUILD is ON, source files are combined to batch for faster compilation. However, when one source file uses "using namespace ngraph", and another has "using namespace ov" - then conflicts may occur depending on how sources were combined
- This fix removes usage of "using namespace ov" from ngraph code to avoid such potential issues. Old code still have "using namespace ngraph"
- Example of failed job due to this: https://github.com/openvinotoolkit/openvino/runs/3684741745
- N/A

Fix potential UNITY build failures (ENABLE_FASTER_BUILD)

---

inference-engine/src/cldnn_engine/cldnn_remote_context.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/concatenation_onednn.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/eltwise_onednn.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/fully_connected_onednn.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/gemm_onednn.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/pooling_onednn.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/register.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/register.hpp
inference-engine/thirdparty/clDNN/src/impls/onednn/reorder_onednn.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/utils.cpp
inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp
inference-engine/thirdparty/clDNN/src/program_dump_graph.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/reorder_gpu_test.cpp

- onednn integration for reorder primitive
- basic unit test for checking integration is implemented
- other onednn primitives are registered with empty list to avoid future conflicts
- Select `queue_type` based on `supports_immad`
- Confirmed that onednn reorder works OK in network execution. (code patch required to use it)
- Added `preferred_impl_type` in dumped graph
- 65752

[GPU] Onednn integration for reorder primitive

---

inference-engine/src/gna_plugin/gna_device.cpp
inference-engine/src/gna_plugin/gna_device.hpp

- When user specifies value for `InferenceEngine::GNAConfigParams::KEY_GNA_EXEC_TARGET` and it's different than the detected GNA device, then use `Gna2DeviceCreateForExport()` to create GNA 'virtual device' compliant with the specified one.
- 66309

[GNA] Fix KEY_EXEC_TARGET

---

inference-engine/ie_bridges/python/tests/test_Blob.py
inference-engine/src/inference_engine/include/ie/ie_blob.h
inference-engine/src/inference_engine/include/ie/ie_layouts.h
inference-engine/src/inference_engine/src/ie_blob_common.cpp
inference-engine/src/inference_engine/src/ie_layouts.cpp
ngraph/core/CMakeLists.txt
ngraph/core/include/openvino/runtime/tensor.hpp
ngraph/core/src/runtime/ov_tensor.cpp
ngraph/test/ov_tensor_test.cpp

- Check that `Tensor` strides are valid
- Fixed behavior for `Blob::setShape` - throw exception in case of ROI blob or external memory
- Removed `size` from ctor with external memory
- CVS-33206
- CVS-66390

Improved ov::Tensor behavior

---

inference-engine/src/gna_plugin/gna_device.cpp
inference-engine/src/gna_plugin/gna_device.hpp

- When user specifies value for `InferenceEngine::GNAConfigParams::KEY_GNA_EXEC_TARGET` and it's different than the detected GNA device, then use `Gna2DeviceCreateForExport()` to create GNA 'virtual device' compliant with the specified one.
- Update detected GNA device version field in GNA Device helper
- Use EXEC instead of COMPILE TARGET condition to append CNN Legacy enforcement (GNA1)
- 66309

[GNA] Fix KEY_EXEC_TARGET (cherry pick #7671)

---

docs/template_plugin/tests/functional/subgraph_reference/preprocess.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/subgraph_tests/preprocess.cpp
inference-engine/tests/functional/shared_test_classes/src/subgraph/preprocess.cpp
inference-engine/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/preprocess/preprocess_builders.hpp

- Use 'u8' element type in tests, as int8 template conversion has issues (to be fixed under separate tickets)
- Use 'float32' output for 'compare with reference' tests to avoid IE undesired conversions of output precisions
- Added GPU preprocessing tests skeleton (+ skip test, issue is raised)
- N/A

[OV20] More preprocessing tests 

---

cmake/toolchains/onecoreuap.toolchain.cmake

See https://cmake.org/pipermail/cmake/2004-May/005136.html
Signed-off-by: Karol Trzcinski <karolx.trzcinski@intel.com>

cmake: OneCoreUap: Use proper dot escape sequence in cmake regex

---

inference-engine/src/vpu/graph_transformer/src/utils/runtime_graph.cpp

- *When serializing execGraph, milliseconds were actually written to the execTimeMcs field. It's just cherry-pick commit from master branch*
- *63275*

[IE][VPU] Fix execTimeMcs for VPU for 2021.4.2

---

inference-engine/src/gna_plugin/transformations/handle_transposes_around_matmul.cpp
inference-engine/tests/unit/gna/ngraph/transformations/handle_transposes_around_matmul.cpp

- Fixed failed to inserting transpose after matmul if output matmul tensor has only one dimension that more than one.
- CVS-66242

[GNA] fixed failed to inserting transpose after matmul

---

inference-engine/thirdparty/clDNN/runtime/debug_configuration.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/reorder_gpu_test.cpp

It receives space-separated parameter. Currently, only first argument is
received in case of string argument.

[GPU] debug_config bug fix of not accepting multiple strings

---

inference-engine/src/plugin_api/cpp_interfaces/impl/ie_infer_async_request_thread_safe_default.hpp
inference-engine/tests/functional/plugin/shared/include/behavior/infer_request/callback.hpp

- If a callback has an internal state it is not copied in the default implementation

Fixed callback copy count

---

inference-engine/src/plugin_api/cpp_interfaces/interface/ie_iplugin_internal.hpp

- On Windows `INFERENCE_PLUGIN_API` macro defined as `extern "C"`, and if use `IE_DEFINE_PLUGIN_CREATE_FUNCTION` macro in a plugin with /EHc compiler key, you will get 'warning C4297: function assumed not to throw an exception but does. The function is extern "C" and /EHc was specified". So we should explicitly specify it as throw function.
https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?redirectedfrom=MSDN&view=msvc-160

Fix for warning C4297 in CPP plugin interface

---

inference-engine/src/mkldnn_plugin/emitters/jit_eltwise_emitters.cpp
inference-engine/src/mkldnn_plugin/emitters/jit_mkldnn_emitters.hpp
inference-engine/src/mkldnn_plugin/mkldnn_node.cpp
inference-engine/src/mkldnn_plugin/mkldnn_node.h
inference-engine/src/mkldnn_plugin/nodes/common/softmax.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_bin_conv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_conv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_conv_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_def_conv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_eltwise_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_eltwise_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_fake_quantize_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_fake_quantize_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_fullyconnected_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_fullyconnected_node.h
inference-engine/src/mkldnn_plugin/nodes/mkldnn_interpolate_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_mvn_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_normalize_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reduce_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_region_yolo_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reorder_node.cpp

What's new:
- binary post
- binary post ops support for gemm convolution and gemm inner product
- plugin fixes
- mkldnn: avx512: fixed prelu post op
Known issues:
- Binary post ops are temporarily disabled for convolution due to performance issues
- Issues with RNN nodes performance
-------
- Old PR https://github.com/openvinotoolkit/openvino/pull/7212
- https://github.com/openvinotoolkit/oneDNN/pull/76
- 66455

[CPU] Migration on oneDNN v2.3.2

---

inference-engine/src/inference_engine/src/compilation_context.cpp
inference-engine/src/mkldnn_plugin/utils/ngraph_utils.hpp
inference-engine/src/transformations/include/transformations/rt_info/attributes.hpp
inference-engine/src/transformations/include/transformations/rt_info/disable_constant_folding.hpp
inference-engine/src/transformations/include/transformations/rt_info/nms_selected_indices.hpp
inference-engine/src/transformations/include/transformations/rt_info/primitives_priority_attribute.hpp
inference-engine/src/transformations/include/transformations/rt_info/strides_property.hpp
inference-engine/src/transformations/src/transformations/rt_info/disable_constant_folding.cpp
inference-engine/src/transformations/src/transformations/rt_info/nms_selected_indices.cpp
inference-engine/src/transformations/src/transformations/rt_info/strides_property.cpp
inference-engine/tests/functional/inference_engine/ir_serialization/rt_info_serialization.cpp
inference-engine/tests/unit/inference_engine/ie_compilation_context_test.cpp
ngraph/core/src/pass/init_node_info.cpp
ngraph/core/src/pass/rt_info/primitives_priority_attribute.cpp

Simplified rt info attribute classes to avoid VariantWrapper usage. This helps to simplify code when creating or accessing attributes and helps to avoid excess classes for simple primitives.

Remove VariantWrapper for simple attr classes

---

model-optimizer/mo/utils/ir_reader/extenders/deconvolution_extender.py

Root cause analysis: IR Reader fails with error if one of `GroupConvolutionBackpropData` attributes (`strides`, `output_padding`, `pads_begin`, `pads_end` or `dilations`) has a scalar value.
Solution: Update `GroupConvolutionBackpropData` extender to read these attributes as `list`
Ticket: 65391
Code:
Validation:
Documentation:

[ MO ][ IR READER ] GroupConvolutionBackpropData extender update

---

docs/template_plugin/tests/functional/op_reference/base_reference_test.cpp
docs/template_plugin/tests/functional/op_reference/base_reference_test.hpp
docs/template_plugin/tests/functional/op_reference/convert_color_nv12.cpp
docs/template_plugin/tests/functional/skip_tests_config.cpp
docs/template_plugin/tests/functional/subgraph_reference/preprocess.cpp
inference-engine/tests/functional/shared_test_classes/include/shared_test_classes/base/layer_test_utils.hpp
inference-engine/tests/functional/shared_test_classes/src/base/layer_test_utils.cpp
inference-engine/tests/functional/shared_test_classes/src/single_layer/convert_color_nv12.cpp
ngraph/core/reference/include/ngraph/runtime/reference/convert_color_nv12.hpp

- Fix 'NV12 batch case' (was sporadic failure)
- Introduced 'absolute threshold' for LayerTests and BaseReferenceTests to consistently catch absolute differences
- Previously, when set 'threshold=1.f' it was treated as 'allowed difference is 100%", so there was no way to allow absolute difference as 1.f
- 62174

Fix reference NV12 batch conversion + Base tests improvements

---

inference-engine/src/cldnn_engine/cldnn_engine.cpp

- Currently the ngraph dump file name is shared within subgraphs. 
- Fix this to be done for each subgraph
-

[GPU] Make ngraph dump to be done for each subnetwork

---

inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api_impl.cpp

- *The problem is python3.9 specific only*
- *Replacing PyUnicode_FromString with PyUnicode_InternFromString fixes memory leak*
- *65443*

[IE PYTHON] Fix memory leak for python3.9

---

inference-engine/src/transformations/include/ngraph_ops/nms_ie_internal.hpp
inference-engine/src/transformations/include/ngraph_ops/type_relaxed.hpp
inference-engine/src/transformations/src/ngraph_ops/nms_ie_internal.cpp
inference-engine/src/transformations/src/transformations/op_conversions/convert_nms_to_nms_ie_internal.cpp
inference-engine/tests/functional/inference_engine/transformations/convert_precision.cpp
inference-engine/tests/functional/inference_engine/transformations/type_relaxed_tests.cpp
ngraph/core/src/pass/convert_precision.cpp

* Fixed ConvertPrecision transformation for NMS5
* Added score_output_type attribute for NMSIE operation to have valid conversion from TypeRelaxed NMS5 to NMSIE
* Fixed an issue with TypeRelax with wrong indexing when setting output type
XXX-62983

Fix ConvertPrecision for NMS5

---

inference-engine/src/mkldnn_plugin/cpu_types.cpp
inference-engine/src/mkldnn_plugin/memory_desc/dnnl_blocked_memory_desc.cpp
inference-engine/src/mkldnn_plugin/memory_desc/dnnl_blocked_memory_desc.h
inference-engine/src/mkldnn_plugin/mkldnn_descriptor.cpp
inference-engine/src/mkldnn_plugin/mkldnn_descriptor.h
inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.cpp
inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.h
inference-engine/src/mkldnn_plugin/mkldnn_plugin.cpp
inference-engine/src/mkldnn_plugin/ngraph_transformations/align_matmul_input_ranks.cpp
inference-engine/src/mkldnn_plugin/ngraph_transformations/align_matmul_input_ranks.hpp
inference-engine/src/mkldnn_plugin/ngraph_transformations/convert_matmul_to_fc.cpp
inference-engine/src/mkldnn_plugin/ngraph_transformations/convert_matmul_to_fc.hpp
inference-engine/src/mkldnn_plugin/ngraph_transformations/convert_to_cpu_specific_opset.hpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_broadcast_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_matmul_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_matmul_node.h
inference-engine/src/mkldnn_plugin/utils/general_utils.h
inference-engine/tests/functional/plugin/cpu/single_layer_tests/mat_mul.cpp
inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/align_mamtul_input_ranks.cpp
ngraph/test/backend/recurrent_cells.in.cpp
ngraph/test/runtime/ie/unit_test.manifest

- SGEMM is replaced with oneDNN MatMul primitive
- AlignMatMulInputRanks transformation is added to support oneDNN 2.3.2 MatMul limitation
- Performance is mostly improved
- Tests are updated with BF16 precision covered
- 48230
oneDNN update:
- https://github.com/openvinotoolkit/oneDNN/pull/62

[CPU] Replace sgemm with MatMul primitive

---

inference-engine/thirdparty/clDNN/api/cldnn/runtime/device_info.hpp
inference-engine/thirdparty/clDNN/runtime/ocl/ocl_device.cpp
inference-engine/thirdparty/clDNN/src/kernel_selector_helper.cpp

- Deleted of duplicated metrics
- Small changes in the device config logic
-

[GPU] Num threads per eu update

---

ngraph/core/include/openvino/op/util/framework_node.hpp
ngraph/test/CMakeLists.txt
ngraph/test/framework_node.cpp

Fix FrameworkNodeAttr Deserialization

---

inference-engine/src/gna_plugin/backend/am_intel_dnn.cpp

- additional `#ifdef`'s to avoid `out_file_name` usage without being declared
- *16638*

[GNA] Adding missed ifdef's

---

inference-engine/src/inference_engine/src/ie_system_conf.cpp
inference-engine/src/plugin_api/ie_system_conf.h
inference-engine/tests/functional/inference_engine/task_executor_tests.cpp

- *Create new API to return the number of logical cores for BIG and All cores*
- *This is needed for gpu plugin's cpu affinity control*
- *63585*

[IE] Add new API to return the number of logical cores

---

runtime/bindings/python/src/openvino/ie_api.py
runtime/bindings/python/src/pyopenvino/core/tensor.cpp
runtime/bindings/python/tests/test_inference_engine/helpers.py
runtime/bindings/python/tests/test_inference_engine/test_infer_request.py
runtime/bindings/python/tests/test_inference_engine/test_tensor.py

- Re-do constructor for Tensor Python API
- Allow user to decide if memory is shared or not between original numpy array. In case memory is not shared, memory copy is performed (with additional step of moving an array's memory layout to C-style row major).
- Add new tests
- *...*

[PYTHON] Fix Tensor creation from numpy arrays

---

inference-engine/src/cldnn_engine/cldnn_async_infer_request.cpp
inference-engine/src/cldnn_engine/cldnn_executable_network.cpp
inference-engine/src/cldnn_engine/cldnn_infer_request.cpp
inference-engine/src/cldnn_engine/cldnn_infer_request.h

- *use configured number of streams in GPU async request waitExecutor instead of one (to prevent wait serialization in case of multiple streams)*
- *68115*

[GPU] Fix some perf drops from breaking GPU pipeline into explicit stages

---

thirdparty/CMakeLists.txt

- make may spawn to many threads and fail with out of memory error. Limit number of threads used for onednn build by cores count to avoid such error.
- 69684

[GPU] Limit number of threads used for onednn build

---

inference-engine/tests/functional/shared_test_classes/src/read_ir/compareResults.cpp

- ASSERT_EQ in case of a fail reports that the test has fail and abort the current function, but does not throw an exception and then the program continues to run and comes to updating the status to PASSED. 
- 68570

[IE TESTS] Fix incorrect result in the Conformance report

---

inference-engine/src/mkldnn_plugin/ngraph_transformations/convert_to_cpu_specific_opset.hpp

*ConvertMatMulToFC transformation is disabled for dynamic cases. This workaround will be removed after dynamic shapes support in FullyConnectedNode*

[CPU][dynamism] MatMulToFullyConnected transformation temporary disabled

---

inference-engine/thirdparty/clDNN/src/primitive_inst.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/fusings_gpu_test.cpp

- in reshape_gpu_f32.shrink_chain_partial test we had usm_device output which could lead to assertion fail in debug or crash in release build

[GPU] Fixed allocation type for optimized out outputs

---

tools/compile_tool/main.cpp

Updated config's parser for compile_tool
The parser can read value containing spaces
- *ticket-id*

[VPUX]Improvement config parser

---

inference-engine/src/mkldnn_plugin/emitters/jit_eltwise_emitters.cpp
inference-engine/src/mkldnn_plugin/emitters/jit_load_store_emitters.cpp
inference-engine/src/mkldnn_plugin/nodes/common/permute_kernel.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_bin_conv_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_eltwise_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_fake_quantize_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_input_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_interpolate_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_mvn_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_normalize_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reduce_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_region_yolo_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_roi_pooling_node.cpp

-------
- Because few issues were detected on AVX (unknown instruction)
and AVX2 (accuracy) platforms. Reverting for now.
- 69567
- 69574

Revert "[CPU] Fix mixing VEX and non-VEX instructions (#7238)"

---

inference-engine/thirdparty/clDNN/src/network.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/fusings_gpu_test.cpp

- This PR prevents usage scale buffer as output buffer for OneDNN primitives

[GPU] Fix incorrect memory reuse for output in case of fused eltwise

---

inference-engine/src/legacy_api/include/legacy/ngraph_ops/pad_ie.hpp
inference-engine/src/legacy_api/src/ngraph_ops/pad_ie.cpp

- *fixed clone_with_new_inputs method which returned nullptr before*

fix in PadIE operation

---

inference-engine/tests/functional/inference_engine/transformations/const_folding_for_if.cpp
inference-engine/tests/functional/inference_engine/transformations/const_folding_prior_box.cpp
inference-engine/tests/functional/inference_engine/transformations/conv_fusion_test.cpp
inference-engine/tests/functional/inference_engine/transformations/convert_convolution_test.cpp
inference-engine/tests/functional/inference_engine/transformations/convert_deconvolution_test.cpp
inference-engine/tests/functional/inference_engine/transformations/convert_ngraph_to_cnn_network_tests.cpp
inference-engine/tests/functional/inference_engine/transformations/convert_reduce_to_pooling_test.cpp
inference-engine/tests/functional/inference_engine/transformations/convert_scatter_elements_to_scatter_test.cpp
inference-engine/tests/functional/inference_engine/transformations/keep_constant_inputs_tests.cpp
inference-engine/tests/functional/inference_engine/transformations/mul_add_conversion_test.cpp
inference-engine/tests/functional/inference_engine/transformations/ngraph_1d_ops_reshape_test.cpp
inference-engine/tests/functional/inference_engine/transformations/nop_elimination.cpp
inference-engine/tests/functional/inference_engine/transformations/type_relaxed_tests.cpp

- updated tests in "inference-engine/tests/functional/inference_engine/transformations/" directory 
- change all run_on_function execution to execution with pass::Manager
- 14/18 test failed in "convert_convolution_test.cpp" probably because validation in pass::Manager 
- 10/16 test failed in "convert_deconvolution_test.cpp" probably because validation in pass::Manager
- 68833

Update existing functional tests to use pass::Manager

---

inference-engine/src/transformations/src/transformations/common_optimizations/pull_transpose_through_fq.cpp
inference-engine/tests/functional/inference_engine/transformations/ngraph_fq_transpose_test.cpp
model-optimizer/extensions/back/MatMulNormalizer.py
model-optimizer/unit_tests/extensions/back/MatMulNormalizer_test.py

Root cause analysis: Using this operation on the activation path can prevent FQ and Conv (for example) fusing using a post op mechanism.
Ticket: 36833
Code:
Validation:
Documentation:

[IE Transformations] Disable pull_transpose_through_fq transformation for activations path

---

ngraph/core/include/openvino/core/partial_shape.hpp
ngraph/test/partial_shape.cpp

Fix PartialShape is_static method caching approach for case when non constant iterators are used.
XXX-62301

Fix PartialShape Iterators to reset cache

---

inference-engine/samples/common/format_reader/opencv_wrapper.cpp

Benchmark_app created mismatching buffer because of transposition of
width/height. Input was not fed into network in case of non-square form.
- The issue was introduced from PR-8093

benchmark_app bugfix for filling input

---

inference-engine/ie_bridges/c/include/c_api/ie_c_api.h
inference-engine/ie_bridges/c/src/ie_c_api.cpp
inference-engine/ie_bridges/c/tests/CMakeLists.txt
inference-engine/ie_bridges/c/tests/ie_c_api_test.cpp
inference-engine/ie_bridges/c/tests/test_model_repo.hpp
inference-engine/tests/functional/plugin/gna/Import_export_tests/import_export_memory_layer.cpp

Merge of #8353
Added Import/Export functions to C API:
Creates an executable network from a network previously exported to file. Users can create as many networks as they
need and use them simultaneously (up to the limitation of the hardware resources). Use the ie_exec_network_free()
method to free
memory.
IEStatusCode ie_core_import_network(ie_core_t *core, const char *file_name, const char *device_name,
const ie_config_t *config, ie_executable_network_t **exe_network)
Creates an executable network from a network previously exported to blob. Users can create as many networks as they
need and use them simultaneously (up to the limitation of the hardware resources). Use the ie_exec_network_free()
method to free
memory.
IEStatusCode ie_core_import_network_from_memory(ie_core_t *core, const …

Added Import/Export functions to C_API #8353

---

inference-engine/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/activation.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/skip_tests_config.cpp
inference-engine/tests/functional/shared_test_classes/src/single_layer/activation.cpp
ngraph/test/runtime/interpreter/evaluates_map.cpp
ngraph/test/runtime/interpreter/opset_int_tbl.hpp

- Enabling **integer precision** tests:
- Threshold for integer networks changed to 1 until the capability of returning actual values in integers
- Separate test suite
- Enabling **floating point** precision tests:
- Returning FP32 and FP16 precisions into the test configuration
- Limiting small input values for `Sign` activation
- Adding `Exp` and `Log` activations in skip list
- *32210*
- *61379*

[GNA] ActivationLayer tests enabled

---

inference-engine/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/eltwise.cpp
inference-engine/tests/functional/shared_test_classes/src/single_layer/eltwise.cpp
inference-engine/tests_deprecated/unit/engines/gna/fp32_non_quantized_tests.cpp

- added GNA_SW_FP32 mode for eltwise tests from tests_deprecated/fp32_non_quantized_tests
- 62542

[GNA] eltwise tests with GNA_SW_FP32

---

tools/pot/openvino/tools/pot/graph/passes.py
tools/pot/openvino/tools/pot/graph/transformer.py

An error occurred while inference ReduceMax operation after a boolean data type node.
- 68966, 66505

[POT]: check precision node when insert reduce op in statistic builder

---

inference-engine/src/transformations/include/ngraph_ops/type_relaxed.hpp
inference-engine/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
ngraph/core/include/openvino/core/descriptor/tensor.hpp
ngraph/core/src/descriptor/tensor.cpp
ngraph/core/src/node.cpp
ngraph/core/src/runtime/host_tensor.cpp

- Deprecated set_* method from `description::Tensor`
- 70361
- 70301

Deprecated set_* methods in desctiption::Tensor

---

inference-engine/src/transformations/src/transformations/common_optimizations/clamp_fusion.cpp
inference-engine/tests/functional/inference_engine/transformations/clamp_fusion.cpp

- Max-Min with const 2-nd inputs is converted to Clamp by ClampFusion transformation while the similar Min-Max pattern isn't converted.
- ClampFusion transformation is updated for this case since it's produced by clip_by_value() function in TensorFlow.
- Transformation tests are added for this case.
70195

Clamp fusion transformation is updated to combine min and max operations to clamp

---

inference-engine/src/low_precision_transformations/include/low_precision/network_helper.hpp
inference-engine/src/low_precision_transformations/include/low_precision/reduce_sum.hpp
inference-engine/src/low_precision_transformations/src/add.cpp
inference-engine/src/low_precision_transformations/src/clamp.cpp
inference-engine/src/low_precision_transformations/src/concat.cpp
inference-engine/src/low_precision_transformations/src/convolution.cpp
inference-engine/src/low_precision_transformations/src/convolution_backprop_data.cpp
inference-engine/src/low_precision_transformations/src/fake_quantize_decomposition.cpp
inference-engine/src/low_precision_transformations/src/mat_mul.cpp
inference-engine/src/low_precision_transformations/src/mvn.cpp
inference-engine/src/low_precision_transformations/src/network_helper.cpp
inference-engine/src/low_precision_transformations/src/normalize_l2.cpp
inference-engine/src/low_precision_transformations/src/split.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/lpt_avoid_shapeof_propagation_test.cpp

- *All main LP Transformations was updated to avoid dequantization propagation to the shapeOf subgraphs*
- *Added functional tests*
- *68634*
- *Validation: 69715*

[LPT][dynamism] Avoided dequantization propagation to the shapeOf subgraphs

---

inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_deconv_node.h
inference-engine/tests/functional/plugin/cpu/single_layer_tests/convolution_backprop_data.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/group_convolution_backprop_data.cpp

- *Fusing with strides more then kernel size was disabled, because oneDNN deconvolution doesn't support it*
- *63468*

[CPU] Deconvolution fusing for 1x1 kernel and 2x2 stride

---

inference-engine/thirdparty/clDNN/src/primitive_inst.cpp

Edge case for huge input mem size.

[GPU] Fix input memory calcuation in allocate_output.

---

inference-engine/src/mkldnn_plugin/mkldnn_graph.cpp
inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/concat_const_inplace.cpp

- *Concat node hasn't supported BF16 precision on input const node. A result additional reorder was used before this fix*
- *51652*

[CPU][BF16] Concat layer properly handle mixed precision input

---

inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp

- Not to select fsv16 for u8 to fp32 conv
- Modified layout optimizer  not to select fsv16 for conv from u8 to fp32
- *ticket-id*

[GPU] Resolve performance regression by selecting ref kernel

---

model-optimizer/mo/main.py

- *Check if namespace argv has the "compress_fp16" attribute before accessing it. Fixes issue added by #7588*
- *None*

Check if argv has compress_fp16 attribute

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_reference_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_reference_node.h

Shape inference is now called each infer request for MKLDNNReference regardless of whether the input shape was changed or not. It is important for operations which output shape depends not only on the input shapes but also on input parameters values (e.g. broadcast has target shape parameter on its second input).
- 70330

[CPU] Reference node forced to perform shape inference for each infer request

---

model-optimizer/extensions/back/ReverseInputChannels.py
model-optimizer/mo/utils/runtime_info.py
model-optimizer/unit_tests/extensions/back/ReverseInputChannels_test.py

In ReverseInputChannels index of dimension to reverse is constant equal to 1 as it was expected that layout of Parameter is always NCHW. But in API 2.0 layout can be NHWC which breaks the transformation.
Solution: 
Check if Parameter node has old_api_map and map channel index to new api.
Ticket: 70164
Code:
Validation:
Documentation:

Fix of ReverseInputChannels for NHWC layout.

---

docs/template_plugin/tests/functional/op_reference/pad.cpp
docs/template_plugin/tests/functional/skip_tests_config.cpp

- *Disabled ReferencePadTestParamsTooLarge in reference tests*
- *Conflict are between PR#8396 and PR#8414*
- *Now exceptions are thrown from SetUp() not from Exec() because some checks were moved to ngraph from CPU plugin*
- *Created ticket 70975 for this case*
- *N/A*

[TESTS] Disable  ReferencePadTestParamsTooLarge in reference tests

---

inference-engine/src/multi_device/multi_device_exec_network.cpp

- borrow device friendly blob if applicable, avoid performance gap in AUTO:GPU case
- *...*
- https://jira.devtools.intel.com/browse/CVS-69728

borrow device memory for AUTO:GPU case to avoid performance gap

---

cmake/developer_package/IEDevScriptsConfig.cmake

- `openvino::conditional_compilation` is not available outside of OpenVINO build tree

Fixed ie_mark_target_as_cc

---

inference-engine/tests/functional/shared_test_classes/src/single_layer/non_max_suppression.cpp

- In the functional tests of `NonMaxsuppression`, the section of `Compare` function for FP32 precision should have a tolerance of `threshold` in stead of zero.
- Looks like this is accidentally changed by #5624 at [this line](https://github.com/openvinotoolkit/openvino/pull/5624/files#diff-5abce52af648507d0f01b0b16c11ded3e045fce945d64c497c622557e1ef8624L78).
- This PR change it back to `threshold`.

NMS: change back threshold for comparison

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_fullyconnected_node.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/mat_mul.cpp

*MKLDNNFullyConnectedNode: fix dimension normalization in case with 2D input and 3D output*
- *52507*

[CPU] FullyConnected: fix dimension normalization

---

docs/template_plugin/tests/functional/subgraph_reference/preprocess.cpp
docs/template_plugin/tests/functional/subgraph_reference/preprocess_legacy.cpp
docs/template_plugin/tests/functional/subgraph_reference/preprocess_opencv.cpp
inference-engine/samples/classification_sample_async/main.cpp
inference-engine/samples/hello_classification/main.cpp
inference-engine/samples/ngraph_function_creation_sample/main.cpp
inference-engine/src/inference_engine/src/ie_network_reader.cpp
inference-engine/tests/functional/plugin/gpu/remote_blob_tests/gpu_remote_tensor_tests.cpp
inference-engine/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
inference-engine/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/preprocess/preprocess_builders.hpp
ngraph/core/include/openvino/core/preprocess/input_info.hpp
ngraph/core/include/openvino/core/preprocess/input_network_info.hpp
ngraph/core/include/openvino/core/preprocess/input_tensor_info.hpp
ngraph/core/include/openvino/core/preprocess/output_info.hpp
ngraph/core/include/openvino/core/preprocess/output_network_info.hpp
ngraph/core/include/openvino/core/preprocess/output_tensor_info.hpp
ngraph/core/include/openvino/core/preprocess/postprocess_steps.hpp
ngraph/core/include/openvino/core/preprocess/pre_post_process.hpp
ngraph/core/include/openvino/core/preprocess/preprocess_steps.hpp
ngraph/core/src/preprocess/pre_post_process.cpp
ngraph/test/preprocess.cpp

- PreProcess API change:
- PrePostProcessor takes 'function' argument in constructor
- PrePostProcessor::build() doesn't take any function anymore
- PrePostProcessor::input() method to get reference to input
- PrePostProcessor::output() method to get reference to output
- InputInfo - add getters of tensor, preprocess, network
- OutputInfo - add getters of tensor, preprocess, network
- Samples:
- ClassificationSampleAsync - use new getters
- Inference engine:
- Use new getters in ie_network_reader.cpp
- TODO
- Consider removal of builder-like API in PrePostProcessor, InputInfo, OutputInfo
- 
- 70404

[OV2.0] Preprocessing API changes

---

inference-engine/src/multi_device/multi_device_plugin.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/behavior/plugin/configuration_tests.cpp

Signed-off-by: Wang, Yang <yang4.wang@intel.com>
- Support PERF_COUNT  and KEY_EXCLUSIVE_ASYNC_REQUESTS within AUTO Plugin. 
- https://jira.devtools.intel.com/browse/CVS-69462

Enable setConfig PERF_COUNT and KEY_EXCLUSIVE_ASYNC_REQUESTS for MULTI/AUTO plugin.

---

ngraph/core/include/openvino/core/function.hpp
ngraph/core/include/openvino/core/node.hpp
ngraph/core/src/descriptor/input.cpp
ngraph/core/src/function.cpp
ngraph/core/src/node.cpp
ngraph/core/src/shared_node_info.hpp
ngraph/test/function.cpp
ngraph/test/util/CMakeLists.txt
ngraph/test/util/test_common.cpp
ngraph/test/util/test_common.hpp

get_ordered_ops is a highly used method across transformations pipeline and common infrastructure. Unfortunately the cost of get_ordered_ops call is not zero and for huge models topological sort takes significant time. But we have an opportunity to optimize this by caching an order and change it we change Function. The number of methods that affect resulting topological order is next ->
**Function methods:**
* ov::Function::set_topological_sort
* ov::Function::add_sinks
* ov::Function::remove_sink 
* ov::Function::add_results
* ov::Function::remove_result
* ov::Function::add_parameters
* ov::Function::remove_parameter
**Node methods:**
* ov::Node::add_control_dependency
* ov::Node::set_argument (based on replace_output)
* ov::Node::set_arguments
*  ov::descriptor::Input::replace_output - …

Optimize Function Topological Sort

---

inference-engine/samples/CMakeLists.txt
inference-engine/samples/benchmark_app/CMakeLists.txt
inference-engine/samples/common/format_reader/CMakeLists.txt

Move OpenCV find_package closely to benchmark_app

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_strided_slice_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_strided_slice_node.h
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/strided_slice.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/strided_slice.cpp

- *Added dynamism support for StridedSlice*
- *Added tests for dynamism*
- *70326*

[CPU] Added dynamism support for StridedSlice

---

ngraph/core/CMakeLists.txt
ngraph/core/builder/CMakeLists.txt
ngraph/core/reference/CMakeLists.txt
ngraph/frontend/frontend_manager/CMakeLists.txt
ngraph/frontend/ir/CMakeLists.txt
ngraph/frontend/onnx/frontend/CMakeLists.txt
ngraph/frontend/paddlepaddle/CMakeLists.txt
ngraph/frontend/tensorflow/CMakeLists.txt
ngraph/test/engines_util/CMakeLists.txt
ngraph/test/onnx_test_util/CMakeLists.txt
ngraph/test/runtime/CMakeLists.txt
ngraph/test/runtime/ie/CMakeLists.txt
ngraph/test/runtime/interpreter/CMakeLists.txt
ngraph/test/util/CMakeLists.txt

- Currently, FEs are not tested on OneCore compliance

Added apiValidator checks for frontends

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_matmul_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_matmul_node.h
inference-engine/tests/functional/plugin/cpu/single_layer_tests/convolution_backprop_data.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/group_convolution_backprop_data.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/mat_mul.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/nonzero.cpp
inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/align_matmul_input_ranks.cpp
inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/conv_maxpool_activ.cpp
inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/reshape_fc.cpp
inference-engine/tests/functional/plugin/cpu/test_utils/cpu_test_utils.cpp
inference-engine/tests/functional/plugin/cpu/test_utils/cpu_test_utils.hpp
inference-engine/tests/functional/plugin/cpu/test_utils/fusing_test_utils.cpp
inference-engine/tests/functional/plugin/cpu/test_utils/fusing_test_utils.hpp
inference-engine/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
inference-engine/tests/ngraph_helpers/ngraph_functions/src/input_layer.cpp

MatMul, NonZero nodes CPU specific single layer (SL) tests are extended with dynamic shapes. The SL tests now use the new common single layer test infrastructure that contains all the latest OpenVINO API changes, especially with regard to support dynamic shapes.
- *ticket-id*

[CPU] Several CPU specific SL tests are extended with dynamic shapes

---

samples/CMakeLists.txt

- Now, CI (which runs samples tests) builds samples by its own and does not use these artifacts

Removed samples installation

---

inference-engine/src/multi_device/multi_device_exec_network.cpp

- when user create more auto requests than the optimal value, fall back to use default memory
- *...*
- *ticket-id*

stick to default memory if userrequest exceed the optimal number

---

inference-engine/src/cldnn_engine/cldnn_transformations_pipeline.cpp
inference-engine/src/mkldnn_plugin/mkldnn_plugin.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/common_optimizations.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/moc_transformations.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
inference-engine/src/transformations/src/transformations/opset_conversions/convert_opset2_to_opset1.cpp
inference-engine/src/transformations/src/transformations/opset_conversions/convert_opset3_to_opset2.cpp
ngraph/core/include/openvino/pass/manager.hpp
ngraph/core/src/pass/manager.cpp

Validation of the Function is a very time consuming process and as it takes significant part of LoadTime we have to minimize its usage inside our transformation pipelines. In this PR MOCTransformations, CommonOptimizations, CPU and GPU common pipelines before LPT were updated and the average number of Validations in this pipelines is ~2-3.
The only disadvantage of this approach is that now we have to care which passes can change model type/shape and in such cases we have to enable Validation manually. But on practice the number of such transformations is really low, so for most cases validation is not required.
_Note: there are still some additional validation that potentially can be removed but their removal requires additional investigation and will be done separately._
Two GPU and CPU …

Reduce number of Function Validations

---

docs/ops/image/I420toRGB_8.md

- Typo fix in I420toRGB specification (example 2). For BGR - spec is fine
- *...*
- N/A

Typo fix in I420toRGB specification example

---

tools/benchmark_tool/openvino/tools/benchmark/utils/inputs_filling.py

- *Allows to use -i image1 -i image2 -i image3. Without this changes only first parameter is processed*

[tools] fix input parameters parsing in python benchmark app

---

inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/transformations/decompose_mvn.cpp
inference-engine/src/gna_plugin/transformations/decompose_mvn.hpp
inference-engine/tests/functional/plugin/gna/pass_tests/decompose_mvn.cpp
inference-engine/tests/unit/gna/ngraph/transformations/gna_decompose_mvn.cpp

- add MVNv6 layer decomposition for GNA
- MVNv1 is translated to MVNv6 by means of existing transformation
- only "inside sqrt eps" setting is supported, even though MVNv1 to MVNv6 transformation enforces "outside" setting (it's ignored and "inside" is used instead)
- only batch = 1 is supported
- only input dimensions 3 and 4 are supported.
- 55394

[GNA] Add MVN decomposition

---

inference-engine/src/transformations/include/transformations/common_optimizations/reshape_sequence_fusion.hpp
inference-engine/src/transformations/include/transformations/common_optimizations/transpose_sinking.hpp
inference-engine/src/transformations/src/transformations/common_optimizations/common_optimizations.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/moc_transformations.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/reshape_sequence_fusion.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/transpose_sinking.cpp
inference-engine/src/transformations/src/transformations/common_optimizations/transpose_to_reshape.cpp
inference-engine/tests/functional/inference_engine/transformations/reshape_sequence_fusion.cpp
inference-engine/tests/functional/inference_engine/transformations/transpose_sinking_test.cpp

* Added new transformation ReshapeSequenceFusion which fuses sequence of Reshapes to single Reshape for simple cases when Reshapes takes Constants without special numbers like 0 or -1.
* Added TransposeConvert transformation which propagates Transpose through Convert. This becomes very useful for cases when PreProcessing was used and original model contained Transpose at the beginning. So now this transposes will be eliminated.
*  Move TransposeToReshape transformation into MOC pipeline as it is shape insensitive transformation.
XXX-71116
XXX-60458

Update Transpose Sinking

---

inference-engine/src/transformations/include/transformations/rt_info/attributes.hpp
inference-engine/src/transformations/src/transformations/rt_info/attributes.cpp
inference-engine/tests/functional/inference_engine/ir_serialization/rt_info_deserialization.cpp
inference-engine/tests/functional/inference_engine/ir_serialization/rt_info_serialization.cpp
ngraph/core/include/openvino/core/preprocess/input_tensor_info.hpp
ngraph/core/src/preprocess/pre_post_process.cpp
ngraph/test/preprocess.cpp

- Support 'set_memory_type(string)' for preprocessing input tensor info
- It defines rt_info "memory_type" for parameter's output tensor
- `<attribute name="memory_type" version="0" value="some_memory_type" />
- Testing: unit tests + serialization/deserialization tests
- 66126

[OV2.0] 'set_memory_type' support for preprocessing input

---

docs/template_plugin/tests/functional/op_reference/pad.cpp
ngraph/core/src/op/pad.cpp
runtime/bindings/python/tests/__init__.py
runtime/bindings/python/tests/test_onnx/test_backend.py
runtime/bindings/python/tests_compatibility/__init__.py
runtime/bindings/python/tests_compatibility/test_onnx/test_backend.py

Previous implementation doesn't support Pad op with NonConst pads_begin and pads_end, that is lead to out of bounds exception (get_pads_begin() and get_pads_end() returned empty CoordinateDiff, so there was a failure when allocate buffer for op with undefined shape)
- 69443

Support NonConst pads_begin and pads_end in Pad op

---

docs/template_plugin/tests/functional/subgraph_reference/preprocess.cpp
docs/template_plugin/tests/functional/subgraph_reference/preprocess_legacy.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/subgraph_tests/preprocess.cpp
inference-engine/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/preprocess/preprocess_builders.hpp
ngraph/core/include/openvino/core/preprocess/color_format.hpp
ngraph/core/src/preprocess/color_utils.cpp
ngraph/core/src/preprocess/color_utils.hpp
ngraph/core/src/preprocess/preprocess_steps_impl.cpp
ngraph/core/src/preprocess/preprocess_steps_impl.hpp

- Preprocessing: convert color RGBX/BGRX -> RGB/BGR implementation
- RGBX->BGR is implemented via RGBX->RGB and reverse channels
- Tests implemented:
- Template reference tests
- Legacy compliance tests
- Common plugin tests (enabled for CPU and GPU)
- 71390

[OV2.0] Preprocessing: convert color RGBX/BGRX -> RGB/BGR implementation

---

docs/ops/sequence/RNNCell_3.md
docs/ops/sequence/RNNSequence_5.md

- add detailed formula on RNNCell spec
- add explanation on RNNSequence attribute direction
- 48463

revise RNN spec

---

inference-engine/src/gna_plugin/backend/gna_limitations.hpp
inference-engine/src/gna_plugin/gna_plugin.cpp
inference-engine/src/gna_plugin/transformations/handle_transposes_around_matmul.cpp
inference-engine/src/gna_plugin/transformations/handle_transposes_around_matmul.hpp
inference-engine/src/gna_plugin/transformations/swap_input_matmul_gna.cpp
inference-engine/src/gna_plugin/transformations/swap_input_matmul_gna.hpp
inference-engine/tests/functional/plugin/gna/pass_tests/convert_matmul_to_fullyconnected.cpp
inference-engine/tests/unit/gna/ngraph/transformations/gna_swap_input_matmul.cpp
inference-engine/tests/unit/gna/ngraph/transformations/handle_transposes_around_matmul.cpp

- Transposed after MatMul should be removed if there is an activation between them
- Swap MatMul inputs transformation should handle a case when there are Transposes around MatMul, these transposes should be removed instead of adding new ones
- Some more small fixes for Transposes handling
- Tests are modified and added according to made changes
56549

[GNA] Fixed handling of transposes around MatMul

---

model-optimizer/extensions/back/ReverseInputChannels.py
model-optimizer/unit_tests/extensions/back/ReverseInputChannels_test.py

Several models fail as axis attribute does not have 'copy' attribute. The root cause is that axis type is changed in pass_rc_through_transpose() method from nd.array to int.
Solution: 
Set correct type in pass_rc_through_transpose() method.
Ticket: 71427
Code:
Validation:
Documentation:

Fixed axis type in ReverseInputChannels.

---

docs/template_plugin/tests/functional/subgraph_reference/preprocess_legacy.cpp
inference-engine/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/preprocess/preprocess_builders.hpp

- Increase image size to avoid test failures on some platforms
- In legacy preprocessing, there is an assert 'length >= nlanes' and 'nlanes' value depends on machine architecture
- Set 160x160 test image to guarantee that image size >= nlanes
- Also increased image size for 'plugin shared tests' to ensure the same (even though tests do not work with legacy preprocessing)
- 71390

[TemplateFuncTests] RGBX->RGB: Increase image size to avoid test failures on some platforms

---

inference-engine/thirdparty/clDNN/CMakeLists.txt
thirdparty/CMakeLists.txt

replaces #8753, related #8757
- do not use custom configure/build/install steps - rely on `ExternalProject_Add`
- use library and headers from install location
- use link directory + library base name to point to library (instead of full library path), this method is not 100% reliable as the library with same name theoretically can replace ours, but the probability of such conflict should be small (can be avoided in future by renaming the library, generating full path to the file, etc.)
- INTERFACE target `onednn_gpu_tgt` brings library and headers - I didn't mark it as IMPORTED because technically it is part of OpenVINO build process, maybe something should be changed here?
Checked:
* Linux with Ninja, Ninja Multi-Config, Makefiles generators in Release and Debug configurations
* Windows …

oneDNN: fixed build with mullti-config generators

---

inference-engine/thirdparty/clDNN/api/cldnn/primitives/convolution.hpp
inference-engine/thirdparty/clDNN/src/graph_optimizer/remove_redundant_reorders.cpp
inference-engine/thirdparty/clDNN/src/graph_optimizer/reorder_inputs.cpp
inference-engine/thirdparty/clDNN/src/include/layout_optimizer.h
inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp

- Minor bugfix in layout optimizer for conv (bfyx->bfyx)
- modify logic of removing reorder for fsv32 (only shallow input)
- *ticket-id*

[GPU] Bugfix 1c redun reorder

---

inference-engine/src/vpu/myriad_plugin/CMakeLists.txt

- *MyriadPlugin is not safe to unload it at runtime. Adding -nodelete for ARM*
- *-65593*

[VPU] Not unload MyriadPlugin at runtime on ARM

---

inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp

- This patch forces cldnn primitives for FP32 path

[GPU] Do not use OneDNN for FP32 pipeline

---

inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp

The LSTMSequenceTest in Azure failed after merging PR #8677. In this PR, this test is temporarily disabled.

[Azure] CPU Tests: failed test disabled

---

inference-engine/src/cldnn_engine/cldnn_graph.cpp
inference-engine/src/cldnn_engine/cldnn_graph.h
inference-engine/src/cldnn_engine/cldnn_transformations_pipeline.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp
inference-engine/thirdparty/clDNN/api/cldnn/graph/network.hpp
inference-engine/thirdparty/clDNN/api/cldnn/graph/program.hpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/resample/resample_kernel_base.cpp
inference-engine/thirdparty/clDNN/src/graph_optimizer/compile_graph.cpp
inference-engine/thirdparty/clDNN/src/network.cpp
inference-engine/thirdparty/clDNN/src/program.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/cache_test.cpp

- Enabled NHWC -> NCHW Interpolate transformation
- Added exception rethrow from compile_graph pass to avoid segfault
- Added suffix with exec precision to impl name in PC and exec graph
- Allow INT8 precision for caffe_bilinear mode
- *71331*
- *71786*

[GPU] Fixed NHWC interp. Added exec precision to impl name in perf counters

---

model-optimizer/extensions/ops/random_uniform.py
tests/layer_tests/tensorflow_tests/test_tf_RandomUniform.py

Root cause analysis: Shape for RandomUniform send as input constant. If it is 4D then it should be permuted.
Ticket: 65858
Code:
Validation:
Documentation:

Dragan: random uniform fix

---

model-optimizer/extensions/front/global_pooling_to_reduce.py
model-optimizer/unit_tests/extensions/front/GlobalPoolingToReduce_test.py

Tensor name is lost for Relu operation in resnet-18 due to use of disconnect() in GlobalPoolingToReduce. disconnect() removes edges with attributes that store tensor names.
Solution: Use set_source() which preserves edge atrributes. 
Ticket: 
Code:
Validation:
Documentation:

Fixed tensor names propagation in GlobalPoolingToReduce.

---

scripts/setupvars/setupvars.sh

they cause a problem on raspbianOS
- https://openvino-ci.intel.com/job/openvino/job/PV_checks/job/pv_check_linux/1035/consoleFull#:~:text=12%3A41%3A43%20%20/localdisk/jenkins/workspace/openvino/PV_checks/pv_check_linux/cvsdk-package-tests/dldt%40tmp/durable-dd1625d4/script.sh%3A%2016%3A%20/opt/intel/openvino_2021.4.684/bin/setupvars.sh%3A%20%5B%5B%3A%20not%20found
- CVS-58300

[setupvars] Removed unnecessary double brackets

---

inference-engine/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp
inference-engine/tests/functional/shared_test_classes/src/single_layer/matrix_nms.cpp
inference-engine/tests/functional/shared_test_classes/src/single_layer/multiclass_nms.cpp
inference-engine/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/utils/ngraph_helpers.hpp
inference-engine/tests/ngraph_helpers/ngraph_functions/src/utils/ngraph_helpers.cpp

- Fixed MatrixNMS and MulticlassNMS functional tests build (broken after #8161)
- After #8571 ROIALign CPU tests are failed for bf16. This PR disables these tests

Fixed master build

---

tests/stress_tests/.automation/memcheck_tests/precommit_configs/desktop_references_config.xml

- These typos prevented correct cache.json parsing and led to many perf regressions

[GPU] Fixed typo in cache.json

---

inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp

- This patch forces b_fs_yx_fsv16 format for OneDNN convolutions in case of FP32 output

[GPU] Use b_fs_yx_fsv16 format for OneDNN convolutins in case of FP32 output

---

inference-engine/src/gna_plugin/gna_graph_patterns.hpp
inference-engine/src/gna_plugin/layers/gna_permute.hpp
inference-engine/src/gna_plugin/optimizer/gna_pass_manager.cpp
inference-engine/tests/functional/plugin/gna/pass_tests/remove_permutations_NHWC_to_NCHW_pass.cpp

- GNA plugin recognizes different patterns with transposes around convolution and removes these transposes
- If transposes are 3d (that is possible for 3d convolution) the recognition doesn't work
- Recognition of 3d transposes has been added and covered by tests
56549
68495

[GNA] Support NHWC convolutions with 3d transposes

---

inference-engine/src/cldnn_engine/ops/gather_nd.cpp
inference-engine/thirdparty/clDNN/api/cldnn/primitives/gather_nd.hpp
inference-engine/thirdparty/clDNN/src/gather_nd.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/fusings_gpu_test.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/gather_nd_gpu_test.cpp

- *Cldnn output memory size at GatherND functional-test is aligned with TensorDesc of output blob*
- *Add param for rank of input data*
- *Update unittests to add rank of input data*
- *Update gpu fusing tests*

[GPU] Update GatherND primitive

---

src/core/src/op/abs.cpp
src/core/src/op/ceiling.cpp
src/core/src/op/floor.cpp
src/core/src/op/log.cpp
src/core/src/op/relu.cpp
src/core/src/op/sign.cpp

Ops inherited from `UnaryElementwiseArithmetic` can't be created with input op type == boolean due https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/op/util/unary_elementwise_arithmetic.cpp#L21, but `evaluate` methods still supports it
- 59321

Remove  evaluate of `boolean` for ops inherited from `UnaryElementwiseArithmetic`

---

inference-engine/thirdparty/clDNN/api/cldnn/graph/network.hpp
inference-engine/thirdparty/clDNN/src/network.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/set_output_memory_gpu_test.cpp

- This PR fixes incorrect memory usage in primitives with several outputs implemented via mutable_data
71076
61880

[GPU] Fix incorrect output result in primitives with two outputs

---

src/core/src/layout.cpp
src/core/tests/preprocess.cpp

- Fix array out-of-bounds error during finding permutation
- This is undefined behavior and unfortunately didn't lead to crash on Linux/Debug. The only way to consistently reproduce it is to use windows-debug builds (or add option -fstack_protector-all to builds)
- 72526

Fix array out-of-bounds error

---

inference-engine/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/convert_color_i420.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/convert_color_nv12.cpp
inference-engine/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/negative_layer_support_test.hpp

- Template for creation of negative single layer tests which expects certain fail on `LoadNetwork()` call
- Negative tests added (using template) for color conversion operations: 
`i420toBGR-8` and `i420toRGB-8`
`NV12toBGR-8` and `NV12toRGB-8`
- *71205*
- *71218*

[GNA] Color conversion operations negative tests

---

src/bindings/python/src/compatibility/ngraph/__init__.py
src/bindings/python/src/compatibility/ngraph/opset8/__init__.py
src/bindings/python/src/compatibility/ngraph/opset8/ops.py
src/bindings/python/src/openvino/runtime/opset8/__init__.py
src/bindings/python/src/openvino/runtime/opset8/ops.py
src/bindings/python/tests/test_ngraph/test_create_op.py
src/bindings/python/tests_compatibility/test_ngraph/test_create_op.py

Add opset8 ops to the PythonAPI:
- 71220, 71207

[Python API] Add opset8 ops: i420toBGR-8, i420toRGB-8, NV12toBGR-8, NV12toRGB-8

---

inference-engine/tests/functional/plugin/cpu/single_layer_tests/deformable_convolution.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/interpolate.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/pad.cpp
inference-engine/tests/functional/plugin/cpu/single_layer_tests/reduce_ops.cpp

- Due to dynamism support on CPU number of functional test cases and as a consequence tests running time significantly increased. This may cause precommit jobs failures due to timeout. The PR desceases number of test cases for "bottleneck" operations by moving them in nightly scope or deleting non-important cases at all.
- Tests running time decrease (measured locally):
-- Interpolate: ~4x
-- Reduce: ~2.5x
-- Pad: ~7x
- How this PR affect cpuFuncTests execution time? 
-- WIP

[CPU][Tests] Decreased number of test cases for several ops

---

src/core/src/preprocess/pre_post_process.cpp
src/core/tests/preprocess.cpp

- Result created after post-processing doesn't have original Runtime Info in it
- Appropriate unit test is added
- 73065

[OV20]Fix preserving runtime info for result after post-processing

---

.ci/azure/linux.yml
.ci/azure/linux_coverity.yml
.ci/azure/linux_lohika.yml
.ci/azure/mac.yml
.ci/azure/windows.yml
.ci/azure/windows_conditional_compilation.yml
cmake/dependencies.cmake
model-optimizer/mo/utils/find_ie_version.py

Move back temp folder with 3rd party components to the CMAKE_SOURCE_DIR so MO will be able to determine where to find libraries when it is used with local build.
CVS-71761

Move back temp frolder to the CMAKE_SOURCE_DIR

---

inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.h

- Two fixes 
1. apply align(2) of output block size only when the feature width is enoughly big
2. set subgroup size as 16 when fp16 && out_feature_size == 8
- 61739

[GPU] Fix bfyx conv degradation for gen9 

---

inference-engine/src/vpu/myriad_plugin/myriad_metrics.cpp

- Since all of the supported devices can use the same cache there is no need to change logic in `DeviceArchitecture`.
- CVS-49309

[VPU] Changes logic for MyriadMetrics::DeviceArchitecture

---

inference-engine/tests/functional/inference_engine/transformations/sr_strided_slice_squeeze.cpp
src/core/src/pass/smart_reshape/strided_slice_squeeze.cpp

- *fix to pass sr_stridedslice_squeeze when begin_masks.size() is no larger than axis that is going to be squeezed..*
- *corresponding unit test case.*
- *CVS-71981*

fix to pass sr_stridedslice_squeeze

---

inference-engine/src/vpu/common/include/vpu/ngraph/transformations/convert_gatherND8.hpp
inference-engine/src/vpu/common/src/ngraph/transformations/convert_gatherND8.cpp
inference-engine/src/vpu/graph_transformer/src/frontend/frontend.cpp
inference-engine/tests/functional/plugin/myriad/shared_tests_instances/single_layer_tests/gather_nd.cpp

In the MyriadX plugin, GatherND-5 will be called instead of GatherND-8, since the non-default batch_dims parameter values ​​are not plugin use cases.
- 66657

[MyriadX] - Add new operation "GatherND-8"

---

src/common/preprocessing/CMakeLists.txt

- Perform all `target_link_libraries` step only iff G-API is enabled
- Previously, `fluid` dependency was missed

Fixed linkage for G-API

---

inference-engine/tests/functional/inference_engine/lp_transformations/reshape_transformation.cpp
inference-engine/tests/functional/inference_engine/lp_transformations/transpose_transformation.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/low_precision_transformations/reshape_transformation.cpp
inference-engine/tests/functional/plugin/cpu/shared_tests_instances/low_precision_transformations/transpose_transformation.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/low_precision_transformations/reshape_transformation.cpp
inference-engine/tests/functional/plugin/gpu/shared_tests_instances/low_precision_transformations/transpose_transformation.cpp
src/common/low_precision_transformations/src/layer_transformation.cpp

- Push dequantize through Transpose->Reshape->Transpose->avgPool pattern
- Disable pull_transpose_through_fq transformation for activations path
- [CPU] 5D & 6D element-wise operations performance degradation
- 51790
- 36833 - merged
- 68856 - merged

[LPT]Enable pushing dequantize operations through nodes with shape size more than 5  

---

src/common/low_precision_transformations/include/low_precision/layer_transformation.hpp
src/common/low_precision_transformations/include/low_precision/rt_info/precisions_attribute.hpp
src/common/low_precision_transformations/src/fake_quantize_decomposition.cpp
src/common/low_precision_transformations/src/layer_transformation.cpp
src/common/low_precision_transformations/src/low_precision.cpp
src/common/low_precision_transformations/src/mat_mul.cpp
src/common/low_precision_transformations/src/multiply_to_group_convolution.cpp
src/common/low_precision_transformations/src/rt_info/precisions_attribute.cpp
src/common/low_precision_transformations/src/weightable_layer_transformation.cpp

LPT has defaultPrecisions global non-const variable
55743

[LPT] Fix not thread safe function setDefaultPrecisions

---

inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/border/border_kernel_ref.cpp
inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/convolution/convolution_kernel_b_fs_zyx_fsv16_imad.cpp
inference-engine/thirdparty/clDNN/src/impls/ocl/border.cpp

- Update tuning logic of convolution_b_fs_zyx_fsv16_imad kernel for Gen12HP
- Add b_fs_yx_fsv32 format support for border primitive
- 71915

[GPU] Update tuning logic of convolution_b_fs_zyx_fsv16_imad kernel

---

inference-engine/thirdparty/clDNN/src/graph_optimizer/remove_redundant_reorders.cpp
inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp
inference-engine/thirdparty/clDNN/src/program_helpers.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/reorder_gpu_test.cpp

+ Remove redundant reorder for meta-only reorder
+ Modify reorder removal logic for conv from fsv32 to fsv16
- *Remove redundant reorder for meta-only reorder*
- *Modify reorder removal logic for conv from fsv32 to fsv16*
- *ticket-id*

[GPU] Modify reorder handling

---

src/bindings/python/src/openvino/runtime/ie_api.py

- solution from https://github.com/openvinotoolkit/openvino/pull/7691 handle case for multiple tensor names, but without respect to providing indexes instead of names
- solution from https://github.com/openvinotoolkit/openvino/pull/9013 handle tensors without names, but incompatible with current API status and not cover case with multiple input names
- My PR is attempt to get desired behaviour for both cases
- *ticket-id*

[PYTHON API]: handle input normalization for tensor without name

---

src/bindings/python/src/pyopenvino/pyopenvino.cpp

Fixes a problem coming from a recent merge of 2 PRs.

Compilation error fix in pyopenvino.cpp

---

tools/mo/setup.py

**Problem:** Instead of storing original requirements with full list, setup.py wiped and rewrote with short list of packages common for all FWs.
**Fix:** copy requirement as is without modification
- CVS-73419

[MO] fix requirements copy in setup.py

---

samples/cpp/common/utils/src/args_helper.cpp

In 2021.4 release input files parser in samples was changed in a not backward-compatible way (see how it was in 2021.3 https://github.com/openvinotoolkit/openvino/blob/c5f7ad383e654dfb4a5ac0805323cf8d43426b3f/inference-engine/samples/common/samples/args_helper.hpp#L74-L87), so support for multiple `-i ` arguments in command line was removed. 
It affected benchmark_app mostly. Thus if we now pass `-i file1 -i file2 -i file3` only `file1` will be read. 
In PR #7788 with modified benchmark we have restored multiple `-i `support and for correct comparison between master and our branch it's needed to fix inputs in master too.

[IE Samples] restored support for multiple -i args

---

inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/convolution/convolution_kernel_base.cpp
inference-engine/thirdparty/clDNN/src/binary_convolution.cpp
inference-engine/thirdparty/clDNN/src/convolution.cpp
inference-engine/thirdparty/clDNN/src/deconvolution.cpp
inference-engine/thirdparty/clDNN/src/graph_optimizer/reorder_inputs.cpp
inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp
inference-engine/thirdparty/clDNN/src/network.cpp
inference-engine/thirdparty/clDNN/src/program.cpp
inference-engine/thirdparty/clDNN/src/program_node.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/convolution_gpu_test.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/fusings_gpu_test.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/memory_test.cpp
src/plugins/intel_gpu/src/plugin/ops/convolution.cpp
src/plugins/intel_gpu/src/plugin/program.cpp

- Added reorders for cases when convolution and deconvolution weights are calculated in runtime and weights aren't in common planar formats
- Added extra checks to determine of convolution / deconvolution consistency
- Added swapping of I/O channels for runtime deconvolution weights
- OneDNN post-ops indexing fix
- Added some restrictions for convolution + sum post-op (not to choose OneDNN convolutions in such cases)
- Fixed wrong unit-tests for group convolutions / deconvolutions
- *65415*

[GPU] Fix for conv/deconv weights calculated in runtime

---

src/bindings/python/tests/test_frontend/test_frontend_onnx.py
src/core/tests/onnx/onnx_import.in.cpp
src/frontends/onnx/frontend/src/core/graph.cpp
src/frontends/onnx/frontend/src/core/graph.hpp
src/frontends/onnx/frontend/src/onnx_framework_node.cpp
src/frontends/onnx/frontend/src/onnx_framework_node.hpp
src/frontends/onnx/frontend/src/utils/onnx_internal.cpp

ONNXFrameworkNode had it own copy of shared_ptr<Graph> so in convert phase,
it can be used to produce real ngraph nodes (by graph->make_ng_nodes(..)).
But Graph also keeps ONNXFrameworkNodes in its cache and in consequence
its own shared_ptr, which is causing a dependency cycle.
This change removes shared_ptr<Graph> from ONNXFrameworkNode class
and moves it to decoded function runtime info, so Graph is in a single
place now and its lifetime ends when decoded function is destroyed.

[ONNX] Fix memleak caused by shared_ptr cyclic dependency

---

inference-engine/src/mkldnn_plugin/nodes/mkldnn_cum_sum_node.cpp
inference-engine/src/mkldnn_plugin/nodes/mkldnn_cum_sum_node.h
src/tests/functional/plugin/cpu/single_layer_tests/cum_sum.cpp

- *In `InitSupportedPrimitiveDescriptors` there is check for precision where bf16 is supported but in `execute` isn't supported (missing in switch case). This PR adds bf16 support for `execute`*
- *CumSum uses template `execute` so I added `ConditionalCompilation` support*
- *Updated CPU tests*
- *71595*

[CPU] Added BF16 support for CumSum as well

---

src/core/src/preprocess/pre_post_process.cpp
src/core/tests/preprocess.cpp

- When user specifies `input/output().model().set_layout("NCHW")` - preprocessing will overwrite existing layout information of parameter/result
- 74065

Overwrite 'model' layout with preprocessing when layout is already set

---

src/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/shared/include/behavior/infer_request/io_blob.hpp
src/tests/ie_test_utils/common_test_utils/data_utils.hpp

- Make use of byteSize for filling blob for precision U4/I4/BIN
- Swap name CanSet[In/Out]BlobWithDifferentLayouts
- Remove CanSet[In/Out]BlobWithDifferentLayouts for precision U4/I4/BIN from skip config
- CVS-68525

[IE TESTS] Fix fill blob with random data for precision U4/I4/BIN

---

inference-engine/thirdparty/clDNN/src/graph_optimizer/add_onednn_optimization_attributes.cpp
inference-engine/thirdparty/clDNN/src/impls/onednn/fully_connected_onednn.cpp
inference-engine/thirdparty/clDNN/tests/test_cases/fusings_gpu_test.cpp

- Move reshaping of fused ops tensors from `fully_connected_onednn::create` method to earlier stage for correct post ops handling

[GPU] Fix fused ops reshaping for OneDNN FC

---

tools/pot/openvino/tools/pot/algorithms/quantization/fake_quantize_configuration.py

- *It is necessary to use `fullname` for correct quantization inside subgraphs in future*
Related to: #8616

[POT] Set fullname instead of name in fq_configuration

---

src/common/legacy/src/transformations/convert_opset1_to_legacy/convert_matmul_to_fc_or_gemm.cpp
src/plugins/intel_gna/frontend/quantization.cpp
src/tests/functional/plugin/gna/scale_factors_tests/perchannel_quant_test.cpp

- Channels multiplier for int8 weights can be 0 in the case if weights dynamic range is quite different in different channels, it causes weights zeroing
- Legacy transformation ConvertMatMulToFC is updated to insert transpose just after constant, not after corresponding FQ (otherwise constant folding doesn't work)
61615

[GNA] Fixed a bug with channel multiplier for int8 weights quantization

---

src/inference/include/ie/ie_core.hpp
src/inference/include/openvino/runtime/core.hpp
src/inference/src/ie_core.cpp
src/tests/functional/plugin/shared/include/behavior/ov_executable_network/exec_network_base.hpp
src/tests/functional/plugin/shared/include/behavior/plugin/core_integration.hpp

Signed-off-by: Wang, Yang <yang4.wang@intel.com>
- Add LoadNetwork API using AUTO as the default device to load executable network.
- Add related test cases.
- https://jira.devtools.intel.com/browse/CVS-57530

Add default device value for ie.LoadNetwork

---

src/core/tests/preprocess.cpp

- Added more preprocessing unit tests for fix of PR #8546. The fix removes 'friendly name' for old 'output' node and assigns it to new output node after post-processing
- Testing: revert changes for the fix. Verify that new tests are failed
- 70602

Leftover: Added unit tests for fix for PR #8546

---

src/frontends/ir/src/ir_deserializer.cpp
src/tests/functional/inference_engine/ir_serialization/deterministicity.cpp

- In order to make runtime more frameworks-friendly, save inputs order same as in original model (i.e. comply with order defined in IR)
- CVS-64962

Save Parameters order during IR deserialization

---

src/tests/functional/inference_engine/serialization/single_layer/slice.cpp

- Enable Slice-8 dynamic shape lower bounds serialization tests
- related to: 54519, 69092

[Slice-8] Enable Slice-8 dynamic shape lower bounds serialization tests

---

inference-engine/thirdparty/clDNN/api/intel_gpu/runtime/engine.hpp
inference-engine/thirdparty/clDNN/runtime/engine.cpp
src/inference/include/ie/gpu/gpu_config.hpp

- Peak memory usage is excluded from the result of memory statistics in order to prevent unintentional misuse

[GPU] Exclude peak memory usage from the result of memory statistics

---

src/common/transformations/include/transformations/rt_info/attributes.hpp
src/common/transformations/include/transformations/rt_info/reverse_input_channels.hpp
src/common/transformations/src/transformations/common_optimizations/ric_fusion.cpp
src/common/transformations/src/transformations/rt_info/attributes.cpp
src/core/CMakeLists.txt
src/core/src/pass/rt_info/reverse_input_channels.cpp
src/core/src/preprocess/preprocess_steps_impl.cpp
src/tests/functional/inference_engine/transformations/ric_fusion_tests.cpp

RIC fusion was updated to fuse Gathers (RIC) for cases when order is unknown. This cases appears when we apply RIC preprocessing for dynamic inputs, so this Gather (RIC) operation are marked with special flag which indicates that this operation is RIC operation and can be fused without any bad consequences.

Update RIC Fusion for known Gathers

---

src/plugins/intel_gna/gna_graph_compiler.cpp

- Fixed a reading error outside the allocated memory range
- CVS-73168

AddressSanitizer: heap-buffer-overflow in PwlApply32

---

tools/pot/compression/__init__.py
tools/pot/openvino/tools/pot/__init__.py
tools/pot/openvino/tools/pot/api/README.md
tools/pot/openvino/tools/pot/api/samples/3d_segmentation/3d_segmentation_sample.py
tools/pot/openvino/tools/pot/api/samples/classification/classification_sample.py
tools/pot/openvino/tools/pot/api/samples/face_detection/face_detection_sample.py
tools/pot/openvino/tools/pot/api/samples/object_detection/data_loader.py
tools/pot/openvino/tools/pot/api/samples/object_detection/metric.py
tools/pot/openvino/tools/pot/api/samples/object_detection/obejct_detection_sample.py
tools/pot/openvino/tools/pot/api/samples/segmentation/segmentation_sample.py
tools/pot/openvino/tools/pot/api/samples/speech/data_loader.py
tools/pot/openvino/tools/pot/api/samples/speech/gna_sample.py

- *Added support for legacy imports*
```python
from compression.api import DataLoader as POTDataLoader
from compression.api import Metric
from compression.engines.ie_engine import IEEngine
from compression.graph import load_model, save_model
from compression.graph.model_utils import compress_model_weights
from compression.pipeline.initializer import create_pipeline
```
- *Enabled import  `DataLoader, Metric, IEEngine, load_model, save_model, compress_model_weights, create_pipeline` without `api` dir*
```python
from openvino.tools.pot import DataLoader, Metric, IEEngine, load_model, save_model, compress_model_weights, create_pipeline
```
- *74012*

Support old import system in POT

---

samples/cpp/speech_sample/main.cpp

- When initializing inputs and outputs element type it's expected that inputs number is equal to outputs number. But it's not always true, a separate index should be used for inputs and outputs
74650

[IE SAMPLE] Fixed inputs and outputs element type initialization

---

src/core/src/pass/smart_reshape/matmul_sr.cpp
src/tests/functional/inference_engine/cnn_network/matmul_sr_tests.cpp

Fix for TransposeMatMul  transformation for cases when Transpose on MatMul inputs has multi-output parent node.

Fix SmartReshape TransposeMatMul pass

---

scripts/CMakeLists.txt

setupvars.bat paths set depends on CMAKE_BUILD_TYPE.
RelWithDebInfo didn't work correctly.

Update setupvars.bat with CMAKE_BUILD_TYPE

---

tools/mo/openvino/tools/mo/front/tf/fifo_replacer.py
tools/mo/unit_tests/mo/front/tf/fifo_replacer_test.py

**Root cause analysis:** Earlier the FIFOQueueDequeue transformation expects defined shape for batch_label placeholder. Due to this the transformation raises exception.
**Solution:** Now we can relax this requirement and convert with a shape specified in FIFOQueueV2 operation shape list attribute in case OOB conversion. For backward compatibility, I left legacy logic when batch_label shape is defined.
**Ticket:** 74143
Code:
Validation:
Documentation:

[MO, OOB] Extend FIFOQueueDequeue replacer to support OOB case

---

src/common/snippets/src/op/subgraph.cpp

- *Support decreasing output shapes in snippets. Was supported: [1,1,64,1] + [1,1,64,512]. Need to support: [1,1,64,512] + [1,1,64,1]*
- *74749*

[Snippets] Support decreasing output shapes

---

src/plugins/intel_gpu/include/intel_gpu/runtime/tensor.hpp
src/plugins/intel_gpu/src/graph/impls/onednn/convolution_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/deconvolution_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/fully_connected_onednn.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/utils.hpp
src/plugins/intel_gpu/src/graph/kernel_selector_helper.cpp
src/plugins/intel_gpu/src/kernel_selector/common/tensor_type.cpp
src/plugins/intel_gpu/src/kernel_selector/common/tensor_type.h
src/plugins/intel_gpu/src/kernel_selector/core/cl_kernels/include/batch_headers/fetch_weights.cl
src/plugins/intel_gpu/src/kernel_selector/core/cl_kernels/reorder_weights.cl
src/plugins/intel_gpu/src/kernel_selector/core/kernel_selector_common.cpp

Because unsupported oneDNN tag issue, one of target network fails on DG2.
Add is_os_yx_isa2_osa8_isv8_osv2 format, which is used in
weight reorder, Fix issue.

[GPU] Enable unet2d enable on DG2

---

tests/stress_tests/.automation/memcheck_tests/nightly_configs/desktop_references_config.xml
tests/stress_tests/.automation/memcheck_tests/nightly_configs/desktop_test_config.xml
tests/stress_tests/.automation/memcheck_tests/nightly_configs/myriad_test_config.xml
tests/stress_tests/.automation/memcheck_tests/weekly_configs/desktop_test_config.xml

Were changed:
```
ssd_mobilenet_v2_coco  - > ssd_mobilenet_v1_coco
se-resnext-101   -> se-resnext-50
se-resnet-101    -> se-resnet-50
se-resnet-152    -> se-resnet-50
resnet-50-caffe2         -> remove as not supported by OMZ
densenet-121-caffe2  -> remove as not supported by OMZ
octave-resnet-50-0.125         -> octave-resnet-26-0.25
octave-se-resnet-50-0.125    ->  octave-resnet-26-0.25 + se-resnet-50
octave-densenet-121-0.125  ->  octave-resnet-26-0.25 + se-resnet-50
octave-resnet-101-0.125       -> octave-resnet-26-0.25
octave-resnet-200-0.125       -> octave-resnet-26-0.25
mobilenet-v1-0.50-160 -> mobilenet-v1-1.0-224
mobilenet-v1-0.50-224 -> mobilenet-v1-1.0-224
mask_rcnn_inception_v2_coco         -> mask_rcnn_inception_resnet_v2_atrous_coco 
mask_rcnn_resnet101_atrous_coco  -> …
```

Update list of OMZ models for stress tests

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/reorder/reorder_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/core/common/kernel_selector_utils.cpp

- Correction of an error related to gws / lws inconsistency inside reorder kernels for _fs_b_yx_fsv32_ format at input and _b_fs_yx_fsv32_ (or double blocked _bsv_fsv_ formats) at the output
- Some changes in _GetTensorFriendlyWorkGroups_ function which can avoid potential issues for cases where X axis isn't the primary spatial axis
- 66180

[GPU] Fix of gws/lws inconsistency for some reorder cases

---

src/plugins/auto/plugin.cpp
src/tests/unit/auto/select_device_test.cpp

Signed-off-by: Hu, Yuan2 <yuan2.hu@intel.com>
- *change VPUX as first priority of INT8 precision*
- *modify test case to match the logic*
- *73605*

[Auto plugin] change VPUX as first priority of INT8 precision

---

src/tests/functional/shared_test_classes/src/subgraph/reduce_eltwise.cpp

- `get_output_size()` usage seems to be incorrect here as it return count of outputs, not output shape.
- 74362

[GPU] Fixed invalid vector element access in reduce test

---

src/core/src/op/divide.cpp
src/core/tests/type_prop/reshape.cpp

Root cause analysis: Tensor shape was set according to shape of the first argument. This tensor was used in operation with both input arguments and result will have shape equal broadcast of 2 input shapes.
Solution: Set correct shape for tensor. Added unit test for such case.
Ticket: 73715

fixed tensor shapes in Divide::evaluate_bound

---

src/bindings/python/tests/__init__.py
src/bindings/python/tests/test_onnx/test_zoo_models.py
src/bindings/python/tests_compatibility/__init__.py
src/bindings/python/tests_compatibility/test_onnx/test_zoo_models.py
src/plugins/intel_cpu/src/mkldnn_graph.cpp
src/plugins/intel_cpu/src/mkldnn_graph.h
src/tests/functional/plugin/cpu/shared_tests_instances/subgraph_tests/simple_if.cpp
src/tests/functional/shared_test_classes/include/shared_test_classes/subgraph/simple_if.hpp
src/tests/functional/shared_test_classes/src/subgraph/simple_if.cpp

- *`TensorIterator` and `If` have bodies that use `Replicate` via `ov::Model`. But if there is op with unused output ports inside body, information about these ports is lost in this line: `op2node[op->output(oi).get_node_shared_ptr()] = {node, outPortIdx++};`. So I aligned behavior `Replicate` via `ov::Model` like via `CNNNetwork`*
- *Added test with the same body in If*
- *N/A*

[CPU] Fixed Replicate via ov::Model

---

src/plugins/intel_gpu/include/intel_gpu/runtime/layout.hpp
src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/impls/ocl/depth_to_space.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/plugin/program.cpp
src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp
src/plugins/intel_gpu/tests/test_cases/resample_gpu_test.cpp

- fp16-int8 mixed precision is implemented
- Allow quantization fusion into previous conv if the it is onednn conv
- Implemented cross-precision and cross-layout configuration for onednn conv
- Select layout based on output of primitives, not input
- Do not enforce fp32 for mixed-precision network
- 65603

[GPU] fp16-int8 mixed precision

---

src/core/src/atomic_guard.hpp

For _compare_exchange_strong_ the compiler most likely will generate the _lock cmpxchg_. 
The Intel reference says: 
_This instruction can be used with a LOCK prefix to allow the instruction to be executed atomically. To simplify the
interface to the processor’s bus, the destination operand receives a write cycle without regard to the result of the
comparison. The destination operand is written back if the comparison fails; otherwise, the source operand is
written into the destination. (The processor never produces a locked read without also producing a locked write.)_
So, to make it a bit faster we can first read the value, and only if the value is false do the CAS.

Atomic guard impromenents

---

tools/mo/openvino/tools/mo/front/YOLO.py

Description:
RegionYOLO operation inserted with transformation enabled by transformation config is inserted in the correct layout, so it shouldn't be reverted by old API map
Ticket: 74941
Code:
Validation:
Documentation:

Fix output layout of tf yolo models converted with transformations config

---

samples/cpp/benchmark_app/main.cpp

- It's needed to set flags for stream used for importing model
- https://github.com/intel-innersource/applications.ai.vpu-accelerators.vpux-plugin/pull/357 - benchmarkApp falls on Windows w/o these changes
CVS-71021

Fix for benchmark_app: set model stream flags

---

src/common/transformations/include/transformations/common_optimizations/mark_precision_sensitive_divides.hpp
src/common/transformations/include/transformations/rt_info/nonconvertible_divide.hpp
src/common/transformations/include/transformations/utils/utils.hpp
src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
src/common/transformations/src/transformations/common_optimizations/mark_precision_sensitive_divides.cpp
src/common/transformations/src/transformations/common_optimizations/mark_precision_sensitive_subgraphs.cpp
src/common/transformations/src/transformations/op_conversions/convert_divide.cpp
src/common/transformations/src/transformations/rt_info/nonconvertible_divide.cpp
src/common/transformations/src/transformations/utils/utils.cpp
src/plugins/intel_cpu/src/mkldnn_plugin.cpp
src/tests/functional/inference_engine/transformations/convert_divide.cpp

- *Added markup transformation to mark fp16 divides in shapeOf subgraphs*
- *Added "nonconvertible_divide" attribute*
- *ConvertDivide disabled for non-convertible divides*
- *57322*

[Transformations] ConvertDivide disabled transformation for divide ops from precision sensitive subgraphs

---

src/plugins/intel_gpu/include/intel_gpu/plugin/infer_request.hpp
src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/plugins/intel_gpu/src/plugin/remote_context.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_engine.cpp
src/plugins/intel_gpu/src/runtime/ocl/ocl_ext.hpp
src/tests/functional/plugin/gpu/behavior/infer_request.cpp
src/tests/functional/plugin/gpu/remote_blob_tests/gpu_remote_tensor_tests.cpp

- changed blob creation logic in infer request to create host blob with custom allocator first, and then wrap it with remote blob (for USM case only)
- *73803*

[GPU] Get rid of PreAllocator usages to allow setShape

---

src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/graph/program_dump_graph.cpp
src/plugins/intel_gpu/src/graph/program_node.cpp

This PR adds new `program::get_output_layout(const program_node& node)` method for accessing private field of `program_node`. That allows do not trigger output layout recalculation and users invalidation in graph dump mode by calling `node.get_output_layout(invalidate_users_if_changed=true)` function, which may affect final graph

[GPU] Fix users invalidation and output layout recalculation in  graph dump mode

---

src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp
src/bindings/python/tests/test_ngraph/test_preprocess.py

- Python bindings: expose InputTensorInfo::set_memory_type
- This method can be used when 'GPU' is a target inference device
- 75713

Python bindings: expose InputTensorInfo::set_memory_type

---

src/core/tests/runtime/interpreter/unit_test.manifest

- Debug Windows build pipeline is broken on master because of "onnx_if_inside_if" failed test. Most likely the issue was introduced in https://github.com/openvinotoolkit/openvino/pull/9524

Temporarily disable onnx_if_inside_if unit test on CPU

---

src/bindings/python/tests_compatibility/__init__.py

Cleanup of obsolete XFAILS in ONNX python tests. Verified both versions (legacy and new) - only one XFAIL marker found.
- 38722

ONNX python tests cleanup (obsolete XFAILs)

---

src/plugins/intel_cpu/src/cache/cache_entry.h
src/plugins/intel_cpu/src/nodes/mkldnn_reorder_node.cpp
src/tests/functional/plugin/cpu/single_layer_tests/convolution.cpp
src/tests/unit/cpu/nodes/mkldnn_reorder_node.cpp

- *Enable Reorder node run time cache.*
- *Unknown*

[CPU_Cache]Enable Reorder node run time cache.

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_buffer_fusing.cpp

Crop uses more eltwise assign kernel which yields better performance than reshape_ref.

[GPU] Don't optimize crop if its user is a reshape that can be optimized

---

src/common/transformations/include/transformations/common_optimizations/skip_gather_before_transpose_and_reshape.hpp
src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
src/common/transformations/src/transformations/common_optimizations/skip_gather_before_transpose_and_reshape.cpp
src/tests/functional/inference_engine/transformations/skip_gather_before_transpose_and_reshape_test.cpp

- *Added transformation that removes Gather from the Gather->Transpose->Reshape sequence in case when input has batch=1 and gather has axis=0 and indices={0}*
- *62214*

[Transformations] SkipGather transformation

---

tools/mo/openvino/tools/mo/utils/ir_engine/compare_graphs.py

Root cause analysis: After changing `rt_info` structure our old IREngine based comparator shows incorrect errors
Solution: Remove incorrect comparison code and skip `rt_info` section because old IREngine used firstly for graph structure check.
Ticket: 75782
Code:
Validation:
Documentation:

[MO] Skip `rt_info` in old graph comparator

---

tools/benchmark_tool/setup.py
tools/openvino_dev/setup.py

- *fix PyPI upload error: Invalid value for classifiers. Error: Classifier 'OSI Approved :: Apache Software License' is not a valid classifier*

remove duplicated classifier from openvino-dev wheel package 

---

tools/mo/openvino/tools/mo/moc_frontend/pipeline.py

Fix of the MO code which sets additional tensor names. In case a placeholder name is not specified in the `mo.py` parameters, the additional tensor setting is not required.
- 75679

MO: Set additional tensor names only if necessary

---

src/plugins/intel_gpu/src/graph/graph_optimizer/pre_replace_deconv.cpp
src/plugins/intel_gpu/src/graph/roi_align.cpp
src/plugins/intel_gpu/src/plugin/infer_request.cpp

- USM shared blob was actually re-allocated due to wrong blob type selected, thus we had redundant data copies

[GPU] Fixed USM shared blob allocation type

---

src/core/include/openvino/core/attribute_visitor.hpp
src/core/src/attribute_visitor.cpp

I've met an error when building OpenCV library with OpenVINO with VS2015 toolset:
```
C:\openvino\runtime\include\openvino/core/attribute_visitor.hpp(122): 
error C2131: expression did not evaluate to a constant (compiling source file C:\opencv\modules\dnn\src\dnn.cpp) [C:\build_release\modules\dnn\opencv_dnn.vcxproj]
C:\openvino\runtime\include\openvino/core/attribute_visitor.hpp(122): 
note: failure was caused by unevaluable pointer value (compiling source file C:\opencv\modules\dnn\src\dnn.cpp)
```
I understand that VS2015 is not supported by OpenVINO, but the change is very small and I hope it should not break anything.

Fixed compilation of user code with VS2015

---

src/core/tests/CMakeLists.txt
src/tests_deprecated/unit/CMakeLists.txt

Gold linker fails to link tests built with sanitizer

Do not force gold linker for sanitizer builds

---

src/core/src/model.cpp
src/core/tests/model.cpp

Update `Model::reshape` to rethrow the currently handled exception like `ov::Exception` with meaningful error message
instead of simple `std::exception` without any info.
-  related to 74952

Update Model::reshape to rethrow currently handled exception

---

tools/mo/openvino/tools/mo/utils/ir_reader/extenders/parameter_extender.py

Root cause analysis: Since we start to generate IRs with undefined dimensions we have 2 symbols to mark such dimensions: `-1` and `?`. But only `-1` was added to `Parameter` extender, and IRs with `?` breaks MO IR Reader.
Solution: Add `?` to `Parameter` extender for correct shape parsing.
Ticket: 75990
Code:
Validation:
Documentation:

Update undefined dimensions parsing in parameter extender

---

src/common/transformations/src/transformations/common_optimizations/pad_fusion.cpp
src/tests/functional/inference_engine/transformations/pad_fusion.cpp

Useful in cases when pad_value is a subgraph marked as decompression
which cannot be constant folded, but still, Pad can be eliminated
if pad_value evaluates to zero.

Allow non constant pad_value in PadFusion's pattern

---

src/plugins/intel_cpu/src/mkldnn_graph_optimizer.cpp
src/tests/functional/plugin/cpu/subgraph_tests/src/fuse_transpose_reorder.cpp

- Fusing of transpose and reorder is disabled for dynamic shapes
- CVS-74863

Fusing of transpose and reorder is disabled for dynamic shapes

---

tools/mo/openvino/tools/mo/middle/AddMeanScaleValues.py
tools/mo/unit_tests/mo/middle/AddMeanScaleValues_test.py

Root cause analysis: AddMeanScaleValues.py were inserting FP64 constants instead of inheriting the type from Parameter.
Solution: Inherit type from Parameter
Ticket: 76077
Code:
Validation:
Documentation:

Fix data type of inserted constants for means and scales

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/pooling/pooling_kernel_gpu_fs_b_yx_fsv32.cpp
src/plugins/intel_gpu/tests/fusions/pooling_fusion_test.cpp

- Fixed incorrect indexes calculation in fusions logic of fs_b_yx_fsv32 pooling kernel
- Added new test case
- Changed per-layer eltwise data from repeating single values to generating random set
- 74848

[GPU] Fix fusions indexes calculation in b_fs_yx_fsv32 pooling kernel

---

inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pxd
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api_impl.cpp
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api_impl.hpp
inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api_impl_defs.pxd
inference-engine/ie_bridges/python/tests/test_IECore.py
src/bindings/python/src/openvino/runtime/ie_api.py
src/bindings/python/src/pyopenvino/core/core.cpp
src/bindings/python/tests/test_inference_engine/test_core.py

Details:
Add Python APIs for loadNetwork and compile_network without device name
Tickets:
https://jira.devtools.intel.com/browse/CVS-75249

[PYTHON] Add python APIs for loadNetwork and compile_network without device name

---

src/bindings/python/src/pyopenvino/core/common.cpp
src/bindings/python/src/pyopenvino/core/common.hpp
src/bindings/python/tests/test_inference_engine/subprocess_test_tensor.py
src/bindings/python/tests/test_inference_engine/test_tensor.py

- Use std::string for static map instead of py::str
- Probable reason is that this static map is destroyed after 'pybind' module is destoryed itself, thus py::str can't be cleaned up properly
- Unfortunately when executing via 'pytest' - crash doesn't happen, looks like this static map is destroyed before python environment in this case. Thus, added test case which executes appropriate test as separate subprocess - with this approach test is failed when fix is not applied
- 76059

[PyBind] Fix crash on destroying dtype_to_ov_type static map

---

inference-engine/thirdparty/movidius/XLink/pc/protocols/pcie_host.c

To prevent leaks, object should be cleaned up
by calling SetupDiDestroyDeviceInfoList()
Refer to https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetclassdevsw#remarks
- CVS-75871
- https://github.com/openvinotoolkit/openvino/issues/9501

Fix memleak caused by SetupDiGetClassDevs() object

---

src/tests/functional/plugin/conformance/test_runner/api_conformance_runner/include/api_conformance_helpers.hpp

- Change lib name VPUXPlugin on: ov_intel_vpux_plugin
- EISW-29106

Change libs name of vpux plugin

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/eltwise/eltwise_kernel_base.cpp
src/plugins/intel_gpu/src/kernel_selector/core/cl_kernels/include/batch_headers/fetch_data.cl
src/plugins/intel_gpu/src/kernel_selector/core/common/jitter.cpp
src/plugins/intel_gpu/tests/test_cases/eltwise_gpu_test.cpp

- Fixed indexes calculation in broadcast mode
- Fixed order of dimensions in default mode
- Added `get index safe` function for `fs_b_yx_fsv32` format
- Added test case
- 74847

[GPU] Fix eltwise's inputs indexes calculation and order of dimensions

---

inference-engine/thirdparty/movidius/XLink/pc/protocols/pcie_host.c

To prevent leaks, object should be cleaned up
by calling SetupDiDestroyDeviceInfoList()
Refer to https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetclassdevsw#remarks
- CVS-75871
- https://github.com/openvinotoolkit/openvino/issues/9501

[2021.4] Fix memleak caused by SetupDiGetClassDevs() object

---

src/bindings/python/tests/mock/ov_mock_py_frontend/mock_py_frontend.hpp
src/bindings/python/tests/test_frontend/test_frontendmanager.py

- This also ensures that actual 'Telemetry' object containing callbacks is still alive even there is no explicit Python objects holding it. So there is no such potential 'crash' when object holding callback on Python side is destroyed
- 72263

[Python Bindings] Frontend test for telemetry extension

---

src/plugins/intel_gpu/src/graph/kernel_runner.cpp
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.hpp

- Previously cl_dump was using same file name for all programs, so that the internal program and body programs are being overwritten. Fixt that issue.
- Removed redundant copy of kernel string in kernel_cahce

[GPU] Make cl_dump to distinguish program

---

src/bindings/python/src/openvino/runtime/ie_api.py
src/bindings/python/tests/test_inference_engine/test_compiled_model.py

- `CompiledModel` class is now callable. User can omit `infer_new_request` by calling object directly:
```python
core = Core()
model = core.read_model(...)
comp_model = core.compile_model(model, ...)
res = comp_model({"data": tensor})
```
- `infer_new_request` function is still valid and provide compatibility with already existing code.
- *76525*

[PYTHON] Callable CompiledModel

---

tools/mo/openvino/tools/mo/ops/Exit.py
tools/mo/unit_tests/mo/ops/exit_test.py

Root cause analysis: TensorIterator output has shape [-1000007, 36], it produces node Exit. During partial shape infer shape from input node  before copiing to output converts to mo_array (np.array before mo_array creation) without correct unmasking.  
Solution: Partial shape infer function was re-written to new API to use get_shape/set_shape to avoid unneeded unmasking/masking of shape.
Ticket: 75732
Code:
Validation:
Documentation:

Exit operation produces shape with -1000007

---

tools/compile_tool/main.cpp

- Set default IO precision for vpux and myriad
- [29258](https://jira.devtools.intel.com/browse/EISW-29258)

[Compile tool] Default IO precision for vpux and myriad

---

.github/workflows/code_style.yml
cmake/developer_package/ncc_naming_style/ncc_naming_style.cmake

- After update of MSFT Azure images, we have failed step for NCC style
- *ticket-id*

Use clang-12 for U20

---

tools/mo/openvino/tools/mo/utils/ir_engine/ir_engine.py

Root cause analysis: Now we have incorrect layout while reading graph by MO IR Reader - we set `graph.graph['layout']` to same value as IR graph has. But it leads to errors in shape inference of layout specific operations.
Solution: Always set `graph.graph['layout'] = 'NCHW'` - the same as MO has on back convertation stage.
Ticket: 75689
Code:
Validation:
Documentation:

[MO IR Reader]Remove incorrect layout changing

---

src/bindings/python/src/openvino/utils.py

- Set PATH to openvino libs, so OpenVINO libs can be found installed in Conda Windows environment when OpenVINO runtime deployed from pip. 
- *Corrected relative path to libs*
- *75038*

Fix for Conda Windows environment

---

tools/pot/openvino/tools/pot/algorithms/quantization/fast_bias_correction/algorithm.py

Before the inference of 1 sample, was used function " get_input_shape_for_bias" and there is also check that the first dim equal 1
- 76810

[POT] Check batch bias shape equal one

---

src/plugins/intel_cpu/src/nodes/mkldnn_tensoriterator_node.cpp

- Fix for memory leak in MKLDNNTensorIteratorNode
- CVS-76087

Fix for memory leak in MKLDNNTensorIteratorNode

---

src/plugins/intel_gpu/include/intel_gpu/plugin/remote_context.hpp
src/tests/functional/plugin/gpu/remote_blob_tests/dx11_remote_ctx_test.cpp

- *force removing all RemoteBlob references from shared RemoteContext surface cache before to make sure all blob objects are correctly cleaned up before context object itself is deleted*
- *74074*

[GPU] Force RemoteBlob cache cleanup before RemoteContext is deleted

---

src/plugins/intel_gpu/src/graph/graph_optimizer/add_required_reorders.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/activation/activation_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/activation/activation_kernel_ref.h
src/plugins/intel_gpu/tests/fusions/convolution_fusion_test.cpp

- *Enable validate after adding reorder: After adding reorder, valid_output_layout is false and this could cause unnecessary output recalculation.*
- *Activation ref kernel doesn't support in case input and output dim size is different, so it should be invalidated for the case.*
- *67962*

[GPU] Enable validate after adding reorder

---

src/plugins/auto_batch/auto_batch.cpp

fixing mem leak by avoiding cyclic ref (when shared_ptr was captured in lambda)

---

src/plugins/intel_gpu/src/graph/include/program_node.h
src/plugins/intel_gpu/src/graph/program.cpp
src/plugins/intel_gpu/src/runtime/kernels_cache.cpp

- Add rethrow_exception for parallel kernels compilation
- Fix `deps` container so that it can store primitive ids with the same names

[GPU] Fix dependencies list in fused primitive descriptor

---

tools/mo/openvino/tools/mo/front/tf/ObjectDetectionAPI.py
tools/mo/unit_tests/mo/front/tf/ObjectDetectionAPI_test.py

**Root cause analysis:** In some TensorFlow object detection 2.4+ models casting node to FP32 is located inside the body graph of the preprocessing block. This casting node must be stayed in the resulting graph along with the preprocessing mean/scale nodes since the preprocessing performs in FP32 data type.
**Solution:** Detect the casting node and leave it in the resulted graph, if the data is processed in FP32 data format
**Ticket:** 65298
Code:
Validation:
Documentation:

[MO] Correct preprocessing block for TensorFlow OD 2.4+ models

---

tools/mo/openvino/tools/mo/utils/cli_parser.py

`mo --help` raises UnicodeEncodeError exception on Ubuntu 18 and Python 3.6.9.
Root cause is single Unicode ellipsis character (U+2026) in this line:
https://github.com/openvinotoolkit/openvino/blob/59fca61dd58ae403eb6793228ab910d8f2eae35a/tools/mo/openvino/tools/mo/utils/cli_parser.py#L336
```
$ mo --help
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  'ascii' codec can't encode character '\u2026' in position 7689: ordinal not in range(128)
[ ERROR ]  Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/main.py", line 445, in …
```

Fix UnicodeEncodeError exception in MO help

---

src/plugins/intel_gna/backend/gna_limitations.hpp
src/plugins/intel_gna/layers/gna_split_layer.hpp
src/plugins/intel_gna/optimizer/gna_pass_manager.cpp
src/tests/functional/plugin/gna/pass_tests/eltwise_split_over_channels_pass.cpp

- fix infinite loop during large eltwise split legacy pass
- add appropriate test.
- 77092.

[GNA] Fix large eltwise split in case split dimension is less than alignment

---

docs/template_plugin/tests/functional/op_reference/non_max_suppression.cpp
docs/template_plugin/tests/functional/skip_tests_config.cpp

- *Add template plugin testcases of i32 to op_reference/non_max_suppression.cpp*
- *Remove skip regex from skip_tests_config.cpp*
- *70324*

Add testcases of index type i32 for NonMaxSuppression

---

src/plugins/intel_gna/backend/gna_limitations.cpp
src/plugins/intel_gna/gna_graph_patterns.hpp
src/plugins/intel_gna/gna_plugin_config.cpp
src/plugins/intel_gna/transformations/handle_transposes_around_matmul.cpp
src/plugins/intel_gna/transformations/handle_transposes_around_matmul.hpp
src/plugins/intel_gna/transformations/swap_input_matmul_gna.cpp
src/tests/functional/plugin/gna/pass_tests/decompose_2d_conv.cpp
src/tests/functional/plugin/gna/pass_tests/insert_transpose_before_matmul.cpp
src/tests/unit/gna/ngraph/transformations/gna_handle_transposes_around_matmul.cpp

- support matmuls with two non-const inputs
- detect concat inputs to matmul as changing batch size and handle appropriately
- fix case when unsupported concat can be reported even without setting config option
- fix unsupported log level message
- fix reshape checking code crash in some cases
- enable 2d convolution decomposition tests in GNA_SW_EXACT mode for cases when stride > kernel size.
- 71531.

[GNA] Extend matmul handling support

---

src/tests/functional/plugin/cpu/single_layer_tests/mat_mul.cpp
src/tests/functional/plugin/cpu/subgraph_tests/src/align_matmul_input_ranks.cpp

- *Enabled brgemm matmul primitives avx512*
- *The PR is copy of PR#[9593](https://github.com/openvinotoolkit/openvino/pull/9593)*
- *Tests are added. Time before: 13s 240ms. Time after: 14s 230ms*
- *[PR](https://github.com/openvinotoolkit/oneDNN/pull/109) in oneDNN*
- *ticket-id*

[CPU] Enabled brgemm matmul primitives avx512

---

src/plugins/intel_vpu/graph_transformer/include/vpu/frontend/frontend.hpp
src/plugins/intel_vpu/graph_transformer/include/vpu/graph_transformer.hpp
src/plugins/intel_vpu/graph_transformer/src/frontend/frontend.cpp
src/plugins/intel_vpu/graph_transformer/src/graph_transformer.cpp
src/plugins/intel_vpu/myriad_plugin/myriad_plugin.cpp
src/tests/functional/plugin/myriad/shared_tests_instances/behavior/ov_infer_request/infer_request_dynamic.cpp
src/tests/functional/plugin/myriad/shared_tests_instances/skip_tests_config.cpp

**Details:**
Currently, calling QueryNetwork from Myriad plugin with dynamic network could result in exception, this PR should fix this by removing nodes that could cause it from consideration.
**Tickets:**
CVS-67972
**Copy of**
PR#[9539](https://github.com/openvinotoolkit/openvino/pull/9539)

[VPU] Added support for dynamic nodes for QueryNetwork - copy

---

tools/mo/openvino/tools/mo/front/tf/loader.py

During implementation of Keras inputs order alignment tf.saved_model.load method was replaced with tf.keras.models.load_model. This led to error, that in some cases tf.keras.models.load_model fails to load model while tf.saved_model.load loads it successfully. In this case MO falls back to tf_v1.saved_model.loader.load which adds 'serving_default_' prefix to input names. This leads to errors in conversion, as MO cannot find specified in command line input names.
Solution: 
In case when tf.keras.models.load_model fails to load model use tf.saved_model.load method.
Ticket: 
Code:
Validation:
Documentation:

Fixed error in TF2/Keras model loading

---

src/common/transformations/include/transformations/utils/utils.hpp
src/common/transformations/src/transformations/common_optimizations/mark_precision_sensitive_divides.cpp
src/common/transformations/src/transformations/common_optimizations/mark_precision_sensitive_subgraphs.cpp
src/common/transformations/src/transformations/common_optimizations/ric_fusion.cpp
src/common/transformations/src/transformations/utils/utils.cpp
src/core/include/openvino/pass/constant_folding.hpp
src/core/src/pass/constant_folding.cpp
src/core/src/rt_info.cpp
src/core/src/validation_util.cpp
src/core/tests/CMakeLists.txt
src/core/tests/constant_folding.cpp
src/core/tests/copy_runtime_info.cpp
src/tests/functional/inference_engine/transformations/compress_float_constants_test.cpp
src/tests/functional/inference_engine/transformations/convert_divide.cpp

This PR is a collection of changes focused on LoadTime improvement.
1. MarkPrecisionSensitiveDivides and MarkPrecisionSensitiveSubgraphs were updated to avoid excess graph traversals (XXX-77126) also additional tests were added. Unfortunately there were some troubles with `PrecisionSensitive` attribute because it was vanished right after function validation due to logic in rt-info propagation into `evaluate_bounds method. So in addition I fixed undefined logic for all `copy_runtime_info` methods, so no they works as expected and covered with tests.
2. ConstantFolding transformation was updated to avoid time consuming `could_propagate` function calls. This changes helps to avoid ReadTime degradations and LoadTime degradations for some models. In addition `disable_constant_folding` was …

Load Time Improvements

---

src/plugins/intel_cpu/src/nodes/mkldnn_fullyconnected_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_fullyconnected_node.h
src/tests/functional/plugin/cpu/subgraph_tests/src/fullyconnected_strided_inputs_outputs.cpp

FullyConnected node with 3D inputs cannot work with strided inputs (for example
inplace descs) because it implicitly reshapes input and output tensors.
- 74807

[CPU] Fix FullyConnected node for strided inputs and outputs

---

docs/IE_DG/Extensibility_DG/VPU_Kernel.md

linker errors for SHAVE_LDSCRIPT, SHAVE_MYRIAD_LD_DIR, and SHAVE_MOVIASM_DIR will be shown before initializing cltools_setenv.sh <device>
- *item1*
- *...*
- *ticket-id*

Initialize cltools_setenv.sh before execute clc binary

---

src/core/tests/engines_util/test_case.hpp
src/core/tests/runtime/ie/unit_test.manifest
src/core/tests/runtime/interpreter/unit_test.manifest

The TestCase class does not store the expected output data and in the result, nothing gets compared after the inference. The missing line has been added and the failing tests have been temporarily skipped.

TestCase class fix

---

src/core/src/op/gru_sequence.cpp
src/core/src/op/lstm_sequence.cpp
src/core/src/op/rnn_sequence.cpp
src/core/tests/type_prop/gru_sequence.cpp
src/core/tests/type_prop/lstm_sequence.cpp
src/core/tests/type_prop/rnn_sequence.cpp

- Fix LSTMSequence/GPUSequence validation behavior consistent with RNNSequence
- Fixed issue with no exception if num_directions=2, but 'm_direction' is not set to BIDIRECTIONAL. Previously there was no error with this (and luckily it failed later in some CPU transformations during compile_network)
- Corrected several tests which use copy-pasted num_directions=2 without m_direction set
- Also for dynamic 'num_directions' - output shape still has 1 or 2 directions, because m_direction is known. Tests for GRU/LSTM were updated for this
- Also several tests worked incorrectly for LSTMv0 - expectation was specific error to be thrown, but no expection was also allowed
- Partially related to 76800 (not a fix, but better error catching via validate_and_infer_types)

LSTMSequence/GPUSequence - fix validate_and_infer_types

---

src/plugins/intel_gna/transformations/insert_reshape_around_matmul.cpp
src/tests/unit/gna/ngraph/transformations/gna_insert_reshape_around_matmul.cpp

- reshape Add's input from 4D/3D to 2D when Add follows MatMul and MatMul needs to be reshaped to 2D
- 76915

[GNA] Fix handling reshapes around matmul with 3D/4D Add layer

---

samples/cpp/benchmark_app/main.cpp

- *If there are several inputs, `get_index()` can give  `0` for every input so we reuse always first preprocessing input. Thus I changed index to the tensor name to avoid conflicts*
- *Fix is after changes from [PR#9703](https://github.com/openvinotoolkit/openvino/pull/9703)*
- *N/A*

[Benchmark] Fixed preprocessing inputs

---

src/plugins/intel_cpu/src/nodes/mkldnn_tensoriterator_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_tensoriterator_node.h
src/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/cpu/single_layer_tests/loop.cpp

- *Fixed last comments in [PR#8879](https://github.com/openvinotoolkit/openvino/pull/8879)*
- *Added `trip_count = 0` and `exec_cond = false` support and removed exception throwing. Now if `TI/Loop` isn't executed output dynamic dims are filled by `0`. This PR doesn't include shape inference for body in these cases because it decreases performance (commit 2f6fce46a1e7e8894111afcd27aca1c3ea4f4818)*
- *Fixed klockworks*
- *Improved `prepareParams` to avoid overheads*
- *74819*

[CPU] Fixed TensorIterator/Loop dynamism leftovers

---

src/frontends/tensorflow/src/op/pack.cpp
src/frontends/tensorflow/src/op/strided_slice.cpp
tools/mo/openvino/tools/mo/front/tf/loader.py
tools/mo/openvino/tools/mo/front/tf/partial_infer/tf.py
tools/mo/openvino/tools/mo/load/tf/loader.py
tools/mo/openvino/tools/mo/middle/CustomSubgraphCall.py
tools/mo/openvino/tools/mo/utils/convert.py
tools/mo/openvino/tools/mo/utils/summarize_graph.py
tools/mo/openvino/tools/mo/utils/tensorboard_util.py
tools/mo/openvino/tools/mo/utils/versions_checker.py

**Root cause analysis:** TensorFlow operation attribute has of int64 type if, it is integer. Dynamic casting for ov::Any throws exception in case casting from int64 to int32 type.
**Solution:** Correct type of StridedSlice and Pack attributes
**Other:** Supress TensorFlow info and warning messages that significantly clutter logs during TensorFlow model conversion by legacy MO.
**Ticket:** 77357
Code:
Validation:
Documentation:

[MO, TF frontend] Correct loaders for StridedSlice and Pack operations

---

src/plugins/intel_myriad/common/src/ngraph/transformations/dynamic_to_static_shape_topk.cpp

Benchmark_application results in an error:
[Step 7/11] Loading the model to the device
[ ERROR ] I64 isn't supported
- 75748
- 75747
- 75029

[VPU] - I64 issue with ONNX models - fix

---

src/common/transformations/src/transformations/op_conversions/convert_broadcast3.cpp
src/tests/functional/inference_engine/transformations/legacy/convert_broadcast3_test.cpp

- *If we perform LogicalOr for "data" input and constant with scalar values equal 1, we always get output filled 1.*
- *76493*

[Transformations] ConvertBroadcast3 for boolean fix

---

tools/mo/automation/package_BOM.txt
tools/mo/openvino/tools/mo/subprocess_main.py
tools/mo/openvino/tools/mo/utils/check_mo_import.py

Fixes #9681
For some reason when subprocess is run with `-c` in PyCharm some extra values are added to command string and they cause problem in Debug mode. Replacing to run a separate file fixed this issue.
- CVS-76194

[MO] fix simplified MO import for PyCharm Debug

---

tools/mo/openvino/tools/mo/front/kaldi/add_reshape_transpose_around_conv_pool.py
tools/mo/openvino/tools/mo/front/kaldi/memory_offset_adjustment.py
tools/mo/unit_tests/mo/front/kaldi/add_reshape_transpose_around_conv_pool_test.py
tools/mo/unit_tests/mo/front/kaldi/memory_offset_adjustment_test.py

Root cause analysis: AddReshapeTransposeConvPool fails on param_node.out_port(0).get_destination() due to several detinations of Parameter. 2 Kaldi transformation add more destinations to Parameter but it can't be run after AddReshapeTransposeConvPool, so added processing of seral outputs for Parameter.
Also AddReshapeTransposeConvPool failed on topological_sort dur to cycle in model (in LSTM cell), so run transformation to remove cycles before AddReshapeTransposeConvPool.
Solution: 1. Process several outputs of Parameter
2. Run transformation to remove cycles before AddReshapeTransposeConvPool
3. Also MemoryOffsetAdjustment can be not done due to cycles inside model, so we assume that MemoryOffset can have t>0 or <0. time_dim now can be >0 or <0 and finding max value was changed too. …

Fix bug in AddReshapeTransposeAroundConvPool for Kaldi LSTM networks

---

src/plugins/intel_gna/gna_plugin_config.cpp

To fix debug build.
according to [C++11: 9.4.2/3]:
- If a non-volatile const static data member is of integral or enumeration type, its declaration in the class definition can specify a brace-or-equal-initializer in which every initializer-clause that is an assignment-expression is a constant expression (5.19). A static data member of literal type can be declared in the class definition with the constexpr specifier; if so, its declaration shall specify a brace-or-equal-initializer in which every initializer-clause that is an assignment-expression is a constant expression. [ Note: In both these cases, the member may appear in constant expressions. —end note ] **The member shall still be defined in a namespace scope if it is odr-used (3.2) in the program and the namespace scope definition …

[GNA] Define static variable

---

src/core/tests/models/onnx/conv_integer_scalar_zp.prototxt
src/core/tests/onnx/onnx_import_quant.in.cpp
src/frontends/onnx/frontend/src/op/conv_integer.cpp

- Scalar zero points are not unsqueezed because it's not required
- *70298*

ONNX ConvInteger - handling of scalar zero points

---

src/bindings/python/src/pyopenvino/graph/ops/constant.cpp

Correct behavior for float16 type when using Constant class.
```python
c = ov.opset8.ops.Constant(ov.Type.f16, ov.Shape([2]), [1.0, 2.0])
c.get_vector()
>>> array([1., 2.], dtype=float16)
```
- *77797*

[PYTHON] Fix vector casting for Constants with float16 type

---

tools/mo/openvino/tools/mo/front/extractor.py
tools/mo/openvino/tools/mo/front/tf/AutomlEfficientDet.py

InputCut sets tensor name incorrectly for input port. It sets `<op name>:<port>`, but should be `<port>:<op name>`. Op name alias should also be added in tensor names for input cut by input port.
AutomlEfficientDet transformation loses tensor names by unnecessary disconnecting of Parameter node.
Solution: 
Set `<port>:<op name>` naming of tensor for input port cut.
Add op name alias for input port cut.
Remove disconnect of Parameter from AutomlEfficientDet.
Ticket: 77357
Code:
Validation:
Documentation:

Fixed tensor names set in InputCut and AutomlEfficientDet transformation.

---

docs/MO_DG/prepare_model/convert_model/Converting_Model.md
tools/mo/openvino/tools/mo/main.py
tools/mo/openvino/tools/mo/utils/cli_parser.py
tools/mo/openvino/tools/mo/utils/guess_framework.py

**Root cause analysis:** Despite of specified `--use_new_frontend` option, MO selects TensorFlow legacy frontend in case unsupported FW format or new frontend absence in a developer environment.
**Solution:** Strictly define what `--use_new_frontend` and `--use_legacy_frontend` options mean. Check consistency of MO command-line and ensure that the selected frontend does not contradict user defined options.
**Ticket:** 77399
Code:
Validation:
Documentation:

Check the selected frontend to correspond use_new/legacy_frontend options

---

src/plugins/intel_gpu/include/intel_gpu/runtime/format.hpp
src/plugins/intel_gpu/src/graph/include/layout_optimizer.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp
src/plugins/intel_gpu/src/runtime/layout.cpp

- Fixed resample's format selection to simple formats when it is close to output layer and all the intermediate layers in between the resample and output layer are not preferring blocked format 
- The idea is that, if there is no users preferring blocked format, reordering to bfyx, which should be done before output layer, is better to be done before resample, otherwise reorder to bfyx should be done for larger (resampled) feature map.
- 59132

[GPU] Adjust preferred format of resample operation

---

docs/template_plugin/tests/functional/shared_tests_instances/behavior/ov_plugin/core_integration.cpp

See https://openvino-ci.intel.com/job/private-ci/job/ie/job/ie-tests-linux-ubuntu20-cpu/55751/testReport/junit/(root)/smoke_OVClassBasicTestP_OVClassBasicTestP/registerNewPluginNoThrows_0/

Fix template plugin tests

---

src/plugins/intel_cpu/src/mkldnn_weights_cache.cpp
src/plugins/intel_cpu/src/mkldnn_weights_cache.hpp

- *Handle the case when one thread attempts to acquire all shared outputs of a const node, but gets blocked by another thread that also tries to lock one of the node outputs (that was already locked by the first thread)*
- *75058*

[CPU] Improve weights sharing sync on multiple outputs

---

src/plugins/auto_batch/auto_batch.cpp
src/plugins/auto_batch/auto_batch.hpp
src/tests/functional/plugin/shared/include/auto_batching/auto_batching_tests.hpp

- *item1*
- *...*
- *ticket-id*

fixed excessive outputs copying (in case when the fallback happened) and updated the test for that

---

src/common/low_precision_transformations/src/fake_quantize.cpp
src/common/transformations/src/transformations/common_optimizations/add_fake_quantize_fusion.cpp
src/common/transformations/src/transformations/common_optimizations/mul_fake_quantize_fusion.cpp
src/tests/functional/inference_engine/lp_transformations/fuse_fake_quantize_transformation.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/add_fake_quantize_fusion.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/mul_fake_quantize_fusion.cpp

This PR fixes cases with non-broadcasted eltwise constants (E.g. data_shape: {X, Y, C}, constant_shape: {C}). The following transformations were fixed:
- *AddFakeQuantizeFusion*
- *MulFakeQuantizeFusion*
- *FakeQuantizeTransformation*
- *CVS-77298*

Transformations: eltwise and FQ fusings fixes

---

tools/mo/openvino/tools/mo/front/extractor.py

If input is cut by operation name without port then 0 input port is used by default. So in this case op name should be added to tensor names. Currently op name is added for output port which is wrong.
Solution: 
Add op name to tensor names list in case if cut is performed by input 0-port instead of output 0-port.
Ticket: 78064
Code:
Validation:
Documentation:

Fixed input cut for case when port is not specified.

---

samples/cpp/benchmark_app/main.cpp

set U8 precision for image-like inputs even in case of random filling (reverting earlier-changed logic)

set U8 precision for image-like inputs even in case of random filling

---

tools/mo/openvino/tools/mo/middle/StridedSliceNormalizer.py

**Root cause analysis**: if there is already Concat for 1st input of StridedSlice during normalization extra inputs are added to this Concat and therefore output shape of Concat data node is changed. During reinferrence there is an assert that check that old and new shapes are equal [openvino/tools/mo/graph/port.py#L101-L102](https://github.com/openvinotoolkit/openvino/blob/master/tools/mo/openvino/tools/mo/graph/port.py#L101-L102), but these shapes should not be equal for cases when Concat is modified by StridedSliceNormalizer.
Picture below - after modifying Concat has 4 inputs but data node still stores out shape `[3]`, need to forcely rewrite it to `[4]`
**Solution**: Mark Concat with `concat['override_output_shape'] = True` so that during reinference unnecessary …

[MO] override_output_shape = True for Concat in StridedSliceNormalizer

---

samples/cpp/benchmark_app/utils.cpp
samples/cpp/benchmark_app/utils.hpp

- *`benchmark_app` shows message: `Number of test configurations is calculated basing on -tensor_shape parameter` in some cases. But `benchmark_app` doesn't have command argument `-tensor_shape`. There is only command argument `-data_shape`. So to avoid disagreements I decided to rename `-tensor_shape` to `-data_shape` in comments and message*:blush:
- *N/A*

[Benchmark] Align comments with command argument 'data_shape'

---

src/core/tests/runtime/ie/unit_test.manifest
src/plugins/intel_cpu/src/nodes/mkldnn_eltwise_node.cpp
src/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp

- *clamp node reduces boundaries in integer case*
- *51676*

[CPU] Clamp reduces float boundaries in the case of integer data

---

src/core/src/validation_util.cpp
src/core/tests/type_prop/gather.cpp
src/tests/functional/inference_engine/transformations/op_conversions/gather_normalize_negative_indices_test.cpp

- *Once partial value was taken from ShapeOf it is being tracked as partial even if then we gathered static pieces out of that partial value. This caused poor shape propagation for truly static sub-graphs which resulted in poor static dimension propagation*
- *72359*
- Current branch: ubuntu20_i7_8700/4205
- Master  branch: ubuntu20_i7_8700/4206
- Comparison: _check_regression/3058 **(no changes in the outcomes)**

Partial Value propagation from partial to static value

---

src/plugins/intel_myriad/third_party/mvnc/src/mvnc_api.c

- The XLinkReadDataWithTimeout() is used with and incorrect value for timeout parameter.
- -77971

[IE][MyriadX] Printf over XLink fails on OpenVINO 2021.4.2 - fix

---

tools/mo/openvino/tools/mo/back/ie_ir_ver_2/emitter.py
tools/mo/openvino/tools/mo/main.py
tools/mo/openvino/tools/mo/moc_frontend/serialize.py

Root cause analysis: IR metadata contains only MO version, while it is equally important to know runtime version and if the IR was created using frontend or legacy MO.
Solution: 
- *Add required data to meta info of IR*
```
<net>
...
<meta_data>
<MO_version value="2022.1.custom_mo/meta_improve_29fd24d7c2636efbfdb68932605a1b1db00802e2"/>
<Runtime_version value="custom_mo/meta_improve_29fd24d7c2636efbfdb68932605a1b1db00802e2"/>
<legacy_path value="False"/>
<cli_parameters>...</cli_parameters>
</meta_data>
</net>
```
Ticket: 77604
Code:
Validation:
Documentation:

Write runtime version and how IR was genarated (legacy path or not)

---

src/common/offline_transformations/include/mask_attribute.hpp
src/common/offline_transformations/src/pruning/propagate_masks.cpp
src/common/offline_transformations/src/pruning/shrink_weights.cpp
src/tests/functional/inference_engine/transformations/offline_transformations/pruning_test.cpp

Valid reshape operation pruning mask propagation support. 
Reshape mask propagator checks input and output dimensions from the beginning till first shape differences or min sizes of in/out shapes and propagate mask only for dimensions which are completely the same from the beginning of the shapes.
Such way to propagate masks through reshape keeps callback connections in valid state
- 67418
TODO:

[Offline Transformations] Reshape Layer Pruning Transformation Support

---

src/common/transformations/src/transformations/common_optimizations/broadcast_elementwise_fusion.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/broadcast_elementwise_fusion_test.cpp

Fix BroadcastElementwiseFusion pass for case when Broadcast has more that one consumer and can't be eliminated.
XXX-76838

Fix BroadcastElementwiseFusion pass

---

src/common/transformations/src/transformations/smart_reshape/proposal_scales_stridedslice.cpp
src/tests/functional/inference_engine/transformations/smart_reshape/sr_proposal_scales.cpp

-  Current Proposal1Scales/Proposal4Scales finds matched to Param->Reshape->Proposal patterns
For FP16 models, there is additional 'Convert' is inserted after 'Parameter'.
It causes transformation is not applied and 'ov::set_batch' or CNNNetwork::set_batch will throw
Proposal1Scales and Proposal4Scales transformations were updated to handle these conditions
- Tests were added to existing ieFuncTests (based on API 1.0) 
- 77382

SmartReshape: support Param->Convert->Reshape->Proposal pattern

---

src/plugins/auto_batch/auto_batch.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp

NB: in the API 1.0 the I32 was automatically used (by the CNNetwork?), so i64 inputs it didn't fail...

adding I64/U64 support to the auto-batching

---

src/common/transformations/include/transformations/common_optimizations/nop_elimination.hpp
src/common/transformations/include/transformations/common_optimizations/reshape_sequence_fusion.hpp
src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/src/transformations/common_optimizations/nop_elimination.cpp
src/common/transformations/src/transformations/common_optimizations/reshape_sequence_fusion.cpp
src/plugins/intel_cpu/src/ngraph_transformations/convert_to_cpu_specific_opset.hpp
src/tests/functional/inference_engine/transformations/common_optimizations/nop_elimination.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/reshape_sequence_fusion.cpp

- *Updated transformation to eliminate interchangeable reshape nodes (`Reshape`, `Squeeze`, `Unsqueeze`).*
- *Example:*
- *CVS-70185*

[Transformations] Added interchangeable reshape elimination

---

src/common/transformations/include/transformations/utils/utils.hpp
src/common/transformations/src/transformations/common_optimizations/add_fake_quantize_fusion.cpp
src/common/transformations/src/transformations/common_optimizations/mul_fake_quantize_fusion.cpp
src/common/transformations/src/transformations/common_optimizations/optimize_strided_slice.cpp
src/common/transformations/src/transformations/utils/utils.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/add_fake_quantize_fusion.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/mul_fake_quantize_fusion.cpp

Fix Mul/Add FakeQuantize fusions to avoid cases when Eltwise constant broadcast another input, so in this case fusion is not allowed as it could lead to shape collisions.
XXX-78516

Fix Add/MulFQFusion transformations

---

src/frontends/tensorflow/src/utils.hpp

The difference between these two calls is which .as<>() method of ov::Any class is actually used.
1. 
// it calls as<>() method with rvalue qualifier ( std::move inside) : as() &&
auto tensor_proto = decoder->get_native_attribute("value").as<::tensorflow::TensorProto>(); 
2. 
// it calls as<>() method with lvalue qualifier : as () &
ov::Any any = decoder->get_native_attribute("value");
auto tensor_proto = any.as<::tensorflow::TensorProto>();
For some reason the 1st variant causes the issue in OVTF integration with TF FE. 
It's not reproducible in TF FE separately.
- *75371*

Fix the issue in values_from_const method in OVTF integration with TF FE

---

tools/mo/openvino/tools/mo/ops/ReduceOps.py

Root cause analysis: We found an issue when trying to create a deepcopy of numpy masked_array which was created from masked constant - the result of numpy.prod operation.
Issue in NumPy repository: https://github.com/numpy/numpy/issues/21022
Solution: Create another masked array and return it as operation result.
Ticket: 77218
Code:
Validation:
Documentation:

[MO] Avoid maskedconstant to array conversion

---

src/core/src/op/interpolate.cpp

Root cause analysis:
There are TF models with the operation `ResizeNearestNeighbor` that has `int64` as the input port 0 element type. But there is no such element type as admissible in `op::v4::Interpolate::validate_and_infer_type()`.
Solution:
Add this type into `op::v4::Interpolate::validate_and_infer_type()`.
- *64906*

Adding int64 and int32 as admissible element types for input port 0 data of Interpolate

---

src/plugins/intel_cpu/src/nodes/mkldnn_interpolate_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_interpolate_node.h

- *If the input of interpolate scales is Constant, we only need to get its value during node init, no need to get it during every inference*
- *cvs-75660*

noise-suppression poconetlike0001 accuracy bug fix

---

tools/mo/openvino/tools/mo/moc_frontend/analysis.py

Null nodes represent optional outputs in ONNX models and should not be processed in the analysis.
- *78654*

MO JSON model analysis - null nodes skip

---

ngraph/core/src/pass/pass.cpp

- Fix of memory leak in PassBase::get_name and leak in jit_avx2_1x1_convolution_with_dw_conv_fwd_t kernel
- CVS-77137

Fix of memory leak in PassBase::get_name and leak in jit_avx2_1x1_convolution_with_dw_conv_fwd_t kernel

---

src/plugins/auto_batch/auto_batch.cpp
src/plugins/intel_gpu/include/intel_gpu/plugin/common_utils.hpp
src/plugins/intel_gpu/src/graph/include/to_string_utils.h
src/plugins/intel_gpu/src/graph/program_node.cpp
src/plugins/intel_gpu/src/plugin/infer_request.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/tests/functional/plugin/gpu/behavior/infer_request.cpp
src/tests/functional/plugin/gpu/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp

- Fixed outputs blobs allocation for U16/I16 data types
- Enabled OVInferRequestCheckTensorPrecision tests for supported precisions
- 75941

[GPU] Fix outputs blobs allocation for U16/I16 data types

---

src/common/snippets/src/op/subgraph.cpp
src/common/snippets/src/pass/insert_load_store.cpp
src/common/snippets/src/pass/vector_to_scalar.cpp

Avoid possible invalid read in vector tile. Relevant if some of the inputs is broadcasted over the last dimension
- *77873*

[Snippets] Convert Load/Store to scalar versions if shape ends with 1

---

src/plugins/intel_cpu/src/memory_desc/cpu_blocked_memory_desc.cpp
src/plugins/intel_cpu/src/mkldnn_graph.cpp

This PR contains some fixes for CpuBlockedMemoryDesc constructor and isReorderAvailable routines induced by the introduction of dynamic shapes.

[CPU] Fixes for CpuBlockedMemoryDesc constructor and reorder availability checks 

---

tools/mo/openvino/tools/mo/utils/versions_checker.py

During checking of telemetry version wrong module name is used which results in "package error" warning.
Solution: 
Add telemetry to module names dictionary.
Ticket: 76840
Code:
Validation:
Documentation:

Added telemetry to modules names list.

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

oneDNN rls-v2.6-pc2 supports double blocked format  batch32.
Remove the batch size limitation in oneDNN check logic.
- *ticket-id* 75903

[GPU] Support deconv double blocked format for b=32

---

src/plugins/intel_cpu/src/mkldnn_node.cpp
src/plugins/intel_cpu/src/mkldnn_node.h
src/plugins/intel_cpu/src/nodes/mkldnn_bin_conv_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_bin_conv_node.h
src/plugins/intel_cpu/src/nodes/mkldnn_conv_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_conv_node.h
src/plugins/intel_cpu/src/nodes/mkldnn_deconv_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_deconv_node.h
src/plugins/intel_cpu/src/nodes/mkldnn_eltwise_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_eltwise_node.h
src/plugins/intel_cpu/src/nodes/mkldnn_fake_quantize_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_fake_quantize_node.h
src/plugins/intel_cpu/src/nodes/mkldnn_fullyconnected_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_interpolate_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_interpolate_node.h
src/plugins/intel_cpu/src/nodes/mkldnn_matmul_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_mvn_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_normalize_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_pooling_node.cpp
src/plugins/intel_cpu/src/nodes/mkldnn_pooling_node.h
src/plugins/intel_cpu/src/nodes/mkldnn_reduce_node.cpp
src/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/cpu/single_layer_tests/convolution.cpp
src/tests/functional/plugin/cpu/single_layer_tests/convolution_backprop_data.cpp
src/tests/functional/plugin/cpu/single_layer_tests/group_convolution_backprop_data.cpp
src/tests/functional/plugin/cpu/test_utils/fusing_test_utils.hpp

- Currently post ops mechanism for depthwise and quantization operations assumes const data pointers are included into generated JIT code. This behavior makes impossible to use executor caching for Convolution and Deconvolution operations. The PR reworks post ops mechanism behavior to switch on runtime data pointers usage.
- Additionally zero points attributes is reworked accrdingly to enable caching for INT8 Convolutions
- oneDNN fork PR: https://github.com/openvinotoolkit/oneDNN/pull/110
- CVS-77102

[CPU] Migrated legacy post ops mechanism on runtime data pointers

---

tools/mo/openvino/tools/mo/utils/ir_reader/layer_to_class.py

**Root cause analysis**: Because of the wrong indentation out port normalization didn't work for `Loop` this cause a lot of problems during shape and type inference while restoring saving IR for POT.
This problem revealed when Loop body contained body where not all ports were connected to the main graph and Loop had port with idx 0 which was disconnected.
Namely, `out_ports_count` remains uninitialized if `op_type in custom_ops`. `Loop` is in `custom_ops` and therefore `out_ports_count` is not initialized for it.
**Solution**: Fixed indentation and node `out_ports_count` is initialized correctly.
Ticket: CVS-77599
Code:
Validation:
* n/a  Unit tests: no new unit-tests were added while existing ones are green
* n/a  Transformation tests
Documentation:
* n/a  Supported frameworks operations …

[MO] fix setting 'out_ports_count' in ir_reader

---

samples/cpp/benchmark_app/README.md
samples/cpp/benchmark_app/benchmark_app.hpp
samples/cpp/benchmark_app/main.cpp

Signed-off-by: xuejun <xuejun.zhai@intel.com>
1. Check if the target device supports ov::hint::performance_mode
2. If step 1 is yes, check if user set hint as throughput or latency in command line
3. If step 2 is yes, set ov::hint::PerformanceMode to THROUGHPUT or LATENCY
4. if step 2 is no, check if user set nstreams or nthreads in command line as legacy
5. if step 4 is no,  set ov::hint::PerformanceMode to THROUGHPUT as default hint and output warn for "default hint value is determined"
6. if step 4 is yes, skip default hint for legacy
https://jira.devtools.intel.com/browse/CVS-69023

Modify for CVS-69023: hint configuration

---

src/plugins/intel_cpu/src/mkldnn_exec_network.cpp
src/plugins/intel_cpu/src/mkldnn_plugin.cpp
src/plugins/intel_cpu/src/mkldnn_plugin.h
src/tests/functional/plugin/cpu/shared_tests_instances/behavior/ov_executable_network/get_metric.cpp

Priority of streams relative to performance hints was not ensured for new API property names
- 78953

[CPU] Fix performance hint property handling

---

src/common/transformations/include/transformations/smart_reshape/broadcast_const_range_replacement.hpp
src/common/transformations/src/transformations/smart_reshape/broadcast_const_range_replacement.cpp
src/common/transformations/src/transformations/smart_reshape/smart_reshape.cpp
src/tests/functional/inference_engine/transformations/smart_reshape/broadcast_const_range_replacement.cpp

Changes already reviewed wihin PR  #10138, separated from offline SmartReshape enablement
----
-  BroadcastConstRangeReplacement transformation needed to enable model reshapeability based on:
https://github.com/openvinotoolkit/openvino/blob/master/tools/mo/openvino/tools/mo/front/broadcast_with_range.py
It replaces Constant range of numbers by Range op as input data to Broadcast op.
-  Registered as a part of SmartReshape transformations.
- 76721

[Transformation] Add BroadcastConstRangeReplacement transformation

---

src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp
src/common/transformations/src/transformations/op_conversions/batch_norm_decomposition.cpp
src/tests/functional/inference_engine/transformations/op_conversions/batch_norm_decompositoin.cpp

BatchNormDecomposition correction to prepare decomposed parts for further fusions:
- *input_sub_mean calculation changed from `input - mean` to `input + mean * -1`*
- *Added calculation of constants from subgraphs (`get_constant_from_source` method)*
- *78122*
- *77064*

[Transformaitons] BatchNormDecomposition fix

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/gemm/gemm_kernel_tiled_opt.cpp
src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/gemm/gemm_kernel_tiled_opt.h

- _tile_n_ size inside _gemm_tiled_opt_ kernel should be >= than simd size, it significantly improves perf for small n sizes and prevents from division by zero in some cases
- *62373*

[GPU] Gemm tiled opt fix for minimal size of tile_n

---

docs/install_guides/installing-openvino-linux.md
docs/install_guides/installing-openvino-macos.md
docs/install_guides/uninstalling-openvino.md

- OpenVINO installer path for macOS
- Default install path on macOS
- Red Hat Enterprise Linux 8.x, 64-bit is not part of IRC installer
- *79264*

Correction for install guides

---

thirdparty/ocl/CMakeLists.txt

- *get rid of D suffix on OpenCL.dll, since it prevents correct system DLL usage in case when our is not supplied in OpenVINO package*
- *n/a*

[GPU] Remove debug suffix from OpenCL.dll on Windows

---

src/frontends/tensorflow/src/op/conv_3d.cpp

- *3D convolution can have either NDHWC or NCDHW data format*
- *None*

Fix Conv3D translator in TF FE

---

src/inference/src/cpp/ie_infer_request.cpp

- Fix coverity finding - move nullptr check before dereferencing
- Even though it is not possible to hit into this situation using existing plugins - there is theoretical possibility that some plugin may return 'nullptr' as it is allowed.
- So this check shall remain in generic part which should not rely on plugin-specific behavior
- Test is not added as it is quite complicated to implement mock plugin which returns 'nullptr' on GetBlob just for such purposes
- 79239

[Coverity] Add nullptr check before dereferencing in InferRequest::GetBlob

---

src/plugins/intel_gpu/src/graph/program_node.cpp

When post-op has pattern like below, binary_mul was ignored previously.
1. binary_add
2. eltwise_linear
3. binary_mul
4. binary_add
It happens when prev_post_op_idx == 2, cur_post_op_idx == 4.
prev_post_op_idx was supposed to proceed to idx 3, but it did not.
- 71916

[GPU] Bugfix for onednn post op optimization

---

src/core/include/ngraph/pass/graph_rewrite.hpp
src/core/include/ngraph/pass/pass.hpp
src/core/include/openvino/pass/graph_rewrite.hpp
src/core/include/openvino/pass/pass.hpp
src/core/src/pass/graph_rewrite.cpp
src/core/tests/models/ir/conv_with_rt_info.xml
src/frontends/ir/src/ir_deserializer.cpp
src/tests/functional/inference_engine/ir_serialization/rt_info_deserialization.cpp

* Remove some useless facilities to ngraph from new openvino headers
* Removed exception for case when reading IR with unknown attribute

Remove deprecated classes from openvino headers

---

src/plugins/intel_cpu/src/nodes/mkldnn_topk_node.cpp

- *item1*
- *...*
- *ticket-id*

Fix the unnecessary calculation of blk_stride for dynamic shape

---

src/plugins/intel_gna/gna_graph_tools.hpp
src/plugins/intel_gna/optimizer/gna_pass_manager.cpp
src/plugins/intel_gna/transformations/decompose_2d_convolution.cpp
src/plugins/intel_gna/transformations/handle_transposes_around_matmul.cpp

- Fixed invalid nullptr check - `graph_data.max_pool` have to be non-null in both cases in `Create1DConv`
- Moved logging in `CNNNetworkReconnectLayer` to prevent nullptr dereference
- Fixed erasing from the `relatedInputs` map, because iterators may be invalidated. `std::erase` in `C++11` returns `Iterator following the last removed element`.
- Fixed check in `bool VerifyConcat(const ngraph::Output<ngraph::Node>& node)` to prevent nullptr dereference
- 78822
- 79233

[GNA] Fix static analyzer issues

---

src/core/include/openvino/core/any.hpp
src/core/include/openvino/core/attribute_adapter.hpp
src/core/src/any.cpp

- *The increase in build time and memory consumption is caused by the multiple instantiation of  as<>() method from the ov::Any class, mostly with enums. For now, we're trying to avoid using the as<>() method, replacing it with the newly added public "addressof" method of the ov::Any class, which allows to operate with a pointer to raw data.*
Tested with https://github.com/openvinotoolkit/openvino/pull/10445
- *78303*
- *78773*
- *79157*

Fix increased build time and memory consumption caused by multiple ov::Any instantiation

---

src/plugins/intel_cpu/src/mkldnn_memory.cpp
src/tests/unit/cpu/nodes/reorder_node_test.cpp

Const & should extend the lifetime of the object.
But we still support old compilers (like for centos7)
which have issues with applying this rule.
Also taking by value is perfectly fine in this case
and generates basically the same assembly.
- 79079

[CPU] [SANITIZER] Avoid possible stack-use-after-scope

---

src/plugins/intel_gpu/src/runtime/kernels_cache.cpp

- If the module size increased, some compiler optimizations are disabled. (limit: 500k llvm instructions)
- Due to the above restriction, some kernels get degradation when it is batched with other large kernels. 
- So reduced the bsize to reduce the chance of such cases. 
- 73245

[GPU] Adjust build batch size to 9 from 10 due to the compiler limitation

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

Default bfyx occurs redundant reorder in fsv-format network.
And remove onednn concat limitation for depdendency input should be
onednn impl.
- *74954*
- *75591*

[GPU] Remove default bfyx quantize in get_preferred_format

---

src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

After enabling deconv b32 onednn, colorization-siggraph f16 b32 has regresison,
Fix it. Add to check sum post ops in case deconv onednn.
- *75903*

[GPU] Fix deconv b32 onednn regression in onednn

---

src/bindings/python/tests/__init__.py
src/bindings/python/tests/test_onnx/test_zoo_models.py
src/bindings/python/tests_compatibility/__init__.py
src/bindings/python/tests_compatibility/test_onnx/test_zoo_models.py
src/common/transformations/src/transformations/common_optimizations/convert_nms_gather_path_to_unsigned.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/convert_nms_gather_path_to_unsigned_test.cpp

`Slice` from opset was missing in the list of operation to skip between `NMS -> Gather` path, therefore onnx models from `faster_rcnn_R_50_FPN` and `mask_rcnn_R_50_FPN` family where failing. Added `Slice` into patter in `convert_nms_gather_path_to_unsigned`.
Ticket: CVS-77668

[nG][IE] fix convert_nms_gather_path_to_unsigned: add Slice into pattern

---

docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_YOLO_From_Tensorflow.md

Description: The instructions for converting YOLO-v3 from DarkNet to TensorFlow only apply to TensorFlow 1.X. Also, if numpy version is 1.20 or higher, the conversion script will throw an error, which is presented in the ticket. Need to add a note about these restrictions.
Ticket: CVS-79042

Add note to YOLO-v3 conversion instructions

---

tools/mo/requirements.txt
tools/mo/requirements_tf.txt
tools/mo/requirements_tf2.txt

**Details:** Due to SNYK hits we decided to upgrade TensorFlow version dependencies for MO.
**Ticket:** 70974

[MO] Upgrade TensorFlow version dependency due to SNYK hits

---

src/bindings/python/src/compatibility/openvino/inference_engine/ie_api.pyx
src/bindings/python/tests_compatibility/test_inference_engine/test_IENetwork.py

Improvement of reshape error message with shape like dynamic in compatibility IE Python API bindings
Previous error: `OverflowError: can't convert negative value to size_t`
- related discussion in 76721

[Python API] Improvement of dynamic reshape error message in compatibility ie

---

tools/mo/openvino/tools/mo/middle/ConvertGroupedStridedSlice.py
tools/mo/unit_tests/mo/middle/ConvertGroupedStridedSlice_test.py

**Root cause analysis**: 
Error happens with model `TF_XLNET_LARGE_SQUAD` in `ConvertGroupedStridedSlice` StridedSlices is replaced with VariadicSplit and after re-inference new shapes are inconsistent with old ones.
This degradation was introduces in #5918. When dynamic shapes were added `out_nodes = unique_by(sorted_out_nodes, strided_slices_equality)` was moved below while continuation condition `if len(out_nodes) <= 1` has remained in the same place => therefore even if `out_nodes` had 2 `StridedSlices` with identical `slices` `ConvertGroupedStridedSlice` interpreted them as different and tried to replace them with `VariadicSplit`.
**Solution**:
Add continuation `if len(out_nodes) <= 1` condition right after sorting by unique slices to prevent trying to group 
Ticket: CVS-77777
Code: …

[MO] fix ConvertGroupedStridedSlice.py for XLNet

---

src/plugins/intel_gpu/src/graph/convolution.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/remove_redundant_reorders.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/tests/test_cases/concatenation_gpu_test.cpp

* Select proper layout for fp16-int8 mixed precision network
* Set proper layout in layout propagation for mixed precision
* Disable onednn implicit concat test for HW that is not using onednn
Previous PR was reverted due to precommit failure: https://github.com/openvinotoolkit/openvino/pull/10467
- 79789
- 74545

[GPU] Mixed precision fix for mask rcnn (#10467)

---

src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
src/plugins/intel_gpu/tests/fusions/fully_connected_fusion_test.cpp

- Temporary removed support of fully connected fusings for fp inputs due to errors in bf_tiled (and potentially in bfyx_ref) fc kernels, the work will be finished after creating of release branch; currently it seems more safely for release stability to stay support of only i8/u8 fusings inside fc kernels as it was before my changes in PR #10035.
- Onednn kernels also have some problems with support of fp fused ops for fully connected layers, needs extra investigations.
- 79558
- 79568
- 79596

[GPU] Fix issues with floating point fusings support for cldnn / onednn fully connected kernels

---

src/plugins/intel_gpu/src/runtime/kernels_cache.cpp

- Re-adjust the batch size to 8 to get more chance of compilation optimization 
-  73245

[GPU] Fixed batch size again to 8 as a workaround of compiler restriction.

---

src/common/low_precision_transformations/src/move_fake_quantize.cpp

- ReverseInputChannels pattern in Concat transformation
- 79074

[LPT] Disable Move Fake Quantize on shuffle channels pattern

---

src/plugins/intel_cpu/src/nodes/eltwise.cpp
src/plugins/intel_cpu/src/nodes/fake_quantize.cpp

- The PR fixes regressions introduced in https://github.com/openvinotoolkit/openvino/pull/9938:
-- Post ops data buffers padding was computed incorrectly which resulted in out-of-bounds read
-- Composability of legacy and binary post ops was broken (required for int8 Deconvolution)
- PR in oneDNN fork: https://github.com/openvinotoolkit/oneDNN/pull/120/
- *CVS-79794*

[CPU] Fixed legacy post ops behavior

---

src/plugins/intel_cpu/src/nodes/reorder.cpp

Note: this does not fix the issue that reorder implementation type is not
set properly when getting primitive from the cache

[CPU] Fix uninitialized reorder implementation type (valgrind, asan)

---

src/common/transformations/include/ngraph_ops/nms_ie_internal.hpp
src/common/transformations/include/ngraph_ops/nms_static_shape_ie.hpp
src/core/src/pass/serialize.cpp
src/frontends/ir/src/ir_deserializer.cpp
src/plugins/intel_cpu/src/ngraph_transformations/move_eltwise_up_data_movement.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/tests/unit/cpu/ngraph_transformations/move_eltwise_up_data_movement_test.cpp

- For type relaxed nodes opset name detected incorrectly at the serialization time.
- "PRelu" renamed to "PReLU" during serialization, resulting in incorrect deserialization.
- Snippets aren't disabled because the cache directory wasn't passed to the CPU plug-in. Snippets serialization isn't currently implemented.
- ngraph::op::internal nodes exported with wrong opset.
- CVS-79088

Fix for broken model cache

---

src/plugins/intel_gpu/src/graph/include/permute_inst.h
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

- If the preferred format of the previous conv of permute is fs_b_yx_fsv32, it is set to b_fs_yx_fsv32 that supports tiled permute
- Add common logic to check rotating of permute and remove duplicate part of code
- 74958, 78858

[GPU] Fix permute performance degradation

---

src/plugins/intel_cpu/src/graph_optimizer.cpp
src/plugins/intel_cpu/src/node.cpp
src/tests/functional/plugin/cpu/single_layer_tests/convolution.cpp
src/tests/functional/plugin/cpu/single_layer_tests/matmul.cpp
src/tests/functional/plugin/cpu/subgraph_tests/src/conv_sum_broadcast.cpp
src/tests/functional/plugin/cpu/test_utils/cpu_test_utils.cpp
src/tests/functional/plugin/cpu/test_utils/cpu_test_utils.hpp
src/tests/functional/plugin/cpu/test_utils/fusing_test_utils.cpp
src/tests/functional/plugin/cpu/test_utils/fusing_test_utils.hpp

- MatMul and FC require different broadcasting shape, so MultiplyAdd and ScaleShiftAndFakeQuantize optimizations are updated
- Refactor post ops generation in tests to be able to access node we fused into
- Also get rid of extra copies in cpu test framework

[CPU] Fix ScaleShift and FQ merge optimization

---

src/plugins/intel_gpu/src/plugin/transformations_pipeline.cpp

Disable unrolling by default for LSTMsequence and TensorIterator having length>=16.
Unrolling of such large primitives takes enormous time and produces too large graphs, that exceed plugin limits.
Now, they will be executed using a loop primitive instead
- *77295*
- *78808*

[GPU] Disable large TI unrolling by default

---

src/common/snippets/src/op/subgraph.cpp
src/common/snippets/src/pass/collapse_subgraph.cpp

- *Check for cyclic dependencies during ternary merge.*
- *Allow outputs with different layouts in canonicalization.*
- *78923*

[Snippets] Check for cyclic dependencies during ternary merge.

---

tools/mo/openvino/tools/mo/middle/passes/infer.py
tools/mo/unit_tests/mo/front/common/partial_infer/eltwise_test.py

Root cause analysis: when reverse infer is not successful error message was unfriendly and didn't show user any hint how to convert model in that case.
Solution: catch if reverse infer was unsuccessfully from the very beginning and inform user to specify input shape directly with the use `--input` /`--input_shape`.
Ticket:  CVS-79979
Code:
Validation:
* n/a  Framework operation tests - no new operations were added
* n/a  Transformation tests - no new operations were added
* n/a  Model Optimizer IR Reader check - changes do not modify IR structure
Documentation:
* n/a  Supported frameworks operations list

[MO] update error message when reverse infer was not successful

---

src/plugins/intel_cpu/src/graph_optimizer.cpp
src/tests/functional/plugin/cpu/subgraph_tests/src/conv_sum_broadcast.cpp

This is an addition to https://github.com/openvinotoolkit/openvino/pull/10235
Functional tests are extended with fusing sum into INT8 convolution, so that pattern with operations between the convolution and sum operations is tested.

[CPU] INT8 tests for convolution sum fusing

---

src/bindings/python/src/pyopenvino/core/compiled_model.cpp
src/bindings/python/src/pyopenvino/core/core.cpp

- Remove get/set_config, get_metric methods from the new Python API as OMZ was migrated to the new Configuration API.
- *ticket-id*

[Python API] Remove get/set_config methods from the PyOV

---

src/plugins/intel_cpu/src/nodes/rnn.cpp
src/tests/functional/plugin/cpu/shared_tests_instances/skip_tests_config.cpp
src/tests/functional/plugin/cpu/single_layer_tests/gru_cell.cpp
src/tests/functional/plugin/cpu/single_layer_tests/gru_sequence.cpp
src/tests/functional/plugin/cpu/single_layer_tests/lstm_cell.cpp
src/tests/functional/plugin/cpu/single_layer_tests/lstm_sequence.cpp
src/tests/functional/plugin/cpu/single_layer_tests/rnn_cell.cpp
src/tests/functional/plugin/cpu/single_layer_tests/rnn_sequence.cpp

- *Enables enforce bf16 tests for RNN node.*
- *Fix for division on zero was merged in scope of the PR9836*
- *74961*

[CPU] RNN node enforce bf16 mode does not work.

---

src/common/snippets/include/snippets/emitter.hpp
src/common/snippets/include/snippets/generator.hpp
src/plugins/intel_cpu/src/emitters/cpu_generator.hpp

Add virtual destructors to Emmiter and TargetMachine, since they are interface classes.

[Sinppets] Add virt destructors to Emitter and TargetMachine

---

src/common/snippets/src/op/subgraph.cpp

- *eliminate invalid read for empty shapes*

[Snippets][CPU] Fix empty shapes handling in canonicalization

---

src/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/builders.hpp
src/tests/ngraph_helpers/ngraph_functions/include/ngraph_functions/utils/data_utils.hpp

- fixed several thousands of warnings from builders.hpp: warning C4244: 'argument': conversion from 'T' to 'ngraph::helpers::nGraphTypesTrait<....
- Generalization for bf16 and f16
- *ticket-id*

Fix warnings from builders.hpp

---

src/plugins/intel_cpu/src/nodes/input.cpp
src/tests/functional/plugin/cpu/subgraph_tests/src/denormal_check.cpp
tests/stress_tests/.automation/memcheck_tests/precommit_configs/desktop_references_config.xml

This PR fixes the floating point subnormal numbers nullifying routine in the CPU plugin input node. The problem was that the rank of the tensor was used instead of the size of the tensor, and only the first few elements of the tensor were checked for a subnormal state. A dedicated test was also introduced.
- 80365

[CPU] Fix for subnormal numbers nullifying routine

---

docs/install_guides/installing-openvino-yocto.md

Point to the new Yocto documentation website.

installing-openvino-yocto: fix documentation links

---

docs/install_guides/installing-openvino-yocto.md

Point to the new Yocto documentation site and request users to checkout hardknott branch for 2021.3 branch.

Yocto documentation updates

---

src/tests/functional/shared_test_classes/src/base/ov_subgraph.cpp
src/tests/ie_test_utils/functional_test_utils/src/skip_tests_config.cpp

Avoid double iteration over skip patterns
Skip test after first pattern match
Main motivation: skip routine takes noticeable part of tests time (around 5-10%)

[IE TESTS] Avoid extra checks for test skipping

---

src/plugins/intel_cpu/src/ngraph_transformations/move_eltwise_up_data_movement.cpp
src/tests/unit/cpu/ngraph_transformations/move_eltwise_up_data_movement_test.cpp

- *MoveEltwiseUpThroughDataMov: friendly name duplication fixed for TypeRelaxed cases*
- *80318*

MoveEltwiseUpThroughDataMov fix

---

samples/cpp/benchmark_app/main.cpp
samples/cpp/benchmark_app/remote_tensors_filling.cpp
samples/cpp/benchmark_app/remote_tensors_filling.hpp

when using auto-batching (e.g. take some simple classification network that is batched to the large batch size, like lenet or age-gender etc) the "--use-device-mem" crashes sporadically.
My impression is that the primary reason is that same (or limited set of the) OCL buffer(s) is set to the inference requests, eventually the may be locked (to [copy the input data to the input of the batched network's request](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/auto_batch/auto_batch.cpp#L539) ) **simultaneously** which leads to a crash due to [failure to lock](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/plugin/remote_context.cpp#L192).
A simple solution is always creating an OCL buffer/OV tensor per request's input.
BTW this gives more …

creating remote ocl buffer/tensor per request, to avoid simulteneous locking of the same ocl buffer when auto-batching is used

---

src/bindings/python/src/pyopenvino/CMakeLists.txt
src/bindings/python/src/pyopenvino/pyopenvino.cpp

Checking compatibility between 'pyopenvino' and 'libopenvino' on 'import phase'
This fix is to prevent undefined behavior when user loads OpenVINO from python, but pyopenvino loads different version of 'libopenvino'
This may happen if user has several releases installed and played around PATH/PYTHONPATH environment variables.
In such case, user may have undefined behavior - application may crash in the middle of the usage or use incorrect release.
Fix checks build versions for pyopenvino and ov::get_openvino_version. If mismatch occurs, exception is thrown.
This logic is disabled if user has built OpenVINO locally, experienced developers probably know what they're doing, so if version has 'custom_'  prefix - this logic is disabled
- Not covered by unit tests, only tested locally with …

Checking compatibility between 'pyopenvino' and 'libopenvino'

---

tools/mo/requirements.txt
tools/mo/requirements_tf.txt

- As it was agreed we should not block the possibility to use TF1.x if user have already set up development environment based on TF1.x. By default latest TF version supported by OpenVINO should be installed.
- Solution is to have range between latest supported TF1.x (1.15.5) and TF2.6
- CVS-80484

Update MO requirements to allow TF1.15 if already installed

---

src/plugins/intel_gpu/include/intel_gpu/plugin/remote_context.hpp
src/plugins/intel_gpu/src/plugin/remote_context.cpp
src/tests/functional/plugin/gpu/remote_blob_tests/cldnn_remote_blob_tests.cpp

This PR fixes data races in RemoteBlob implementation 
- *ticket-id*

[GPU] Fix RemoteBlob lock() and ulock() behaviour in case of multiple threads

---

src/bindings/python/src/pyopenvino/graph/descriptors/tensor.cpp

- method named `set_names` while it should be `add_names`
- *ticket-id*

[Python API] Fix typo in method name

---

src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp
src/bindings/python/src/pyopenvino/graph/types/element_type.cpp
src/bindings/python/tests/test_ngraph/test_preprocess.py
src/core/include/openvino/core/model.hpp

Fix in Preprocessing python bindings - add correct default arguments for:
- PreProcessSteps::convert_element_type
- PostProcessSteps::convert_element_type
- InputTensorInfo::set_color_format
Otherwise, python users must always specify optional params
E.g. without fix, instead of writing `tensor().set_color_format(ColorFormat.RGB)` python users have to write `tensor().set_color_format(ColorFormat.RGB, [])`
Unit tests were also corrected to cover these cases
- 80563

Fix issue with default arguments in preprocessing python bindings

---

src/plugins/intel_cpu/src/plugin.cpp

- *RNN/GRU/LSTM decomposition: dynamic shapes make impossible to check seq_len in CPU callback due to shapeOf subgraphs but the sequence is still supported in CPU and doesn't need to be decomposed (to save a performance). For this reason, decomposition has been disabled for the dynamic case*
- *80363*

[CPU] Disabled sequences decomposition for dynamic case

---

src/plugins/intel_gpu/src/graph/program_node.cpp

- When external id of a loop is fused, the i/o map of a loop should be updated too
- 80559

[GPU] Fixed bug in loop operation

---

cmake/developer_package/api_validator/api_validator.cmake
cmake/developer_package/plugins/plugins.cmake

- Enable apivalidator check for windows build when `BUILD_SHARED_LIBS=OFF`
- Change dependency `_ie_plugins_hpp` to `inference_engine_obj`
1. Build OpenVINO and extra module KMB plugin with the following command on Windows: 
`cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_SHARED_LIBS=OFF -D IE_EXTRA_MODULES=$KMB_PLUGIN_HOME -D ENABLE_INTEL_MYRIAD_COMMON=ON ..`
`cmake --build . --config Release -- -m:16`
- Target `_ie_plugins_hpp` needs to be built manually, otherwise the build would fail. Thus this PR changes this dependency to `inference_engine_obj`
- We get following error from intel gpu plugin, and this error still occurs when we disable apivalidator check and build with the same command `LINK : fatal error LNK1181: cannot open input file 'onednn_gpu.lib' …

Enable apivalidator check when BUILD_SHARED_LIBS=OFF

---

samples/cpp/speech_sample/main.cpp

Details:
- Improved processing outputs for model with more than one output
Tickets:
- 77735

[IE Samples] Improved processing outputs for model with more than one output

---

src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp
src/plugins/intel_gpu/src/graph/layout_optimizer.cpp

local_formats from users/dependencies would be better
even though reorder_cnt.number and best_reorder_cnt.totla_size equal.
- 74954

[GPU] update to check quantize fusing condition in oneDNN

---

tools/mo/openvino/tools/mo/main.py
tools/mo/openvino/tools/mo/utils/cli_parser.py

**Details:** MO should not list IR frontend in a list of available frontends and should not employ it for further IR processing since IR frontend is uncapable to do conversion to the latest IR version.
**Ticket:** 80863
Signed-off-by: Roman Kazantsev <roman.kazantsev@intel.com>

[MO] Remove IR frontend from available frontend list in MO

---

src/plugins/auto/executable_network.cpp

Do not share blobs in multi, this may lead to memory corruption

fix multi infer result corrupt issue

---

src/plugins/intel_cpu/src/edge.cpp

Due to the fact that the memory mngr is not thread safe, but constant layers are shared between threads we may have data race in case multiple edges shares the same constant node.
Master PR: https://github.com/openvinotoolkit/openvino/pull/10744
- 80654
- 80616

[CPU] Use raw pointer to share peer data for constants

---

src/plugins/intel_cpu/src/edge.cpp

To avoid concurrent allocation while resolving inplace conflicts
-------
- 79095

[CPU] Avoid using cache for constant inplace or multi-child edges

---

docs/OV_Runtime_UG/migration_ov_2_0/deployment_migration.md
docs/OV_Runtime_UG/migration_ov_2_0/intro.md

- *item1*
- *...*
- *ticket-id*

Added migration for deployment

---

src/plugins/intel_gpu/src/graph/program.cpp

When partial build is called for dryrun, do constant propagate too.
In normal case, partial build is not doing constant propate for saving build time of internal program.
However, if partial build is called with dryrun, it will fail at transfer_constants due to the generic nodes which does not have impl.

[GPU][DRYRUN] Fix dryrun in partial build

---

docs/OV_Runtime_UG/integrate_with_your_application.md
docs/OV_Runtime_UG/ov_infer_request.md

- Moved link to infer request from dedicated section when we are running inference request
- Added notes when `set_callback` should be used
- Removed duplication of main page's "Run inference" and inference requests details

Updated common IE pipeline infer-request section

---

tools/mo/openvino/tools/mo/ops/activation_ops.py
tools/mo/unit_tests/mo/ops/activation_test.py

Root cause analysis: Swish value infer was incorrect it was taking input from port 1, while port 0 must be taken
Solution: Change port number
Ticket: 80650
Code:
Validation:
Documentation:

[MO] Fix swish value infer

---

src/common/legacy/src/transformations/convert_opset1_to_legacy/convert_matmul_to_fc_or_gemm.cpp
src/plugins/intel_gna/frontend/scale_factor_calc.hpp
src/tests/functional/plugin/gna/scale_factors_tests/matmul_overload_correction.cpp

- MatMul input re-quantization is started if its output scale factor is too large to fit the maximum int32 value
- Condition for FakeQuantize after Constant is fixed in ConvertMatMulToFC transformation
- Tests are added
79347

[GNA] Support of overload correction for MatMul with 2 non-constant layers

---

src/common/transformations/src/transformations/common_optimizations/optimize_strided_slice.cpp
src/inference/dev_api/memory_solver.hpp

- Fix of regression of PR #10278 
- Root cause is that 'popupTogetherWith' shall be executed for boxes. With using logical or "||" - if popped_up is already  'true' - next calls will not execute 'popupTogetherWith'
- Surprisingly, it significantly affects load time of some models, especially POT-ones during quantization
- Same is also observed for optimize_strided_slice transformation, fixed this as well (but it didn't cause load time issues)
- 80808

Fix loading time issues for POT models (with lots of results)

---

src/tests/functional/plugin/conformance/test_runner/conformance_infra/src/read_ir_test/read_ir.cpp

- *The fix was prepared for dims which have `-1` value*
- *The target static Shape is min, max and some between then. In case `-1`: zeros will be replaces by `1`, The upper bound - is max limit for `char`*
- *81328*

[IE TESTS][CONFORMANCE] Fix for IRs with dynamic shapes

---

src/common/low_precision_transformations/src/reshape.cpp

[LPT] Turn back checks in reshape transformation when subtract is absent

---

samples/cpp/hello_reshape_ssd/main.cpp
src/core/include/openvino/core/model.hpp
src/core/include/openvino/core/rtti.hpp
src/core/include/openvino/core/runtime_attribute.hpp
src/core/include/openvino/core/visibility.hpp
src/core/include/openvino/op/if.hpp
src/core/include/openvino/op/op.hpp
src/core/tests/frontend/decoder_transformation_extension.cpp

- Each plugin linked with openvino library contains `type_info_static` symbols due default visibility. In case when one of the libraries is unloaded and app tries to get opset, it leads to segfault. So mark `get_type_info_static()` as hidden to use only one implementation exactly from openvino lib. 
- Issue may be reproduced via tests (e.g. `ov_template_func_tests`) on step https://github.com/openvinotoolkit/openvino/blob/master/src/tests/ie_test_utils/functional_test_utils/src/layer_test_utils/summary.cpp#L40 when `BWDCMP_RTTI_DECLARATION` macroses are removed/not used for some ops from opset (e.g. `AdaptiveAvgPool` from opset8)
- CVS-74690

Mark `get_type_info_static()` op class methods as hidden

---

src/plugins/auto/plugin.cpp

Signed-off-by: Hu, Yuan2 <yuan2.hu@intel.com>
- *when there is only one device, do not check the device if support dynamic shape*
- *81028*

[AUTOPLUGIN] don't check dynamic shape when there is only one device

---

src/plugins/intel_cpu/src/nodes/strided_slice.cpp
src/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/strided_slice.cpp

- *There are cases when default ellipsis mask (has only 0) size is less than input/output rank but isn't equal to zero. So we should to fill mask by zero to full size as begin, end masks and other masks*
- *DLB is successfully passed*
- *80532*

[CPU] Fixed default ellipsis mask in StridedSlice

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/fully_connected/fully_connected_kernel_imad.cpp

- Fixed crash of Android build due to unused variable "tuning_data"
- *81796*

[GPU] Removed unused variable "tuning_data" from the code

---

tools/deployment_manager/configs/darwin.json
tools/deployment_manager/configs/windows.json

- DM configs: Updated path for MacOS. Removed MovidiusDriver for HDDL target
- Master PR https://github.com/openvinotoolkit/openvino/pull/11000

Fix Deployment Manager configs for MacOS and Win-HDDL target

---

tools/deployment_manager/configs/darwin.json
tools/deployment_manager/configs/windows.json

- DM configs: Updated path for MacOS. Removed MovidiusDriver for HDDL target

Fix Deployment Manager configs for MacOS and Win-HDDL target (master)

---

CMakeLists.txt

This behavior is already used by default because ONNX is enabled by default and thirdparty/onnx/onnx/CMakeLists.txt forcing CMAKE_BUILD_TYPE to Release if it is not set
It fixes the following issues:
- When ONNX frontend is disabled - source is built for Debug, which is very unexpected comparing to Release with ONNX frontend enabled
- When ONNX frontend is disabled, even libopenvino.so could not be built due to some generated makefiles issues
It is set to 'Release' (not to 'Debug') to comply with default behavior when ONNX is enabled (it is default option working for most users)
- 80842

[CMAKE] If CMAKE_BUILD_TYPE is not set - set it to 'Release' by default

---

src/plugins/intel_gpu/tests/fusions/loop_fusion_test.cpp

- When external id of a loop is fused, the i/o map should be updated too. Added a unittest to check that occasion.
- This is a following up task of https://github.com/openvinotoolkit/openvino/pull/10726
- 80559

[GPU] Added a new unittest to test the fused external primitive

---

src/plugins/intel_gpu/src/graph/impls/onednn/primitive_onednn_base.h
src/plugins/intel_gpu/src/graph/impls/onednn/utils.cpp
src/plugins/intel_gpu/src/graph/impls/onednn/utils.hpp

Inserting padding into oneDNN primitive has issue with implicit concat behavior.
Deconv onedNN initialized output buffer to 0 including padding area. Padding area should be reserved.
Use oneDNN offset from program_node in/out lower_padding instead of oneDNN memory desc.
- *7616*

[GPU] Fix implicit concat padding offset issue in OneDNN

---

src/common/snippets/src/pass/collapse_subgraph.cpp

- `Subgraph` originalLayersNames property is not correct. PR fixes it.

[snippets] Tokenization fix: fused names

---

src/plugins/intel_gpu/src/kernel_selector/core/actual_kernels/detection_output/detection_output_kernel_ref.cpp
src/plugins/intel_gpu/src/kernel_selector/core/cl_kernels/detection_output_gpu_ref.cl

- This PR adds estimations related to required `private` memory for `decoded_bboxes` array and changes allocation type to `local` if required amount of memory is not available
- 80193

[GPU] Add estimation of required memory for CAFFE_OPT_2 stage of GPU DO

---

src/core/src/preprocess/preprocess_impls.cpp
src/core/tests/preprocess.cpp

Scenario:
- Node "Split" with multiple outputs (e.g. 3). All outputs are connected to "Result"s
- Add post-processing step (e.g. convert element type, can be also implicit)
Issue: after post-processing, 3 new results will be created, each will have "Split" friendly name - inconsistency with IRv10 rules
Fix:
- For nodes with multiple outputs, add '.<idx>' suffix to new output's friendly name
- If no post-processing is applied, return immediately, keeping original results as is
- Split with 3 outputs where 2 outputs have post-processing.
- Split with 3 outputs, post-processing doesn't create any nodes
- 82010

[Preprocessing] Fix issue with output's friendly name after post-processing

---

src/tests/ie_test_utils/common_test_utils/file_utils.hpp

- *item1*
- *...*
- *ticket-id*

Fix saving report in dir with more than one non-existing level

---

cmake/developer_package/add_ie_target.cmake

- *Corrects regular expression for EXCLUDED_SOURCE_PATHS, star indicates 0 or more times repetition of the character in front of it*
- *79629*

Correcting a regular expression for EXCLUDED_SOURCE_PATHS

---

src/common/transformations/src/transformations/common_optimizations/simplify_shape_of_sub_graph.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/simplify_second_input_of_reshape_test.cpp

Fixed SimplifySecondInputOfReshape transformation for case when Concat takes Gather which is not valid for fusion and has more than one index, so valid Gathers were fused incorrectly.
In addition tests for SimplifySecondInputOfReshape were refactored to use TransformationsTestsF fixture.
XXX-82150
XXX-80295

Fix SimplifySecondInputOfReshape Transformation

---

cmake/developer_package/options.cmake
cmake/developer_package/plugins/plugins.cmake
docs/template_plugin/CMakeLists.txt
docs/template_plugin/README.md
docs/template_plugin/src/CMakeLists.txt
src/cmake/openvino.cmake

- Changed approach for plugins registration
- Fix:
```
if (IE_REGISTER_POSSIBLE_PLUGINS AND NOT name IN_LIST IE_REGISTER_POSSIBLE_PLUGINS)
continue()
endif()
```
Removes all registered plugins from plugins.xml if new plugin is registered

Fixed registration of template plugin

---

src/plugins/hetero/executable_network.cpp

- Add constant folding to hetero plugin to avoid network splitting to dynamic parts and submit them to devices that do not support dynamism
- CVS-71762

Add constant folding to hetero to avoid dynamism on GPU

---

docs/MO_DG/prepare_model/convert_model/onnx_specific/Convert_Faster_RCNN.md
docs/MO_DG/prepare_model/convert_model/onnx_specific/Convert_Mask_RCNN.md

- A backslash "\\" is missed right after `mo` in the command example.
- The missing backslash is required to run the command with just copy and paste.

Missing backslashes right after mo

---

src/tests/functional/inference_engine/transformations/common_optimizations/hswish_fusion_test.cpp
src/tests/functional/inference_engine/transformations/common_optimizations/mish_fusion_test.cpp

- *During the experiments with new accuracy check was found that these tests fail on accuracy check step*
- *Because of that changed div_constant to 0.1 (division by 0 is not valid)*
- *changed f64 to f32*
- *https://github.com/openvinotoolkit/openvino/pull/10766*

ieFuncTests minor improvements

---

docs/OV_Runtime_UG/performance_hints.md

Latency and throughput are not "some of the most critical factors that influence the overall performance of an application", they are metrics that measure this performance. Factors that influence performance include number of model parameters. input size, etc. This PR changes that sentence, and updates a few surrounding sentences for clarity. There were three sentences in these paragraphs about how portable and future proof this solution is. I merged them into one sentence. 
In my opinion it would be better if these docs explain what this does, instead of explaining why it is presumably better than what we had before. Explaining the difference with previous releases is more suitable for release notes or the transition guide. That is not a minor change though, so not in scope for this PR.

Update two paragraphs in performance hints docs

---

src/core/include/ngraph/opsets/opset.hpp

If ov based application includes opset.hpp file, clang compiler will report the follow error during build process
In file included from /build/ironhide/tmp/portage/chromeos-base/intel-openvino-9999/work/intel-openvino-9999/src/plugins/vpux-plugin/samples/kmb_classification_sample/main.cpp:20:
In file included from /build/ironhide/tmp/portage/chromeos-base/intel-openvino-9999/work/intel-openvino-9999/src/inference/include/ie/inference_engine.hpp:12:
In file included from /build/ironhide/tmp/portage/chromeos-base/intel-openvino-9999/work/intel-openvino-9999/src/inference/include/ie/ie_core.hpp:19:
In file included from /build/ironhide/tmp/portage/chromeos-base/intel-openvino-9999/work/intel-openvino-9999/src/inference/include/ie/ie_extension.h:17:
In file included from …

[ngraph] Fix -Winfinite-recursion error reported by compiler

---

cmake/dependencies.cmake

- hanged symlink order of libgna
- [CVS-79514](https://jira.devtools.intel.com/browse/CVS-79514)

Сhanged symlink order of libgna

---

tests/utils/path_utils.py

- In case of ubuntu system `get_os_name()` returns "ubuntu", but `get_os_type()` returns "Linux" which is expected by tests

Replace `get_os_name()` with `get_os_type()` in `get_lib_path()`

---

src/plugins/auto/executable_network.cpp
src/plugins/auto/executable_network.hpp

decouple createInferRequest() for single/multi device situation

return device infer request in passthrough mode

---

scripts/install_dependencies/install_NCS_udev_rules.sh
src/plugins/intel_myriad/CMakeLists.txt
src/plugins/intel_myriad/myriad_plugin/CMakeLists.txt

- Install `97-myriad-usbboot.rules` to the same location as `install_NCS_udev_rules.sh` which installs this file
- Because of that, `install_NCS_udev_rules.sh` does not depend on `setupvars.sh` script
- *ticket-id*

Install 97-myriad-usbboot.rules to install_dependencies

---

src/frontends/ir/src/rt_info_deserializer.cpp
src/frontends/ir/src/utils.cpp
src/frontends/ir/src/utils.hpp
src/tests/functional/inference_engine/ir_serialization/rt_info_deserialization.cpp

- Add new function to handle layer and fused names with whitespaces. Trim leading and trailing whitespaces
- Modify tests
- CVS-71762

Fix for str_to_container if string value has whitespaces

---

src/inference/dev_api/cpp_interfaces/interface/ie_iplugin_internal.hpp
src/inference/src/cpp_interfaces/interface/ie_iplugin_internal.cpp
src/plugins/intel_cpu/src/plugin.cpp
src/plugins/intel_gpu/src/plugin/plugin.cpp
src/plugins/intel_myriad/common/src/ngraph/query_network.cpp
src/plugins/intel_myriad/myriad_plugin/myriad_plugin.cpp
src/tests/functional/plugin/cpu/behavior/hetero_cpu_query_network.cpp
src/tests/functional/plugin/gpu/behavior/hetero_gpu_query_network.cpp
src/tests/functional/plugin/shared/include/behavior/plugin/hetero_query_network.hpp

- Fixes in queryNetwork:
- If operation removed after transformation in plugins, mark it as supported
- Check layer name as well as its fused names, because in some networks layer name is not contained in its fused names
- CVS-71762

Fix query network for hetero plugin

---

src/tests/functional/plugin/gpu/remote_blob_tests/cldnn_remote_blob_tests.cpp

- These changes fix clBuffers size calculation in smoke_RemoteBlob/RemoteBlob_Test.smoke_canInferOnUserQueue_*/RemoteBlob_Test tests
- 83014

[GPU] Fix remote blobs tests

---

src/plugins/intel_gpu/src/graph/eltwise.cpp
src/plugins/intel_gpu/src/graph/graph_optimizer/reorder_inputs.cpp

- Prevent layouts invalidation after reorders adding for runtime weights
- Update cacl_output_layout function of eltwise primitive to keep "runtime format" propagation instead of "constant format"

[GPU] Update eltwise calc_output_layout function

---

src/plugins/intel_gna/backend/make_pwl.cpp
src/plugins/intel_gna/frontend/scale_factor_calc.hpp
src/plugins/intel_gna/optimizer/gna_pass_manager.cpp
src/tests/functional/plugin/gna/pass_tests/fq_fusion_with_multiple_weights.cpp
src/tests/functional/plugin/gna/scale_factors_tests/eltwise_act_fq.cpp
src/tests/functional/plugin/gna/scale_factors_tests/matmul_overload_correction.cpp
src/tests/functional/plugin/gna/scale_factors_tests/weighable_layer_without_fq.cpp
src/tests/functional/shared_test_classes/src/subgraph/multiple_input_fq.cpp

- FQ layers are fused with previous layers if they are not required for precision change
- Calculation of PWL for Identity is made taking into account FQ statistics
- Workaround is added for activation-activation patterns quantization until the final solution is not implemented in POT
- Fixed Identity insertion before Eltwise which inputs are connected with the same layer
- Fixed Identity insertion after layer with output connected to multiple layers
- Added exception for the case when split alignment with ConvolutionFilter isn't supported
- Some tests are fixed to allow their passing with the required accuracy
58806

[GNA] Remove extra FQ layers from the final network

---

docs/template_plugin/tests/functional/op_reference/strided_slice.cpp
src/core/reference/src/runtime/reference/strided_slice.cpp

If reference::strided_slice execute with empty (zero dims) input/output tensor we get sefgaul. According to [this comment](https://github.com/openvinotoolkit/openvino/blob/master/src/common/transformations/src/transformations/common_optimizations/moc_transformations.cpp#L89) reference implementations don't work with empty tensors.
For model from ticket problem doesn't reproduce for static model because `RemoveConcatZeroDimInput` remove `StridedSlice` from model. But in dynamic case we still have `StridedSlice` with non constant `begin_mask` and `end_mask`. This case is unsupported by CPU plug-in and we fallback on ngraph reference implementation.
- *80923*

Don't execute reference::strided_slice if input/output tensor is empty

---

src/plugins/intel_gpu/include/intel_gpu/primitives/one_hot.hpp
src/plugins/intel_gpu/src/graph/impls/ocl/one_hot.cpp
src/plugins/intel_gpu/src/plugin/ops/one_hot.cpp
src/plugins/intel_gpu/tests/test_cases/one_hot_gpu_test.cpp

- Align one_hot_axis and depth parameters of one_hot primitive to reuse ngraph shape inference further

[GPU] Align OneHot primitive parameters with ngraph
